### ISSUE TITLE
What is the consensus algorithm used

### ISSUE THREAD

**Issue by MTAndroidDev** [tronprotocol/java-tron#1]

**Comment by conglinduye** [comment]
TRON's consensus algorithm refers to the Raft-based consensus algorithm and Tendermint's consensus algorithm.
Raft：Each node in a Raft cluster can switch between three states based on how the cluster is running: follower, candidate, and leader. The leader synchronizes the log to the follower, and the follower only gets the log from the leader.
Tendermint is a BFT consensus protocol that is easy to understand and mostly asynchronous.

**Comment by OktayGardener** [comment]
Dios fucking mio. Raft.

**Comment by marcolopes** [comment]
@OktayGardener , you don't like it?

**Comment by Eyesonly88** [comment]
> Each node in a Raft cluster can switch between three states based on how the cluster is running: follower, candidate, and leader

@conglinduye What does the candidate do in this case? Who's proposing what to vote on? how long are those logs stored for and where are they stored? or are they just streamed through Kafka?

**Comment by JusticeForMikeBrown** [comment]
How can Tron use BFT and Raft?  I am not an expert on this topic though [as explained here](https://eng.paxos.com/why-arent-distributed-systems-engineers-working-on-blockchain-technology) it seems Raft would not work for blockchain.

**Comment by shunyauads** [comment]
Yes, please elaborate, there are mentions that raft is not a viable solution for blockchain on the web.
https://ethereum.stackexchange.com/questions/23071/bitcoin-ethereum-raft-paxo
https://www.quora.com/Why-is-a-blockchain-implementation-different-than-a-distributed-consensus-system-like-raft

**Comment by shunyau** [comment]
Yes, please elaborate, there are mentions that raft is not a viable solution for a public blockchain on the web. It would require all nodes to be trustworthy for it to work. 

https://ethereum.stackexchange.com/questions/23071/bitcoin-ethereum-raft-paxo
https://www.quora.com/Why-is-a-blockchain-implementation-different-than-a-distributed-consensus-system-like-raft

**Comment by JusticeForMikeBrown** [comment]
@shunyau

[Does this help](https://github.com/tronprotocol/wiki/blob/master/Home.md)?

**Comment by zscole** [comment]
Is there an actual technical whitepaper because I'm having trouble understanding the value Tron proposes.

**Comment by Rovak** [comment]
More information can be found on the website https://tron.network/entechnical.html. If you have anymore questions then you can reopen this issue
