### ISSUE TITLE
An error message "We get a unlinked block" was reported

### ISSUE THREAD

**Issue by wangzichichi** [tronprotocol/java-tron#1002]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Query the server log

2. What did you expect to see?
No error message

3. What did you see instead?
Beta fullnode :47.93.184.2:50051, on July 13, an error message was reported.

11:37:36.238 ERROR [nioEventLoopGroup-3-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:801) We get a unlinked block Num:4,ID:0000000000000004d33d9d512e1e158f27ae52ff20707b788292cebaa82898aa, from 123.56.10.6, head is Num:1,ID:00000000000000016a6c085158f14383024f994705f66299ce9b5474ab7d743b

**Comment by Shrey33** [comment]
How to reproduce it ?

**Comment by Shrey33** [comment]
@wangzichichi can you provide me the log file ?
