### ISSUE TITLE
Testnet/Mainnet version (suggestion)

### ISSUE THREAD

**Issue by iiimoon** [tronprotocol/java-tron#1007]
Tron team, Is there any way to publish the current version of Testnet/Mainnet on tronscan.org. I think the best place to display version information under Tool->System menu. It would be a great help to the community to make sure they are building the compatible solutions.  maybe an API to get version information ( not sure if already exists).

**Comment by kookiekrak** [comment]
@Rovak

**Comment by jerkyrs** [comment]
ive said this before, we need better communication of what version (based on a github tag) testnet and mainnet are running. The only way to really see this at the moment is the P2P version increments and if you get a lot of errors of incompatible version you know your probably not on the right one. Right now seems like *10000* is mainnet but  then i see this in logs

```
11:30:40.274 INFO  [nioEventLoopGroup-3-4] [HandshakeHandler](HandshakeHandler.java:135) Peer /45.58.96.210:51594 different p2p version, peer->46, me->10000
```

So some really old code running in the network. But now seems this version no longer increments with updates out of master. The latest proper tag i see is 2.0.1(10 days old) but there is some other variant 3.0.1(29 days old) that is older.
