### ISSUE TITLE
The block remain in pending status, can't produce block anymore,  with an exception report when there is no enough money to transaction tax

### ISSUE THREAD

**Issue by wangzichichi** [tronprotocol/java-tron#1010]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
No bandwidth, use the tax to send coin to a account, until the account doesn't have enough money any more.

2. What did you expect to see?
No exception reported.

3. What did you see instead?
18:07:18.006 ERROR [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:246) Account Insufficient bandwidth and balance to create new account
org.tron.core.exception.AccountResourceInsufficientException: Account Insufficient bandwidth and balance to create new account
  at org.tron.core.db.BandwidthProcessor.consumeBandwidth(BandwidthProcessor.java:121)
  at org.tron.core.db.Manager.consumeBandwidth(Manager.java:517)
  at org.tron.core.db.Manager.processTransaction(Manager.java:885)
  at org.tron.core.db.Manager.generateBlock(Manager.java:947)
  at org.tron.core.services.WitnessService.generateBlock(WitnessService.java:264)
  at org.tron.core.services.WitnessService.tryProduceBlock(WitnessService.java:222)
  at org.tron.core.services.WitnessService.blockProductionLoop(WitnessService.java:120)
  at org.tron.core.services.WitnessService.lambda$new$1(WitnessService.java:105)
  at java.lang.Thread.run(Thread.java:748)
18:07:18.006 INFO  [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:130) EXCEPTION_PRODUCING_BLOCK

18:23:49.468 INFO  [pool-17-thread-3] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.478 INFO  [pool-17-thread-4] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.479 INFO  [pool-17-thread-4] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.505 INFO  [pool-17-thread-1] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.519 INFO  [pool-17-thread-3] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.521 INFO  [pool-17-thread-3] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.541 INFO  [pool-17-thread-2] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.553 INFO  [pool-17-thread-1] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.554 INFO  [pool-17-thread-1] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.575 INFO  [pool-17-thread-4] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.594 INFO  [pool-17-thread-2] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.596 INFO  [pool-17-thread-2] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.626 INFO  [pool-17-thread-4] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.639 INFO  [pool-17-thread-2] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.641 INFO  [pool-17-thread-2] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.645 INFO  [pool-2-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:638) LocalNode stats:
============
MyHeadBlockNum: 6146
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 0
blockWaitToProc: 0
blockJustReceived: 0
syncBlockIdWeRequested: 1
badAdvObj: 0

18:23:49.661 INFO  [pool-17-thread-3] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.683 INFO  [pool-17-thread-4] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.684 INFO  [pool-17-thread-4] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.710 INFO  [pool-17-thread-1] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.725 INFO  [pool-17-thread-3] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.727 INFO  [pool-17-thread-3] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.755 INFO  [pool-17-thread-2] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.769 INFO  [pool-17-thread-1] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.771 INFO  [pool-17-thread-1] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.795 INFO  [pool-17-thread-2] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.819 INFO  [pool-17-thread-1] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.820 INFO  [pool-17-thread-1] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.843 INFO  [pool-17-thread-4] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.856 INFO  [pool-17-thread-2] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.858 INFO  [pool-17-thread-2] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.881 INFO  [pool-17-thread-3] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.894 INFO  [pool-17-thread-4] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.895 INFO  [pool-17-thread-4] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.916 INFO  [pool-17-thread-1] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.932 INFO  [pool-17-thread-3] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.933 INFO  [pool-17-thread-3] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.951 INFO  [pool-17-thread-2] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:49.967 INFO  [pool-17-thread-1] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:49.972 INFO  [pool-17-thread-1] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:49.997 INFO  [pool-17-thread-4] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:50.014 INFO  [pool-17-thread-2] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:50.016 INFO  [pool-17-thread-2] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:50.045 INFO  [pool-17-thread-3] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:50.058 INFO  [pool-17-thread-4] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:50.060 INFO  [pool-17-thread-4] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:50.085 INFO  [pool-17-thread-1] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:50.100 INFO  [pool-17-thread-3] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:50.102 INFO  [pool-17-thread-3] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:50.122 INFO  [pool-17-thread-2] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:50.140 INFO  [pool-17-thread-1] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:50.141 INFO  [pool-17-thread-1] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account
18:23:50.164 INFO  [pool-17-thread-4] [o.t.c.c.TransactionCapsule](TransactionCapsule.java:172) Transaction create succeeded！
18:23:50.178 INFO  [pool-17-thread-2] [o.t.c.d.Manager](Manager.java:490) push transaction
18:23:50.179 INFO  [pool-17-thread-2] [o.t.c.Wallet](Wallet.java:264) Account Insufficient bandwidth and balance to create new account

**Comment by sean-liu55** [comment]
This exception occurred during the producing block stage and should be caught and the log level is debug.This problem has no effect on the main program operation.

**Comment by sean-liu55** [comment]
https://github.com/tronprotocol/java-tron/pull/1011/files
