### ISSUE TITLE
No sync block when running a local node and connecting to the public testnet

### ISSUE THREAD

**Issue by lamductan** [tronprotocol/java-tron#1029]
I follow the tutorial on http://wiki.tron.network/en/latest/The_TRON_Network.html#how-to-build. I built successfully but when I use command "./gradlew run" the terminal is always at 85%. I try to edit the config.conf file in src/main/resource directory p2p version from 10000 to 71 then I remove output-directory but the problem don't be solved.
![config](https://user-images.githubusercontent.com/17760788/41583839-dd693df8-73cf-11e8-8083-b1ec183e73a9.png)
![run_85](https://user-images.githubusercontent.com/17760788/41584102-9d7ed5d0-73d0-11e8-99b7-4e0b7198eb3f.png)

How to get the result as in http://wiki.tron.network/en/latest/The_TRON_Network.html#how-to-build ?

**Comment by kookiekrak** [comment]
@lamductan Try following this guide: https://github.com/tronprotocol/Documentation/blob/master/TRX/Solidity_and_Full_Node_Deployment_EN.md

also 85% is fine, check the logs to see the sync status

**Comment by lamductan** [comment]
Thank you @kookiekrak for your support. I follow this tut and here is my tron.log in fullnode directory. I think there is some thing wrong. Another question is how long does it take to sync full node on test net?
[Here](https://github.com/tronprotocol/java-tron/files/2114933/tron.log) is my tron.log file.
