### ISSUE TITLE
Need help to setup a node for super representative election

### ISSUE THREAD

**Issue by kitgary** [tronprotocol/java-tron#1038]
I followed the README to setup a test node connected to the public test net but I can't managed to make it work. Here is my step.

sudo apt-get update
sudo apt-get upgrade
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo git clone https://github.com/tronprotocol/java-tron.git 
cd java-tron
sudo ./gradlew build
sudo cp src/main/resources/config.conf .
sudo vi ./config.conf

Change the followings

node.discovery = {
enable = true
persist = true
bind.ip = "INTERNAL.IP.ADDRESS"
external.ip = "EXTERNAL.IP.ADDRESS"
}

witnesses = [
{
address: theaddressthatyougotfromtronscan
url = "http://EXAMPLE.COM",
voteCount = 104
},
...
]

localwitness = [
ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890
]

sudo ./gradlew run -Pwitness

The node was deployed on Azure and I opened port 18888 and 50051

But it keeps showing

10:40:36.095 INFO  [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:138) Try Produce Block
10:40:36.095 INFO  [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:130) NOT_SYNCED

Please help!

**Comment by kookiekrak** [comment]
@kitgary hi please email me for a developer slack invite tian@tron.network

someone will be able to assist you in there
