### ISSUE TITLE
On contract "AccountCreateContract", there are two "type" print

### ISSUE THREAD

**Issue by wangzichichi** [tronprotocol/java-tron#1048]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Try to create account, see the contract information.

2. What did you expect to see?
All the information print normal.

3. What did you see instead?
there are two "type" print
14:43:47.176 INFO  [main] [TestClient](TestClient.java:821) hash: 
c68b8bb980437475cb83cadfa7507b57167e66bbdbc8bc35a865656835ecf99de756141622c883b5f97
txid: 
e7079e2e2bc5017fb0d7a546b1eab52c491fe23bcb54ce756141622c883b5f97
raw_data: 
{
ref_block_bytes: 0896
ref_block_num: 0
ref_block_hash: 923aa81485b247b6
contract: 
{
contract 0 :::
[
type: AccountCreateContract
type: Normal
account_address: AH艶HI��
                         <٫Z
                            p?�;3
owner_address: TTW2oPaCo4TJbhjDPAnS8imBdUnLsKGPXV
]

}
timestamp: Wed Jun 20 14:43:13 CST 2018
}
signature: 
{
signature 0 :e7ef2cd44b1114759d9de3be5c26cde2a633b83bba9d88ef69dd3f817cf2b2c56a0bb4dfcbd815ecfa57f5ebc6ba2d8461f9bbbf37811a175e15968b1d178c5b00
}

**Comment by nanfengpo** [comment]
fixed: https://github.com/tronprotocol/wallet-cli/pull/133
