### ISSUE TITLE
Please add the "walletextension" service in grpc-gateway project

### ISSUE THREAD

**Issue by wangzichichi** [tronprotocol/java-tron#1052]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Try to use http to query the "rpc GetTransactionsToThis (AccountPaginated) returns (TransactionList)"

2. What did you expect to see?
The transaction list can receipt, and the information is right.

3. What did you see instead?
404 NOT FOUND

**Comment by ithinker1991** [comment]
done @wangzichichi
