### ISSUE TITLE
package org.tron.protos.core does not exist

### ISSUE THREAD

**Issue by yangboz** [tronprotocol/java-tron#106]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

“
Error:(12, 28) java: package org.tron.protos.core does not exist
”

2. What did you expect to see?

“
gradlew get dependency ready.
”

3. What did you see instead?

“
Error:(12, 28) java: package org.tron.protos.core does not exist
”

**Comment by xiechang33** [comment]
Please update the latest code , then execute “./gradlew run”.

**Comment by yangboz** [comment]
Just copied the *.proto gen files to java/main folder, now it works, thanks.
