### ISSUE TITLE
What do you mean by kafka based network

### ISSUE THREAD

**Issue by ajayt6** [tronprotocol/java-tron#11]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Question:
What do you mean by kafka based network? In actual deployment, would there be a centralized kafka for all nodes or would the kafka instances run silently on each and every node?

2. What did you expect to see?
Question

3. What did you see instead?
Question

**Comment by sasaxie** [comment]
The consensus of TRON adopts a three-step strategy. The first step is to adopt a Kafka-based technology system to implement a centralized consensus algorithm. The purpose of TRON is to achieve system joint debugging and functional integration.

The second step is to use Raft-based distributed consensus mechanism to realize the centralized and distributed leapfrogging. This step gradually improves the functions of network and distribution and lays the foundation for the eventual realization of a wide distribution with no logical center.

The third step is to realize the Consensus mechanism of PoS and realize the Byzantine Fault Tolerant Consensus based on the "Margin Mechanism + Epoch Confirmation" and the compatibility consensus between PoS and PoW.

TRON is currently open source code to achieve a consensus algorithm for the first phase of the center. The second phase of the distributed consensus algorithm is under development and testing.

**Comment by ajayt6** [comment]
Thanks for the quick response. Going through your answer.

Should i keep this issue open so that others can see your answer?

Is there some other place your foundation is planning for all these technical questions to be discussed (like a subreddit) or is the current plan to discuss via github issues?
Thanks
