### ISSUE TITLE
Looping/Frozen MyHeadBlockNum

### ISSUE THREAD

**Issue by tronhub** [tronprotocol/java-tron#1106]
Hi there,

My script detected looping at MyHeadBlockNum.
It is frozen? It has been running fine since day one.

07:09:43.751 INFO  [pool-1-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:635) LocalNode stats:
============
MyHeadBlockNum: 107458
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 0
blockWaitToProc: 0
blockJustReceived: 0
syncBlockIdWeRequested: 125
badAdvObj: 0

07:09:52.026 INFO  [pool-10-thread-1] [SyncPool](SyncPool.java:140) -------- active connect channel 0
07:09:52.026 INFO  [pool-10-thread-1] [SyncPool](SyncPool.java:141) -------- passive connect channel 0
07:09:52.026 INFO  [pool-10-thread-1] [SyncPool](SyncPool.java:142) -------- all connect channel 0
07:09:52.026 INFO  [pool-10-thread-1] [SyncPool](SyncPool.java:163) Peer stats:
Active peers
============
Other connected peers
============

07:09:53.752 INFO  [pool-1-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:635) LocalNode stats:
============
MyHeadBlockNum: 107458
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 0
blockWaitToProc: 0
blockJustReceived: 0
syncBlockIdWeRequested: 125
badAdvObj: 0

07:10:02.031 INFO  [pool-10-thread-1] [SyncPool](SyncPool.java:140) -------- active connect channel 0
07:10:02.031 INFO  [pool-10-thread-1] [SyncPool](SyncPool.java:141) -------- passive connect channel 0
07:10:02.031 INFO  [pool-10-thread-1] [SyncPool](SyncPool.java:142) -------- all connect channel 0
07:10:02.032 INFO  [pool-10-thread-1] [SyncPool](SyncPool.java:163) Peer stats:
Active peers
============
Other connected peers
============

07:10:03.753 INFO  [pool-1-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:635) LocalNode stats:
============
MyHeadBlockNum: 107458
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 0
blockWaitToProc: 0
blockJustReceived: 0
syncBlockIdWeRequested: 125
badAdvObj: 0

Regards,
David

**Comment by kookiekrak** [comment]
Please update to latest release and also wipe your output-directory database!
