### ISSUE TITLE
gRPC API should include block and transaction hashes in replies.

### ISSUE THREAD

**Issue by Crypto2** [tronprotocol/java-tron#1107]
I feel like the gRPC API should include block and transaction hashes in replies including Blocks and Transactions.

The main reasons being:

1. Depending on the language used it can be hard if not impossible to get the raw data for them. The spec also doesn't specify if it means the protobuf serialized format or the actual raw data concatenated somehow. I'm also not sure if the serialized format could potentially change in the future or when new fields are added to the messages causing issues?

2. People using the gRPC to REST gateway I don't think would have any way to calculate the hashes.

3. For example in PHP it seems like contracts can't be read properly since it can't handle the polymorphic parameter field in the contract so those users would be forced to use the gateway to read transactions/blocks.

**Comment by zhaohong** [comment]
good  suggestion, will do.
