### ISSUE TITLE
The transactions can't create successfully after continuing create transaction 500+/second for a while

### ISSUE THREAD

**Issue by wangzichichi** [tronprotocol/java-tron#1108]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Try to create 500+ transactions per seconds, do the test at least 20 minutes.

2. What did you expect to see?
The transaction num is remain at 300+ in every block.

3. What did you see instead?
After 10 minutes, no transaction can create successfully, there are no transaction in the block.
And in the server, the log below is always displayed.

14:26:21.956 INFO  [pool-17-thread-2] [o.t.c.d.Manager](Manager.java:456) Tapos failed, block not found, ref block 0,  , solid block Num:108228,ID:000000000001a6c4e4cf2dbb6bb9635925355df6730f99d838013a5e11cb0c3d head block Num:108231,ID:000000000001a6c7bb4af357bcd2bb985a63326b79d59590e1f7f69222d47715
14:26:21.957 INFO  [pool-17-thread-2] [o.t.c.Wallet](Wallet.java:275) tapos errorTapos failed, block not found, ref block 0,  , solid block Num:108228,ID:000000000001a6c4e4cf2dbb6bb9635925355df6730f99d838013a5e11cb0c3d head block Num:108231,ID:000000000001a6c7bb4af357bcd2bb985a63326b79d59590e1f7f69222d47715
14:26:21.957 INFO  [pool-17-thread-1] [o.t.c.d.Manager](Manager.java:456) Tapos failed, block not found, ref block 0,  , solid block Num:108228,ID:000000000001a6c4e4cf2dbb6bb9635925355df6730f99d838013a5e11cb0c3d head block Num:108231,ID:000000000001a6c7bb4af357bcd2bb985a63326b79d59590e1f7f69222d47715
14:26:21.957 INFO  [pool-17-thread-1] [o.t.c.Wallet](Wallet.java:275) tapos errorTapos failed, block not found, ref block 0,  , solid block Num:108228,ID:000000000001a6c4e4cf2dbb6bb9635925355df6730f99d838013a5e11cb0c3d head block Num:108231,ID:000000000001a6c7bb4af357bcd2bb985a63326b79d59590e1f7f69222d47715
14:26:21.957 INFO  [pool-17-thread-3] [o.t.c.d.Manager](Manager.java:456) Tapos failed, block not found, ref block 0,  , solid block Num:108228,ID:000000000001a6c4e4cf2dbb6bb9635925355df6730f99d838013a5e11cb0c3d head block Num:108231,ID:000000000001a6c7bb4af357bcd2bb985a63326b79d59590e1f7f69222d47715
14:26:21.957 INFO  [pool-17-thread-3] [o.t.c.Wallet](Wallet.java:275) tapos errorTapos failed, block not found, ref block 0,  , solid block Num:108228,ID:000000000001a6c4e4cf2dbb6bb9635925355df6730f99d838013a5e11cb0c3d head block Num:108231,ID:000000000001a6c7bb4af357bcd2bb985a63326b79d59590e1f7f69222d47715

**Comment by Shrey33** [comment]
@wangzichichi Can you tell me the reproduction steps ?
