### ISSUE TITLE
How check transaction is confirmed or not?

### ISSUE THREAD

**Issue by 2tvenom** [tronprotocol/java-tron#1111]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Need check transaction confirmation, how do it?

2. What did you expect to see?
In test net confirmed transaction. six-day transactions still not confirmed in test net https://test.tronscan.org/#/transaction/0005ffdbdd6d7b725cd15dd35006002b043ffb9979f13dc8e53855b95a86fe03

**Comment by zhaohong** [comment]
hi,  about  19 block to confirm the transaction.,

**Comment by kookiekrak** [comment]
@2tvenom if you can find the transaction in the solidity node, then the transaction is guaranteed confirmed
