### ISSUE TITLE
Not able to get account info

### ISSUE THREAD

**Issue by Anil402** [tronprotocol/java-tron#1112]
have set up the gRPC and full node for tron.
I have created a new address by using this API
curl -X POST -k http://127.0.0.1:18890/wallet/generateaddress.\
It gives me the address and key.

And also when I am using account info API.
curl -X POST http://127.0.0.1:18890/wallet/getaccount -d '{"address": "base 64 encoded address pasted here"}'
it return {} blank object

**Comment by stevenkitter** [comment]
i get the same issue please reopen it.
