### ISSUE TITLE
Confusion in syncing

### ISSUE THREAD

**Issue by Anil402** [tronprotocol/java-tron#1113]
I have started the full node jar in with testnet config
I am getting output like this
17:55:38.058 INFO [pool-3-thread-1] o.t.c.n.n.NodeImpl LocalNode stats:
MyHeadBlockNum: 107460
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 0
blockWaitToProc: 0
blockJustReceived: 0
syncBlockIdWeRequested: 8086
badAdvObj: 0

Is it ok?
It is stuck at this point since last 4 days

**Comment by kookiekrak** [comment]
@Anil402 please update to the latest 2.0.6 release + configuration files from https://github.com/tronprotocol/TronDeployment

and delete the output-directory folder
