### ISSUE TITLE
The http API "gettransactioninfobyid" and "/walletsolidity/getpaginatedassetissuelist" didn't work normally

### ISSUE THREAD

**Issue by wangzichichi** [tronprotocol/java-tron#1115]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Try to use http API request "gettransactioninfobyid" and "/walletsolidity/getpaginatedassetissuelist"

2. What did you expect to see?
These two API can work normally

3. What did you see instead?
Get nothing from ApI "gettransactioninfobyid"
API "/walletsolidity/getpaginatedassetissuelist" is not support.

**Comment by zk19862018** [comment]
![image](https://user-images.githubusercontent.com/39797046/59400749-17e0d980-8dcb-11e9-9951-e40efb1ae03b.png)
and "gettransactioninfobyid" works
