### ISSUE TITLE
Method not found exception in both case full node and solidity node

### ISSUE THREAD

**Issue by Anil402** [tronprotocol/java-tron#1119]
curl -X POST http://127.0.0.1:8086/wallet/createadresss -d '{"value": "QW5pbEAxMjM=" }'
{"error":"Method not found: protocol.Wallet/CreateAdresss","code":12}

I have started both full node and solidity node.
Started 2 grpc-gateway one for full node and another for solidity node
but still, API not working under wallet section
1. Tried for full node 
curl -X POST http://127.0.0.1:8086/wallet/createadresss -d '{"value": "QW5pbEAxMjM=" }'
{"error":"Method not found: protocol.Wallet/CreateAdresss","code":12}

2.  Tried for solidity node 
curl -X POST http://127.0.0.1:8088/wallet/createadresss -d '{"value": "QW5pbEAxMjM=" }'
{"error":"Method not found: protocol.Wallet/CreateAdresss","code":12}

**Comment by kookiekrak** [comment]
@Anil402 we've corrected the spelling of that function, it's now
```
 curl -X POST http://127.0.0.1:8090/wallet/createaddress -d '{"value": "483945255C4A4975746B22696F57" }'
```

additionally please provide the value as hex
