### ISSUE TITLE
The English version of the whitepaper has been removed for over a month now.. 

### ISSUE THREAD

**Issue by TRXPetEmporium** [tronprotocol/java-tron#113]
A lot of people are starting to ask questions about that.  

It's hard to answer a lot of questions about the project and how it all works without having that as a reference.  

Please provide an update on this.

Okay it's been 8 days.  No response.  You guys plagiarized a lot of the white paper, and blamed it on the English translation.. But then someone dug up the Chinese version and found the exact same issues proving Justin Sun lied about that.  BOTH VERSIONS have been removed from your website and all trace of them have disappeared.  You NEED to re-issue the whitepapers, this is not something you can just dismiss and ignore.

**Comment by JusticeForMikeBrown** [comment]
These types of questions should be posted to Tron's Telegram channel.

**Comment by ruchern** [comment]
@styk-tv Is there an official telegram channel that I am unaware of?

**Comment by Pit-R** [comment]
@TronNetworkEs
@TronNetworkEn
@Tronfc
@TronNetworkUk
@TronNetworkRU
@TronNetworkKR
@TronNetworkUS
@TronNetworkCN

**Comment by ybhgenius** [comment]
Hello,

Thanks for your participation.

Please check this link:

https://crowdin.com/project/trondocs

You can translate or correct relevant texts through this link.

We will reward you according to your contribution.

Best Regards

Boheng Yang
