### ISSUE TITLE
I cannot withdraw my tron on the tron website. Any help for me?

### ISSUE THREAD

**Issue by daladala2015** [tronprotocol/java-tron#1131]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

**Comment by nanfengpo** [comment]
Please show more details

**Comment by kookiekrak** [comment]
@daladala2015 Hi, please provide more information where you're trying to withdraw? Closing for now but you can always reopen!

**Comment by daladala2015** [comment]
I transferred my tron from an exchange to an ERC20 wallet. Somewhere along the line, I saw the message that we should transfer the coins back to the exchanges before the end of June. But by the time I saw it, the deadline had already elapsed. So I have been trying since to withdraw my tron, but no success so far.

**Comment by kookiekrak** [comment]
You have access to the erc20 wallet right? There are a few exchanges supporting the swap still, like binance

**Comment by Aqwords** [comment]
Baik terima kasih

**Comment by daladala2015** [comment]
So what do I do when I go to binnance. Can you help me with the step by step approach? I am grateful to all of you for your concern in helping me out. Thanks.

**Comment by daladala2015** [comment]
I have not been able to access my coins yet, but i am so grateful for the care and concern. Thanks so much.
