### ISSUE TITLE
Is there any more documentation for developing smart contracts?

### ISSUE THREAD

**Issue by Dylan-Phoon** [tronprotocol/java-tron#1135]
https://tron-wiki.readthedocs.io/en/latest/TRON_Virtual_Machine.html
^This is very dry and doesnt explain a whole lot. e.g. How to use javascript in contracts or any of the API's for the tron mainnet.

**Comment by kookiekrak** [comment]
@Dylan-Phoon the first version TRON VM will support solidity. you can use the remix (http://remix.ethereum.org) to compile the code.

please join our developer slack if you haven't yet. email me at tian@tron.network for an invite
