### ISSUE TITLE
How to implement tron payments to a website?

### ISSUE THREAD

**Issue by miratcan** [tronprotocol/java-tron#1136]
1. Are there any guide to do it?
2. Should I run Tron node to accept payments? Or are there any API's that can I use?

**Comment by kookiekrak** [comment]
@miratcan you can either write the code and run a tron node so that you can generate address to accept payments, or use a 3rd party service like https://www.coinpayments.net/ that has finished TRON integration.

**Comment by miratcan** [comment]
thanks @kookiekrak
