### ISSUE TITLE
wallet always showing 0 balance

### ISSUE THREAD

**Issue by zebpaypeswani** [tronprotocol/java-tron#1141]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I am running a testnet node. I connected Android app to my node and generated address. 
Go to tronscan website where I login with my private key and requested test tokens I got 10,000 TRX
in account here. But In android wallet or any other wallet I tried It shows 0 balance. I tried with wallet-cli also but it also showing zero balance.

 2. What did you expect to see?
Balance should be 10,000 TRX on all wallets

3. What did you see instead?
0 balance 

Here is the more info
https://github.com/lky1001/tron-android-wallet/issues/20

**Comment by kookiekrak** [comment]
can you try the wallet-cli app for testnet?
