### ISSUE TITLE
Off-line multi sign

### ISSUE THREAD

**Issue by xianaofei** [tronprotocol/java-tron#1181]
Do you support off - line multi - sign?
Please provide a reference, thank you.

**Comment by zaranur** [comment]
Dear if possible? Suggest Me for that

**Comment by zaranur** [comment]
My device is hacking

**Comment by unbridledwharf9** [comment]
Interesting

**Comment by zhaohong** [comment]
not support for now

**Comment by Melvillian** [comment]
> not support for now

Does this mean there is no multisignature support in TRON? If there is support for multisig, can someone link a developer guide for how to implement it outside of java-tron?

**Comment by zhaohong** [comment]
@Melvillian  you can implement multisignature by smart contract for  now.
also, we will release the  native muti-sig feauture by the end of 2018.

**Comment by argjv** [comment]
> @Melvillian you can implement multisignature by smart contract for now.
> also, we will release the native muti-sig feauture by the end of 2018.

Can't find any documentation about the recently added multisig feature. Is there any example on how to create a multisig account and transaction?

**Comment by zk19862018** [comment]
https://tronprotocol.github.io/documentation-EN/Tron-multi-signatures/
