### ISSUE TITLE
toString() returns null

### ISSUE THREAD

**Issue by sdargutev** [tronprotocol/java-tron#125]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Looked at the code.

2. What did you expect to see?
Just wondering.

3. What did you see instead?
toString() method of many classes in the package org.tron.core.net.message return null. Is this intentional? 
This can cause some side effects, and some confusion when debugging...

**Comment by Rovak** [comment]
Thanks for your suggestion, the overrides (while not optimal) aren't causing any problems right now.

Feel free to open a pull request if you find any cases where these overrides cause you any trouble. Or reopen this issue and refer to specific classes that you believe should be improved.
