### ISSUE TITLE
(docs) README- Quick Start does not contain initial software packages needed to build java-tron.

### ISSUE THREAD

**Issue by anthrwrld** [tronprotocol/java-tron#129]
1. What did you do?
I looked at the README document to understand what is needed to build the java-tron code.

2. What did you expect to see?
I expected to see a list of all software package dependencies needed to build java-tron upfront before seeing steps to download/build java-tron.

3. What did you see instead?
I saw immediate commands to build the code, but no indication as to where I input the commands to build the code base or what packages I needed installed already. My thoughts as I saw the initial build steps:

-I have git installed already, so I could clone the repo. (What if I didn't have git? where can I download it? Does it matter which version?)

-After cloning the repo, I use gradle to build. (What if I don't have gradle? where can I download it? Does it matter which version?)

-Import project to IDEA. (What is IDEA? Where can I get the package? Does it matter which version?)

**I understand as a software engineer it can be understood where the cmd line arguments, however, the build process 'could' differ slightly with different OS in the future and should be clear as to what the user needs to have installed on his machine before attempting any compilation of code.

**Comment by matthewscode** [comment]
If you're a developer git should be easily enough found. Google perhaps.

You need gradle. Latest version. Google.

IDEA -> IntelliJ IDEA one of the most popular IDE's for Java Developers.

This build is as standard as standard gets for Java.

I feel like these question's don't need to be answered in the readme personally.

**Comment by Rovak** [comment]
Most of the questions have been answered in recent updates on the readme. As matthew suggests we should assume that developers know the basics.

Maybe we could improve the documentation for non-technical people who want to run their own node.

Closing for now, if you have any specific details that really should be in the readme then feel free to reopen this issue or make a new one.
