### ISSUE TITLE
One of mainnet node grpc not responding anymore

### ISSUE THREAD

**Issue by nfleury** [tronprotocol/java-tron#1368]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Query one of mainnet seed node (18.220.232.201:50051) via grpc for example get last block (or any other query)

2. What did you expect to see?

Node responding 

3. What did you see instead?

The node is constantly responding with unavailable exception

```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
```

`connection timed out: ec2-18-220-232-201.us-east-2.compute.amazonaws.com/18.220.232.201:50051`

**Comment by Shrey33** [comment]
Can you tell me the reproduction steps ?

**Comment by nfleury** [comment]
@Shrey33 Just do any request via grpc to that node (like get block by num), or you can also do a rpc request on this url with a post: http://18.220.232.201:8090/wallet/getblockbynum

With the following body request: 

{"num" : 1}

The request keep pending, using another mainnet address (from https://github.com/tronprotocol/Documentation/blob/master/TRX/Official_Public_Node.md) it's ok:

For ex: http://35.183.101.48:8090/wallet/getblockbynum is OK

**Comment by Shrey33** [comment]
@nfleury this could be because you did some improper operation or your system have some problem, please provide the complete log file to us, then let us check what happened in your computer.

**Comment by nfleury** [comment]
@Shrey33 Maybe my previous comments wasn't clear. I think that the mainnet node with the address 18.220.232.201 is down or is very slow., testing the same request with another node is working fine.

Could you do a rpc or grpc request on this address : 18.220.232.201 ?

**Comment by Shrey33** [comment]
@nfleury Can you enlighten me about the negative impact ?

**Comment by nfleury** [comment]
The negative impact was just that some third party client, like trxplorer.io in my case can rely on one of those nodes that don't reply anymore

But anyway it was fixed and I implemented a load balancer to prevent this kind of thing from happening again. 

I am closing this issue. Thanks
