### ISSUE TITLE
Lost 31,000 trx sending to Binance

### ISSUE THREAD

**Issue by craigcreasy** [tronprotocol/java-tron#1378]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I sent 31,000 trx to Binance from my TranWatch Desktop wallet on August 23 at 9:52pm. I received a "successful" message on my wallet, but never received any notification from Binance saying it was received. It's now been two days and nothing.

2. What did you expect to see?
I have used Binance many times and I expected to see my history processing the deposit and then a complete message.

3. What did you see instead?
Binance has no record of anything ever attempting to be deposited.

**Comment by Rovak** [comment]
What is your wallet address? Then i can take a look where it went

**Comment by craigcreasy** [comment]
Where do I find the address for you? I have also attached a couple screenshots of my wallet, so you can see the "sent" transaction and my backup information. I had also tried to send 736 trx earlier that day and it also did not deposit.
Thank you   On Sunday, August 26, 2018, 6:58:13 AM MDT, Roy van Kaathoven <notifications@github.com> wrote:  
 
 
What is your wallet address? Then i can take a look where it went

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avg.com  |

**Comment by craigcreasy** [comment]
Here is an image of the original received TRX to my wallet.    On Sunday, August 26, 2018, 6:58:13 AM MDT, Roy van Kaathoven <notifications@github.com> wrote:  
 
 
What is your wallet address? Then i can take a look where it went

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avg.com  |
