### ISSUE TITLE
Wallet balance and transaction amount is of type long. Shouldn't be double? 

### ISSUE THREAD

**Issue by sdargutev** [tronprotocol/java-tron#138]
1. What did you do?
Just looking at the source code.

2. What did you expect to see?
Wallet balance and transaction amount to support floating point values.

3. What did you see instead?
Wallet balance and transaction amount is of type "long". Does that mean that there will be no fractions of TRX being transferred?

**Comment by Arfanmi** [comment]
Noticed the same issue.

**Comment by zhaohong** [comment]
@sdargutev    double  numbers may  lose precision.      We can use  number 10 stands for one trx  if we want fraction of trx.

**Comment by sdargutev** [comment]
Thank you for your reply @zhaohong 

In that case you will still need to provide additional value for precision, in other words, the scaling factor (10, 100, 1000 or so on). This is just like BigDecimal, so i guess you could switch to BigDecimal, to save yourself some effort. 
The question is, if you release the Mainnet without support for fractions, will it be possible to add this feature later... I only have general knowledge of Blockchain, but isn't it supposed to prevent changing past values? 

E.g.:
Time `x` (no support for fractions):
Transaction 10 TRX from  A to B.

Time `x+1` (support for fractions added with scale factor 10):
at this point the previous transaction must be updated with the value 100, but it wont be possible because that will break the blockchain. Also what happens with cold storage wallets at this point, they also must be updated to reflect the new value.

At this point fractions might not be needed, but if TRX grows to the value of say 2 USD (i will be in heaven then 💃), then it will be needed, otherwise the cheapest thing you could purchase with TRX will cost 2 USD.

Sorry my ignorance if i totally misunderstood something :)

**Comment by zhaohong** [comment]
@sdargutev   the  minimum  unit of tron is fixed like eth , bitcoin.     for  example 1 bitcoin = 10^9 satoshi,  when you transfer 0.1 bitcoin,  actually  bitcoin use  10^8 satoshi  representing  0.1 bitcoin .

**Comment by sdargutev** [comment]
@zhaohong ok I get it now 👍 
closing the issue
