### ISSUE TITLE
How can I get the TRX from the testnet

### ISSUE THREAD

**Issue by CooperLee123** [tronprotocol/java-tron#1380]
hello, I want to get some test TRX, and I create a wallet on the trx testnet, but How to go get the test TRX,Thank you !

**Comment by lilaizhencn** [comment]
@huzhenyuan

**Comment by haidoan** [comment]
@CooperLee123 Did you manage to get some TRX for testing? i get same issue when request TRX after register at test.tronscan.org, thanks

**Comment by zhp1254** [comment]
how to get trx on test-net

**Comment by lightshine001** [comment]
Same to me. Is any way to get test TRX?

**Comment by haidoan** [comment]
in case some one need some real trx for testing, visit this channel and get 2 free trx.
