### ISSUE TITLE
Transaction list RPC call

### ISSUE THREAD

**Issue by mathieumagalhaes** [tronprotocol/java-tron#1390]
Please answer these questions before submitting your issue. Thanks!

**1. What did you do?**
Deployed a FullNode and a Solidity node (--trust-node correctly pointing to FullNode)
Following the guide I tried to get the transactions of an account.
``` 
/walletextension/gettransactionsfromthis
Function：Query the list of transactions sent by an address
demo: curl -X POST  http://127.0.0.1:8091/walletextension/gettransactionsfromthis -d '{"account" : {"address" : "41E552F6487585C2B58BC2C9BB4492BC1F17132CD0"}, "offset": 0, "limit": 10}'
Parameters：Address is the account address, converted to a hex string; offset is the index of the starting transaction; limit is the number of transactions expected to be returned
Return value：Transactions list
```

If possible, provide a recipe for reproducing the error.

**2. What did you expect to see?**
A transaction list with transactions of the account.
( There are transactions, I checked with TRON explorer )
( Address: TWsm8HtU2A5eEzoT8ev8yaoFjHsXLLrckb )
( HEX: 41E552F6487585C2B58BC2C9BB4492BC1F17132CD0 )

**3. What did you see instead?**
The response is an empty array.
`{"transaction":[]}`

Am I missing something to get this functionality/API working?

**Comment by kookiekrak** [comment]
@mathieumagalhaes is your solidity node synced to the network? it takes around 3-4 hours

**Comment by mathieumagalhaes** [comment]
@kookiekrak firstly thanks for your reply.
I'm not quite sure actually as I'm not aware how to check this.
I'm however sure it's been on for a couple of days right now so I hope it is.
Is there an endpoint to check if the solidity node is synced?

Thanks in advance

**Comment by zk19862018** [comment]
![image](https://user-images.githubusercontent.com/39797046/59584630-18ea7180-9111-11e9-86cb-741f1f44b053.png)

**Comment by livingrock7** [comment]
can I fetch the block transactions using fullnode?
