### ISSUE TITLE
Build failing for Odyssey-v2.0.8.1 release on windows.

### ISSUE THREAD

**Issue by myraushanraj** [tronprotocol/java-tron#1395]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Download the Odyssey-v2.0.8.1 release.
From the command line, ran the command gradlew build.

2. What did you expect to see?
Expected to see the build succeed, and output a jar file.

3. What did you see instead?
Build Failed.

![tron build fail](https://user-images.githubusercontent.com/26787881/44716894-2890bf00-aad9-11e8-8de2-ba5fe6504c15.PNG)

**Comment by zhaohong** [comment]
thanks feedback, will  figure this out.
