### ISSUE TITLE
Two instances of tron: balance not getting reduced

### ISSUE THREAD

**Issue by ajayt6** [tronprotocol/java-tron#14]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I ran two instances of tron on the same machine (started one as --type server and other as --type normal). Sent 10 from one account to another.Then checked balances on both.

2. What did you expect to see?
Balance reducing by 10 on account from which it was sent. Balance increasing by 10 on the other account.

3. What did you see instead?
Balance remaining same on account from which it was sent. Balance increasing by 10 on the other account.

**Comment by sasaxie** [comment]
Thanks for your issue.

I did not repeat the bug. Whether the two addresses are the same?

![send](https://user-images.githubusercontent.com/11765472/34416129-0bc8d468-ec2d-11e7-8999-4d51cc3f0019.gif)

**Comment by ajayt6** [comment]
No. The addresses were distinct. Note that one instance was type normal and the other was type server.

**Comment by sasaxie** [comment]
Copy that, I try again. Thank you so much.

**Comment by sasaxie** [comment]
Still correct. Is Kafka working?

**Comment by ajayt6** [comment]
Yes Kafka and zookeeper is working. I am outside now. If you want I can get you a screen grab like you did earlier, showing the situation , when I reach back after a few hours. What tool did you use to get the screen grab?

**Comment by sasaxie** [comment]
That's perfect! Thanks you very much. [LICEcap](https://www.cockos.com/licecap/) can help you to get the screen grab.

**Comment by ajayt6** [comment]
PFA gif of the reproduction of above issue
Note that on sending 10 from one account to another, the account from which it was sent still shows a balance of 10 while the receiving account shows the credit correctly.
![issue14](https://user-images.githubusercontent.com/10473899/34421489-2e95fe88-ebd5-11e7-9c4b-46de368659a6.gif)

**Comment by ajayt6** [comment]
Let me know if the above gif is clear.

**Comment by khuezy** [comment]
@ajayt6 good find!

That gif was like watching a feature film 📽 . 5/5 🍅

**Comment by tronfoundation** [comment]
WIP

**Comment by sasaxie** [comment]
@ajayt6 very clear!
What's your current commit id? I run it still correctly.

**Comment by ajayt6** [comment]
Sure. Let me know what more info is required from my side.
Initially I was on these commits:
server - 6e48e622cb2d303790139f118b515165bf7a843c
normal - 5a61a4f4fed2ddd8abb3e51470e045987344870c

I updated both to latest (e0c668c8a0f03ed87760952b660e16a8b9e5a976) now and checked again and i get the same issue.
>I found that gif, sender didn't reindex.

Is the reindexing supposed to happen automatically or is there a separate command that needs to be manually executed for that?

**Comment by ajayt6** [comment]
Another observation is that this issue is occurring when the sender is of 'type --normal'. I tried starting both instances as '--type server', and things work fine without a bug then.

**Comment by sasaxie** [comment]
Thank you very much! 

First, reindexing is a Java function, it happend automatically.

Second, I will follow your description to try.

Have a good time!

**Comment by ajayt6** [comment]
I tried some debugging (kind of like blackbox, since I am still not very familiar with the project) .

When type is 'normal', in receiveBlock(), the below if condition evaluates to 'true' and returns before         utxoSet.reindex() is called. This is the reason reindexing is not happening automatically. I tried calling utxoSet.reindex() before the below conditional statement, but still resulted in balance not getting reduced by sent amount. 
>        if (!ByteArray.toHexString(block.getBlockHeader().getParentHash().toByteArray()).equals(ByteArray.toHexString
https://github.com/tronprotocol/java-tron/blob/e0c668c8a0f03ed87760952b660e16a8b9e5a976/src/main/java/org/tron/core/Blockchain.java#L270

**Comment by sasaxie** [comment]
> if(!ByteArray.toHexString(block.getBlockHeader().getParentHash().toByteArray()).equals(ByteArray.toHexString

The if condition evaluates to 'true',  indicating that the received Block can not be appended to Blockchain.

```java
if (block.getBlockHeader.getParentHash == LASH_HASH) {
    // can be appended to Blockchain
} else {
    // can not be appended to Blockchain
}
```

**Comment by ajayt6** [comment]
Were you able to reproduce this @sasaxie  ?

**Comment by sasaxie** [comment]
No.

**Comment by Rovak** [comment]
A lot of changes have been made in the latest version. I can no longer reproduce this problem. If this issue persist then please reopen the issue.
