### ISSUE TITLE
My FULLNODE block height stays at 2241159 and is out of sync

### ISSUE THREAD

**Issue by wanglei-sky** [tronprotocol/java-tron#1509]
My FULLNODE block height stays at 2241159 and is out of sync

I call wallet/getnowblock, which returns "number":2241159, and I wonder why

Log:

13:18:43.022 INFO  [pool-9-thread-1] [SyncPool](SyncPool.java:163) Peer stats:
Active peers
============
Peer 18.130.56.16:18888: [           bc4715bc, ping    226 ms]-----------
connect time: 2018-09-11 11:49:48.05
last know block num: 2241159
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:2419
syncToFetchSizePeekNum:2241160
syncBlockRequestedSize:0
unFetchSynNum:0
syncChainRequested:NULL
blockInPorc:0
NodeStat[reput: 153(137), discover: 1/1 1/1 0/0 0/0 192ms, p2p: 1/1/1 , tron: 1535/535   , tcp flow: 2

Peer 13.211.164.189:18888: [           41bd5553, ping    300 ms]-----------
connect time: 2018-09-11 11:49:48.065
last know block num: 2241159
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:2419
syncToFetchSizePeekNum:2241160
syncBlockRequestedSize:0
unFetchSynNum:0
syncChainRequested:NULL
blockInPorc:0
NodeStat[reput: 153(147), discover: 1/1 0/0 372/413 0/0 354ms, p2p: 1/1/1 , tron: 534/533   , tcp flow: 2

**Comment by charaton** [comment]
Did you resolve this? I'm having same issue.
