### ISSUE TITLE
Suggestion: Add GetMetaData API

### ISSUE THREAD

**Issue by Rovak** [tronprotocol/java-tron#1550]
I would like to suggest to add an API which provides information about the node

The API could return the following data:

* Version number
* Latest Block Number and Hash
* Operation System
* GRPC API Usage + Configuration
* HTTP API Usage + Configuration

Optionally 

* Average CPU usage
* Database size
* Total / Used RAM

With this data we can get a better insight in the network:

* How many nodes have upgraded to the latest version. How many nodes will be left behind when doing a network upgrade
* Which chains are active on the network, if any nodes are forked
* Detect abnormalities between nodes
* Check if the node is available for HTTP or GRPC API calls
* Check how much the GRPC and HTTP API are being used and decide if it is better for a dapp to connect to another node

**Comment by zhaohong** [comment]
will do
