### ISSUE TITLE
The solidity node data is damaged，i want to resync,  it is too slow,  any  suggestion?

### ISSUE THREAD

**Issue by bitcodernull** [tronprotocol/java-tron#1552]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

**Comment by zhaohong** [comment]
please use kill -15 to stop node.

**Comment by wanglei-sky** [comment]
I want to know how to solve the following error?
Sometimes the process itself dies
**Error in sync solidity block dup exception**

**Comment by zhaohong** [comment]
@wanglei-sky   the data has corrupt at this situation.
