### ISSUE TITLE
Solidity/Fullnode stucks when DupTransactionException occurs.

### ISSUE THREAD

**Issue by benjaminchencobinhood** [tronprotocol/java-tron#1557]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Running fullnode and solidity node in docker on k8s.  Once the fullnode/solidity receive a duplicate transaction, then the node can't sync anymore.

2. What did you expect to see?

Fullnode/solidity node should recover and keep syncing.

3. What did you see instead?

Node stucks, never going forward, it keep requesting the same block. The only way is to delete the output-directory.

**Comment by taihaofu** [comment]
This seems to be a known issue that when you try to stop java-tron you shutdown docker directly on k8s or use kill -9, and this lead db not revoke properly. The recommended way is to use kill -15 to stop java-tron. Now, you have to delete and resync db...

**Comment by Shrey33** [comment]
@benjaminchencobinhood can you provide me the logs ?

**Comment by benjaminchencobinhood** [comment]
> @benjaminchencobinhood can you provide me the logs ?

Sure, could you provide me an email or somewhere that I can upload the log? (about 122MB)

**Comment by Shrey33** [comment]
@benjaminchencobinhood ya sure, shrey.shah002@gmail.com

**Comment by Shrey33** [comment]
@benjaminchencobinhood the file type is unsupported, can you send the logs in a text file ?

**Comment by Shrey33** [comment]
@benjaminchencobinhood can you add the reproduction steps ?

**Comment by Shrey33** [comment]
@benjaminchencobinhood reproduction steps ?

**Comment by benjaminchencobinhood** [comment]
Sorry,I don't have specific reproduce steps. Because we deploy the docker image on k8s, the pod will automatically restart if needed.

Just hope that the fullnode can do something like "rollback some blocks", then keep syncing.

**Comment by Shrey33** [comment]
@benjaminchencobinhood you are right when I'm running fullnode and solidity node in docker on k8s the node can't sync anymore.

Can you tell me the impact ?

**Comment by benjaminchencobinhood** [comment]
I don't understand why you ask me the impact.
If a blockchain can't not sync to latest block, what it can do?

**Comment by Shrey33** [comment]
@benjaminchencobinhood Your database is corrupted. Please delete the output-directory and resync.

**Comment by benjaminchencobinhood** [comment]
Of course I know delete the output-directory and resync works. But tron team needs to provide a better solution for this issue. You can't just say "delete the output-directory and resync", for me, the response equals to "Sorry, you can't run TRON in a docker on k8s".

**Comment by zhaohong** [comment]
@benjaminchencobinhood  sorry,   Shrey33 is scam.
