### ISSUE TITLE
Build Failed on Linux

### ISSUE THREAD

**Issue by SnearK6354** [tronprotocol/java-tron#1572]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Trying to build latest Odyssey release 3.1.1.
sudo ./gradlew build

2. What did you expect to see?
BUILD SUCCESSFUL

3. What did you see instead?
![image](https://user-images.githubusercontent.com/35176703/46340618-3f758480-c636-11e8-80d4-b78bfa28d966.png)

**Comment by gregorst3** [comment]
Same here

**Comment by kookiekrak** [comment]
Seems like the maven repository is having some issues. Please manually apply this patch to your build.gradle file

https://github.com/tronprotocol/java-tron/pull/1574

**Comment by gregorst3** [comment]
Thank you @kookiekrak

**Comment by gregorst3** [comment]
Thank you @kookiekrak

**Comment by giancarlo94** [comment]
Thanks, fixed the issue for me!

**Comment by SnearK6354** [comment]
Thanks !

**Comment by SnearK6354** [comment]
If Maven url is not updated on their side, do not forget to add this change in next release :-)

Thanks again for the support.
