### ISSUE TITLE
节点同步卡在2242360

### ISSUE THREAD

**Issue by zhp1254** [tronprotocol/java-tron#1576]
为什么节点块一直不同步呢，好多天了一直出现下面这条日志，配置文件是git上的没有修改

Peer 120.79.141.222:18888: [           cb1f0537, ping     52 ms]-----------
connect time: 2018-10-08 10:42:08.114
last know block num: 2242360
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:2242361
syncBlockRequestedSize:0
unFetchSynNum:3266
syncChainRequested:NULL
blockInPorc:0
NodeStat[reput: 157(0), discover: 3/3 0/0 6/6 0/0 35ms, p2p: 1/1/1 , tron: 22/23   , tcp flow: 164128

MyHeadBlockNum: 2242360
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 771762
blockWaitToProc: 3999
blockJustReceived: 0
syncBlockIdWeRequested: 4000

**Comment by Shrey33** [comment]
@zhp1254 what is the issue here ?

**Comment by zhp1254** [comment]
when run the node for a while,  the services stop sync block, it log above info , i try it on other machine, i got the same problem and there no error log  

> @zhp1254 what is the issue here ?

**Comment by xcluo** [comment]
Same thing with me!!! how to fix and what can i do?  we are in emergency!

**Comment by taihaofu** [comment]
> Same thing with me!!! how to fix and what can i do? we are in emergency!

Please update your code to 3.1.2 release. And try again.

**Comment by xcluo** [comment]
> > Same thing with me!!! how to fix and what can i do? we are in emergency!
> 
> Please update your code to 3.1.2 release. And try again.

Return error by call grpc-gateway/master:
API -> GetNowBlock:
{"error":"unknown message type \"protocol.TriggerSmartContract\"","code":2}

**Comment by taihaofu** [comment]
> > > Same thing with me!!! how to fix and what can i do? we are in emergency!
> > 
> > 
> > Please update your code to 3.1.2 release. And try again.
> 
> Return error by call grpc-gateway/master:
> API -> GetNowBlock:
> {"error":"unknown message type "protocol.TriggerSmartContract"","code":2}

We didn't support grpc-gateway for months. Suggest to use our http api or wallet-cli to make call.

**Comment by xcluo** [comment]
> > > > Same thing with me!!! how to fix and what can i do? we are in emergency!
> > > 
> > > 
> > > Please update your code to 3.1.2 release. And try again.
> > 
> > 
> > Return error by call grpc-gateway/master:
> > API -> GetNowBlock:
> > {"error":"unknown message type "protocol.TriggerSmartContract"","code":2}
> 
> We didn't support grpc-gateway for months. Suggest to use our http api or wallet-cli to make call.

As you know,  call the API has been in HTTP by github.com/tronprotocol/grpc-gateway, so you mean Tron supply API services originally by github.com/tronprotocol/java-tron?

**Comment by xcluo** [comment]
> > > > Same thing with me!!! how to fix and what can i do? we are in emergency!
> > > 
> > > 
> > > Please update your code to 3.1.2 release. And try again.
> > 
> > 
> > Return error by call grpc-gateway/master:
> > API -> GetNowBlock:
> > {"error":"unknown message type "protocol.TriggerSmartContract"","code":2}
> 
> We didn't support grpc-gateway for months. Suggest to use our http api or wallet-cli to make call.



> > > > Same thing with me!!! how to fix and what can i do? we are in emergency!
> > > 
> > > 
> > > Please update your code to 3.1.2 release. And try again.
> > 
> > 
> > Return error by call grpc-gateway/master:
> > API -> GetNowBlock:
> > {"error":"unknown message type "protocol.TriggerSmartContract"","code":2}
> 
> We didn't support grpc-gateway for months. Suggest to use our http api or wallet-cli to make call.

Thanks so much! The problem has been resolved by to upgrade v3.1.2!

**Comment by zhp1254** [comment]
> > > > Same thing with me!!! how to fix and what can i do? we are in emergency!
> > > 
> > > 
> > > Please update your code to 3.1.2 release. And try again.
> > 
> > 
> > Return error by call grpc-gateway/master:
> > API -> GetNowBlock:
> > {"error":"unknown message type "protocol.TriggerSmartContract"","code":2}
> 
> We didn't support grpc-gateway for months. Suggest to use our http api or wallet-cli to make call.

@taihaofu 节点应该会支付grpc接口吧

**Comment by taihaofu** [comment]
> > > > > Same thing with me!!! how to fix and what can i do? we are in emergency!
> > > > 
> > > > 
> > > > Please update your code to 3.1.2 release. And try again.
> > > 
> > > 
> > > Return error by call grpc-gateway/master:
> > > API -> GetNowBlock:
> > > {"error":"unknown message type "protocol.TriggerSmartContract"","code":2}
> > 
> > 
> > We didn't support grpc-gateway for months. Suggest to use our http api or wallet-cli to make call.
> 
> @taihaofu 节点应该会支付grpc接口吧

是的，支持的。
grpc https://github.com/tronprotocol/Documentation/blob/master/中文文档/波场协议/波场钱包RPC-API.md
http https://github.com/tronprotocol/Documentation/blob/master/TRX_CN/Tron-http.md

**Comment by zhp1254** [comment]
update to 3.1.2 release
