### ISSUE TITLE
cannot build both linux and windows with error ”Content is not allowed in prolog“

### ISSUE THREAD

**Issue by luomiwhy** [tronprotocol/java-tron#1577]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

~/tron/java-tron-Odyssey-v3.1.1$ ./gradlew build
Download http://mvnrepository.com/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.pom

> Configure project :
[Fatal Error] protobuf-gradle-plugin-0.8.3.pom:1:44: Content is not allowed in prolog.

Download http://mvnrepository.com/org/sonarsource/scanner/gradle/sonarqube-gradle-plugin/2.6/sonarqube-gradle-plugin-2.6.pom
Download http://mvnrepository.com/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom

> Configure project :
[Fatal Error] sonarqube-gradle-plugin-2.6.pom:1:44: Content is not allowed in prolog.
[Fatal Error] shadow-2.0.2.pom:1:44: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java-tron'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.google.protobuf:protobuf-gradle-plugin:0.8.3.
     Required by:
         project :
      > Could not resolve com.google.protobuf:protobuf-gradle-plugin:0.8.3.
         > Could not parse POM http://mvnrepository.com/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.pom
            > Content is not allowed in prolog.
   > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
     Required by:
         project :
      > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
         > Could not parse POM http://mvnrepository.com/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom
            > Content is not allowed in prolog.
   > Could not resolve org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.6.
     Required by:
         project :
      > Could not resolve org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.6.
         > Could not parse POM http://mvnrepository.com/org/sonarsource/scanner/gradle/sonarqube-gradle-plugin/2.6/sonarqube-gradle-plugin-2.6.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

2. What did you expect to see?
编译成功

3. What did you see instead?
BUILD FAILED in 6s

**Comment by taihaofu** [comment]
please refer to https://github.com/tronprotocol/java-tron/pull/1574/files

**Comment by luomiwhy** [comment]
good, resolved
