### ISSUE TITLE
Is the Tron foundation's 33,251,807,424 TRX actually locked?

### ISSUE THREAD

**Issue by jotto** [tronprotocol/java-tron#1579]
Hello all,

After reading this blog post https://medium.com/tron-foundation/33-251-807-424-trx-were-locked-in-1000-addresses-of-tron-mainnet-feee5a5685c9 

I assumed there was some locking functionality in Tron, but I can't find it.

1. Are those 1,000 accounts actually locked, meaning impossible to withdraw from?
2. What locking functionality exists in Tron?

**Comment by jotto** [comment]
@kookiekrak it looks like the max freeze duration is only 3 days, am I looking at this wrong? https://github.com/tronprotocol/java-tron/blob/3f5eadd9993d308aeb28d3dbd84ebc227b601a71/src/main/java/org/tron/core/db/DynamicPropertiesStore.java#L188

**Comment by kookiekrak** [comment]
heh yep you're right. as long as no unfreeze is called, the balance remains frozen

**Comment by jotto** [comment]
And in the case of those 1,000 address where the 33 billion TRX was sent, I just checked 3 random ones but they were never frozen, am I correct?

* TAff8nzfnQdEwijAHK2ag2AjoZ3iqxfJTN
* TRLq2Zxdzxr6oqnsjHu9eSm5Qj2QQLHWvb
* TWT6Hzh2NDDNLkLKgSd5XNMVnsF7S8wbEf

**Comment by kookiekrak** [comment]
Yeah, the foundation's TRX aren't "frozen" locked because it would compete for available network bandwidth for other users.

They published the addresses so that users can observe the balance at any time.

**Comment by jotto** [comment]
thank you for the answers @kookiekrak

**Comment by kookiekrak** [comment]
np. feel free to email tian@tron.network or telegram @kookiekrak if you have future questions!
