### ISSUE TITLE
Are transactions created for the 32 TRX block reward?

### ISSUE THREAD

**Issue by jotto** [tronprotocol/java-tron#1580]
When I query all the blocks via the [API](https://github.com/tronprotocol/Documentation/blob/master/TRX/Tron-http.md), e.g.:

```
curl -X POST  http://127.0.0.1:8090/wallet/getblockbynum -d '{"num" : 100}'
```

and group all transactions by type:

```
11172087	TransferAssetContract
4083531	TransferContract
484831	VoteWitnessContract
165023	FreezeBalanceContract
42813	ParticipateAssetIssueContract
27404	UnfreezeBalanceContract
6976	AccountUpdateContract
2452	WithdrawBalanceContract
1038	AssetIssueContract
305	AccountCreateContract
123	WitnessUpdateContract
118	WitnessCreateContract
15	UnfreezeAssetContract
12	UpdateAssetContract
```

I don't see any transactions for the block rewards. I looked through the code and found [this](https://github.com/tronprotocol/java-tron/blob/3f5eadd9993d308aeb28d3dbd84ebc227b601a71/src/main/java/org/tron/core/db/Manager.java#L1203) call to `updateSignedWitness` which calls `adjustAllowance`, but it doesn't look like this process creates any transactions to record the newly created supply. As far as I can tell it merely increased the allowance of the account.

Is there transactional record of the 32 TRX block reward?

**Comment by jotto** [comment]
thanks @kookiekrak 

Do you know why we can't see the amount in the `WithdrawBalanceContract` transactions? It seems impossible to audit block rewards.

**Comment by kookiekrak** [comment]
it wasn't added to the protocol. the block rewards need to be calculated based on a formula, you can see which sr produced every block

**Comment by zhaohong** [comment]
@jotto  you can use getaccount api to see the allowance field

**Comment by alecalve** [comment]
You can also use `/walletsolidity/gettransactioninfobyid` to get the `withdraw_amount` for each transaction invoking `WithdrawBalanceContract`
