### ISSUE TITLE
whats wrong?

### ISSUE THREAD

**Issue by indocolabs** [tronprotocol/java-tron#1585]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

when i run build i see the following error like bellow
i dont know what should i do

2. What did you expect to see?

3. What did you see instead?

root@vps489802:/home/java-tron# ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-4.3-all.zip
...........................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-4.3-all/2c1rgv6vofd95kl0ugolfeu5r/gradle-4.3-all.zip to /root/.gradle/wrapper/dists/gradle-4.3-all/2c1rgv6vofd95kl0ugolfeu5r
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-4.3-all/2c1rgv6vofd95kl0ugolfeu5r/gradle-4.3/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Download http://mvnrepository.com/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.pom
Download http://mvnrepository.com/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom
Download http://mvnrepository.com/org/sonarsource/scanner/gradle/sonarqube-gradle-plugin/2.6/sonarqube-gradle-plugin-2.6.pom

> Configure project : 
[Fatal Error] protobuf-gradle-plugin-0.8.3.pom:1:44: Content is not allowed in prolog.
[Fatal Error] sonarqube-gradle-plugin-2.6.pom:1:44: Content is not allowed in prolog.
[Fatal Error] shadow-2.0.2.pom:1:44: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java-tron'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.google.protobuf:protobuf-gradle-plugin:0.8.3.
     Required by:
         project :
      > Could not resolve com.google.protobuf:protobuf-gradle-plugin:0.8.3.
         > Could not parse POM http://mvnrepository.com/com/google/protobuf/protobuf-gradle-plugin/0.8.3/protobuf-gradle-plugin-0.8.3.pom
            > Content is not allowed in prolog.
   > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
     Required by:
         project :
      > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
         > Could not parse POM http://mvnrepository.com/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom
            > Content is not allowed in prolog.
   > Could not resolve org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.6.
     Required by:
         project :
      > Could not resolve org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.6.
         > Could not parse POM http://mvnrepository.com/org/sonarsource/scanner/gradle/sonarqube-gradle-plugin/2.6/sonarqube-gradle-plugin-2.6.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

**Comment by sonpython** [comment]
the same to me.

it seems the link for downloading grpc-core-1.14.0 was not reachable. 

`http://mvnrepository.com/io/grpc/grpc-core/1.14.0/grpc-core-1.14.0.pom`

should be replaced by this link
`http://central.maven.org/maven2/io/grpc/grpc-core/1.14.0/grpc-core-1.14.0.pom`

**Comment by lightshine001** [comment]
Same to me
[aaron@localhost tron]$ sudo bash deploy_tron.sh 
download code from git repositorie
--2018-10-11 18:09:39--  https://raw.githubusercontent.com/tronprotocol/TronDeployment/master/main_net_config.conf
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.188.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.188.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8955 (8.7K) [text/plain]
Saving to: ‘main_net_config.conf’

100%[=========================================================================================================================================================================>] 8,955       --.-K/s   in 0s      

2018-10-11 18:09:40 (175 MB/s) - ‘main_net_config.conf’ saved [8955/8955]

Already on 'master'
HEAD is now at 419129c Merge pull request #1541 from tronprotocol/soliditynodedup
fatal: A branch named 'release' already exists.
Download http://mvnrepository.com/io/grpc/grpc-core/maven-metadata.xml
Download http://mvnrepository.com/io/netty/netty-codec-http2/maven-metadata.xml
Download http://mvnrepository.com/io/grpc/grpc-core/1.14.0/grpc-core-1.14.0.pom
[Fatal Error] grpc-core-1.14.0.pom:1:44: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/aaron/project/src/github.com/tron/FullNode/java-tron/build.gradle' line: 304

* What went wrong:
Could not determine the dependencies of task ':buildKeystoreFactoryJar'.
> Could not resolve all files for configuration ':compile'.
   > Could not resolve io.grpc:grpc-core:[1.14.0].
     Required by:
         project : > io.grpc:grpc-netty:1.14.0
      > Could not resolve io.grpc:grpc-core:[1.14.0].
         > Failed to list versions for io.grpc:grpc-core.
            > Unable to load Maven meta-data from http://mvnrepository.com/io/grpc/grpc-core/maven-metadata.xml.
               > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
   > Could not resolve io.netty:netty-codec-http2:[4.1.27.Final].
     Required by:
         project : > io.grpc:grpc-netty:1.14.0
      > Could not resolve io.netty:netty-codec-http2:[4.1.27.Final].
         > Failed to list versions for io.netty:netty-codec-http2.
            > Unable to load Maven meta-data from http://mvnrepository.com/io/netty/netty-codec-http2/maven-metadata.xml.
               > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
   > Could not resolve io.grpc:grpc-core:1.14.0.
     Required by:
         project : > io.grpc:grpc-protobuf:1.14.0
         project : > io.grpc:grpc-stub:1.14.0
         project : > io.grpc:grpc-protobuf:1.14.0 > io.grpc:grpc-protobuf-lite:1.14.0
      > Could not resolve io.grpc:grpc-core:1.14.0.
         > Could not parse POM http://mvnrepository.com/io/grpc/grpc-core/1.14.0/grpc-core-1.14.0.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
cp: cannot stat ‘/home/aaron/project/src/github.com/tron/FullNode/java-tron/build/libs/FullNode.jar’: No such file or directory
FullNode killed
starting FullNode

run FullNode failed, please check your parameters
bash: __vte_prompt_command: command not found
