### ISSUE TITLE
on printblockchain, the timestamp of first block shows 1969. Is this related in some way to the genesis block?

### ISSUE THREAD

**Issue by ajayt6** [tronprotocol/java-tron#16]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

printblockchain

2. What did you expect to see?
current times in blockchain

3. What did you see instead?

Block {
	timestamp=1969/12/31 18:00:00, 
	parentHash=, 
	hash=92cc7b05be081109f2245a3cca1a214222751a598abae447df636932b2a0b855, 
	nonce=, 
	difficulty=2001, 
	number=0
}
is this in some way related to the genesis block? Is that the standard for the very first block?

**Comment by sasaxie** [comment]
Yes, it's default genesis block configuration.  We will support it by `genesis.json` or others.

https://github.com/tronprotocol/java-tron/blob/7325a77267764720fc6fa29545bcbef19edaba3e/src/main/java/org/tron/core/BlockUtils.java#L82

**Comment by ajayt6** [comment]
Thanks!

**Comment by sasaxie** [comment]
I am glad that I can help.:handshake:
