### ISSUE TITLE
FreezeBalance2 grpc api frozenDuration could not  set other number except 3

### ISSUE THREAD

**Issue by zhp1254** [tronprotocol/java-tron#1607]
FreezeBalance2 grpc api frozenDuration could not  set other number except 3
i got an error when set it 2 or 4
**error code**:
CONTRACT_VALIDATE_ERROR
**error msg:**
frozenDuration must be less than 3 days and more than 3 days

**Comment by taihaofu** [comment]
This is expected by design. Only 3 is valid. It may be changed in future release, but we prefer to keep it as 3 for now. https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Protocol/Freezing%26Voting_Update.MD
