### ISSUE TITLE
cannot sync past block3244926

### ISSUE THREAD

**Issue by frank077** [tronprotocol/java-tron#1619]
cannot sync past block 3244926 tried 4 times with 2 different servers 
32 cores 64GB 2 TB SAS
i have deleted output directory and resynced but stops at the same block every time

Peer 95.179.152.13:18888: [           88ca0b78, ping    194 ms]-----------
connect time: 2018-10-18 05:42:06.212
last know block num: 3244924
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:3999
syncToFetchSizePeekNum:3244926
syncBlockRequestedSize:0
unFetchSynNum:46265
syncChainRequested:NULL
blockInPorc:1
NodeStat[reput: 189(185), discover: 1/1 0/0 8/8 0/0 183ms, p2p: 1/1/1 , tron: 16/14   , tcp flow: 164184

Peer 79.137.68.78:18888: [           ca303f1c, ping    220 ms]-----------
connect time: 2018-10-18 05:42:06.233
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
unFetchSynNum:0
syncChainRequested:NULL
blockInPorc:0
NodeStat[reput: 157(164), discover: 1/1 1/1 8/8 0/0 209ms, p2p: 1/1/1 , tron: 14/15   , tcp flow: 680

Other connected peers
============

05:44:20.632 INFO  [pool-6-thread-1] [PeerClient](PeerClient.java:77) connect peer 54.36.226.194 18888 fa64cf4f15dca16ae748f27a2861647a56be3db0807348b08720743d2f55601f9ac128664f897c323e894e533dfb57e8c0c725c82c99c809dc4ea25b443b2479
05:44:20.633 INFO  [pool-6-thread-1] [PeerClient](PeerClient.java:77) connect peer 34.253.187.192 18888 a8e15e24a631999215439ede6b191fb30de5bcb486ac2b6e7942fde8ffff064199c4334aca34b47dc39bf02e8f0459b8c4e33ce66a5b22e8926a165625d4d428
05:44:20.812 INFO  [TronJClientWorker-1] [HandshakeHandler](HandshakeHandler.java:74) channel active, /54.36.226.194:18888
05:44:20.817 INFO  [TronJClientWorker-2] [HandshakeHandler](HandshakeHandler.java:74) channel active, /34.253.187.192:18888
05:44:20.822 INFO  [TronJClientWorker-8] [MessageQueue](MessageQueue.java:106) Receive from /173.212.201.195:18888, type: P2P_PONG

05:44:20.832 INFO  [TronJClientWorker-4] [MessageQueue](MessageQueue.java:106) Receive from /79.137.68.78:18888, type: P2P_PONG

05:45:24.139 INFO  [TronJClientWorker-7] [MessageQueue](MessageQueue.java:106) Receive from /159.69.46.112:18888, type: P2P_PING

05:45:24.139 INFO  [TronJClientWorker-3] [MessageQueue](MessageQueue.java:106) Receive from /88.208.34.114:18888, type: P2P_PING

05:45:24.139 INFO  [TronJClientWorker-7] [MessageQueue](MessageQueue.java:94) Send to /159.69.46.112:18888, type: P2P_PONG
 
05:45:55.679 WARN  [sendTimer] [MessageQueue](MessageQueue.java:142) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /79.133.37.14:18888.
05:46:58.603 INFO  [P2pPingTimer] [MessageQueue](MessageQueue.java:94) Send to /88.208.34.114:18888, type: P2P_PING
 
05:45:10.831 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:140) -------- active connect channel 7
05:45:24.139 INFO  [TronJClientWorker-3] [MessageQueue](MessageQueue.java:94) Send to /88.208.34.114:18888, type: P2P_PONG
 
05:51:24.759 INFO  [P2pPingTimer] [MessageQueue](MessageQueue.java:94) Send to /145.239.232.78:18888, type: P2P_PING
 17:06:02.632 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:140) -------- active connect channel 0
tail: cannot open 'tail' for reading: No such file or directory

==> logs/tron.log <==
17:05:20.923 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:141) -------- passive connect channel 0
17:05:42.112 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:142) -------- all connect channel 0
17:05:42.112 WARN  [sendTimer] [MessageQueue](MessageQueue.java:142) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /159.69.46.112:18888.
17:05:42.113 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:163) Peer stats:
Active peers
============
Other connected peers
============

17:06:02.632 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:140) -------- active connect channel 0
 Wait class org.tron.common.overlay.message.PongMessage timeout.
==> logs/tron.log <==
17:06:02.632 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:141) -------- passive connect channel 0

==> logs/tron.log <==
17:06:02.632 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:141) -------- passive connect channel 0

==> logs/tron.log <==
17:08:52.189 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:142) -------- all connect channel 0

==> logs/tron.log <==
17:08:52.189 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:142) -------- all connect channel 0

==> logs/tron.log <==
17:10:01.327 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:163) Peer stats:
Active peers
============
Other connected peers
============

==> logs/tron.log <==
17:10:01.327 INFO  [pool-7-thread-1] [SyncPool](SyncPool.java:163) Peer stats:
Active peers
============

**Comment by bitcodernull** [comment]
i have stopped at 3307927

**Comment by frank077** [comment]
solved my problem by downloading the latest file /java-tron.git and rebuilt   fullnode.jar 
copied the file into my folder  and synced from scratch
