### ISSUE TITLE
No URL validation for Tokens

### ISSUE THREAD

**Issue by nfleury** [tronprotocol/java-tron#1620]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Checked some urls of some tokens

2. What did you expect to see?
Valid URLs for the tokens

3. What did you see instead?
Invalid URLs for many tokens . Some of them doesn't contain any protocol (http://), some are just basic emails, and others only contain the protocol part or nothing related to an URL

Some examples:

https://www.trxplorer.io/token/SugarCaneCoin
https://www.trxplorer.io/token/TronTips
https://tronscan.org/#/token/TRONIX/TYE4LK3LPZJUKtK9qEPuxPCYFStoY3JYd7

**Comment by nfleury** [comment]
@Shrey33 I don't have any logs or screenshot. The fact that these type of url exists on the blockchain (see urls) shows that there is currently no validation, but I don't know if that was intentional to have a loose validation like that.

After looking at the code that should validate the URL (TransactionUtil::validUrl) I see some very basic validation only on length right now, but also a comment with  "// other rules." so maybe it is planned to add more strict rules :D

**Comment by zhaohong** [comment]
will not add this validater at protocol  layer.

**Comment by nfleury** [comment]
Ok thanks for the clear answer @zhaohong
