### ISSUE TITLE
I would like to help with the translation for Spanish language 

### ISSUE THREAD

**Issue by joelalcan** [tronprotocol/java-tron#164]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

**Comment by zhaohong** [comment]
thanks! @HaoqiZhao will contact you later.

**Comment by HaoqiZhao** [comment]
@joelalcan How can I reach you in a less exposed & more instantaneous way？Any email or live chat tools?

**Comment by joelalcan** [comment]
You can contact me email base: joelalcan@gmail.com

**Comment by ybhgenius** [comment]
Hello,

Thanks for your participation.

Please check this link:

https://crowdin.com/project/trondocs

You can translate or correct relevant texts through this link.

We will reward you according to your contribution.

Best Regards

Boheng Yang

**Comment by Rovak** [comment]
Closing this issue as translations are now being done through Crowdin. Follow the link above to contribute your translations.
