### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by kaankozan** [tronprotocol/java-tron#1646]
Please answer these questions before submitting your issue. Thanks!

My error this and not sync

java.lang.OutOfMemoryError: GC overhead limit exceeded

What is a problem?

**Comment by Shrey33** [comment]
@kaankozan can you provide the logs and reproduction steps ?

**Comment by zhaohong** [comment]
what's your jvm  heap size ?   -xmx.   It's seems that  there are not enough heap memory.

**Comment by kaankozan** [comment]
https://github.com/tronprotocol/java-tron/issues/1668#issuecomment-435175691
