### ISSUE TITLE
transaction confirmed but the owner address balance do not change

### ISSUE THREAD

**Issue by zhp1254** [tronprotocol/java-tron#1649]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
i do not know is the transaction is success
transaction hash :  954206e7c889abf971945f6f1f0131ebae55451a2666814659c4b6a66d5fd2a8
block chain https://www.trxplorer.io/tx/954206e7c889abf971945f6f1f0131ebae55451a2666814659c4b6a66d5fd2a8

3. What did you see instead?
as the image show: the transaction is confirmed but the owner address blanace not changed
and then transaction block is 3528501,   the now block is 3531405

![image](https://user-images.githubusercontent.com/18046237/47557647-cd960f80-d943-11e8-84dd-71cbd4e8ccb6.png)
![image](https://user-images.githubusercontent.com/18046237/47557727-0635e900-d944-11e8-92b4-2c2fcc3d7b9a.png)

**Comment by nfleury** [comment]
@zhp1254 This issue is not related to java-tron, but trxplorer.io - I am currently working on fixing this issue, you can close this issue here an reopen it here if you want to : https://github.com/trxplorer/explorer/issues

**Comment by zhaohong** [comment]
@nfleury  thanks.
