### ISSUE TITLE
The test_ev2 branch is recommended to add the contract address filter configuration

### ISSUE THREAD

**Issue by weijinsun** [tronprotocol/java-tron#1653]
When I deployed the event node myself, I wanted to save only the contract events I was interested in, which would save space and improve query efficiency

**Comment by weijinsun** [comment]
> please provide more info , thanks.
Mongodb will save all events, but I want to only save my own contract events, so I hope to add a filter configuration.

**Comment by weijinsun** [comment]
> please provide more info , thanks.

Mongodb will save all events, but I want to only save my own contract events, so I hope to add a filter configuration.

**Comment by zhaohong** [comment]
test_ev2 branch is not released branch and the feature in test_ev2 is not support by core team.
