### ISSUE TITLE
Address SonarQube Blocker, Critical, Major Issues

### ISSUE THREAD

**Issue by bpetridis** [tronprotocol/java-tron#1692]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Ran the current develop branch through Sonarqube scanner to evaluate the 101, code quality

2. What did you expect to see?

No Blocker, Major or Critical issues

3. What did you see instead?

Lots of Blocker, Major and Critical issues. 
![2018-11-08_8-30-46](https://user-images.githubusercontent.com/41990123/48165222-ae7a8300-e330-11e8-88e7-a408bf57f724.jpg)

**Comment by zhaohong** [comment]
we are also using sonarcloud,  so we are continuous improving the quality of code.

**Comment by bpetridis** [comment]
Thanks for the response. God speed cleaning it up. I've setup my local dev env so will see if I can contritube some of the fixes myself time permitting. Thanks mate 👍

**Comment by zhaohong** [comment]
@bpetridis  welcome

**Comment by bpetridis** [comment]
Hi - note have been actively re-scanning and it seems to have gotten much better in the last couple months so well done on that front :-)
https://sonarcloud.io/dashboard?id=BillPTron
