### ISSUE TITLE
Run a full node connecting Shasta Testnet

### ISSUE THREAD

**Issue by jinshunjing** [tronprotocol/java-tron#1694]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I ran a full node with below config trying to connect Shasta testnet:
...
  p2p {
    version = 20180911
  }

  active = [
"47.254.45.208:18888",
"47.90.240.239:18888",
"47.88.55.186:18888",
"47.89.188.162:18888",
"148.251.42.172:18888",
"47.254.33.129:18888",
"47.254.75.152:18888",
"47.254.73.154:18888",
"47.90.208.195:18888"
  ]
...
seed.node = {
  ip.list = [
"47.254.146.147:18888",
"47.254.18.49:18888"
  ]
}
...
  witnesses = [
    {
      address: TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY,
      url = "http://tronstudio.com",
      voteCount = 10000
    }
  ]
...

2. What did you expect to see?
I expect the full node can connect to Shasta testnet and sync the blocks.

3. What did you see instead?
I only saw some PING/PONG traffics. Seems I'm connecting the unnamed testnet (current height is 1557350):

14:27:45.429 INFO  [pool-6-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:594) LocalNode stats:
MyHeadBlockNum: 0
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 1557300
blockWaitToProc: 3998
blockJustReceived: 0
syncBlockIdWeRequested: 4000

14:27:46.260 INFO  [TronJClientWorker-3] [MessageQueue](MessageQueue.java:106) Receive from /148.251.42.172:18888, type: P2P_PING
14:27:46.260 INFO  [TronJClientWorker-3] [MessageQueue](MessageQueue.java:94) Send to /148.251.42.172:18888, type: P2P_PONG
14:27:47.376 INFO  [P2pPingTimer] [MessageQueue](MessageQueue.java:94) Send to /47.90.240.239:18888, type: P2P_PING
14:27:47.619 INFO  [TronJClientWorker-1] [MessageQueue](MessageQueue.java:106) Receive from /47.90.240.239:18888, type: P2P_PONG
14:27:52.830 INFO  [P2pPingTimer] [MessageQueue](MessageQueue.java:94) Send to /47.254.73.154:18888, type: P2P_PING
14:27:52.847 INFO  [TronJClientWorker-2] [MessageQueue](MessageQueue.java:106) Receive from /47.254.73.154:18888, type: P2P_PING
14:27:52.847 INFO  [TronJClientWorker-2] [MessageQueue](MessageQueue.java:94) Send to /47.254.73.154:18888, type: P2P_PONG
14:27:52.847 INFO  [TronJClientWorker-3] [MessageQueue](MessageQueue.java:106) Receive from /47.254.75.152:18888, type: P2P_PING
14:27:52.847 INFO  [TronJClientWorker-3] [MessageQueue](MessageQueue.java:94) Send to /47.254.75.152:18888, type: P2P_PONG
14:27:52.883 INFO  [TronJClientWorker-6] [MessageQueue](MessageQueue.java:106) Receive from /47.254.33.129:18888, type: P2P_PING
14:27:52.884 INFO  [TronJClientWorker-6] [MessageQueue](MessageQueue.java:94) Send to /47.254.33.129:18888, type: P2P_PONG
14:27:52.902 INFO  [TronJClientWorker-4] [MessageQueue](MessageQueue.java:106) Receive from /47.88.55.186:18888, type: P2P_PING
14:27:52.903 INFO  [TronJClientWorker-4] [MessageQueue](MessageQueue.java:94) Send to /47.88.55.186:18888, type: P2P_PONG

**Comment by tmao1129** [comment]
@jinshunjing  Please join us in the TRON Developers Discord channel at https://discordapp.com/invite/GsRgsTD. Thanks.

**Comment by kookiekrak** [comment]
@UnforgivenZZZ update this plz

**Comment by DNK90** [comment]
@UnforgivenZZZ can we do this now?

**Comment by trnhgquan** [comment]
@jinshunjing Hello, did you successfully run a full node  connect to Shasta?

**Comment by sc0Vu** [comment]
@tycm4109 is this official discord channel?

**Comment by MannGates** [comment]
> @tycm4109 is this official discord channel?

Hi be cautious, this is TRON developers discord official channel: https://discord.gg/sNpQbmwJ
