### ISSUE TITLE
Question: Kotlin

### ISSUE THREAD

**Issue by khuezy** [tronprotocol/java-tron#17]
How does the team feel about using Kotlin?

**Comment by sasaxie** [comment]
Personally, I think Kotlin can do it well, but we still use Java for some time in the future.

**Comment by ac-opensource** [comment]
I was going to ask this too, I feel like we can get a lot of community support if we use kotlin

**Comment by sasaxie** [comment]
Maybe will, I will discuss this with I team. Thank you everyone.

**Comment by Rovak** [comment]
If you are considering other languages then also please consider I've made a small start on converting java classes to scala in [this repository](https://github.com/Rovak/scala-tron/tree/scala/src/main/scala/org/tron) to experiment if i could make it work with sbt.

**Comment by staticmukesh** [comment]
We can try `golang` too.
