### ISSUE TITLE
SmartContract-there are no details information for TRX 20 transfer

### ISSUE THREAD

**Issue by rainysiu** [tronprotocol/java-tron#1709]
While transfer directly by TRX20’s smart contract to send transaction 
https://tronscan.org/#/transaction/26c44b2a5407d04beaf0605ef8e9d813914a04a181ae5a72f922eb21223231bf
There are no details information about this transaction
We need : Token’s name, from, to, amount, symbol, decimal and so on.

Please refer to the TRX20’s standard definition

**Comment by taihaofu** [comment]
@rainysiu , we already implemented related part in java-tron. Tronscan team will work on the rest part of it.

**Comment by zhaohong** [comment]
this is a requirement for tronscan ,   java-tron alreay support his. 
please submit the requirement to tronscan github.
