### ISSUE TITLE
The amount of TRX internal-transaction in smart contract  is not shown

### ISSUE THREAD

**Issue by rainysiu** [tronprotocol/java-tron#1710]
The amount of TRX internal-transaction in smart contract  is not shown
https://tronscan.org/#/transaction/a697b50e3f464d3dab695f654cea40c03c480d337010b7bf72f2f99ca35c6cb5

If transfer trx in smart contact, the amount of trx isn’t shown
If there are several TRX transfer transactions, please show all of them

**Comment by taihaofu** [comment]
@rainysiu , Thank you for your question. This will be released in Odyssey-3.2 at the end of this month. Now it is in the testing stage.

**Comment by zhaohong** [comment]
@taihaofu please refer this to release node, thanks
