### ISSUE TITLE
The amount of TRX20 internal-transaction in smart contract is not shown on tronscan

### ISSUE THREAD

**Issue by rainysiu** [tronprotocol/java-tron#1711]
The amount of TRX20 internal-transaction in smart contract is not shown on tronscan
https://tronscan.org/#/contract/TBHN6guS6ztVVXbFivajdG3PxFUZ5UXGxY/events

If transfer trx20 in smart contact, the amount of trx20 isn’t shown
If there are several TRX20 transfer transactions, please show all of them

*You can get events data by the interface  getTransactionInfoById

**Comment by zhaohong** [comment]
when #1710 finished , tronscan team can do this.

**Comment by zhaohong** [comment]
please submit the tronscan requirement to tronscan github, thanks.

**Comment by jeancky** [comment]
Tron scan has support this feature now
