### ISSUE TITLE
I would like to help translating whitepaper, website etc. to German and Turkish

### ISSUE THREAD

**Issue by DrKaradenizli** [tronprotocol/java-tron#174]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
No errors 🗡 

2. What did you expect to see?

3. What did you see instead?

**Comment by zhaohong** [comment]
thanks!      @HaoqiZhao  will contact you later.

**Comment by HaoqiZhao** [comment]
@DrKaradenizli How can I reach you in a less exposed & more instantaneous way？Any email or live chat tools?

**Comment by DrKaradenizli** [comment]
@HaoqiZhao Just throw a mail to trabzonlu_styler_ 61@hotmail.de :)

**Comment by ybhgenius** [comment]
Hello,

Thanks for your participation.

Please check this link:

https://crowdin.com/project/trondocs

You can translate or correct relevant texts through this link.

We will reward you according to your contribution.

Best Regards

Boheng Yang

**Comment by Rovak** [comment]
Closing this issue as translations are now being done through Crowdin. Follow the link above to contribute your translations.
