### ISSUE TITLE
The transaction type "UpdateSettingContract" is missing.

### ISSUE THREAD

**Issue by shequ123** [tronprotocol/java-tron#1777]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
When I using Tron API (HTTP)
getTransaction("4fd9098bdb223afffd749b57080ae75edf4af7eb14ee4fe835279619c2a67600");
I didn't get any information about the contract.
only
```
{ ret: [ { contractRet: 'SUCCESS' } ],
  signature:
   [ '0a4dc4624d7873dc98b30ed63f4696d5f99ed410a1398f704aeb367eb4ac87d33b6e596a07a2f6ab34b756aca3bffbdbf66e58dfc6371ef77e8b55abf2c9ea8d01' ],
  txID: '4fd9098bdb223afffd749b57080ae75edf4af7eb14ee4fe835279619c2a67600',
  raw_data:
   { contract: [ [Object] ],
     ref_block_bytes: 'd01a',
     ref_block_hash: '7989d6d516547b99',
     expiration: 1540335072000,
     timestamp: 1540335013052 } }
```
and the Object:
```
{ parameter:
   { type_url: 'type.googleapis.com/protocol.UpdateSettingContract' },
  type: 'UpdateSettingContract' }
```

2. What did you expect to see?
the correct information of the contract.

3. What did you see instead?
{ type_url: 'type.googleapis.com/protocol.UpdateSettingContract' },
  type: 'UpdateSettingContract' }

**Comment by taihaofu** [comment]
Hi, @shequ123 . Do you still have the same issue? Are you using TronWeb or just our http api?
I try this api on my local environment. And after I trigger a update setting contract. Use gettransactionbyid interface to query my transaction, I can successfully get :  

        {
              "ret":[{"contractRet":"SUCCESS"}],
              "signature":["ea5f0f310fbfcbe2cba3eeb94719e404b9e3880c97a71f2cda9e64272f537c2b59ab741bd8c26540d39d545c103f99c65060b09242628b3e56cf96e10dbb146600"],"txID":"cc5a6b48325ed31ab40f4f8bf1f187f5588b7fdef6d64df95901458b04c03fdd",
              "raw_data":{
                "contract":
                    [{"parameter":{"value":{"consume_user_resource_percent":30,"owner_address":"41881999bf04b401b6ecf4d0cb91374d7353602732","contract_address":"410d553bac872cf2eae4b4177b83ccaaecd7b80ef5"},
                "type_url":"type.googleapis.com/protocol.UpdateSettingContract"},
                "type":"UpdateSettingContract"}],
                "ref_block_bytes":"00f0",
                "ref_block_hash":"b7500caae6a057c1",
                "expiration":1543809978000,
                "timestamp":1543809920735
              }
        }

Is this what you expected to see? 
Please let me know if you still have the question.


Thanks.

**Comment by taihaofu** [comment]
Hi, I get your point. I query the same transaction id you are using and get your output. The reason is the node you are using do not have the latest code contain update setting contract decoder. Connecting to a node contains the latest Odyssey_v3.2 code you would be able to get it. Try this node:
47.89.244.139.

"contract":[  
         {  
            "parameter":{  
               "value":{  
                  "owner_address":"413109d0a8930b31bb0c0fe67b0373862deed3788e",
                  "contract_address":"4112bad7f08c61bfd1d94c2f7e0a5695a6faf3173e"
               },
               "type_url":"type.googleapis.com/protocol.UpdateSettingContract"
            },
            "type":"UpdateSettingContract"
         }
      ],

**Comment by shequ123** [comment]
Thanks, that worked :)
