### ISSUE TITLE
about backups.trongrid.io

### ISSUE THREAD

**Issue by benjaminchencobinhood** [tronprotocol/java-tron#1781]
The question is about https://backups.trongrid.io

Since the website provide links to download fullnode and solidity database,
could you please add a link point to the latest fullnode and solidity? 
So that I don't need to parse the website to get the latest data.

**Comment by atomlab** [comment]
I can't get latest release
```
$ curl -I  https://backups.trongrid.io/FullNode-latest-output-directory.tgz
HTTP/2 404
date: Sun, 15 Sep 2019 13:35:20 GMT
content-type: text/html; charset=utf-8
content-length: 176
server: nginx/1.12.2
x-powered-by: Express
content-security-policy: default-src 'none'
x-content-type-options: nosniff
```

Only specific snapshot

```
$ curl -I https://fullnode-backups-2.s3-eu-central-1.amazonaws.com/FullNode-12761299-3.6.1-output-directory.tgz
HTTP/1.1 200 OK
x-amz-id-2: cLCgJVPnUTpju0sX2DEWk2SizD5un8E1ZqKtT1jmmV+t8Hp1qMtuuKM4UGtfr2mtPvAOyrwc9jc=
x-amz-request-id: 1B9687BD02DD3341
Date: Sun, 15 Sep 2019 13:36:42 GMT
Last-Modified: Sun, 15 Sep 2019 06:55:46 GMT
ETag: "82eec670f7ce3f8891748c5c05d92863-7928"
Accept-Ranges: bytes
Content-Type: application/x-tar
Content-Length: 266001079488
Server: AmazonS3
```

Can you add latest snapshot symlink?

**Comment by jiangyy0824** [comment]
@atomlab 
You can find the latest snapshot here:
America: https://backup.trongrid.io/ 
China: http://47.89.178.46/

**Comment by atomlab** [comment]
thanks for response, but I found solution for automatization to get latest release.  Each repository contain XML file. It easy parsing.

https://fullnode-backups.s3-us-west-2.amazonaws.com/
