### ISSUE TITLE
geteventbytransactionid  return null array

### ISSUE THREAD

**Issue by bitcodernull** [tronprotocol/java-tron#1791]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

i want to get the trc20 internal transfer from my mode
i use the interface :  getEventByTransactionid, but return null array.

2. What did you expect to see?
i want to get the events

3. What did you see instead?

null array

**Comment by zhaohong** [comment]
@taihaofu

**Comment by taihaofu** [comment]
Hi, @bitcodernull. Currently we don't provide getEventByTransactionid interface in Java-tron. Which branch are you using for test?
