### ISSUE TITLE
How to get TRC20 token balance of an account

### ISSUE THREAD

**Issue by jooyyy** [tronprotocol/java-tron#1805]
There is no direct way to get TRC20 token balance for an account;
I also try to trigger smart contract and call "func balanceof(address)", but get "error other error : cannot call constant method" in the end.

**Comment by taihaofu** [comment]
Hi, how do you call the balanceOf function? Http/rpc api? Or wallet-cli, TronWeb, tronstudio? Can you please provide more specific way?

Normally what you should do is use trigger contract  and call "balanceOf(address) <address>" on a constant call supported fullnode, such as 54.236.37.243. 

Using wallet-cli you can use: triggercontract contractaddress balanceOf(address) "youraddress
" false 1000000000 0 0 #

**Comment by jooyyy** [comment]
> Hi, how do you call the balanceOf function? Http/rpc api? Or wallet-cli, TronWeb, tronstudio? Can you please provide more specific information?
> 
> Normally what you should do is use trigger contract and call "balanceOf(address) <address>"on a constant call supported fullnode, such as 54.236.37.243.
> 
> With wallet-cli you can use: triggercontract contractaddress balanceOf(address) "youraddress
> " false 0 0 0 #
> And it works for me to check mainnet result.

Thank u, i get a right way by capture package from TronLink.  Just trigger contract it works!

**Comment by zk19862018** [comment]
+
