### ISSUE TITLE
Solidity node syncing performance.

### ISSUE THREAD

**Issue by benjaminchencobinhood** [tronprotocol/java-tron#1820]
I had upgrade my node to v3.2.0.
However I found my solidity node performance is not good.

When tps is more than 25 (about 75 tx in a block), the solidity node can not catch up to the latest block. It only sync less than 10 blocks per minute when the block contains a lot of tx.
 
Seems that building the index of solidity database slow down the solidity syncing.I need the getTransacitonbyID so I can't turn off the index...
Also I already allocate more than 4G ram to ensure it won't trigger OOM killer.

Any solution?

**Comment by zhaohong** [comment]
hi , in 3.2.2
the soliditynode and fullnode will be merged in one node.

**Comment by chrisc93** [comment]
So do we put the fullnode data in the solidity node directory too? I downloaded a backup from yesterday but the wallet-cli is not moving past block 13458947 for me.

**Comment by jiangyy0824** [comment]
@chrisc93 Solidity node isn't suggested. Make sure you have connected to the fullnode with wallet-cli. Please open an new issue and list your error log and related configure.
