### ISSUE TITLE
Can not get events of internal-transaction

### ISSUE THREAD

**Issue by emn178** [tronprotocol/java-tron#1821]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Call contract A, A call contract B, B emits an event. 
Try to use tronWeb.getEventResult and tronWeb.getEventByTransactionID.

2. What did you expect to see?
It should return events.

3. What did you see instead?
It return empty.

environment is shasta

**Comment by jeancky** [comment]
The tron scan has supported this feature.
