### ISSUE TITLE
The node won't work with 1 core

### ISSUE THREAD

**Issue by sullof** [tronprotocol/java-tron#1832]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Run a private network on a VM with only 1 core.

2. What did you expect to see?

It should work.

3. What did you see instead?

It does not work.

If you look at the code at 
https://github.com/tronprotocol/java-tron/blob/develop/src/main/java/org/tron/core/config/args/Args.java#L712

You see where the problem is. I think it should be something like:

```
INSTANCE.validateSignThreadNum = 
    config.hasPath("node.validateSignThreadNum") 
    ? config.getInt("node.validateSignThreadNum") 
    : Runtime.getRuntime().availableProcessors() > 1 
    ? Runtime.getRuntime().availableProcessors() / 2 
    : 1;
```

**Comment by zhaohong** [comment]
thanks,   should process this more carefully.

**Comment by Shrey33** [comment]
Can you tell the impact ?

**Comment by sullof** [comment]
Honestly, I don't know. 
But since I have been contacted by three people with the same issue on Discord, maybe the problem has more impact than what we can think.
Consider that those people were trying, in different ways, to create their own private network, 2 of them using Tron Quickstart, the other installing and running his own nodes.

BTW, the solution I proposed above worked in those cases but I don't know if can create any issues in other situations, so I expect that you find the optimal solution.
Thanks anyway.

**Comment by zhaohong** [comment]
@sullof  hi, thanks! I think you can make a pr for this.
