### ISSUE TITLE
TRC10 access from smart contract

### ISSUE THREAD

**Issue by k06a** [tronprotocol/java-tron#1859]
I see Odissey 3.2 have this ability but see nothing in documentation

**Comment by ithinker1991** [comment]
You can refer to this doc
https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Virtual_Machine/TRC10_IN_SMARTCONTRACT.MD

**Comment by k06a** [comment]
Thanks, just implemented missing `sendToken` library: https://gist.github.com/k06a/71bdf3e8ea553e4086b50b7ba0a7a171

**Comment by k06a** [comment]
@ithinker1991 do `transferToken` provide 2300 energy exactly as `transfer`? Is this functionality accessible from Solidity Assembly?
