### ISSUE TITLE
Transactions received by an address /walletextension/gettransactionstothis

### ISSUE THREAD

**Issue by WalkerBuldog** [tronprotocol/java-tron#1867]
1. What did you do?
Make server as here
https://github.com/tronprotocol/Documentation/blob/master/TRX/Solidity_and_Full_Node_Deployment_EN.md
curl as

 curl -X POST  http://127.0.0.1:8091/walletsolidity/getaccount -d '{"address": "41E552F6487585C2B58BC2C9BB4492BC1F17132CD0"}'

curl -X POST  http://127.0.0.1:8091/walletsolidity/gettransactionbyid -d '{"value" : "35d006ad12e91e6672c1c4f4a1c284910d925a9740ac2f24f710d06cdb7d5ffc"}'

its work normal.

But when I try get

curl -X POST http://127.0.0.1:8091/walletextension/gettransactionstothis -d '{"account" : {"address" : "41E552F6487585C2B58BC2C9BB4492BC1F17132CD0"}, "offset": 0, "limit": 10}'

get this 

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 405 HTTP method POST is not supported by this URL</title>
</head>
<body><h2>HTTP ERROR 405</h2>
<p>Problem accessing /walletextension/gettransactionstothis. Reason:
<pre>    HTTP method POST is not supported by this URL</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>

expect to see 
at least 

{ }

**Comment by alexkvak** [comment]
@sullof could you provide some information about this issue? 
Is it planned to be fixed?

**Comment by sullof** [comment]
@alexkvak I don't work on java-tron. That said, I suspect that that is not an issue with java-tron.
Since that API can take the entire resources for even 2 seconds, we disabled the walletextension api on TronGrid because was causing crashes on the service. If you need it that API, you must use your own solidity node.

**Comment by sullof** [comment]
I don't work on java-tron. Is that an issue with Tron Quickstart or with your own node?

**Comment by alexkvak** [comment]
@sullof oh, sorry. This issue only on full node. QuickStart works like a charm!

**Comment by seelin** [comment]
I had the same error in my node too,How do I solve it?

**Comment by yopoing** [comment]
我也遇到这个问题，没有解决办法了吗？只有自己同步数据来做查询交易历史记录的接口了么？

**Comment by jiangyy0824** [comment]
This api is desigined for solidity node. It seems that you post the query to fullnode. Please check again. Thanks!

**Comment by DSalko** [comment]
> This api is desigined for solidity node. It seems that you post the query to fullnode. Please check again. Thanks!

I'm new to Tron. Shouldn't Fullnode support everything Solidity node supports?

**Comment by phoenix8918** [comment]
when signing wallet/gettransactionsign  method , i am getting scalar not in the interval[n, n-1] issue.please help me to fix this issue.

**Comment by vivian-kang** [comment]
> when signing wallet/gettransactionsign method , i am getting scalar not in the interval[n, n-1] issue.please help me to fix this issue.

It is not suggest to use this api except running own node, signing transaction offline is a good choice, please refer to this doc: https://developers.tron.network/docs/make-transaction-locally. 
If you are running your own node, please refer to the guide : https://developers.tron.network/reference/walletgettransactionsign-1   or please provide detailed error information, thanks.

**Comment by amirali2121333** [comment]
Hi, I get the same error in Ethereum transfer
scalar is not interval
please guide me
