### ISSUE TITLE
synchronization failed

### ISSUE THREAD

**Issue by Ye841679636** [tronprotocol/java-tron#1868]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

two super node data synchronization

2. What did you expect to see?

two super nodes should sync blocks normally

3. What did you see instead?

I want to deploy two super nodes locally. I can only synchronize the first two pieces of information during the process of synchronizing data. Then I can report the error ValidateScheduleException can explain?

**Comment by ithinker1991** [comment]
Could you provide more infomation about this, like logs and your config
