### ISSUE TITLE
unable to emit events with array as parameter

### ISSUE THREAD

**Issue by oartemis26** [tronprotocol/java-tron#1870]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

contract

```
pragma solidity ^0.4.23;
contract testArrEvent {
    
    event testEvent(uint8[2] cards);
    
    function emitArray() public {
        uint8[2] memory cards = [uint8(3), 5];
        emit testEvent(cards);
    }
}
```

tronweb

```
let abi = [{"anonymous":false,"inputs":[{"indexed":false,"name":"cards","type":"uint8[2]"}],"name":"testEvent","type":"event"},{"constant":false,"inputs":[],"name":"emitArray","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}];

let contract = tronWeb.contract(abi,"41f8aee5fe7da5f0f7c99485f7fb00582d2f9d36d5");

contract.testEvent().watch(function(err, res) {
    if (err)
        console.log("error " + err);
    console.log('eventResult:', res);
});

let args = {
    freeLimit:1000,
    callValue:0,
    shouldPollResponse: false,
}

contract.emitArray().send(args, function(err, res) {
    if (err)
        console.log("error " + err);
    console.log('Result:', res);
});
```

After I execute the scripts to trigger contracts function on shasta test network, it return the transaction id `f4fdf9a4251aa7a5b0116bb62341e75db24cdd7acb087e6d1da80396fa85978b`, and nothing else is printed on console.

I checked the transaction on shasta tronscan, it shows that the transaction is executed and comfirmed.
https://shasta.tronscan.org/#/transaction/f4fdf9a4251aa7a5b0116bb62341e75db24cdd7acb087e6d1da80396fa85978b

But When I check events of the contract, no event is shown.
https://shasta.tronscan.org/#/contract/TYe86neVHvzfd7qGax3fFG5HmNyTPjEJvj/events

2. What did you expect to see?

- tronweb event watch should return the event and print on console
- events should be shown on tronscan.

3. What did you see instead?

event info is neither returned by tronweb nor shown in tronscan.

**Comment by sullof** [comment]
@oartemis26 That is a problem with TronGrid. I have just replicated it and we are investigating.
