### ISSUE TITLE
Compatibility of backup & DUP_WITNESS

### ISSUE THREAD

**Issue by wubin12** [tronprotocol/java-tron#1873]
Wrong backup operation can cause DUP_WITNESS leading to miss block, should solve the compatibility of backup & DUP_WITNESS
#1875 

test case
1: DUP_WITNESS function regression test
2: Backup test: 
    Continuous switching of master and slave node, Not triggering DUP_WITNESS leading to miss block

**Comment by lvs007** [comment]
Can you write how the wrong can come out

**Comment by wubin12** [comment]
[](url)
