### ISSUE TITLE
Improve the hard fork mechanism

### ISSUE THREAD

**Issue by Yrp** [tronprotocol/java-tron#1884]
Hard forks are achieved by adding block versions to the block. When all SRs have produced this block of the version, the hard fork mechanism will take effect immediately.
If in the test network or other private chains, all SRs are producing high-level blocks, some hard-forked mechanisms that rely on low-level triggers will not take effect. We need a solution to solve this problem.

**Comment by renchenchang** [comment]
yes, this is a problem

**Comment by Yrp** [comment]
When all SRs have a higher version of the block, the hard fork triggered by the lower version block automatically takes effect.

**Comment by Yrp** [comment]
this is my solution. #1890
