### ISSUE TITLE
Need a new method of  multi thread validating signature preValidateTransactionSign after supporting multi signature

### ISSUE THREAD

**Issue by renchenchang** [tronprotocol/java-tron#1889]
The permission in a account will be updated after a full node executes a UpdateAccountPermission transaction that broadcasted from rpc or other nodes. The status of level db will update too. Next this full node will receive a block which contains the same UpdateAccountPermission transaction. It will throw a ValidateSignatureException when  full node executes preValidateTransactionSign in handleBlock function.

**Comment by olenheim** [comment]
can disscus multi-signuature （TRC16） here
https://github.com/tronprotocol/TIPs/issues/16

**Comment by lvs007** [comment]
1、When producing a block, the same account in each block can only contain one signature modified transaction. At the same time, the parallel verification needs to be moved before the transaction is executed.
PR: #1917 
2、Do not modify the logic of the production block, only modify the logic of the parallel verification.
The transactions of different accounts are grouped. In the same account, as long as one transaction is a signature update transaction, the transaction group of this account is serially checked, and other parallel inspections are performed.At the same time, the parallel verification needs to be moved before the transaction is executed.
PR: #1916

**Comment by lvs007** [comment]
The first method #1917  is simple to modify and difficult to introduce. The second method #1916 is complicated to modify, but it can effectively improve the efficiency of block execution. Considering the first method is more suitable #1917

**Comment by lvs007** [comment]
Test case:
1、Only one transaction with the most account signature modification can be included in each block
2、If there are SR cheats, and each block has scored multiple signature modification transactions for the same account, then other nodes will fail to pass the verification.
3、A block can contain multiple transactions in the same account that are not signed modified.
4、Parallel verification can be performed normally when performing chain cutting
5、The overall execution time of the block will not increase significantly

**Comment by Samuel0147** [comment]
Nice
