### ISSUE TITLE
Address generation problem

### ISSUE THREAD

**Issue by Martis467** [tronprotocol/java-tron#1901]
I was trying to sign a transaction offline and then broadcast it and the response I'm getting is really weird.
`{
    "success": false,
    "code": "SIGERROR",
    "message": "validate signature error",
    "transaction": {
        "hash": "b3e56ab77b288499dccb033830e26de2636facbbac71f3e8fdfed55d6934e843",
        "timestamp": 1546513801186,
        "contracts": [
            {
                "amount": 1000000,
                "contractType": "TransferContract",
                "contractTypeID": 1,
                "owner_address": "3z1tjMQtvmSJWBZ4sx4TkVWob33B7B1njEz6ACD5",
                "to_address": "3z1Jzfi8UDASMpHKQWGLdW8Szuxtp7MeDPMDqAbZ"
            }
        ],
        "data": "",
        "signatures": [
            {
                "bytes": "2GHRvpbD1r7x5q9cmIciq/PutywTk9dqizJRxF0H4B9Sb/Ac/D/T0GJFiGIKdN/2HdK1821WZK9Sa2pl993yGgE=",
                "address": "TSBDcUsKHuTiBUf14KW6bhbsq4suFN3edD"
            }
        ]
    }
}`

First of all the `owner_address` and `to_address` doesn't match at all with the ones I've entered.
`owner_address` should be `TSXrCaC9vzaw2njgmb8Bd8LMMthYWjK1nP`

Second the `owner_address` is different then the one in signatures.

Maybe there is a problem with the way I implemented address generation or transaction creation process?

Address generation process: https://pastebin.com/grTmikaF
Transaction creation process: https://pastebin.com/wuvLNiWn

**Comment by wubinTRON** [comment]
Could you change the address generation process to try again?
Like using this function String address = org.tron.core.Wallet.encode58Check(ecKeyPair.getAddress());
to address generation.
more detail could be seen in java-tron/src/main/java/org/tron/keystore/Credentials.java
