### ISSUE TITLE
[DOCS] "MINIMUM 2 ENERGY Cores" ?

### ISSUE THREAD

**Issue by lazaridiscom** [tronprotocol/java-tron#1910]
The README is and introductional document, yet it mentions:

"MINIMUM 2 ENERGY Cores"

as a prerequisite.

What are "ENERGY Cores" ?

(clarify it, or remove it from the README)

**Comment by jiangyy0824** [comment]
@lazaridiscom Thanks for your correction. It should be 2 CPU cores. We will fix it right now.
