### ISSUE TITLE
[PROJECT] Revise README

### ISSUE THREAD

**Issue by ghost** [tronprotocol/java-tron#1911]
I tried to Evaluate java-tron, and expected to see a compact & concise README, focused on developers familiar with basic concepts (like shell, git etc.).

What I saw was a chaotic & verbose README

## New README

Something like

* Compact Intro, Pointer to User-Level Documentation
* Prerequisites
* Build, Test, Install, Run
* Further Info

I can provide a draft so you can see what I'm talking about.

**Comment by zhaohong** [comment]
sounds great.
