### ISSUE TITLE
[DOCS] Increase Contrast of Documentation Site

### ISSUE THREAD

**Issue by ghost** [tronprotocol/java-tron#1913]
I visited the documentation site https://developers.tron.network/docs/download-the-code and expected naturally a High Contrast Site (Black on White).

Instead, I saw a Low Constrast (Grey on White) with low readability.

## Solution

Increase the contrast.

Rationales: none (obvious)

**Comment by zk19862018** [comment]
Hi, you can check our new documentation site: https://tronprotocol.github.io/documentation-EN/
