### ISSUE TITLE
Gettransactionsfrom this API generates an error of "Error 405 HTTP method POST is not supported by this URL"

### ISSUE THREAD

**Issue by seelin** [tronprotocol/java-tron#1921]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
 curl -X POST  http://127.0.0.1:8091/walletextension/gettransactionsfromthis -d '{"account" :{"address" : "41E552F6487585C2B58BC2C9BB4492BC1F17132CD0"}, "offset": 0, "limit": 10}'
```
2. What did you expect to see?
the list of transaction history by address 

3. What did you see instead?
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 405 HTTP method POST is not supported by this URL</title>
</head>
<body><h2>HTTP ERROR 405</h2>
<p>Problem accessing /walletextension/gettransactionsfromthis. Reason:
<pre>    HTTP method POST is not supported by this URL</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>
</body>
</html>
```

**Comment by XieWeiZM** [comment]
@seelin  Are you using https://api.trongrid.io?     May be  Version below v3.2

**Comment by alexkvak** [comment]
I guess it's related to #1867

**Comment by yopoing** [comment]
我也是遇到这个问题，没有解决办法吗？

**Comment by jiangyy0824** [comment]
@seelin @XieWeiZM @benjioh5 @alexkvak @yopoing This api is desigined for solidity node. It seems that you post the query to fullnode. Please check again. Thanks!
