### ISSUE TITLE
Captcha load broken

### ISSUE THREAD

**Issue by zokito** [tronprotocol/java-tron#193]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
login to wallet to check balance

2. What did you expect to see?
captcha entry puzzle.

3. What did you see instead?

```
Uncaught ReferenceError: capInit is not defined
    at HTMLFormElement.<anonymous> (login.8dc4c594.js:1)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.q.handle (jquery.min.js:3)

```

**Comment by zhaohong** [comment]
do you mean tron.network?

**Comment by zokito** [comment]
yes
