### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridiscom** [tronprotocol/java-tron#1935]

**Comment by joadr** [comment]
I totally agree, It's very difficult to work with TRON at the moment because of the documentation.

**Comment by lazaridiscom** [comment]
The other problem is that the public project resources are essentially dead, there are near-zero responses to issues:

https://github.com/search?q=org%3Atronprotocol+author%3Alazaridiscom&type=Issues

General overview of tron:

https://github.com/lazaridiscom/dapp-platform/issues/5

**Comment by joadr** [comment]
I've been able to get help on their discord channel. Is very active and developers are very willing to help.

**Comment by taiyangc** [comment]
@lazaridiscom As stated on the first line of the README:

Please visit the new [TRON Developers Hub](https://developers.tron.network/) for detailed guides, interactive APIs, and much more!

The new guides are more organized and up-to-date.

**Comment by lazaridiscom** [comment]
> I've been able to get help on their discord channel. Is very active and developers are very willing to help.

Well, and at the same time they do not process the open issues (which has always priority over chat-talk). I call this "amateurs to the bones".

The Tron CEO is busy to play "Clown-Wars" with Buterin on Twitter, instead of setting up a rule-system which ensures that this repo here does not feel like its dead.

@taiyangc , you want to confirm my point?

When new documentation supersedes the old one, you shred the old one, otherwise one has to guess if its still valid or not.

Its nowadays a sports in projects, like there is a competition "who make the crappiest docs, who hast the worst response times".

(as a sidenote, the new developer site has still a very low quality.)

As for this issue here:

## Actions

* Close the issues within https://github.com/tronprotocol/Documentation
* Remove content (or replace all content with link to new docs), cleanup
* Archive the Repo
* Close this fracking issue

10 to 15 min.
