### ISSUE TITLE
java-tron怎么验证签名

### ISSUE THREAD

**Issue by 1726431685** [tronprotocol/java-tron#1947]
现有的verify方法需要三个参数，verify(byte[] data, byte[] signature, byte[] pub),有没有不通过公钥而是地址验证签名的方法呢

**Comment by 1726431685** [comment]
help

**Comment by lazaridiscom** [comment]
No help here. This repo is dead.

**Comment by yashbhavsar007** [comment]
Is there any other community or group where tron developer still alive ? Because in github they are not solving any issues!

**Comment by 1726431685** [comment]
I think tron code is so sucks!

**Comment by yashbhavsar007** [comment]
Hi @1726431685 i have found a way to reach tron community via discord !

**Comment by 1726431685** [comment]
Wow,what's that?

**Comment by lazaridiscom** [comment]
#171

**Comment by haihaole01** [comment]
> 现有的verify方法需要三个参数，verify(byte[] data, byte[] signature, byte[] pub),有没有不通过公钥而是地址验证签名的方法呢

朋友你验签成功了吗，我现在也遇到了同样的问题，求助

**Comment by yanchain** [comment]
> 
怎么解决？

> Wow,what's that?

How to solve it?
