### ISSUE TITLE
transaction don't broadcast to other peer

### ISSUE THREAD

**Issue by zjb0807** [tronprotocol/java-tron#1954]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
04:04:41.022 WARN  [pool-41-thread-1] [o.t.c.Wallet](Wallet.java:423) Broadcast transaction aaea18747e1b5229f44193d24b4a970b65c7bce3a1037f22c1f3b0c74c360a3e failed, effective connection:0 lt minEffectiveConnection:1.
04:04:49.615 INFO  [pool-41-thread-1] [o.t.c.Wallet](Wallet.java:451) Broadcast transaction aaea18747e1b5229f44193d24b4a970b65c7bce3a1037f22c1f3b0c74c360a3e successfully. 
```
when effective connection > 0, broadcast transaction will return successfully, but don't broadcast transaction to other peer. 
After a while,  the new transaction will broadcast successfully，but the old transaction still in mempool.

2. What did you expect to see?
Broadcast transaction to other peer.

3. What did you see instead?
Transaction still in mempool.

**Comment by jiangyy0824** [comment]
@zjb0807 This is by design. "minEffectiveConnection" means that you should have more than 1 active peer in your private network. Please set "minEffectiveConnection" to 0 in your config. It should solve your issue. Thanks

rpc {
    port = 50051
    #solidityPort = 50061
    # Number of gRPC thread, default availableProcessors / 2
    # thread = 16

    # The maximum number of concurrent calls permitted for each incoming connection
    # maxConcurrentCallsPerConnection =

    # The HTTP/2 flow control window, default 1MB
    # flowControlWindow =

    # Connection being idle for longer than which will be gracefully terminated
    maxConnectionIdleInMillis = 60000

    # Connection lasting longer than which will be gracefully terminated
    # maxConnectionAgeInMillis =

    # The maximum message size allowed to be received on the server, default 4MB
    # maxMessageSize =

    # The maximum size of header list allowed to be received, default 8192
    # maxHeaderListSize =

    # Transactions can only be broadcast if the number of effective connections is reached.
    minEffectiveConnection = 1
  }
