### ISSUE TITLE
why org.tron.common.utils.ForkController has hard folk check

### ISSUE THREAD

**Issue by UnforgivenZZZ** [tronprotocol/java-tron#1963]
in the file org.tron.common.utils.ForkController,
there is a function 
  private boolean checkForEnergyLimit() {
    long blockNum = manager.getDynamicPropertiesStore().getLatestBlockHeaderNumber();
    return blockNum >= 4727890L;
  }
this block height check prevent some proposal creation such like allow delegate resource for
some private test net

is there a reason to hard coded the block height or is it possible to remove this check in future release?

**Comment by jiangyy0824** [comment]
@UnforgivenZZZ The blockNum for energy limit check  could be configured. Please add the configuration below in your config file. Thanks!

enery.limit = {
    block.num = 111 // the blocknumber to specify
}
