### ISSUE TITLE
Missing query of get votelist by address

### ISSUE THREAD

**Issue by CTJaeger** [tronprotocol/java-tron#1984]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
A very important feature is missing here. How can an SR / SRC view its voters without accessing third party vendors? This is important!

3. What did you see instead?
Nothing.

**Comment by jiangyy0824** [comment]
@CTJaeger The function has been implemented in tronscan. Please refer to the following link.

https://tronscan.org/#/address/TGzz8gjYiYRqpfmDwnLxfgPuLVNmpCswVp/voters
