### ISSUE TITLE
gradlew build failed in mac

### ISSUE THREAD

**Issue by zychappy** [tronprotocol/java-tron#1985]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
build the latest master branch
./graldew build

2. What did you expect to see?
build success

3. What did you see instead?
> Task :extractIncludeTestProto FAILED
[Fatal Error] objenesis-parent-2.6.pom:513:7: The markup in the document following the root element must be well-formed.

**Comment by jiangyy0824** [comment]
@zychappy Sorry for your inconvenience. Please try again with "./gradlew clean", if fails again. Please check whether your configuration is right. Thanks.

```
JDK 1.8 (JDK 1.9+ are not supported yet)
On Linux Ubuntu system (e.g. Ubuntu 16.04.4 LTS), ensure that the machine has Oracle JDK 8, instead of having Open JDK 8 in the system. If you are building the source code by using Open JDK 8, you will get Build Failed result.
Open UDP ports for connection to the network
MINIMUM 2 ENERGY Cores
```
