### ISSUE TITLE
The assert function in contract Will cost huge Energy

### ISSUE THREAD

**Issue by rickshenjp** [tronprotocol/java-tron#1986]
The assert function in contract  like this:
`
function mul(uint256 a, uint256 b) internal pure returns (uint256) 
{
        if (a == 0) {
            return 0;
        }
        uint256 c = a * b;
        assert(c / a == b);
        return c;
}
`
When the function trigger assert(false) , it will be cost all Energy up to fee_limit

**Comment by jeancky** [comment]
@rickshenjp   According to the Solidity document, Assert error will take all your energy as you claimed if the condition is false.

We suggest you use Required instead of Assert.
