### ISSUE TITLE
struct energy cost problem in TRON/solidity Odyssey_v3.2

### ISSUE THREAD

**Issue by rickshenjp** [tronprotocol/java-tron#1987]
I found some struct energy cost problem in TRON/solidity Odyssey_v3.2:

```
mapping (address => Order10) orderMap;
struct Order10 {
        uint32  qw1;
        uint16  dw1;
        uint16  dw2;
        uint16  dw3;
        uint16  dw4;
        uint160 addr1;
    }

```
When I store one order10 into orderMap, it will cost about 45000 Energy
But in other version, it only cost about 25000 Energy

And when I change one existed order, in TRON/solidity Odyssey_v3.2 it will cost about 30000 Energy
But in other version it only cost about 5300 Energy

**Comment by tjchern** [comment]
1. which solidity compiler version do you use? some version of tron solidity compiler or some version of eth solidity compiler?
2. can you provide the function which change one existed order ?

**Comment by tjchern** [comment]
this is my test:
1. my solidity code:
```
contract test {
    mapping (address => Order10) orderMap;
    struct Order10 {
        uint32  qw1;
        uint16  dw1;
        uint16  dw2;
        uint16  dw3;
        uint16  dw4;
        uint160 addr1;
    }
    
    function addMap(address a) {
        orderMap[a] = Order10(1, 1, 1, 1, 1, 1);
    }
}
```
2. compile it with tron solidity compiler version trondev_v0.4.24, call the "addMap(address)", it will cost 46258 energy
3. compile it with tron solidity compiler version odyssey3.2, call the "addMap(address)", it will cost 46306 energy

so, using odyssey3.2, there is just  an extra 48 energy costed.
