### ISSUE TITLE
[VM](VM.java:1327) VM halted: [Not enough energy for

### ISSUE THREAD

**Issue by zhangsj** [tronprotocol/java-tron#1988]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
在一台4核16G的ubuntu上运行fullnode，日志显示
:50:19.482 INFO  [pool-8-thread-1] [VM](VM.java:1327) VM halted: [CPU timeout for 'PUSH1' operation executing]
09:50:19.482 INFO  [pool-8-thread-1] [Runtime](RuntimeImpl.java:637) timeout: CPU timeout for 'PUSH1' operation executing
09:50:49.436 INFO  [pool-8-thread-1] [VM](VM.java:1327) VM halted: [Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[4413], curOpEnergy[5000], usedEnergy[411]]
09:50:49.436 INFO  [pool-8-thread-1] [VM](VM.java:1327) VM halted: [Not enough energy for 'ISZERO' operation executing: curInvokeEnergyLimit[5741], curOpEnergy[3], usedEnergy[5741]]
09:50:49.436 INFO  [pool-8-thread-1] [Runtime](RuntimeImpl.java:651) runtime result is :Not enough energy for 'ISZERO' operation executing: curInvokeEnergyLimit[5741], curOpEnergy[3], usedEnergy[5741]
09:50:51.893 INFO  [pool-8-thread-1] [VM](VM.java:1327) VM halted: [Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[18985], curOpEnergy[20000], usedEnergy[774]]
09:50:51.894 INFO  [pool-8-thread-1] [Runtime](RuntimeImpl.java:651) runtime result is :Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[18985], curOpEnergy[20000], usedEnergy[774]
09:50:53.706 INFO  [pool-8-thread-1] [VM](VM.java:1327) VM halted: [Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[12591], curOpEnergy[5000], usedEnergy[9507]]
09:50:53.706 INFO  [pool-8-thread-1] [Runtime](RuntimeImpl.java:651) runtime result is :Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[12591], curOpEnergy[5000], usedEnergy[9507]
09:51:43.750 INFO  [pool-8-thread-1] [VM](VM.java:1327) VM halted: [Not enough energy for 'SHA3' operation executing: curInvokeEnergyLimit[412], curOpEnergy[42], usedEnergy[407]]
09:51:43.750 INFO  [pool-8-thread-1] [Runtime](RuntimeImpl.java:651) runtime result is :Not enough energy for 'SHA3' operation executing: curInvokeEnergyLimit[412], curOpEnergy[42], usedEnergy[407]

是否正常，如不正常如何避免这样的错误

**Comment by jeancky** [comment]
That means a CPU Timeout Error has token place.
Many reason could cause this error, complex contract or other abnormal situation, such as java gc just happened when the wittiness processing this transaction. 

we would like to have a look at your solidity code to make sure.

**Comment by CarlZhangbs** [comment]
I got the same issues!

**Comment by nicram-cf** [comment]
Hello, We got the same issues! Can it be reason if synchronization getting very slow, slower than real time so blocks are getting older and older. 
But when I restart tron (with deploy_tron.sh script) though these warnings synchronization speeds up but when tron is working about one hour it slows again

**Comment by jiangyy0824** [comment]
@nicram-cf Pls provide detailed tron.log and your machine configuration.

**Comment by nicram-cf** [comment]
Unfortunalely tron produces a lot of logs, many logs is divided by many lines and is difficult to find proper line in thousands others. 
`16:58:14.031 INFO  [pool-36-thread-1] [VM](VM.java:1419) VM halted: [Not enough energy for 'JUMPI' operation executing: curInvokeEnergyLimit[31], curOpEnergy[10], usedEnergy[26]]
16:58:14.031 INFO  [pool-36-thread-1] [VM](RuntimeImpl.java:703) runtime result is :Not enough energy for 'JUMPI' operation executing: curInvokeEnergyLimit[31], curOpEnergy[10], usedEnergy[26]

16:58:14.031 INFO  [pool-36-thread-1] [VM](VM.java:1419) VM halted: [Not enough energy for 'JUMPI' operation executing: curInvokeEnergyLimit[31], curOpEnergy[10], usedEnergy[26]]
16:58:14.031 INFO  [pool-36-thread-1] [VM](RuntimeImpl.java:703) runtime result is :Not enough energy for 'JUMPI' operation executing: curInvokeEnergyLimit[31], curOpEnergy[10], usedEnergy[26]

============ Peer stats: all 9, active 9, passive 0


8:22:04.935 WARN  [sendTimer] [net](MessageQueue.java:171) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /51.68.119.188:18888.
18:22:04.944 WARN  [sendTimer] [net](MessageQueue.java:171) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /47.254.77.236:18888.
generate time=2019-07-25 18:18:57.0
18:22:12.865 WARN  [sendTimer] [net](MessageQueue.java:171) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /34.219.97.75:18888.
generate time=2019-07-25 18:19:00.0
generate time=2019-07-25 18:19:03.0
============ Peer stats: all 30, active 30, passive 0
Peer 54.37.81.146:18888 [b4bb4b4c]
needSyncFromPeer:true

18:23:03.287 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 5 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.287 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 5 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.287 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 3 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.287 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 3 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.287 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.287 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 2 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.287 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.287 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 5 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 8 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 2 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 9 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: BLOCK size: 1 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 4 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 12 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: BLOCK size: 1 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.288 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 9 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 4 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 10 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 8 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 5 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 5 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 4 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 7 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 6 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 2 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 7 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.
18:23:03.289 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /34.247.231.60, syncFromUs: false, syncFromPeer: true.
18:23:03.290 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 6 from Peer /18.184.239.103, syncFromUs: false, syncFromPeer: true.


18:25:05.563 INFO  [TronJClientWorker-1] [net](Channel.java:216) Peer /47.88.225.9:18888 status change to SYNCING.
18:25:05.566 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.88.171.106, syncFromUs: false, syncFromPeer: true.
18:25:05.566 WARN  [TronJClientWorker-1] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 7 from Peer /18.231.88.120, syncFromUs: false, syncFromPeer: true.
18:25:05.574 WARN  [TronJClientWorker-1] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.75.10.71, syncFromUs: false, syncFromPeer: true.
18:25:05.579 WARN  [TronJClientWorker-0] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 5 from Peer /18.229.43.112, syncFromUs: false, syncFromPeer: true.
18:25:05.596 WARN  [TronJClientWorker-3] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.88.171.106, syncFromUs: false, syncFromPeer: true.
18:25:05.596 WARN  [TronJClientWorker-1] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 2 from Peer /18.231.88.120, syncFromUs: false, syncFromPeer: true.
18:25:05.603 WARN  [TronJClientWorker-0] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.75.65.115, syncFromUs: false, syncFromPeer: true.
18:25:05.609 WARN  [TronJClientWorker-0] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 2 from Peer /18.229.43.112, syncFromUs: false, syncFromPeer: true.
18:25:05.627 WARN  [TronJClientWorker-1] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /18.231.88.120, syncFromUs: false, syncFromPeer: true.
18:25:05.629 INFO  [TronJClientWorker-3] [net](Channel.java:216) Peer /18.182.120.69:18888 status change to HANDSHAKE_FINISHED.
18:25:05.629 INFO  [TronJClientWorker-3] [net](ChannelManager.java:162) Add active peer /18.182.120.69:18888 | 10c32d1d412effdabcaec365ece526a0b1a18c464483dffd7e3920854f966862f5fe93ab6cde8e1b9bd0f6d15d8cfe4e467384fd3b9990754293bd25491ec5ac, total active peers: 22
18:25:05.629 INFO  [TronJClientWorker-3] [net](Channel.java:216) Peer /18.182.120.69:18888 status change to SYNCING.
18:25:05.629 INFO  [TronJClientWorker-3] [net](Channel.java:216) Peer /18.182.120.69:18888 status change to SYNCING.
18:25:05.657 WARN  [TronJClientWorker-1] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /18.231.88.120, syncFromUs: false, syncFromPeer: true.
18:25:05.663 WARN  [TronJClientWorker-0] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.75.65.115, syncFromUs: false, syncFromPeer: true.
18:25:05.701 WARN  [TronJClientWorker-0] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 3 from Peer /18.229.43.112, syncFromUs: false, syncFromPeer: true
18:26:32.474 WARN  [sendTimer] [net](MessageQueue.java:171) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /34.237.210.82:18888.
18:26:32.484 WARN  [sendTimer] [net](MessageQueue.java:171) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /34.219.43.251:18888.


`

**Comment by sullof** [comment]
In TronGrid, despite that a full node can work with 4vCPu/8GbRAM, we use 16vCPU/64GbRAM instances because with less than that the nodes are unable to handle peaks and get memory leaks and/or become irresponsive, showing errors like this.

**Comment by chrisc93** [comment]
Is there any solution here? Or is it limited to the hardware?

**Comment by microcai** [comment]
I got the same issue

**Comment by Benson0224** [comment]
Take this line for example:

> 09:50:49.436 INFO [pool-8-thread-1] VM VM halted: [Not enough energy for 'ISZERO' operation executing: curInvokeEnergyLimit[5741], curOpEnergy[3], usedEnergy[5741]]

From the node point of view, this is just an `INFO`, it is not an error. As long as your node can sync to the latest block, there should be no issue for your node. 

Regarding the VM halted, it is mean that the smart contract transaction execution failed in VM, this is a very common case. no need to worry. 

If your node failed to sync to the latest Block or run into 'Different result code' error, please check this guide on how to fix it. thanks. 
https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

**Comment by joshh71390** [comment]
> why is this issue closed?

because tron is a black hole designed to keep people from being able to develop. ... one thing they fucking hate is when people actually mention the issues of tron... they will ban block or close anything that brings light to the fact that u cant make it here if ur name is not justin sun.

**Comment by dmytro-samoylenko** [comment]
For everyone who get this kind of errors you should double check that you are running java-tron with docs-recommended params  `-XX:+UseConcMarkSweepGC` and `-Xmx24g` just like this:
```
java -Xmx24g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c .....
```
`-XX:+UseConcMarkSweepGC` should be placed before the -jar parameter, not at the end
`-Xmx` can be set to 80% of physical memory

Without these I have contract constant function failed (such as get USDT contract balance) no matter how high I set  vm.maxTimeRatio with next messages in `logs/tron.log`:
```
 CPU timeout for 'ADD' operation executing
 CPU timeout for 'SWAP1' operation executing
 CPU timeout for 'RETURN' operation executing
 CPU timeout for 'PUSH4' operation executing
 CPU timeout for 'PUSH1' operation executing
```

**Comment by cyberskycat** [comment]
when concurrent get the token balance , the cpu timeout error may be occur
` CPU timeout for 'ADD' operation executing
`

here just a workaround,don't know another effect
could add` --debug `cmdline param to FullNode.jar to elimate these error
`java -Xmx24g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c config.cnf --debug`

according the code --debug can turn off the tvm time checking
```
 @Parameter(names = {"--debug"}, description = "Switch for TVM debug mode. In debug model, TVM " +
      "will not check for timeout. (default: false)")
  public boolean debug = false;
```

i wonder why a readonly call could cause such cpu timeout error!!!!
