### ISSUE TITLE
Transfer TRC10 Failure

### ISSUE THREAD

**Issue by lishuo5263** [tronprotocol/java-tron#1990]
Please answer these questions before submitting your issue. Thanks!

- Here is my executed log , I fllow [offcial document direction](https://developers.tron.network/docs/api-sign-flow#wallets-accounts)，and use offcial recommend Full Node to executed api.

1.MakeTransfer

**- `curl -X POST  http://54.236.37.243:8090/wallet/transferasset -d '{"owner_address":"412a11aadd8fd2ee249db7d9cb8e820baeb645b190", "to_address": "4130f6704e31315e3b9c508fd4d23dbca766f31503", "asset_name": "31303032303030", "amount": 100000}'`**

Response：

- `{"txID":"4d7186963bfecefebffc420d23f02973712c4333c288ba9ebaa8f22ebd981ae4","raw_data":{"contract":[{"parameter":{"value":{"amount":100000,"asset_name":"31303032303030","owner_address":"412a11aadd8fd2ee249db7d9cb8e820baeb645b190","to_address":"4130f6704e31315e3b9c508fd4d23dbca766f31503"},"type_url":"type.googleapis.com/protocol.TransferAssetContract"},"type":"TransferAssetContract"}],"ref_block_bytes":"a1a7","ref_block_hash":"0a56bca6a6deac2a","expiration":1550476437000,"timestamp":1550476378200}}`

2.SignTranscation

**- `curl -X POST  http://54.236.37.243:8090/wallet/gettransactionsign -d '{"transaction":{"txID":"4d7186963bfecefebffc420d23f02973712c4333c288ba9ebaa8f22ebd981ae4","raw_data":{"contract":[{"parameter":{"value":{"amount":100000,"asset_name":"31303032303030","owner_address":"412a11aadd8fd2ee249db7d9cb8e820baeb645b190","to_address":"4130f6704e31315e3b9c508fd4d23dbca766f31503"},"type_url":"type.googleapis.com/protocol.TransferAssetContract"},"type":"TransferAssetContract"}],"ref_block_bytes":"a1a7","ref_block_hash":"0a56bca6a6deac2a","expiration":1550476437000,"timestamp":1550476378200} },"privateKey":"etc ********"}'`**

Response：

- `{"signature":["d6c3ee856d93ba03cba0467d160868499a769087c425d12883ba61108eec6fde03346e2ab18198d7649758a27ed41b7f87ecfbb9e1fc681d52702b04764f543500"],"txID":"4d7186963bfecefebffc420d23f02973712c4333c288ba9ebaa8f22ebd981ae4","raw_data":{"contract":[{"parameter":{"value":{"amount":100000,"asset_name":"31303032303030","owner_address":"412a11aadd8fd2ee249db7d9cb8e820baeb645b190","to_address":"4130f6704e31315e3b9c508fd4d23dbca766f31503"},"type_url":"type.googleapis.com/protocol.TransferAssetContract"},"type":"TransferAssetContract"}],"ref_block_bytes":"a1a7","ref_block_hash":"0a56bca6a6deac2a","expiration":1550476437000,"timestamp":1550476378200}}`

3.Broadcast Transaction:

**-` curl -X POST  http://54.236.37.243:8090/wallet/broadcasttransaction -d '{"signature":["ß"],"txID":"4d7186963bfecefebffc420d23f02973712c4333c288ba9ebaa8f22ebd981ae4","raw_data":{"contract":[{"parameter":{"value":{"amount":100000,"asset_name":"31303032303030","owner_address":"412a11aadd8fd2ee249db7d9cb8e820baeb645b190","to_address":"4130f6704e31315e3b9c508fd4d23dbca766f31503"},"type_url":"type.googleapis.com/protocol.TransferAssetContract"},"type":"TransferAssetContract"}],"ref_block_bytes":"a1a7","ref_block_hash":"0a56bca6a6deac2a","expiration":1550476437000,"timestamp":1550476378200}}'`**

Response：

- `{"code": "SIGERROR","message": "76616c6964617465207369676e6174757265206572726f72"}`

**validate signature error   why ？？？please help ASAP ！！！**

**Comment by zk19862018** [comment]
It is "alidate signature error", make sure you use the right privatekey
