### ISSUE TITLE
cannot change log level

### ISSUE THREAD

**Issue by Wheaties466** [tronprotocol/java-tron#1995]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I built it an got it up and working sucessfully but I cannot get it to respect the log level in the config file. I have even tried changing the log level in logback.xml files to all ERROR instead of info. This did not help either. Suggestions appreciated because the INFO log level is writing maybe a GB/min

log.level = {
   root = "ERROR" // TRACE;DEBUG;INFO;WARN;ERROR
}

java-tron/build/resources/main/logback.xml
java-tron/src/main/resources/logback.xml

2. What did you expect to see?
Once I changed the log level and stopped and started the application I expect to only see ERROR level logs yet I continue to see INFO level logs.

3. What did you see instead?
I am continuing to see INFO level logs even with everything I have stated above set for ERROR. I also checked setting it to TRACE and that did not seem to produce any additional logs so it looks like it is not respecting any of the settings in the config.conf file.

**Comment by jiangyy0824** [comment]
@Wheaties466 The log level is defined in logback.xml. Please set the root level to "ERROR" if you want to filter only error logs. Please refer to the configuration below.

<root level="ERROR">
    
    <appender-ref ref="ASYNC"/>
  </root>

  <logger name="app" level="ERROR"/>
  <logger name="net" level="ERROR"/>
  <logger name="backup" level="ERROR"/>
  <logger name="discover" level="ERROR"/>
  <logger name="crypto" level="ERROR"/>
  <logger name="utils" level="ERROR"/>
  <logger name="actuator" level="ERROR"/>
  <logger name="API" level="ERROR"/>
  <logger name="witness" level="ERROR"/>
  <logger name="DB" level="ERROR"/>
  <logger name="capsule" level="ERROR"/>
  <logger name="VM" level="ERROR"/>

**Comment by zk19862018** [comment]
+
