### ISSUE TITLE
cpu 资源 安全问题

### ISSUE THREAD

**Issue by rabbitHX** [tronprotocol/java-tron#2001]
阅读了下java-tron的代码，有个疑惑：
  代码的逻辑：如果用户质押的cpu资源不足，而且账户中也没有足够的trx用来抵扣，那么这个交易会被丢弃。
  问题是：这样的话如果有人恶意攻击，调用合约接口，每次都因为资源、余额不足而失败，交易被丢弃。这个人可以一直这样发送恶意请求而没有任何惩罚，请问这个问题有没有考虑？

**Comment by jeancky** [comment]
We have considered this. The transaction you described wouldn't be dropped. It will only execute as many instructions as your energy would cover. So, it is not an attack.
