### ISSUE TITLE
Node stuck at block 370594, reinstall + resync many times not work

### ISSUE THREAD

**Issue by antechdemo** [tronprotocol/java-tron#2024]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
    * My Fullnode sync normally until block `370594` it just stuck there.
2. Related Issues
    * #1625
    * #1619
But not getting any solution in my case.

**Comment by CarilKing** [comment]
me too, My Fullnode normally until block 5094012

**Comment by zhaohong** [comment]
could you please provide your conf file?

**Comment by CarilKing** [comment]
https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf

**Comment by CarilKing** [comment]
> could you please provide your conf file?

https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf

**Comment by antechdemo** [comment]
could you please provide your conf file?

https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf

**Comment by jiangyy0824** [comment]
> could you please provide your conf file?
> 
> https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf

Could you please provide:
1 tron.log or the related error messages;
2 code branch.

Then we can try to figure out the root cause. 
Thanks a lot!

**Comment by DNK90** [comment]
I also got stuck at 370594. I Tried delete out_directory but it didn't work.
1. I am using master
2. this is my log
[tron.log.zip](https://github.com/tronprotocol/java-tron/files/2956014/tron.log.zip)

**Comment by jiangyy0824** [comment]
> I also got stuck at 370594. I Tried delete out_directory but it didn't work.
> 
> 1. I am using master branch
> 2. this is my log
>    [tron.log.zip](https://github.com/tronprotocol/java-tron/files/2956014/tron.log.zip)

According to your logs, all of the peer node are out of sync. We will check what's wrong with the test environment. Thanks for your patient.

**Comment by jiangyy0824** [comment]
@CarilKing @antechdemo Sorry for the late reply. We will be very appreciated if you could provide the tron log or the related error messages.

Could you please provide:
1 tron.log or the related error messages;
2 code branch.

Thanks!

**Comment by jiangyy0824** [comment]
@antechdemo @DNK90 We have found the root cause. This is caused by proposal tests. Full node failed to execute the updatePermission transaction in block 370594. 

We have re-deployed the test environment. Please clean the data and start to sync. Sorry for the inconvenience.

@CarilKing This is difference case. You are using the mainnet config other than the test environment. Hope you could provide the tron.log. Thanks.

**Comment by phucnguyenit** [comment]
@jiangyy0824: the sync process from test-net too slow at this time... So we have to re-deploy and run testnet from master branch, right?

**Comment by jiangyy0824** [comment]
> @jiangyy0824: the sync process from test-net too slow at this time... So we have to re-deploy and run testnet from master branch, right?

Yes,there was sync issue in the test environment.  Please delete the output-directory and re-sync your fullnode.

**Comment by DNK90** [comment]
@jiangyy0824 is this testnet related to shasta? Current block number is shasta is about 220xxxx.
However the current block number shown here is much less than this (about 7xxx at commented time)

**Comment by jiangyy0824** [comment]
> @jiangyy0824 is this testnet related to shasta? Current block number is shasta is about 220xxxx.
> However the current block number shown here is much less than this (about 7xxx at commented time)
The testnet has no relation with shasta. We re-deploy the testnet about six hours ago, and the latest block number is near to 6000. Please check again. Thanks.
