### ISSUE TITLE
ERROR: NOT_ENOUGH_EFFECTIVE_CONNECTION (effective connection:0 lt minEffectiveConnection:1) while broadcasting the transaction to create the contract Migrations

### ISSUE THREAD

**Issue by varshakhandre14** [tronprotocol/java-tron#2033]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Trying to migrate a smart contract on private node network using command 
`tronbox migrate --reset --network development`

2. What did you expect to see?
Sucessful migration to network

3. What did you see instead?

> ERROR: NOT_ENOUGH_EFFECTIVE_CONNECTION (effective connection:0 lt minEffectiveConnection:1) while broadcasting the transaction to create the contract Migrations

**Comment by jiangyy0824** [comment]
Hi, it seems that your private network has only one fullnode. In wallet.java, Fullnode will check whether it has more than one active peer node . If the count is 0, fullnode will return NOT_ENOUGH_EFFECTIVE_CONNECTION.

To continue your work, please comment the code below and rebuild java-tron.

Thanks.
 
if (minEffectiveConnection != 0) {
        if (p2pNode.getActivePeer().isEmpty()) {
          logger.warn("Broadcast transaction {} failed, no connection.", trx.getTransactionId());
          return builder.setResult(false).setCode(response_code.NO_CONNECTION)
              .setMessage(ByteString.copyFromUtf8("no connection"))
              .build();
        }

        int count = (int) p2pNode.getActivePeer().stream()
            .filter(p -> !p.isNeedSyncFromUs() && !p.isNeedSyncFromPeer())
            .count();

        if (count < minEffectiveConnection) {
          String info = "effective connection:" + count + " lt minEffectiveConnection:"
              + minEffectiveConnection;
          logger.warn("Broadcast transaction {} failed, {}.", trx.getTransactionId(), info);
          return builder.setResult(false).setCode(response_code.NOT_ENOUGH_EFFECTIVE_CONNECTION)
              .setMessage(ByteString.copyFromUtf8(info))
              .build();
        }
      }

**Comment by jiangyy0824** [comment]
Set "minEffectiveConnection" from 1 to 0 could solve your issue.

rpc {
    port = 50051
    #solidityPort = 50061
    # Number of gRPC thread, default availableProcessors / 2
    # thread = 16

    # The maximum number of concurrent calls permitted for each incoming connection
    # maxConcurrentCallsPerConnection =

    # The HTTP/2 flow control window, default 1MB
    # flowControlWindow =

    # Connection being idle for longer than which will be gracefully terminated
    maxConnectionIdleInMillis = 60000

    # Connection lasting longer than which will be gracefully terminated
    # maxConnectionAgeInMillis =

    # The maximum message size allowed to be received on the server, default 4MB
    # maxMessageSize =

    # The maximum size of header list allowed to be received, default 8192
    # maxHeaderListSize =

    # Transactions can only be broadcast if the number of effective connections is reached.
    minEffectiveConnection = 0
  }
