### ISSUE TITLE
Can I call TRON (TRX) smart contracts with Java? -- Similar to web3j on Ethereum

### ISSUE THREAD

**Issue by dmerniestic1987** [tronprotocol/java-tron#2037]
Hello everybody!
I am developing a native Android java application and I need to call some transactions of an smart contracts written in Solidity. Can I do this with native Android App?
In another project for web3j to call contracts with java classes, is there something similar for TRON (TRX)?
If there is no similar project, can I invoke the methods of a smart contract with tron-web?
Thanks!

**Comment by jeancky** [comment]
Tron has no projects like web3j yet. 

But you can communicate with a Tron Fullnode via the grpc api. Here is a PC end wallet-client which can trigger smart contracts:
https://github.com/tronprotocol/wallet-cli

You may find useful example there.

**Comment by dmerniestic1987** [comment]
Thanks!!!!

**Comment by zhaohong** [comment]
sure, we provide gRpc api.
