### ISSUE TITLE
transactions are rollback frequently

### ISSUE THREAD

**Issue by rainysiu** [tronprotocol/java-tron#2072]
The transactions are rollback frequently.

58bb27395c787c52d57d266c431fdd37f4dff3e08cb36995dc603f32a034f8ad
f2b70cd180bd3e7ef46a152e21bd19d874d5f827c78b1e0d30bb1a2deb250c64

https://api.trongrid.io/wallet/gettransactioninfobyid?value=f2b70cd180bd3e7ef46a152e21bd19d874d5f827c78b1e0d30bb1a2deb250c64

 User even said that he saw the token/trx in his wallet for a few seconds, and then the token/trx is decreased.
check the hash, and it's returned {}

**Comment by jiangyy0824** [comment]
@rainysiu 
58bb27395c787c52d57d266c431fdd37f4dff3e08cb36995dc603f32a034f8ad, this transaction  could be queried successfully with trongrid. The other one failed to query with trongrid and tronscan.

Could you provide more details?
1. what's the relationship between the two transactions?
2. which wallet does the user use?  And the data source of the wallet. 
3. The tron log if possible.

Thanks.

**Comment by rainysiu** [comment]
11f699faf536b4e14bd5d56b045a9234bb8398b6eacac9920cc89757715b4441

this  hash

**Comment by jiangyy0824** [comment]
> 11f699faf536b4e14bd5d56b045a9234bb8398b6eacac9920cc89757715b4441
> 
> this hash

Please provide the block number and the details in the comments.

**Comment by rainysiu** [comment]
7815247
11f699faf536b4e14bd5d56b045a9234bb8398b6eacac9920cc89757715b4441

7815247
f2b70cd180bd3e7ef46a152e21bd19d874d5f827c78b1e0d30bb1a2deb250c64
