### ISSUE TITLE
I want to know how much memory an address is about.

### ISSUE THREAD

**Issue by lihuawei321** [tronprotocol/java-tron#2073]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Calculate memory space.

2. What did you expect to see?

I want to know how much memory an address is about.

3. What did you see instead?
What needs to be stored in memory.

**Comment by jiangyy0824** [comment]
@lihuawei321 Could you explain more detailed? Address for transaction? Please give us an example.

**Comment by lihuawei321** [comment]
@jiangyy0824 Hello, I want to calculate the memory usage of a node in TRON now, so I want to know what the memory of a node is stored in, and should include the address, so I want to know how much memory space an address probably occupies.

**Comment by lihuawei321** [comment]
@jiangyy0824 For example, if I assume that TPS reaches 2000, how can I calculate if my memory is enough?

**Comment by wubinTRON** [comment]
When we do stress testing,  it seems to used memory from 10k-10M. Because of the transaction space is different(from 100B - 500kb) and we save unconfirmed transaction in the memory.

**Comment by lihuawei321** [comment]
@wubinTRON So how much memory is used in an address.

**Comment by lihuawei321** [comment]
@wubinTRON hello， I want to know how you specifically calculate the TPS.

**Comment by wubinTRON** [comment]
for example, if there is 100 transaction in a block, and in general the time of process block is 3 second. So the TPS is 100 / 3. You can simply estimate tps in this way.

**Comment by lihuawei321** [comment]
@wubinTRON 
So what is stored in the node's memory?  AND
How to calculate the use of memory?

**Comment by lihuawei321** [comment]
@wubinTRON Hello, where can I see the configuration required for the TRON node?

**Comment by jiangyy0824** [comment]
@lihuawei321 There is no configuration. Since this is not an issue. If you still have question, please join tron's telegram. Thanks.

**Comment by lihuawei321** [comment]
@jiangyy0824 Hello, I think TRON has all the accounts and smart contracts in memory, is that correct? I want to know how many smart contracts are there now?

**Comment by lihuawei321** [comment]
@wubinTRON Hello, I want to ask how much memory each smart contract in TRON accounts for?
