### ISSUE TITLE
Sending BTT from Tron wallet to Binance No Show

### ISSUE THREAD

**Issue by USCryptoCurrency** [tronprotocol/java-tron#2076]
I tried to send BTT token from my Tron wallet to binance

Transfer was confirmed on Tron Network

Hashtags confirmed

Binance did not receive the tokens why

**Comment by brunocampos-ssa** [comment]
Hello there, TronWallet is just a interface to tron blockchain. Al operations occurs in-chain, in decentralized way. Have you contact Binance to track the token once the transaction was confirmed in tron blockchain?
Can you share transaction hash to we help you better?

Thanks,

Bruno.

**Comment by USCryptoCurrency** [comment]
yes who are you Bruno? I sent them everything, hash tags transactions, all of it

**Comment by brunocampos-ssa** [comment]
I’m from TronWallet team and I would like to help you.

**Comment by USCryptoCurrency** [comment]
How sir?

**Comment by USCryptoCurrency** [comment]
Thank you I will contact you in the morning

**Comment by USCryptoCurrency** [comment]
Call me 323.338.1545

**Comment by USCryptoCurrency** [comment]
Call me 323 338 1545.

I will pay you to help figure this out
