### ISSUE TITLE
test.tronscan.org is not working

### ISSUE THREAD

**Issue by APshenkin** [tronprotocol/java-tron#2078]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
visit test.tronscan.org

2. What did you expect to see?
See testnet explorer, as described in docs https://github.com/tronprotocol/Documentation/blob/master/TRX/Tron-exchange.md

3. What did you see instead?
This site can’t be reached test.tronscan.org took too long to respond.

**Comment by jiangyy0824** [comment]
@APshenkin Please use https://tronscan.org/#/ instead. The test url is unavailable.

**Comment by APshenkin** [comment]
@jiangyy0824 As described in docs https://tronscan.org/ is for mainnet, but I want to see block explorer for testnet. And not for shasta testet, because I want to setup my own testnet node (with shasta this is unavalible)

In docs there is two configs. I used testet configuration and already sync it (400k blocks). So what about blockexplorer for it?

**Comment by APshenkin** [comment]
BTW, updated documentation will be great
