### ISSUE TITLE
Synchronization node failure

### ISSUE THREAD

**Issue by TanLiangZhong** [tronprotocol/java-tron#2079]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
Synchronize normally.

3. What did you see instead?
23:02:42.845 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @55418ms
23:02:42.846 INFO  [main] [discover](DiscoverServer.java:120) Closing discovery server...
23:02:43.077 INFO  [DiscoverServer] [discover](DiscoverServer.java:106) Shutdown discovery server
23:02:45.294 INFO  [main] [app](SolidityNode.java:159) headBlockNum:7829289, solidityBlockNum:7829271, diff:18
23:02:45.294 INFO  [main] [app](SolidityNode.java:162) use fullNode database, headBlockNum:7829289, solidityBlockNum:7829271, diff:18
23:02:45.459 ERROR [main] [app](SolidityNode.java:143) Failed to get last solid blockNum: 0, reason: UNAVAILABLE: io exception.
23:02:46.460 ERROR [main] [app](SolidityNode.java:143) Failed to get last solid blockNum: 0, reason: UNAVAILABLE: io exception.
23:02:47.460 ERROR [main] [app](SolidityNode.java:143) Failed to get last solid blockNum: 0, reason: UNAVAILABLE: io exception.
23:02:48.461 ERROR [main] [app](SolidityNode.java:143) Failed to get last solid blockNum: 0, reason: UNAVAILABLE: io exception.

**Comment by jiangyy0824** [comment]
@TanLiangZhong Please provide the details below:
1. code branch
2. config.conf
Thanks.

**Comment by TanLiangZhong** [comment]
1. https://github.com/tronprotocol/java-tron/releases       v3.5.0.1
2. https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf

**Comment by wubinTRON** [comment]
I synchronize it normally. And UNAVAILABLE: io exception, It means your node isn't able to connect other nodes.
