### ISSUE TITLE
java-tron build failed

### ISSUE THREAD

**Issue by keeplearning77** [tronprotocol/java-tron#2080]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I tried to build java-tron using gradlew in an AWS Ubuntu instance. The build get failed as some of the tests are failing.

I executed the following commands:
:~/java-tron$ sudo git checkout Odyssey-v3.5.0.1

~/java-tron$ git branch -vv
* (HEAD detached at Odyssey-v3.5.0.1) bdb69b9 Merge pull request #2023 from tronprotocol/decrease_cpu_usage
  develop dd59c0c [origin/develop] Merge pull request #2077 from tronprotocol/sync_m
  master  01ead01 [origin/master] Merge pull request #2066 from tronprotocol/update_circleCi_Config_to_master

~/java-tron$ cd ..
~$ sudo cp java-tron/src/main/resources/config.conf java-tron/
~$ cd java-tron/
~/java-tron$ sudo ./gradlew build

Here are some progress statistics of the build command:

<=------------> 10% EXECUTING [34s]
<===----------> 23% EXECUTING [1m 44s]
<===========--> 90% EXECUTING [3m 43s]
> :test > 0 tests completed
<===========--> 90% EXECUTING [4m 16s]
> :test > 116 tests completed, 34 failed, 8 skipped
..
> :test > Executing test org.tron.core.net.node.BroadTest
..
..
org.tron.core.net.node.FinishProcessSyncBlockTest > testFinishProcessSyncBlock FAILED
    java.lang.NullPointerException
        at org.tron.common.utils.ReflectUtils.invokeMethod(ReflectUtils.java:28)
        at org.tron.core.net.node.FinishProcessSyncBlockTest.testFinishProcessSyncBlock(FinishProcessSyncBlockTest.java:59)

org.tron.core.net.node.FinishProcessSyncBlockTest > classMethod FAILED
    java.lang.NullPointerException
        at org.tron.common.utils.ReflectUtils.invokeMethod(ReflectUtils.java:28)
        at org.tron.core.net.node.FinishProcessSyncBlockTest.destroy(FinishProcessSyncBlockTest.java:212)
..
<===========--> 90% EXECUTING [12m 24s]
> :test > 123 tests completed, 41 failed, 8 skipped
> :test > Executing test org.tron.core.net.node.GetLostBlockIdsTest

..
..
<===========--> 90% EXECUTING [20m 28s]
> :test > 131 tests completed, 49 failed, 8 skipped
> :test > Executing test org.tron.core.net.node.TcpNetTest
..
..
        at org.tron.core.db2.RevokingDbWithCacheNewValueTest.removeDb(RevokingDbWithCacheNewValueTest.java:45)
<===========--> 90% EXECUTING [21m 39s]
> :test > 216 tests completed, 126 failed, 15 skipped
> :test > Executing test org.tron.core.services.NodeInfoServiceTest
org.tron.common.storage.leveldb.LevelDbDataSourceImplTest > getValuesNext PASSED

org.tron.common.storage.leveldb.LevelDbDataSourceImplTest > getValuesPrev PASSED

411 tests completed, 195 failed, 29 skipped

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/ubuntu/java-tron/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 29m 42s
22 actionable tasks: 22 executed

2. What did you expect to see?

I expected to see BUILD-SUCCESSFUL for the build of a tagged release.

3. What did you see instead?

Build Failed.

I am new to the gradle build environment. Can I bypass some of the test tasks, to let the build to succeed, and then use the gradlew run command to start java-tron as a full-node?

**Comment by jiangyy0824** [comment]
@keeplearning77 Please use "./gradlew build -x test" to skip the test cases.

**Comment by keeplearning77** [comment]
Thanks for your help.

**Comment by zk19862018** [comment]
+
