### ISSUE TITLE
How to setup private peering between Tron nodes

### ISSUE THREAD

**Issue by keeplearning77** [tronprotocol/java-tron#2082]
This ticket is nor related to an issue, rather it is a query for which I would like to get some inputs.

I want to setup 2 tron nodes on separate AWS instances - say node1 and node2. Both will be initially joining the test-net and syncing up with traffic on the test-net.

Later, I want to detach node2 from the test-net, and keep only node1 in the test-net. I want to setup private peering between node2 and node1, so that while node1 continuously gets synced up with the test-net, my node2 will sync itself privately with node1.

Can someone please share inputs on whether and how this setup can be configured on the two nodes?

**Comment by zhaohong** [comment]
1.  move your node2 to the local network without public IP. 
2.  set the active property in node2

**Comment by jiangyy0824** [comment]
@keeplearning77 
1. Close node discovery of node2, it's in the config.conf
node.discovery = {
  enable = false
}

2. add node1's ip:port in node2's config.conf 
 
active = [
    # Active establish connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]

3. add node2's ip port in node1's config.conf
passive = [
    # Passive accept connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]
