### ISSUE TITLE
调用节点rpc接口返回广播成功，但是过很久区块浏览器也查不到

### ISSUE THREAD

**Issue by zhp1254** [tronprotocol/java-tron#2083]
1、wallet/broadcasttransaction接口返回成功
2、wallet/gettransactionsign 当时也能查到交易（1执行完后立即执行的这个接口）

3、问题是：过一段时间后区块浏览器上没有该交易，再用wallet/gettransactionsign也查不到了，用同样的数据再调用wallet/broadcasttransaction就报DUP_TRANSACTION_ERROR，出现频率随机

想要解决的问题
4、如何避免这个问题？
5、我这个交易到底有没有广播成功？

**Comment by jiangyy0824** [comment]
@zhp1254 
请问你们的节点是fullnode还是soliditynode? 如果是soliditynode，交易需要一分钟左右才能确认。
DUP_TRANSACTION_ERROR说明该交易已经上链。

**Comment by jeancky** [comment]
The transaction has been broadcasted, but not written into the block.

DUP_TRANSACTION_ERROR means it's been received by the FullNode.  Cannot found from the tronscan (for a long time, i.e. 1 minutes and more) means the transaction has been missed because of forking or other reasons. 

The former tx is cached by the FullNode you connected. ReSind would cause DUP_TRANSACTION_ERROR.

You could try other FullNodes, or resign the transaction data and broadcast again.

**Comment by zhp1254** [comment]
@jiangyy0824  soliditynode如果1分钟查不到可以确认交易失败了吗

**Comment by jiangyy0824** [comment]
@zhp1254 帮忙提供下transactionid，可以通过wallet/getTransactionInfoById,或者wallet/gettransactionbyid查看下。
soliditynode存储的是固化块，一个block从产出到最终固化，大概需要20个块，也就是1分钟时间。

**Comment by zhp1254** [comment]
现在txid查不到了

**Comment by tensecond** [comment]
我也遇到这个错误提示，自己搭建的私链，调用发送交易接口：blockingStubFull.broadcastTransaction(signaturedTransaction)，返回给我的错误code是：DUP_TRANSACTION_ERROR，但是交易查不到

**Comment by greensea** [comment]
我也遇到这个问题，现在也不知道交易到底有没有上链。
这会造成的后果是，我签发一个交易之后，过了很长时间（十分钟以上） solidity 节点上查不到这个交易，在 fullnode 重新广播交易时又获得 DUP_TRANSACTION_ERROR，那么这个交易到底成功没有？
A. 如果交易成功了，那么我不需要重新签名，重新发送一个新的交易；
B. 如果交易没有成功，那么我需要重新签名，重新发送一个新的交易（因为尝试重发旧的交易会得到 DUP_TRANSACTION_ERROR)
这就产生一个问题，由于我无法明确地知道这个交易到底有没有成功，所以没办法继续下一步的操作（把交易标记为成功，或者是重新签发新的交易），这对应用和用户来说太不友好了：
* 如果我们向用户显示“交易已上链”，但用户却查不到这个交易，显然会怀疑我们有问题；
* 如果我们向用户显示“正在等待交易上链”，但用户等了很久却还没看到交易 hash，这就会质疑我们钱包的处理速度

楼上用户 @jeancky 提出了一个解决方法：将旧交易在其他 fullnode 上重新广播。这个方法在实践上并不可靠。首先，我们需要找到一个或多个备用的 fullnode，这就不太好完成；其次，即使我们有多个 fullnode，在向其他 fullnode 重新广播此交易的时候，仍然可能出现交易广播成功，但无法查询到交易的情况，这并不能从根本上解决问题。

恳请开发人员提供一个有效的解决方法。

**Comment by wubinTron** [comment]
请问您是签名后，过了一段时间才广播么？广播的时候发现DUP_TRANSACTION_ERROR？

**Comment by wubinTron** [comment]
因为同一笔signaturedTransaction的交易broadcasted后会记录再缓存中(不论上不上链)，一定时间内再broadcasted同样的交易，就会返回DUP_TRANSACTION_ERROR。

**Comment by wubinTron** [comment]
查询交易是否上链目前可以通过gettransactionbyid。这么设计当初的考虑是同一笔交易只能被处理和broadcasted一次，不论是失败或者成功了。

**Comment by wubinTron** [comment]
可以通过返回值来判断。返回值是true代表这个交易被效验正确的并且被广播出去了。最终合适上链取决于witness 产块的时候啥时候打包。如果返回不是true，那就没上链。这么做也是较为合理的，因为同一笔没有必要再处理和广播两次。广播返回true只是这笔交易处理正确，它并不知道合适会被打包和上链。

**Comment by wubinTron** [comment]
正常情况下broadcast返回true 一分钟之内就能上链，除非是网络环境极其不好的情况下，才会一直不上链。

**Comment by dengcg0727** [comment]
这个问题解决了？现在运行过程中还是会遇到广播后，链上查不到hash对应的交易，即使是广播后返回的是true.
