### ISSUE TITLE
安卓 使用jar也报错 jar中的class都是 重复的  使用依赖 也报错报找不到这个地址

### ISSUE THREAD

**Issue by qishengtao** [tronprotocol/java-tron#2085]
安卓 使用jar也报错 jar中的class都是 重复的  使用依赖 也报错报找不到这个地址

**Comment by jiangyy0824** [comment]
@qishengtao java-tron的问题吗? java-tron不支持安卓，请问使用的什么开发IDE？有具体错误信息吗？

**Comment by qishengtao** [comment]
嗯好的吧  用的事 androidstuiod 工具开发的  用jar的方式 报错class重复   依赖的方式是报错找不到地址  原来是不支持安卓 谢谢了

**Comment by jiangyy0824** [comment]
@qishengtao 请使用Intellij IDEA.
