### ISSUE TITLE
Big difference in block IDs seen by my Tron node and the test-net explorer

### ISSUE THREAD

**Issue by keeplearning77** [tronprotocol/java-tron#2087]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I setup a tron node to participate as a node in the test-net using the following test-net config.conf

https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf

Note: The p2p version value in this config file is 20190312.

I compared the block number (block id) of the latest block seen by the node against the block numbers show by the test-net (shasta) block explorer. 

https://shasta.tronscan.org/#/blockchain/blocks

The block number as shown by my nodes getnowblock API is way far behind the block ID of the blocks as shown by the explorer.

:~/java-tron$ curl -X POST http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"0000000000086bd2b8bd0bcabb22cf244f6d74c03b0ce3ffc959e4688a56d7fb","block_header":{"raw_data":{"number":551890,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"410e93d739dbb8874f599a8bc29c7faefbf8eeab0f","parentHash":"0000000000086bd1c1f354c28af22e95cc2ea355af18627cd7396f5013797fc7","version":7,"timestamp":1554121092000},"witness_signature":"39961e2718d10db5ab5a22885dd0bd7c1de9352ff7c77c37df438ea94f98ddfe6fbd771901f9c59d5b75a2dcb0331d1526f4352fc61a39b27698af6191272f2401"}}

The block IDs of the latest block as shown by the explorer is: 2757356, 2757355, 2757354 etc.

Could someone please explain why my node is not seeing these blocks?

Is my node participating (or listening) to only a few specific peers in the network? Or is the traffic that my node listens to, and the traffic as shown by the shasta testate explorer totally different?

2. What did you expect to see?

I expected to see almost the same set of blocks in my node, as the ones shown by the test-net explorer URL.

3. What did you see instead?

The block ID of the blocks seen by my node is way far behind the block ID of the blocks shown by the test-net explorer URL.

**Comment by APshenkin** [comment]
shasta != testnet from this config

it's separated test network

you can vote my issue with question how to set up own testnet node and use explorer, faucet etc.  https://github.com/tronprotocol/java-tron/issues/2086

**Comment by keeplearning77** [comment]
Thanks @APshenkin for your answer.

Couple of more questions:

a) Is there an Explorer URL or page that shows the statistics and details of this separated test network, which my node is connected to now?

b) Also, where can I find the reference to a config file by which I can attach my node to the shasta test network?

**Comment by jiangyy0824** [comment]
@keeplearning77 you can use wallet-cli to query block data on testnet. Since this is java-tron project, for shasta-related issues, please seek advice from related team.

**Comment by APshenkin** [comment]
```
a) Is there an Explorer URL or page that shows the statistics and details of this separated test network, which my node is connected to now?
```

It should be test.tronscan.org but it's not working. The only one option is to use wallet-cli as discribed in prev comment

```
b) Also, where can I find the reference to a config file by which I can attach my node to the shasta test network?
```

You can't now see this issue https://github.com/tronprotocol/java-tron/issues/1694

**Comment by jiangyy0824** [comment]
@APshenkin We have provided event subscribe for java-tron. Please refer to https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Event_Subscribe/Tron-eventsubscribe.md

We suggest that you setup a local node and export the trigger data to mongodb or kafka. Then set up the eventquery. It works as another tronscan. You can customize your own reqirement.

We provide a public eventquery of mainet. Hope it will meet your requirement. https://api.tronex.io/transactions

Thanks.

**Comment by APshenkin** [comment]
@jiangyy0824 
Some more notes in issue https://github.com/tronprotocol/java-tron/issues/2086

will duplicate it here

t's a bad answer

There is still no test enviroment, where we can get everything for integration.

Undocumented testnet (notions only in readme)
no explorer (ok, I can run it by myself)
no faucet (how I can take test coins for it?)
yes all API (includes /walletextension)
yes to have your own node
Shasta testnet
yes explorer, but it's not in sync already 3 days https://shasta.tronscan.org/#/
yes faucet
not all API are supported (e.g. /walletextension)
unable to setup own node (to e.g. support walletextension)
So question is still open

How I can test integration with TRON not on mainnet. It's very important to test all cases, but I can't because of this situation.

And all your answers are not helpful.

**Comment by jiangyy0824** [comment]
@APshenkin For shasta issues, please ask help from the shasta team.

For test environment, use this config: https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf

For explorer, we also provide an lternative solution, which is eventquery.

We have provided the deployment document, please read more carefully.

https://github.com/tronprotocol/java-tron/blob/develop/README.md

**Comment by zk19862018** [comment]
+
