### ISSUE TITLE
How to find block size (in number of bytes terms) for test-net traffic?

### ISSUE THREAD

**Issue by keeplearning77** [tronprotocol/java-tron#2090]
I would like to find the size of the block (in terms of number of bytes).

I am using the test-net config for my node.
https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf

The following APIs do not seem to give the block size in terms of number of bytes.

~/java-tron$ curl -X POST http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"0000000000091b746213322f14f70f865d57f5d6f302dbff85e7bdf5a3e9dcde","block_header":{"raw_data":{"number":596852,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"410839c20021492188f92ad9bc0722320d637e12c7","parentHash":"0000000000091b73d47e0010ccfa25f92f1d6e8101660cb0e7142c71c330653d","version":7,"timestamp":1554257400000},"witness_signature":"786305d92047256447bc40f6ada34b198e00bcc65e334d9aef47e2f5bc10e6145f92653fa790596c7477d22d795fb3aa881a064849824a67fca2b623f83fee2e01"}}

~/java-tron$ curl -X POST  http://127.0.0.1:8090/wallet/getblockbyid -d '{"value": "0000000000091b746213322f14f70f865d57f5d6f302dbff85e7bdf5a3e9dcde"}'
{"blockID":"0000000000091b746213322f14f70f865d57f5d6f302dbff85e7bdf5a3e9dcde","block_header":{"raw_data":{"number":596852,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"410839c20021492188f92ad9bc0722320d637e12c7","parentHash":"0000000000091b73d47e0010ccfa25f92f1d6e8101660cb0e7142c71c330653d","version":7,"timestamp":1554257400000},"witness_signature":"786305d92047256447bc40f6ada34b198e00bcc65e334d9aef47e2f5bc10e6145f92653fa790596c7477d22d795fb3aa881a064849824a67fca2b623f83fee2e01"}}

Looks like most of the blocks propagated in the test-net are zero-transaction blocks. 

02:16:57.459 INFO  [TronJClientWorker-0] [net](MessageQueue.java:111) Receive from /47.74.149.105:18888, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
02:16:57.477 INFO  [broad-msg] [net](MessageQueue.java:97) Send to /47.74.149.105:18888, type: FETCH_INV_DATA
invType: BLOCK, size: 1, First hash: 0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
02:16:57.489 INFO  [TronJClientWorker-0] [net](MessageQueue.java:111) Receive from /47.74.149.105:18888, type: BLOCK
Num:596989,ID:0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85, trx size: 0

02:16:57.506 INFO  [TronJClientWorker-1] [net](MessageQueue.java:111) Receive from /47.74.152.210:18888, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
02:16:57.535 INFO  [TronJClientWorker-0] [DB](SnapshotManager.java:289) flush cost:45, create checkpoint cost:45, refresh cost:0
02:16:57.550 INFO  [TronJClientWorker-2] [net](MessageQueue.java:111) Receive from /47.74.159.205:18888, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
02:16:57.551 INFO  [TronJClientWorker-3] [net](MessageQueue.java:111) Receive from /47.88.237.77:18888, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
02:16:57.551 INFO  [TronJClientWorker-0] [witness](WitnessController.java:222) scheduledWitness:41817801760492c0360f56c5a58836f277edb8016e, currentSlot:518085939
02:16:57.551 INFO  [TronJClientWorker-0] [DB](Manager.java:1809) PreValidate Transaction Sign, size:0,block num:596989
02:16:57.551 INFO  [TronJClientWorker-0] [DB](Manager.java:1097) update head, num = 596989
02:16:57.551 INFO  [TronJClientWorker-0] [DB](DynamicPropertiesStore.java:1486) update latest block header id = 0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
02:16:57.551 INFO  [TronJClientWorker-0] [DB](DynamicPropertiesStore.java:1478) update latest block header number = 596989
02:16:57.551 INFO  [TronJClientWorker-0] [DB](DynamicPropertiesStore.java:1470) update latest block header timestamp = 1554257817000
02:16:57.551 INFO  [TronJClientWorker-0] [DB](Manager.java:1592) update solid block, num = 596971
02:16:57.552 INFO  [TronJClientWorker-0] [DB](DynamicPropertiesStore.java:1493) update state flag = 0
02:16:57.552 INFO  [TronJClientWorker-0] [DB](Manager.java:1052) save block: BlockCapsule
[ hash=0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
number=596989
parentId=0000000000091bfc58c25adff5d3695d4041a3b63f590e2dc68c8a3150b651e0
witness address=41817801760492c0360f56c5a58836f277edb8016e
generated by myself=false
generate time=2019-04-03 02:16:57.0
**txs are empty**
]
02:16:57.552 INFO  [TronJClientWorker-0] [DB](Manager.java:1068) pushBlock block number:596989, cost/txs:63/0
02:16:57.552 INFO  [TronJClientWorker-0] [net](NodeImpl.java:1263) update peer 47.88.237.77 block both we have Num:596989,ID:0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
02:16:57.552 INFO  [TronJClientWorker-0] [net](NodeImpl.java:1263) update peer 47.74.159.205 block both we have Num:596989,ID:0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85
02:16:57.552 INFO  [TronJClientWorker-0] [net](NodeImpl.java:1263) update peer 47.74.152.210 block both we have Num:596989,ID:0000000000091bfd11e3a6d1cadd981c95a245351971a90ca96f312dc92f4f85

Still, even if the block does not contain any transactions, the block would have an associated size in terms of the number of bytes? How can I find this value?

Thanks

**Comment by jiangyy0824** [comment]
@keeplearning77 Please refer to https://github.com/tronprotocol/java-tron/blob/develop/src/main/java/org/tron/core/db/Manager.java#L1331, you can add logic on your local fullnode.
Block size is the sum of size of BlockCapsule and the transactions.
