### ISSUE TITLE
广播报签名错误

### ISSUE THREAD

**Issue by kongliang95** [tronprotocol/java-tron#2094]
{"raw_data":{"contract":[{"parameter":{"type_url":"type.googleapis.com/protocol.TransferContract","value":{"amount":100000000,"owner_address":"41aed8b191c49361e54ba57552364bcaf0080e2904","toAddress":"41dfa234a54a2e29d0996557d8f7919d3777efe229"}},"type":"TransferContract"}],"expiration":1554314754000,"ref_block_bytes":"e017","ref_block_hash":"22363f3c30bfb063","timestamp":1554278757201},"signature":["30319d7ed60268059a3f7926473747108325e0f1775e9b012624cadc3847dac815d4b9bf109e9f68b4db9953b54362b9c7bc58e3a3e2700751f5e8689513afb601"],"txID":"2a56e744e6b69295673ead36085e5100865dd1d38853cb1ad883e1e3ee9bbfdd"}
你好，可以看下这数据有什么问题吗

**Comment by jiangyy0824** [comment]
@kongliang95 Please provide the details:
1. your environment, testnet?
2.How you triggered the transaction?
3. The error message in tron.log.

Then we can try to find the root cause.
Thanks.

**Comment by crossle** [comment]
@kongliang95 Whats error info after broadcast ?
