### ISSUE TITLE
Abnormal transaction timestamp + not consistent transaction timestamp

### ISSUE THREAD

**Issue by wxue** [tronprotocol/java-tron#2096]
Please answer these questions before submitting your issue. Thanks!

Description: 
I found out there's about 0.1 - 0.2 probability that the newly generated block contains at least one abnormal transaction timestamp (which is dated back in the year of 1988).

Plus, the transaction timestamps in near blocks are disordered. Meaning, one block could contain transaction with a later timestamp than a transaction timestamp in the future block.

1. What did you do?
If possible, provide a recipe for reproducing the error.

a. https://api.trongrid.io/wallet/getblockbyid?value=00000000007b0166222daa70d79cc569a378c83276cfa035f298e61a5fc9a311

contains abnormal timestamp: 576017389361

b. https://api.trongrid.io/wallet/getblockbyid?value=00000000007b0173913749b76f3bb6fc08a52b2496aab834c7a1f2782261e369

contains abnormal timestamp: 576017420392

2. What did you expect to see?

valid timestamps; better to keep the same timestamp with block timestamp.

3. What did you see instead?

see examples in 1.

**Comment by wubinTRON** [comment]
TimeStamp in a transaction is set by user self. So it isn't really the time when the transaction occurred. The occurred time is in the block. I see it is normal.( "timestamp":1554324630000)

**Comment by wubinTRON** [comment]
"block_header":{
        "raw_data":{
            "number":8061299,
            "txTrieRoot":"583e1a6a412737aa35ad8d0803d42a57a5a112abee87f2a1a2bad1f66627c002",
            "witness_address":"4193a8bc2e7d6bb1bd75fb2d74107ffbda81af439d",
            "parentHash":"00000000007b01725a644430d19a4bf004021175a7faee5f9648c0910343e58b",
            "version":7,
            "timestamp":1554324630000
        },
        "witness_signature":"16ca30722b6e8b47c0b748c9cec5ea5f613872d78df0d69a8eb0a382f90545fb60fced7fba429eca14aae88df2ff77f476ee88f9e3fe6fa1f9d9dcf08bb513ce01"
    }

**Comment by wxue** [comment]
Please see the transaction in the example: 
https://api.trongrid.io/wallet/getblockbyid?value=00000000007b0166222daa70d79cc569a378c83276cfa035f298e61a5fc9a311

{
"ret": [
{
"contractRet": "SUCCESS"
}
],
"signature": [
"90747b5dc23f98a04d9a0c5d350642075619f28e34c5eaa4970a7ef34b44b2096d7e831ca879be529e91608aa376401b67a1984c43ac2aa66ebc1309993c5e7f1c"
],
"txID": "1d8c45d9e93f4ff29112c108e70ea2a5284b9f2ecc8dd2041f2fc205c0deedee",
"raw_data": {
"data": "2053656e742066726f6d2054726f6e57616c6c6574",
"contract": [
{
"parameter": {
"value": {
"exchange_id": 9,
"token_id": "31303030303031",
"expected": 3146447,
"owner_address": "41764ba7e8891cb8d03cd5dc09aa37f88a67859d34",
"quant": 1
},
"type_url": "type.googleapis.com/protocol.ExchangeTransactionContract"
},
"type": "ExchangeTransactionContract"
}
],
"ref_block_bytes": "0164",
"ref_block_hash": "622702d9f30ab71b",
"expiration": 1554324889189,
"timestamp": __576017389361__
},
"raw_data_hex": "0a0201642208622702d9f30ab71b40e5bceea79e2d52152053656e742066726f6d2054726f6e57616c6c65745a69082c12650a38747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e45786368616e67655472616e73616374696f6e436f6e747261637412290a1541764ba7e8891cb8d03cd5dc09aa37f88a67859d3410091a0731303030303031200128cf85c00170b1aebfeae110"
},

**Comment by wubinTRON** [comment]
timeStamp in the transaction is submitted by the user, so it is not really timeStamp of the transaction occurred. So it is not an issue.
