### ISSUE TITLE
请问官方是否提供TPS测试接口？请问哪里有私有测试网络搭建的方法？

### ISSUE THREAD

**Issue by JKinGH** [tronprotocol/java-tron#2112]
请问官方是否提供TPS测试接口？请问哪里有私有测试网络搭建的方法？

**Comment by jiangyy0824** [comment]
For private network deployment, please use the config: https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf, or use deploy scripts: https://github.com/tronprotocol/tron-deployment.

TPS interface is not provided.

**Comment by JKinGH** [comment]
> For private network deployment, please use the config: https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf, or use deploy scripts: https://github.com/tronprotocol/tron-deployment.
> 
> TPS interface is not provided.

Why not use https://github.com/tronprotocol/tron-deployment/blob/master/private_net_config.conf ?
What is the difference between`private_net_config.conf`  and `test_net_config.conf`?
Can you provide the detailed steps to create a private test network? I think the document you provided is not very clear in https://github.com/tronprotocol/java-tron/blob/develop/README.md , I hope to get your help.

**Comment by jiangyy0824** [comment]
@JKinGH private_net_config.conf is the latest public configuration. test_net_config.conf is the template. 

For test network, you just need specify the path of the private_net_config.conf. 
For example,  java -jar FullNode.jar  -c private_net_config.conf

**Comment by JKinGH** [comment]
> @JKinGH private_net_config.conf is the latest public configuration. test_net_config.conf is the template.
> 
> For test network, you just need specify the path of the private_net_config.conf.
> For example, java -jar FullNode.jar -c private_net_config.conf

I want to create a private test network which contains `super nodes` and `normal nodes`(fullnode) ,how to config the private_net_config.conf to run  `super node` and how to config the private_net_config.conf to run  `normal node`(fullnode) .
In addition, is there a developer WeChat group or telegram group?

**Comment by jiangyy0824** [comment]
@JKinGH 
Developer discord group:
https://discord.gg/tHDPVN
https://discord.gg/8HbyrC

For private network deployment. Please refer to 
https://github.com/tronprotocol/java-tron/blob/develop/README.md#running-a-super-representative-node-for-private-testnet.

SR use the same configuration with fullnode.

**Comment by jiangyy0824** [comment]
For more detailed explanation:

https://github.com/tronprotocol/documentation/blob/master/TRX_CN/Tron-doc.md#463-%E6%90%AD%E5%BB%BA%E7%A7%81%E6%9C%89%E7%BD%91%E7%BB%9C

**Comment by JKinGH** [comment]
> For more detailed explanation:
> 
> https://github.com/tronprotocol/documentation/blob/master/TRX_CN/Tron-doc.md#463-%E6%90%AD%E5%BB%BA%E7%A7%81%E6%9C%89%E7%BD%91%E7%BB%9C

Thanks you very much. I have created the private testnet now. But
How to use the wallet API  office offer from https://cn.developers.tron.network/docs/tron-wallet-rpc-api  ? Is there JSON-RPC API ? for example ,how to create new address by RPC API .can you give me some example?  I create address by wallte-cli which connected full node 127.0.0.1:17000
the `getblock` method is successful  in wallet-cli like the screenshot1
![image](https://user-images.githubusercontent.com/41677975/55939344-1c283380-5c70-11e9-8fea-d4285483db48.png)

 I create address fail in postman like the screenshot2
![image](https://user-images.githubusercontent.com/41677975/55939481-6f9a8180-5c70-11e9-9f77-6d3a1ce63e7a.png)

Can I join you wechat to leran about tron?

**Comment by jiangyy0824** [comment]
@JKinGH Please contact our technical support. The wechat account is: 13520256828.
