### ISSUE TITLE
Faucet for testent

### ISSUE THREAD

**Issue by APshenkin** [tronprotocol/java-tron#2120]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
We want to test our integration with Tron. For these we setup testnet node using this conf https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf
But how we can get some test TRX? We don't want to use shasta, because shasta doesn't support `walletextension` API

2. What did you expect to see?
Testnet faucet

3. What did you see instead?
No faucet :(

**Comment by jiangyy0824** [comment]
@APshenkin Please provide your account address. Then we can transfer some test trx to your test account.

**Comment by APshenkin** [comment]
@jiangyy0824 `TFhdp6DBKNUnCCtugWRTc5qGLXTVbQYSRv`

**Comment by jiangyy0824** [comment]
@APshenkin Please check your account balance. You have a large amount of trx now.

**Comment by APshenkin** [comment]
@jiangyy0824 thanks a lot!

**Comment by gituser** [comment]
@jiangyy0824 why don't you set-up faucet and block explorer for official testnet?
It would ease up the process for developers on TRX integration and adoption.

Can you send some TRX to `TSzva1joGXnZSiykkHvV5A37Cdey3eeXjZ` on testnet? 

Thank you.
