### ISSUE TITLE
walletextension api in solidity node not working

### ISSUE THREAD

**Issue by APshenkin** [tronprotocol/java-tron#2123]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
 curl -X POST  http://127.0.0.1:8091/walletextension/gettransactionsfromthis -d '{"account" :{"address" : "413EDECF76875AB79FCF41B39B5B3231830886DC09"}, "offset": 0, "limit": 10}'

returns 405 not allowed error.

This error is because here https://github.com/tronprotocol/java-tron/blob/master/src/main/java/org/tron/core/services/interfaceOnSolidity/http/solidity/HttpApiOnSolidityService.java these routes are not described. They are discribed here https://github.com/tronprotocol/java-tron/blob/master/src/main/java/org/tron/core/services/http/solidity/SolidityNodeHttpApiService.java#L131 but it takes no effect. I tried to add these routes, but now I get resp status code 200 with `null` in body :(

2. What did you expect to see?
Transaction list

3. What did you see instead?
Errors... different errors

**Comment by APshenkin** [comment]
Also there is many warn logs in solidity node like

```
21:04:57.687 WARN  [Thread-14] [DB](Manager.java:1586) latestSolidifiedBlockNum = 0,LatestBlockNum:[845875, 845876, 845877, 845878, 845879, 845880, 845881, 845882, 845883, 845884, 845885, 845886, 845887, 845888, 845889, 845890, 845891, 845892, 845893, 845894, 845895, 845896, 845897, 845898, 845899, 845900, 845901]
--
```

Tested in testnet enviroment

**Comment by APshenkin** [comment]
Found a solution for workaround this.

You have to run node with db.version = 1 in config.
https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf#L8
If it's set to 1 it works.

So there is a problem with db.version 2

**Comment by shydesky** [comment]
These interfaces include "/walletextension/gettransactionstothis" and "/walletextension/gettransactionsfromthis"  have been deprecated

**Comment by APshenkin** [comment]
hm, will they be supported by db.version 1 ? And will be db.version 1 supported in next tron releases? Is there any official announcement?

And what alternative should we use for this? Create our own explorer?

**Comment by gituser** [comment]
@shydesky 
>These interfaces include "/walletextension/gettransactionstothis" and "/walletextension/gettransactionsfromthis" have been deprecated

What does this mean? What do we need to use instead to get list of transactions for an account? Is there an alternative API?

Also I don't get at all what's the difference between FullNode and SolidityNode? Can anybody explain it to me?

**Comment by shydesky** [comment]
> @shydesky
> 
> hm, will they be supported by db.version 1 ? And will be db.version 1 supported in next tron releases? Is there any official announcement?
> 
> And what alternative should we use for this? Create our own explorer?

the db.version 1 will be unsupported in the future,I think.

**Comment by awiech** [comment]
> > These interfaces include "/walletextension/gettransactionstothis" and "/walletextension/gettransactionsfromthis" have been deprecated
> 
> What does this mean? What do we need to use instead to get list of transactions for an account? Is there an alternative API?

I'm also interested in that. What's the alternative to gettransactionsfromthis to list transactions for an account?
