### ISSUE TITLE
How can I get Trx from privatenet

### ISSUE THREAD

**Issue by ZhengFrey** [tronprotocol/java-tron#2132]
I run a SR and FullNode in my own private net。
when I get the witness address balance from the fullnode,it shows as below:
{"type": "AssetIssue","address": "414ee46f8581ee353226ff9c4d372c82d5281021fb","allowance": 150752000000,"is_witness": true,"account_resource": {}} 
Now I want to test transaction in the private net through the witness address,but it always shows "Validate TransferContract error, balance is not sufficient" . 
If the witness address' balance can not be used,I really don't know how to get Trx from the private net .
Can anybody tell me how can I  use my private net to verify the API.
Thank you for youre help

**Comment by jiangyy0824** [comment]
@ZhengFrey In private network, you can set the initial account balance in config file. Please refer to below settings:

```
genesis.block = {
  # Reserve balance
  assets = [
    {
      accountName = "TestA"
      accountType = "AssetIssue"
      address = "THRR7uvFbRLfNzpKPXEyQa8KCJqi59V59e"
      balance = "1000000000000000"
    },
    {
      accountName = "TestB"
      accountType = "AssetIssue"
      address = "TBLZaw93rsnLJ1SWTvoPkr7GVg5ixn2Jv1"
      balance = "1000000000000000"
    },
    {
      accountName = "TestC"
      accountType = "AssetIssue"
      address = "TJg8yZ4Co8RXsHmTWissmSL1VpL7dCybY1"
      balance = "1000000000000000"
    }
  ]
```

**Comment by ZhengFrey** [comment]
@jiangyy0824 Thank you for your answer.

**Comment by zk19862018** [comment]
+
