### ISSUE TITLE
How to calculate fee after offline sign transaction

### ISSUE THREAD

**Issue by crossle** [tronprotocol/java-tron#2133]
I sign transaction offline, and use wallet/getaccountnet get the `freeNetLimit`, how to calcuate the signed transaction fee before send broaddcast transaction？

**Comment by jiangyy0824** [comment]
The transaction fee depends on transaction type, transaction size, account's free bandwidth&energy, account balance, and so on.

Please refer to tron's cost model:
https://github.com/tronprotocol/documentation/blob/master/English_Documentation/TRON_Protocol/TRON_CostModel_Update.MD

**Comment by crossle** [comment]
TranferContract and TransferAssetContact, i wanna to calcuate before send broadcast,  byte array length of a transaction mean the the protobuff `Transaction`'s byte array?

**Comment by crossle** [comment]
Closed?

**Comment by zk19862018** [comment]
+
