### ISSUE TITLE
"PayloadTooLargeError: request entity too large" when run "tronbox test"

### ISSUE THREAD

**Issue by dzarezenko** [tronprotocol/java-tron#2136]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I have tried run unit tests with `tronbox test` command

2. What did you expect to see?

I expected to see unit tests execution results. 

3. What did you see instead?

Error described below...

I am trying to run my unit tests with `tronbox test` command, but received this error:

```
Deploying contracts to development network...
ERROR: Request failed with status code 413
```

In the __Tron Quickstart__ console:
<img width="938" alt="Screen Shot 2019-04-11 at 14 39 00" src="https://user-images.githubusercontent.com/148570/55954540-9acca300-5c67-11e9-9509-f76bfa451b9c.png">

How can I fix this issue? Thanks!

**Comment by jiangyy0824** [comment]
@dzarezenko This is not a  java-tron issue. Please ask help from tronbox team.
