### ISSUE TITLE
[Error] Cannot deploy contract onto Testnet

### ISSUE THREAD

**Issue by mrsirja** [tronprotocol/java-tron#2146]
## What I am doing
I am trying to deploy smart contract onto testnet shasta. But whenever I try to deploy a contract it always shows OUT_OF_ENERGY error.

## Expected Behaviour
Contact should be deployed successfully onto Testnet. 

## Actual Behaviour
When I try to migrate a smart contract using tronbox it shows below error.
```
ERROR: Contract Election has not been deployed on the network.
For more details, check the transaction at:
https://api.shasta.trongrid.io/wallet/gettransactionbyid?value=1deabb8330f39f6a153781fb7e3ce83c2ba2c31914e14d5d99fc37db95e20038
If the transaction above is empty, most likely, your address had no bandwidth/energy to deploy the contract.
```
Even if I have enough energy for deploying the smart contracts.

This is the configuration that I had added in the tronbox.js file.
```
shasta: {
      privateKey: 'edec2a9abe800b8f71288cb0315b682e8257f2c7553a3503cae7b4a362cd787f',
      consume_user_resource_percent: 100,
      fullNode: "https://api.shasta.trongrid.io",
      solidityNode: "https://api.shasta.trongrid.io",
      eventServer: "https://api.shasta.trongrid.io",
      network_id: "*"
    }
```

And this solidity contract code that i want to deploy in the test network.
``` 
pragma solidity ^0.4.25;

contract Election{

    struct Candidate{
        uint id;
        string name;
        uint voteCount;
    }
    mapping (uint => Candidate) public candidates;
    uint public candidatecount;
    mapping (address => bool) public voter;

    event eventVote(
        uint indexed _candidateid
    );

    function addCandidate(string _name) public {
        candidatecount++;
        candidates[candidatecount] = Candidate(candidatecount,_name,0);
    }

    function vote(uint _candidateid) public {
        require(!voter[msg.sender]);
        require(_candidateid > 0 && _candidateid <= candidatecount);
        voter[msg.sender] = true;
        candidates[_candidateid].voteCount ++;
        emit eventVote(_candidateid);
    }

}
```

Any help would be highly appreciated.

**Comment by fakel** [comment]
The same issue here, do not matter the size or complexity of the code, event the startup codes, I'm not able to deploy them due to OUT_OF_ENERGY error.

I'm thinking that maybe there is too much TRX freeze on test network, idk.

**Comment by jiangyy0824** [comment]
@mrsirja @fakel The energy limit proposal on main-net doesn't take effect on shasta, because the block height of shasta doesn't reach. 

Since this is shasta related issue, please ask solution from them.

**Comment by mrsirja** [comment]
@jiangyy0824 Where can I ask them?

**Comment by fakel** [comment]
@mrsirja probably as @jiangyy0824 state, the main-net doesn't take effect on shasta, however, after some debugging I found some messages that seem to state a limit on energy to around ~19k and a single store operator consuming around ~20k and dropping the transaction there.

Trying the same transaction on main net went well, without problems so, yes, probably a Shasta problem.

**Comment by mrsirja** [comment]
Hello @fakel and @jiangyy0824, Thank you for your kind response. You both are right. There is a problem with Shasta energy limit. I tried to deploy a contract using a newly created account without any energy. So deployment of a contract will burn some TRX and it is working successfully.

Because I found a solution, I'm closing this issue now.

**Comment by gfijrb** [comment]
> Hello @fakel and @jiangyy0824, Thank you for your kind response. You both are right. There is a problem with Shasta energy limit. I tried to deploy a contract using a newly created account without any energy. So deployment of a contract will burn some TRX and it is working successfully.
> 
> Because I found a solution, I'm closing this issue now.

What was your solution?

**Comment by okorieebube** [comment]
> Hello @fakel and @jiangyy0824, Thank you for your kind response. You both are right. There is a problem with Shasta energy limit. I tried to deploy a contract using a newly created account without any energy. So deployment of a contract will burn some TRX and it is working successfully.
> 
> Because I found a solution, I'm closing this issue now.

Uhm, @ghost can you paste your solution here? Thanks.

**Comment by harshnambiar** [comment]
> > Hello @fakel and @jiangyy0824, Thank you for your kind response. You both are right. There is a problem with Shasta energy limit. I tried to deploy a contract using a newly created account without any energy. So deployment of a contract will burn some TRX and it is working successfully.
> > Because I found a solution, I'm closing this issue now.
> 
> Uhm, @ghost can you paste your solution here? Thanks.

Did you or anyone find out? I am looking for answers now as well :)
