### ISSUE TITLE
My TRX can not get unfreeze

### ISSUE THREAD

**Issue by silravend** [tronprotocol/java-tron#2165]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I freeze my TRX for another contract address, 4000 TRX for bandwidth, and 3000 TRX for engine, my address is TNi7QoSGheU2iKZR3VYTcJ1XwmNAZmw7G3, and the target contract address is TLvUe7hvZsvYyfmZ3NkTHrMBwtU4pXn83K.

2. What did you expect to see?
I wish I can unfreeze them.

3. What did you see instead?
I see "Unable to unfreeze TRX. This could be caused because the minimal freeze period hasn't been reached yet.", I don't know why, is that because the contract I executed selfdestruct.

**Comment by silravend** [comment]
so now how I can get unfreeze of the 7000 TRX?

**Comment by jiangyy0824** [comment]
@silravend The frozen trx can be unfreezed after three days.

**Comment by silravend** [comment]
Yeah, I know, but my trx has expired for 3 days

**Comment by renchenchang** [comment]
UnfreezeBalance owner_address  BANDWIDTH or ENERGY receiver_address
