### ISSUE TITLE
How to watch my account for transactions

### ISSUE THREAD

**Issue by stone89son** [tronprotocol/java-tron#2178]
Hi.
I am looking for an example of checking transactions that occur on my account.
Clarification: I am building a trading platform. When a user orders a Buy token, they will have to send TRX to my TRONX account. The part I'm building is getting that realtime order information via TRONX account and adding it to the database.

Thank for reply.

**Comment by jiangyy0824** [comment]
@stone89son We provide service to subscribe transactions on main-net. 

To meet your needs, you can setup your own event subscribe server. For more details, please refer to https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Event_Subscribe/Tron-eventsubscribe.md

We also provide a public event query service. You could use the http api to query the realtime transactions on main-net.

For example, the transaction id on main-net:
https://tronscan.org/#/transaction/403b952a5873225837eec5b1e38b035c2ab60dd0add39750844c93596fdaccb5

From: TWzYGbDtBRkFXFFykixNx1NddBATJHdBQV
to:  MYFmRuAA1t4zHQUuoYh1Fqe1diBZM4
amount: 551 trx

Using the eventquery service to get the transaction info:
https://api.tronex.io/transactions/403b952a5873225837eec5b1e38b035c2ab60dd0add39750844c93596fdaccb5

Then filter the transactions with fromAddress or toAddress.

**Comment by stone89son** [comment]
Thank for help, I think my case use event-plugin is good, but must install tronx node and kafka
https://github.com/tronprotocol/event-plugin
So, I want to custom event-plugin.
I can custom event-plugin use Websocket Client send new transaction to my Websocket Server?

**Comment by jiangyy0824** [comment]
@stone89son We will also provide built-in message queue on version 3.6(to be release, the code is in develop branch). With built-in message queue, you don't need installing kafka or other event plugin.
Please refer to https://github.com/tronprotocol/TIPs/issues/28

With built-in message queue, you can subscribe the events by socket.

**Comment by jiangyy0824** [comment]
@stone89son The end of May. Please pay attention to tron's update.

**Comment by zk19862018** [comment]
+

**Comment by BeycanDeveloper** [comment]
We realized that this was a big gap in the Tron Blockchain network without WebSockets, so we built [TronSocket.com](https://tronsocket.com). Now it's easy to listen to Tron Blockchain events via WebSocket.
