### ISSUE TITLE
jitpack 全部是编译失败的依赖

### ISSUE THREAD

**Issue by mtdp** [tronprotocol/java-tron#2183]
按照官方操作步骤，maven 更新不到最新的依赖。

Using maven:

...
<repositories>
  <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
  </repository>
</repositories>
...
<dependency>
    <groupId>com.github.tronprotocol</groupId>
    <artifactId>java-tron</artifactId>
    <version>develop-SNAPSHOT</version>
</dependency>

查看jitpack 最后都是编译失败，没有可用的maven 依赖。

https://jitpack.io/com/github/tronprotocol/java-tron/Odyssey-v3.5/build.log
https://jitpack.io/com/github/tronprotocol/java-tron/Odyssey-v3.5.0.1/build.log
https://jitpack.io/com/github/tronprotocol/java-tron/Odyssey-v3.2.5/build.log

**Comment by jiangyy0824** [comment]
@mtdp Do you want to include java-tron as dependency?  If not, use "./gradlew build" to compile.

**Comment by mtdp** [comment]
好的，谢谢。
