### ISSUE TITLE
trx 支持hd钱包吗

### ISSUE THREAD

**Issue by mtdp** [tronprotocol/java-tron#2194]
如题，如果支持公私钥推导有什么样的类库，我看wallet-cli，只有私钥推导公钥及地址；没有找到从seed到私钥的相关方法，谢谢！

**Comment by jiangyy0824** [comment]
@mtdp Tron doesn't support hd wallet.

**Comment by mtdp** [comment]
https://github.com/tronprotocol/TIPs/blob/master/tip-01.md
tips协议里不是说支持吗？
