### ISSUE TITLE
[BUG] contract.abi is undefined when the contract is created by another contract instead of being deployed

### ISSUE THREAD

**Issue by Cashik** [tronprotocol/java-tron#2201]
I have Factory contract. There is a function in it creating another contract. The function returns the contract address. So far so good. But when I
await tronWeb.contract().at(contractAddress)
to get the new contract,

TypeError: Cannot read property 'entrys' of undefined
      at e.<anonymous> (node_modules/tronweb/dist/webpack:/src/lib/contract/index.js:198:39)

is thrown.
I looked at the tronweb code, it shows that this.loadAbi(contract.abi.entrys); threw the error. Obviously contract.abi is undefined in this case. Not sure if this is java-tron problem or tronweb problem.

[Original issue](https://github.com/tronprotocol/tron-web/issues/120)

**Comment by jiangyy0824** [comment]
@Cashik This is tronweb related problem. Please ask help from tronweb team.

**Comment by Cashik** [comment]
> @Cashik This is tronweb related problem. Please ask help from tronweb team.

Please see the link to the original issue.

**Comment by jeancky** [comment]
@Cashik  If you create a contract in another contract, there is no way for TRON to noted your new contract's abi.

So, TronWeb must deal this undefined problem.
