### ISSUE TITLE
my TRX freeze for ENERGY and BANDWIDTH for another contract address can't be unfreeze after 3 days

### ISSUE THREAD

**Issue by silravend** [tronprotocol/java-tron#2210]
Please answer these questions before submitting your issue. Thanks!

What did you do?
I freeze my TRX for another contract address, 4000 TRX for bandwidth, and 3000 TRX for engine, my address is TNi7QoSGheU2iKZR3VYTcJ1XwmNAZmw7G3, and the target contract address is TLvUe7hvZsvYyfmZ3NkTHrMBwtU4pXn83K.

What did you expect to see?
I wish I can unfreeze them.

What did you see instead?
I see "Unable to unfreeze TRX. This could be caused because the minimal freeze period hasn't been reached yet.", I don't know why, is that because the contract I executed selfdestruct.

Maybe it is because I call the 'killdestruct' function on the contract TLvUe7hvZsvYyfmZ3NkTHrMBwtU4pXn83K, so when I try to unfreeze the TRX, it returns:

> await tronWeb.transactionBuilder.unfreezeBalance("ENERGY", "TNi7QoSGheU2iKZR3VYTcJ1XwmNAZmw7G3", "TLvUe7hvZsvYyfmZ3NkTHrMBwtU4pXn83K").catch(err => {
        console.log(err);
    })

class org.tron.core.exception.ContractValidateException : AcquiredDelegatedFrozenBalanceForEnergy[0] < delegatedEnergy[3000000000],this should never happen

**Comment by otakuinny** [comment]
Hi. Are you still unable to freeze your TRX? If so, can you post the code in the "killdestruct" function of your contract? I'll see if I can help you.
Thanks.

**Comment by silravend** [comment]
It's here

> function kill() external onlyOwner {
       selfdestruct(owner);
    }

**Comment by otakuinny** [comment]
Thanks. I'll test this and will keep you posted in 3 days.

**Comment by otakuinny** [comment]
Hi. I tested this on Mainnet and can confirm that I am unable to unfreeze trx delegated to a contract that has executed a selfdestruct function.
@renchenchang, can you please take a look ASAP. This is a big vulnerability. 
Steps to reproduce.

1. Create a contract that has the following function "kill". 
address public owner;
modifier onlyOwner()
{
     require(msg.sender == owner);
     _;
}
function kill() external onlyOwner {
selfdestruct(owner);
}

2. Delegate TRX for energy to this contract from an address that is not the creator of the contract
3. Call the kill function of the contract from the contract creator's address. This will self destruct the contract and sends any funds in the contract to the caller.
4. Try unfreezing TRX delegated to this contract after 3 days. You'll see the following response.

code: "CONTRACT_VALIDATE_ERROR"
message: "contract validate error : Account[<contract address here>] not exists"
success: false
transaction: ""

Thanks.

**Comment by silravend** [comment]
thanks @otakuinny the issue is exist, someone please fix it.

**Comment by otakuinny** [comment]
Hi @tronfoundation. This is a serious vulnerability. Please look into this ASAP.
Thank you.

**Comment by renchenchang** [comment]
will fix it in next version

**Comment by otakuinny** [comment]
Thanks.

**Comment by silravend** [comment]
May I ask when it will be fixed? what 's the time of next version?

**Comment by jeancky** [comment]
refer to https://github.com/tronprotocol/java-tron/pull/2290

**Comment by jeancky** [comment]
the fix will be released in next version, which is 3.6.0
