### ISSUE TITLE
Can't freeze TRX longer than 3 days.

### ISSUE THREAD

**Issue by otakuinny** [tronprotocol/java-tron#2222]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Try using the FreezeBalance FULLNODE HTTP API with "Frozen Duration" value as 7. You'll receive a  really ambiguous error "class org.tron.core.exception.ContractValidateException : frozenDuration must be less than 3 days and more than 3 days"

2. What did you expect to see?

I expected to see TRX frozen for the specified duration

3. What did you see instead?

An error "class org.tron.core.exception.ContractValidateException : frozenDuration must be less than 3 days and more than 3 days"

Thanks.

**Comment by renchenchang** [comment]
Frozen Duration must be 3 now. It means you can UnFreezeBalance after 3 days at least. If you do'n UnFreezeBalance after 3 days, the frozen TRX will be frozen forever.

**Comment by otakuinny** [comment]
Thanks @renchenchang. I understand that it is only 3 days now. Can you allow the API to freeze for longer than 3 days?

**Comment by otakuinny** [comment]
@renchenchang, can you change the API to allow for longer freeze period in the next version? Thanks.

**Comment by jeancky** [comment]
@otakuinny 
What he means is that after you start freezing, you can't unfreeze within  <3 days. Of course, you can also unfreeze after a long time. In this period of time. These TRX is always frozen and can always provide you with energy/bandwidth.

**Comment by otakuinny** [comment]
@jeancky Thanks. I wanted the ability to lock the TRX for X days with no option to unfreeze even if I wanted to. Isn't that the whole point of having a number of days parameter in the function.

**Comment by jeancky** [comment]
@otakuinny , "frozen duration must not be less than MAX days and more than MIN days."
Right now, the MAX and MIN values are both 3.  

There is a workaround, you freeze 1 trx every other day (or 2 days), which will make all your frozen TRX unreachable.

**Comment by otakuinny** [comment]
@jeancky, thank you. This is for a dapp. Can you please make sure this gets fixed in 3.6.0?

**Comment by jeancky** [comment]
@otakuinny, hey.  it's more complicated than "fixed".

First, we need to add a proposal to modify the value of this MAX.
Second, we have to choose a more appropriate MAX, then initiate a proposal, and all Witness votes pass.
Than, u can use a new MAX freeze days.

As far as I know, this is not a part of 3.6.0

u can get more details from @renchenchang

**Comment by otakuinny** [comment]
@jeancky I see. So, this needs to be proposed and voted on first. Thanks for the clarification.

**Comment by taihaofu** [comment]
Close for now. Please feel free to reopen this issue if you still have questions.
