### ISSUE TITLE
Build error new RevokingTuple(dbSource, key)

### ISSUE THREAD

**Issue by ItFlyingStart** [tronprotocol/java-tron#223]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I have followed the instruction described on http://wiki.tron.network/en/latest/quick_start.html

2. What did you expect to see?
A working demo/test version.

3. What did you see instead?
I get the next build error when I try to run it.

Error:(47, 42) java: constructor RevokingTuple in class org.tron.core.db.AbstractRevokingStore.RevokingTuple cannot be applied to given types;
  required: no arguments
  found: org.tron.common.storage.leveldb.LevelDbDataSourceImpl,byte[]
  reason: actual and formal argument lists differ in length

![buiderror](https://user-images.githubusercontent.com/5562995/37268391-faa6e472-25c5-11e8-85af-5c12ef5fd0d4.png)

**Comment by Rovak** [comment]
You need to enable `Annotation processing` in Intellij

Preferences (Ctrl + Alt + S) -> Build, Execution, Deployment -> Compiler -> Annotation Processors -> Enable annotation processing. 

Make sure you have the Lombok plugin for IntelliJ installed!

1. Preferences -> Plugins
2. Search for "Lombok Plugin"
3. Click Browse repositories...
4. Choose Lombok Plugin
5. Install
6. Restart IntelliJ

[Source](https://stackoverflow.com/a/27430992/916247)

**Comment by zhaohong** [comment]
@Rovak  thanks!

**Comment by ItFlyingStart** [comment]
Thank you. This has resolved my issue. Another question: which main class should I use? Because org.tron.example.Tron (described in http://wiki.tron.network/en/latest/quick_start.html) doesn't exist.
