### ISSUE TITLE
TRON 

### ISSUE THREAD

**Issue by lihuawei321** [tronprotocol/java-tron#2266]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I am calculating theTRON's memory size and capacoty.

2. What did you expect to see?
I want to know the size of each transaction in TRON
I want to know how many smart contracts are there in TRON.
I want to know the hardware configuration of the running node of TRON.
3. What did you see instead?

**Comment by jiangyy0824** [comment]
@lihuawei321 

1. Transaction size is not constant.  And there is no exported interface to query it.  You can calculate it using the method TransactionCapsule::getSerializedSize(). 

2. The count of smart contracts is not constant. There are two kinds of contract, system and developer's. Which do you mean? 

3. Please refer to
https://github.com/tronprotocol/documentation/blob/master/TRX/Tron-overview.md#31-recommended-hardware-specifications
