### ISSUE TITLE
RIPEMD160 in TVM doesn't implement the proper hash

### ISSUE THREAD

**Issue by ColonelJ** [tronprotocol/java-tron#2272]
The precompiled contract for RIPEMD160 seems to do some double hashing with SHA256 instead of actually computing the RIPEMD160 hash.  This will produce the wrong output compared to Ethereum chains (or whatever specific purpose you need this hash for), and it should be fixed ASAP.

https://github.com/tronprotocol/java-tron/blob/e9e78b056b0380e6ae141c0f9ba0baef1348936c/src/main/java/org/tron/common/runtime/vm/PrecompiledContracts.java#L337

**Comment by jeancky** [comment]
@ColonelJ , Hey
We've mention in our [documentation](https://github.com/tronprotocol/documentation/) about "we don't support RIPEMD160 yet."

We're evaluating about deal this issue. It should be done in next version after 3.6.0

**Comment by ColonelJ** [comment]
What was the decision regarding this?  It will not be supported?

**Comment by jeancky** [comment]
> What was the decision regarding this? It will not be supported?

@ColonelJ , hi, TRON's implementation of RIPEMD160 is 'twice Sha256Hash()' now. and, we have to keep it in that way. Otherwise it might bring unknown problem to those who have already used this instruction. 

We are planning to add a new instruction TRIPEMD160 which is real RIPEMD160 algorithm in TRON's solidity compiler.

**Comment by ColonelJ** [comment]
Ah, I suspected that might be the case.

> We are planning to add a new instruction TRIPEMD160 which is real RIPEMD160 algorithm in TRON's solidity compiler.

Well, that's one way to solve it, but it's not an ideal situation you've gotten yourself into by not implementing RIPEMD160 properly in the first place.  With this you will get different values for RIPEMD160 depending on which Solidity compiler version you use.
