### ISSUE TITLE
Tronscan: problems to send trx to exchange (binance)

### ISSUE THREAD

**Issue by knantje** [tronprotocol/java-tron#2281]
Hello,

A while ago I bought trx and send it to my tronscan wallet on my pc. Now I wanted to send some trx to the exchange in order to check of it works. But I have no idea how to do this.

When I open my tronscan wallet and put on the button 'send' I get a screen with: Create Raw transfer. When I fill in the recipient address and the amount of trx I want to send, I can click on the button 'create' and then a very long code appears.

But what do I have to do next in order to sent my trx?

Hopefully someone can help me!

Kind regards, Ard Jan

**Comment by Realtronlink** [comment]
fisrt of all, make sure your access website is https://tronscan.org/#/

secondly, if you still have the problem,you can submit your question in tronscan. the url is https://support.tronscan.org/hc/en-us/requests/new

Attaching the corresponding screenshot will make your problem solved faster.
