### ISSUE TITLE
after build ok; gradlew run FAIL.

### ISSUE THREAD

**Issue by EvertonMelo** [tronprotocol/java-tron#2292]
Please answer these questions before submitting your issue. Thanks!

**os:** Fedora 30
**kernel:** linux 5.1.5-300.fc30.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

oracle jdk 8; 

**Java =** 
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
**javac =**  1.8.0_211

1. What did you do?
after buid java-tron:

gradlew build -x test ( result OK ) 
 ./gradlew run -Pwitness=true ( fail )

2. gradlew run, details?
./gradlew run -Pwitness=true
Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :generateProto UP-TO-DATE
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.

> Task :run FAILED
******** begin to pop revokingDb ********
******** before revokingDb size:0
******** end to pop revokingDb ********

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/java/jdk1.8.0_211-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
6 actionable tasks: 1 executed, 5 up-to-date

3. What did you see instead?
build ok;
gradlew run ( fail not install )

**Comment by shydesky** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> **os:** Fedora 30
> **kernel:** linux 5.1.5-300.fc30.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux
> 
> oracle jdk 8;
> 
> **Java =**
> java version "1.8.0_211"
> Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
> **javac =** 1.8.0_211
> 
> 1. What did you do?
>    after buid java-tron:
> 
> gradlew build -x test ( result OK )
> ./gradlew run -Pwitness=true ( fail )
> 
> 1. gradlew run, details?
>    ./gradlew run -Pwitness=true
>    Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> 
> > Task :generateProto UP-TO-DATE
> > Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.
> 
> > Task :run FAILED
> > ******** begin to pop revokingDb ********
> > ******** before revokingDb size:0
> > ******** end to pop revokingDb ********
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':run'.
> 
> > Process 'command '/usr/java/jdk1.8.0_211-amd64/bin/java'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 41s
> 6 actionable tasks: 1 executed, 5 up-to-date
> 
> 1. What did you see instead?
>    build ok;
>    gradlew run ( fail not install )

Hi, EvertonMelo, Thank you for your issue!
I try to reproduce the problem as your description as follows:
1、os env:
![env](https://user-images.githubusercontent.com/3627357/59249579-b4826a80-8c57-11e9-95ac-c002db30ba42.png)
2、gradlew run：
![run](https://user-images.githubusercontent.com/3627357/59249618-c6640d80-8c57-11e9-9e33-61256338366c.png)
3、java-tron's run log
![log](https://user-images.githubusercontent.com/3627357/59249652-d8de4700-8c57-11e9-92c7-03e2cfbbbfed.png)

so, i think it is normal.
Do you have any problem for now?
