### ISSUE TITLE
Suggestion: Documentation and comment review

### ISSUE THREAD

**Issue by khuezy** [tronprotocol/java-tron#23]
We understand that English is not your native language and we appreciate you trying your best to communicate with us in English.

But may I suggest that you tag us native English speaking contributors into the PR so we can review and make grammatically/syntactical/etc... recommendations? That way it improves the documentation without it needing additional amending PRs.

Thanks!

**Comment by thePerfesser** [comment]
Great suggestion. I too would be happy to contribute to this effort.

**Comment by ruchern** [comment]
I would love to contribute for the translation as well.

**Comment by ernesthilvano** [comment]
me too

**Comment by phadnisvinay30** [comment]
same here!!

**Comment by ybhgenius** [comment]
Hello,

Thanks for your participation.

Please check this link:

https://crowdin.com/project/trondocs

You can translate or correct relevant texts through this link.

We will reward you according to your contribution.

Best Regards

Boheng Yang

**Comment by Rovak** [comment]
Translations will be done using crowdin, follow the link above to help out with translating
