### ISSUE TITLE
how to get latest block number, getnowblock returns too many data include tx list.

### ISSUE THREAD

**Issue by jerry-sl** [tronprotocol/java-tron#2307]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Add http api getlatestblocknumber or 

2. What did you expect to see?
 just return latest block number, not tx list.

3. What did you see instead?
data include tx list and tireroot.

**Comment by zk19862018** [comment]
all the api we support is listed at https://tronprotocol.github.io/documentation-EN/Tron-http/
