### ISSUE TITLE
看了下大部分都是垃圾代码提交

### ISSUE THREAD

**Issue by chencore** [tronprotocol/java-tron#2310]
大部分提交都是是加点注释、改点字符串！忽悠啊！！

**Comment by taihaofu** [comment]
长沙有很多优秀的眼科医院，特意帮您查了一下，推荐给您：

[长沙湘江爱尔眼科医院](https://map.baidu.com/poi/长沙湘江爱尔眼科医院/@12571240,3259032,13z?uid=7040d6547f3f620c7f29bdd1&primaryUid=7040d6547f3f620c7f29bdd1&ugc_type=3&ugc_ver=1&device_ratio=2&compat=1&querytype=detailConInfo&da_src=shareurl)
[长沙宏朗眼科医院](https://map.baidu.com/poi/长沙宏朗眼科医院/@12580101.784872614,3257783.778338641,11z?uid=05e028b1e04f5c4f9e82eab1&primaryUid=704298936502113934&ugc_type=3&ugc_ver=1&device_ratio=2&compat=1&querytype=detailConInfo&da_src=shareurl)

衷心祝您早日康复

**Comment by chencore** [comment]
最近的commit，自己仔细看看！
