### ISSUE TITLE
Now (block.timestamp) null during block mined

### ISSUE THREAD

**Issue by julesGoullee** [tronprotocol/java-tron#2321]
When a contract is deploying block.timestamp (alias of) now is 0. But when call some reading method later it becomes the right value in second in Unix time. On Ethereum now when you create tx write in the chain is the timestamp of the block, it's necessary to do some stuff time-based need time proof.
To explain more clearly an example:
```solidity
pragma solidity ^0.4.25;

contract Time {

  uint256 startTime = block.timestamp;
  uint256 constructorTime;
  uint256 nonce = 0;
  uint256 writeTime;

  constructor() public {

    constructorTime = block.timestamp;

  }

  function readOnly() public view returns (uint256, uint256, uint256, uint256, uint256){

    return (
    startTime,
    constructorTime,
    nonce,
    writeTime,
    block.timestamp
    );

  }

  function write() public {

    nonce = nonce + 1;
    writeTime = block.timestamp; // let's call it unixTime2 in test suite

  }

}
```

```javascript
const Time = artifacts.require('./time.sol');

contract('Time', () => {

  before(async () => {

    this.time = await Time.deployed();

  });

  it('Get wrong time', async () => {

    const read = await this.time.readOnly();
    // read = 0 0 0 0 unixTime1

    await this.time.write(); // write in contract unixTime2

    const read1 = await this.time.readOnly();
    // read1 = 0 0 1 0 unixTime3
    // expect: read1 = 0 0 1 unixTime2 unixTime3
    // And also better expect constructorTime and startTime to be the correct unixTime not 0
  
  });

});
```

**Comment by taihaofu** [comment]
Hi @julesGoullee , I tested your code using compiler 0.4.25 on remix and execute contract on my private testnet using master branch.
Here is my result using command line tool:
```
triggerContract TDwiSk5bydC7MqgJKN9h8Sre7wa5VU3ZyT readOnly() # false 1000000000 0 0 #

  000000000000000000000000000000000000000000000000000000005d0c5a2d
  000000000000000000000000000000000000000000000000000000005d0c5a2d
  0000000000000000000000000000000000000000000000000000000000000000
  0000000000000000000000000000000000000000000000000000000000000000
  000000000000000000000000000000000000000000000000000000005d0c5a3f
```
Then
```
triggerContract TDwiSk5bydC7MqgJKN9h8Sre7wa5VU3ZyT write() # false 1000000000 0 0 #
triggerContract TDwiSk5bydC7MqgJKN9h8Sre7wa5VU3ZyT readOnly() # false 1000000000 0 0 #
  000000000000000000000000000000000000000000000000000000005d0c5a2d
  000000000000000000000000000000000000000000000000000000005d0c5a2d
  0000000000000000000000000000000000000000000000000000000000000001
  000000000000000000000000000000000000000000000000000000005d0c5aa2
  000000000000000000000000000000000000000000000000000000005d0c5aba

```

Seems get the same result on etherem. Could you provide your compiler version and testing environment information?

**Comment by jeancky** [comment]
I've test in the mainnet. I cann't reproduce this issue.

this is the contract address, you can verify it.
TBH8pfYFW42iGsrJCMiLLcVf1qy9MrXHQg

**Comment by julesGoullee** [comment]
@jeancky if I open an issue it's not to break your ball is to help you. So to be polite usually we waiting for the answer of the creator before closing it.
I use the same compiler as you 0.4.25. I test it through tronbox with trontools/quickstart:2.0.15. 
I don't really understand your result `# false 1000000000 0 0 #` all of the values are `uint`.
The point is when I 'write to chain' if I access to `block.timestamp` it's 0. If I 'read the chain'  with view method the timestamp is correct.

**Comment by taihaofu** [comment]
@julesGoullee , I use [tronprotocal/wallet-cli](https://github.com/tronprotocol/wallet-cli) to interact with our chain. `triggerContract TDwiSk5bydC7MqgJKN9h8Sre7wa5VU3ZyT readOnly() # false 1000000000 0 0 #` is a command to trigger contract with feelimit=1000000000, callvalue=0 and tokenvalue =0. 
my result convert to your test case can be:
```
     //unixTime0 the time you deploy your contract
     //unixTime1 first time call readOnly()
     read   = unixTime0 unixTime0    0     0          unixTime1

     // unixTime2 write in contract  by calling write()
     // unixTime3 second time call readOnly()
     read1 = unixTime0 unixTime0     1     unixTime2  unixTime3
```
Also tested on main net, I get the same answer.
This is as expected and the same as ethereum, which means you can set block.timestamp in a constructor or directly when declare a variable. Is this also your expected result on your side?

I think it might be a problem by using tronbox with trontools/quickstart:2.0.15, if you still have this problem. You can report to there repo to let them have a check on it. 

Thanks,
Taihao

**Comment by julesGoullee** [comment]
ok it was my first supposition it's not from java-tron but from tronbox/ quicktsart, I already made an issue in tronbox repo devs told me I need to post here. Probably we need to talk together about this, can you arrange this maybe in discord with all teams to find who need to manage it ?
