### ISSUE TITLE
transaction is confirmed but not success 

### ISSUE THREAD

**Issue by haidt18** [tronprotocol/java-tron#2334]
I sent TRX10 token it was confirmed but there is no `Result : SUCCESS` field from its receipt.
I see some other transaction was confirmed and there is `Result : SUCCESS`.
So what is different between them? and whether my transaction is success or not ?
1. What did you do?
I sent TRX10 Token transaction at https://tronscan.org/#/transaction/cd12d0f0eebdce359e43b5d0b3091c99c4201942c8e6a40ac8ee9950851ec4aa

2. What did I expect to see?
`Result : SUCCESS` from tronscan.org and ` "contractRet": "SUCCESS"` from its receipt when I call `getTransaction()`

3. What did I see instead?
I see it was confirmed but there is no `Result : SUCCESS` field on the tronscan.org and there is no ` "contractRet": "SUCCESS"`  from its receipt.

thanks

**Comment by shydesky** [comment]
you should not judge whether the transaction is success or not according to the "contractRet" value because it is not a part of consensus data . you can confirm the transaction is success by judging
whether the transcation is on the blockchain.

**Comment by haidt18** [comment]
@shydesky thanks for your reply, but what actually is the `contractRet`? and what is different between these 2 transactions (tx with `contractRet` and without `contractRet`) ?
thanks

**Comment by yuliazo** [comment]
Same problem.
I didn't get `contractRet` on any of my transaction although the transaction is confirmed.
Example: 
https://shasta.tronscan.org/#/transaction/19d5f29ab75f7ba5c1a91fcf542a6b4b062600de8fc708df020b7e5163ee9b58

@shydesky if need to confirm the transaction by judging only by blocks
- how much blocks needs to wait?
- what will happen if the transaction will failed at the end?
- what is actually is `contractRet` if not for the transaction status? 

Thank you.

**Comment by jeancky** [comment]
@yuliazo ,

**Comment by athamidn** [comment]
@jeancky 
Why did you close this without any answer?! what actually is `contractRet`?

**Comment by KI5FPL** [comment]
@athamidn `contractRet` only applies for EVM based transactions. createsmartcontract and triggersmartcontract.

**Comment by manish8561** [comment]
How we get successful transaction from the network?

**Comment by mr-mr7** [comment]
The problem was solved?
How to check that the transaction was successful?
