### ISSUE TITLE
使用快照数据，无法继续同步区块

### ISSUE THREAD

**Issue by asdzxc7728** [tronprotocol/java-tron#2335]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
从https://backup.trongrid.io/ 下载数据到fullnode下的out_put文件夹下，启动fullnode，区块高度不增长

2. What did you expect to see?
希望使用快照数据，可以继续同步区块

3. What did you see instead?
使用快照数据，启动后无法继续同步区块

**Comment by jerry-sl** [comment]
一样的问题。 请问你有解决这个问题吗？ @asdzxc7728

**Comment by XiangyueMeng** [comment]
Can you provide tron.log and the branch you use? @asdzxc7728

**Comment by love386** [comment]
![image](https://user-images.githubusercontent.com/45838695/60753829-f611f580-a00a-11e9-9e1d-4c6a79ea83db.png)

**Comment by love386** [comment]
Unable to continue sync block
(venv) root@iZj6cikpuh59vzdyubi3bsZ:/trx/Python-3.7.1/tron_nodes/fullnode/logs# tron-cli version
[ TRON-CLI ]: Version:...
    1.0.5
ⓘ: Upgrade to latest version:
    pip install troncli --upgrade

**Comment by shydesky** [comment]
please upgrade java-tron to version 3.6

**Comment by asdzxc7728** [comment]
@jerry-sl  现在好了，官方的快照数据有问题，就是那个backups网站的，用新的就好了

**Comment by zzz1020** [comment]
我这边也遇到了同样的问题，后来下载了最新的FullNode.jar ，重新启动程序才解决的
