### ISSUE TITLE
There are two BlockUtil class define int the same package.

### ISSUE THREAD

**Issue by passionofvc** [tronprotocol/java-tron#2337]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
git clone https://github.com/tronprotocol/java-tron.git
cd java-tron
./gradlew build
open eclipse
import as Gradle project
and also install Lombok plugin in eclipse.

there are two BlockUtil's class defined in src and test,
and some IDE(eclipse) report compile error.
diff show only one more method createTestBlockCapsule in main's one.
 
src/test/java
  org.tron.core.capsule.utils.BlockUtil
src/main/java
   org.tron.core.capsule.utils.BlockUtil
```
$ find . -name "BlockUtil.java" -type f 
./src/test/java/org/tron/core/capsule/utils/BlockUtil.java
./src/main/java/org/tron/core/capsule/utils/BlockUtil.java

$ colordiff ./src/test/java/org/tron/core/capsule/utils/BlockUtil.java ./src/main/java/org/tron/core/capsule/utils/BlockUtil.java
1c1,14
< package org.tron.core.capsule.utils;
---
> /*
>  * java-tron is free software: you can redistribute it and/or modify
>  * it under the terms of the GNU General Public License as published by
>  * the Free Software Foundation, either version 3 of the License, or
>  * (at your option) any later version.
>  *
>  * java-tron is distributed in the hope that it will be useful,
>  * but WITHOUT ANY WARRANTY; without even the implied warranty of
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>  * GNU General Public License for more details.
>  *
>  * You should have received a copy of the GNU General Public License
>  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
>  */
2a16
> package org.tron.core.capsule.utils;
5a20
> import java.util.Map;
7a23
> import org.tron.common.utils.Sha256Hash;
10a27,28
> import org.tron.core.db.Manager;
> import org.tron.core.witness.WitnessController;
40c58,59
<         "A new system must allow existing systems to be linked together without requiring any central control or coordination");
---
>         "A new system must allow existing systems to be linked together without "
>             + "requiring any central control or coordination");
45a65,67
>   /**
>    * Whether the hash of the judge block is equal to the hash of the parent block.
>    */
50c72,84
< }
\ No newline at end of file
---
>   public static BlockCapsule createTestBlockCapsule(Manager dbManager, long time,
>       long number, ByteString hash, Map<ByteString, String> addressToProvateKeys) {
>     WitnessController witnessController = dbManager.getWitnessController();
>     ByteString witnessAddress =
>         witnessController.getScheduledWitness(witnessController.getSlotAtTime(time));
>     BlockCapsule blockCapsule = new BlockCapsule(number, Sha256Hash.wrap(hash), time,
>         witnessAddress);
>     blockCapsule.generatedByMyself = true;
>     blockCapsule.setMerkleRoot();
>     blockCapsule.sign(ByteArray.fromHexString(addressToProvateKeys.get(witnessAddress)));
>     return blockCapsule;
>   }
> }
```

2. What did you expect to see?
should be only one class in the same package.

3. What did you see instead?
build error in eclipse [The type BlockUtil is already defined]error occurred.

**Comment by XiangyueMeng** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What did you do?
>    git clone https://github.com/tronprotocol/java-tron.git
>    cd java-tron
>    ./gradlew build
>    open eclipse
>    import as Gradle project
>    and also install Lombok plugin in eclipse.
> 
> there are two BlockUtil's class defined in src and test,
> and some IDE(eclipse) report compile error.
> diff show only one more method createTestBlockCapsule in main's one.
> 
> src/test/java
> org.tron.core.capsule.utils.BlockUtil
> src/main/java
> org.tron.core.capsule.utils.BlockUtil
> 
> ```
> $ find . -name "BlockUtil.java" -type f 
> ./src/test/java/org/tron/core/capsule/utils/BlockUtil.java
> ./src/main/java/org/tron/core/capsule/utils/BlockUtil.java
> 
> $ colordiff ./src/test/java/org/tron/core/capsule/utils/BlockUtil.java ./src/main/java/org/tron/core/capsule/utils/BlockUtil.java
> 1c1,14
> < package org.tron.core.capsule.utils;
> ---
> > /*
> >  * java-tron is free software: you can redistribute it and/or modify
> >  * it under the terms of the GNU General Public License as published by
> >  * the Free Software Foundation, either version 3 of the License, or
> >  * (at your option) any later version.
> >  *
> >  * java-tron is distributed in the hope that it will be useful,
> >  * but WITHOUT ANY WARRANTY; without even the implied warranty of
> >  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> >  * GNU General Public License for more details.
> >  *
> >  * You should have received a copy of the GNU General Public License
> >  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
> >  */
> 2a16
> > package org.tron.core.capsule.utils;
> 5a20
> > import java.util.Map;
> 7a23
> > import org.tron.common.utils.Sha256Hash;
> 10a27,28
> > import org.tron.core.db.Manager;
> > import org.tron.core.witness.WitnessController;
> 40c58,59
> <         "A new system must allow existing systems to be linked together without requiring any central control or coordination");
> ---
> >         "A new system must allow existing systems to be linked together without "
> >             + "requiring any central control or coordination");
> 45a65,67
> >   /**
> >    * Whether the hash of the judge block is equal to the hash of the parent block.
> >    */
> 50c72,84
> < }
> \ No newline at end of file
> ---
> >   public static BlockCapsule createTestBlockCapsule(Manager dbManager, long time,
> >       long number, ByteString hash, Map<ByteString, String> addressToProvateKeys) {
> >     WitnessController witnessController = dbManager.getWitnessController();
> >     ByteString witnessAddress =
> >         witnessController.getScheduledWitness(witnessController.getSlotAtTime(time));
> >     BlockCapsule blockCapsule = new BlockCapsule(number, Sha256Hash.wrap(hash), time,
> >         witnessAddress);
> >     blockCapsule.generatedByMyself = true;
> >     blockCapsule.setMerkleRoot();
> >     blockCapsule.sign(ByteArray.fromHexString(addressToProvateKeys.get(witnessAddress)));
> >     return blockCapsule;
> >   }
> > }
> ```
> 
> 1. What did you expect to see?
>    should be only one class in the same package.
> 2. What did you see instead?
>    build error in eclipse [The type BlockUtil is already defined]error occurred.

Can you provide the branch you use? I tried master and develop branch but I didn't have that problem. You can also try to switch you IDE to Intellij

**Comment by passionofvc** [comment]
@XiangyueMeng 
I use master branch, and I not  use Intellij.
in src and test package there are just two same BlockUtil  class.
Gradle may not put test/classes into jar,  not problem in build.
