### ISSUE TITLE
Unsynchronized block

### ISSUE THREAD

**Issue by love386** [tronprotocol/java-tron#2341]
At present, the block 10705315 has been synchronized.

/trx/Python-3.7.1# tron-cli version
[ TRON-CLI ]: Version:...
    1.0.5
ⓘ: Upgrade to latest version:
    pip install troncli --upgrade

**Comment by love386** [comment]
![image](https://user-images.githubusercontent.com/45838695/60753683-15a81e80-a009-11e9-96ef-521802185ec8.png)

**Comment by love386** [comment]
![image](https://user-images.githubusercontent.com/45838695/60753693-383a3780-a009-11e9-847c-fbbdb75af793.png)

**Comment by zhaohong** [comment]
please use 3.6 version,  the miannet of TRON has been upgraded to 3.6

**Comment by love386** [comment]
你好，请发个下载链接，谢谢

**Comment by shydesky** [comment]
> 你好，请发个下载链接，谢谢
The TRON-CLI is not maintained by us, if you want to the 3.6 version of tron-cli, please contact with the tron-cli team.
But, you can download the newest version of java tron at here.  https://github.com/tronprotocol/java-tron/releases
