### ISSUE TITLE
Too many gRPC connections damages output-directory

### ISSUE THREAD

**Issue by sullof** [tronprotocol/java-tron#2358]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Send a lot of gRPC connection to a node. It can happen is someone is doing a stress test (specifically, BitTorrent Atlas team was testing Atlas against TronGrid).

2. What did you expect to see?
The node should just refuse the connections that it can not handle.

3. What did you see instead?
The node stops syncing. After isolating that node and restarting it, the node is unable to sync, which means that the database has been damaged irreparably. In Trongrid we were forced to recover many nodes from a backup.

Notice that we didn't have any issue like this with the 3.5 for many months. After we upgraded the TronGrid nodes to the 3.6.0, on June 21st, we started having issues. To be more specific, the following week we had all the nodes in North America out of sync and we had to restore them from a backup.

You can check the logs of one of the nodes who were affected at
https://drive.google.com/drive/folders/0Bxb7I2qrCKateXBybjRwZFFEYkE?usp=sharing

This is a vulnerability.
Theoretically, I can target an SR with hundred thousands of gRPC connections and send it out of sync.

**Comment by sullof** [comment]
To be more specific the nodes are set to handle 64000 opened files (as the JavaTron team suggested many months ago). In `/etc/security/limits.conf` we have:
```
*     soft   nofile  64000
*     hard   nofile  64000
```

**Comment by Yrp** [comment]
1. Please provide the machine configuration (cpu/mem/disk/bandwidth)
2. run the command when javaTron process is running and give me the result.
 ```
$ netstat -apn
```

**Comment by sullof** [comment]
Here is the result of that command ran on one of the nodes in Oregon.
https://drive.google.com/drive/folders/0Bxb7I2qrCKateXBybjRwZFFEYkE?usp=sharing

The machine is an 8 CPU/ 32 Gb RAM / 900 Gb disk / 10 Gigabit.

**Comment by Yrp** [comment]
I checked the netstat.log file. There are 34,724 connections in the TIME_WAIT state. This is an exception. reboot the system and restart the node, then the sync should be normal.

**Comment by Yrp** [comment]
I checked the netstat.log file. There are 34,724 connections in the TIME_WAIT state. This is an exception. 
Increase these two values in /etc/security/limits.conf and reboot the system and restart the JavaTron node:
```
*     soft   nofile  64000
*     hard   nofile  64000
```
BTW, what service is provided by this port,```172.31.51.85:80```?

**Comment by shydesky** [comment]
@sullof 
hello, from the log you paste，i found a block (height: 10899388) is processed failure because of "account not exist", you can find it in the picture.  It is usually because of the database
damaged irreparably as you mentioned. So, the block will still be processed failure when the FullNode restarted if you do not replace the old database with a good one.

From the log you supply, I  know you restart it, but the log ends, any log subsequent is available? so did the node sync normally？
Do you replace the database with a backup one to make the node sync normally? 
What is the source data of damage database, is it synced from block 0 or is it one copy of some backup?

You have said many nodes of TronGrid recovered from a backup, do you have any logs of those nodes for us.

I am looking forward to your reply!
![image](https://user-images.githubusercontent.com/3627357/61937869-5ff63d00-afc2-11e9-97b6-567851d3c55e.png)

**Comment by sullof** [comment]
We tried restarting the node in many ways but it was useless. In the end, the only solution was to delete the output-directory and recover it from a backup.
We had the same issue many times with different nodes, in mainnet and in shasta, and in all of those cases, we were forced to restore a previous backup.

Btw, in the last week, we didn't have any issue, which means that the configuration with the hard and soft file limit to 64000 is working. 
It makes sense that too many files create a problem, but I think that it should not damage the database because that is a vulnerability and someone can find a way to trigger it.

**Comment by shydesky** [comment]
@sullof  thanks for your reply. 
We try to reproduce the database been damaged irreparably with a lot of RPC connections, but it is not successful even though we have met the same problem with too many files opened. We can continue our sync after the node restarts without using database backup.  So, we currently not ensure whether massive connections in a short time can cause the database damaged. Can you help us reproduce it on your nodes and give us the logs and the wrong node's database output-directory?

**Comment by sullof** [comment]
We are not having the issue anymore and I am not sure that we can replicate it. We will try and I will let you know asap. Thanks.
