### ISSUE TITLE
Block process time exceeds 50 seconds.

### ISSUE THREAD

**Issue by bjianhang** [tronprotocol/java-tron#2375]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
Block process time in one second.

3. What did you see instead?

00:37:14.394 INFO  [pool-34-thread-1] [DB](Manager.java:1074) pushBlock block number:11173019, cost/txs:54929/300
00:37:14.394 INFO  [pool-34-thread-1] [net](TronNetDelegate.java:176) Success process block Num:11173019,ID:0000000000aa7c9b4f6a3bf7214b583826b524f02993f1579285e784e0fe78ab.
00:37:14.394 INFO  [TronJClientWorker-12] [net](ChainInventoryMsgHandler.java:68) Block Num:11173019,ID:0000000000aa7c9b4f6a3bf7214b583826b524f02993f1579285e784e0fe78ab from 157.230.148.166 is processed
00:37:14.395 INFO  [TronJClientWorker-12] [DB](Manager.java:1608) headNumber:11173019
00:37:14.395 INFO  [TronJClientWorker-12] [DB](Manager.java:1609) syncBeginNumber:11173000
00:37:14.395 INFO  [TronJClientWorker-15] [net](ChainInventoryMsgHandler.java:68) Block Num:11173019,ID:0000000000aa7c9b4f6a3bf7214b583826b524f02993f1579285e784e0fe78ab from 35.176.40.38 is processed
00:37:14.395 INFO  [TronJClientWorker-12] [DB](Manager.java:1612) solidBlockNumber:11173001
00:37:14.395 INFO  [TronJClientWorker-15] [DB](Manager.java:1608) headNumber:11173019
00:37:14.395 INFO  [TronJClientWorker-15] [DB](Manager.java:1609) syncBeginNumber:11173000
00:37:14.395 INFO  [TronJClientWorker-6] [net](ChainInventoryMsgHandler.java:68) Block Num:11173019,ID:0000000000aa7c9b4f6a3bf7214b583826b524f02993f1579285e784e0fe78ab from 94.130.255.100 is processed
00:37:14.395 INFO  [TronJClientWorker-15] [DB](Manager.java:1612) solidBlockNumber:11173001
00:37:14.395 INFO  [TronJClientWorker-6] [DB](Manager.java:1608) headNumber:11173019
00:37:14.395 INFO  [TronJClientWorker-4] [net](ChainInventoryMsgHandler.java:68) Block Num:11173019,ID:0000000000aa7c9b4f6a3bf7214b583826b524f02993f1579285e784e0fe78ab from 77.237.249.181 is processed
00:37:14.395 INFO  [TronJClientWorker-6] [DB](Manager.java:1609) syncBeginNumber:11173000
00:37:14.396 INFO  [TronJClientWorker-6] [DB](Manager.java:1612) solidBlockNumber:11173001
00:37:14.396 INFO  [TronJClientWorker-4] [DB](Manager.java:1608) headNumber:11173019
00:37:14.396 INFO  [TronJClientWorker-4] [DB](Manager.java:1609) syncBeginNumber:11173000
00:37:14.396 INFO  [TronJClientWorker-14] [net](ChainInventoryMsgHandler.java:68) Block Num:11173019,ID:0000000000aa7c9b4f6a3bf7214b583826b524f02993f1579285e784e0fe78ab from 47.89.243.195 is processed
00:37:14.396 INFO  [TronJClientWorker-12] [net](SyncService.java:175) Get block chain summary, low: 11173000, highNoFork: 11173019, high: 11173019, realHigh: 11175018
00:37:14.396 INFO  [TronJClientWorker-4] [DB](Manager.java:1612) solidBlockNumber:11173001
00:37:14.396 INFO  [TronJClientWorker-14] [DB](Manager.java:1608) headNumber:11173019
00:37:14.396 INFO  [TronJClientWorker-6] [net](SyncService.java:175) Get block chain summary, low: 11173000, highNoFork: 11173019, high: 11173019, realHigh: 11175018
00:37:14.396 INFO  [TronJClientWorker-14] [DB](Manager.java:1609) syncBeginNumber:11173000
00:37:14.396 INFO  [TronJClientWorker-14] [DB](Manager.java:1612) solidBlockNumber:11173001
00:37:14.396 INFO  [TronJClientWorker-6] [net](MessageQueue.java:97) Send to /94.130.255.100:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:11173000,ID:0000000000aa7c8821f64dad746aa2aee31baca163c62e0c35b0ef0229e9a25c, end block Num:11175018,ID:0000000000aa846a3315b795b7ad4a1f1c9b5812ebd5b4b7273707bd4f844587 
00:37:14.396 INFO  [TronJClientWorker-4] [net](SyncService.java:175) Get block chain summary, low: 11173000, highNoFork: 11173019, high: 11173019, realHigh: 11175018
00:37:14.397 INFO  [TronJClientWorker-7] [net](ChainInventoryMsgHandler.java:68) Block Num:11173019,ID:0000000000aa7c9b4f6a3bf7214b583826b524f02993f1579285e784e0fe78ab from 84.239.4.145 is processed
00:37:14.397 INFO  [TronJClientWorker-14] [net](SyncService.java:175) Get block chain summary, low: 11173000, highNoFork: 11173019, high: 11173019, realHigh: 11175018
00:37:14.397 INFO  [TronJClientWorker-4] [net](MessageQueue.java:97) Send to /77.237.249.181:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:11173000,ID:0000000000aa7c8821f64dad746aa2aee31baca163c62e0c35b0ef0229e9a25c, end block Num:11175018,ID:0000000000aa846a3315b795b7ad4a1f1c9b5812ebd5b4b7273707bd4f844587 
00:37:14.397 INFO  [TronJClientWorker-14] [net](MessageQueue.java:97) Send to /47.89.243.195:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:11173000,ID:0000000000aa7c8821f64dad746aa2aee31baca163c62e0c35b0ef0229e9a25c, end block Num:11175018,ID:0000000000aa846a3315b795b7ad4a1f1c9b5812ebd5b4b7273707bd4f844587 
00:37:14.397 INFO  [TronJClientWorker-7] [DB](Manager.java:1608) headNumber:11173019
00:37:14.397 INFO  [TronJClientWorker-7] [DB](Manager.java:1609) syncBeginNumber:11172999
00:37:14.397 INFO  [TronJClientWorker-7] [DB](Manager.java:1612) solidBlockNumber:11173001

**Comment by wubinTron** [comment]
Could you give me the machine configuration？

**Comment by bjianhang** [comment]
@wubinTron CPU: 4 core, RAM: 8G

**Comment by jiangyy0824** [comment]
@bjianhang The transaction volume per day surges in recent days. Java-tron need more RAM to process transactions. 

Suggested configuration:
https://github.com/tronprotocol/documentation-EN/blob/master/docs/architecture/network.md#fullnode

Please upgrade your configuration, thanks.

**Comment by wubinTron** [comment]
suggest upgrading machine to 16 core, 64G

**Comment by zk19862018** [comment]
+
