### ISSUE TITLE
Config option for sending logs to stdout

### ISSUE THREAD

**Issue by ksemaev** [tronprotocol/java-tron#2380]
I'm running the code in kuber, and nodes are sending logs to ~/node/tron.log file, filling the filesystem

Is there any config file option, which I can use for sending logs to stdout?
Please advice!

**Comment by jiangyy0824** [comment]
@ksemaev

Steps to send logs to stdout:

1. Download https://github.com/tronprotocol/java-tron/blob/develop/src/main/resources/logback.xml
2. Uncomment the configuration: 
`appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender"`
3. Go to the configuration: `root level="INFO"`
 uncomment the configuration: `appender-ref ref="STDOUT"` 
 comment the configuration: `appender-ref ref="ASYNC"`

4. Move logback.xml to the same directory with FullNode.jar
5. Launch FullNode.jar with additional parameter: --log-config logback.xml, for example
`java -jar FullNode.jar  --log-config logback.xml 
`

**Comment by jiangyy0824** [comment]
![sample](https://user-images.githubusercontent.com/9377378/61762392-676fe780-ae04-11e9-97ce-60b410c10ba0.jpg)

**Comment by ksemaev** [comment]
@jiangyy0824 it worked perfectly for FullNode, but didn't for Solidity. Please advice!

**Comment by jiangyy0824** [comment]
@ksemaev It worked for solidity, I tried on my environment with the same configuration. Please provide your startup parameters.

**Comment by ksemaev** [comment]
@jiangyy0824  I use the same `logback.xml` for both Full and Solidity:
```
<?xml version="1.0" encoding="UTF-8"?>

<configuration>

    <!-- Be sure to flush latest logs on exit -->
    <shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
    <pattern>%d{HH:mm:ss.SSS} %-5level [%t] [%c{1}]\(%F:%L\) %m%n</pattern>
    </encoder>
    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">-->
    <level>INFO</level>
    </filter>
    </appender>

    <appender name="FILE"
              class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>./logs/tron.log</file>
        <rollingPolicy
                class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <!-- rollover daily -->
            <fileNamePattern>./logs/tron-%d{yyyy-MM-dd}.%i.log.gz</fileNamePattern>
            <!-- each file should be at most 500MB, keep 30 days worth of history, but at most 50GB -->
            <maxFileSize>500MB</maxFileSize>
            <maxHistory>3</maxHistory>
            <totalSizeCap>50GB</totalSizeCap>
        </rollingPolicy>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} %-5level [%t] [%c{1}]\(%F:%L\) %m%n</pattern>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>TRACE</level>
        </filter>
    </appender>

    <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <!-- Don't discard INFO, DEBUG, TRACE events in case of queue is 80% full -->
        <discardingThreshold>0</discardingThreshold>
        <!-- Default is 256 -->
        <!-- Logger will block incoming events (log calls) until queue will free some space -->
        <!-- (the smaller value -> flush occurs often) -->
        <queueSize>100</queueSize>
        <includeCallerData>true</includeCallerData>
        <appender-ref ref="FILE"/>
    </appender>

    <root level="INFO">
        <appender-ref ref="STDOUT"/>
        <!--<appender-ref ref="ASYNC"/>-->
    </root>

    <logger name="app" level="INFO"/>
    <logger name="net" level="INFO"/>
    <logger name="backup" level="INFO"/>
    <logger name="discover" level="INFO"/>
    <logger name="crypto" level="INFO"/>
    <logger name="utils" level="INFO"/>
    <logger name="actuator" level="INFO"/>
    <logger name="API" level="INFO"/>
    <logger name="witness" level="INFO"/>
    <logger name="DB" level="INFO"/>
    <logger name="capsule" level="INFO"/>
    <logger name="VM" level="INFO"/>

</configuration>
```

I start Full node with:
`java -jar FullNode.jar -c config.conf --log-config logback.xml --output-directory /home/tron/data`
And Solidity with:
`java -jar SolidityNode.jar -c config.conf --log-config logback.xml --output-directory /home/tron/data --trust-node tron-full-trust:80`
The only difference in config.conf is line `index.switch`.

FullNode provides output to stdout, SolidityNode doesn't.
Please advice

**Comment by shydesky** [comment]
@ksemaev  hi, SolidityNode.jar is not supported by defining the --log-config field. If you want to define it, you must modify the logback.xml in the resource directory and rebuild a new SolidityNode.jar. I recommend you use the FullNode.jar because the FullNode.jar supplies all the function that soliditynode supplies. It is not necessary to deploy a SolidityNode any more.

**Comment by zk19862018** [comment]
+
