### ISSUE TITLE
Backup of solidity node

### ISSUE THREAD

**Issue by ksemaev** [tronprotocol/java-tron#2391]
Guys, I see the backups for FullNode provided here: https://backup.trongrid.io/
However, there's no backups for SolidityNode, and building it's DB from FullNode api takes months.

Can you please advice something, or upload some offline chain data for solidity node?

**Comment by shydesky** [comment]
what do you want to do with a solidity node? All API interfaces are supported by FullNode right now.  You can just run a full node.

**Comment by ksemaev** [comment]
@shydesky so currently there's no difference between them?

**Comment by shydesky** [comment]
@ksemaev  if http api, you can use {your ip}:8091/walletsolidity/getnowblock  
if grpc api,  you can use {your ip}:50061
