### ISSUE TITLE
How to offline create/sign transaction. Any docs about it?

### ISSUE THREAD

**Issue by jerry-sl** [tronprotocol/java-tron#2392]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Offline trx transaction even when fullnode is down or not properly synced.

2. What did you expect to see?
Properly create/sign transaction offline.

3. What did you see instead?
Not found docs or demo about how to offline sign transaction.

**Comment by jerry-sl** [comment]
#2387  My fullnode is not sync properly and can't send trx transaction.

**Comment by shydesky** [comment]
you can send trx transaction by using other's fullnode.
Btw, why your node is not synced, is there any error log in the tron.log?

**Comment by zk19862018** [comment]
You can use [tronweb](https://developers.tron.network/docs/api-sign-flow)

**Comment by zk19862018** [comment]
+
