### ISSUE TITLE
java maven项目引用java-tron报错

### ISSUE THREAD

**Issue by caojianmin** [tronprotocol/java-tron#2408]
<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>
	<dependencies>
		
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.github.tronprotocol</groupId>
			<artifactId>java-tron</artifactId>
			<version>Odyssey-v3.6.1</version>
		</dependency>
	</dependencies>
报错误：Missing artifact com.github.tronprotocol:java-tron:jar:Odyssey-v3.6.1

**Comment by zk19862018** [comment]
Hi, It will be supported in version 3.6.2 which will be released soon.

**Comment by caojianmin** [comment]
@zk19862018 您好，在https://github.com/tronprotocol/java-tron/releases中我看已经发布了Odyssey-v3.6.2，但是我将<version>Odyssey-v3.6.1</version>改成<version>Odyssey-v3.6.1</version>还是报错，另外我想问下，如果我不通过maven工程加载jar包，我直接在java项目中使用FullNode.jar或者SolidityNode.jar，是否可以调用trc20智能合约？

**Comment by jiangyy0824** [comment]
@caojianmin Version 3.6.2 has not been released yet. You can directly launch the java-tron project. 
Then launch wallet-cli to deploy the contract.
