### ISSUE TITLE
TRON full-node issue

### ISSUE THREAD

**Issue by lvs007** [tronprotocol/java-tron#2424]
Dear TRON team,

we have a problem with the update 3.6.0/3.6.2: 
full-node periodically stops synchronizing. After the restart is works for several hours and after that we have messages like this in the logs:

15:16:45.525 INFO  [pool-2-thread-1] [net](SyncPool.java:142) 
 
 ============ Peer stats: all 0, active 0, passive 0
 
 
 15:16:53.315 INFO  [NodeManagerTasks] [discover](NodeManager.java:160) Write Node statistics to PeersStore: 2939 nodes.
 15:16:55.525 INFO  [pool-2-thread-1] [net](SyncPool.java:142) 
 
 ============ Peer stats: all 0, active 0, passive 0
 
 
 15:17:05.526 INFO  [pool-2-thread-1] [net](SyncPool.java:142) 
 
 ============ Peer stats: all 0, active 0, passive 0
 
 
 15:17:15.526 INFO  [pool-2-thread-1] [net](SyncPool.java:142) 
 
 ============ Peer stats: all 0, active 0, passive 0
 
 
 15:17:25.526 INFO  [pool-2-thread-1] [net](SyncPool.java:142) 
 
 ============ Peer stats: all 0, active 0, passive 0
 
 
 15:17:35.527 INFO  [pool-2-thread-1] [net](SyncPool.java:142) 
 
 ============ Peer stats: all 0, active 0, passive 0

We are using TRX 3.6.0/3.6.2
config: https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf
Please be so kind to advise what to do - we'll be looking forward for your reply.

Thank you!

**Comment by shydesky** [comment]
Hello, we analyze the log of your node. The phenomenon full-node periodically stops synchronizing is caused by the no connected node available. In the log, we can find out the last node disconnect( ip: 51.68.119.188) from your node is because of Too Many Peers. 

Normally, the node has 9 nodes connected when running, so we want to get your node's previous log to check the other node's disconnected reasons.

**Comment by zk19862018** [comment]
Could you please join into gitter and talk about some details? Thank you.
https://gitter.im/tronprotocol/allcoredev

**Comment by zhangtiantian222** [comment]
me
[tron.log.tar.gz](https://github.com/tronprotocol/java-tron/files/3549398/tron.log.tar.gz)
 to

**Comment by zk19862018** [comment]
To make the communication more efficiently, please join the our Gitter channel to talk about this issue.

https://gitter.im/tronprotocol/allcoredev

**Comment by shydesky** [comment]
> me
> [tron.log.tar.gz](https://github.com/tronprotocol/java-tron/files/3549398/tron.log.tar.gz)
> to

 you can add some active nodes in your config and restart the node.
