### ISSUE TITLE
Support interact with built-in dex in smartcontract

### ISSUE THREAD

**Issue by HiroKryptor** [tronprotocol/java-tron#2427]
### 1. What did you do?
Interact with built-in dex in smartcontract for auto swap token. 

### 2. What did you expect to see?

Support interact with built-in dex in smartcontract

### 3. What did you see instead?

Not supported

**Comment by Sh11thead** [comment]
Did you mean the trc-10 exchange? 
Now TVM don't support  interact with exchange,if you have suggest,you can put detail in TIP Issue
[https://github.com/tronprotocol/TIPs/issues](url)
