### ISSUE TITLE
Problem accessing /event/contract/TApHKRiVy1M8t319WRjmCFUFgGgnGKEx6J/LogLotteryRevealed/latest. Reason: not found

### ISSUE THREAD

**Issue by github8577** [tronprotocol/java-tron#2430]
Problem accessing /event/contract/TApHKRiVy1M8t319WRjmCFUFgGgnGKEx6J/LogLotteryRevealed/latest. Reason: not found

this is full node

9-08-22 12:37 +08:00: [2019-08-22T12:37:00.877] [ERROR] console - <html>
2|reveal_s | 2019-08-22 12:37 +08:00: <head>
2|reveal_s | 2019-08-22 12:37 +08:00: <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
2|reveal_s | 2019-08-22 12:37 +08:00: <title>Error 404 Not Found</title>
2|reveal_s | 2019-08-22 12:37 +08:00: </head>
2|reveal_s | 2019-08-22 12:37 +08:00: <body><h2>HTTP ERROR 404</h2>
2|reveal_s | 2019-08-22 12:37 +08:00: <p>Problem accessing /event/contract/TApHKRiVy1M8t319WRjmCFUFgGgnGKEx6J/LogLotteryRevealed/latest. Reason:
2|reveal_s | 2019-08-22 12:37 +08:00: <pre>    Not Found</pre></p ><hr>< a href=" ">Powered by Jetty:// 9.4.z-SNAPSHOT</ a><hr/>
2|reveal_s | 2019-08-22 12:37 +08:00:
2|reveal_s | 2019-08-22 12:37 +08:00: </body>
2|reveal_s | 2019-08-22 12:37 +08:00: </html>

resolved

**Comment by Sh11thead** [comment]
This error occurs when tronweb can not connect to event server.
For now,java-tron don't provied event service.
for more details, you can look up here [https://github.com/TRON-US/tronweb](url)
