### ISSUE TITLE
java-tron能否提供验签的sdk，对于基础功能统一提供有利于生态接入

### ISSUE THREAD

**Issue by haihaole01** [tronprotocol/java-tron#2434]

**Comment by wubinTron** [comment]
Could you please join into gitter and talk about some details? Thank you.
https://gitter.im/tronprotocol/allcoredev

**Comment by zk19862018** [comment]
Can you write a TIP, so we can discuss it in the next core devs meeting. 
https://github.com/tronprotocol/TIPs
