### ISSUE TITLE
eventPluginLoader转发出来的transaction添加一下originAddress？

### ISSUE THREAD

**Issue by heipacker** [tronprotocol/java-tron#2446]
如题

**Comment by jiangyy0824** [comment]
@heipacker Please use another interface, for example: https://api.tronex.io/events/transaction/649ea9225df32109ec5091d281c7deb21c7d7dfe7d3a3085db3960961fa7608c

649ea9225df32109ec5091d281c7deb21c7d7dfe7d3a3085db3960961fa7608c is the transactionId. You can get the origin address.

**Comment by heipacker** [comment]
@jiangyy0824  thanks ,  i know can use this interface, but if when i get transaction message from kafka, and then do one rpc to get origin address, it maybe too low,  because i must do rpc request.  so i want to get this info from transaction message which come from kafka.

**Comment by jiangyy0824** [comment]
You can subscribe topic with "transaction" and "contractevent" from Kafaka. Then you can receive the transaction info and the contractevent locally.

Since originAddress only exists in contracted related transactions. We put this param in contractevent trigger. This is by design.
