### ISSUE TITLE
RPC-Gateway endpoint `/wallet/gettransactioninfobyid` always returns blank object

### ISSUE THREAD

**Issue by hugorut** [tronprotocol/java-tron#2514]
Hello I am having some problems with the tron `/wallet/getransactioninfobyid` http rpc endpoint. I seem to only ever receive blank json object no matter what transaction hash  I use.

### 1. What did you do?
I have a synced tron full-node, with the latest block tip. I was testing trying to retrieve an arbitrary transaction from one of the more recent ones, found in the public explorer [here](https://tronscan.org/#/blockchain/transactions) 

I tried a few transactions, here’s a [specific example](https://tronscan.org/#/transaction/2e9e373ee74ce7534280467925ab3125280f3d2a8391173b3c683f1de861b4d3), and CURLd the `/wallet/getransactioninfobyid` endpoint:

```
$ curl -X POST http://127.0.0.1/wallet/gettransactioninfobyid -d '{"value” : "2e9e373ee74ce7534280467925ab3125280f3d2a8391173b3c683f1de861b4d3"}'
```

### 2. What did you expect to see?
a valid transaction response (not sure of the exact JSON, hence why I was trying to CURL it)

### 3. What did you see instead?
`{}`

Other endpoints such as `/wallet/getaccount` are working just fine, I’m probably just doing something very stupid with the transaction endpoint. Any help would be greatly appreciated.

**Comment by hugorut** [comment]
found the issue, thanks

**Comment by wkoszycki** [comment]
@hugorut what was it ? I am facing similar one :)

**Comment by zapilich** [comment]
@wkoszycki it looks like the documentation is outdated, and both `gettransactionbyid` and `gettransactioninfobyid` methods are GET now. Try `curl -X GET http://127.0.0.1/wallet/gettransactioninfobyid?value=2e9e373ee74ce7534280467925ab3125280f3d2a8391173b3c683f1de861b4d3`
