### ISSUE TITLE
about broadcast transaction interface (grpc)

### ISSUE THREAD

**Issue by tensecond** [tronprotocol/java-tron#2516]
Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

step 1. Create a transfer transaction, A to B, 1trx
step 2. Sign the result with the private key of C
step 3. call the broadcast transaction interface (grpc), get the error: SIGERROR
step 4. repeat the steps of 3, send again, get the error: DUP_TRANSACTION_ERROR

### 2. What did you expect to see?
 No matter how many times step 3 is repeated, the result should still be the original error SIGERROR

### 3. What did you see instead?
When step 3 is repeated, the DUP_TRANSACTION_ERROR error is no longer the original error of the transaction. The original error SIGERROR has been lost

**Comment by zk19862018** [comment]
when you  repeat the steps of 3, the same transactions will be broadcasted into the MainNet, so the  error message "DUP_TRANSACTION_ERROR" is correct for duplicated transactions broadcast.  

Anyway, Thanks for your contribution. 
https://tronprotocol.github.io/documentation-en/developers/incentives/

**Comment by tensecond** [comment]
> when you repeat the steps of 3, the same transactions will be broadcasted into the MainNet, so the error message "DUP_TRANSACTION_ERROR" is correct for duplicated transactions broadcast.
> 
> Anyway, Thanks for your contribution.
> https://tronprotocol.github.io/documentation-en/developers/incentives/

When the server receives the request, the first step should not be to verify the correctness of the request?

**Comment by jiangyy0824** [comment]
When fullnode receive the transaction at first time, it will be executed, and SIGERROR is returned, and the transaction is stored locally.

When fullnode receive the same transaction again. Fullnode will check the local store to prevent executing again. This is by design. This logic could save large resource on main-net.

**Comment by jpnapps** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> ### 1. What did you do?
> step 1. Create a transfer transaction, A to B, 1trx
> step 2. Sign the result with the private key of C
> step 3. call the broadcast transaction interface (grpc), get the error: SIGERROR
> step 4. repeat the steps of 3, send again, get the error: DUP_TRANSACTION_ERROR
> 
> ### 2. What did you expect to see?
> No matter how many times step 3 is repeated, the result should still be the original error SIGERROR
> 
> ### 3. What did you see instead?
> When step 3 is repeated, the DUP_TRANSACTION_ERROR error is no longer the original error of the transaction. The original error SIGERROR has been lost

Did u got solution ?
