### ISSUE TITLE
What's the use of seed.node?

### ISSUE THREAD

**Issue by Zara-lang** [tronprotocol/java-tron#2536]
Hello, 

What's the use of the seed.node? 
What role do they play in TronNetwok? 
What's the difference with SR node?
What's the difference with FullNode?
Is seed.node a FullNode?

Thanks for your reply.

**Comment by shydesky** [comment]
The seed.node is the initial nodes set.  They are used to be connected when a new node joins the Tron Network.  All the seed.node are Full Node now. SR node can pack the transactions and produce blocks.

**Comment by Zara-lang** [comment]
Are the seed nodes running by Tron officially?
When a new node joins, it syncs data from seed nodes?(from random one single? or syncs from multiple nodes)

**Comment by shydesky** [comment]
yes, some of them are run by Tron and some are run by the community.
when a new node joins, it will communicate with the seed nodes to ask their neighbors. Then the node will choose the top N nearest nodes to sync data. Generally, the N is about 9.

**Comment by Zara-lang** [comment]
@shydesky 
It syncs from "top N nearest nodes" concurrently or it syncs from just 1 node of the "top N nearest nodes" as the rest plays the backup roles?
Why can't the fullnode I deploy finds its neighbors itself, as you mentioned  "it will communicate with the seed nodes to ask their neighbors"?

**Comment by shydesky** [comment]
It syncs from N nodes, for example, it syncs block 1~1000 from node A and 1001~2000 from node B, 2001~3000 from node C. The synchronization runs parallelly.

Your node can not know other nodes' IP addresses if it does not communicate with the seed node at first. The seed nodes are running all the time. When a new node join in, the node will communicate with the seed nodes, and then the seed nodes store the new node's IP address. So, the seed node can be considered as the introducer when your node wants to join the network.
