### ISSUE TITLE
fullnode's data snapshot exceeds 200G

### ISSUE THREAD

**Issue by richardhallhall** [tronprotocol/java-tron#2539]
### 3. What did you see instead?

How to reduce disk occupancy of fullnode.

**Comment by shydesky** [comment]
yes, if you run a full node, you must have all the data of blockchain. we will develop a light node in the near future.

**Comment by richardhallhall** [comment]
@shydesky What is the principle of light node? And when when will it be released.

**Comment by shydesky** [comment]
> @shydesky What is the principle of lite node? And when when will it be released.

The lite node runs with part of data that contains accounts and recent blocks and some transactions. It will begin to fetch other node's data when he is interesting in some specific transactions. So, the lite node can run with very little data.
The lite node is under investigation and I think it will be developed and released next year.

**Comment by zk19862018** [comment]
Hi,

If your problem has been solved, please close this issue.

Thank you!
