### ISSUE TITLE
 What are these scripts used for?

### ISSUE THREAD

**Issue by shychrdw** [tronprotocol/java-tron#2556]
### 1. What did you do?

I review the code and find many scripts in the project like tron.sh, start.sh, work.sh, gen.sh, deploy.sh.

### 2. What did you expect to see?
I want to know every script's meaning and usage.

**Comment by Sh11thead** [comment]
`tron.sh` and `deploy.sh` is used for travis CI  in `.travis.yml`
`work.sh` is the start script for java-tron

you can read script content for more details

**Comment by shychrdw** [comment]
Thanks! I read the code of the script and I found that the work.sh is repeated with start.sh.
