### ISSUE TITLE
usdt balance is not shown

### ISSUE THREAD

**Issue by puffanddmx** [tronprotocol/java-tron#2560]
1 . issue 
- for the address only holds the usdt balance
-> curl -X POST  http://127.0.0.1:8091/walletsolidity/getaccount 
-> with above curl command, there are no asset for the response but explorer can see the balance.

**Comment by zk19862018** [comment]
Hi,

USDT is TRC-20 token, you need to trigger USDT's contract address to get the balance. 
walletsolidity/getaccount api only shows TRC-10 token.

If your question is solved, please close this issue. 
If you have any further question, please feel free to contract us.

**Comment by puffanddmx** [comment]
thanks for your help!
can you give me the example link that i can send trc20 and trigger things u mentioned above ?
- if tronweb suppport it , it will be helpful.

**Comment by puffanddmx** [comment]
thanks!
