### ISSUE TITLE
What is the so-called modular code?

### ISSUE THREAD

**Issue by gogogogo296** [tronprotocol/java-tron#2562]
### 1. What did you do?

Finding the module repair code and would like to know how and what you have changed.

### 2. What did you expect to see?

The clear explanation of what is the module code, what and how it has changed. Besides, not only a simple URL.

### 3. What did you see instead?

https://github.com/tronprotocol/java-tron/tree/develop/framework/src/test/java

**Comment by Sh11thead** [comment]
In order to quickly iterate new features and the requirements of a one-click chain,the new version of java-tron uses gradle's multi-module to organize code,  which is divided into actuator, chainbase, protocol, framework, consensus 5 modules
