### ISSUE TITLE
[Main Class]: org.tron.example.Tron doesn't exist

### ISSUE THREAD

**Issue by ItFlyingStart** [tronprotocol/java-tron#257]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Which main class should I use? Because **org.tron.example.Tron** (described in http://wiki.tron.network/en/latest/quick_start.html) doesn't exist.

**Comment by KamilZielinski** [comment]
Make sure you are on `master` branch

**Comment by lky1001** [comment]
check master branch (https://github.com/tronprotocol/java-tron/blob/master/src/main/java/org/tron/example/Tron.java)
