### ISSUE TITLE
triggersmartcontract 

### ISSUE THREAD

**Issue by puffanddmx** [tronprotocol/java-tron#2585]
hi
curl -X POST  http://172.2.24.11:8090/wallet/triggersmartcontract -d '{"contract_address":"41a614f803b6fd780986a42c78ec9c7f77e6ded13c","function_selector":"balanceOf(address)","parameter":"000000000000000000000041c78004d69b606dac1f6d6a7e891ff8c9ec1f2827","owner_address":"41a614f803b6fd780986a42c78ec9c7f77e6ded13c"}' 
{
    "result": {
        "code": "CONTRACT_VALIDATE_ERROR",
        "message": "74686973206e6f646520646f6e277420737570706f727420636f6e7374616e74"
    }
}
error : this node don't support constant
i got this, where is problem ? only my local fullnode daemon got errror. (dbconfig error)
public endpoint is working well.

**Comment by Sh11thead** [comment]
check if 
`vm = {
  supportConstant = true
}` is opened

**Comment by puffanddmx** [comment]
thanks
