### ISSUE TITLE
When getting a block, if visible is enabled, the acquisition fails.

### ISSUE THREAD

**Issue by zyumingfit** [tronprotocol/java-tron#2587]
When getting a block, if visible is enabled, the acquisition fails.If visible is set to false, no error will be reported.

Only this block will report an error, and no other blocks have been found yet.

**input the command：**
`curl -X POST "http://3.225.171.164:8090/wallet/getblockbyid" -H "Content-Type: application/json" --data '{"value":"00000000001324121bcb2b41ab01d26c5ff2f1de40ce71148bd775aa0939ddcd","visible":true}'`

**Report an error：**
`{"Error":"class com.alibaba.fastjson.JSONException : syntax error, position at 173, name description"}`

**Comment by zk19862018** [comment]
Hi, 
The block id you query does not exist.

**Comment by zk19862018** [comment]
Hi,

Thanks for your issue, we will fix it.

**Comment by zk19862018** [comment]
Hi,

It has been fixed and merged into develop branch.

**Comment by mayaoguang** [comment]
我遇到了同样的问题
curl -X POST "34.220.77.106:8090/wallet/getblockbynum" -H "Content-Type: application/json" --data '{"num":20181145,"visible":true}'
在获取 20181145 和20645902 的时候返回这个错误

**Comment by DmytroShalaiev** [comment]
Have the same problem on TronGrid mainnet: tronWeb.trx.getBlockByNumber(40134306)

returned {Error: 'class com.alibaba.fastjson.JSONException : illegal state. 0'}
all other blocks is good!
What's happened ?
