### ISSUE TITLE
http api "getblockbynum" 缺失区块高度字段

### ISSUE THREAD

**Issue by LeorCao** [tronprotocol/java-tron#2599]
我在本地搭建了一个quickstart的节点，在做分叉检查时调用getblockbynum发现有些区块缺失了区块高度等字段。请问这是为啥？

**Comment by LeorCao** [comment]
我的程序逻辑是通过 getnowblock 接口扫描获取最新区块然后用最新区块高度-1获取上一个区块检查是否有分叉，但是发现有一些区块的 block_header 中缺失了 区块高度 等几个字段

**Comment by zk19862018** [comment]
Hi,  Can you provide the data return from getblockbynum?

**Comment by LeorCao** [comment]
> 嗨，您能提供getblockbynum返回的数据吗？

thinks, It's settled.It's my own problem
