### ISSUE TITLE
contract revert error

### ISSUE THREAD

**Issue by puffanddmx** [tronprotocol/java-tron#2601]
hi 
i test contract for sending usdt using contract
i got the revert error . can you share what the problem is ?
https://tronscan.org/#/transaction/b7790f4b43728e76a06d8a4ebd444760f819952ed2406fd830f1b0bd8535c2a7

**Comment by Sh11thead** [comment]
could you provide specific contract solidity code  for analysis of reasons ？

**Comment by puffanddmx** [comment]
{
    "constant_result": [
        "0000000000000000000000004960877bf8e19f8f11678dfd1c8d414452d7aa5e"
    ],
    "result": {
        "result": true
    },
    "transaction": {
        "raw_data": {
            "contract": [
                {
                    "parameter": {
                        "type_url": "type.googleapis.com/protocol.TriggerSmartContract",
                        "value": {
                            "contract_address": "4157bc6387a2fd28d29556dcae07e5c9e9ee65e3e9",
                            "data": "6a28ba850000000000000000000000000000000000000000000000000000000000000000",
                            "owner_address": "41a614f803b6fd780986a42c78ec9c7f77e6ded13c"
                        }
                    },
                    "type": "TriggerSmartContract"
                }
            ],
            "expiration": 1571803164000,
            "ref_block_bytes": "5e10",
            "ref_block_hash": "800e17419ade4583",
            "timestamp": 1571803105408
        },
        "raw_data_hex": "0a025e102208800e17419ade458340e0da93b6df2d5a8e01081f1289010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412540a1541a614f803b6fd780986a42c78ec9c7f77e6ded13c12154157bc6387a2fd28d29556dcae07e5c9e9ee65e3e922246a28ba85000000000000000000000000000000000000000000000000000000000000000070809190b6df2d",
        "ret": [
            {}
        ],
        "txID": "9f08be1c817467e021a849af742742b2a808f1f0f8df1a1cfccf1a19e34a6a51",
        "visible": false
    }
}

**Comment by Sh11thead** [comment]
can you put your solidity code here？

**Comment by puffanddmx** [comment]
pragma solidity ^0.5.4;
   
contract TRC20Interface {
    function totalSupply() public view returns (uint);
    function balanceOf(address tokenOwner) public view returns (uint balance);
    function allowance(address tokenOwner, address spender) public view returns (uint remaining);
    function transfer(address to, uint tokens) public returns (bool success);
    function approve(address spender, uint tokens) public returns (bool success);
    function transferFrom(address from, address to, uint tokens) public returns (bool success);

    event Transfer(address indexed from, address indexed to, uint tokens);
    event Approval(address indexed tokenOwner, address indexed spender, uint tokens);
}
  
contract User {
    address manager;
    bool sending;
    constructor() public {
        manager=msg.sender;
    }
      
    function sendTrc20(address _token, address _to, uint256 _value) public returns (bool) {
        require(msg.sender==manager);
        require(TRC20Interface(_token).transfer(_to, _value));
        return true;
    }
      
    function () external {
          
    }
}
  
contract Manager {
    mapping(address => bool) public CheckOwner;
    mapping(address => bool) public UserCheck;
    address[] public Users;
    constructor() public {
        CheckOwner[msg.sender]=true;
    }
      
    function addOwner(address _newOwner) public {
        require(CheckOwner[msg.sender]);
        CheckOwner[_newOwner]=true;
    }
      
    function changeOwner() public {
        require(CheckOwner[msg.sender]);
        CheckOwner[msg.sender]=false;
    }
      
    function newUser() public {
        require(CheckOwner[msg.sender]);
        for(uint i=0; i<23; i++) {
            User newUserContract = new User();
            Users.push(address(newUserContract));
            UserCheck[address(newUserContract)]=true;
        }
    }
      
    function sendTrc20(address _token, address _from, address _to, uint256 _value) public {
        require(CheckOwner[msg.sender]);
        require(UserCheck[_from]);
        require(User(_from).sendTrc20(_token,_to,_value));
    }
      
    function getToken(address _from, address _token) public view returns (uint256) {
        return TRC20Interface(_token).balanceOf(_from);
    }
     
    function getUsersLength() public view returns (uint256) {
        return Users.length;
    }

    function getUsersAddress(uint _index) public view returns (address) {
        return Users[_index];
    }

}

**Comment by Sh11thead** [comment]
You need to add 41 to the beginning of the byte array,then convert to typical TRON address.
Length of the initial address should be 21 bytes.

`
4960877bf8e19f8f11678dfd1c8d414452d7aa5e
->
414960877bf8e19f8f11678dfd1c8d414452d7aa5e
->
TGfBy2n9MHMAUoqcBidDLG37qiNwjeGJio
`
You can convert online in tronscan

https://tronscan.org/#/tools/tron-convert-tool


Read  https://github.com/tronprotocol/documentation/blob/master/TRX/Tron-overview.md Part 6 for more details

**Comment by puffanddmx** [comment]
i try it , but it has revert error also
https://tronscan.org/#/transaction/5956bbe46e8e87a9f0834bab27f7991570e008c5dfab746851561496675559ff

**Comment by Sh11thead** [comment]
We noticed that the USDT contract is not a standard TRC20 contract, `function transfer(address to, uint tokens) public returns (bool success) ` would always retuns 0 ,so     require(TRC20Interface(_token).transfer(_to, _value)) would throw revert directly

**Comment by puffanddmx** [comment]
Do you mean that we can't transfer usdt to our contract with this partial transfer?

**Comment by Sh11thead** [comment]
if you use usdt ,change `require(TRC20Interface(_token).transfer(_to, _value)) ` to `TRC20Interface(_token).transfer(_to, _value)`

**Comment by puffanddmx** [comment]
if function transfer(address to, uint tokens) public returns (bool success) transaction failed, function transfer(address to, uint tokens) public returns (bool success) would always retuns 0

**Comment by Sh11thead** [comment]
The USDT contract code is not public now.I suggest you can trigger the USDT contract youself to judge what exactly happens when failed.

**Comment by puffanddmx** [comment]
is it possible to send btt with contract in our contract code?
Send usdt A-> B fee by C

**Comment by jeancky** [comment]
@puffanddmx , BTT is a TRC10 token.  You can send it in smart contract  with this solidity function "address.transferToken(uint256 tokenValue, trcToken tokenId)". such as "TF5Bn4cJCT6GVeUgyCN4rBhDg42KBrpAjg.transferToken(10, 1002000)"

**Comment by puffanddmx** [comment]
thanks man!

**Comment by puffanddmx** [comment]
thanks!
