### ISSUE TITLE
master分支 fullnode无法同步

### ISSUE THREAD

**Issue by zhifeiji** [tronprotocol/java-tron#2602]
### 1. What did you do?

java -jar /full_node/java-tron.jar -c /full_node/config.conf

启动了fullnode节点程序，master分支的代码编译的。区块同步到大概 4496783 高度，就没法继续新的区块了

### 2. What did you expect to see?
期望区块同步到最新高度

### 3. What did you see instead?
部分日志
02:08:41.077 INFO  [TronJClientWorker-1] [net](Channel.java:195) Peer /149.202.210.187:18888 status change to SYNCING.
02:08:41.077 INFO  [TronJClientWorker-1] [net](Channel.java:195) Peer /149.202.210.187:18888 status change to SYNCING.
02:08:41.077 INFO  [TronJClientWorker-1] [DB](Manager.java:1591) headNumber:4496783
02:08:41.077 INFO  [TronJClientWorker-1] [DB](Manager.java:1592) syncBeginNumber:4496764
02:08:41.078 INFO  [TronJClientWorker-1] [DB](Manager.java:1595) solidBlockNumber:4496765
02:08:41.078 INFO  [TronJClientWorker-1] [net](SyncService.java:175) Get block chain summary, low: 4496764, highNoFork: 4496783, high: 4496783, realHigh: 4496783
02:08:41.078 INFO  [TronJClientWorker-1] [net](MessageQueue.java:94) Send to /149.202.210.187:18888, type: SYNC_BLOCK_CHAIN
size: 5, start block: Num:4496764,ID:0000000000449d7cfbdb0b103392a7ec167b3ddeec10058880a1b55b3a224fd3, end block Num:4496783,ID:0000000000449d8f579f93cba2e1b6501bcccee8d55f729c03fb1a31cd85da72 
02:08:41.088 INFO  [TronJClientWorker-9] [net](MessageQueue.java:108) Receive from /47.75.128.222:18888, type: BLOCK
Num:4497714,ID:000000000044a132feb14203781dbae5c6cac858afa9bb8203a73d58829c6b02, trx size: 74

**Comment by shydesky** [comment]
hi, can you provide the detail logs?

**Comment by zhifeiji** [comment]
03:15:26.978 INFO  [TronJClientWorker-15] [net](MessageQueue.java:108) Receive from /47.75.193.143:18888, type: BLOCK
Num:4498641,ID:000000000044a4d185a752cb5ef1c5e4611e01fbcaf985f20f81ad73bc53e2b3, trx size: 65

03:15:26.993 INFO  [TronJClientWorker-6] [net](MessageQueue.java:108) Receive from /47.75.91.185:18888, type: BLOCK
Num:4498742,ID:000000000044a5365444d0f36c0d1310afc0863ffcdc80e468f8106b49ec2354, trx size: 55

03:15:26.994 WARN  [TronJClientWorker-12] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 2 from Peer /47.75.249.119, syncFromUs: false, syncFromPeer: true.
03:15:26.995 WARN  [TronJClientWorker-12] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.75.249.119, syncFromUs: false, syncFromPeer: true.
03:15:26.995 WARN  [TronJClientWorker-12] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.75.249.119, syncFromUs: false, syncFromPeer: true.
03:15:27.008 INFO  [TronJClientWorker-13] [net](MessageQueue.java:108) Receive from /47.75.211.242:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:4496783,ID:0000000000449d8f579f93cba2e1b6501bcccee8d55f729c03fb1a31cd85da72, end blockId: Num:4498783,ID:000000000044a55f179c99cb0672e92aa2863d056f3ba9f0bd1d5bb784830d74
03:15:27.010 INFO  [TronJClientWorker-13] [DB](Manager.java:1591) headNumber:4496783
03:15:27.011 INFO  [TronJClientWorker-13] [DB](Manager.java:1592) syncBeginNumber:4496764
03:15:27.011 INFO  [TronJClientWorker-13] [DB](Manager.java:1595) solidBlockNumber:4496765
03:15:27.011 INFO  [TronJClientWorker-13] [net](SyncService.java:175) Get block chain summary, low: 4496764, highNoFork: 4496783, high: 4496783, realHigh: 4498783

**Comment by shydesky** [comment]
need the whole log file

**Comment by zhifeiji** [comment]
log file is too large

**Comment by shydesky** [comment]
> log file is too large

From the log you paste, we can not get any useful information. Can you send the "tron.log" to me by email shydesky@gmail.com?

**Comment by shydesky** [comment]
From your log, I find that you use actually an old version of the develop branch to run the Full node. So, I think you should 
1. git checkout master
2. git pull origin master
3. ./gradlew clean build
and find the newly packaged jar file in the path  build/libs
then restart the full node using this new jar
