### ISSUE TITLE
disconnect with all other nodes because of "Different resultCode" problem

### ISSUE THREAD

**Issue by shychrdw** [tronprotocol/java-tron#2609]
### 1. What did you do?

sync block with other nodes.

### 2. What did you expect to see?
sync block with other nodes normally and finally to the highest height block.

### 3. What did you see instead?
sync block with nodes failure sometimes and then disconnect with all other nodes.

**Comment by shydesky** [comment]
hello，this is because of your low machine performance. You can update the item "maxTimeRatio" in the config.conf from 5.0 to 20.0. Then restart the node and check whether the sync normal.

**Comment by zk19862018** [comment]
Hi, 

If your problem has been solved, please close this issue. 

Thank you!
