### ISSUE TITLE
Verification of transactions in the block

### ISSUE THREAD

**Issue by damianrusinek** [tronprotocol/java-tron#2611]
How does the FullNode verify whether all transactions received within a block are correctly signed?

### 1. What did you do?
I have checked the `BlockMsgHandler` class which is called when a new block arrives from a peer (correct me if I am wrong). The signature of the block and correctness of the merkle root is verified in `Manager` class (chain `BlockMsgHandler.processMessage` -> `BlockMsgHandler.processBlock` -> `TronNetDelegate.processBlock` -> `Manager.pushBlock`).

The `Manager.pushBlock` method verifies the signature (`l.986: block.validateSignature(this)`) and merkle root (`l.991: block.calcMerkleRoot().equals(block.getMerkleRoot())`).

### 2. What did you expect to see?
I expected the transactions list to have verified signatures as well.

### 3. What did you see instead?
I cannot find place where transaction signatures are verified (on a new block arrival event).

I assume that malicious node can add his malicious and incorrect transactions to the block, validate the block and broadcast it.

**Comment by zk19862018** [comment]
Hi, 
you  can find the  transaction signatures verification at:
pushBlock -> applyBlock -> processBlock -> preValidateTransactionSign

**Comment by damianrusinek** [comment]
Thanks.
