### ISSUE TITLE
rest api : gettransactions command

### ISSUE THREAD

**Issue by puffanddmx** [tronprotocol/java-tron#2619]
We ask if there is a rest api command that takes all the transactions associated with from_address or to_address  and returns them from my local fullnode which i run on my cloud server.

---------------------------------no longer support-------------------------------------------------
walletextension/gettransactionsfromthis(The new version will no longer be supported)
Function：Query the list of transactions sent by an address
demo: curl -X POST  http://127.0.0.1:8091/walletextension/gettransactionsfromthis -d '{"account" 
  : {"address" : "41E552F6487585C2B58BC2C9BB4492BC1F17132CD0"}, "offset": 0, "limit": 10,"startTime": 1546099200000, "endTime": 1552028828000}'

/walletextension/gettransactionstothis(The new version will no longer be supported)
Function：Query the list of transactions received by an address
demo: curl -X POST  http://127.0.0.1:8091/walletextension/gettransactionstothis -d '{"account" : 
 {"address" : "41E552F6487585C2B58BC2C9BB4492BC1F17132CD0"}, "offset": 0, "limit": 10,"startTime": 1546099200000, "endTime": 1552028828000}'

Get Transactions Related
tronWeb.trx.getTransactionsRelated("TNDFkUNA2TukukC1Moeqj61pAS53NFchGF", "all", 30, 0);

**Comment by gituser** [comment]
Here is a related issue fo SolidityNode - https://github.com/tronprotocol/java-tron/issues/2615

**Comment by jiangyy0824** [comment]
@puffanddmx gettransactionstothis is deprecated. To meet your requirement, you can use event plugin. 
For detailed usage, please refer to https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Event_Subscribe/Tron-eventsubscribe.md

**Comment by gituser** [comment]
@jiangyy0824 

I've looked over event plugin it seems it's a very complicated system relying on many moving parts (kafka, mongodb, etc). 

Why there is no ability for the FullNode to produce simple transaction list for the TRON account?
The FullNode already downloads whole blockchain in some kind of form and occupies a lot of space and you want to load it again into some 3rd party database (e.g. mongodb) just to get a list of transactions? Very inefficient.

Is there any other way?

**Comment by jiangyy0824** [comment]
The mongodb should not be deployed on the fullnode. This is a solution for dapp developers.

It's not suggested to implement such interface to developers, special cost performance. We have already provided the code implementation. You can implement it on your local environment.

**Comment by gituser** [comment]
@jiangyy0824 
>We have already provided the code implementation. You can implement it on your local environment.

How to implement this in the FullNode? Is there any instructions on how to activate `gettransactiontothis` and `gettransactionsfromthis` RPC API calls?

**Comment by richardhallhall** [comment]
> @jiangyy0824
> 
> > We have already provided the code implementation. You can implement it on your local environment.
> 
> How to implement this in the FullNode? Is there any instructions on how to activate `gettransactiontothis` and `gettransactionsfromthis` RPC API calls?

There is no instructions to active the calls. You need to implement it by yourself. The implementation can refer to the follow links.

https://github.com/tronprotocol/java-tron/blob/master/src/main/java/org/tron/core/db/api/StoreAPI.java

https://github.com/tronprotocol/java-tron/blob/master/src/main/java/org/tron/core/WalletSolidity.java

The current develop has been refactored, it would cost quite a lot of time to implement the transaction. It depends on you.
