### ISSUE TITLE
Contribution Winners of October is Published!

### ISSUE THREAD

**Issue by jiangyy0824** [tronprotocol/java-tron#2622]
Dear developers,

Our Community Developers Incentives Programme has been on for 1 month. 

Thanks to every developer who contributes to our project. 

By the end of the 31 Oct, 2019, the top 5 winners are:

NO.1 bjianhang, 200 USDT
NO.2 geb789, niuniublockchain, 180 USDT
NO.3 Zara-lang, 150 USDT
NO.4 shychrdw, 120 USDT
NO.5 test2019-crypto, sss-rain110 100USDT

Congratulation! The cash reward will be sent in the form of USDT within this month. 

You can claim your reward by emailing your USDT address to coreDevs@tron.network through the email you used to contribute to our project before the end of 10 Nov, 2019. 

For those who failed to end up in Top 5, keep your chin up! The points gap is very small, so continute to earn points, then next month or the quarter reward may hit you. 

For more information, please refer to:

https://tronprotocol.github.io/documentation-en/developers/incentives/
https://tronscan.org/#/developersreward

**Comment by niuniublockchain** [comment]
@jiangyy0824 Got it! Thanks.

**Comment by jiangyy0824** [comment]
You are welcome

**Comment by jiangyy0824** [comment]
@bjianhang @geb789 @Zara-lang, @shychrdw, @test2019-crypto, @sss-rain110 @niuniublockchain  Please send your USDT address to receive the bonus.

**Comment by jiangyy0824** [comment]
@shychrdw We haven't received your address up to now.  Please don't forget.

**Comment by jiangyy0824** [comment]
github   account | bonus | USDT address | hash |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
bjianhang | 200 USDT | 0xd35094f87c7f3c02ed065e1982feb37df4ac1829 | https://etherscan.io/tx/0x68b3339f3bf24c539eacd1a20e9f24114a487c5bf0f518a176e8715b3f744e02 |  
geb789 | 180 USDT | 0x2b5e56506e616c95166c6c75dc79aec4b8576d56 | https://etherscan.io/tx/0x537a2651264b567b98bebc6a5c5c11080f95b46b985d282d9ee420e6d4276028
niuniublockchain | 180 USDT | 18LHax5bRcaCjNXpvvorrjMVeBQaVFq1L6 | https://www.omniexplorer.info/tx/e33b0fbbec1792bd42292634d2b7949c74af11eb65fd2e02de6917442df45f47
Zara-lang | 150 USDT | 0x9ac6fa17f6c7f7a70591a70ae49ce2d097e183da | https://etherscan.io/tx/0x6f831570ed4de19baf7861d4175960171ace295c720b4309c126e6abbf4d4541
shychrdw | 120 USDT | 0x7a7943472345252c1ac80fcbb59be0a45ae39457 | https://etherscan.io/tx/0xb3141724cd8570778b228ee231e2f18223e315e89c8cbad862c9b3600e9b25b8
test2019-crypto | 100 USDT | 0x8d5c84449068d9819aa93fe2a2cdf1e40bde6a0b | https://etherscan.io/tx/0x72acc632498e5a2c6cecc80a7ce25a7d4ae581fd018955f08de30719126fe995 |  
sss-rain110 | 100 USDT | 1CrUDG4srprMXJfSMoTdJootJHEjTwTPZs | https://www.omniexplorer.info/tx/823f9e0bf665f74ecb4eed45edb84968c23e789a4437a0b3aa2444fc401039c5

**Comment by jiangyy0824** [comment]
@bjianhang @geb789 @Zara-lang, @shychrdw, @test2019-crypto, @sss-rain110 @niuniublockchain

The rewards have been released. Please confirm.

Thanks!
