### ISSUE TITLE
MAVEN 依赖不存在!  com.github.tronprotocol:java-tron:Odyssey-v3.6.2

### ISSUE THREAD

**Issue by apa7** [tronprotocol/java-tron#2656]
<dependency>
	<groupId>com.github.tronprotocol</groupId>
	<artifactId>java-tron</artifactId>
	<version>Odyssey-v3.6.2</version>
</dependency>

请问应该使用哪个镜像站? 
还是应该自己去mvn install

**Comment by jiangyy0824** [comment]
Please refer to https://jitpack.io/#tronprotocol/java-tron/Odyssey-v3.6.2 to check whether your code have the right dependency.
