### ISSUE TITLE
How to get useful info from API:getTransactionInfoById()?  Just like fromAddress, toAddress, amount.

### ISSUE THREAD

**Issue by apa7** [tronprotocol/java-tron#2658]
![image](https://user-images.githubusercontent.com/9262517/69041346-53db3300-0a2a-11ea-826d-c290dfc66d9f.png)

I went through the API documentation and found no API that could solve my problem.
How should I get this info?

**Comment by Starsakary** [comment]
To get transaction details please refer to this API: gettransactionbyid
<img width="959" alt="image" src="https://user-images.githubusercontent.com/51088710/69113425-ed9ff000-0abd-11ea-8590-093c180496cd.png">

**Comment by Starsakary** [comment]
To get transaction details please refer to this API: gettransactionbyid

**Comment by apa7** [comment]
> To get transaction details please refer to this API: gettransactionbyid

Great!
I use mongo plugin have resolved this problem!
