### ISSUE TITLE
I would like to help for french translation

### ISSUE THREAD

**Issue by Kowai** [tronprotocol/java-tron#267]
Hey guys, any need of French translation for the website / app / github ? I would be happy to do it and would also appreciate some Tron rewards. My e-mail : salocinigrub@gmail.com

**Comment by ybhgenius** [comment]
Hello,

Thanks for your participation.

Please check this link:

https://crowdin.com/project/trondocs

You can translate or correct relevant texts through this link.

We will reward you according to your contribution.

Best Regards

Boheng Yang

**Comment by Rovak** [comment]
Closing this issue as translations are now being done through Crowdin. Follow the link above to contribute your translations.
