### ISSUE TITLE
Websocket 

### ISSUE THREAD

**Issue by puffanddmx** [tronprotocol/java-tron#2673]
Hi
I want to make websocket for getting the latest block from tron fullnode.
Ether has subscribe, how to make it on tron node not polling?

**Comment by jiangyy0824** [comment]
@puffanddmx TRON has provided build-in message queue for subscribing. Please refer to https://github.com/tronprotocol/TIPs/blob/master/tip-28.md

The configuration of message queue is in config.conf. You can enable the trigger according to your requirement.
for example, 

```
topics = [
{
      triggerName = "block" // block trigger, the value can't be modified
      enable = true
      topic = "block" // plugin topic, the value could be modified
},

```
Subscribe client
Topics to subscribe, they are case-sensitive. 

```
blockTrigger
transactionTrigger
contractLogTrigger
contractEventTrigger
```
 
Test code

JAVA

try (ZContext context = new ZContext()) {

   ZMQ.Socket subscriber = context.createSocket(SocketType.SUB);
   subscriber.subscribe("blockTrigger");
   subscriber.subscribe("transactionTrigger");
   subscriber.subscribe("contractLogTrigger");
   subscriber.subscribe("contractEventTrigger");

   while (!Thread.currentThread().isInterrupted()) {
      byte[] message = subscriber.recv();
      System.out.println("receive : " + new String(message));
   }
}

 
Python

import zmq
import sys

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.connect("tcp://localhost:5555")
socket.setsockopt_string(zmq.SUBSCRIBE,'blockTrigger') 
socket.setsockopt_string(zmq.SUBSCRIBE,'transactionTrigger') 
socket.setsockopt_string(zmq.SUBSCRIBE,'contractLogTrigger')  
socket.setsockopt_string(zmq.SUBSCRIBE,'contractEventTrigger') 

while True:
    response = str(socket.recv(), encoding = "utf8")
    print(response)
 

Nodejs

var zmq = require('zeromq')
    , sock = zmq.socket('sub');

sock.connect('tcp://127.0.0.1:5555');
sock.subscribe('blockTrigger');
sock.subscribe('transactionTrigger');
sock.subscribe('contractLogTrigger');
sock.subscribe('contractEventTrigger');

sock.on('message', function(topic, message) {
  console.log(new Buffer(topic).toString('utf8'), new Buffer(message).toString('utf8'));
});
 

Go

func main() {
   subscriber, _ := zmq.NewSocket(zmq.SUB)
   defer subscriber.Close()
   subscriber.Connect("tcp://127.0.0.1:5555")
   subscriber.SetSubscribe("blockTrigger")
   subscriber.SetSubscribe("transactionTrigger")
   subscriber.SetSubscribe("contractLogTrigger")
   subscriber.SetSubscribe("contractEventTrigger")

   for {
      msg, _ := subscriber.Recv(0)
      fmt.Printf( msg);
   }
}

**Comment by jiangyy0824** [comment]
You should also add "--es"  to command line, for example:
 java -jar FullNode.jar -c config.conf --es

**Comment by l3lackrooz** [comment]
@jiangyy0824  i cant receive any data from contract event & contract log
`event.subscribe = {
    native = {
      useNativeQueue = true // if true, use native message queue, else use event plugin.
      bindport = 5555 // bind port
      sendqueuelength = 1000 //max length of send queue
    }

    path = "/home/user/fullnode/event-plugin/build/plugins/plugin-kafka-1.0.0.zip" // absolute path of plugin
    server = "127.0.0.1:50051" // target server address to receive event triggers
    contractParse = true,
    topics = [
        {
          triggerName = "block" // block trigger, the value cant be modified
          enable = true
          topic = "block" // plugin topic, the value could be modified
        },
        {
          triggerName = "transaction"
          enable = true
          topic = "transaction"
        },
        {
          triggerName = "contractevent"
          enable = true
          topic = "contractevent"
        },
        {
          triggerName = "contractlog"
          enable = true
          topic = "contractlog"
        },
        {
          triggerName = "solidity"  // solidity block event trigger, the value cant be modified
          enable = true // the default value is true
          topic = "solidity"
        },
        {
          triggerName = "solidityevent"
          enable = true
          topic = "solidityevent"
        },
        {
          triggerName = "soliditylog"
          enable = true
          topic = "soliditylog"
        }
    ]

    filter = {
       fromblock = "" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
       toblock = "" // the value could be "", "latest" or a specified block number as end of the queried range
       contractAddress = [
           "" // contract address you want to subscribe, if its set to "", you will receive contract logs/events with any contract address.
       ]

       contractTopic = [
           "" // contract topic you want to subscribe, if its set to "", you will receive contract logs/events with any contract topic.
       ]
    }
    
}
`

**Comment by Bratishques** [comment]
Someone has the answer to this issue? Running full node is sync and cant get anything from mentioned node.js code

**Comment by gbl-tylers** [comment]
@jiangyy0824 Is there a reason that this functionality isn't documented anywhere in official documentation except for in issues like this? https://developers.tron.network/docs/event-subscription doesn't mention it, nor does https://tronprotocol.github.io/documentation-en/developers/deployment/#event-subscribe-plugin-deployment.

The only sources are tickets talking about how this functionality isn't working for them. Would be great if there was more support for this method of interacting with the blockchain

**Comment by BeycanDeveloper** [comment]
Hi, I was facing the same problem and that's why I developed [https://tronsocket.com](https://tronsocket.com) it will probably fulfill your need.

We took care of the node installation processes that other friends gave in their examples and we took the risk to cover the expensive server costs. You can use our service by simply creating a token.
