### ISSUE TITLE
Contribution Winners of November is Published! 

### ISSUE THREAD

**Issue by jiangyy0824** [tronprotocol/java-tron#2693]
Dear developers,

Our Community Developers Incentives Program has been on its second month.

Thanks to every developer who contributes to our project.

By the end of the 30 Nov, 2019, the top 5 winners are:

NO.1 richardhallhall, 200 USDT
NO.2 Zara-lang, tronalex, Parachuteuk, tomos01, 180 USDT
NO.3 geb789, 150 USDT
NO.4 sss-rain110, james-green-am, FernandoT9, Marilas, 120 USDT
NO.5 M-blockcoder, 100 USDT

Congratulation! The cash reward will be sent in the form of USDT ASAP.

You can claim your reward by emailing your USDT address to coreDevs@tron.network through the email you used to contribute to our project before the end of 10 Dec, 2019.

For those who failed to end up in Top 5, keep your chin up! The points gap is very small, so continute to earn points, then next month or the quarter reward may hit you.

For more information, please refer to:

https://tronprotocol.github.io/documentation-en/developers/incentives/
https://tronscan.org/#/developersreward

**Comment by jiangyy0824** [comment]
@tronalex @richardhallhall We haven't received your usdt address. Please send the address to coreDevs@tron.network ASAP. Thanks.

**Comment by tronalex** [comment]
@jiangyy0824 Thanks for your reminder. The address is provided. Please check.

**Comment by jiangyy0824** [comment]
@tronalex @richardhallhall @Zara-lang @geb789 @sss-rain110 @M-blockcoder @james-green-am @ FernandoT9 @marilas  
Thanks for your contributions. The bonus has been released.
