### ISSUE TITLE
TRX deposits are completed on Etherscan but not in exchange account

### ISSUE THREAD

**Issue by KingBababalang** [tronprotocol/java-tron#27]
Hello,  I am hoping you can help because the problem below is happening to hundreds of people and there is a growing panic. Over the last month, some deposits into HitBTC are not going through. The transactions look successful on Etherscan but are not being deposited into our accounts. HitBTC support is completely non-responsive to anyone.  Can you please shed some light on what is causing this? Here is my last and non-received transaction:

0x1c68d4a21daadf9faa4d0c4a2462e0a96312becd1c127c5b5975e1e996627fee

For comparison, here is the previous transaction which was successfully received:

0x3e8a79f5cc48f55dd844714c19bc53f52ae4211e5287d3eeae41636ea48de549

Please let me know what is the cause and I will pass the message on to the rest of the affected community. Is there anything we can do to fix this? 

Thank you

**Comment by Rovak** [comment]
How is this relevant to the java-tron project? You should contact HitBTC support. Some people on twitter report that they got their deposit after 2 days.

A lot of exchanges are experiencing degraded performance.

**Comment by farukonder** [comment]
this is not a forum page. this ticket should be closed immediatelly.
