### ISSUE TITLE
Suggestion for improvement query "listwitnesses"

### ISSUE THREAD

**Issue by tronfamily** [tronprotocol/java-tron#2700]
### 1. What did you do?
Many queries are necessary to keep your app in the Votes section up to date.

1x query "Listwitnesses" - ~220 entries
220x queries "GetAccount" - to get the name of each single candidate
220x queries "GetBrokerage" - to find out the current level of rewards.

These are 441 queries. If you could add the name and the brokerage info, it would only be 1 query.

### 2. What did you expect to see?
`{"witnesses": [{
  "name": "54524f4e2d46616d696c79",
  "address": "41de9c3c2276abe2da70a7cdb34a205ecf7750d063",
  "voteCount": 13618992,
  "brokerage": 0,
  "url": "https://twitter.com/tron_family"
}]}`
![wish](https://user-images.githubusercontent.com/55282514/69989531-173c2b00-1544-11ea-8696-9024ecdebec9.png)

### 3. What did you see instead?
`{"witnesses": [{
  "address": "41de9c3c2276abe2da70a7cdb34a205ecf7750d063",
  "voteCount": 13618992,
  "url": "https://twitter.com/tron_family"
}]}
`
![now](https://user-images.githubusercontent.com/55282514/69989530-173c2b00-1544-11ea-8c75-f616b462f6c0.png)

**Comment by zhangwenhua-tron** [comment]
@tronfamily , thanks for your suggestion, but I'm afraid we cannot do it in a short time, because the structure of the data need to be modified to satisfy the new feature. Otherwise, we need to read three different stores to fetch all the data, and this will increase the response time.
