### ISSUE TITLE
translation mistake on web

### ISSUE THREAD

**Issue by 451PCBCOM** [tronprotocol/java-tron#2701]
### 1. What did you do?

Check the spanish web page of a token contract on tronscan.org
For example:
https://tronscan.org/#/contract/TJzcEaqgYk9g4jZLEsB2DksLGikM4dWwYJ/code

### 2. What did you expect to see?
You can read: "Escribit contrato"

### 3. What did you see instead?
The right spanish translation is:
"Escribir contrato"
![Captura de pantalla de 2019-12-02 21-14-19](https://user-images.githubusercontent.com/52361477/69992169-63d63500-1549-11ea-8b90-3bfe7ef52512.png)

**Comment by jiangyy0824** [comment]
Thank you for your feedback. We'll follow up soon.

**Comment by 451PCBCOM** [comment]
Nice.
You are wellcome.

Another big translation mistake is in the first page of tronscan.org:
"Aumento de cuenta en los últimos 14 días"

The real translation of "14 days Accounts Growth" is:
"Aumento de cuentas en los últimos 14 días" or "Crecimiento de cuentas en los últimos 14 días".

Regards.
451pcb.com
![Captura de pantalla de 2019-12-04 18-11-27](https://user-images.githubusercontent.com/52361477/70164845-35c83080-16c2-11ea-8f65-642b1fe530eb.png)
