### ISSUE TITLE
你好，请问有编译好的jar包吗？ 我这边编译一直报错

### ISSUE THREAD

**Issue by ying23** [tronprotocol/java-tron#2717]

**Comment by jiangyy0824** [comment]
@ying23 You can find the jar from https://github.com/tronprotocol/java-tron/releases
If you need to compile the jar correctly, please tell me the steps you build and attach the detailed error log. Thanks.

**Comment by ying23** [comment]
@jiangyy0824  This's detailed error log. Thanks.
[root@localhost java-tron]# ./gradlew build

> Task :generateProto UP-TO-DATE
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.

> Task :compileJava 
/home/trx/java-tron/src/main/java/org/tron/common/overlay/discover/DiscoverServer.java:21: warning: Arg is internal proprietary API and may be removed in a future release
import com.sun.org.apache.xpath.internal.Arg;
                                        ^
Note: class org.pf4j.processor.ExtensionAnnotationProcessor init
/home/trx/java-tron/src/main/java/org/tron/common/overlay/discover/DiscoverServer.java:21: warning: Arg is internal proprietary API and may be removed in a future release
import com.sun.org.apache.xpath.internal.Arg;
                                        ^
/home/trx/java-tron/src/main/java/org/tron/core/db/Manager.java:38: error: package javafx.util does not exist
import javafx.util.Pair;
                  ^
/home/trx/java-tron/src/main/java/org/tron/core/db/KhaosDatabase.java:15: error: package javafx.util does not exist
import javafx.util.Pair;
                  ^
/home/trx/java-tron/src/main/java/org/tron/core/db/KhaosDatabase.java:273: error: cannot find symbol
  public Pair<LinkedList<KhaosBlock>, LinkedList<KhaosBlock>> getBranch(Sha256Hash block1,
         ^
  symbol:   class Pair
  location: class KhaosDatabase
/home/trx/java-tron/src/main/java/org/tron/core/db/KhaosDatabase.java:321: error: cannot find symbol
  public Pair<LinkedList<BlockCapsule>, LinkedList<BlockCapsule>> getBranch(
         ^
  symbol:   class Pair
  location: class KhaosDatabase
/home/trx/java-tron/src/main/java/org/tron/core/net/service/SyncService.java:17: error: package javafx.util does not exist
import javafx.util.Pair;
                  ^
/home/trx/java-tron/src/main/java/org/tron/core/net/peer/PeerConnection.java:14: error: package javafx.util does not exist
import javafx.util.Pair;
                  ^
/home/trx/java-tron/src/main/java/org/tron/core/net/peer/PeerConnection.java:101: error: cannot find symbol
  @Getter
  ^
  symbol:   class Pair
  location: class PeerConnection
/home/trx/java-tron/src/main/java/org/tron/common/overlay/discover/DiscoverServer.java:21: warning: Arg is internal proprietary API and may be removed in a future release
import com.sun.org.apache.xpath.internal.Arg;
                                        ^
7 errors
3 warnings


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
4 actionable tasks: 1 executed, 3 up-to-date

**Comment by jiangyy0824** [comment]
@ying23 
1. code branch
2. jdk version

https://github.com/tronprotocol/documentation/blob/master/TRX/Solidity_and_Full_Node_Deployment_EN.md

**Comment by ying23** [comment]
1.code branch of java-tron
[root@localhost java-tron]# git branch
* master

2.jdk version
[root@localhost java-tron]# java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

**Comment by jiangyy0824** [comment]
Open JDK 8 in the system. If you are building the source code by using Open JDK 8, you will get Build Failed result.
Please refer to the link https://github.com/tronprotocol/documentation/blob/master/TRX/Solidity_and_Full_Node_Deployment_EN.md

**Comment by ying23** [comment]
@jiangyy0824 
Build successful, thanks.
