### ISSUE TITLE
GetAccount RPC does not return errors correctly

### ISSUE THREAD

**Issue by hlb8122** [tronprotocol/java-tron#2761]
### 1. What did you do?
Call GetAccount RPC with an unknown address/invalid address.

### 2. What did you expect to see?
Response with status code 5 NOT_FOUND/3 INVALID_ARGUMENT.

### 3. What did you see instead?
Status code 0 but with an empty Account response.

**Comment by kevinLee2015** [comment]
Hi,
Thank you for your suggestion. We may improve it in the future version.

**Comment by hlb8122** [comment]
On closer inspection it's not just GetAccount, it seems that all RPC commands return null rather than an error when an error occurs.

**Comment by kevinLee2015** [comment]
Yes, we will put it on our schedule.

**Comment by andelf** [comment]
Related TIP: https://github.com/tronprotocol/tips/pull/126/files?short_path=a29997a#diff-a29997a9ac8d5d2bce94e1d681a8e208

**Comment by Benson0224** [comment]
After reviewing with the team, this kind of change will cause compatibility issues. we decide to ignore this issue. 
Suggest developers do a workaround based on current return value.
