### ISSUE TITLE
question:how to vote ,freeze, unfreeze in contract ?

### ISSUE THREAD

**Issue by jin10086** [tronprotocol/java-tron#2787]
i want to freeze, unfreeze ,vote in contract 

but i can't find manual,

Can you give me the document or the demo code

**Comment by kevinLee2015** [comment]
You can refer to the api 'freezebalance', 'unfreezebalance', 'votewitnessaccount' in
https://tronprotocol.github.io/documentation-en/api/http/

**Comment by jin10086** [comment]
@kevinLee2015  in contract ,not http api

**Comment by mattopolitan** [comment]
Hi @jin10086 
If you are asking how to write smart contract in TRON, as they are written in Solidity, you may search for the answers directly in Solidity-related materials. 

Not sure if these would be helpful for you?

1. Freeze & Unfreeze 
https://ethereum.stackexchange.com/questions/17235/freeze-an-amount-in-address-until-i-unfreeze-it
2. Vote
https://solidity.readthedocs.io/en/latest/solidity-by-example.html

**Comment by shydesky** [comment]
> i want to freeze, unfreeze ,vote in contract
> 
> but i can't find manual,
> 
> Can you give me the document or the demo code

these operations can not be done in the contract.

**Comment by jin10086** [comment]
@shychrdw  ok...
