### ISSUE TITLE
Contribution Winners of December is Published! 

### ISSUE THREAD

**Issue by jiangyy0824** [tronprotocol/java-tron#2825]
Dear developers,

Our Community Developers Incentives Program has been on its third month.

Thanks to every developer who contributes to our project.

By the end of the 31 Dec, 2019, the top 5 winners are:

NO.1 tronalex 200 USDT
NO.2 geb789, greygary01, jassfferson01 180 USDT
NO.3 Zara-lang, Parachuteuk, tomos01, Marilas, M-blockcoder, helloboy 150 USDT

Congratulation! The cash reward will be sent in the form of USDT ASAP.

You can claim your reward by emailing your USDT address to coreDevs@tron.network through the email you used to contribute to our project before the end of 5 January, 2020.

For those who failed to end up in Top 5, keep your chin up! The points gap is very small, so continue to earn points, then next month or the quarter reward may hit you.

For more information, please refer to:

https://tronprotocol.github.io/documentation-en/developers/incentives/
https://tronscan.org/#/developersreward

**Comment by jiangyy0824** [comment]
@tronalex @geb789 @gregary01 @jafferson01 @ZaraLang @Parachuteuk @tomos01 @marilas @M-blockcoder @helloboy 
Congratulations! Please check the reward list.

**Comment by jiangyy0824** [comment]
![dec](https://user-images.githubusercontent.com/9377378/71656815-e1bf7300-2d77-11ea-8cff-b9c388cf4bc5.jpeg)

**Comment by Starsakary** [comment]
@ZaraLang @Parachuteuk @tomos01 @marilas Please send your: github id, USDT address to coreDevs@tron.network . If someone here has already sent a mail, please make sure the mail should include: **github id**  together with your USDT address
