### ISSUE TITLE
Contribution Winners of fourth quarter is Published! 

### ISSUE THREAD

**Issue by jiangyy0824** [tronprotocol/java-tron#2826]
Dear developers,

Our Community Developers Incentives Program has been on for one quarter.

Thanks to every developer who contributes to our project.

From the start of OCT 2019 to the end of DEC  2019, the top 5 winners of the fourth quarter are:

NO.1 geb789, 200 USDT
NO.2 Zara-lang, 180 USDT
NO.3 tronalex, 150 USDT
NO.4 bjianhang, 120 USDT
NO.5 richardhallhall, Parachuteuk, tomos01, 100 USDT

Congratulation! The cash reward will be sent in the form of USDT ASAP.

You can claim your reward by emailing your USDT address to coreDevs@tron.network through the email you used to contribute to our project before the end of 7 Jan, 2020.

For those who failed to end up in Top 5, keep your chin up! The points gap is very small, so continute to earn points, then next month or the quarter reward may hit you.

For more information, please refer to:

https://tronprotocol.github.io/documentation-en/developers/incentives/
https://tronscan.org/#/developersreward

**Comment by jiangyy0824** [comment]
Congratulations! Please check the reward list.
@geb789 @ZaraLang @tronalex @bjianhang @richardhallhall @Parachuteuk @tomos01

**Comment by jiangyy0824** [comment]
![quarter](https://user-images.githubusercontent.com/9377378/71656711-5d6cf000-2d77-11ea-9558-7695b8485bef.jpeg)

**Comment by Starsakary** [comment]
@ZaraLang @bjianhang @Parachuteuk @tomos01 Please send your: github id, USDT address to coreDevs@tron.network . If someone here has already sent a mail, please make sure the mail should include: **github id** together with your USDT address

**Comment by richardhallhall** [comment]
@Starsakary @jiangyy0824 Has the award been released? No reward yet. Pls check.
