### ISSUE TITLE
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

### ISSUE THREAD

**Issue by will7455** [tronprotocol/java-tron#2850]
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

Install the 1.8 jdk its a dependency issue the error comes from a function that has been deprecated in the latest java version.

_Originally posted by @AydenRennaker in https://github.com/tronprotocol/java-tron/issues/337#issuecomment-377663500_

```
$ sudo add-apt-repository ppa:webupd8team/java
$ sudo apt-get update

$ sudo apt-get install oracle-java8-installer

$ sudo apt install oracle-java8-installer
```
//Reading package lists... Done
//Building dependency tree
//Reading state information... Done
//Package oracle-java8-installer is not available, but is referred to by another package.
//This may mean that the package is missing, has been obsoleted, or
//is only available from another source
//E: Package 'oracle-java8-installer' has no installation candidate
//root@tron:~#

**This no longer works**

**Comment by guoquanwu** [comment]
you can download jdk8 from oracle official web and install by yourself.
BTW, why question here?
