### ISSUE TITLE
BroadCastTransaction failed

### ISSUE THREAD

**Issue by zaga01** [tronprotocol/java-tron#2858]
{"visible":false,"signature":["1d38f6d6f6728ebc17b99df7b37635e81e1eba3fdc6e175830072324d4a006715fc7672938759470204158ae082c12517304923ec5e1d9a7cab4e8348b9cdb7901"],"txID":"68223c2f1c0c451c534d0b12a697d4067951152665a7550146eb2be83571ed2d","raw_data":{"contract":[{"parameter":{"value":{"amount":41814000,"owner_address":"4165c0443ca50eb3c2147532377c4f9925ed21e290","to_address":"41007499642efab20417b7cb29a17ae82af3ab3885"},"type_url":"type.googleapis.com/protocol.TransferContract"},"type":"TransferContract"}],"ref_block_bytes":"2463","ref_block_hash":"b1736b2bfff206f6","expiration":1578648957000,"timestamp":1578648898680},"raw_data_hex":"0a0224632208b1736b2bfff206f640c8e0bdf6f82d5a68080112640a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412330a154165c0443ca50eb3c2147532377c4f9925ed21e290121541007499642efab20417b7cb29a17ae82af3ab388518f08ff81370f898baf6f82d"}

{"code": "CONTRACT_VALIDATE_ERROR","message": "636f6e74726163742076616c6964617465206572726f72203a2056616c6964617465205472616e73666572436f6e7472616374206572726f722c2062616c616e6365206973206e6f742073756666696369656e742e"}

How to solve the problem？

**Comment by andelf** [comment]
```console
> bytes.fromhex('636f6e74726163742076616c6964617465206572726f72203a2056616c6964617465205472616e73666572436f6e7472616374206572726f722c2062616c616e6365206973206e6f742073756666696369656e742e')
b'contract validate error : Validate TransferContract error, balance is not sufficient.'
```

**Comment by zaga01** [comment]
我知道了，对方是新生成的地址，没有激活，好像是要扣0.1trx费用？这个费用是干嘛用的呢？支付给矿工？




| |
周承鹏
|
|
邮箱：yaotingzcp@163.com
|

签名由 网易邮箱大师 定制

**Comment by zaga01** [comment]
就是因为要扣0.1trx，所以余额不足，减去0.1就能转




| |
周承鹏
|
|
邮箱：yaotingzcp@163.com
|

签名由 网易邮箱大师 定制

On 01/10/2020 18:19, zaga01 wrote:
我知道了，对方是新生成的地址，没有激活，好像是要扣0.1trx费用？这个费用是干嘛用的呢？支付给矿工？




| |
周承鹏
|
|
邮箱：yaotingzcp@163.com
|

签名由 网易邮箱大师 定制

**Comment by andelf** [comment]
When transferring to an address that does not exist, the account creation fee will be paid.

The reason for this design is to increase the cost of evil doing.

Thank you

转账到不存在地址时候会默认支付账户创建费用.

之所以这么设计是为了提高作恶成本.

谢谢

**Comment by zaga01** [comment]
关于trx交易的带宽消耗问题，我猜想如下：
每个账号都有5000带宽费用，用于支付交易手续费，如果消耗完了是不是得从账号里扣trx费用？

或者说每个账号的带宽都会维持一个平衡，充值的时候会增加带宽费用，提现的时候会减少带宽费用？

哪种猜测是对的呢





| |
周承鹏
|
|
邮箱：yaotingzcp@163.com
|

签名由 网易邮箱大师 定制

On 01/10/2020 18:25, ShuYu Wang wrote:

When transferring to an address that does not exist, the account creation fee will be paid.

The reason for this design is to increase the cost of evil doing.

Thank you

转账到不存在地址时候会默认支付账户创建费用.

之所以这么设计是为了提高作恶成本.

谢谢

**Comment by andelf** [comment]
<https://cn.developers.tron.network/docs/bandwidth-points>

😄 Freezed -> Free Bandwidth -> TRX balance

**Comment by andelf** [comment]
@zaga01 Can this issue be closed?

**Comment by zaga01** [comment]
> @zaga01 Can this issue be closed?

yes, i close it
