### ISSUE TITLE
How to get account address by account name?

### ISSUE THREAD

**Issue by bh1xuw** [tronprotocol/java-tron#2859]
GetAccount(actually it is a by-address call), GetAccountById already exists.

How to get account address by account name?

**Comment by guoquanwu** [comment]
sry, not supported yet

**Comment by andelf** [comment]
This is a missing feature. Will be implemented.

**Comment by guoquanwu** [comment]
accountName in tron is not unique, it is just a nickname, so can't  get accountinfo by name, GetAccountById is Preferred

**Comment by andelf** [comment]
won't fix
