### ISSUE TITLE
multisig signing bug

### ISSUE THREAD

**Issue by gologo13** [tronprotocol/java-tron#2893]
### 1. What did you do?

we develop enterprise cryptocurrency trading system.

we tried to send TRX from multisig address.
the flow of our program is as follows:

1. create a multisg address (2-of-3)
2. build a transaction with a transfer contract from the address
3. add signatures from 2 cosigners to the transaction
4. check transaction sign weight 
5. if we see `ENOUGH_PERMISSION` of sign weight return code, we broadcast the transaction.

However, the problem is we sometimes don't see `ENOUGH_PERMISSION` even though our signing process is successful.
this problems doesn't always happen. 
However, if this issue happens once, it never be recovered automatically. 
in that sense, this issue is critical to us.

we use https://github.com/tronprotocol/wallet-cli as API client and run programs in private net of Odyssey-v3.6.6.

### 2. What did you expect to see?

after multi signing process completes, what we expect is

* see `ENOUGH_PERMISSION(0)` in return code of `getTransactionSignWeight` API 
* see 2 cosigner addresses in approved list of `getTransactionSignWeight` API 

### 3. What did you see instead?

here is the log of our programs when we ran multi signing process in private net.
I added comments for each log output about what we're doing and our opinion.

NB: I removed some commercial information such as class name and package names.

```
// this is the owner permission of the multisig address in question.
// as you can see, there are 3 cosigners and the number of minimum required signatures is 2.
TRACE 2020-01-17 18:27:30.050 {http-nio-9080-exec-1}: owner permission of multisig address [address=TTNr1TqnrYbgnnCo2HdD91r4YBQiCJ266a, permission=permission_type: Owner
permission_id: 0
permission_name: 
threshold: 2
parent_id: 0
operations: 
keys:
[
address: TRuqcmgua2kmacyKsbuwe3zDkZUyy5whFG
weight: 1
address: TLAa9EMUwoED7SgfHxkUx61fZQY66G1dzt
weight: 1
address: TN9RZtLcXHffb2yfH5SQCLVSje1Vdemmrk
weight: 1
]
]

// add a signature by one of the cosigners
DEBUG 2020-01-17 18:27:30.313 {http-nio-9080-exec-2}: signing multisig transaction [co-signer=TRuqcmgua2kmacyKsbuwe3zDkZUyy5whFG, tx-id=a618619d6f58e519500bb75d7a69c3d2a5e863dcb45c4b20e7dc8a4b2950a1dd]

// add a signature by another cosigner
DEBUG 2020-01-17 18:27:30.354 {http-nio-9080-exec-3}: signing multisig transaction [co-signer=TLAa9EMUwoED7SgfHxkUx61fZQY66G1dzt, tx-id=a618619d6f58e519500bb75d7a69c3d2a5e863dcb45c4b20e7dc8a4b2950a1dd]

// after multisig signing completes, we check the transaction sign weight to see if signatures are correctly added to the transaction
// we retry 10 times to fetch tx sign weight as long as we see return code except ENOUGH_PERMISSION (because first of all we thought this issue was related to temporary problem of java-tron)
// as you can see, 2 signatures are added in `Protocol.Transaction` object.
WARN  2020-01-17 18:27:39.500 {http-nio-9080-exec-1}: Retrying getTxSignWeight [current-attempt=9, arg=raw_data {
  ref_block_bytes: "\002\321"
  ref_block_hash: "!\323\vN`V@\b"
  expiration: 1579350447000
  contract {
    type: TransferContract
    parameter {
      type_url: "type.googleapis.com/protocol.TransferContract"
      value: "\n\025A\370\006\201\031\035\263\000*\344\367doP\177t\302\265\316+$\022\025ASW\267\243\307\024u\215U!\362X\v\254\370\311\334\325\351\211\030\350\a"
    }
  }
  timestamp: 1579314449789
}
signature: "*H\351i\v\022\370\303\306\375hx\243K\332\261\311\241l7\367\244\224\235\227\332\260!\232;\f\356\023\304\2316\344~n`U%\030\267\222HL5\263Z8\327\031 ys\021\001H\326?\302|C\000"
signature: "\023p\316\000\305\237\035\255T\027\2677OA\346\343\342K.\035\250W\276\024KO\325/\275\373\205\3072\300.\343\345\214\236\001\374\aIh\3347\200yK\220\017\"\214\254\021\3167\034Z\313\021\362\215(\000"
]

// finishes 10 retries, the some part of output of tx sign weight. we get no approved-list.
// after all, we could not see return code ENOUGH_PERMISSION
DEBUG 2020-01-17 18:27:39.507  {http-nio-9080-exec-1}: sign weight after co-signers make signatures [multisig-address=TTNr1TqnrYbgnnCo2HdD91r4YBQiCJ266a, approved-list=[]]

// this is the error response of tx sign weight and also the most problematic part.
// it's obvious that TRuqcmgua2kmacyKsbuwe3zDkZUyy5whFG is one of the cosigners of the multisig address in question, but java-tron says it's not.
cannot get enough signatures [code=PERMISSION_ERROR, message=2a48e9690b12f8c3c6fd6878a34bdab1c9a16c37f7a4949d97dab0219a3b0cee13c49936e47e6e60552518b792484c35b35a38d719207973110148d63fc27c4300 is signed by TRuqcmgua2kmacyKsbuwe3zDkZUyy5whFG but it is not contained of permission., current-sign=0]
```

Please let us know if you need additional information.

**Comment by andelf** [comment]
Can't find your address on any of mainnet / testnet. 
So I can't check the permission settings.
Is this your private net?

**Comment by gologo13** [comment]
> Is this your private net?

Yes, we test on private net.

**Comment by gologo13** [comment]
I intended this issue is a bug report.

**Comment by andelf** [comment]
Ok, I'll investigate it.

**Comment by shydesky** [comment]
Could you please show me the output of Http API --  **http://yourIP:port/wallet/getaccount?address= TTNr1TqnrYbgnnCo2HdD91r4YBQiCJ266a&visible=true**
we can discuss this issue in the Gitter channel:  **https://gitter.im/tronprotocol/wallet-cli**

**Comment by gologo13** [comment]
Hi, thank you for your attentions.

> Could you please show me the output of Http API -- http://yourIP:port/wallet/getaccount?address=TTNr1TqnrYbgnnCo2HdD91r4YBQiCJ266a&visible=true


Unfortunately the environment has already gone.. it worked in the docker environment. I'm trying to reproduce it, but still don't get conditions for the reproduction.
we run the full node inside the docker container with the following command:

```bash
$ nohup java -jar FullNode.jar -c fullnode.conf --witness >/dev/null 2>&1 &
```

this problem happened once on my laptop(macOS) and several times on Jenkins (ubuntu) environment.

judging from the source code, one possible cause I think is `permission` was an empty list in `getWeight` method.

https://github.com/tronprotocol/java-tron/blob/a9c0b877f247101851289dc592a6b8efae034b8a/chainbase/src/main/java/org/tron/core/capsule/TransactionCapsule.java#L213

this may be irrelevant to this topic, but sometimes we face `ownerAddress account does not exist` error when we create new accounts from some account.

```
ERROR 2020-01-02 02:53:39.026 {http-nio-9080-exec-9}: failed to validate contract for updating account permissions [tx = result {
  code: CONTRACT_VALIDATE_ERROR
  message: "contract validate error : ownerAddress account does not exist"
}
]
```

`ownerAddress` is defined at `genesis.block` in full.conf with good amount of fund through.
that sounds strange too.
this is just my guesswork, but considering everything it's possible that data fetches from database or cache failed for a reason.

**Comment by shydesky** [comment]
@gologo13  hi, I advise you determine whether your SuperNodes of the private network have reached the consensus about the UpdatePermission transactions.  And then you can start the multisign transaction.

**Comment by gologo13** [comment]
@shychrdw thank you for your suggestion. okay, I'll do that. 
I'll close this ticket for now. I'll reopen if I reproduce it and can get an output of HTTP API (wallet/getaccount)

**Comment by Fishojoy** [comment]
Hi, I am not sure if this right place to ask
Is anyone here able to give me advice, hacker got my tronwallet and he put a multi signature replace my access.. any way I can revoke that?

**Comment by axiang-huge** [comment]
java-tron deployed to the MacOS environment has a permission issue using the wallet-cli SendCoin command. This is the exception message given:
sendcoin failed!
4b2b50dd2080df8f3c1a51b44ecb2e97e5827f7d50215e65120b0d52699b01223bac48ebe7ecb443c34a09f23f23ff259951a3535a98aa0da910307e 9200138701 is signed by TCaF9bUQzZbBtHXFHcLHKi44g43ijFqdnz but it is not contained of permission.
