### ISSUE TITLE
What is the best way to sync FullNode fast?

### ISSUE THREAD

**Issue by yivo** [tronprotocol/java-tron#2905]
I recently managed to deploy FullNode to VM with large size SSD and lot of memory and great network connection (GCP) however node downloaded blocks only up to 4M (4 000 000) in two days. Up to date height in TRX is around 16M. So I guess node will require around 10-14 days to sync fully.

Is there any way to dot this faster?

**Comment by kevinLee2015** [comment]
You can download the data backup from http://47.89.178.46/

**Comment by yivo** [comment]
@kevinLee2015 Nice! Thank you

**Comment by Reza-SadriNia** [comment]
> You can download the data backup from http://47.89.178.46/

How Can I Use From Thin Database ?
