### ISSUE TITLE
java trc20 usdt转账怎么实现

### ISSUE THREAD

**Issue by yangjianyao** [tronprotocol/java-tron#2907]
目前使用SHASTA TESTNET，想实现usdt转账功能和监听交易功能，查看了官方文档，没有找到相关的代码，有相关的文档或者技术群吗？

**Comment by guoquanwu** [comment]
> 目前使用SHASTA TESTNET，想实现usdt转账功能和监听交易功能，查看了官方文档，没有找到相关的代码，有相关的文档或者技术群吗？

Translation in English: Now I want to transfer USDT and monitor the transaction as well on SHASTA TESTNET, but I don't find any references about this, can someone give me some references or any technical community for help?

**Comment by guoquanwu** [comment]
How about this: https://developers.tron.network/docs/trc20-introduction

If this still doesn’t solve your doubts, you can join our official developer telegram group: https://t.me/TronOfficialDevelopersGroupEn. 

We also have wechat developer group, you can also provide your wechat ID, so I can invite you.

**Comment by yangjianyao** [comment]
thanks,I have joined tg

**Comment by jiangyy0824** [comment]
Hello, 

If your problem has been solved, please close this issue. 

Thank you!

**Comment by yangjianyao** [comment]
it has not been solved, I'm trying to solve it

**Comment by andelf** [comment]
Close for no response for long.
Feel free to re-open or open-new if you have any questions.
:)

**Comment by yujianFresh** [comment]
> 目前使用SHASTA TESTNET，想实现usdt转账功能和监听交易功能，查看了官方文档，没有找到相关的代码，有相关的文档或者技术群吗？

hello,你这个问题解决了吗？我也在寻找trx20转账的java离线签名demo
