### ISSUE TITLE
无法获取到交易

### ISSUE THREAD

**Issue by TroyWind** [tronprotocol/java-tron#2919]
### 1. What did you do?

我通过以下api想要获取某个地址的交易：
https://api.trongrid.io/v1/accounts/TZAE5EXugxrxgMjAVS6YjNpJdrpXQBPokd/transactions
但是得到的交易个数为0，而该地址是有一个交易的，交易ID是：
e57492ab5656a44022922bb1831d3837bf60a49c4b6b8e9836cc9e7b235ddeaa
并且我上tronscan查看该地址时，在交易页签也无法看到该交易，只能在转账页签中看到该交易
请问除了调用该API，我还有没其它方法可以到某个地址的交易？我这需要监听到这些交易后在系统中为对应用户做业务操作

### 2. What did you expect to see?
获取到该地址的交易

### 3. What did you see instead?
0个交易

**Comment by jiangyy0824** [comment]
@TroyWind This trongrid related issue. I have forwarded it to the dev team.  Thanks.

**Comment by shenyongri110** [comment]
@jiangyy0824 Since it's a trc20 transaction, we have separate api to retrieve the trc20 transaction data,
https://api.trongrid.io/v1/accounts/TZAE5EXugxrxgMjAVS6YjNpJdrpXQBPokd/transactions/trc20, Please use this api to have a try, thanks.
