### ISSUE TITLE
JSON-RPC API?

### ISSUE THREAD

**Issue by kevholder** [tronprotocol/java-tron#2921]
Does Tron have a JSON-RPC API similar to [Ethereum's JSON-RPC API](https://github.com/ethereum/wiki/wiki/JSON-RPC)? I'm trying to port a dApp to Tron and couldn't find any documentation on a JSON-RPC API. It seems that only a [REST like API is available](https://developers.tron.network/reference#wallets-accounts)?

**Comment by jiangyy0824** [comment]
Hi @kevholder TRON use gRPC instead of JSON-RPC. Please refer to https://tronprotocol.github.io/documentation-en/api/http/ , hope it helps.
If you have any other question, please join https://t.me/troncoredevscommunity

**Comment by andelf** [comment]
Close for no response.  😃 
(Also answered you on telegram channel)
Feel free to re-open or open-new if you have any questions.

**Comment by 0xcoinymous** [comment]
Yes JSON-RPC is available on the Tron network. check this API: https://api.trongrid.io/jsonrpc

Example request:
```sh
curl -X POST 'https://api.trongrid.io/jsonrpc' \
--data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":64}'
```
Example response:
```json
{"jsonrpc":"2.0","id":64,"result":"0x42a6672"}
```
