### ISSUE TITLE
Java 10? - currently unable to compile java-tron with JDK 10

### ISSUE THREAD

**Issue by seanrobbins** [tronprotocol/java-tron#295]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

With the recent release of Java JDK 10, I tried building java-tron with the latest version of java.

2. What did you expect to see?

I hoped to see the upgrade path for java-tron to the latest JDK to be unimpeded.

3. What did you see instead?

Looks like these is a problem with java-tron's dependency lombok. lombok annotated classes are not currently compiling under java 10, see https://github.com/rzwitserloot/lombok/issues/1572

**This is not an issue with java-tron itself**. If there was interest in using the latest Java JDK features though this will be a blocker for now and in the future potential contributors may see issues with this when trying to build the code.

The only solution I was able to find was to return to a previous version of the Java JDK.

**Comment by zhaohong** [comment]
thanks!  we can fix this later.
