### ISSUE TITLE
Add note/memo support for HTTP API

### ISSUE THREAD

**Issue by AceLuodan** [tronprotocol/java-tron#2953]
由于http api 缺少直接的 附带备注的交易 ，导致开发难度上升，对用户和开发者不友好，请在http  api 新增备注字段！

**Comment by andelf** [comment]
For gRPC API, you can refer <https://github.com/tronprotocol/java-tron/issues/2954>.

For HTTP API, this is a feature request. 😃

**Comment by andelf** [comment]
Already implemented in https://github.com/tronprotocol/java-tron/pull/2583.
Will be in next major release.

**Comment by andelf** [comment]
This issue will be closed since it has already been fixed on the develop branch.
Thanks.
