### ISSUE TITLE
Tron testnet FullNode stuck at particular block

### ISSUE THREAD

**Issue by livingrock7** [tronprotocol/java-tron#2996]
### 1. What did you do?

followed https://tronprotocol.github.io/documentation-en/developers/deployment/

-clone the repo, compile it using gradlew build
-run the node using java -jar FullNode.jar -c test_net_config.conf
the config file was not modified

FullNode.jar is bopied from ./build/libs in repo (master branch)

### 2. What did you expect to see?

FullNode synced up to latest block as shows on test net explorer

### 3. What did you see instead?

Starts syncing from block 0 and goes up to this block 

curl -X POST  http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"000000000001b4e2ce2918536b4bd6e865cc14a6acbd1fd35ffe9ec21389f205","block_header":{"raw_data":{"number":111842,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"41a6d8443e85fe275b5ca6e8eb895bdfde60f4f261","parentHash":"000000000001b4e16fca040e61e304447b737c52f34d66164860abc6fe3a4caa","version":9,"timestamp":1562314029000},"witness_signature":"c4ba9c3c6e1ae48b7c3e8b3b994f2ce1a89241cf63bc6606b187c256b0b4b4d95371ad0195237a57dafe06952e093d4f6fab49702e219d55d9239809b80b8f6700"}}

Same response 

curl -X POST  http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"000000000001b4e2ce2918536b4bd6e865cc14a6acbd1fd35ffe9ec21389f205","block_header":{"raw_data":{"number":111842,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"41a6d8443e85fe275b5ca6e8eb895bdfde60f4f261","parentHash":"000000000001b4e16fca040e61e304447b737c52f34d66164860abc6fe3a4caa","version":9,"timestamp":1562314029000},"witness_signature":"c4ba9c3c6e1ae48b7c3e8b3b994f2ce1a89241cf63bc6606b187c256b0b4b4d95371ad0195237a57dafe06952e093d4f6fab49702e219d55d9239809b80b8f6700"}}

Here is the log,
I am getting PEER_DISCONNECT message

 Peer 47.252.80.97:18888 [fa96636e]
ping msg: count 18, max-average-min-last: 988 252 202 207
connect time: 11s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:111843
syncBlockRequestedSize:0
remainNum:6814891
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 0(0), discover: 1/1 33/33 89/89 0/0 205ms, p2p: 10/10/10 , tron: 768/75 X 9<=TIME_OUT , tcp flow: 320204

**Comment by livingrock7** [comment]
https://github.com/tronprotocol/java-tron/issues/2342

Someone has recommended using feature/ZenToken branch. I am not sure which branch should be used

**Comment by andelf** [comment]
I've checked the listing nodes. The code version is 3.6.2. The release tag is `Odyssey-v3.6.2`.



```
47.252.81.126:50051
    "codeVersion": "3.6.2",
47.252.80.163:50051
    "codeVersion": "3.6.2",
47.252.84.148:50051
    "codeVersion": "3.6.2",
47.252.80.45:50051
    "codeVersion": "3.6.2",
47.252.86.9:50051
    "codeVersion": "3.6.2",
47.252.81.42:50051
    "codeVersion": "3.6.2",
47.252.84.110:50051
    "codeVersion": "3.6.2",
47.252.81.102:50051
    "codeVersion": "3.6.2",
47.252.80.220:50051
    "codeVersion": "3.6.2",
47.252.80.96:50051
    "codeVersion": "3.6.2",
47.252.84.22:50051
    "codeVersion": "3.6.2",
47.252.81.33:50051
    "codeVersion": "3.6.2",
47.252.86.18:50051
    "codeVersion": "3.6.2",
47.252.84.177:50051
    "codeVersion": "3.6.2",
47.252.80.3:50051
    "codeVersion": "3.6.2",
47.252.81.135:50051
    "codeVersion": "3.6.2",
47.252.81.153:50051
    "codeVersion": "3.6.2",
47.252.87.234:50051
    "codeVersion": "3.6.2",
47.252.85.150:50051
    "codeVersion": "3.6.2",
47.252.81.120:50051
    "codeVersion": "3.6.2",
47.252.87.12:50051
    "codeVersion": "3.6.2",
47.252.84.142:50051
    "codeVersion": "3.6.2",
47.252.84.58:50051
......
```

**Comment by andelf** [comment]
You can join the Nile testnet, which is the newest.

<http://nileex.io/join/getJoinPage>

**Comment by livingrock7** [comment]
@andelf 
For current test net I am using, how can I fix the issue? Which branch is recommended?

If I were to use Nile I can change the config file, download the jar file and restart the node?

**Comment by andelf** [comment]
> For current test net I am using, how can I fix the issue? Which branch is recommended?

`Odyssey-v3.6.2`

> If I were to use Nile I can change the config file, download the jar file and restart the node?

Before restart, you should clean your data directory.

**Comment by livingrock7** [comment]
Thank you!

```
[root@localhost java-tron]# ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/chirag/tron/deploy/java-tron/build.gradle' line: 336

* What went wrong:
Could not determine the dependencies of task ':buildDBConvertJar'.
> Could not resolve all files for configuration ':compile'.
   > Could not resolve io.grpc:grpc-core:[1.14.0].
     Required by:
         project : > io.grpc:grpc-netty:1.14.0
      > Could not resolve io.grpc:grpc-core:[1.14.0].
         > Failed to list versions for io.grpc:grpc-core.
            > Unable to load Maven meta-data from http://repo.spring.io/plugins-release/io/grpc/grpc-core/maven-metadata.xml.
               > Could not get resource 'http://repo.spring.io/plugins-release/io/grpc/grpc-core/maven-metadata.xml'.
                  > Could not GET 'http://repo.spring.io/plugins-release/io/grpc/grpc-core/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve io.netty:netty-codec-http2:[4.1.27.Final].
     Required by:
         project : > io.grpc:grpc-netty:1.14.0
      > Could not resolve io.netty:netty-codec-http2:[4.1.27.Final].
         > Failed to list versions for io.netty:netty-codec-http2.
            > Unable to load Maven meta-data from http://repo.spring.io/plugins-release/io/netty/netty-codec-http2/maven-metadata.xml.
               > Could not get resource 'http://repo.spring.io/plugins-release/io/netty/netty-codec-http2/maven-metadata.xml'.
                  > Could not GET 'http://repo.spring.io/plugins-release/io/netty/netty-codec-http2/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s


Any particular reason for Build failure?
I am using Oracle Java
```

java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

**Comment by andelf** [comment]
For that it's too old, you should fix the repo url.

Change the url in `build.gradle`:

ref: <https://spring.io/blog/2019/09/16/goodbye-http-repo-spring-use-https>

**Comment by livingrock7** [comment]
@andelf Many thanks! I got past 111842 block and it is syncing 

1) Please tell me if there is any block explorer for Nile testnet?

2) Which branch and config should I use when I deploy my FullNode on mainnet? Does master branch have similar issue with getting stuck at particular block

**Comment by andelf** [comment]
> Please tell me if there is any block explorer for Nile testnet?

Home page: <http://nileex.io/>
Faucet: <http://nileex.io/join/getJoinPage>
Explorer: <https://nile.tronscan.org/>
Status: <http://nileex.io/status/getStatusPage>
Full Node / Solidity Node HTTP API: <https://api.nileex.io/>
Event API: <https://event.nileex.io/>
Tronscan API: <https://nileapi.tronscan.org>

Public Fullnode
- 47.252.19.181
- 47.252.3.238

Which branch and config should I use when I deploy my FullNode on mainnet? Does master branch have similar issue with getting stuck at particular block

> `Odyssey-v3.6.6`, actually, `master` branch is the mainnet.
> The codebase is OK for sync. Yet many deployment use snapshot database to start sync:

> To download the snapshot database:
> - http://47.89.178.46/
> - https://backups.trongrid.io/

**Comment by livingrock7** [comment]
Alright Thanks! closing the issue

**Comment by livingrock7** [comment]
`[root@localhost logs]# curl -X POST  http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"000000000018d8e6b2144823a19b602baeddb83eb4bd4cea038f1867dbf6f9a7","block_header":{"raw_data":{"number":1628390,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"41fa3e4daeb9ecdea6289062c6b582a77ba068fa4c","parentHash":"000000000018d8e5860e6c031f6dcafd4602d069bdb258af7bc4f68bdc65bef3","version":15,"timestamp":1577444784000},"witness_signature":"712d0618d920a4005b71ed3aea52bca98046d8e3b6bdd9c27d2506bb0b984a67382b775a5659437336c4392fc6476b6e8a0a2a20350b9d46bd7ca64c449aa3e401"}}
[root@localhost logs]# curl -X POST  http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"000000000018d8e6b2144823a19b602baeddb83eb4bd4cea038f1867dbf6f9a7","block_header":{"raw_data":{"number":1628390,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"41fa3e4daeb9ecdea6289062c6b582a77ba068fa4c","parentHash":"000000000018d8e5860e6c031f6dcafd4602d069bdb258af7bc4f68bdc65bef3","version":15,"timestamp":1577444784000},"witness_signature":"712d0618d920a4005b71ed3aea52bca98046d8e3b6bdd9c27d2506bb0b984a67382b775a5659437336c4392fc6476b6e8a0a2a20350b9d46bd7ca64c449aa3e401"}}
[root@localhost logs]# curl -X POST  http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"000000000018d8e6b2144823a19b602baeddb83eb4bd4cea038f1867dbf6f9a7","block_header":{"raw_data":{"number":1628390,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"41fa3e4daeb9ecdea6289062c6b582a77ba068fa4c","parentHash":"000000000018d8e5860e6c031f6dcafd4602d069bdb258af7bc4f68bdc65bef3","version":15,"timestamp":1577444784000},"witness_signature":"712d0618d920a4005b71ed3aea52bca98046d8e3b6bdd9c27d2506bb0b984a67382b775a5659437336c4392fc6476b6e8a0a2a20350b9d46bd7ca64c449aa3e401"}}
[root@localhost logs]# curl -X POST  http://127.0.0.1:8090/wallet/getnowblock
{"blockID":"000000000018d8e6b2144823a19b602baeddb83eb4bd4cea038f1867dbf6f9a7","block_header":{"raw_data":{"number":1628390,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"41fa3e4daeb9ecdea6289062c6b582a77ba068fa4c","parentHash":"000000000018d8e5860e6c031f6dcafd4602d069bdb258af7bc4f68bdc65bef3","version":15,"timestamp":1577444784000},"witness_signature":"712d0618d920a4005b71ed3aea52bca98046d8e3b6bdd9c27d2506bb0b984a67382b775a5659437336c4392fc6476b6e8a0a2a20350b9d46bd7ca64c449aa3e401"}}
`
Node has been running and is now stuck at particular block again

**Comment by livingrock7** [comment]
Here is the snippet from logs. Kindly advise @andelf 

```
Peer 47.252.17.40:18888 [0f60b7e5]
ping msg: count 1338, max-average-min-last: 19769 710 196 212
connect time: 21s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:1628391
syncBlockRequestedSize:0
remainNum:1929176
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 0(0), discover: 1/1 1/1 11608/11669 0/0 220ms, p2p: 259/259/259 , tron: 300806/7234 X 15<=TIME_OUT , tcp flow: 34943329


01:23:42.099 WARN  [pool-38-thread-1] [net](PeerStatusCheck.java:49) Peer /47.90.243.177 not sync for a long time.
01:23:42.099 INFO  [pool-38-thread-1] [net](Channel.java:138) Send to /47.90.243.177:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
01:23:42.108 INFO  [TronJClientWorker-0] [net](TronChannelInitializer.java:48) Close channel:/47.90.243.177:18888 | d20ecc2f344e657b277844e504ccc69b4ca76e49b270a03926beb67b956036170301b15261a011e2f47e25e6ec48f623bb6aa742839570d7d12fbe0c1718ab12
01:23:48.100 WARN  [pool-38-thread-1] [net](PeerStatusCheck.java:49) Peer /47.252.19.181 not sync for a long time.
01:23:48.100 INFO  [pool-38-thread-1] [net](Channel.java:138) Send to /47.252.19.181:18888 online-time 30s, type: P2P_DISCONNECT
reason: TIME_OUT
01:23:48.100 WARN  [pool-38-thread-1] [net](PeerStatusCheck.java:49) Peer /47.90.214.183 not sync for a long time.
01:23:48.100 INFO  [pool-38-thread-1] [net](Channel.java:138) Send to /47.90.214.183:18888 online-time 30s, type: P2P_DISCONNECT
reason: TIME_OUT
01:23:48.100 WARN  [pool-38-thread-1] [net](PeerStatusCheck.java:49) Peer /47.252.3.198 not sync for a long time.
01:23:48.100 INFO  [pool-38-thread-1] [net](Channel.java:138) Send to /47.252.3.198:18888 online-time 30s, type: P2P_DISCONNECT
 ChannelInitializer.java:48) Close channel:/47.252.19.181:18888 | 67d893384461c3db42129dad9af0092b6851ff7948c9cb931b72459d79768304e6d482032f63e70e1e68216ca5c25a75b4a83e8a268c1ce9453db50832570f66
01:23:48.104 INFO  [TronJClientWorker-3] [net](TronChannelInitializer.java:48) Close channel:/47.252.17.40:18888 | 0f60b7e5222fa7370c5839c0df72eab232dc48c23d5bf66e53930a75ae706bed360500fdc44860277c156e55b7a7dd761164ce3843738360ca2c10d757d3f829
01:23:48.104 INFO  [TronJClientWorker-4] [net](TronChannelInitializer.java:48) Close channel:/47.252.3.198:18888 | 06cb912602eaa6c128e62792adb28342e7edae7ec1eea02c327dcbee0f3d26647867fd731518e4e3682255c62d53d5d99ab619e1f85e0be4d21fbb767a540ebd
01:23:48.807 INFO  [pool-2-thread-1] [net](SyncPool.java:123)

============ Peer stats: all 0, active 0, passive 0


01:23:58.807 INFO  [pool-2-thread-1] [net](SyncPool.java:123)

============ Peer stats: all 0, active 0, passive 0


01:24:04.190 INFO  [NodeManagerTasks] [discover](NodeManager.java:135) Write Node statistics to PeersStore after: m:20/t:6/6/6 nodes.
01:24:08.808 INFO  [pool-2-thread-1] [net](SyncPool.java:123)

============ Peer stats: all 0, active 0, passive 0


01:24:18.808 INFO  [pool-2-thread-1] [net](SyncPool.java:123)


```

**Comment by andelf** [comment]
Does restarting your FullNode solve?

**Comment by livingrock7** [comment]
@andelf on it. It has been syncing for a while now, will find out

**Comment by andelf** [comment]
it is caused by that all p2p peers are marked unusable. might be poor network or node scoring.

**Comment by livingrock7** [comment]
I see! Took about a whole day yesterday. I checked today it has stopped to same block again

**Comment by livingrock7** [comment]
What would you suggest? I need to test RPC calls on any testnet FullNode and process incoming transactions
Thanks!

**Comment by andelf** [comment]
How about using public FullNode?

## Nile Testnet

Home page: <http://nileex.io/>

Faucet: <http://nileex.io/join/getJoinPage>

Explorer: <https://nile.tronscan.org/>

Status: <http://nileex.io/status/getStatusPage>

Full Node HTTP API: <https://api.nileex.io/>

Event API: <https://event.nileex.io/>

Tronscan API: <https://nileapi.tronscan.org>

Public Fullnode

- 47.252.19.181
- 47.252.3.238

## Shasta Testnet

Home page: <https://www.trongrid.io/shasta>

Faucet: <https://www.trongrid.io/faucet>

Explorer: <https://shasta.tronscan.org/>

Full Node / Event HTTP API: <https://api.shasta.trongrid.io>

Tronscan API: <https://api.shasta.tronscan.org>

gRPC

- grpc.shasta.trongrid.io:50051

**Comment by livingrock7** [comment]
Thanks!
Although still stuck at same block!

I could use public fullnode but for sign and submitting transactions I prefer to send it from my own write node which has control over keys of generated addresses.

**Comment by andelf** [comment]
You can generate the address locally, and sign locally.

**Comment by andelf** [comment]
Close for no response. Fell free to re-open or open-new.😃

**Comment by darklow** [comment]
I'm having same problem, Nile node stuck on block 1628390. Running newest `GreatVoyage-v4.4.2`.
Restart doesn't help.

@andelf Could we please reopen issue? I can provide any logs needed. 

We need tron testnet node as staging environment and can't rely on public node.
Or maybe someone could share snapshots to bootstrap node pass this block?

RPC
```
curl -X GET http://65.108.89.126:8090/wallet/getnowblock
{"blockID":"000000000018d8e6b2144823a19b602baeddb83eb4bd4cea038f1867dbf6f9a7","block_header":{"raw_data":{"number":1628390,"txTrieRoot":"0000000000000000000000000000000000000000000000000000000000000000","witness_address":"41fa3e4daeb9ecdea6289062c6b582a77ba068fa4c","parentHash":"000000000018d8e5860e6c031f6dcafd4602d069bdb258af7bc4f68bdc65bef3","version":15,"timestamp":1577444784000},"witness_signature":"712d0618d920a4005b71ed3aea52bca98046d8e3b6bdd9c27d2506bb0b984a67382b775a5659437336c4392fc6476b6e8a0a2a20350b9d46bd7ca64c449aa3e401"}}
```

It seems like an issue with not enough peers to data from, but what makes it strange that at this exact block so many users can't sync anymore.

More logs:
<details>
  <summary>Click to expand</summary>
============ Peer stats: all 2, active 1, passive 1

Peer 47.90.206.149:18888 [e4b304b2]
ping msg: count 0, max-average-min-last: 0 0 0 0
connect time: 8s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:1628391
syncBlockRequestedSize:0
remainNum:21247963
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 212(0), discover: 1/1 0/0 26/26 71/71 126ms, p2p: 1/1/1 , tron: 6/3 X 3<=CONNECT_FAIL , tcp flow: 160446

Peer 103.9.231.76:18888 [391d9cfa]
ping msg: count 20, max-average-min-last: 199 166 158 162
connect time: 405s
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:false
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:0
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 126(0), discover: 1/1 1/1 0/45 0/0 160ms, p2p: 1/1/1 , tron: 41/41   , tcp flow: 28


12:45:33.944 INFO  [pool-38-thread-1] [net](PeerClient.java:70) connect peer 47.90.214.183 18888 1fb952d74fcd43bcdca7cf3a5e70ad6643dcd7a7c09d5024248b09950936400d889ec56cc2849db6d032992701caf6b668cc90eb45a0298c38bb7e12f54255f3
12:45:34.068 INFO  [TronJClientWorker-7] [net](HandshakeHandler.java:77) channel active, /47.90.214.183:18888
12:45:34.069 INFO  [TronJClientWorker-7] [net](HandshakeHandler.java:131) Handshake send to /47.90.214.183:18888, type: P2P_HELLO
from {
  address: "65.108.89.126"
  port: 18888
  nodeId: "^\243\232\233\367\240\021+\217\275\201\220\341\027\232\234uo&~\020~|\221\236\261}\242s\211v\022\251{_\370\215\340\312\215\234t\202B\314\034(\357S\322\026<\030\035L\342\3430\342\ts\243\346\362"
}
version: 201910292
timestamp: 1641905134069
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\326\230\324\031,V\313k\347$\245XD\216&\204\200-\344\326\315\206\220\334"
}
solidBlockId {
  hash: "\000\000\000\000\000\030\330\324\a\313\263BW$M\210w\267V\003\374\302\275\265{/\201\231r=\006\275"
  number: 1628372
}
headBlockId {
  hash: "\000\000\000\000\000\030\330\346\262\024H#\241\233`+\256\335\270>\264\275L\352\003\217\030g\333\366\371\247"
  number: 1628390
}

12:45:34.191 INFO  [TronJClientWorker-7] [net](HandshakeHandler.java:92) Handshake receive from /47.90.214.183:18888, type: P2P_DISCONNECT
reason: TOO_MANY_PEERS
12:45:34.192 INFO  [TronJClientWorker-7] [net](TronChannelInitializer.java:48) Close channel:/47.90.214.183:18888 | 1fb952d74fcd43bcdca7cf3a5e70ad6643dcd7a7c09d5024248b09950936400d889ec56cc2849db6d032992701caf6b668cc90eb45a0298c38bb7e12f54255f3
12:45:37.546 INFO  [pool-38-thread-1] [net](PeerClient.java:70) connect peer 47.90.214.183 18888 1fb952d74fcd43bcdca7cf3a5e70ad6643dcd7a7c09d5024248b09950936400d889ec56cc2849db6d032992701caf6b668cc90eb45a0298c38bb7e12f54255f3
12:45:37.670 INFO  [TronJClientWorker-0] [net](HandshakeHandler.java:77) channel active, /47.90.214.183:18888
12:45:37.671 INFO  [TronJClientWorker-0] [net](HandshakeHandler.java:131) Handshake send to /47.90.214.183:18888, type: P2P_HELLO
from {
  address: "65.108.89.126"
  port: 18888
  nodeId: "^\243\232\233\367\240\021+\217\275\201\220\341\027\232\234uo&~\020~|\221\236\261}\242s\211v\022\251{_\370\215\340\312\215\234t\202B\314\034(\357S\322\026<\030\035L\342\3430\342\ts\243\346\362"
}
version: 201910292
timestamp: 1641905137670
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\326\230\324\031,V\313k\347$\245XD\216&\204\200-\344\326\315\206\220\334"
}
solidBlockId {
  hash: "\000\000\000\000\000\030\330\324\a\313\263BW$M\210w\267V\003\374\302\275\265{/\201\231r=\006\275"
  number: 1628372
}
headBlockId {
  hash: "\000\000\000\000\000\030\330\346\262\024H#\241\233`+\256\335\270>\264\275L\352\003\217\030g\333\366\371\247"
  number: 1628390
}

12:45:37.792 INFO  [TronJClientWorker-0] [net](HandshakeHandler.java:92) Handshake receive from /47.90.214.183:18888, type: P2P_DISCONNECT
reason: TOO_MANY_PEERS
12:45:37.793 INFO  [TronJClientWorker-0] [net](TronChannelInitializer.java:48) Close channel:/47.90.214.183:18888 | 1fb952d74fcd43bcdca7cf3a5e70ad6643dcd7a7c09d5024248b09950936400d889ec56cc2849db6d032992701caf6b668cc90eb45a0298c38bb7e12f54255f3
12:45:41.147 INFO  [pool-38-thread-1] [net](PeerClient.java:70) connect peer 47.90.214.183 18888 1fb952d74fcd43bcdca7cf3a5e70ad6643dcd7a7c09d5024248b09950936400d889ec56cc2849db6d032992701caf6b668cc90eb45a0298c38bb7e12f54255f3
12:45:41.272 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:77) channel active, /47.90.214.183:18888
12:45:41.272 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:131) Handshake send to /47.90.214.183:18888, type: P2P_HELLO
from {
  address: "65.108.89.126"
  port: 18888
  nodeId: "^\243\232\233\367\240\021+\217\275\201\220\341\027\232\234uo&~\020~|\221\236\261}\242s\211v\022\251{_\370\215\340\312\215\234t\202B\314\034(\357S\322\026<\030\035L\342\3430\342\ts\243\346\362"
}
version: 201910292
timestamp: 1641905141272
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\326\230\324\031,V\313k\347$\245XD\216&\204\200-\344\326\315\206\220\334"
}
solidBlockId {
  hash: "\000\000\000\000\000\030\330\324\a\313\263BW$M\210w\267V\003\374\302\275\265{/\201\231r=\006\275"
  number: 1628372
}
headBlockId {
  hash: "\000\000\000\000\000\030\330\346\262\024H#\241\233`+\256\335\270>\264\275L\352\003\217\030g\333\366\371\247"
  number: 1628390
}

12:45:41.394 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:92) Handshake receive from /47.90.214.183:18888, type: P2P_DISCONNECT
reason: TOO_MANY_PEERS
12:45:41.395 INFO  [TronJClientWorker-1] [net](TronChannelInitializer.java:48) Close channel:/47.90.214.183:18888 | 1fb952d74fcd43bcdca7cf3a5e70ad6643dcd7a7c09d5024248b09950936400d889ec56cc2849db6d032992701caf6b668cc90eb45a0298c38bb7e12f54255f3
12:45:42.428 INFO  [pool-39-thread-1] [net](SyncPool.java:137)
</details>

**Comment by vivian-kang** [comment]
Hi @darklow , suggest to use the database snapshot, and you can download it from https://nileex.io/join/getJoinPage . 
That is a convenient way to run a nile node. Thanks.
By the way, the log you paste means your node is connected by other node, they are only the info logs, not the error log. never mind.

**Comment by darklow** [comment]
@vivian-kang Oh, somehow I missed backup link. Great now I was able to download and sync. Thanks a lot.
