### ISSUE TITLE
I see you used UTXO in TRON project, I would like to ask what is UTXO?

### ISSUE THREAD

**Issue by jectjian** [tronprotocol/java-tron#3]

**Comment by zhangzhongwen007** [comment]
Bitcoin's blockchain book records one transaction after another.

Each transaction has a number of transaction input, that is, the source of funds, but also have a number of transactions output, that is, whereabouts of funds. In general, each transaction spends one input, producing one output, and the output it generates is "unspent transaction output," which is UTXO.

The total amount of transactions entered in any one transaction must equal the total amount of transactions output, and the two sides of the equation must be trimmed.

**Comment by Rovak** [comment]
Also checkout https://bitcoin.org/en/glossary/unspent-transaction-output and https://bitcoin.org/en/developer-guide#transactions for more detailed information
