### ISSUE TITLE
How do I fill in the smart contract string type parameters when triggering a smart contract method?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3039]
### 1. What did you do?

Call smart contract to pass string parameters.

### 2. What did you expect to see?
Hope for an example.

**Comment by Alexliu007** [comment]
Take the method get (string) parameter content 123456789 as an example: the position of the string type should be offset, and then the offset is the content. Parameter = offset + content (length + content).
0000000000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000009
313233343536373839000000000000000000000000000000000000000000000000
Or use tronide to send contract test verification
