### ISSUE TITLE
OUT_OF_TIME error while transferring TRC20 USDT 

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3040]
### 1. What did you do?

There was an error in a USDT transfer. The txid is:bc5d49c3a00e9f3951efe159f26fef42dbc90418bf817215378f1fb12db607ec

### 2. What did you expect to see?
Hope to return a successful status

### 3. What did you see instead?
It shows this error in tronscan：
FAIL-CPU TIMEOUT FOR 'PUSH1' OPERATION EXECUTING
link:https://tronscan.org/#/transaction/bc5d49c3a00e9f3951efe159f26fef42dbc90418bf817215378f1fb12db607ec

**Comment by Alexliu007** [comment]
The contract execution time has expired. The maximum contract execution time is 50ms.
It may be related to the contract and the machine environment. When writing smart contracts, it is as simple as possible to reduce loops.It is also recommended to set feelimit smaller to reduce losses.

**Comment by jiangyy0824** [comment]
If your problem is solved, please close this issue, thanks.

**Comment by stagmentterminal** [comment]
I have this problem, how did you (@xueyafighting)  solve it? 

This happened when I made an withdrawal request from binance and they said the coins left the binance wallet, but i didn't get the USDTs.
please help me if you have information.
thank you

**Comment by chetansaini1234** [comment]
😭😢
This happened when I made an withdrawal request from binance and they said the coins left the binance wallet, but i didn't get the USDTs.
please help me if you have information.
thank you
Tell me how to solve it 😢😭

**Comment by chetansaini1234** [comment]
> I have this problem, how did you (@xueyafighting) solve it?
> 
> This happened when I made an withdrawal request from binance and they said the coins left the binance wallet, but i didn't get the USDTs.
> please help me if you have information.
> thank you

😭😢
This happened when I made an withdrawal request from binance and they said the coins left the binance wallet, but i didn't get the USDTs.
please help me if you have information.
thank you
Tell me how to solve it 😢😭

**Comment by chetansaini1234** [comment]
> If your problem is solved, please close this issue, thanks.

😭😢
This happened when I made an withdrawal request from binance and they said the coins left the binance wallet, but i didn't get the USDTs.
please help me if you have information.
thank you
Tell me how to solve it 😢😭

**Comment by chetansaini1234** [comment]
> ### 1. What did you do?
> There was an error in a USDT transfer. The txid is:bc5d49c3a00e9f3951efe159f26fef42dbc90418bf817215378f1fb12db607ec
> 
> ### 2. What did you expect to see?
> Hope to return a successful status
> 
> ### 3. What did you see instead?
> It shows this error in tronscan：
> FAIL-CPU TIMEOUT FOR 'PUSH1' OPERATION EXECUTING
> link:https://tronscan.org/#/transaction/bc5d49c3a00e9f3951efe159f26fef42dbc90418bf817215378f1fb12db607ec

😭😢
This happened when I made an withdrawal request from binance and they said the coins left the binance wallet, but i didn't get the USDTs.
please help me if you have information.
thank you
Tell me how to solve it 😢😭

**Comment by marcelinho111** [comment]
> 
> 
> > ### 1. What did you do?
> > There was an error in a USDT transfer. The txid is:bc5d49c3a00e9f3951efe159f26fef42dbc90418bf817215378f1fb12db607ec
> > ### 2. What did you expect to see?
> > Hope to return a successful status
> > ### 3. What did you see instead?
> > It shows this error in tronscan：
> > FAIL-CPU TIMEOUT FOR 'PUSH1' OPERATION EXECUTING
> > link:https://tronscan.org/#/transaction/bc5d49c3a00e9f3951efe159f26fef42dbc90418bf817215378f1fb12db607ec
> 
> 😭😢
> This happened when I made an withdrawal request from binance and they said the coins left the binance wallet, but i didn't get the USDTs.
> please help me if you have information.
> thank you
> Tell me how to solve it 😢😭

this error happened friend can also solve ?

**Comment by navneetboghani** [comment]
It shows this error in tronscan：
FAIL-CPU TIMEOUT FOR 'PUSH1' OPERATION EXECUTING

https://tronscan.org/#/transaction/2d658223b9ce79fd62919b971147af8edfada3ddd071a503930d010a5af40657

Please help me if you have information

**Comment by MeHaCe** [comment]
I had same problem

**Comment by chetansaini1234** [comment]
I can really help you the same problem i had face but now its solve 😊

tolk to me on my telegram
 @Stoshinamatako

**Comment by oguzsen83** [comment]
How did you solve this problem?i can not reach you on telegram.. #

**Comment by chetansaini1234** [comment]
On this telegram support @Binance_support_chat

**Comment by oguzsen83** [comment]
Thank you friend...

**Comment by AliyaAllush** [comment]
I have same problem. Is it refunded to your wallets guys? How did you solve it?

**Comment by Benson0224** [comment]
> I have same problem. Is it refunded to your wallets guys? How did you solve it?

failed transaction will not conduct any USDT from the sender address. 
Please contact exchange support if this transaction is a withdraw transaction from the exchange. thanks.

**Comment by wds657** [comment]
> @Binance_support_chat

https://twitter.com/binance/status/1373431684117450753

Reminder: [#Binance](https://twitter.com/hashtag/Binance?src=hashtag_click) does not provide customer support on Telegram, and we will never ask you for personal information.

Be careful, stay SAFU.
