### ISSUE TITLE
ILLEGAL_OPERATION error when i deploy trc20 contract in Private chain。

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3041]
### 1. What did you do?

I set up a TRON private chain，
then i deploy a trc20 contract use wallet/deploycontrac, but it return error during broadcast transaction。

### 2. What did you expect to see?
Hope to return a successful status，and contract address.

### 3. What did you see instead?
return  ILLEGAL_OPERATION, and i find this message in tron.log file: VM halted: [Invalid operation code: opCode[d3];]

**Comment by Alexliu007** [comment]
After setting up the private chain, there are some proposals that need to be passed. You can check whether your proposal is consistent with the tron mainnet. Regarding your question, proposal 18[#18 Propose to allow the TRC-10 token transfer in smart contracts] should not be approved. So I suggest you check if proposal 18 is approved.

**Comment by woaichixigua07** [comment]
thanks, it's work now!

**Comment by jiangyy0824** [comment]
If your problem is solved, please close this issue, thanks.
