### ISSUE TITLE
How to add the memo to a transaction？

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3063]
### 1. What did you do?

i did not find the related api.

### 2. What did you expect to see?
a transcation with the memo.

### 3. What did you see instead?
a transcation without the memo.

**Comment by guoquanwu** [comment]
You can refer this doc: https://cn.developers.tron.network/docs/%E6%9C%AC%E5%9C%B0%E6%9E%84%E5%BB%BA%E4%BA%A4%E6%98%93

**Comment by xueyafighting** [comment]
thanks~
