### ISSUE TITLE
Cannot get internal transaction via gettransactioninfobyid api

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3064]
### 1. What did you do?

I had built a node connected to mainnet and keep syncing with others, the result of gettransactioninfobyid, no internal transaction found, why？ actually it exists....

### 2. What did you expect to see?
get the internal transaction 

### 3. What did you see instead?
no internal transaction found

**Comment by guoquanwu** [comment]
You should set `saveInternalTx = true` in the config file when you want to save and query the internal transactions
