### ISSUE TITLE
How can i get the privatekey of address when i use wallet/createaddress this api?

### ISSUE THREAD

**Issue by Alexliu007** [tronprotocol/java-tron#3065]
### 1. What did you do?
How can i get the privatekey of address that created from https://api.trongrid.io/wallet/createaddress

### 2. What did you expect to see?
get privatekey of the address

### 3. What did you see instead?
none

**Comment by Alexliu007** [comment]
when use this command curl  --data  '{"value":"7465737470617373776f7264"}' https://api.trongrid.io/wallet/createaddress,
the private key is the sha256 result of the /wallet/createaddress input value, java-tron just tranfer your input to privatekey by sha256 your input， then get and return the address of the privatekey to you.

**Comment by woaichixigua07** [comment]
hi, when you use command curl  --data  '{"value":"7465737470617373776f7264"}'  https://api.trongrid.io/wallet/createaddress 
,the private key is the sha256 result of the /wallet/createaddress input value， java-tron just tranfer your input to privatekey by sha256 your input， then get and return the address of the privatekey to you.

**Comment by Alexliu007** [comment]
Thanks! Solved my problem
