### ISSUE TITLE
Can't get bytecode of the contract created from another deployed contract.

### ISSUE THREAD

**Issue by Alexliu007** [tronprotocol/java-tron#3066]
### 1. What did you do?

Through /wallet/getcontract API, I can not get bytecode of the contract created from another deployed contract ? 

### 2. What did you expect to see?
can get bytecode of the contract from another deployed when i use wallet/getcontract api

### 3. What did you see instead?
can't get bytecode  info

**Comment by xueyafighting** [comment]
Thank you for your feedback, this is a known issue, but it does not affect normal contract calls and we will fix it in a future version.
