### ISSUE TITLE
Cannot find result in solidity node

### ISSUE THREAD

**Issue by mitGen** [tronprotocol/java-tron#3067]
### 1. What did you do?
Connected to tronweb through fullHost:"https://api.trongrid.io" and called smart contract methods

### 2. What did you expect to see?
I wanted to get the transaction confirmed, but I received such a response, although periodically the same methods work !!!!!
{"message" : "Cannot find result in solidity node" } 

### 3. What did you see instead?
Expected to receive a response about the transaction.

**Comment by summertanh** [comment]
@mitGen Hi，could you show more info about your issue please? For example, 
1. How do you new TronWeb
2. Which method of tronWeb you called to get the transaction confirmed.

**Comment by mitGen** [comment]
1.Create: 
const TronWeb = require('tronweb');
const tronWeb = new TronWeb({
  fullHost: "https://api.trongrid.io",
  privateKey: PRIVATE_KEY
});

2. Called a smart contract method in this way :
      const tx = await contract.transferTo(address, tronWeb.toSun(amount)).send({
        shouldPollResponse: true
      });

All this works fine, only sometimes this error pops up !!!!!! (((((

**Comment by mitGen** [comment]
> @mitGen Привет ， не могли бы вы показать больше информации о вашей проблеме, пожалуйста? Например,
> 
> 1. Как вы создаете TronWeb
> 2. Какой метод tronWeb вы вызвали для подтверждения транзакции.

1.Create:
const TronWeb = require('tronweb');
const tronWeb = new TronWeb({
fullHost: "https://api.trongrid.io",
privateKey: PRIVATE_KEY
});

Called a smart contract method in this way :
let contract = await tronWeb.contract().at(CONTRACT_ADDRESS);
const tx = await contract.transferTo(address, tronWeb.toSun(amount)).send({
shouldPollResponse: true
});
All this works fine, only sometimes this error pops up !!!!!! (((((
version tronweb 2.8.1

**Comment by mitGen** [comment]
> @mitGen Hi，could you show more info about your issue please? For example,
> 
> 1. How do you create TronWeb
> 2. Which method of tronWeb you called to get the transaction confirmed.

1.Create:
const TronWeb = require('tronweb');
const tronWeb = new TronWeb({
fullHost: "https://api.trongrid.io",
privateKey: PRIVATE_KEY
});

Called a smart contract method in this way :
let contract = await tronWeb.contract().at(CONTRACT_ADDRESS);
const tx = await contract.transferTo(address, tronWeb.toSun(amount)).send({
shouldPollResponse: true
});
All this works fine, only sometimes this error pops up !!!!!! (((((
version tronweb 2.8.1

**Comment by summertanh** [comment]
@mitGen Hi, the real reason is that you use the param 'shouldPollResponse: true', which means you wanna get transaction result from tronweb 'send()' method. Here is some source code in 'send()' method :
![image](https://user-images.githubusercontent.com/16298463/78329294-e03e5a80-75b3-11ea-838e-24559433eeb5.png)
You got the err msg as tronWeb was checking the transaction result from tron network, sometimes   
due to network or other reason, it comes to the limit 20 times,  tronWeb will throw an error 'Cannot find result in solidity node'.
You could confirm the transaction result by yourself or maybe you can take it as a special error in your code.

Thanks.

**Comment by manish8561** [comment]
same issue after transaction no logs generated in send function of tron contract
