### ISSUE TITLE
the code `Runtime.getRuntime().availableProcessors() / 2 ` is unavailable for single-core machine

### ISSUE THREAD

**Issue by AceLuodan** [tronprotocol/java-tron#3070]
但我使用单核机器的的时候，出现程序启动报错

建议Runtime.getRuntime().availableProcessors() / 2 把这个 /2 删了

对孤苦伶仃的程序员需要照顾一下，提高友好性。

There is a program startup error when I use a single-core machine.
I recommend modifying the code sniept `Runtime.getRuntime().availableProcessors() / 2`.

**Comment by shydesky** [comment]
Yes, good advice. Thank you!
