### ISSUE TITLE
Can't sync Nile testnet on FullNode with latest DB backup

### ISSUE THREAD

**Issue by mattopolitan** [tronprotocol/java-tron#3073]
### 1. What did you do?

I'm just trying to sync the Nile testnet on FullNode with latest DB backup provided here: [Database Backup Address](http://47.90.243.177/)
I've checked my environment, as stated [here](http://nileex.io/join/getJoinPage)
Branch: develop
Commit: 6221f48. 
And I'm using a config.conf copied from [here](http://nileex.io/join/getJoinPage) as well.

Yet I always get stuck at block number :4489787, with reason: BAD_BLOCK

> 12:23:54.798 INFO  [pool-42-thread-1] [DB](Manager.java:994) pushBlock block number:4489787, cost/txs:13/0
12:23:54.798 INFO  [pool-42-thread-1] [net](TronNetDelegate.java:212) Success process block Num:4489787,ID:000000000044823bb1b9199eee6372d09d849b2624f2485e7d8cf2e4392eaa2f.
12:23:54.799 INFO  [pool-42-thread-1] [DB](Manager.java:1434) PreValidate Transaction Sign, size:1, block num:4489788
12:23:54.813 ERROR [pool-42-thread-1] [DB](Manager.java:970) librustzcashSaplingCheckSpend error
org.tron.core.exception.ZkProofValidateException: librustzcashSaplingCheckSpend error
	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:306)
	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:266)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1081)
	at org.tron.core.db.Manager.processBlock(Manager.java:1311)
	at org.tron.core.db.Manager.applyBlock(Manager.java:740)
	at org.tron.core.db.Manager.pushBlock(Manager.java:963)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:210)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
12:23:54.815 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:237) Process block failed, Num:4489788,ID:000000000044823cafbc039cb6c37c27daf8c75b12b57da83bce92f993bfa50b, reason: librustzcashSaplingCheckSpend error.
12:23:54.815 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:4489788,ID:000000000044823cafbc039cb6c37c27daf8c75b12b57da83bce92f993bfa50b failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ZkProofValidateException: librustzcashSaplingCheckSpend error
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:238)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ZkProofValidateException: librustzcashSaplingCheckSpend error
	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:306)
	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:266)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:63)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1081)
	at org.tron.core.db.Manager.processBlock(Manager.java:1311)
	at org.tron.core.db.Manager.applyBlock(Manager.java:740)
	at org.tron.core.db.Manager.pushBlock(Manager.java:963)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:210)
	... 12 common frames omitted
12:23:54.817 INFO  [pool-42-thread-1] [net](Channel.java:123) Send to /47.90.214.183:18888 online-time 90s, type: P2P_DISCONNECT
reason: BAD_BLOCK
12:23:54.822 INFO  [TronJClientWorker-0] [net](TronChannelInitializer.java:48) Close channel:/47.90.214.183:18888 | 1d1f54ffeb6ae384587fef0e7400812b772c78ae2fdd42210df539d7538cbf0692b755383eff20ab1b5dd4361d14bb02aebb76b7236297e19fc36c188f0e32e3

 
### 2. What did you expect to see?
Please advice me on how to solve the issue, and let me now if there are any more information needed to be provided in advance.

**Comment by andelf** [comment]
ref: <http://nileex.io/>
Current nile branch is `release_4.0_nile`. Could you have a try?

**Comment by mattopolitan** [comment]
Hi @andelf,
I've changed my branch to `release_4.0_nile` & rebuild the FullNode.jar. Delete the whole output-directory & copy the backup again. Doesn't help.

**Comment by andelf** [comment]
This may be related to the shielded transaction.

FYI, the 4489788 block:

```json
{
  "block_header": {
    "raw_data": {
      "accountStateRoot": [],
      "number": 4489788,
      "parentHash": "000000000044823bb1b9199eee6372d09d849b2624f2485e7d8cf2e4392eaa2f",
      "timestamp": 1586115897000,
      "txTrieRoot": "10d8f0c079431c056a2fccd4f37163ece64a4bf89c423665997ffaed36abc59a",
      "version": 15,
      "witness_address": "41e4944233438d495b81327b5913257d8ec5cae677",
      "witness_id": 0
    },
    "witness_signature": "0460c4c604e9379529d95697f82206feba11487936b955c6589f39df7fd05fae6f731827fce705034d5dce3b375e12f023f403560c1dc83fb057b04bd61fbd2601"
  },
  "blockid": "000000000044823cafbc039cb6c37c27daf8c75b12b57da83bce92f993bfa50b",
  "transactions": [
    {
      "constant_result": [],
      "result": {
        "code": "SUCCESS",
        "message": [],
        "result": true
      },
      "transaction": {
        "raw_data": {
          "auths": [],
          "contract": [
            {
              "ContractName": [],
              "Permission_id": 0,
              "field_type": "ShieldedTransferContract",
              "parameter": {
                "type_url": "type.googleapis.com/protocol.ShieldedTransferContract",
                "value": {
                  "binding_signature": "09aed95a223f3222e6e1cb578680b9cce2b1d3d9e537a88b0c172b7f7f312d0f3ea1eba448a47d637e98c97adad27c960a1ebe424ce3a0db2025cf9521181002",
                  "from_amount": 0,
                  "receive_description": [
                    {
                      "c_enc": "2a9132a3e6cb349e1ae1a30ddfeb935756cf00ce1278e4cf76dd6544b65152c279f3ecb2f331418be7d9fd4f50d71370f1cda63d010371c20b70b2c3aa5ab1650c5e7fdec1475e073a454e898d5e1924a68111a8b8503fea867da571efd6157d44d36942da1ecc6ce8640a6651c6399b3b55e9bb3fd425bd05ea3f9380d572b7d5384e000803aa7a499c98a6963721287d76ebba3561dc05016a6e2bafe0fbcced91aa0339613e946d8bcbcbe04a12205e0c6870fa6d5d4d879c773ebe840db36c9a71845c80e998cbcfe44a08bc18ecc592dc11f70c7bb12556575d38cb371c1cdb2f60154f4d4dd28900dde89e38cb89d2c4c2322ed8fbe05dfcb13706ae3d29b798234fa926740bd40564802a3c8a86cac5bc9695796bb29f33b23adb1106f7c9bb77e1732cc36174d656083380727438456cb31c59a6e494a9bb828cc053ac39a44ac44e387e841a05cf469f317380f422958be3875809053ae862da870817193e2053678223606f101a8d3bb815c26e8f3ecb4af88b6491b858164046873d7a539134b1a855a217669df60052115d4285365938e3e362d7ad49e33b7b357389e7d8f66b2dc07604c61a075de6470db2794f0beb89bdd058e7fe198cd3d7a18b3a2cc4d3036532ea5f895bc5fcf9750a676ead4004ba75704cbf7f6571fc46e9452f07f97769b5fe39261f8ce8a52fe5037bbd5560cee23578ec1772afa259bc3cb96c9e798b5e01b8d86aeeb0effbe1a623d27e954da5171f40f16acf4f5a9486c0f185ed66ea115567d83fa37e92b82c43d60c53c189dd6f6aedbe22cf8b7f492e",
                      "c_out": "b5b280a21c21694def74e301bb7c22135ed282049765ce1a9f245446192c3a1c773b6353d6198909861d9b99b940daab55d8bd84c0115760586d0711a5eb5045f48f2fbb6da48e3707d8ae05417f059f",
                      "epk": "9f6d3ca19f3c513159eb43052fcdbe080eca7ea39f8bc1171216485a74ef75a2",
                      "note_commitment": "621756eef4c8fcf6de0c31f40a3612e084e3e1516d24094b31fd2c99740d9356",
                      "value_commitment": "76c52262afb6f806f1334d245fb7a44f81ee5bb63cd7844836e51c48e7eebdd6",
                      "zkproof": "90c173f55c581a2bc599a84704ef111ce8b16a515647eb438a5330b48af5bd86053ecc58dd6d7778e006bd1c7913a85a8b6b42050df4c356b82df464f788ea31a3be4c7bf29548d208a9d06dac521d73285ef21cfbdc49a1799a698e50aba4a30f1823260faac9f4c6c97c0a1696d0b545ab71737b1eabcbd4e61d471267fb5f5c240caac2bdfd4b07293ab92b44e0bc8f7ec8f10492967538072e86b95c19cb903878c181e63595214d1d33d828964f32355eb8b13a7c5b38326d9779432b4a"
                    }
                  ],
                  "spend_description": [
                    {
                      "anchor": "cc77016b2201720492275223acd14ccc1ab58ccc833a248e59d882b72cd0f514",
                      "nullifier": "94a3d5658737f0c60b491c70c3cebe8405ba74b03143b59289dc9e0b818f9df7",
                      "rk": "dc43262cf8c73e709b484818bfcba2aa7f519b8d1778a86ef784993d24e0a3a2",
                      "spend_authority_signature": "bda5ba560a7e31c9ca765d9ebf7365c2f54042a532d11a2f96eb796c5a0d72aa47df96db2dad5f9acc22a5eabcbc794c352ee2e003ffd5e997f86746a869ae00",
                      "value_commitment": "23ed70f171216553bda2f795f9059aeea20379187afbaa3a5caa009b38038937",
                      "zkproof": "aa845aba5ef65084254cecd052e70f453c5f330ef5cd549e289d54d71d05181765876be1788645b2b43ead50fcb59a2d965495e887ec0a05f5f362d7e99763cb3251b1ee84fd97b550877477c1a89c7530096ea3c628fb22a75ab8947bd0dba000541cd1d1271ef6404d2454895ba71e8775188bbcf0f7e43842c01bc012a91045052b19b48f8ef8582bad6440f23cd1a0ac1591e41768abb023c97b2935cf567f996ac142bcc4652b253035964876087f45cb8f293270b02f9255767ad8aae6"
                    }
                  ],
                  "to_amount": 1114304,
                  "transparent_from_address": "",
                  "transparent_to_address": "416c0214c9995c6f3a61ab23f0eb84b0cde7fd9c7c"
                }
              },
              "provider": []
            }
          ],
          "data": "",
          "expiration": 1586116188000,
          "fee_limit": 0,
          "ref_block_bytes": "8239",
          "ref_block_hash": "ffcee07947f981b9",
          "ref_block_num": 0,
          "scripts": [],
          "timestamp": 1586115890992
        },
        "ret": [
          {
            "assetIssueID": "",
            "contractRet": "SUCCESS",
            "exchange_id": 0,
            "exchange_inject_another_amount": 0,
            "exchange_received_amount": 0,
            "exchange_withdraw_another_amount": 0,
            "fee": 0,
            "ret": "SUCESS",
            "shielded_transaction_fee": 0,
            "unfreeze_amount": 0,
            "withdraw_amount": 0
          }
        ],
        "signature": []
      },
      "txid": "9b5612d5aaade4145c73ab95bee779cbe20041416552751d66e4fee4f6a220dd"
    }
  ]
}
```

**Comment by Benson0224** [comment]
@mattopolitan 

we have successfully verified that code on` release_4.0_nile`  branch work OK for Nile testnet. 
the FullNode.jar on http://nileex.io/join/getJoinPage was a wrong version, we have removed from that page.

to join the Nile, here are the steps: 

1. git clone the Nile code from  https://github.com/tronprotocol/java-tron/tree/release_4.0_nile 
2. build FullNode.jar (build instruction: https://github.com/tronprotocol/java-tron/blob/release_4.0_nile/build.md).
3. Copy the configuration file from  http://nileex.io/join/getJoinPage, save it as `nilenet_config.conf`
4. Delete the whole output-directory & copy the backup again.
5. run fullnode.jar : `nohup java -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -jar FullNode.jar -c nilenet_config.conf &>/dev/null &`

**Comment by Benson0224** [comment]
> Hi @Benson0224 ,
> 
> I followed your instruction but still got stuck at block 6359584 due to P2P_DISCONNECT and HANDSHAKE_FAILED.
> Could you please tell me which branch now support sync fullnode Nile network ?
> 
> Thanks.

Branch info was listed on: https://nileex.io/  you can also directly download the jar from the link.
Odyssey-v4.0.1 Beta    Branch name：new_hard_fork_nile

**Comment by trnhgquan** [comment]
> > Hi @Benson0224 ,
> > I followed your instruction but still got stuck at block 6359584 due to P2P_DISCONNECT and HANDSHAKE_FAILED.
> > Could you please tell me which branch now support sync fullnode Nile network ?
> > Thanks.
> 
> Branch info was listed on: https://nileex.io/ you can also directly download the jar from the link.
> Odyssey-v4.0.1 Beta Branch name：new_hard_fork_nile

Hi Bensen,

As now my full node already sync 6,3 m blocks, is there anyway switch to new_hard_fork_nile and sycn from this block ? If can please give me instruction, thanks.

**Comment by Benson0224** [comment]
> > > Hi @Benson0224 ,
> > > I followed your instruction but still got stuck at block 6359584 due to P2P_DISCONNECT and HANDSHAKE_FAILED.
> > > Could you please tell me which branch now support sync fullnode Nile network ?
> > > Thanks.
> > 
> > 
> > Branch info was listed on: https://nileex.io/ you can also directly download the jar from the link.
> > Odyssey-v4.0.1 Beta Branch name：new_hard_fork_nile
> 
> Hi Bensen,
> 
> As now my full node already sync 6,3 m blocks, is there anyway switch to new_hard_fork_nile and sycn from this block ? If can please give me instruction, thanks.

Stop the fullnode.jar process(kill -15 $pid), do backup(both jar and output dir), replace your local fullnode.jar with the latest jar which downloaded from nileex.io, then start the fullnode.jar again.  
https://docs.google.com/document/d/1tAaHVFp_j_2rA6TqcFfOMvey6B7YuGp9FcIJYKURl_I/edit?usp=sharing

**Comment by trnhgquan** [comment]
> > > > Hi @Benson0224 ,
> > > > I followed your instruction but still got stuck at block 6359584 due to P2P_DISCONNECT and HANDSHAKE_FAILED.
> > > > Could you please tell me which branch now support sync fullnode Nile network ?
> > > > Thanks.
> > > 
> > > 
> > > Branch info was listed on: https://nileex.io/ you can also directly download the jar from the link.
> > > Odyssey-v4.0.1 Beta Branch name：new_hard_fork_nile
> > 
> > 
> > Hi Bensen,
> > As now my full node already sync 6,3 m blocks, is there anyway switch to new_hard_fork_nile and sycn from this block ? If can please give me instruction, thanks.
> 
> Stop the fullnode.jar process(kill -15 $pid), do backup(both jar and output dir), replace your local fullnode.jar with the latest jar which downloaded from nileex.io, then start the fullnode.jar again.
> https://docs.google.com/document/d/1tAaHVFp_j_2rA6TqcFfOMvey6B7YuGp9FcIJYKURl_I/edit?usp=sharing

Hi, thanks, 
Besides, I have these [issues](https://github.com/TRON-US/docker-tron-quickstart/issues/16) and still looking for a reply, please check it out, if can give me a suggestion, thanks so much:
