### ISSUE TITLE
How to back up the database regularly?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3077]
### 1. What did you do?
How to back up the database regularly?

### 2. What did you expect to see?
Back up the database regularly.

### 3. What did you see instead?
None

**Comment by Alexliu007** [comment]
Use RocksDB as the data storage engine, need to set db.engine to "ROCKSDB". Then use RocksDB's data backup function, choose RocksDB to be the data storage engine, you can use its data backup function while running.
https://github.com/tronprotocol/documentation-en/blob/master/docs/architecture/database.md

**Comment by woaichixigua07** [comment]
yes, i find the config, thanks!
