### ISSUE TITLE
How to broadcast a hex generated after an offline transaction signature on the TRON network?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3079]
### 1. What did you do?

How to broadcast a hex generated after an offline transaction signature on the TRON network?

### 2. What did you expect to see?
none

### 3. What did you see instead?

none

**Comment by Alexliu007** [comment]
In version 3.7, add `broadcasthex` API for HTTP, the user can broadcast the hex of the transaction.  You can refer to the relevant interface introduction(https://tronprotocol.github.io/documentation-en/api/http/)

**Comment by woaichixigua07** [comment]
thanks! but i use trongrid api, it returns 405 error, i find trongrid node version is 3.6.6, then i use other node, it's works! thank u.

**Comment by Alexliu007** [comment]
Trondrid is currently preparing to upgrade to version 3.7, which can be used later.
