### ISSUE TITLE
Unable to transfer asset to this address TS3x55FLDasvNFPwMJwq2T7B2YBzc5sgxm.

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3093]
### 1. What did you do?

when i send usdt to TS3x55FLDasvNFPwMJwq2T7B2YBzc5sgxm this address, and can't transfer USDT successfully.

### 2. What did you expect to see?
Send USDT to this address successful.

### 3. What did you see instead?
None

**Comment by Alexliu007** [comment]
After checking, the address is an illegal address, the correct address should be TS3x55FLDasvNFPwMJwq2T7B2YBzc5s**GxM**。 （https://tronscan.org/#/address/TS3x55FLDasvNFPwMJwq2T7B2YBzc5sGxM）

**Comment by Benson0224** [comment]
@woaichixigua07  since this issue is already clarified, please help to close this issue, thanks. 

feel free to re-open it once you get further questions.

**Comment by woaichixigua07** [comment]
Thanks for solving my problem.
