### ISSUE TITLE
How to understand this transfer ed1e152f8ad4c24a5142622058db743d02aeceafb6b4142be93bc61459dc0ff3?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3096]
### 1. What did you do?

https://tronscan.org/#/transaction/ed1e152f8ad4c24a5142622058db743d02aeceafb6b4142be93bc61459dc0ff3
I do not understand the method "transferFrom" of trc20.

### 2. What did you expect to see?
Explanation of trc20 method "transferFrom".

### 3. What did you see instead?
I did not see the relevant explanation about this.

**Comment by Alexliu007** [comment]
This transaction is transferred by calling the transferFrom of USDT, which is a kind of entrusted transaction and is a type of normal transaction. For example, account A has 1000 USDT and wants to allow account B  to call 100 USDT at will. The account A calls the approve function approve (B, 100) in the following form. When the account B wants to trasnfer 10 of the 100 USDT to the account C, then the account B calls transferFrom (A, C, 10).
