### ISSUE TITLE
Tests with calls to new Blockchain("any address argument") call System.exit(0) and end all test execution

### ISSUE THREAD

**Issue by seanrobbins** [tronprotocol/java-tron#31]
1. What did you do?
- Clone java-tron repository
- Import java-tron into IntelliJ
- Open BlockchainTest.java
- Run full test suite BlockchainTest.java

2. What did you expect to see?
- All of the tests run

3. What did you see instead?
- When running the full test suite, none of the tests run

**Comment by seanrobbins** [comment]
The reason for this is:

`public class BlockchainTest {
    private static final Logger LOGGER = LoggerFactory.getLogger("Test");

    @Test
    public void testBlockchain() {
        Blockchain blockchain = new Blockchain
                ("0304f784e4e7bae517bcab94c3e0c9214fb4ac7ff9d7d5a937d1f40031f87b85");`

Calls the following code:

`    public Blockchain(String address) {
        if (dbExists()) {
            LOGGER.info("blockchain already exists.");
            System.exit(0);
        }`

dbExists is always true. So System.exit(0) is always called.

System.exit(0) terminates the test running process, so further tests are not run.

**Comment by sasaxie** [comment]
dbExists return false when the first time you start java-tron.

**Comment by seanrobbins** [comment]
Seems to be returning true the first time running from the test suite. Maybe I can try to figure out why that is the case.

**Comment by seanrobbins** [comment]
I have run tron on my machine prior to running the unit tests in IntelliJ... maybe this has meant a Blockchain and a db already exists locally?

- I'm starting to think it may be desirable to be able to mock db within the unit tests, to be able to control db state?

**Comment by seanrobbins** [comment]
If I run a test such as BlockchainTest.testBlockchain without the database-test existing on my local machine, this directory will be created and the test will pass.

If I re-run the same test again, it will then exit as the database directory already exists. 

It would be possible to delete the directory as part of the test clean up each time, but that feels like a hack and I'm convinced there would be a better way of doing it.

**Comment by seanrobbins** [comment]
Attempted a fix for these unit test issues in PR https://github.com/tronprotocol/java-tron/pull/33

**Comment by sasaxie** [comment]
```java
if (dbExists()) {
    // load blockchain data from db
} else {
    // create new blockchain and save it
}
```

**Comment by seanrobbins** [comment]
Fixes for the issues with these unit tests were merged to the develop branch in these PRs:
https://github.com/tronprotocol/java-tron/pull/33
https://github.com/tronprotocol/java-tron/pull/34

I'm going to close this issue.

**Comment by seanrobbins** [comment]
Re-opening this issue as I notice this has been re-introduced into the develop branch: https://github.com/tronprotocol/java-tron/blob/ef9efb263f66826e176a50ebb246366196f3554a/src/main/java/org/tron/core/Blockchain.java#L67

And the issues this can cause is now workaround by ignoring the BlockchainTest.

It looks like the System.out(0) came back in this commit: https://github.com/tronprotocol/java-tron/commit/4403dadd2ee54cbc7bcaa5eb4c20261d589990a1

It looks like it returned as a result of a merge between a local branch and the develop branch with these changes.

Ignoring BlockchainTest seems bad, as there's a lot of important features to the Blockchain class. Is the following the right approach:

```
if (dbExists()) {
    // load blockchain data from db
} else {
    // create new blockchain and save it
}
```
Or is the System.exit(0) what you actually want?

**Comment by seanrobbins** [comment]
Closing again. Latest on develop has been fixed back to
 
`if (dbExists()) {
    // load blockchain data from db
} else {
    // create new blockchain and save it
}`
