### ISSUE TITLE
how to getBalance of TRC20 by curl

### ISSUE THREAD

**Issue by 1971192997** [tronprotocol/java-tron#3105]
how to getBalance of TRC20 by curl "
 is there any api?

**Comment by 1971192997** [comment]
and how to get the decimal of trc20 token by curl?

**Comment by cathy-lishipu** [comment]
1. getBalance of TRC20 by curl:
curl -X POST https://api.shasta.trongrid.io/wallet/triggersmartcontract -d '{
"contract_address":"419E62BE7F4F103C36507CB2A753418791B1CDC182",
"function_selector":"balanceOf(address)",
"parameter":"000000000000000000000041977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB",
"owner_address":"41977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB"
}'
2. get the decimal of TRC20 token by curl:
curl -X POST  https://api.shasta.trongrid.io/wallet/triggersmartcontract -d '{
"contract_address":"419E62BE7F4F103C36507CB2A753418791B1CDC182",
"function_selector":"decimals()",
"owner_address":"41977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB"
}'

**Comment by 1971192997** [comment]
is it possible to get balance of one token in an address directly?   

i can get the list assets of an address but how to get one token?

**Comment by 1971192997** [comment]
> 1. getBalance of TRC20 by curl:
>    curl -X POST https://api.shasta.trongrid.io/wallet/triggersmartcontract -d '{
>    "contract_address":"419E62BE7F4F103C36507CB2A753418791B1CDC182",
>    "function_selector":"balanceOf(address)",
>    "parameter":"000000000000000000000041977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB",
>    "owner_address":"41977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB"
>    }'
> 2. get the decimal of TRC20 token by curl:
>    curl -X POST  https://api.shasta.trongrid.io/wallet/triggersmartcontract -d '{
>    "contract_address":"419E62BE7F4F103C36507CB2A753418791B1CDC182",
>    "function_selector":"decimals()",
>    "owner_address":"41977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB"
>    }'

thanks

**Comment by andelf** [comment]
> is it possible to get balance of one token in an address directly?
> 
> i can get the list assets of an address but how to get one token?

Can you repeat your questions? since I haven't get your point. Sim Chinese is OK.

**Comment by 1971192997** [comment]
> > is it possible to get balance of one token in an address directly?
> > i can get the list assets of an address but how to get one token?
> 
> Can you repeat your questions? since I haven't get your point. Sim Chinese is OK.

thank you  i know how to do that.
