### ISSUE TITLE
GrpcClient getTransactionInfoByID not available for fullnode 

### ISSUE THREAD

**Issue by Chirag-DanteChain** [tronprotocol/java-tron#3106]
### 1. What did you do?

Imported java-tron jar by using following in pom.xml
```
<dependency>
        <groupId>com.github.tronprotocol</groupId>
        <artifactId>java-tron</artifactId>
        <version>master</version>
```
Assuming this is correct maven dependency. I tried to implement wallet client using GrpcClient class. 
I am trying to get method GetTransactionInfoById but it is showing unavailable in WalletBlockingStub (fullnode) and is only available in soliditynode.

### 2. What did you expect to see?

Expected to call below method using grpc service exposed on fullnode 

```java
   public Optional<TransactionInfo> getTransactionInfoById(String txID) {
        ByteString bsTxid = ByteString.copyFrom(ByteArray.fromHexString(txID));
        GrpcAPI.BytesMessage request = GrpcAPI.BytesMessage.newBuilder().setValue(bsTxid).build();
        TransactionInfo transactionInfo;
        if (blockingStubSolidity != null) {
            transactionInfo = blockingStubSolidity.getTransactionInfoById(request);
        } else {
            transactionInfo = blockingStubFull.getTransactionInfoById(request);
        }
        return Optional.ofNullable(transactionInfo);
    }
```

### 3. What did you see instead?
described above.

Cannot resolve method in WalletBlockingStub

**Comment by livingrock7** [comment]
Appreciate if anyone from tron can help me with this. 
I need to get blockNumber using only txId. 

getTransactionByID does not get me block it was in

**Comment by cathy-lishipu** [comment]
Hi, you can try to use the HTTP interface, such as:https://api.trongrid.io/wallet/gettransactioninfobyid?value=a7055649513763a32bf554541a7d417223950990c546eebbb38f5ccd4f58d672

**Comment by cathy-lishipu** [comment]
You can try another way, such as using the HTTP interface.
https://api.trongrid.io/wallet/gettransactioninfobyid?value=a7055649513763a32bf554541a7d417223950990c546eebbb38f5ccd4f58d672

**Comment by Benson0224** [comment]
close this issue as the answer is clear. thanks.
