### ISSUE TITLE
How to calculate a transaction will consume the amount of the bandwidth?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3112]
### 1. What did you do?

Before the transaction occurs, I want to calculate the amount of bandwidth required for the transaction.

### 2. What did you expect to see?
i do not how to do.Hope to get a usable reference plan

### 3. What did you see instead?
i do not how to do.

**Comment by andelf** [comment]
FYI: https://github.com/tronprotocol/documentation/issues/370
