### ISSUE TITLE
I query the USDT balance , but returned "this node don't support constant"

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3113]
### 1. What did you do?

I use my local node to query the balance of usdt.

### 2. What did you expect to see?
the balance of usdt was returned.

### 3. What did you see instead?
And the balance was not returned. But returned "this node don't support constant".

**Comment by cathy-lishipu** [comment]
You can try setting 'vm.supportConstant = true' in the configuration file.

**Comment by yujianFresh** [comment]
> You can try setting 'vm.supportConstant = true' in the configuration file.

hi, i have setting vm.supportConstant= true in config file.but is doesn't effect.

the wrong message below:

{"result":{"code":"CONTRACT_VALIDATE_ERROR","message":"4e6f20636f6e7472616374206f72206e6f7420612076616c696420736d61727420636f6e7472616374"}}

**Comment by lintao989898** [comment]
我遇到了类似的问题。真的糟糕。
No contract or not a smart contract

**Comment by sc0Vu** [comment]
Is this issue fixed?
