### ISSUE TITLE
How to get TRX that freezes the whole network to get bandwidth or energy?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3123]
### 1. What did you do?

How to get TRX that freezes the whole network to get bandwidth or energy? 

### 2. What did you expect to see?
The amount of bandwidth obtained by freezing TRX in the whole network or energy

### 3. What did you see instead?
None

**Comment by Alexliu007** [comment]
You can use the wallet / getaccountresource interface to query, such as 

TotalNetLimit: 43200000000: the total bandwidth of the entire network
TotalNetWeight: 6633270674: The amount of bandwidth obtained by freezing TRX in the whole network, the unit is trx
TotalEnergyLimit: 100000000000: total energy of the entire network
TotalEnergyWeight: 762143248: The amount of energy obtained by freezing TRX in the whole network, the unit is trx

**Comment by woaichixigua07** [comment]
thanks!
