### ISSUE TITLE
Are there any rules for bandwidth consumption?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3124]
### 1. What did you do?

Are there any rules for bandwidth consumption?

### 2. What did you expect to see?
rules of bandwidth consumption

### 3. What did you see instead?
none

**Comment by Alexliu007** [comment]
https://developers.tron.network/docs/resource-model You can see the relevant documentation introduction.

**Comment by woaichixigua07** [comment]
thanks!
