### ISSUE TITLE
After broadcasting the transaction, the error code is returned:"NOT_ENOUGH_EFFECTIVE_CONNECTION"

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3125]
### 1. What did you do?

After broadcasting the transaction, the error code is returned:
"NOT_ENOUGH_EFFECTIVE_CONNECTION"

### 2. What did you expect to see?
Successful broadcast transaction.

### 3. What did you see instead?
{"code":"NOT_ENOUGH_EFFECTIVE_CONNECTION","message":"effective connection:0 lt minEffectiveConnection:1"}

**Comment by Alexliu007** [comment]
the node is not synchronized to the latest block and it cannot broadcast transactions.
