### ISSUE TITLE
After broadcasting the transaction, the error code is returned.

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3126]
### 1. What did you do?

After broadcasting the transaction, the error code is returned:
{"result":{"code":"OTHER_ERROR","message":"6f74686572206572726f72203a20546865206b657920617267756d656e742063616e6e6f74206265206e756c6c"},

### 2. What did you expect to see?
successful broadcast transaction

### 3. What did you see instead?
After broadcasting the transaction, the error code is returned:
{"result":{"code":"OTHER_ERROR","message":"6f74686572206572726f72203a20546865206b657920617267756d656e742063616e6e6f74206265206e756c6c"},

**Comment by Alexliu007** [comment]
You need to convert "message" field from hexadecimal to character, 
6f74686572206572726f72203a20546865206b657920617267756d656e742063616e6e6f74206265206e756c6c ===> "other error : The key argument cannot be null"Then you can see the clear message.
