### ISSUE TITLE
How to confirm the total supply of the TRC10 token ‘1002940’

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3132]
### 1. What did you do?

I don't know how to confirm the total supply of the TRC10 token ‘1002940’.

### 2. What did you expect to see?
the total supply of the TRC10 token ‘1002940’.

### 3. What did you see instead?
The total supply of this TRC10 token ‘1002940’,it's different from the tronscan.org data and the data returned via API.

**Comment by guoquanwu** [comment]
The data returned by the API is 6 more zeros than the data in  tronscan.org.
Because the data returned by the API is with precision. For example, if you have 6-digit precision, add 6 zeros after the total supply.
