### ISSUE TITLE
How to parse the data of smart contract transactions?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3133]
### 1. What did you do?

i need to parse the data of smart contract transactions.

### 2. What did you expect to see?
I need to know the address and amount of TRC 20 to transfer.

### 3. What did you see instead?
only return the data.
https://tronscan.org/#/transaction/abe22a059f0757b6a71e1653d02fb85c258c6c21e8dc531047053d90f1c1c638
https://api.trongrid.io/walletsolidity/gettransactionbyid?value=abe22a059f0757b6a71e1653d02fb85c258c6c21e8dc531047053d90f1c1c638

**Comment by guoquanwu** [comment]
For example:
a9059cbb  -->method
0000000000000000000000417c3bdf925dde1e17ef781d8d7eb2d6aeebbc0d41-->address
00000000000000000000000000000000000000000000000000000000cbbf2630-->uint256

There are 4 abytes of a9059cbb in front. These 4 bytes are the method ID. This is derived from the first 4 bytes of the Keccak hash signed by transfer (address, uint256) in ASCII format. Used by virtual machines to address functions.
Each 32 bytes in the back represents a parameter, which is not enough to fill in with 0.
