### ISSUE TITLE
Broadcasting the transaction with my own node, but it returns the error "Validate TransferContract error, no OwnerAccount." But using public nodes can be successful, how about it?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3135]
### 1. What did you do?

Broadcasting the transaction with my own node, but it returns the error "Validate TransferContract error, no OwnerAccount."
But using public nodes can be successful, how about it?

### 2. What did you expect to see?
sucess

**Comment by xueyafighting** [comment]
The block height is not synchronized to the latest height, and the transaction cannot be broadcast.
