### ISSUE TITLE
How much does it cost to activate a new account?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3147]
### 1. What did you do?

When activating an account, the required fee is uncertain.

### 2. What did you expect to see?
Instructions for activating account fees.

### 3. What did you see instead?
When activating an account, sometimes consume 0.1trx, sometimes only consume bandwidth.

**Comment by Alexliu007** [comment]
When you transfer(TRX or TRC10 token) to an account that does not exist in the network, this operation will first create that account in the network and then do the transfer. It only consumes Bandwidth points for account creation, no extra Bandwidth points consumption for transfer.

Create a new account transaction, Bandwidth points consumption sequence: 

Bandwidth points from freezing TRX. If transaction initiator does not have enough Bandwidth Points of this type(not free Bandwidth Points(5000) every day ), it will go to step 2;
Burn 0.1 TRX.
