### ISSUE TITLE
How to specify the log path when the node starts?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3151]
### 1. What did you do?

I need to know how to change the directory of tron.log.

### 2. What did you expect to see?
How to change the log directory.

### 3. What did you see instead?
i couldn't find this method.

**Comment by Alexliu007** [comment]
Modify the tron.log path in logback.xml.

<file>./logs/tron.log</file>

https://github.com/tronprotocol/java-tron/blob/b732245051598c5d059a6dee1ed92a57e0e028d0/framework/src/main/resources/logback.xml#L19
