### ISSUE TITLE
Feature Request: Filter transaction logs

### ISSUE THREAD

**Issue by alexqrid** [tronprotocol/java-tron#3157]
### 1. What do you want?

I want to find all transfers/burns/issuance of the specific token.

### 2. What did you expect to see?
I want to get JSON with  the information about transactions where this token was transferred/burned/issued.

### 3. What did you see instead?
There is no such a good feature in API.
### 4. How can be this implemented?  
It would be cool to have an API endpoint like ethereum has [eth_getLogs](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs) or [eth_newFilter](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter).

**Comment by Benson0224** [comment]
Tron do have event service on Transactions. 
check this guide on how to subscribe to the event  from fullnode: https://developers.tron.network/docs/event-subscribe

Check this guide if you need to setup your own event service
https://developers.tron.network/docs/event-plugin-deployment-mongodb

You can also find Trongrid API on customized event service. 
https://developers.tron.network/reference#events-1

I would say the last one Trongrid event API might be what you need.
