### ISSUE TITLE
Error on deployment

### ISSUE THREAD

**Issue by danielimkk** [tronprotocol/java-tron#3158]
Hey there! Could you please help me out with the following error? I'm trying to deploy a node using guide provided on docs page and having difficulties understanding the error.

### 1. What did you do?
I'm deploying the node using kubernetes and docker image. Where as an image I use official oracle jdk 1.8 image (Image Name: store/oracle/serverjre:8) there I build the code from this repo: https://github.com/tronprotocol/java-tron.git. Get all the executables succesfully. And launch the following command:
`nohup` java -XX:+UseConcMarkSweepGC -jar FullNode.jar  -p  private key --witness -c main_net_config.conf </dev/null &>/dev/null &`

### 2. What did you expect to see?
I expected to see the node start synchronization

### 3. What did you see instead?
But instead I recieve an exception which starts with the following line:
`09:53:38.324 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:546) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException`

Would be extremely thankfull if someone could explain why could I possibly receive this error.

P.S didn't want to leave any mess out here, so deployed logs to github repo.
Link : https://raw.githubusercontent.com/danielimkk/tron-logs/master/tron.log

**Comment by Benson0224** [comment]
Can you please share the main_net_config.conf file here.

**Comment by danielimkk** [comment]
Sure, but I use the mainnet config. Downloading it wit the following command:
`wget https://raw.githubusercontent.com/tronprotocol/tron-deployment/master/main_net_config.conf`
After downloading I just start the node with command mentioned above, so no changes to the config are made.

**Comment by Benson0224** [comment]
are you going to run an SR node or just a fullnode, if you just want to join Tron network as a fullnode, please remove ” --witness “ option

**Comment by danielimkk** [comment]
I'm going to run SR node

**Comment by Benson0224** [comment]
Try this: 
configure the localwitness in the config file, fill your private key there. line 419


// Optional.The default is empty.
// It is used when the witness account has set the witnessPermission.
// When it is not empty, the localWitnessAccountAddress represents the address of the witness account,
// and the localwitness is configured with the private key of the witnessPermissionAddress in the witness account.
// When it is empty,the localwitness is configured with the private key of the witness account.

//localWitnessAccountAddress =

localwitness = [
]

**Comment by danielimkk** [comment]
Tried the above suggestion, where localwitness is defined the following way:
`localwitness = [
   "private-key"
]`
Also tried removing witness option, same error.

Actually I don't understand the error log, if you have any ideas what it is saying, could you please share them? I would take a look into those spaces

**Comment by Benson0224** [comment]
org.springframework.beans.factory.BeanCreationException  this exception is java spring exception , should be ENV related issue, please check your env setup and make sure spring is also OK within that docker image.

**Comment by danielimkk** [comment]
Hey @Benson0224. I've been trying to find the case of an error and spotted one more thing.
Output of the node launch command looks the following:
`******** begin to pop revokingDb ********`
`******** before revokingDb size:0`
`******** end to pop revokingDb ********`
Could you please tell me if you have any idea what could've caused this error?

P.S. I've checked if spring works or not, simple applications run properly.
And also if the env list can be helpful here it is:
`HOSTNAME=tron-deployment-57d4c7c796-2lpkb`
`KUBERNETES_PORT_443_TCP_PORT=443`
`KUBERNETES_PORT=tcp://10.96.0.1:443`
`TERM=xterm`
`KUBERNETES_SERVICE_PORT=443`
`KUBERNETES_SERVICE_HOST=10.96.0.1`
`PATH=/usr/java/jdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
`PWD=/project/tron/java-tron/build/libs`
`JAVA_HOME=/usr/java/jdk-8`
`LANG=en_US.UTF-8`
`JAVA_VERSION=1.8.0_241`
`SHLVL=1`
`HOME=/root`
`KUBERNETES_PORT_443_TCP_PROTO=tcp`
`KUBERNETES_SERVICE_PORT_HTTPS=443`
`KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1`
`KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443`
`_=/usr/bin/printenv`
`OLDPWD=/`

**Comment by Benson0224** [comment]
@danielimkk  suggest to check the number of docker CPU cores,  it cannot be 1.  

we got a similar issue before. check detail explaination at: 
https://github.com/tronprotocol/java-tron/issues/2988#issuecomment-593100171

**Comment by danielimkk** [comment]
@Benson0224 Yeap, thank you very much! Indeed that was the case. By the way are the requirements for SR node: 16 cores, 32G RAM, 500G+ Storage?

**Comment by Benson0224** [comment]
From the official recommendation, your HW step up should be OK. 

minimum requirement:
CPU: 16 cores, RAM: 32G, Bandwidth: 100M, Disk: 1T
Recommended requirement:
CPU: > 64 cores RAM: > 64G, Bandwidth: > 500M, Disk: > 2T

check detail at: 
https://github.com/tronprotocol/documentation-en/blob/master/docs/architecture/network.md

**Comment by danielimkk** [comment]
Cool, thank you for all the help!
