### ISSUE TITLE
Nile Testnet query trc20 balance error.

### ISSUE THREAD

**Issue by minchenzz** [tronprotocol/java-tron#3164]
I deployed the Nile Testnet locally. I want query trc20 balance, but I got an error.

message: this node does not support constant.

I replace ```localhost:8090``` with ```47.252.19.181:8090```(public node), got a successfully response.

I dont know how to fix it.

```curl http://localhost:8090/wallet/triggersmartcontract -d '{"contract_address": "4126a5993a3887ebcb500590fc156a87c71157952a", "function_selector": "balanceOf(address)", "parameter": "000000000000000000000041ef8e49a6f852f4f0a7ba0c593b2806ca97228722", "owner_address": "41ef8e49a6f852f4f0a7ba0c593b2806ca97228722"}'```
```{"result":{"code":"CONTRACT_VALIDATE_ERROR","message":"74686973206e6f646520646f6573206e6f7420737570706f727420636f6e7374616e74"}}```

**Comment by Alexliu007** [comment]
Modify vm.supportConstant in the configuration file to true。supportConstant = true

**Comment by yujianFresh** [comment]
> Modify vm.supportConstant in the configuration file to true, supportConstant = true

only modify config and restart node ? isn't it sync again ?
