### ISSUE TITLE
what is triggerconstantcontract function different from triggersmartcontract function?？

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3167]
### 1. What did you do?

what is triggerconstantcontract function different from triggersmartcontract function?？

**Comment by Alexliu007** [comment]
triggerconstantcontract function : Trigger the constant function of the smart contract, the transaction is off the blockchain, and it will not consume resources.
triggersmartcontract function : Trigger the inconstant function of the smart contract, it will be broadcasted in the form of a transaction while be called, the function will change the data on the chain, such as transfer, changing the value of the internal variables of contracts, etc. And it will not consume resources(energy and bandwidth).
