### ISSUE TITLE
Does "transferFrom" function of TRC20 smart contract require authorization?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3169]
### 1. What did you do?

Does "transferFrom" function of TRC20 smart contract require authorization?

### 2. What did you expect to see?
I failed to call the method

### 3. What did you see instead?
success to call this method

**Comment by Alexliu007** [comment]
Yes, this method needs to be combined with the approve to be used. For example, account A has 1000 USDT, and you want to allow account B to call 100 USDT at will. The A account calls the approve function approve (B address, 100) in the following form. When the B account wants to use 10 of the 100 TRC20 to the C account, the B account calls transferFrom (A, C, 10).
