### ISSUE TITLE
Does nile testnet support "Wallet/GetTransactionInfoByBlockNum "? 

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3170]
### 1. What did you do?

Accessing this API via nile's fullnode (47.252.3.238) failed

### 2. What did you expect to see?
Method not found: protocol.Wallet/GetTransactionInfoByBlockNum

### 3. What did you see instead?
successfully access to this API

**Comment by Alexliu007** [comment]
(47.252.3.238,  Method not found: protocol.Wallet/GetTransactionInfoByBlockNum )

yes, for some reasons, nile testnet does not yet support this API, you can use shasta testnet.
