### ISSUE TITLE
How to estimate the energy consumed by contract execution before calling the contract function?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3180]
### 1. What did you do?

How to estimate the energy consumed by contract execution before calling the contract function?

### 2. What did you expect to see?
estimate the energy consumed.

### 3. What did you see instead?
i don't know how to do it

**Comment by Alexliu007** [comment]
The current estimated method is: you can execute the contract method on the test network, estimate the energy usage, and attention to setting the "feelimit" parameter.
