### ISSUE TITLE
When signing the transaction, "validate signature error" is returned. What is the reason?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3181]
### 1. What did you do?

When signing the transaction, an error is returned. 
"validate signature error XXX.....XXXX is signed by xxx but it is not contained of permission."

### 2. What did you expect to see?
What is the reason?

### 3. What did you see instead?
what i should do

**Comment by Alexliu007** [comment]
The following checks are required:
1. Confirm whether the account has multi-signature authority.
2. Confirm whether the owner address is correct.
