### ISSUE TITLE
The address is not prefixed by 41 in the returned data field by "wallet/gettransactionbyid" API,  what's the reason?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3182]
### 1. What did you do?

Some addresses are prefixed by 41 , some are not, what is the reason?

### 2. What did you expect to see?
Some addresses are prefixed by 41 , some are not.

### 3. What did you see instead?
what is the reason?

**Comment by Alexliu007** [comment]
This is because when creating a transaction, it is related to the parameters passed, some with 41, some without 41.These will be ignored when the virtual machine is executed, and only the last 20 bytes are looked at. You can ensure that these 20 bytes are correct.
