### ISSUE TITLE
Failed to deploy trc20 contract on private chain, return "contractRet": "ILLEGAL_OPERATION" error

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3184]
### 1. What did you do?

return VM halted: [Invalid operation code: opCode[d3];] error

### 2. What did you expect to see?
deploy contract sucess.

**Comment by Alexliu007** [comment]
Use the interface wallet/getchainparameters to query the relevant proposal configuration and ensure that the getAllowTvmTransferTrc10 parameter value is 1. For details, please refer to the documentation 
https://cn.developers.tron.network/docs/%E7%A7%81%E9%93%BE%E6%90%AD%E5%BB%BA
