### ISSUE TITLE
When deploying a contract on a private chain, return error "contractRet": "ILLEGAL_OPERATION"

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3197]
### 1. What did you do?

For the same contract, shasta testnet can be successfully deployed, but an error is reported when deploying on the private chain.

### 2. What did you expect to see?
successfully deploy the contract.

### 3. What did you see instead?
error "contractRet": "ILLEGAL_OPERATION"

**Comment by Alexliu007** [comment]
The proposal "getAllowTvmTransferTrc10" needs to be initiated on the private chain, set to value=1
