### ISSUE TITLE
When broadcasting transactions, return error “Code = TAPOS_ERROR Message = Tapos check error”

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3198]

**Comment by Alexliu007** [comment]
Modify the configuration file: trx.reference.block = "solid"
Every legal transaction needs to have a block within a certain period of time on the chain as a reference (TaPOS). If the block used as a reference block when you create a transaction is rolled back or not new enough, TaPOS verification failure will occur. “solid ”refers to using the confirmed block as the reference block, and “head ”uses the latest block
