### ISSUE TITLE
Nile testnet upgrade cannot synchronize blocks

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3220]
### 1. What did you do?

my fullnode on Nile testnet stop synchronizing blocks,pls check it

### 2. What did you expect to see?
12:10:53.499 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:6402520,ID:000000000061b1d829bee3549b1131dbcca7fcb992e01361847b6fd3af9e1e4f failed.
12:10:53.497 ERROR [pool-42-thread-1] [DB](Manager.java:1142) Validate ShieldedTransferContract error, balance is not sufficient
12:10:53.499 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:6402520,ID:000000000061b1d829bee3549b1131dbcca7fcb992e01361847b6fd3af9e1e4f, reason: Validate ShieldedTransferContract error, balance is not sufficient.
12:10:53.499 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:6402520,ID:000000000061b1d829bee3549b1131dbcca7fcb992e01361847b6fd3af9e1e4f failed.

### 3. What did you see instead?
pls check it

**Comment by Alexliu007** [comment]
nile testnet has been upgraded , please use the new branch code: feature/vm_shielded_nile

**Comment by ccdonn** [comment]
same problem.

after i upgrade to new version with new config, still cannot sync blocks.

i check the logs as you can see following. 
it looks like some node haven't upgrade yet. i am not sure is that cause this problem?
what can i do to avoid this situation?

`
13:27:52.902 INFO  [TronJClientWorker-5] [net](HandshakeHandler.java:112) Handshake Send to /47.252.19.181:18888, type: P2P_HELLO
from {
  address: "123.51.190.194"
  port: 18888
  nodeId: "\032\274\261\2469k\302-\245\024\335H\375\245Qe\367\237\340\rj_\251\242\001\263n\244\036\213\002\365\356\356\2769I\004:\247\227\025\245\241[\261\371v\363\221\366\206*2\t\332\364\336\237K\304\226\036*"
}
headBlockId {
  hash: "\000\000\000\000\000a\t\322<\327\377\363\316-\a\235/\305\350i\317Y\364b\244\b\316\\+-\365l"
  number: 6359506
}
--
13:27:53.104 INFO  [TronJClientWorker-5] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.19.181:18888, type: P2P_HELLO
from {
  address: "47.252.19.181"
  port: 18888
  nodeId: "\213\302\366.+Q;Yl\263z\234-\002P\005\360\360\263\233_)\345eU\035\250\276\214\nv\207\016\b\342\301\221\207Q]Q\314\261\354\n\255B|\037\216FsD\325\234\027\211\227\233\342\030\306\337@"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.107 INFO  [TronJClientWorker-2] [net](HandshakeHandler.java:77) Handshake Receive from /47.90.243.177:18888, type: P2P_HELLO
from {
  address: "47.90.243.177"
  port: 18888
  nodeId: "\264\a\024\240\r\275\345\"\207\001\324\3470O`\366\273J\204\004\022\231\342\001\254\020V\364\026~h\332#\247\312$\345\212\250M\304\0027A\365\006\263\022h\te\333X=[\333\3745\2554\312\237\032\261"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.106 INFO  [TronJClientWorker-6] [net](HandshakeHandler.java:77) Handshake Receive from /47.90.214.183:18888, type: P2P_HELLO
from {
  address: "47.90.214.183"
  port: 18888
  nodeId: "\177}\004\204k\340(\374$V\201\242\023\257\254f\357w\373li\366\203\260\000\372U7}xa\2611\003^in\034(\332\215\nt\227\034\016t\367\272\2537\227M\310!\341\3329j?\177\207\002\326"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.111 INFO  [TronJClientWorker-4] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.17.40:18888, type: P2P_HELLO
from {
  address: "47.252.17.40"
  port: 18888
  nodeId: "\255ap\256\246T\263\247\213\237\336@G\273\203\226\247 \344\000\226/\275m\v\177W\037\205\0006\302\305\311k\002\340\244.\327\306\245\a\237\265\n\310)B\220\206\311\244\020\260o\377\350\260jes\210Q"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.108 INFO  [TronJClientWorker-3] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.3.238:18888, type: P2P_HELLO
from {
  address: "47.252.3.238"
  port: 18888
  nodeId: "\306\006\025\255htA3dc\214\213\017\304\343*{\023\344E\257\034\004u\353.\272\177U\033\253\nx9\311_C\322\000Q%H$\242o\034dg\260\021\264\254\231\200j\'Lf\343\326\024q\277\024"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.691 INFO  [TronJClientWorker-7] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.73.173:18888, type: P2P_HELLO
from {
  address: "47.252.73.173"
  port: 18888
  nodeId: "\024b(\317\211@l\345\325<\331\245I\213\342\206~\002\353z\tQ5\267\240;\245\342\361\022\312\362L\370\352\vU\a\034\240\310|2)\325\003\021\006j\347\325\264O\207>\316\221\365\375\f}w\312\244"
}
headBlockId {
  hash: "\000\000\000\000\000a\n 3\363+\217O\326\312\357\fM@\334\330b/\366J\206\230\"\377Lf\377"
  number: 6359584
}
--
13:27:53.823 INFO  [TronJClientWorker-0] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.84.138:18888, type: P2P_HELLO
from {
  address: "47.252.84.138"
  port: 18888
  nodeId: "+\307E|\376\200\312Z\354\250et\274\f\322\360g\2159=]1N\245\334W\341\244\274#s6h\234UT9U\bp\302\243Q\357\020\266\321\302\033q\320sTR\177\2362\236J\310\231\216\"\326"
}
headBlockId {
  hash: "\000\000\000\000\000a\n 3\363+\217O\326\312\357\fM@\334\330b/\366J\206\230\"\377Lf\377"
  number: 6359584
}
`

**Comment by ccdonn** [comment]
same problem.

after i upgrade to new version with new config, still cannot sync blocks.

i check the logs as you can see following. 
it looks like some node haven't upgrade yet. i am not sure is that cause this problem?
what can i do to avoid this situation?

```
13:27:52.902 INFO  [TronJClientWorker-5] [net](HandshakeHandler.java:112) Handshake Send to /47.252.19.181:18888, type: P2P_HELLO
from {
  address: "123.51.190.194"
  port: 18888
  nodeId: "\032\274\261\2469k\302-\245\024\335H\375\245Qe\367\237\340\rj_\251\242\001\263n\244\036\213\002\365\356\356\2769I\004:\247\227\025\245\241[\261\371v\363\221\366\206*2\t\332\364\336\237K\304\226\036*"
}
headBlockId {
  hash: "\000\000\000\000\000a\t\322<\327\377\363\316-\a\235/\305\350i\317Y\364b\244\b\316\\+-\365l"
  number: 6359506
}
--
13:27:53.104 INFO  [TronJClientWorker-5] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.19.181:18888, type: P2P_HELLO
from {
  address: "47.252.19.181"
  port: 18888
  nodeId: "\213\302\366.+Q;Yl\263z\234-\002P\005\360\360\263\233_)\345eU\035\250\276\214\nv\207\016\b\342\301\221\207Q]Q\314\261\354\n\255B|\037\216FsD\325\234\027\211\227\233\342\030\306\337@"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.107 INFO  [TronJClientWorker-2] [net](HandshakeHandler.java:77) Handshake Receive from /47.90.243.177:18888, type: P2P_HELLO
from {
  address: "47.90.243.177"
  port: 18888
  nodeId: "\264\a\024\240\r\275\345\"\207\001\324\3470O`\366\273J\204\004\022\231\342\001\254\020V\364\026~h\332#\247\312$\345\212\250M\304\0027A\365\006\263\022h\te\333X=[\333\3745\2554\312\237\032\261"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.106 INFO  [TronJClientWorker-6] [net](HandshakeHandler.java:77) Handshake Receive from /47.90.214.183:18888, type: P2P_HELLO
from {
  address: "47.90.214.183"
  port: 18888
  nodeId: "\177}\004\204k\340(\374$V\201\242\023\257\254f\357w\373li\366\203\260\000\372U7}xa\2611\003^in\034(\332\215\nt\227\034\016t\367\272\2537\227M\310!\341\3329j?\177\207\002\326"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.111 INFO  [TronJClientWorker-4] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.17.40:18888, type: P2P_HELLO
from {
  address: "47.252.17.40"
  port: 18888
  nodeId: "\255ap\256\246T\263\247\213\237\336@G\273\203\226\247 \344\000\226/\275m\v\177W\037\205\0006\302\305\311k\002\340\244.\327\306\245\a\237\265\n\310)B\220\206\311\244\020\260o\377\350\260jes\210Q"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.108 INFO  [TronJClientWorker-3] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.3.238:18888, type: P2P_HELLO
from {
  address: "47.252.3.238"
  port: 18888
  nodeId: "\306\006\025\255htA3dc\214\213\017\304\343*{\023\344E\257\034\004u\353.\272\177U\033\253\nx9\311_C\322\000Q%H$\242o\034dg\260\021\264\254\231\200j\'Lf\343\326\024q\277\024"
}
headBlockId {
  hash: "\000\000\000\000\000c#\\\0219\024 \213\345\276B\247\331\2156)5]B\203\224c\224\234e\3552"
  number: 6497116
}
--
13:27:53.691 INFO  [TronJClientWorker-7] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.73.173:18888, type: P2P_HELLO
from {
  address: "47.252.73.173"
  port: 18888
  nodeId: "\024b(\317\211@l\345\325<\331\245I\213\342\206~\002\353z\tQ5\267\240;\245\342\361\022\312\362L\370\352\vU\a\034\240\310|2)\325\003\021\006j\347\325\264O\207>\316\221\365\375\f}w\312\244"
}
headBlockId {
  hash: "\000\000\000\000\000a\n 3\363+\217O\326\312\357\fM@\334\330b/\366J\206\230\"\377Lf\377"
  number: 6359584
}
--
13:27:53.823 INFO  [TronJClientWorker-0] [net](HandshakeHandler.java:77) Handshake Receive from /47.252.84.138:18888, type: P2P_HELLO
from {
  address: "47.252.84.138"
  port: 18888
  nodeId: "+\307E|\376\200\312Z\354\250et\274\f\322\360g\2159=]1N\245\334W\341\244\274#s6h\234UT9U\bp\302\243Q\357\020\266\321\302\033q\320sTR\177\2362\236J\310\231\216\"\326"
}
headBlockId {
  hash: "\000\000\000\000\000a\n 3\363+\217O\326\312\357\fM@\334\330b/\366J\206\230\"\377Lf\377"
  number: 6359584
}
```

**Comment by ccdonn** [comment]
leave nile testnet logs with two error messages. build with commit  67f20f404988b0cb0f4a157240a7338b4048ab7a.

Case1.
```
10:44:35.646 ERROR [pool-43-thread-1] [DB](Manager.java:1142) record is fail, skip proof
org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:284)
	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:265)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
10:44:35.651 ERROR [pool-43-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:6359585,ID:0000000000610a215fada79175f763d5372374597bf7ce33741fa8da0380a8af, reason: record is fail, skip proof.
10:44:35.653 ERROR [pool-43-thread-1] [net](SyncService.java:264) Process sync block Num:6359585,ID:0000000000610a215fada79175f763d5372374597bf7ce33741fa8da0380a8af failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:224)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:284)
	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:265)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	... 12 common frames omitted
```

Case2.
```
10:21:03.808 INFO  [pool-42-thread-1] [DB](Manager.java:1715) PreValidate Transaction Sign, size:1,block num:1628391
10:21:03.823 ERROR [pool-42-thread-1] [DB](Manager.java:1142) Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
org.tron.core.exception.ContractValidateException: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
	at org.tron.core.utils.ProposalUtil.validator(ProposalUtil.java:255)
	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:123)
	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:116)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
10:21:03.825 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:1628391,ID:000000000018d8e7060c6fb06bd3fb3b35d9b294a268a76699654551a8f83a38, reason: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION].
10:21:03.826 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:1628391,ID:000000000018d8e7060c6fb06bd3fb3b35d9b294a268a76699654551a8f83a38 failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ContractValidateException: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:224)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ContractValidateException: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
	at org.tron.core.utils.ProposalUtil.validator(ProposalUtil.java:255)
	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:123)
	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:116)
	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
	... 12 common frames omitted
```

**Comment by shydesky** [comment]
> leave nile testnet fullnode logs with two error messages. build with commit [67f20f4](https://github.com/tronprotocol/java-tron/commit/67f20f404988b0cb0f4a157240a7338b4048ab7a).
> 
> Case1.
> 
> ```
> 10:44:35.646 ERROR [pool-43-thread-1] [DB](Manager.java:1142) record is fail, skip proof
> org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
> 	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:284)
> 	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:265)
> 	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
> 	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
> 	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
> 	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
> 	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
> 	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
> 	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
> 	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
> 	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
> 	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
> 	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 10:44:35.651 ERROR [pool-43-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:6359585,ID:0000000000610a215fada79175f763d5372374597bf7ce33741fa8da0380a8af, reason: record is fail, skip proof.
> 10:44:35.653 ERROR [pool-43-thread-1] [net](SyncService.java:264) Process sync block Num:6359585,ID:0000000000610a215fada79175f763d5372374597bf7ce33741fa8da0380a8af failed.
> org.tron.core.exception.P2pException: org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:224)
> 	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
> 	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
> 	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
> 	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
> 	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.tron.core.exception.ZkProofValidateException: record is fail, skip proof
> 	at org.tron.core.actuator.ShieldedTransferActuator.checkProof(ShieldedTransferActuator.java:284)
> 	at org.tron.core.actuator.ShieldedTransferActuator.validate(ShieldedTransferActuator.java:265)
> 	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
> 	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
> 	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
> 	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
> 	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
> 	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
> 	... 12 common frames omitted
> ```
> 
> Case2.
> 
> ```
> 10:21:03.808 INFO  [pool-42-thread-1] [DB](Manager.java:1715) PreValidate Transaction Sign, size:1,block num:1628391
> 10:21:03.823 ERROR [pool-42-thread-1] [DB](Manager.java:1142) Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
> org.tron.core.exception.ContractValidateException: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
> 	at org.tron.core.utils.ProposalUtil.validator(ProposalUtil.java:255)
> 	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:123)
> 	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:116)
> 	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
> 	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
> 	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
> 	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
> 	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
> 	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
> 	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
> 	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
> 	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
> 	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
> 	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 10:21:03.825 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:1628391,ID:000000000018d8e7060c6fb06bd3fb3b35d9b294a268a76699654551a8f83a38, reason: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION].
> 10:21:03.826 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:1628391,ID:000000000018d8e7060c6fb06bd3fb3b35d9b294a268a76699654551a8f83a38 failed.
> org.tron.core.exception.P2pException: org.tron.core.exception.ContractValidateException: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:224)
> 	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:262)
> 	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:251)
> 	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
> 	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:234)
> 	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.tron.core.exception.ContractValidateException: Bad chain parameter id [ALLOW_SHIELDED_TRANSACTION]
> 	at org.tron.core.utils.ProposalUtil.validator(ProposalUtil.java:255)
> 	at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:123)
> 	at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:116)
> 	at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:64)
> 	at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:169)
> 	at org.tron.core.db.Manager.processTransaction(Manager.java:1299)
> 	at org.tron.core.db.Manager.processBlock(Manager.java:1535)
> 	at org.tron.core.db.Manager.applyBlock(Manager.java:922)
> 	at org.tron.core.db.Manager.pushBlock(Manager.java:1135)
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:197)
> 	... 12 common frames omitted
> ```

the database may be incorrect because of using the different version code. Please download the newest backup of database at here: http://47.90.243.177/

**Comment by ccdonn** [comment]
awesome!
everything goes well after using the backup database.
thanks, you save my day.
