### ISSUE TITLE
区块遍历问题

### ISSUE THREAD

**Issue by mayaoguang** [tronprotocol/java-tron#3225]
在遍历区块的时候遇到错误：
{"Error":"class com.alibaba.fastjson.JSONException : unclosed string : :"}
遍历的命令：
curl -X POST "34.220.77.106:8090/wallet/getblockbynum" -H "Content-Type: application/json" --data '{"num":20181145,"visible":true}'
这个问题只有部分区块会遇到
如果把参数visible 改为false，不会报错
20645902 区块也有同样的问题

**Comment by andelf** [comment]
Please use `curl -X POST "34.220.77.106:8090/wallet/getblockbynum?visible=true" -H "Content-Type: application/json" --data '{"num":20181145}'  as a replacement.

**Comment by mayaoguang** [comment]
使用这个命令的话返回的地址格式是“Hex string format“但是我们需要返回”Base58check“ 的地址，使用这个命令需要额外转一次

**Comment by mayaoguang** [comment]
使用这个命令的话返回的地址格式是“Hex string format“但是我们需要返回”Base58check“ 的地址，使用这个命令需要额外转一次。

**Comment by andelf** [comment]
This is caused by a bug when JsonFormat `AssetIssueContract` with visible=true.
To reproduce the bug:

```
curl --request POST \
  --url https://api.trongrid.io/wallet/gettransactionbyid \
  --header 'content-type: application/json' \
  --data '{"value":"8d0fe62ab1215efae8c45421f6b97f8b5ec8ca07239bd9d6dc7ae6feaf6a78f5","visible":true}'
```

**Comment by mayaoguang** [comment]
> 这是由JsonFormat `AssetIssueContract`与visible = true 时的错误引起的。
> 重现该错误：
> 
> ```
> curl --request POST \
>   --url https://api.trongrid.io/wallet/gettransactionbyid \
>   --header 'content-type: application/json' \
>   --data '{"value":"8d0fe62ab1215efae8c45421f6b97f8b5ec8ca07239bd9d6dc7ae6feaf6a78f5","visible":true}'
> ```

请问使用 visible = true 有什么办法避免这个错误么？

**Comment by andelf** [comment]
SWill fix it soon.

+UPDATE: 

bug in: 

```java
  static String escapeBytesSelfType(ByteString input, final String fliedName) {
    //Address
    if (HttpSelfFormatFieldName.isAddressFormat(fliedName)) {
      return WalletUtil.encode58Check(input.toByteArray());
    }

    //Normal String
    if (HttpSelfFormatFieldName.isNameStringFormat(fliedName)) {
      String result = new String(input.toByteArray());
      return result.replaceAll("\"", "\\\\\"");
    }

    //HEX
    return ByteArray.toHexString(input.toByteArray());
  }
```

**Comment by mayaoguang** [comment]
> Will fix it soon.
> 
> +UPDATE:
> 
> bug in:
> 
> ```java
>   static String escapeBytesSelfType(ByteString input, final String fliedName) {
>     //Address
>     if (HttpSelfFormatFieldName.isAddressFormat(fliedName)) {
>       return WalletUtil.encode58Check(input.toByteArray());
>     }
> 
>     //Normal String
>     if (HttpSelfFormatFieldName.isNameStringFormat(fliedName)) {
>       String result = new String(input.toByteArray());
>       return result.replaceAll("\"", "\\\\\"");
>     }
> 
>     //HEX
>     return ByteArray.toHexString(input.toByteArray());
>   }
> ```

大概需要多久可以完成修改呢？已经找到问题了应该比较快吧

**Comment by mayaoguang** [comment]
> > Will fix it soon.
> 
> 大概需要多久可以完成修改呢？已经找到问题了应该比较快吧

**Comment by mayaoguang** [comment]
> ~Please use `curl -X POST "34.220.77.106:8090/wallet/getblockbynum?visible=true" -H "Content-Type: application/json" --data '{"num":20181145}'` as a replacement.~

请问修改方向是推荐使用 visible=true 还是不使用

**Comment by mayaoguang** [comment]
遍历区块的rpc接口 修改方向是推荐使用 visible=true 还是不推荐使用呢？

**Comment by shydesky** [comment]
> visible

`visible = true` is for the base58check type of address. Namely, if you use the base58check address(address starts with the character "T"), you should add the visible parameter.

**Comment by shydesky** [comment]
> 无
you can look at this, maybe helpful.
https://github.com/tronprotocol/wallet-cli/blob/ae1c6002fda27297dee709ba711e5b14a41242fe/src/main/java/org/tron/walletserver/WalletApi.java#L1096

**Comment by shixiaofeia** [comment]
So how can this problem be solved?

**Comment by shixiaofeia** [comment]
@shydesky

**Comment by shixiaofeia** [comment]
Will there be similar problems when I reference visible = true in other interfaces? Or is this problem only when traversing the blockchain information will appea
