### ISSUE TITLE
全节点是最新版本，同步滞后，追不上公链节点

### ISSUE THREAD

**Issue by zhenghq** [tronprotocol/java-tron#3227]
### 1. What did you do?

全节点是最新版本，同步滞后，追不上公链节点

### 2. What did you expect to see?

19:45:36.272 INFO  [TronJClientWorker-2] [net](Channel.java:195) Peer /47.90.240.187:18888 status change to HANDSHAKE_FINISHED.
19:45:36.272 INFO  [TronJClientWorker-2] [net](Channel.java:105) Finish handshake with /47.90.240.187:18888.
19:45:36.272 INFO  [TronJClientWorker-2] [net](ChannelManager.java:156) Add active peer /47.90.240.187:18888 | bf391f49e7a4997472af7ea552251dbe5638e6914455743b84753f672e4f1969228e16cc1ec1337e05c880c268927e17604313133b57ed8e16ecb67015a6685a, total active peers: 18
19:45:36.273 INFO  [TronJClientWorker-2] [net](Channel.java:195) Peer /47.90.240.187:18888 status change to SYNCING.
19:45:36.273 INFO  [TronJClientWorker-2] [net](Channel.java:195) Peer /47.90.240.187:18888 status change to SYNCING.
19:45:36.273 INFO  [TronJClientWorker-2] [DB](Manager.java:1601) headNumber:20516089
19:45:36.273 INFO  [TronJClientWorker-2] [DB](Manager.java:1602) syncBeginNumber:20516070
19:45:36.273 INFO  [TronJClientWorker-2] [DB](Manager.java:1605) solidBlockNumber:20516071
19:45:36.273 INFO  [TronJClientWorker-2] [net](SyncService.java:175) Get block chain summary, low: 20516070, highNoFork: 20516089, high: 20516089, realHigh: 20516089
19:45:36.273 INFO  [TronJClientWorker-2] [net](MessageQueue.java:94) Send to /47.90.240.187:18888, type: SYNC_BLOCK_CHAIN
size: 5, start block: Num:20516070,ID:0000000001390ce60bcde359a078d6d21f384250dd194dc55c3705bcbc920db0, end block Num:20516089,ID:0000000001390cf94d0fe5a1b526098e9154502e234e913697e212798ba1365a
19:45:36.273 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.90.240.187, syncFromUs: false, syncFromPeer: true.
19:45:36.274 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.90.240.187, syncFromUs: false, syncFromPeer: true.
19:45:36.274 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.90.240.187, syncFromUs: false, syncFromPeer: true.
19:45:36.274 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 2 from Peer /47.90.240.187, syncFromUs: false, syncFromPeer: true.
19:45:36.274 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.90.240.187, syncFromUs: false, syncFromPeer: true.
19:45:36.274 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 2 from Peer /47.90.240.187, syncFromUs: false, syncFromPeer: true.
19:45:36.395 WARN  [TronJClientWorker-2] [net](InventoryMsgHandler.java:51) Drop inv: TRX size: 1 from Peer /47.90.240.187, syncFromUs: false, syncFromPeer: true.
19:45:36.998 INFO  [TronJClientWorker-0] [net](MessageQueue.java:108) Receive from /47.74.35.73:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:20516089,ID:0000000001390cf94d0fe5a1b526098e9154502e234e913697e212798ba1365a, end blockId: Num:20518089,ID:00000000013914c97f82d71e1ff0b7da84f3609d1343b02f5a4114c2bb4fd9a3

### 3. What did you see instead?

有人知道是什么问题么

**Comment by guoquanwu** [comment]
Could you provide more details? Logs that contain "ERROR" is preferred.

**Comment by zhenghq** [comment]
> Could you provide more details? Logs that contain "ERROR" is preferred.

09:13:22.738 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.738 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.738 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.738 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.738 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.739 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.740 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.740 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.740 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.740 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.740 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.740 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.740 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:13:22.740 ERROR [TronJClientWorker-0] [net](MessageQueue.java:68) Fail send to /81.169.194.160:18888, type: BLOCK
09:29:15.781 ERROR [pool-42-thread-1] [DB](Manager.java:1142) Different resultCode
09:29:15.782 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:20518317,ID:00000000013915adc549132e3ee39394a9f7e30f22d7012aea4ad023d179506f, reason: Different resultCode.
09:29:15.782 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:20518317,ID:00000000013915adc549132e3ee39394a9f7e30f22d7012aea4ad023d179506f failed.
10:30:21.465 ERROR [TronJClientWorker-3] [net](MessageQueue.java:172) Fail send to /18.229.43.112:18888, type: P2P_PING
10:30:53.075 ERROR [TronJClientWorker-2] [net](MessageQueue.java:172) Fail send to /35.240.160.120:18888, type: P2P_PING
10:31:40.441 ERROR [TronJClientWorker-0] [net](MessageQueue.java:172) Fail send to /209.188.7.230:18888, type: P2P_PING
10:31:40.464 ERROR [TronJClientWorker-3] [net](MessageQueue.java:172) Fail send to /47.254.77.146:18888, type: SYNC_BLOCK_CHAIN
10:31:59.000 ERROR [TronJClientWorker-0] [net](MessageQueue.java:172) Fail send to /47.74.224.123:18888, type: P2P_PING
10:32:33.905 ERROR [TronJClientWorker-0] [net](MessageQueue.java:172) Fail send to /84.239.4.146:18888, type: P2P_PING
10:33:12.117 ERROR [TronJClientWorker-3] [net](MessageQueue.java:172) Fail send to /47.74.57.254:18888, type: P2P_PING
10:34:47.672 ERROR [TronJClientWorker-0] [net](MessageQueue.java:172) Fail send to /78.159.97.95:18888, type: SYNC_BLOCK_CHAIN
10:35:16.690 ERROR [TronJClientWorker-1] [net](MessageQueue.java:172) Fail send to /35.159.8.92:18888, type: P2P_PING
10:35:16.690 ERROR [TronJClientWorker-1] [net](MessageQueue.java:172) Fail send to /47.74.35.73:18888, type: P2P_PING
10:35:16.690 ERROR [TronJClientWorker-1] [net](MessageQueue.java:172) Fail send to /47.90.215.50:18888, type: P2P_PING
10:35:23.988 ERROR [TronJClientWorker-3] [net](MessageQueue.java:172) Fail send to /52.31.177.139:18888, type: P2P_PING
10:35:23.989 ERROR [TronJClientWorker-3] [net](MessageQueue.java:172) Fail send to /51.68.119.188:18888, type: P2P_PING
10:35:36.665 ERROR [TronJClientWorker-1] [net](MessageQueue.java:172) Fail send to /47.75.38.234:18888, type: P2P_PING
10:35:47.838 ERROR [TronJClientWorker-1] [net](MessageQueue.java:172) Fail send to /47.75.128.222:18888, type: P2P_PING
10:35:47.838 ERROR [TronJClientWorker-1] [net](MessageQueue.java:172) Fail send to /47.75.55.26:18888, type: P2P_PING
10:36:30.109 ERROR [TronJClientWorker-1] [net](MessageQueue.java:172) Fail send to /47.75.77.31:18888, type: P2P_PING
10:37:39.823 ERROR [TronJClientWorker-2] [net](MessageQueue.java:172) Fail send to /47.89.243.195:18888, type: P2P_PING
10:38:05.506 ERROR [pool-42-thread-1] [DB](Manager.java:1142) Different resultCode
10:38:05.506 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:20518606,ID:00000000013916ce93aefd7e8696e98338b41c20acdb7795e4a016b353533e44, reason: Different resultCode.
10:38:05.506 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:20518606,ID:00000000013916ce93aefd7e8696e98338b41c20acdb7795e4a016b353533e44 failed.
11:38:00.517 ERROR [TronJClientWorker-2] [net](MessageQueue.java:172) Fail send to /81.169.138.153:18888, type: SYNC_BLOCK_CHAIN
11:38:17.291 ERROR [TronJClientWorker-2] [net](MessageQueue.java:172) Fail send to /84.239.4.57:18888, type: SYNC_BLOCK_CHAIN
11:38:17.294 ERROR [TronJClientWorker-3] [net](MessageQueue.java:172) Fail send to /46.4.80.152:18888, type: SYNC_BLOCK_CHAIN
11:38:38.127 ERROR [TronJClientWorker-0] [net](MessageQueue.java:172) Fail send to /18.229.43.112:18888, type: P2P_PING
11:38:52.965 ERROR [pool-42-thread-1] [DB](Manager.java:1142) Different resultCode
11:38:52.973 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:20518658,ID:000000000139170273b8d0004aa69a5dc4e55f1680d732cc631f669ff806bb95, reason: Different resultCode.
11:38:52.973 ERROR [pool-42-thread-1] [net](SyncService.java:264) Process sync block Num:20518658,ID:000000000139170273b8d0004aa69a5dc4e55f1680d732cc631f669ff806bb95 failed.

**Comment by guoquanwu** [comment]
You can check the `resultCode` in the logs. 
If it is caused by `TIMEOUT`, try to increase the `vm.maxTimeRatio` to a larger number(maybe 10.0 is ok?). 
If it is caused by other reasons,  maybe your database is corrupted, you can download the backups from this website: http://47.89.178.46/

**Comment by zhenghq** [comment]
> You can check the `resultCode` in the logs.
> If it is caused by `TIMEOUT`, try to increase the `vm.maxTimeRatio` to a larger number(maybe 10.0 is ok?).
> If it is caused by other reasons, maybe your database is corrupted, you can download the backups from this website: http://47.89.178.46/

每次重启全节点，块高度会发很小幅度的更新，会更新40个左右，但之后就不再更新。
将vm.maxTimeRatio调整为：10.0后，超时问题还在： SUCCESS, the resultCode in self: OUT_OF_TIME，如下日志, 

14:12:46.371 INFO  [pool-42-thread-1] [DB](Manager.java:1311) Retry result for tx id: 15e98ef6b6d8742f1e78e80b0eb3ccd3bd41bee8eb6bcba2374bbc4d0901ffe6, tx resultCode in receipt: OUT_OF_TIME
14:12:46.372 INFO  [pool-42-thread-1] [TransactionTrace](TransactionTrace.java:254) this tx id: 15e98ef6b6d8742f1e78e80b0eb3ccd3bd41bee8eb6bcba2374bbc4d0901ffe6, the resultCode in received block: SUCCESS, the resultCode in self: OUT_OF_TIME
14:12:46.374 ERROR [pool-42-thread-1] [DB](Manager.java:1142) Different resultCode
org.tron.core.exception.ReceiptCheckErrException: Different resultCode
14:12:46.378 ERROR [pool-42-thread-1] [net](TronNetDelegate.java:223) Process block failed, Num:20518582,ID:00000000013916b609e01e94ac17e86a51344602c2870d3355cb712a094151e2, reason: Different resultCode.
org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
Caused by: org.tron.core.exception.ReceiptCheckErrException: Different resultCode

**Comment by guoquanwu** [comment]
I think the CPU is not fast enough, maybe you should continue to increase the `vm.maxTimeRatio`

**Comment by zhenghq** [comment]
> I think the CPU is not fast enough, maybe you should continue to increase the `vm.maxTimeRatio`

增加到15.0，全节点可以正常工作了，谢谢！
