### ISSUE TITLE
How to transfer TRX?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3230]

**Comment by Alexliu007** [comment]
1.TRX transfer via API
(A) wallet/createtransaction
(B) wallet/easytransfer
(c) wallet/easytransferbyprivate
(d) tronWeb.transactionBuilder.sendTrx(to, amount, from, options)
(d) tronWeb.trx.sendTransaction()

2.TRX transfer via wallet or tronscan
