### ISSUE TITLE
How to transfer TRC10 Token?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3231]

**Comment by Alexliu007** [comment]
1.HTTP API :
               （a）wallet/transferasset
               （b）wallet/easytransferasset
                 (c)   wallet/easytransferassetbyprivate
                  TronWeb API:
                 (a)   tronWeb.transactionBuilder.sendTrx(to,amount,tokenID,from,options);
                 (b)   tronWeb.trx.sendToken();
  Wallet-cli:
                 (d)   TransferAsset [OwnerAddress] ToAddress AssertID Amount
2.TRX transfer via wallet or tronscan
