### ISSUE TITLE
How to transfer TRC20 Token?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3232]

**Comment by Alexliu007** [comment]
a）HTTP API 

                            wallet/triggersmartcontract

                            curl -X POST https://api.shasta.trongrid.io/wallet/triggersmartcontract -d '{
                            "contract_address":"419E62BE7F4F103C36507CB2A753418791B1CDC182",
                            "function_selector":"transfer(address,uint256)",
                            "parameter":"00000000000000000000004115208EF33A926919ED270E2FA61367B2DA3753DA0000000000000000000000000000000000000000000000000000000000000032",
                            "fee_limit":100000000,
                            "call_value":0,
                            "owner_address":"41977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB"
                            }'

                      (b) Web API                           

                            const privateKey = "...";
                            const trc20ContractAddress = "TQQg4EL8o1BSeKJY4MJ8TB8XK7xufxFBvK"；//contract address
                            let contract = await tronWeb.contract().at(trc20ContractAddress);
                            
                            await contract.transfer(
                                  "TVDGp...", //address _to
                                  1000000 //amount
                           ).send({
                                  feeLimit = 1000000
                           }).then(output => {console.log('- Output:', output, '\n');});

                         (c) wallet-cli

                              TriggerContract TQQg4EL8o1BSeKJY4MJ8TB8XK7xufxFBvK transfer(address,uint256) "TBQDyqoJ2ZJHTRDsrGQasyqBm4nUVLbWee",100 false 100000000 0 0 #                            

              2. TRX transfer via wallet or tronscan

**Comment by yujianFresh** [comment]
> a）HTTP API
> 
> ```
>                         wallet/triggersmartcontract
> 
>                         curl -X POST https://api.shasta.trongrid.io/wallet/triggersmartcontract -d '{
>                         "contract_address":"419E62BE7F4F103C36507CB2A753418791B1CDC182",
>                         "function_selector":"transfer(address,uint256)",
>                         "parameter":"00000000000000000000004115208EF33A926919ED270E2FA61367B2DA3753DA0000000000000000000000000000000000000000000000000000000000000032",
>                         "fee_limit":100000000,
>                         "call_value":0,
>                         "owner_address":"41977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB"
>                         }'
> 
>                   (b) Web API                           
> 
>                         const privateKey = "...";
>                         const trc20ContractAddress = "TQQg4EL8o1BSeKJY4MJ8TB8XK7xufxFBvK"；//contract address
>                         let contract = await tronWeb.contract().at(trc20ContractAddress);
>                         
>                         await contract.transfer(
>                               "TVDGp...", //address _to
>                               1000000 //amount
>                        ).send({
>                               feeLimit = 1000000
>                        }).then(output => {console.log('- Output:', output, '\n');});
> 
>                      (c) wallet-cli
> 
>                           TriggerContract TQQg4EL8o1BSeKJY4MJ8TB8XK7xufxFBvK transfer(address,uint256) "TBQDyqoJ2ZJHTRDsrGQasyqBm4nUVLbWee",100 false 100000000 0 0 #                            
> 
>           2. TRX transfer via wallet or tronscan
> ```

TRC20 transfer ,can you provider a java sign demo, how to sign TriggerContract ?
