### ISSUE TITLE
class org.tron.common.runtime.vm.program.Program$OutOfTimeException : CPU timeout for 'PUSH1' operation executing

### ISSUE THREAD

**Issue by niulingyun** [tronprotocol/java-tron#3233]
### 1. What did you do?
通过智能合约批量查询地址的余额
### 2. What did you expect to see?
正常余额列表
### 3. What did you see instead?
偶尔报错

复现代码：

~~~js
           let contract = req.body.contract
            let addresses = JSON.parse(req.body.addresses)

            if (contract === undefined) {
                contract = ""
            }

            let data = {}
            let instance = await client.contract().at("TLXr3z8kbRBVtvjbRyPcWkAb4EyTErorgA")

            if (!contract) { //trx
                let balances = await instance.balances(addresses).call()
                for (let i = 0; i < addresses.length; i++) {
                    data[addresses[i]] = balances[i].toString()
                }
      
            } else if (contract.length === 34) {
                let balances = await instance.trc20Balances(addresses, contract).call()
                for (let i = 0; i < addresses.length; i++) {
                    data[addresses[i]] = balances[i].toString()
                }

            } else { //trc10
                let tokenID = tronWeb.toUtf8(contract)
                let balances = await instance.trc10Balances(addresses, tokenID).call()
                for (let i = 0; i < addresses.length; i++) {
                    data[addresses[i]] = balances[i].toString()
                }
            }
console.log(data)
~~~

**Comment by Benson0224** [comment]
can you please share with us the error message?

**Comment by niulingyun** [comment]
class org.tron.common.runtime.vm.program.Program$OutOfTimeException : CPU timeout for 'XXX' operation executing

**Comment by Benson0224** [comment]
The contract execution time is too long, The maximum contract execution time is 50ms.
Usually, timeout issues have 2 reasons. 1. The smart contract is too complex. 2. The fullnode  performance is poor(for example,  the fullnode is also running other services which caused performance issue. )

here is the suggestion: 
1. When writing smart contracts, Keep the execution as simple as possible, do not do long loops in smart contracts.
2.It is also recommended to set feelimit smaller to reduce losses. 

you can also get more details here : https://cn.developers.tron.network/docs/faq

**Comment by Benson0224** [comment]
> class org.tron.common.runtime.vm.program.Program$OutOfTimeException : CPU timeout for 'XXX' operation executing

We will close this issue if you don't have further questions.
