### ISSUE TITLE
Negative bandwidth after unfreeze amount

### ISSUE THREAD

**Issue by aghamir** [tronprotocol/java-tron#3240]
### 1. What did you do?
I freezed some amount in my wallet using `/wallet/freezebalance`. Then after one week, I unfreeze them using `/wallet/unfreezebalance`.

### 2. What did you expect to see?
I expect to see that my bandwidth is zero or positive amount after unfreezing.

### 3. What did you see instead?
My bandwidth is negative amount. After freezing again this goes to previous amount before unfreezing.

**Comment by cathy-lishipu** [comment]
Which node and api are you using?You may provide the address that can be helpful for us to locate the problem.

**Comment by aghamir** [comment]
Dear @cathy-lishipu ,
I used [tron-api-python](https://github.com/iexbase/tron-api-python/) which is a wrapper for python and using this java api at the end(I just used the request wrapper and urls are provided in my previous comment). And the node address is https://api.trongrid.io/. This is the bandwidth after I unfreeze the balance(TScb1PvfJbQp2ULjcAXcHsow3uJirQ6ffM):
![photo_2020-06-28_20-02-17](https://user-images.githubusercontent.com/1880925/85951764-7f3bde00-b97a-11ea-9e37-5c069f94f296.jpg)

**Comment by cathy-lishipu** [comment]
Hello, I checked it and now your bandwidth is positive amount, so please check it again.

**Comment by aghamir** [comment]
Thanks a lot cathy. I will check it after unfreezing again. I forced to freeze it again to avoid negative bandwidth. BTW, why there is negative amount resource in that moment? Is this a thing related to tron protocol or is it overflow because of the amount freeze?

**Comment by sean-liu55** [comment]
@aghamir,  the remaining value in your screenshot is equaled to the bandwidth you have minus the bandwidth you used. Because you unfreeze balance, so the bandwidth you have become zero, while the used bandwidth is the same, so the value becomes negative. In addition, the used bandwidth will decrease to zero after 24h.
