### ISSUE TITLE
how to get the source code of the trc20 smart contract?

### ISSUE THREAD

**Issue by 1971192997** [tronprotocol/java-tron#3245]
### 1. What did you do?

 get the source code of of trc20 smart contract

### 2. What did you expect to see?

get the source code of of trc20 smart contract

**Comment by 1971192997** [comment]
你好：
      请问怎样获取trc20只能合约的源码？

**Comment by cathy-lishipu** [comment]
You can refer to this link: https://github.com/tronprotocol/tron-contracts/tree/master/contracts/tokens/TRC20

**Comment by 1971192997** [comment]
thanks.
