### ISSUE TITLE
When broadcast the transaction, return SERVER_BUSY error?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3259]

**Comment by Alexliu007** [comment]
When the node broadcasts the transaction, the number of transactions in pending of mempool is greater than 2000, which will trigger this situation.

1. Check whether there are a large number of transactions during this time period, such as airdrop.

2. Check the network status of the node to see if the network status is not good, resulting in a backlog of pending list.

The transaction is now kept in pending for up to 1 minute. When the threshold is exceeded, the transaction is completely deleted from pending. After server_busy appears, it can be automatically restored, just try the interface after a while.
