### ISSUE TITLE
When broadcasting a transaction, return DUP_TRANSACTION_ERROR error ?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3260]

**Comment by Alexliu007** [comment]
The transaction is repeatedly broadcast, the transaction is broadcast to node A for the first time, node A will be cached first (may not be recorded on the chain), the transaction is broadcast to node A again, it will report DUP_TRANSACTION_ERROR, you can change the node or resend one Just transaction. 
If there is no error in the first broadcast, it is best to wait until the expiration time of the transaction has passed.
