### ISSUE TITLE
When broadcasting transaction, return Tapos check error?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3261]

**Comment by Alexliu007** [comment]
1. If the transaction is generated through the API, modify the configuration file config.conf: trx.reference.block = "solid".

2. If it is a transaction constructed by yourself, you need to check whether the reference block of the transaction is new enough or will be rolled back.

Every legal transaction needs to have a block that has existed on the chain for a certain period of time as a reference block (TaPOS). If the block used as a reference block when you create a transaction is rolled back or not new enough, TaPOS verification failure will occur , "Solid" refers to the confirmed block as the reference block, and "head" uses the latest block
