### ISSUE TITLE
Alternative to /walletextension/gettransactionstothis

### ISSUE THREAD

**Issue by aghamir** [tronprotocol/java-tron#3264]
Dear devs,

I don't see any alternative api in fullnode to get transactions of an account. Which api we must use to migrate from deprecated solidity apis?

**Comment by zyumingfit** [comment]
Use the strongrid interface as an alternative: https://developers.tron.network/reference#transaction -information-by-account-address

**Comment by aghamir** [comment]
Hi @zyumingfit ,
Unfortunately this interface returns the information of an account with delay(I think there is a cache system for normal request). BTW, thanks for your imformation.
