### ISSUE TITLE
I tried to transfer trc10 failed with “call” method in the smart contract

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3273]
### 2. What did you expect to see?
The transaction is in success state, but the transfer did not happen.
https://nile.tronscan.org/#/transaction/dcdd3067835b967b1101513f3eef5147752572a728dc05be5c858d9b5318f546

**Comment by Alexliu007** [comment]
Call method in the smart contract does not support TRC10 transfer
