### ISSUE TITLE
After I update the token logo on tronscan, I cannot view the latest logo on tronlink?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3274]
### 1. What did you do?

After I update the token logo on tronscan, I cannot view the latest logo on tronlink?
https://tronscan.org/#/token20/TTqzqazGQgZW51zhJa321dpWAP1WwheE7P

**Comment by xueyafighting** [comment]
Regarding the update of LOGO, tronlink has a delay time of 1 hour, you can wait to check it after 1 hour.
