### ISSUE TITLE
Can I connect to the mainnet using trontools/quickstart?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3275]
### 1. What did you do?

Can I connect to the mainnet using trontools/quickstart?
https://github.com/TRON-US/docker-tron-quickstart/tree/b127a0846cfe4d8d20302b816c746749140bd3f1

**Comment by xueyafighting** [comment]
The purpose of it is to set up a complete private network for Tron development，so currently it does not support connecting to the main network.
