### ISSUE TITLE
TransactionLogTriggerCapsule logic optimization

### ISSUE THREAD

**Issue by heipacker** [tronprotocol/java-tron#3297]
can we add the analysis of triggersmartcontract in the constructor so that we can get his origin address for this class

**Comment by heipacker** [comment]
https://tronscan.org/#/transaction/847f6900d4be259bae3343100fa46a6e1bc9608e16e21fcb6448e86d28ace8bc

**Comment by heipacker** [comment]
you can see the transaction above, if i can get origin address of this transaction, so that i can known from and to address of this transaction

**Comment by heipacker** [comment]
https://github.com/TP-Lab/java-tron/tree/GreatVoyage-v4.0.0-kafka-plugin

We have made some customization in this branch, which can be used under git diff

**Comment by Starsakary** [comment]
You can make a pull request for us to review your contribution.

**Comment by Benson0224** [comment]
> https://github.com/TP-Lab/java-tron/tree/GreatVoyage-v4.0.0-kafka-plugin
> 
> We have made some customization in this branch, which can be used under git diff

could you please submit a PR to `develop` branch with your change?

**Comment by Benson0224** [comment]
Please submit PR if you think this is a must for you.  we will review the source code and progress there.  

Here is the guide on how to submit pr based on your branch. 
![image](https://user-images.githubusercontent.com/61768920/91516256-8e5cef00-e91d-11ea-9665-4d8d3194a242.png)

I will close this issue, please reopen it or submit a new issue if you have further questions. thanks.
