### ISSUE TITLE
There is no "is_sent" in gererated note.

### ISSUE THREAD

**Issue by yudonghoon** [tronprotocol/java-tron#3336]
There is no "is_sent" in Note. 
And when the generated note is read using IsShieldedTrc20ContractNoteSpent, it only returns null.

  in Nile

  block : 8139987
  shieldedAddress : TF3dXv29ASqxHraFP5ZtVnQYFqrDpVgp72 
  ivk : 217e129cb5729531f7b43c40eb458f37f27f53c4e7c99d44ccc1c286630b1a03
  nk : d6fde59e9fd28e960c0b5f15faea92e081c0ae54952877f37709a699ff4c678c
  nk : d6fde59e9fd28e960c0b5f15faea92e081c0ae54952877f37709a699ff4c678c

![image](https://user-images.githubusercontent.com/24370251/90043706-6eb3ad00-dd07-11ea-95c2-2db15b7ced09.png)

**Comment by andelf** [comment]
Refer: https://github.com/andelf/tronpy/blob/master/tronpy/contract.py#L564

This is a known issue when converting from protobuf to JSON when a value is default/zero in protobuf.

BTW: the `index` field is hardcoded in JSON convert logic, so you can get a `index=0` but will never get a `is_spent=False`.
