### ISSUE TITLE
How to convert between base58 address and hexstring address format?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3342]
### 1. What did you do?

How to convert between base58 address and hexstring address format?

**Comment by Alexliu007** [comment]
HexString and Base58check Transcode Demo

JAVA: GH tronprotocol/wallet-cli/src/main/java/org/tron/demo/TransactionSignDemo.java#L92

or you can use tronweb to convert address between base58 and hexstring. 

tronWeb.address.fromHex
Convert Hexstring format address to Base58 format address

tronWeb.address.toHex
Convert Base58 format addresses to Hex
