### ISSUE TITLE
Error: 'class org.tron.core.exception.ZksnarkException : build the shielded TRC-20 parameters error: param is null'

### ISSUE THREAD

**Issue by yudonghoon** [tronprotocol/java-tron#3346]
hello,

What does this error mean?

I am trying to send a token from address Z to address T using createshieldedcontractparameters (burn) but I always get the same error as title. Error: 'class org.tron.core.exception.ZksnarkException : build the shielded TRC-20 parameters error: param is null'
Is there anything I am missing?

Please help.

var request = require("request");

var options = {
  method: 'POST',
  url: 'https://api.nileex.io/wallet/createshieldedcontractparameters',
  headers: {'content-type': 'application/json'},
  body: {
          ask:"17ff31bc430d69272bb48c20abab53ba178f5f921286dfda1ac795879f74a809",
          nsk:"21878fe0fe551ceb4a9de036ed80fbf1aaf65ea3bdd0acc3560e856787f76f00",
          ovk:"3f65d05421db5f63794a46b7d1e8551ea52d7b2b5f2fe9b3a00ad715104c98ae",
          to_amount: "1000000",
          transparent_to_address:"418b7d0798988cf4c012fe493e5135f68504bafe8f",
          shielded_TRC20_contract_address:"4137aec56360c862781f60c47d7b118fa360a84734",
          shielded_spends:
          {
            note:{
            payment_address: "ztron1yahfg55muvwq7s0f5lht7vtzjgkmddfmcfxx64lltzge6gfxz4ft82vs2nfdk448l8ju6w8e92x",
            memo: "41",
            value: 1000,
            rcm: "582943e020d2eac61592313b59f65c405b10cbe83de83993e8391dbfcca5290d",
            },
            alpah: "574f795cf137e1343e15b8a2836258287ec1ce23f517288eb69e7e8b35e65703",
            root: "fcc0e0d8b707d08afd810836974e6dff7b2d40197d40e1034137c3aea9c62425",
            path: "b2eed031d4d6a4f02a097f80b54cc1541d4163c6b6f5971f88b6e41d35c5381412935f14b676509b81eb49ef25f39269ed72309238b4c145803544b646dca62de1f34b034d4a3cd28557e2907ebf990c918f64ecb50a94f01d6fda5ca5c7ef7228e7b841dcbc47cceb69d7cb8d94245fb7cb2ba3a7a6bc18f13f945f7dbd6e2aa5122c08ff9c161d9ca6fc462073396c7d7d38e8ee48cdb3bea7e2230134ed6ad2e1642c9a462229289e5b0e3b7f9008e0301cbb93385ee0e21da2545073cb5816d6252968971a83da8521d65382e61f0176646d771c91528e3276ee45383e4afee0e52802cb0c46b1eb4d376c62697f4759f6c8917fa352571202fd778fd7124c6937d78f42685f84b43ad3b7b00f81285662f85c6a68ef11d62ad1a3ee08500769557bc682b1bf308646fd0b22e648e8b9e98f57e29f5af40f6edb833e2c4908eeab0c13abd6069e6310197bf80f9c1ea6de78fd19cbae24d4a520e6cf30238d5fa43e5a10d11605ac7430ba1f5d81fb1b68d29a640405767749e8415276736aca8448d8263e547d5ff2950e2ed3839e998d31cbc6ac9fd57bc6002b159216cd1c8dbf6e3acc7a80439bc4962cf25b9dce7c896f3a5bd70803fc5a0e33cf006edb16d01907b759977d7650dad7e3ec049af1a3d875380b697c862c9ec5d51c1ea6675f9551eeb9dfaaa9247bc9858270d3d3a4c5afa7177a984d5ed1be2451d6acdedf95f608e09fa53fb43dcd0990475726c5131210c9e5caeab97f0e642fbd74b25aacb92378a871bf27d225cfc26baca344a1ea35fdd94510f3d157082c1b77dac4d24fb7258c3c528704c59430b630718bec486421837021cf75dab651ec677114c27206f5debc1c1ed66f95e2b1885da5b7be3d736b1de985794730484777c8776a3b1e69b73a62fa701fa4f7a6282d9aee2c7a6b82e7937d7081c23cba49b659fbd0b7334211ea6a9d9df185c757e70aa81da562fb912b84f49bce7243ff5457f13b926b61df552d4e402ee6dc1463f99a535f9a713439264d5b616b7b99abdc3730991cc9274727d7d82d28cb794edbc7034b4f0053ff7c4b680444d6c639ac24b46bd19341c91b13fdcab31581ddaf7f1411336a271f3d0aa528138ac9cf9c391e3fd42891d27238a81a8a5c1d3a72b1bcbea8cf44a58ce7389613912d82b2c2bca231f71efcf61737fbf0a08befa0416215aeef53e8bb6d23390ae110de65c907b9dea4ae0bd83a4b0a51bea175646a64c12b4c9f931b2cb31b49e4c7ba8d7cbc57be9ae71191c878d96267764457ae630035cbea42d61f86e056db541e5049763dd80fbd7f47491415d75d2e096641b5fc2ab07cd76303f3de26817de36ab2d57feb077634bca77819c8e0bd298c04f6fed0e6a83cc1356ca1558600f0194c3d01ec839879921bde4320923f64b5e4f735d1111b118ef7aeb141",
            pos: 13,
          }
        },
  json: true
};

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});

**Comment by KI5FPL** [comment]
A typo, `alpah` => `alpha`.
