### ISSUE TITLE
i want to translate the tron website for Iranians 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [tronprotocol/java-tron#335]
please provide a way for translation for other languages especially for Persian Language 

in Iran a lot  of people are following tron coin news and like to invest on it   

my gmail :  physitime@gmail.com

and we have a great telegram group with 6500 members that are talking about tron coin 

@zhaohong

**Comment by ybhgenius** [comment]
Hello,

Thanks for your participation.

Please check this link: 

https://crowdin.com/project/trondocs

You can translate or correct relevant texts through this link.

We will reward you according to your contribution.

Best Regards

Boheng Yang

**Comment by Rovak** [comment]
Closing this issue as translations are now being done through Crowdin. Follow the link above to contribute your translations.
