### ISSUE TITLE
trx

### ISSUE THREAD

**Issue by yzn5555** [tronprotocol/java-tron#3354]

**Comment by yzn5555** [comment]
trx区块同步停止在：2020-08-11 15:06:32
后台查询trx程序正常，不知道为什么通过http://IP:8090/wallet/getnowblock获取到区块高度信息：停在：22286076 不动了

**Comment by Starsakary** [comment]
You can provide the log to check the error details.

**Comment by Benson0224** [comment]
is the issue still exist?  
We will close this issue in 3 days if no new comments. 
Please reopen it if you still see the issue. thanks.
