### ISSUE TITLE
"transaction expired" happened when sending a transaction 

### ISSUE THREAD

**Issue by readygo586** [tronprotocol/java-tron#3360]
### 1. What did you do?
 After Create a TRX Tx，and send it after sleep  60s,  "transaction expired" exception will happen.
using "https://github.com/fbsobreira/gotron-sdk" as lib.

`	
rawTx, err := grpcClient.Transfer("TYbcQrwHHjcd3n4pKGkxmCnjtw3nPoBs8b", "TRGvtQpC8cpk1ksbwLn7xr5DK7aYZgmWcA", 10000000)
	require.Nil(t, err)

	signature1, err := crypto.Sign(rawTx.GetTxid(), (*ecdsa.PrivateKey)(priv))
	require.Nil(t, err)

	rawTx.GetTransaction().Signature = append(rawTx.GetTransaction().Signature, signature1)

	//interval = 20s
	t.Logf("sleep 60 seconds")
	time.Sleep(time.Duration(time.Second * 60))
	_, err = grpcClient.Broadcast(rawTx.GetTransaction())
	require.Nil(t, err)

	time.Sleep(time.Second * 5)
	_, err = grpcClient.GetTransactionByID(hex.EncodeToString(rawTx.GetTxid()))
	require.Nil(t, err)
`
### 2. What did you expect to see?
Transaction is sent successfully.

### 3. What did you see instead?
exception hasppens.

**Comment by Benson0224** [comment]
The transaction must be broadcasted within 60s after it was created, otherwise, it will expire.
in this case, you can try to sleep 30 seconds or sleep after broadcasting the transaction.

**Comment by readygo586** [comment]
@Benson0224.
Very thanks for your clear answer.
