### ISSUE TITLE
Build Failed in Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by WendySanarwanto** [tronprotocol/java-tron#337]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
When I followed instruction on `README.md` file for building the source by running `./gradlew build`, the build process was ended as __BUILD FAILED__

2. What did you expect to see?
The build process should be ended as successful.

3. What did you see instead?
![image](https://user-images.githubusercontent.com/18456618/38158972-b98d7d46-34d1-11e8-8143-0e9fbee8a939.png)

My environment settings:
![image](https://user-images.githubusercontent.com/18456618/38158974-d84f2b62-34d1-11e8-9d1b-45d5c0c88c7d.png)

**Comment by AydenRennaker** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

Install the 1.8 jdk its a dependency issue the error comes from a function that has been deprecated in the latest java version.

**Comment by WendySanarwanto** [comment]
Hi @AydenRennaker,

I've followed your suggestion by installing `Oracle JDK 8`, replacing my `OpenJDK 8`, and then re-ran the build. The build's outcome is `SUCCESS`. I will edit the `README.md` file to tell the reader that they should use `Oracle JDK 8` over `OpenJDK 8` so that they won't get failing build.

Cheers.

**Comment by lacasseio** [comment]
I suggest installing `openjfx` using `sudo apt-get install openjfx` instead of forcing users to install Oracle JDK 8 as the issue is related to missing JavaFX package. See https://stackoverflow.com/a/19529820.

**Comment by WendySanarwanto** [comment]
Hi @lacasseio ,

Thanks for your feedback. I will retest your suggestion and will get back with the result.

**Comment by vniche** [comment]
Real pain to work with Oracle JDK now as it always been, any new words on the dependency on it? I would really like to go for at least OpenJDK being officially supported...

**Comment by Nguyentiensy99** [comment]
Cảm ơn các bạn làm ơn thêm tên tôi OK nguyentiensy. Tôi không hiểu về công nghệ nên các bạn giúp đỡ cảm ơn nhiều nhiều

**Comment by gen2brain** [comment]
I managed to compile on Fedora with OpenJDK and OpenJFX, I just installed distro packages and build with the gradle. Just wanted to let you know Oracle JDK is not necessary.
Not related to Ubuntu though, sorry, just think this info can be useful to someone else.

**Comment by fahrinh** [comment]
Or you could use `zulu-javafx` with [asdf](https://asdf-vm.com/)
1. `asdf install java zulu-javafx-8.58.0.13`
2. `asdf global java zulu-javafx-8.58.0.13`
3. `./gradlew build`
