### ISSUE TITLE
I have a question regarding shielded trc20. (Z to Z / transfer function)

### ISSUE THREAD

**Issue by yudonghoon** [tronprotocol/java-tron#3375]
Hello.

I have a question regarding shielded trc20. I have confirmed that sending from T  to Z and sending from Z to T work normally. 
But sending from Z to Z is always reverted. Anyone can help?
Thanks in advance.

in nile server.

export const CONTRACT = {
  TRC20: "TP2tdyBx5RacoVu1fTatdJnqEADs8KgcoR",
  SHIELDED: {
    address:"TGs4tQ8R2jCCLTZLj7kyS6c7h3QPpKZHm1",
    addressHex:"414B9F9C5DD94503DAAA28AA05522F2C46C6139FF6",
    gain:1000000
  }
}

1.
![image](https://user-images.githubusercontent.com/24370251/91661031-77342200-eb14-11ea-889a-bc35a61c5a8e.png)
2.
![image](https://user-images.githubusercontent.com/24370251/91661051-9763e100-eb14-11ea-9b9c-82a367794b6a.png)
3.
![image](https://user-images.githubusercontent.com/24370251/91661077-c712e900-eb14-11ea-9c8b-0ca3f8bd7e94.png)
4.
![image](https://user-images.githubusercontent.com/24370251/91661111-d5f99b80-eb14-11ea-8a1d-ef21aa877152.png)

**Comment by Benson0224** [comment]
can you transfer 10000 trc20 token to "TGJsr9WzLnVrTXwnT7up3646SqxmT9wEXM",  We will try your contract. thanks.

**Comment by yudonghoon** [comment]
> can you transfer 10000 trc20 token to "TGJsr9WzLnVrTXwnT7up3646SqxmT9wEXM", We will try your contract. thanks.
I just sent it. Thank you.

**Comment by Benson0224** [comment]
just tried, everything works fine:  
mint: https://nile.tronscan.org/?_ga=2.32463358.1918206889.1598353678-2035861273.1597993699#/transaction/fa4715c2dfdd5a834834d0a39b7b797104417ebc0989cc47d802486d3983a036

Transfer (from shielded Address to shielded Address): https://nile.tronscan.org/?_ga=2.32463358.1918206889.1598353678-2035861273.1597993699#/transaction/2f7e91d80e0dea35012b238138f33f5dcdb1737802e9f1484843b5ff91977dad

**Comment by yudonghoon** [comment]
> just tried, everything works fine:
> mint: https://nile.tronscan.org/?_ga=2.32463358.1918206889.1598353678-2035861273.1597993699#/transaction/fa4715c2dfdd5a834834d0a39b7b797104417ebc0989cc47d802486d3983a036
> 
> Transfer (from shielded Address to shielded Address): https://nile.tronscan.org/?_ga=2.32463358.1918206889.1598353678-2035861273.1597993699#/transaction/2f7e91d80e0dea35012b238138f33f5dcdb1737802e9f1484843b5ff91977dad

thank you for checking. i will try to check my code again
