### ISSUE TITLE
Contribution Winners of August is Published! 

### ISSUE THREAD

**Issue by Benson0224** [tronprotocol/java-tron#3377]
Dear developers,

Our Community Developers Incentives Program has been on its eighth month of 2020.
Thanks to every developer who contributes to our project.

By the end of the 31 August, 2020, the winners are:
NO.1 @EleanoraJo 
NO.2 @KI5FPL, @paoerpaul, @AlexeyAkhunov-star, @DisneyFairiesFly, @kaiserlinda, @BentoCrypto, @niuniublockchain

Congratulation! The reward will be sent in the form of USDT ASAP.

Please claim your reward by emailing your TRC-20 USDT address to coredevs@tron.network through the email you used to contribute to our project before the end of 10 September, 2020.

For those developers who have not won, keep your chin up! The points gap is very small, so continue to earn points, then next month reward may hit you.

For more information, please refer to:
https://tronprotocol.github.io/documentation-en/developers/incentives/
https://tronscan.org/#/developersreward

**Comment by jiangyy0824** [comment]
All rewards have been distributed, please check your balance. Please respond to any questions on the issue.
