### ISSUE TITLE
How to solve the display error CONTRACT_VALIDATE_ERROR when using the local node to query the TRC20 balance？

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3385]
### 1. What did you do?

How to solve the display error CONTRACT_VALIDATE_ERROR when using the local node to query the TRC20 balance？
{"code":"CONTRACT_VALIDATE_ERROR","message":"this node does not support constant"}}

**Comment by Alexliu007** [comment]
Need to modify the node configuration file vm.supportConstant = true

**Comment by Benson0224** [comment]
closed as the answer is clear

**Comment by yujianFresh** [comment]
> closed as the answer is clear

hi, i get the same wrong message , and my node already set vm.supportConstant = true, and restart java-tron .
so how can i do to resolve this question ?
