### ISSUE TITLE
Someone that has been revoking my transfers

### ISSUE THREAD

**Issue by olayizzy** [tronprotocol/java-tron#3387]

**Comment by Benson0224** [comment]
Can you share the full name of the wallet app you used?

**Comment by olayizzy** [comment]
TRON WALLET

**Comment by Benson0224** [comment]
> TRON WALLET

can you share the app link?

**Comment by Benson0224** [comment]
We will close this issue now as no feedback for more than 7 days. 

Please re-open this issue(or report a new one) if you still see the same issue.
