### ISSUE TITLE
how to sign rawtransaction by java,wallet-cli can not import by maven 

### ISSUE THREAD

**Issue by yujianFresh** [tronprotocol/java-tron#3395]
### 2. What did you expect to see?

i want a java sdk demo for sign transaction ,  maven project is for good.

**Comment by Benson0224** [comment]
FYI:
java: https://developers.tron.network/docs/transaction#signing-the-transaction
python & javascript: https://andelf.gitbook.io/tron/tron-by-example/transfer-trc20

**Comment by Benson0224** [comment]
We will close this issue, please re-open it if you still see this issue.
