### ISSUE TITLE
How to use the transferFrom method in USDT？

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3399]
### 1. What did you do?

How to use the transferFrom method in USDT？

**Comment by Alexliu007** [comment]
This method needs to be combined with the approve to be used. For example, account A has 1000 USDT, and you want to allow account B to call 100 USDT at will. The A account calls the approve function approve (B address, 100) in the following form. When the B account wants to use 10 of the 100 TRC20 to the C account, the B account calls transferFrom (A, C, 10).

**Comment by bungfut** [comment]
> ### 1. What did you do?
> How to use the transferFrom method in USDT？
> 
> ### 2. What did you expect to see?
> ### 3. What did you see instead?

https://github.com/tronprotocol/java-tron/issues/3399#issue-700596283
