### ISSUE TITLE
How to understand the return of revert error when calling the contract?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3407]
### 1. What did you do?

How to understand the return of revert error when calling the contract?

**Comment by Alexliu007** [comment]
The following conditions generate a require-style exception, which throws a revert error, and only consume the already consumed energy, excluding the unconsumed energy.  
Details you can see this document~
 https://developers.tron.network/docs/vm-exception

**Comment by 1337SEnergy** [comment]
@Alexliu007 I assume he is asking how to read the actual message in the exception, e.g.

```solidity
uint256 x = 2;
require(x >= 3, "x less than 3");
```
would result in a failed TX, but the message "x less than 3" is nowhere to be found on the tronscan

I'd also like to know how to properly read these, as error messages are quite important for both, the developer and user
