### ISSUE TITLE
How to solve tronbox compilation error? （error Tronbox supports only the following versions）

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3408]
### 1. What did you do?

How to solve tronbox compilation error? （error Tronbox supports only the following versions）

**Comment by Alexliu007** [comment]
Check if the compiler version is written in the tronbox.js configuration. 
https://developers.tron.network/docs/tron-box-contract-deployment

**Comment by bungfut** [comment]
4168f224ffb38b566867d20f76469d8979b8d808

**Comment by bungfut** [comment]
https://github.com/settings/tokens/386847019
