### ISSUE TITLE
> @yujianFresh 不需要从创世块同步， 建议仔细核实一下 配置文件是否正确， 查看一下是否所有的fullnode.jar的进程都结束掉了，然后在重新启动。0000000001654dd35ca94ac89b064c3bd6f6e5353b842ee913667138c38fb0bf

### ISSUE THREAD

**Issue by bungfut** [tronprotocol/java-tron#3409]
> @yujianFresh 不需要从创世块同步， 建议仔细核实一下 配置文件是否正确， 查看一下是否所有的fullnode.jar的进程都结束掉了，然后在重新启动。
> 
> 目前从你节点返回的信息看， supportConstant 确实是false。
> curl --request POST --url http://47.108.48.70:8090/wallet/getnodeinfo
> ![image](https://user-images.githubusercontent.com/61768920/93552517-3311a000-f9a3-11ea-9b66-52451572aa13.png)

确实是我没有把java-tron的进程杀死，导致配置没有生效，谢啦

_Originally posted by @yujianFresh in https://github.com/tronprotocol/java-tron/issues/3402#issuecomment-695214114_

**Comment by yujianFresh** [comment]
ok,确实是我没有杀死进程导致的，不需要重启

**Comment by Benson0224** [comment]
We will close this issue as the issue is solved now, please start a new issue if you still see issues. thanks.
