### ISSUE TITLE
I can't open my TronWallet to login?

### ISSUE THREAD

**Issue by bavaria88** [tronprotocol/java-tron#3433]
### 1. What did you do?

I tap on my TronWallet app, I entered my Pin#, I clicked the agreement, and I clicked to restore my wallet but I could no longer proceed...

### 2. What did you expect to see?
I want to login in my TronWallet in order to add funds in a new site.

### 3. What did you see instead?
I could no longer logged in. I need your support, thank you.

**Comment by Benson0224** [comment]
please share the link of the wallet app,

**Comment by Benson0224** [comment]
close this issue due to no response, feel free to re-open it.

**Comment by bavaria88** [comment]
https://tronwallet.com?ref=TW4dcjAZixNYdSEbsD9RX6m6tqGNEXviZq

https://tronscan.org/#/address/TW4dcjAZixNYdSEbsD9RX6m6tqGNEXviZq/transactions

**Comment by bavaria88** [comment]
Dear sir, Benson,

Good morning!

Herewith, I want to inform you that I uninstalled and installed my TronWallet App, when I clicked the TronWallet App, I wrote my Pin Number, I couldn't click, CONTINUE, just automatically proceed to TronWallet App Logo!

Your utmost support regarding this matter is greatly appreciated, thank you,

Best regards!
