### ISSUE TITLE
how to prevent contract from directly receiving TRX?

### ISSUE THREAD

**Issue by 1337SEnergy** [tronprotocol/java-tron#3434]
alright, I have read up all about how TRON was designed not to call smart contract's fallback functions when sending TRX directly with .send or .transfer or w/e tronLink uses (for some reason, I think it was terrible decision but w/e), however I have no idea how to actually prevent this, so user's TRX are not lost when he sends them to the contract directly...

I tried this
```solidity
pragma solidity ^0.5.9;

contract Test
{
    function() external payable
    { require(false); }
}
```
but this, since TVM is not called, does not do anything at all, and the TRX sent to the contract are lost there forever anyway... how to prevent this?

**Comment by KI5FPL** [comment]
In short: **There's no solution to this**.

In detail:

There was a proposal parameter named `ForbidTransferToContract` to solve this. But the proposal is a design flaw and never gets passed. (It breaks many old DApps).

To Solve This, A new proposal should be set up:

- Add a `forbid_direct_transfer` field to every SmartContract
- `forbid_direct_transfer` defaults to `0`, so it won't break old DApps
- Owner of a smart contract can update the setting to `1` to forbid all direct transfer to the smart contract
- Smart contract created by factory smart contract will inherit this setting

**Comment by Benson0224** [comment]
We will close this issue, Please feel free to re-open it if you still face this issue.
