### ISSUE TITLE
api param visible=true error

### ISSUE THREAD

**Issue by shixiaofeia** [tronprotocol/java-tron#3438]
### 1. What did you do?

curl -X POST“ 34.220.77.106:8090/wallet/getblockbynum” -H“ Content-Type：application / json” --data'{“ num”：20181145，“ visible”：true}'  

### 2. What did you see instead?

{"Error":"class com.alibaba.fastjson.JSONException : unclosed string : :"}

### 3. What did you expect to see?

I have seen this problem mentioned by others before, but it has not been resolved until now. I want to know if this interface does not support visible parameters? In other words, can all interfaces with this parameter have this problem?

**Comment by Benson0224** [comment]
Please pay attention to the format of your command.  especially the ”,  at least do not use Chinese "(不要使用中文的双引号，另外--data 后面也缺少空格，)
At least it works on my PC. check the below result. 

`curl -X POST  http://34.220.77.106:8090/wallet/getblockbynum -d '{"num":20181145}' `

![image](https://user-images.githubusercontent.com/61768920/95809969-87116980-0d42-11eb-9589-1ccd024fd7f7.png)

**Comment by shixiaofeia** [comment]
> Please pay attention to the format of your command. especially the ”, at least do not use Chinese "(不要使用中文的双引号，另外--data 后面也缺少空格，)
> At least it works on my PC. check the below result.
> 
> `curl -X POST http://34.220.77.106:8090/wallet/getblockbynum -d '{"num":20181145}' `
> 
> ![image](https://user-images.githubusercontent.com/61768920/95809969-87116980-0d42-11eb-9589-1ccd024fd7f7.png)

请看清楚我的问题, 加上参数 visible=true 后会引发此异常

**Comment by shydesky** [comment]
@shixiaofeia  yes. This is a known bug. we will fix it asap. Thank you.
The "visible" is a high-level parameter that is used to return the base58check format type address. All the interfaces should support the visible parameters. But right now, please avoid using it in the `getblockbynum` API.

**Comment by shixiaofeia** [comment]
I see this issue is mentioned in issuse 2587. In October 2019, I want to confirm whether there is a clear recovery plan. Currently, I have disabled this parameter

**Comment by shydesky** [comment]
> I see this issue is mentioned in issuse 2587. In October 2019, I want to confirm whether there is a clear recovery plan. Currently, I have disabled this parameter

yes. this bug is fixed right now. It will be released in the  4.1 version, maybe November this year.

**Comment by shixiaofeia** [comment]
Ok, thanks
