### ISSUE TITLE
FullNode.jar and Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by mitGen** [tronprotocol/java-tron#3445]
I want to use the connection through my node on the front. I run my node on the ovh server with this command:

"nohup java -Xmx24g -XX:+HeapDumpOnOutOfMemoryError -jar FullNode.jar -c main_net_config.conf </dev/null &>/dev/null &"

But from the front I can not connect to my node, swears at Access-Control-Allow-Origin.

How can I start a node so that I can connect from the front ????????

**Comment by Benson0224** [comment]
Please try bellow command to see whether you have correct responce. 

`curl -X POST  https://YOURNODEIP:PORT/walle/getnowblock`

**Comment by Benson0224** [comment]
This is a missing feature, will be added in the future.
For now, an nginx proxy is needed to set up CORS.

**Comment by mitGen** [comment]
Thanks!!!

**Comment by liu212117** [comment]
```java
/**
 * @author liujh
 * @email littleliujh@gmail.com
 * @date 2020-12-07 15:15:04
 */
@Component
public class CorsInterceptor implements Filter {

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
    }

    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain)
            throws IOException, ServletException {
        HttpServletResponse response = (HttpServletResponse) servletResponse;
        response.setHeader("Access-Control-Allow-Origin", "*");
        response.setHeader("Access-Control-Allow-Methods", "*");
        response.setHeader("Access-Control-Max-Age", "3600");
        response.addHeader("Access-Control-Allow-Headers", "*");
        response.setHeader("Access-Control-Allow-Credentials", "*");
        filterChain.doFilter(servletRequest, servletResponse);
    }

    @Override
    public void destroy() {
    }
}
```
![image](https://user-images.githubusercontent.com/17373379/101599844-665d4b80-3a35-11eb-8cda-45f122d545b4.png)

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
We will close this issue as no update for a long time.
Please feel free to re-open this issue if you still see it, thanks.
