### ISSUE TITLE
Question: Witnesses Key

### ISSUE THREAD

**Issue by fbsobreira** [tronprotocol/java-tron#347]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
a. Create a wallet
b. get the private key
c. Create Witness
d. Vote for Witness
e. config resources/main/config.conf on java-tron project with the new private key
f. run: ./gradlew run -Pwitness=true

2. What did you expect to see?
run witnesses with success

3. What did you see instead?
- The private key must be 66-bits hex string
- The new create private key using the wallet-cli has only 64 hex strings

Should it be completed with zeros on the front? 
Is there any way to check the blocks generated by your node?

**Comment by romzes13** [comment]
Can confirm. I updated  my config.conf with new private key, tried to run gradlew, but it gave me an error "The private key must be 66-bits hex string"

**Comment by fbsobreira** [comment]
Yes, no problem creating and vote for witness on the wallet-cli or the tronscan.io
If I add "00" in the from of the private key for java-tron I get no error, but I don't know if this is the correct approach or if it will work on the network

**Comment by romzes13** [comment]
I can not create a Witness on tronscan.io, maybe because I haven't deposit any trx on it.
Thanks for the info. I'll try to add 00.

**Comment by zhaohong** [comment]
@fbsobreira  thanks for your feedback.    add "00" in the front of the private key can pass the check. we will fix this bug.
