### ISSUE TITLE
my problem trx.market 

### ISSUE THREAD

**Issue by kaankozan** [tronprotocol/java-tron#3477]
### 1. What did you do?
i sell on poloniex.org in coin WIN - LIVE - BNKR

### 2. What did you expect to see?
i want to see my transactions in page 
https://api.trx.market/api/exchange/user/order?uAddr=TSrqJQjonUGQqrNAtyM4RQTrHrtaHvicPe&start=0&limit=100
### 3. What did you see instead?
but my sell coin not see this page or poloniex.org

what this problems

my transactionss:
57f30d5e92fd5044119a7a38e8849f07eab3ce3f43b6b82bf67282f28b12d7ed

b650dc3c484aad95912ee3d19c6dc9e448ae78d81b67330af7d5770feb24f965

8d6a4f2942e40d2faecf2f51c08ca5484acb656e48bee7e0ab8b1f89d706cb21

**Comment by Benson0224** [comment]
Regarding Poloniex issue, I would suggest you check with Poloniex support team.

**Comment by kaankozan** [comment]
thank u
