### ISSUE TITLE
[Nile Testnet] CREATE2 function result has been changed

### ISSUE THREAD

**Issue by twilightrus** [tronprotocol/java-tron#3489]
CREATE2 function in Nile Testnet has different behavior in near releases. I think it was broken in [last release](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.1.0) ([Optimize TVM instruction CREATE2. #3351](https://github.com/tronprotocol/java-tron/pull/3351)).

Input Data:

Salt: 0
OwnerAddress: TNgaAP3PQtek9rGuJj6DJsWchJcCZmuHi4
ContractAddress: TE4U7S5YZ3tf79TNs8yNGkkbdn2s4wRSXh
Bytecode for CREATE2: `608060405234801561001057600080fd5b5060405161036a38038061036a8339818101604052602081101561003357600080fd5b50516001600160a01b038116156100dd57604080516370a0823160e01b8152306004820152905182916100db9132916001600160a01b038516916370a0823191602480820192602092909190829003018186803b15801561009357600080fd5b505afa1580156100a7573d6000803e3d6000fd5b505050506040513d60208110156100bd57600080fd5b50516001600160a01b03841691906100e0602090811b61000917901c565b505b32ff5b604080516001600160a01b038416602482015260448082018490528251808303909101815260649091019091526020810180516001600160e01b0390811663a9059cbb60e01b1790915261013691859161013b16565b505050565b610157826001600160a01b031661030360201b6100601760201c565b6101a8576040805162461bcd60e51b815260206004820152601f60248201527f5361666545524332303a2063616c6c20746f206e6f6e2d636f6e747261637400604482015290519081900360640190fd5b60006060836001600160a01b0316836040518082805190602001908083835b602083106101e65780518252601f1990920191602091820191016101c7565b6001836020036101000a0380198251168184511680821785525050505050509050019150506000604051808303816000865af19150503d8060008114610248576040519150601f19603f3d011682016040523d82523d6000602084013e61024d565b606091505b5091509150816102a4576040805162461bcd60e51b815260206004820181905260248201527f5361666545524332303a206c6f772d6c6576656c2063616c6c206661696c6564604482015290519081900360640190fd5b8051156102fd578080602001905160208110156102c057600080fd5b50516102fd5760405162461bcd60e51b815260040180806020018281038252602a815260200180610340602a913960400191505060405180910390fd5b50505050565b6000813f7fc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a47081158015906103375750808214155b94935050505056fe5361666545524332303a204552433230206f7065726174696f6e20646964206e6f742073756363656564`

Before last release CREATE2 result:
TRjTvs2vGbjuuUC73rX1xmAsbdqkuPEagV

After last release CREATE2 result:
TPXdrEm3uyEvEe37CbwQ6cZUrsfP2ZNcry

I think that CREATE2 after last release for initial address takes contract address instead of owner address as it was before.

**Comment by KI5FPL** [comment]
Yes. FYI:

Before: https://github.com/tronprotocol/java-tron/blob/eb28e896e6/actuator/src/main/java/org/tron/core/vm/program/Program.java#L1307

Now: https://github.com/tronprotocol/java-tron/blob/4700d8179e75b7c5c38a093312e6fdeb7755e503/actuator/src/main/java/org/tron/core/vm/program/Program.java#L1455

**Comment by twilightrus** [comment]
This is a breaking change that affects my system. where could I find out about this?

**Comment by Benson0224** [comment]
KI5FPL is correct， just follow the latest implementation is oK.

**Comment by Benson0224** [comment]
We will close this issue now, please feel free to re-open it if you still face this  issue.
