### ISSUE TITLE
maven导入wallet-cli.jar

### ISSUE THREAD

**Issue by guang-guang** [tronprotocol/java-tron#3490]
maven导入wallet-cli.jar后
启动springboot提示错误：
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method consulServiceRegistry in org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistryAutoConfiguration required a bean of type 'com.ecwid.consul.v1.ConsulClient' that could not be found.

Action:

Consider defining a bean of type 'com.ecwid.consul.v1.ConsulClient' in your configuration.

**Comment by guang-guang** [comment]
![Uploading QQ截图20201108163922.png…]()

**Comment by Bamboo898** [comment]
不要直接导入这个jar，先下载tron-java，自己编译，然后把编译出来的jar包一个一个的导入到maven

**Comment by Benson0224** [comment]
we will close this issue now, feel free to re-open it if you still face this issue.

**Comment by laopaoer-wallet** [comment]
> 不要直接导入这个jar，先下载java-tron，自己编译，然后把编译出来的jar包一个一个的导入到maven

我也遇到同样问题啊,如何解决啊 兄弟

**Comment by xiaohuajian** [comment]
> 不要直接导入这个jar，先下载java-tron，自己编译，然后把编译出来的jar包一个一个的导入到maven

能指导一下吗？大佬，具体要怎么搞，想直接能用的
