### ISSUE TITLE
更新到4.1.0后，我的sdk无法获得最新的块，重启全节点后，发现取到的块高度发生回退现象，块高度比原先还要小

### ISSUE THREAD

**Issue by zhenghq** [tronprotocol/java-tron#3491]
### 1. What did you do?

我找了一部分日志，也没有发现一些很关键的信息，下面的信息显示了vm出现了halted
10:48:40.280 INFO  [pool-46-thread-1] [VM](Program.java:1098) minTimeRatio: 0.0, maxTimeRatio: 20.0, vm should end time in us: 12079657583777, vm now time in us: 12079660273190, vm start time in us: 12079656583777
10:48:40.280 INFO  [pool-46-thread-1] [VM](VM.java:1539) VM halted: [CPU timeout for 'SWAP1' operation executing]
10:48:40.281 INFO  [pool-46-thread-1] [VM](VMActuator.java:252) timeout: CPU timeout for 'SWAP1' operation executing
10:48:40.319 INFO  [pool-46-thread-1] [VM](VM.java:1539) VM halted: [Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]]
10:48:40.319 INFO  [pool-46-thread-1] [VM](VMActuator.java:266) runtime result is :Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]
10:48:46.401 INFO  [pool-46-thread-1] [VM](VM.java:1539) VM halted: [Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]]
10:48:46.402 INFO  [pool-46-thread-1] [VM](VMActuator.java:266) runtime result is :Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]

### 2. What did you expect to see?
我想知道下这会是问题造成的, 如何处理。

**Comment by shydesky** [comment]
这些日志数据都是正常的。如果你的节点不能正常同步，大部分原因是因为 Different result code， 你可以将日志文件删掉重启节点，停止同步之后将最新的完整日志上传。另外提供一下你的启动命令和机器配置。

**Comment by zhenghq** [comment]
> 这些日志数据都是正常的。如果你的节点不能正常同步，大部分原因是因为 Different result code， 你可以将日志文件删掉重启节点，停止同步之后将最新的完整日志上传。另外提供一下你的启动命令和机器配置。

```
java -Xms10g -Xmx10g -jar /data03/TraceNode/bin/FullNode-4.1.0.jar -c /data03/TraceNode/bin/../etc/config.conf -d /data03/TraceNode/bin/../output-directory
```
服务器：cpu 12核  内存：24G   

你指的是哪部分日志文件，是tron.log这个日志么？

**Comment by zhenghq** [comment]
我还有个疑问，这次同步延迟，我查看tron.log也没发现特别明显的报错信息，那如何才能确定全节点是正常工作。

**Comment by shydesky** [comment]
对，tron.log。
可以通过日志来看： tail -f logs/tron.log | grep pushBlock
也可以通过api访问   curl http://ip:8090/wallet/getnowblock
观察区块高度的变化。

zhenghq <notifications@github.com> 于2020年11月9日周一 下午3:34写道：

**Comment by zhenghq** [comment]
我增加了Java的内存，节点的同步也追上了

**Comment by Benson0224** [comment]
Feel free to open this issue if you still see it, now we will close this issue.
