### ISSUE TITLE
Feature request: pending trasaction query API

### ISSUE THREAD

**Issue by Cletitia** [tronprotocol/java-tron#3495]
### 1. What did you do?
Got _**server busy**_ when broadcasting.

This is caused by the node’s pending list is full.

I’d like to ask for a new function like in the Txpool of Etherrum that pending transactions can be queried somewhere.

**Comment by shydesky** [comment]
I think this is a useful feature. The client can determine the rate of sending transactions porperly according to the count of the pending list of transactions.

**Comment by Benson0224** [comment]
Close this issue as this feature is already included in the latest release. check detail at: https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.1.3
