### ISSUE TITLE
How to solve TAPOS_ERROR error?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3498]
### 1. What did you do?

How to solve TAPOS_ERROR error?When broadcasting transactions, always return this error “Code = TAPOS_ERROR Message = Tapos check error”

**Comment by Alexliu007** [comment]
Modify the configuration file: trx.reference.block = "solid"
Every legal transaction needs to have a block within a certain period of time on the chain as a reference (TaPOS). If the block used as a reference block when you create a transaction is rolled back or not new enough, TaPOS verification failure will occur. “solid ”refers to using the confirmed block as the reference block, and “head ”uses the latest block
