### ISSUE TITLE
How to automatically verify ownership by verifying the address as your name, partners name or rights to that address. then generating new recovery phrase or private key in cases of loosing it. Lol, there’s so many recovery phrases I have I don’t know which go to where lol 

### ISSUE THREAD

**Issue by busymaster55** [tronprotocol/java-tron#3503]

**Comment by busymaster55** [comment]
Lol, there’s so many recovery phrases I have I don’t know which go to where lol

**Comment by Benson0224** [comment]
Currently, it is not supported that recover the account via name, partner's name, or rights to that address.

**Comment by sunshine1620** [comment]
I can't make transaction after I recovery my trust wallet back

**Comment by sunshine1620** [comment]
My account has be press on watching address I can't make transaction after I recovery my trust wallet back

**Comment by Benson0224** [comment]
We will close this issue, please feel free to re-open it if you still face the issue.
