### ISSUE TITLE
TRON RPC API with NodeJS

### ISSUE THREAD

**Issue by wc-codebase** [tronprotocol/java-tron#3505]
### 1. What did you do?

Dear everyone
I am working on Tron for development of  exchange platform.
I downloaded fullnode.jar and full node history on my server then synchronize it.
### 2. What did you expect to see?
I am going to use RPC request to communicate with tron daemon.
I am working on NodeJS and I am looking for a example of RPC API.
I visited https://tronprotocol.github.io/documentation-en/api/rpc.
But there is no completed solution.
How can I use RPC API with NodeJS ?

**Comment by Benson0224** [comment]
Please check the google RPC JS guide, thanks.

**Comment by Benson0224** [comment]
We will close this issue now, feel free to re-open it if you still face this issue.
