### ISSUE TITLE
The key argument cannot be null

### ISSUE THREAD

**Issue by yan253319066** [tronprotocol/java-tron#3513]
![image](https://user-images.githubusercontent.com/37472467/99510385-fc1b3300-29c1-11eb-884d-1fb43a7b33c6.png)

 
wallet> CreateAccount TPB2n6Zqiwyn76h32q4enWqML3NdUmYbea
{
	"raw_data":{
		"contract":[
			{
				"parameter":{
					"value":{
						"owner_address":"TJ28g2UAP6ww77gfyxiZNjTZuBqWrXCjXq",
						"account_address":"TPB2n6Zqiwyn76h32q4enWqML3NdUmYbea"
					},
					"type_url":"type.googleapis.com/protocol.AccountCreateContract"
				},
				"type":"AccountCreateContract"
			}
		],
		"ref_block_bytes":"029f",
		"ref_block_hash":"35c068d2fe20b3c7",
		"expiration":1605690459000,
		"timestamp":1605690399304
	},
	"raw_data_hex":"0a02029f220835c068d2fe20b3c740f886f0d4dd2e5a6612640a32747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e4163636f756e74437265617465436f6e7472616374122e0a1541584ea42563952cc838d6085ad1bd71442f17ce0e12154190d617b43b6f282b29c411560b4448b0c05d45e170c8b4ecd4dd2e"
}
before sign transaction hex string is 0a84010a02029f220835c068d2fe20b3c740f886f0d4dd2e5a6612640a32747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e4163636f756e74437265617465436f6e7472616374122e0a1541584ea42563952cc838d6085ad1bd71442f17ce0e12154190d617b43b6f282b29c411560b4448b0c05d45e170c8b4ecd4dd2e
Please confirm and input your permission id, if input y or Y means default 0, other non-numeric characters will cancel transaction.
y
Please choose your key for sign.
The 1th keystore file name is UTC--2020-11-18T03-44-00.383000000Z--TT5VPTzaVRD6RNhVHQtiPMbLwDPMy1HjXX.json
The 2th keystore file name is UTC--2020-11-18T03-57-24.866000000Z--TBi86NoPiTbgWCTyVhkXEzRV2rJs4CEgyf.json
The 3th keystore file name is UTC--2020-11-18T06-45-36.581000000Z--TJ28g2UAP6ww77gfyxiZNjTZuBqWrXCjXq.json
Please choose between 1 and 3
3
Please input your password.
password: 
after sign transaction hex string is 0a84010a02029f220835c068d2fe20b3c740d5e292dfdd2e5a6612640a32747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e4163636f756e74437265617465436f6e7472616374122e0a1541584ea42563952cc838d6085ad1bd71442f17ce0e12154190d617b43b6f282b29c411560b4448b0c05d45e170c8b4ecd4dd2e1241355d21baecee778a9c8bba68bc44bd5b764726913600598940370914802197c97467263b28646061daf38934f905f5cd8bbcb44ee2dcf7dd191169b520ac086101
txid is 8511bc1be1629a6f9caab25eccb235278f6b970f796d894ff310d29c42b3354f
Code = OTHER_ERROR
Message = other error : The key argument cannot be null
CreateAccount failed !!
wallet>

**Comment by ngocbd** [comment]
Same error here 
```
08:45:40.190 ERROR [qtp1330447795-31] [o.t.c.Wallet](Wallet.java:563) Broadcast transaction 6813858876e9631ad98928907787c8d143300641031dbac6e2a375f44f56a73d failed, The key argument cannot be null.
```

**Comment by Benson0224** [comment]
are you on main net or testnet?

**Comment by yan253319066** [comment]
@Benson0224 private

**Comment by Benson0224** [comment]
can you please share your private network configuration file, thanks.

**Comment by ngocbd** [comment]
I known why Exception throw . Because in private network I rename 3 default wallet Zion , Sun and Blackhole .
We need to keep this name .

**Comment by yan253319066** [comment]
> I known why Exception throw . Because in private network I rename 3 default wallet Zion , Sun and Blackhole .
> We need to keep this name . @see https://github.com/tronprotocol/java-tron/blob/develop/chainbase/src/main/java/org/tron/core/store/AccountStore.java

thanks
