### ISSUE TITLE
rate limiter default config

### ISSUE THREAD

**Issue by heipacker** [tronprotocol/java-tron#3515]
### 1. What did you do?

If do not set, the "default strategy" is set.The "default startegy" is based on QpsRateLimiterAdapter, the qps is set as 10000.

### 2. What did you expect to see?

IRateLimiter rateLimiter = new DefaultBaseQqsAdapter("qps=10000");

### 3. What did you see instead?

IRateLimiter rateLimiter = new DefaultBaseQqsAdapter("qps=1000");

**Comment by Btcrabbit** [comment]
yes, the comment in the config file is wrong, we will fix it as soon as possible. Thanks for your reminding.

**Comment by Benson0224** [comment]
yes, the comment in the config file is wrong, we will fix it as soon as possible. Thanks for your reminding.

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
