### ISSUE TITLE
How to use "transferFrom" function of the TRC20 smart contract?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3516]
### 1. What did you do?

How to use "transferFrom" function of the TRC20 smart contract?

**Comment by Alexliu007** [comment]
This method needs to be combined with the approve to be used. For example, account A has 1000 USDT, and you want to allow account B to call 100 USDT at will. The A account calls the approve function approve (B address, 100) in the following form. When the B account wants to use 10 of the 100 TRC20 to the C account, the B account calls transferFrom (A, C, 10).
