### ISSUE TITLE
MAVEN 依赖不存在! com.github.tronprotocol:java-tron:v4.1.1

### ISSUE THREAD

**Issue by Bamboo898** [tronprotocol/java-tron#3519]
com.github.tronprotocol java-tron v4.1.1

**Comment by Benson0224** [comment]
Please feel free to re-open this issue if you still see it. we will close this issue as no update for a long time. 
The latest release is GreatVoyage-v4.1.3(Thales), check more detail at https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.1.3
