### ISSUE TITLE
get event result is empty

### ISSUE THREAD

**Issue by lzxm160** [tronprotocol/java-tron#3520]
### 1. What did you do?

use tronweb call this tronWeb.getEventResult or call api like this:
https://api.trongrid.io/v1/contracts/TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE/events?event_name=TokenPurchase

### 2. What did you expect to see?
the return's result is not empty

### 3. What did you see instead?
the returns like this:

`{"data":[{"block_number":25325976,"block_timestamp":1606305528000,"caller_contract_address":"TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE","contract_address":"TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE","event_index":7,"event_name":"TokenPurchase","result":{},"result_type":{},"transaction_id":"31900daba68e016a628291a33eda1eb77f762ad8c0f01a0a46094cc78e94a8aa","_unconfirmed":true}`

**Comment by joker-gdb** [comment]
The result field is the name and parameter information of the event. Because this contract has no abi on the chain, the result cannot be parsed

**Comment by Benson0224** [comment]
Thanks for your contribution to TRON network, since no reply in days, we will close this issue.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by Funarp** [comment]
> Thanks for your contribution to TRON network, since no reply in days, we will close this issue.
> 
> Please feel free to re-open it if you still see the issue, thanks.



> The result field is the name and parameter information of the event. Because this contract has no abi on the chain, the result cannot be parsed

I found this issue while I create a contract by a contract, it seems contract like this don't storage ABI on chain, so nodes, trongrid, or tronscan can not parse event correctly, so can i send abi too? or is there any way I can parse data by myself for events of contract by a contract?
