### ISSUE TITLE
How to solve the problem of insufficient energy? 

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3525]
### 1. What did you do?

How to solve the problem of insufficient energy?

**Comment by Alexliu007** [comment]
The NO.47 and NO.48 voting request of TRON network were officially approved at 2:00 25th Nov. 2020(SGT)：increase the resource cost of the TRON network. The unit price of energy and bandwidth will be increased from the original 10sun to 40sun,if trx is consumed directly, the cost is increased to 4x, if it consumes the resources obtained by freezing TRX, it will not be affected. Please increase the feelimit setting of the transaction according to your needs.
https://tronscan.org/#/proposal/47
https://tronscan.org/#/proposal/48

After this proposal takes effect，More DAPP developers will freeze TRX，the freezing of the whole network will be greatly improved, network will be more stable. The TRON network is still the lowest cost public chain, we believe that the TRON network will become more prosperous with the efforts of all communities.
