### ISSUE TITLE
Optimization of transfer contract

### ISSUE THREAD

**Issue by forfreeday** [tronprotocol/java-tron#3527]
### Transfer performance optimization

The performance of the transfer contract has room for improvement. Expect further performance improvements through optimization.Save account transfer time. 

The improvement contents are as follows:
| Project                                                  | Progress |
| -------------------------------------------------------- | -------- |
| Adapter gRPC HTTP                                        | 0%       |
| New account balance store                         | 100%     |
| Import data of account store to account balance store    | 100%     |
| Unit test                                        | 50%      |
| Testing phase                                     | 0%      |

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
