### ISSUE TITLE
🚀 A series of performance improvement plans

### ISSUE THREAD

**Issue by Yrp** [tronprotocol/java-tron#3528]
|Project|Issue|Description|Progess(%)|
|---|---|---|---|
|Optimization of transfer contract|#3527||60|
|High-frequency data caching|#3585|||
|Parallelization of validate and execute||||
|R/W Separation and R/W Parallelism||For database||
|Parallelization of pushTransaction and pushBlock||||
|Support JDK 11|#3542|ZGC||
|Optimization of process execution sequence||such as block execution and broadcast sequences||
|||||

**Comment by Yrp** [comment]
👏  Suggestions for improvement are welcome!

**Comment by andelf** [comment]
JDK 11 support is almost impossible. Java-tron should stay at JDK8.

See-also: https://github.com/opentron/opentron/issues/36

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
