### ISSUE TITLE
Different resultCode

### ISSUE THREAD

**Issue by StephanDre** [tronprotocol/java-tron#3530]
### 1. What did you do?

![image](https://user-images.githubusercontent.com/41446758/100603580-999d2d80-3305-11eb-9609-fd08fd3f20ea.png)

Node after restarting the computer does not want to synchronize, it stands on block no.25466632, I have had it a few times each time I downloaded a new database, but this is not the way I read about previous similar problems and changed maxTimeRatio to 20.0, but it does nothing

**Comment by andelf** [comment]
grep former ERROR logs and find what are the different resultCode.
If it is a `TIME_OUT`, changing `maxTimeRatio` solves.
In other cases, your local storage might be broken.

**Comment by Benson0224** [comment]
Thanks for your contribution to TRON network, since no reply in days, we will close this issue.

Please feel free to re-open it if you still see the issue, thanks.
