### ISSUE TITLE
Upgrade to JDK 11

### ISSUE THREAD

**Issue by Yrp** [tronprotocol/java-tron#3542]
JDK 11 support is almost impossible. Java-tron should stay at JDK8.

See-also: https://github.com/opentron/opentron/issues/36

_Originally posted by @andelf in https://github.com/tronprotocol/java-tron/issues/3528#issuecomment-734756153_

**Comment by Yrp** [comment]
👏  @andelf Hi, guys. Let's talk about JDK11 here.
1. Has it been tested on both Oracle JDK11 and OpenJDK11?
2. If the difference is only in floating-point numbers, is it possible to solve the problem by porting the JDK8 code to JDK11 to customize the JDK11?
3. Or fix the problem by plugging in the JNI library.

**Comment by andelf** [comment]
Assembly code solves.

https://github.com/opentron/opentron/commit/6e6d9571b45838bbbfcecf9e6ba5892a29c131ec#diff-9da8cba26bbcd97e04ae72b60139e86cef92874dd1169990b1099af23ab04908R550-R567

**Comment by andelf** [comment]
Not yet to know if there's any other misuse of `Math`.

You should test the ported code at least by syncing from the genesis block to the current head.

**Comment by andelf** [comment]
Softfp will solve all this misused mess. Considering java-tron is already a slow implementation, it is not acceptable.

**Comment by Yrp** [comment]
The first step is to test whether ZGC can bring performance improvements, and the second step is to work out some details.

**Comment by Yrp** [comment]
In addition to Math.pow(), other fp methods need to be tested as well.

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
