### ISSUE TITLE
create tron derived address

### ISSUE THREAD

**Issue by block-hac** [tronprotocol/java-tron#3549]
### 1. What did you do?

I am using TRON http api to connect tron full node.
I installed tron full node and synced it.
I am developing the multiple cryptocurrency wallet management api and it contains merchant account.
In case of BTC, bitcoin has utxo so it makes possible to create many other addresses which represent same wallet.
How can I do same thing in TRON ?

**Comment by joker-gdb** [comment]
> ### 1. What did you do?
> I am using TRON http api to connect tron full node.
> I installed tron full node and synced it.
> I am developing the multiple cryptocurrency wallet management api and it contains merchant account.
> In case of BTC, bitcoin has utxo so it makes possible to create many other addresses which represent same wallet.
> How can I do same thing in TRON ?

"Create many other addresses which represent same wallet." I don't think these accounts can represent the same wallet, just transfer～

**Comment by block-hac** [comment]
> > ### 1. What did you do?
> > I am using TRON http api to connect tron full node.
> > I installed tron full node and synced it.
> > I am developing the multiple cryptocurrency wallet management api and it contains merchant account.
> > In case of BTC, bitcoin has utxo so it makes possible to create many other addresses which represent same wallet.
> > How can I do same thing in TRON ?
> 
> "Create many other addresses which represent same wallet." I don't think these accounts can represent the same wallet, just transfer～

![Capture](https://user-images.githubusercontent.com/72842926/101482776-24c79480-3992-11eb-8c52-4f07a10bfde2.PNG)
![Capture1](https://user-images.githubusercontent.com/72842926/101482781-26915800-3992-11eb-87f1-04b030cc05fc.PNG)
please see these screen shots.
I created these addresses by using getnewaddress .
And they represent the same wallet.

**Comment by Benson0224** [comment]
Check this issue regarding address creation: https://github.com/tronprotocol/java-tron/issues/3229

**Comment by Benson0224** [comment]
Thanks for your contribution to TRON network, since no reply in days, we will close this issue.

Please feel free to re-open it if you still see the issue, thanks.
