### ISSUE TITLE
 Abnormal energy consumption

### ISSUE THREAD

**Issue by shixiaofeia** [tronprotocol/java-tron#3556]
I have a problem, when I transfer USDT, my energy consumption will be 14,631 or 29,631, I want to know what causes this problem?

example:
https://tronscan.org/#/transaction/4201025c8ec3d9bc9f9410b223329ada1ef12279e4dff58b35eb70f038530538 
https://tronscan.org/#/transaction/142543db01d574f2b24a19e1168fe0db186a327c285acd5f086c73f17e151743

**Comment by Benson0224** [comment]
![image](https://user-images.githubusercontent.com/61768920/101600614-89d4c600-3a36-11eb-9f47-46764f25b7fc.png)

The energy cost is different, depends on whether the address is new to the USDT contract.  
- If the address is new to the USDT contract,  transferring USDT to that account is "SET" operation. 
- If the address is not new to the USDT contract,  transferring USDT to that account is "RESET" operation.


Check this doc for further info. https://developers.tron.network/docs/energy-cost#opcode-energy

**Comment by shixiaofeia** [comment]
Thank you, when I transfer all USDT out and in again, it is still "SET" operation

**Comment by shixiaofeia** [comment]
In theory, most standard contract transfers will not consume more than 1TRX, right? Except for non-standard contracts and SET operations

**Comment by shixiaofeia** [comment]
> ![image](https://user-images.githubusercontent.com/61768920/101600614-89d4c600-3a36-11eb-9f47-46764f25b7fc.png)
> 
> The energy cost is different, depends on whether the address is new to the USDT contract.
> 
> * If the address is new to the USDT contract,  transferring USDT to that account is "SET" operation.
> * If the address is not new to the USDT contract,  transferring USDT to that account is "RESET" operation.
> 
> Check this doc for further info. https://developers.tron.network/docs/energy-cost#opcode-energy

There is another question, why is the energy obtained by burning trx different each time, for example
![image](https://user-images.githubusercontent.com/63829677/101710060-bbe43780-3acb-11eb-8188-4073aa2f21e9.png)

**Comment by Benson0224** [comment]
The NO.47 and NO.48 voting request of TRON network were officially approved at 2:00 25th Nov. 2020(SGT): increase the resource cost of the TRON network. 
that is why the cost in left pic is 4 times than the cost in right pic. 

check the voting request detail at https://tronscan.org/#/proposal/47

**Comment by shixiaofeia** [comment]
> 特隆的47次,NO.48投票要求网络正式批准2020年11月25日淩晨2点(SGT):增加特隆网络的资源成本。
> 这就是为什么左图片的成本比成本4次正确的图片。
> 
> 检查请求细节在投票 [https://tronscan.org/ /建议/ 47 ](https://tronscan.org/#/proposal/47)

Oh, I admire your knowledge, thank you for your reply
