### ISSUE TITLE
How to solve NOT_ENOUGH_EFFECTIVE_CONNECTION error?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3560]
### 1. What did you do?

How to solve NOT_ENOUGH_EFFECTIVE_CONNECTION error?
{"code":"NOT_ENOUGH_EFFECTIVE_CONNECTION","message":"effective connection:0 lt minEffectiveConnection:1"}

**Comment by Alexliu007** [comment]
The node is not synchronized to the latest block and it cannot broadcast transactions.
