### ISSUE TITLE
How to send to TRX ?

### ISSUE THREAD

**Issue by block-hac** [tronprotocol/java-tron#3562]
### 1. What did you do?

When I create a new TRX account it contains address (e.g, TWpyNorJbinyEttTWHiPCJUQSaAc4QhKWy) and hexAddress(e.g, 41e4cbf0afbf639a9daa31333b03d74e46d11e85c2).
I am using Tron HTTP API to connect to Tron mainnet and implement some features.
I need to send TRX from my account to another address and I can use following APIs :
EasyTransfer( )
EasyTransferByPrivate( ) or CreateTransaction => GetTransactionSign => BroadcastTransaction
But they need hexAddress for destination address as a parameter.
How can I send TRX to tron address( e.g, TWpyNorJbinyEttTWHiPCJUQSaAc4QhKWy), not hexAddress ?

**Comment by Benson0224** [comment]
parameter "visible" is used to tell whether HEX or Base58check addresses should be used. 
Like this one:  https://developers.tron.network/reference#sendtrx 
if visible is set to false, Hex address should be used, if set to true Base58check addresses should be used.

**Comment by Benson0224** [comment]
close this issue as no feedback for a long time.
