### ISSUE TITLE
内存泄漏了吧， 跑一周不到就内存满了挂掉了

### ISSUE THREAD

**Issue by heipacker** [tronprotocol/java-tron#3563]
### 1. What did you do?

nohup java -Xmx24g -XX:+UseConcMarkSweepGC -jar fullnode/FullNode.jar -c main_net_config.conf --es -d /data/ >/dev/null 2>&1 &

**Comment by a49688448** [comment]
What is the configuration of your machine？

**Comment by heipacker** [comment]
8core, 32G RAM

**Comment by a49688448** [comment]
> 8core, 32G RAM

1.Improve machine configuration, recommend 16core 32GRAM 1TB hard drive (ssd)
In the result of the following command, the maximum value of both cpu cores and siblings needs to be greater than or equal to 16.
$cat /proc/cpuinfo | grep -e “cpu cores”  -e “siblings” | sort | uniq
cpu cores   : 8
siblings    : 16

**Comment by Yrp** [comment]
Please execute the following command and paste the result into the reply.
> $ pmap -x $pid

**Comment by Benson0224** [comment]
Close this issue as no more feedback for a long time.
