### ISSUE TITLE
How to get raw_data_hex

### ISSUE THREAD

**Issue by ansalbeeone** [tronprotocol/java-tron#3569]
Below is my signing output result and how I get **raw_data_hex** form that json

`{"raw_data":{"contract":[{"parameter":{"type_url":"type.googleapis.com/protocol.TransferContract","value":{"amount":1000000,"owner_address":"419c84ec90ef46e68530893cf3229a1dd695b8b457","to_address":"41105e58ce5d754034475f24149ab910f9602bc141"}},"type":"TransferContract"}],"expiration":1608078105411,"ref_block_bytes":"0000","ref_block_hash":"9afbf4c8996fb924","timestamp":1608042105411},"signature":["7204dd578e610164d415f30e57eeb07cab2028a82992c6986f932271796d14b810f85e7b634e0606eefcfe9c76a85663f68a076be8efe7f2355fdb2dc5986f2801"],"txID":"6f3027995c380950442a0f9479ccf31948c7d1134314e333d4b3688799f3d4d1"}`

**Comment by Benson0224** [comment]
"raw_data_hex" is included in the transaction detail. please provide the full transaction info.  

This is one Transaction example from the mainnet. 
https://api.trongrid.io/wallet/gettransactionbyid?value=c62e10b25ab45ca400dbdf6bcba249e76aa14caf50a3fb1c108dc1a64d116bc9

you can also check the demo codes of TRANSFER TRX from https://andelf.gitbook.io/tron/tron-by-example/transfer-trx

**Comment by ansalbeeone** [comment]
@Benson0224  detailed question is here 
https://stackoverflow.com/questions/65307890/tron-wallet-integration-in-android-application

**Comment by Benson0224** [comment]
> @Benson0224 detailed question is here
> https://stackoverflow.com/questions/65307890/tron-wallet-integration-in-android-application

check this guide: https://developers.tron.network/docs/make-transaction-locally

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.

**Comment by ansalbeeone** [comment]
@Benson0224  i update my question please help me
