### ISSUE TITLE
请问合约和侧链是一个概念吗

### ISSUE THREAD

**Issue by sywyn219** [tronprotocol/java-tron#3572]
1,合约开发及部署就是在主链上扩展一条侧链吗？
2,合约是主链的合约，侧链是另一种合约的部署方式？
请问，上面两种说法哪个正确？或者有其他解释，请解惑下，please，正在拜读代码

**Comment by Benson0224** [comment]
Both of your statements are wrong！

Smart Contract and sidechain are 2 different things.
- Smart Contract introduction： https://cn.developers.tron.network/docs/%E4%BB%8B%E7%BB%8D-1
- Tron Sidechain info： https://tron.network/sunnetwork/#/

More info below:
- Smart Contract development guide: https://cn.developers.tron.network/docs/%E5%85%A5%E9%97%A8-4
- Issue TRC20 token guide: https://cn.developers.tron.network/docs/%E5%8F%91%E8%A1%8Ctrc20%E4%BB%A3%E5%B8%81%E6%95%99%E7%A8%8B

**Comment by sywyn219** [comment]
谢谢
