### ISSUE TITLE
How to solve SERVER_BUSY error?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3576]
### 1. What did you do?

How to solve SERVER_BUSY error?

**Comment by Alexliu007** [comment]
When the number of transaction from the pending is greater than 2000, the problem will be triggered.First,check the network status of the node to see if the network status is not good, resulting in a backlog of pending list.Then if you encounter SERVER_BUSY, you can delay retry.

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
