### ISSUE TITLE
How to solve the revert error？

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3577]
### 1. What did you do?

How to solve the revert error？

**Comment by Alexliu007** [comment]
The following conditions generate a require-style exception, which throws a revert error, and only consume the already consumed energy, excluding the unconsumed energy.  
https://developers.tron.network/docs/vm-exception
https://developers.tron.network/docs/faq#4-how-to-troubleshoot-when-calling-the-contract-and-return-the-revert-error

**Comment by ksp-04** [comment]
Gow to revert?

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
