### ISSUE TITLE
How to make transactions after i recovry my trust wallets

### ISSUE THREAD

**Issue by sunshine1620** [tronprotocol/java-tron#3582]

**Comment by Benson0224** [comment]
What kind of transaction do you mean here?   TRX transfer or TRC20 token transfer?

Please query the user guide from Trust wallets' official guides, or check the official support team of trust wallets. thanks

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
