### ISSUE TITLE
__Originally posted by @queenbrifrfr in https://github.com/tronprotocol/wallet-cli/pull/372__

### ISSUE THREAD

**Issue by queenbrifrfr** [tronprotocol/java-tron#3584]
__Originally posted by @queenbrifrfr in https://github.com/tronprotocol/wallet-cli/pull/372__

__Originally posted by @queenbrifrfr in https://github.com/tronprotocol/wallet-cli/issues/373__

__Originally posted by @queenbrifrfr in https://github.com/tronprotocol/wallet-cli/issues/387__

**Comment by Benson0224** [comment]
Can you please give more info on your issue?  thanks.

**Comment by queenbrifrfr** [comment]
I was try to develop a easy way to use wallet/ci

**Comment by Benson0224** [comment]
> I was try to develop a easy way to use wallet/cli

Please help to close this issue if it is a misoperation, thanks.

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
