### ISSUE TITLE
How to  create/integrate  tron wallet in  android app 

### ISSUE THREAD

**Issue by jpnapps** [tronprotocol/java-tron#3588]
### 1. What did you do?
How to  create/integrate  tron wallet in  android app ?

any sample code for android app ?

**Comment by Benson0224** [comment]
Regarding Address creation, you can refer to this issue: https://github.com/tronprotocol/java-tron/issues/3374 

Regrading Tronlink integration, please check this guide: https://developers.tron.network/docs/tronlink-integration

**Comment by Benson0224** [comment]
We will close this issue now, please feel free to open this issue if you have further questions.

**Comment by fanil30** [comment]
404 Page not found.
