### ISSUE TITLE
Not authorized jitpack

### ISSUE THREAD

**Issue by tdnhduc** [tronprotocol/java-tron#3596]
### 1. What did you do?

Could not transfer artifact com.github.tronprotocol:framework:pom:1.0.0 from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized.

### 2. What did you expect to see?

I have build ```java-tron``` repo from official repo and deploy to our server. But I have run again and get this issuse

### 3. What did you see instead?
No error

**Comment by andelf** [comment]
Please refer to any available docs of jitpack.io.
