### ISSUE TITLE
TriggerConstantContract via gRPC not working.

### ISSUE THREAD

**Issue by neshala** [tronprotocol/java-tron#3602]
I am trying to execute TriggerConstantContract via gRPC protocol and having returned this error:

"A���=contract validate error: No contract or not a smart contract

I am setting addresses like this:

```php
$sc = new TriggerSmartContract();
$sc->setOwnerAddress('41977C20977F412C2A1AA4EF3D49FEE5EC4C31CDFB');
$sc->setContractAddress('419E62BE7F4F103C36507CB2A753418791B1CDC182'); // USDT contract.
```

gRPC client is PHP library generated from this repo, but I think that's irrelevant.
I am using the latest stable release.

I have TriggerConstantContract working via HTTP but can't make it working using gRPC.

Problem is caused because of this part of framework/src/main/java/org/tron/core/Wallet.java
public Transaction triggerConstantContract

to be more specific:
```java
    if (ArrayUtils.isEmpty(isContractExist)) {
      throw new ContractValidateException(
          "No contract or not a smart contract");
    }
```
I am getting this error even with provided USDT contract at this format: 419E62BE7F4F103C36507CB2A753418791B1CDC182

Is there a bug or I am passing invalid variables? I am just trying to call USDT TRC20 contract and call function name()

**Comment by Starsakary** [comment]
Have you checked if you are in the correct network? These addresses work only in Shasta test net.

**Comment by neshala** [comment]
I am using my own node and doing it all via 127.0.0.1
I have this main config supportConstant = true

I am using the latest release and even tried to compile from the latest source from the main brench.

I just don't understand what I am doing wrong. When using HTTP API I can query my contract, but when try the same via gRPC I have that error: "No contract or not a smart contract".

I only have a problem calling triggerConstantContract, other endpoints are working both in HTTP and gRPC.

I am thinking should I maybe again deploy my contract to my local node and see if then it will exist, but that just doesn't make sense to me, because it works via HTTP.

**Comment by Starsakary** [comment]
I've said that the addresses you provided are from Shasta test net but not the main net. 
USDT address on main net is : 
TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t -- Base58
41A614F803B6FD780986A42C78EC9C7F77E6DED13C -- Hex

**Comment by neshala** [comment]
Ok, that was just a bad example I provided.

I have now tried with usdt contract address and owner like this:

$sc = new TriggerSmartContract();
$sc->setOwnerAddress('41517591d35d313bf6a5e33098284502b045e2bc08'); // THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC
$sc->setContractAddress('41a614f803b6fd780986a42c78ec9c7f77e6ded13c'); //  TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t

My node is synced 1 second ago with the main network, but still, I have this returned: "No contract or not a smart contract"
Via HTTP it works the same example is working.

I have even changed and recompiled FullNode to see if the address is passed properly and I can see there it's received as "41a614f803b6fd780986a42c78ec9c7f77e6ded13c", but still node thin fails with "No contract or not a smart contract".

I am so desperate to figure out this, but can't figure out what is wrong. Thanks for helping.

**Comment by Starsakary** [comment]
Alright, in the Protobuf definition that addresses are in the type of `byte`. You may try to find out the corresponding data type in your language and set the param again.

**Comment by neshala** [comment]
Well, this is how gRPC library was generated for my programming language (PHP): 
```php
    /**
     * Generated from protobuf field <code>bytes contract_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContractAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->contract_address = $var;

        return $this;
    }
 ```       
So it's expected to have a string as input for address, and validation exist for that.

Also, I have checked what is received on the server-side in FullNode and it was byte type that I had to convert to string in JAVA in order to see if the proper value was passed.

So I think that server receive byte format of hex address, but for some reason it trow exception with message that it's not an existing contract even for USDT contract in synced and up to date node.

**Comment by Starsakary** [comment]
The param should be a `raw String` but not `hex String`

**Comment by neshala** [comment]
I have tried like this ( i hope that's what you mean by rad String)

```php
$sc = new TriggerSmartContract();
$sc->setOwnerAddress('THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC');
$sc->setContractAddress('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t');
```

but again I am the same error getting returned: "contract validate error: No contract or not a smart contract"

**Comment by Starsakary** [comment]
Raw String means string with escaped raw bytes.
Assuming the API receives a hex string starts with '41', `bytes` in java is `ByteString`, what we do in java is like below:
```
bytes[] raw = Hex.decode("your hex address");
return ByteString.copyFrom(raw);
```java

The `Hex.decode` function is from `org.bouncycastle.util.encoders.Hex`

**Comment by neshala** [comment]
Well, gRPC protobuf library should make this agnostic.

From PHP I should only provide string (protobuf generated files for PHP) that will be translated to bytes and I should not have to do anything on the server side written in Java.

The only thing I can do wrong is to send an invalid string format, eg with 0x or 41 as a prefix. I don't have any more ideas on what to try when calling gRPC API.

**Comment by Starsakary** [comment]
It doesn't matter what kind of conversion process you have done but to give a string with escaped raw bytes.

**Comment by neshala** [comment]
Ok thanks a lot, I think that I have found what I need in PHP:

https://www.php.net/manual/en/function.bin2hex.php
https://www.php.net/manual/en/function.hex2bin.php
