### ISSUE TITLE
Reducing Bandwidth consumption  

### ISSUE THREAD

**Issue by playandlike** [tronprotocol/java-tron#3606]
### 1. What did you do ?
We are a developer of ‘Play and Like (PAL)’ token .

### 2. What did you expect to see?
There are almost 45k users are alloted their wallet and their rewards are being distributed in shape of PAL token  every minute and as much as they use application they will get the rewards .In whole we need to reduce bandwidth of transaction which will result in less transaction fee.

### 3. What did you see instead?
We find a very high fee for these transaction.
Looking for codes that will result in reducing bandwidth consumption of transaction.

**Comment by andelf** [comment]
This is not a product issue, you should open a request at https://github.com/tronprotocol/tips .

Feel free to open an issue here if you have any other questions about the usage of java-tron.
