### ISSUE TITLE
Does Tron support proxy contract ?

### ISSUE THREAD

**Issue by rabinhod** [tronprotocol/java-tron#3614]
is it possible to create upgradeable smart contract  in tron ?

**Comment by Omo-Coc** [comment]
Yes, whether the contract supports upgrade is a matter of contract implementation level, and has nothing to do with the chain itself. You can refer to the implementation of openzeppelin's upgradeable contract

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
