### ISSUE TITLE
What is a new API used for?

### ISSUE THREAD

**Issue by tdnhduc** [tronprotocol/java-tron#3627]
### 1. What did you do?

I've read a new API support 
```GetBurnTrxAmount: query burned trx amount```

### 2. What did you expect to see?
What is API used for?

### 3. What did you see instead?
How can I integrate our payment system?

**Comment by lvs007** [comment]
This interface will only take effect after Proposal 49 is passed

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
