### ISSUE TITLE
Build failed Raspbian

### ISSUE THREAD

**Issue by Tomboo1** [tronprotocol/java-tron#363]
I already started a node succesfull on my normal computer. But gave it a shot on my Raspberry PI due to its power efficiency. Unfortunately it failed to build and get it to work. Is it compatible with ARM processors?

1. What did you do?
Tried to install a node on my raspberry pi 3b+ with raspbian. I followed the instructions in the readme and installed oracle JSK 8. Tried to find more info about this issue online but wasn't able to find anything suitable.

2. What did you expect to see?
A build without errors. 

3. What did you see instead?
![2018-04-04-173059_1680x1050_scrot](https://user-images.githubusercontent.com/38075566/38324672-81a5b83c-3830-11e8-9f12-eff3fc5cfdd8.png)

**Comment by zhaohong** [comment]
it seams like this is no protoc-3.5.1 in maven for arm.

**Comment by lky1001** [comment]
compile google protobuf and install on raspbian.
https://github.com/google/protobuf
http://osdevlab.blogspot.kr/2016/03/how-to-install-google-protocol-buffers.html

**Comment by taylorwilkersonoliver** [comment]
Maybe try croscompiling from Linux.  When I get some time I'll take a look and try to figure this out.

**Comment by Tomboo1** [comment]
Never did crosscompiling before, gave it a try but couldnt get it to work. If someone with a little more experience can give it a try that would be great!
