### ISSUE TITLE
Transaction could not broadcast or Fail from network.

### ISSUE THREAD

**Issue by TurgutKanceltik** [tronprotocol/java-tron#3630]
Hello,

First of all, I have to say that we use the **Official Public Node** with .NET Core.

### 1. What did you do?
I create transactions and then broadcast to the endpoint I call: `wallet/broadcasttransaction`

### 2. What did you expect to see?

Resulting successful broadcast. And a valid transaction hash in response.

### 3. What did you see instead?

**Result 1.**
```
{"code":"NOT_ENOUGH_EFFECTIVE_CONNECTION","txid":"202c011b25be7148b8facb3a35d1ee301e60cd43c07872d3b3b32c09b308a07f","messa
ge":"65666665637469766520636f6e6e656374696f6e3a30206c74206d696e456666656374697665436f6e6e656374696f6e3a31"}
```

**Result 2.**
```
{"code":"TRANSACTION_EXPIRATION_ERROR","txid":"f80c82e374f2b067cea37d3272051637723eff20da672fcec52ae79c984e0451","message":"7472616e73616374696f6e2065787069726564"}
```

**Result 3.**
Transactions fail sometimes on the network.
A sample transaction hash as follows;

> [4f0ab4c1620cd622d213372f59852b00edbbeb270ddc6088ec8a91736a021476](https://tronscan.org/#/transaction/4f0ab4c1620cd622d213372f59852b00edbbeb270ddc6088ec8a91736a021476)

### 4. My questions are.

1. What could this be caused by?
2. For result 1 and result 2, is there any way I can understand that these transactions will not go later? Or can we say that it definitely won't happen later?
3. For result 3, when I get transaction detail, How can I distinguish between successful and fails?
4. For result 1 and result 2, if I get these exceptions, can I try to spend again? Can it be double spend?

**Comment by Starsakary** [comment]
'not effective connection' means the node cannot be synchronized normally. Try to set 'mineffectiveconnection = 1'

**Comment by TurgutKanceltik** [comment]
@Starsakary 
`'not effective connection' means the node cannot be synchronized normally. Try to set 'mineffectiveconnection = 1'`
that's mean if I get this error, I can spend again right? So it will not double spend?
I also stated that I use **Official Public Node.** It is not in my hands to manage `mineffectiveconnection`.

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
