### ISSUE TITLE
Invalid amount in transaction

### ISSUE THREAD

**Issue by newnya** [tronprotocol/java-tron#3631]
### 1. What did you do?
 (Not sure if this is an issue with TronLink or the protocol itself.)
I've tried to send a small SUN token amount with Tronlink API:
```
try {
  let instance = await tronWeb.contract().at("TKkeiboTkxXKJpbmVFbv4a8ov5rAfRDMf9"); // contract for SUN token
  let res = await instance.transfer(<recipient>,tronWeb.toSun(0.000001)).send({
		            feeLimit:100000000,
		            callValue:0,
		            shouldPollResponse:true
		        });
  console.log(res);
} catch (error) {
  console.log("error:"+JSON.stringify(error));
}	
```
This code worked and the tx was broadcasted, but it has an unexpectedly small amount:
0.000000000000000001 SUN. Which is not even a valid amount as per the protocol: the smallest transferable amount is 0.000001, so this transaction should not even be included in a block.

I expected to transfer 0.000001 SUN  ( i.e. 1 sun of SUN token )
Indeed if i remember well, when Tronlink asked me to sign the tx, it reported "1" in the second parameter of the smart contract.

### 2. What did you expect to see?
In the resulting transaction 355984341a1dad7037f3f467ba95ac4b21631a6edce932792a7398779bdd6c33
i expected to see an amount of 1 sun of SUN, which would be 0.000001 SUN

### 3. What did you see instead?
The transaction 355984341a1dad7037f3f467ba95ac4b21631a6edce932792a7398779bdd6c33   has amount  0.000000000000000001, which is way lower than the expected amount 0.000001

**Comment by andelf** [comment]
`tronWeb.toSun` is used for TRX unit convertion in SUN(the smallest unit of TRX).

SUN of TKkeiboTkxXKJpbmVFbv4a8ov5rAfRDMf9 is a TRC20 token, which has a decimal of 18.

**Comment by newnya** [comment]
@andelf Thanks
