### ISSUE TITLE
怎么判断节点同步完成

### ISSUE THREAD

**Issue by LyyDandelion** [tronprotocol/java-tron#3634]
日志显示比最新区块慢几十个块，不能达到完全同步，这是正常现象吗。

**Comment by cathy-lishipu** [comment]
You can refer to this document: https://cn.developers.tron.network/docs/faq#8%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E8%8A%82%E7%82%B9%E5%8C%BA%E5%9D%97%E5%90%8C%E6%AD%A5%E6%85%A2%E6%88%96%E8%80%85%E5%81%9C%E6%AD%A2%E5%90%8C%E6%AD%A5%E9%97%AE%E9%A2%98%EF%BC%9F

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
