### ISSUE TITLE
My nodes always stop pulling after a few hours

### ISSUE THREAD

**Issue by Acodemiao** [tronprotocol/java-tron#3635]
This is the log content when the pull is stopped
![image](https://user-images.githubusercontent.com/51939982/106412768-70268c80-6483-11eb-982e-3ca0d62aca4c.png)

**Comment by Acodemiao** [comment]
size: 11, start block: Num:27241541,ID:00000000019fac4597f44a2a68bd41fac899288ce941ee2133e03cb694e25e11, end block Num:27243560,ID:00000000019fb4289fe04516af382ed4e1434d0ee747b590306734a53d73eb65
07:30:32.988 INFO  [pool-35-thread-1] [net](PeerClient.java:70) connect peer 47.90.209.213 18888 f7bcc5f8fc640734c2a1fc92ccb961737374b57df060b353f33dee7f63b5b73dfe91c01a480d511ea9dc6ff7d2af8118ce3c6acf762010030544a67dc36ea558
07:30:35.718 INFO  [pool-35-thread-1] [net](PeerClient.java:70) connect peer 47.89.153.222 18888 6c5f8396e118d465561de50a9a56f823bb33f20576cfe75d320bb8a5d8036ca47e2e3f399457238501465e27df90c1fe44eda19cb2dc14bfd179269a73f23c37
07:30:35.718 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /47.89.244.105:18888.
07:30:32.988 INFO  [TronJClientWorker-13] [net](MessageQueue.java:121) Receive from /52.63.185.80:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:27241560,ID:00000000019fac58c7a91ee1b835d44e20b93ecd8a248b9134b8e997818e2022, end blockId: Num:27243560,ID:00000000019fb4289fe04516af382ed4e1434d0ee747b590306734a53d73eb65
07:30:35.718 INFO  [TronJClientWorker-14] [DB](Manager.java:1520) headNumber:27241560
07:30:32.988 INFO  [TronJClientWorker-15] [net](MessageQueue.java:121) Receive from /47.89.188.118:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:27241560,ID:00000000019fac58c7a91ee1b835d44e20b93ecd8a248b9134b8e997818e2022, end blockId: Num:27243560,ID:00000000019fb4289fe04516af382ed4e1434d0ee747b590306734a53d73eb65
07:30:35.718 INFO  [pool-35-thread-1] [net](PeerClient.java:70) connect peer 78.108.216.201 18888 25a0dcc073180b9a2b21d62db8db107a9495e56a5ec6f3899a4bf7dcb6bbc52f53fe0f93fbbdcfe35b3d17d90a443bb66972e45bad542b20c4182a2a50d145a2

**Comment by cathy-lishipu** [comment]
Can you provide the error log?

**Comment by Acodemiao** [comment]
> 您可以提供错误日志吗？

There is no error log.Is the error file in a file?I'm showing is trog.log The last part.

**Comment by cathy-lishipu** [comment]
> > 您可以提供错误日志吗？
> 
> There is no error log.Is the error file in a file?I'm showing is trog.log The last part.

you can execute this command: grep -i error

**Comment by Acodemiao** [comment]
> > > 您可以提供错误日志吗？
> > 
> > 
> > 没有错误日志。错误文件是否在文件中？我显示的是trog.log最后一部分。
> 
> 您可以执行以下命令：grep -i error

![image](https://user-images.githubusercontent.com/51939982/106434055-fce54080-64ab-11eb-91a0-5a1bd925c242.png)

**Comment by cathy-lishipu** [comment]
The logs show that the memory size allocated to the JVM at node startup is not appropriate and should be 80% of the physical memory. You can refer to this document: https://developers.tron.network/docs/fullnode

**Comment by Acodemiao** [comment]
> The logs show that the memory size allocated to the JVM at node startup is not appropriate and should be 80% of the physical memory. You can refer to this document: https://developers.tron.network/docs/fullnode

java -Xmx13g -jar FullNode.jar -c config.conf &   
This is my start command.My machine is 8-core 16g

**Comment by cathy-lishipu** [comment]
> > The logs show that the memory size allocated to the JVM at node startup is not appropriate and should be 80% of the physical memory. You can refer to this document: https://developers.tron.network/docs/fullnode
> 
> java -Xmx13g -jar FullNode.jar -c config.conf &
> This is my start command.My machine is 8-core 16g

You can refer to this document: https://developers.tron.network/docs/fullnode
<img width="643" alt="IMG" src="https://user-images.githubusercontent.com/59823661/106445234-b565b100-64b9-11eb-9526-8a3b0617383d.png">

**Comment by Acodemiao** [comment]
My problem has been solved.thank you
