### ISSUE TITLE
地址监控 TRX 和 USDT数量

### ISSUE THREAD

**Issue by speakphp** [tronprotocol/java-tron#3638]
# 如何监控某个地址上面的 TRX 数量变动  和 USDT 的变动呢？
# 目前我参考的文档是：https://cn.developers.tron.network/docs/trc20%E5%90%88%E7%BA%A6%E4%BA%A4%E4%BA%92%E4%BB%A5usdt%E4%B8%BA%E4%BE%8B
但是这种方式监控不到 我目前的流程如下：

- 首先生成一个离线账号【本地生成】A
- 然后使用火币 或者是 币安APP 往A地址里面转入 100个USDT 
- 然后进行监控地址 A 但是监控不到消息
- 在继续往A里面充值 10个TRX 同样也监控不到

**Comment by andelf** [comment]
Ref: https://cn.developers.tron.network/docs/trc20%E4%BA%8B%E4%BB%B6

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
