### ISSUE TITLE
Block checksum mismatch

### ISSUE THREAD

**Issue by neshala** [tronprotocol/java-tron#3641]
My Tron node is corrupted and out of sync I guess because of corrupted DB on disk, I have this error message:

Corruption: block checksum mismatch

What can be done to fix this and avoid removing the full output_directory and sync from zero?

**Comment by cathy-lishipu** [comment]
You can download the backup data: https://backup.trongrid.io/

**Comment by neshala** [comment]
I know for that, but it can take several hours to get the node back on that way. There should be a faster way to execute some command and fix last few fetched blocks on disk that was corrupted and continue.

**Comment by BisonAl** [comment]
yeah if there was a way to remove the last 1,000 blocks or so that would be very helpful, even as a potential debugging path for issues like https://github.com/tronprotocol/java-tron/issues/3643 or https://github.com/tronprotocol/java-tron/issues/3580

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
