### ISSUE TITLE
Tron Stuck at Block 27465569

### ISSUE THREAD

**Issue by areebmajeed** [tronprotocol/java-tron#3643]
The node was stuck at 27465569 even after several reboots. Was there a hard-fork at that block?

As soon as I updated the binaries, it started syncing normally.

**Comment by dunghuynh** [comment]
I'm having the same problem. I'm trying to update to binary

**Comment by areebmajeed** [comment]
> I'm having the same problem at block "0000000001a31761e616fbafa1880915d2565cbcaab2c6164907996400bac17b". I'm trying to update to binary

That confirms the issue :) My server was stuck at that block as well.

**Comment by dunghuynh** [comment]
After updating binary from GreatVoyage-v4.1.1 to GreatVoyage-v4.1.2
The server can now continue to sync normally.
Thanks for the suggestion

**Comment by smart55557777** [comment]
tron is suck, always requered updata binary . like a centralized system.

**Comment by areebmajeed** [comment]
I hope there is more clarity on this "forced upgrade".

**Comment by xy83918** [comment]
could you help me to confirm how to upgrade the binaries

**Comment by areebmajeed** [comment]
> could you help me to confirm how to upgrade the binaries

First of all, kill the Tron process. Then, download the latest FullNode.jar from Releases page (https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.1.2) and replace it on your server. Start your FullNode as you did before.

**Comment by xy83918** [comment]
Thanks a lot, I am trying to do this

**Comment by xy83918** [comment]
It's work, Thanks

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
