### ISSUE TITLE
I had currency extraction but there is no money or transaction in my wallet, how can I follow up?

### ISSUE THREAD

**Issue by pinat935** [tronprotocol/java-tron#3645]

**Comment by Benson0224** [comment]
Could you provide us more info.  
Do you mean you withdraw some currency from exchange to your wallet?  if yes, I would suggest you check with the exchange support team for help. thanks.

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 
Feel free to re-open this issue if you still see it, thanks.
