### ISSUE TITLE
Self node recharge problem

### ISSUE THREAD

**Issue by xdleihui** [tronprotocol/java-tron#3646]
### 1. What did you do?
I deployed a FullNode, created an address, and transferred other addresses to the accounts in my deployed node. How can I find out these transactions

**Comment by Benson0224** [comment]
https://developers.tron.network/docs/transaction-11 

I would suggest you check this guide to understand the lifecycle of a transaction. 
To complete one transaction you need the below 3 steps. from your description, we cannot tell which step you failed. please give us more info after you read the guide. thanks. 
1. Create a transaction
2. Sign the transaction
3. Broadcast the transaction

**Comment by xdleihui** [comment]
For example, I am an exchange and I have deployed a node myself，Other exchanges recharge my exchange address，How can I find the transaction information in my own node @Benson0224

**Comment by xdleihui** [comment]
How to monitor the transaction information recharged to your own node

**Comment by Benson0224** [comment]
currently, there is no such mechanism in java-tron.

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time.
Please feel free to re-open it if you still see it, thanks.
