### ISSUE TITLE
TRON Contract doesn't deploy despite consuming 2000 TRX

### ISSUE THREAD

**Issue by jasrajput** [tronprotocol/java-tron#3647]
I write a smart contract of 862 lines and whenever I try to deploy it, I got an error Not enough energy for 'save just created contract code' executing:needEnergy(8145800), leftEnergy(6528866). You've lost 999.99 TRX.. This thing happened to me twice, Despite having 1000 TRX as a fee Limit which in Sun is 1000000000 and origin energy limit is 10 TRX... I have also freeze TRX to obtain additional energy.But that didn't help as the same error pops up..Now I've lost 2000 TRX as a result..Can anyone help me regarding it ??

**Comment by Benson0224** [comment]
can you share the transaction hash? 

check this general guide  for "OUT_OF_ENERGY" issue: https://developers.tron.network/docs/faq#7-how-to-solve-out_of_energy-error

**Comment by jasrajput** [comment]
sure, this is the txn hash cde433aad5f7b76f372a69911070feac9a8f60f902ce0e8b126cf500f5aff3f7

**Comment by Benson0224** [comment]
https://api.trongrid.io/wallet/gettransactioninfobyid?value=cde433aad5f7b76f372a69911070feac9a8f60f902ce0e8b126cf500f5aff3f7  

transfer the resMessage to a string:
Not enough energy for 'save just created contract code' executing: needEnergy[8145800], leftEnergy[6528066];

from the transaction, we can see current fee_limit is 1000 TRX, and it caused the OUT_OF_ENERGY error. so suggest increasing the fee_limit.
https://api.trongrid.io/wallet/gettransactionbyid?value=cde433aad5f7b76f372a69911070feac9a8f60f902ce0e8b126cf500f5aff3f7

I would suggest you try this on shasta testnet first to see how much energy is needed and then try again on mainnet with a proper fee_limit .

**Comment by jasrajput** [comment]
the fee_limit are in the orders are: 100, 1000, 10000 and so on..On Shasta testnet, it doesn't consume much trx as compare to mainnet.

**Comment by Benson0224** [comment]
> the fee_limit are in the orders are: 100, 1000, 10000 and so on..On Shasta testnet, it doesn't consume much trx as compare to mainnet.

Currently, the max fee_limit is 5000TRX,    in your case, I would suggest you try 3000TRX as fee_limit on shasta testnet first to see how much energy is needed and then try again on mainnet with a proper fee_limit .

Shasta now get the same consumption as mainnet as it also changed the unit price to 140 Sun on 22nd Feb. https://shasta.tronscan.org/#/proposal/18

**Comment by jjhesk** [comment]
I also have the same error #3660

**Comment by jasrajput** [comment]
Those, who is still having issue with large contract deployment, All you have to do is to buy some energy from http://tokengoodies.com/ platform and there you go!! Buy energy of atleast 500 TRX for large contracts, after that there would be no consuming of trx from your wallet by blockchain..

Cheers..

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time.
Please feel free to re-open this issue if you still see it. thanks.

**Comment by nitikeshd** [comment]
I am getting the same issue
