### ISSUE TITLE
Account asset optimization

### ISSUE THREAD

**Issue by forfreeday** [tronprotocol/java-tron#3648]
### 1. What did you do?
Optimize your Account account. Create a new store of account assets.

Compare with [release_4.1.2](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.1.2) and  [optimized version](https://github.com/tronprotocol/java-tron/tree/feature/account_asset_optimization) 

The serialization speed is optimized on the original side according to the Account account volume, and as much as possible, other than the necessary fields of the account, such as address, balance, accountName and other related fields are kept, other business fields that can be taken out separately are extracted.

This time, the Asset asset-related storage is optimized, stripped from the Account and moved to the new Asset-related storage.

### 2. What did you expect to see?
Account transfer speed further optimized
**1. Serialization speed**
Account reduces Asset-related fields during serialization, and after serialization fields are performed, a performance comparison of 1 million serializations is performed:

**Results of comparing the results of 4 tests**
|    version   |  improvements  |
| ---- | ---- |
|   1      |  14.77%  |
|    2    |  37.31%  |
|    3    |  28.69%  |
|    4     |  23.15%  |

**2.Transaction processing speed**
Account deserialization 1 million times compared, the optimized version will be slightly faster in deserialization about 16%

**Results of comparing the results of 4 tests**
|    version |  improvements  |
| ---- | ---- |
|    1    |  28.75% |
|    2    |  39.35% |
|    3   |  37.92%  |
|    4   |  30.04%  |

**3.Transaction processing speed**
There is a significant increase in average speed when comparing both transaction and block processing speeds

|    version  |  txs/ms   |  block/ms    |  
| ---- | ---- | ---- |
|    optimized   |  23.26%| 33.91% |

### 3. What did you see instead?
Account transfer speeds have improved, as have transaction and block packing speeds
Based on the above comparison, it can be determined that the version that extracts the fields will be faster in the serialization operation.

**Comment by Benson0224** [comment]
By current design, Tron network produced a new block every 3 seconds.  that is to say, It takes more than 3 seconds to transfer TRX to a newly created account. Do you mean you want to optimize this part?

**Comment by forfreeday** [comment]
> By current design, Tron network produced a new block every 3 seconds. that is to say, It takes more than 3 seconds to transfer TRX to a newly created account. Do you mean you want to optimize this part?

The purpose of this optimization to improve the speed of account serialization is to improve the TPS of packing out blocks so that more transactions can be packed into blocks.

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
