### ISSUE TITLE
tron node issues

### ISSUE THREAD

**Issue by Akonova1enko** [tronprotocol/java-tron#3650]
can't receive info from node, seems it can't start
logs are on screenshot
thank you all in advance
![image](https://user-images.githubusercontent.com/16065186/108718299-f421e080-7526-11eb-8487-a60c26e74bc3.png)

**Comment by Starsakary** [comment]
You can put your device configuration and the full log here

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 
Please feel free to re-open this issue if you still see it. thanks.
