### ISSUE TITLE
Please support tron mempool transaction tracing

### ISSUE THREAD

**Issue by ytrezq** [tronprotocol/java-tron#3651]
Hello,

since Tron allows to run Ethereum bytecode unmodified, this leed to the same frontrunning opportunities.

A key point for doing this is determining if chaining an action using my own address with the transaction comming from an address I don t control would result in a specific amount being sent.

So what s the equivalent of https://openethereum.github.io/JSONRPC-trace-module#trace_callmany in Tron. Also by the way, would it be possible to get Tron specific implementation details concerning implemented instruction and gas costs (I m meaning where is the documentation about it)?

**Comment by andelf** [comment]
> since Tron allows to run Ethereum bytecode unmodified, this leed to the same front-running opportunities.

Front-running is not acceptable in java-tron. i.e. It is impossible to broadcast a newer transaction with higher priority(no concept of gas_price). SRs generates block in the order they come.

Energy cost is documented at <https://developers.tron.network/docs/energy-cost>. You might need to dig into the source code `OpCode.java`.

Currently, there's no `call trace` in java-tron. It might be implemented in a future version.

**Comment by ytrezq** [comment]
> > since Tron allows to run Ethereum bytecode unmodified, this leed to the same front-running opportunities.
> 
> Front-running is not acceptable in java-tron. i.e. It is impossible to broadcast a newer transaction with higher priority(no concept of gas_price). SRs pack transactions in the order they arrive.
> 
I disagree, this also exist in Ethereum where you want can insert a transaction of yours between 2 transaction of the same gas price. This is the matter of detecting the transaction as soon as possible and sent them reordered directly to miners nodes. The only barrier is private mining is not as developped on Tron as it is on Ethereum which is translated to less blocks (in %) with custom ordereing.

**Comment by Benson0224** [comment]
As andelf already gave the answer and no update for a long time, we will close this issue now. 
Please feel free to re-open this issue if you would like to talk more on this topic, thanks.
