### ISSUE TITLE
Failed- transaction revert but coins didn't return

### ISSUE THREAD

**Issue by emydark** [tronprotocol/java-tron#3652]
### 1. What did you do?
I initiated a usdt transfer to a trc20 address
###2. What did you expect?
For coins to deliver to recipient

### 3. What did you see instead?
After waiting for hours I checked the transaction hash and I saw failed- transaction revert. However it's been hours now and coins didn't return to me
![Screenshot_2021-02-23-13-27-59-084_com android chrome](https://user-images.githubusercontent.com/79525862/108860749-c902c400-75ee-11eb-8182-32396aeaeef1.jpg)

**Comment by yanghang8612** [comment]
Hi, which kind of conis do you mean that didn`t return to you?

**Comment by emydark** [comment]
Thanks for your reply. It is USDT coins

**Comment by yanghang8612** [comment]
Ok got it, You can check out another [issue](https://github.com/tronprotocol/java-tron/issues/3642#issuecomment-781002655) for more information. Thanks!

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 
Please feel free to re-open this issue if you still see it, thanks.

**Comment by raph64990** [comment]
I have just the same pb with TronLink? Does anyone knows how can I get back my USDT?

**Comment by Benson0224** [comment]
> I have just the same pb with TronLink? Does anyone knows how can I get back my USDT?

1. Revert means the transaction failed.  for example, if you are trying to send USDT to another account, if a revert happened, your USDT will be still in your account. 
2. If you are trying to withdraw USDT from exchange to your own account, Please contact Exchange support if revert happened.

**Comment by quangdaidws** [comment]
Can you help me for this issue ?

**Comment by quangdaidws** [comment]
![Uploading Screenshot_2022-05-12-08-17-21-24_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by quangdaidws** [comment]
How can I get back usdt coin ?
![Uploading Screenshot_2022-05-12-08-17-21-24_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()
