### ISSUE TITLE
Node is not syncing

### ISSUE THREAD

**Issue by pion33r** [tronprotocol/java-tron#3657]
### 1. What did you do?
1. Downloaded the fullnode chain backup from https://backup.trongrid.io/
2. java -jar FullNode.jar -c mainnet.conf

### 2. What did you expect to see?
Constantly syncing fullnode with the network.

### 3. What did you see instead?
Node is not syncing forward. Stuck with block 27976864

Log output:
--------------
05:42:01.272 INFO  [TronJClientWorker-82] [net](MessageQueue.java:121) Receive from /47.241.0.3:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:27976864,ID:0000000001aae4a020b6bed050266de93e19a434a26455b8bbccd3110e7474c4, end blockId: Num:27978864,ID:0000000001aaec70f794a23300d7d0e52874a005ad9a737c997b4e79ae7b7d1d
05:42:01.273 INFO  [TronJClientWorker-82] [DB](Manager.java:1424) headNumber:27976864
05:42:01.274 INFO  [TronJClientWorker-82] [DB](Manager.java:1426) syncBeginNumber:27976845
05:42:01.274 INFO  [TronJClientWorker-82] [DB](Manager.java:1430) solidBlockNumber:27976846
05:42:01.274 INFO  [TronJClientWorker-82] [net](SyncService.java:179) Get block chain summary, low: 27976845, highNoFork: 27976864, high: 27976864, realHigh: 27978864
05:42:01.274 INFO  [TronJClientWorker-82] [net](MessageQueue.java:106) Send to /47.241.0.3:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:27976845,ID:0000000001aae48d303e917ae02eff03b0ccb8a7d86f278264ba0808a6ca0a2d, end block Num:27978864,ID:0000000001aaec70f794a23300d7d0e52874a005ad9a737c997b4e79ae7b7d1d 
05:42:01.524 INFO  [TronJClientWorker-82] [net](MessageQueue.java:121) Receive from /47.241.0.3:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:27978864,ID:0000000001aaec70f794a23300d7d0e52874a005ad9a737c997b4e79ae7b7d1d, end blockId: Num:27980864,ID:0000000001aaf440e54f5e458c09650fd350983184b5a0567a80700ea4447371
05:42:09.075 INFO  [pool-34-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 9, active 9, passive 0

Peer 51.38.62.207:18888 [433cee23]
ping msg: count 159, max-average-min-last: 169 19 12 16
connect time: 30s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:27976865
syncBlockRequestedSize:0
remainNum:24401
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 250(0), discover: 1/1 0/0 0/0 0/0 12ms, p2p: 80/80/86 , tron: 550/561 X 1<=TIME_OUT , tcp flow: 328200

Peer 135.181.180.102:18888 [b7e578a1]
ping msg: count 146, max-average-min-last: 47 29 23 30
connect time: 23s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:27976865
syncBlockRequestedSize:0
remainNum:24404
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 230(0), discover: 1/1 0/0 2691/2691 0/0 23ms, p2p: 77/77/77 , tron: 2024/545 X 3<=TIME_OUT , tcp flow: 1312800

Peer 47.90.215.84:18888 [9f143956]
ping msg: count 121, max-average-min-last: 341 106 99 101
connect time: 23s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:27976865
syncBlockRequestedSize:0
remainNum:24404
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 230(0), discover: 1/1 0/0 902/902 767/767 99ms, p2p: 64/64/65 , tron: 955/444 X 2<=TIME_OUT , tcp flow: 492300

Peer 47.105.117.128:18888 [41b6d3c8]
ping msg: count 68, max-average-min-last: 552 209 162 215
connect time: 12s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:27976865
syncBlockRequestedSize:0
remainNum:24407
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 224(0), discover: 1/1 0/0 0/0 0/0 206ms, p2p: 40/40/51 , tron: 444/279 X 2<=TIME_OUT , tcp flow: 492302

Peer 165.227.141.213:18888 [0acedcd3]
ping msg: count 1056, max-average-min-last: 19299 215 3 8
connect time: 974s
last know block num: 27550701
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:426163
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 211(0), discover: 1/1 1/1 0/0 0/0 5ms, p2p: 43/43/48 , tron: 2338/16229 X 3<=PING_TIMEOUT=>DUPLICATE_PEER, tcp flow: 19350

Peer 47.75.163.60:18888 [26de9c55]
ping msg: count 63, max-average-min-last: 411 230 217 238
connect time: 26s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:27976865
syncBlockRequestedSize:0
remainNum:24402
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 233(0), discover: 1/1 0/0 0/0 0/0 258ms, p2p: 34/34/50 , tron: 730/252 X 1 =>TOO_MANY_PEERS, tcp flow: 1148700

Peer 47.241.0.3:18888 [a60cad77]
ping msg: count 48, max-average-min-last: 390 253 233 261
connect time: 8s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:27976865
syncBlockRequestedSize:0
remainNum:24409
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 243(0), discover: 1/1 0/0 432/432 0/0 333ms, p2p: 28/28/48 , tron: 185/208 X 0  , tcp flow: 1640989

Peer 183.230.39.133:18888 [4126b2c6]
ping msg: count 99, max-average-min-last: 1684 255 185 254
connect time: 12s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:27976865
syncBlockRequestedSize:0
remainNum:24407
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 225(0), discover: 1/1 1/1 0/0 0/0 184ms, p2p: 54/54/54 , tron: 964/379 X 2<=TIME_OUT , tcp flow: 492302

Peer 47.75.246.83:18888 [399239bb]
ping msg: count 70, max-average-min-last: 2902 274 215 220
connect time: 15s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:27976865
syncBlockRequestedSize:0
remainNum:24406
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 234(0), discover: 1/1 0/0 0/0 0/0 230ms, p2p: 37/37/54 , tron: 652/277 X 1<=TIME_OUT , tcp flow: 328204

05:42:09.185 WARN  [pool-47-thread-1] [net](PeerStatusCheck.java:49) Peer /51.38.62.207 not sync for a long time.
05:42:09.186 INFO  [pool-47-thread-1] [net](Channel.java:129) Send to /51.38.62.207:18888 online-time 30s, type: P2P_DISCONNECT
reason: TIME_OUT
05:42:09.190 INFO  [TronJClientWorker-74] [net](TronChannelInitializer.java:48) Close channel:/51.38.62.207:18888 | 433cee230fcae6a422629b26de5de76395381644ddbbc668b6e035cbf4c93da221db0281340ba47c216e42a8059fe638ab563df1eaad3aa9beff235a5d9ad7d5
05:42:10.889 INFO  [pool-33-thread-1] [net](PeerClient.java:70) connect peer 51.255.85.155 18888 15704aed027c2a50a538c8e7f6251fdd1f1eaa2884521a8331de8043652f8178bafefd8361fa44116f81e8573c669d8eb6349bf730c059a2411478d851976bee
05:42:10.903 INFO  [TronJClientWorker-83] [net](HandshakeHandler.java:77) channel active, /51.255.85.155:18888
05:42:10.903 INFO  [TronJClientWorker-83] [net](HandshakeHandler.java:130) Handshake send to /51.255.85.155:18888, type: P2P_HELLO
from {
  address: "188.34.132.30"
  port: 18888
  nodeId: "\266\247[a\323\275V\"\361\3554\250\'\365E\000\356\246o\027\342\275\303C\r\311\242]X|\325\342\214\224\005b\226Y\250r\371\275\335\222\355\321\a/vQ\323\341~\272[\017\266\215\025O\210\366\2735"
}
version: 11111
timestamp: 1614404530903
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\036\277\210P\212\003\206\\q\324R\342_MQ\031A\226\241\322+fS\334"
}
solidBlockId {
  hash: "\000\000\000\000\001\252\344\216w.\327\202\311\021I\260sh\\\\Q0aY\367\225p)\240\3458\001"
  number: 27976846
}
headBlockId {
  hash: "\000\000\000\000\001\252\344\240 \266\276\320P&m\351>\031\2444\242dU\270\273\314\323\021\016tt\304"
  number: 27976864
}

**Comment by pthor11** [comment]
I've got this problem too.

**Comment by pion33r** [comment]
I replaced the Fullnode.jar with the [recent release](https://github.com/tronprotocol/java-tron/releases), Extracted the trongrid backup again and started syncing again. So far it's syncing good. Thanks to Telegram group.
