### ISSUE TITLE
Is there a limit on the size of contract xx.sol file? eth limit 24576 bytes

### ISSUE THREAD

**Issue by Zz451117872** [tronprotocol/java-tron#3661]
Is there a limit on the size of contract xx.sol file? eth limit 24576 bytes

**Comment by andelf** [comment]
Hard to say.

Max block size of Tron is 2_MB.
Max transaction size of Tron is 500_KiB.
Max fee limit of the current mainnet is 5000_TRX.
Max duration of a smart execution(create/trigger) is 50ms.

current energy price is 140sun/point.

So the answer might be  5000_000_000 / 140 / 200 = 174KiB.

**Comment by Zz451117872** [comment]
Why divide by 200

**Comment by andelf** [comment]
I forgot to mention that deploying a contract requires 200x(runtime code size).

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 
Please feel free to re-open this issue if you still see it, thanks.
