### ISSUE TITLE
out_of_time

### ISSUE THREAD

**Issue by Zz451117872** [tronprotocol/java-tron#3662]
My contract is prone to out_of_time exceptions. 
I deploy it on the docker-tron-quickstart test node. 
I want to know which code are more time-consuming？
the code consume more energy，does it mean consume more time?

**Comment by yanghang8612** [comment]
> the code consume more energy，does it mean consume more time?

In general, you are right. Out_Of_Time excepitons may cause by complex contracts or some infinite loops.
Check more detail from this guide: https://developers.tron.network/docs/timeout-and-infinite-loop-pitfalls
>I want to know which code are more time-consuming？

Check energy costs for all opcodes from this guide: https://developers.tron.network/docs/energy-cost

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 
Please feel free to re-open this issue if you still see it, thanks.
