### ISSUE TITLE
Tron Transaction Error

### ISSUE THREAD

**Issue by anvarisoraya** [tronprotocol/java-tron#3663]
### 1. What did you do?

I try to sign the Tron transaction, which I created, with the offline tool. As I do not want to send my private key to tronWeb.trx.sign. I append my signature to tradeobj. But when I want to broadcast the transaction to Tron Shasta Testnet, I got this error:
validate signature error Header byte out of range: 66

### 2. What did you expect to see?
I expect to get a true response from sending the transaction.

### 3. What did you see instead?
Does anyone know what is the problem with signing a transaction by our own?

**Comment by cathy-lishipu** [comment]
You can check if the signature is correct when broadcasting the transaction. Ref: https://developers.tron.network/reference#sign

**Comment by anvarisoraya** [comment]
> You can check if the signature is correct when broadcasting the transaction. Ref: https://developers.tron.network/reference#sign

I know that! My question was how to sign the private key locally, without using tronobj.sign

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 
Please feel free to re-open this issue if you still see it, thanks.
