### ISSUE TITLE
Compiler version issue

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3665]
1. What did you do?
The below contract can be deployed successfully in tron command-line. 
"https://shasta.tronscan.org/#/contract/TRvaNUC461gqAqsMGwjdPGaBBG6nu9bG6i/code" 
I try to deploy 0.5.10 version contract in tron command-line. The result will be **Illegal_Operation**
Sample Code: "https://shasta.tronscan.org/#/contract/TWKfBbyrrLkZaaxjmb6rY5Mc9fGr2F8yT2/code"

2. What did you expect to see?
The result will be successful when i deploy any version in solidity file

3. What did you see instead?
![image](https://user-images.githubusercontent.com/48212011/110200177-a42a0e80-7e82-11eb-8517-2e18160ab114.png)

**Comment by andelf** [comment]
Your private node hash `AllowTvmTransferTrc10` disabled

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 
Please feel free to re-open this issue if you still see it, thanks.
