### ISSUE TITLE
Full Node stalled at block 28158974

### ISSUE THREAD

**Issue by BisonAl** [tronprotocol/java-tron#3666]
### 1. What did you do?
I built tron `v4.1.2` from source, using the `release_v.4.1.2` branch: https://github.com/tronprotocol/java-tron/tree/release_v4.1.2

However it seems some additional commits were sent to the `GreatVoyage-v.4.1.2` branch as well if you look at https://github.com/tronprotocol/java-tron/compare/GreatVoyage-v4.1.2...release_v4.1.2

### 2. What did you expect to see?
I expected I was on the latest `v4.1.2` release, which unfortunately was not the case.
I also expected the node to continue syncing uninterrupted, with its peer connections healthy.

### 3. What did you see instead?
My node instead came to a halt and stopped syncing at block `28158974` - similar to the recent stall at block `27465569 ` https://github.com/tronprotocol/java-tron/issues/3643. Most, if not all of it's p2p connections have also been timing out or erroring.

However I had actually already hit that block `27465569 ` stall, and even jotted down some notes to https://github.com/tronprotocol/java-tron/issues/3580#issuecomment-781393226. At the time of writing this is 16 days ago, and I'm convinced that this is actually a new stall - now `~700,000` blocks further into the chain.

The way I got past the stall at around `27465569` was by upgrading our tron configuration from branch `release_v4.1` -> `release_v4.1.2`, which is detailed by [this diff](https://github.com/tronprotocol/java-tron/compare/release_v4.1...release_v4.1.2). 

So I had thought I was already running `v4.1.2`, and evidently if I wasn't I shouldn't have been able to make it past this block `27465569` back then. This is consistent with the resolution found in https://github.com/tronprotocol/java-tron/issues/3643 as well.
I've actually been running a number of additional nodes simultaneously, and with one node was able to verify that on `release_v4.1` it would stall at block `27465569` - and that upgrading to `release_v.4.1.2` would allow it to continue syncing.

#### Confguration
My configuration is mostly based off https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf, with some changes that I've gleaned over time from the tron team.

Some notable modifications I've made:
- Increased node discovery timeouts:
```
    node.discovery = {
      enable = true
      persist = true
      bind.ip = ""
      external.ip = null
      ping.timeout = 50000
    }
```
- VM tuning
```
    vm = {
      supportConstant = false
      minTimeRatio = 0.0
      maxTimeRatio = 100.0
      saveInternalTx = false
    
      # In rare cases, transactions that will be within the specified maximum execution time (default 10(ms)) are re-executed and packaged
      # longRunningTime = 10
    }
```
- Peering with official Tron fullnodes from https://developers.tron.network/docs/official-public-node:
```
      active = [
        # Active establish connection in any case
        # Sample entries:
        # "ip:port",
        # "ip:port"
        "3.225.171.164:18888",
        ...
      ]
```

#### Distributed Failure
Notably, I have had 2 independent nodes stall at the exact same block. Each of those nodes are running in different locations geologically, and use different providers alltogether. The unifying factor between these 2 nodes is that they were both built from source using the `release_v.4.1.2` branch.

**Update:** We've since seen this failure on even more nodes across different regions, across Asia/Europe/North-America

#### Hardware
Worried hardware might be the barrier, I also opted to move one of these nodes to a High Memory **32cpu**/**256GB** Ram machine.
I then ran the `fullNode` jar like so:
```
    Command:
      java
    Args:
      -Xmx180g
      -XX:+UseConcMarkSweepGC
      -jar
      FullNode.jar
      -c
      /path/to/my_config.conf
      --log-config
      /path/to/logback.xml
      --es
      --debug
```
So I am doubtful hardware is a limiting factor here. Even on this machine, this nodes^ cpu and memory usage were very low.

#### Eventquery Note
My nodes are additionally talking to a mongodb sidecar database, using the [official eventquery indexer ](https://github.com/tronprotocol/tron-eventquery). However I'm doubtful that it's an interaction between these two that's causing the stall - if there's an issue with the eventquery sidecar the full node will typically just sync ahead of it.

#### Logs
Digging through the logs of each of these nodes, `grep Error` | `grep Corruption` | `grep err` | `grep GC` all return nothing, literally not a single line. Although these nodes were stalling, they were actually not logging a single error. This hasn't changed in at least 20 restarts now.

The relevant portions of our `logback.xml` file if interested - 
```
      <logger level="INFO" name="app"/>
      <logger level="INFO" name="net"/>
      <logger level="INFO" name="backup"/>
      <logger level="INFO" name="discover"/>
      <logger level="INFO" name="crypto"/>
      <logger level="INFO" name="utils"/>
      <logger level="INFO" name="actuator"/>
      <logger level="INFO" name="API"/>
      <logger level="INFO" name="witness"/>
      <logger level="INFO" name="DB"/>
      <logger level="INFO" name="capsule"/>
      <logger level="INFO" name="VM"/>
    
    </configuration>
```
we were of course still catching verbose logs otherwise, and have captured millions of `INFO` level statements from these stalled nodes.

What we did see from the logs has essentially been:
1. Node takes 5 minutes or so to bootup
2. Node Tries to start syncing again from block `28158974`
3. Node establishes its 9+ peer connections
4. Node tries to sync additional blocks, retrying again and again maybe 10 times
5. Most or all of the node's peer connections time out
6. The node then cycles back to step 2^

In an endless loop.

### 5. Potential Root Cause
Thanks to some telegram help, I took a look inside the running tron instance, and queried the http port for the following:
```
curl http://localhost:8091/wallet/getnodeinfo
```

Digging into this, I saw that my node actually believed it was running:
```
"codeVersion": "4.1.1"
```

Which apparently had not been updated in the [release_v.4.1.2 branch](https://github.com/tronprotocol/java-tron/tree/release_v4.1.2).

I made absolutely certain that we were in fact running this branch^; we had actually rebuilt tron from source using https://github.com/tronprotocol/java-tron/tree/release_v4.1.2 3+ times in our debugging efforts.

I built it one more time to be sure, and reconfirmed after updating the node to that querying `curl http://localhost:8091/wallet/getnodeinfo` would still return 
```
"codeVersion": "4.1.1"
```

Verified that this is likely the expected behavior, if you look to this github diff between the `release_v.4.1.2` and `GreatVoyage-v4.1.2` branches: [see this change in paticular](https://github.com/tronprotocol/java-tron/compare/GreatVoyage-v4.1.2...release_v4.1.2#diff-b7f5229b5661a6195a1c5e7b2d3cfa01bdc58a0ea02c48757f799f9e27412e09R17)

Is it possible that this could have caused my node to stall?

**Comment by BisonAl** [comment]
Our nodes are still stuck at block `28158974` in the meantime. My next step is going to be building either https://github.com/tronprotocol/java-tron/tree/GreatVoyage-v4.1.2 or https://github.com/tronprotocol/java-tron/tree/release_v4.1.3.

I thought it made the most sense to build from the release branches, which you can see with: https://github.com/tronprotocol/java-tron/branches/all?query=release

However if these aren't a good source of truth I can modify my builds.

**Comment by BisonAl** [comment]
Rebuilt our image from https://github.com/tronprotocol/java-tron/tree/GreatVoyage-v4.1.2  but our node is still stalled, seems both `release_v.4.1.2` and the official `GreatVoyage4.1.2` branches are breaking.

**Comment by 1doce8** [comment]
I have the same problem. Please help

**Comment by LyyDandelion** [comment]
same problem

**Comment by Benson0224** [comment]
Please check this guide syncing issue, thanks.
https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

**Comment by BisonAl** [comment]
Hey @Benson0224, if you read through the issue you'll see that we're already trying everything listed in https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization.

I understand that jvm settings can be a potential root cause for the chain stalling, however I think it's fair to say we've ruled that out in this instance.

**Comment by Benson0224** [comment]
> Hey @Benson0224, if you read through the issue you'll see that we're already trying everything listed in https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization.
> 
> I understand that jvm settings can be a potential root cause for the chain stalling, however I think it's fair to say we've ruled that out in this instance.

Could you please help to provide the log of the node, so we can help to do further investigation, thanks.

**Comment by BisonAl** [comment]
It's not well tracked in this issue, but I've been sending logs back and forth with @Alexliu007 over telegram. Of the last logs we sent, the one identifying error Alex picked up on was:
```
18:32:51.340 ERROR [pool-49-thread-1] [net](TronNetDelegate.java:237) Process block failed, Num:28158999,ID:0000000001adac17a7690fdd156e99c3cf674691729a485ab3d4100909041943, reason: Different resultCode.
18:32:51.340 ERROR [pool-49-thread-1] [net](SyncService.java:269) Process sync block Num:28158999,ID:0000000001adac17a7690fdd156e99c3cf674691729a485ab3d4100909041943 failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:238)
	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:266)
	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:255)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:238)
	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
```

However this was on the same **32cpu/256GB** machine we originally posted info from, running with the following args:
```
    Command:
      java
    Args:
      -Xmx180g
      -XX:+UseConcMarkSweepGC
      -jar
      FullNode.jar
      -c
      /path/to/my_config.conf
      --log-config
      /path/to/logback.xml
      --es
      --debug
```

So we were unsure why this could have been happening. We ran into this stall at block `28158974 ` on dozens of different machines and configurations

**Comment by LyyDandelion** [comment]
ok,dead block 28762211. log info:
`============ Peer stats: all 7, active 7, passive 0

Peer 47.254.129.80:18888 [896dd996]
ping msg: count 0, max-average-min-last: 0 0 0 0
connect time: 1s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:28762212
syncBlockRequestedSize:0
remainNum:20106
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 239(0), discover: 1/1 0/0 0/0 0/0 251ms, p2p: 1/1/1 , tron: 3/3   , tcp flow: 164092

Peer 47.252.16.203:18888 [1e35ee14]
ping msg: count 7, max-average-min-last: 224 222 219 219
connect time: 1s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:28762212
syncBlockRequestedSize:0
remainNum:20106
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 204(0), discover: 1/1 0/0 0/0 0/0 219ms, p2p: 5/5/5 , tron: 30/31 X 4<=TIME_OUT , tcp flow: 656398

Peer 47.90.209.213:18888 [f7bcc5f8]
ping msg: count 4, max-average-min-last: 227 223 220 227
connect time: 8s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:28762212
syncBlockRequestedSize:0
remainNum:20104
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 224(0), discover: 1/1 0/0 0/0 0/0 218ms, p2p: 3/3/3 , tron: 17/17 X 2<=TIME_OUT , tcp flow: 492292

Peer 47.91.75.144:18888 [0c7a9afb]
ping msg: count 1, max-average-min-last: 244 244 244 244
connect time: 30s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:28762212
syncBlockRequestedSize:0
remainNum:20097
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 239(0), discover: 1/1 0/0 0/0 0/0 251ms, p2p: 1/1/1 , tron: 5/5   , tcp flow: 164096

Peer 8.209.102.140:18888 [00206e52]
ping msg: count 4, max-average-min-last: 259 250 245 259
connect time: 1s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:28762212
syncBlockRequestedSize:0
remainNum:20106
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 214(0), discover: 1/1 0/0 0/0 0/0 243ms, p2p: 4/4/4 , tron: 22/24 X 3<=TIME_OUT , tcp flow: 656388

Peer 8.209.76.78:18888 [6562d32e]
ping msg: count 6, max-average-min-last: 264 254 248 248
connect time: 8s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:28762212
syncBlockRequestedSize:0
remainNum:20104
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 214(0), discover: 1/1 0/0 0/0 0/0 245ms, p2p: 4/4/4 , tron: 23/24 X 3<=TIME_OUT , tcp flow: 656390

Peer 15.236.149.86:18888 [6704a592]
ping msg: count 1, max-average-min-last: 324 324 324 324
connect time: 30s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:28762212
syncBlockRequestedSize:0
remainNum:20097
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 239(0), discover: 1/1 0/0 0/0 0/0 324ms, p2p: 1/1/1 , tron: 5/5   , tcp flow: 164096


17:44:34.571 WARN  [pool-50-thread-1] [net](PeerStatusCheck.java:49) Peer /47.91.75.144 not sync for a long time.
17:44:34.571 INFO  [pool-50-thread-1] [net](Channel.java:129) Send to /47.91.75.144:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
17:44:34.571 WARN  [pool-50-thread-1] [net](PeerStatusCheck.java:49) Peer /15.236.149.86 not sync for a long time.
17:44:34.571 INFO  [pool-50-thread-1] [net](Channel.java:129) Send to /15.236.149.86:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
17:44:34.580 INFO  [TronJClientWorker-54] [net](TronChannelInitializer.java:48) Close channel:/47.91.75.144:18888 | 0c7a9afb64ac09c78ce69783691f5f6509f38837ed551a866f9d39f7d8109a489528ddbff2b1b67211cfd49796ceb7961b75c74a406f349b194f48b86e84d42a
17:44:34.580 INFO  [TronJClientWorker-53] [net](TronChannelInitializer.java:48) Close channel:/15.236.149.86:18888 | 6704a592dcb1a67e498a00ae16bc4e8127e87af65618b09b2f64659f9d0d98c937f4bad6866729cc18c851c30ee4ffef9c54d016eb0b8e95856a384eb7407ac4
17:44:34.597 INFO  [TronJClientWorker-62] [net](HandshakeHandler.java:92) Handshake receive from /54.36.114.4:18888, type: P2P_HELLO
from {
  address: "54.36.114.4"
  port: 18888
  nodeId: "\n\310\365\026B\371\030L\336\334${\354\344\022\243\240+\374\255\335\254\312\211\347\211\225\323\377\261B\0376\237d\3564W9e\237\003\023\363!\350\"\325\231\334\246\023WA\351\2526\366\005\177T\223\265/"
}
version: 11111
timestamp: 1616751871490
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\036\277\210P\212\003\206\\q\324R\342_MQ\031A\226\241\322+fS\334"
}
solidBlockId {
  hash: "\000\000\000\000\001\267>r\213\323\352\241*s7\217\246z3y\201\217\016\201;{\360%\231\023\234a"
  number: 28786290
}
headBlockId {
  hash: "\000\000\000\000\001\267>\204*\205\340\n \343,\327ZU\251\365\250!\377d\363\2032\216j\035\f\027"
  number: 28786308
}

17:44:34.598 INFO  [TronJClientWorker-62] [net](Channel.java:201) Peer /54.36.114.4:18888 status change to HANDSHAKE_FINISHED.
17:44:34.598 INFO  [TronJClientWorker-62] [net](Channel.java:111) Finish handshake with /54.36.114.4:18888.
17:44:34.599 INFO  [TronJClientWorker-62] [net](ChannelManager.java:161) Add active peer /54.36.114.4:18888 | 0ac8f51642f9184cdedc247bece412a3a02bfcadddacca89e78995d3ffb1421f369f64ee345739659f0313f321e822d599dca6135741e9aa36f6057f5493b52f, total active peers: 6
17:44:34.599 INFO  [TronJClientWorker-62] [net](Channel.java:201) Peer /54.36.114.4:18888 status change to SYNCING.
17:44:34.599 INFO  [TronJClientWorker-62] [net](Channel.java:201) Peer /54.36.114.4:18888 status change to SYNCING.
17:44:34.599 INFO  [TronJClientWorker-62] [DB](Manager.java:1520) headNumber:28762211
17:44:34.599 INFO  [TronJClientWorker-62] [DB](Manager.java:1522) syncBeginNumber:28762192
17:44:34.599 INFO  [TronJClientWorker-62] [DB](Manager.java:1526) solidBlockNumber:28762193
`

**Comment by LyyDandelion** [comment]
java -Xmx32g -XX:+UseConcMarkSweepGC -jar FullNode.jar  -c main_net_config.conf

**Comment by BisonAl** [comment]
Thanks @LyyDandelion I have been seeing those same exact logs as well^

Particularly those p2p timeouts like:
```
NodeStat[reput: 214(0), discover: 1/1 0/0 0/0 0/0 245ms, p2p: 4/4/4 , tron: 23/24 X 3<=TIME_OUT , tcp flow: 656390
```
have been a constant factor so long as the blockchain is stalling - suggesting all our outbound p2p connections are getting dropped. 
My hypothesis is that because the node isn't able to peer correctly, it can't begin to sync correctly either

**Comment by Benson0224** [comment]
> It's not well tracked in this issue, but I've been sending logs back and forth with @Alexliu007 over telegram. Of the last logs we sent, the one identifying error Alex picked up on was:
> 
> ```
> 18:32:51.340 ERROR [pool-49-thread-1] [net](TronNetDelegate.java:237) Process block failed, Num:28158999,ID:0000000001adac17a7690fdd156e99c3cf674691729a485ab3d4100909041943, reason: Different resultCode.
> 18:32:51.340 ERROR [pool-49-thread-1] [net](SyncService.java:269) Process sync block Num:28158999,ID:0000000001adac17a7690fdd156e99c3cf674691729a485ab3d4100909041943 failed.
> org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
> 	at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:238)
> 	at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:266)
> 	at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:255)
> 	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
> 	at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:238)
> 	at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:81)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> ```
> 
> However this was on the same **32cpu/256GB** machine we originally posted info from, running with the following args:
> 
> ```
>     Command:
>       java
>     Args:
>       -Xmx180g
>       -XX:+UseConcMarkSweepGC
>       -jar
>       FullNode.jar
>       -c
>       /path/to/my_config.conf
>       --log-config
>       /path/to/logback.xml
>       --es
>       --debug
> ```
> 
> So we were unsure why this could have been happening.
> We ran into this stall at block `28158974 ` on dozens of different machines and configurations, that `Process block failed` failure has been a common factor across them.

Regarding the " Different resultCode" ， Please increase the value of maxTimeRatio in config file, such as 50 or 100. and it should be ok after you restart the fullnode.

![image](https://user-images.githubusercontent.com/61768920/113111114-6c707580-923a-11eb-87f7-2f5260e2761c.png)

**Comment by Benson0224** [comment]
Since there is no full log,  we cannot do further investigation for your case, here is the suggestion. 
1. Download the latest binary release from https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.1.3
2. Download the latest snapshot data. 
3. Start the FullNode.jar and share the full log if you still face this issue. 
Thanks.

**Comment by BisonAl** [comment]
Even if we dumped our entire data directory and download an official snapshot, what's the guarantee this won't just happen again a few weeks from now?

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
