### ISSUE TITLE
sync fail

### ISSUE THREAD

**Issue by LyyDandelion** [tronprotocol/java-tron#3681]
### 1. What did you do?

I want sync fullNode.jar.

### 2. What did you expect to see?
finished,and the point `s block height is newest height.

### 3. What did you see instead?
 current headNum is: 28306329,and was untils
`16:53:20.556 INFO  [main] [app](FullNode.java:62) not in debug mode, it will check energy time
16:53:20.736 INFO  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:578) Refreshing org.tron.common.application.TronApplicationContext@3541cb24: startup date [Mon Mar 15 16:53:20 CST 2021]; root of context hierarchy
16:53:22.689 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
16:53:22.993 INFO  [main] [app](DefaultConfig.java:58) key-value data source created.
16:53:24.551 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractLogTriggerMap
16:53:24.551 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractEventTriggerMap
16:53:24.661 INFO  [main] [discover](NodeManager.java:78) homeNode : Node{ host='0.0.0.0', port=18889, id=4f2d3ecfdd33397e54951acfdf29f8047f11b8b069ce12326ce2298fbe3d02b607891c86d7c9d3a040a15c901994db927a5b4d278e58620b79f03a404b612a2f}
16:53:55.338 INFO  [main] [DB](Manager.java:534) begin to init txs cache.
16:53:55.338 INFO  [main] [DB](Manager.java:541) current headNum is: 28306329
^C
[root@localhost logs]# screen -r fullNode
[detached from 50919.fullNode]
[root@localhost logs]# tail -20f tron.log 
16:53:20.554 INFO  [main] [app](Args.java:1067) Backup listen keepAliveInterval: 3000
16:53:20.554 INFO  [main] [app](Args.java:1068) Backup member size: 0
16:53:20.554 INFO  [main] [app](Args.java:1069) ************************ Code version *************************
16:53:20.555 INFO  [main] [app](Args.java:1070) Code version : 4.1.2
16:53:20.555 INFO  [main] [app](Args.java:1071) Version code: 15262
16:53:20.555 INFO  [main] [app](Args.java:1072) ************************ DB config *************************
16:53:20.555 INFO  [main] [app](Args.java:1073) DB version : 2
16:53:20.555 INFO  [main] [app](Args.java:1074) DB engine : LEVELDB
16:53:20.555 INFO  [main] [app](Args.java:1075) ***************************************************************
16:53:20.555 INFO  [main] [app](Args.java:1076) 

16:53:20.556 INFO  [main] [app](FullNode.java:62) not in debug mode, it will check energy time
16:53:20.736 INFO  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:578) Refreshing org.tron.common.application.TronApplicationContext@3541cb24: startup date [Mon Mar 15 16:53:20 CST 2021]; root of context hierarchy
16:53:22.689 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
16:53:22.993 INFO  [main] [app](DefaultConfig.java:58) key-value data source created.
16:53:24.551 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractLogTriggerMap
16:53:24.551 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractEventTriggerMap
16:53:24.661 INFO  [main] [discover](NodeManager.java:78) homeNode : Node{ host='0.0.0.0', port=18889, id=4f2d3ecfdd33397e54951acfdf29f8047f11b8b069ce12326ce2298fbe3d02b607891c86d7c9d3a040a15c901994db927a5b4d278e58620b79f03a404b612a2f}
16:53:55.338 INFO  [main] [DB](Manager.java:534) begin to init txs cache.
16:53:55.338 INFO  [main] [DB](Manager.java:541) current headNum is: 28306329
16:57:01.983 INFO  [main] [DB](Manager.java:581) end to init txs cache. trx ids:7325939, block count:65536, empty block count:41, cost:186645
16:57:02.530 INFO  [main] [o.r.Reflections](Reflections.java:232) Reflections took 524 ms to scan 1 urls, producing 442 keys and 2525 values 
16:57:02.684 INFO  [main] [net](PeerConnectionCheckService.java:44) start the PeerConnectionCheckService
16:57:02.788 INFO  [DiscoverServer] [discover](DiscoverServer.java:102) Discovery server started, bind port 18889
16:57:03.011 INFO  [nioEventLoopGroup-2-1] [discover](NodeManager.java:123) Reading node statistics from store: 0 nodes.
16:57:03.462 INFO  [main] [app](FullNode.java:116) ********register application shutdown hook********
16:57:03.466 INFO  [main] [API](FullNodeHttpApiService.java:296) init zk param begin
16:57:04.283 INFO  [main] [API](FullNodeHttpApiService.java:317) init zk param done
16:57:04.493 INFO  [main] [API](RpcApiService.java:271) RpcApiService has started, listening on 50051
16:57:04.502 INFO  [main] [o.e.j.u.log](Log.java:193) Logging initialized @265132ms to org.eclipse.jetty.util.log.Slf4jLog
16:57:04.608 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 1.8.0_271-b09
16:57:04.652 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
16:57:04.652 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
16:57:04.655 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 600000ms
16:57:04.670 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@17dbca0a{/,null,AVAILABLE}
16:57:04.682 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@671f545b{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}
16:57:04.683 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @265312ms
16:57:04.699 INFO  [main] [API](RpcApiServiceOnSolidity.java:126) RpcApiServiceOnSolidity started, listening on 50061
16:57:04.702 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 1.8.0_271-b09
16:57:04.704 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
16:57:04.704 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
16:57:04.704 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 660000ms
16:57:04.706 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@3a5e4f32{/,null,AVAILABLE}
16:57:04.710 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@2b0494a8{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}
16:57:04.710 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @265340ms
16:57:04.717 INFO  [main] [API](RpcApiServiceOnPBFT.java:126) RpcApiServiceOnPBFT started, listening on 50071
16:57:04.718 WARN  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:1566) o.e.j.s.ServletContextHandler@414d2821{/,null,UNAVAILABLE} contextPath ends with /
16:57:04.719 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 1.8.0_271-b09
16:57:04.721 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
16:57:04.721 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
16:57:04.721 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 600000ms
16:57:04.723 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@414d2821{/walletpbft,null,AVAILABLE}
16:57:04.727 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@484876a1{HTTP/1.1,[http/1.1]}{0.0.0.0:8092}
16:57:04.727 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @265357ms
16:57:04.731 INFO  [main] [net](ChannelManager.java:86) Node config, trust 2, active 0, forward 2.
16:57:04.736 INFO  [main] [net](FastForward.java:61) Fast forward config, isWitness: false, keySize: 0, fastForwardNodes: 2
16:57:04.745 INFO  [main] [net](TronNetService.java:69) TronNetService start successfully.
16:57:04.746 WARN  [main] [app](LocalWitnesses.java:104) privateKey is null
16:57:04.746 WARN  [main] [consensus](ConsensusService.java:73) Witness 41dcc703c0e500b653ca82273b7bfad8045d85a470 is not in witnessStore.
16:57:04.751 INFO  [main] [consensus](ConsensusService.java:84) consensus service start success
16:57:04.752 INFO  [PeerServerThread] [net](PeerServer.java:54) TCP listener started, bind port 18889
16:57:34.734 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:57:44.734 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:57:54.735 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:58:03.014 INFO  [NodeManagerTasks] [discover](NodeManager.java:153) Write node statistics to store: m:29/t:0/0/0 nodes.
16:58:04.735 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:58:14.736 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:58:24.737 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:58:34.738 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:58:44.739 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:58:54.739 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:59:03.012 INFO  [NodeManagerTasks] [discover](NodeManager.java:153) Write node statistics to store: m:29/t:0/0/0 nodes.
16:59:04.740 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:59:14.740 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:59:24.740 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:59:34.741 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:59:44.742 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0

16:59:54.742 INFO  [pool-36-thread-1] [net](SyncPool.java:123) 

============ Peer stats: all 0, active 0, passive 0
`

**Comment by BisonAl** [comment]
Ah yeah I ran into the same with https://github.com/tronprotocol/java-tron/issues/3666. 

It's been a reoccurring issue for me that my nodes can't sync any new blocks, from what appears to be dying peer connections.

**Comment by Benson0224** [comment]
Please check this guide for fix: https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks

**Comment by begetan** [comment]
Why this issue is closed?

Is there any solution to make a FullNode working?
