### ISSUE TITLE
Server suddenly shutted down and synchronization was interrupted

### ISSUE THREAD

**Issue by piotrwatola** [tronprotocol/java-tron#3689]
My server suddenly shutted down and synchronization was interrupted. After starting java-tron, synchronization stops. Is there a chance to fix it or all i have to do is to restore the backup from https://backup.trongrid.io/ ?

**Comment by Alexliu007** [comment]
You can provide a complete log, but in this case there is a possibility of database corruption, you can use the latest backup data to resynchronize. backup: https://backup.trongrid.io/

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks.
