### ISSUE TITLE
WHEN ws connecting for events ?

### ISSUE THREAD

**Issue by DmytroShalaiev** [tronprotocol/java-tron#3699]
### 1. What did you do?

Cry.
event.watch() using tronWeb

### 2. What did you expect to see?
ws connecting for events .etc

### 3. What did you see instead?
Infinity looping HTTP endpoint /event with params

**Comment by Alexliu007** [comment]
Is it convenient to provide some simple examples? For related use of tronweb, please refer to the [document](https://developers.tron.network/reference#methodwatch)

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks.
