### ISSUE TITLE
http://tron.game.com does not redirect to https://tron.game.com

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [tronprotocol/java-tron#37]
Hi

Your site http://tron.game.com/#/home has no certificate.  This means logins can be stolen.  Can you please fix by having it redirect to https://tron.game.com?

![screenshot from 2018-01-03 13-41-29](https://user-images.githubusercontent.com/14250760/34534386-ee97b374-f08b-11e7-8291-4232a5623a14.png)

**Comment by JusticeForMikeBrown** [comment]
You are running nginx according to [SSL server test.](https://www.ssllabs.com/ssltest/analyze.html?d=tron.game.com) so please see [these steps](https://zaiste.net/posts/rewrite_http_to_https_in_nginx/).

**Comment by sasaxie** [comment]
Yes, I will notify the relevant personnel for processing.

**Comment by sasaxie** [comment]
Support it, but did not redirect.

**Comment by JusticeForMikeBrown** [comment]
Thanks @sasaxie I also emailed ```support@game.com```

**Comment by JusticeForMikeBrown** [comment]
Can you please fix?  No reply from ```support@game.com```.  **This is a really bad misconfiguration**!

**Comment by sasaxie** [comment]
Someone will reply to you.

**Comment by JusticeForMikeBrown** [comment]
Thank you @sasaxie!

**Comment by JusticeForMikeBrown** [comment]
It has been fixed.  Thanks a lot!!!
