### ISSUE TITLE
SERVER_BUSY

### ISSUE THREAD

**Issue by StephanDre** [tronprotocol/java-tron#3709]
SERVER_BUSY problem

Tonight I had a problem with node - "SERVER_BUSY"
In faq tron ​​(https://developers.tron.network/docs/faq) I read that the default value for maxTransactionPendingSize is 2000, but in my and official config for the node there is no this variable so i added to cfg like this:

maxTransactionPendingSize = 5000

Then I restarted the node, the node started but I don't know if it has changed.
For me and the company that this is very important because we are pushing 50.000 transactions in one day, I was also looking at the node logs and http api "getnodeinfo" but there is no information about maxTransactionPendingSize, is any method to check this value ?

**Comment by jamestompson** [comment]
The code to parse maxTransactionPendingSize is as follow：

PARAMETER.maxTransactionPendingSize = config.hasPath(Constant.NODE_MAX_TRANSACTION_PENDING_SIZE)
        ? config.getInt(Constant.NODE_MAX_TRANSACTION_PENDING_SIZE) : 2000;

NODE_MAX_TRANSACTION_PENDING_SIZE is defined as "node.maxTransactionPendingSize"

so your config value should be included in

 node{
    maxTransactionPendingSize = 5000
}

BTW, you don't need to change your configuration. The default 2000 is enough for your business. 

You can sleep every 100ms to send the transaction.
