### ISSUE TITLE
TRC20 fee estimator

### ISSUE THREAD

**Issue by StephanDre** [tronprotocol/java-tron#3710]
1.Hi, i would like calculate fee for transfer trc20, what is the best way ? Maybe is any api ?
2.Is any method to pay for fee from other address ?

**Comment by Alexliu007** [comment]
1.The bandwidth is calculated based on the number of bytes encoded by the transaction protobuf.
Energy is deducted based on the instructions executed by the contract. Different instructions are deducted differently. The more complex the contract, the more energy will be consumed. The energy consumed by the current contract can be estimated by testing on the testnet or viewing the previous historical calls of the contract through tronscan.
Resource model can refer to the document
2.You can use wallet/freezebalance freeze TRX to grant Energy or Bandwidth to other users.
