### ISSUE TITLE
Alternative for evm_increaseTime?

### ISSUE THREAD

**Issue by martianatwork** [tronprotocol/java-tron#3712]
### 1. What did you do?
Trying test my smart contract based on time.

### 2. What did you expect to see?
Change the time in TVM test future transactions.

**Comment by yanghang8612** [comment]
This feature is not supported in TVM. Thanks for your issus.

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
