### ISSUE TITLE
Problem with event server

### ISSUE THREAD

**Issue by Grigoriy555** [tronprotocol/java-tron#3713]
Hello.
I have a raised full tron node (working normally) and kafva server for event server. 
Kafka server is launched, logs are writing. It can be seen that the events are being worked out.
Full node answers normally for http requst, type "http://my_ip:8090/wallet/getnowblock"
But for requests to the event server like "http://my_ip:8090/v1/contracts/TWiti6GpPJPRXtCFKURdTtxN7UEcurQoeS/events" i have a 404 http error. 
What am I doing wrong?

---------------------------
--------------------------- 
LOGS:
root@ns3115251:~/tron/logs# tail -f tron.log |grep -i eventplugin

13:02:17.635 INFO  [main] [o.t.c.l.EventPluginLoader](EventPluginLoader.java:365) start loading '/root/tron/event-plugin/build/plugins/plugin-kafka-1.0.0.zip'
13:02:17.664 INFO  [main] [o.t.c.l.EventPluginLoader](EventPluginLoader.java:399) '/root/tron/event-plugin/build/plugins/plugin-kafka-1.0.0.zip' loaded
---------------------------
---------------------------

--event plugin conf:
event.subscribe = {
    path = "/root/tron/event-plugin/build/plugins/plugin-kafka-1.0.0.zip" // absolute path of plugin
    server = "127.0.0.1:9092" // target server address to receive event triggers
    topics = [
        {
          triggerName = "block" // block trigger, the value can't be modified
          enable = false
          topic = "block" // plugin topic, the value could be modified
        },
        {
          triggerName = "transaction"
          enable = false
          topic = "transaction"
        },
        {
          triggerName = "contractevent"
          enable = true
          topic = "contractevent"
        },
        {
          triggerName = "contractlog"
          enable = true
          topic = "contractlog"
        },
        {
          triggerName = "solidity" // solidity block event trigger, the value can't be modified
          enable = true            // the default value is true
          topic = "solidity"
        },
        {
          triggerName = "solidityevent"
          enable = false
          topic = "solidityevent"
        },
        {
          triggerName = "soliditylog"
          enable = false
          topic = "soliditylog"
        }
    ]

    filter = {
       fromblock = "" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
       toblock = "" // the value could be "", "latest" or a specified block number as end of the queried range
       contractAddress = [
           "" // contract address you want to subscribe, if it's set to "", you will receive contract logs/events with any contract address.
       ]

       contractTopic = [
           "" // contract topic you want to subscribe, if it's set to "", you will receive contract logs/events with any contract topic.
       ]
    }
}

**Comment by neoromantique** [comment]
:eyes:

**Comment by woaichixigua07** [comment]
hi, /v1/contracts/xxx this interface is only provided by Trongrid for query, there is no such interface in Kafka.

**Comment by Grigoriy555** [comment]
And what is the correct way to access the event server on a local node?

**Comment by Alexliu007** [comment]
> And what is the correct way to access the event server on a local node?
For details, please refer to the [documentation](https://github.com/tronprotocol/event-plugin) and the way Kafka consumes data.

**Comment by neoromantique** [comment]
> hi, /v1/contracts/xxx this interface is only provided by Trongrid for query, there is no such interface in Kafka.

Is it possible to deploy the trongrid(Eventron) locally?

**Comment by Grigoriy555** [comment]
> > And what is the correct way to access the event server on a local node?
> 
> For details, please refer to the [documentation](https://github.com/tronprotocol/event-plugin) and the way Kafka consumes data.

I raised the kafka server using this documentation, but I can't figure out how to access it ...

**Comment by Alexliu007** [comment]
It is recommended that you find relevant information about the use of [kafka](https://kafka.apache.org/documentation.html).

**Comment by Benson0224** [comment]
> > > And what is the correct way to access the event server on a local node?
> > 
> > 
> > For details, please refer to the [documentation](https://github.com/tronprotocol/event-plugin) and the way Kafka consumes data.
> 
> I raised the kafka server using this documentation, but I can't figure out how to access it ...

Please  refer to this guide: https://developers.tron.network/docs/event-plugin-deployment-mongodb

**Comment by Grigoriy555** [comment]
> > > > And what is the correct way to access the event server on a local node?
> > > 
> > > 
> > > For details, please refer to the [documentation](https://github.com/tronprotocol/event-plugin) and the way Kafka consumes data.
> > 
> > 
> > I raised the kafka server using this documentation, but I can't figure out how to access it ...
> 
> Please refer to this guide: https://developers.tron.network/docs/event-plugin-deployment-mongodb

Its working. thanks!!!
