### ISSUE TITLE
Private Chain Net. Configurations

### ISSUE THREAD

**Issue by edonskov** [tronprotocol/java-tron#3714]
Hello everyone! I am trying to create a private network of 2 servers. Each of them must have 1 supernode and 1 fullnode. My goal is to make 2 super nodes mine together. I do not understand what the configuration of the files should be.
(The documentation describes the steps for creating a network of 1 super node and 1 full node.)
Please help me figure out what places to register the ip and ports.

**Comment by Dmckinney2** [comment]
Thank you

**Comment by cathy-lishipu** [comment]
you can refer to this document: https://developers.tron.network/docs/tron-private-chain

**Comment by edonskov** [comment]
> you can refer to this document: https://developers.tron.network/docs/tron-private-chain

Thanks for the answer. I set up the configuration according to this instruction, but as I said earlier, it describes how to set up a network consisting of 1 super node and 1 full node

**Comment by Benson0224** [comment]
> > you can refer to this document: https://developers.tron.network/docs/tron-private-chain
> 
> Thanks for the answer. I set up the configuration according to this instruction, but as I said earlier, it describes how to set up a network consisting of 1 super node and 1 full node. My goal is to make 2 super nodes mine together.

Repeat the Super Node step to set up another Super node:  https://tronprotocol.github.io/documentation-en/architecture/network/#deploy-the-supernode

Pay attention to the below parts:
1. Each SuperNode has its own private key, 2 SuperNodes means you need 2 private keys. 
2. The first Super Node `needSyncCheck = false`, others can be set true

**Comment by edonskov** [comment]
I think I did it. Thanks for the answer!

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
