### ISSUE TITLE
vanishing txid on blockchain

### ISSUE THREAD

**Issue by StephanDre** [tronprotocol/java-tron#3715]
Hello tonight, I had a very strange situation, it happened 3 times.
First, I ordered a transaction with the txId you can see first in the picture, then when the deposit was detected it turned out that the txId had been changed. Can someone explain it to me? txid that I sent to the network is not on blochain.
![aaa](https://user-images.githubusercontent.com/41446758/113112455-7928a580-9209-11eb-9753-b88978ea1e66.png)

**Comment by pthor11** [comment]
May be your transaction is time out. Having txid does not mean it's confirmed, tron network is not bitcoin.

**Comment by Benson0224** [comment]
1. Different TX ID means different Transactions. 
2. Successful broadcasting does not mean that the transaction will be on the chain. 

Please refer to this doc on how to confirm a transaction, thanks: https://developers.tron.network/docs/transaction-11#transaction-confirmation

**Comment by StephanDre** [comment]
I understand you, but as I wrote, this is exactly the same transaction that I sent, only txId is different,so I will ask again why txId has changed?

**Comment by Benson0224** [comment]
Sorry, the pic u uploaded is not very clear, I cannot read all the content there. 

Could you please copy the Text info here， thanks.

**Comment by StephanDre** [comment]
ok, so, first i use wallet/broadcasttransaction for send transaction to send my log with json transaction is(no error):

2021-03-30 18:24:31,330 -INFO - {"raw_data":"{\"contract\":[{\"parameter\":{\"value\":{\"amount\":75198370,\"owner_address\":\"TYUvtnn7bpYGRe7DGpTwH35P2cQieEtWH4\",
\"to_address\":\"TJR7PDtA4FTJadRbECSA8hSFFjcuryCb15\"},\"type_url\":\"type.googleapis.com/protocol.TransferContract\"},\"type\":\"TransferContract\"}],\"ref_block_bytes\":\"1f2c\",
\"ref_block_hash\":\"ef1d96bb4add1000\",\"expiration\":1617143071301,\"timestamp\":1617121471292}",
"raw_data_hex":"0a021f2c2208ef1d96bb4add100040c584f4a9882f5a68080112640a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412330a1541f6f1ccbc146f86514ff8700af49f0b55b4dc63a81215415ca721b86f74f7a0709108b42634dd6c4dd7ecc618a2dfed2370bcd6cd9f882f",
"signature":["mysignature"],"visible":true,"txID":"d00aca8ddb4b80c97d1f6254e35bff27ebce11032af801a5ea7085cbda4e3d78"}

then my program detected deposit (i get block and search my addresses as receiver) my log:

2021-03-30 18:24:34,575 -INFO - new transaction ---> DuringReceived{, receiver='TJR7PDtA4FTJadRbECSA8hSFFjcuryCb15', sender='TYUvtnn7bpYGRe7DGpTwH35P2cQieEtWH4', 
txId='157df19f8c2ad6f265e11cdf7c3a78f2789ac54e170819ed189e5752ed770397', value=75.19837, txblockheight=28909357, confirmed=0, complete=false, serverStatus=RECEIVED, confirmations=0, 
 blochHash=0000000001b91f2df76046438c01564c91698e3c26a0a56f87eed1987f268c14, requiredConfirmations=1, tokenId=TRON}

and first txId which I added to the method broadcast does not exist, but second which i find as my address is exist, this is the same transaction but have other txId.

**Comment by StephanDre** [comment]
maybe you have this problem ? https://paxful.com/blog/bitcoin-transaction-malleability-explained/ ?

**Comment by Benson0224** [comment]
![image](https://user-images.githubusercontent.com/61768920/113267153-9a23f000-9308-11eb-9b8a-fba38ae896b8.png)

if all the data is not modified this transaction broadcasting must fail because the signature data is not correct. 
Please refer to this guide on `broadcasttransaction` API: 
https://tronprotocol.github.io/documentation-en/api/http/

**Comment by StephanDre** [comment]
i change this before send to github, normally was here my signature

**Comment by StephanDre** [comment]
2021-03-30 18:24:31,330 -INFO - {"raw_data":"{\"contract\":[{\"parameter\":{\"value\":{\"amount\":75198370,\"owner_address\":\"TYUvtnn7bpYGRe7DGpTwH35P2cQieEtWH4\",
\"to_address\":\"TJR7PDtA4FTJadRbECSA8hSFFjcuryCb15\"},\"type_url\":\"type.googleapis.com/protocol.TransferContract\"},\"type\":\"TransferContract\"}],\"ref_block_bytes\":\"1f2c\",
\"ref_block_hash\":\"ef1d96bb4add1000\",\"expiration\":1617143071301,\"timestamp\":1617121471292}","raw_data_hex":"0a021f2c2208ef1d96bb4add100040c584f4a9882f5a68080112640a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412330a1541f6f1ccbc146f86514ff8700af49f0b55b4dc63a81215415ca721b86f74f7a0709108b42634dd6c4dd7ecc618a2dfed2370bcd6cd9f882f","signature":["c042a687671cf33a4c70d1e23d5c2a546e1bbff2c0752110b84614287fa10a7a7d8adf0da3732fd4274e59f94b644df8d7d55c527d89f121fdea2752571f3ef701"],"visible":true,"txID":"d00aca8ddb4b80c97d1f6254e35bff27ebce11032af801a5ea7085cbda4e3d78"}

This is orginal log

**Comment by Benson0224** [comment]
OK, thanks for your clarification.  
Compare the timestamp of these 2 transactions.  I would say these 2 transactions are 2 different transactions. I would suggest you double-check your code and try again.

https://api.trongrid.io/wallet/gettransactionbyid?value=157df19f8c2ad6f265e11cdf7c3a78f2789ac54e170819ed189e5752ed770397

**Comment by StephanDre** [comment]
This is the same transaction, I am convinced of it, I SENT IT TO MY DEPOSIT ADDRESS - ANOTHER PEOPLE DIDN'T KNOW THIS ADDRESS!
After all, it is known that the time of sending will be different from the time of detection, because the transaction had to enter the block

**Comment by StephanDre** [comment]
sory timestamp yes you all right, but in 90% for me this is the same tx

**Comment by jackzhp** [comment]
why is this issue closed? is it resolved?

yeah, it is very weird. 
how a txid is calculated?

As for the example here:
https://developers.tron.network/v3.7/docs/transaction

we can not even get to know its txid, why is so?
