### ISSUE TITLE
SR Claim reward 

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3717]
Hi,

### 1. What did you do?
I am trying to claim reward in tron-wallet-cli.
Command: withdrawbalance [owner_address].

### 2. What did you expect to see?
Reward withdraw sucessfully.

### 3. What did you see instead?
It results Account[hex_address] is a guard representative and is not allowed to withdraw balance.

**Comment by Alexliu007** [comment]
hi,you need to check if your address has permission to withdrawbalance.

**Comment by osiz-blockchainapp** [comment]
Hi @Alexliu007,
How to check my address has permission or not?

**Comment by osiz-blockchainapp** [comment]
> > Hi @Alexliu007,
> > How to check my address has permission or not?
> 
> use /wallet/getaccount，or you can provide your address and I will check it for you.

Running tron private network and i am getting account details from wallet-cli.
Here is my account details:
![Screenshot from 2021-04-01 13-11-17](https://user-images.githubusercontent.com/48212011/113261607-4b1c9180-92ed-11eb-88dd-5355bae6b5e8.png)

**Comment by Alexliu007** [comment]
> > > Hi @Alexliu007,
> > > How to check my address has permission or not?
> > 
> > 
> > use /wallet/getaccount，or you can provide your address and I will check it for you.
> 
> Running tron private network and i am getting account details from wallet-cli.
> Here is my account details:
> ![Screenshot from 2021-04-01 13-11-17](https://user-images.githubusercontent.com/48212011/113261607-4b1c9180-92ed-11eb-88dd-5355bae6b5e8.png)

The genesis address configured in the config file cannot withdraw the rewards. The SR that can withdraw the rewards must be a new SR generated by createWitness. You can try to use wallet/createwitness to create a new SR that can withdraw rewards.

**Comment by Alexliu007** [comment]
What do you mean by permission? If it is to modify the permissions of the genesis address to withdraw rewards, this needs to adjust the code

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
