### ISSUE TITLE
Your own tron?

### ISSUE THREAD

**Issue by Serqati** [tronprotocol/java-tron#3720]
So I know java-tron and sun-network is open source. so can I create my own tron with another name and people can come and create their dApps and tokens on that?

Thanks

**Comment by cathy-lishipu** [comment]
Of course, you can refer to this document: https://developers.tron.network/docs/tron-private-chain

**Comment by Serqati** [comment]
Thanks men ;)

**Comment by Serqati** [comment]
but why i Should get private key from a closed source website?

**Comment by Benson0224** [comment]
> but why i Should get private key from a closed source website?

Sorry i do not understand your question, can you please give more detail?

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
