### ISSUE TITLE
Token record en verifier contract tronscan.org

### ISSUE THREAD

**Issue by Wintron200228** [tronprotocol/java-tron#3722]

**Comment by yanghang8612** [comment]
Can you provide more details about your issue?

**Comment by Wintron200228** [comment]
On November 19, 2020 I sent 3.383 Tron from my binance account, I just thought to exchange it for AGI coins in my own binance account . But there it went wrong because I can only track my wallet via Tronlink viewing wallet and via Tronscan org I get into my online wallet, but I cannot change or manage anything yet, because it requires a cold wallet!  I installed cold wallet on an old phone turned off all kinds of connections but nothing works.  So I track my money but can't own it!  I hope it is a little clear now and I hope you can help me come out.  I really need help, I'm really a rookie in this and don't understand much yet but I really want to get it ... Helpppp

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by Wintron200228** [comment]
> Kunt u meer informatie geven over uw probleem?

Ja ik kan mijn trc20 token niet vinden. Ik heb mijn ron
