### ISSUE TITLE
i sent usdt trc20 to my trc20 adress...

### ISSUE THREAD

**Issue by duvi42** [tronprotocol/java-tron#3723]
### 1. What did you do?
recive back transaction

### 3. What did you see instead? 0

i have copy by mistake my adress in tronlink wallet and i sent usdt to that adress and i can see the usdt in tronscan smart contract

https://tronscan.io/#/transaction/5b9a88aa329a88acd8622fb663a99e73ab237066a75a34a1fd7ff044461d0026

**Comment by Benson0224** [comment]
Please contact Tether support team to fix it. thanks.

https://tether.to/contact-us/

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
