### ISSUE TITLE
gRPC TriggerSmartContract Fee Limit

### ISSUE THREAD

**Issue by neshala** [tronprotocol/java-tron#3725]
I am trying to make the gRPC call to trigger a smart contract.

As you can see here:
https://github.com/tronprotocol/protocol/blob/master/core/contract/smart_contract.proto

Proto file have following specs for Smart Contract:
```proto
message TriggerSmartContract {
  bytes owner_address = 1;
  bytes contract_address = 2;
  int64 call_value = 3;
  bytes data = 4;
  int64 call_token_value = 5;
  int64 token_id = 6;
}
```

But there is no option to set Fee Limit, so when I run that + sign transaction + broadcast transaction I am getting an error: "FAIL-OUT OF ENERGY>" and the fee limit is empty.

Any idea how to provide fee limit info when executing a smart contract call?

**Comment by Starsakary** [comment]
The API of 'triggersmartcontract' returns an unsigned transaction.
You'd better take a look at the proto of 'Transaction' then you can find 'feelimit' there.

**Comment by neshala** [comment]
Can you please point to the exact proto where the Transaction fee is defined because I can't find it?

Here is what I am doing:

# Step 1
trigger smart contract to get unsigned transaction

# Step 2
sign received transaction with primary key

# Step 3
broadcast transaction


In which step should I define the Fee Limit that I want to set?

I have checked the properties of the transaction object received as a result of step 1, but I can't find their property for the fee limit.

Thanks for helping.

**Comment by Benson0224** [comment]
check here: https://github.com/tronprotocol/protocol/blob/master/core/Tron.proto#L406

**Comment by neshala** [comment]
Thanks, how I communicate with that, I mean in which step of 3 above should I call it?

For step 1 I am using 	
TriggerContract(ctx context.Context, in *core.TriggerSmartContract, opts ...grpc.CallOption) (*TransactionExtention, error)

for step 2 I am using 
GetTransactionSign2(ctx context.Context, in *core.TransactionSign, opts ...grpc.CallOption) (*TransactionExtention, error)

and for step 3 
BroadcastTransaction(ctx context.Context, in *core.Transaction, opts ...grpc.CallOption) (*Return, error)

I don't see how and where to use Transaction raw proto ?

**Comment by neshala** [comment]
Thanks a lot, finally I made it by setting the raw data fee limit.
