### ISSUE TITLE
I need to parse the response,but no documentation tells me the meaning of the attribute.

### ISSUE THREAD

**Issue by xiaoizichao** [tronprotocol/java-tron#3738]
I need to parse the response,but no documentation tells me the meaning of the attribute.

url:https://api.trongrid.io/wallet/gettransactioninfobyid
param:{"value":"efde2ab4d7522f67c5bd3c5bf546d2112a4004fe76d45db2d5b94334b8077878"}
response:{
    "id": "efde2ab4d7522f67c5bd3c5bf546d2112a4004fe76d45db2d5b94334b8077878",
    "fee": 1231300,
    "blockNumber": 29129143,
    "blockTimeStamp": 1617807429000,
    "contractResult": [
        "0000000000000000000000000000000000000000000000000000000000000000"
    ],
    "contract_address": "41a614f803b6fd780986a42c78ec9c7f77e6ded13c",
    "receipt": {
        "energy_fee": 1231300,
        "origin_energy_usage": 5836,
        "energy_usage_total": 14631,
        "net_usage": 351,
        "result": "SUCCESS"
    },
    "log": [
        {
            "address": "a614f803b6fd780986a42c78ec9c7f77e6ded13c",
            "topics": [
                "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "000000000000000000000000796258bfbd23d238a304fb54dbb835b7714b8130",
                "00000000000000000000000088bb8fcadbf29ee90dffbc8c7fd1e02a485fbeff"
            ],
            "data": "00000000000000000000000000000000000000000000000000000000000f4240"
        }
    ]
}
**topics[0]: ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
what is it?How can i parse it?**

**Comment by xiaoizichao** [comment]
Actually, I can't parse it.
Data,Topics[0]

**Comment by xiaoizichao** [comment]
Is anyone here? Can you help me?

**Comment by Benson0224** [comment]
Transaction info is exactly following the google protobuff. check more from the proto definition:
Transaction definition: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto#L307
TransactionInfo definition: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto#L415 

Here is a doc which introduced the detailed meaning of each field, it may not cover all the messages, but should be enough for a start point: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/English%20version%20of%20TRON%20Protocol%20document.md


Learn more about Google Protobuff: https://github.com/protocolbuffers/protobuf

**Comment by xiaoizichao** [comment]
Can't solve my problem after reading it....
look eth_getTransactionByHash
![image](https://user-images.githubusercontent.com/27492132/114538810-5a54f500-9c86-11eb-996e-95ffbbbcb6ee.png)
I need a description of the return value

**Comment by xiaoizichao** [comment]
> Transaction info is exactly following the google protobuff. check more from the proto definition:
> Transaction definition: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto#L307
> TransactionInfo definition: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto#L415
> 
> Here is a doc which introduced the detailed meaning of each field, it may not cover all the messages, but should be enough for a start point: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/English%20version%20of%20TRON%20Protocol%20document.md
> 
> Learn more about Google Protobuff: https://github.com/protocolbuffers/protobuf

![image](https://user-images.githubusercontent.com/27492132/114545923-20d4b780-9c8f-11eb-874b-3475b0f1dcce.png)
Did not explain what is in the topics array,I have been stuck for these two days, help me.

**Comment by Benson0224** [comment]
> > Transaction info is exactly following the google protobuff. check more from the proto definition:
> > Transaction definition: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto#L307
> > TransactionInfo definition: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto#L415
> > Here is a doc which introduced the detailed meaning of each field, it may not cover all the messages, but should be enough for a start point: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/English%20version%20of%20TRON%20Protocol%20document.md
> > Learn more about Google Protobuff: https://github.com/protocolbuffers/protobuf
> 
> ![image](https://user-images.githubusercontent.com/27492132/114545923-20d4b780-9c8f-11eb-874b-3475b0f1dcce.png)
> Did not explain what is in the topics array,I have been stuck for these two days, help me.

The topic is Event related. please check more detail from here: https://developers.tron.network/docs/vm-event

**Comment by xiaoizichao** [comment]
> > > Transaction info is exactly following the google protobuff. check more from the proto definition:
> > > Transaction definition: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto#L307
> > > TransactionInfo definition: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/Tron.proto#L415
> > > Here is a doc which introduced the detailed meaning of each field, it may not cover all the messages, but should be enough for a start point: https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/English%20version%20of%20TRON%20Protocol%20document.md
> > > Learn more about Google Protobuff: https://github.com/protocolbuffers/protobuf
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/27492132/114545923-20d4b780-9c8f-11eb-874b-3475b0f1dcce.png)
> > Did not explain what is in the topics array,I have been stuck for these two days, help me.
> 
> The topic is Event related. please check more detail from here: https://developers.tron.network/docs/vm-event

Thank you very much.
