### ISSUE TITLE
There was an error in a free coin swap. The txid is:b3330b38638ed2f50b5b55b4127e92420a22aeecb5561a73f8dd8bd945404eda

### ISSUE THREAD

**Issue by junz3** [tronprotocol/java-tron#3745]
There was an error on the coin swap. The txid is:c6ed98ee286432bae257d95c802e6d1c17140d9b91034f938adb91dc238199f1

my trx is deducted from my wallet already but the freecoin not added yet. how can i get back my trx?

**Comment by Benson0224** [comment]
out-of-energy is Require-style Exception in TVM. 
This Exception will lead to transaction failure.  This type of exception actually means that the smart contract is executed to a certain step and exits, and the execution is not completely completed. When this kind of exception occurs, the energy consumed before the exit step will be deducted from the user's account. that is why your 12.05652 were consumed. 

check more technical description from here: 
https://developers.tron.network/docs/vm-exception#require-style-exception

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time.
Please feel free to reopen it if you still see the issue. thanks
