### ISSUE TITLE
My help for French and Arabic translations

### ISSUE THREAD

**Issue by DevObs1** [tronprotocol/java-tron#375]
Hi Team,
I can help you to do translations in French but also in Arabic. Rewards in Tron would be welcome.
Do not hesitate to contact me on my email: devobs1@gmail.com

**Comment by ybhgenius** [comment]
Hello,

Thanks for your participation.

Please check this link: 

https://crowdin.com/project/trondocs

You can translate or correct relevant texts through this link.

We will reward you according to your contribution.

Best Regards

Boheng Yang

**Comment by Rovak** [comment]
Closing this issue as translations are now being done through Crowdin. Follow the link above to contribute your translations.

**Comment by DevObs1** [comment]
Hello,
Thanks.
Happy to join you !
