### ISSUE TITLE
Send TRX - No error message on wrong value

### ISSUE THREAD

**Issue by miimiispets** [tronprotocol/java-tron#376]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Tried sending incorrect amounts of trx.: Negative amount and smaller then 0.000001

2. What did you expect to see?
Error message on clicking "Send" button.

3. What did you see instead?
Transactions were not executed, however an error message is currently not displayed and would clarify transaction status.

**Comment by Rovak** [comment]
I think this is related to the `wallet-web` project

**Comment by Rovak** [comment]
Fixed by https://github.com/tronprotocol/wallet-web/pull/17
