### ISSUE TITLE
api.trongrid.io cannot query account data, but the actual account has data

### ISSUE THREAD

**Issue by HebeBlock** [tronprotocol/java-tron#3763]
I am using api.trongrid.io for account query, but there is no data

https://api.trongrid.io/v1/accounts/TLGtAnJTEssjEnVjZNfuXSFcY1G8cXEAeK

The data can be queried in the block explorer：

https://tronscan.io/#/address/TLGtAnJTEssjEnVjZNfuXSFcY1G8cXEAeK

At present, several of our users have encountered such a situation. Is there a backup api or can you fix it?

**Comment by Alexliu007** [comment]
The address is not activated, the v1 interface cannot query inactive accounts.

**Comment by HebeBlock** [comment]
> The address is not activated, the v1 interface cannot query inactive accounts.

Thanks for your message
