### ISSUE TITLE
Private Tron Chain in Docker

### ISSUE THREAD

**Issue by albomo** [tronprotocol/java-tron#3766]
**1. What did you do?**
I am setting a private chain in Docker via the same logic, as I did it on 3 VMs. My architecture was 2 Super Nodes + 1 Full Node.
Now I am trying to do the same in docker container. Firstly, I try to set up 1 Super Node in docker. I tried to use the ready one, but it does not work.
I did all the same steps as before. And I took the same .conf file from the working private chain I did on VM. 
**But now my Super Node does not work and displays the same error:**
**Tron  active witnesses is null.**

**2. What did you expect to see?**
Block producing, correct work of the Super Node

**3. What did you see instead?**
Tron produce block error.
Tron  active witnesses is null.
---------------------------------------------------------------------------------------------
But the container is configured correctly, the configuration is working, and the witnesses are registered according to the instructions. The configuration file taken from the [official instructions](https://developers.tron.network/docs/tron-private-chain) gives the same result - as if the witnesses are not written in the configuration file.
What could be the mistake? It is imperative to set up networking in docker containers.
Previous appeal: https://github.com/tronprotocol/java-tron/issues/3714

**Comment by Benson0224** [comment]
here is the suggestion, please let us know once you complete the checking. 
1. check whether you have correctly configured the witness info in config.conf file.  it looks like below: 

```
  witnesses = [
    {
      address: TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY,
      url = "http://tronstudio.com",
      voteCount = 10000
    }
  ]
```
2.  Check your seed.node configuration, make sure the existing SR was configured there.  here the port is the  `listen.port ` in the existing SR configuration. 
```
seed.node = {
  # List of the seed nodes. This is used to enable the node can connect when join one net at first.
  # If you deploy one private net, you must add some "ip:port" here for other node connecting.
  # Seed nodes are stable full nodes, and the first SuperNode must be inclued in.
  # example:
  # ip.list = [
  #   "ip:port",
  #   "ip:port"
  # ]
  ip.list = [
  ]
}
```

3. checked the command of starting the SR node, make sure `--witness` is used. 
```
nohup java -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -jar  FullNode.jar **--witness** -c supernode.conf
```

**Comment by albomo** [comment]
Hello, @Benson0224 
Thank you very much for your reply.
Items 1, 2, 3, that you mentioned were completed correctly and were originally filled in correctly as well. Unfortunately, the error is still the same. This is what causes the main difficulties, that everything for launching witnesses is full, but an error appears.
I may provide you with code, if it is necessary, but on VMs all the same files work in a correct way.

**Comment by Benson0224** [comment]
Please join our telegram group for more support, there you can post more detailed info to the group admins for further help. thanks. 
https://t.me/TronOfficialDevelopersGroupEn

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
We will close this issue as no update for more than one week.
Please feel free to re-open this issue if you still see it, thanks.
