### ISSUE TITLE
My FULLNODE block height stays at 29462263 and is out of sync

### ISSUE THREAD

**Issue by xiaka53** [tronprotocol/java-tron#3769]
The configuration file has not been modified, the code version has been updated to the latest, and the block has always been this one
The log is as follows:

size: 2001, first blockId: Num:29462263,ID:0000000001c18ef71913dad6ca799eea4422013e7b241cd56cbf814b3faa3cca, end blockId: Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4
18:48:55.746 INFO  [TronJClientWorker-0] [DB](Manager.java:1543) headNumber:29462263
18:48:55.746 INFO  [TronJClientWorker-0] [DB](Manager.java:1545) syncBeginNumber:29462263
18:48:55.746 INFO  [TronJClientWorker-0] [DB](Manager.java:1549) solidBlockNumber:29462245
18:48:55.746 INFO  [TronJClientWorker-0] [net](SyncService.java:179) Get block chain summary, low: 29462263, highNoFork: 29462263, high: 29462263, realHigh: 29464263
18:48:55.747 INFO  [TronJClientWorker-0] [net](MessageQueue.java:106) Send to /121.78.223.199:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:29462263,ID:0000000001c18ef71913dad6ca799eea4422013e7b241cd56cbf814b3faa3cca, end block Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4
18:48:55.854 INFO  [TronJClientWorker-0] [net](MessageQueue.java:121) Receive from /121.78.223.199:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4, end blockId: Num:29466263,ID:0000000001c19e97cc2afd84eab7265753876e0f1a2fcfb37e4caf4bc9885078
18:49:04.805 WARN  [pool-49-thread-1] [net](PeerStatusCheck.java:49) Peer /34.234.164.105 not sync for a long time.
18:49:04.805 INFO  [pool-49-thread-1] [net](Channel.java:129) Send to /34.234.164.105:18888 online-time 30s, type: P2P_DISCONNECT
reason: TIME_OUT
18:49:04.809 INFO  [TronJClientWorker-8] [net](TronChannelInitializer.java:48) Close channel:/34.234.164.105:18888 | da096f99560061e0826b60161aea53c01bff1d2b7fba8c89ba01f053e476f0af18bc4ce1e4c1fd23a626df3db98ca81e1c19a55ab7adafd651158864b491c40a
18:49:05.616 INFO  [pool-36-thread-1] [net](SyncPool.java:123)

============ Peer stats: all 8, active 8, passive 0

Peer 162.55.0.212:18888 [6782b093]
ping msg: count 1, max-average-min-last: 262 262 262 262
connect time: 17s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:29462264
syncBlockRequestedSize:0
remainNum:254460
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 239(0), discover: 1/1 0/0 0/0 0/0 271ms, p2p: 1/1/1 , tron: 5/5   , tcp flow: 164096

Peer 121.78.223.199:18888 [877f0e3b]
ping msg: count 9, max-average-min-last: 89 84 81 85
connect time: 10s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:29462264
syncBlockRequestedSize:0
remainNum:254462
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 202(0), discover: 1/1 0/0 0/0 0/0 81ms, p2p: 5/5/6 , tron: 33/34 X 5<=TIME_OUT=>TOO_MANY_PEERS, tcp flow: 492300

**Comment by xiaka53** [comment]
18:49:06.088 INFO  [pool-35-thread-1] [net](PeerClient.java:70) connect peer 47.90.250.85 18888 84a06aaaf67a50a92fc9ce25709922c9c1bc54d5f5f3eaa66b0f5fabac97dd1294efa917a9086e58d2517d434074d4b2cad934d7257532805505b37599a6bcb0
18:49:06.310 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:77) channel active, /47.90.250.85:18888
18:49:06.310 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:130) Handshake send to /47.90.250.85:18888, type: P2P_HELLO
from {
  address: "8.210.7.238"
  port: 18888
  nodeId: "\004\265\022\255\351Dl!g\363\320\002\317\222>\277\345\317\277\311:\3362-\355\341\205n</\306Z\303\370a\333z(a\001\361\301\2754X.X\261>5PL\325\362N\245\'\263O\235\372\264/\201"
}
version: 11111
timestamp: 1619606946310
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\036\277\210P\212\003\206\\q\324R\342_MQ\031A\226\241\322+fS\334"
}
solidBlockId {
  hash: "\000\000\000\000\001\301\216\345!c\255ws\312Z_\366\216F\330\214\343\217/\344\346\215;\230\325\036\350"
  number: 29462245
}
headBlockId {
  hash: "\000\000\000\000\001\301\216\367\031\023\332\326\312y\236\352D\"\001>{$\034\325l\277\201K?\252<\312"
  number: 29462263
}

18:49:06.535 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:92) Handshake receive from /47.90.250.85:18888, type: P2P_HELLO
from {
  address: "47.90.250.85"
  port: 18888
  nodeId: "\204\240j\252\366zP\251/\311\316%p\231\"\311\301\274T\325\365\363\352\246k\017_\253\254\227\335\022\224\357\251\027\251\bnX\322Q}C@t\324\262\312\3314\327%u2\200U\005\263u\231\246\274\260"
}
version: 11111
timestamp: 1619606946310
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\036\277\210P\212\003\206\\q\324R\342_MQ\031A\226\241\322+fS\334"
}
solidBlockId {
  hash: "\000\000\000\000\001\305\200\206\016\371,\274\347\212\340\333;\242\364\320\031k\221W\200\027\333\330_2!\253"
  number: 29720710
}
headBlockId {
  hash: "\000\000\000\000\001\305\200\230\001C\276\000\372\310\313q\312<t\353\275\373\213c\036W\273\303\251\267\004\240"
  number: 29720728
}

18:49:06.535 INFO  [TronJClientWorker-1] [net](Channel.java:201) Peer /47.90.250.85:18888 status change to HANDSHAKE_FINISHED.
18:49:06.535 INFO  [TronJClientWorker-1] [net](Channel.java:111) Finish handshake with /47.90.250.85:18888.
18:49:06.535 INFO  [TronJClientWorker-1] [net](ChannelManager.java:161) Add active peer /47.90.250.85:18888 | 84a06aaaf67a50a92fc9ce25709922c9c1bc54d5f5f3eaa66b0f5fabac97dd1294efa917a9086e58d2517d434074d4b2cad934d7257532805505b37599a6bcb0, total active peers: 9
18:49:06.535 INFO  [TronJClientWorker-1] [net](Channel.java:201) Peer /47.90.250.85:18888 status change to SYNCING.
18:49:06.535 INFO  [TronJClientWorker-1] [net](Channel.java:201) Peer /47.90.250.85:18888 status change to SYNCING.
18:49:06.536 INFO  [TronJClientWorker-1] [DB](Manager.java:1543) headNumber:29462263
18:49:06.536 INFO  [TronJClientWorker-1] [DB](Manager.java:1545) syncBeginNumber:29462263
18:49:06.536 INFO  [TronJClientWorker-1] [DB](Manager.java:1549) solidBlockNumber:29462245
18:49:06.536 INFO  [TronJClientWorker-1] [net](SyncService.java:179) Get block chain summary, low: 29462263, highNoFork: 29462263, high: 29462263, realHigh: 29462263
18:49:06.536 INFO  [TronJClientWorker-1] [net](MessageQueue.java:106) Send to /47.90.250.85:18888, type: SYNC_BLOCK_CHAIN
size: 1, start block: Num:29462263,ID:0000000001c18ef71913dad6ca799eea4422013e7b241cd56cbf814b3faa3cca
18:49:07.220 INFO  [TronJClientWorker-1] [net](MessageQueue.java:121) Receive from /47.90.250.85:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:29462263,ID:0000000001c18ef71913dad6ca799eea4422013e7b241cd56cbf814b3faa3cca, end blockId: Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4
18:49:07.221 INFO  [TronJClientWorker-1] [DB](Manager.java:1543) headNumber:29462263
18:49:07.221 INFO  [TronJClientWorker-1] [DB](Manager.java:1545) syncBeginNumber:29462263
18:49:07.221 INFO  [TronJClientWorker-1] [DB](Manager.java:1549) solidBlockNumber:29462245
18:49:07.221 INFO  [TronJClientWorker-1] [net](SyncService.java:179) Get block chain summary, low: 29462263, highNoFork: 29462263, high: 29462263, realHigh: 29464263
18:49:07.221 INFO  [TronJClientWorker-1] [net](MessageQueue.java:106) Send to /47.90.250.85:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:29462263,ID:0000000001c18ef71913dad6ca799eea4422013e7b241cd56cbf814b3faa3cca, end block Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4
18:49:07.461 INFO  [TronJClientWorker-1] [net](MessageQueue.java:121) Receive from /47.90.250.85:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4, end blockId: Num:29466263,ID:0000000001c19e97cc2afd84eab7265753876e0f1a2fcfb37e4caf4bc9885078
18:49:08.805 WARN  [pool-49-thread-1] [net](PeerStatusCheck.java:49) Peer /52.47.129.140 not sync for a long time.
18:49:08.805 INFO  [pool-49-thread-1] [net](Channel.java:129) Send to /52.47.129.140:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
18:49:08.806 WARN  [pool-49-thread-1] [net](PeerStatusCheck.java:49) Peer /185.108.112.243 not sync for a long time.
18:49:08.806 INFO  [pool-49-thread-1] [net](Channel.java:129) Send to /185.108.112.243:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
18:49:08.806 WARN  [pool-49-thread-1] [net](PeerStatusCheck.java:49) Peer /47.90.201.112 not sync for a long time.
18:49:08.806 INFO  [pool-49-thread-1] [net](Channel.java:129) Send to /47.90.201.112:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
18:49:08.808 INFO  [TronJClientWorker-11] [net](TronChannelInitializer.java:48) Close channel:/52.47.129.140:18888 | 977eebf398367e2593082236064dc4e4d154a536468e89f3754d53f385032b16e8d13b8d79df7d6e1b7c16640e3ee7f5986101ff407ba265b0a0641e654deb76
18:49:08.812 INFO  [TronJClientWorker-9] [net](TronChannelInitializer.java:48) Close channel:/47.90.201.112:18888 | 6e112887d2863cb080fea08415fbaf68c130ace5059ce0e97a848bb082d746f480474b098cf49c9bda7d13afe5f4b7c86a2997c4afa448bb43a7d17fd4eb0242

**Comment by pthor11** [comment]
Does it relate to 4.2 forced upgrade?

**Comment by xiaka53** [comment]
> Does it relate to 4.2 forced upgrade?

**Comment by xiaka53** [comment]
> > Does it relate to 4.2 forced upgrade?

4.2 how to operate the forced update?

**Comment by Benson0224** [comment]
all new features in 4.2 will be enabled by the proposal. there will be no impact before the voting request was initialted. 

Could you please share the full log file of after your node started , thanks.

**Comment by xiaka53** [comment]
> all new features in 4.2 will be enabled by the proposal. there will be no impact before the voting request was initialted.
> 
> Could you please share the full log file of after your node started , thanks.

It has been updated to 4.2, and the error is still there.
The log is as follows:



11:36:42.623 INFO  [main] [DB](Manager.java:548) begin to init txs cache.
11:36:42.623 INFO  [main] [DB](Manager.java:555) current headNum is: 29462263
11:38:14.654 WARN  [pool-43-thread-11] [DB](Manager.java:578) block not found. num: 29462261
11:38:14.654 WARN  [pool-43-thread-11] [DB](Manager.java:578) block not found. num: 29462262
11:38:17.148 INFO  [main] [DB](Manager.java:595) end to init txs cache. trx ids:8656798, block count:65536, empty block count:33, cost:94525
11:38:17.793 INFO  [main] [o.r.Reflections](Reflections.java:232) Reflections took 635 ms to scan 1 urls, producing 443 keys and 2537 values
11:38:17.870 INFO  [main] [net](PeerConnectionCheckService.java:44) start the PeerConnectionCheckService
11:38:17.925 INFO  [DiscoverServer] [discover](DiscoverServer.java:102) Discovery server started, bind port 18888
11:38:18.080 INFO  [nioEventLoopGroup-2-1] [discover](NodeManager.java:123) Reading node statistics from store: 30 nodes.
11:38:18.252 INFO  [main] [app](FullNode.java:116) ********register application shutdown hook********
11:38:18.254 INFO  [main] [API](FullNodeHttpApiService.java:302) init zk param begin
11:38:18.653 INFO  [main] [API](FullNodeHttpApiService.java:323) init zk param done
11:38:18.775 INFO  [main] [API](RpcApiService.java:272) RpcApiService has started, listening on 50051
11:38:18.783 INFO  [main] [o.e.j.u.log](Log.java:193) Logging initialized @123421ms to org.eclipse.jetty.util.log.Slf4jLog
11:38:18.866 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 1.8.0_281-b09
11:38:18.896 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
11:38:18.896 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
11:38:18.897 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 600000ms
11:38:18.908 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@3180aee{/,null,AVAILABLE}
11:38:18.913 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@33ccead{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}
11:38:18.913 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @123552ms
11:38:18.919 INFO  [main] [API](RpcApiServiceOnSolidity.java:126) RpcApiServiceOnSolidity started, listening on 50061
11:38:18.920 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 1.8.0_281-b09
11:38:18.921 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
11:38:18.921 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
11:38:18.921 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 600000ms
11:38:18.923 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@7b9d1a4{/,null,AVAILABLE}
11:38:18.925 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@fcd3a6f{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}
11:38:18.925 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @123563ms
11:38:18.929 INFO  [main] [API](RpcApiServiceOnPBFT.java:126) RpcApiServiceOnPBFT started, listening on 50071
11:38:18.929 WARN  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:1566) o.e.j.s.ServletContextHandler@5c60f096{/,null,UNAVAILABLE} contextPath ends with /
11:38:18.930 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 1.8.0_281-b09
11:38:18.935 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
11:38:18.936 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
11:38:18.936 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 660000ms
11:38:18.937 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@5c60f096{/walletpbft,null,AVAILABLE}
11:38:18.938 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@759f45f1{HTTP/1.1,[http/1.1]}{0.0.0.0:8092}
11:38:18.938 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @123577ms
11:38:18.942 INFO  [main] [net](ChannelManager.java:86) Node config, trust 2, active 0, forward 2.
11:38:18.951 INFO  [main] [net](FastForward.java:61) Fast forward config, isWitness: false, keySize: 0, fastForwardNodes: 2
11:38:18.953 INFO  [PeerServerThread] [net](PeerServer.java:54) TCP listener started, bind port 18888
11:38:18.961 INFO  [main] [net](TronNetService.java:69) TronNetService start successfully.
11:38:18.962 WARN  [main] [app](LocalWitnesses.java:104) privateKey is null
11:38:18.962 WARN  [main] [consensus](ConsensusService.java:73) Witness 41dcc703c0e500b653ca82273b7bfad8045d85a470 is not in witnessStore.
11:38:18.964 INFO  [main] [consensus](ConsensusService.java:84) consensus service start success

**Comment by zyumingfit** [comment]
You join the official support group and provide a complete log：https://cn.developers.tron.network/docs/%E6%8A%80%E6%9C%AF%E6%94%AF%E6%8C%81%E7%BE%A4

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
We will close this issue as no update for more than one week.
Please feel free to re-open this issue if you still see it, thanks.
