### ISSUE TITLE
https://tronprotocol.github.io/wallet-web/#/network/nodes Node Count Issue

### ISSUE THREAD

**Issue by stinklefritz** [tronprotocol/java-tron#377]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Visited https://tronprotocol.github.io/wallet-web/#/network/nodes and looked at the node count over a period of a few days.

2. What did you expect to see?
Around 3,000 active nodes, most of which located in Malaysia.

3. What did you see instead?
It seems the node count always wants to reset when it approches 2,700 nodes. The first time I noticed this error, most of the nodes were congregated in Malaysia. The next day the node count dropped back around 2,000 with most of the nodes in Spain. Last night (4/7/2018), the node count again approached 2700 only to have it fall back down to 2,000 for a second time, as of 4/8/2018

**Comment by zhaohong** [comment]
fix: Weight removal for node info #378
https://github.com/tronprotocol/java-tron/pull/378
