### ISSUE TITLE
18:49:06.088 INFO  [pool-35-thread-1] [net](PeerClient.java:70) connect peer 47.90.250.85 18888 84a06aaaf67a50a92fc9ce25709922c9c1bc54d5f5f3eaa66b0f5fabac97dd1294efa917a9086e58d2517d434074d4b2cad934d7257532805505b37599a6bcb0

### ISSUE THREAD

**Issue by phamquangquy92vd** [tronprotocol/java-tron#3772]
18:49:06.088 INFO  [pool-35-thread-1] [net](PeerClient.java:70) connect peer 47.90.250.85 18888 84a06aaaf67a50a92fc9ce25709922c9c1bc54d5f5f3eaa66b0f5fabac97dd1294efa917a9086e58d2517d434074d4b2cad934d7257532805505b37599a6bcb0
18:49:06.310 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:77) channel active, /47.90.250.85:18888
18:49:06.310 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:130) Handshake send to /47.90.250.85:18888, type: P2P_HELLO
from {
  address: "8.210.7.238"
  port: 18888
  nodeId: "\004\265\022\255\351Dl!g\363\320\002\317\222>\277\345\317\277\311:\3362-\355\341\205n</\306Z\303\370a\333z(a\001\361\301\2754X.X\261>5PL\325\362N\245\'\263O\235\372\264/\201"
}
version: 11111
timestamp: 1619606946310
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\036\277\210P\212\003\206\\q\324R\342_MQ\031A\226\241\322+fS\334"
}
solidBlockId {
  hash: "\000\000\000\000\001\301\216\345!c\255ws\312Z_\366\216F\330\214\343\217/\344\346\215;\230\325\036\350"
  number: 29462245
}
headBlockId {
  hash: "\000\000\000\000\001\301\216\367\031\023\332\326\312y\236\352D\"\001>{$\034\325l\277\201K?\252<\312"
  number: 29462263
}

18:49:06.535 INFO  [TronJClientWorker-1] [net](HandshakeHandler.java:92) Handshake receive from /47.90.250.85:18888, type: P2P_HELLO
from {
  address: "47.90.250.85"
  port: 18888
  nodeId: "\204\240j\252\366zP\251/\311\316%p\231\"\311\301\274T\325\365\363\352\246k\017_\253\254\227\335\022\224\357\251\027\251\bnX\322Q}C@t\324\262\312\3314\327%u2\200U\005\263u\231\246\274\260"
}
version: 11111
timestamp: 1619606946310
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\036\277\210P\212\003\206\\q\324R\342_MQ\031A\226\241\322+fS\334"
}
solidBlockId {
  hash: "\000\000\000\000\001\305\200\206\016\371,\274\347\212\340\333;\242\364\320\031k\221W\200\027\333\330_2!\253"
  number: 29720710
}
headBlockId {
  hash: "\000\000\000\000\001\305\200\230\001C\276\000\372\310\313q\312<t\353\275\373\213c\036W\273\303\251\267\004\240"
  number: 29720728
}

18:49:06.535 INFO  [TronJClientWorker-1] [net](Channel.java:201) Peer /47.90.250.85:18888 status change to HANDSHAKE_FINISHED.
18:49:06.535 INFO  [TronJClientWorker-1] [net](Channel.java:111) Finish handshake with /47.90.250.85:18888.
18:49:06.535 INFO  [TronJClientWorker-1] [net](ChannelManager.java:161) Add active peer /47.90.250.85:18888 | 84a06aaaf67a50a92fc9ce25709922c9c1bc54d5f5f3eaa66b0f5fabac97dd1294efa917a9086e58d2517d434074d4b2cad934d7257532805505b37599a6bcb0, total active peers: 9
18:49:06.535 INFO  [TronJClientWorker-1] [net](Channel.java:201) Peer /47.90.250.85:18888 status change to SYNCING.
18:49:06.535 INFO  [TronJClientWorker-1] [net](Channel.java:201) Peer /47.90.250.85:18888 status change to SYNCING.
18:49:06.536 INFO  [TronJClientWorker-1] [DB](Manager.java:1543) headNumber:29462263
18:49:06.536 INFO  [TronJClientWorker-1] [DB](Manager.java:1545) syncBeginNumber:29462263
18:49:06.536 INFO  [TronJClientWorker-1] [DB](Manager.java:1549) solidBlockNumber:29462245
18:49:06.536 INFO  [TronJClientWorker-1] [net](SyncService.java:179) Get block chain summary, low: 29462263, highNoFork: 29462263, high: 29462263, realHigh: 29462263
18:49:06.536 INFO  [TronJClientWorker-1] [net](MessageQueue.java:106) Send to /47.90.250.85:18888, type: SYNC_BLOCK_CHAIN
size: 1, start block: Num:29462263,ID:0000000001c18ef71913dad6ca799eea4422013e7b241cd56cbf814b3faa3cca
18:49:07.220 INFO  [TronJClientWorker-1] [net](MessageQueue.java:121) Receive from /47.90.250.85:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:29462263,ID:0000000001c18ef71913dad6ca799eea4422013e7b241cd56cbf814b3faa3cca, end blockId: Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4
18:49:07.221 INFO  [TronJClientWorker-1] [DB](Manager.java:1543) headNumber:29462263
18:49:07.221 INFO  [TronJClientWorker-1] [DB](Manager.java:1545) syncBeginNumber:29462263
18:49:07.221 INFO  [TronJClientWorker-1] [DB](Manager.java:1549) solidBlockNumber:29462245
18:49:07.221 INFO  [TronJClientWorker-1] [net](SyncService.java:179) Get block chain summary, low: 29462263, highNoFork: 29462263, high: 29462263, realHigh: 29464263
18:49:07.221 INFO  [TronJClientWorker-1] [net](MessageQueue.java:106) Send to /47.90.250.85:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:29462263,ID:0000000001c18ef71913dad6ca799eea4422013e7b241cd56cbf814b3faa3cca, end block Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4
18:49:07.461 INFO  [TronJClientWorker-1] [net](MessageQueue.java:121) Receive from /47.90.250.85:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:29464263,ID:0000000001c196c72308b3ec0bef1f2761f97f1cc04709a62697e7e8c1e02eb4, end blockId: Num:29466263,ID:0000000001c19e97cc2afd84eab7265753876e0f1a2fcfb37e4caf4bc9885078
18:49:08.805 WARN  [pool-49-thread-1] [net](PeerStatusCheck.java:49) Peer /52.47.129.140 not sync for a long time.
18:49:08.805 INFO  [pool-49-thread-1] [net](Channel.java:129) Send to /52.47.129.140:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
18:49:08.806 WARN  [pool-49-thread-1] [net](PeerStatusCheck.java:49) Peer /185.108.112.243 not sync for a long time.
18:49:08.806 INFO  [pool-49-thread-1] [net](Channel.java:129) Send to /185.108.112.243:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
18:49:08.806 WARN  [pool-49-thread-1] [net](PeerStatusCheck.java:49) Peer /47.90.201.112 not sync for a long time.
18:49:08.806 INFO  [pool-49-thread-1] [net](Channel.java:129) Send to /47.90.201.112:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
18:49:08.808 INFO  [TronJClientWorker-11] [net](TronChannelInitializer.java:48) Close channel:/52.47.129.140:18888 | 977eebf398367e2593082236064dc4e4d154a536468e89f3754d53f385032b16e8d13b8d79df7d6e1b7c16640e3ee7f5986101ff407ba265b0a0641e654deb76
18:49:08.812 INFO  [TronJClientWorker-9] [net](TronChannelInitializer.java:48) Close channel:/47.90.201.112:18888 | 6e112887d2863cb080fea08415fbaf68c130ace5059ce0e97a848bb082d746f480474b098cf49c9bda7d13afe5f4b7c86a2997c4afa448bb43a7d17fd4eb0242

_Originally posted by @xiaka53 in https://github.com/tronprotocol/java-tron/issues/3769#issuecomment-828358918_

**Comment by zyumingfit** [comment]
No valuable information was found in this log, you need to send a complete log file: tron.log，Or you can search for "ERROR" in the log

**Comment by Benson0224** [comment]
We will close this issue now as no update for a long time.
Please feel free to re-open this issue if you still see it. thanks.
