### ISSUE TITLE
Tron node is not syncing after block 29616911

### ISSUE THREAD

**Issue by rajesh1158** [tronprotocol/java-tron#3773]
### 1. What did you do?

I have tried using the official nodes from https://developers.tron.network/docs/official-public-node. I tried setting MaxTimeRatio to 100. I also tried using the latest javatron release GreatVoyage-v4.2.0(Plato).

### 2. What did you expect to see?
I expect to see tron node sync

### 3. What did you see instead?
Tron node is stuck at block 29616911 and I keep getting P2P_DISCONNECT reason: TOO_MANY_PEERS error

I have attached a sample log file below:

[tron.log](https://github.com/tronprotocol/java-tron/files/6409029/tron.log)

I am running a fast lite node. I had downloaded the latest snapshot and started the FullNode.jar. For the first few days, tron node was syncing correctly, but a few days back it stopped syncing due to the above mentioned peer error. Is there a fix for this?

**Comment by zyumingfit** [comment]
Your log is incomplete, please stop the node, delete the old log, restart the node, reproduce the problem, and send  the new log file

**Comment by rajesh1158** [comment]
I had to delete the output-directory and download and extract the new snapshot to make the sync work again, but still not clue why the old snapshot stopped sync. It always gave the TOO MANY PEERS error, there is no other error in the entire log file. I do not have the complete old log file.

**Comment by BisonAl** [comment]
Seems related to https://github.com/tronprotocol/java-tron/issues/3666, although this issue was closed before any fix was found

**Comment by Benson0224** [comment]
We are going to close this issue as you have solved it. please feel free to reopen it if you still see it, thanks.

**Comment by iuwreouh** [comment]
> I had to delete the output-directory and download and extract the new snapshot to make the sync work again, but still not clue why the old snapshot stopped sync. It always gave the TOO MANY PEERS error, there is no other error in the entire log file. I do not have the complete old log file.

Did you resolve the issue?
