### ISSUE TITLE
Contract with event subscribe

### ISSUE THREAD

**Issue by CerberusGR** [tronprotocol/java-tron#3774]
Hello,

I have a java-tron node running on my pc. I have enabled event subscriber in order to communicate java-tron with python or nodejs code.

I want to create a smart contract and I would like to know how a new smart contract is broadcasted on network and saved on block. When I will create the smart contract which trigger will be executed (contractlogtrigger or contractevent trigger) and with what eventName?
Is there any way to check a previous contract how was stored in a block?

Thanks

**Comment by Benson0224** [comment]
1. Check this guide on how to issue a TRC20 Token on Tron. https://developers.tron.network/docs/issuing-trc20-tokens-tutorial 
2.  Check this guide on how to deploy a contract on tron network:  https://developers.tron.network/docs/deploying
3.  Check the contract detail of USDT from here: https://tronscan.org/#/contract/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/code.   you can also see the event of that contract from here: https://tronscan.org/#/contract/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/events

**Comment by CerberusGR** [comment]
Benson0224 thanks for your reply.
Is there any way to trigger all new smart contracts after their creation?

**Comment by Benson0224** [comment]
https://developers.tron.network/docs/trc20-contract-interaction

Check this guide on how to interact with the TRC20 contract.

**Comment by Benson0224** [comment]
We will close this issue now as no update for a long time. 
Please feel free to re-open this issue if you still see it. thanks.
