### ISSUE TITLE
NOT_ENOUGH_EFFECTIVE_CONNECTION

### ISSUE THREAD

**Issue by StephanDre** [tronprotocol/java-tron#3775]
Hi, i have problem with push transaction in mainnet.

When i send transaction to node is error NOT_ENOUGH_EFFECTIVE_CONNECTION,
or NO_CONNECTION, i have cfg from your github.

This only happens with a large amount of transactions I send

**Comment by Starsakary** [comment]
Did you send transactions through your own node?

**Comment by StephanDre** [comment]
Yes, my program connect to only my node.

**Comment by Starsakary** [comment]
You may put your full log here for our analysis.

**Comment by StephanDre** [comment]
error in line 5168807
txId e5a2c35a03a401124fb10520f55efa558e9636c8dec17c5c7cf8090ac686cbf9

[tron-2021-05-03.0.zip](https://github.com/tronprotocol/java-tron/files/6434208/tron-2021-05-03.0.zip)

**Comment by Starsakary** [comment]
There are many 'block xxxx not found' in your log. The reason was the node had not synchronized to the block you acquired. 
Also, the error of 'NOT_ENOUGH_EFFECTIVE_CONNECTION' is caused by unsynchronized.

**Comment by StephanDre** [comment]
but my application works like this,  checks if there is the next block and if there is, I get it and check transactions ...

**Comment by Starsakary** [comment]
You need to make sure that your application will never try to acquire a block that your database does not contain.

**Comment by StephanDre** [comment]
so, i should first ask node getnowblock, and then get block yes ?

**Comment by Starsakary** [comment]
Well, this can be a solution.

**Comment by StephanDre** [comment]
oke, for now i close this issue, thank for help i will make changes in my code.
