### ISSUE TITLE
How to calculate the txid of a transaction in python?

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [tronprotocol/java-tron#3785]
String txid = ByteArray.toHexString(Sha256Hash.hash(transaction.getRawData().toByteArray()));

_Originally posted by @Alexliu007 in https://github.com/tronprotocol/java-tron/issues/3244#issuecomment-650688310_

**Comment by oushu1zhangxiangxuan1** [comment]
I've used codes below, but the result hash can not find in tronscan.org

```
tb = blkIns.transactions[0].SerializeToString()
import hashlib
thash = hashlib.sha256(tb).hexdigest()
# 'c88d1767b0d0ef382c6c9b74bf8e5f48d7ee46e5e397d6e5efcf6a6bfd895854'

# but the hash in tronscan is 5fd5625600927e2eb62c261e94c04d500074e5582200bdaa98cd3ca5b2ea45b6
```

**Comment by Benson0224** [comment]
TX id is the hash value of "RawData", you can see the parameter passed to `hash` is actually the `transaction.getRawData().toByteArray() `, from your code seems you passed the whole transaction to `hash`.

`String txid = ByteArray.toHexString(Sha256Hash.hash(  transaction.getRawData().toByteArray()    ));`

**Comment by oushu1zhangxiangxuan1** [comment]
> TX id is the hash value of "RawData", you can see the parameter passed to `hash` is actually the `transaction.getRawData().toByteArray() `, from your code seems you passed the whole transaction to `hash`.
> 
> `String txid = ByteArray.toHexString(Sha256Hash.hash( transaction.getRawData().toByteArray() ));`

@Benson0224 Thank you! It works.
