### ISSUE TITLE
ret being Fail but contractRet being Success

### ISSUE THREAD

**Issue by msak222** [tronprotocol/java-tron#3788]
Regarding ret being Fail but contractRet being Success, how to explain this situation? Request for help
### 1. What did you do?

I transfer token from one account to another

### 2. What did you expect to see?
no fail
![image](https://user-images.githubusercontent.com/19371846/118444024-353d2180-b71f-11eb-92e4-4391d1bd34b1.png)

### 3. What did you see instead?
no fail

**Comment by Starsakary** [comment]
How did you get the data in your screenshot? You'd better give the transaction hash here.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
We will close this issue as no update for a long time.
please feel free to re-open it if you still see it. thanks.
