### ISSUE TITLE
VM halted: [Not enough energy for 'PUSH1' operation executing

### ISSUE THREAD

**Issue by StephanDre** [tronprotocol/java-tron#3789]
Hi i have problem when i send wallet/broadcasttransaction:
{"signature":["0ec83f78a1766a1acfb5a8529bdab6d74766e287e8ab4ee9574d2a840678db992ee85bed1d48f0b835f680aba9310aa8036fa866cb10351b3ff3db9fba24404100"],"txID":"c5b70a649c94c46436f99e63d1e31fa953038ec1a8add4d30ea3bd5508de427c","raw_data":{"contract":[{"parameter":{"value":{"amount":300000,"owner_address":"TFCVZZDFip2UunP9wjnut7mTTL5PgChcBd","to_address":"TYrxNkkiUpuwjkLj4gPQY4sGJUCTS1j7MU"},"type_url":"type.googleapis.com/protocol.TransferContract"},"type":"TransferContract"}],"ref_block_bytes":"df59","ref_block_hash":"d6a696772e33088f","expiration":1621280882861,"timestamp":1621259282622},"raw_data_hex":"0a02df592208d6a696772e33088f40ad81fcde972f5a67080112630a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412320a1541395bdc3a15ec32f2062baa635236b434833de713121541fb1c302a5ee6ef2012669ffc742c8c9fb94d09ab18e0a71270bed1d5d4972f"}

node return me first other error, and then DUP_TRANSACTION_ERROR, but transaction not exist in tronscan
i log node i find Not enough energry for push1:

`15:48:03.147 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 1 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.449 INFO  [nioEventLoopGroup-6-51] [net](MessageQueue.java:121) Receive from /15.236.149.86:25114, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.449 INFO  [nioEventLoopGroup-6-51] [net](MessageQueue.java:89) Fast send to /15.236.149.86:25114, type: FETCH_INV_DATA
invType: BLOCK, size: 1, First hash: 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.473 INFO  [nioEventLoopGroup-6-17] [net](MessageQueue.java:121) Receive from /135.181.165.37:40018, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.474 INFO  [nioEventLoopGroup-6-51] [net](MessageQueue.java:121) Receive from /15.236.149.86:25114, type: BLOCK
Num:30269274,ID:0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c, trx size: 136

15:48:03.479 INFO  [nioEventLoopGroup-6-51] [DB](KhaosDatabase.java:330) remove from khaosDatabase:0000000001cddf45395afa24d0d89caf42d1d76727ec0eb9b893a996c6728930
15:48:03.480 INFO  [nioEventLoopGroup-6-51] [DB](Manager.java:1596) PreValidate Transaction Sign, size:136, block num:30269274
15:48:03.495 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 1 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.496 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 1 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.496 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 1 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.496 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 3 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.496 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 1 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.496 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 1 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.536 INFO  [nioEventLoopGroup-6-30] [net](MessageQueue.java:121) Receive from /77.22.212.121:60860, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.546 INFO  [nioEventLoopGroup-6-23] [net](MessageQueue.java:121) Receive from /109.90.46.35:56372, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.557 INFO  [nioEventLoopGroup-6-51] [VM](VM.java:1247) VM halted: [Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[3], curOpEnergy[3], usedEnergy[3]]
15:48:03.557 INFO  [nioEventLoopGroup-6-51] [VM](VMActuator.java:265) runtime result is :Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[3], curOpEnergy[3], usedEnergy[3]
15:48:03.563 INFO  [nioEventLoopGroup-6-67] [net](MessageQueue.java:121) Receive from /54.38.178.205:45890, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.582 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 1 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.601 INFO  [nioEventLoopGroup-6-56] [net](MessageQueue.java:121) Receive from /8.209.79.63:41631, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.610 INFO  [nioEventLoopGroup-6-51] [VM](VM.java:1247) VM halted: [Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]]
15:48:03.610 INFO  [nioEventLoopGroup-6-51] [VM](VMActuator.java:265) runtime result is :Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]
15:48:03.612 WARN  [nioEventLoopGroup-6-41] [net](InventoryMsgHandler.java:52) Drop inv: TRX size: 3 from Peer /221.122.37.82, syncFromUs: true, syncFromPeer: false.
15:48:03.624 INFO  [nioEventLoopGroup-6-42] [net](MessageQueue.java:121) Receive from /49.12.129.50:41714, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.666 INFO  [nioEventLoopGroup-6-51] [DB](DynamicPropertiesStore.java:1992) update state flag = 0
15:48:03.666 INFO  [nioEventLoopGroup-6-51] [consensus](DposService.java:162) Update solid block number to 30269256
15:48:03.667 INFO  [nioEventLoopGroup-6-51] [DB](DynamicPropertiesStore.java:1987) update latest block header id = 0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
15:48:03.667 INFO  [nioEventLoopGroup-6-51] [DB](DynamicPropertiesStore.java:1979) update latest block header number = 30269274
15:48:03.667 INFO  [nioEventLoopGroup-6-51] [DB](DynamicPropertiesStore.java:1971) update latest block header timestamp = 1621259283000
15:48:03.668 INFO  [nioEventLoopGroup-6-51] [utils](ForkController.java:169) *******update hard fork:[JZYH=1, UWBZ=1, yD4M=1, PuCg=1, 7Jqf=1, DxQ1=1, Tere=1, dB9V=1, oZo1=1, 2sw9=1, MZcU=1, R3og=1, rQRt>
15:48:03.668 INFO  [nioEventLoopGroup-6-51] [DB](Manager.java:1044) save block: BlockCapsule
[ hash=0000000001cddf5ad0c2f1625cdb7e85af18b20a7e76bcc4ee2fc81996cbaf4c
number=30269274
parentId=0000000001cddf59d6a696772e33088fe3d5ebb145a6010788cc0ef87896ec68
`

**Comment by Starsakary** [comment]
1. DUP_TRANSACTION_ERROR: You've broadcasted a transaction with the same transaction hash as a former transaction, and neither of them was on the chain.
2. You don't have enough energy to completely execute the function. This can be caused by: low fee limit, insufficient energy and insufficient TRX for burning.

**Comment by StephanDre** [comment]
But it is transfer trx, no trc10 or trc20, and i not set fee limit, and i have tron on this address

**Comment by Starsakary** [comment]
That is a transaction of triggering a smart contract.
'PUSH1` is a TVM instruction, it will only be used with smart contracts.
