### ISSUE TITLE
USDT TRC20: Error "FAIL-TRANSACTION REVERT"

### ISSUE THREAD

**Issue by mainguyen1221** [tronprotocol/java-tron#3791]
### 1. What did you do?
I got "FAIL-TRANSACTION REVERT" problem when withdraw USDT. I used TRC20 transaction
Please check the below hash for more info
https://tronscan.org/#/transaction/37e9245336f1f252c60a51ce9089a1a06ce2c7dd51615529a8ac9558312b44d2
### 2. What did you expect to see?
I expected the USTD TRC20 transaction to go through (successfully) or the asset will be return to my USDT wallet

### 3. What did you see instead?
i see error FAIL-TRANSACTION REVERT and can not recieve my usdt. please help me recover my funds

**Comment by Starsakary** [comment]
'REVERT' usually points to an error that you haven't met the conditions in the 'require' statement.
The most commonly seen error while calling the function 'transfer' is you do not pass the check of balance.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
We will close this issue as no update for more than one week. 
Please feel free to re-open this issue if you still see it, thanks.
