### ISSUE TITLE
Tron address in Ruby

### ISSUE THREAD

**Issue by huuhait** [tronprotocol/java-tron#3796]
1. What did you do?
I'm trying to make my software working with Tron but i've no idea to encode Tron address in Ruby

Thanks for your help!

**Comment by Starsakary** [comment]
As far as I know, currently, there is not an official Ruby SDK.
You may refer to Protobuf and ABI encoding instructions.

**Comment by huuhait** [comment]
yes, maybe i'll make a NodeJS backend call to Tron
