### ISSUE TITLE
No asserts in unit tests

### ISSUE THREAD

**Issue by herpdederp** [tronprotocol/java-tron#38]
1. What did you do?
Run unit tests

2. What did you expect to see?
Asserts or validations.

3. What did you see instead?
Only logging

**Comment by seanrobbins** [comment]
There are some asserts, for example in TrieTest from what I can see. I agree this is an area which can definitely be improved.

**Comment by Rovak** [comment]
The team is aware of this are working on improving the tests. A lot of tests have already been improved since this issue has been created. I'll be closing this issue, if you have any specific tests you want to see improved then please reopen and update this issue with the specific tests.
