### ISSUE TITLE
FAIL-TRANSACTION REVERT>

### ISSUE THREAD

**Issue by freebrs16** [tronprotocol/java-tron#3806]
from bithumb global,gate.io I transferred usdt to the stock exchange, the money came out of bithumb global, but it appears as a perpetrator on the TRX page, please help, I sent $ 492 through the trc20 network, but my money did not come to my account 
![Screenshot_20210521-173413_Bithumb Global](https://user-images.githubusercontent.com/84595961/119192810-5f794100-ba89-11eb-8b7a-82f5a5928ec4.jpg)
![Screenshot_20210521-230857_Chrome](https://user-images.githubusercontent.com/84595961/119192942-90597600-ba89-11eb-9c98-ec111f216aa5.jpg)

**Comment by Alexliu007** [comment]
You need to check whether your address has enough USDT to transfer. also you can refer to this document for revert errors. https://developers.tron.network/docs/faq#4-how-to-troubleshoot-when-calling-the-contract-and-return-the-revert-error

**Comment by Benson0224** [comment]
We will close this issue as no feedback for more than one week. 
Please feel free to open this issue if you still see it. 

Thanks for your contribution to java-tron.

**Comment by rex951** [comment]
Pls benson I made a transfer of 9.9k usdt from an exchange to an external wallet and the receiving wallet didn’t get it, and the usdt dindt reverse bsck pls help,
