### ISSUE TITLE
Runing Tron FullNode

### ISSUE THREAD

**Issue by eskal** [tronprotocol/java-tron#3809]
### 1. What did you do?

Im runing tron fullnode on my server with 32cores, 128GB ram and nvme disk. I thougt this setup would be sufficient. 

### 2. What did you expect to see?
My heapsize is set to 100G, i expected to see no "not enough energy" messages :D 

### 3. What did you see instead?
12:40:27.340 INFO  [TronJClientWorker-3] [DB](KhaosDatabase.java:330) remove from khaosDatabase:0000000001d071e0364f977fa248e2d3293ddee6a2fb8f0c19f3ce470ee1c618
12:40:27.340 INFO  [TronJClientWorker-3] [DB](Manager.java:1597) PreValidate Transaction Sign, size:136, block num:30437877
12:40:27.371 INFO  [TronJClientWorker-3] [VM](VM.java:1247) VM halted: [Not enough energy for 'LOG3' operation executing: curInvokeEnergyLimit[27891], curOpEnergy[1756], usedEnergy[26197]]
12:40:27.371 INFO  [TronJClientWorker-3] [VM](VM.java:1247) VM halted: [Not enough energy for 'SWAP2' operation executing: curInvokeEnergyLimit[35723], curOpEnergy[3], usedEnergy[35723]]
12:40:27.371 INFO  [TronJClientWorker-3] [VM](VMActuator.java:265) runtime result is :Not enough energy for 'SWAP2' operation executing: curInvokeEnergyLimit[35723], curOpEnergy[3], usedEnergy[35723]
12:40:27.391 INFO  [TronJClientWorker-3] [VM](VM.java:1247) VM halted: [Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[5310], curOpEnergy[5000], usedEnergy[2303]]
12:40:27.391 INFO  [TronJClientWorker-3] [VM](VMActuator.java:265) runtime result is :Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[5310], curOpEnergy[5000], usedEnergy[2303]
12:40:27.411 INFO  [TronJClientWorker-3] [VM](VM.java:1247) VM halted: [Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[7143], curOpEnergy[5000], usedEnergy[6137]]
12:40:27.411 INFO  [TronJClientWorker-3] [VM](VMActuator.java:265) runtime result is :Not enough energy for 'SSTORE' operation executing: curInvokeEnergyLimit[7143], curOpEnergy[5000], usedEnergy[6137]
12:40:27.433 INFO  [TronJClientWorker-3] [DB](DynamicPropertiesStore.java:1992) update state flag = 0
12:40:27.433 INFO  [TronJClientWorker-3] [consensus](DposService.java:162) Update solid block number to 30437859
12:40:27.434 INFO  [TronJClientWorker-3] [DB](DynamicPropertiesStore.java:1987) update latest block header id = 0000000001d071f5b89e411226ce96aff49fb57eda5434cdbdde9e9ce3a5d9df
12:40:27.434 INFO  [TronJClientWorker-3] [DB](DynamicPropertiesStore.java:1979) update latest block header number = 30437877
12:40:27.434 INFO  [TronJClientWorker-3] [DB](DynamicPropertiesStore.java:1971) update latest block header timestamp = 1621766427000
12:40:27.434 INFO  [TronJClientWorker-3] [utils](ForkController.java:169) *******update hard fork:[JZYH=1, UWBZ=1, yD4M=1, PuCg=1, Tere=1, 7Jqf=1, DxQ1=1, dB9V=1, oZo1=1, 2sw9=1, MZcU=1, R3og=1, rQRt=1, mP6T=1, ZiR4=1, AWaA=1, fMqw=1, m6qY=1, ga7j=1, paTM=1, SToF=1, jEWP=1, z7sT=0, 7yGu=1, JA7b=1, WrfA=1, Bz1p=1], witness size:27, solt:20, witness:TKSXDA8HfE9E1y39RczVQ1ZascUEtaSToF, version:21
12:40:27.434 INFO  [TronJClientWorker-3] [DB](Manager.java:1044) save block: BlockCapsule 
[ hash=0000000001d071f5b89e411226ce96aff49fb57eda5434cdbdde9e9ce3a5d9df
number=30437877
parentId=0000000001d071f46834276a434046d3d8b5855f3d4aa80c8593bc4017c5e9cd
witness address=4167e39013be3cdd3814bed152d7439fb5b6791409

Thanks for letting me know if this output is ok all i need to configure something. Thanks!

**Comment by Alexliu007** [comment]
hi eskal, this is an error when the virtual machine executes the transaction, it will not affect the node, you can ignore it

**Comment by eskal** [comment]
Oh nice! i was affraid i have not enough resources :)

Dňa po 24. 5. 2021 o 7:56 Alexliu007 ***@***.***> napísala(a):

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
We will close this issue as it is already fixed. 
please feel free to re-open it if you still see it. thanks.
