### ISSUE TITLE
We will close this issue now as no update for a long time.

### ISSUE THREAD

**Issue by bungfut** [tronprotocol/java-tron#3817]
We will close this issue now as no update for a long time.
Please feel free to re-open this issue if you still see it. thanks.

_Originally posted by @Benson0224 in https://github.com/tronprotocol/java-tron/issues/3780#issuecomment-846758080_

**Comment by Benson0224** [comment]
HI

I just tried all the below links with my Chrome, all the addresses can successfully return the correct value.  does any of the below not working on your side? if yes please share the error messages. thanks. 

http://18.196.99.16:8090/wallet/getnodeinfo
http://18.133.82.227:8090/wallet/getnodeinfo
http://34.253.187.192:8090/wallet/getnodeinfo
http://35.180.51.163:8090/wallet/getnodeinfo
http://3.225.171.164:8090/wallet/getnodeinfo
http://13.127.47.162:8090/wallet/getnodeinfo
http://52.53.189.99:8090/wallet/getnodeinfo
http://34.220.77.106:8090/wallet/getnodeinfo
http://18.228.15.36:8090/wallet/getnodeinfo
http://13.124.62.58:8090/wallet/getnodeinfo
http://54.252.224.209:8090/wallet/getnodeinfo

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
We will close this PR as it is already answered in the above comments. 

Please feel free to re-open this PR if you still see the issue, thanks.

**Comment by bungfut** [comment]
> เราจะปิดปัญหานี้ในขณะนี้เนื่องจากไม่มีการอัปเดตเป็นเวลานาน
> โปรดเปิดปัญหานี้อีกครั้งหากคุณยังคงเห็น ขอบคุณ
> 
> _โพสต์ครั้งแรกโดย@Benson0224ใน[#3780 (ความคิดเห็น)](https://github.com/tronprotocol/java-tron/issues/3780#issuecomment-846758080)_

**Comment by bungfut** [comment]
> สวัสดี
> 
> ฉันเพิ่งลองลิงก์ด้านล่างทั้งหมดกับ Chrome ของฉัน ที่อยู่ทั้งหมดสามารถคืนค่าที่ถูกต้องได้สำเร็จ สิ่งใดด้านล่างไม่ทำงานกับคุณ? ถ้าใช่ โปรดแชร์ข้อความแสดงข้อผิดพลาด ขอบคุณ
> 
> [http://18.196.99.16:8090/wallet/getnodeinfo ](http://18.196.99.16:8090/wallet/getnodeinfo)
> [http://18.133.82.227:8090/wallet/getnodeinfo ](http://18.133.82.227:8090/wallet/getnodeinfo)
> [http://34.253.187.192:8090/wallet/getnodeinfo ](http://34.253.187.192:8090/wallet/getnodeinfo)
> [http://35.180.51.163:8090/wallet /getnodeinfo ](http://35.180.51.163:8090/wallet/getnodeinfo)
> [http://3.225.171.164:8090/wallet/getnodeinfo ](http://3.225.171.164:8090/wallet/getnodeinfo)
> [http://13.127.47.162:8090/wallet/getnodeinfo ](http://13.127.47.162:8090/wallet/getnodeinfo)
> [http://52.53.189.99:8090/wallet/getnodeinfo ](http://52.53.189.99:8090/wallet/getnodeinfo)
> [http://34.220.77.106:8090 /wallet/getnodeinfo ](http://34.220.77.106:8090/wallet/getnodeinfo)
> [http://18.228.15.36:8090/wallet/getnodeinfo ](http://18.228.15.36:8090/wallet/getnodeinfo)
> [http://13.124.62.58:8090/wallet/getnodeinfo ](http://13.124.62.58:8090/wallet/getnodeinfo)
> http://54.252.224.209:8090/wallet/getnodeinfo

@bungfut
