### ISSUE TITLE
Exception: GC overhead limit exceeded

### ISSUE THREAD

**Issue by CerberusGR** [tronprotocol/java-tron#3821]
/usr/lib/jvm/jdk1.8.0_281/bin/java -jar FullNode4.2.1.jar -c config.conf --es

### 2. What did you expect to see?
No errors

### 3. What did you see instead?
The following exception every time:

SLF4J: Failed toString() invocation on an object of type [org.tron.core.net.message.ChainInventoryMessage]
Reported exception:
java.lang.OutOfMemoryError: GC overhead limit exceeded
SLF4J: Failed toString() invocation on an object of type [org.tron.core.net.message.ChainInventoryMessage]
Reported exception:
java.lang.OutOfMemoryError: GC overhead limit exceeded

The same exception with Fullnode4.2.0 which I executed it for more than 15 days now with no errors, until yesterday.

**Comment by Alexliu007** [comment]
> /usr/lib/jvm/jdk1.8.0_281/bin/java -jar FullNode4.2.1.jar -c config.conf --es
> 
> ### 2. What did you expect to see?
> No errors
> 
> ### 3. What did you see instead?
> The following exception every time:
> 
> SLF4J: Failed toString() invocation on an object of type [org.tron.core.net.message.ChainInventoryMessage]
> Reported exception:
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> SLF4J: Failed toString() invocation on an object of type [org.tron.core.net.message.ChainInventoryMessage]
> Reported exception:
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> 
> The same exception with Fullnode4.2.0 which I executed it for more than 15 days now with no errors, until yesterday.

hi,What is your node machine configuration? Please provide the start command, also you can use Optimize Memory Allocation with tcmalloc,pls refer to this document  https://developers.tron.network/docs/fullnode#optimize-memory-allocation-with-tcmalloc

**Comment by CerberusGR** [comment]
Hello Alexliu007

The config file is the default config file for mainnet with the following changes:

    topics = [
        {
          triggerName = "block" // block trigger, the value can't be modified
          enable = true
          topic = "block" // plugin topic, the value could be modified
        },
        {
          triggerName = "transaction"
          enable = true
          topic = "transaction"
        },
        {
          triggerName = "contractevent"
          enable = true
          topic = "contractevent"
        },
        {
          triggerName = "contractlog"
          enable = true
          topic = "contractlog"
        },
        {
          triggerName = "solidity" // solidity block event trigger, the value can't be modified
          enable = false           // the default value is true
          topic = "solidity"
        }
    ]

I am using the same config for almost 2 months now with no problems.

the bash script I run is the following:

#!/bin/bash
export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4"
export TCMALLOC_RELEASE_RATE=8
cd /home/user/tron/deploy/fullnode/
/usr/lib/jvm/jdk1.8.0_281/bin/java -jar /home/user/tron/deploy/fullnode/FullNode4.2.1.jar -c config.conf --es

**Comment by Alexliu007** [comment]
Hi,could you add a gclog parameter when starting the node?  -Xloggc:./gc.log, and then re-start the node to provide the latest log file and gc log file？also you can try use this start script https://github.com/tronprotocol/java-tron/blob/develop/start.sh, thanks!

> Hello Alexliu007
> 
> The config file is the default config file for mainnet with the following changes:
> 
> ```
> topics = [
>     {
>       triggerName = "block" // block trigger, the value can't be modified
>       enable = true
>       topic = "block" // plugin topic, the value could be modified
>     },
>     {
>       triggerName = "transaction"
>       enable = true
>       topic = "transaction"
>     },
>     {
>       triggerName = "contractevent"
>       enable = true
>       topic = "contractevent"
>     },
>     {
>       triggerName = "contractlog"
>       enable = true
>       topic = "contractlog"
>     },
>     {
>       triggerName = "solidity" // solidity block event trigger, the value can't be modified
>       enable = false           // the default value is true
>       topic = "solidity"
>     }
> ]
> ```
> 
> I am using the same config for almost 2 months now with no problems.
> 
> the bash script I run is the following:
> 
> #!/bin/bash
> export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4"
> export TCMALLOC_RELEASE_RATE=8
> cd /home/user/tron/deploy/fullnode/
> /usr/lib/jvm/jdk1.8.0_281/bin/java -jar /home/user/tron/deploy/fullnode/FullNode4.2.1.jar -c config.conf --es

Hi,could you add a gclog parameter when starting the node?  -Xloggc:./gc.log, and then re-start the node to provide the latest log file and gc log file？also you can try use this start script https://github.com/tronprotocol/java-tron/blob/develop/start.sh, thanks!

**Comment by CerberusGR** [comment]
Hello,

I executed java-tron with start.sh script. The speed of processing is amazing on the same pc, no lag of events on event server.
I had also added tcmalloc option too.
On gc.log file I always get the following error which although does not stop the whole process:

2021-05-29T21:51:05.023+0300: 13629,196: [GC (Allocation Failure) 2021-05-29T21:51:05.023+0300: 13629,196: [ParNew: 281818K->4483K(306688K), 0,0115311 secs] 4422163K->4149996K(4884644K), 0,0116450 secs] [Times: user=0,04 sys=0,01, real=0,01 secs] 
2021-05-29T21:51:06.423+0300: 13630,596: [GC (Allocation Failure) 2021-05-29T21:51:06.424+0300: 13630,596: [ParNew: 277123K->4995K(306688K), 0,0124832 secs] 4422636K->4150708K(4884644K), 0,0126039 secs] [Times: user=0,05 sys=0,00, real=0,01 secs]

**Comment by Alexliu007** [comment]
> no lag of events on event server.
> I had also added tcmalloc option too.
> On gc.log file I always get the following error which although does not stop the whole process:

hi, you can add it in the startup script: XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./java-tron_heapdump.hprof
Dump file will be generated after oom, so you can provide the dump file, we will continue to analyze this problem, thanks!

**Comment by CerberusGR** [comment]
Hello again,

It crashed again with the following error:

2021-06-03T22:00:00.451+0300: 1803,821: [GC (Allocation Failure) 2021-06-03T22:00:00.451+0300: 1803,821: [ParNew: 283933K->15353K(306688K), 0,0147447 secs] 6606373K->6337816K(10818172K), 0,0148799 secs] [Times: user=0,06 sys=0,00, real=0,01 secs] 
2021-06-03T22:00:01.036+0300: 1804,406: [GC (Allocation Failure) 2021-06-03T22:00:01.036+0300: 1804,406: [ParNew: 287993K->15754K(306688K), 0,0166285 secs] 6610456K->6340944K(10818172K), 0,0167365 secs] [Times: user=0,06 sys=0,00, real=0,02 secs] 
2021-06-03T22:00:01.219+0300: 1804,589: [GC (Allocation Failure) 2021-06-03T22:00:01.219+0300: 1804,590: [ParNew: 288394K->11258K(306688K), 0,0157756 secs] 6613584K->6340853K(10818172K), 0,0158796 secs] [Times: user=0,06 sys=0,00, real=0,02 secs] 
2021-06-03T22:00:01.605+0300: 1804,975: [GC (Allocation Failure) 2021-06-03T22:00:01.605+0300: 1804,975: [ParNew: 283898K->11417K(306688K), 0,0133641 secs] 6613493K->6341034K(10818172K), 0,0134710 secs] [Times: user=0,05 sys=0,00, real=0,01 secs] 
Heap
 par new generation   total 306688K, used 184101K [0x00000004c0000000, 0x00000004d4cc0000, 0x00000004d4cc0000)
  eden space 272640K,  63% used [0x00000004c0000000, 0x00000004ca8a31f0, 0x00000004d0a40000)
  from space 34048K,  33% used [0x00000004d2b80000, 0x00000004d36a6560, 0x00000004d4cc0000)
  to   space 34048K,   0% used [0x00000004d0a40000, 0x00000004d0a40000, 0x00000004d2b80000)
 concurrent mark-sweep generation total 10511484K, used 6329617K [0x00000004d4cc0000, 0x00000007565df000, 0x00000007c0000000)
 Metaspace       used 53351K, capacity 55422K, committed 55692K, reserved 1097728K
  class space    used 6088K, capacity 6478K, committed 6600K, reserved 1048576K

Dump file never created

**Comment by Alexliu007** [comment]
> Hello again,
> 
> It crashed again with the following error:
> 
> ```
> 2021-06-03T22:00:00.451+0300: 1803,821: [GC (Allocation Failure) 2021-06-03T22:00:00.451+0300: 1803,821: [ParNew: 283933K->15353K(306688K), 0,0147447 secs] 6606373K->6337816K(10818172K), 0,0148799 secs] [Times: user=0,06 sys=0,00, real=0,01 secs] 
> 2021-06-03T22:00:01.036+0300: 1804,406: [GC (Allocation Failure) 2021-06-03T22:00:01.036+0300: 1804,406: [ParNew: 287993K->15754K(306688K), 0,0166285 secs] 6610456K->6340944K(10818172K), 0,0167365 secs] [Times: user=0,06 sys=0,00, real=0,02 secs] 
> 2021-06-03T22:00:01.219+0300: 1804,589: [GC (Allocation Failure) 2021-06-03T22:00:01.219+0300: 1804,590: [ParNew: 288394K->11258K(306688K), 0,0157756 secs] 6613584K->6340853K(10818172K), 0,0158796 secs] [Times: user=0,06 sys=0,00, real=0,02 secs] 
> 2021-06-03T22:00:01.605+0300: 1804,975: [GC (Allocation Failure) 2021-06-03T22:00:01.605+0300: 1804,975: [ParNew: 283898K->11417K(306688K), 0,0133641 secs] 6613493K->6341034K(10818172K), 0,0134710 secs] [Times: user=0,05 sys=0,00, real=0,01 secs] 
> Heap
>  par new generation   total 306688K, used 184101K [0x00000004c0000000, 0x00000004d4cc0000, 0x00000004d4cc0000)
>   eden space 272640K,  63% used [0x00000004c0000000, 0x00000004ca8a31f0, 0x00000004d0a40000)
>   from space 34048K,  33% used [0x00000004d2b80000, 0x00000004d36a6560, 0x00000004d4cc0000)
>   to   space 34048K,   0% used [0x00000004d0a40000, 0x00000004d0a40000, 0x00000004d2b80000)
>  concurrent mark-sweep generation total 10511484K, used 6329617K [0x00000004d4cc0000, 0x00000007565df000, 0x00000007c0000000)
>  Metaspace       used 53351K, capacity 55422K, committed 55692K, reserved 1097728K
>   class space    used 6088K, capacity 6478K, committed 6600K, reserved 1048576K
> ```
> 
> Dump file never created
Hi, how is your node machine configuration? cores and Memory?  Our recommended configuration:
CPU: 16 cores
Memory: 32G
also could u please execute jinfo -flags [tron pid] and provide return information? 

thanks!

**Comment by Alexliu007** [comment]
Hi, does your tron node service and event-plugin service run on the same server? and what is your node machine configuration?

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
We will close this issue as no feedback for a long time. 

Please feel free to re-open this issue if you still see it, thanks.
