### ISSUE TITLE
[Error] Cannot deploy contract onto Testnet

### ISSUE THREAD

**Issue by puftoken** [tronprotocol/java-tron#3822]
**What I am doing**
I am trying to deploy smart contract onto testnet shasta. But whenever I try to deploy a contract it always shows CORS POLICY ERROR error.

**Expected Behaviour**
Contact should be deployed successfully onto Testnet.

**Actual Behaviour**
I am trying to deploy a smart contract via the online tool at: https://shasta.tronscan.org/#/contracts/contract-compiler

It compiles fine, without errors, but when I am trying to deploy it, in the network developer tools tab I get the following error: 
`Access to XMLHttpRequest at 'https://api.shasta.trongrid.io/walletsolidity/gettransactioninfobyid' from origin 'https://shasta.tronscan.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
and
`POST https://api.shasta.trongrid.io/walletsolidity/gettransactioninfobyid net::ERR_FAILED`

What can the issue be ?

**Comment by Alexliu007** [comment]
> **What I am doing**
> I am trying to deploy smart contract onto testnet shasta. But whenever I try to deploy a contract it always shows CORS POLICY ERROR error.
> 
> **Expected Behaviour**
> Contact should be deployed successfully onto Testnet.
> 
> **Actual Behaviour**
> I am trying to deploy a smart contract via the online tool at: https://shasta.tronscan.org/#/contracts/contract-compiler
> 
> It compiles fine, without errors, but when I am trying to deploy it, in the network developer tools tab I get the following error:
> `Access to XMLHttpRequest at 'https://api.shasta.trongrid.io/walletsolidity/gettransactioninfobyid' from origin 'https://shasta.tronscan.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
> and
> `POST https://api.shasta.trongrid.io/walletsolidity/gettransactioninfobyid net::ERR_FAILED`
> 
> What can the issue be ?

Hi, I can normally deploy contracts on the shasta testnet. Is the tronlink plug-in network you are using the shasta testnet?

**Comment by puftoken** [comment]
Hello @Alexliu007 

I confirm that I am connected to the shasta testnet whilst trying to deploy the contract.
I have some trx as well from the faucet and i have energy and power.

Thank you,
Cristian

**Comment by Alexliu007** [comment]
hi puftoken, you can try to clear the browser cache and deploy again, or you can join the TRON developer community, so that communication may be more efficient  Telegram:https://developers.tron.network/docs/online-technical-support                                                     ![image](https://user-images.githubusercontent.com/33770261/119782740-231d6900-beff-11eb-99cd-5fb2e2d2270b.png)

**Comment by puftoken** [comment]
As it appears, the contract gets deployed eventually, even if I do not get the response in the browser.
