### ISSUE TITLE
After adding the directory mapping, docker cannot start the image

### ISSUE THREAD

**Issue by liuhuanhui** [tronprotocol/java-tron#3824]
（ -v /tron:/java-tron）After adding the directory mapping, docker cannot start the image:
```
[root@VM-16-4-centos tron]# docker run -v /tron:/java-tron -d -p 18888:18888 -p 50051:50051 -it tronprotocol/java-tron
217f15307c2616014b12c2304413ad32f05da3d629636b2330393ecb46241185
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./bin/docker-entrypoint.sh": stat ./bin/docker-entrypoint.sh: no such file or directory: unknown.
```

**Comment by Alexliu007** [comment]
hi you can refer to the dockerfile https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile, but currently you need to create a image by yourself. We will feedback your needs to the relevant team as soon as possible, thanks!

**Comment by liuhuanhui** [comment]
> hi you can refer to the dockerfile https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile, but currently you need to create a image by yourself. We will feedback your needs to the relevant team as soon as possible, thanks!
I have created my own image through build, but when I started the image to set the node directory mapping, I threw an error and did not run it
**exec comand**
```
 docker run -v /tron:/java-tron -d -p 18888:18888 -p 50051:50051 -it javatron:latest
```
**error:**
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./bin/docker-entrypoint.sh": stat ./bin/docker-entrypoint.sh: no such file or directory: unknown.
```

**Comment by Alexliu007** [comment]
> > hi you can refer to the dockerfile https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile, but currently you need to create a image by yourself. We will feedback your needs to the relevant team as soon as possible, thanks!
> > I have created my own image through build, but when I started the image to set the node directory mapping, I threw an error and did not run it
> > **exec comand**
> 
> ```
>  docker run -v /tron:/java-tron -d -p 18888:18888 -p 50051:50051 -it javatron:latest
> ```
> 
> **error:**
> 
> ```
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./bin/docker-entrypoint.sh": stat ./bin/docker-entrypoint.sh: no such file or directory: unknown.
> ```
> 
> Dockerfile
> https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile

Hi, You can try to modify the permissions of docker-entrypoint.sh, such as executing RUN chmod +x $BASE_DIR/bin/docker-entrypoint.sh

**Comment by liuhuanhui** [comment]
> https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile
Docker didn't work all the time, so I decided to give up

**Comment by liuhuanhui** [comment]
> > > hi you can refer to the dockerfile https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile, but currently you need to create a image by yourself. We will feedback your needs to the relevant team as soon as possible, thanks!
> > > I have created my own image through build, but when I started the image to set the node directory mapping, I threw an error and did not run it
> > > **exec comand**
> > 
> > 
> > ```
> >  docker run -v /tron:/java-tron -d -p 18888:18888 -p 50051:50051 -it javatron:latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **error:**
> > ```
> > docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./bin/docker-entrypoint.sh": stat ./bin/docker-entrypoint.sh: no such file or directory: unknown.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Dockerfile
> > https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile
> 
> Hi, You can try to modify the permissions of docker-entrypoint.sh, such as executing RUN chmod +x $BASE_DIR/bin/docker-entrypoint.sh

Docker didn't work all the time, so I decided to give up

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
We will close this issue now. 
please feel free to re-open it if you still see it. thanks.
