### ISSUE TITLE
Vote counting issue

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3825]
Hi everyone,
I am running private network in tron. 

### 1. What did you do?
I created SR using RPC call, then i started to vote for SR using RPC call but vote count can't increase waited for 2 days and the transaction result will be success 
**Command for SR vote:** curl --request POST --url http://<ip>:16667/wallet/votewitnessaccount --header 'Content-Type: application/json' --data '{"owner_address":"<owner_address>","votes":[{"vote_address":"<voter_address>","vote_count":100}]}'

How long does it take to complete the vote count increasing?

### 2. What did you expect to see?
Vote count updation.

### 3. What did you see instead?
Waiting for long time i cannot get any update in vote count.

**Comment by Alexliu007** [comment]
> Hi everyone,
> I am running private network in tron.
> 
> ### 1. What did you do?
> I created SR using RPC call, then i started to vote for SR using RPC call but vote count can't increase waited for 2 days and the transaction result will be success
> **Command for SR vote:** curl --request POST --url http://:16667/wallet/votewitnessaccount --header 'Content-Type: application/json' --data '{"owner_address":"<owner_address>","votes":[{"vote_address":"<voter_address>","vote_count":100}]}'
> 
> How long does it take to complete the vote count increasing?
> 
> ### 2. What did you expect to see?
> Vote count updation.
> 
> ### 3. What did you see instead?
> Waiting for long time i cannot get any update in vote count.

Hi, this interface just creates an unsigned transaction, you also need to sign the transaction and broadcast the transaction

**Comment by osiz-blockchainapp** [comment]
> > Hi everyone,
> > I am running private network in tron.
> > ### 1. What did you do?
> > I created SR using RPC call, then i started to vote for SR using RPC call but vote count can't increase waited for 2 days and the transaction result will be success
> > **Command for SR vote:** curl --request POST --url http://:16667/wallet/votewitnessaccount --header 'Content-Type: application/json' --data '{"owner_address":"<owner_address>","votes":[{"vote_address":"<voter_address>","vote_count":100}]}'
> > How long does it take to complete the vote count increasing?
> > ### 2. What did you expect to see?
> > Vote count updation.
> > ### 3. What did you see instead?
> > Waiting for long time i cannot get any update in vote count.
> 
> Hi, this interface just creates an unsigned transaction, you also need to sign the transaction and broadcast the transaction

Hi @Alexliu007,
I creates unsigned transaction, then sign and broadcast the transaction. Everything i did, but vote count takes long time to update.

**Comment by Alexliu007** [comment]
Hi, @osiz-blockchainapp, you can check as follows:

1. Check whether the transaction parameters are correct, like vote_address is the SR address.
2. Make sure the transaction is successful.
3. The mainnet counts votes every 6 hours. Please check the setting of this parameter maintenanceTimeInterval in your private chain configuration file.
4. Check whether the proposal on the private chain is consistent with the mainnet.

Thanks!

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
We will close this issue as no feedback for a long time.

Please feel free to re-open this issue if you still see it, thanks.
