### ISSUE TITLE
How can I get real asset name in  transfer_asset_contract.asset_name，now it's a number(asset_id which I guess)

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [tronprotocol/java-tron#3828]
### 1. What did you do?

Tried to get asset name by using  transfer_asset_contract.asset_name=asset_issue_contract.id,
but asset_issue_contract.id is always null string
### 2. What did you expect to see?
Expect get real asset name (compare to tronscan.org ) from transfer_asset_contract.asset_name
Thanks!
![image](https://user-images.githubusercontent.com/39079736/120258652-08fbd600-c2c5-11eb-919f-9c854dffbe82.png)

### 3. What did you see instead?
none

**Comment by Starsakary** [comment]
```java
message AssetIssueContract {
  string id = 41;

  message FrozenSupply {
    int64 frozen_amount = 1;
    int64 frozen_days = 2;
  }
  bytes owner_address = 1;
  bytes name = 2;
  bytes abbr = 3;
  int64 total_supply = 4;
  repeated FrozenSupply frozen_supply = 5;
  int32 trx_num = 6;
  int32 precision = 7;
  int32 num = 8;
  int64 start_time = 9;
  int64 end_time = 10;
  int64 order = 11;  // useless
  int32 vote_score = 16;
  bytes description = 20;
  bytes url = 21;
  int64 free_asset_net_limit = 22;
  int64 public_free_asset_net_limit = 23;
  int64 public_free_asset_net_usage = 24;
  int64 public_latest_free_net_time = 25;
}
```
This is the original proto of `AssetIssue`. You should get `name` instead of `id`.

**Comment by oushu1zhangxiangxuan1** [comment]
> ```java
> message AssetIssueContract {
>   string id = 41;
> 
>   message FrozenSupply {
>     int64 frozen_amount = 1;
>     int64 frozen_days = 2;
>   }
>   bytes owner_address = 1;
>   bytes name = 2;
>   bytes abbr = 3;
>   int64 total_supply = 4;
>   repeated FrozenSupply frozen_supply = 5;
>   int32 trx_num = 6;
>   int32 precision = 7;
>   int32 num = 8;
>   int64 start_time = 9;
>   int64 end_time = 10;
>   int64 order = 11;  // useless
>   int32 vote_score = 16;
>   bytes description = 20;
>   bytes url = 21;
>   int64 free_asset_net_limit = 22;
>   int64 public_free_asset_net_limit = 23;
>   int64 public_free_asset_net_usage = 24;
>   int64 public_latest_free_net_time = 25;
> }
> ```
> 
> This is the original proto of `AssetIssue`. You should get `name` instead of `id`.

Thank you ~ but what I want to know it how to get the mapping between asset_id and asset_name, AssetIssueContract.id is always a null string, do you know how to get the exact asset_id by AssetIssueContract proto?

I found a workaround by retrieve the fullnode database asset_issue_v2,  but it's not a proper way for real-time demand。

**Comment by Starsakary** [comment]
If you were trying to acquire data directly from the database, the suggestion will be reading the code here :
https://github.com/tronprotocol/java-tron/blob/develop/framework/src/main/java/org/tron/core/Wallet.java#L1249
as the reference.

**Comment by Starsakary** [comment]
You can't specify the id of a TRC-10 token, as you can see here: 
https://github.com/tronprotocol/java-tron/blob/develop/actuator/src/main/java/org/tron/core/actuator/AssetIssueActuator.java#L70

id is automatically incremented by 1 each time.

**Comment by oushu1zhangxiangxuan1** [comment]
> You can't specify the id of a TRC-10 token, as you can see here:
> https://github.com/tronprotocol/java-tron/blob/develop/actuator/src/main/java/org/tron/core/actuator/AssetIssueActuator.java#L70
> 
> id is automatically incremented by 1 each time.

Truly appreciate your timely help
