### ISSUE TITLE
Optimize the logic of block production to reduce block production time

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/java-tron#3829]
### 1. What did you do?

Avoid repeated execution of transactions to save block production time. In the current block production logic, witness will re-execute the transactions in the pending queue, and set the packaging timeout period to 750ms, this will cost much time.

### 2. What did you expect to see?
Shorten the time to produce the block as much as possible.

### 3. What did you see instead?
The time consumption of block production is mainly used to execute transactions. Can the pending transaction be directly assigned to the block? It is completely feasible in theory, because pending transactions are executed in order, so there is no need to re-execute them.

A new block production method:
1. Assign the transaction of the pending queue directly to the block
2. If there are still transactions in the re-push queue, pack the transactions in the re-push queue
3. The execution time of cumulative transactions cannot exceed 750ms

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed.
Please feel free to re-open it if you still see it. thanks.

**Comment by lazike66** [comment]
Great
