### ISSUE TITLE
Tron compile with Apple Silicon MacBook Pro m1

### ISSUE THREAD

**Issue by folowing** [tronprotocol/java-tron#3834]
### 1. What did you do?

git clone -b master https://github.com/tronprotocol/java-tron.git
cd ./java-tron
./gradlew build

### 2. What did you expect to see?
Build Success

### 3. What did you see instead?
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':protocol:generateProto'.
> Could not resolve all files for configuration ':protocol:protobufToolsLocator_grpc'.
   > Could not find protoc-gen-grpc-java-osx-aarch_64.exe (io.grpc:protoc-gen-grpc-java:1.9.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.9.0/protoc-gen-grpc-java-1.9.0-osx-aarch_64.exe

**Comment by Benson0224** [comment]
Please make sure you are using Oracle JDK 8, otherwise the build will fail.

check build guide at : https://github.com/tronprotocol/java-tron/blob/develop/build.md

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open this issue if you still see it, thanks.
