### ISSUE TITLE
Deploying tron mainnet. Problem with conf parsing.

### ISSUE THREAD

**Issue by MarcSky** [tronprotocol/java-tron#3840]
### 1. What did you do?
I want to run Tron main net Full node.
I using this guide https://steemcn.herokuapp.com/tron/@ety001/how-to-deploy-a-tron-fullnode-by-docker

### 2. What did you expect to see?
I want to run node :)

### 3. What did you see instead?
`Exception in thread "main" com.typesafe.config.ConfigException$Parse: main_net_config.conf: 7: Key '<' may not be followed by token: '!' (Reserved character '!' is not allowed outside quotes) (if you intended '!' (Reserved character '!' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes)`

**Comment by Benson0224** [comment]
From the error message seems your `main_net_config.conf` file includes some illegal characters. 

Please download the correct file from : https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf 

You can also refer to the official guide on how to deploy a fullnode: 
https://developers.tron.network/docs/fullnode

**Comment by MarcSky** [comment]
@Benson0224 it's sad but I using official mainnet config from your link above...

**Comment by Benson0224** [comment]
can you please share the command of starting the fullnode? thanks. 
Please upload your config file here for further checking, thanks.

**Comment by lazike66** [comment]
> ### 1. What did you do?
> I want to run Tron main net Full node.
> I using this guide https://steemcn.herokuapp.com/tron/@ety001/how-to-deploy-a-tron-fullnode-by-docker
> 
> ### 2. What did you expect to see?
> I want to run node :)
> 
> 
> ### 3. What did you see instead?
> `Exception in thread "main" com.typesafe.config.ConfigException$Parse: main_net_config.conf: 7: Key '<' may not be followed by token: '!' (Reserved character '!' is not allowed outside quotes) (if you intended '!' (Reserved character '!' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes)`

**Comment by Benson0224** [comment]
is the issue still there? please provide more info:
1. The java version ( only support JDK 1.8 Oracle JDK, no open jdk)
2. The command of starting the fullnode

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open this issue if you still see it, thanks.

**Comment by MarcSky** [comment]
@Benson0224 I starting node with my command

```
docker run -itd --name tron-node \
    --restart always \
    -p 18888:18888 \
    -p 8090:8090 \
    -p 8091:8091 \
    -p 5555:5555 \
    -v $(pwd):/app \
    --workdir /app \
    mcr.microsoft.com/java/jdk:8-zulu-ubuntu \
    java -Xmx32g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c main_net_config.conf
```

I found this solution here https://game.dclick.io/posts/@ety001/how-to-deploy-a-tron-fullnode-by-docker

**Comment by MarcSky** [comment]
When I try using 11-zulu-ubuntu I getting next error, hm :)

```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/app/FullNode.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
******** begin to pop revokingDb ********
******** before revokingDb size:0
******** end to pop revokingDb ********
```

**Comment by MarcSky** [comment]
I don't know how its work but I just downloaded fresh config and now its work )

**Comment by daniel-tron** [comment]
They should update the documents.

Correct:
wget **https://raw.githubusercontent.com**/tronprotocol/tron-deployment/master/main_net_config.conf

Wrong:
wget https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf
