### ISSUE TITLE
Where is the Wallet or Accounts stored? 

### ISSUE THREAD

**Issue by MohseniBigBoy** [tronprotocol/java-tron#3842]
I run Tron node using `java -jar FullNode.jar -c config_main.conf` and I use [tronpy](https://tronpy.readthedocs.io/en/latest/quickstart.html#installation) to use RPC methods. When I use `client.generate_address()` a new address is generated, but I could not find where these addresses were stored. Do I have to save them myself in a database?

**Comment by vivian-kang** [comment]
Hi MohseniBigBoy，
This API helps to generate an account and returns the address info and public and private keys. They are not stored automatically. You should store the account information by yourself.

**Comment by MohseniBigBoy** [comment]
Thanks.
🙏🌹
