### ISSUE TITLE
Brokerage ratio updation

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3844]
Hi Everyone,

### 1. What did you do?
I try to update brokerage ratio in tron private network using RPC call.
But it wont update.

curl --request POST \
>   --url http://<ip>:16667/wallet/updateBrokerage \
>   --header 'Accept: application/json' \
>   --header 'Content-Type: application/json' \
>   --data '
> {
>   "owner_address": "<address>",
>   "brokerage": 30
> }
> '

### 2. What did you expect to see?
Brokerage ratio updation successfully

### 3. What did you see instead?
{"Error":"class org.tron.core.exception.ContractValidateException : contract type error, unexpected type [UpdateBrokerageContract]"}

Kindly provide solution for this issue

**Comment by ibsaaqa11** [comment]
Register

**Comment by ibsaaqa11** [comment]
Register problem

**Comment by ibsaaqa11** [comment]
He was studied in haramaya

**Comment by ibsaaqa11** [comment]
Iv

**Comment by ibsaaqa11** [comment]
Hgv

**Comment by ibsaaqa11** [comment]
Ttgf

**Comment by ibsaaqa11** [comment]
Ggih

**Comment by osiz-blockchainapp** [comment]
> Register problem

Hi,
Where to register?

**Comment by Starsakary** [comment]
The cause is parameter `CHANGE_DELEGATION`.

The is a proposal-related problem, happens mostly on private chain builders. The simplest way to solve this is to add the parameter in the `committee` item of your node configuration:

```xml
committee = {
  allowChangeDelegation = 1
}
```

I will highly recommend you to take a look at the code if you need to build a private chain, as the documentation may not have every detail of the code.

**Comment by osiz-blockchainapp** [comment]
> The cause is parameter `CHANGE_DELEGATION`.
> 
> The is a proposal-related problem, happens mostly on private chain builders. The simplest way to solve this is to add the parameter in the `committee` item of your node configuration:
> 
> ```
> committee = {
>   allowChangeDelegation = 1
> }
> ```
> 
> I will highly recommend you to take a look at the code if you need to build a private chain, as the documentation may not have every detail of the code.

Hi @Starsakary,
I added  'allowChangeDelegation = 1' but still having same issue while update brokerge.

**Comment by Benson0224** [comment]
Please share the updated configuration file here for further investigation. thanks.

**Comment by osiz-blockchainapp** [comment]
> Please share the updated configuration file here for further investigation. thanks.

Hi @Benson0224 
The below configuration file is updated.
net {
  type = mainnet
  # type = testnet
}

storage {
  # Directory for storing persistent data

  db.version = 2,
  db.engine = "LEVELDB",
  db.directory = "database",
  index.directory = "index",

  # You can custom these 14 databases' configs:

  # account, account-index, asset-issue, block, block-index,
  # block_KDB, peers, properties, recent-block, trans,
  # utxo, votes, witness, witness_schedule.

  # Otherwise, db configs will remain defualt and data will be stored in
  # the path of "output-directory" or which is set by "-d" ("--output-directory").

  # Attention: name is a required field that must be set !!!
  properties = [
    //    {
    //      name = "account",
    //      path = "storage_directory_test",
    //      createIfMissing = true,
    //      paranoidChecks = true,
    //      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
    //    {
    //      name = "account-index",
    //      path = "storage_directory_test",
    //      createIfMissing = true,
    //      paranoidChecks = true,
    //      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
  ]

}

# this part of config is used to node discovery.
node.discovery = {
  enable = true  # you should set this entry value with ture if you want your node can be discovered by other node.
  persist = true  # this entry is used to determined to whether storing the peers in the database or not.
  bind.ip = ""
  external.ip = 127.0.0.1
}

# this part of config is used to set backup node for witness service.
node.backup {
  port = 10001
  priority = 8
  members = [
  ]
}

node {
  # trust node for solidity node
  # trustNode = "ip:port"
  trustNode = "127.0.0.1:50051"

  # expose extension api to public or not
  walletExtensionApi = true

  listen.port = 16666

  connection.timeout = 2

  tcpNettyWorkThreadNum = 0

  udpNettyWorkThreadNum = 1

  # Number of validate sign thread, default availableProcessors / 2
  # validateSignThreadNum = 16

  maxActiveNodes = 30

  maxActiveNodesWithSameIp = 2

  minParticipationRate = 0

  # check the peer data transfer ,disconnect factor
  disconnectNumberFactor = 0.4
  maxConnectNumberFactor = 0.8
  receiveTcpMinDataLength = 2048
  isOpenFullTcpDisconnect = true

  p2p {
    version = 22222 # 11111: mainnet; 20180622: testnet; you can set other number when you deploy one private net, but the node must have the same number in some private net. 
  }

  active = [
    # Active establish connection in any case
    # Sample entries:
    # "ip:port"
  ]

  passive = [
    # Passive accept connection in any case
    # Sample entries:
    # "ip:port"
  ]

  http {
    fullNodePort = 16667
    solidityPort = 16668
  }

  rpc {
    port = 50051

    # Number of gRPC thread, default availableProcessors / 2
    # thread = 16

    # The maximum number of concurrent calls permitted for each incoming connection
    # maxConcurrentCallsPerConnection =

    # The HTTP/2 flow control window, default 1MB
    # flowControlWindow =

    # Connection being idle for longer than which will be gracefully terminated
    maxConnectionIdleInMillis = 60000

    # Connection lasting longer than which will be gracefully terminated
    # maxConnectionAgeInMillis =

    # The maximum message size allowed to be received on the server, default 4MB
    # maxMessageSize =

    # The maximum size of header list allowed to be received, default 8192
    # maxHeaderListSize =

    # Transactions can only be broadcast if the number of effective connections is reached.
    minEffectiveConnection = 0
  }

}



seed.node = {
  # List of the seed nodes. This is used to enable the node can connect when join one net at first.
  # If you deploy one private net, you must add some "ip:port" here for other node connecting.
  # Seed nodes are stable full nodes, and the first SuperNode must be inclued in.
  # example:
  # ip.list = [
  #   "ip:port",
  #   "ip:port"
  # ]
  ip.list = [
  ]
}

genesis.block = {
  # Reserve balance
  assets = [
       {
      accountName = "Zion"
      accountType = "AssetIssue"
      address = "TDp4x8kCJ6aHz8wnqZgkaVQAm2ajH1og3L"
      balance = "95000000000000000"
    },
    {
      accountName = "Sun"
      accountType = "AssetIssue"
      address = "TDp4x8kCJ6aHz8wnqZgkaVQAm2ajH1og3L"
      balance = "5000000000000000"
    },
    {
      accountName = "Blackhole"
      accountType = "AssetIssue"
      address = "TDp4x8kCJ6aHz8wnqZgkaVQAm2ajH1og3L"
      balance = "-9223372036854775808"
    }
  ]

  witnesses = [
    {
      address: TPbBpRXnt6ztse8XkCLiJstZyqQZvxW2sx,
      url = "http://w1.com",
      voteCount = 10200
    }
  ]

  timestamp = "0" #2017-8-26 12:00:00

  parentHash = "957dc2d350daecc7bb6a38f3938ebde0a0c1cedafe15f0edae4256a2907449f6"
}

localwitness = [
  08089C24EC3BAEB34254DDF5297CF8FBB8E031496FF67B4EFACA738FF9EBD455 # you must enable this value and the witness address are match.
]

#localwitnesskeystore = [
#  "src/main/resources/localwitnesskeystore.json"  # if you do not set the localwitness above, you must set this value.Otherwise,your SuperNode can not produce the block. 
#]

block = {
  needSyncCheck = false # first node : false, other : true
  maintenanceTimeInterval = 21600000 // 1 day: 86400000(ms), 6 hours: 21600000(ms)
}


vm = {
  supportConstant = true
  minTimeRatio = 0.0
  maxTimeRatio = 5.0
}

committee = {
  allowCreationOfContracts = 1  //mainnet:0 (reset by committee),test:1
  allowMultiSign = 1 //mainnet:0 (reset by committee),test:1
  allowChangeDelegation = 1
  allowDelegateResource = 1
  allowSameTokenName = 1
  allowLvmTransferTrc10 = 1
  allowLvmConstantinople = 1
  allowLvmSolidity059 = 1
  allowMarketTransaction = 1
}

event.subscribe = {
  native = {
    useNativeQueue = true // if true, use native message queue, else use event plugin.
    bindport = 5555 // bind port
    sendqueuelength = 1000 //max length of send queue
  }

  path = "" // absolute path of plugin
  server = "" // target server address to receive event triggers
  dbconfig = "" // dbname|username|password
  contractParse = true,
  topics = [
    {
      triggerName = "block" // block trigger, the value can't be modified
      enable = false
      topic = "block" // plugin topic, the value could be modified
    },
    {
      triggerName = "transaction"
      enable = false
      topic = "transaction"
    },
    {
      triggerName = "contractevent"
      enable = false
      topic = "contractevent"
    },
    {
      triggerName = "contractlog"
      enable = false
      topic = "contractlog"
    },
    {
      triggerName = "solidity" // solidity block event trigger, the value can't be modified
      enable = true            // the default value is true
      topic = "solidity"
    }
  ]

  filter = {
    fromblock = "" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
    toblock = "" // the value could be "", "latest" or a specified block number as end of the queried range
    contractAddress = [
      "" // contract address you want to subscribe, if it's set to "", you will receive contract logs/events with any contract address.
    ]

    contractTopic = [
      "" // contract topic you want to subscribe, if it's set to "", you will receive contract logs/events with any contract topic.
    ]
  }
}

**Comment by BIGBANGDEVTRON** [comment]
66938dae3329c7aebe598c2246a8e6af90d04646

**Comment by Benson0224** [comment]
dup as https://github.com/tronprotocol/java-tron/issues/3855,  
This issue will be closed and please sue https://github.com/tronprotocol/java-tron/issues/3855 to follow up, thanks.
