### ISSUE TITLE
Some trans has no timestamp

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [tronprotocol/java-tron#3845]
### 1. What did you do?

Parsing trans data from block leveldb of fullnode snapshot 20210425

### 2. What did you expect to see?
Get trans timestamp

### 3. What did you see instead?
Some trans has no timestamp in raw data.
For example
| trans_hash | block_num | 
| - | - | 
| e778d0a204d72dc2b3507c17823f797dc5d35fdf34ac1e17280421f2c7c36063|28466248 | 
| 783b564cedaf323c8dc955cd2c4a9cb00e14a1dc5df784ceacc2c1e1e96f2576|28519316 |
| 2c171162d498bab62adcb8826155bef171d56eaf63086448316ba72e975733a9|28519302 |

**Comment by oushu1zhangxiangxuan1** [comment]
### Another problem
trans_hash f2281a79ab38039aa375ec308d30e1824ec5805f26b6a444dfded4cf02aaa829 in block 26937276

I got timestamp: 1611191710144 and transformed it to datetime with postgresql(without timezone) and python: 
```
without time zone: 2021-1-21 01:15:10
with time zone: 2021-1-21 09:15:10
```

But in transcan.org, the time is 
![image](https://user-images.githubusercontent.com/39079736/122155526-b7914080-ce99-11eb-86f7-4fb2758603ad.png)
AND
https://tronscan.org/#/transaction/f2281a79ab38039aa375ec308d30e1824ec5805f26b6a444dfded4cf02aaa829

**Comment by Benson0224** [comment]
Hi,
The time displayed on Tronscan is the block timestamp. not transaction timestamp. 
The timestamp of the block you mentioned above is 1611191724000, after transferred it is the same with tronscan. 

![image](https://user-images.githubusercontent.com/61768920/122166410-2c6d7600-ceac-11eb-83a2-6ac1dd7c71a6.png)

You can get the block timestamp from this this API: 
https://api.trongrid.io/wallet/gettransactioninfobyid?value=f2281a79ab38039aa375ec308d30e1824ec5805f26b6a444dfded4cf02aaa829

**Comment by oushu1zhangxiangxuan1** [comment]
> Hi,
> The time displayed on Tronscan is the block timestamp. not transaction timestamp.
> The timestamp of the block you mentioned above is 1611191724000, after transferred it is the same with tronscan.
> 
> ![image](https://user-images.githubusercontent.com/61768920/122166410-2c6d7600-ceac-11eb-83a2-6ac1dd7c71a6.png)
> 
> You can get the block timestamp from this this API:
> https://api.trongrid.io/wallet/gettransactioninfobyid?value=f2281a79ab38039aa375ec308d30e1824ec5805f26b6a444dfded4cf02aaa829

Thanks! And the time in transaction detail page on Tronscan is block time too?
![image](https://user-images.githubusercontent.com/39079736/122167540-b79b3b80-cead-11eb-81b7-41cda971dd1c.png)

**Comment by Benson0224** [comment]
> > Hi,
> > The time displayed on Tronscan is the block timestamp. not transaction timestamp.
> > The timestamp of the block you mentioned above is 1611191724000, after transferred it is the same with tronscan.
> > ![image](https://user-images.githubusercontent.com/61768920/122166410-2c6d7600-ceac-11eb-83a2-6ac1dd7c71a6.png)
> > You can get the block timestamp from this this API:
> > https://api.trongrid.io/wallet/gettransactioninfobyid?value=f2281a79ab38039aa375ec308d30e1824ec5805f26b6a444dfded4cf02aaa829
> 
> Thanks! And the time in transaction detail page on Tronscan is block time too?
> ![image](https://user-images.githubusercontent.com/39079736/122167540-b79b3b80-cead-11eb-81b7-41cda971dd1c.png)

Yes.

**Comment by oushu1zhangxiangxuan1** [comment]
这种交易一般是自己写代码创建的， 没有指定时间戳， 交易中的时间戳被没有被用到， 所以指不指定都没啥影响"

**Comment by oushu1zhangxiangxuan1** [comment]
> ### 1. What did you do?
> Parsing trans data from block leveldb of fullnode snapshot 20210425
> 
> ### 2. What did you expect to see?
> Get trans timestamp
> 
> ### 3. What did you see instead?
> Some trans has no timestamp in raw data.
> For example
> 
> trans_hash	block_num
> e778d0a204d72dc2b3507c17823f797dc5d35fdf34ac1e17280421f2c7c36063	28466248
> 783b564cedaf323c8dc955cd2c4a9cb00e14a1dc5df784ceacc2c1e1e96f2576	28519316
> 2c171162d498bab62adcb8826155bef171d56eaf63086448316ba72e975733a9	28519302

这种交易一般是自己写代码创建的， 没有指定时间戳， 交易中的时间戳被没有被用到， 所以指不指定都没啥影响"

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed as the answer is already clear now. 
Please feel free to re-open this issue if you still see it, thanks.
