### ISSUE TITLE
be careful, trace.getRuntimeResult().getTriggerList() should never return null

### ISSUE THREAD

**Issue by bartly** [tronprotocol/java-tron#3850]
### 1. What did you do?

Deploy the java tron in my server. And deploy the event plugin which is connected to Mongodb
There is a question is . I can only receive Three of topic . 

![image](https://user-images.githubusercontent.com/3798791/122316814-0d73f000-cf4f-11eb-9657-6dc92990dc39.png)

the following screemshot is my config.conf
![image](https://user-images.githubusercontent.com/3798791/122316852-182e8500-cf4f-11eb-9b41-a227aef5926f.png)

### 2. What did you expect to see?

Why did not I see all the topic event in my mongodb?

With debugger, I found the code didnt go in the code block because of trace.getRuntimeResult().getTriggerList() is null.But it is supposed to be not null???

Can anyone tell me why ?
Is it a wrong configuration? Or something what?

Thank you for all your help.

**Comment by Alexliu007** [comment]
hi What is the block height of your local TRON node? Is the event plugin synchronized from the genesis block? you can refer to this is Event Plugin Deployment (MongoDB) related deployment [documents](https://developers.tron.network/docs/event-plugin-deployment-mongodb)

**Comment by Benson0224** [comment]
Thanks for your contribution to https://github.com/tronprotocol/java-tron
This issue will be closed as the answer is already included in the above comments.
Please feel free to re-open this issue if you still see it, thanks.
