### ISSUE TITLE
How can I get TRC20&721 info like tronscan from fullnode data

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [tronprotocol/java-tron#3856]
### 1. What did you do?

Parsed full-node block data
Want to get TRC20&721 detail

### 2. What did you expect to see?
 TRC20&721 detail which contains:
from_address
to_address
amount
contract_address or asset_id ?

like this:
![image](https://user-images.githubusercontent.com/39079736/122516057-dd0c7e80-d040-11eb-965c-fbb1f524f9ec.png)

### 3. What did you see instead?
I parsed trans&contract in block data,
but only get data for TriggerSmartContract like this :
```python
>>> c = smart_contract.TriggerSmartContract()
>>> c.ParseFromString(t.raw_data.contract[0].parameter.value)
116
>>>
>>> c
owner_address: "AT\373\266\234+y\363\3362p\270\2374\207q\362\325\251\201\212"
contract_address: "A\246\024\370\003\266\375x\t\206\244,x\354\234\177w\346\336\321<"
data: "\251\005\234\273\000\000\000\000\000\000\000\000\000\000\000Aa@D\246v\234\223\323\373b\212\246\323\303\323P\007\302\205\213\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000w&Q\300"
```
How could I get TRC20&TRC721's from_address & to_address & amount

**Comment by Alexliu007** [comment]
You can refer to the [document](https://developers.tron.network/docs/parameter-and-return-value-encoding-and-decoding
) 
I see that you have a lot of questions here. You can join the TRON developer group so that your questions will be answered in time.
Telegram TRON English Developer Technical Support：
https://t.me/TronOfficialDevelopersGroupEn
Wechat group:
hello-zyuming

**Comment by Benson0224** [comment]
Thanks for your contribution to https://github.com/tronprotocol/java-tron
This issue will be closed as the answer is already included in the above comments.
Please feel free to re-open this issue if you still see it, thanks.
