### ISSUE TITLE
InternalTransaction data stores in which database in fullnode ?

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [tronprotocol/java-tron#3857]

**Comment by Alexliu007** [comment]
hi, InternalTransaction stored in transactionRetStore, for details, you can check the relevant source code. And you can get relevant data of internal transactions through the interface [gettransactioninfobyid](https://developers.tron.network/reference#transaction-info-by-id).

**Comment by Benson0224** [comment]
Thanks for your contribution to https://github.com/tronprotocol/java-tron
This issue will be closed as the answer is already included in the above comments.
Please feel free to re-open this issue if you still see it, thanks.
