### ISSUE TITLE
> You will not lose your token if the transaction failed, it is still in your wallet.

### ISSUE THREAD

**Issue by lazike66** [tronprotocol/java-tron#3864]
> You will not lose your token if the transaction failed, it is still in your wallet.
> 
> Please check more info on why time out from here: https://developers.tron.network/docs/faq#2-why-would-i-trigger-out_of_time-error-when-calling-contract-function

Thanks for the info. I will close the ticket when the exchange returns the money to me.

_Originally posted by @Lobzzzz in https://github.com/tronprotocol/java-tron/issues/3843#issuecomment-862184477_

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed as the answer is already clear now. 
Please feel free to re-open this issue if you still see it, thanks.
