### ISSUE TITLE
Issue on brokerage limit

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3879]
Hi,
I am running private network in Tron.

### 1. What did you do?
Updation of brokerage broadcast successfully.But still not updated in getBrokerage for particular address.

### 2. What did you expect to see?
The updated brokerage ratio is updated in getbrokerage.

### 3. What did you see instead?
Not updated in get brokerage

Kindly give me a solution asap.

**Comment by Starsakary** [comment]
I'm trying to reproduce this problem on my own private chain. The solution will be given later.
