### ISSUE TITLE
Cannot update SR Team Information On Tronscan Due To Bug.

### ISSUE THREAD

**Issue by chainchopper** [tronprotocol/java-tron#3886]
### 1. What did you do?

Added a github link for team information to tronscan.org as directed.

### 2. What did you expect to see?
Team information updated

### 3. What did you see instead?
The link is malformed that is created including two HTTPS paramaters. This is a bug within tronscan and have to be fixed by someone with access to the script. Nothing i can do can fix this unless there is another mechanism for updating team information for SR.

![image](https://user-images.githubusercontent.com/36168576/124062984-d5b18180-d9ff-11eb-890b-528d62f1dff9.png)

**Comment by zyumingfit** [comment]
Please provide your SR address.

**Comment by Benson0224** [comment]
Team info is already updated, check the detail info here:   https://tronscan.org/#/representative/TGBSbjAmv4NU8w11q4drFj2Pz9PcEXf62Z 

this issue will be closed as it is already fixed, please feel free to re-open this issue if you still see it, thanks.
