### ISSUE TITLE
Is it possible to use from SAS 10K HDD instead of SSD storage?

### ISSUE THREAD

**Issue by MohseniBigBoy** [tronprotocol/java-tron#3889]
I want to generate a new address, send TRX, and get received transactions by an address, so I run a Tron full node using [this](https://developers.tron.network/docs/fullnode). To speed up syncing I download and use the [database](https://backups.trongrid.io/). after some days I see the last block number in my node is 31229944 but the current value is [31580880](https://tronscan.org/#/). I use an HP G10 server with 256GB RAM and 40 cores but the storage is SAS 10K instead of SSD. 

What should be the minimum read and write speed on the hard drive? 

Should I use from SSD storage or it will be synced in the next few days?

**Comment by Benson0224** [comment]
can you share the tron.log  of your node for further investigation? thanks.

**Comment by MohseniBigBoy** [comment]
You can download and extract [this](https://github.com/tronprotocol/java-tron/files/6754054/tron.log.zip).

**Comment by Benson0224** [comment]
from the log i can see your node has run into "Different resultCode" Error.
![image](https://user-images.githubusercontent.com/61768920/124361873-16a9d000-dc64-11eb-8e5e-d53515968fdf.png)

please change `maxTimeRatio` to 50 or higher value in your node configuration and start the node again after change done. thanks. 

here is the detail guide: 
https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

**Comment by MohseniBigBoy** [comment]
I change `maxTimeRatio` to **150** ! Every thing is OK and synchronization speed has been increased. when synchronization finished I will report that usage of SAS (instead of SSD) does not cause problem on syncing.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open this issue if you still see it.  thanks.
