### ISSUE TITLE
Warning: Address is empty

### ISSUE THREAD

**Issue by nnl-engineering** [tronprotocol/java-tron#3890]
### 1. What did you do?

1. Use command

Run FullNode in testnet
```bash
nohup java -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -jar FullNode.jar   -p eb0c48f154855f8b1ee8f30b7b254c2c51fe17d603d17a66fb58bf429aa4464b --witness -c /home/user/FullNode/test_net_config.conf
```

### 2. What did you expect to see?

Launched FullNode

### 3. What did you see instead?
Error in logs

```bash
13:58:46.378 INFO  [main] [app](FullNode.java:48) Full node running.
13:58:47.294 WARN  [main] [Commons](DecodeUtil.java:28) Warning: Address need prefix with -96 but 65 !!
13:58:47.295 WARN  [main] [Commons](DecodeUtil.java:17) Warning: Address is empty !!
```

Is my command to launch FullNode correct? I have export private key from a browser extenstion.

**Comment by vivian-kang** [comment]
Maybe you should change the net type as mainnet in config file as below:
net {
  type = mainnet
  # type = testnet
}

**Comment by nnl-engineering** [comment]
@vivian-kang I have changed net type to mainet in the file FullNode/test_net_config.conf. FullNode has started!
