### ISSUE TITLE
Method calling issue

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3892]
Hi,
Running private network in Tron. Trying to call method in tronweb.
I was not able to call method function but write function works fine.

![image](https://user-images.githubusercontent.com/48212011/124580002-4d9f0200-de6d-11eb-9809-ac2b6f62568f.png)

How to overcome this issue?

**Comment by Benson0224** [comment]
Please check the log of your node, and quote the response message here, thanks.

**Comment by osiz-blockchainapp** [comment]
> Please check the log of your node, and quote the response message here, thanks.

Hi @Benson0224 ,
In my 'tron.log' file, it does not contain any response message. 
Running the tronweb node while method calling it results: "The call has been reverted or has thrown an error."

**Comment by vivian-kang** [comment]
which version of java-tron do you use?

**Comment by osiz-blockchainapp** [comment]
> which version of java-tron do you use?

Cloned develop branch in java tron.

**Comment by vivian-kang** [comment]
Did you ever use the java-tron whose version is bigger than 4.2.1?

**Comment by Benson0224** [comment]
pleases share your tron.log here for further investigation. thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open this issue if you still see it. thanks.
