### ISSUE TITLE
Please help me FAIL-TRANSACTION REVERT

### ISSUE THREAD

**Issue by samsunglucky** [tronprotocol/java-tron#3895]
### 1. What did you do?

Please help me FAIL-TRANSACTION REVERT
https://tronscan.org/#/transaction/764d168c0726ca26f06db0daea8539366cea97039dfddfd78e20b885f281815c

**Comment by Benson0224** [comment]
HI,

from your account, I can see you have 44 USDT now.  
![image](https://user-images.githubusercontent.com/61768920/124891669-c936b580-e00b-11eb-9f14-7b3f66bd6c68.png)


however, in that transaction, you are trying to transfer 415 USDT to TJCcU8YcXLADYwNsaAty3u2FfGSkpqBTqh . 

That is why it reverted. please check your balance and input the correct amount during transfer. thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue if you still see it. thanks.
