### ISSUE TITLE
* What went wrong: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

### ISSUE THREAD

**Issue by Gr3enh4nd** [tronprotocol/java-tron#3897]
### 1. What did you do?

sudo ./gradlew build

### 2. What did you expect to see?
编译报错

### 3. What did you see instead?

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

16:44:19.770 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
16:44:19.770 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:44:19.770 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.<init>(DefaultExtraPropertiesExtension.java:29)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.extensibility.DefaultConvention.<init>(DefaultConvention.java:48)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.plugins.DefaultConvention.<init>(DefaultConvention.java:28)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.extensibility.ExtensibleDynamicObject.<init>(ExtensibleDynamicObject.java:60)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.instantiation.MixInExtensibleDynamicObject.<init>(MixInExtensibleDynamicObject.java:34)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultSettings_Decorated.getAsDynamicObject(Unknown Source)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.SettingsFactory.createSettings(SettingsFactory.java:58)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.process(ScriptEvaluatingSettingsProcessor.java:61)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.PropertiesLoadingSettingsProcessor.process(PropertiesLoadingSettingsProcessor.java:38)
16:44:19.771 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.SettingsEvaluatedCallbackFiringSettingsProcessor.process(SettingsEvaluatedCallbackFiringSettingsProcessor.java:34)

**Comment by Gr3enh4nd** [comment]
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**Comment by Benson0224** [comment]
HI,
java-tron only support JDK8 for compile. 
![image](https://user-images.githubusercontent.com/61768920/125056880-40874a80-e0db-11eb-8b80-a38f82644a8d.png)

Check the detail compile instruction here: 
https://github.com/tronprotocol/java-tron/blob/develop/build.md

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue if you still see it. thanks.
