### ISSUE TITLE
How long does the compilation process take? I've been compiling for more than an hour and I haven't finished it yet

### ISSUE THREAD

**Issue by Gr3enh4nd** [tronprotocol/java-tron#3900]
### 1. What did you do?

sudo ./gradlew build

### 3. What did you see instead?

![2021-07-12 13-58-03 的屏幕截图](https://user-images.githubusercontent.com/29044777/125238038-38b4e980-e319-11eb-886d-fe99e15bc5c1.png)

**Comment by Benson0224** [comment]
it depends on your HW configuration. 

By default, the test cases are enabled and quite time-consuming.  you can try below command which can skip the test part. 

`./gradlew build -x test`

**Comment by Gr3enh4nd** [comment]
thank you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月12日(星期一) 下午2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tronprotocol/java-tron] How long does the compilation process take? I&#39;ve been compiling for more than an hour and I haven&#39;t finished it yet (#3900)





 
it depends on your HW configuration.
 
By default, the test cases are enabled and quite time-consuming.  you can try below command which can skip the test part.
 
./gradlew build -x test

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue if you still see it. thanks.

**Comment by Mita1w** [comment]
I been scamed  bad you have no idea
