### ISSUE TITLE
Developing own indexer for Tron

### ISSUE THREAD

**Issue by MarcSky** [tronprotocol/java-tron#3918]
### 1. What did you do?
I developing indexer for quickly search transaction in blockchain, for example, for payment purpose.

### 2. What did you expect to see?
I want receiving different transactions with different input fields (amount, from address, to address, date)

### 3. What did you see instead?
Nothing :)

I have few questions because now I developing my own indexer for Tron blockchain.

1) Does the Tron mempool or I can get all transactions from blocks.
2) Does the Tron reorganisation of chain like ethereum or bitcoin, or with dPoS its not problem in Tron.
3) Can be transaction replaced with new (for example, with more fee).

**Comment by peacebd** [comment]
Thanks

**Comment by Starsakary** [comment]
1. You can retrieve all transactions from the hard disk database, as RAM is used to store only unconfirmed transactions.

2. Assuming you're referring to forked chains, I can say that forking is not a problem for DPOS; or, if you're referring to something like Ethereum layer 2, I can say that is not a problem for TRON at the moment, as those upgrades are primarily aimed at improving performance, and DPOS is significantly more efficient than POW.

3. Transactions have an expiration duration (60 seconds by default, 24 hours by maximum, depending on the specific node configuration), and they cannot be cancelled on TRON until they have expired.

On TRON, transactions are processed serially according to their broadcasting times, and transaction fees are automatically generated based on the transaction's size and the number of TVM instructions involved. Transaction fees cannot be customized.

Please refer to the following documentation for details:
[Resource Model](https://developers.tron.network/docs/resource-model)
[DPOS Concensus](https://developers.tron.network/docs/concensus)
[Energy Cost Calculations](https://developers.tron.network/docs/energy-cost)

**Comment by MarcSky** [comment]
@Starsakary Hello. Thanks for your great answer.
I have one question. How can I get access to ROCKSDB from Golang? Do you know some examples?

**Comment by Starsakary** [comment]
You're welcome.
I suggest you search for demos from Google.
