### ISSUE TITLE
Invalid operation code: opCode[47] on contract balance

### ISSUE THREAD

**Issue by GalinDinkov** [tronprotocol/java-tron#3929]
### 1. What did you do?

Accessing the balance of a contract address reverts with ILLEGAL_OPERATION (Invalid operation code: opCode[47])
The solidity code causing this is:

function getBalance() public view returns (uint256) {
  return address(this).balance; // This is causing it
}

This reverts in tronbox tests running on tron/quickstart docker image (java tron 3.6.6) with solidity version 0.5.4

### 2. What did you expect to see?

The contract address balance to be returned.

### 3. What did you see instead?

{
  id: '942e082271f6fe19dbbc497b8a126fe01cdec3aad3c8af339edaa1380300c122',
  fee: 990000100,
  blockNumber: 87,
  blockTimeStamp: 1626454500000,
  contractResult: [ '' ],
  contract_address: '4194e437b9a2deac92ca89ba0202f04d602901021e',
  receipt: {
    energy_usage: 54492042461,
    energy_fee: 990000100,
    energy_usage_total: 54501942462,
    net_usage: 346,
    result: 'ILLEGAL_OPERATION'
  },
  result: 'FAILED',
  resMessage: '496e76616c6964206f7065726174696f6e20636f64653a206f70436f64655b34375d3b'
}

**Comment by Alexliu007** [comment]
Use the interface wallet/getchainparameters to query the relevant proposal configuration and ensure that the getAllowTvmTransferTrc10 parameter value is 1.

**Comment by GalinDinkov** [comment]
Thanks for the reply @Alexliu007 

> Use the interface wallet/getchainparameters to query the relevant proposal configuration and ensure that the getAllowTvmTransferTrc10 parameter value is 1.

It is on:
{"key": "getAllowTvmTransferTrc10","value": 1}

However shouldn't it work with TRX?

The problems is only with contract addresses.

**Comment by GalinDinkov** [comment]
Seems that this is duplicate of this one: 
https://github.com/tronprotocol/tronbox/issues/116

**Comment by Alexliu007** [comment]
> tronprotocol/tronbox#116

Yes, please use the latest Fullnode version, like 4.2.2, thanks!

**Comment by rubo** [comment]
It's worth mentioning that `allowTvmIstanbul = 1` is required. Otherwise, it doesn't work.
