### ISSUE TITLE
Help for German translation

### ISSUE THREAD

**Issue by adrianlambertz** [tronprotocol/java-tron#394]
I would like to help for german translations. I am familiar with mo/po file localization.
Could help with the Website, Tronscan, Weekly Report and so on.

Feel free to contact me if any help is needed.

**Comment by DrKaradenizli** [comment]
Hi m8!

Currently I am assigned for the German translations. If you want you can give me your mail and I throw you a mail if I need your help with something?

Best Regards

**Comment by ebyjacob** [comment]
Hi

My Mail id is eby7jacob@gmail.com. Please do let me know if there is
anything i can be of help with tron project

Regards,
Eby

**Comment by adrianlambertz** [comment]
adrian.lambertz@me.com is my mail address.

**Comment by DrKaradenizli** [comment]
Thank you guys! Will definitely do that.

Best Regards

**Comment by HaoqiZhao** [comment]
We are setting up the translation platform using crowdin.com. 
You can find more information there. https://crowdin.com/project/trondocs
Thanks.

**Comment by DrKaradenizli** [comment]
I can not access the link.

**Comment by ybhgenius** [comment]
Hello,

Thanks for your participation.

Please check this link:

https://crowdin.com/project/trondocs

You can translate or correct relevant texts through this link.

We will reward you according to your contribution.

Best Regards

Boheng Yang
