### ISSUE TITLE
Voting calculation

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3944]
Hi,
How to calculate voting, block and voter reward in tron?
**scenario-1**
If I am not a witness and vote for witness, can i get voting reward?
If yes, How the calculation works?

**scenario-2**
If I am a SR Partner and not producing any blocks, How unwithdraw rewards will be occured?

Kindly anyone give a brief explanation about voting and block reward concept.
Thanks in advance!

**Comment by Benson0224** [comment]
Please check the reward calculation guide here: https://developers.tron.network/docs/mechanism#rewards
Please leave comments here if you still have more questions. thanks.

**Comment by osiz-blockchainapp** [comment]
> Please check the reward calculation guide here: https://developers.tron.network/docs/mechanism#rewards
> Please leave comments here if you still have more questions. thanks.

Hi,
Checked with above link. But calculation is mismatched. 
What is voting, block and voter reward?
How it can be calculated?

**Comment by Benson0224** [comment]
> > Please check the reward calculation guide here: https://developers.tron.network/docs/mechanism#rewards
> > Please leave comments here if you still have more questions. thanks.
> 
> Hi,
> Checked with above link. But calculation is mismatched.
> What is voting, block and voter reward?
> How it can be calculated?
Please provide more regarding the mismatch item.
It would help if you can provide how you calculate the reward? thanks. 

Regarding block reward and Vote reward, per TRON design, there will be 16TRX block reward and 160 Vote reward for every new block.

**Comment by osiz-blockchainapp** [comment]
> > > Please check the reward calculation guide here: https://developers.tron.network/docs/mechanism#rewards
> > > Please leave comments here if you still have more questions. thanks.
> > 
> > 
> > Hi,
> > Checked with above link. But calculation is mismatched.
> > What is voting, block and voter reward?
> > How it can be calculated?
> > Please provide more regarding the mismatch item.
> > It would help if you can provide how you calculate the reward? thanks.
> 
> Regarding block reward and Vote reward, per TRON design, there will be 16TRX block reward and 160 Vote reward for every new block.

What about voter rewards?

**Comment by Benson0224** [comment]
> > > > Please check the reward calculation guide here: https://developers.tron.network/docs/mechanism#rewards
> > > > Please leave comments here if you still have more questions. thanks.
> > > 
> > > 
> > > Hi,
> > > Checked with above link. But calculation is mismatched.
> > > What is voting, block and voter reward?
> > > How it can be calculated?
> > > Please provide more regarding the mismatch item.
> > > It would help if you can provide how you calculate the reward? thanks.
> > 
> > 
> > Regarding block reward and Vote reward, per TRON design, there will be 16TRX block reward and 160 Vote reward for every new block.
> 
> What about voter rewards?

The Voter Reward section in the document talks about how to calculate the rewards allocated to Voters.

**Comment by osiz-blockchainapp** [comment]
> > > > > Please check the reward calculation guide here: https://developers.tron.network/docs/mechanism#rewards
> > > > > Please leave comments here if you still have more questions. thanks.
> > > > 
> > > > 
> > > > Hi,
> > > > Checked with above link. But calculation is mismatched.
> > > > What is voting, block and voter reward?
> > > > How it can be calculated?
> > > > Please provide more regarding the mismatch item.
> > > > It would help if you can provide how you calculate the reward? thanks.
> > > 
> > > 
> > > Regarding block reward and Vote reward, per TRON design, there will be 16TRX block reward and 160 Vote reward for every new block.
> > 
> > 
> > What about voter rewards?
> 
> The Voter Reward section in the document talks about how to calculate the rewards allocated to Voters.

Hi,
I vote for SR, but can i get voting reward or voter reward?
The reward will be added in 'allowance under getaccount' or 'getreward' function.

**Comment by Benson0224** [comment]
> Hi,
> I vote for SR, but can i get voting reward or voter reward?
> The reward will be added in 'allowance under getaccount' or 'getreward' function.

After Vote SR, whether you can get a reward also depends on the SR Setting.  for example, if a SR set "Voting sharing ratio" to 0, means his/her voters cannot get any reward.  see below pic. https://tronscan.org/#/sr/representatives
![image](https://user-images.githubusercontent.com/61768920/127818370-0d490d3b-4f0c-4916-98d6-c3503b5bbdeb.png)

Your reward can be queried from "getReward" API. 

Regarding "I vote for SR, but can i get voting reward or voter reward?", you can find the answers from https://developers.tron.network/docs/mechanism, Please read carefully. thanks.

**Comment by osiz-blockchainapp** [comment]
> > Hi,
> > I vote for SR, but can i get voting reward or voter reward?
> > The reward will be added in 'allowance under getaccount' or 'getreward' function.
> 
> After Vote SR, whether you can get a reward also depends on the SR Setting. for example, if a SR set "Voting sharing ratio" to 0, means his/her voters cannot get any reward. see below pic. https://tronscan.org/#/sr/representatives
> ![image](https://user-images.githubusercontent.com/61768920/127818370-0d490d3b-4f0c-4916-98d6-c3503b5bbdeb.png)
> 
> Your reward can be queried from "getReward" API.
> 
> Regarding "I vote for SR, but can i get voting reward or voter reward?", you can find the answers from https://developers.tron.network/docs/mechanism, Please read carefully. thanks.

Hi,
Thanks @Benson0224 
Then how to calculate APR in above image?

**Comment by Benson0224** [comment]
> Hi,
> Thanks @Benson0224
> Then how to calculate APR in above image?

It is very easy, based on how many votes the SR gets, you can calculate how much reward that SR can earn per year. 
Then can you calculate how much your vote can earn if you vote that SR based on the ratio SR set. 
Then you will know what is the APR.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed as no update for days.
Feel free to re-open it if you still see it. thanks.
