### ISSUE TITLE
Add an api for querying block header in `http api` and `grpc`

### ISSUE THREAD

**Issue by MIMIEYES** [tronprotocol/java-tron#3945]
It is strongly recommended to add an api for querying block headers in `http api` and `grpc`. In some business scenarios, I only need to know the block hash and block time. Currently, I have to query an entire block. On the mainnet, most blocks are hundreds of transactions, which undoubtedly increases the IO burden on API servers and developers.

**Comment by zhangwenhua-tron** [comment]
@MIMIEYES Thank you for your suggestion, getting only the block header would be more convenient in some scenarios. The community will discuss your suggestion and decide whether to add some block header-only interfaces.

**Comment by MIMIEYES** [comment]
Thank you for your reply. I suggest that the design of `TRON`'s api should refer to the api design of `ethereum` to make it easier for developers to join the development of `TRON`.

For example, I check the confirmed transaction through the transaction hash, and want to get the block height where it is located, I have to check the transaction receipt again.

For example, in `trident-java`, I query transactions through transaction hash, but I can’t intuitively get basic transaction information like `from`, `to`, `value`. Of course, I know that `TRON` has many transaction types. However, the basic transaction information can still be abstracted out.

**Comment by Benson0224** [comment]
> Thank you for your reply. I suggest that the design of `TRON`'s api should refer to the api design of `ethereum` to make it easier for developers to join the development of `TRON`.
> 
> For example, I check the confirmed transaction through the transaction hash, and want to get the block height where it is located, I have to check the transaction receipt again.
> 
> For example, in `trident-java`, I query transactions through transaction hash, but I can’t intuitively get basic transaction information like `from`, `to`, `value`. Of course, I know that `TRON` has many transaction types. However, the basic transaction information can still be abstracted out.

Thanks for your suggestion. 
Please submit new issues to https://github.com/tronprotocol/trident if you run into any issue in Trident. 
Also, feel free to join our Telegram Groups. There are many very experienced developers in the group who can help each other. https://t.me/TronOfficialDevelopersGroupEn

**Comment by halibobo1205** [comment]
@MIMIEYES , I think we can refer to `eth`, add `a  bool parameter` to all methods of getting block.
 F or example, parameter `detail,` `true `means get transaction information, `false `means just get block header.

**Comment by halibobo1205** [comment]
No longer using compatible with the original interface, but in future versions of the new interface

**Comment by Rachi26** [comment]
سليم

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as it is implemented by [GreatVoyage-v4.5.2](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.5.2).

Check implementation PR at https://github.com/tronprotocol/java-tron/pull/4492  https://github.com/tronprotocol/java-tron/pull/4552 .
