### ISSUE TITLE
FAIL-TRANSACTION REVERT>

### ISSUE THREAD

**Issue by 3461610003** [tronprotocol/java-tron#3948]
### 1. What did you do?
Please look at this question for me：FAIL-TRANSACTION REVERT>
https://tronscan.io/#/transaction/ee9a047222494ede5ee766caa9cf02d10cb1414cc47e2eaad4ef09f071889991

### 2. What did you expect to see?
Transfer succeeded

### 3. What did you see instead?
FAIL-TRANSACTION REVERT>

**Comment by Benson0224** [comment]
Hi,
From your account history seems Your account has an insufficient USDT balance at that time.

![image](https://user-images.githubusercontent.com/61768920/127606965-1ae30a54-343c-4f97-880b-1ba13a6e70ee.png)

Until now(2021-07-30 13:55:45  SGT) you have 693USDT.  Let us do a simple calculation:
693 + 30 + 199 - 699 +259 - 299 = 183

So at the reverted transaction time (2021-07-29 11:20:00), you have 183 USDT and you are trying to send 199 USDT to TQEQ7PpJDZpqTarvFXbhW7QwgvNaeb5Xkb, that is why it is reverted. thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed as no update for days.
Feel free to re-open it if you still see it. thanks.
