### ISSUE TITLE
Random password login access

### ISSUE THREAD

**Issue by Cyphernode** [tronprotocol/java-tron#395]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I can login in the tronscan account with any random password and it logs into a new account address.

2. What did you expect to see?

Obviously not being able to login

3. What did you see instead?

Login access with any password

**Comment by Rovak** [comment]
Thanks for the report, moved to `wallet-web` project: https://github.com/tronprotocol/wallet-web/issues/20

**Comment by grandpaWilly** [comment]
I suspect this is a matter of language. Your password seems to be your input salt to generate your expected private key. "Logging in" with a different password simply gives you a new receiving address.

**Comment by Rovak** [comment]
That is correct, we use the term "password" because most non-technical people are familiar with that
