### ISSUE TITLE
GreatVoyage-v4.3.0(Bacon) Forced upgrade deadline?

### ISSUE THREAD

**Issue by pthor11** [tronprotocol/java-tron#3964]
### 1. What did you do?

There new coming release GreatVoyage-v4.3.0(Bacon) is mentioned that is "Forced upgrade"

### 2. What did you expect to see?
But what is the last day for older version compatible. 

### 3. What did you see instead?
A more clear about timeline would be very helpful.

**Comment by Benson0224** [comment]
Please complete your upgrade to the new version before 23:59 17th August 2021 (SGT). Otherwise, it will affect the node synchronization.

**Comment by pthor11** [comment]
Perfectly clear, thank you @Benson0224

**Comment by BisonAl** [comment]
My team had the same question, it could be very helpful to add these timelines to the [releases](https://github.com/tronprotocol/java-tron/releases) themselves!

**Comment by Benson0224** [comment]
> My team had the same question, it could be very helpful to add these timelines to the [releases](https://github.com/tronprotocol/java-tron/releases) themselves!

One option is to join "Tron Official Developer Group" at https://t.me/TronOfficialDevelopersGroupEn 
or join our Discord at https://discord.gg/Sk3ehK3mzq 

We will notify all developers regarding the upgrade there.
