### ISSUE TITLE
Is is possible block hash (blockID) of a block number could changed ?

### ISSUE THREAD

**Issue by pthor11** [tronprotocol/java-tron#3965]
### 1. What did you do?

 We installed kafka plugin to our mainnet full node. But the block hash we get sometimes is not the same as data we call to explorer by api. How did that possible ?. We did received a block number 32494192 with block hash `0000000001efd270219973c25f1a162825e5e6dabfc9206e030a7bb9e62ced34`, timestamp `1627959870000` from our kafka

### 2. What did you expect to see?
Block hash is `0000000001efd270219973c25f1a162825e5e6dabfc9206e030a7bb9e62ced34` of course

### 3. What did you see instead?
`0000000001efd270c570c5243d6a71d26ac806e8c20fb83c2dbf55f77f1a085b`
https://tronscan.org/#/block/32494192

**Comment by halibobo1205** [comment]
Hi , this is a normal occurrence. The switchFork occurred at that point, and you can check the logs to confirm.
You might find that `switch fork! new head num` in the log for that day

**Comment by pthor11** [comment]
Thank you @halibobo1205 , as a client, how can I get this `switch fork` logs from our node ? Is there any API or WebSocket for something like that?

**Comment by pthor11** [comment]
Oh no ....

**Comment by Benson0224** [comment]
The event also supports "Solidity Event", Solidity Event will be triggered once the block is confirmed on Chain.  There will be no fork issue at the Solidity event. try it. 
This is the related configuration item:  https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf#L486

Regarding the log, it can be seen at the FullNode log, please check the log file of your fullnode.

**Comment by pthor11** [comment]
Thank you @Benson0224

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Feel free to reopen this issue if you still see it, thanks.
