### ISSUE TITLE
About tron backup downloads

### ISSUE THREAD

**Issue by hrach-hambaryan** [tronprotocol/java-tron#3966]
Hi all, I want to create an ansible script to automate tron fullnode deployments

I stacked on the backup download step,  I see that there was a link like this https://backups.trongrid.io/FullNode-latest-output-directory.tgz  but it doesn't work now, do we have another kind of that link?

**Comment by Benson0224** [comment]
you can find all the snapshots from this link: https://developers.tron.network/docs/mainnet-backups

You can also refer to this doc for how to run a node. https://developers.tron.network/docs/fullnode

Please refer to the Tron deployment tool from: https://github.com/tronprotocol/tron-deployment

**Comment by hrach-hambaryan** [comment]
@Benson0224 Thanks for response, I am writing an ansible script, and want to download the latest backup anytime I run the script, that is the main problem, I don't want to open that link and get the link of latest backup version

**Comment by Benson0224** [comment]
> @Benson0224 Thanks for response, I am writing an ansible script, and want to download the latest backup anytime I run the script, that is the main problem, I don't want to open that link and get the link of latest backup version

The download link will not change, you can select any of them based on your need. 
![image](https://user-images.githubusercontent.com/61768920/128165443-b5be7e02-c8fb-4256-b7e6-7555af7de176.png)

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed as no update for days.
Feel free to re-open it if you still see it. thanks.
