### ISSUE TITLE
trx-trasfer

### ISSUE THREAD

**Issue by lijianl** [tronprotocol/java-tron#3970]
I get some 1 SUN transfer recently from my wallet;

does these transactions have any meanings

**Comment by Starsakary** [comment]
Usually, within the transaction, there is a memo contains ADs.
These transactions are spam.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed as no update for days.
Feel free to re-open it if you still see it. thanks.
