### ISSUE TITLE
ArchiveManifest is cool !!!!!!!!!

### ISSUE THREAD

**Issue by ghanavati27** [tronprotocol/java-tron#3972]
Hello,
I upgraded my node to GreatVoyage-v4.3.0(Bacon) and ArchiveManifest.jar
Startup time reduced from 15 minutes to less than 30 seconds !
Awsome guys.
Thank for this great work.

**Comment by Benson0224** [comment]
Thanks For your sharing. goog to hear that.

**Comment by pthor11** [comment]
Yeah, it fasten the node boost up a lot. Shall core developers implement it into the node source code (instead run as plugin) in the next versions?

**Comment by Benson0224** [comment]
> Yeah, it fasten the node boost up a lot. Shall core developers implement it into the node source code (instead run as plugin) in the next versions?

Thanks for your suggestion, you can integrate this plugin into the startup script as this guide mentioned. 
https://github.com/tronprotocol/documentation-en/blob/master/docs/developers/archive-manifest.md

**Comment by pthor11** [comment]
Sure, thank you.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
