### ISSUE TITLE
UTF-8 error in block

### ISSUE THREAD

**Issue by centromere** [tronprotocol/java-tron#3973]
### 1. What did you do?
```
➜  ~ curl -s http://localhost:8091/walletsolidity/getblockbynum -d '{"num": 32600828}' | iconv -f UTF-8 -t UTF-8
...
":"41f8993a1f34d42e8c56b5231819565b8c5970f688","weight":1},{"address":"417bd64fb62c07d3391f94260e0f76905b87ee5cf9","weight":1},{"address":"41536d94e429695182c13db49a30f8c12ad0990e1b","weight":1}],"threshold":3,"type":"Active","permission_name":"Oguz Demir
iconv: (stdin):1:139575: cannot convert
```

This is with version 4.3.0.

**Comment by Kantitad** [comment]
รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________
From: Alex Wied ***@***.***>
Sent: Tuesday, August 10, 2021 2:38:56 AM
To: tronprotocol/java-tron ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tronprotocol/java-tron] UTF-8 error in block (#3973)


1. What did you do?

➜  ~ curl -s http://localhost:8091/walletsolidity/getblockbynum -d '{"num": 32600828}' | iconv -f UTF-8 -t UTF-8

...

":"41f8993a1f34d42e8c56b5231819565b8c5970f688","weight":1},{"address":"417bd64fb62c07d3391f94260e0f76905b87ee5cf9","weight":1},{"address":"41536d94e429695182c13db49a30f8c12ad0990e1b","weight":1}],"threshold":3,"type":"Active","permission_name":"Oguz Demir

iconv: (stdin):1:139575: cannot convert



This is with version 4.3.0.

**Comment by Alexliu007** [comment]
> ### 1. What did you do?
> ```
> ➜  ~ curl -s http://localhost:8091/walletsolidity/getblockbynum -d '{"num": 32600828}' | iconv -f UTF-8 -t UTF-8
> ...
> ":"41f8993a1f34d42e8c56b5231819565b8c5970f688","weight":1},{"address":"417bd64fb62c07d3391f94260e0f76905b87ee5cf9","weight":1},{"address":"41536d94e429695182c13db49a30f8c12ad0990e1b","weight":1}],"threshold":3,"type":"Active","permission_name":"Oguz Demir
> iconv: (stdin):1:139575: cannot convert
> ```
> 
> This is with version 4.3.0.

Hil, we will give feedback to the relevant team, and because the block has special characters. You can use the -c option to skip them: curl -s http://localhost:8091/walletsolidity/getblockbynum -d '{"num": 32600828}'| iconv -c -f UTF-8 -t UTF-8

**Comment by halibobo1205** [comment]
Scenes cannot be reproduced. @centromere
