### ISSUE TITLE
Proposal voting in tron

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3974]
Hi,
I am the Super Representative Partner in tron and i raised a proposal.
Can SR only vote for the proposal?

**Comment by Benson0224** [comment]
Please refer to the proposal guide here: https://developers.tron.network/docs/committee-and-proposal 

SR, super partner and SR candidate can initiate and vote for proposals. A proposal will be adopted if it is voted for by at least 18 SRs. The adopted proposal will apply its changes to network parameters in the next maintenance period.

**Comment by Mita1w** [comment]
You want tron

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed as no update for a long time. 
Feel free to re-open this issue if you still see it. thanks.
