### ISSUE TITLE
Tron full node is syncing very slowly 

### ISSUE THREAD

**Issue by chandramouli-scs** [tronprotocol/java-tron#3976]
1. What did you do?
Syncing full node using Java-tron-GreatVoyage-v4.2.2.1 version , Java -version is  "1.8.0_291" , Cpu cores -16 cores , Ram - 32gb.
Almost 41 days ago i started syncing full node block number present is at - 17277644.

2. What did you expect to see?
Fullnode is fully synced.

3. What did you see instead?
But it still syncing , initial 10 million blocks are synced with in 3 days after that not syncing fast , Please help , Thank you .

**Comment by Benson0224** [comment]
Did you syncing from 0 or based on any snapshot? syncing from 0 may take months.  you can download official snapshot from this link: https://developers.tron.network/docs/mainnet-backups 

Please also refer to this doc regarding syncing issue.  
https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

By the way, the latest version of java-tron is GreatVoyage-v4.3.0, please upgrade your version ASAP. here is the link.  https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.3.0

**Comment by kraymond37** [comment]
The same issue. At some time, tron exits. After I restart tron, it can not catch up mainnet forever. Currently it's 11 days behind.
Tron version: v4.3.0
Machine
```
CPU: AMD EPYC 7R32 @ 32x 3.215GHz
RAM: 21678MiB / 63729MiB
```
Command
```
java -Xmx24g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseConcMarkSweepGC -jar FullNode.jar -c main_net_config.conf
```

**Comment by Benson0224** [comment]
Please share tron.log for further investigation, thanks.

**Comment by Kantitad** [comment]
https://github.com/tronprotocol/java-tron/blob/4.3.0-to-nile/CONTRIBUTING.md

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by chandramouli-scs** [comment]
Solved with downloaded database snapshot from this link - http://47.89.178.46/ and started the node . it works , don't sync from zero block.
