### ISSUE TITLE
seeing unit test fail

### ISSUE THREAD

**Issue by mark-staked** [tronprotocol/java-tron#3979]
### 1. What did you do?

in some envs when I build 4.3.0 

### 2. What did you expect to see?
something like 
org.tron.core.config.args.ArgsTest > config PASSED

### 3. What did you see instead?

org.tron.core.config.args.ArgsTest > get FAILED
    org.junit.ComparisonFailure: expected:<[]database> but was:<[metrics-]database>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.tron.core.config.args.ArgsTest.get(ArgsTest.java:52)

should I just be using -x test or is there deeper lesson?

**Comment by Benson0224** [comment]
Thanks for your info. can you please provide the full build log of the failure? we can further investigate based on the log. 

Please use  -x  to skip the testing part, thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Feel free to re-open this issue if you still see it. thanks.
