### ISSUE TITLE
Impossible to get fees or blockheight for old transaction

### ISSUE THREAD

**Issue by ClementPavue** [tronprotocol/java-tron#3989]
### 1. What did you do?
Trying to get basic informations s.a. blockheight or fees used regarding old transactions ie b4a674f632990e467d46a533dfc9f8fcf617b91ec3bb9245ad3583a79a86a92f.

When POST /wallet/gettransactioninfobyid for b4a674f632990e467d46a533dfc9f8fcf617b91ec3bb9245ad3583a79a86a92f
### 2. What did you expect to see?
The 0.00212 burn TRX and 2438408 as a blockheight

### 3. What did you see instead?
{}

**Comment by Alexliu007** [comment]
> ### 1. What did you do?
> Trying to get basic informations s.a. blockheight or fees used regarding old transactions ie b4a674f632990e467d46a533dfc9f8fcf617b91ec3bb9245ad3583a79a86a92f.
> 
> When POST /wallet/gettransactioninfobyid for b4a674f632990e467d46a533dfc9f8fcf617b91ec3bb9245ad3583a79a86a92f
> 
> ### 2. What did you expect to see?
> The 0.00212 burn TRX and 2438408 as a blockheight
> 
> ### 3. What did you see instead?
> {}

This transaction above occurred on 2018-09-18, but the interface /wallet/gettransactioninfobyid is a new feature in Java tron version 3.2, which was released on 2018-11-30, so transactions before that date cannot be queried using gettransactioninfobyid query.
![image](https://user-images.githubusercontent.com/33770261/129654707-e312e412-2fc3-498c-a18f-30338ca2bf54.png)
![image](https://user-images.githubusercontent.com/33770261/129654773-b4204180-dd8c-4360-969a-2c44b7221f0c.png)

**Comment by ClementPavue** [comment]
Hi Alex thank you for your answer. How did tronscan then was able to deduce that the from_address in this transaction burnt some TRX ? I know that bandwidth is computed by the number of bytes of the transaction. But how did they do with the free daily bandwidth ?

Thanks in advance

**Comment by Alexliu007** [comment]
> Hi Alex thank you for your answer. How did tronscan then was able to deduce that the from_address in this transaction burnt some TRX ? I know that bandwidth is computed by the number of bytes of the transaction. But how did they do with the free daily bandwidth ?
> 
> Thanks in advance

The tronscan team uses its own fullndoe nodes, they have special processing for the nodes, for these transactions you can use the interface provided by tronscan to query.  https://apilist.tronscan.org/api/transaction-info?hash=b4a674f632990e467d46a533dfc9f8fcf617b91ec3bb9245ad3583a79a86a92f

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Feel free to re-open this issue if you still see it. thanks.
