### ISSUE TITLE
wallet-web TRX balance not auto refresh after send

### ISSUE THREAD

**Issue by miimiispets** [tronprotocol/java-tron#399]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Send trx from wallet

2. What did you expect to see?
Refreshed/updated wallet amount after pressing "make another transaction"

3. What did you see instead?
Previous wallet balance. Only after freshing browserpage, the wallet balance is updated/refreshed.

**Comment by Rovak** [comment]
Fixed in https://github.com/tronprotocol/wallet-web/commit/5cde4f4407718b3f5736fa933cef8e88bb677f99

**Comment by tronmarcus** [comment]
Hi, miimiispets
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network  so we can deliver the TRX on time. 
Thanks,
Marcus Yang
