### ISSUE TITLE
I can't decode constant_result for triggerconstantcontract 

### ISSUE THREAD

**Issue by chandramouli-scs** [tronprotocol/java-tron#3996]
I can't decode constant_result for triggerconstantcontract.

1. What did you do?
I am calling constant function of a smart contract ( network - nile test net , contract_address is - TTLVwFFk9CXtDZi9Ad6de1WTpgup5yKTCZ , i am calling balanceOf() function ).

call result is success but constant_result hex is not decoding correctly.

here is the response - 

{"result"=>{"result"=>true}, "energy_used"=>594, "constant_result"=>["000000000000000000000000000000000000000000000020cc0fc77b6c5840d4"], "transaction"=>{"ret"=>[{}], "visible"=>false, "txID"=>"11f01a5dd1abc65a7909d76d67ff7dbff9f07ced2d991a44792c1ed59f89ed53", "raw_data"=>{"contract"=>[{"parameter"=>{"value"=>{"data"=>"70a08231000000000000000000000000ea224c2a0ed4cb9553c35da4449596a6eee8c170", "owner_address"=>"41ea224c2a0ed4cb9553c35da4449596a6eee8c170", "contract_address"=>"41be8102710a1a07db07669f110bf66c33ca943cc1"}, "type_url"=>"type.googleapis.com/protocol.TriggerSmartContract"}, "type"=>"TriggerSmartContract"}], "ref_block_bytes"=>"7be8", "ref_block_hash"=>"02a16d9b44e05a5d", "expiration"=>1629265521000, "timestamp"=>1629265462174}, "raw_data_hex"=>"0a027be8220802a16d9b44e05a5d40e8d2abbeb52f5a8e01081f1289010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412540a1541ea224c2a0ed4cb9553c35da4449596a6eee8c170121541be8102710a1a07db07669f110bf66c33ca943cc1222470a08231000000000000000000000000ea224c2a0ed4cb9553c35da4449596a6eee8c170709e87a8beb52f"}} 

Please help me to decode the hex of constant_result , other function calls are working fine .

below response is for symbol() function ( i can decode constant_result in this response )- 

{"result"=>{"result"=>true}, "energy_used"=>1034, "constant_result"=>["000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000074a41594132305400000000000000000000000000000000000000000000000000"], "transaction"=>{"ret"=>[{}], "visible"=>false, "txID"=>"6f54d3b28fea395cd21133b6320722607b05c1321623064ba593a1acf3492258", "raw_data"=>{"contract"=>[{"parameter"=>{"value"=>{"data"=>"95d89b41", "owner_address"=>"41ea224c2a0ed4cb9553c35da4449596a6eee8c170", "contract_address"=>"41be8102710a1a07db07669f110bf66c33ca943cc1"}, "type_url"=>"type.googleapis.com/protocol.TriggerSmartContract"}, "type"=>"TriggerSmartContract"}], "ref_block_bytes"=>"7bcd", "ref_block_hash"=>"a246be0873f0497a", "expiration"=>1629265440000, "timestamp"=>1629265382944}, "raw_data_hex"=>"0a027bcd2208a246be0873f0497a4080daa6beb52f5a6d081f12690a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412340a1541ea224c2a0ed4cb9553c35da4449596a6eee8c170121541be8102710a1a07db07669f110bf66c33ca943cc1220495d89b4170a09ca3beb52f"}} 

Thank you .

**Comment by Benson0224** [comment]
The types of return values are different for different functions. 
For `symbol ()`, it returns str.  for `balanceOf`, it returns unit.

The return value of your first contract call should be `unit`. The result is a hexadecimal number: 20cc0fc77b6c5840d4

Transfer it to int it is 605000001000006238420, it is the same as contract call on tronscan. 
![image](https://user-images.githubusercontent.com/61768920/129847194-7601857e-563e-453b-830a-8ec7973132bb.png)

![image](https://user-images.githubusercontent.com/61768920/129846630-e59899de-00d2-4db7-9424-d2cc74f351e4.png)

Please refer to this guide on TRC20 contract interactions, thanks: https://developers.tron.network/docs/trc20-contract-interaction

**Comment by chandramouli-scs** [comment]
Thank you @Benson0224
