### ISSUE TITLE
The usdt sent to the anonymous address is always displayed in synchronization

### ISSUE THREAD

**Issue by Admini123** [tronprotocol/java-tron#3997]
The usdt sent to the anonymous address is always displayed in synchronization

**Comment by Benson0224** [comment]
Please provide more detail on your issue, like screenshots, transaction hash, thanks.

**Comment by Admini123** [comment]
> Please provide more detail on your issue, like screenshots, transaction hash, thanks.

![111122](https://user-images.githubusercontent.com/12041836/129860560-f93438a5-6d12-4fd7-b308-d81fca817db1.png)
 is always displayed in synchronization
The USDT sent to the anonymous asset is not displayed, it has been synchronized for a day

**Comment by Benson0224** [comment]
Thanks for your info, Team is checking now, it would be great if you can provide your address here.  thanks. 
You can also contact group admin in our telegram groups if you do not want to public your address on GitHub. here is the link of our telegram group: https://t.me/TronOfficialDevelopersGroupEn

**Comment by Benson0224** [comment]
Please Try below steps on tronlink:
1. Go to My --> Shielded Account Management --> Backup Mnemonic ; 
2. Make sure you have successfully backup your Mnemonic before the further operation, Suggest writing the Mnemonic down. 
3. Back to `Shielded Account Management` page, Click `Delete Wallet` to remove this account.
4. After Delete Done, Back to `Shielded Account Management` page, click the Add button on the Upper right corner, use the backup Mnemonic to restore your account. 
5. It should be OK after above steps finished. 

![image](https://user-images.githubusercontent.com/61768920/130026478-35f77015-efd1-4e52-89f9-3a96a4dc5fc1.png)

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron. 
This issue will be closed as it is already fixed.

**Comment by WAT251922ty** [comment]
ในวันที่ พฤ. 19 ส.ค. 2021 12:57 น. Benson ***@***.***>
เขียนว่า:
