### ISSUE TITLE
Failed dependancy injection

### ISSUE THREAD

**Issue by herpdederp** [tronprotocol/java-tron#40]
https://github.com/tronprotocol/java-tron/blob/develop/src/main/java/org/tron/core/TronBlockChainImpl.java#L37-L38

There's no componentScan for the framework to "find" the beans under the specific package. 
Wiring in beans that aren't marked as components to begin with (see the BlockStore dependency in the above link). In addition most classes hold mutable state and no accommodation to checkpoint this information in a persistent store seems to have been made.

**Comment by Rovak** [comment]
The referenced code is outdated. If the problem still persists in other places then feel free to reopen this issue.
