### ISSUE TITLE
Error transfer trc20 from address

### ISSUE THREAD

**Issue by oggy95** [tronprotocol/java-tron#4006]
### 1. What did you do?

Generating address via API "wallet/createaddress", get new address. Testing transfer TRX via API "wallet/easytransfer", all good. But while trying to use this private key of this address to import it in wallet or compose TRC20 transfer, it compose another address.

### 2. What did you expect to see?
Forming correct address frrom given private key.

### 3. What did you see instead?
Incorrect address from given private key.

**Comment by vivian-kang** [comment]
hi @oggy95, 
"wallet/createaddress" is used to create a address through a user password,  the password is not the private key, but it can convert to private key through SHA256 algorithm, so if you want to import the address into an wallet, you should use the private key not the password.  
https://developers.tron.network/reference#walletcreateaddress

**Comment by oggy95** [comment]
As I understand correctly, a value, which I used in "wallet/createaddress", I should convert from Hex to string, than use sha256 for receiving private key?

**Comment by vivian-kang** [comment]
Yes, In "wallet/createaddress" API, the parameter should be the hex format. 
and then convert hex to string to use sha256(*) to get the private key.

**Comment by oggy95** [comment]
Ok, is there are correct version of converting from hex to string for tron?

**Comment by vivian-kang** [comment]
Do you mean the conversion tool or api?
For tool, you can use the TRON-IDE or other online tools. http://www.tronide.io/ 
For api, java : Hex.toHexString(*), tronweb js: toHex() https://developers.tron.network/reference#tohex

**Comment by Ufakeimdope** [comment]
So how do I get the transfer to go through could I give u my info and to
help me

ufakeimdope

**Comment by vivian-kang** [comment]
About trx transfer, please refer to this doc   https://developers.tron.network/docs/trx-transfer

**Comment by oggy95** [comment]
Thank you very much, it helps, issue closed.
