### ISSUE TITLE
syncing stuck

### ISSUE THREAD

**Issue by 0x799** [tronprotocol/java-tron#4012]
### 1. What did you do?
1.Download FullNode.jar ( GreatVoyage-4.3.0 ) from https://github.com/tronprotocol/java-tron/releases. 
2.Download database snapshots in https://backups.trongrid.io/.
3.The config file from https://raw.githubusercontent.com/tronprotocol/tron-deployment/master/main_net_config.conf
4.  java -Xmx24g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c main_net_config.conf

I checked the disk space is sufficient.
System time has been updated used ntpdate.

### 2. What did you expect to see?
The node to continue syncing.

### 3. What did you see instead?
The block height stops at 33103995.

Log:

12:17:56.587 INFO  [TronJClientWorker-59] [net](Channel.java:201) Peer /106.55.11.96:18888 status change to HANDSHAKE_FINISHED.
12:17:56.588 INFO  [TronJClientWorker-59] [net](Channel.java:111) Finish handshake with /106.55.11.96:18888.
12:17:56.588 INFO  [TronJClientWorker-59] [net](ChannelManager.java:161) Add active peer /106.55.11.96:18888 | 61a89bc2114c1b98bf356b68c598e48047c5d0cb3520c00dc74f83405e5287c33be992fef832be433a00e5d7bc25209bfcbe00c9d17e86962b2e69cc65f829c6, total active peers: 9
12:17:56.589 INFO  [TronJClientWorker-59] [net](Channel.java:201) Peer /106.55.11.96:18888 status change to SYNCING.
12:17:56.589 INFO  [TronJClientWorker-59] [net](Channel.java:201) Peer /106.55.11.96:18888 status change to SYNCING.
12:17:56.589 INFO  [TronJClientWorker-59] [DB](Manager.java:1612) headNumber:33104014
12:17:56.589 INFO  [TronJClientWorker-59] [DB](Manager.java:1614) syncBeginNumber:33103995
12:17:56.589 INFO  [TronJClientWorker-59] [DB](Manager.java:1618) solidBlockNumber:33103996
12:17:56.589 INFO  [TronJClientWorker-59] [net](SyncService.java:179) Get block chain summary, low: 33103995, highNoFork: 33104014, high: 33104014, realHigh: 33104014
12:17:56.590 INFO  [TronJClientWorker-59] [net](MessageQueue.java:106) Send to /106.55.11.96:18888, type: SYNC_BLOCK_CHAIN
size: 5, start block: Num:33103995,ID:0000000001f9207b7f1a8c3b0ac7d03281a2ce34f6b2005bf7deabdd6e06a19e, end block Num:33104014,ID:0000000001f9208eaa8df3412e35c85c1ffd906dbb7edf791c66f8352ab89ed9
12:17:56.734 INFO  [TronJClientWorker-59] [net](MessageQueue.java:121) Receive from /106.55.11.96:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:33104014,ID:0000000001f9208eaa8df3412e35c85c1ffd906dbb7edf791c66f8352ab89ed9, end blockId: Num:33106014,ID:0000000001f9285e5b05e7f6a00477a9f473433d5821bfe6a0f84b8035f7baec
12:17:56.739 INFO  [TronJClientWorker-59] [DB](Manager.java:1612) headNumber:33104014
12:17:56.739 INFO  [TronJClientWorker-59] [DB](Manager.java:1614) syncBeginNumber:33103995
12:17:56.739 INFO  [TronJClientWorker-59] [DB](Manager.java:1618) solidBlockNumber:33103996
12:17:56.739 INFO  [TronJClientWorker-59] [net](SyncService.java:179) Get block chain summary, low: 33103995, highNoFork: 33104014, high: 33104014, realHigh: 33106014
12:17:56.739 INFO  [TronJClientWorker-59] [net](MessageQueue.java:106) Send to /106.55.11.96:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:33103995,ID:0000000001f9207b7f1a8c3b0ac7d03281a2ce34f6b2005bf7deabdd6e06a19e, end block Num:33106014,ID:0000000001f9285e5b05e7f6a00477a9f473433d5821bfe6a0f84b8035f7baec
12:17:56.804 INFO  [TronJClientWorker-59] [net](MessageQueue.java:121) Receive from /106.55.11.96:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:33106014,ID:0000000001f9285e5b05e7f6a00477a9f473433d5821bfe6a0f84b8035f7baec, end blockId: Num:33108014,ID:0000000001f9302ec3fe648ed200c64770c37fa7891c6545362f77fccb7937f6
12:17:59.522 INFO  [pool-38-thread-1] [net](SyncPool.java:123)

============ Peer stats: all 9, active 9, passive 0

Peer 47.89.178.46:18888 [247f798c]
ping msg: count 0, max-average-min-last: 0 0 0 0
connect time: 6s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:2000
syncToFetchSizePeekNum:33104015
syncBlockRequestedSize:0
remainNum:20536
syncChainRequested:3
blockInProcess:0
NodeStat[reput: 232(0), discover: 1/1 0/0 0/0 0/0 234ms, p2p: 1/1/1 , tron: 2/3   , tcp flow: 82046

Peer 47.89.242.50:18888 [934ff679]
ping msg: count 3, max-average-min-last: 156 153 152 156
connect time: 17s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:33104015
syncBlockRequestedSize:0
remainNum:18533
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 236(0), discover: 1/1 0/0 6/6 45/45 144ms, p2p: 2/2/2 , tron: 12/12 X 1<=TIME_OUT , tcp flow: 328196

Peer 8.211.61.165:18888 [581ddf00]
ping msg: count 3, max-average-min-last: 198 157 136 198
connect time: 24s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:33104015
syncBlockRequestedSize:0
remainNum:18530
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 236(0), discover: 1/1 0/0 0/0 0/0 149ms, p2p: 2/2/2 , tron: 12/12 X 1<=TIME_OUT , tcp flow: 328196

Peer 12.203.154.36:18888 [ddb57765]
ping msg: count 2, max-average-min-last: 163 160 158 163
connect time: 6s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:33104015
syncBlockRequestedSize:0
remainNum:17026
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 235(0), discover: 1/1 0/0 0/0 0/0 180ms, p2p: 2/2/2 , tron: 10/10 X 1<=TIME_OUT , tcp flow: 328192

Peer 47.252.17.26:18888 [7754159f]
ping msg: count 1, max-average-min-last: 236 236 236 236
connect time: 24s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:33104015
syncBlockRequestedSize:0
remainNum:18531
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 205(112), discover: 1/1 0/0 45/61 0/0 224ms, p2p: 2/2/2 , tron: 13/9 X 1<=TIME_OUT , tcp flow: 569197

Peer 89.111.33.137:18888 [865c2e84]
ping msg: count 2, max-average-min-last: 296 295 294 294
connect time: 6s
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:29988333
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 215(0), discover: 1/1 0/0 1/1 4/4 191ms, p2p: 2/2/2 , tron: 11/10 X 1 =>TIME_OUT, tcp flow: 1327

Peer 173.249.54.119:18888 [d5ca278b]
ping msg: count 1, max-average-min-last: 335 335 335 335
connect time: 17s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:33104015
syncBlockRequestedSize:0
remainNum:18533
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 241(0), discover: 1/1 0/0 0/0 0/0 184ms, p2p: 1/1/1 , tron: 5/5   , tcp flow: 164096

Peer 162.218.55.150:18888 [a4bcfa18]
ping msg: count 1, max-average-min-last: 3043 3043 3043 3043
connect time: 17s
last know block num: 4602216
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:28501499
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 226(0), discover: 16/16 0/0 13/13 0/0 188ms, p2p: 1/1/1 , tron: 8/305   , tcp flow: 10871

Peer 106.55.11.96:18888 [61a89bc2]
ping msg: count 3, max-average-min-last: 19655 6582 45 45
connect time: 2s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:33104015
syncBlockRequestedSize:0
remainNum:18537
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 210(0), discover: 1/1 0/0 0/0 0/0 41ms, p2p: 5/5/6 , tron: 2720/53 X 5<=TIME_OUT=>TOO_MANY_PEERS, tcp flow: 94785999

**Comment by Benson0224** [comment]
Please provide the full log file, the log you pasted here does not include the Error message.

**Comment by 0x799** [comment]
This problem has been fixed.
Increase the value of the maxTimeRatio configuration item in the node configuration file to 20.0 or higher.

refer from https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization
