### ISSUE TITLE
Libsodium issue

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#4024]
Hi,
I had a issue while building java tron.
> Task :chainbase:compileJava FAILED
java-tron/chainbase/src/main/java/org/tron/common/zksnark/JLibrustzcash.java:32: error: cannot find symbol
  private static Librustzcash INSTANCE;
                 ^
  symbol:   class Librustzcash
  location: class JLibrustzcash
java-tron/chainbase/src/main/java/org/tron/common/zksnark/JLibsodium.java:15: error: cannot find symbol
  private static Libsodium INSTANCE;
                 ^
  symbol:   class Libsodium
  location: class JLibsodium
2 errors

FAILURE: Build failed with an exception.

Can anyone solve this issue?

**Comment by Benson0224** [comment]
could you please share your OS Version and Java Version:
Currently, only Oracle JDK 8 is supported. 

![image](https://user-images.githubusercontent.com/61768920/131429693-f895bf2f-f45d-4343-b811-bd78ffe93063.png)

https://github.com/tronprotocol/java-tron/blob/develop/build.md#prepare-dependencies

**Comment by osiz-blockchainapp** [comment]
> could you please share your OS Version and Java Version:
> Currently, only Oracle JDK 8 is supported.
> 
> ![image](https://user-images.githubusercontent.com/61768920/131429693-f895bf2f-f45d-4343-b811-bd78ffe93063.png)
> 
> https://github.com/tronprotocol/java-tron/blob/develop/build.md#prepare-dependencies

Hi,
The below is my JDK version.
![image](https://user-images.githubusercontent.com/48212011/131434991-b4b33689-9bcd-4810-af1f-0838260bfa6e.png)

**Comment by Benson0224** [comment]
> > could you please share your OS Version and Java Version:
> > Currently, only Oracle JDK 8 is supported.
> > ![image](https://user-images.githubusercontent.com/61768920/131429693-f895bf2f-f45d-4343-b811-bd78ffe93063.png)
> > https://github.com/tronprotocol/java-tron/blob/develop/build.md#prepare-dependencies
> 
> Hi,
> The below is my JDK version.
> ![image](https://user-images.githubusercontent.com/48212011/131434991-b4b33689-9bcd-4810-af1f-0838260bfa6e.png)

open JDK is not supported, please change it to Oracle JDK. thanks.

**Comment by osiz-blockchainapp** [comment]
> > > could you please share your OS Version and Java Version:
> > > Currently, only Oracle JDK 8 is supported.
> > > ![image](https://user-images.githubusercontent.com/61768920/131429693-f895bf2f-f45d-4343-b811-bd78ffe93063.png)
> > > https://github.com/tronprotocol/java-tron/blob/develop/build.md#prepare-dependencies
> > 
> > 
> > Hi,
> > The below is my JDK version.
> > ![image](https://user-images.githubusercontent.com/48212011/131434991-b4b33689-9bcd-4810-af1f-0838260bfa6e.png)
> 
> open JDK is not supported, please change it to Oracle JDK. thanks.

How to check oracle JDK version?

**Comment by Benson0224** [comment]
> How to check oracle JDK version?

1. check the oracle JDK installation guide from : https://docs.oracle.com/javase/8/docs/technotes/guides/install/install_overview.html
2. you can also check the JDK version via `java -version` in the terminal. 
![image](https://user-images.githubusercontent.com/61768920/131439580-837dea60-5b67-49a4-9f52-a3456edcbbfb.png)

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed since no update for a long time. 
Feel free to re-open this issue if you still see it, thanks.
