### ISSUE TITLE
Token withdraw

### ISSUE THREAD

**Issue by fublok77** [tronprotocol/java-tron#4028]

**Comment by Benson0224** [comment]
Please provide detail of your issue, otherwise, we will close this issue as no valid info here.

**Comment by fublok77** [comment]
I don't know what you mean the issue,,what wrong ,, please give for the example,,tq

**Comment by Benson0224** [comment]
> I don't know what you mean the issue,,what wrong ,, please give for the example,,tq

check this guide: https://developers.tron.network/docs/trc20-contract-interaction

**Comment by Benson0224** [comment]
This issue will be closed as no update for a long time.
Feel free to re-open it if you still see the issue, thanks.

**Comment by WAT251922ty** [comment]
TUZQvRZAPmSpwoYsP1mt8fPRQyBqq7kyfX
Recil. Wallet. Address.  Key. Wath. Is. Tish
WAT251922
***@***.***

ในวันที่ พ. 15 ก.ย. 2021 10:27 Benson ***@***.***> เขียนว่า:
