### ISSUE TITLE
Sync extremely slow and output-directory not being updated

### ISSUE THREAD

**Issue by bluedusk** [tronprotocol/java-tron#4029]
### 1. What did you do?

- I downloaded data snapshot (for example 20210830) from https://backups.trongrid.io/ and unpacked to Fullnode.jar folder.
- I'm using this config file https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf 
- I'm running fullnode with command:
```
java -jar FullNode.jar -c ./main_net_config.conf
```

- tron.log here

https://gist.github.com/bluedusk/23b1d496ffd791310e335ce2eb7deb48#file-tron-log

### 2. What did you expect to see?

Node start to sync and output-directory is updated.

### 3. What did you see instead?

Sync is extremely slow, even slower than block generation speed.
output-directory is not getting updated while the node is syncing.
Connecting with wallet-cli, I can see the block is slowly syncing. (by checking with getblock command)
If I run the node for sometime and restart, it will start syncing from the 20210830 snapshot again. No data is persisted.

**Comment by Benson0224** [comment]
No Error was found in your log, I would suggest you check this guide and update the `maxTimeRatio = 20.0` . thanks. 
https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

**Comment by Benson0224** [comment]
This issue will be closed as no update for a long time.
Feel free to re-open it if you still see the issue, thanks.
