### ISSUE TITLE
How we can write our own tron block explorer ?

### ISSUE THREAD

**Issue by Serqati** [tronprotocol/java-tron#4034]

**Comment by Serqati** [comment]
What we need ?

**Comment by Benson0224** [comment]
Tronscan is not an open-source project,  I would suggest you try to search Alternative on github.

**Comment by HoneyCivik** [comment]
TRONSCAN Token Donation Aceess
Please Sir
TRX Address TPzi5iTX7ue8B7tn2VK7cXy94s1xwbNhsY

**Comment by Ufakeimdope** [comment]
And name it ufakeimdope and put as a owner of an new wallet able to
exchange with any of the defi world and trc and erc merge and bit coin ass
well nfts also and make the kyc factor a thing of the past week would be
great and worth hella money
