### ISSUE TITLE
Validator setup in tron

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#4040]
Hi Everyone,
Can we run two validator in different server. 
How to setup?

**Comment by Benson0224** [comment]
Check this guide for Node Setup : https://developers.tron.network/docs/fullnode

**Comment by osiz-blockchainapp** [comment]
> Check this guide for Node Setup : https://developers.tron.network/docs/fullnode

I run supernode in one server and fullnode in another server. Fullnode only syncs supernode blocks.
If i add another witness in fullnode, will it act as witness or not?

**Comment by hitlxy** [comment]
Yes, you can setup several witnesses. please make sure they have the same p2p.version.

**Comment by vivian-kang** [comment]
The answer is yes, and please refer to the above guide to setup other SR nodes

**Comment by Benson0224** [comment]
This issue will be closed as no update for a long time.
Feel free to re-open it if you still see the issue, thanks.
