### ISSUE TITLE
verification failed. Please confirm the correct parameters and try again 

### ISSUE THREAD

**Issue by LyyDandelion** [tronprotocol/java-tron#4042]
### 1. What did you do?

 https://cn.developers.tron.network/docs/%E5%8F%91%E8%A1%8Ctrc20%E4%BB%A3%E5%B8%81%E6%95%99%E7%A8%8B
使用官方提供的步骤执行代币发行，验证的时候无法验证

### 2. What did you expect to see?

验证成功

### 3. What did you see instead?

![image](https://user-images.githubusercontent.com/33171640/132296761-87c4d368-84fb-439e-aea0-97949a9482aa.png)

TMVh3NgpZgV5gvQDXEBD5f4edpG66djP4b  verification failed. Please confirm the correct parameters and try again
提示验证失败

**Comment by Benson0224** [comment]
All parameters used in verification must be exactly the same as those used in contract compile.  otherwise it will fail. 

Please check the parameters and try again. thanks.

**Comment by LyyDandelion** [comment]
官方提供的发行trc20代币的demo版本是0.5.0，但是验证页面只有0.5.10,其余参数均正确，是这个原因导致的吗

**Comment by Benson0224** [comment]
> 官方提供的发行trc20代币的demo版本是0.5.0，但是验证页面只有0.5.10,其余参数均正确，是这个原因导致的吗
pragma solidity ^0.5.0;  means all versions in this scope "0.5.0  <= version <= 0.6.0"  are OK for the contract compile. 

From the verification page, I can see many versions which start with 0.5., please confirm the version used in contract deployment and choose the same version in verification, thanks. 

![image](https://user-images.githubusercontent.com/61768920/132317738-0c83eefe-cd0d-45aa-8dab-02a66dd7bfc3.png)

**Comment by LyyDandelion** [comment]
![image](https://user-images.githubusercontent.com/33171640/132318780-82889d8e-af74-4a86-b80c-5889ec1a0621.png)
![image](https://user-images.githubusercontent.com/33171640/132318827-83670a14-95d6-4fd7-881d-c181cdd0062f.png)
0.5.0没有

**Comment by Benson0224** [comment]
> 0.5.0没有

Let me repeart again:  `pragma solidity ^0.5.0; ` means all versions in this scope "0.5.0 <= version <= 0.6.0" are OK for the contract compile. 

On the compile page,  there is also no 0.5.0, and all versions which are greater than 0.5.0 and less than 0.6.0 can be used to compile this contract. 
![image](https://user-images.githubusercontent.com/61768920/132319292-c1b5bd76-1fcf-4173-a6aa-eaa9f8374c05.png)

**Comment by LyyDandelion** [comment]
![image](https://user-images.githubusercontent.com/33171640/132319996-bc83a10b-7a2c-4243-b559-4e0d1b637d91.png)
![image](https://user-images.githubusercontent.com/33171640/132320021-609ab628-56ab-45bc-9723-409b0abdc120.png)
但是还是提示参数有误

**Comment by Benson0224** [comment]
> 但是还是提示参数有误

验证的时候 所有要填写的参数 必须和编译时候 的一致。 一共就6个参数，仔细核实一下。 

合约名称 可以在合约的主页里看到。 
![image](https://user-images.githubusercontent.com/61768920/132320783-ad1e202d-6005-4f53-acfe-93f9b05e2f2a.png)

这个是我刚刚用demo部署 并验证的合约。 请仔细核对参数。谢谢。
https://shasta.tronscan.org/#/contract/TYUhE5MEy9KrUSNFRP1Mkm5T3s3cXoiizq/code

**Comment by LyyDandelion** [comment]
![image](https://user-images.githubusercontent.com/33171640/132321793-d9915839-8280-45bf-84ff-fab02ae32cc1.png)
![image](https://user-images.githubusercontent.com/33171640/132321994-adc75e53-c108-4084-b104-64ab9b9433c0.png)
![image](https://user-images.githubusercontent.com/33171640/132322049-997a75e0-9d87-462d-9879-7413e77b3061.png)
跟你的一样

**Comment by Benson0224** [comment]
> ![image](https://user-images.githubusercontent.com/33171640/132321793-d9915839-8280-45bf-84ff-fab02ae32cc1.png)
> ![image](https://user-images.githubusercontent.com/33171640/132321994-adc75e53-c108-4084-b104-64ab9b9433c0.png)
> ![image](https://user-images.githubusercontent.com/33171640/132322049-997a75e0-9d87-462d-9879-7413e77b3061.png)
> 跟你的一样

is your issue fixed? 
if no please join https://t.me/TronOfficialDevelopersGroupEn and DM the admin for better communication.

**Comment by LyyDandelion** [comment]
你可以拿你的官方trc20部署步骤，走一遍吗，或者有一样的部署示例，你上次给的明显错误，sol版本都不对。你给的文档都是错的。

**Comment by Benson0224** [comment]
> 你可以拿你的官方trc20部署步骤，走一遍吗，或者有一样的部署示例，你上次给的明显错误，sol版本都不对。你给的文档都是错的。

Please provide more info on which Doc is not correct, thanks.

This is the contract I deployed on the shasta testnet using the contract demo code from this guide: 
https://cn.developers.tron.network/docs/%E5%8F%91%E8%A1%8Ctrc20%E4%BB%A3%E5%B8%81%E6%95%99%E7%A8%8B

Check detail at: https://shasta.tronscan.org/#/contract/TD9jkTV8pZnSHHy4uBBnuZh4B4mrDM4hjr/code 
and the contract can be successfully deployed and verified. no issue.

**Comment by Benson0224** [comment]
This issue will be closed as no update for a long time.
Feel free to re-open it if you still see the issue, thanks.

**Comment by mstcoins** [comment]
Compile has two '0.5.10', your select is not correct one. choose another one, then you'll get it.

**Comment by d1ggy1bh** [comment]
may i ask this where can i found??

![image](https://user-images.githubusercontent.com/97116048/149332097-6f785e09-e6d3-40f8-9c0f-c371f0f66fcd.png)
