### ISSUE TITLE
When I  use java to run the FullNode.jar, there is no output in my console.

### ISSUE THREAD

**Issue by donnol** [tronprotocol/java-tron#4052]
### 1. What did you do?

clone the `java-tron`  project, and checkout to `Nile` branch

build: `./gradlew build -x test`.

copy [the config](https://nileex.io/join/getJoinPage) to my local  config.conf.

run: `$ java -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -jar ./build/libs/FullNode.jar -c config.conf`.

### 2. What did you expect to see?

some logs about the node.

### 3. What did you see instead?

nothing, like below:

```sh
$ java -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -jar ./build/libs/FullNode.jar -c config.conf

^C*** shutting down gRPC server since JVM is shutting down
*** server is shutdown
*** shutting down gRPC server on solidity since JVM is shutting down
*** shutting down gRPC server on PBFT since JVM is shutting down
*** server on PBFT shut down
*** server on solidity shut down
******** begin to pop revokingDb ********
******** before revokingDb size:20
******** end to pop revokingDb ********
```

**Comment by Benson0224** [comment]
The `logs` folder will be generated at the same directory of `FullNode.jar` if you did not specify the `--log-config` parameter. 
And `tron.log` file will be generated in `logs` folder. like below.  

![image](https://user-images.githubusercontent.com/61768920/133409455-80d12bdd-ea73-4b4c-ba64-bb9617f8e1c8.png)

**Comment by donnol** [comment]
Oh, I miss it. Thanks.

But, how about add a note in the doc?  I think it's very helpful.

**Comment by Benson0224** [comment]
> Oh, I miss it. Thanks.
> 
> But, how about add a note in the doc? I think it's very helpful.

thanks for your suggestion. it is already covered in the `Fullnode` deployment guide. https://developers.tron.network/docs/fullnode

**Comment by donnol** [comment]
What a pity, I follow the [run.md](https://github.com/tronprotocol/java-tron/blob/develop/run.md) which the project's [README.md](https://github.com/tronprotocol/java-tron) Deploy part tell.

**Comment by Tyu67th8** [comment]
Thank. You
Khunanon. Wongouan

**Comment by Tyu67th8** [comment]
TLpJmUc2Kt6zrABEtbqT115nggrqW6tFtg
User. Khunanon 2519
wiwatwongth@gmail.com

**Comment by WAT251922ty** [comment]
TEvepBrMMwCwaooz3GvuNyyTyiR7jy8P2D
Wallet. Addresses.
{"address":"41365ceda3bab7d3c26486a940daca0e9707f3efd6","crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"05dbe7924b8a75cb99ac2348c8c7fc3d"},"ciphertext":"08b8ce84e620005b24ca2ed5c42e86fcafa1bac0e5b3617bc5a37496df82a3bc","kdf":"scrypt","kdfparams":{"dklen":32,"n":16384,"p":1,"r":8,"salt":"666b4ea0337eb48556afa03ceb136a98160293559e9e491575b2b54b3f2b865b"},"mac":"32cf0a8d27f5c6921a715cefb6214e0c1565623750dcbec2d6ed2f0d08662431"},"id":"c5e9ebcf-0eca-4825-b037-d
3b608987293","version":3}
Key
Khunanon2519
***@***.***

ในวันที่ พ. 15 ก.ย. 2021 16:25 donnol ***@***.***> เขียนว่า:

**Comment by Tyu67th8** [comment]
Thank. You. 
Account. Twitter. 0910618574
  ABCD123123s$
Tyu67th8
wiwatwongth@gmail.com

**Comment by WAT251922ty** [comment]
You. Help. Mee. Pliesses
Send. TRX.  To.  Wallet. Addresses.
Now.  Thank. You

Khunanon. ***@***.***

ในวันที่ พ. 15 ก.ย. 2021 22:07 Tyu67th8 ***@***.***> เขียนว่า:

**Comment by Benson0224** [comment]
This issue will be closed as no update for a long time. 
Feel free to re-open it if you still see the issue, thanks.

**Comment by WAT251922ty** [comment]
Stop. 14.  Day


  Geting. To. How. Moush. Withdraeal


Khunanon. Wongouan

ในวันที่ ศ. 24 ก.ย. 2021 17:04 Benson ***@***.***> เขียนว่า:
