### ISSUE TITLE
websocket contract event doesn't work in event plugin

### ISSUE THREAD

**Issue by l3lackrooz** [tronprotocol/java-tron#4054]
I want to watch the event usdt trc20
I ran a full node server with the event plugin service, but i can only see "blockTrigger", "transactionTrigger" and "solidityTrigger" 
i can't see contract event and contract log trigger 

**my config.conf**:

`{
event.subscribe = {
    native = {
      useNativeQueue = true // if true, use native message queue, else use event plugin.
      bindport = 5555 // bind port
      sendqueuelength = 1000 //max length of send queue
    }

    path = "/home/dbgames/fullnode/event-plugin/build/plugins/plugin-kafka-1.0.0.zip" // absolute path of plugin
    server = "127.0.0.1:50051" // target server address to receive event triggers
    #dbconfig="" // dbname|username|password
    contractParse = true,
    topics = [
        {
          triggerName = "block" // block trigger, the value can't be modified
          enable = true
          topic = "block" // plugin topic, the value could be modified
        },
        {
          triggerName = "transaction"
          enable = true
          topic = "transaction"
        },
        {
          triggerName = "contractevent"
          enable = true
          topic = "contractevent"
        },
        {
          triggerName = "contractlog"
          enable = true
          topic = "contractlog"
        },
        {
          triggerName = "solidity" // solidity block event trigger, the value can't be modified
          enable = true            // the default value is true
          topic = "solidity"
        },
        {
          triggerName = "solidityevent"
          enable = false
          topic = "solidityevent"
        },
        {
          triggerName = "soliditylog"
          enable = false
          topic = "soliditylog"
        }
    ]

    filter = {
       fromblock = "" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
       toblock = "" // the value could be "", "latest" or a specified block number as end of the queried range
       contractAddress = [
           "TVkNuE1BYxECWq85d8UR9zsv6WppBns9iH" // contract address you want to subscribe, if it's set to "", you will receive contract logs/events with any contract address.
       ]

       contractTopic = [
           "" // contract topic you want to subscribe, if it's set to "", you will receive contract logs/events with any contract topic.
       ]
    }
}
`
my socket.js file  : 
`
var zmq = require('zeromq')
, sock = zmq.socket('sub');

sock.connect('tcp://127.0.0.1:5555');
sock.subscribe('blockTrigger');
sock.subscribe('transactionTrigger');
sock.subscribe('contractLogTrigger');
sock.subscribe('contractEventTrigger');

sock.on('message', function(topic, message) {
console.log(new Buffer(topic).toString('utf8'), new Buffer(message).toString('utf8'));
});
`

**Comment by WAT251922ty** [comment]
ในวันที่ พฤ. 16 ก.ย. 2021 02:11 l3lackrooz ***@***.***>
เขียนว่า:

**Comment by Alexliu007** [comment]
If you use the event plugin, you need to set useNativeQueue to false in the configuration file, for details of deploying the event plugin you can refer to the documentation at https://developers.tron.network/docs/event-subscribe

**Comment by hoseinmh64** [comment]
Good

**Comment by Benson0224** [comment]
This issue will be closed as no update for a long time.
Feel free to re-open it or submit a new issue if you still see it. thanks.

**Comment by WAT251922ty** [comment]
No ting. To. Play. 14. Day
Fuk.  Geting. To. Account. Withdrawal. Fuk. You.  Noting. A. Bout. To.
Send.  Fuk.  Stop.  14. Day

ในวันที่ พฤ. 16 ก.ย. 2021 02:11 l3lackrooz ***@***.***>
เขียนว่า:

**Comment by BeycanDeveloper** [comment]
We realized that this was a big gap in the Tron Blockchain network without WebSockets, so we built [TronSocket.com](https://tronsocket.com). Now it's easy to listen to Tron Blockchain events via WebSocket.
