### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by elaheh4** [tronprotocol/java-tron#4080]
hello 
when i wanna install java tron AFTER 
`./gradlew build`
in 78% i have this error 
`java.lang.OutOfMemoryError: GC overhead limit exceeded`
my server has 128gig ram and 2TB hard

**Comment by elaheh4** [comment]
![image](https://user-images.githubusercontent.com/75408886/134614352-1f648a32-1d81-4247-8b83-159bf3e8799d.png)
![image](https://user-images.githubusercontent.com/75408886/134614388-5c14bae4-7b86-4c02-8c05-ee2364472cad.png)
![image](https://user-images.githubusercontent.com/75408886/134614427-26e46edb-bf01-4944-a2df-89fa1ea7c5eb.png)

**Comment by elaheh4** [comment]
![image](https://user-images.githubusercontent.com/75408886/134614509-0a84adcc-f9c3-4369-baff-a973f5d1aadd.png)

**Comment by Benson0224** [comment]
1. make sure you are using Oracle jdk 8. other versions are not supported. 
2.  Try `./gradlew build -x test` to skip the test part.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue or submit a new issue if you still see it, thanks.
