### ISSUE TITLE
/gettransactioninfobyid doesn't return internal_transactions

### ISSUE THREAD

**Issue by twilightrus** [tronprotocol/java-tron#4083]
HTTP API Endpoint /gettransactioninfobyid does not return internal_transactions.

Request:
`{
    "value": "e5bb8a5464e2dc04a6b4e104503bdce7d527d034a3ec9f387ff24d5ddc306fb5"
}`

Response:
`{
    "id": "e5bb8a5464e2dc04a6b4e104503bdce7d527d034a3ec9f387ff24d5ddc306fb5",
    "fee": 5192740,
    "blockNumber": 33886423,
    "blockTimeStamp": 1632173124000,
    "contractResult": [
        "0000000000000000000000000000000000000000000000000000000000000001"
    ],
    "contract_address": "41867288dc1903136bbd57b8a61d7c4c16a97b0a9a",
    "receipt": {
        "energy_fee": 4814740,
        "energy_usage_total": 34391,
        "net_fee": 378000,
        "result": "SUCCESS"
    },
    "log": [
        {
            "address": "867288dc1903136bbd57b8a61d7c4c16a97b0a9a",
            "topics": [
                "7fa05134de03ce8318f72680a2b90bda5ab9e9d1de396962402f48f0f116a6bc"
            ],
            "data": "000000000000000000000000989d548b0aa32548f68db7f65c6008f5a94c3bed000000000000000000000000000000000000000000000000000000000db585800000000000000000000000000000000000000000000000000000000000000003"
        }
    ]
}
`

But on tronscan https://tronscan.org/#/transaction/e5bb8a5464e2dc04a6b4e104503bdce7d527d034a3ec9f387ff24d5ddc306fb5 i see the internal transfer 230 TRX.

**Comment by Benson0224** [comment]
https://api.trongrid.io/wallet/gettransactioninfobyid?value=e5bb8a5464e2dc04a6b4e104503bdce7d527d034a3ec9f387ff24d5ddc306fb5 

From trongrid, i can see it can return the internal transitions. 
which Node are you connecting to?  
make sure `saveInternalTx` is set to True of the Node you are connecting to. 
![image](https://user-images.githubusercontent.com/61768920/134649598-a9b92082-294e-4fd5-b025-24d96ec6aa1b.png)

 https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf#L442

**Comment by twilightrus** [comment]
@Benson0224 i use node from https://developers.tron.network/docs/official-public-node
yes, trongrid returns internal_transactions. does he have RPS limitations?

**Comment by Benson0224** [comment]
> @Benson0224 i use node from https://developers.tron.network/docs/official-public-node
> yes, trongrid returns internal_transactions. does he have RPS limitations?

yes, TronGrid do have Ratio Limits
By default, one account with API key visiting can have up to 100,000 requests per day. now, users can claim up to 500,000 requests per day for free from https://www.trongrid.io/price more info please refer to: https://developers.tron.network/reference#rate-limits

You can also set up your own FullNode if trongrid can not meet your requirement.  here is the FullNode deployment guide: https://developers.tron.network/docs/fullnode

**Comment by WAT251922ty** [comment]
Stop.  14Day.  Geting.  How. Moush
To. Withd awwl

Khunanon. Wongouan

ในวันที่ ศ. 24 ก.ย. 2021 16:07 Ruslan ***@***.***> เขียนว่า:

**Comment by WAT251922ty** [comment]
Thank. You
Khunanon. Wongouan

You. Wont. To. Thailand.  Pliesses

ในวันที่ ส. 25 ก.ย. 2021 00:55 Ruslan ***@***.***> เขียนว่า:
