### ISSUE TITLE
How much time Tron Node Take to Full  sync?

### ISSUE THREAD

**Issue by vikaskumar123** [tronprotocol/java-tron#4084]
### 1. What did you do?

i have 'TB9BLvWipwGMoUav6npVg1KFBRAFryppCn' tron address.. Someone send it some tron. Hash is showing [here](7caebe2adfeca4a18a50b659100ce34bb2b9bed5606ebf8bf2249a84a2de06dc)

i made a curl call here 
curl -X POST  http://127.0.0.1:8090/wallet/gettransactioninfobyid -d '{"value": "7caebe2adfeca4a18a50b659100ce34bb2b9bed5606ebf8bf2249a84a2de06dc"}'

### 2. What did you expect to see?

But it return {} blank Json. Is it due to node is not fully sync ??

### 3. What did you see instead?

Other endpoints such as /wallet/getaccount are working just fine .Any help would be greatly appreciated.

**Comment by WAT251922ty** [comment]
Im. Withdrawal. How. Moush

ในวันที่ ศ. 24 ก.ย. 2021 23:14 vikaskumar123 ***@***.***>
เขียนว่า:

**Comment by Benson0224** [comment]
https://developers.tron.network/reference#wallet-getnowblock

you can query the latest block of your node via this API. and compare it to the latest block from tronscan, then you can see where you are. 

You can also use the mainnet snapshot from here which can be used for node sync
https://developers.tron.network/docs/mainnet-backups

**Comment by Kantitad** [comment]
Kantitad​ Pramchit​

________________________________
จาก: Benson ***@***.***>
ส่งแล้ว: วันเสาร์ที่ 25 กันยายน ค.ศ. 2021 09:14 น.
ถึง: tronprotocol/java-tron
สำเนาถึง: Subscribed
ชื่อเรื่อง: Re: [tronprotocol/java-tron] How much time Tron Node Take to Full sync? (#4084)


https://developers.tron.network/reference#wallet-getnowblock

you can query the latest block of your node via this API. and compare it to the latest block from tronscan, then you can see where you are.

You can also use the mainnet snapshot from here which can be used for node sync
https://developers.tron.network/docs/mainnet-backups

**Comment by vikaskumar123** [comment]
> from
Thanks for your nice reply...
I just check 
https://developers.tron.network/reference#wallet-getnowblock
i got the blockID
000000000206fb0451c24478f8b3c5c80ce56467c74f2fa8db0f8237565ef467

when i did on my Server with Curl
curl -X GET  http://127.0.0.1:8090/wallet/getnowblock
i got this BlockID
00000000003b3bc2ff2a6d1fc99ee2fd15ac4296ab0cbe5df59c15050fe43248
So i think it is not sync yet..

For the downloading i have this one
https://backups.trongrid.io/
But here the fullnode size is 793 GB
But when i check here 
http://47.89.178.46/backup20210925/
it is like  590GB 
What is the difference between them ..

Also for the sync what i think 
1. Download the latest backup
2. unzip them
3. rename/delete the exiting output-directory of FullNode folder 
4. move the unzipped folder into FullNode folder 

that's it or we have to recompile and run again
if yes please guide me steps .. It will be great help for me..

**Comment by WAT251922ty** [comment]
Team.  Fuk.


Fuk. GitHup.  Noting. A. Withdra al token. Im. Fuk. You.


Fuk. GitHup

Fuk. Team. GitHup


Khunanon. Wongouan

ในวันที่ ส. 25 ก.ย. 2021 09:14 Benson ***@***.***> เขียนว่า:

**Comment by WAT251922ty** [comment]
Fuk. You. Fuk. GitHup. Geting. Token. Im. Fuk. You

ในวันที่ ส. 25 ก.ย. 2021 09:14 Benson ***@***.***> เขียนว่า:

**Comment by Benson0224** [comment]
793 GB snapshot including the internal transaction while 590GB snapshot does not include the snapshot. 

Please refer to the user guide of snapshot from here: 
https://developers.tron.network/docs/mainnet-backups#ii-how-to-use-the-data-snapshot

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue or submit a new issue if you still see it, thanks.
