### ISSUE TITLE
Contract-to-contract TRC10 transfer by payable method

### ISSUE THREAD

**Issue by DrgMitev** [tronprotocol/java-tron#4085]
### 1. What did you do?

1. Created 2 contracts:

``` 
contract B {
    function method() external payable {
        //TRC10 logic
    }
}

contract A {
    function method () external payable {
        // first variant - B.{tokenValue: <x>, tokenId: <y> }method();
        /* second variant */ B.tokenValue(<x>).tokenId(<y>).method();
    }
}
```
2. Called {A-method()}

### 2. What did you expect to see?
Successful transaction of tokens by utilizing one of the *possible* transaction logics

### 3. What did you see instead?
```B.{tokenValue: <x>, tokenId: <y> }method();``` results in ```,TypeError: Unknown call option "tokenValue". Valid options are "salt", "value" and "gas".``` and ```TypeError: Unknown call option "tokenId". Valid options are "salt", "value" and "gas".```

```B.tokenValue(<x>).tokenId(<y>).method();``` results in ```,TypeError: Member "tokenValue" not found or not visible after argument-dependent lookup in contract A.```

Is there a valid way to transfer TRC10 tokens from a contract to a contract by calling a payable method, rather than calling { payable(address).transferToken(sum, type);}

**Comment by Benson0224** [comment]
https://developers.tron.network/docs/trc10-transfer-in-smart-contracts-2

Please refer to this guide on how to transfer TRC10 in smart contract, thanks.

**Comment by DrgMitev** [comment]
Hello @Benson0224! 
As I wrote - I do agree that sending TRC10 can be done trough ```address.transferToken(amount, id)```, but I am rather searching for a way to call a ```payable``` method from a contract and send the same amount of tokens with the call.

**Comment by Benson0224** [comment]
> Hello @Benson0224!
> As I wrote - I do agree that sending TRC10 can be done trough `address.transferToken(amount, id)`, but I am rather searching for a way to call a `payable` method from a contract and send the same amount of tokens with the call.

Check this WBTT contract, it receives the TRC10 token with a payable function. 
https://tronscan.org/#/contract/TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt/code

**Comment by WAT251922ty** [comment]
Noting. A.  Withdrawal

ในวันที่ อ. 28 ก.ย. 2021 09:49 Benson ***@***.***> เขียนว่า:

**Comment by yanghang8612** [comment]
@DrgMitev Hey, thanks for your issue. ^ _ ^
Sending TRC10 token to contract while calling the specific method to another contact in tx is not supported by tron-solidity compiler now. We will take a discussion and decide including this feature or not.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks

**Comment by prasad-kumkar** [comment]
Any update on the feature?
