### ISSUE TITLE
Contract-to-contract ```receive() payable``` fallback loses state variables

### ISSUE THREAD

**Issue by DrgMitev** [tronprotocol/java-tron#4086]
### 1. What did you do? 
1. Created 2 contracts:

``` 
contract B {
    bool stateVar1;
    uint256 stateVar2;
   
    constructor() { 
        stateVar1;
        stateVar2;
    } 
    receive() payable {
        return method();
    }
    function method() external payable {
        require(stateVar1 == false && stateVar2 == 900000, "random message");
        return;
    }
}

contract A {
    address payable addressB;
    function method () external payable { 
        addressB.transferToken(<sum>, <id>);
    }
}
```

2. Called {A-method}

### 2. What did you expect to see?
Successful transaction with no return values/message.

### 3. What did you see instead?
Revert opcode with an empty "contract_result". After some investigation I came up to the conclusion that both state variables are missing any values, as those don't return any value if I try to return them before the "require" check, which leads to the transaction revert. 

The issue does not occur if I call B.method directly! 

Any ideas?

**Comment by Benson0224** [comment]
https://developers.tron.network/docs/trc10-transfer-in-smart-contracts-2

Please refer to this guide on how to transfer TRC10 in smart contract, thanks.

**Comment by DrgMitev** [comment]
> https://developers.tron.network/docs/trc10-transfer-in-smart-contracts-2
> 
> Please refer to this guide on how to transfer TRC10 in smart contract, thanks.

Hi, @Benson0224 
I haven't seen anything in the APi documentation, related to the issue

**Comment by Benson0224** [comment]
can you share more detail? 
for example the failed transaction hash? which testnet? and how did you call the function? what are the parameters?  thanks.

**Comment by WAT251922ty** [comment]
Noting. A. Withdrawal

You. Dont. Im. A. Withdrawwl

ในวันที่ อ. 28 ก.ย. 2021 16:25 Benson ***@***.***> เขียนว่า:

**Comment by yanghang8612** [comment]
@DrgMitev Hey, the state variable `addressB` in contract B seems not be initialized which means that the value will be `all zero address` when you access it. So `revert` exception is throwed.

**Comment by WAT251922ty** [comment]
Fuk. You
Noting. A. Withdrawal

Khunanon. Wongouan

ในวันที่ พ. 29 ก.ย. 2021 10:58 Asuka ***@***.***> เขียนว่า:

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Feel free to re-open it if you still see the issue, thanks.
