### ISSUE TITLE
cant get activation email

### ISSUE THREAD

**Issue by dpacino55** [tronprotocol/java-tron#4087]
In Tronscan. after I click on Register and fillup Email address and password, and clicking submit gives me a success message and asks me to activate via email. But I am not receiving any email.

**Comment by Benson0224** [comment]
please share your email, thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue or submit a new issue if you still see it, thanks.

**Comment by asim0blackhat** [comment]
How can I confirm my email in TronScan? I will not be sent an email to activate my account.
[Keyvansadeghi68@gmail.com](mailto:Keyvansadeghi68@gmail.com)

**Comment by asim0blackhat** [comment]
> please share your email, thanks.

How can I confirm my email in TronScan? I will not be sent an email to activate my account.
[Keyvansadeghi68@gmail.com](mailto:Keyvansadeghi68@gmail.com)

**Comment by sunflower-sun** [comment]
> > please share your email, thanks.
> 
> How can I confirm my email in TronScan? I will not be sent an email to activate my account. [Keyvansadeghi68@gmail.com](mailto:Keyvansadeghi68@gmail.com)

Maybe the email server is unavailable that time, just retry now
