### ISSUE TITLE
local tron full node can

### ISSUE THREAD

**Issue by foole11** [tronprotocol/java-tron#4094]
### 1. What did you do?

nohup sh start.sh &

### 2. What did you expect to see?
13:21:04.878 INFO  [TronJClientWorker-8] [net](Channel.java:201) Peer /47.89.243.195:18888 status change to SYNCING.
13:21:04.879 INFO  [TronJClientWorker-8] [net](Channel.java:201) Peer /47.89.243.195:18888 status change to SYNCING.
13:21:04.879 INFO  [TronJClientWorker-8] [DB](Manager.java:1612) headNumber:33776426
13:21:04.879 INFO  [TronJClientWorker-8] [DB](Manager.java:1614) syncBeginNumber:33776426
13:21:04.880 INFO  [TronJClientWorker-8] [DB](Manager.java:1618) solidBlockNumber:33776408
13:21:04.880 INFO  [TronJClientWorker-8] [net](SyncService.java:179) Get block chain summary, low: 33776426, highNoFork: 33776426, high: 33776426, realHigh: 33776426
13:21:04.881 INFO  [TronJClientWorker-8] [net](MessageQueue.java:106) Send to /47.89.243.195:18888, type: SYNC_BLOCK_CHAIN
size: 1, start block: Num:33776426,ID:000000000203632af61de810eb52a9b406b3fd2647e73fa98da313ea5be2ada1 
13:21:05.455 INFO  [TronJClientWorker-8] [net](MessageQueue.java:121) Receive from /47.89.243.195:18888, type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:33776426,ID:000000000203632af61de810eb52a9b406b3fd2647e73fa98da313ea5be2ada1, end blockId: Num:33778426,ID:0000000002036afadb023fb4e78494910110d7e65a7e2b044aacd7e2d3daffe3
13:21:05.458 INFO  [TronJClientWorker-8] [DB](Manager.java:1612) headNumber:33776426
13:21:05.458 INFO  [TronJClientWorker-8] [DB](Manager.java:1614) syncBeginNumber:33776426
13:21:05.459 INFO  [TronJClientWorker-8] [DB](Manager.java:1618) solidBlockNumber:33776408
13:21:05.459 INFO  [TronJClientWorker-8] [net](SyncService.java:179) Get block chain summary, low: 33776426, highNoFork: 33776426, high: 33776426, realHigh: 33778426
13:21:05.459 INFO  [TronJClientWorker-8] [net](MessageQueue.java:106) Send to /47.89.243.195:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:33776426,ID:000000000203632af61de810eb52a9b406b3fd2647e73fa98da313ea5be2ada1, end block Num:33778426,ID:0000000002036afadb023fb4e78494910110d7e65a7e2b044aacd7e2d3daffe3 

### 3. What did you see instead?

本地的全节点无法同步，日志在更新，但是向本地的全节点发送请求，返回的结果是块号没有变化。

**Comment by WAT251922ty** [comment]
Fuk. You

Noting. A. Withdrawl

Fuk. You

Khunanon. Wongouan



ในวันที่ พฤ. 30 ก.ย. 2021 12:28 Nobody ***@***.***> เขียนว่า:
