### ISSUE TITLE
local tron full node block number can't update

### ISSUE THREAD

**Issue by foole11** [tronprotocol/java-tron#4095]
[tron_log.txt](https://github.com/tronprotocol/java-tron/files/7256911/tron_log.txt)

### 1. What did you do?

nohup sh start.sh & 

### 2. What did you expect to see?

波场本地的全节点同步起来。

### 3. What did you see instead?

全节点的日志在继续打印，但是快号没有更新。

**Comment by Benson0224** [comment]
Please share the full tron.log file.

**Comment by foole11** [comment]
this is my full tron.log file
[tron.log.tar.gz](https://github.com/tronprotocol/java-tron/files/7257658/tron.log.tar.gz)

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue or submit a new issue if you still see it, thanks.
