### ISSUE TITLE
GoTron

### ISSUE THREAD

**Issue by ggxed** [tronprotocol/java-tron#4096]
Are you planning to rewrite the throne into more modern languages ​​like Go?

**Comment by WAT251922ty** [comment]
No. Im. Noting. A. Withdrawal

Your. Noting. A. Withdrwwal

Khunanon. Wongouan

***@***.***

ในวันที่ ศ. 1 ต.ค. 2021 16:20 Gregory Mikhailov ***@***.***>
เขียนว่า:

**Comment by Benson0224** [comment]
currently no plan, thanks.

**Comment by WAT251922ty** [comment]
Fuk. You
Noting. A. Withdrawal

Khunanon. Wongouan

ในวันที่ ส. 2 ต.ค. 2021 09:37 Benson ***@***.***> เขียนว่า:
