### ISSUE TITLE
Node stuck at block 34178258 , reinstall + resync many times not work

### ISSUE THREAD

**Issue by umarfarooqitgcuf** [tronprotocol/java-tron#4101]
### 1. What did you do?
i have run my fullnode with :
nohup java -Xmx398g -XX:+HeapDumpOnOutOfMemoryError -jar FullNode.jar  -c /home/ubuntu/FullNode/main_net_config.conf  >> start.log 2>&1 &

### 2. What did you expect to see?
i expect it to sync fully but it stucks 

### 3. What did you see instead?
10:42:34.812 WARN  [TronJClientWorker-76] [net](PeerClient.java:58) connect to 13.229.128.108:18888 fail,cause:connection timed out: /13.229.128.108:18888
10:42:34.812 INFO  [TronJClientWorker-75] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 INFO  [TronJClientWorker-76] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 WARN  [TronJClientWorker-78] [net](PeerClient.java:58) connect to 35.165.103.105:18888 fail,cause:connection timed out: /35.165.103.105:18888
10:42:34.812 INFO  [TronJClientWorker-78] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 WARN  [TronJClientWorker-79] [net](PeerClient.java:58) connect to 18.184.238.21:18888 fail,cause:connection timed out: /18.184.238.21:18888
10:42:34.812 WARN  [TronJClientWorker-80] [net](PeerClient.java:58) connect to 35.176.192.130:18888 fail,cause:connection timed out: /35.176.192.130:18888
10:42:34.812 INFO  [TronJClientWorker-79] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 INFO  [TronJClientWorker-80] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 WARN  [TronJClientWorker-81] [net](PeerClient.java:58) connect to 52.47.197.188:18888 fail,cause:connection timed out: /52.47.197.188:18888
10:42:34.812 WARN  [TronJClientWorker-82] [net](PeerClient.java:58) connect to 13.231.4.243:18888 fail,cause:connection timed out: /13.231.4.243:18888
10:42:34.812 INFO  [TronJClientWorker-81] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 WARN  [TronJClientWorker-83] [net](PeerClient.java:58) connect to 34.200.228.125:18888 fail,cause:connection timed out: /34.200.228.125:18888
10:42:34.812 WARN  [TronJClientWorker-84] [net](PeerClient.java:58) connect to 18.220.232.201:18888 fail,cause:connection timed out: /18.220.232.201:18888
10:42:34.812 INFO  [TronJClientWorker-82] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 INFO  [TronJClientWorker-83] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 INFO  [TronJClientWorker-84] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 WARN  [TronJClientWorker-85] [net](PeerClient.java:58) connect to 34.250.140.143:18888 fail,cause:connection timed out: /34.250.140.143:18888
10:42:34.812 WARN  [TronJClientWorker-86] [net](PeerClient.java:58) connect to 13.125.210.234:18888 fail,cause:connection timed out: /13.125.210.234:18888
10:42:34.812 INFO  [TronJClientWorker-85] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 WARN  [TronJClientWorker-87] [net](PeerClient.java:58) connect to 52.62.210.100:18888 fail,cause:connection timed out: /52.62.210.100:18888
10:42:34.812 INFO  [TronJClientWorker-86] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 INFO  [TronJClientWorker-87] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.812 WARN  [TronJClientWorker-88] [net](PeerClient.java:58) connect to 18.231.76.29:18888 fail,cause:connection timed out: /18.231.76.29:18888
10:42:34.812 INFO  [TronJClientWorker-88] [net](TronChannelInitializer.java:48) Close channel:null | <null>
10:42:34.981 INFO  [nioEventLoopGroup-6-31] [net](MessageQueue.java:121) Receive from /5.200.73.29:37922, type: P2P_DISCONNECT
reason: TIME_OUT
10:42:34.984 INFO  [nioEventLoopGroup-6-31] [net](TronChannelInitializer.java:48) Close channel:/5.200.73.29:37922 | 2ca0aa0ecd1af77ad062eff6a54d872b9b110fa3c9ecbba3e6260ee91aafda33f0201a3c879289f6efc433290cc04d6567e9fe9e9306ab17163ea054cb2be6dd

**Comment by umarfarooqitgcuf** [comment]
> Please update your fullnode to 4.3.0 and try again.
> and share the new log if you still got the issue. thanks.
> https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.3.0

yes that works for me thanx

**Comment by Benson0224** [comment]
This issue will be closed as it is already fixed, thanks.
