### ISSUE TITLE
Running tron node with docker

### ISSUE THREAD

**Issue by dzmitrykliapkou** [tronprotocol/java-tron#4106]
### 1. What did you do?
Hi there! I'm investigating the possibility to use docker to run Tron Full Node and as I can see the latest tag for tronprotocol/java-tron is v4.1.1. Is this way of running nodes still supported?

### 2. What did you expect to see?
The latest tag is expected to be v4.3.0

### 3. What did you see instead?
The latest tag for the docker image is v4.1.1

**Comment by Alexliu007** [comment]
Hi, I will give feedback to the relevant team，also you can create and update your own docker image, the relevant dockerfile is available at https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile.
