### ISSUE TITLE
Running Light FullNode

### ISSUE THREAD

**Issue by dzmitrykliapkou** [tronprotocol/java-tron#4121]
Sorry if the issue is not related to the repo, but
Tron Documentation sometimes reads, that there is Light FullNode that (as I understand) requires less disk space. But the problem is that I can not find any documentation on how to run this variant of node

 It would be nice if somebody could point me at that documentation

**Comment by Starsakary** [comment]
Only full nodes are equipped with full functions on TRON, moreover, a lite full node will finally become a full node as a result of synchronization. 
It is recommended to directly use a full node.

**Comment by dzmitrykliapkou** [comment]
Ah, I see. Thanks for clarification
