### ISSUE TITLE
netty.channel error

### ISSUE THREAD

**Issue by heisentab** [tronprotocol/java-tron#4122]
### 1. What did you do?

[globalEventExecutor-1-629] [net](PeerClient.java:58) connect to 52.193.255.15:18888 fail,cause:Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
### 2. What did you expect to see?
Upgrade to the latest version

**Comment by Benson0224** [comment]
Please share the full tron.log file, thanks

**Comment by kraymond37** [comment]
The same issue with v4.4.0.  v4.3.0 is ok.

**Comment by rhrusha** [comment]
> `unlimit -n -1`

Hi @forfreeday, did you mean `ulimit` ?

**Comment by rhrusha** [comment]
I'm using `ulimit -n 65535` because option `-1` does not work.
