### ISSUE TITLE
Fail-Transaction-Revert 

### ISSUE THREAD

**Issue by Jayesh1420** [tronprotocol/java-tron#4127]
### 1. What did you do?
I Transferred 21500 Usdt from TRC20 network & Did not Get them anywhere 
My Txn Hash:- 60b569362f48e48e84c03fcc8b5a36ddedbeeaff300d4edc65682e5880d1b410
I know I need Energy for this but how to get that and after I get energy how will I get this funds reverted I need a solution for this 
I read all articles related this but Nothing was the output
### 2. What did you expect to see?
I expect the revert on the transaction 

### 3. What did you see instead?
No Funds Both side

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open it if you still see this issue.

**Comment by rex951** [comment]
Benson pls help I made a transfer from an exchange to an external wallet but the funds didn’t deliver and dindt reverse, the error was “failed transaction revert “ and I’ve chatted the exchange support they keep telling me to remain calm and wait but still I’ve not gotten my usdt back, pls how long does this kind of case take

**Comment by Benson0224** [comment]
> Benson pls help I made a transfer from an exchange to an external wallet but the funds didn’t deliver and dindt reverse, the error was “failed transaction revert “ and I’ve chatted the exchange support they keep telling me to remain calm and wait but still I’ve not gotten my usdt back, pls how long does this kind of case take

usually Exchange team will re-send you the tokens if the transaction reverted. please contact them for a fix, thanks
