### ISSUE TITLE
FullNode.jar CLI parameters - FullNode.jar -help

### ISSUE THREAD

**Issue by air3ijai** [tronprotocol/java-tron#4131]
### 1. What did you do?
```
java -jar FullNode.jar -h
java -jar FullNode.jar --help
```

### 2. What did you expect to see?
See CLI parameters for the application

### 3. What did you see instead?
Some information probably can be found in the source code - [CommonParameter.java](https://github.com/tronprotocol/java-tron/blob/develop/common/src/main/java/org/tron/common/parameter/CommonParameter.java).

### 4. Questions
1. How can we run correctly application to the get the help information in the output?
2. Is there any documentation about all CLI parameters?

Thank you!

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open it if you still see this issue.
