### ISSUE TITLE
Json-rpc is supported from java-tron 4.4.0. and this function needs open manually through config file.

### ISSUE THREAD

**Issue by belka9091** [tronprotocol/java-tron#4135]
Json-rpc is supported from java-tron 4.4.0. and this function needs open manually through config file. 
If your node is the latest version, please add below configures in your node's config file:
node.jsonrpc {
    httpFullNodeEnable = true
    httpFullNodePort = 50545
    httpSolidityEnable = true
    httpSolidityPort = 50555
}

_Originally posted by @yingvi in https://github.com/tronprotocol/java-tron/issues/4134#issuecomment-952494907_

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open it if you still see this issue.
