### ISSUE TITLE
How to get more TRX in the deployed node

### ISSUE THREAD

**Issue by Wysten-Hgg** [tronprotocol/java-tron#4136]
### 1. What did you do?

I deployed a node,And can successfully produce new blocks

```
11:43:54.341 INFO  [DPosMiner] [DB](Manager.java:1075) save block: BlockCapsule
[ hash=00000000000464deee6dd3d65671fbf6399a1ab868324f841c6e67c9f83c9167
number=287966
parentId=00000000000464dda198668c619dea65aca4ab685221ba296c1a15b78c34b897
witness address=41a84ca1c4206d0b3e17e46c938be342e91302e3c5
generated by myself=true
generate time=2021-10-29 11:43:54.0
account root=0000000000000000000000000000000000000000000000000000000000000000
txs are empty
]
```

### 2. What did you expect to see?

I want to get TRX from the node i deploy

### 3. What did you see instead?

Now I only have the TRX filled in the genesis.block. I want to get more TRX. What can I do

**Comment by Wysten-Hgg** [comment]
> #3717 Please refer to this issue

Thanks,I have created a SR through ``createwitness``, but how to make him work and get the reward of generating blocks.Now he has no option of is_job
![微信截图_20211101113934](https://user-images.githubusercontent.com/12461366/139618608-85042f1b-c6c4-44c0-ad5e-65163d0ad05f.png)

**Comment by vivian-kang** [comment]
> > #4097 Check this issue, it may help.
> 
> Thanks.It's different from my problem.First, I already have set `changeddelegation = 1`,Second, I called `getreward` and got the correct result.
> 
> My problem now is that the call to `withdrawbalance` returned an error.
> 
> This is my error.
> 
> ```
> {
>     "Error": "class org.tron.core.exception.ContractValidateException : Account[41ea73f4c4cf756869938e0feb2b656ece487074e7] is a guard representative and is not allowed to withdraw Balance"
> }
> ```

Account[41ea73f4c4cf756869938e0feb2b656ece487074e7] This account is in genesis.node of your node's configure file, so this account cannot withdraw balance.
![image](https://user-images.githubusercontent.com/83150421/139619424-58998afa-c196-43a0-ac3a-bed878854e75.png)
![image](https://user-images.githubusercontent.com/83150421/139619464-c2377c79-8ca9-4031-83a9-335a64e6c1ce.png)

**Comment by Wysten-Hgg** [comment]
> 账户[41ea73f4c4cf756869938e0feb2b656ece487074e7] 这个账户在你节点配置文件的genesis.node中，所以这个账户不能提现。

I already know. The above reply says that I want to create a new witness. Now I have created it, but I don't know how to make it work. Please see the above reply

**Comment by Benson0224** [comment]
Please contact us at Telegram channel for Chinese support https://t.me/TronOfficialTechSupport
