### ISSUE TITLE
Showing contract deployment will take 4.2 TRX but burned my entire wallet.

### ISSUE THREAD

**Issue by nitikeshd** [tronprotocol/java-tron#4138]
### 2. What did you expect to see?
I expected it to show me successful contract deployment as per tron documentation.
Step1: 
https://tronscan.io/#/contracts/contract-compiler
step2:
https://github.com/TRON-Developer-Hub/TRC20-Contract-Template/blob/main/Token.sol
step3:
compile and deploy

### 3. What did you see instead?
https://tronscan.io/#/transaction/426e53d6c3ccdf120578fbe49baf954f47ac9375f1f866f4d81525e81120142f
https://tronscan.io/#/transaction/e4b8e9217d747cd0892c3fbd5f8819aa6b84f7dbfdfe8b48bf94250e2b6bf89e
https://tronscan.io/#/transaction/d1ce20f512016044246e1715edb5d0e769007e49392e97c560cf75f2b950a774
![image](https://user-images.githubusercontent.com/32154791/140290347-aa936093-dc7e-4923-af8e-04f0278a0137.png)

**Comment by vivian-kang** [comment]
out of energy - please refer to this doc to solve this issue: https://developers.tron.network/docs/faq#7-how-to-solve-out_of_energy-error

You can try to estimate the energy cost by this guide:  https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-calling-the-contract

**Comment by nitikeshd** [comment]
It needed 185 TRX, so i recharged with 1000TRX before hand. But there should be a check. But i will leave you with that to decide. Thanks
