### ISSUE TITLE
triggerCall contract error

### ISSUE THREAD

**Issue by laopaoer-wallet** [tronprotocol/java-tron#4139]
### 1. What did you do?

Contract address : https://shasta.tronscan.io/#/contract/TTQ4W1uDRm6S7DgLRhR9hpnhcE4CePuYBY

Fuction Name: sendTrx

I triggerCall the contract use trident

### 2. What did you expect to see?

Exception in thread "main" java.lang.RuntimeException: OTHER_ERROR, <ByteString@1863d2fe size=15 contents="Error: Index: 0">
	at org.tron.trident.core.ApiWrapper.broadcastTransaction(ApiWrapper.java:307)
	at com.ruoyi.bot.Tron.main(Tron.java:487)

### 3. What did you see instead?

        List<Address> addressList = new ArrayList<>();
        addressList.add(new Address("TDRfzLYsBWYh9sFYhuvZjMT8JwjFZX2UTJ"));
        addressList.add(new Address("TGexVEQ9ex5688Leb9TA3v2EMRprdxidUt"));

        List<Uint256> amounts = new ArrayList<>();
        amounts.add(new Uint256(BigInteger.valueOf(1000000l)));
        amounts.add(new Uint256(BigInteger.valueOf(1000000l)));

        List<Type> inputParameters = new ArrayList<>();
        inputParameters.add(new DynamicArray<>(Address.class,addressList));
        inputParameters.add(new DynamicArray<>(Uint256.class,amounts));

        Function sendTrx = new Function("sendTrx",inputParameters, Arrays.asList(new TypeReference<Bool>() {}));

        TransactionBuilder b = wrapper.triggerCall(OWNER_ADDRESS, "TTQ4W1uDRm6S7DgLRhR9hpnhcE4CePuYBY", sendTrx);

        b.setFeeLimit(5000000);
        b.setMemo("");

        Chain.Transaction transaction = wrapper.signTransaction(b.build());

        System.out.println(transaction);

        String s = wrapper.broadcastTransaction(transaction);
        System.out.println(s);

The signature cannot be passed, resulting in a broadcast error..Please help

**Comment by Starsakary** [comment]
Params were not passed correctly. You must choose types from `org.tron.trident.abi.datatypes`.
You were trying to pass an array of `Uint256`, here is an example:
```java
List v = new ArrayList<Uint256>();
            v.add(new Uint256(1));
            v.add(new Uint256(30));
            Function add = new Function("add", 
                                Arrays.asList(new DynamicArray(v)),
                                Arrays.asList(new TypeReference<Uint256>() {})); // the returns type
```

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks
