### ISSUE TITLE
Can't get useful data (to_address, amount) from about transaction from gotron-sdk

### ISSUE THREAD

**Issue by l4zygreed** [tronprotocol/java-tron#4141]
### 1. What did you do?
Got full synced Fullnode (saveInternalTx is true)
called GetTransactionInfoById via gotron-sdk / trongrid http api

### 2. What did you expect to see?
Most transaction fields like `address_owner`, `to_address`, `amount`

### 3. What did you see instead?
```json
{
    "id": "b3eee31aaaa39ed448aca390e05927978bc185b70690059b5128893e17e45ceb",
    "fee": 268000,
    "blockNumber": 35347843,
    "blockTimeStamp": 1636561146000,
    "contractResult": [
        ""
    ],
    "receipt": {
        "net_fee": 268000
    }
}
```
most fields (especially `to_address`, `amount` which i need) are always empty for any recent transaction (via sdk grpc client calls)
even via trongrid http api on mainnet/testnet result are the same

There are some usefull fields in GetTransactionById response, but I can't get them via sdk because they in `proto *Any.any` format and I don't know how to unmarshal them correctly (also addresses fields doesn't look like correct, or they somehow encoded...)

**Comment by Alexliu007** [comment]
Please use the interface gettransactionbyid to query the details of the transaction, please refer to the relevant interface [documentation](https://developers.tron.network/reference/walletgettransactionbyid)

**Comment by l4zygreed** [comment]
I can't get correct data from `gettransactionbyid` either. 
useful information only in RawData.Contract.Parameter field, which have `proto *Any.any` type and seems not be easily decoded.

Also via trongrid http api, it doesn't seems like it's returning a correct value

Addresses
```json
{
      "owner_address": "41054ce6121a943140570bade676a5354bdb0a6482",
      "to_address": "419594d9a12b0e2b4cef885335b5e7c6b334a2ac19"
}
```
doesn't look like correct one `TTG8u8fUKqJwMtB59ppaWqgFVGDb5ojWPU` and `TGn24G6p5bRqNfmv8SBKEFZziMvSNpkp8A`

via gotron-sdk `proto.core.TransferContract` type and `XXX_Unmarshal()` function I can only unmarshal received addresses to array of bytes (which is less length, than correct address).

Can you please provide correct instruction about how to get info like sender/receiver address of transaction?

**Comment by l4zygreed** [comment]
I'm using Fullnode version 4.4.1 (don't know which versions have trongrid apis)

**Comment by Alexliu007** [comment]
> I can't get correct data from `gettransactionbyid` either. useful information only in RawData.Contract.Parameter field, which have `proto *Any.any` type and seems not be easily decoded.
> 
> Also via trongrid http api, it doesn't seems like it's returning a correct value
> 
> Addresses
> 
> ```json
> {
>       "owner_address": "41054ce6121a943140570bade676a5354bdb0a6482",
>       "to_address": "419594d9a12b0e2b4cef885335b5e7c6b334a2ac19"
> }
> ```
> 
> doesn't look like correct one `TTG8u8fUKqJwMtB59ppaWqgFVGDb5ojWPU` and `TGn24G6p5bRqNfmv8SBKEFZziMvSNpkp8A`
> 
> via gotron-sdk `proto.core.TransferContract` type and `XXX_Unmarshal()` function I can only unmarshal received addresses to array of bytes (which is less length, than correct address) and I don't know what to do with them, converting via `string()` or anything I tried doesn't return anything useful.
> 
> Can you please provide correct instruction about how to get info like sender/receiver address of transaction?

Please provide the txid, also you can refer to this [document](https://developers.tron.network/docs/parameter-and-return-value-encoding-and-decoding) for instructions on parsing.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks
