### ISSUE TITLE
I TO LOST MY USDT TRC20 TOKENS

### ISSUE THREAD

**Issue by POLU12458** [tronprotocol/java-tron#4143]
### 1. What did you do?
TWedeAY9Wag7cq171UyopaUtXBPz8rtadm

### 2. What did you expect to see?
I want to receive them back

**Comment by Benson0224** [comment]
from the transaction history, I can see that you have transferred your USDT to TYJwJEC46v56Bh4GRyfoPMGUJkjzW6w9pp.

What do you mean lost? 
https://tronscan.org/#/transaction/7d085465b0d53a9288cccf37617e27b338fa475db972bb5e661d24fcab6ac574

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks
