### ISSUE TITLE
TIMEOUT error ignores the fee limit value of a transaction and consumes the maximum energy

### ISSUE THREAD

**Issue by TokenGoodies** [tronprotocol/java-tron#4144]
### 1. What did you do?

Hi! When a transaction throws an OUT_OF_TIME error, it is ignoring the fee_limit value set and is consuming the maximum amount of energy. Please refer to the following transaction. It has a fee limit value set to 80 TRX, which means the maximum amount of energy this transaction is supposed to consume is 80 * 3,571.429 = 285,714 energy, even in the case of an error. But this transaction ended up consuming 10,276,075 energy.

https://tronscan.org/#/transaction/f176764ffe0628afe1bcc8e60fe74674d671c2f771248ef58826e182a8400128

### 2. What did you expect to see?
I expected to see it consume no more energy than the fee limit value set.

### 3. What did you see instead?
It consumed more energy than the fee limit value.

**Comment by Benson0224** [comment]
First of all, fee_limit only limits the energy consumption of the owner_address, it will not impact the contract side. 

In this transaction,  the energy consumption of the user is 80,206  + 195,869 = 276,075, the fee is 276,075 * 280 /1,000,000  = 77.301 TRX, less than  80 TRX. 

![image](https://user-images.githubusercontent.com/61768920/141716360-83534b66-21f3-4f5b-a7f1-0e6ff8965b76.png)

Secondary, regarding the contract energy consumption, it was decided by 2 parameters of the contract,  the `consume_user_resource_percent` and `origin_energy_limit`.

queried from the network we can see the  `consume_user_resource_percent` of your contract is 0,  and `origin_energy_limit` is 10,000,000.  that is why this transaction consumed 10,000,000 Energy from the contract. hope this can answer your question. thanks. 

![image](https://user-images.githubusercontent.com/61768920/141716846-cd3fcc72-e644-4574-a1d0-fd81177d4977.png)
https://api.trongrid.io/wallet/getcontract?value=TTepbLhaPnWWgBrPuWT4SqrM1phsWwDGuD&visible=true

**Comment by TokenGoodies** [comment]
> First of all, fee_limit only limits the energy consumption of the owner_address, it will not impact the contract side.
> 
> In this transaction, the energy consumption of the user is 80,206 + 195,869 = 276,075, the fee is 276,075 * 280 /1,000,000 = 77.301 TRX, less than 80 TRX.
> 
> ![image](https://user-images.githubusercontent.com/61768920/141716360-83534b66-21f3-4f5b-a7f1-0e6ff8965b76.png)
> 
> Secondary, regarding the contract energy consumption, it was decided by 2 parameters of the contract, the `consume_user_resource_percent` and `origin_energy_limit`.
> 
> queried from the network we can see the `consume_user_resource_percent` of your contract is 0, and `origin_energy_limit` is 10,000,000. that is why this transaction consumed 10,000,000 Energy from the contract. hope this can answer your question. thanks.
> 
> ![image](https://user-images.githubusercontent.com/61768920/141716846-cd3fcc72-e644-4574-a1d0-fd81177d4977.png) https://api.trongrid.io/wallet/getcontract?value=TTepbLhaPnWWgBrPuWT4SqrM1phsWwDGuD&visible=true

Thanks @Benson0224. I thought the fee_limit value is honored even when the contract pays for the transaction. I'll use updateEnergyLimit to modify the current value. Thank you for your help.
