### ISSUE TITLE
Reason: Not enough energy for 'save just created contract code' executing: needEnergy[353800], leftEnergy[35279];

### ISSUE THREAD

**Issue by dimamillion** [tronprotocol/java-tron#4151]
I have tried to create a token. The amount of the token is 300000000000, I used 0.5.10 version compiler. But I have failed.  Could you help me with ерпу creation and explain
---
FAILED deploying TRC20. You lost: 8.26672 TRX
Reason: Not enough energy for 'save just created contract code' executing: needEnergy[353800], leftEnergy[35279];. Transaction here
-----

**Comment by Benson0224** [comment]
a standard TRC20 contract deployment will cost about <200 TRX.
make sure you have enough TRX in your wallet before deploying the new contract. otherwise, it will lead to out-of-energy failure.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks
