### ISSUE TITLE
Outdated Docker image

### ISSUE THREAD

**Issue by rubo** [tronprotocol/java-tron#4152]
Can we have the official Docker [image](https://hub.docker.com/r/tronprotocol/java-tron) updated and always have it up to date? It's a year old now.

Given the abandoned status of [Tron Quickstart](https://github.com/TRON-US/docker-tron-quickstart) and the obsolete version of the official Docker image, it's hard to do testing with modern stuff. Currently, there's no way to quickly pull an up-to-date Docker image and start with it. Building and running an image yourself is not straightforward and requires a lot of effort to get things right.

**Comment by Benson0224** [comment]
https://github.com/tronprotocol/java-tron/tree/develop/docker
I would suggest you follow this guide to create the docker image locally. thanks.

**Comment by rubo** [comment]
@Benson0224 That looks like an outdated guide and build fails, unsurprisingly.
Building the Dockerfile in the project's root works but it fails on run. It exits immediately meanwhile the current image from Docker Hub runs just fine with the exact same parameters.

**Comment by Benson0224** [comment]
Try this one 
https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile

**Comment by rubo** [comment]
@Benson0224 In the comment above I talk about that one exactly.

**Comment by Benson0224** [comment]
Any error message on the failure?

**Comment by rubo** [comment]
I managed to run the image built with [Dockerfile](https://github.com/tronprotocol/java-tron/blob/master/Dockerfile). However, it builds an old version as calling `getnodeinfo` reports v4.0.1.

**Comment by Benson0224** [comment]
> I managed to run the image built with [Dockerfile](https://github.com/tronprotocol/java-tron/blob/master/Dockerfile). However, it builds an old version as calling `getnodeinfo` reports v4.0.1.

Thanks for your sharing, we will try to re-produce this issue and will update you later, thanks.

**Comment by Benson0224** [comment]
> I managed to run the image built with [Dockerfile](https://github.com/tronprotocol/java-tron/blob/master/Dockerfile). However, it builds an old version as calling `getnodeinfo` reports v4.0.1.

Just build the dock image with [Dockerfile](https://github.com/tronprotocol/java-tron/blob/master/Dockerfile), the version is correct, please double check again, thanks. 

![image](https://user-images.githubusercontent.com/61768920/144561262-a355750c-ccb7-43e7-877e-488cff91f02a.png)

and the `getnodeinfo` also returns 4.4.1

`{“activeConnectCount”:0,“beginSyncNum”:0,“block”:“Num:0,ID:00000000000000001ebf88508a03865c71d452e25f4d51194196a1d22b6653dc”,“cheatWitnessInfoMap”:{},“configNodeInfo”:{“activeNodeSize”:0,“allowAdaptiveEnergy”:0,“allowCreationOfContracts”:0,“backupListenPort”:10001,“backupMemberSize”:0,“backupPriority”:8,“codeVersion”:“4.4.1",“dbVersion”:2,“discoverEnable”:true,“listenPort”:18888,“maxConnectCount”:30,“maxTimeRatio”:5.0,“minParticipationRate”:15,“minTimeRatio”:0.0,“p2pVersion”:“11111”,“passiveNodeSize”:0,“sameIpMaxConnectCount”:2,“sendNodeSize”:0,“supportConstant”:false,“versionNum”:“16334”},“currentConnectCount”:0,“machineInfo”:{“cpuCount”:4,“cpuRate”:0.21776635021839716,“deadLockThreadCount”:0,“deadLockThreadInfoList”:[],“freeMemory”:730558464,“javaVersion”:“1.8.0_202",“jvmFreeMemory”:471911032,“jvmTotalMemory”:504889344,“memoryDescInfoList”:[{“initSize”:2555904,“maxSize”:268435456,“name”:“Code Cache”,“useRate”:0.04974532127380371,“useSize”:13353408},{“initSize”:0,“maxSize”:-1,“name”:“Metaspace”,“useRate”:0.9747869164904178,“useSize”:46251752},{“initSize”:0,“maxSize”:1073741824,“name”:“Compressed Class Space”,“useRate”:0.005311854183673859,“useSize”:5703560},{“initSize”:8912896,“maxSize”:138739712,“name”:“Par Eden Space”,“useRate”:0.04564120761617265,“useSize”:6332248},{“initSize”:1114112,“maxSize”:17301504,“name”:“Par Survivor Space”,“useRate”:0.06439393939393939,“useSize”:1114112},{“initSize”:22413312,“maxSize”:348848128,“name”:“CMS Old Gen”,“useRate”:0.0733602216721656,“useSize”:25591576}],“osName”:“Linux 4.19.76-linuxkit”,“processCpuRate”:0.005485979492349763,“threadCount”:56,“totalMemory”:2086154240},“passiveConnectCount”:0,“peerList”:[],“solidityBlock”:“Num:0,ID:00000000000000001ebf88508a03865c71d452e25f4d51194196a1d22b6653dc”,“totalFlow”:0}`

**Comment by rubo** [comment]
@Benson0224 Thank you, you're right, got it reporting the right version. Perhaps was an issue with the Docker cache.
Now, when trying to run  `tronbox --migrate`, I'm getting `NOT_ENOUGH_EFFECTIVE_CONNECTION` error. I use [config-localtest.conf](https://github.com/tronprotocol/java-tron/blob/develop/framework/src/main/resources/config-localtest.conf) and it has `minEffectiveConnection = 0`, so it's weird getting this error. Has something changed in this regard in v4.4?

**Comment by Benson0224** [comment]
> 
Are you trying to build a local test network with only one supernode which is producing blocks?

if yes, 2 options to fix this issue:
1. set up one more node(Either Fullnode or supper node is OK), and make sure it is connected to the Super node. here is the guide for deploying a private network:  https://developers.tron.network/docs/tron-private-chain
2.  make sure your codebase includes  this change: https://github.com/tronprotocol/java-tron/commit/0a6bb72d6e5a7d3ca631b30968bf80ed7d710915, or you can use this branch:  v4.4.1_temp

**Comment by rubo** [comment]
Thanks, @Benson0224. Option 2 worked for me.

Side note. The Dockerfile needs to be revised as [this line](https://github.com/tronprotocol/java-tron/blob/030ef17b432a9fe5b12a0e144f37583f9c4823fb/Dockerfile#L24) is redundant given the fact that there's no `docker` branch.

Now, when will the official Docker image be available on Docker Hub? It's great we can build it ourselves but it's much better to have one on Docker Hub ready to use for everyone.

**Comment by Benson0224** [comment]
Thanks for your sharing. 
I see the change is already there https://github.com/tronprotocol/java-tron/pull/4168 it should be included in the next release. 

Regarding the Docker image, will forward it to the RD team. thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks
