### ISSUE TITLE
Unable to show node on map of tronscan

### ISSUE THREAD

**Issue by tqcc** [tronprotocol/java-tron#4155]
### 1. What did you do?

I am running a SR node, and node info like below

`{"activeConnectCount":3,"beginSyncNum":35760313,"block":"Num:35760332,ID:000000000221a8cc8764b147c83ef9b347e83412d763233808f8ef0e2d9fcb37","cheatWitnessInfoMap":{},"configNodeInfo":{"activeNodeSize":0,"allowAdaptiveEnergy":0,"allowCreationOfContracts":0,"backupListenPort":10001,"backupMemberSize":0,"backupPriority":8,"codeVersion":"4.4.1","dbVersion":2,"discoverEnable":true,"listenPort":18888,"maxConnectCount":30,"maxTimeRatio":5.0,"minParticipationRate":15,"minTimeRatio":0.0,"p2pVersion":"11111","passiveNodeSize":0,"sameIpMaxConnectCount":2,"sendNodeSize":0,"supportConstant":false,"versionNum":"16334"},"currentConnectCount":24,"machineInfo":{"cpuCount":16,"cpuRate":0.02960113639858364,"deadLockThreadCount":0,"deadLockThreadInfoList":[],"freeMemory":258875392,"javaVersion":"1.8.0_311","jvmFreeMemory":18173175896,"jvmTotalMemory":22906667008,"memoryDescInfoList":[{"initSize":2555904,"maxSize":251658240,"name":"Code Cache","useRate":0.1808825174967448,"useSize":45520576},{"initSize":0,"maxSize":-1,"name":"Metaspace","useRate":0.9597257193872484,"useSize":59374376},{"initSize":0,"maxSize":1073741824,"name":"Compressed Class Space","useRate":0.006199732422828674,"useSize":6656912},{"initSize":132120576,"maxSize":8115453952,"name":"PS Eden Space","useRate":0.10793169540246564,"useSize":875914704},{"initSize":21495808,"maxSize":234356736,"name":"PS Survivor Space","useRate":0.9137926549719484,"useSize":214153464},{"initSize":351272960,"maxSize":17179869184,"name":"PS Old Gen","useRate":0.21207919903099537,"useSize":3643492896}],"osName":"Linux 3.10.0-1127.el7.x86_64","processCpuRate":0.032159252751121706,"threadCount":219,"totalMemory":33565200384},"passiveConnectCount":21,"peerList":[{"active":true,"avgLatency":7.0,"blockInPorcSize":0,"connectTime":1637804278885,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760325,ID:000000000221a8c5fe716128b8dd19d95c4d363f137ca39d3bac28bc30d32b9b","host":"161.117.230.163","inFlow":804489,"lastBlockUpdateTime":1637809371907,"lastSyncBlock":"Num:35760031,ID:000000000221a79fcfdd91fcc13a8a9aa3e62635a16ae5519f434706c05f8b83","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"28c93ca8daf11ef8566ea8a33f131a8f94fca221403a8f7bce368780f39c287471e58cd9483e1e2482ccf10af015a342ca0f6f476d8f55ae91893543ff62d6d2","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":260,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":7.0,"blockInPorcSize":0,"connectTime":1637809221931,"disconnectTimes":2,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760325,ID:000000000221a8c5fe716128b8dd19d95c4d363f137ca39d3bac28bc30d32b9b","host":"47.74.240.136","inFlow":1073177,"lastBlockUpdateTime":1637809371907,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"c328e2455edaf80e805202a9feec8b7d5e855cd3328f78e4ceed2f65540101d0759f2df2daf653a352f4cba10ab4715353546c4411c3da40a99641e3a1b9b672","port":18888,"remainNum":0,"remoteDisconnectReason":"RESET","score":240,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":8.0,"blockInPorcSize":0,"connectTime":1637807406778,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760326,ID:000000000221a8c6e78fa22063ab3e30143ee3e9054e2f01a0baa1130e5f6b75","host":"18.140.204.79","inFlow":240915,"lastBlockUpdateTime":1637809374895,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"8935dd4a0437f023564ed3e61716fe7bf9ce8702765770ab65a1bfd9027d7a710f1a4112fdc7dbd74edb816a5a3ff233ade8f6124572b3bebe7a2925657e19e2","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":250,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":9.0,"blockInPorcSize":0,"connectTime":1637775883188,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760326,ID:000000000221a8c6e78fa22063ab3e30143ee3e9054e2f01a0baa1130e5f6b75","host":"52.221.76.247","inFlow":402214,"lastBlockUpdateTime":1637809374891,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"25c58b982ac550f60633390812bb5b3d66cd3128eaa009e686d81455355afedb60c4d14ada71f8d1fcb698dc84a15ad9fe8cc6773ee589bd8f91f22365c9d31c","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":40,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":true,"avgLatency":9.0,"blockInPorcSize":0,"connectTime":1637804512897,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35758947,ID:000000000221a3637340eea56e23022930974ca01a55db82bceeb2f2bb5f51da","host":"111.221.44.70","inFlow":261807,"lastBlockUpdateTime":1637805234374,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"78d2d3d5d14b830347c19152de3bb132f9132372beca82f5915a6856f02317b91fa4297f222d0c0d3938ba090cab03ee7940fa701bb01b34ac3fa0f672a5f2b4","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":260,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":10.0,"blockInPorcSize":0,"connectTime":1637808785135,"disconnectTimes":1,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760326,ID:000000000221a8c6e78fa22063ab3e30143ee3e9054e2f01a0baa1130e5f6b75","host":"47.74.242.55","inFlow":824755,"lastBlockUpdateTime":1637809374892,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"ab6362236925b5bf0578ae608eca0f7a0ffb7ea4e24ed80876f70654eb391bad85848aafcf8682b6438033964267bca1584c73013165eafec4e2b564441513c5","port":18888,"remainNum":0,"remoteDisconnectReason":"RESET","score":250,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":11.0,"blockInPorcSize":0,"connectTime":1637807547484,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760325,ID:000000000221a8c5fe716128b8dd19d95c4d363f137ca39d3bac28bc30d32b9b","host":"47.241.20.47","inFlow":858331,"lastBlockUpdateTime":1637809371950,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"1428b797fc7408b50bf659bf22b8312e8fb7faebffa624a07daf806e80eec70cf190823d109c1757512cae00f3c922b50fa4dcfb1fe5ae68edaf1740ad9f258b","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":260,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":11.0,"blockInPorcSize":0,"connectTime":1637807637364,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760325,ID:000000000221a8c5fe716128b8dd19d95c4d363f137ca39d3bac28bc30d32b9b","host":"47.241.0.3","inFlow":463513,"lastBlockUpdateTime":1637809371910,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"ff055cae2569b7dd2033e4dab50d5425e08ba2759d919ecb02964e25e039fdff2f1e42fe8609b68a81ac481cb5d2cff7fd913f2e5cec581ddf1a9e244c8eac35","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":260,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":17.0,"blockInPorcSize":0,"connectTime":1637774017614,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760326,ID:000000000221a8c6e78fa22063ab3e30143ee3e9054e2f01a0baa1130e5f6b75","host":"13.213.225.227","inFlow":662526,"lastBlockUpdateTime":1637809374891,"lastSyncBlock":"Num:35752005,ID:0000000002218845191ebe5fe61b210bbbea75a06d66257395dc3c15c3814e12","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"54bb2fcb5ede6f9facba7cc4e44685bde5352e8d78b4de9f64fe77dac437e4c738de3ec09d84c26085b9fdd5955ef814e877ea8094e04155fdac73147bcb706f","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":307,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":26.0,"blockInPorcSize":0,"connectTime":1637808414836,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760325,ID:000000000221a8c5fe716128b8dd19d95c4d363f137ca39d3bac28bc30d32b9b","host":"161.117.85.97","inFlow":696708,"lastBlockUpdateTime":1637809371906,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"c97423346219f3a9949d29e414e5ecf9eb985d63d8b1dcf9e12071449729613f0f26848fc031880805d4553ce2fe9dd4ac95678f3fdb8bf1ced0c111778c059b","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":260,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":47.0,"blockInPorcSize":0,"connectTime":1637771386607,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760326,ID:000000000221a8c6e78fa22063ab3e30143ee3e9054e2f01a0baa1130e5f6b75","host":"43.226.126.149","inFlow":215474,"lastBlockUpdateTime":1637809374928,"lastSyncBlock":"Num:35753786,ID:0000000002218f3a6319c4994813d13a297895a532627c7fb2e64714f5da3295","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"3991fa59b1de94ee05926d0de61a1160b4cc011eb2d33f8bb0d78b46d4c45f5c20e8f89abd0b9044f339083cae4ca051543ba331292e6f96d9a455c8f13be9ad","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":300,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":47.0,"blockInPorcSize":0,"connectTime":1637808199683,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760325,ID:000000000221a8c5fe716128b8dd19d95c4d363f137ca39d3bac28bc30d32b9b","host":"8.210.206.39","inFlow":919240,"lastBlockUpdateTime":1637809371948,"lastSyncBlock":"Num:35760171,ID:000000000221a82bdc445e8c05e0ff533661b16a07465dd461c817a52a5d40c4","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"613dc6871e45180280287f3bc81d6f19486cf6573dd82bbe2db9b6abb0a9aab8c356c54ec91607029c5414c02f469e21db473d4b6d4008b15ba7dc1f002dfeb2","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":260,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":true,"avgLatency":47.0,"blockInPorcSize":0,"connectTime":1637809330156,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760323,ID:000000000221a8c382ac56ce2dfc37e7921ba015e69d036b27be2b371dbfe605","host":"47.75.74.31","inFlow":481118,"lastBlockUpdateTime":1637809366083,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"6945243052c204c46cbfc67b697ea0a8868b01bcc2e9da827121cee1fdc1454c63ca9596bd4bcb31301637f690b4d6b02b4bb20ba26b632be0e57dc335634b54","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":260,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":78.0,"blockInPorcSize":0,"connectTime":1637773400532,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760326,ID:000000000221a8c6e78fa22063ab3e30143ee3e9054e2f01a0baa1130e5f6b75","host":"13.114.133.127","inFlow":679478,"lastBlockUpdateTime":1637809374971,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"d1f93396f96a5be01b2db7e81415e554545cb7469c3b4ceac521f4a07132475943b978729396ef31d5c4485ec4af90595d1457d026001a7bee82d6c7a3151415","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":40,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":80.0,"blockInPorcSize":0,"connectTime":1637771395741,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760331,ID:000000000221a8cbc92a63013633fa1a7de52a5a126eeff84042808a4639c9db","host":"13.115.75.251","inFlow":1223372,"lastBlockUpdateTime":1637809389997,"lastSyncBlock":"Num:35753134,ID:0000000002218cae63d62ddae7ab8e248b87d28338feb92e2849eda90dd3646b","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"728dee50e11a9a787409ed353e433304317a65e3d6aace8a1f60120b8a98b93fb3721bfa6c9b0e3ba474c7e0dd464c5980dd329e28884d8d752bb7d462d2285f","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":90,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":95.0,"blockInPorcSize":0,"connectTime":1637807282294,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760325,ID:000000000221a8c5fe716128b8dd19d95c4d363f137ca39d3bac28bc30d32b9b","host":"77.242.242.207","inFlow":359421,"lastBlockUpdateTime":1637809371995,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"8793edd2a3bf31a02b281b1a7bc038cbd0724c8dec46102a098a49b428f055055a4bfa6e8054bd9e2746f6bcefd8d0421b0c55c1eed1a245cb803f682d541d03","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":40,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":117.0,"blockInPorcSize":0,"connectTime":1637792756175,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760331,ID:000000000221a8cbc92a63013633fa1a7de52a5a126eeff84042808a4639c9db","host":"202.143.111.11","inFlow":244169,"lastBlockUpdateTime":1637809389939,"lastSyncBlock":"Num:35755809,ID:00000000022197216d279ba8cf0d0d2999b96625e2e2047732b57b776c6173b1","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"16c633b4b1c83f4c3a64e07532a331725802518be8de73f397488713826400dd8870d7292f6b5d7a69ed68305ed21f7854199a656882ffefa929928bcebc7561","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":40,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":157.0,"blockInPorcSize":0,"connectTime":1637784412415,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760331,ID:000000000221a8cbc92a63013633fa1a7de52a5a126eeff84042808a4639c9db","host":"1.234.54.78","inFlow":846654,"lastBlockUpdateTime":1637809390050,"lastSyncBlock":"Num:35759902,ID:000000000221a71e26ebebaf78717f2a6751dc38ceb08c8c475e921dcde93c86","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"8457ae2171c37723781d8640d38a1b372cda3e86f46791afff9a718c93a964ebc0d62416a98e32210f06e1fb328453341918830e3191ab00309869fcc79ebad3","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":40,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":177.0,"blockInPorcSize":0,"connectTime":1637809380489,"disconnectTimes":1,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:0,ID:0000000000000000000000000000000000000000000000000000000000000000","host":"138.201.45.232","inFlow":1003,"lastBlockUpdateTime":1637809380582,"lastSyncBlock":"Num:34888342,ID:0000000002145a96a9b98bb3a2f092a0e4791d80fe3ca72589a3cdfaf9c0e336","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":true,"nodeCount":90,"nodeId":"b873ffa112068bf94fc085586100f67875d89269388e210df1e8422f8b7de0a5b139f234253bdfad2748fbad0c37de14c03a23f4da148d98ebafe327efebb0f3","port":19083,"remainNum":871985,"remoteDisconnectReason":"TIME_OUT","score":214,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":871985},{"active":false,"avgLatency":178.0,"blockInPorcSize":0,"connectTime":1637809370799,"disconnectTimes":1,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:0,ID:0000000000000000000000000000000000000000000000000000000000000000","host":"78.83.124.135","inFlow":16775,"lastBlockUpdateTime":1637809370886,"lastSyncBlock":"Num:3122003,ID:00000000002fa35338002d46f6f6d5f388e5f46404a37741f70763e6d41aef0d","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":true,"nodeCount":90,"nodeId":"0507e4b8142f0e094d528b73994537fbf27344f7d35a84af629a3ec719aa41b0a75e4311a846ecb4a18127550080de86d82b19a5d5562ca8cae7c1b5100e3df1","port":18888,"remainNum":32638321,"remoteDisconnectReason":"TIME_OUT","score":11,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":32638321},{"active":false,"avgLatency":200.0,"blockInPorcSize":0,"connectTime":1637774114390,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760323,ID:000000000221a8c382ac56ce2dfc37e7921ba015e69d036b27be2b371dbfe605","host":"168.119.137.225","inFlow":6571218,"lastBlockUpdateTime":1637809366219,"lastSyncBlock":"Num:35748583,ID:0000000002217ae7dd1de8bc6e3305745d742a1df2babb54ccec085b62afd912","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"9d001c995c77eb2fe820d06849935c11129d47d0dbb9f71e15606cab62a39275a0033fdfd2aca5e24655d6c73cbd545fb3dd1c74aceb17924344f124c0534e12","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":40,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":206.0,"blockInPorcSize":0,"connectTime":1637788383247,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760277,ID:000000000221a895943dd150760f3a83d5ad1635565ab8ff4321e2df85e2f4db","host":"66.29.147.99","inFlow":5710646,"lastBlockUpdateTime":1637809228025,"lastSyncBlock":"","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"64e3214790132fd778068bdc4e106d12f1c9327ca96545cc3982d59a8ecb44bede8bb427f3e43afca9ac0a42739099dc78841eee38214f102e7ba7dfcdb77c70","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":40,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0},{"active":false,"avgLatency":482.0,"blockInPorcSize":0,"connectTime":1637809307616,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:32552491,ID:0000000001f0b62b105f55ed0426694a25f995c321bb3d3cc0dcc5e379e6336e","host":"13.230.237.195","inFlow":24970,"lastBlockUpdateTime":1637809333529,"lastSyncBlock":"Num:32553036,ID:0000000001f0b84ce29b7e49829281ba1c684011c4b2b2c8c3929c5ef2cae4d9","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":true,"nodeCount":90,"nodeId":"71f25b131a549b33cc5c6643c02e7e7bff84144efe07ee3ccac79127c9877bbc92104bb5d2e08ef4e8d9503edde3c25a5a7d0a61a49ecdd28135bc96f012ca0a","port":18888,"remainNum":3207269,"remoteDisconnectReason":"","score":22,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":3207269},{"active":false,"avgLatency":781.0,"blockInPorcSize":0,"connectTime":1637808001120,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:35760326,ID:000000000221a8c6e78fa22063ab3e30143ee3e9054e2f01a0baa1130e5f6b75","host":"47.243.43.165","inFlow":301724,"lastBlockUpdateTime":1637809374930,"lastSyncBlock":"Num:35760302,ID:000000000221a8ae5bd6ddc595f9ed39083072a39db66354631d2de9d1c7668d","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":false,"nodeCount":90,"nodeId":"661050f66701337b909443df8ed47e82dc51e9ec7600d0094250f4212559d035256b6e239939657bc3ea791e14a29fc23ecf139b856a937967ed6eb8222a9fa5","port":18888,"remainNum":0,"remoteDisconnectReason":"","score":40,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":0}],"solidityBlock":"Num:35760314,ID:000000000221a8ba14dda1b0850c7fe46d2c0995bf984c9e7fb435c5b50eb0cd","totalFlow":23883697}`
### 2. What did you expect to see?

 how to show this node on map https://tronscan.org/#/blockchain/nodes

**Comment by Benson0224** [comment]
please contact @benson0224 on telegram and share your IP info, thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks
