### ISSUE TITLE
lose leveldbjni-all/1.18.3 in spring.io

### ISSUE THREAD

**Issue by RelicOfTesla** [tronprotocol/java-tron#4159]
```
FAILURE: Build failed with an exception.

* Where:
Build file 'E:\java-tron\framework\build.gradle' line: 208

* What went wrong:
Could not determine the dependencies of task ':framework:buildSolidityNodeJar'.
> Could not resolve all files for configuration ':framework:compile'.
   > Could not resolve org.ethereum:leveldbjni-all:1.18.3.
     Required by:
         project :framework > project :chainbase
         project :framework > project :chainbase > project :common
      > Could not resolve org.ethereum:leveldbjni-all:1.18.3.
         > Could not get resource 'https://repo.spring.io/plugins-release/org/ethereum/leveldbjni-all/1.18.3/leveldbjni-all-1.18.3.pom'.
            > Could not GET 'https://repo.spring.io/plugins-release/org/ethereum/leveldbjni-all/1.18.3/leveldbjni-all-1.18.3.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 14s
```

**Comment by Benson0224** [comment]
Please use Oracle Java8 instead of openjdk.
https://github.com/frekele/oracle-java/releases/tag/8u202-b08

**Comment by RelicOfTesla** [comment]
```
C:\Users\Administrator>java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```

**Comment by Benson0224** [comment]
by default it is not supported on Windows, Suggest you try on Ubuntu or Mac.

However, some developers also build it successfully on Windows with "Linux SubSystem"
![image](https://user-images.githubusercontent.com/61768920/143998777-9642a471-b601-4d57-b832-7110c8ba258a.png)

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks

**Comment by ligki** [comment]
I got the same problem about leveldbjni. Because https://repo.spring.io/plugins-release/org/ethereum/leveldbjni-all/1.18.3/leveldbjni-all-1.18.3.pom requires logged in to download, I dont know why.
I fixed this issue by comment all leveldbjni config in build.gradle files, then add this jar library file to local like this

https://stackoverflow.com/questions/20700053/how-to-add-local-jar-file-dependency-to-build-gradle-file

**Comment by optinsoft** [comment]
In build.gradle in repositories section change this:
maven { url 'https://repo.spring.io/plugins-release' }
by this:
maven { url 'https://repo.softmotions.com/repository/softmotions-public' }
or you can use your url that points to repo org/ethereum/leveldbjni-all/org/1.18.3
