### ISSUE TITLE
Unable to display sr node on transcan map

### ISSUE THREAD

**Issue by tqcc** [tronprotocol/java-tron#4167]
### 1. What did you do?

I am running a SR node, but node can not display on tronscan map

the node map did not update since 2021/04 
https://www.blocdesk.com/tron-growth-as-us-nodes-dominate-the-network/

### 2. What did you expect to see?

 how to show this node on map https://tronscan.org/#/blockchain/nodes

if being able to display our node on map, it improve credibility of our node, and attract more users to vote.

**Comment by Benson0224** [comment]
Team is working on that, will update you here once fixed. thanks.

**Comment by Benson0224** [comment]
Tronscan already updated the node page.  
Please check more detail here: https://tronscan.org/#/blockchain/nodes 

Feel free to let us know if you have more issue, thanks.

**Comment by Benson0224** [comment]
thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open this issue if you still see it. thanks.
