### ISSUE TITLE
Full node stop syncing after 500 blocks

### ISSUE THREAD

**Issue by kyrychenko-dmytro** [tronprotocol/java-tron#4174]
### 1. What did you do?
Start full node and solidity node by the config from github.
We tried from start and with backup.
In config only these param are edited: supportConstant = true, db.sync = true,

### 2. What did you expect to see?
We expect to see fully synced node or syncing at least.

### 3. What did you see instead?
But node stop syncing after 500 blocks.
After restart node process only 500 blocks synced again.

**Comment by Benson0224** [comment]
Please share the latest log file, thanks.

**Comment by kyrychenko-dmytro** [comment]
Log file

14:33:26.045 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /136.243.144.79:18888.
14:33:26.054 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /3.67.199.220:18888.
14:33:29.702 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /8.208.8.242:18888.
14:33:32.315 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /144.76.75.170:18888.
14:33:33.257 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /162.55.133.112:18888.
14:33:33.258 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /23.88.68.118:18888.
14:33:33.268 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /157.90.211.229:18888.
14:33:33.268 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /157.90.129.152:18888.
14:33:33.355 WARN  [sendTimer] [net](MessageQueue.java:176) Wait class org.tron.common.overlay.message.PongMessage timeout. close channel /195.123.188.191:18888.

**Comment by Benson0224** [comment]
The log you shared does not include any useful info,  Please share the full log file, or you can share the log file with the admins of this group in telegram: https://t.me/TronOfficialDevelopersGroupEn 

Thanks.

**Comment by kyrychenko-dmytro** [comment]
Thanks, all works,but without docker. In docker it is stuck

**Comment by mehdi-agh** [comment]
Route 18888 udp to the docker container or change the below line in docker.sh:
parameter=" -p $HOST_HTTP_PORT:$DOCKER_HTTP_PORT -p $HOST_RPC_PORT:$DOCKER_RPC_PORT -p $HOST_LISTEN_PORT:$DOCKER_LISTEN_PORT -p $HOST_LISTEN_PORT:$DOCKER_LISTEN_PORT/udp"
