### ISSUE TITLE
WBTT was transferred to gate.io exchange instead of BTT and now it is stuck in the blockchain

### ISSUE THREAD

**Issue by SiriusAlphaa** [tronprotocol/java-tron#4176]
### 1. What did you do?

Contacted with gate.io support team, opened a ticked and was told WBTT wasn't supported on gate.io as of now 

### 2. What did you expect to see?
My WBTT (Wrapped Bittorent) token got stuck in the gate.io blockchain and I want to recover them 

### 3. What did you see instead?
I don't see any my WBTT tokens in my gate.io account 
Need advice and help to recover them

**Comment by Benson0224** [comment]
This can only be fixed by gate.io.  Please contact gate.io for support. thanks.

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks
