### ISSUE TITLE
nile testnet peers

### ISSUE THREAD

**Issue by Black52** [tronprotocol/java-tron#4179]
nile URL：https://nileex.io/join/getJoinPage
I used the snapshot and configuration file here to start，There is only one seed.node in the configuration  

seed.node = {
  ip.list = [
    "47.90.214.183:18888",
  ]
}
Can anyone give me a little bit more peers? I'm out of sync now！！

**Comment by Benson0224** [comment]
Please share the fulllog file. there must be some other reason. 
After started, the node will build its own connection peers automatically.

**Comment by Black52** [comment]
> 请分享完整日志文件。一定有别的原因。 启动后，节点会自动建立自己的连接对等体。

10:38:14.783 INFO  [main] [app](FullNode.java:53) Full node running.
10:38:15.275 INFO  [main] [app](Args.java:1026) Bind address wasn't set, Punching to identify it...
10:38:15.302 INFO  [main] [app](Args.java:1029) UDP local bound to: 172.31.22.106
10:38:15.306 INFO  [main] [app](Args.java:1044) External IP wasn't set, using checkip.amazonaws.com to identify it...
10:38:15.716 INFO  [main] [app](Args.java:1058) External address identified: 18.139.3.9
10:38:15.731 INFO  [main] [app](Args.java:1141) 

10:38:15.732 INFO  [main] [app](Args.java:1142) ************************ Net config ************************
10:38:15.732 INFO  [main] [app](Args.java:1143) P2P version: 201910292
10:38:15.732 INFO  [main] [app](Args.java:1144) Bind IP: 172.31.22.106
10:38:15.732 INFO  [main] [app](Args.java:1145) External IP: 18.139.3.9
10:38:15.733 INFO  [main] [app](Args.java:1146) Listen port: 18888
10:38:15.733 INFO  [main] [app](Args.java:1147) Discover enable: true
10:38:15.733 INFO  [main] [app](Args.java:1148) Active node size: 1
10:38:15.733 INFO  [main] [app](Args.java:1149) Passive node size: 0
10:38:15.734 INFO  [main] [app](Args.java:1150) FastForward node size: 0
10:38:15.734 INFO  [main] [app](Args.java:1151) Seed node size: 1
10:38:15.734 INFO  [main] [app](Args.java:1152) Max connection: 30
10:38:15.734 INFO  [main] [app](Args.java:1153) Max connection with same IP: 2
10:38:15.734 INFO  [main] [app](Args.java:1154) Solidity threads: 8
10:38:15.734 INFO  [main] [app](Args.java:1155) ************************ Backup config ************************
10:38:15.734 INFO  [main] [app](Args.java:1156) Backup priority: 8
10:38:15.735 INFO  [main] [app](Args.java:1157) Backup listen port: 10001
10:38:15.735 INFO  [main] [app](Args.java:1158) Backup listen keepAliveInterval: 3000
10:38:15.735 INFO  [main] [app](Args.java:1159) Backup member size: 0
10:38:15.735 INFO  [main] [app](Args.java:1160) ************************ Code version *************************
10:38:15.736 INFO  [main] [app](Args.java:1161) Code version : 4.4.0
10:38:15.736 INFO  [main] [app](Args.java:1162) Version code: 16334
10:38:15.737 INFO  [main] [app](Args.java:1163) ************************ DB config *************************
10:38:15.738 INFO  [main] [app](Args.java:1164) DB version : 2
10:38:15.739 INFO  [main] [app](Args.java:1165) DB engine : LEVELDB
10:38:15.739 INFO  [main] [app](Args.java:1166) ***************************************************************
10:38:15.739 INFO  [main] [app](Args.java:1167) 

10:38:15.739 INFO  [main] [app](FullNode.java:67) not in debug mode, it will check energy time
10:38:16.007 INFO  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:578) Refreshing org.tron.common.application.TronApplicationContext@4d0d9fe7: startup date [Fri Dec 10 10:38:16 CST 2021]; root of context hierarchy
10:38:18.247 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
10:38:19.112 INFO  [main] [app](DefaultConfig.java:58) key-value data source created.
10:38:23.280 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractLogTriggerMap
10:38:23.280 WARN  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:398) Autowired annotation is not supported on static fields: private static java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractEventTriggerMap
10:38:23.584 INFO  [main] [discover](NodeManager.java:78) homeNode : Node{ host='18.139.3.9', port=18888, id=1a6ca4d98ea53faed6f077cc9013f7f2436893fa50e5f873e08fb7bc2dde13a9f297a9d6957a9721d0f18aea92519987b7d6670a0452058e272ccdfb73825763}
10:38:23.596 WARN  [main] [app](LocalWitnesses.java:104) privateKey is null
10:38:25.544 INFO  [DiscoverServer] [discover](DiscoverServer.java:102) Discovery server started, bind port 18888
10:38:25.874 INFO  [nioEventLoopGroup-2-1] [discover](NodeManager.java:123) Reading node statistics from store: 30 nodes.
10:38:26.183 INFO  [main] [app](FullNode.java:141) ********register application shutdown hook********
10:38:26.186 INFO  [main] [API](FullNodeHttpApiService.java:307) init zk param begin
10:38:27.086 INFO  [main] [API](FullNodeHttpApiService.java:328) init zk param done
10:38:27.841 INFO  [main] [API](RpcApiService.java:278) RpcApiService has started, listening on 50051
10:38:27.873 INFO  [main] [o.e.j.u.log](Log.java:193) Logging initialized @13892ms to org.eclipse.jetty.util.log.Slf4jLog
10:38:28.234 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
10:38:28.371 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
10:38:28.372 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
10:38:28.374 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 600000ms
10:38:28.422 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@77978658{/,null,AVAILABLE}
10:38:28.444 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@2bee1c13{HTTP/1.1,[http/1.1]}{0.0.0.0:8090}
10:38:28.444 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @14463ms
10:38:28.470 INFO  [main] [API](RpcApiServiceOnSolidity.java:133) RpcApiServiceOnSolidity started, listening on 50061
10:38:28.474 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
10:38:28.541 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
10:38:28.541 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
10:38:28.541 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 600000ms
10:38:28.572 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@361483eb{/,null,AVAILABLE}
10:38:28.576 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@14983265{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}
10:38:28.576 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @14595ms
10:38:28.595 INFO  [main] [API](RpcApiServiceOnPBFT.java:133) RpcApiServiceOnPBFT started, listening on 50071
10:38:28.596 WARN  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:1566) o.e.j.s.ServletContextHandler@3fa50a24{/,null,UNAVAILABLE} contextPath ends with /
10:38:28.598 INFO  [main] [o.e.j.s.Server](Server.java:374) jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 11.0.11+9-Ubuntu-0ubuntu2.20.04
10:38:28.706 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:365) DefaultSessionIdManager workerName=node0
10:38:28.706 INFO  [main] [o.e.j.s.session](DefaultSessionIdManager.java:370) No SessionScavenger set, using defaults
10:38:28.707 INFO  [main] [o.e.j.s.session](HouseKeeper.java:149) node0 Scavenging every 600000ms
10:38:28.728 INFO  [main] [o.e.j.s.h.ContextHandler](ContextHandler.java:851) Started o.e.j.s.ServletContextHandler@3fa50a24{/walletpbft,null,AVAILABLE}
10:38:28.730 INFO  [main] [o.e.j.s.AbstractConnector](AbstractConnector.java:289) Started ServerConnector@630febd7{HTTP/1.1,[http/1.1]}{0.0.0.0:8092}
10:38:28.730 INFO  [main] [o.e.j.s.Server](Server.java:411) Started @14749ms
10:38:28.748 INFO  [main] [net](ChannelManager.java:86) Node config, trust 1, active 1, forward 0.
10:38:28.780 INFO  [main] [net](FastForward.java:61) Fast forward config, isWitness: false, keySize: 0, fastForwardNodes: 0
10:38:28.845 INFO  [main] [net](TronNetService.java:70) TronNetService start successfully.
10:38:28.846 WARN  [main] [app](LocalWitnesses.java:104) privateKey is null
10:38:28.859 WARN  [main] [consensus](ConsensusService.java:73) Witness 41dcc703c0e500b653ca82273b7bfad8045d85a470 is not in witnessStore.
10:38:28.871 INFO  [PeerServerThread] [net](PeerServer.java:54) TCP listener started, bind port 18888
10:38:28.871 INFO  [main] [consensus](ConsensusService.java:84) consensus service start success
10:38:57.329 WARN  [nioEventLoopGroup-2-1] [discover](NodeHandler.java:176) Receive neighbors from 188.93.90.138 without send find nodes.
10:38:57.391 WARN  [nioEventLoopGroup-2-1] [discover](NodeHandler.java:176) Receive neighbors from 18.156.5.225 without send find nodes.
10:38:57.421 WARN  [nioEventLoopGroup-2-1] [discover](NodeHandler.java:176) Receive neighbors from 47.252.23.81 without send find nodes.
10:38:58.761 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 47.90.214.183 18888 55d77118b0ad6232c61f65eb8ea4fb5ac3d377c115f07822f283730160a1f15d6a23cd584c2535a18d06e18efbbf8374acbbeeea032608ea148e27bd342d0f9b
10:38:58.762 INFO  [pool-2-thread-1] [net](SyncPool.java:137) 

============ Peer stats: all 0, active 0, passive 0


10:38:58.770 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 47.75.109.52 18888 bfcc34cd9b870867d58f00c435a972f97e4712c3bb64894227ccb59b9e625d9dc04b84e1588b617080bec1468ef30a7686406d4fb4fb5d426b3f826a9299280e
10:38:58.771 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 198.13.41.193 18888 e5d0b8b520412c54da8f2bdaf38df0c778cf0a9835953b4ecffa3482f7e1e80a924d1021e11b97704f6dcddfb0fd02658a87004bcc6b53e47490c7432aafecbd
10:38:58.772 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 47.90.206.149 18888 ed9f8b9581b4609a1f4b225203fd9df1431fe2dba6ba1af2d8d226172f8071bf2bb616679bd46eaca69a58eeee391efbca02f57481c6f1652b662e2e305c6947
10:38:58.777 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 47.253.34.98 18888 aed33a9ebc41be6998de6f2d7505dc864de2e00bf2f732aeae6a42b4799988399299c994dc6ed750183486124be9e9f3b51f73ffb37c5d1fc492187d3da3127d
10:38:58.778 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 47.252.19.181 18888 4b403cd54d2c82ea9e929e627be10fde62725d95587dac019be8494ce01f2d6a748d414165b5f45baa97770f09c60bb3cb92924288789ba68a816604f0777977
10:38:58.782 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 135.181.216.36 18888 42140cca2198476fea2789605985b07cc12e048a2df87b70b4ccdde1f9dfccb294ef4e4f02b1b6d19847679b1df6530289a51d1fbdb404338c78109a15bb197c
10:38:58.785 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 47.100.235.92 18888 c2f26f042244693dde9a7fdf90e6b5bd63eae192d1dc12238ca9a7084128ddd854af944e338f7ab0bce816beeadc122c2f021d01a3cf96d474da5b6beaeb4fa4
10:38:58.788 INFO  [pool-1-thread-1] [net](PeerClient.java:70) connect peer 47.252.23.81 18888 3719126968c69945e0e0ff063634d12097253573be00a3f8b71911932c0235fbdeda315b3c06024eb72d8602cf6cbdd1ef6305d6fd8ba302f62694111c472791
10:38:59.095 INFO  [TronJClientWorker-8] [net](HandshakeHandler.java:77) channel active, /47.252.23.81:18888
10:38:59.097 ERROR [TronJClientWorker-8] [net](Channel.java:156) Close peer /47.252.23.81:18888, exception caught
java.lang.NullPointerException: null
	at org.tron.core.ChainBaseManager.getGenesisBlockId(ChainBaseManager.java:369)
	at org.tron.common.overlay.server.HandshakeHandler.sendHelloMsg(HandshakeHandler.java:123)
	at org.tron.common.overlay.server.HandshakeHandler.channelActive(HandshakeHandler.java:81)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.base/java.lang.Thread.run(Thread.java:829)
10:38:59.098 INFO  [TronJClientWorker-8] [net](TronChannelInitializer.java:48) Close channel:/47.252.23.81:18888 | 3719126968c69945e0e0ff063634d12097253573be00a3f8b71911932c0235fbdeda315b3c06024eb72d8602cf6cbdd1ef6305d6fd8ba302f62694111c472791
10:38:59.098 INFO  [TronJClientWorker-4] [net](HandshakeHandler.java:77) channel active, /47.253.34.98:18888
10:38:59.099 ERROR [TronJClientWorker-4] [net](Channel.java:156) Close peer /47.253.34.98:18888, exception caught
java.lang.NullPointerException: null
	at org.tron.core.ChainBaseManager.getGenesisBlockId(ChainBaseManager.java:369)

**Comment by Benson0224** [comment]
Please share the full log file, thanks. 
Contact @benson0224 on telegram if the file is too big. thanks.

**Comment by Black52** [comment]
> Please share the full log file, thanks. Contact @Benson0224 on telegram if the file is too big. thanks.

These are the complete logs. Failed to connect to the peer。

Could you please tell us the deployment steps of tron testnetwork synchronization

**Comment by Benson0224** [comment]
Did you change any item of the configuration file?  if yes please share your configuration file here.   
if not please share below info:
1. how many CPU cores and memory size of your server
2. Java version
3. The command of starting fullnode.

**Comment by Black52** [comment]
> Did you change any item of the configuration file? if yes please share your configuration file here. if not please share below info:
> 
> 1. how many CPU cores and memory size of your server
> 2. Java version
> 3. The command of starting fullnode.


Configuration file copy no change here https://nileex.io/join/getJoinPage

1、CPU：8C   memory：32G
2、openjdk version "11.0.11" 2021-04-20
     OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
     OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
3、nohup java -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -jar /data/trx-testnet/FullNode.jar  -c /data/trx-testnet/fullnode.conf --output-directory /data/trx-testnet/output-directory/ &

**Comment by Benson0224** [comment]
1. Please use oracle java8, other JAVA versions are not supported.  https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile#L12
2.  change the ` -Xmx6g` to  `-Xmx24g` since you have 32G memory. thanks.

**Comment by Black52** [comment]
> 1. Please use oracle java8, other JAVA versions are not supported.  https://github.com/tronprotocol/java-tron/blob/develop/Dockerfile#L12
> 2. change the ` -Xmx6g` to  `-Xmx24g` since you have 32G memory. thanks.

Oracle java8 started successfully, thank you very much

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks
