### ISSUE TITLE
Querying data of old transactions

### ISSUE THREAD

**Issue by Bratishques** [tronprotocol/java-tron#4181]
Hi! I'm having an issue with getting the old block data, and I need someone who is familiar with older history of java-tron to help me.
I want to query data of earlier transaction fees, as far as I know you can get fee via http://localhost:8090/wallet/gettransactioninfobyid, but querying earlier tx (for example c3e1417f78d4200e02cd496b2e548d3f516d6a93de0694b4a6c0e8f720f88d28 from 500003 block) yields empty no result

### 1. What did you do?
I did a POST gettransactioninfobyid request to a FullNode interface with an earlier txid.

### 2. What did you expect to see?
Something like this

``` json
{
	"id": "07ff56fdb569193b9139b53a5933d4a51a0cea258cb94387e507ca8ad5afd366",
	"fee": 268000,
	"blockNumber": 36204259,
	"blockTimeStamp": 1639144938000,
	"contractResult": [
		""
	],
	"receipt": {
		"net_fee": 268000
	}
}
```

### 3. What did you see instead?
{}

Is there a way to query this data using FullNode? If not, what will be an optimal solution

**Comment by Benson0224** [comment]
Please refer to the below reply. transactions before 2018-11-30 cannot be queried via `gettransactioninfobyid`. 
https://github.com/tronprotocol/java-tron/issues/3989#issuecomment-899947604

**Comment by Bratishques** [comment]
Thanks a lot! Will try to do some workarounds
