### ISSUE TITLE
OpenJDK, newer Java versions

### ISSUE THREAD

**Issue by briancolecoinmetrics** [tronprotocol/java-tron#4211]
Currently https://github.com/tronprotocol/java-tron/blob/develop/build.md says,

> JDK 1.8 (JDK 1.9+ are not supported yet)
> On Linux Ubuntu system (e.g. Ubuntu 16.04.4 LTS), ensure that the machine has Oracle JDK 8, instead of having Open JDK 8 in the system. If you are building the source code by using Open JDK 8, you will get Build Failed result.

First: OpenJDK works fine and has for a while; we've been building with openjdk-8-jdk-headless and running on openjdk-8-jre-headless on Ubuntu for a while now.

Second: While Java 8 will keep getting security updates for a while yet, it's nearing the end of its normal support life; is there any plan to support newer levels?

**Comment by Benson0224** [comment]
Thanks for your suggestion. 
Team will update you here if there is a plan on the Java new versions.

**Comment by andelf** [comment]
For compatibility with the mainnet, java-tron can only be run on x86-64 platforms(and jdk8). It requires 8087 float instructions.
See-also: https://github.com/tronprotocol/java-tron/issues/3542 https://github.com/opentron/opentron/issues/36

**Comment by ai-chen2050** [comment]
> For compatibility with the mainnet, java-tron can only be run on x86-64 platforms(and jdk8). It requires 8087 float instructions.

I use the mac m1 pro/jdk8,whether work?

**Comment by halibobo1205** [comment]
> > For compatibility with the mainnet, java-tron can only be run on x86-64 platforms(and jdk8). It requires 8087 float instructions.
> 
> I use the mac m1 pro/jdk8,whether work?

Use x86_jdk8 can work well.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks
