### ISSUE TITLE
java-tron not syncing and silently exits

### ISSUE THREAD

**Issue by camharris** [tronprotocol/java-tron#4234]
### 1. What did you do?
I've restarted the node several times without touching it's block data. 

### 2. What did you expect to see?
The node able to sync pass block 36757995

### 3. What did you see instead?
Seems that the node has been unable to connect to any peers for several hours and after restarting attempts to sync for several minutes before exiting. Almost every peer that it attempts to connect to seems to respond with TOO_MANY_PEERS.  Currently running release GreatVoyage-v4.4.1(Protagoras)
Log snippet before exit: https://0bin.net/paste/thMH96YV#t4MIqqnhEYCRO8C76yGgE5ICFU+bWzqS2nb7U9NMtTt

tron.conf: https://0bin.net/paste/ZLyDweNO#2bOEWejPZiziMJ9TJoPtuorzbKuBXwyQk5zHuVHdU7Z

**Comment by vivian-kang** [comment]
Hi camharris,
