### ISSUE TITLE
Update protoc-gen-grpc-java dependency to > v1.26.0 to be able to build in ARM64

### ISSUE THREAD

**Issue by yagop** [tronprotocol/java-tron#4248]
### 1. What did you do?
Trying to build java-tron

### 2. What did you expect to see?
A java-tron builded

### 3. What did you see instead?
```
 > Could not find protoc-gen-grpc-java-linux-aarch_64.exe (io.grpc:protoc-gen-grpc-java:1.9.0).13 actionable tasks: 13 executed
#8 164.9      Searched in the following locations:
#8 164.9          https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.9.0/protoc-gen-grpc-java-1.9.0-linux-aarch_64.exe
```

### Problem
You are using old version of `protoc-gen-grpc-java` which lacks arm64 binaries. See `protoc-gen-grpc-java-1.9.0-linux-aarch_64.exe` is missing from https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.9.0/ .

### Asking
Update `protoc-gen-grpc-java` to >= v1.26.0  in order to be able to build java-tron in arm64.

**Comment by vivian-kang** [comment]
Hi, please provide detailed information, thanks. which operation system and device do you compile the java-tron project, and do you use any IDE or compile tool to compile the project?

**Comment by yagop** [comment]
> which operation system and device do you compile the java-tron project
I'm using Ubuntu 18.04.6 Docker for ARM64

> do you use any IDE or compile tool to compile the project
I'm not using any IDE. Just `./gradlew build -x test`

**Comment by vivian-kang** [comment]
Currently ARM64 architecture is not supported by java-tron, but it is under planning，so now I will suggest to build and run fulllnode under intel or AMD architecture, and for ARM64 support, please pay attention to the announcement or release of java-tron. Thanks.

**Comment by yagop** [comment]
To support ARM64 you need to upgrade `protoc-gen-grpc-java` which uses a very old version with CVE, see https://mvnrepository.com/artifact/io.grpc/protoc-gen-grpc-java/1.9.0

I need to run java-tron in my machine which is an ARM64. I would be happy to test for you if you do the changes.

**Comment by vivian-kang** [comment]
Thanks for your information. but for supporting ARM64 architecture, It maybe not just a dependent library needs to be upgraded, but JDK or DB and so on. and it is under planning. So now it is recommended to build on an alternative machine which based on intel/AMD.  Or if you're interested on this, you can try to modify the code to meet the requirement. Thanks.

**Comment by yagop** [comment]
That library is a block, there might be others, you can try to build to arm64 with this Dockerfile:

```Dockerfile
# centos7 is ready for arm64
FROM centos:centos7 

ENV TMP_DIR="/tron-build"
# Use arm64-vfp-hflt
ENV JDK_TAR="jdk-8u202-linux-arm64-vfp-hflt.tar.gz"
ENV JDK_DIR="jdk1.8.0_202"
ENV BASE_DIR="/java-tron"


RUN set -o errexit -o nounset \
    && yum -y install git wget \
    && wget -P /usr/local https://github.com/frekele/oracle-java/releases/download/8u202-b08/$JDK_TAR \
    && tar -zxf /usr/local/$JDK_TAR -C /usr/local \
    && rm /usr/local/$JDK_TAR

RUN export JAVA_HOME=/usr/local/$JDK_DIR \
    && export CLASSPATH=$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar \
    && export PATH=$PATH:$JAVA_HOME/bin \
    && echo "git clone" \
    && mkdir -p $TMP_DIR \
    && cd $TMP_DIR \
    && git clone https://github.com/tronprotocol/java-tron.git \
    && cd java-tron \
    && git checkout "GreatVoyage-v4.4.3" \
    && ./gradlew build -x test \
    && cd build/distributions \
    && unzip -o java-tron-1.0.0.zip \
    && mv java-tron-1.0.0 $BASE_DIR \
    && rm -rf $TMP_DIR \
    && rm -rf ~/.gradle \
    && mv $JAVA_HOME/jre /usr/local \
    && rm -rf $JAVA_HOME \
    && yum clean all

ENV JAVA_HOME="/usr/local/jre"
ENV PATH=$PATH:$JAVA_HOME/bin

COPY docker-entrypoint.sh $BASE_DIR/bin

WORKDIR $BASE_DIR

ENTRYPOINT ["./bin/docker-entrypoint.sh"]
```

```
docker buildx build --platform linux/arm64 -t java-tron .
```

**Comment by vivian-kang** [comment]
Thanks for your information. Because it has already under planning, so we will keep you informed if there's any progress

**Comment by yagop** [comment]
Any updates on this?

**Comment by forfreeday** [comment]
@yagop 
A docker mirror supporting the ARM architecture is already in development

**Comment by yagop** [comment]
Any update on this?

**Comment by yagop** [comment]
Update protoc-gen-grpc-java please

**Comment by 11111961abc** [comment]
79136741676 все переговоры на русском.Сергей Николаевич

чт, 16 июн. 2022 г., 17:57 Yago ***@***.***>:

**Comment by andelf** [comment]
For compatibility with the mainnet, java-tron can only be run on x86-64 platforms(and jdk8). It requires 8087 float instructions.
See-also: https://github.com/tronprotocol/java-tron/issues/3542 https://github.com/opentron/opentron/issues/36

**Comment by yagop** [comment]
> It requires 8087 float instructions.

What instructions? AFIK Tron is written in pure Java so should be able to compile for the ARM JVM.

**Comment by andelf** [comment]
@yagop That's the hidden part of JVM.
FYI: https://github.com/opentron/opentron/issues/36

**Comment by yagop** [comment]
Please stop saying not verified unrelated justifications.

I’m only asking you guys to update protoc-gen-grpc-java which is using old version which is vulnerable.

@vivian-kang and @forfreeday stated this was underplaying half a year ago but no progress was made

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
