### ISSUE TITLE
Full Node Sync Problem. The node stayed on the 37491526. block !

### ISSUE THREAD

**Issue by gitloverr** [tronprotocol/java-tron#4260]
Hi everyone,

I'm running a Tron Full Node on my server. My node version is   **GreatVoyage-v4.4.3(Pythagoras)**

But the node stayed on the  Block 37491526. Also I got this error: 

`18:38:58.973 ERROR [pool-50-thread-1] [net](SyncService.java:270) Process sync block Num:37491526,ID:00000000023c13463ad951b0c17ad1378e0ebc072dbd641a2eb50fecd2b573de failed.`

all logs is here: 

`
18:38:58.973 ERROR [pool-50-thread-1] [net](SyncService.java:270) Process sync block Num:37491526,ID:00000000023c13463ad951b0c17ad1378e0ebc072dbd641a2eb50fecd2b573de failed.
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
last know block num: 0
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
last know block num: 0
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
size: 5, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37491525,ID:00000000023c134537694d65d9cf184801334c839158a34a596b30c94bdb8c3a
size: 11, start block: Num:37491506,ID:00000000023c13328dd8b54407b3b2d7163338cfdcb16601f6bfc2e648b9922e, end block Num:37493525,ID:00000000023c1b15fabcc39cd2e48976da7ded4547ce3bb978374010468a8c77
`

how can I solve this problem?

thank you

**Comment by Benson0224** [comment]
Please try this and see whether it fixes your issue.  Please share the new full log file if you still see it. thanks. 

https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

**Comment by Ufakeimdope** [comment]
https://open.spotify.com/track/49BdaEKbK8wgcjCiZFn8Mb?si=M7tHTJi8RuW4P8MImhC9iw&utm_source=copy-link
