### ISSUE TITLE
How do I get TRC20 transaction information and balance using FullNode.

### ISSUE THREAD

**Issue by yeahkuang** [tronprotocol/java-tron#4264]
### 1. What did you do?
I built my own FullNode.
But I checked the documentation and found that the FullNode API doesn't have any APIs like https://api.shasta.trongrid.io/v1/contracts/{contractAddress}/transactions and https://api.shasta.trongrid.io/v1/contracts/{contractAddress}/tokens
.
### 2. What did you expect to see?

How do I get TRC20 transaction information and balance using FullNode.

**Comment by vivian-kang** [comment]
Yes, these two interfaces are the exclusive api of Trongrid. 

For TRC20 transaction information, You can get them through scanning block, please refer to the guide: https://developers.tron.network/docs/how-to-determine-address-recharge 

For trc20 balance, please refer to : https://developers.tron.network/docs/trc20-contract-interaction#balanceof

Thanks.

**Comment by yeahkuang** [comment]
Thank you. 🙏
