### ISSUE TITLE
Updated README.

### ISSUE THREAD

**Issue by Balance2020Happiness2021** [tronprotocol/java-tron#4274]
Updated README.

_Originally posted by @cowtowncoder in https://github.com/FasterXML/jackson/issues/99#issuecomment-1006840206_

**Comment by vivian-kang** [comment]
Thanks for your information. Would you please describe the issue in detail?
If you mean to update the jackson lib, team will update you here if there is any plan for this. Thanks.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
