### ISSUE TITLE
Transaction cache loading consumes too much time

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/java-tron#4281]
### 1. What did you do?
I start the node with the official suggested machine configuration (16cores, 32G, SSD) and the provided startup script.
It takes a long time to start syncing blocks each time.
Through analysis, it is found that transaction cache loading consumes too much time

### 2. What did you expect to see?
I expect blocks to be synced within a very short time after the node is up.

### 3. What did you see instead?
It takes too long to start the node, sometimes close to a minute.

**Comment by Omo-Coc** [comment]
I think it has nothing to do with hardware configration, beacuse sometimes my fullnode need 10 min
