### ISSUE TITLE
Can the community documentation be optimized?

### ISSUE THREAD

**Issue by forfreeday** [tronprotocol/java-tron#4282]
### 1. What did you do?

I looked at the community contribution document and found it a bit complicated to read, I would like to optimize the community contribution document.

[CONTRIBUTING.md](https://github.com/tronprotocol/java-tron/blob/develop/CONTRIBUTING.md)

### 2. What did you expect to see?
Expect to see a simpler and clearer community contribution document

### 3. What did you see instead?
The community documentation is a bit complicated

**Comment by kunlunxuejue11** [comment]
You got the point～

**Comment by wubin01** [comment]
+1
