### ISSUE TITLE
Support metrics and alerting  with  open-source monitoring solution

### ISSUE THREAD

**Issue by halibobo1205** [tronprotocol/java-tron#4284]
### 1. What did you do?

 
I want to use grafana to monitor node metrics.
 
### 2. What did you expect to see?

Hope there is a exporter like prometheus ,or some.

### 3. What did you see instead?

Find a  not compatible http interface ：/monitor/getstatsinfo.

**Comment by Omo-Coc** [comment]
I kind of agree with these ideas.

**Comment by halibobo1205** [comment]
https://github.com/tronprotocol/tips/issues/369
