### ISSUE TITLE
Asset data structures have no size limit

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/java-tron#4286]
### 1. What did you do?
When reading the asset transfer code, I found the following problems. The asset data structure is a map. When performing asset operations, I found that the map has no size limit, and there are certain loopholes in the design.
 `message Account {`
   `...`
     ` map<string, int64> asset = 6;`
     `map<string, int64> assetV2 = 56;`
     `...`
`}`

### 2. What did you expect to see?
Expect the map to have a size limit, or use other data structures.

### 3. What did you see instead?
The map has no size limit, it may expand infinitely, and there are hidden dangers.

**Comment by joker-gdb** [comment]
This is a good suggestion, kindly remind you to  submit a TIP issue to describe your solution in detail.
