### ISSUE TITLE
Please change the default value of trx.reference.block and supportConstant

### ISSUE THREAD

**Issue by L-Reid** [tronprotocol/java-tron#4321]
### 1. What did you do?

Would you please modify the default value of below two configurations , thanks.
trx.reference.block = head
supportConstant = false

### 2. What did you expect to see?
The default value should be:
trx.reference.block = solid
supportConstant = true

Then transactions can execute successfully. 
Users can query smart contract data.

### 3. What did you see instead?

Some transactions whose reference block is "head" executed failed, and the error is TAPOS_ERROR.
User cannot do the query operation on smart contract, because  the node does not supportConstant.

**Comment by sunflower-sun** [comment]
Good point. That will avoid some troubles for users.

**Comment by halibobo1205** [comment]
`trx.reference.block` can set the default value to `solid` to avoid TaPos error.  `supportConstant `remains unchanged, turn on by yourself if needed, when turned on, slow block synchronization may occur.

**Comment by PisethChhang** [comment]
989255

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
