### ISSUE TITLE
The API of Lite fullnode is closed

### ISSUE THREAD

**Issue by EgbertWu** [tronprotocol/java-tron#4324]
### 1. What did you do?

we have a lite node. updated the latest  version  fullnode.jar.  but the api is closed.
the logs prompt "UNAVALABLE: this API is closed because this node is a lite fullnode"
![image](https://user-images.githubusercontent.com/25194431/158944029-c654561c-2d17-4bbb-8d2d-85b0e523cc38.png)

### 2. What did you expect to see?

how can i used the api function or turn the lite fullnode into a fullnode?

**Comment by sunflower-sun** [comment]
Database should be changed to fullnode's

**Comment by forfreeday** [comment]
lite fullnode does not enable the query function by default, you need to change the configuration file config.conf: openHistoryQueryWhenLiteFN = true

**Comment by sunflower-sun** [comment]
Oh, another update to my reply, and I learned again.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
