### ISSUE TITLE
Fetch all transactions of a certain address

### ISSUE THREAD

**Issue by SergiFortunejack** [tronprotocol/java-tron#4328]
### 1. What did you do?

Im trying to fetch all transactions of a certain address, which has more than 28k transactions.
I have tried to use `walletextension/gettransactionsfromthis` and `walletextension/gettransactionstothis` but those are no longer available and also limited to 10k:
Parameter offset: The start index of the transactions, must not greater then 10000
Parameter limit: The number of transactions expected to return, maximum 50, offset+limit must smaller than 10000
### 2. What did you expect to see?
I am looking for a way to get all transactions of a certain address.

**Comment by halibobo1205** [comment]
@SergiFortunejack , `java-tron` does not provide this, you can get all transactions of a certain address through `tronscan`, such as https://tronscan.org/#/address/TGJR6xtPgSgqcsD3hJFgKg4spXiKBeb6Ej

**Comment by SergiFortunejack** [comment]
@halibobo1205 , Thanks for the answer. I tried `tronscan` already, but unfortunately only the first 10,000 transactions are available there. 
I have more than 28k transactions.

**Comment by L-Reid** [comment]
@SergiFortunejack, I got all transactions of an account through trongrid API before, you can have a try:  /accounts/{address}/transactions

**Comment by L-Reid** [comment]
To get more transactions by using "fingerprint" param.  You can get more detailed description in Tron document.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
