### ISSUE TITLE
Cant figure out how to create an account 

### ISSUE THREAD

**Issue by gwumkt** [tronprotocol/java-tron#4332]
Hi there,
I just cant understand what im doing wrong here..
im using: https://tronprotocol.github.io/documentation-en/api/http/ for reff
﻿
<img width="1576" alt="Screenshot 2022-03-27 at 2 45 45 PM" src="https://user-images.githubusercontent.com/28900951/160280016-4e513aa6-2903-4b15-8d81-0953d222ca53.png">

after i created an address, i assume i need to create account..
because in the end i want to be able to check my balance and send funds out..

if i just use the address:
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/28900951/160280125-a82f7d9a-d254-4df5-84d6-e0ef622ac9dd.png">

or if i use that tool:
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/28900951/160280148-4dc4d635-ee56-4cf2-8563-f25ca0f9d6c2.png">

<img width="1578" alt="image" src="https://user-images.githubusercontent.com/28900951/160280175-0c6957aa-bfd9-4df0-8e77-1d1da11f8008.png">

Thanks!

**Comment by m-o-m12** [comment]
The parameters are incorrect, there are two required params, one is owner account which has already activated, the other is the new created address which is waiting to be activated.

**Comment by gwumkt** [comment]
how do i activate an account?

**Comment by joker-gdb** [comment]
@gwumkt Accounts can be activated by the following two ways:

- Send any amount of TRX or TRC-10 tokens from an existing account to the new account;
- Call Java-tron's `wallet/createaccount api` to create a transaction from an existing account, then sign the transaction, and broadcast it to the TRON network.


I saw it in deveoper-hub doc, hope it helps you!

**Comment by stolosgroup** [comment]
I just fail to understand the process..

1. i created address with generaetaddress
2. i sent there usdt + tron

now what?

i tried to send and im getting err
<img width="1376" alt="Screenshot 2022-03-28 at 11 17 36 PM" src="https://user-images.githubusercontent.com/86804292/160480365-a3c716d0-b3b3-40d3-9d60-f6ba6f942198.png">
i tried with all the options here aswell: https://tronscan.org/#/tools/tron-convert-tool

also im getting not found for many other endpoints
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/86804292/160480495-186e49dd-0a7a-4d5d-b874-6296f632a903.png">

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/86804292/160480624-ed9405dd-9fe8-4540-9784-6be5ac9073de.png">

This whole api drives me crazy :/

**Comment by gwumkt** [comment]
I just fail to understand the process..

1. i created address with generaetaddress
2. i sent there usdt + tron

now what?

i tried to send and im getting err
<img width="1376" alt="Screenshot 2022-03-28 at 11 17 36 PM" src="https://user-images.githubusercontent.com/86804292/160480365-a3c716d0-b3b3-40d3-9d60-f6ba6f942198.png">
i tried with all the options here aswell: https://tronscan.org/#/tools/tron-convert-tool

also im getting not found for many other endpoints
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/86804292/160480495-186e49dd-0a7a-4d5d-b874-6296f632a903.png">

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/86804292/160480624-ed9405dd-9fe8-4540-9784-6be5ac9073de.png">

This whole api drives me crazy :/

**Comment by m-o-m12** [comment]
I will suggest you to fix the issue from below ways:
1. For 404 error, please check the node's ip and http port. 
2. For account address: there are two formats, one is Hex, the other is base58, beginning with "T" is the base58 format address. **Please do not use base64.**
3. Generating CURL request through "POST"

**Comment by gwumkt** [comment]
1. what do you mean i am using the right ip.. i just hide it here on the image.. but you can see that the first req is working..
2.  but on the first pic i am using the one starts with T
3. ?

**Comment by m-o-m12** [comment]
Your address is not the base58 format, even though it is begin with T.  Maybe it is base64 format.
BTW, before using your node's api,  you can test TRON http api with shasta testnet.

**Comment by gwumkt** [comment]
So how do i conert the address i got on generateaddress to base58

**Comment by m-o-m12** [comment]
I got different result items with you when calling wallet/generateaddress api.  It returns hex format address, base58 format address and privatekey.   You can do a test on shasta testnet : https://api.shasta.trongrid.io/

**Comment by vivian-kang** [comment]
Hi @gwumkt , what's the java-tron version of your node.

**Comment by gwumkt** [comment]
Supposed to be the latest one.. how can i check?

**Comment by m-o-m12** [comment]
You can get the node info from log. Restart the node, and you can find the version info.

**Comment by gwumkt** [comment]
how to i restart the node? ans where are the logs?

**Comment by gwumkt** [comment]
09:03:06.726 INFO  [main] [app](Args.java:1163) ************************ Code version *************************
09:03:06.727 INFO  [main] [app](Args.java:1164) Code version : 4.4.4
09:03:06.727 INFO  [main] [app](Args.java:1165) Version code: 16676
09:03:06.727 INFO  [main] [app](Args.java:1166) ************************ DB config *************************
09:03:06.727 INFO  [main] [app](Args.java:1167) DB version : 2
09:03:06.727 INFO  [main] [app](Args.java:1168) DB engine : LEVELDB
09:03:06.727 INFO  [main] [app](Args.java:1169) ***************************************************************

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by Vadimkristalov** [comment]
Привет!!!  Пожалуйста помогите мне активировать адрес кошелька в Байбите🙏🏻🙏🏻🙏🏻

**Comment by 0921917916** [comment]
> how do i activate an account?(Tonke:TKhqFE97GvUDBDcHkeULfCz8DGTUxxas3e) $ chuyển đúng loại Tiền ảo vào ví hoặc Quét mã QR USDTC (TRC20) 
LỆNH GIAO DỊCH 200 MÃ QR 👇 [Screenshot_2024-12-04-09-54-48-30](https://github.com/user-attachments/assets/01ac2571-dd32-419f-8bdd-6c4878f39495)
![Screenshot_2024-12-04-09-54-48-30](https://github.com/user-attachments/assets/76bdd92c-a54d-4467-b914-95c3d5129479)
