### ISSUE TITLE
ERROR [pool-50-thread-1] [DB](Manager.java:1112) Tapos failed, different block hash

### ISSUE THREAD

**Issue by gitloverr** [tronprotocol/java-tron#4333]
hi everyone,

My full node stayed on the block #39269000 . I upgraded the node from 4.4.3 to 4.4.4 but the problem continues.

there is this error in logs:

`
size: 11, start block: Num:39269000,ID:0000000002573288cdee4c44e14695b6ace8da13b1c0f7ed4720c5f3b8cdd9cf, end block Num:39271000,ID:0000000002573a58442d23602ed61cecc48a13ea1e781a3e2adff36f8110e265
17:51:37.369 INFO  [pool-50-thread-1] [DB](Manager.java:1003) Block num: 39269001, re-push-size: 0, pending-size: 0, block-tx-size: 88, verify-tx-size: 88
17:51:37.541 INFO  [pool-50-thread-1] [DB](Manager.java:648) Tapos failed, different block hash, 12935, 5f916f6699ec0bac , recent block 184858465a2f60a6, solid block Num:39268982,ID:00000000025732760dd4a89f085aa48569c8ff56dba0738702953220a57b6e67 head block Num:39269000,ID:0000000002573288cdee4c44e14695b6ace8da13b1c0f7ed4720c5f3b8cdd9cf
17:51:37.542 ERROR [pool-50-thread-1] [DB](Manager.java:1112) Tapos failed, different block hash, 12935, 5f916f6699ec0bac , recent block 184858465a2f60a6, solid block Num:39268982,ID:00000000025732760dd4a89f085aa48569c8ff56dba0738702953220a57b6e67 head block Num:39269000,ID:0000000002573288cdee4c44e14695b6ace8da13b1c0f7ed4720c5f3b8cdd9cf
org.tron.core.exception.TaposException: Tapos failed, different block hash, 12935, 5f916f6699ec0bac , recent block 184858465a2f60a6, solid block Num:39268982,ID:00000000025732760dd4a89f085aa48569c8ff56dba0738702953220a57b6e67 head block Num:39269000,ID:0000000002573288cdee4c44e14695b6ace8da13b1c0f7ed4720c5f3b8cdd9cf
17:51:37.544 ERROR [pool-50-thread-1] [net](TronNetDelegate.java:237) Process block failed, Num:39269001,ID:0000000002573289f73a4b3158d904ad61d6764c87bf864a2e102652aed94666, reason: Tapos failed, different block hash, 12935, 5f916f6699ec0bac , recent block 184858465a2f60a6, solid block Num:39268982,ID:00000000025732760dd4a89f085aa48569c8ff56dba0738702953220a57b6e67 head block Num:39269000,ID:0000000002573288cdee4c44e14695b6ace8da13b1c0f7ed4720c5f3b8cdd9cf.
17:51:37.545 ERROR [pool-50-thread-1] [net](SyncService.java:270) Process sync block Num:39269001,ID:0000000002573289f73a4b3158d904ad61d6764c87bf864a2e102652aed94666 failed.
org.tron.core.exception.P2pException: org.tron.core.exception.TaposException: Tapos failed, different block hash, 12935, 5f916f6699ec0bac , recent block 184858465a2f60a6, solid block Num:39268982,ID:00000000025732760dd4a89f085aa48569c8ff56dba0738702953220a57b6e67 head block Num:39269000,ID:0000000002573288cdee4c44e14695b6ace8da13b1c0f7ed4720c5f3b8cdd9cf
Caused by: org.tron.core.exception.TaposException: Tapos failed, different block hash, 12935, 5f916f6699ec0bac , recent block 184858465a2f60a6, solid block Num:39268982,ID:00000000025732760dd4a89f085aa48569c8ff56dba0738702953220a57b6e67 head block Num:39269000,ID:0000000002573288cdee4c44e14695b6ace8da13b1c0f7ed4720c5f3b8cdd9cf
size: 11, start block: Num:39269000,ID:0000000002573288cdee4c44e14695b6ace8da13b1c0f7ed4720c5f3b8cdd9cf, end block Num:39271000,ID:0000000002573a58442d23602ed61cecc48a13ea1e781a3e2adff36f8110e265
`

how can I solve this?

thank you

**Comment by wubin01** [comment]
@vivian-kang  Need to confirm a question, is the transaction created through this node? It may be caused by the block not being synchronized

**Comment by gitloverr** [comment]
hi again, I got the whole data from snapshot this error is solved.
