### ISSUE TITLE
Error when building a private chain

### ISSUE THREAD

**Issue by Geapefurit** [tronprotocol/java-tron#4345]
I build private chain.fllow https://cn.developers.tron.network/docs/tron-private-chain
But wrong,when I start supernode(it`s also first node).
![image](https://user-images.githubusercontent.com/25075249/163954863-96777628-4426-43a6-b607-7fca8fbde81f.png)

consult！

**Comment by forfreeday** [comment]
@Geapefurit 
What are your start-up parameters and can you give the full start-up command?

**Comment by Geapefurit** [comment]
@forfreeday 
I have successfully built it,using the configuration file of v-4.4.4.There are two reasons that cause me go wrong,one is the configuration in tutorial file have expired,the other is I just put my key in config.like this
"
genesis.block = {
  # Reserve balance
  assets = [
    {
      accountName = "Zion"
      accountType = "AssetIssue"
      address = "TSVW4axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      balance = "95000000000000000"
    }
  ]

  witnesses = [
    {
      address: TLQmawxxxxxxxxxxxxxxxx,
      url = "http://tronstudio.com",
      voteCount = 10000
    }
  ]

  timestamp = "0" #2017-8-26 12:00:00

  parentHash = "0xe58f33f9baf9305dc6fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
"

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
