### ISSUE TITLE
Git ssh in start.sh

### ISSUE THREAD

**Issue by aghamir** [tronprotocol/java-tron#4371]
### 1. What did you do?
Run `./start.sh --release --run`

### 2. What did you expect to see?
Run the fullnode with built jar file

### 3. What did you see instead?
Error because git@github.com: Permission denied (publickey).

It seems the script write with git ssh instead of https. Therefore, other people who doesn't add the ssh key to this repo cannot use this script

**Comment by forfreeday** [comment]
HTTPS support can be added

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
