### ISSUE TITLE
I have a few questions that need to be answered

### ISSUE THREAD

**Issue by wuaidajiejie** [tronprotocol/java-tron#4374]
1. does SR produce the blocks first and then pack the transactions into the blocks?

2. does SR have the right to change the block hash?

3. can SR pack specified transactions or ignore specified transactions?

**Comment by m-o-m12** [comment]
I looked into the java-tron code before. SR will not pick and ignore specific transactions. when it is time for one SR's turn to produce block, it will pack the transactions in pending pool into a block, and the transaction hash will be generated according to the block's data. SR of course has no right to modify the block hash.

**Comment by wuaidajiejie** [comment]
> 

Thank you!
