### ISSUE TITLE
LiteFullNodeTool.jar not included in release artifacts

### ISSUE THREAD

**Issue by wkoszycki** [tronprotocol/java-tron#4413]
### 1. What did you do?
I would like to use LiteFullNodeTool.jar to perform splits / merge of data 

### 2. What did you expect to see?
Tool should be included into released artifacts 

### 3. What did you see instead?
I need to build tool myself in order to use it

**Comment by forfreeday** [comment]
LiteFullNodeTool.jar is available via build, which requires no complex operations and only one build.

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/

**Comment by joeky888** [comment]
For anyone ended up here, they used to provide [lite fullnode daily snapshots](https://developers.tron.network/docs/main-net-database-snapshots) but was removed some time this year in favor of upcoming GreatVoyage-V4.5.0. If you google `LiteFullNode_output-directory.tgz` you can find the [last backup here](http://47.89.188.118/backup20210806/). I haven't tried it so use it at your own risk.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
