### ISSUE TITLE
how the net can it work when ocurre  state of LOW_PARTICIPATION 

### ISSUE THREAD

**Issue by lyy4j** [tronprotocol/java-tron#4417]
i have a doubt:
In the main net, the config value of minParticipationRate is 15. 
How about the consensus can  continued working in this case:
There are Symmetric network partitioning separating the net into two part, one part are num of 5, the other part are num of 22 for a period of time。And after 4 round（1 round per num of  27 block produce）consensus,  the accumulative total amount of  un filled slots count must be more than 20 for each node, which mean each node will change state into LOW_PARTICIPATION。
before a node producing bock, it will judge it state is OK ，which will cause it can't produce a block any more for each node?

**Comment by lyy4j** [comment]
@h4ck3rm1k3 @andelf @seanrobbins ，who can answer my doubt please, ths!

**Comment by forfreeday** [comment]
The node can still continue to operate, as long as the 'participation' does not drop to the set value of 15%, and the 'participation' will gradually recover when the node is restored

**Comment by forfreeday** [comment]
If the node's minParticipationRate is not 15% above the set value, it can continue to produce blocks.
If it falls below minParticipationRate, the node will stop producing blocks.

**Comment by lyy4j** [comment]
> If it falls below minParticipationRated


> If the node's minParticipationRate is not 15% above the set value, it can continue to produce blocks. If it falls below minParticipationRate, the node will stop producing blocks.

I don't know you understand the case i descripte or not, all you answer is  the condtion of   falling below minParticipationRate.But i have clarified  the Symmetric network partitioning condtion above i  put forward  must cause the minParticipationRate greater than 15%, right? And how the block produce in this conditon?

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/

**Comment by anypathrouter** [comment]
If it is greater than 15%, you need to adjust the minParticipation of all nodes to 0, and wait for all nodes to produce blocks before minParticipation will be restored

**Comment by 11111961abc** [comment]
79136741676 все переговоры на русском.Сергей Николаевич

пт, 17 июн. 2022 г., 12:22 anypathrouter ***@***.***>:

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by stabilaprotocol1** [comment]
In the case participation rate dropped and the nodes can not produce blocks, is  minParticipation=0 enough to restore?

**Comment by forfreeday** [comment]
@stabilaprotocol1 
Yes, minParticipation is a value that controls the block-producing node's participation. If you don't need to care whether the block-producing node is producing blocks properly, you can set minParticipation=0
