### ISSUE TITLE
How do I do the equivalent of Geth.debug_traceTransaction

### ISSUE THREAD

**Issue by diwu1989** [tronprotocol/java-tron#4422]
How do I do the equivalent of Geth debug trace?
https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracetransaction

Specifically, how do I do a call tracing of a transaction?

**Comment by lakfly** [comment]
> How do I do the equivalent of Geth debug trace? https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracetransaction
> 
> Specifically, how do I do a call tracing of a transaction?

As far as I know, there is no function like Geth.debug_traceTransaction on TRON. But it is possible to go through the interface to check if the transaction was successful and to estimate the energy needed for the transaction.

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/

**Comment by okwapa210** [comment]
TRON does not support debugging of the historical transaction, only support obtaining the receipt of the historical transaction, but if TRON will support the debug_traceTransaction, it should be easy！

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
