### ISSUE TITLE
Get Error when deploy contracts to private chain using tronbox

### ISSUE THREAD

**Issue by chaonengs** [tronprotocol/java-tron#4426]
ERROR: Contract Vault has not been deployed on the network.
For more details, check the transaction at:
http://127.0.0.1:16667/wallet/gettransactionbyid?value=9ff6d269945103f96a3be9aa7b8218267c3136172dc07914d78beb29463400e2
If the transaction above is empty, most likely, your address had no bandwidth/energy to deploy the contract.

{"ret":[{"contractRet":"ILLEGAL_OPERATION"}],"signature":["af39abe3d83938b61cdb0bfbb98efc6718f50c9b5295f9640d93e672a4aab75c002bbb31603e200d42e9873fe7a7d3a54dc91d83fb15df7a97e17cf6ad528fc401"],"txID":"096b543e7d23a01c7082fa05e92f5ecd45ac71ad447343a7c12cb9c1a85d59a6","contract_address":"416baa955a4926eb0b3f257b2cc8130d8988dec2c3","raw_data":{"contract":[{"parameter":{"value":{"owner_address":"4188bec01a03616c1dcaa13f8e14c6fe45fbeff2b2","new_contract":...

any idea?

**Comment by joker-gdb** [comment]
I think it is because the on-chain parameters of your private chain are different from those of the main network, and you need to activate it through some proposals~

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
