### ISSUE TITLE
Cannot send TRC20 token in SHASTA testate

### ISSUE THREAD

**Issue by xfishernet** [tronprotocol/java-tron#4429]
Hi all! A use this example: https://andelf.gitbook.io/tron/tron-by-example/transfer-trc20

but I always get an error: 

error: 'CONTRACT_VALIDATE_ERROR',
message: 'Contract validate error : account does not exist'

this is my test token: https://shasta.tronscan.org/#/token20/TCoEUJpjX8FKDRcJsb7hKMy7MraAjTHq8F

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
