### ISSUE TITLE
[Bounty]AccountStore.class Singleton Thread Safe Issue

### ISSUE THREAD

**Issue by L--7** [tronprotocol/java-tron#443]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Please answer these questions before submitting your issue. Thanks!

```java
private static AccountStore instance;

  /**
   * create fun.
   *
   * @param dbName the name of database
   */
  public static AccountStore create(String dbName) {
    if (instance == null) {
      synchronized (AccountStore.class) {
        if (instance == null) {
          instance = new AccountStore(dbName);
        }
      }
    }
    return instance;
  }
```

This is no thread safe singleton

**Comment by Yrp** [comment]
@L--7 Yes, you are right. We will use spring's class initialization to ensure singletons instead of this way

**Comment by Yrp** [comment]
```java
private volatile static Singleton instance；
```
is an another solution.

**Comment by L--7** [comment]
yes, your code have many this issue. And like " String s; if(s == null || "".equals(s))", you can use  "StringUtils" of Apache.

**Comment by L--7** [comment]
Your code quality is bad。

**Comment by Rovak** [comment]
@L--7 there is room for improvement, but could you be more specific about which parts of the code you believe are low quality so they can be improved?

**Comment by L--7** [comment]
String ， List or Map  maybe use the apache common utils.And the useless annotations，the unsafe singleton。。。。。 I just check a bit of code。

**Comment by Rovak** [comment]
* Which annotations are you referring to? 
* The `Create` method doesn't need to statically store the `instance` that it just created. It should be made a factory method. The `db.Manager` is the only class that calls the `Create` method once so there aren't any thread safety issues. I'm more concerned that subsequent calls to `Create` with a different `dbName` value returns the first created singleton instance instead of a `AccountStore` with the given `dbName`.
* Replacing code with Apache Commons can simplify code in most cases but i don't consider `if (s == null || "".equals(s))` to necessarily be bad, there are lots of different ways to do the same thing without affecting code quality.

**Comment by L--7** [comment]
1.BlockStore.class  create method. bad annotations.
2.“The db.Manager is the only class that calls the Create method once so there aren't any thread safety issues.”if call once and one thread,remove synchronized.

**Comment by L--7** [comment]
Many Singleton is like this----unsafe   double check

**Comment by L--7** [comment]
`  public static BlockStore create(String dbName) {
    if (instance == null) {
      synchronized (BlockStore.class) {
        if (instance == null) {
          **logger.info("adafasdfasdfasdfasdf");**
          instance = new BlockStore(dbName);
        }
      }
    }
    return instance;
  }`

**Comment by L--7** [comment]
private static WitnessStore instance;

  public static void destory() {
    instance = null;
  }

  /**
   * create fun.
   *
   * @param dbName the name of database
   */
  public static WitnessStore create(String dbName) {
    if (instance == null) {
      synchronized (UtxoStore.class) {
        if (instance == null) {
          instance = new WitnessStore(dbName);
        }
      }
    }
    return instance;
  }
too many  like this。。。。。

**Comment by zhaohong** [comment]
@L--7  thanks for your feedback.  The tron code are Iterated quickly in past two months, so some design are unnecessary.   We'll gradually improve this when we have enough time and welcome your submission of  new pull request.

**Comment by Rovak** [comment]
this has been fixed in `develop` branch

**Comment by marcusyanghe** [comment]
Hi, @L--7 ,
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang
