### ISSUE TITLE
[Bounty] Cannot login in website

### ISSUE THREAD

**Issue by bloc4ain** [tronprotocol/java-tron#444]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I tried to login into https://tron.network

2. What did you expect to see?
My account page

3. What did you see instead?
CORS error for Captcha script

![image](https://user-images.githubusercontent.com/6628773/38778604-cd45288a-40c4-11e8-90c3-f73edbdf3ad3.png)

I am using Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by bloc4ain** [comment]
Issue resolved

**Comment by tronmarcus** [comment]
Hi, @bloc4ain Alex,
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang
