### ISSUE TITLE
布隆过滤器有点问题

### ISSUE THREAD

**Issue by hxfjsw** [tronprotocol/java-tron#4447]
### 1. What did you do?

```
{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "address": "0x6328314b34b5b6f3b858af753e4d382a1a8efdfe",
            "fromBlock": "0x2666bbe",
            "toBlock": "0x2666bbe",
            "topics": [
                [
                    "0x0f65888c138565bbf00092521aa48930ce6ffd250de638739b75dd80b9ebca46",
                    "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0"
                ]
            ]
        }
    ],
    "id": 74
}
```

### 2. What did you expect to see?
布隆过滤器有点问题，加了address字段之后 无法正确获得log

### 3. What did you see instead?
临时解决方案：
framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java
```
//    List<Long> possibleBlockList = logBlockQuery.getPossibleBlock();
 for(long i=logFilterWrapper.getFromBlock() ;i<=logFilterWrapper.getToBlock();i++){
      possibleBlockList.add(i);
 }
```
关闭布隆过滤器，所有区块都进行检索

**Comment by zhangwenhua-tron** [comment]
Hi, can you provide more information, such as the request uri, the config about the jsonrpc, on the mainnet or nile, the response and the expected response.

**Comment by hxfjsw** [comment]
```
curl --location --request POST 'http://3.84.131.80:50545/jsonrpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [
        {
            "address": "0x6328314b34b5b6f3b858af753e4d382a1a8efdfe",
            "fromBlock": "0x2666bbe",
            "toBlock": "0x2666bbe",
            "topics": [
                [
                    "0x0f65888c138565bbf00092521aa48930ce6ffd250de638739b75dd80b9ebca46",
                    "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0"
                ]
            ]
        }
    ],
    "id": 74
}'
```
on mainnet

**Comment by 317787106** [comment]
we replace your url with offical jsonrpc url https://api.oregon.trongrid.io/jsonrpc, and get the result: 
`{
    "jsonrpc": "2.0",
    "id": 74,
    "result": [
        {
            "address": "0x6328314b34b5b6f3b858af753e4d382a1a8efdfe",
            "blockHash": "0x0000000002666bbe349499eadfa16a969828843c18806d7e83f515028a90507a",
            "blockNumber": "0x2666bbe",
            "data": "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000008547278517565656e000000000000000000000000000000000000000000000000",
            "logIndex": "0xf",
            "removed": false,
            "topics": [
                "0x0f65888c138565bbf00092521aa48930ce6ffd250de638739b75dd80b9ebca46",
                "0x0000000000000000000000000cbcf8ddc47162479e15480c96e84b2909e101dd",
                "0x0000000000000000000000000000000000000000000000000000000000000012",
                "0x000000000000000000000000000000000000000000000000000000000000a1d9"
            ],
            "transactionHash": "0x2f3e6d124c53ca6cb682df4be74daf4dbe6d9d322a2583694d25dcb215e18b3c",
            "transactionIndex": "0x1a"
        }
    ]
}`

this block number is mainet 40266686, and we can check the result with trongrid : https://api.trongrid.io/v1/blocks/40266686/events. 
I find the only one result which matched your request in second page: https://api.trongrid.io/v1/blocks/40266686/events?fingerprint=9mPzvhwtq8uTG3KkJa6hTebJWTQNwvnDMgv7MhKRVDAcuU9MVj87ZU4a1GQyWZwHMH4EBZDVRvLYtRe7qd8APKJQxMb8aVNUF.  

The offical jsonurl api will open some times later, but please checkout your parameter jsonrpc.httpFullNodeEnable in config.conf  is true when your Fullnode dealwith block  40266686.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
