### ISSUE TITLE
Nodes fail to synchronize

### ISSUE THREAD

**Issue by 545011916** [tronprotocol/java-tron#4448]
### 1. What did you do?

Nodes fail to synchronize

### 2. What did you expect to see?
Normal Node synchronization

### 3. What did you see instead?

getnodeinfo:
{
	"cheatWitnessInfoMap": {},
	"totalFlow": 45806,
	"activeConnectCount": 6,
	"currentConnectCount": 7,
	"beginSyncNum": 41568906,
	"configNodeInfo": {
		"maxTimeRatio": 300.0,
		"backupListenPort": 10001,
		"codeVersion": "4.4.6",
		"minParticipationRate": 15,
		"dbVersion": 2,
		"versionNum": "16685",
		"passiveNodeSize": 0,
		"supportConstant": true,
		"activeNodeSize": 0,
		"minTimeRatio": 0.0,
		"allowCreationOfContracts": 0,
		"allowAdaptiveEnergy": 0,
		"discoverEnable": true,
		"sameIpMaxConnectCount": 2,
		"sendNodeSize": 0,
		"p2pVersion": "11111",
		"backupPriority": 8,
		"listenPort": 18888,
		"maxConnectCount": 30,
		"backupMemberSize": 0
	},
	"block": "Num:41568906,ID:00000000027a4a8abeb1f19be2966f57d341968d7a1fc30c529f7c4fd1c851bf",
	"passiveConnectCount": 1,
	"solidityBlock": "Num:41568888,ID:00000000027a4a786813244bdaa740453177264bc2e1c94942a8f218a8dfa4ac",
	"peerList": [{
		"syncToFetchSizePeekNum": -1,
		"headBlockTimeWeBothHave": 0,
		"unFetchSynNum": 25225296,
		"syncBlockRequestedSize": 0,
		"needSyncFromPeer": false,
		"score": 224,
		"needSyncFromUs": true,
		"lastBlockUpdateTime": 1655324139763,
		"blockInPorcSize": 0,
		"connectTime": 1655324139788,
		"lastSyncBlock": "Num:16343610,ID:0000000000f9623ae51a77d92144368e28be3ac96deb8de8a4c2aba16f395f6e",
		"host": "18.162.52.8",
		"headBlockWeBothHave": "Num:0,ID:0000000000000000000000000000000000000000000000000000000000000000",
		"nodeCount": 94,
		"remainNum": 25225296,
		"avgLatency": 0.0,
		"remoteDisconnectReason": "",
		"syncFlag": false,
		"active": true,
		"inFlow": 618,
		"disconnectTimes": 2,
		"port": 18888,
		"localDisconnectReason": "PING_TIMEOUT",
		"nodeId": "10cbbfbf10898f915d3e3396550d9cd6518b8d9cea40421058f8782eab84b3b62cdac6280d9ddf7c3ae75f0de78eaebb5a5f8484784258c56b9cf5a57e5a105d",
		"syncToFetchSize": 0
	}, {
		"syncToFetchSizePeekNum": -1,
		"headBlockTimeWeBothHave": 0,
		"unFetchSynNum": 8265087,
		"syncBlockRequestedSize": 0,
		"needSyncFromPeer": false,
		"score": 220,
		"needSyncFromUs": true,
		"lastBlockUpdateTime": 1655324143364,
		"blockInPorcSize": 0,
		"connectTime": 1655324143396,
		"lastSyncBlock": "Num:33303819,ID:0000000001fc2d0b564d9f1d7528732357dc66d6428c14a9756901829b7d1634",
		"host": "128.199.159.155",
		"headBlockWeBothHave": "Num:0,ID:0000000000000000000000000000000000000000000000000000000000000000",
		"nodeCount": 94,
		"remainNum": 8265087,
		"avgLatency": 39.0,
		"remoteDisconnectReason": "TIME_OUT",
		"syncFlag": false,
		"active": true,
		"inFlow": 2000,
		"disconnectTimes": 2,
		"port": 18888,
		"localDisconnectReason": "",
		"nodeId": "fa5e6e10e7afdde38f84f4383d433183b94c647dedee8d001bcbcb900d7f693beca84ae145f3b2adfd208ad79cb4a862e3a5f713fc7a8ace54c35c2de8d2a311",
		"syncToFetchSize": 0
	}, {
		"syncToFetchSizePeekNum": -1,
		"headBlockTimeWeBothHave": 0,
		"unFetchSynNum": 1851422,
		"syncBlockRequestedSize": 0,
		"needSyncFromPeer": false,
		"score": 213,
		"needSyncFromUs": true,
		"lastBlockUpdateTime": 1655324154169,
		"blockInPorcSize": 0,
		"connectTime": 1655324154463,
		"lastSyncBlock": "Num:39717484,ID:00000000025e0a6c521f7467ff0c2bdf24adfbd0cf299a3c79c26af85cf1c4bc",
		"host": "173.249.54.119",
		"headBlockWeBothHave": "Num:0,ID:0000000000000000000000000000000000000000000000000000000000000000",
		"nodeCount": 94,
		"remainNum": 1851422,
		"avgLatency": 304.0,
		"remoteDisconnectReason": "TIME_OUT",
		"syncFlag": false,
		"active": true,
		"inFlow": 1003,
		"disconnectTimes": 1,
		"port": 18888,
		"localDisconnectReason": "",
		"nodeId": "3eb287d2e2437ff330733f6238d11d4e927c4fe9593b49708d8034bbfa09e3287d9e721420b93d7c513713f1fd7552b86bcf4885c98138146e849578bfe4e4da",
		"syncToFetchSize": 0
	}, {
		"syncToFetchSizePeekNum": -1,
		"headBlockTimeWeBothHave": 0,
		"unFetchSynNum": 624825,
		"syncBlockRequestedSize": 0,
		"needSyncFromPeer": false,
		"score": 123,
		"needSyncFromUs": true,
		"lastBlockUpdateTime": 1655324162021,
		"blockInPorcSize": 0,
		"connectTime": 1655324156555,
		"lastSyncBlock": "Num:40944081,ID:000000000270c1d1e1cdce65bdf090b9cedc447741bf13983c69e1f7fb0a56d8",
		"host": "18.141.141.135",
		"headBlockWeBothHave": "Num:40940838,ID:000000000270b52647b5c13398c212458e7aad62bfce9280d2a723e23ff4ffa5",
		"nodeCount": 94,
		"remainNum": 624825,
		"avgLatency": 666.0,
		"remoteDisconnectReason": "TIME_OUT",
		"syncFlag": false,
		"active": false,
		"inFlow": 32611,
		"disconnectTimes": 2,
		"port": 18888,
		"localDisconnectReason": "",
		"nodeId": "6cc3ce94dcac585153fd4b31dc0157db9d9ecfdaebccec61cd39f06eb2824dfdac403220a3fe2bf80aeffe501badb5a75c0a42720619f88d55e5a5bf64532c2e",
		"syncToFetchSize": 0
	}, {
		"syncToFetchSizePeekNum": -1,
		"headBlockTimeWeBothHave": 0,
		"unFetchSynNum": 20513253,
		"syncBlockRequestedSize": 0,
		"needSyncFromPeer": false,
		"score": 214,
		"needSyncFromUs": true,
		"lastBlockUpdateTime": 1655324064133,
		"blockInPorcSize": 0,
		"connectTime": 1655324064361,
		"lastSyncBlock": "Num:21055653,ID:00000000014148a599e2c63871430b5445a413249dd886afe2e80a2eba89fd73",
		"host": "65.21.132.184",
		"headBlockWeBothHave": "Num:0,ID:0000000000000000000000000000000000000000000000000000000000000000",
		"nodeCount": 94,
		"remainNum": 20513253,
		"avgLatency": 1747.0,
		"remoteDisconnectReason": "",
		"syncFlag": false,
		"active": true,
		"inFlow": 472,
		"disconnectTimes": 1,
		"port": 18888,
		"localDisconnectReason": "PING_TIMEOUT",
		"nodeId": "224a9abce8d67b580c2025f581da8e6168bb1f1d9d97f3692d63a71fa067460602bfcc01b115d4491a843bced1165d6f60045d7113b1c436896718346604bc1a",
		"syncToFetchSize": 0
	}, {
		"syncToFetchSizePeekNum": -1,
		"headBlockTimeWeBothHave": 0,
		"unFetchSynNum": 25880198,
		"syncBlockRequestedSize": 0,
		"needSyncFromPeer": false,
		"score": 214,
		"needSyncFromUs": true,
		"lastBlockUpdateTime": 1655324109613,
		"blockInPorcSize": 0,
		"connectTime": 1655324075151,
		"lastSyncBlock": "Num:15688708,ID:0000000000ef6404285bfc2340218641890cae47c033425cfce6af015333e8e5",
		"host": "5.9.97.28",
		"headBlockWeBothHave": "Num:15688708,ID:0000000000ef6404285bfc2340218641890cae47c033425cfce6af015333e8e5",
		"nodeCount": 94,
		"remainNum": 25880198,
		"avgLatency": 6192.0,
		"remoteDisconnectReason": "",
		"syncFlag": false,
		"active": true,
		"inFlow": 4622,
		"disconnectTimes": 1,
		"port": 18888,
		"localDisconnectReason": "PING_TIMEOUT",
		"nodeId": "056e401ccb66479e266b920b9bd2d0b586afdddfec2eb366cdfd51b3c2a6beec243b168736b9231edcec1cc106ba051ad858f0c44604a3561df1cb049603b931",
		"syncToFetchSize": 0
	}, {
		"syncToFetchSizePeekNum": -1,
		"headBlockTimeWeBothHave": 0,
		"unFetchSynNum": 2468693,
		"syncBlockRequestedSize": 0,
		"needSyncFromPeer": false,
		"score": 215,
		"needSyncFromUs": true,
		"lastBlockUpdateTime": 1655324150567,
		"blockInPorcSize": 0,
		"connectTime": 1655324150789,
		"lastSyncBlock": "Num:39100213,ID:0000000002549f357126c47acea0f7edd0fecce0161cae91426ae5d1ffe31787",
		"host": "162.55.239.134",
		"headBlockWeBothHave": "Num:0,ID:0000000000000000000000000000000000000000000000000000000000000000",
		"nodeCount": 94,
		"remainNum": 2468693,
		"avgLatency": 12595.0,
		"remoteDisconnectReason": "TIME_OUT",
		"syncFlag": false,
		"active": true,
		"inFlow": 4480,
		"disconnectTimes": 2,
		"port": 18888,
		"localDisconnectReason": "PING_TIMEOUT",
		"nodeId": "ae58575b63e1f9cabb02147e98a85052ef5dfb5c820bde78630cb022a18c8db13cf65e745c60c72d68b56dc1154423843a2476c90055b5085404a2b31ad46212",
		"syncToFetchSize": 0
	}],
	"machineInfo": {
		"javaVersion": "1.8.0_311",
		"deadLockThreadInfoList": [],
		"threadCount": 130,
		"jvmFreeMemory": 22504727248,
		"osName": "Linux 5.10.60-9.al8.x86_64",
		"totalMemory": 32312356864,
		"deadLockThreadCount": 0,
		"processCpuRate": 0.0017827406699904486,
		"cpuRate": 0.0025978507098458293,
		"jvmTotalMemory": 25656426496,
		"freeMemory": 266506240,
		"memoryDescInfoList": [{
			"useSize": 28137152,
			"name": "Code Cache",
			"maxSize": 251658240,
			"useRate": 0.11180699666341146,
			"initSize": 2555904
		}, {
			"useSize": 52896928,
			"name": "Metaspace",
			"maxSize": -1,
			"useRate": 0.969978148002103,
			"initSize": 0
		}, {
			"useSize": 6184336,
			"name": "Compressed Class Space",
			"maxSize": 1073741824,
			"useRate": 0.00575961172580719,
			"initSize": 0
		}, {
			"useSize": 56108008,
			"name": "Par Eden Space",
			"maxSize": 907345920,
			"useRate": 0.06183750514908361,
			"initSize": 134742016
		}, {
			"useSize": 16842752,
			"name": "Par Survivor Space",
			"maxSize": 113377280,
			"useRate": 0.1485549132947977,
			"initSize": 16842752
		}, {
			"useSize": 3078748488,
			"name": "CMS Old Gen",
			"maxSize": 24635703296,
			"useRate": 0.12497100046256378,
			"initSize": 336986112
		}],
		"cpuCount": 16
	}
}

[tron.log](https://github.com/tronprotocol/java-tron/files/8912836/tron.log)

**Comment by wubin01** [comment]
Looking at the log, it should be that the database is damaged, the block with a height of 41568888 is lost. When handshake, the solid block carrying information is 41568888, but the database cannot query this block.

**Comment by 545011916** [comment]
> Looking at the log, it should be that the database is damaged, the block with a height of 41568888 is lost. When handshake, the solid block carrying information is 41568888, but the database cannot query this block.

Do I have to delete the database? How do you do it? Will this require resynchronization of all blocks?

**Comment by hitlxy** [comment]
> > Looking at the log, it should be that the database is damaged, the block with a height of 41568888 is lost. When handshake, the solid block carrying information is 41568888, but the database cannot query this block.
> 
> Do I have to delete the database? How do you do it? Will this require resynchronization of all blocks?

As I know, the only way to solve this issue is to delete the database. You can  use db snapshot to accelerate the sync speed, and the db snapshot can be download here: https://developers.tron.network/docs/main-net-database-snapshots

**Comment by hitlxy** [comment]
I have a question, does not java-tron use atomic operation to write data to disk? if it is atomic write, why does the database corruption occurs？

**Comment by 545011916** [comment]
What is it that  atomic operation to write data to disk，I am starting with the tutorial on the official website.
