### ISSUE TITLE
[Bounty]Blockchain.java not right try catch.

### ISSUE THREAD

**Issue by L--7** [tronprotocol/java-tron#445]
public Blockchain(@Named("block") LevelDbDataSourceImpl blockDB) {
    this.blockDB = blockDB;
    this.lastHash = blockDB.getData(LAST_HASH);

    if (this.lastHash == null) {

      InputStream is = getClass().getClassLoader().getResourceAsStream("genesis.json");
      String json = null;
      try {
        json = new String(ByteStreams.toByteArray(is));
      } catch (IOException e) {
        e.printStackTrace();
      }

      GenesisBlockLoader genesisBlockLoader = JSON.parseObject(json, GenesisBlockLoader.class);

      Iterator iterator = genesisBlockLoader.getTransaction().entrySet().iterator();

if `json = new String(ByteStreams.toByteArray(is));` throw `IOException `,  the json is null. if the code go on, it maybe cause the NullPointerException.

**Comment by Rovak** [comment]
@L--7 make sure you are checking the `develop` branch, the `blockchain.java` and `genesis.json` no longer exist

**Comment by L--7** [comment]
ok thanks.
