### ISSUE TITLE
How can I reduce the storage usage 

### ISSUE THREAD

**Issue by sillygod** [tronprotocol/java-tron#4468]
As the title mentioned, I need a way to reduce storage usage.  In bitcoin, it has a [mechanism to prune node](https://bitcoin.org/en/full-node#reduce-storage) which perfectly massive reduces the storage usage.

Could you please tell me how to get the same thing for the Tron node.

**Comment by m-o-m12** [comment]
Lite fullnode does not store all data. Lit fulllnode is a good choice If its function meet your need.

**Comment by sillygod** [comment]
> Lite fullnode does not store all data. Lit fulllnode is a good choice If its function meet your need.

@m-o-m12 , thanks for the reply. After reading the [tron lite full node documentation](https://tronprotocol.github.io/documentation-en/developers/litefullnode/), I think it works not like the bitcoin's prune node function. If I understand correctly, running the tron lite fullnode will rely on the fullnode's database which means I have to prepare more disk storage for running a litefullnode?!

**Comment by m-o-m12** [comment]
> > Lite fullnode does not store all data. Lit fulllnode is a good choice If its function meet your need.
> 
> @m-o-m12 , thanks for the reply. After reading the [tron lite full node documentation](https://tronprotocol.github.io/documentation-en/developers/litefullnode/), I think it works not like the bitcoin's prune node function. If I understand correctly, running the tron lite fullnode will rely on the fullnode's database which means I have to prepare more disk storage for running a litefullnode?!

You can prepare a temporary large storage to download a fullnode database snapshot and use lite fullnode tool to convert it to a lite fullnode database, then you do not need large storage anymore, just use a relatively small storage to run a lite fullnode. You can also wait for the database snapshot of the light node, I saw on the Tron doc before, the lite full node snapshot will be open on 4.5 version, and java-tron v4.5.1 has already been released just days, may be the lite fullnode snapshot will online soon

**Comment by sillygod** [comment]
> > > Lite fullnode does not store all data. Lit fulllnode is a good choice If its function meet your need.
> > 
> > 
> > @m-o-m12 , thanks for the reply. After reading the [tron lite full node documentation](https://tronprotocol.github.io/documentation-en/developers/litefullnode/), I think it works not like the bitcoin's prune node function. If I understand correctly, running the tron lite fullnode will rely on the fullnode's database which means I have to prepare more disk storage for running a litefullnode?!
> 
> You can prepare a temporary large storage to download a fullnode database snapshot and use lite fullnode tool to convert it to a lite fullnode database, then you do not need large storage anymore, just use a relatively small storage to run a lite fullnode. You can also wait for the database snapshot of the light node, I saw on the Tron doc before, the lite full node snapshot will be open on 4.5 version, and java-tron v4.5.1 has already been released just days, may be the lite fullnode snapshot will online soon

Yes! That's also the current solution in my mind. However, I have one more question. How can I decide which block number to be the first block of the lite fullnode? For example, I want a lite fullnode that has block data starting from one year ago.

**Comment by sillygod** [comment]
> As i know, it has no such function. Lite fullnode only stores the state data needed for startup, but not the historical block data.

hmm,  whatever, thanks for your reply 😄

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
