### ISSUE TITLE
How to solve Travis build error?(attached image)

### ISSUE THREAD

**Issue by AhnSinYong** [tronprotocol/java-tron#450]
I got this error after I made the PR.
![image](https://user-images.githubusercontent.com/2742452/38786330-288c8736-4162-11e8-999c-40a31fd3c6ae.png)

**Comment by zhaohong** [comment]
this seem that  something wrong during  auto deploy the code to beta environment.

**Comment by AhnSinYong** [comment]
The following variable is not set differently from others when the "Encrypted environment variables have been removed for security reasons." is displayed.
Setting environment variables from repository settings
**$ export encrypted_e5855cb9e09c_key = [secure]
$ export encrypted_e5855cb9e09c_iv = [secure]**

**Comment by huzhenyuan** [comment]
Travis settings problem

**Comment by threedayz** [comment]
AhnSinYong님 안녕하세요.
괜찮으시다면 연락한번 해주시면 감사하겠습니다. 10-3338-6888
