### ISSUE TITLE
Potential Refactoring Estimate

### ISSUE THREAD

**Issue by alvintanjianjia** [tronprotocol/java-tron#4500]
**Summary**
I have identified a few classes with refactoring potential along with its estimated time to refactor, specifically TronJsonRpc.java. The estimated time is based on historical commits containing refactoring and the complexity of the involved classes. The class was refactored once on Sep 28, 2021 along with other classes in commit ef38f9a8e2d59d79c0c6662e00ff4630f1023fa0. Given the duration of the last refactoring, could it be possible to improve this class further? I am probably not qualified and experienced enough to point out the exact code needs to be refactored, given my limited knowledge of the project and codebase.

**Urgency**
Low priority. For maintenance of code in the long run.

Hi,
I am currently doing some research on Estimating Time Taken for Software Refactoring. Java-tron is one of my case studies being a highly popular project. Would appreciate your kind feedback on the appropriateness of the estimated time to refactor. 
I am specifically looking at potential for refactoring, such as breaking functions that are too long into shorter functions, or to remove code duplication. Would you agree that there could be some modification to the code to make it better in the listed classes? And if so, is the estimated time appropriate to carry out the improvement? I will be grateful for any help you can provide.

1. TronJsonRpc.java - 4 hours
2. TronJsonRpcImpl.java - 3 hours

Thank you.

Regards,
Alvin

**Comment by zhangwenhua-tron** [comment]
@alvintanjianjia  Hi, thank you for your report.

How did you get the following statistical data? 
> * TronJsonRpc.java - 4 hours
> * TronJsonRpcImpl.java - 3 hours

And for jsonrpc, it is the initial version and we will refactor the codes in the future, such as moving the object classes into specific files, making the structure more clearly, etc. Maybe we can discuss about it.

If you have any questions or ideas, please let us know.

**Comment by alvintanjianjia** [comment]
@zhangwenhua-tron Hello, thank you for replying.

The estimates based on historical commits containing refactoring and the complexity of the involved classes. For example, in commit ef38f9a8e2d59d79c0c6662e00ff4630f1023fa0, I obtained the time between commits as well as the dependency and complexity of TronJsonRpc (lines of code, dependency to other classes, etc) and built a model to predict effort needed to refactor. 

I understand that I am not proposing / suggesting a very concrete refactoring plan, but would you agree that 4 hours is an appropriate time for improving it in the future such as moving the object classes into specific files like you suggested.

Looking forward to your reply.

Regards,
Alvin

**Comment by zhangwenhua-tron** [comment]
@alvintanjianjia 
For just refactoring the codes of TronJsonRpc.java without testing, I think 4 hours may be an appropriate time if you already have an a reasonable plan, and the TronJsonRpcImpl.java may be will cost more time.

Besides, from my opinion, refactoring codes is just a small part of the work, testing is more important and it will also cost more time.

**Comment by alvintanjianjia** [comment]
Hi @zhangwenhua-tron thank you very much for your comments! I definitely agree and respect your opinion regarding the estimates, and your feedback is greatly appreciated in improving my research. I will add in your suggestion of testing on top of refactoring estimates as well.

Once again, thank you very much for your help.
