### ISSUE TITLE
Tron Network withdraw balance broadcast issue

### ISSUE THREAD

**Issue by blockchain-app12** [tronprotocol/java-tron#4503]
Hi Team,
I tried the tron network run in local. My network config -  3 validators peers are running. 
when I am trying to claim the reward balance amount by the withdraw balance API Request , it shows response as broadcast failed, index 0 error.
here by I attached the screenshot. kindly let me know, what the changes have to do for the solution of the issue.

![image](https://user-images.githubusercontent.com/48212011/177094272-c57f32f2-6a2f-4ea6-850b-5ceb9bfa9a6b.png)

**Comment by wubin01** [comment]
Can you tell me how to reproduce the problem, or show me the transaction content you broadcast?

**Comment by blockchain-app12** [comment]
Hi wubin,

Here by I share the transaction content for your reference. kindly let me know what are the details do you want ?

http://IP:PORT/wallet/withdrawbalance
data :-
{
     "owner_address": "owneraddress",
     "visible": true
}

when I try to broadcast these transaction, i'm getting the error of Braodcast transaction -  Index 0, Failed. 
kindly suggest me to resolve this issue.

**Comment by blockchain-app12** [comment]
Hi 
Okay I agreed, but my question is when my broadcasting these transaction , that time the contract was empty. can i know reason for this.

Transaction data :

![image](https://user-images.githubusercontent.com/48212011/178460240-87995a5b-56d5-4c44-85c7-6fed563b0460.png)


Create Transaction data :

{"visible":true,"txID":"fcfc5dca06c81f9a766a1611a79a2e8511dcd143676185ecff32d2c97d114b64","raw_data":{"contract":[{"parameter":{"value":{"owner_address":"address"},"type_url":"type.googleapis.com/protocol.WithdrawBalanceContract"},"type":"WithdrawBalanceContract"}],"ref_block_bytes":"c18f","ref_block_hash":"63b7b775a08137a1","expiration":1657603968000,"timestamp":1657603910694},"raw_data_hex":"0a02c18f220863b7b775a08137a140809895879f305a53080d124f0a34747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e576974686472617742616c616e6365436f6e747261637412170a151c471146752aa6fd186438a0c7a7b8213b783c821770a6d891879f30"}

**Comment by lakfly** [comment]
> Hi Okay I agreed, but my question is when my broadcasting these transaction , that time the contract was empty. can i know reason for this.
> 
> 2. Sign Transaction data :
> 
> ![image](https://user-images.githubusercontent.com/48212011/178460240-87995a5b-56d5-4c44-85c7-6fed563b0460.png)
> 
> 1. Create Transaction data :
> 
> {"visible":true,"txID":"fcfc5dca06c81f9a766a1611a79a2e8511dcd143676185ecff32d2c97d114b64","raw_data":{"contract":[{"parameter":{"value":{"owner_address":"address"},"type_url":"type.googleapis.com/protocol.WithdrawBalanceContract"},"type":"WithdrawBalanceContract"}],"ref_block_bytes":"c18f","ref_block_hash":"63b7b775a08137a1","expiration":1657603968000,"timestamp":1657603910694},"raw_data_hex":"0a02c18f220863b7b775a08137a140809895879f305a53080d124f0a34747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e576974686472617742616c616e6365436f6e747261637412170a151c471146752aa6fd186438a0c7a7b8213b783c821770a6d891879f30"}

If the signed parameter raw_data.contract.parameter.value.owner_address is empty or non-address, raw_data.contract is empty after signing. so you need to check that the signature parameters are correct.
![image](https://user-images.githubusercontent.com/100565897/180122898-c007d732-74c4-48f1-9494-40f01444e1b1.png)

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
