### ISSUE TITLE
solidity tx execute that have a problem “hex string has length 0, want 64 for common.Hash”

### ISSUE THREAD

**Issue by feiyiban** [tronprotocol/java-tron#4504]
i use the tron-ide can work well，but use the interface by abigen report “hex string has length 0, want 64 for common.Hash”

**Comment by Omo-Coc** [comment]
It's best to give your detailed command steps

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
