### ISSUE TITLE
Using fullnode database snapshots, but cant follow the  event plugin filter configurable

### ISSUE THREAD

**Issue by SevenLM361** [tronprotocol/java-tron#4505]
### 1. What did you do?
When i use the main net database snapshots to start the full node, i cant use the event plugin with kafka because the fromblock in the filter configuration is invalid then the event data still sync from the latest.

```
event.subscribe = {
    native = {
      useNativeQueue = false // if true, use native message queue, else use event plugin.
      bindport = 5555 // bind port
      sendqueuelength = 1000 //max length of send queue
    }

    path = "./plugin-kafka-1.0.0.zip"
    server = "my-server:9092"
    dbconfig="" // dbname|username|password
    contractParse = true,
    topics = [
        {
          triggerName = "block"
          enable = true
          topic = "tron_block"
        },
        {
          triggerName = "transaction"
          enable = true
          topic = "tron_transaction"
        },
        {
          triggerName = "contractevent"
          enable = true
          topic = "tron_contract_event"
        }
    ]

    filter = {
       fromblock = "8418290" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
       toblock = "latest" // the value could be "", "latest" or a specified block number as end of the queried range
       contractAddress = [
           "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t" // contract address you want to subscribe, if it's set to "", you will receive contract logs/events with any contract address.
       ]

       contractTopic = [
           "" // contract topic you want to subscribe, if it's set to "", you will receive contract logs/events with any contract topic.
       ]
    }
}
```

```
nohup java -jar FullNode.jar -c main_net_config.conf --es &
```

### 2. What did you expect to see?
I want to subscribe follow my filter configuration config when i use the event plugin with the fullnode database snapshot

**Comment by joker-gdb** [comment]
What is the block height of the database snapshot?  It starts filtering from the lastest of the snapshot unless you start syncing blocks from a database snapshot before 8418290

**Comment by SevenLM361** [comment]
> What is the block height of the database snapshot? It starts filtering from the lastest of the snapshot unless you start syncing blocks from a database snapshot before 8418290

i think the snapshot is latest, u means the fromblock of event filter have to start on the fullnode current height, right? i already start a emty fullnode start on height zero, but now the sync speed is very low, just 1 million blocks a day. Do u have some suggest to improve this progress? Thank for your time.

**Comment by joker-gdb** [comment]
Yes, start on the fullnode current height, the way to improve is to use snapshot data, no other solution. But you need to begin sync from 0, so it seems that there is no solution.

I suggest that event parsing from 0 to the latest height, don't use event-plugin, scan the block directly, and parse the block yourself, this is much faster than sync

**Comment by SevenLM361** [comment]
> parse the block yourself
can u give me a demo or other link for example to learn this method，I've barely touched on the details of full node parsing.

**Comment by joker-gdb** [comment]
> can u give me a demo or other link for example to learn this method, I've barely touched on the details of full node parsing.

@SevenLM361 I found an instruction for parsing transaction records:https://developers.tron.network/docs/exchangewallet-integrate-with-the-tron-network#parse-blocks-to-get-transaction-records,  I think parsing events is similar

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
