### ISSUE TITLE
Tron Network Withdraw balance issue

### ISSUE THREAD

**Issue by blockchain-app12** [tronprotocol/java-tron#4515]
Hi Team,

    I have a query on the withdraw balance procedures  ? I'm running the Private node.
    
    Is there have any time limit or conditions reach for user rewards balance withdraw by using the withdraw balance API ?
    
    kindly suggest me to what the procedures to follow to withdraw the rewards balance from the user.

**Comment by blockchain-app12** [comment]
Hi, I explaining in detail
I am running the Private Tron Nodes in my machine.
1 Master node and 2 Peer Nodes.
All nodes are sync together and blocks are produced.
Individual user vote for the witness and then get reward balance after the certain maintenance time from the Tron.
But I'm trying to claim the withdraw balance for the user by triggering the withdraw balance API, it displays "Other error - Index 0 Failed"
so my question, Is there have any time limit or conditions reach for user rewards balance withdraw by using the withdraw balance API ?

**Comment by joker-gdb** [comment]
There should be a problem with your transaction body, it is better to show the transaction body

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
