### ISSUE TITLE
"This is a witness node,but localWitnesses is null" is this correct behaviour?

### ISSUE THREAD

**Issue by shymi80** [tronprotocol/java-tron#453]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
sudo ./gradlew run -Pwitness=True

2. What did you expect to see?
Running witness node without any warnings, etc.

3. What did you see instead?
I have seen following line when run started:
"07:03:59.219 WARN [o.t.c.c.a.Args] This is a witness node,but localWitnesses is null"
Is this a correct behavior?
I have looked for how and where to set localWitness but I couldn't find some step by step guide how to do this. Can you please explaing how the localWintess should be (if it really should) set, with what and where? Thanks.

**Comment by zhaohong** [comment]
you can set the localwitness in config file .

**Comment by bondibox** [comment]
I've found if you enter your own info in the witnesses block without also setting localwitness it will throw an error. The converse is not true, I can set just localwitness without an error. Is the purpose of the witnesses block to provide a URL for those nodes wishing to run as Super Representative?

**Comment by ibnzUK** [comment]
http://wiki.tron.network/en/latest/start_witness_node.html 
--------- This page does not exist yet.-----------
