### ISSUE TITLE
How get bytecode of the contract created from another contract?

### ISSUE THREAD

**Issue by leonchuk** [tronprotocol/java-tron#4530]
### 1. What did you do?
https://developers.tron.network/reference/wallet-getcontract

### 2. What did you expect to see?
"bytecode" in response for all contracts

----
I'm found another issues with such a question [3066](https://github.com/tronprotocol/java-tron/issues/3066), [2636](https://github.com/tronprotocol/java-tron/issues/2636) both are completed.
But this problem has not yet been solved(

Maybe there is another way to get "bytecode" for all contacts?

**Comment by hitlxy** [comment]
we cannot get the bytecode of a contract which created by other contract. but I know a fullnode api wallet/getcontractinfo which can get the runtime bytecode of a contract.

**Comment by leonchuk** [comment]
> we cannot get the bytecode of a contract which created by other contract. but I know a fullnode api wallet/getcontractinfo which can get the runtime bytecode of a contract.

yes, "runtimecode" can be used instead of "bytecode" in some cases
thanks @hitlxy  i will think about it

---
https://developers.tron.network/reference/getcontractinfo
> Compared with bytecode, runtime bytecode does not contain constructor and constructor parameter information.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
