### ISSUE TITLE
Bug bounty

### ISSUE THREAD

**Issue by akincibor** [tronprotocol/java-tron#4531]
How to report vulnerabilities, I'm trying to contact you via email since may without response from you.

90 days of no response -> public disclosure

**Comment by ethan1844** [comment]
Bug bounty on Hakone coming soon, please send it to support@tron.network first, thanks!

**Comment by ethan1844** [comment]
Hi, what email address did you send to?

**Comment by akincibor** [comment]
I tried all feedback@tron.network press@tron.network service@tron.network

Also I found your bug bounty policy at https://tron.network/findBug which have a link to Hackerone but it is private or ended.

**Comment by ethan1844** [comment]
@akincibo Bug bounty on Hackerone is coming, please send your finding to bounty@tron.network first, thanks!

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by akincibor** [comment]
Thanks, all the vulnerabilities was reported. For HackerOne, it will be a private or public program ? Private programs are not visible to everyone so please invite me too :)

**Comment by ethan1844** [comment]
> Thanks, all the vulnerabilities was reported. For HackerOne, it will be a private or public program ? Private programs are not visible to everyone so please invite me too :)

The HackerOne java-tron bug bounty will be a public program.
