### ISSUE TITLE
FullNode.jar doesn't start without any error message

### ISSUE THREAD

**Issue by krautcat** [tronprotocol/java-tron#4534]
#### System information

java-tron version: ` java -verbose -Xmx24g -XX:+UseConcMarkSweepGC -Djava.library.path=/usr/local/lib/java -jar build/libs/FullNode.jar -c ../main_net_config.conf 2>&1 | tee run.log`
OS & Version: Linux, Debian 11
Commit hash: GreatVoyage-v4.5.1

#### Expected behaviour

Running full node.

#### Actual behaviour

Node doesn't start without any error message.

#### Steps to reproduce the behaviour

Just build and run node.

#### Backtrace

See attachment.[run.log](https://github.com/tronprotocol/java-tron/files/9110766/run.log), [tron.log](https://github.com/tronprotocol/java-tron/files/9112679/tron.log).

**Comment by krautcat** [comment]
Update: it seems, it is again issue with dependencies. Noe with leveldb.

**Comment by halibobo1205** [comment]
Can't load AMD 64-bit .so on a AARCH64-bit platform, java-tron not support arm.

**Comment by krautcat** [comment]
Yes, I've resolved it. Thanks!
