### ISSUE TITLE
What is the deadline of upgrading full node to GreatVoyage-v4.5.1(Tertullian) ?

### ISSUE THREAD

**Issue by pthor11** [tronprotocol/java-tron#4539]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS & Version: Windows/Linux/OSX

**Comment by joker-gdb** [comment]
https://github.com/tronprotocol/tips/issues/436,looks like the voting request will be submitted on August 2nd, you have to complete the upgrade before that time, or you node will stop syncing~

**Comment by pthor11** [comment]
Thank guys!
I've updated the full node to v4.5.1.
