### ISSUE TITLE
number: 42950084 is not found!

### ISSUE THREAD

**Issue by slashramin** [tronprotocol/java-tron#4566]
it is 2 hours I am getting this error:

[qtp2079042829-62] [o.t.c.Wallet](Wallet.java:661) number: 42950084 is not found!

- my node is updated with last version 
- its 2 year I have this node

**Comment by lakfly** [comment]
> it is 2 hours I am getting this error:
> 
> [qtp2079042829-62] o.t.c.Wallet number: 42950084 is not found!
> 
> * my node is updated with last version
> * its 2 year I have this node

Yesterday there was a new proposal for the TRON network that required upgrading the node to the latest version[ 4.5.1. ](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.5.1)

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
