### ISSUE TITLE
How to optimize the query performance of http and json rpc

### ISSUE THREAD

**Issue by SevenLM361** [tronprotocol/java-tron#4567]
### System information

4.5.0
GreatVoyage-v4.4.6-241-g7045f0659
OS & Version: Linux. 16core 128G

### 1. Backgroud

1. I started a query service to extract the full node data and when I opened over 10 threads to extract it, performance dropped. 
2. i didnt found the fullnode have hareware pressure and the jvm is normal.

### 2. What did you expect to see?

How to optimize the query performance of http and json rpc?  
Do u have any configuration to optimize this situation?
how many the default limit? how can i imporve this limit?

**Comment by joker-gdb** [comment]
You can try `node.maxHttpConnectNumber`

**Comment by SevenLM361** [comment]
> You can try `node.maxHttpConnectNumber`

i already set maxHttpConnectNumber to 300，but the qps still only 16.  I think the fullnode limit the request,  right？

Can i adjust this limit？Because the cpu and memory still have space.

**Comment by lakfly** [comment]
> 

You can also adjust the QPS for each API by modifying rate.limiter in the configuration file, which can be found in the [documentation](https://github.com/tronprotocol/java-tron/blob/fcdefd56a9e8f790eee76c1dc64f28444c3deedc/framework/src/main/resources/config.conf#L276)

**Comment by SevenLM361** [comment]
> > 
> 
> You can also adjust the QPS for each API by modifying rate.limiter in the configuration file, which can be found in the [documentation](https://github.com/tronprotocol/java-tron/blob/fcdefd56a9e8f790eee76c1dc64f28444c3deedc/framework/src/main/resources/config.conf#L276)

i cant see all the fullnode api component enum type, Are all interface names based on the hump form，right？

**Comment by lakfly** [comment]
> 

Yes no problem, you only need to set the interface for the one you want to modify.

**Comment by SevenLM361** [comment]
> > 
> 
> Yes no problem, you only need to set the interface for the one you want to modify.

But it seem not working，which the fullnode not follow this configuration.
The jsonrpc api qps still is 15, once the etl task over 3 then it will down to 10.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
