### ISSUE TITLE
Tron testnet FullNode stuck at particular block 

### ISSUE THREAD

**Issue by singhsahilzeeve** [tronprotocol/java-tron#4573]
#### System information

java-tron version: 4.5.1
                            GreatVoyage-v4.4.6-257-ge06abd15c
                            16944
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
I am trying to  run tron nile testnet, but everytime it gets stuck at a particular block number.As recommended i am deleting the old database and using the latest snaphsots , but still it gets  stuck to a particular block height.I have tried this 3-4 times in last 4 days , everyday with new snaphot. I tried with latest snapshot of 8 august from this [link](http://47.90.243.177/backup20220808/l) and the block number is stuck at 28756108 .
I tried the solutions on this issue  #2996  but they are not  wokring.

#### Actual behaviour
Block height should increase with time.

#### Steps to reproduce the behaviour
1. Download Binary from [Tron Binary](https://github.com/tronprotocol/java-tron/releases/download/GreatVoyage-v4.5.1/FullNode.jar)
2. Download Testnet Config File from [Testnet Config file](https://raw.githubusercontent.com/tronprotocol/tron-deployment/master/test_net_config.conf)
3. Run the following command:
`java -Xmx24g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c test_net_config.conf --es`

**Below are the logs**

`
Peer 15.207.88.30:18888 [9c95e10b]
ping msg: count 5, max-average-min-last: 213 203 194 213
connect time: 29s
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:27123718
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 113(0), discover: 1/4 1/1 6/7 0/0 196ms, p2p: 3/3/3 , tron: 21/19 X 4<=CONNECT_FAIL=>TIME_OUT, tcp flow: 1952
top99 : 0.000000, top95 : 0.000000, top75 : 0.000000, max : 0, min : 0, mean : 0.000000, median : 0.000000

Peer 45.195.61.127:18888 [7bf9ff7b]
ping msg: count 5, max-average-min-last: 259 249 236 254
connect time: 25s
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:1177141
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 204(0), discover: 1/1 1/1 28/28 0/0 248ms, p2p: 3/3/3 , tron: 21/19 X 2 =>TIME_OUT, tcp flow: 2000
top99 : 0.000000, top95 : 0.000000, top75 : 0.000000, max : 0, min : 0, mean : 0.000000, median : 0.000000

Peer 119.23.79.46:18888 [df7384a6]
ping msg: count 5, max-average-min-last: 1774 589 262 1774
connect time: 29s
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:27123718
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 183(0), discover: 1/1 1/1 0/0 0/0 306ms, p2p: 3/3/3 , tron: 20/18 X 4<=CONNECT_FAIL=>TIME_OUT, tcp flow: 1950
top99 : 0.000000, top95 : 0.000000, top75 : 0.000000, max : 0, min : 0, mean : 0.000000, median : 0.000000

Peer 119.23.35.152:18888 [3886bb19]
ping msg: count 5, max-average-min-last: 10700 2436 263 10700
connect time: 28s
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:1177141
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 192(0), discover: 1/1 1/1 0/0 0/0 349ms, p2p: 4/4/4 , tron: 25/25 X 3<=PING_TIMEOUT=>TIME_OUT, tcp flow: 2660
top99 : 0.000000, top95 : 0.000000, top75 : 0.000000, max : 0, min : 0, mean : 0.000000, median : 0.000000

06:33:59.980 INFO  [nioEventLoopGroup-6-1] [net](MessageQueue.java:131) Receive from /15.207.88.30:35184, type: P2P_DISCONNECT
reason: TIME_OUT
06:33:59.986 INFO  [nioEventLoopGroup-6-1] [net](TronChannelInitializer.java:48) Close channel:/15.207.88.30:35184 | 9c95e10bf5294cf901490cb48b83c074b4511036af2dcf03aff3d9a3b047ae5f71caf10ee2f267bafb03edf959ce3253187b5fb5bd1afe2491402b77bba09e24
06:34:00.653 INFO  [nioEventLoopGroup-6-2] [net](MessageQueue.java:131) Receive from /119.23.79.46:44904, type: P2P_DISCONNECT
reason: TIME_OUT
06:34:00.654 INFO  [nioEventLoopGroup-6-2] [net](TronChannelInitializer.java:48) Close channel:/119.23.79.46:44904 | df7384a6850086f87b0720b21d728c8480ab721b0b135441ce323e971802eb60df3d15d7777b3d1b3551b4159849e736fe5a6854e693cf05cabdafe31bcf4f5e
06:34:02.839 INFO  [nioEventLoopGroup-6-3] [net](MessageQueue.java:131) Receive from /119.23.35.152:46536, type: P2P_DISCONNECT
reason: TIME_OUT
06:34:02.842 INFO  [nioEventLoopGroup-6-3] [net](TronChannelInitializer.java:48) Close channel:/119.23.35.152:46536 | 3886bb1994dd5f9a3dcea856a39eae1fff9a294752bfeccb4e4f1a4d0ab43573ed81383c7b882a60a91bc99d939c63fd7686836944b8e4fc4033db41af0ecb99
06:34:03.009 INFO  [nioEventLoopGroup-6-4] [net](MessageQueue.java:131) Receive from /52.14.68.169:51198, type: P2P_DISCONNECT
reason: TIME_OUT
06:34:03.018 INFO  [nioEventLoopGroup-6-4] [net](TronChannelInitializer.java:48) Close channel:/52.14.68.169:51198 | ed46f497d3d9d1148b97211160e3ecc0794e7794f2839ee9e0ff44ebe39921d6f3cd148653d5a1235ddd88185922f4c727a2c87f9e277c1a493342a9043ebba3
06:34:03.033 INFO  [nioEventLoopGroup-6-1] [net](MessageQueue.java:131) Receive from /51.68.208.180:32838, type: P2P_DISCONNECT
reason: TIME_OUT
06:34:03.038 INFO  [pool-39-thread-1] [net](PeerClient.java:70) connect peer 47.90.214.183 18888 58c99e96b696500996594c115b67ba05ffa9e31db1778668dbf6ca4373a10ea06b426e2c5a29f82a1ef3b0e521b0d44f3bdab14fa521db96df7ad025e4ff447e
06:34:03.038 INFO  [nioEventLoopGroup-6-1] [net](TronChannelInitializer.java:48) Close channel:/51.68.208.180:32838 | e5bd8f0d784bc4a7dc8ec2c834f90b58919e82e4e1c21f7f9d860edfe9e88807fd38217e122da6e70e49f325627781f1feae77e085568df1e7802601c3bbee0e
06:34:03.039 INFO  [pool-39-thread-1] [net](PeerClient.java:70) connect peer 3.129.224.33 18888 a91c79ae51796adc6f8407e427988d811ca101f2aeaf227a0106cfece21a6c106a481946b61b319a4cf75189300185160b4dee8250995ecee488d05c570f7573
06:34:03.047 INFO  [TronJClientWorker-3] [net](HandshakeHandler.java:81) channel active, /47.90.214.183:18888
06:34:03.047 INFO  [TronJClientWorker-3] [net](HandshakeHandler.java:137) Handshake send to /47.90.214.183:18888, type: P2P_HELLO
from {
  address: "165.227.193.213"
  port: 18888
  nodeId: "\254O\365,d\267\213kw\372\276s\017\031\316+u\344uA\"\001\311]\350W\027\234\303\304\004%x\316dx\302\210\272\361\351\267V\002;\244|is\b/T\320\250\255\235\030\362@\333\262\323\020w"
}
version: 201910292
timestamp: 1659940443047
genesisBlockId {
  hash: "\000\000\000\000\000\000\000\000\326\230\324\031,V\313k\347$\245XD\216&\204\200-\344\326\315\206\220\334"
}
solidBlockId {
  hash: "\000\000\000\000\001\266\310z\376L#\236\t3.u\255\222\325\372\243\371\206t\306\344`#\364\312\267t"
  number: 28756090
}
headBlockId {
  hash: "\000\000\000\000\001\266\310\214\267K\372T|6+\303\274\320\310\330\352!\313\220ojj\264\2474?\316"
  number: 28756108
}
 
06:34:03.055 INFO  [TronJClientWorker-3] [net](HandshakeHandler.java:96) Handshake receive from /47.90.214.183:18888, type: P2P_DISCONNECT
reason: TOO_MANY_PEERS
06:34:03.055 INFO  [TronJClientWorker-3] [net](TronChannelInitializer.java:48) Close channel:/47.90.214.183:18888 | 58c99e96b696500996594c115b67ba05ffa9e31db1778668dbf6ca4373a10ea06b426e2c5a29f82a1ef3b0e521b0d44f3bdab14fa521db96df7ad025e4ff447e
06:34:03.416 INFO  [nioEventLoopGroup-6-2] [net](MessageQueue.java:131) Receive from /151.106.12.22:43184, type: P2P_DISCONNECT
reason: TIME_OUT
06:34:03.425 INFO  [nioEventLoopGroup-6-2] [net](TronChannelInitializer.java:48) Close channel:/151.106.12.22:43184 | 0569e8d858fae18322233de7474304b3865ee4ae90d045acdded8dc5f0c8cfab46f7daa4a5a0b4de2ebfab98871762137785906e4296bb518ebcb3ea1d5dda76
06:34:04.738 INFO  [nioEventLoopGroup-6-3] [net](MessageQueue.java:131) Receive from /44.240.166.110:51721, type: P2P_DISCONNECT
reason: TIME_OUT
06:34:04.744 INFO  [nioEventLoopGroup-6-3] [net](TronChannelInitializer.java:48) Close channel:/44.240.166.110:51721 | 8a8137973143a1e25b054f28896e51131eba8887c53cb1f81210bd964b5b8d00d4d4cace0b7dec6215835014a1ab483678c3c6de469088c08704c4db70084489
06:34:04.905 INFO  [TronJClientWorker-2] [net](MessageQueue.java:131) Receive from /45.195.61.127:18888, type: P2P_DISCONNECT
reason: TIME_OUT
06:34:04.906 INFO  [TronJClientWorker-2] [net](TronChannelInitializer.java:48) Close channel:/45.195.61.127:18888 | 7bf9ff7b24cb6aab14be03935c39000693b607af9b80962a6815c903a135c1bb9c61cda2b3981eee6c43586d0cecf7f6c78e76c71649f1ef14798ab9c079e809
06:34:05.042 WARN  [TronJClientWorker-0] [net](PeerClient.java:58) connect to 3.129.224.33:18888 fail,cause:connection timed out: /3.129.224.33:18888
06:34:05.042 INFO  [TronJClientWorker-0] [net](TronChannelInitializer.java:48) Close channel:null | <null>
06:34:05.307 INFO  [nioEventLoopGroup-6-4] [net](MessageQueue.java:131) Receive from /46.4.85.108:54452, type: P2P_DISCONNECT
reason: TIME_OUT

**Comment by singhsahilzeeve** [comment]
> Same for me! Tried different snapshots for about a week without any success. If i'm starting the node with empty output directory I'm able to sync up to 1628390, then all peers failing with TOO_MANY_PEERS or TIME_OUT reasons.

Today  i tried a snap of 21 July 2022. I think that is the last snapshot that is working fine you can use that and it will help your node sync in 6-7 hours [.](http://47.90.243.177/backup20220721/FullNode_output-directory.tgz) But the database problem still needs to be resolved for future.

**Comment by dmytro-samoylenko** [comment]
> Today i tried a snap of 21 July 2022. I think that is the last snapshot that is working fine you can use that and it will help your node sync in 6-7 hours [snapshot link](http://47.90.243.177/backup20220721/FullNode_output-directory.tgz) But the database problem still needs to be resolved for future.

It works! Thank you.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
