### ISSUE TITLE
there is something wrong after i build the develop branch in my ecplise

### ISSUE THREAD

**Issue by kou-gou** [tronprotocol/java-tron#459]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
 I clone the java-tron to my local ,then import into ecplise and after gradle bulid successful.

2. What did you expect to see?
no compile error .

3. What did you see instead?
 i got compile error on my ecplise.

![image 1](https://user-images.githubusercontent.com/28554769/38855401-5281d1fc-425e-11e8-9ab8-c15af924fc8c.png)

**Comment by zhaohong** [comment]
you need third-party lib, such as protobuf, lombok.

**Comment by Rovak** [comment]
Looks similar to https://github.com/tronprotocol/java-tron/issues/223#issuecomment-372261198

**Comment by kou-gou** [comment]
thanks i will try it.
