### ISSUE TITLE
Why my node stopped sync?

### ISSUE THREAD

**Issue by Anderson-Juhasc** [tronprotocol/java-tron#4592]
### System information

java-tron version: 4.5.1 GreatVoyage-v4.4.6-257-ge06abd15c 16944
OS & Version: Linux Debian@latest

Well, I'm running the node on mainnet and it stuck at x block at this time is **4152501**.
I deleted the db to start again but I got the same error...

Command: java -Xmx24g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c main_net_config.conf --es

Any idea?

**Comment by 11111961abc** [comment]
Пишите на русском пожалуйста

пн, 15 авг. 2022 г., 22:59 Anderson Juhasc ***@***.***>:

**Comment by Anderson-Juhasc** [comment]
@11111961abc 
Что ж, я запускаю узел в основной сети, и он застрял в блоке x, в настоящее время это 4152501.
Я удалил БД, чтобы начать снова, но я получил ту же ошибку...

Команда: java -Xmx24g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c main_net_config.conf --es

Есть идеи?

**Comment by joker-gdb** [comment]
Hopes it can help you：https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

Syncing from 0 is not a good idea, you can use snapshot data, it is very fast to build a node.

**Comment by halibobo1205** [comment]
java-tron need `jdk1.8_x86_64`, other jdk or arch such as `arm `not support for now.

**Comment by Anderson-Juhasc** [comment]
@halibobo1205 how can I install that version on debian?
