### ISSUE TITLE
Inaccessible API wallet/getaccountbalance

### ISSUE THREAD

**Issue by hub-il** [tronprotocol/java-tron#4605]
Per the documentation the API call "wallet/getaccountbalance" is only available on select official nodes.  Why is it limited to these nodes and is it possible to enable it on other private nodes?

Documentation:
https://developers.tron.network/reference/getaccountbalance

**Comment by L-Reid** [comment]
Yes, you can enable the history balance lookup feature on your own node by configuring the `storage.balance.history.lookup=true` , and this will occupy more disk capacity to store the historical data.

**Comment by L-Reid** [comment]
Just add `balance.history.lookup = true` into `storage` section of the node configuration file.  Then start the fullnode,  you can query the account balance at the block which synced after starting the node. and it is not supported to query the account balance at the block synced before.  

So you can download a snapshot of certain time according your demand, and enable the configure item, then you can query the blocks after the snapshot time.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
