### ISSUE TITLE
Hello, how get address transactions history?

### ISSUE THREAD

**Issue by abj3ct10n** [tronprotocol/java-tron#4613]
I did not find how to query the historical transaction records of an account by consulting the TRON FULL NODE documents. At present, I only know that TRONGRID supports the query of account transaction records, but I am not sure whether TRONGRID supports the TRONGRID API. A query using the TRONGRID API via the public node server address prompts me with 404.

Check whether the interface of the TRON FULL NODE supports querying historical transaction records of an account.

thank you

**Comment by joker-gdb** [comment]
Fullnode does not support the API.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
