### ISSUE TITLE
callstatic is possible?

### ISSUE THREAD

**Issue by leonchuk** [tronprotocol/java-tron#4624]
Like in [eth network](https://docs.ethers.io/v5/api/contract/contract/#contract-callStatic) or other alternatives for get result of contract methods?

**Comment by m-o-m12** [comment]
TRON api : wallet/triggerconstantcontract  is the same as callstatic of eth,  we can use it to invoke the readonly method for querying contract data, and can also use it to invoke the non-readonly method of a contract to check the returned result and estimate the energy consumption of this transaction by energy_limit filed.

**Comment by leonchuk** [comment]
@m-o-m12 thank you!! it's so simple!

https://developers.tron.network/reference/triggerconstantcontract
in documentation should mention this, as with the energy calculation, it's a popular question

**Comment by m-o-m12** [comment]
You are welcome. I get to know how to do energy calculation from [here](https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-calling-the-contract)
