### ISSUE TITLE
The eth_estimateGas interface returns no execution status.

### ISSUE THREAD

**Issue by darrendutt** [tronprotocol/java-tron#4657]
### 1. What did you do?

I call the eth_estimateGas interface of the **local node(v4.5.1)** to estimate the energy required by the transaction, and at the same time determine whether the address has enough TRX payment energy. If the conditions are met, the transaction will be broadcast, but after a transaction is broadcast, it indicates that the energy is insufficient and failed.

### 2. What did you expect to see?
Transaction execution successful.

### 3. What did you see instead?
Transaction fails due to out of energy.

**Comment by lakfly** [comment]
> ### 1. What did you do?
> I call the eth_estimateGas interface of the **local node(v4.5.1)** to estimate the energy required by the transaction, and at the same time determine whether the address has enough TRX payment energy. If the conditions are met, the transaction will be broadcast, but after a transaction is broadcast, it indicates that the energy is insufficient and failed.
> 
> ### 2. What did you expect to see?
> Transaction execution successful.
> 
> ### 3. What did you see instead?
> Transaction fails due to out of energy.

Before version 4.5.1(including version 4.5.1), the eth_estimateGas interface for transaction, regardless of its execution success or failure (such as  revert error), only returned the energy value consumed during the execution process, and did not return the execution result status, but this problem has been solved in version 4.5.2， the eth_estimateGas  interface will return error information when smart contract transaction execution is interrupted.
So you can upgrade the node to version 4.5.2,  please refer to the following link for the technical introduction of this version:
https://developers.tron.network/docs/greatvoyage-v452aurelius

**Comment by darrendutt** [comment]
The latest version(v4.5.2) already supports returning the execution status. Very helpful, thanks!

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
