### ISSUE TITLE
Event plugin configuration issues

### ISSUE THREAD

**Issue by carterbllake** [tronprotocol/java-tron#4660]
### 1. What did you do?

I have already built the TRON node and event plugin locally and I want to listen to the Transfer event of the USDT contract, What should I do?

### 2. What did you expect to see?
Get the Transfer event of the USDT contract

**Comment by lakfly** [comment]
> ### 1. What did you do?
> I have already built the TRON node and event plugin locally and I want to listen to the Transfer event of the USDT contract, What should I do?
> 
> ### 2. What did you expect to see?
> Get the Transfer event of the USDT contract

Use the filter parameter in config.conf file, for example：
filter = {
       fromblock = "" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
       toblock = "" // the value could be "", "latest" or a specified block number as end of the queried range
       contractAddress = [
           "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t" // contract address you want to subscribe, if it's set to "", you will receive contract logs/events with any contract address.
       ]

       contractTopic = [
           "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef" // contract topic you want to subscribe, if it's set to "", you will receive contract logs/events with any contract topic.
       ]
    }
Note:contractTopic：ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef is the Transfer event itself, the value is the calculation result of keccak256('Transfer(address,address,uint256)’).

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
