### ISSUE TITLE
Event interface returns null

### ISSUE THREAD

**Issue by daphnnee** [tronprotocol/java-tron#4661]
### 1. What did you do?

I used the Trongrid interface to query the events for this transaction and the interface returned null with the below request URL: https://api.trongrid.io/v1/transactions/ 87778d260459296d41804b50afac497bb2ef64d223d81116ec51e5ded5b4047f/events' 

Is there something wrong with my operation?

### 2. What did you expect to see?

Return events data.

**Comment by Shaunbutler24** [comment]
Unsubscribe

**Comment by lakfly** [comment]
> ### 1. What did you do?
> I used the Trongrid interface to query the events for this transaction and the interface returned null with the below request URL: https://api.trongrid.io/v1/transactions/ 87778d260459296d41804b50afac497bb2ef64d223d81116ec51e5ded5b4047f/events'
> 
> Is there something wrong with my operation?
> 
> ### 2. What did you expect to see?
> Return events data.

TRX transfer, TRC10 transfer belongs to the system call, only the smart contract transactions will trigger the event, such as TRC20 transfer .Please refer to the event-related documentation: https://developers.tron.network/docs/event

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
