### ISSUE TITLE
BANDWITH_ERROR error 

### ISSUE THREAD

**Issue by gailgia** [tronprotocol/java-tron#4688]
### 1. What did you do?

When my address TEYjMQk4RoE93T2Pz1AX8Zko5gk8SiYLAw broadcast transaction(USDT transfer), i got BANDWITH_ERROR error. I checked through tronscan that this address has 391 bandwidth, which is enough for USDT transfer.  
<img width="533" alt="image" src="https://user-images.githubusercontent.com/100566638/192686128-0983a8c6-23b6-445d-a288-5b1b18b8fdc4.png">

### 2. What did you expect to see?
successful transfer

### 3. What did you see instead?

BANDWITH_ERROR error

**Comment by sunflower-sun** [comment]
BANDWITH_ERROR  means account bandwidth resource is insufficient. The amount of bandwidth changes in real-time according to the total stake amount in the network. So you need to ensure the enough resources before broadcasting a transaction.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
