### ISSUE TITLE
Syncing stopped, with TOO_MANY_PEERS error in the logs

### ISSUE THREAD

**Issue by agathakazar** [tronprotocol/java-tron#4696]
### System information

java-tron version: docker tronprotocol/java-tron:latest
OS & Version: 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

### 1. What did you do?
Ran the container for some time to sync the mainnet bockchain

### 2. What did you expect to see?
A sync in progress with `docker.sh --log | grep 'pushBlock'` showing progress

### 3. What did you see instead?
The blockchain was synchronizing for some time, but stopped and is now throwing errors:
12:34:48.817 INFO  [TronJClientWorker-14] [net](HandshakeHandler.java:96) Handshake receive from
 /63.32.28.153:18888, type: P2P_DISCONNECT
reason: TOO_MANY_PEERS

The above `docker.sh --log | grep 'pushBlock'` command doesn't provide any output

### 4. Additional info: 
Output of http://127.0.0.1:8090/wallet/getnodeinfo

> {"activeConnectCount":4,"beginSyncNum":27497085,"block":"Num:27497100,ID:0000000001a3928cb1d504943a1c17c143d65a8e756fc87895436e9ef4a18f18","cheatWitnessInfoMap":{},"configNodeInfo":{"activeNodeSize":0,"allowAdaptiveEnergy":0,"allowCreationOfContracts":0,"backupListenPort":10001,"backupMemberSize":0,"backupPriority":8,"codeVersion":"4.5.1","dbVersion":2,"discoverEnable":true,"listenPort":18888,"maxConnectCount":30,"maxTimeRatio":5.0,"minParticipationRate":15,"minTimeRatio":0.0,"p2pVersion":"11111","passiveNodeSize":0,"sameIpMaxConnectCount":2,"sendNodeSize":0,"supportConstant":false,"versionNum":"16944"},"currentConnectCount":6,"machineInfo":{"cpuCount":24,"cpuRate":0.006440398865611563,"deadLockThreadCount":0,"deadLockThreadInfoList":[],"freeMemory":11625861120,"javaVersion":"1.8.0_202","jvmFreeMemory":4845272256,"jvmTotalMemory":8231583744,"memoryDescInfoList":[{"initSize":2555904,"maxSize":268435456,"name":"CodeCache","useRate":0.15260815620422363,"useSize":40965440},{"initSize":0,"maxSize":-1,"name":"Metaspace","useRate":0.9656147303305626,"useSize":61380096},{"initSize":0,"maxSize":1073741824,"name":"Compressed Class Space","useRate":0.006551764905452728,"useSize":7034904},{"initSize":139853824,"maxSize":1256259584,"name":"Par Eden Space","useRate":0.04758567477722821,"useSize":59779960},{"initSize":17432576,"maxSize":157024256,"name":"Par Survivor Space","useRate":0.038483328333681135,"useSize":6042816},{"initSize":349569024,"maxSize":6818299904,"name":"CMS Old Gen","useRate":0.4869965766762494,"useSize":3320488712}],"osName":"Linux 5.10.0-18-amd64","processCpuRate":0.005525771686824145,"threadCount":229,"totalMemory":33548742656},"passiveConnectCount":2,"peerList":[{"active":true,"avgLatency":14.0,"blockInPorcSize":0,"connectTime":1664627566229,"disconnectTimes":2,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:0,ID:00000000000000001ebf88508a03865c71d452e25f4d51194196a1d22b6653dc","host":"217.28.62.50","inFlow":492302,"lastBlockUpdateTime":1664627566243,"lastSyncBlock":"","localDisconnectReason":"TIME_OUT","needSyncFromPeer":true,"needSyncFromUs":false,"nodeCount":90,"nodeId":"be99e443a9a7ee59c7bb699778128027cae87fbc5899643873b4d59c9454d8a9ed9abcf05793b29998ecafae8c7256d7938e4ccd6f7041f8a058c0d1b18ea5aa","port":18888,"remainNum":9892435,"remoteDisconnectReason":"","score":240,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":4000,"syncToFetchSizePeekNum":27497101,"unFetchSynNum":9892435},{"active":true,"avgLatency":25.0,"blockInPorcSize":0,"connectTime":1664627584248,"disconnectTimes":3,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:0,ID:0000000000000000000000000000000000000000000000000000000000000000","host":"95.216.66.24","inFlow":2665,"lastBlockUpdateTime":1664627584232,"lastSyncBlock":"Num:23272713,ID:0000000001631d09803cac79445401e126a15c448be8a1e6fcfbabaeffdbf001","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":true,"nodeCount":90,"nodeId":"674a2e5fe5c49626f7deca2ca8aec2a997b424c1966106fc8aae3630105d8f290094c3cc8fe7786d1d60c3637a48dff62e7675a974fdf0d9ad045ed7a9a4de87","port":18888,"remainNum":4224387,"remoteDisconnectReason":"TIME_OUT","score":210,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":4224387},{"active":false,"avgLatency":36.0,"blockInPorcSize":0,"connectTime":1664627034282,"disconnectTimes":0,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:22878998,ID:00000000015d1b160eb7f22a8d87cd6bc93caab26648c9eb6ee8831fe76c9f38","host":"212.32.249.175","inFlow":24,"lastBlockUpdateTime":1664627036043,"lastSyncBlock":"Num:22878998,ID:00000000015d1b160eb7f22a8d87cd6bc93caab26648c9eb6ee8831fe76c9f38","localDisconnectReason":"","needSyncFromPeer":false,"needSyncFromUs":true,"nodeCount":90,"nodeId":"1bf0b49fdb4844371c85a1684a988dfd47cdeb0344615db7c06c1bddf96c5a05a112c653b2532450d9f61ac97c186a72cf60e0e29ab1f010d8fbed87bf5f21f7","port":18888,"remainNum":4618102,"remoteDisconnectReason":"","score":240,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":0,"syncToFetchSizePeekNum":-1,"unFetchSynNum":4618102},{"active":true,"avgLatency":37.0,"blockInPorcSize":0,"connectTime":1664627577056,"disconnectTimes":4,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:0,ID:00000000000000001ebf88508a03865c71d452e25f4d51194196a1d22b6653dc","host":"23.88.73.152","inFlow":492302,"lastBlockUpdateTime":1664627577090,"lastSyncBlock":"","localDisconnectReason":"TIME_OUT","needSyncFromPeer":true,"needSyncFromUs":false,"nodeCount":90,"nodeId":"407f00b9d7c7d46b67cace18e94780f16e77c2369cd4485b52bd08db52502dc87b01c99858a367ef234fe1f478c6ed7dc186b91a92d874e488bcf7cc3feb1805","port":18888,"remainNum":15448983,"remoteDisconnectReason":"TOO_MANY_PEERS","score":220,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":4000,"syncToFetchSizePeekNum":27497101,"unFetchSynNum":15448983},{"active":false,"avgLatency":40.0,"blockInPorcSize":0,"connectTime":1664627567838,"disconnectTimes":2,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:0,ID:00000000000000001ebf88508a03865c71d452e25f4d51194196a1d22b6653dc","host":"45.13.59.30","inFlow":492302,"lastBlockUpdateTime":1664627567855,"lastSyncBlock":"","localDisconnectReason":"TIME_OUT","needSyncFromPeer":true,"needSyncFromUs":false,"nodeCount":90,"nodeId":"d860e537ff5617ae563c4f3a7620b1896cbcda75ee8cf67997feca71e415170281b209a8885bd4a4aaa7a707a368ce3017b7eb10326f4e88c3493ddfe442085a","port":18888,"remainNum":11581890,"remoteDisconnectReason":"","score":20,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":4000,"syncToFetchSizePeekNum":27497101,"unFetchSynNum":11581890},{"active":true,"avgLatency":183.0,"blockInPorcSize":0,"connectTime":1664627559198,"disconnectTimes":3,"headBlockTimeWeBothHave":0,"headBlockWeBothHave":"Num:0,ID:00000000000000001ebf88508a03865c71d452e25f4d51194196a1d22b6653dc","host":"66.29.144.70","inFlow":656404,"lastBlockUpdateTime":1664627559386,"lastSyncBlock":"","localDisconnectReason":"TIME_OUT","needSyncFromPeer":true,"needSyncFromUs":false,"nodeCount":90,"nodeId":"9fb701c02d63c780c1727aa5359c10a59ff7abd1c3414f7aad50f19b70232130b32d487e148e5b43eef7625e4b2d0677a325b8317da9bc8351504bb96fca70d0","port":18888,"remainNum":15448983,"remoteDisconnectReason":"","score":215,"syncBlockRequestedSize":0,"syncFlag":false,"syncToFetchSize":4000,"syncToFetchSizePeekNum":27497101,"unFetchSynNum":15448983}],"solidityBlock":"Num:27497082,ID:0000000001a3927a8368670528b5d4f6084e0baeb63059e750f089153f57ae5a","totalFlow":2135999}

**Comment by agathakazar** [comment]
Checked today, and it started syncing again after not showing any sings of life for about 12 hours. 

Before it started syncing, there were a number of BAD_BLOCK error messages in the logs, here's an example: 
> 04:24:10.986 WARN  [pool-52-thread-1] [DB](PendingManager.java:57) pending tx size:0
04:24:10.986 ERROR [pool-52-thread-1] [net](TronNetDelegate.java:281) Process block failed, Num:27497088,ID:00000000
01a39280bc129e2380d93ff34f83281e1a809ec3846aee0956512c98, reason: Different resultCode.
04:24:10.986 ERROR [pool-52-thread-1] [net](SyncService.java:270) Process sync block Num:27497088,ID:0000000001a3928
0bc129e2380d93ff34f83281e1a809ec3846aee0956512c98 failed.
org.tron.core.exception.P2pException: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:282)
        at org.tron.core.net.service.SyncService.processSyncBlock(SyncService.java:267)
        at org.tron.core.net.service.SyncService.lambda$handleSyncBlock$8(SyncService.java:255)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.service.SyncService.handleSyncBlock(SyncService.java:238)
        at org.tron.core.net.service.SyncService.lambda$init$1(SyncService.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecut
or.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java
:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.tron.core.exception.ReceiptCheckErrException: Different resultCode
        at org.tron.core.db.TransactionTrace.check(TransactionTrace.java:279)
        at org.tron.core.db.Manager.processTransaction(Manager.java:1324)
        at org.tron.core.db.Manager.processBlock(Manager.java:1594)
        at org.tron.core.db.Manager.applyBlock(Manager.java:878)
        at org.tron.core.db.Manager.pushBlock(Manager.java:1177)
        at org.tron.core.net.TronNetDelegate.processBlock(TronNetDelegate.java:252)
        ... 12 common frames omitted
04:24:10.986 INFO  [pool-52-thread-1] [net](Channel.java:140) Send to /65.108.103.49:18888 online-time 1s, type: P2P
_DISCONNECT
reason: BAD_BLOCK

**Comment by sunflower-sun** [comment]
Maybe you can try the below two ways to solve your node syncing issue:  
1. improve machine configuration, for example, 16core 32GRAM 1T SSD.  
2. set maxTimeRatio to 20.0 or higher.

If these two ways cannot solve your issue,  maybe you should re-download the database snapshot.

**Comment by j4ys0n** [comment]
I just had the same issue. setting `maxTimeRatio` to `20.0` seems to have fixed it. thank you!

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
