### ISSUE TITLE
Cant get account or balance

### ISSUE THREAD

**Issue by gwumkt** [tronprotocol/java-tron#4697]
1. Im always getting 0 for any wallet balance.
2. how do i get trx and usdt balance

* running Lite mode.

### System information

OS : Linux
JVM : Private Build 1.8.0_342 amd64
Git : 349116e6ef109869b2fb1e3ed6f8a6753012d564
Version : 4.5.2
Code : 17071

```
POST http://MyServerIp:8090/wallet/getaccountbalance
{
	"account_identifier": {
		"address": "TVkT4aoze1Kes6cNHJXGEr4fm4dNVxkMfc"
	}, 
	"block_identifier": {
		"hash": "0000000002a9fc16e134626ab58d0cc37f4f2ad61839685255901e7fa5c68aeb",
		"number": 44694550
	},
	"visible": true
}
```

Response:
```

{
	"balance": 0,
	"block_identifier": {
		"hash": "0000000002a9fc16e134626ab58d0cc37f4f2ad61839685255901e7fa5c68aeb",
		"number": 44694550
	}
}

```

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
