### ISSUE TITLE
How long does it take to Sync full node from latest file download?

### ISSUE THREAD

**Issue by devfxplayer** [tronprotocol/java-tron#4698]
### System information

java-tron version: latest
OS & Version: Linux

### 1. What did you do?
Started Synch from file

### 2. What did you expect to see?
Fast Load of the node

### 3. What did you see instead?
Very slow synch almost 3 days passed.

**Comment by ahmadbrainworks** [comment]
experiencing the same problem with the latest release, sync is very slow, about 2 blocks per hour.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
