### ISSUE TITLE
Tron Account model. Can we have multiple deposit addresses for one account?

### ISSUE THREAD

**Issue by raitech12** [tronprotocol/java-tron#4701]
Can we have multiple deposit addresses for one account?
I want to assign a deposit address to each customer but receive the incoming TRON into a single account to spend it later .
In another word, one private key is able to sign multiple public keys.

**Comment by hitlxy** [comment]
No. A private key corresponds to a public key, that is an account. But you can realize your idea by modifying the customer account's permission.

**Comment by raitech12** [comment]
If it is not possible, how crypto exchanges are able to create a deposit address for their customers. They have to collect all incoming funds to a single account because spending them is not possible (or very hard) if funds are collected in separated accounts.

**Comment by hitlxy** [comment]
Exchange will create separate TRON accounts for each user and keep all private keys. After Users depositing funds into their exchange account, exchange will collect the funds into its own account to facilitate centralized management. Exchanges have all users' privatekey, they can do transferring anytime.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
