### ISSUE TITLE
Failed - Transaction Revert. Didn't receive 100% of sended funds after revert

### ISSUE THREAD

**Issue by luflud** [tronprotocol/java-tron#4729]
**1. What did you do?**

I Transferred 21048 USDT from TRC20 network(exodus wallet) to another TRC20 wallet.
My Txn Hash: 
https://tronscan.org/#/transaction/8e6debef172c394a202181da6268b9195aa10170a8a37736ed93b192d1050de8

**2. What did you expect to see?**
I expect the revert on the transaction

**3. What did you see instead?**
After ~30 minutes i recieved only 15048 USDT back. Where is 6000 USDT?

**Comment by m-o-m12** [comment]
For blockchain, failed transaction will not deduct your balance and successful transaction will not be rolled back. so you should contact the wallet support team for your issue.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by abn2357** [comment]
@luflud Have you ever figured out the problem? I plan to transfer  usdt recently. It will help me decide whether to use trc20 usdt.
Thx.
