### ISSUE TITLE
Pruning Tron Fullnode

### ISSUE THREAD

**Issue by AlirezaO** [tronprotocol/java-tron#4731]
### System information

java-tron version: 4.5.2
OS & Version: Linux 20.04.1

### 1. What did you do?
I have deployed Tron Nile testnet and it is syncing without any problem.

### 2. Your question?
Is there any way to prune the syncing Nile testnet or Tron mainnet?(please answer both if they are different)
or does Tron have a auto prune mechanism?

Thanks.

**Comment by forfreeday** [comment]
You can use the tools provided by tron, e.g

```shell
java -jar LiteFullNodeTool.jar -o split -t snapshot --fn-data-path output-directory/database --dataset-path liteDatabase/output-directory/
```

**Comment by AlirezaO** [comment]
So after starting node with this command:
"sudo java -Xmx24g -XX:+UseConcMarkSweepGC -jar /home/keyone/nile/java-tron/build/libs/FullNode.jar -c /home/keyone/nile/java-tron/nile_net_config.conf"

I should stop it and run the command you said? do I have to run the FullNode.jar again or does LiteFullNodeTool.jar do the job?

**Comment by forfreeday** [comment]
Yes ,you must first stop the `FullNode.jar`
`LiteFullNodeTool.jar` utility in the java-tron build code directory:java-tron/build/libs.
Then execute the command.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by AlirezaO** [comment]
@forfreeday sorry to bother you again. First of all, thank you for your previous solution which was very helpful. 
I got a quick question about the pruning process and I would be thankful if you could help me again.

Is it possible to set the size of the pruned output directory in the pruning command (by reducing block height or content size)?

**Comment by sigaev-pro** [comment]
@AlirezaO, did you find a solution?
