### ISSUE TITLE
How to calculate energy consumption of sending TRC20 Token?

### ISSUE THREAD

**Issue by mahnunchik** [tronprotocol/java-tron#4737]
Is there any documentation how to calculate energy consumption of sending TRC20 Token?

The previous question was left unanswered: https://github.com/tronprotocol/java-tron/issues/2982

Second question: how to calculate amount of TRX needed to obtain that amount of energy?

**Comment by sunflower-sun** [comment]
you can refer to this page to calculate energy. https://stackoverflow.com/questions/67172564/how-to-estimate-trc20-token-transfer-gas-fee/73222761#73222761 

currently the unit price of energy is 280sun. 1000sun=1TRX.

**Comment by mahnunchik** [comment]
I think it have to be added to official documentation.

**Comment by mahnunchik** [comment]
`eth_estimategas` API method doesn't work:

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"REVERT opcode executed","data":"{}"}}
```

Documentation: https://developers.tron.network/reference/eth_estimategas

**Comment by sunflower-sun** [comment]
The returned error message shows the transaction executed failed. If you execute the transaction in TRON mainnet directly, it will also be fail. You should check the transaction and make sure it can run successfully and then this api can return the energy needed by this transaction.

**Comment by mahnunchik** [comment]
As I see the API doesn't require contract address. The parameters are correct in the example? 

```sh
curl -X POST '47.95.206.44:50545/jsonrpc' --data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "eth_estimateGas",
    "params": [{
        "from": "0x41F0CC5A2A84CD0F68ED1667070934542D673ACBD8",
        "to": "0x4170082243784DCDF3042034E7B044D6D342A91360",
        "gas": "0x01",
        "gasPrice": "0x8c",
        "value": "0x01",
        "data": "0x70a08231000000000000000000000041f0cc5a2a84cd0f68ed1667070934542d673acbd8"
    }]
}'
```

**Comment by sunflower-sun** [comment]
"to" is the contract address or the external address, the usage of this api is the same as ethereum'. 

Even the example can execute successfully before, because of the state data on-chain may be changed, the example maybe execute failed now. so you should construct your own parameters.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by lliypuk** [comment]
Solution: https://developers.tron.network/docs/set-feelimit#how-to-estimate-energy-consumption
