### ISSUE TITLE
Please invite me to the HackerOne program

### ISSUE THREAD

**Issue by fulldecent** [tronprotocol/java-tron#4764]
This issue is a duplicate of https://github.com/tronprotocol/java-tron/issues/4531

Because that other issue was closed prematurely

**Comment by ethan1844** [comment]
Java-tron bug bounty program on Hackerone is coming, please wait patiently.

**Comment by fulldecent** [comment]
Any progress on this?

**Comment by ethan1844** [comment]
@fulldecent please refer to: https://hackerone.com/tron_dao?type=team

**Comment by fulldecent** [comment]
Are these final amounts?

I was expecting payouts to be 100x or 1000 more, lol
