### ISSUE TITLE
Document architecture implementation decisions

### ISSUE THREAD

**Issue by fulldecent** [tronprotocol/java-tron#4765]
In previous versions of the TRON documentation, details were published about how the VM works.

For example, here is an old page explaining how storage values are hashed and stored in the state tree on disk.

https://developers.tron.network/v4.0/docs/virtual-machine-storage

The latest TRON documentation does not include that page and Java TRON documentation also does not include this detail.

Please publish and maintain this detail for current releases.

**Comment by Jakevsky** [comment]
The content of the VM in Java-tron has been rearranged in the recent release, the team is still working on it and it would be available later.
