### ISSUE TITLE
maven import wallet-cli.jar will error

### ISSUE THREAD

**Issue by xiaohuajian** [tronprotocol/java-tron#4794]
maven导入wallet-cli.jar后
启动springboot提示错误：

APPLICATION FAILED TO START

Description:

Parameter 0 of method consulServiceRegistry in org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistryAutoConfiguration required a bean of type 'com.ecwid.consul.v1.ConsulClient' that could not be found.

Action:

Consider defining a bean of type 'com.ecwid.consul.v1.ConsulClient' in your configuration.

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consulServiceRegistry' defined in class path resource [org/springframework/cloud/consul/serviceregistry/ConsulServiceRegistryAutoConfiguration.class]: Unsatisfied dependency expressed through method 'consulServiceRegistry' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.ecwid.consul.v1.ConsulClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by xiaohuajian** [comment]
someone have report this pormble,but this question still exit , I use the lastest java-wallet project code generate the wallet-cli.jar . So, i want to how to fix this problem ,thanks

**Comment by GodLovesme324** [comment]
Kindly contact the Support team to fix the issue below is their livechat link https://direct.lc.chat/14756535/

**Comment by txoh1603** [comment]
I use trident, It is very convenient for me. You can have a try.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
