### ISSUE TITLE
Consider using the SEI CERT Oracle Coding Standard for Java

### ISSUE THREAD

**Issue by suiginsoft** [tronprotocol/java-tron#48]
Hello.

What are your thoughts on adopting say the SEI CERT Oracle Coding Standard for Java for use in the Tron project to improve security, robustness and overall quality and consistency of the project?

You could hook up a static analyzer like SonarQube's SonarJava or Coverity Scan that supports the SEI CERT standard, and integrate with TravisCI and the gradle build script. These tools generate reports of all of the violations of the standard and potential bugs and problems that need to be remedied to come into compliance. This combined with good unit testing is pretty much the next best thing you can do short of using formal verification and automatic proof checkers.

See the following link for more information:

https://wiki.sei.cmu.edu/confluence/display/java/SEI+CERT+Oracle+Coding+Standard+for+Java

**Comment by JohnnyQQQQ** [comment]
@suiginsoft what do you think of codeclimate with [sonar-java](https://docs.codeclimate.com/docs/sonar-java) analyzer?

**Comment by suiginsoft** [comment]
@JohnnyQQQQ 
Looks pretty good, worth trying out at least.
