### ISSUE TITLE
using multi signature function in shasta

### ISSUE THREAD

**Issue by misaqsaadat** [tronprotocol/java-tron#4816]
Hi
does shasta supports multi-signature functionality?
I try to use existing UIs to test it. I created a wallet and changed permissions. but from "shasta.tronscan.org" I couldn't create multisignature transaction. (the Accounts under Control list is always empty)
from Andriod version in another try, there is a message says that :"Shasta network does not support initiating multisig transfers"
is it true? shasta does't support it? so why I can change permissions?
is there any other tron test network which I can test multi-sig feature?
Cost of changing permissions is too high (100 TRX) and there is a possibility to lose all my assets if I use main network.
is there any solutions?

**Comment by L-Reid** [comment]
I can create multi-sign transaction through shasta tronscan，and then invoke tronlink chrome extension to sign it.

**Comment by misaqsaadat** [comment]
Thanks for reply.
So what am I doing wrong?
this is my wallet:
https://shasta.tronscan.org/#/address/TKVn8aJf5RxBHxXM4eB7nCbUnuPxJTfu41
and this is change permission transaction : 
https://shasta.tronscan.org/#/transaction/ee56098e352e1f8ed9c6bd90324632b1892a1e3e7b52dfcbe329158f57cd3b66
but in "Multisig Transaction" menu there is no Accounts under Control.
What am I missing?
I can give you mnemonic if you need

**Comment by misaqsaadat** [comment]
I think I found problem.
multisig process works fine in "nile". but shasta has some problems.
when loading multisig form, a request goes to server. this is request and response from NILE which works normal:

request : 
get_private_and_public_tags
request payload : 
{"target_address_list":["TKVn8aJf5RxBHxXM4eB7nCbUnuPxJTfu41"]}
response :
{"retCode":"0","retMsg":["SUCCESS"],"data":{"contract_map":{"TKVn8aJf5RxBHxXM4eB7nCbUnuPxJTfu41":false},"tag_map":{"TKVn8aJf5RxBHxXM4eB7nCbUnuPxJTfu41":{"private_tag":"","public_tag":null}}}}

but in shasta for same operation we have:

request : 
get_private_and_public_tags
request payload : 
{"target_address_list":[]}
response : 
{"retCode":"1","retMsg":["miss some parameter"],"data":{}}

I think this might be a bug or something. I try it in different browsers and PCs. all have same problem. is this right github page for checking it?

**Comment by hitlxy** [comment]
Last week it indeed cannot trigger multi-sign transaction on shasta tronscan. But now  multi-sign function on shasta tronscan is normal. you can have a try.

**Comment by Majidbaba** [comment]
> Thanks for reply.
> 
> So what am I doing wrong?
> 
> this is my wallet:
> 
> https://shasta.tronscan.org/#/address/TKVn8aJf5RxBHxXM4eB7nCbUnuPxJTfu41
> 
> and this is change permission transaction : 
> 
> https://shasta.tronscan.org/#/transaction/ee56098e352e1f8ed9c6bd90324632b1892a1e3e7b52dfcbe329158f57cd3b66
> 
> but in "Multisig Transaction" menu there is no Accounts under Control.
> 
> What am I missing?
> 
> I can give you mnemonic if you need

**Comment by Majidbaba** [comment]
> Thanks for reply.
> 
> So what am I doing wrong?
> 
> this is my wallet:
> 
> https://shasta.tronscan.org/#/address/TKVn8aJf5RxBHxXM4eB7nCbUnuPxJTfu41
> 
> and this is change permission transaction : 
> 
> https://shasta.tronscan.org/#/transaction/ee56098e352e1f8ed9c6bd90324632b1892a1e3e7b52dfcbe329158f57cd3b66
> 
> but in "Multisig Transaction" menu there is no Accounts under Control.
> 
> What am I missing?
> 
> I can give you mnemonic if you need

I don't understand what you mean, please help me more

**Comment by misaqsaadat** [comment]
> Last week it indeed cannot trigger multi-sign transaction on shasta tronscan. But now multi-sign function on shasta tronscan is normal. you can have a try.

Thanks. my problem fixed.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
