### ISSUE TITLE
ZeroMQ Subscription logic isn't documented anywhere in official docs

### ISSUE THREAD

**Issue by gbl-tylers** [tronprotocol/java-tron#4822]
Is there a reason that this functionality (introduced in https://github.com/tronprotocol/tips/blob/master/tip-28.md) isn't documented anywhere in official documentation? https://developers.tron.network/docs/event-subscription doesn't mention it, nor does https://tronprotocol.github.io/documentation-en/developers/deployment/#event-subscribe-plugin-deployment.

The only sources are tickets talking about how this functionality isn't working for them, or the original PR. Would be great if there was more support for this method of interacting with the blockchain.

**Comment by ethan1844** [comment]
Please refer to [here](https://developers.tron.network/docs/event-plugin-deployment-kafka#311-plugin-configurations).

**Comment by MrShutCo** [comment]
It does briefly mention it, but it does so in the Kafka section. It just says to set it false to use Kafka, otherwise it uses "native message queue" and makes no mention of zeromq or how to use that queue, and is still inconsistent in the Github.io docs

**Comment by ethan1844** [comment]
> It does briefly mention it, but it does so in the Kafka section. It just says to set it false to use Kafka, otherwise it uses "native message queue" and makes no mention of zeromq or how to use that queue, and is still inconsistent in the Github.io docs

Thanks, we will update the Github and Developer docs soon, of course, for github doc, it is an open source [project](https://github.com/tronprotocol/documentation-en), we also welcome you to submit PRs.

**Comment by ethan1844** [comment]
Please refer to :https://developers.tron.network/docs/use-java-trons-built-in-message-queue-for-event-subscription

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed.
