### ISSUE TITLE
> > > > > hash 13007f51b7deba3b5d41593b88310f5974a0d179865898b1601aa50141b5604f

### ISSUE THREAD

**Issue by newlife08** [tronprotocol/java-tron#4827]
> > > > > hash
> > > > 
> > > > 13007f51b7deba3b5d41593b88310f5974a0d179865898b1601aa50141b5604f
> > > > 
> > > > Aprouve 
> > > >  TXxJL1qCJ38Xsb89GhxYikUpg4F68K1j5
> > > > 13007f51b7deba3b5d41593b88310f5974a0d179865898b1601aa50141b5604f Event Log (1)
> > > > Owner Address:
> > > > TNXoiAJ3dct8Fjg4M9fkLFh9S2v9T
> > > > Xc32G
> > > > (Binance-Hot)
> > > > Copy
> > > > Open in a new tab
> > > > Show QR Code
> > > > Send Tokens
> > > > Contract Address:
> > > > TFczxzPhnThNSqr5by8tvxsdCFRRz
> > > > 6cPNq
> > > > (NFT Token)
> > > > Token Transfer:1
> > > > From
> > > > TNXoiAJ3dct8Fjg4M9fkLFh9S2v9T
> > > > Xc32G
> > > > (Binance-Hot)
> > > > Copy
> > > > Open in a new tab
> > > > Show QR Code
> > > > Send Tokens
> > > > To
> > > > TCzUYnFSwtH2bJkynGB46tWxWjdTQ
> > > > qL1SG
> > > > (NFT Token)
> > > > 
> > > > Token
> > > > 71,375.16106$
> > > > APENFT
> > > > NFT
> > > > Value:
> > > > 0 
> > > > trx 
> > > > TRX
> > > > Method Calling:
> > > > transfer(address _to, uint256 _value)
> > > > MethodID:    a9059cbb
> > > > [0]:   0000000000000000000000412125c56fcd4bb9462bdba4f916ab6064e5fc86da
> > > > [1]:   000000000000000000000000000000000000000000000000000000109e4a86e4
> > > > 
> > > 
> > > Address
> > > TFczxzPhnThNSqr5by8tvxsdCFRRz6cPNq
> > > (NFT Token)
> > > Method
> > > transfer(address _to,uint256 _value)
> > > Topics
> > > Transfer(from,to,value)
> > > 0
> > > TNXoiAJ3dct8Fjg4M9fkLFh9S2v9TXc32G
> > > 1
> > > TCzUYnFSwtH2bJkynGB46tWxWjdTQqL1SG
> > > 2
> > > 71375161060
> > > Data
> > > from:
> > > TNXoiAJ3dct8Fjg4M9fkLFh9S2v9TXc32G
> > > to:
> > > TCzUYnFSwtH2bJkynGB46tWxWjdTQqL1SG
> > > value:
> > > 71375161060
> > Conment
> 
> Comment

- [ fixer value] - TXxJL1qCJ38Xsb89GhxYikUpg4F68K1j5V

_Originally posted by @newlife08 in https://github.com/tronprotocol/tron-deployment/issues/69#issuecomment-1338284739_

**Comment by Mohsenkoomatso** [comment]
@ #
