### ISSUE TITLE
Node stuck at block 46772580 with P2P_DISCONNECT reason: TOO_MANY_PEERS

### ISSUE THREAD

**Issue by twilightrus** [tronprotocol/java-tron#4845]
#### System information

java-tron version: GreatVoyage-v4.6.0(Socrates)
OS & Version: Linux & Ubuntu 20.04.5 LTS
Commit hash : -

#### Expected behaviour
Node doesn't stuck

#### Actual behaviour
Node stuck

#### Steps to reproduce the behaviour
java -Xmx40g -XX:ReservedCodeCacheSize=256m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=1G -XX:+UseConcMarkSweepGC -XX:NewRatio=2 -XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=70 -jar /home/blockchain/tron/FullNode.jar -c /home/blockchain/tron/main_net_config.conf --output-directory /mnt/tron --log-config /home/blockchain/tron/logback.xml

Config and logs in attachments

[main_net_config.conf.txt](https://github.com/tronprotocol/java-tron/files/10225106/main_net_config.conf.txt)
[tron.out.log](https://github.com/tronprotocol/java-tron/files/10225107/tron.out.log)

**Comment by SergeevDmitry** [comment]
Same here. Node stuck on 46772580 block

**Comment by sunflower-sun** [comment]
Did your node have already upgraded to the latest version 4.6.0?

**Comment by twilightrus** [comment]
> Did your node have already been upgraded to the latest version 4.6.0?

Yes

**Comment by currylinux** [comment]
I have the same problem, what is the reason?

**Comment by zikorayann** [comment]
I also stopped syncing yesterday on block 46836809, version 4.6.0

**Comment by SergeevDmitry** [comment]
Fixed after upgrading to the latest version (4.6.0)

**Comment by chengtx01** [comment]
> > Did your node have already been upgraded to the latest version 4.6.0?
> 
> Yes

Judging from the information you have provided so far, it is difficult for us to determine the cause of your problem. Have you tried restarting your node. If the problem still occurs after restarting, please provide the following complete log from the node startup to the time the problem occurs.

**Comment by twilightrus** [comment]
Solved by rebuild node from 4.6.0
