### ISSUE TITLE
SendCoin Failed

### ISSUE THREAD

**Issue by axiang-huge** [tronprotocol/java-tron#4847]
**I failed to use the sendcoin command with the following information. How should I successfully execute the SendCoin command?**

wallet> sendCoin TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY TAtooXhMzxsKoq9heNkU3H32k2ZRVZN6Cm 1000000
{
        "raw_data":{
                "contract":[
                        {
                                "parameter":{
                                        "value":{
                                                "amount":1000000,
                                                "owner_address":"TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY",
                                                "to_address":"TAtooXhMzxsKoq9heNkU3H32k2ZRVZN6Cm"
                                        },
                                        "type_url":"type.googleapis.com/protocol.TransferContract"
                                },
                                "type":"TransferContract"
                        }
                ],
                "ref_block_bytes":"4aa7",
                "ref_block_hash":"2e6ec7fa89188169",
                "expiration":1671087816000,
                "timestamp":1671087757937
        },
        "raw_data_hex":"0a024aa722082e6ec7fa8918816940c0fae1a4d1305a67080112630a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412320a1541928c9af0651632157ef27a2cf17ca72c575a4d211215410a2318b91ca08362c4a6d2845a59eaea65b9c30718c0843d70f1b4dea4d130"
}
before sign transaction hex string is 0a85010a024aa722082e6ec7fa8918816940c0fae1a4d1305a67080112630a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412320a1541928c9af0651632157ef27a2cf17ca72c575a4d211215410a2318b91ca08362c4a6d2845a59eaea65b9c30718c0843d70f1b4dea4d130
Please confirm and input your permission id, if input y or Y means default 0, other non-numeric characters will cancel transaction.
y
Please choose your key for sign.
The 1th keystore file name is UTC--2022-12-14T08-23-52.443000000Z--TE1sQCD3owNv1bd5Xw9a23jsd8SWDCu6Rv.json
The 2th keystore file name is UTC--2022-12-15T06-47-58.588000000Z--TAtooXhMzxsKoq9heNkU3H32k2ZRVZN6Cm.json
Please choose between 1 and 2
2
Please input your password.
password: 
sendCoin failed!
a6edf0d3802f94c01c68d02e02d0892328beefc58dde05f1d75350be60f284350e08dc30469dc53823e6f05fe7659f14603c52908b54c5ac47126ba610bed42c01 is signed by TAtooXhMzxsKoq9heNkU3H32k2ZRVZN6Cm but it is not contained of permission.
wallet>

**Comment by joker-gdb** [comment]
You should use the privatekey of TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
