### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by zhangtiantian222** [tronprotocol/java-tron#4867]
FAILURE: Build failed with an exception.

* Where:
Build file '/opt/tron/java-tron-GreatVoyage-v4.6.0/plugins/build.gradle' line: 102

* What went wrong:
Could not determine the dependencies of task ':plugins:buildToolkitJar'.
> Could not resolve all files for configuration ':plugins:compile'.
   > Could not resolve com.github.halibobo1205.leveldb-java:leveldb:v0.12.5.
     Required by:
         project :plugins
      > Could not resolve com.github.halibobo1205.leveldb-java:leveldb:v0.12.5.
         > Could not get resource 'https://repo.spring.io/plugins-release/com/github/halibobo1205/leveldb-java/leveldb/v0.12.5/leveldb-v0.12.5.pom'.
            > Could not GET 'https://repo.spring.io/plugins-release/com/github/halibobo1205/leveldb-java/leveldb/v0.12.5/leveldb-v0.12.5.pom'. Received status code 401 from server: Unauthorized
      > Could not resolve com.github.halibobo1205.leveldb-java:leveldb:v0.12.5.
         > Could not get resource 'https://jitpack.io/com/github/halibobo1205/leveldb-java/leveldb/v0.12.5/leveldb-v0.12.5.pom'.
            > Could not GET 'https://jitpack.io/com/github/halibobo1205/leveldb-java/leveldb/v0.12.5/leveldb-v0.12.5.pom'. Received status code 521 from server: 
   > Could not resolve com.github.halibobo1205.leveldb-java:leveldb-api:v0.12.5.
     Required by:
         project :plugins
      > Could not resolve com.github.halibobo1205.leveldb-java:leveldb-api:v0.12.5.
         > Could not get resource 'https://repo.spring.io/plugins-release/com/github/halibobo1205/leveldb-java/leveldb-api/v0.12.5/leveldb-api-v0.12.5.pom'.
            > Could not HEAD 'https://repo.spring.io/plugins-release/com/github/halibobo1205/leveldb-java/leveldb-api/v0.12.5/leveldb-api-v0.12.5.pom'. Received status code 401 from server: Unauthorized
      > Could not resolve com.github.halibobo1205.leveldb-java:leveldb-api:v0.12.5.
         > Could not get resource 'https://jitpack.io/com/github/halibobo1205/leveldb-java/leveldb-api/v0.12.5/leveldb-api-v0.12.5.pom'.
            > Could not HEAD 'https://jitpack.io/com/github/halibobo1205/leveldb-java/leveldb-api/v0.12.5/leveldb-api-v0.12.5.pom'. Received status code 521 from server: 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by halibobo1205** [comment]
`com.github.halibobo1205.leveldb-java:leveldb:v0.12.5` and `com.github.halibobo1205.leveldb-java:leveldb-api:v0.12.5` are released  by [jitpack.io](https://jitpack.io/) for 4.6.0 . Now it looks like there is something wrong with the official site,  please try it later. We  release `leveldb-java` jars on  [maven](https://mvnrepository.com/search?q=com.halibobor) since 4.7.0 .
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/82020050/209101052-41bc40a5-2298-4574-90b1-99a581e6cd28.png">

**Comment by halibobo1205** [comment]
https://github.com/jitpack/jitpack.io/issues/5337
