### ISSUE TITLE
Transaction volume doubled

### ISSUE THREAD

**Issue by git-yongge** [tronprotocol/java-tron#4880]
May I ask why the number of transactions in the most recent block has doubled?

**Comment by halibobo1205** [comment]
Here are the statistics of the last 2 weeks, not much has changed.
![image](https://user-images.githubusercontent.com/82020050/209782577-18823004-5468-4970-a068-4fc43a59ab29.png)

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
