### ISSUE TITLE
No websocket endpoint

### ISSUE THREAD

**Issue by wdcs-amit-kumar** [tronprotocol/java-tron#4881]
I find it difficult to connect my rust client to listen to smart contract events.

Please provide a stable websocket endpoint...
Premium or free both works.

Thanks!!

**Comment by lxcmyf** [comment]
You need to set up and start your own FullNode to listen to events. See the link below: https://developers.tron.network/docs/deploy-the-fullnode-or-supernode
If you don't want to build it yourself, refer to the link: https://developers.tron.network/docs/trongrid
