### ISSUE TITLE
Tron Transaction Memo Not Working

### ISSUE THREAD

**Issue by nkavian** [tronprotocol/java-tron#4931]
#### Expected behavior

When adding a note/memo to the TRX transaction, it should show up in TronScan.

#### Actual behavior

The memo is never displayed for TRX transactions in TronScan.

#### Steps to reproduce the behavior

1. Use the [createTransaction](https://developers.tron.network/reference/createtransaction) API to attach `extra_data`.
2. Sign and submit the data. We successfully submit it and the Transaction was confirmed.
3. View the transaction in TronScan and notice the memo is not displayed.

Note: The transaction was successfully submitted with `raw_data.data` equal to the memo and the signature was accepted.
Note: If we send a memo with a token contract transaction, there is no issue. TronScan displays it.

#### Related

https://github.com/tronprotocol/java-tron/pull/2583

**Comment by joker-gdb** [comment]
Tronscan does not display memo for TRX transfers with small value, may be the reason.

**Comment by nkavian** [comment]
Wow, that is so annoying. Thanks for the clue. I've been testing with low values; I tried a higher value and it worked.

Do you know where this is documented and/or what the threshold is?

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
