### ISSUE TITLE
Unclear returns for non-existent APIs

### ISSUE THREAD

**Issue by Vita-Diva** [tronprotocol/java-tron#4952]
### System information

java-tron version: 4.7.01

### 1. What did you do?
I called an non-existent API on a node:

```bash
/wallet/getnowblock1
```

### 2. What did you expect to see?

Java-tron is the only node service provided by TRON. For all API returns, successful or failed, the return type should be in json type to keep consistent. Cluttered HTMLs are returned now when calling non-existent APIs and these have changed with a recent `org.eclipse.jetty:jetty-server` upgrade.  This has caused obstacles to the integration of other applications.

It would be better to return a json containing errors like Trongrid:
![图片](https://user-images.githubusercontent.com/61683126/215719859-c6bf621c-8c4c-49ed-bc04-11cc0be70358.png)

### 3. What did you see instead?

Some HTMLs, contains error reasons but cluttered.

**Comment by forfreeday** [comment]
This is a good suggestion and we will consider changing it to json

**Comment by PeaStew** [comment]
Please do change this, it broke our e2e integration scripts at Ankr, and it should be fixed soon because we don't want to change it to parse HTML only for it to be changed back to json in a few weeks or months.

**Comment by halibobo1205** [comment]
Try this,`curl --request GET --url http://127.0.0.1:8090/wallet/getblock2 --header 'accept: application/json' `

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/82020050/216025347-55801658-45e7-49f1-b591-5452981a651b.png">

**Comment by PeaStew** [comment]
Thanks! testing now :)

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
