### ISSUE TITLE
The height of the node  remained stuck at 48234714

### ISSUE THREAD

**Issue by airstring** [tronprotocol/java-tron#4957]
After the node version was updated to v4.7.0.1, the height of the node  remained stuck at 48234714.
The log is as follows:
...
03:15:37.430 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:40.430 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:40.430 INFO  [qtp19473874-54] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:41.723 INFO  [qtp19473874-28] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:41.723 INFO  [qtp19473874-54] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:41.724 INFO  [qtp19473874-23] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:41.725 INFO  [qtp19473874-57] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:43.428 INFO  [qtp19473874-54] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:43.428 INFO  [qtp19473874-57] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:46.430 INFO  [qtp19473874-57] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:46.431 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:46.568 INFO  [qtp19473874-54] [VM](Program.java:1140) minTimeRatio: 0.0, maxTimeRatio: 5.0, vm should end time in us: 6779805775807, vm now time in us: 6779805832105, vm start time in us: 6779805695807
03:15:46.569 INFO  [qtp19473874-54] [VM](VM.java:92) VM halted: [CPU timeout for 'SLOAD' operation executing]
03:15:46.569 INFO  [qtp19473874-54] [VM](VMActuator.java:268) timeout: CPU timeout for 'SLOAD' operation executing
03:15:46.569 WARN  [qtp19473874-54] [o.t.c.Wallet](Wallet.java:3018) Constant call has an error CPU timeout for 'SLOAD' operation executing
03:15:46.745 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:46.745 INFO  [qtp19473874-53] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:46.745 INFO  [qtp19473874-28] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:46.746 INFO  [qtp19473874-57] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:49.428 INFO  [qtp19473874-22] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:15:49.428 INFO  [qtp19473874-53] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
...
03:19:25.428 INFO  [qtp19473874-22] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:28.112 INFO  [qtp19473874-22] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:28.117 INFO  [qtp19473874-28] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:28.117 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:28.120 INFO  [qtp19473874-28] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:28.429 INFO  [qtp19473874-28] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:28.430 INFO  [qtp19473874-22] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:31.431 INFO  [qtp19473874-54] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:31.431 INFO  [qtp19473874-53] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:33.139 INFO  [qtp19473874-55] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:33.141 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:33.172 INFO  [qtp19473874-55] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:33.172 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:34.215 storage-row Compacting 3@0 + 0@1 files
03:19:34.287 storage-row Generated table #27744223: 78356 keys, 2117858 bytes
03:19:34.351 storage-row Generated table #27744224: 79909 keys, 2115418 bytes
03:19:34.408 storage-row Generated table #27744225: 79897 keys, 2114283 bytes
03:19:34.429 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:34.429 INFO  [qtp19473874-28] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:34.465 storage-row Generated table #27744226: 79947 keys, 2114860 bytes
03:19:34.521 storage-row Generated table #27744227: 79856 keys, 2116242 bytes
03:19:34.538 storage-row Generated table #27744228: 20369 keys, 553911 bytes
03:19:34.538 storage-row Compacted 3@0 + 0@1 files => 11132572 bytes
03:19:34.539 storage-row compacted to: files[ 0 6 36 681 12122 0 0 ]
03:19:34.544 storage-row Delete type=2 #27744218

03:19:34.545 storage-row Delete type=2 #27744217

03:19:34.546 storage-row Delete type=2 #27744221

03:19:34.549 storage-row Moved #27744223 to level-2 2117858 bytes OK: files[ 0 5 37 681 12122 0 0 ]

03:19:37.430 INFO  [qtp19473874-53] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:37.431 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:38.219 INFO  [qtp19473874-53] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:38.219 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:38.221 INFO  [qtp19473874-52] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
03:19:38.235 INFO  [qtp19473874-28] [DB](Manager.java:1881) HeadNumber: 48234714, syncBeginNumber: 48234714, solidBlockNumber: 48234696.
...

**Comment by L-Reid** [comment]
Suggest to Increase the value of the maxTimeRatio configuration item in the node configuration file to 20.0 or higher.

vm = {
maxTimeRatio = 20.0
}

**Comment by airstring** [comment]
> Suggest to Increase the value of the maxTimeRatio configuration item in the node configuration file to 20.0 or higher.
> 
> vm = { maxTimeRatio = 20.0 }

Thanks. I'll have a  try.

**Comment by bsantoni-bc** [comment]
We have followed the suggestion and our node synced up to block 48238314.

Now we are seeing a lot of peers handshakes that mention the same `last know block num`:

`Peer 18.228.63.12:18888 [ad5f9aae]
ping msg: count 97, max-average-min-last: 219 198 192 193
connect time: 1982s
last know block num: 48238314
needSyncFromPeer:false
needSyncFromUs:false
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:0
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 159(171), discover: 1/1 0/0 0/175 0/0 192ms, p2p: 1/1/1 , tron: 204/207   , tcp flow: 1528
top99 : 0.000000, top95 : 0.000000, top75 : 0.000000, max : 0, min : 0, mean : 0.000000, median : 0.000000`

There are a couple of nodes that have `needSyncFromUs:true`, but no nodes with `needSyncFromPeer:true`
