### ISSUE TITLE
internal Tx can't get input data of contract A invoked contractB 

### ISSUE THREAD

**Issue by SuperEdison** [tronprotocol/java-tron#4973]
its difficult to trace internal tx containing trc20 tx.... no input data

 and tron node still need to saveInternalTx and then Do not display when user query transactioninfo API when saveInternalTx = false. now If the user accidentally makes the configuration item wrong, internalTx will disappear forever,that sound so bad

**Comment by hitlxy** [comment]
I got transaction information through gettransactioninfobyid API and there are internal transactions in return value, so we do not need to query the internal transactions through transaction hash.   Your question, if the configuration item is setting wrong, internalTx will disappear forever?  No.  If  saveInternalTx = false, only means this node does not include the internal transactions. but the transactions are in there, they will not disappear.  When we re-download the database snapshot, set saveInternalTx=true and re-start the node, let it to sync from a certain time, then the node will include all internal transactions from this certain time.

**Comment by hitlxy** [comment]
> > I got transaction information through gettransactioninfobyid API and there are internal transactions in return value, so we do not need to query the internal transactions through transaction hash.  >  > Your question, if the configuration item is setting wrong, internalTx will disappear forever? No. If saveInternalTx = false, only means this node does not include the internal transactions. but the transactions are in there, they will not disappear. When we re-download the database snapshot, set saveInternalTx=true and re-start the node, let it to sync from a certain time, then the node will include all internal transactions from this certain time.
> 
> ```json
> {
>                 "caller_address": "TLUqyV9rGYXZ2E8kXe6J3P1rvYV1Au1Goe",
>                 "note": "63616c6c",
>                 "transferTo_address": "TBHN6guS6ztVVXbFivajdG3PxFUZ5UXGxY",
>                 "callValueInfo": [
>                     {}
>                 ],
>                 "hash": "fc2f9edb249dfd4a4ce8998c8f179e113e7ad2e3c23d2e2da980741be322fc50"
>             }
> ```
> 
> There's no information here other than what method of the contract he called, right.if set saveInternalTx = false A period of time, we don't know from which block there was no internal tx, and the second , how do I set the CERTAIN TIME to resync internal tx?

This internal transaction do not have callvalueinfo means there is no any TRX/trc10 token transfers. and we can do not care about such internal transactions. 

"if set saveInternalTx = false A period of time, we don't know from which block there was no internal tx,". we can know the detailed block number through node log.

"how do I set the CERTAIN TIME to resync internal tx?" .  suppose we want the node support internal transactions since time A, just to download the database snapshot before time A, and set saveInternalTx to true, then start the node, then the synced blocks will include internal transactions.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by Johnnynzcryptonite** [comment]
> > I got transaction information through gettransactioninfobyid API and there are internal transactions in return value, so we do not need to query the internal transactions through transaction hash.   Your question, if the configuration item is setting wrong, internalTx will disappear forever? No. If saveInternalTx = false, only means this node does not include the internal transactions. but the transactions are in there, they will not disappear. When we re-download the database snapshot, set saveInternalTx=true and re-start the node, let it to sync from a certain time, then the node will include all internal transactions from this certain time.
> 
> ```json
> {
>                 "caller_address": "TLUqyV9rGYXZ2E8kXe6J3P1rvYV1Au1Goe",
>                 "note": "63616c6c",
>                 "transferTo_address": "TBHN6guS6ztVVXbFivajdG3PxFUZ5UXGxY",
>                 "callValueInfo": [
>                     {}
>                 ],
>                 "hash": "fc2f9edb249dfd4a4ce8998c8f179e113e7ad2e3c23d2e2da980741be322fc50"
>             }
> ```
> There's no information here other than what method of the contract he called, right.if set saveInternalTx = false A period of time, we don't know from which block there was no internal tx, and the second , how do I set the CERTAIN TIME to resync internal tx?
