### ISSUE TITLE
How do I use the protocol? Where do I use it?

### ISSUE THREAD

**Issue by jarivers082461** [tronprotocol/java-tron#4976]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS & Version: Windows/Linux/OSX

### 3. What did you see instead?

**Comment by 317787106** [comment]
Here is an example: https://github.com/tronprotocol/libp2p/blob/main/build.gradle
`sourceSets {
    main {
        proto {
            srcDir 'src/main/protos'
        }
        java {
            srcDir 'src/main/java'
        }
    }
}`

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
