### ISSUE TITLE
How to estimate energy consumption for TRC20

### ISSUE THREAD

**Issue by mahnunchik** [tronprotocol/java-tron#4978]
How to estimate energy consumption for sending TRC20 token according to new rules of extra energy consumption?

* Previously discussed method `eth_estimateGas` returns small value.
* `tronWeb.transactionBuilder.estimateEnergy` returns `this node does not support estimate energy` with `https://api.trongrid.io/` node.

**Comment by mahnunchik** [comment]
Related issue https://github.com/tronprotocol/java-tron/issues/4737

**Comment by mahnunchik** [comment]
Estimate API in `tronweb` library https://github.com/tronprotocol/tronweb/commit/dd8bba465dd16eee62acfad60f7e6f92e3c69cfa

**Comment by m-o-m12** [comment]
The old api which used to estimate energy consumption has already supported the extra energy.  I have used it, it works. and this is their article: https://medium.com/@coredevs/dynamic-energy-model-deployed-and-opened-on-nile-testnet-59b81cb748f5

**Comment by m-o-m12** [comment]
estimateEnergy is an optional api for tron node. only the node which has already opened this api through config file will provide this api service. just use triggerconstantcontract in tronweb to estimate is ok.

**Comment by m-o-m12** [comment]
You said :" Previously discussed method eth_estimateGas returns small value."     No.  eth_estimateGas is the same as triggerconstantcontract, when estimating the energy consumption, if the transaction runs failed, for example revert error..., then the return value will be the energy consumption until the error occurs. so it will be small than the normal. but there are also result field in return value to illustrate the execution result of the transaction, we can know the transaction execution result information according to it, and do some adjustments to ensure the transaction's successfully execution.  So through eth_estimateGas or triggerconstantcontract, we do not onnly can use them to estimate energy consumption, but also test if the transaction can execute successfully.

**Comment by earth-2022** [comment]
> The old api which used to estimate energy consumption has already supported the extra energy. I have used it, it works. and this is their article: https://medium.com/@coredevs/dynamic-energy-model-deployed-and-opened-on-nile-testnet-59b81cb748f5

Test BTT in nile.trongrid.io   is OK,such like 
post https://nile.trongrid.io/wallet/estimateenergy
{
    "owner_address": "TTGhREx2pDSxFX555NWz1YwGpiBVPvQA7e",
    "contract_address": "TVSvjZdyDSNocHm7dP3jvCmMNsCnMTPa5W",
    "function_selector": "transfer(address,uint256)",
    "parameter": "0000000000000000000000002ce5de57373427f799cc0a3dd03b841322514a8c00000000000000000000000000000000000000000000000000038d7ea4c68000",
    "visible": true
}
{
     "result": {
          "result": true
     },
     "energy_required": 14910
}
![image](https://user-images.githubusercontent.com/119399817/219560484-61004d32-cf21-4a31-a3b2-024c32f15d2d.png)

but with USDT in nile.trongrid.io   is NOT OK
![image](https://user-images.githubusercontent.com/119399817/219560874-2494456a-47b3-4a9e-9034-48e7ba6b36e7.png)

{
     "result": {
          "code": "CONTRACT_EXE_ERROR",
          "message": "REVERT opcode executed"
     }
}
and the same as USDC,USDJ

**Comment by m-o-m12** [comment]
Different parameters will lead to different result, if this estimate energy api returns the error code, then if you use the same parameter to run the transaction, the transaction will also fail.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
