### ISSUE TITLE
TRON TAPOS_ERROR 

### ISSUE THREAD

**Issue by SamXcodeX** [tronprotocol/java-tron#4981]
Can someone help me to get rid out of this error. I have already wasted 2 working days and tried other ways also but not working.

I'm trying to broadcast this transaction via https://tronscan.org/#/tools/transaction-viewer
I have pasted the output hex (value of signedTransaction variable) to that broadcast tron website. 

```
const CryptoUtils = require("@tronscan/client/src/utils/crypto");
const TransactionUtils = require("@tronscan/client/src/utils/transactionBuilder");

async function transferContractTx() {
    const fromPrivKey = "MY_PRIVATE_KEY";
    const fromAddress = "TGBWAxZrXFELAgpCALMdNbe1C16b7U6qKH";
    const toAddress = "TGFtUCXAcRpejsxNrU1cGGuadx8BgbSmzb";
    const privateKey = fromPrivKey;
    const token = "TRX";
    const amount = 1000000;
        
    let transaction = TransactionUtils.buildTransferTransaction(token, fromAddress, toAddress, amount);
    console.log(JSON.stringify(transaction));
    let signedTransaction = CryptoUtils.signTransaction(privateKey, transaction);
    console.log(signedTransaction);
}

transferContractTx();
```

**Comment by wubin01** [comment]
How is this transaction generated, is it generated by your own node or someone else’s node?

**Comment by wubin01** [comment]
The transaction does not set these two fields：
```
.setRefBlockHash(ByteString.copyFrom(ByteArray.subArray(blockHash, 8, 16)))
.setRefBlockBytes(ByteString.copyFrom(ByteArray.subArray(refBlockNum, 6, 8)))
```

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
