### ISSUE TITLE
Unwanted line comes in display. 

### ISSUE THREAD

**Issue by AyonX** [tronprotocol/java-tron#499]
[Please](url) answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Zoom in. And it wasn't there. 

2. What did you expect to see?
![screenshot_2018-04-22-01-19-56-623_com android chrome](https://user-images.githubusercontent.com/38592915/39088020-cddfeb24-45cc-11e8-9c69-1394c8d6bcb1.png)

3. What did you see instead?

A line which blocking the headline

**Comment by shanadas** [comment]
This is a wallet web issue and would be better file there - https://github.com/tronprotocol/wallet-web/issues

**Comment by huzhenyuan** [comment]
Please move the bug to https://github.com/tronprotocol/wallet-web.
