### ISSUE TITLE
new API (TIP-467 Add Stake 2.0) didn't work

### ISSUE THREAD

**Issue by yankevych** [tronprotocol/java-tron#4998]
### System information

java-tron version: `java -jar FullNode.jar -v 4.7.0.1(Aristotle)`
OS & Version: Linux

### 1. What did you do?
curl -X POST  http://*******:8090/wallet/freezebalancev2 -d  \
'{"owner_address":"T**************",
 "frozen_balance": 10,
 "resource":"ENERGY",
 "visible":true
}'

### 2. What did you expect to see?
Expect to use V2 API to "freeze balance" and to "delegate resources"

### 3. What did you see instead?
{"Error":"class org.tron.core.exception.ContractValidateException : Not support FreezeV2 transaction, need to be opened by the committee"}

**Comment by m-o-m12** [comment]
Stake 2.0 has not been opened on TRON mainnet, but on nile testnet. so we can test the stake2.0 feature on nile testnet and do the preparation for it.

**Comment by yankevych** [comment]
I think this information should be in the release notes. Because in the current version, it's looks like this feature released to mainnet.
What estimated release date for Stake 2.0?

**Comment by m-o-m12** [comment]
I saw it mentioned on release note. https://tronprotocol.github.io/documentation-en/releases/GreatVoyage-v470/  . I do not the date of this feature's activation, but we can pay attention to the announcement from the community.

**Comment by lurais** [comment]
@yankevych hello , as I can see from this issue:https://github.com/tronprotocol/tips/issues/519 ,The estimated timeline of the Stake 2.0 is the middle and late March.
