### ISSUE TITLE
Wrong data format in ancient blocks

### ISSUE THREAD

**Issue by chuwt** [tronprotocol/java-tron#5018]
### 1. What did you do?
I query the old blocks data and try to find the TRC10 transfer.

### 2. What did you expect to see?
According to the doc [here](https://developers.tron.network/docs/exchangewallet-integrate-with-the-tron-network#parse-blocks-to-get-transaction-records), the `asset_name` should be the tokenId.

### 3. What did you see instead?
I got a string name for this asset. But if the block number is nea the latest, the `asset_name` will be the tokenId.

Here is the data in [458f516ce0b3884e5c880cd962595cbd81b6c11380ae5c6701b23ff0175421dc](https://tronscan.org/#/transaction/458f516ce0b3884e5c880cd962595cbd81b6c11380ae5c6701b23ff0175421dc)
```
{
    "amount":13,
    "asset_name":"TRONONE",
    "owner_address":"TYVJ8JuQ6ctzCa2u79MFmvvNQ1U2tYQEUM",
    "to_address":"TYwXtnW5kh6uxB3b6BXDxZJFLyHjZhZ6ZE"
}
```

Here is the data in [503580574eb6f7232e4dea637f0eff01c08800d40f7b30246466d05f4155220f](https://tronscan.org/#/transaction/503580574eb6f7232e4dea637f0eff01c08800d40f7b30246466d05f4155220f)
```
{
    "amount":24,
    "asset_name":"1002270",
    "owner_address":"TL4st2ySoV9P8SdRXhNSLgRz8vvhbq7mdc",
    "to_address":"THs5b6Nt8q4NxaFiQPcaSRfXscdjqXfteG"
}
```

**Comment by halibobo1205** [comment]
Which api did you use for the query, `gettransactioninfobyid` or `getblockbynum`?
Here are the results of the query via `gettransactioninfobyid`.

[458f516ce0b3884e5c880cd962595cbd81b6c11380ae5c6701b23ff0175421dc](https://tronscan.org/#/transaction/458f516ce0b3884e5c880cd962595cbd81b6c11380ae5c6701b23ff0175421dc)
```json
{
  "amount": 7,
  "asset_name": "5061794974466f7277617264",
  "owner_address": "4155eaf154bbdb95e2f31afddc96b90a26a4a41fbc",
  "to_address": "41bfa08977d0cdcb2ff4de1d7c47c4640a709f17e8"
}
```
[503580574eb6f7232e4dea637f0eff01c08800d40f7b30246466d05f4155220f](https://tronscan.org/#/transaction/503580574eb6f7232e4dea637f0eff01c08800d40f7b30246466d05f4155220f)
```json
{
  "amount": 6,
  "asset_name": "31303031373236",
  "owner_address": "41cfd8935d7b21bad9bd33043c3cab9108685a5bc5",
  "to_address": "41518d58617052ec0f220aec6fa63831cf11486296"
}
```

**Comment by chuwt** [comment]
Hi @halibobo1205 , I used `getblockbynum`.

**Comment by chuwt** [comment]
Hi @halibobo1205, yes, `54524f4e4f4e45` is the hex string of `TRONONE`.
You can set `{"visible": true}` when querying the block to get the decoded data.
This only happened in ancient blocks.

**Comment by halibobo1205** [comment]
Hi, @chuwt this happens normally in ancient blocks, no id for early assets, @ethan1844 please update the document.

**Comment by chuwt** [comment]
@halibobo1205 How to get asset information by using this name?

**Comment by halibobo1205** [comment]
You can try `/wallet/getassetissuelistbyname`, @chuwt

**Comment by chuwt** [comment]
Okay, thank you!
