### ISSUE TITLE
Questions about internal transactions

### ISSUE THREAD

**Issue by Johnnynzcryptonite** [tronprotocol/java-tron#5019]
> > I got transaction information through gettransactioninfobyid API and there are internal transactions in return value, so we do not need to query the internal transactions through transaction hash.   Your question, if the configuration item is setting wrong, internalTx will disappear forever? No. If saveInternalTx = false, only means this node does not include the internal transactions. but the transactions are in there, they will not disappear. When we re-download the database snapshot, set saveInternalTx=true and re-start the node, let it to sync from a certain time, then the node will include all internal transactions from this certain time.
> 
> ```json
> {
>                 "caller_address": "TLUqyV9rGYXZ2E8kXe6J3P1rvYV1Au1Goe",
>                 "note": "63616c6c",
>                 "transferTo_address": "TBHN6guS6ztVVXbFivajdG3PxFUZ5UXGxY",
>                 "callValueInfo": [
>                     {}
>                 ],
>                 "hash": "fc2f9edb249dfd4a4ce8998c8f179e113e7ad2e3c23d2e2da980741be322fc50"
>             }
> ```
> There's no information here other than what method of the contract he called, right.if set saveInternalTx = false A period of time, we don't know from which block there was no internal tx, and the second , how do I set the CERTAIN TIME to resync internal tx?

_Originally posted by @Johnnynzcryptonite in https://github.com/tronprotocol/java-tron/issues/4973#issuecomment-1432816441_

**Comment by lxcmyf** [comment]
If you want the node to start supporting internal transactions at a certain time, just download the database snapshot before this time, set saveInternalTx to true, and then start the node. After that, internal transactions will be included when synchronizing blocks.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
