### ISSUE TITLE
improve voting mechanism.

### ISSUE THREAD

**Issue by zhaohong** [tronprotocol/java-tron#504]
1. add  the voting reward mechanism.
2. add reward lock mechanism.

**Comment by miimiispets** [comment]
Hi Marcus.
Question: Could you elaborate on mechanism under 1 a little? Where and when is this mechanism triggered, for example at placing a vote for SR?

Question: Could you elaborate on reward lock mechanism under 2 a little? Where and when is this mechanism triggered?

Thanks for your replies.

**Comment by zhaohong** [comment]
@miimiispets  1. when someone vote a trx for witness,  after the vote statistics system will give the reward to voter, about 1 trx give 1 drop
2.  when witness received the reward,   the witness must wait for one day to withdraw the reward.

by the way ,   vote reward is implements but not enable.

**Comment by miimiispets** [comment]
@zhaohong Marcus thank you for answering! Additionally on: 
1. Is the drop defined as a drop in trx, or will the drop consist of something different. Or is this still under investigation/debate? Will the vote reward be enabled with main net?
