### ISSUE TITLE
How to make the contract trigger an event when successfully transferred to the contract 

### ISSUE THREAD

**Issue by kaiser-9527** [tronprotocol/java-tron#5046]
When the TRX is successfully transferred to the contract, how to make the contract trigger an event?

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
 
contract ExampleContract {
    event TransactionReceived(address indexed sender, uint value);
    
    function clog  () public {
        emit TransactionReceived(msg.sender, 1);
    }
    
    receive () external payable {
        emit TransactionReceived(msg.sender, 2);
    }
    
    fallback () external payable {
        emit TransactionReceived(msg.sender, 3);
    }
}
When the transfer was successful, I didn't receive the TransactionReceived event.

**Comment by yanghang8612** [comment]
Transfers to contract addresses via `/wallet/createtransaction` do not raise an event.
You must transfer TRX to the contract address via `/wallet/triggersmartcontract` (by setting `call_value` to amount), which will raise an event.

**Comment by kaiser-9527** [comment]
What if I use tronlink wallet to transfer trx

**Comment by joker-gdb** [comment]
> What if I use tronlink wallet to transfer trx

Th a t will not raise the event

**Comment by kaiser-9527** [comment]
Then how can i get the transfer record?

**Comment by yanghang8612** [comment]
If you want to view the transaction history of a certain address, you can view it on [TRONSCAN](https://tronscan.org/#/) for mainnet or [Nile TRONSCAN](https://nile.tronscan.org/#/) for Nile testnet.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by CursedMun** [comment]
Any example on how to do it?

**Comment by abdullahAttiq** [comment]
did anybody find solution for this. i am also trying a similer thing where recieve funds will instantaniously transfered to a predefined wallet. 
after the transfer the transaction passes but the funds get stuck in the contract. 

`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.6;

contract TRXForwarder {
    address payable public immutable destination;

    event TRXForwarded(uint256 amount);

    constructor(address payable _destination) {
       // require(_destination != address(0), "Invalid address");
        destination = _destination;
    }

    receive() external payable {
        require(msg.value > 0, "No TRX sent");
        payable(destination).call{value: msg.value}("");
    }

    fallback() external payable {
        require(msg.value > 0, "No TRX sent");
        payable(destination).call{value: msg.value}("");
    }

    function renounceOwnership() public pure {
        revert("Ownership renouncement not allowed");
    }

    function selfDestruct() public pure {
        revert("Self-destruction not allowed");
    }
}`

**Comment by vedant-asati** [comment]
was this issue solved? is there any way for achieving this functionality?
It works quite well in ethereum chains but not on tron.

**Comment by vedant-asati** [comment]
> Transfers to contract addresses via `/wallet/createtransaction` do not raise an event. You must transfer TRX to the contract address via `/wallet/triggersmartcontract` (by setting `call_value` to amount), which will raise an event.

is there any way i can create `/wallet/triggersmartcontract` txn from wallets like tronlink?

**Comment by abdullahAttiq** [comment]
> was this issue solved? is there any way for achieving this functionality? It works quite well in ethereum chains but not on tron.
> 
> sometimes this is intended, specifically for achieving autosweep functionalities.

Sorry mate.....nothing so far
