### ISSUE TITLE
Fee estimation: different values for triggerconstantcontract and estimateenergy methods

### ISSUE THREAD

**Issue by mahnunchik** [tronprotocol/java-tron#5068]
Two methods from the documentation gives a different results for fee estimation. How to use that data?

#### System information

Examples from the documentation: https://developers.tron.network/docs/set-feelimit#how-to-estimate-energy-consumption

Using `wallet/triggerconstantcontract`:

```bash
$ curl -X POST  https://nile.trongrid.io/wallet/triggerconstantcontract -d '{
    "owner_address": "TTGhREx2pDSxFX555NWz1YwGpiBVPvQA7e",
    "contract_address": "TVSvjZdyDSNocHm7dP3jvCmMNsCnMTPa5W",
    "function_selector": "transfer(address,uint256)",
    "parameter": "0000000000000000000000002ce5de57373427f799cc0a3dd03b841322514a8c00000000000000000000000000000000000000000000000000038d7ea4c68000",
    "visible": true
}'
```

Using `wallet/estimateenergy`:

```bash
$ curl -X POST  https://nile.trongrid.io/wallet/estimateenergy -d '{
    "owner_address": "TTGhREx2pDSxFX555NWz1YwGpiBVPvQA7e",
    "contract_address": "TVSvjZdyDSNocHm7dP3jvCmMNsCnMTPa5W",
    "function_selector": "transfer(address,uint256)",
    "parameter": "0000000000000000000000002ce5de57373427f799cc0a3dd03b841322514a8c00000000000000000000000000000000000000000000000000038d7ea4c68000",
    "visible": true
}'
```

#### Expected behaviour

Fee estimations are the same.

#### Actual behaviour

`wallet/triggerconstantcontract`:
```
{"result":{"result":true},"energy_used":13253
```

`wallet/estimateenergy`:
```
{"result": {"result": true},"energy_required": 14910}
```

13253 !== 14910

#### Steps to reproduce the behaviour

Request data from the API.

Related issues:
* https://github.com/tronprotocol/java-tron/issues/4737
* https://github.com/tronprotocol/java-tron/issues/2982

**Comment by sunflower-sun** [comment]
triggerconstantcontract returns the actual energy consumed to execute the transaction through "energy_used" field. and estimateenergy returns the estimated energy needed to execute the transaction successfully through "energy_required" field, and this estimated energy can ensure the provided energy is enough.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
