### ISSUE TITLE
How to get the blockId?

### ISSUE THREAD

**Issue by pengten** [tronprotocol/java-tron#5099]
### System information
sdk 0.3.0

### 1. What did you do?

I call `getBlockByNum` by `ApiWrapper`, but there is no `blockId`.

### 2. What did you expect to see?
I want to get blockId by blockNumber

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
