### ISSUE TITLE
litenode testnet snapshot

### ISSUE THREAD

**Issue by A2DNEW** [tronprotocol/java-tron#5104]
Hi
I want to use testnet with litenode
Is there any snapshot for this?

**Comment by chengtx01** [comment]
Unfortunately, there is currently no testnet litenode snapshot provided，because the testnet full node snapshots are not very large.

**Comment by A2DNEW** [comment]
I started testnet node
It takes about 10 days!

**Comment by mcroni** [comment]
@A2DNEW can you give us a brief on how you were able to achieve this ? Thanks

**Comment by lurais** [comment]
> I started testnet node It takes about 10 days!

hello , could you please provide the  system information of your machine, and is the network condition good？

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
