### ISSUE TITLE
How can I get all transaction of account/address?

### ISSUE THREAD

**Issue by A2DNEW** [tronprotocol/java-tron#5107]
Hi,
I have running a node on my server.
And tronweb for send, getbalance and ...
But I can't access all transactions of account/address

**Comment by Basit108** [comment]
Prove

**Comment by A2DNEW** [comment]
Can you help me more?

**Comment by hitlxy** [comment]
For fullnode, it has no such API to  to query all transactions of an account. Tronweb is an javascript SDK for TRON and it also does not have such API.  But trongrid service provides some its proprietary user-friendly API which including [get all transactions of an account ](https://developers.tron.network/reference/get-transaction-info-by-account-address).

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by SugamKuber** [comment]
Hey there
@hitlxy we need an API endpoint which will give the user transaction directly by calling the tron java node.
The one you gave was an trongrid api to get the transactions from 3rd party party tron server. 
I need to get from my own local tron node server
