### ISSUE TITLE
How can I get all account/address on my own node?

### ISSUE THREAD

**Issue by A2DNEW** [tronprotocol/java-tron#5108]
I run a node on my server,
And I create account address with this code:
`tronweb.createAccount()`
Now, I want to find how many account created in my own node?
I want to get list of all addresses/accounts created in my node

**Comment by hitlxy** [comment]
There is no api to get the list of all addresses created in a  fullnode. but as an alternative way, we can record the created address by ourselves or program.

**Comment by A2DNEW** [comment]
@hitlxy how I can record?
Because 10 users use my node and these users use `tronweb.createAccount()` in self server.
Is there any event listener for record in node?

**Comment by hitlxy** [comment]
tronweb.createAccount() is to generate address locally, not by fullnode. And creating address locally is a more safety way for users.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
