### ISSUE TITLE
JAVA-TRON FULLNODE

### ISSUE THREAD

**Issue by rootbesi** [tronprotocol/java-tron#5113]
Currently our server already setup 3.5tb storage,day by day it's keep consume our storage..now it's almost 100% usage,is there any pruning method on this?

**Comment by m-o-m12** [comment]
If your node save the internal transactions and the historical internal transactions are no more used,  you can download the latest snaphot without internal transactions, this way will save some space, and new synced blocks will also include internal transactions.   And if the node only used for broadcasting transactions, you can choose litefullnode.

**Comment by rootbesi** [comment]
@m-o-m12 sorry, im not clear by what you say,can show me example for snapshot without internal transactions?

**Comment by lurais** [comment]
@rootbesi hello, you can try to get the full data by downloading a file to replace what you use , just refer to this:https://developers.tron.network/docs/main-net-database-snapshots , or if you don't need the full data, you can try to split the data with the LiteFullNodeTool, just refer this:https://developers.tron.network/docs/main-net-database-snapshots#lite-fullnode-tool

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
