### ISSUE TITLE
What's the policy for banning a node which disconnected for a while?

### ISSUE THREAD

**Issue by KaiQiu9527** [tronprotocol/java-tron#5114]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS : Linux
JVM : Oracle Corporation 1.8.0_131 amd64
Git : da2673cd28e368b68c9a8056b7c3aa15ec880bf7
Version : 4.7.1
Code : 17673

### 1. What did you do?

I have two fullnode nodes in a same subnet.
Node A has a public ip and connect to the mainnet. 
Node B's seed node only contains Node A's private address, so it only connect to Node A when starting.
I'm testing the robust of the connection between Node A and Node B, so Node B will stop fullnode process occasionally.

### 2. What did you expect to see?
When I restart the fullnode process on Node B, it will soonly connected to Node A and start syncing.

### 3. What did you see instead?
If Node B stop the fullnode process for a short time, like 10 minutes, it can reconnect to the Node A shortly when I restart the process. But if I stop Node B fullnode process for a long time, like more than 30 minutes, it will be banned by Node A for a time. When I check the log on Node A, it shows that "Peer *NODE B'S PRIVATE IP* recently disconnected" and then the channel is closed. Node B has to wait for a long time to reconnect to the Node B. I want to know the policy for the disconnected node, and what we can do to avoid the "ban" policy if Node B occasionally disconnect.
<img width="650" alt="20230406-172727(WeLinkPC)" src="https://user-images.githubusercontent.com/16130943/230335187-3eb8cd66-6887-4e52-b475-98f3e4cf99aa.png">

**Comment by wubin01** [comment]
Look at the reason for disconnection, if it is `BAD_PROTOCOL, BAD_BLOCK, BAD_TX`, it will be banned for one hour, otherwise it will be banned for 1 minute.
If you want to to avoid the "ban" policy, you can add the IP of node B to A's `node.passive` configuration
```
passive = [
    # Passive accept connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]
```

**Comment by KaiQiu9527** [comment]
Thank you Wubin for the answer, you really help me a lot.
For the `node.passive`, I still have two questions about it:
1. Can we add a network segment rather than a specific ip into  `node.passive`? Cause I may create a lot of nodes like Node B in the same subnet which only connect to Node A.
2. Is there a way to add ip to `node.passive` of Node A without restarting it? Like rpc calling, etc.

**Comment by lurais** [comment]
> Thank you Wubin for the answer, you really help me a lot. For the `node.passive`, I still have two questions about it:
> 
> 1. Can we add a network segment rather than a specific ip into  `node.passive`? Cause I may create a lot of nodes like Node B in the same subnet which only connect to Node A.
> 2. Is there a way to add ip to `node.passive` of Node A without restarting it? Like rpc calling, etc.

1. A network segment is not supported now.
2. Adding ip to `node.passive` without restarting  will be supported in recently updates.

**Comment by KaiQiu9527** [comment]
Thanks Lurais! For the "ban" policy, I still have a question about. As I said before, I have a Node B which only has a private ip address and sync from Node A. When I check the logs, it shows that Node B occasionally stop syncing from Node A. It seems like Node B "ban" Node A for some reason and recover after about one minute. I wonder the reason why Node B stop syncing from Node A. Is it because of the Tron Chain itself, or the machine running the Node B? 
BTW, the flavor of Node B is 8U16G, 2T SATA harddisk.
<img width="669" alt="3" src="https://user-images.githubusercontent.com/16130943/230708430-fd22537a-db17-476f-a17f-f93b3ede52d7.png">
<img width="688" alt="2" src="https://user-images.githubusercontent.com/16130943/230708433-2e7d0526-d65c-48f2-9d50-95d93c333a69.png">
<img width="635" alt="1" src="https://user-images.githubusercontent.com/16130943/230708440-16ac27b5-1609-4866-a0ae-27eafb7dcff0.png">

**Comment by KaiQiu9527** [comment]
It seems like each time Node B disconnected Node A, the log shows "Node A not sync for a long time" and then Node B "ban" Node A for one minute. As Node B only connect to Node A for syncing, it stop syncing until reconnect to Node A. I wonder why Node B "ban"  Node A for sync timeout.
<img width="646" alt="4" src="https://user-images.githubusercontent.com/16130943/230712984-8b1e4e10-10f9-47c7-80d6-a1f81eaa03ca.png">

**Comment by lurais** [comment]
> 

As I know,  it depends on the way of  peer connection management in node A, if node A can not be connected by B now, node B shall not try to connect to A again immediately, actually the logic of dealing with connections in both A and B show you the result.

**Comment by KaiQiu9527** [comment]
Hi Lurais, I think that the problem may not cause by the network problem, bacause Node A and Node B are in the same subnet and connect to each other by private address. I wonder why Node B think Node A lost connection and ban it for one minute. I found that each time the "ban" happened, the syncing of Node B has been suspended for a while. The block of Node B didn't grow so that Node B thought that Node A not sync for a while. For example: ''16:39:48-16:40:48".
The tron log is uploaded to google drive:https://drive.google.com/file/d/1DUamfrDexh-gFQrPUzjhbKTu7HvdacuU/view?usp=share_link

**Comment by lurais** [comment]
> Hi Lurais, I think that the problem may not cause by the network problem, bacause Node A and Node B are in the same subnet and connect to each other by private address. I wonder why Node B think Node A lost connection and ban it for one minute. I found that each time the "ban" happened, the syncing of Node B has been suspended for a while. The block of Node B didn't grow so that Node B thought that Node A not sync for a while. For example: ''16:39:48-16:40:48". The tron log is uploaded to google drive:https://drive.google.com/file/d/1DUamfrDexh-gFQrPUzjhbKTu7HvdacuU/view?usp=share_link

Hello, I noticed that you opened another issue ,is that the real question you want to ask?

**Comment by KaiQiu9527** [comment]
Hi Lurais, these two questions are different. In this issue I want to know why Node B occasionally thinks Node A not sync for a long time and disconnect Node A for one minute. It shouldn't be a network problem I guess, because Node B connects to Node A by local network. I cannot find the reason why it happened some times. The two nodes run well from the monitor process.

**Comment by lurais** [comment]
> Hi Lurais, these two questions are different. In this issue I want to know why Node B occasionally thinks Node A not sync for a long time and disconnect Node A for one minute. It shouldn't be a network problem I guess, because Node B connects to Node A by local network. I cannot find the reason why it happened some times. The two nodes run well from the monitor process.

Do you mean that the Node A continue to get new blocks and  the Node B just thinks Node A not sync for a long time ?

**Comment by lurais** [comment]
> https://drive.google.com/file/d/1DUamfrDexh-gFQrPUzjhbKTu7HvdacuU/view?usp=share_link

As I can see from the log file, the node B have not receive sync message from A during about 30s, and to release the connection resource , the node A will be disconnected according to the code implementation.

**Comment by KaiQiu9527** [comment]
> > Hi Lurais, these two questions are different. In this issue I want to know why Node B occasionally thinks Node A not sync for a long time and disconnect Node A for one minute. It shouldn't be a network problem I guess, because Node B connects to Node A by local network. I cannot find the reason why it happened some times. The two nodes run well from the monitor process.
> 
> Do you mean that the Node A continue to get new blocks and the Node B just thinks Node A not sync for a long time ?

Yes exactly, Node A connects to the public network and sync normal at that time, but Node B, which only connect to Node A, thinks that it has not received sync message from A for a long time and drop the connection. I know that if B has a public ip and connects to hundred of public fullnodes, it should sync normally. But in this situation, B only has a private ip and sync from A, I want to know why the connection breaks osscationally. Are there some explanations for it? For example, is there a logic that one node should not connect to a specific node for a long time? Or there is a bug in this situation? I really want to locate this problem so that I can evaluate whether the "Node A and Node B" mode works. Looking forward for you help, Lurais.

Btw, I'm a Chinese developer and we can speak Chinese if you are too :)

**Comment by lurais** [comment]
> > > Hi Lurais, these two questions are different. In this issue I want to know why Node B occasionally thinks Node A not sync for a long time and disconnect Node A for one minute. It shouldn't be a network problem I guess, because Node B connects to Node A by local network. I cannot find the reason why it happened some times. The two nodes run well from the monitor process.
> > 
> > 
> > Do you mean that the Node A continue to get new blocks and the Node B just thinks Node A not sync for a long time ?
> 
> Yes exactly, Node A connects to the public network and sync normal at that time, but Node B, which only connect to Node A, thinks that it has not received sync message from A for a long time and drop the connection. I know that if B has a public ip and connects to hundred of public fullnodes, it should sync normally. But in this situation, B only has a private ip and sync from A, I want to know why the connection breaks osscationally. Are there some explanations for it? For example, is there a logic that one node should not connect to a specific node for a long time? Or there is a bug in this situation? I really want to locate this problem so that I can evaluate whether the "Node A and Node B" mode works. Looking forward for you help, Lurais.
> 
> Btw, I'm a Chinese developer and we can speak Chinese if you are too :)

As I can see from the log, Node B received the message(16:39:15.016 ) from A that says Node A has no more blocks to sync to B. And if node B has no need to sync from node A ,the connection to node A will be disconnected to recycle connection resource  (refer: https://github.com/tronprotocol/java-tron/blob/develop/framework/src/main/java/org/tron/core/net/peer/PeerStatusCheck.java),actually it is pointless to maintain the connection between A and B when there is no message send between them.  And if you found the blocks in B  continue to sync from A , it means that Node B connect to A is OK although it is not recommended for java-tron is designed for a decentralized network. And this repo is a global project, it is recommended to use a popular language in this site.
