### ISSUE TITLE
Snapshot server speed is not good

### ISSUE THREAD

**Issue by A2DNEW** [tronprotocol/java-tron#5115]
Hi
I want to download these snapshot:
https://developers.tron.network/docs/main-net-database-snapshots
But download speed is very slow
I use digitalocean servers

Sample: 127GiB/1,171GiB(10%) CN:14 DL:13MiB ETA:21h50m4s

**Comment by okwapa210** [comment]
Estimated 21h50m4s?  I think the speed is already very fast

**Comment by A2DNEW** [comment]
@okwapa210 I think is not good.
Because I downlodet 2TR of BSC snapshot in 7 hours.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
