### ISSUE TITLE
BUSD Token contract doesn't have name(), symbol() and decimals() methods

### ISSUE THREAD

**Issue by mahnunchik** [tronprotocol/java-tron#5122]
BUSD Token contract doesn't have `name()`, `symbol()` and `decimals()` methods. 

https://tronscan.org/#/token20/TMz2SWatiAtZVVcH2ebpsbVtYwUPT9EdjH

#### Expected behaviour

Contract has TRC20 methods

#### Actual behaviour

Contract doesn't have such methods

#### Steps to reproduce the behaviour

Call contract methods by any library.

Related issue: https://github.com/tronprotocol/tronweb/issues/356

**Comment by sunflower-sun** [comment]
It is a proxy contract, you can get the name and symbol information from its implementation contract which can be get on tronscan by clicking "Contract" -> "Read as proxy".

**Comment by mahnunchik** [comment]
@sunflower-sun thank you for the clarification. Maybe you know how to access that methods with https://github.com/tronprotocol/tronweb library?

**Comment by sunflower-sun** [comment]
> @sunflower-sun thank you for the clarification. Maybe you know how to access that methods with https://github.com/tronprotocol/tronweb library?

Just pass the implementation contract's address to tronweb api. https://tronweb.network/docu/docs/Interact%20with%20contract#call

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by WheresPizza** [comment]
@sunflower-sun it wont work for BUSD still, you'll get decimals is undefined, and how im gonna pass implementation if i dont have ABI of BUSD?

**Comment by ferdinand026** [comment]
@WheresPizza For upgradeable token, there are two contracts: one is the proxy contract (BUSD token contract), the other is the implementation contract (there are name(), decimals() method in it). And if we want to get the decimals using tronweb, the steps are:
1. get the BUSD token contract
2. obtain the implementation contract address
3. obtain the ABI of the implementation contract address
4. get the decimals through BUSD token contract address and the ABI of the implementation contract address

**Comment by WheresPizza** [comment]
@ferdinand026 right, i did it already, but wondering if there is a way to obtain such information through tron lib or whatever else in one place/automatically, just to not to store or request full abi for these kind of tokens?

**Comment by ferdinand026** [comment]
@WheresPizza Sorry, it cannot be automatically. If we only want to access decimals() method, we can just copy the decimals's ABI from tronscan, but not all abi.
