### ISSUE TITLE
Why node stop syncing for one hour occasionally?

### ISSUE THREAD

**Issue by KaiQiu9527** [tronprotocol/java-tron#5125]
System information
java-tron version: java -jar FullNode.jar -v
OS : Linux
JVM : Oracle Corporation 1.8.0_131 amd64
Git : https://github.com/tronprotocol/java-tron/commit/da2673cd28e368b68c9a8056b7c3aa15ec880bf7
Version : 4.7.1
Code : 17673

Machine Flavor: 16u32g with 2T hdd and 20Mbit/s bandwidth

1. What did you do?

I downloaded the snapshot archived on April 3rd, and start tron fullnode with the snapshot today.

2. What did you expect to see?
The node should run well and will catch up the lastest block in about 14 hours.

3. What did you see instead?
The syncing of Block has always been suspended for one hour. I ran a background shell which call "eth_syncing" in 5 seconds period, and it shows the syncing process. It seems like the node is always "banned" by all the other nodes for one hour each time. I wonder why this always happens? I attach the fullnode log named "tron-2023-04-10.0.log.gz" and the backgound running shell log named "count.log". According to the logs, the syncing process stop time are "10:35:40-11:23:28" "12:49:08-13:13:41" "13:40:06-14:39:40" "14:40:25-15:40:25" "15:44:51-16:44:45" "16:55:07-17:55:07" "17:55:37-18:55:16" "18:56:01-19:32:47". On 19:32:47 I restarted the fullnode process.
[count.log](https://github.com/tronprotocol/java-tron/files/11190525/count.log)

P.S. The tron log is too large and I upload it to google drive :）
https://drive.google.com/file/d/14bqps9pAGJR-LEkeVIXKZzo2P7ytG02L/view?usp=sharing

**Comment by ExOCeo** [comment]
It seems like node 47.90.254.215 is tossing manipulated blocks so that your node disconnected all other nodes that had these blocks, this happens periodically as long as you sync from 47.90.254.215 and it produces questionable blocks.

**Comment by ExOCeo** [comment]
@Bellgin he may ban it in the firewall, eliminating any traffic with that IP.

**Comment by KaiQiu9527** [comment]
> It seems like node 47.90.254.215 is tossing manipulated blocks so that your node disconnected all other nodes that had these blocks, this happens periodically as long as you sync from 47.90.254.215 and it produces questionable blocks.

Thanks ExoCeo. I redownload the latest snapshot and restart the sync using it, It runs well this time. Thanks~
