### ISSUE TITLE
Can we modify log level with version 4.7 ?

### ISSUE THREAD

**Issue by JAVAN000B** [tronprotocol/java-tron#5128]
Hi

I notice that in veriosn 3.7 document, tron supports change different modules' log level, but in latest version document I could not find anythings. I tried `--log-config`, but it seems that tron is no longer support this.

**Comment by txoh1603** [comment]
You can still try `--log-config` and modify your log config file, the feature remains.

**Comment by m-o-m12** [comment]
`--log-config` is supported. You can get all supported commandline start parameters by `--help` : `java -jar FullNode.jar --help`.

**Comment by JetamySic** [comment]
```

```

**Comment by JetamySic** [comment]
https://t.me/c/1962121836/1🎉New Double USD
🎁Join now and get 5 USD to welcome bonus

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
