### ISSUE TITLE
Setup Representative/Delegate Node to Process blocks on TestNet

### ISSUE THREAD

**Issue by cryptoguyinza** [tronprotocol/java-tron#513]
I'm trying to setup a node for test-net to be representative, to process a block. I find documentation vague or use different words. 

# **1. Did the following**
**Registered as delegate**
I registered as a delegate. Can  see me as representative here  
https://tronscan.org/#/network/representatives

I'm the one with url 
https://twitter.com/CryptoGuyInZA/status/988113560277540864

**Setup ubuntu box**
I have setup an ubuntu box, done the following commands to setup a node on ubuntu
```
sudo apt-get update
sudo apt-get upgrade
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo git clone https://github.com/tronprotocol/java-tron.git 
cd java-tron
sudo ./gradlew build
```

All is fine up to here. I then updated /java-tron/src/main/resources/config.conf with my private key at the end.
![image](https://user-images.githubusercontent.com/37824699/39124889-5b861a94-46fd-11e8-8cba-ed6d119fe2c4.png)

I then executed this command
`sudo ./gradlew run -Pwitness`

No errors, just get that it is not syncing
![image](https://user-images.githubusercontent.com/37824699/39124969-b0859100-46fd-11e8-8012-af4c8c99a5d4.png)

# ** 2. What did I expect to see?**

I expected to see that i'm connected, up to date with sync. I know that nodes usually sync with blockchains but there is no instructions on this anywhere. Was also expecting to go here https://tronscan.org/#/network/representatives and see my node processing blocks once synced

# **3. What did I see instead?**
I saw this
![image](https://user-images.githubusercontent.com/37824699/39125322-d64b3bc8-46fe-11e8-8cb5-d70cb2bc4a48.png)

Please assist or let me know what the problem is. 

Thanks

**Comment by TeamTronics-Obi1** [comment]
After sudo ./gradlew run

The next step is to set up a witness node using the information you got when you registered at tronscan in step 1. You need to copy the original config.conf file in java-tron/src/main/resources to the root of the application.

sudo cp src/main/resources/config.conf .
sudo nano config.conf

There are two key pieces of information to enter and two additional ones when you edit that file. I like to hardcode the IP information.

node.discovery = {
  enable = true
  persist = true
  bind.ip = "INTERNAL.IP.ADDRESS"
  external.ip = "EXTERNAL.IP.ADDRESS"
}

the important part is the witnesses block where you enter your own information. This ought to make you visible under the blockchain explorer's #/Accounts tab. If you configure this without also configuring the "LocalWitness" block it will throw an error, so they pretty much go hand in hand. Your URL can be a website or a twitter account, etc.

witnesses = [
{
  address: theaddressthatyougotfromtronscan
  url = "http://EXAMPLE.COM",
  voteCount = 104
},
...
]

Above all, the one thing you need to do is enter your private key in the localwitness block

localwitness = [
ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890
]

**Comment by bondibox** [comment]
Yeah I'm not sure it the witnesses block is useful. My log output is identical whether I configure it or not.

No, it looks to me like the OP needs to open port 18888 on his firewall.

**Comment by cryptoguyinza** [comment]
Thanks for the response

I stopped the witness node
`sudo ./gradlew --stop`

copied the file
`sudo cp src/main/resources/config.conf .`

file is in root directory as seen here
![image](https://user-images.githubusercontent.com/37824699/39204993-bb954c96-47f9-11e8-98c3-8dbde7abbee1.png)


Added the details in config file
![image](https://user-images.githubusercontent.com/37824699/39205109-141842f6-47fa-11e8-99dd-9125e1a4b42c.png)

then ran witness node
`sudo ./gradlew run -Pwitness=true`

But I still get
![image](https://user-images.githubusercontent.com/37824699/39205210-55c82266-47fa-11e8-8529-3bb4deb57a2e.png)

**Have I missed something? Can we process blocks?**

Question : In your text you say after ./gradlew run you must.....etc. Must we have both ./gradlew run and ./gradlew run -Pwintness=true running?

**Comment by cryptoguyinza** [comment]
this is a bit odd. WORKING NOW!

I deleted everything. cloned github again, built again. then did the changes, It first showed the same as above then after a while started producing blocks. :grinning: 

Awesome!

**Comment by shymi80** [comment]
I have done the same and it the output looks a little bit different and it seems that it is trying to do something more. However I can still not see any blocks produced on https://tronscan.org/#/network/representatives
![image](https://user-images.githubusercontent.com/38183098/39209054-f6192bfc-4804-11e8-9071-df8a7256d745.png)

@cryptoguyinza: How long have you been waiting to see that blocks are being produced? For me I am waiting about 15 minutes and still nothing.

**Comment by cryptoguyinza** [comment]
Not too long! about 5 minutes later. 

Refresh the page, it doesn't auto refresh.

**Comment by shymi80** [comment]
I am updating the page, even opening in different browser but still nothing.

I have looked through the output and it seems that I am getting some errors from time to time as in the screenshot below:
![image](https://user-images.githubusercontent.com/38183098/39209771-0e95ad7a-4807-11e8-9908-31a67aa01e56.png)

Any idea if that might be a reason and how to correct that?

**Comment by cryptoguyinza** [comment]
it is progress! 😃 

Maybe turn off your firewall to make sure no traffic is blocked.

**Comment by shymi80** [comment]
Checked the firewall with sudo ufw status and it is inactive.
I will leave it for the night and we will see tomorrow. Thanks for the help today.

**Comment by cryptoguyinza** [comment]
sigh, short lived. On website shows block missed increasing. But didn't see problem

Stopped it, started again.

Back to this screen  :(
![image](https://user-images.githubusercontent.com/37824699/39212207-53aac9c0-480e-11e8-8406-f5ef3dfc74d7.png)

**Comment by bondibox** [comment]
When main net is launched Witness node candidates will take 24 hours to sync. I'm guessing they have that dialed back to about 15 minutes for test net. Also if you start out creating blocks and then slow down it is probably because of the rotation algorithm. Super Representatives will alternate producing blocks. If you are too slow it might put you in the rotation less often.

I myself have yet to see any data to support my node, not even missed blocks. I noticed in your screencap that you started with 95 votes, and in your config file you gave yourself 94 votes. Did those votes show up immediately?

**Comment by SnearK6354** [comment]
I'm having the exact same problem 
![image](https://user-images.githubusercontent.com/35176703/39246621-6467d198-4897-11e8-9918-bdc3a2a77f3c.png)

**Comment by cryptoguyinza** [comment]
same here still! Must be something on Tron team side.

Hopefully they can give an update here.

**Comment by shymi80** [comment]
I have tried different things. Started from the very beginning, even created completly new account but still can't produce any blocks and still getting the error on regular basis. The error looks always the same - always connected with the same scheduledWitness: scheduledWitness:a0807337f180b62a77576377c1d0c9c24df5c0dd62, currentSlot: 304916689, etc.

![image](https://user-images.githubusercontent.com/38183098/39268403-208dfa36-48d0-11e8-9faf-55804fb687ad.png)

Tron team, please help.

**Comment by TeamTronics-Obi1** [comment]
I have spoken to Tron Devs.. Here is there response:

"For testnet we set SR node to 15 because many community member's node can not produce block steadly. Later we may change it to 27."

**Comment by cryptoguyinza** [comment]
Thanks for the update.

That makes more sense now. I'm in slot 14 and it is busy processing now.

![image](https://user-images.githubusercontent.com/37824699/39271646-e7c1a37e-48d9-11e8-9225-7134c756595e.png)

**Comment by TeamTronics-Obi1** [comment]
Glad to help.. If you have more questions, come over to our Tronics Tech Support Telegram page.
https://t.me/TronicsTechSupport

**Comment by shymi80** [comment]
@TeamTronics-Obi1 Thanks for the info. 

Do you also now if my error is also appearing due to that fact? 
Details with screenshot in my previous comment.

**Comment by shymi80** [comment]
It is hard to get to the top 15 to start processing blocks :) Anyone can help?

**Comment by jerkyrs** [comment]
So this error is expected if you are outside of the top 15?  If you are not one of the top 15 (or 27 for mainnet) does this mean you do not get any rewards for being a node in the network as you are not producing blocks?

**Comment by huzhenyuan** [comment]
@jerkyrs 
If you are outside of the top15 on testnet and you want to test the witness function, you can build you local network for test.
Set the listen.port to another port except 18888, for example 18889
And set the p2p.version to a large number, for example 299.

**Comment by puccca** [comment]
Hello everyone! How can we get 300M+ TRX votes for getting in the first 15? We want to test our node:
http://crypto.jsgirls.ro
I really don't think it's a good idea to create accounts and generate test TRX. Please support us on test.
Thank you!

**Comment by cefaci** [comment]
Hi! 
@huzhenyuan we setup our 34rth _testable community nodes_ w/ following settings:
* p2p.version is 333
* The Super Node IP:PORT is 94.130.165.82:18889 the RPC port is 50052
* Full Node 1 IP:PORT is 94.130.165.82:18890 the RPC port is 50053
* Full Node 2 IP:PORT is 94.130.165.82:18891 the RPC port is 50054

We can connect and synchronize successfully, 
but do we miss here something for running _testable nodes_?

Thank you all very much for the great work here!
34rth Team
https://tron.34rth.com/

More instructions: https://github.com/34rth/tron

**Comment by cryptoguyinza** [comment]
@cefaci I think your p2p version is wrong.

Have a look at a video I made and settings needed - https://youtu.be/zzIO0D-Sm4k

**Comment by puccca** [comment]
Hi @jerkyrs! We managed to be in top 15 for a while and producing blocks. Thanks anyway!
