### ISSUE TITLE
It keeps getting stuck at block 1628390 on TestNet.

### ISSUE THREAD

**Issue by junghyun0783** [tronprotocol/java-tron#5152]
### System information

java-tron version: `java -jar GreatVoyage-v4.7.1/FullNode.jar -v`
OS & Version: Linux

It keeps getting stuck at block 1628390 on testnet.
After looking around the issue... there are many answers asking to get a backup database...
Is this the only way to solve it?
Is there any other way?
I'm wondering if there is any other way than backing up the data.

### 1. What did you do?
Synchronized testnet block.

### 2. What did you expect?
block synchronized scene

### 3. What did you see instead?
Stopping at block number 1628390
![블록 390](https://user-images.githubusercontent.com/25001497/232431524-f5f74989-23cf-4fb8-97c2-8a5c06388a17.png)

**Comment by okwapa210** [comment]
Nile can't sync from 0 block, looks like using the backup database is the only option.

**Comment by junghyun0783** [comment]
Aha that's right!
Then you can't receive the block from beginning to end... Why did you make it this way? I have my doubts.

**Comment by forfreeday** [comment]
@okwapa210 
Is the profile you are using a Nile profile

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
