### ISSUE TITLE
Is there any more detailed document about TRON node APIs?

### ISSUE THREAD

**Issue by CooperDepp** [tronprotocol/java-tron#5163]
There is not any remark for the return of calling APIs on TRON network at all, it's hard to know the meaning of information returned. Using interfaces with unclear meaning is fatal to the financial system.

**Comment by Ocea91** [comment]
yep, same question, especially the interpretation of the return fields and items, someone asked this question as well in another issue

**Comment by vivian-kang** [comment]
Thanks for your feedback, yes, now only a few APIs have return value descriptions, for example, `/wallet/getaccount`. And we have added this issue to the schedule and will complete the return value description of all querying APIs as soon as possible.

**Comment by vivian-kang** [comment]
The detailed return information has been added to the querying APIs of fullnode, please refer to https://developers.tron.network/reference/full-node-api-overview.  Thanks.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
