### ISSUE TITLE
Votes dons work on https://tronscan.org/#/network/representatives

### ISSUE THREAD

**Issue by cryptoguyinza** [tronprotocol/java-tron#517]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Voted on https://tronscan.org

2. What did you expect to see?
Success message is seen. But when you go back in you cant see where you voted, cant change the votes, cant adjust votes. Also once succeed you should be able to see the votes cast. There should be columns showing active votes, new votes, etc.

3. What did you see instead?
When you go back in you see nothing. So you pray and hope the next day the votes took.

**Comment by cryptoguyinza** [comment]
The following in addition to countdown would be nice for mainnet.
-see addresses that voted for SR on block explorer with vote/tron weight
-be able to unvote and vote for new SR. So if SR doesn't perform change to another SR
-more info of status of SR nodes, is node up/down. Last time block produced, etc
-show active SR differently from inactive SR

**Comment by bondibox** [comment]
> be able to unvote and vote for new SR. So if SR doesn't perform change to another SR
This is already a feature unbeknownest to most people you can re-vote as often as you like before the deadline. You can change your mind as many times as you like, only the last vote entry will count. So if you have 100,000 votes and you put them all on Game.com and later that day you change your mind and want to vote Peiwo with 1/2 of them you can. Or you can decide to just vote half the TRX and leave the rest to spoil. The point is, if you vote 90,000 votes and come back and vote 10,000 votes, at the end of the day you will only have exercised 10,000 votes.
