### ISSUE TITLE
Tron

### ISSUE THREAD

**Issue by tethert** [tronprotocol/java-tron#5183]

**Comment by tethert** [comment]
{
"name":"JustSwap Default List",
"tokens":[
  {

     "symbol":"SUN",

     "address":"TWMvfHDaNThsYwSbRdDSk7nXvwrkNX1maQ",

     "chainId":1,

     "decimals":18,

     "name":"SUN TOKEN",

     "logoURI":"https://docs.github.com/site-policy/github-terms/github-terms-of-service"

  },

  {

     "symbol":"MXNT",

     "address":"TQVBKz6evh9y8U6VzyZJZUnj1xgT8qRgpU",

     "chainId":1,

     "decimals":18,

     "name":"MexicanPesoToken",

     "logoURI":"https://static.tronscan.org/production/upload/logo/TQVBKz6evh9y8U6VzyZJZUnj1xgT8qRgpU.jpeg?t=1617910788962"

  },

  {

     "symbol":"NUBA",

     "address":"TGFrczzD5Uj4SM8d4xdousZSxgt4to2htX",

     "chainId":1,

     "decimals":18,

     "name":"NubaHealthTech",

     "logoURI":"https://static.tronscan.org/production/upload/logo/TGFrczzD5Uj4SM8d4xdousZSxgt4to2htX.jpeg?t=1617925518503"

  },

  {

     "symbol":"BTC",

     "address":"TJf3oS92wpD2A9EX173Eu9aU8psEoLS66M",

     "chainId":1,

     "decimals":8,

     "name":"Bitcoin",

     "logoURI":"https://coin.top/production/logo/TJf3oS92wpD2A9EX173Eu9aU8psEoLS66M.png"

  },

  {

     "symbol":"WBTC",

     "address":"TViiqPZYZ8FUrpZqWVhkg8ZoEnNh3QCp1G",

     "chainId":1,

     "decimals":8,

     "name":"Wrapped BTC",

     "logoURI":"https://coin.top/production/logo/TViiqPZYZ8FUrpZqWVhkg8ZoEnNh3QCp1G.png"

  },

  {

     "symbol":"ETH",

     "address":"TWo7aNcmFcsBT4WsenPqYQUjwqtC321cvJ",

     "chainId":1,

     "decimals":18,

     "name":"Ethereum",

     "logoURI":"https://coin.top/production/logo/TWo7aNcmFcsBT4WsenPqYQUjwqtC321cvJ.png"

  },

  {

     "symbol":"WETH",

     "address":"TSqjdpTatNpq66jVhbeoHeojjSsEMgD8TP",

     "chainId":1,

     "decimals":18,

     "name":"Wrapped ETH",

     "logoURI":"https://coin.top/production/logo/TSqjdpTatNpq66jVhbeoHeojjSsEMgD8TP.png"

  },

  {

     "symbol":"WBTT",

     "address":"TKYX4pBfhWSMyNHHaRLebacxYTHQcaeLJT",

     "chainId":1,

     "decimals":6,

     "name":"Wrapped BitTorrent",

     "logoURI":"https://coin.top/production/logo/TKYX4pBfhWSMyNHHaRLebacxYTHQcaeLJT.png"

  },

  {

     "symbol":"WTRX",

     "address":"THLFxd1iBHWBwQKHaKccKDZRzs5ucgpkBy",

     "chainId":1,

     "decimals":6,

     "name":"Wrapped TRX",

     "logoURI":"https://coin.top/production/upload/logo/THLFxd1iBHWBwQKHaKccKDZRzs5ucgpkBy.png"

  },

  {

     "symbol":"JST",

     "address":"TLB64V2rUfQMbLGCBcCGxALURP8mzaRp5M",

     "chainId":1,

     "decimals":18,

     "name":"JUST GOV v1.0",

     "logoURI":"https://coin.top/production/logo/just_icon.png"

  },

  {

     "symbol":"WIN",

     "address":"TLB64V2rUfQMbLGCBcCGxALURP8mzaRp5M",

     "chainId":1,

     "decimals":6,

     "name":"WINK",

     "logoURI":"https://coin.top/profile_images/JKtJTydD_400x400.jpg"

  },

  {

     "symbol":"DICE",

     "address":"TCAkhex72FbLUuPQaCqAxbX7kHiytXLjmJ",

     "chainId":1,

     "decimals":6,

     "name":"TRONbetDice",

     "logoURI":"https://coin.top/production/logo/TCAkhex72FbLUuPQaCqAxbX7kHiytXLjmJ.jpg"

  },

  {

     "symbol":"LIVE",

     "address":"TRkePZKCmwYARpQiakja1p1RTALHtuyhWV",

     "chainId":1,

     "decimals":6,

     "name":"TRONbetLive",

     "logoURI":"https://coin.top/production/upload/logo/TRkePZKCmwYARpQiakja1p1RTALHtuyhWV.png"

  },

  {

     "symbol":"USDT",

     "address":"TSgjCpwCd7FhYrnx8rsTv4AFqpk3eo9rwZ",

     "chainId":1,

     "decimals":6,

     "name":"Tether USD",

     "logoURI":"https://coin.top/production/logo/usdtlogo.png"

  },

  {

     "symbol":"USDJ",

     "address":"TH2MB1oV4b7oPQ6oM99FiWoiu9dPL4yP8d",

     "chainId":1,

     "decimals":18,

     "name":"JUST Stablecoin v1.0",

     "logoURI":"https://coin.top/production/logo/usdj.png"

  },

  {

     "symbol":"LTC",

     "address":"TRcbSbc3HJWxU7rzScNJBEs7M9ktKH7Xao",

     "chainId":1,

     "decimals":8,

     "name":"Litecoin",

     "logoURI":"https://coin.top/production/logo/THSgGExL6YEPH5ebRXutfyojf8nBqshCh2.png"

  },

  {

     "symbol":"HT",

     "address":"THSgGExL6YEPH5ebRXutfyojf8nBqshCh2",

     "chainId":1,

     "decimals":18,

     "name":"HuobiToken",

     "logoURI":"https://coin.top/production/logo/TM8fAzrg7gFuBktzpjMoaRKGtvZscxFCoy.png"

  }
],
"logoURI":"https://justswaporg/justlists",
"version":{
  "patch":1,

  "major":1,

  "minor":0
},
"timestamp":1611147166000
}
—

**Comment by tethert** [comment]
> {
> "name":"JustSwap Default List",
> "tokens":[
>   {
> 
>      "symbol":"SUN",
> 
>      "address":"TWMvfHDaNThsYwSbRdDSk7nXvwrkNX1maQ",
> 
>      "chainId":1,
> 
>      "decimals":18,
> 
>      "name":"SUN TOKEN",
> 
>      "logoURI":"https://docs.github.com/site-policy/github-terms/github-terms-of-service"
> 
>   },
> 
>   {
> 
>      "symbol":"MXNT",
> 
>      "address":"TQVBKz6evh9y8U6VzyZJZUnj1xgT8qRgpU",
> 
>      "chainId":1,
> 
>      "decimals":18,
> 
>      "name":"MexicanPesoToken",
> 
>      "logoURI":"https://static.tronscan.org/production/upload/logo/TQVBKz6evh9y8U6VzyZJZUnj1xgT8qRgpU.jpeg?t=1617910788962"
> 
>   },
> 
>   {
> 
>      "symbol":"NUBA",
> 
>      "address":"TGFrczzD5Uj4SM8d4xdousZSxgt4to2htX",
> 
>      "chainId":1,
> 
>      "decimals":18,
> 
>      "name":"NubaHealthTech",
> 
>      "logoURI":"https://static.tronscan.org/production/upload/logo/TGFrczzD5Uj4SM8d4xdousZSxgt4to2htX.jpeg?t=1617925518503"
> 
>   },
> 
>   {
> 
>      "symbol":"BTC",
> 
>      "address":"TJf3oS92wpD2A9EX173Eu9aU8psEoLS66M",
> 
>      "chainId":1,
> 
>      "decimals":8,
> 
>      "name":"Bitcoin",
> 
>      "logoURI":"https://coin.top/production/logo/TJf3oS92wpD2A9EX173Eu9aU8psEoLS66M.png"
> 
>   },
> 
>   {
> 
>      "symbol":"WBTC",
> 
>      "address":"TViiqPZYZ8FUrpZqWVhkg8ZoEnNh3QCp1G",
> 
>      "chainId":1,
> 
>      "decimals":8,
> 
>      "name":"Wrapped BTC",
> 
>      "logoURI":"https://coin.top/production/logo/TViiqPZYZ8FUrpZqWVhkg8ZoEnNh3QCp1G.png"
> 
>   },
> 
>   {
> 
>      "symbol":"ETH",
> 
>      "address":"TWo7aNcmFcsBT4WsenPqYQUjwqtC321cvJ",
> 
>      "chainId":1,
> 
>      "decimals":18,
> 
>      "name":"Ethereum",
> 
>      "logoURI":"https://coin.top/production/logo/TWo7aNcmFcsBT4WsenPqYQUjwqtC321cvJ.png"
> 
>   },
> 
>   {
> 
>      "symbol":"WETH",
> 
>      "address":"TSqjdpTatNpq66jVhbeoHeojjSsEMgD8TP",
> 
>      "chainId":1,
> 
>      "decimals":18,
> 
>      "name":"Wrapped ETH",
> 
>      "logoURI":"https://coin.top/production/logo/TSqjdpTatNpq66jVhbeoHeojjSsEMgD8TP.png"
> 
>   },
> 
>   {
> 
>      "symbol":"WBTT",
> 
>      "address":"TKYX4pBfhWSMyNHHaRLebacxYTHQcaeLJT",
> 
>      "chainId":1,
> 
>      "decimals":6,
> 
>      "name":"Wrapped BitTorrent",
> 
>      "logoURI":"https://coin.top/production/logo/TKYX4pBfhWSMyNHHaRLebacxYTHQcaeLJT.png"
> 
>   },
> 
>   {
> 
>      "symbol":"WTRX",
> 
>      "address":"THLFxd1iBHWBwQKHaKccKDZRzs5ucgpkBy",
> 
>      "chainId":1,
> 
>      "decimals":6,
> 
>      "name":"Wrapped TRX",
> 
>      "logoURI":"https://coin.top/production/upload/logo/THLFxd1iBHWBwQKHaKccKDZRzs5ucgpkBy.png"
> 
>   },
> 
>   {
> 
>      "symbol":"JST",
> 
>      "address":"TLB64V2rUfQMbLGCBcCGxALURP8mzaRp5M",
> 
>      "chainId":1,
> 
>      "decimals":18,
> 
>      "name":"JUST GOV v1.0",
> 
>      "logoURI":"https://coin.top/production/logo/just_icon.png"
> 
>   },
> 
>   {
> 
>      "symbol":"WIN",
> 
>      "address":"TLB64V2rUfQMbLGCBcCGxALURP8mzaRp5M",
> 
>      "chainId":1,
> 
>      "decimals":6,
> 
>      "name":"WINK",
> 
>      "logoURI":"https://coin.top/profile_images/JKtJTydD_400x400.jpg"
> 
>   },
> 
>   {
> 
>      "symbol":"DICE",
> 
>      "address":"TCAkhex72FbLUuPQaCqAxbX7kHiytXLjmJ",
> 
>      "chainId":1,
> 
>      "decimals":6,
> 
>      "name":"TRONbetDice",
> 
>      "logoURI":"https://coin.top/production/logo/TCAkhex72FbLUuPQaCqAxbX7kHiytXLjmJ.jpg"
> 
>   },
> 
>   {
> 
>      "symbol":"LIVE",
> 
>      "address":"TRkePZKCmwYARpQiakja1p1RTALHtuyhWV",
> 
>      "chainId":1,
> 
>      "decimals":6,
> 
>      "name":"TRONbetLive",
> 
>      "logoURI":"https://coin.top/production/upload/logo/TRkePZKCmwYARpQiakja1p1RTALHtuyhWV.png"
> 
>   },
> 
>   {
> 
>      "symbol":"USDT",
> 
>      "address":"TSgjCpwCd7FhYrnx8rsTv4AFqpk3eo9rwZ",
> 
>      "chainId":1,
> 
>      "decimals":6,
> 
>      "name":"Tether USD",
> 
>      "logoURI":"https://coin.top/production/logo/usdtlogo.png"
> 
>   },
> 
>   {
> 
>      "symbol":"USDJ",
> 
>      "address":"TH2MB1oV4b7oPQ6oM99FiWoiu9dPL4yP8d",
> 
>      "chainId":1,
> 
>      "decimals":18,
> 
>      "name":"JUST Stablecoin v1.0",
> 
>      "logoURI":"https://coin.top/production/logo/usdj.png"
> 
>   },
> 
>   {
> 
>      "symbol":"LTC",
> 
>      "address":"TRcbSbc3HJWxU7rzScNJBEs7M9ktKH7Xao",
> 
>      "chainId":1,
> 
>      "decimals":8,
> 
>      "name":"Litecoin",
> 
>      "logoURI":"https://coin.top/production/logo/THSgGExL6YEPH5ebRXutfyojf8nBqshCh2.png"
> 
>   },
> 
>   {
> 
>      "symbol":"HT",
> 
>      "address":"THSgGExL6YEPH5ebRXutfyojf8nBqshCh2",
> 
>      "chainId":1,
> 
>      "decimals":18,
> 
>      "name":"HuobiToken",
> 
>      "logoURI":"https://coin.top/production/logo/TM8fAzrg7gFuBktzpjMoaRKGtvZscxFCoy.png"
> 
>   }
> ],
> "logoURI":"https://justswaporg/justlists",
> "version":{
>   "patch":1,
> 
>   "major":1,
> 
>   "minor":0
> },
> "timestamp":1611147166000
> }
> —

**Comment by vivian-kang** [comment]
For justlist issue, please report your issue on its repository https://github.com/justswaporg/justlists . Thanks.
