### ISSUE TITLE
I withdraw to the scam wallet addtess USDT TRC20 can be reverse, i want to back my transanction to my OKX account my

### ISSUE THREAD

**Issue by sana200x** [tronprotocol/java-tron#5191]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS & Version: Windows/Linux/OSX

### 1. What did you do?
i withdraw my USDT TRC20 to scam Address TRX ID: a9f53ddab59bffcb7d575a9dd588a64986d95448176417b2f09d10f0dd42de28
i want to reverse this transaction to back my OKX account.

### 2. What did you expect to see?
I want to Reverse Transaction USDT TRC20 back money to my OKX account

### 3. What did you see instead?
USDT 320 Transfer to scam wallet need help plz

**Comment by m-o-m12** [comment]
Due to the characteristics of blockchain, on-chain transaction can not be reverted. No centralized system controls the accounts.

**Comment by sana200x** [comment]
is there any possibility to back my money i took loan 320 USDT which i stuck i have to pay back this amount. any body help me plz
if its not possible then share me the legit website without investment earn USDT i have to return this loan. plz HELP

**Comment by Yessika224** [comment]
> is there any possibility to back my money i took loan 320 USDT which i stuck i have to pay back this amount. any body help me plz
> if its not possible then share me the legit website without investment earn USDT i have to return this loan. plz HELP

Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by sana200x** [comment]
> 

i contact him i hope he help

**Comment by sana200x** [comment]
> > is there any possibility to back my money i took loan 320 USDT which i stuck i have to pay back this amount. any body help me plz
> > if its not possible then share me the legit website without investment earn USDT i have to return this loan. plz HELP
> 
> Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

thanks for giving this contact i contact him i hope he help me

**Comment by Yessika224** [comment]
> > > is there any possibility to back my money i took loan 320 USDT which i stuck i have to pay back this amount. any body help me plz
> > > if its not possible then share me the legit website without investment earn USDT i have to return this loan. plz HELP
> > 
> > 
> > Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111
> 
> thanks for giving this contact i contact him i hope he help me

Yeah message him

**Comment by m-o-m12** [comment]
@sana200x nobody can revert the the transaction or get back the asset. Please do not trust anyone who can help you get your assets back.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
