### ISSUE TITLE
backup download speed from 47.74.159.117 in kilobytes

### ISSUE THREAD

**Issue by nateless** [tronprotocol/java-tron#5192]
Hello,

We are trying to download archive from http://47.74.159.117/saveInternalTx/backup20230501/ and current ETA is 60+ days, with the average speed in hundreds of Kbs.. 

Can you increase bandwidth for the server or install additional servers?

**Comment by L-Reid** [comment]
Try at another time, finish downloading the whole backup database within one or two days is feasible.

**Comment by sunflower-sun** [comment]
@nateless you can download the snapshot at https://backup.trongrid.io/ and select the closest region to speed up the process. The snapshot includes the internal transactions.

**Comment by nateless** [comment]
@sunflower-sun here it says that data does not include internal transactions: https://github.com/tronprotocol/java-tron/issues/5089#issuecomment-1482210689

**Comment by sunflower-sun** [comment]
https://backup.trongrid.io/  includes the internal transactions, please have a try.
