### ISSUE TITLE
DB corruption repair failed in private chain

### ISSUE THREAD

**Issue by KaiQiu9527** [tronprotocol/java-tron#5194]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS : Linux
JVM : Oracle Corporation 1.8.0_131 amd64
Git : https://github.com/tronprotocol/java-tron/commit/da2673cd28e368b68c9a8056b7c3aa15ec880bf7
Version : 4.7.1
Code : 17673
Chain: local private chain

### 1. What did you do?

I hava built up a private tron chain on a cloud machine with a SR Fullnode, and run some fullnodes on other machines.
I'm tesing the robust of tron fullnode. I run a node in a k8s cluster, and run tron fullnode as a container inside a k8s pod.
I did the test by following the steps: shutdown vm -> start vm -> wait for about 2 minutes -> shutdown vm -> start vm.

### 2. What did you expect to see?
I expect that the tron fullnode process can run well and the syncing process will recover ASAP.

### 3. What did you see instead?
The pod crashLoopback. When I check the tron log, it shows that the fullnode process tried to fix the DB corruption but failed, and finally "Can not find Dynamic highest block from DB. Please delete database directory(/workdir) and restart" and the pod restarted. 
It's a low-probability event that the probability could be lower than 10% or even 5%.
![image](https://user-images.githubusercontent.com/16130943/236371572-0b570e11-bf68-4297-af5e-65da21e2be20.png)
[tron.log](https://github.com/tronprotocol/java-tron/files/11403064/tron.log)
I think that it's normal for some unavoidable situations like restart the vm / process killed by oom, etc. I wonder why the error happened and how to fix it instead of rebuilding the database, which may take some days to recover the syncing process.
Thanks!

**Comment by hitlxy** [comment]
I know there is a checkpoint mechanism, you can try it according to below article. The fourth in Core: https://coredevs.medium.com/greatvoyage-v4-6-0-socrates-release-note-c5b68423eff2

**Comment by guoquanwu** [comment]
Theoretically, Database corruption is often caused by disk flush failure, the most common scenario is that the machine is down while the data is being written to the disk. So TRON will pre-write data to a temporary db to ensure data recovery after crash, the temporary db is called `tmp`, but I find the `tmp` db is even corrupted in the log.
The root reason is why the `tmp` db corrupted. It depends on many conditions:
- `kill -9` is safe, but there is a certain probability that the machine crash will cause the database to be corrupted
- How did you stop the container, normal shutdown or kill the process of the container?
- How did you mount the disk of the container, using a external disk or just using the default disk in the container?
- Is the cloud machine strong enough? Can it ensure that data will be flushed to disk in various abnormal scenarios？

**Comment by lurais** [comment]
Hello, as I can see from the log, leveldb file is corrupted ,many reason shall be the cause , but it is clear that when you stop the tron service, leveldb has not finished the data write operation, youcan refer to some blog like this:(https://lonesysadmin.net/2013/12/22/better-linux-disk-caching-performance-vm-dirty_ratio/) if you want to know more detail .

**Comment by KaiQiu9527** [comment]
> I know there is a checkpoint mechanism, you can try it according to below article. The fourth in Core: https://coredevs.medium.com/greatvoyage-v4-6-0-socrates-release-note-c5b68423eff2

Thanks hitlxy, the checkpoint v2 is really helpful!

**Comment by KaiQiu9527** [comment]
> Theoretically, Database corruption is often caused by disk flush failure, the most common scenario is that the machine is down while the data is being written to the disk. So TRON will pre-write data to a temporary db to ensure data recovery after crash, the temporary db is called `tmp`, but I find the `tmp` db is even corrupted in the log. The root reason is why the `tmp` db corrupted. It depends on many conditions:
> 
> * `kill -9` is safe, but there is a certain probability that the machine crash will cause the database to be corrupted
> * How did you stop the container, normal shutdown or kill the process of the container?
> * How did you mount the disk of the container, using a external disk or just using the default disk in the container?
> * Is the cloud machine strong enough? Can it ensure that data will be flushed to disk in various abnormal scenarios？

Hi Quanwu, thanks for your info!
The tron database is located on an indepent disk which is mounted by pvc inside the k8s container. I have written "preStop" part in my k8s deployment yaml, which is called "Lifecycle PreStop Hook". If I kill the pod normally, the tron process will be killed by "-15", which is pretty safe. However, if I shutdown the virtual machine directly, the tron process will be kill immediately and sometime make the database crash. That should be the reason why this happened.
It seems like the checkpoint v2 works well after I trun it on in the config file.

**Comment by KaiQiu9527** [comment]
> Hello, as I can see from the log, leveldb file is corrupted ,many reason shall be the cause , but it is clear that when you stop the tron service, leveldb has not finished the data write operation, you can refer to some blog like this:(https://lonesysadmin.net/2013/12/22/better-linux-disk-caching-performance-vm-dirty_ratio/) if you want to know more detail .

Thanks lurais, the checkpoint v2 is really helpful!
