### ISSUE TITLE
message `there was an attack from your server` when running tron node

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5197]
I running tron node in my server,after 5 days,I get email from the server provider

email message : 
We have indications that there was an attack from your server.
Please take all necessary measures to avoid this in the future and to solve the issue.

We also request that you send a short response to us. This response should contain information about how this could have happened and what you intend to do about it.
In the event that the following steps are not completed successfully, your server can be blocked at any time after the 2023-05-04 20:12:21 +0200

this is my docker command to run tron node : 
docker run -d --name="java-tron" \
             -v /root/tron/output-directory:/java-tron/output-directory \
             -v /root/tron/logs:/java-tron/logs \
             -v /root/tron/main_net_config.conf:/java-tron/config/main_net_config.conf \
             --restart always \
             -p 8090:8090 -p 18888:18888 -p 50051:50051 -p 8091:8091 \
             tronprotocol/java-tron \
             -c /java-tron/config/main_net_config.conf

I think tron network scanning made a security bug for server provider
So,how can fix that or How can we limit the scanning of the port to some particular nodes or particular ports?

**Comment by forfreeday** [comment]
Which service provider's server you are running on
Whether the attack suggested in the email clearly states that the security issue is coming from tron's network, or some other definite indication.

**Comment by kasrakhamesi** [comment]
> Which service provider's server you are running on
> 
> Whether the attack suggested in the email clearly states that the security issue is coming from tron's network, or some other definite indication.


provider is Hetzner

I only running tron node in my server, only tron node with docker command.

so,problem should only for tron node

**Comment by guoquanwu** [comment]
As I know, TRON node only uses the UDP protocol for node discovery and the TCP protocol for data transmission when interacting with the outside, neither of them is malicious.
Is it convenient for you to communicate with the service provider to confirm the **type of attack** so that we can further investigate?

**Comment by dewebdes** [comment]
I have a similar issue: https://github.com/tronprotocol/java-tron/issues/5310#issue-1781375766

**Comment by asi90sp** [comment]
Ok

**Comment by halibobo1205** [comment]
Guessing this got resolved. Otherwise we can reopen.
