### ISSUE TITLE
The test files cannot import 'org.tron.protos' package correctly.

### ISSUE THREAD

**Issue by sepine** [tronprotocol/java-tron#5211]
Hi,

When I want to use the test cases, I found the following issues

The test files cannot import 'org.tron.protos' package correctly.

I currently use the latest develop branch from this repo.

Maybe the package name is wrong because I cannot find the package named 'org.tron.protos'.

@forfreeday  @yanghang8612

**Comment by forfreeday** [comment]
Have you already compiled the `protocol` project.

**Comment by sepine** [comment]
Thank you for your reply.

Actually, I have compiled all the project.

**Comment by sepine** [comment]
All the wrong things lie in the file Protocol.java. It cannot be properly considered a Class file after compilation. It reserves the original filename 'Protocol.java' in IDEA. Thus, it cannot be imported by other class.
![image](https://github.com/tronprotocol/java-tron/assets/28748734/5d713070-2610-48bc-9937-4f39ae1c4a68)

**Comment by chengtx01** [comment]
There is a prompt above the file window: "The file size exceeds the file size limit of IDEA". Appending "idea.max.intellisense.filesize=5000" to the file ‘idea.properties’ should solve your problem.

**Comment by sepine** [comment]
Many thanks for your help.

It is my first time I've had a problem like this, now it can work correctly.

Thank you !
