### ISSUE TITLE
Why FullNode's active peer number is below 10 and sync slowly

### ISSUE THREAD

**Issue by KaiQiu9527** [tronprotocol/java-tron#5214]
### System information

OS : Linux
JVM : Oracle Corporation 1.8.0_131 amd64
Git : https://github.com/tronprotocol/java-tron/commit/da2673cd28e368b68c9a8056b7c3aa15ec880bf7
Version : 4.7.1
Code : 17673

### 1. What did you do?

I'm running 3 fullnodes using three 16U32G machines inside a cluster.
I started the process with offcial snapshot.
Most of the config are the same as original tron mainnet config.

### 2. What did you expect to see?
The FullNode sync process is normal and the fullnode should have more than 100 active peers.
It should catch up with the latest block in a short time.

### 3. What did you see instead?
As the log said, the active peer number is always lower than 10. 
![image](https://github.com/tronprotocol/java-tron/assets/16130943/29ced52a-7d9c-4f02-bb8b-16d3ad2ca109)
![image](https://github.com/tronprotocol/java-tron/assets/16130943/434e728c-3afa-4968-bada-8d53d5946a27)
The syncing process is quite slow that it decreases about 20 blocks in one minute for the "gap" between current block and highest block.
![image](https://github.com/tronprotocol/java-tron/assets/16130943/232c448a-1007-4a8f-9639-741b1269b467)

I did a test before with the same machine, the syncing process was about 6 times quicker than the current process.
I wonder why the syncing is so slow and why the active peers are so few.
BTW, I set the firewall to drop all the incoming traffic so that there are no passive peers and only active peers, in order to decrease the network traffic.
Thanks!
[mainnet_config.txt](https://github.com/tronprotocol/java-tron/files/11473966/mainnet_config.txt)

**Comment by wubin01** [comment]
Did you specify a configuration file when running? The current default minimum number of connections is 8. Of course, the synchronization is slow, which should be related to the time-consuming processing of blocks. Can you send us your logs?

**Comment by KaiQiu9527** [comment]
> Did you specify a configuration file when running? The current default minimum number of connections is 8. Of course, the synchronization is slow, which should be related to the time-consuming processing of blocks. Can you send us your logs?

Hi wubin01!
As the config file attached showed, I didn't specify "node.connectFactor" and "node.activeConnectFactor", I think that's the reason why min connection is set to default value 8. But it seems that the connection number is "limited" to 8 as the avtive peers are always <= 8. From what I understand, the "min connection" should be the lower bound of the conneciton numbers, and the total peers should between 8-1000(from what I set in "node.maxActiveNodes"). Do I misunderstand the parameters, or I miss some setting in the config file?

I read your latest commit in tron-deployment and it's obviously more readable for developers to set the connection factors, that's really great!

And for the syncing problem, I attach the log file and really hope to figure out why the syncing process is so slow and sometimes even stop growing. Btw, I'm sorry that the timeline of the log file is in reverse order.

Thanks! 
[tron.log](https://github.com/tronprotocol/java-tron/files/11483314/tron.log)

**Comment by lurais** [comment]
@KaiQiu9527 As I can see from the log, the operation push block seems to be the cause of slowly sync, and there is no more info about the push block process, you can just try to use arthas(https://arthas.aliyun.com/en/doc/trace.html#trace-result-time-inaccuracy-problem) command: _trace -E org.tron.core.db.Manager pushBlock|applyBlock -n 50  --skipJDKMethod false_  in arthas to find the root cause , as the root cause may be deeper in the invoke method, this trace may be tried more times,

**Comment by KaiQiu9527** [comment]
> @KaiQiu9527 As I can see from the log, the operation push block seems to be the cause of slowly sync, and there is no more info about the push block process, you can just try to use arthas(https://arthas.aliyun.com/en/doc/trace.html#trace-result-time-inaccuracy-problem) command: _trace -E org.tron.core.db.Manager pushBlock|applyBlock -n 50 --skipJDKMethod false_ in arthas to find the root cause , as the root cause may be deeper in the invoke method, this trace may be tried more times.

@lurais Hi lurais!

I'm sorry that I couldn't log in to the machine to use the arthas tools because of some policy. What I can do is only collecting the logs and do analysis.

I want to know the factors affecting sync speed. Will more active nodes provider a faster sync? How I can accelarate the sync speed by adjusting the tron config?
Thanks!

**Comment by lurais** [comment]
> > @KaiQiu9527 As I can see from the log, the operation push block seems to be the cause of slowly sync, and there is no more info about the push block process, you can just try to use arthas(https://arthas.aliyun.com/en/doc/trace.html#trace-result-time-inaccuracy-problem) command: _trace -E org.tron.core.db.Manager pushBlock|applyBlock -n 50 --skipJDKMethod false_ in arthas to find the root cause , as the root cause may be deeper in the invoke method, this trace may be tried more times.
> 
> @lurais Hi lurais!
> 
> I'm sorry that I couldn't log in to the machine to use the arthas tools because of some policy. What I can do is only collecting the logs and do analysis.
> 
> I want to know the factors affecting sync speed. Will more active nodes provider a faster sync? How I can accelarate the sync speed by adjusting the tron config? Thanks!

Actually, the sync speed is related to many factors, just like the block collect speed, verify sign cost, execute transactions cost, or the speed of data read from the memory or the disk, more active nodes won't provide a faster sync as the cost is mainly in push block, which is not related to the block fetch process, and it is pointless to adjust the tron config without any investigation on the cause, you can just add some metric in the method org.tron.core.db.Manager#pushBlock to find which operation cost much time, and then you can try to adjust the tron config according to the cause.

**Comment by KaiQiu9527** [comment]
> > > @KaiQiu9527 As I can see from the log, the operation push block seems to be the cause of slowly sync, and there is no more info about the push block process, you can just try to use arthas(https://arthas.aliyun.com/en/doc/trace.html#trace-result-time-inaccuracy-problem) command: _trace -E org.tron.core.db.Manager pushBlock|applyBlock -n 50 --skipJDKMethod false_ in arthas to find the root cause , as the root cause may be deeper in the invoke method, this trace may be tried more times.
> > 
> > 
> > @lurais Hi lurais!
> > I'm sorry that I couldn't log in to the machine to use the arthas tools because of some policy. What I can do is only collecting the logs and do analysis.
> > I want to know the factors affecting sync speed. Will more active nodes provider a faster sync? How I can accelarate the sync speed by adjusting the tron config? Thanks!
> 
> Actually, the sync speed is related to many factors, just like the block collect speed, verify sign cost, execute transactions cost, or the speed of data read from the memory or the disk, more active nodes won't provide a faster sync as the cost is mainly in push block, which is not related to the block fetch process, and it is pointless to adjust the tron config without any investigation on the cause, you can just add some metric in the method org.tron.core.db.Manager#pushBlock to find which operation cost much time, and then you can try to adjust the tron config according to the cause, or you can just check the hardware of the machine you use if you are sure that the software config is the same as before completely.

Hi @lurais !
I will find a way to use the arthas, it may take some time.

The node is currently more than 60,000 blocks behind. When I check the tron log, I found that sometimes it stopped growing the current block. For example, in 15:09-15:40, the current block stayed in 51129659. It seems like the tron always send P2P_HELLO to new nodes and closed the channel immediately. The activePeers rasied to 8 and soonly droped to 2. I think it's because of the peer connection issue.
![image](https://github.com/tronprotocol/java-tron/assets/16130943/f2bf3182-3005-4ffa-929e-9ae88137bbe2)


I wonder why the connections dropped immediately. Do I have some network setting problems? Or is it possible that the fullnode connected to a lite node and couldn't fetch the required blocks, so that it dropped the connection?

The log file is attached. Btw, I'm sorry that it's in reverse order. 
[AOM-ap-southeast-3()-2023-5-16.txt](https://github.com/tronprotocol/java-tron/files/11485789/AOM-ap-southeast-3.-2023-5-16.txt)

Thank you!

**Comment by lurais** [comment]
> > > > @KaiQiu9527 As I can see from the log, the operation push block seems to be the cause of slowly sync, and there is no more info about the push block process, you can just try to use arthas(https://arthas.aliyun.com/en/doc/trace.html#trace-result-time-inaccuracy-problem) command: _trace -E org.tron.core.db.Manager pushBlock|applyBlock -n 50 --skipJDKMethod false_ in arthas to find the root cause , as the root cause may be deeper in the invoke method, this trace may be tried more times.
> > > 
> > > 
> > > @lurais Hi lurais!
> > > I'm sorry that I couldn't log in to the machine to use the arthas tools because of some policy. What I can do is only collecting the logs and do analysis.
> > > I want to know the factors affecting sync speed. Will more active nodes provider a faster sync? How I can accelarate the sync speed by adjusting the tron config? Thanks!
> > 
> > 
> > Actually, the sync speed is related to many factors, just like the block collect speed, verify sign cost, execute transactions cost, or the speed of data read from the memory or the disk, more active nodes won't provide a faster sync as the cost is mainly in push block, which is not related to the block fetch process, and it is pointless to adjust the tron config without any investigation on the cause, you can just add some metric in the method org.tron.core.db.Manager#pushBlock to find which operation cost much time, and then you can try to adjust the tron config according to the cause, or you can just check the hardware of the machine you use if you are sure that the software config is the same as before completely.
> 
> Hi @lurais ! I will find a way to use the arthas, it may take some time.
> 
> The node is currently more than 60,000 blocks behind. When I check the tron log, I found that sometimes it stopped growing the current block. For example, in 15:09-15:40, the current block stayed in 51129659. It seems like the tron always send P2P_HELLO to new nodes and closed the channel immediately. The activePeers rasied to 8 and soonly droped to 2. I think it's because of the peer connection issue. ![image](https://user-images.githubusercontent.com/16130943/238586403-f2bf3182-3005-4ffa-929e-9ae88137bbe2.png)
> 
> I wonder why the connections dropped immediately. Do I have some network setting problems? Or is it possible that the fullnode connected to a lite node and couldn't fetch the required blocks, so that it dropped the connection?
> 
> The log file is attached. Btw, I'm sorry that it's in reverse order. [AOM-ap-southeast-3()-2023-5-16.txt](https://github.com/tronprotocol/java-tron/files/11485789/AOM-ap-southeast-3.-2023-5-16.txt)
> 
> Thank you!

As I can see from the log, it seems to be normal to decrese to 2 as the number of active peers is decrese to 2 one by one and prints some log like 'Peer /47.74.229.70 not sync for a long time', just refer to this:https://github.com/tronprotocol/java-tron/issues/5114#event-9173101752 . And if you want to figure out why did it stoped to sync, you shall provide the log from last push block operation, that's to say you should check it from the push of block 51129658 if you want to know why block 51129659 has not been pushed, so as the log you provided.

**Comment by lurais** [comment]
> stucked

Hello, you can provide the log from block 51129657 pushed to the place it stucked as some info in the log may not be noticed by you. And it seems impossible to set the parameter without change the config file or change the source code.

**Comment by KaiQiu9527** [comment]
Hi @lurais !
I recheck the log and found that block 51129659 processed successfully, but block 51129660 process time out so that it stucked for about 40 minutes.
![image](https://github.com/tronprotocol/java-tron/assets/16130943/c4add679-1905-4e2a-b40e-4f9c79e38fa3)

In about 1509:38-15:41:11, it keep stucking.
On 15:41:11, it retry to process the failed transaction and success this time.
![image](https://github.com/tronprotocol/java-tron/assets/16130943/5da9e0de-c070-47c4-8b2c-14aeeb2cbc09)
![image](https://github.com/tronprotocol/java-tron/assets/16130943/fde21f2f-299a-4d83-a262-b55bc4c92f87)

So I guess that is it related to the setting "maxTimeRatio"?
The logs are attached. Btw, I used a tool to reverse the log so that this time they are in a normal order.

Thanks!
[0516-150830-151000.txt](https://github.com/tronprotocol/java-tron/files/11493652/0516-150830-151000.txt)

[0516-153930-154200.txt](https://github.com/tronprotocol/java-tron/files/11493653/0516-153930-154200.txt)

**Comment by lurais** [comment]
> 

yes, setting the "maxTimeRatio" should help.

**Comment by wubin01** [comment]
> > Did you specify a configuration file when running? The current default minimum number of connections is 8. Of course, the synchronization is slow, which should be related to the time-consuming processing of blocks. Can you send us your logs?
> 
> Hi wubin01! As the config file attached showed, I didn't specify "node.connectFactor" and "node.activeConnectFactor", I think that's the reason why min connection is set to default value 8. But it seems that the connection number is "limited" to 8 as the avtive peers are always <= 8. From what I understand, the "min connection" should be the lower bound of the conneciton numbers, and the total peers should between 8-1000(from what I set in "node.maxActiveNodes"). Do I misunderstand the parameters, or I miss some setting in the config file?
> 
> I read your latest commit in tron-deployment and it's obviously more readable for developers to set the connection factors, that's really great!
> 
> And for the syncing problem, I attach the log file and really hope to figure out why the syncing process is so slow and sometimes even stop growing. Btw, I'm sorry that the timeline of the log file is in reverse order.
> 
> Thanks! [tron.log](https://github.com/tronprotocol/java-tron/files/11483314/tron.log)

I have updated the configuration file of the main network. The number of connections is mainly controlled by the following three parameters. 
 ```
  maxConnections = 30
  minConnections = 8
  minActiveConnections = 3
```
As long as the blocks can be synchronized, too many connections will not increase the speed.

**Comment by KaiQiu9527** [comment]
> > 
> 
> yes, setting the "maxTimeRatio" should help.

Hi @lurais !
What is the result of processing block failed? Will it wait for a specific time, such as 30 minutes, to continue the process?
Thanks!

**Comment by KaiQiu9527** [comment]
> > > Did you specify a configuration file when running? The current default minimum number of connections is 8. Of course, the synchronization is slow, which should be related to the time-consuming processing of blocks. Can you send us your logs?
> > 
> > 
> > Hi wubin01! As the config file attached showed, I didn't specify "node.connectFactor" and "node.activeConnectFactor", I think that's the reason why min connection is set to default value 8. But it seems that the connection number is "limited" to 8 as the avtive peers are always <= 8. From what I understand, the "min connection" should be the lower bound of the conneciton numbers, and the total peers should between 8-1000(from what I set in "node.maxActiveNodes"). Do I misunderstand the parameters, or I miss some setting in the config file?
> > I read your latest commit in tron-deployment and it's obviously more readable for developers to set the connection factors, that's really great!
> > And for the syncing problem, I attach the log file and really hope to figure out why the syncing process is so slow and sometimes even stop growing. Btw, I'm sorry that the timeline of the log file is in reverse order.
> > Thanks! [tron.log](https://github.com/tronprotocol/java-tron/files/11483314/tron.log)
> 
> @KaiQiu9527 I have updated the configuration file of the main network. The number of connections is mainly controlled by the following three parameters.
> 
> ```
>  maxConnections = 30
>  minConnections = 8
>  minActiveConnections = 3
> ```
> 
> As long as the blocks can be synchronized, too many connections will not increase the speed.

Hi @wubin01 !
As I know that, tron have active peers and passive peers, and I want to know how the three parameters will affect the nodes number? I use the default value "30-8-3", and it seems like that the total peers number is limited to 8. It won't grow to 30. If some of the nodes lost connetion, it will find more nodes and the total number of nodes are always keep to 8. 
Thanks!

**Comment by lurais** [comment]
> maxTimeRatio

Hello ,you may provide the detail of the machine hardware(eg.cpu memory disk), and have you tried to set the param maxTimeRatio?  It seems to be some fluctuation of machine performance from what we can see, and it is not absolutely certain to recover, just refer to this: https://developers.tron.network/docs/faq

**Comment by KaiQiu9527** [comment]
> > maxTimeRatio
> 
> Hello ,you may provide the detail of the machine hardware(eg.cpu memory disk), and have you tried to set the param maxTimeRatio? It seems to be some fluctuation of machine performance from what we can see, and it is not absolutely certain to recover, just refer to this: https://developers.tron.network/docs/faq

Hi @lurais !
I'm using 16U32G cloud machine with 1.8T HDD harddisk on Huawei Cloud. As far as I know, the hdd disk may be the bottleneck of tron fullnode performance. Is there any way to prove it?
For the param "maxTimeRatio", I will find a chance to adjsut it, as it's not allow for me to modify the config file on machine nowadays.
Thanks!

**Comment by lurais** [comment]
> > > 最大时间比
> > 
> > 
> > 您好，您可以提供机器硬件的详细信息（例如.cpu内存磁盘），您是否尝试设置参数maxTimeRatio？看的好像是机器性能有些波动，也不一定一定能恢复，参考这个： https: [//developers.tron.network/docs/faq](https://developers.tron.network/docs/faq)
> 
> 你好@lurais！ 我在华为云上用的是16U32G云机，1.8T HDD硬盘。据我所知，hdd磁盘可能是tron fullnode性能的瓶颈。有什么办法可以证明吗？ 对于参数“maxTimeRatio”，我会找机会调整它，因为现在不允许我修改机器上的配置文件。 谢谢！

hello, you can try to download lite node data to try to sync again refer to here:https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/, It can be sure that the cloud machine is the cause if the sync speed is fast than the cloud machine while the other requirements are the same.

**Comment by KaiQiu9527** [comment]
> > > > 最大时间比
> > > 
> > > 
> > > 您好，您可以提供机器硬件的详细信息（例如.cpu内存磁盘），您是否尝试设置参数maxTimeRatio？看的好像是机器性能有些波动，也不一定一定能恢复，参考这个： https: [//developers.tron.network/docs/faq](https://developers.tron.network/docs/faq)
> > 
> > 
> > 你好@lurais！ 我在华为云上用的是16U32G云机，1.8T HDD硬盘。据我所知，hdd磁盘可能是tron fullnode性能的瓶颈。有什么办法可以证明吗？ 对于参数“maxTimeRatio”，我会找机会调整它，因为现在不允许我修改机器上的配置文件。 谢谢！
> 
> hello, you can try to download lite node data to try to sync again refer to here:https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/, It can be sure that the cloud machine is the cause if the sync speed is fast than the cloud machine while the other requirements are the same.

Hi @lurais !

I have another fullnode using the same machine with 16U32G HDD, and it also meets the slow syncing problem. I wrote a script to call eth_syncing method in one minute period, and it shows that the fullnode only catch up about 3 to 5 blocks in one minute. At this moment, the memory used is about 75% of 32G.

I use Arthas tool to trace the process, and the result is attached. Could you please have a check the reason why the sync is so slow? Btw, each time I restart the machine, the syncing will be much faster and the mem used is about 20%. The syncing speed will become slower and the mem used will grow to above 70 in about one days.
[trace.log](https://github.com/tronprotocol/java-tron/files/11504142/trace.log)


Thanks!

**Comment by lurais** [comment]
> > > > Did you specify a configuration file when running? The current default minimum number of connections is 8. Of course, the synchronization is slow, which should be related to the time-consuming processing of blocks. Can you send us your logs?
> > > 
> > > 
> > > Hi wubin01! As the config file attached showed, I didn't specify "node.connectFactor" and "node.activeConnectFactor", I think that's the reason why min connection is set to default value 8. But it seems that the connection number is "limited" to 8 as the avtive peers are always <= 8. From what I understand, the "min connection" should be the lower bound of the conneciton numbers, and the total peers should between 8-1000(from what I set in "node.maxActiveNodes"). Do I misunderstand the parameters, or I miss some setting in the config file?
> > > I read your latest commit in tron-deployment and it's obviously more readable for developers to set the connection factors, that's really great!
> > > And for the syncing problem, I attach the log file and really hope to figure out why the syncing process is so slow and sometimes even stop growing. Btw, I'm sorry that the timeline of the log file is in reverse order.
> > > Thanks! [tron.log](https://github.com/tronprotocol/java-tron/files/11483314/tron.log)
> > 
> > 
> > @KaiQiu9527 I have updated the configuration file of the main network. The number of connections is mainly controlled by the following three parameters.
> > ```
> >  maxConnections = 30
> >  minConnections = 8
> >  minActiveConnections = 3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As long as the blocks can be synchronized, too many connections will not increase the speed.
> 
> Hi @wubin01 ! As I know that, tron have active peers and passive peers, and I want to know how the three parameters will affect the nodes number? I use the default value "30-8-3", and it seems like that the total peers number is limited to 8. It won't grow to 30. If some of the nodes lost connetion, it will find more nodes and the total number of nodes are always keep to 8. Thanks!



> > > > > 最大时间比
> > > > 
> > > > 
> > > > 您好，您可以提供机器硬件的详细信息（例如.cpu内存磁盘），您是否尝试设置参数maxTimeRatio？看的好像是机器性能有些波动，也不一定一定能恢复，参考这个： https: [//developers.tron.network/docs/faq](https://developers.tron.network/docs/faq)
> > > 
> > > 
> > > 你好@lurais！ 我在华为云上用的是16U32G云机，1.8T HDD硬盘。据我所知，hdd磁盘可能是tron fullnode性能的瓶颈。有什么办法可以证明吗？ 对于参数“maxTimeRatio”，我会找机会调整它，因为现在不允许我修改机器上的配置文件。 谢谢！
> > 
> > 
> > hello, you can try to download lite node data to try to sync again refer to here:https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/, It can be sure that the cloud machine is the cause if the sync speed is fast than the cloud machine while the other requirements are the same.
> 
> Hi @lurais !
> 
> I have another fullnode using the same machine with 16U32G HDD, and it also meets the slow syncing problem. I wrote a script to call eth_syncing method in one minute period, and it shows that the fullnode only catch up about 3 to 5 blocks in one minute. At this moment, the memory used is about 75% of 32G.
> 
> I use Arthas tool to trace the process, and the result is attached. Could you please have a check the reason why the sync is so slow? Btw, each time I restart the machine, the syncing will be much faster and the mem used is about 20%. The syncing speed will become slower and the mem used will grow to above 70 in about one days. [trace.log](https://github.com/tronprotocol/java-tron/files/11504142/trace.log)
> 
> Thanks!

Hi, you should just trace deeper and deeper into the method org.tron.core.db.Manager:processBlock() to find the root cause, I can just know that processBlock takes most of the time now from the trace log. And you can check the gc log to find if there is too much gc operation also.

**Comment by lurais** [comment]
@KaiQiu9527 maxConnections means to limit the connections to protect the server, and minConnections means how many peer it needs at least, so when it reached 8 it is enough to sync and will not connect to others actively. You may find it more than 8 when you allow the passive peers.

**Comment by KaiQiu9527** [comment]
> > > > > Did you specify a configuration file when running? The current default minimum number of connections is 8. Of course, the synchronization is slow, which should be related to the time-consuming processing of blocks. Can you send us your logs?
> > > > 
> > > > 
> > > > Hi wubin01! As the config file attached showed, I didn't specify "node.connectFactor" and "node.activeConnectFactor", I think that's the reason why min connection is set to default value 8. But it seems that the connection number is "limited" to 8 as the avtive peers are always <= 8. From what I understand, the "min connection" should be the lower bound of the conneciton numbers, and the total peers should between 8-1000(from what I set in "node.maxActiveNodes"). Do I misunderstand the parameters, or I miss some setting in the config file?
> > > > I read your latest commit in tron-deployment and it's obviously more readable for developers to set the connection factors, that's really great!
> > > > And for the syncing problem, I attach the log file and really hope to figure out why the syncing process is so slow and sometimes even stop growing. Btw, I'm sorry that the timeline of the log file is in reverse order.
> > > > Thanks! [tron.log](https://github.com/tronprotocol/java-tron/files/11483314/tron.log)
> > > 
> > > 
> > > @KaiQiu9527 I have updated the configuration file of the main network. The number of connections is mainly controlled by the following three parameters.
> > > ```
> > >  maxConnections = 30
> > >  minConnections = 8
> > >  minActiveConnections = 3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > As long as the blocks can be synchronized, too many connections will not increase the speed.
> > 
> > 
> > Hi @wubin01 ! As I know that, tron have active peers and passive peers, and I want to know how the three parameters will affect the nodes number? I use the default value "30-8-3", and it seems like that the total peers number is limited to 8. It won't grow to 30. If some of the nodes lost connetion, it will find more nodes and the total number of nodes are always keep to 8. Thanks!
> 
> > > > > > 最大时间比
> > > > > 
> > > > > 
> > > > > 您好，您可以提供机器硬件的详细信息（例如.cpu内存磁盘），您是否尝试设置参数maxTimeRatio？看的好像是机器性能有些波动，也不一定一定能恢复，参考这个： https: [//developers.tron.network/docs/faq](https://developers.tron.network/docs/faq)
> > > > 
> > > > 
> > > > 你好@lurais！ 我在华为云上用的是16U32G云机，1.8T HDD硬盘。据我所知，hdd磁盘可能是tron fullnode性能的瓶颈。有什么办法可以证明吗？ 对于参数“maxTimeRatio”，我会找机会调整它，因为现在不允许我修改机器上的配置文件。 谢谢！
> > > 
> > > 
> > > hello, you can try to download lite node data to try to sync again refer to here:https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/, It can be sure that the cloud machine is the cause if the sync speed is fast than the cloud machine while the other requirements are the same.
> > 
> > 
> > Hi @lurais !
> > I have another fullnode using the same machine with 16U32G HDD, and it also meets the slow syncing problem. I wrote a script to call eth_syncing method in one minute period, and it shows that the fullnode only catch up about 3 to 5 blocks in one minute. At this moment, the memory used is about 75% of 32G.
> > I use Arthas tool to trace the process, and the result is attached. Could you please have a check the reason why the sync is so slow? Btw, each time I restart the machine, the syncing will be much faster and the mem used is about 20%. The syncing speed will become slower and the mem used will grow to above 70 in about one days. [trace.log](https://github.com/tronprotocol/java-tron/files/11504142/trace.log)
> > Thanks!
> 
> Hi, you should just trace deeper and deeper into the method org.tron.core.db.Manager:processBlock() to find the root cause, I can just know that processBlock takes most of the time now from the trace log. And you can check the gc log to find if there is too much gc operation also.

Hi @lurais !
I traced deeper of processBlock(), and found that the most time-costing method is preValidateTransactionSign. And I trace preValidateTransactionSign() and the most time-costing method is java.util.concurrent.CountDownLatch:await(). The two trace logs are attached. Do I need to do more trace?
[trace-processBlock.log](https://github.com/tronprotocol/java-tron/files/11505127/trace-processBlock.log)
[trace-preValidateTransactionSign.log](https://github.com/tronprotocol/java-tron/files/11505128/trace-preValidateTransactionSign.log)

Thanks!

**Comment by lurais** [comment]
> trace-processBlock.log

actually , trace into the method org.tron.core.capsule.TransactionCapsule#validateSignature(org.tron.core.store.AccountStore, org.tron.core.store.DynamicPropertiesStore) may help, the await method means waiting for some task to complete.

**Comment by KaiQiu9527** [comment]
> > > > > Did you specify a configuration file when running? The current default minimum number of connections is 8. Of course, the synchronization is slow, which should be related to the time-consuming processing of blocks. Can you send us your logs?
> > > > 
> > > > 
> > > > Hi wubin01! As the config file attached showed, I didn't specify "node.connectFactor" and "node.activeConnectFactor", I think that's the reason why min connection is set to default value 8. But it seems that the connection number is "limited" to 8 as the avtive peers are always <= 8. From what I understand, the "min connection" should be the lower bound of the conneciton numbers, and the total peers should between 8-1000(from what I set in "node.maxActiveNodes"). Do I misunderstand the parameters, or I miss some setting in the config file?
> > > > I read your latest commit in tron-deployment and it's obviously more readable for developers to set the connection factors, that's really great!
> > > > And for the syncing problem, I attach the log file and really hope to figure out why the syncing process is so slow and sometimes even stop growing. Btw, I'm sorry that the timeline of the log file is in reverse order.
> > > > Thanks! [tron.log](https://github.com/tronprotocol/java-tron/files/11483314/tron.log)
> > > 
> > > 
> > > @KaiQiu9527 I have updated the configuration file of the main network. The number of connections is mainly controlled by the following three parameters.
> > > ```
> > >  maxConnections = 30
> > >  minConnections = 8
> > >  minActiveConnections = 3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > As long as the blocks can be synchronized, too many connections will not increase the speed.
> > 
> > 
> > Hi @wubin01 ! As I know that, tron have active peers and passive peers, and I want to know how the three parameters will affect the nodes number? I use the default value "30-8-3", and it seems like that the total peers number is limited to 8. It won't grow to 30. If some of the nodes lost connetion, it will find more nodes and the total number of nodes are always keep to 8. Thanks!
> 
> > > > > > 最大时间比
> > > > > 
> > > > > 
> > > > > 您好，您可以提供机器硬件的详细信息（例如.cpu内存磁盘），您是否尝试设置参数maxTimeRatio？看的好像是机器性能有些波动，也不一定一定能恢复，参考这个： https: [//developers.tron.network/docs/faq](https://developers.tron.network/docs/faq)
> > > > 
> > > > 
> > > > 你好@lurais！ 我在华为云上用的是16U32G云机，1.8T HDD硬盘。据我所知，hdd磁盘可能是tron fullnode性能的瓶颈。有什么办法可以证明吗？ 对于参数“maxTimeRatio”，我会找机会调整它，因为现在不允许我修改机器上的配置文件。 谢谢！
> > > 
> > > 
> > > hello, you can try to download lite node data to try to sync again refer to here:https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/, It can be sure that the cloud machine is the cause if the sync speed is fast than the cloud machine while the other requirements are the same.
> > 
> > 
> > Hi @lurais !
> > I have another fullnode using the same machine with 16U32G HDD, and it also meets the slow syncing problem. I wrote a script to call eth_syncing method in one minute period, and it shows that the fullnode only catch up about 3 to 5 blocks in one minute. At this moment, the memory used is about 75% of 32G.
> > I use Arthas tool to trace the process, and the result is attached. Could you please have a check the reason why the sync is so slow? Btw, each time I restart the machine, the syncing will be much faster and the mem used is about 20%. The syncing speed will become slower and the mem used will grow to above 70 in about one days. [trace.log](https://github.com/tronprotocol/java-tron/files/11504142/trace.log)
> > Thanks!
> 
> Hi, you should just trace deeper and deeper into the method org.tron.core.db.Manager:processBlock() to find the root cause, I can just know that processBlock takes most of the time now from the trace log. And you can check the gc log to find if there is too much gc operation also.

Hi @lurais !
I did a gc trace using jstat, and analysed the result using "gcesay" which is an online ayalysing website. It seems that the gc throughput is 41%, which is really bad. 
[Brilliant GC graphs, metrics and KPIs.pdf](https://github.com/tronprotocol/java-tron/files/11505635/Brilliant.GC.graphs.metrics.and.KPIs.pdf)
Is it related to the slow syncing? I'm sorry that I'm not that familiar to java programming.

Thanks!

**Comment by KaiQiu9527** [comment]
> @KaiQiu9527 maxConnections means to limit the connections to protect the server, and minConnections means how many peer it needs at least, so when it reached 8 it is enough to sync and will not connect to others actively. You may find it more than 8 when you allow the passive peers.

Thanks! The explanation really help me a lot!

**Comment by KaiQiu9527** [comment]
> > trace-processBlock.log
> 
> Actually , trace into the method org.tron.core.capsule.TransactionCapsule#validateSignature(org.tron.core.store.AccountStore, org.tron.core.store.DynamicPropertiesStore) may help, the await method means waiting for some task to complete.

Hi @lurais !
I trace org.tron.core.capsule.TransactionCapsule#validateSignature and deeper, the most time-costing method is org.bouncycastle.math.ec.ECAlgorithms:sumOfTwoMultiplies(). 
![image](https://github.com/tronprotocol/java-tron/assets/16130943/49dd62f9-02ae-4497-8229-c6df7c0f96b5)

Is it normal or do I need to go further for the tracking? I'm concerned about the performance of the hardware. As we know that different CPUs have different performance, although they are both 16 cores.
[tracelog.zip](https://github.com/tronprotocol/java-tron/files/11506431/tracelog.zip)

Thanks!

**Comment by lurais** [comment]
> related to the slow syncing

yes, shall be related to the slow syncing ,you can use other tools to make sure that.

**Comment by KaiQiu9527** [comment]
> > related to the slow syncing
> 
> yes, shall be related to the slow syncing ,you can use other tools to make sure that. It seems no need to trace more deeper, or you can trace more times to find how many times a long validateSign may happens. And shall you provide the start jar command?

Yes sure. The start up command is "java -Xmx24g -XX:+UseConcMarkSweepGC -jar FullNode.jar". The "-Xmx" I set to about 80% of 32G mem. Do I need to change the GC policy?

Thanks!

**Comment by lurais** [comment]
> 

That seems no need to change as the mem match the gc performance.

**Comment by KaiQiu9527** [comment]
Thank you so much!
