### ISSUE TITLE
Possible Bug in System Contract [AccountPermissionUpdateContract]

### ISSUE THREAD

**Issue by Aiden-777** [tronprotocol/java-tron#5221]
When attempting to retrieve detailed information about the "AccountPermissionUpdateContract" via the gRPC interface, it has been observed that the value of ActivePermissionId is consistently 0. This behavior may indicate a potential issue with the assignment of this value in tron-java.

Furthermore, it should be noted that the retrieval of information through the "getAccount" interface functions correctly.

Apologies for any deviation from the submission format in this issue. Thank you for your understanding.

**Comment by hitlxy** [comment]
AccountPermissionUpdateContract is a modify interface which used for updating the account permission. and when executing the transaction, the node will set the ID of these three type of permission to the corresponding value: owner id is 0, witness id is 1, active id is start from 2.  Then, we can query the account permission through getAccount query api.

**Comment by Aiden-777** [comment]
> AccountPermissionUpdateContract is a modify interface which used for updating the account permission. and when executing the transaction, the node will set the ID of these three type of permission to the corresponding value: owner id is 0, witness id is 1, active id is start from 2. Then, we can query the account permission through getAccount query api.

Regarding the retrieval of ActivePermission, is the Id always sorted in sequential order? I am currently utilizing a for loop to parse the results.

**Comment by hitlxy** [comment]
yes, the ID of active permission is always sorted in sequent starting from 2

**Comment by Aiden-777** [comment]
> yes, the ID of active permission is always sorted in sequent starting from 2

The consistent results I obtained from multiple unit tests align with the situation you described. I truly appreciate your assistance. Thank you very much!
