### ISSUE TITLE
Big Problem with `triggerConstantContract` for estimate fee

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5227]
#### System information

docker command for running latest version of java-tron :

docker run -d --name="java-tron" \
             -v /root/tron/output-directory:/java-tron/output-directory \
             -v /root/tron/logs:/java-tron/logs \
             -v /root/tron/main_net_config.conf:/java-tron/config/main_net_config.conf \
             --restart always \
             -p 8090:8090 -p 18888:18888 -p 50051:50051 -p 8091:8091 \
             tronprotocol/java-tron \
             -c /java-tron/config/main_net_config.conf
             
             
4TB SSD NVME 64GB RAM Linux Ubuntu is my os

*Latest version > v4.7.0.1*

#### Expected behaviour

$ curl -X POST  https://nile.trongrid.io/wallet/triggerconstantcontract -d '{
    "owner_address": "TTGhREx2pDSxFX555NWz1YwGpiBVPvQA7e",
    "contract_address": "TVSvjZdyDSNocHm7dP3jvCmMNsCnMTPa5W",
    "function_selector": "transfer(address,uint256)",
    "parameter": "0000000000000000000000002ce5de57373427f799cc0a3dd03b841322514a8c00000000000000000000000000000000000000000000000000038d7ea4c68000",
    "visible": true
}'

In this endpoint,if the owner_address only have Smart contract balance and trx balance equal 0
always return this error : "message": "REVERT opcode executed" and we can't estimate fee with this endpoint

and when I using this $ curl -X POST  https://nile.trongrid.io/wallet/estimateenergy -d '{
    "owner_address": "TTGhREx2pDSxFX555NWz1YwGpiBVPvQA7e",
    "contract_address": "TVSvjZdyDSNocHm7dP3jvCmMNsCnMTPa5W",
    "function_selector": "transfer(address,uint256)",
    "parameter": "0000000000000000000000002ce5de57373427f799cc0a3dd03b841322514a8c00000000000000000000000000000000000000000000000000038d7ea4c68000",
    "visible": true
}'

on my own node, I always get ` "this node does not support estimate energy"`,but my node version greater than  v4.7.0.1

So, how can active estimateenegry endpoint ? 
is it fix with changing main_net_config.conf file ?

give me a solution

**Comment by Ocea91** [comment]
I prefer `estimateenergy`. You probably forget to enable `vm.estimateEnergy` and `vm.supportConstant` in the node config file.

**Comment by kasrakhamesi** [comment]
> I prefer `estimateenergy`. You probably forget to enable `vm.estimateEnergy` and `vm.supportConstant` in the node config file.

solved,thanks
