### ISSUE TITLE
Shutting down full node via docker question

### ISSUE THREAD

**Issue by junghyun0783** [tronprotocol/java-tron#5233]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS & Version: Windows/Linux/OSX

### 3. What did you see instead?

hello.
I'm running tron fullNode through docker.
However, I have a question.
When shutting down docker, I always terminated it with the stop container button.
Wouldn't this forcefully stopping the container cause problems with the fullNode data?
Also, is there a separate container "shutdown command" inside?
Thanks for reading the long article.

**Comment by ExOCeo** [comment]
I assume the stop.sh is what you are looking for, https://tronprotocol.github.io/documentation-en/developers/deployment/#stop-node-gracefully. Not sure how the stop container process is executed, could cause some data loss.

**Comment by lxcmyf** [comment]
You can get help here, https://github.com/tronprotocol/java-tron/blob/develop/docker/docker.md
