### ISSUE TITLE
How to get current unit price of `bandwidth` from the API?

### ISSUE THREAD

**Issue by mahnunchik** [tronprotocol/java-tron#5239]
### 1. What did you do?

I'm calculating transaction fee in TRX. According to the official documentation: https://developers.tron.network/docs/resource-model#bandwidth

```
Burned TRX =  the amount of bandwidth consumed * the unit price of bandwidth
```

### 2. What did you expect to see?

There is API method: https://developers.tron.network/reference/wallet-getchainparameters

There is a field `getEnergyFee` for the energy price. But there is no data for bandwidth price.

### 3. What did you see instead?

How to get current unit price of `bandwidth` from the API?

**Comment by hitlxy** [comment]
`getTransactionFee` is for the bandwidth price.

**Comment by mahnunchik** [comment]
I think it should be documented in https://developers.tron.network/reference/wallet-getchainparameters

**Comment by vivian-kang** [comment]
Thanks for your suggestion. And next we will add the chain parameters description on this API page.  And before this has been done, now you can get the meaning of each filed by referring to Tronscan, the fields in the return value of getchainparameters correspond to the parameters on Tronscan one by one: https://tronscan.org/#/sr/committee.

**Comment by vivian-kang** [comment]
@mahnunchik  The parameter names and their description has already added into [`/wallet/getchainparameters`](https://developers.tron.network/reference/wallet-getchainparameters) API page. Thanks again for your suggestion.

**Comment by mahnunchik** [comment]
@vivian-kang Thank you! It helps me a lot.
