### ISSUE TITLE
Tron Dynamic Model Fee Estimation Formula Is Wrong

### ISSUE THREAD

**Issue by hasanparasteh** [tronprotocol/java-tron#5243]
I use `/wallet/triggerconstantcontract` to retrieve `energy_used` and `energy_penalty`! 

Then I call `/wallet/getcontractinfo` to retrieve `energy_factor` and `energy_usage`! 

Then I extract `getDynamicEnergyThreshold`, `getDynamicEnergyIncreaseFactor` and `getDynamicEnergyMaxFactor` from chain params. The energy price is currently `420`!

Here is the code example and variables I set:

```php
$energy = $result['body']['energy'];
$energyPenalty = @$result['body']['energy_penalty'] ?? 0;
$energyPrice = $result['body']['energy_price'];

$dynamicEnergyThreshold = $result['body']['factors']['getDynamicEnergyThreshold']; // energy Threshold
$dynamicEnergyIncreaseFactor = $result['body']['factors']['getDynamicEnergyIncreaseFactor'] / 10_000; // Step of energy_factor increase
$dynamicEnergyDecreaseFactor = $dynamicEnergyIncreaseFactor / 4; // step of energy_factor decrease
$dynamicEnergyMaxFactor = $result['body']['factors']['getDynamicEnergyMaxFactor'] / 10_000; // maximum value of energy_factor

$energyUsage = @$result['body']['contract_info']['energy_usage'] ?? 0; // current state of network energy
$currentEnergyFactor = @$result['body']['contract_info']['energy_factor'] ?? 0;
if ($currentEnergyFactor != 0)
    $currentEnergyFactor = $currentEnergyFactor / 10_000;

if ($energyUsage > $dynamicEnergyThreshold) {
    // Network Is Now Over-loaded
    $energyFactor = min((1 + $currentEnergyFactor) * (1 + $dynamicEnergyIncreaseFactor) - 1, $dynamicEnergyMaxFactor);
} else {
    // Network at safe state
    $energyFactor = max((1 + $currentEnergyFactor) * (1 - $dynamicEnergyDecreaseFactor) - 1, 0);
}
```

Then I calculate the basic energy consumption like below:

```php
$basicEnergyConsumptionValue = $energy - $energyPenalty;
$additionalEnergyConsumption = $energyPenalty;
```

Now I estimate the energy using below formula:

```php
$totalEnergy = $basicEnergyConsumptionValue * (1 + $energyFactor)) + ($additionalEnergyConsumption * (1 + $energyFactor));
```

Now I compare this energy number to network transactions energy and it's very different. I mean numbers just don't add up correctly or there's something wrong in my formula! I copied all formulas from [developers.tron.network](https://developers.tron.network/docs/resource-model#dynamic-energy-model) which is the source of Tron Network...

considrations: the energy from actual confirmed transaction was around `31,000 energy` but I calculated `9121 energy` which is totally wrong.

Also here is my sample data which I queried from blockchain:

```json
"bandwidth": 345
"energy": 4146
"energy_penalty": 2162
"bandwidth_price": "1000"
"bandwidth_timestamp": "1627279200000"
"energy_price": "420"
"energy_timestamp": "1670133600000"
"getDynamicEnergyThreshold": 3000000000
"getDynamicEnergyIncreaseFactor": 2000
"getDynamicEnergyMaxFactor": 12000

"contract_info": 
   "energy_usage": 7521200946,
   "energy_factor": 12000,
   "update_cycle": 5221


Logger: Network is on Overloaded Mode - Calculated Energy Factor is 1.2

Logger:    Calculated Energy: 9121.2
```

Can anyone help me to find the correct estimations of energy just by using these data?

**Comment by Ocea91** [comment]
The basic energy consumption of calling a particular contract is fixed, the formula is `Transaction energy consumption of calling the contract * (1 +  energy_factor)`. This article would show you more explicit details of the model.

**Comment by hasanparasteh** [comment]
So, how should I estimate the final energy of the trc20 transactions?

**Comment by Ocea91** [comment]
<img width="667" alt="image" src="https://github.com/tronprotocol/java-tron/assets/114645811/c85957a3-8310-4e89-a399-b2decc652aa5">
It is just like you mentioned above, check any transactions that call a contract, use `energy used in total` minus `energy penalty in total`, the difference is the base energy consumption of calling that contract, of course, with the same function selected.

**Comment by hasanparasteh** [comment]
I get it now! And I found the solution too in my codes. I was calling the `triggerconstantcontract` and I was giving it the wrong `parameter`. It was telling me `Revert OP_CODE Executed` and i wasn't paying attention to it! 

I'm so dumb! Sorry for taking your time..

**Comment by widynek** [comment]
@hasanparasteh I have exactly the same problem - I'm getting too low energy..and response also contains `Revert OP_CODE Executed`. Could you provide me some valid `function_selector` and `parameter` ?
I took them from https://tronscan.org/#/transaction/a219388e7348699e97b91ba8528a3c1f46121c1b74a65d5b4b83338223e23296
So I'm sending:
function_selector:transfer(address _to, uint256 _value)
parameter:a9059cbb000000000000000000000041a614f803b6fd780986a42c78ec9c7f77e6ded13c00000000000000000000000000000000000000000000000000000000026c3ced

But it doesn't work :/

**Comment by widynek** [comment]
solved https://github.com/trustwallet/wallet-core/discussions/2786#discussioncomment-7189541
