### ISSUE TITLE
windows编译java-tron异常，失败怎么解决啊

### ISSUE THREAD

**Issue by XINGCHUSI** [tronprotocol/java-tron#5248]
这是报错的内容有知道的吗？
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Tron\java-tron-develop\framework\build.gradle' line: 205

* What went wrong:
Could not determine the dependencies of task ':framework:buildSolidityNodeJar'.
> Could not resolve all files for configuration ':framework:compile'.
   > Could not resolve org.ethereum:leveldbjni-all:1.18.3.
     Required by:
         project :framework > project :chainbase
         project :framework > project :chainbase > project :common
      > Could not resolve org.ethereum:leveldbjni-all:1.18.3.
         > Could not get resource 'https://repo.spring.io/plugins-release/org/ethereum/leveldbjni-all/1.18.3/leveldbjni-all-1.18.3.pom'.
            > Could not GET 'https://repo.spring.io/plugins-release/org/ethereum/leveldbjni-all/1.18.3/leveldbjni-all-1.18.3.pom'. Received status code 401 from server:

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

**Comment by sunflower-sun** [comment]
Windows is not supported, you may try to build and deploy java-tron node on Linux or MacOS.

**Comment by dongzhenye** [comment]
On Windows, you may use WSL (eg. Ubuntu) as a workaround.
See https://github.com/tronprotocol/java-tron/issues/4159#issuecomment-982334983
