### ISSUE TITLE
Why Request to get `Smart Contract Balance` is too `SLOW` ??

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5257]
why request for get smart contract balance is too slow in tron node ?
each response time greater than 3second and its very bad

I run tron node with this docker command : 

docker run -d --name="java-tron" \
             -v /root/tron/output-directory:/java-tron/output-directory \
             -v /root/tron/logs:/java-tron/logs \
             -v /root/tron/main_net_config.conf:/java-tron/config/main_net_config.conf \
             --restart always \
             -p 8090:8090 -p 18888:18888 -p 50051:50051 -p 8091:8091 \
             tronprotocol/java-tron \
             -c /java-tron/config/main_net_config.conf

### System information
CPU(s): 12
Thread(s) per core: 2
Core(s) per socket: 6
Model name:  AMD Ryzen 5 5600X 6-Core Processor
OS :  Ubuntu 20.04
64GB memory
4TB NVMe
150TB Transfer

how can fix that ?

**Comment by forfreeday** [comment]
@kasrakhamesi 
Do you have access in a non-docker environment on this machine and is it this slow

**Comment by kasrakhamesi** [comment]
> @kasrakhamesi Do you have access in a non-docker environment on this machine and is it this slow

yes

**Comment by 317787106** [comment]
> > @kasrakhamesi Do you have access in a non-docker environment on this machine and is it this slow
> 
> yes

what do you mean "get smart contract balance"? Did you use api 'eth_getBalance' ?

**Comment by forfreeday** [comment]
Can you show the configuration of the database section in main_net_config.conf

**Comment by kasrakhamesi** [comment]
> Can you show the configuration of the database section in main_net_config.conf

https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf 

this is my main_net_config.conf but I change   supportConstant from false to true

**Comment by kasrakhamesi** [comment]
> > > @kasrakhamesi Do you have access in a non-docker environment on this machine and is it this slow
> > 
> > 
> > yes
> 
> what do you mean "get smart contract balance"? Did you use api 'eth_getBalance' or '/wallet/getaccountbalance' ?

this request :
 const { abi } = await tronWeb.trx.getContract(contractAddress)
      const currentContract = tronWeb.contract(abi.entrys, contractAddress)
      const balance = await currentContract.methods.balanceOf(address).call()
      
      for example get usdt balance of trc20 for any address

**Comment by forfreeday** [comment]
@kasrakhamesi 
Did your `TronWeb` specify the IP of the FullNode as local when it was initialized.

**Comment by 317787106** [comment]
If you use your own fullnode, you can initialize tronweb like this:
```const TronWeb = require('tronweb')
const tronWeb = new TronWeb({
    fullHost: 'http://x.x.x.x:port',
    privateKey: 'private key responsed to your address'
})
```

Please refer more details on https://tronweb.network/docu/docs/intro/

**Comment by kasrakhamesi** [comment]
> 

I know,but my problem is another thing.

response for my request in too slow. this is my problem.

> If you use your own fullnode, you can initialize tronweb like this:
> 
> ```
> const tronWeb = new TronWeb({
>     fullHost: 'http://x.x.x.x:port',
>     privateKey: 'private key responsed to your address'
> })
> ```
> 
> Please refer more details on https://tronweb.network/docu/docs/intro/

**Comment by 317787106** [comment]
TronWeb will use triggerconstantcontract to get address's balance of usdt. while this api is nothing to do with supportConstant. So please first check that if this query is slow:
```
curl --request POST \
     --url http://localhost:8090/wallet/triggerconstantcontract \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "owner_address": "TJnUPhmZyuDUrq9adJiBSMrs5ZyNRq2ZCy",
  "contract_address": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
  "function_selector": "balanceOf(address)",
  "parameter": "000000000000000000000000a614f803b6fd780986a42c78ec9c7f77e6ded13c",
  "visible": true
}
'
```

**Comment by kasrakhamesi** [comment]
> 

![image](https://github.com/tronprotocol/java-tron/assets/80700084/2d643dac-dac7-49a4-a6d6-547fd2b26e35)

![image](https://github.com/tronprotocol/java-tron/assets/80700084/bf46a6c7-9690-4142-868c-e8c34e9589f2)


I,m waiting for 18 second to get response !!

this is too slow,
how can fix that ?

> TronWeb will use triggerconstantcontract to get address's balance of usdt, and supportConstant must be true. So please first check that if this query is slow:
> 
> ```
> curl --request POST \
>      --url http://localhost:8090/wallet/triggerconstantcontract \
>      --header 'accept: application/json' \
>      --header 'content-type: application/json' \
>      --data '
> {
>   "owner_address": "TJnUPhmZyuDUrq9adJiBSMrs5ZyNRq2ZCy",
>   "contract_address": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
>   "function_selector": "balanceOf(address)",
>   "parameter": "000000000000000000000000a614f803b6fd780986a42c78ec9c7f77e6ded13c",
>   "visible": true
> }
> '
> ```
> 
> This example can be found on https://developers.tron.network/reference/triggerconstantcontract-1. Your hardware configuration looks fine. Generally, this api will be slow only when disk is slow.

**Comment by 317787106** [comment]
Were you calling your own node? Was the host you calling from on the same machine as your node? What was your calling frequency?

**Comment by 317787106** [comment]
Is the api `getnowblock` also slow?

**Comment by kasrakhamesi** [comment]
> Is the api `getnowblock` also slow? Is it all api slow or only `triggerconstantcontract` slow ? I knows little about your environment, so we must try any possibility.

yes its my own server,location is us New Jersey

getnowblock and another request is normal and good 

just I have problem with triggerconstantcontract  and transfer TRC20 function

**Comment by LauraYH** [comment]
@kasrakhamesi Would you mind negotiating this issue you had through Telegram? Or joining in the TRON developer group chat and specifying your issue? I am sure either way, you may find some helpers.

**Comment by yanghang8612** [comment]
@kasrakhamesi Can you provide me with docker-related version information and configuration? You can get the above information by typing `docker version` and `docker info` in the command line.

Also, if possible, could you please provide some of the FullNode sync logs?
According to your docker container startup parameters, they are located in the `/root/tron/logs` directory.
