### ISSUE TITLE
How to speed up node sync?

### ISSUE THREAD

**Issue by chad-fi** [tronprotocol/java-tron#5265]
### System information

java-tron version: https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.7.1
OS & Version:
  PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
  NAME="Debian GNU/Linux"
  VERSION_ID="11"
  VERSION="11 (bullseye)"
  VERSION_CODENAME=bullseye
  ID=debian
CPUs: 7
Memory: 24Gi

### 1. What did you do?
Started syncing node from genesis block.

config used: https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf

Added to line 109 in config file:
node.jsonrpc {
  httpFullNodeEnable = true
  httpFullNodePort = 50545
  httpSolidityEnable = true
  httpSolidityPort = 50555
}

recent logs:
trx-node2-0 trx 15:43:44.911 INFO  [pool-48-thread-1] [DB](Manager.java:1305) Save block: BlockCapsule
trx-node2-0 trx [ hash=00000000007b4bec2ff9adae5d8ca2124d1e73337eaf87c51bd0f6fd68a96872
trx-node2-0 trx number=8080364
trx-node2-0 trx parentId=00000000007b4beb7f5cc9a14b5fdb9f43a1020b35885df782206b0027c12001
trx-node2-0 trx witness address=41bac7378c4265ad2739772337682183b8864f517a
trx-node2-0 trx generated by myself=false
trx-node2-0 trx generate time=2019-04-04 12:46:57.0
trx-node2-0 trx account root=0000000000000000000000000000000000000000000000000000000000000000
trx-node2-0 trx merkle root=c43e6774fc4cf2749514577270f1e3a52be0d0b32499c9fc80ebbfdaa51f78fe
trx-node2-0 trx txs size=63
trx-node2-0 trx ]
trx-node2-0 trx 15:43:44.911 INFO  [pool-48-thread-1] [DB](PendingManager.java:57) Pending tx size: 0.
trx-node2-0 trx 15:43:44.911 INFO  [pool-48-thread-1] [DB](Manager.java:1323) PushBlock block number: 8080364, cost/txs: 221/63 false.
trx-node2-0 trx 15:43:44.911 INFO  [pool-48-thread-1] [net](TronNetDelegate.java:258) Success process block Num:8080364,ID:00000000007b4bec2ff9adae5d8ca2124d1e73337eaf87c51bd0f6fd68a96872
trx-node2-0 trx 15:43:44.913 INFO  [pool-48-thread-1] [DB](Manager.java:1197) Block num: 8080365, re-push-size: 0, pending-size: 0, block-tx-size: 56, verify-tx-size: 56
trx-node2-0 trx 15:43:44.914 INFO  [pool-48-thread-1] [DB](KhaosDatabase.java:331) Remove from khaosDatabase: 00000000007b4bd84decf8e1efb6aef30810952839ad325082382e313bc76e3b.
trx-node2-0 trx 15:43:44.936 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Generated table #318349: 20853 keys, 2113336 bytes
trx-node2-0 trx 15:43:44.943 INFO  [pool-48-thread-1] [DB](SnapshotManager.java:363) Flush cost: 29 ms, create checkpoint cost: 26 ms, refresh cost: 3 ms.
trx-node2-0 trx 15:43:44.972 INFO  [pool-48-thread-1] [VM](VM.java:92) VM halted: [Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]]
trx-node2-0 trx 15:43:44.972 INFO  [pool-48-thread-1] [VM](VMActuator.java:282) runtime result is :Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]
trx-node2-0 trx 15:43:44.980 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Generated table #318350: 20816 keys, 2113068 bytes
trx-node2-0 trx 15:43:44.991 INFO  [pool-48-thread-1] [VM](VM.java:92) VM halted: [Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[112], curOpEnergy[3], usedEnergy[112]]
trx-node2-0 trx 15:43:44.991 INFO  [pool-48-thread-1] [VM](VMActuator.java:282) runtime result is :Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[112], curOpEnergy[3], usedEnergy[112]
trx-node2-0 trx 15:43:44.997 INFO  [NodePersistTaskTimer] [net](NodePersistService.java:83) Write nodes to store: 15/15 nodes
trx-node2-0 trx 15:43:45.018 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Generated table #318351: 20335 keys, 2114404 bytes
trx-node2-0 trx 15:43:45.032 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2180) Update state flag = 0.
trx-node2-0 trx 15:43:45.032 INFO  [pool-48-thread-1] [consensus](DposService.java:162) Update solid block number to 8080347
trx-node2-0 trx 15:43:45.033 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2175) Update latest block header id = 00000000007b4bedd41df23879bacddc6442df8aa7435ff3eac5dd911d99846f.
trx-node2-0 trx 15:43:45.033 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2167) Update latest block header number = 8080365.
trx-node2-0 trx 15:43:45.033 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2159) Update latest block header timestamp = 1554382020000.
trx-node2-0 trx 15:43:45.039 INFO  [pool-48-thread-1] [DB](Manager.java:1305) Save block: BlockCapsule
trx-node2-0 trx [ hash=00000000007b4bedd41df23879bacddc6442df8aa7435ff3eac5dd911d99846f
trx-node2-0 trx number=8080365
trx-node2-0 trx parentId=00000000007b4bec2ff9adae5d8ca2124d1e73337eaf87c51bd0f6fd68a96872
trx-node2-0 trx witness address=41b487cdc02de90f15ac89a68c82f44cbfe3d915ea
trx-node2-0 trx generated by myself=false
trx-node2-0 trx generate time=2019-04-04 12:47:00.0
trx-node2-0 trx account root=0000000000000000000000000000000000000000000000000000000000000000
trx-node2-0 trx merkle root=009f2b6bdfde8f1de088345733058661f2f869f57c1f05195830fa5f811cab32
trx-node2-0 trx txs size=56
trx-node2-0 trx ]
trx-node2-0 trx 15:43:45.039 INFO  [pool-48-thread-1] [DB](PendingManager.java:57) Pending tx size: 0.
trx-node2-0 trx 15:43:45.039 INFO  [pool-48-thread-1] [DB](Manager.java:1323) PushBlock block number: 8080365, cost/txs: 126/56 false.
trx-node2-0 trx 15:43:45.039 INFO  [pool-48-thread-1] [net](TronNetDelegate.java:258) Success process block Num:8080365,ID:00000000007b4bedd41df23879bacddc6442df8aa7435ff3eac5dd911d99846f
trx-node2-0 trx 15:43:45.041 INFO  [pool-48-thread-1] [DB](Manager.java:1197) Block num: 8080366, re-push-size: 0, pending-size: 0, block-tx-size: 50, verify-tx-size: 50
trx-node2-0 trx 15:43:45.042 INFO  [pool-48-thread-1] [DB](KhaosDatabase.java:331) Remove from khaosDatabase: 00000000007b4bd93639e03bf8e5a975da2cdaa0687aedeea8f7549300f7d36a.
trx-node2-0 trx 15:43:45.057 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Generated table #318352: 20247 keys, 2114621 bytes
trx-node2-0 trx 15:43:45.059 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Generated table #318353: 19 keys, 2593 bytes
trx-node2-0 trx 15:43:45.060 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Compacted 1@2 + 10@3 files => 21142339 bytes
trx-node2-0 trx 15:43:45.063 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account compacted to: files[ 0 0 10 132 0 0 0 ]
trx-node2-0 trx 15:43:45.064 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318199
trx-node2-0 trx
trx-node2-0 trx 15:43:45.065 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318197
trx-node2-0 trx
trx-node2-0 trx 15:43:45.066 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318196
trx-node2-0 trx
trx-node2-0 trx 15:43:45.066 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318201
trx-node2-0 trx
trx-node2-0 trx 15:43:45.067 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318202
trx-node2-0 trx
trx-node2-0 trx 15:43:45.068 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318194
trx-node2-0 trx
trx-node2-0 trx 15:43:45.069 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318200
trx-node2-0 trx
trx-node2-0 trx 15:43:45.069 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318198
trx-node2-0 trx
trx-node2-0 trx 15:43:45.070 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318193
trx-node2-0 trx
trx-node2-0 trx 15:43:45.071 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318329
trx-node2-0 trx
trx-node2-0 trx 15:43:45.071 INFO  [leveldb] [LEVELDB](LevelDbDataSourceImpl.java:80) account Delete type=2 #318195
trx-node2-0 trx
trx-node2-0 trx 15:43:45.073 INFO  [pool-48-thread-1] [DB](SnapshotManager.java:363) Flush cost: 31 ms, create checkpoint cost: 28 ms, refresh cost: 3 ms.
trx-node2-0 trx 15:43:45.144 INFO  [pool-48-thread-1] [VM](VM.java:92) VM halted: [Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]]
trx-node2-0 trx 15:43:45.144 INFO  [pool-48-thread-1] [VM](VMActuator.java:282) runtime result is :Not enough energy for 'PUSH1' operation executing: curInvokeEnergyLimit[0], curOpEnergy[3], usedEnergy[0]
trx-node2-0 trx 15:43:45.158 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2180) Update state flag = 0.
trx-node2-0 trx 15:43:45.158 INFO  [pool-48-thread-1] [consensus](DposService.java:162) Update solid block number to 8080348
trx-node2-0 trx 15:43:45.159 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2175) Update latest block header id = 00000000007b4bee8b38a41e7a2fd8f601f9c6350aab273c1202a63ce63f6240.
trx-node2-0 trx 15:43:45.159 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2167) Update latest block header number = 8080366.
trx-node2-0 trx 15:43:45.159 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2159) Update latest block header timestamp = 1554382023000.
trx-node2-0 trx 15:43:45.165 INFO  [pool-48-thread-1] [DB](Manager.java:1305) Save block: BlockCapsule
trx-node2-0 trx [ hash=00000000007b4bee8b38a41e7a2fd8f601f9c6350aab273c1202a63ce63f6240
trx-node2-0 trx number=8080366
trx-node2-0 trx parentId=00000000007b4bedd41df23879bacddc6442df8aa7435ff3eac5dd911d99846f
trx-node2-0 trx witness address=4138e3e3a163163db1f6cfceca1d1c64594dd1f0ca
trx-node2-0 trx generated by myself=false
trx-node2-0 trx generate time=2019-04-04 12:47:03.0
trx-node2-0 trx account root=0000000000000000000000000000000000000000000000000000000000000000
trx-node2-0 trx merkle root=81b36edf2926d4c9e98e7a8f7af7436c46aae548bc3c94c1f425f09e72e75cbf
trx-node2-0 trx txs size=50
trx-node2-0 trx ]
trx-node2-0 trx 15:43:45.165 INFO  [pool-48-thread-1] [DB](PendingManager.java:57) Pending tx size: 0.
trx-node2-0 trx 15:43:45.165 INFO  [pool-48-thread-1] [DB](Manager.java:1323) PushBlock block number: 8080366, cost/txs: 124/50 false.
trx-node2-0 trx 15:43:45.165 INFO  [pool-48-thread-1] [net](TronNetDelegate.java:258) Success process block Num:8080366,ID:00000000007b4bee8b38a41e7a2fd8f601f9c6350aab273c1202a63ce63f6240
trx-node2-0 trx 15:43:45.167 INFO  [pool-48-thread-1] [DB](Manager.java:1197) Block num: 8080367, re-push-size: 0, pending-size: 0, block-tx-size: 65, verify-tx-size: 65
trx-node2-0 trx 15:43:45.167 INFO  [pool-48-thread-1] [DB](KhaosDatabase.java:331) Remove from khaosDatabase: 00000000007b4bdab808174d42edf242072917fd931088beddf72713ce2fc8af.
trx-node2-0 trx 15:43:45.198 INFO  [pool-48-thread-1] [DB](SnapshotManager.java:363) Flush cost: 31 ms, create checkpoint cost: 30 ms, refresh cost: 1 ms.
trx-node2-0 trx 15:43:45.304 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2180) Update state flag = 0.
trx-node2-0 trx 15:43:45.304 INFO  [pool-48-thread-1] [consensus](DposService.java:162) Update solid block number to 8080349
trx-node2-0 trx 15:43:45.304 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2175) Update latest block header id = 00000000007b4befb043930f31b5ac205af9c0f91123da387617d1caa45bf0ff.
trx-node2-0 trx 15:43:45.305 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2167) Update latest block header number = 8080367.
trx-node2-0 trx 15:43:45.305 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2159) Update latest block header timestamp = 1554382026000.
trx-node2-0 trx 15:43:45.309 INFO  [pool-48-thread-1] [DB](Manager.java:1305) Save block: BlockCapsule
trx-node2-0 trx [ hash=00000000007b4befb043930f31b5ac205af9c0f91123da387617d1caa45bf0ff
trx-node2-0 trx number=8080367
trx-node2-0 trx parentId=00000000007b4bee8b38a41e7a2fd8f601f9c6350aab273c1202a63ce63f6240
trx-node2-0 trx witness address=41f29f57614a6b201729473c837e1d2879e9f90b8e
trx-node2-0 trx generated by myself=false
trx-node2-0 trx generate time=2019-04-04 12:47:06.0
trx-node2-0 trx account root=0000000000000000000000000000000000000000000000000000000000000000
trx-node2-0 trx merkle root=48c4975dddbb2006fbd68b61cb5f8cf01184209a9b9eab7704949aa2aa505748
trx-node2-0 trx txs size=65
trx-node2-0 trx ]
trx-node2-0 trx 15:43:45.310 INFO  [pool-48-thread-1] [DB](PendingManager.java:57) Pending tx size: 0.
trx-node2-0 trx 15:43:45.310 INFO  [pool-48-thread-1] [DB](Manager.java:1323) PushBlock block number: 8080367, cost/txs: 143/65 false.
trx-node2-0 trx 15:43:45.310 INFO  [pool-48-thread-1] [net](TronNetDelegate.java:258) Success process block Num:8080367,ID:00000000007b4befb043930f31b5ac205af9c0f91123da387617d1caa45bf0ff
trx-node2-0 trx 15:43:45.312 INFO  [pool-48-thread-1] [DB](Manager.java:1197) Block num: 8080368, re-push-size: 0, pending-size: 0, block-tx-size: 62, verify-tx-size: 62
trx-node2-0 trx 15:43:45.312 INFO  [pool-48-thread-1] [DB](KhaosDatabase.java:331) Remove from khaosDatabase: 00000000007b4bdba3eebbe5afb88163f5388216fbac4d0316a0f88bbe4e2e77.
trx-node2-0 trx 15:43:45.338 INFO  [pool-48-thread-1] [DB](SnapshotManager.java:363) Flush cost: 26 ms, create checkpoint cost: 25 ms, refresh cost: 1 ms.
trx-node2-0 trx 15:43:45.446 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2180) Update state flag = 0.
trx-node2-0 trx 15:43:45.447 INFO  [pool-48-thread-1] [consensus](DposService.java:162) Update solid block number to 8080350
trx-node2-0 trx 15:43:45.447 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2175) Update latest block header id = 00000000007b4bf0dd6f51d641bf1e1dc854bddda99bd42caf55c7d888f71f19.
trx-node2-0 trx 15:43:45.447 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2167) Update latest block header number = 8080368.
trx-node2-0 trx 15:43:45.447 INFO  [pool-48-thread-1] [DB](DynamicPropertiesStore.java:2159) Update latest block header timestamp = 1554382029000.
trx-node2-0 trx 15:43:45.453 INFO  [pool-48-thread-1] [DB](Manager.java:1305) Save block: BlockCapsule
trx-node2-0 trx [ hash=00000000007b4bf0dd6f51d641bf1e1dc854bddda99bd42caf55c7d888f71f19
trx-node2-0 trx number=8080368
trx-node2-0 trx parentId=00000000007b4befb043930f31b5ac205af9c0f91123da387617d1caa45bf0ff
trx-node2-0 trx witness address=41beab998551416b02f6721129bb01b51fceceba08
trx-node2-0 trx generated by myself=false
trx-node2-0 trx generate time=2019-04-04 12:47:09.0
trx-node2-0 trx account root=0000000000000000000000000000000000000000000000000000000000000000
trx-node2-0 trx merkle root=45ca55860afc5c728d67d443fd7a61d80e01f43ba127bc7d574f82e350ad49ce
trx-node2-0 trx txs size=62
trx-node2-0 trx ]
trx-node2-0 trx 15:43:45.454 INFO  [pool-48-thread-1] [DB](PendingManager.java:57) Pending tx size: 0.
trx-node2-0 trx 15:43:45.454 INFO  [pool-48-thread-1] [DB](Manager.java:1323) PushBlock block number: 8080368, cost/txs: 142/62 false.
trx-node2-0 trx 15:43:45.454 INFO  [pool-48-thread-1] [net](TronNetDelegate.java:258) Success process block Num:8080368,ID:00000000007b4bf0dd6f51d641bf1e1dc854bddda99bd42caf55c7d888f71f19
trx-node2-0 trx 15:43:45.456 INFO  [pool-48-thread-1] [DB](Manager.java:1197) Block num: 8080369, re-push-size: 0, pending-size: 0, block-tx-size: 66, verify-tx-size: 66
trx-node2-0 trx 15:43:45.456 INFO  [pool-48-thread-1] [DB](KhaosDatabase.java:331) Remove from khaosDatabase: 00000000007b4bdc1ab6f937164da203e2a43535d3ead058a33cbc4a90e7843b.
trx-node2-0 trx 15:43:45.485 INFO  [pool-48-thread-1] [DB](SnapshotManager.java:363) Flush cost: 29 ms, create checkpoint cost: 27 ms, refresh cost: 2 ms.

### 2. What did you expect to see?
More performant syncing

### 3. What did you see instead?
Only syncing ~1M blocks per day

**Comment by L-Reid** [comment]
The recommended configuration is 16Cores 32G memory 1.5T SSD. Maybe the machine configuration should be improved. Another, syncing from genesis block takes a lot of time, I will suggest to download the latest database snapshot that will speed up the synchronization.

**Comment by plansten** [comment]
https://developers.tron.network/docs/main-net-database-snapshots

**Comment by chad-fi** [comment]
@L-Reid @plansten 

Thanks for the suggestions. Unfortunately none of these available snapshots had `balance.history.lookup = true` added to the storage section of the node configuration file when synced, which I need. Is there a snapshot with this config enabled?

In the meantime I will look into improving the machine configurations.

**Comment by L-Reid** [comment]
Just query begin from the block at which the accounts generated. So suppose the block time is A, then just download the snapshot before the time A, then make the configure item enabled: balance.history.lookup = true. Start the node, then all later synced blocks will include the account balance information.

**Comment by chad-fi** [comment]
I need account balance history from genesis so unfortunately that will not work for me.

Are there snapshots of these official nodes that have the account balances active?

13.228.119.63; 18.139.193.235; 18.141.79.38; 18.139.248.26

https://developers.tron.network/reference/getaccountbalance

**Comment by L-Reid** [comment]
> I need account balance history from genesis so unfortunately that will not work for me.
> 
> Are there snapshots of these official nodes that have the account balances active?
> 
> 13.228.119.63; 18.139.193.235; 18.141.79.38; 18.139.248.26
> 
> https://developers.tron.network/reference/getaccountbalance

I think there is no database snapshot of these nodes. As the public nodes, they can provide data query service and support account history balance query.

**Comment by chad-fi** [comment]
Is it possible for one of the data engineers to take a snapshot and upload it?

**Comment by hosein6666** [comment]
Hoseinghasemi

**Comment by m-o-m12** [comment]
@chad-fi You can download db snapshot with user history balance here.  http://3.219.199.168:18811/

**Comment by chad-fi** [comment]
@m-o-m12 thank you but this snapshot will not work for me, it excludes internal transactions, which I need.

**Comment by chad-fi** [comment]
@L-Reid after reviewing the machine configs, the node is only using between 0 - 1 cpu because it has trouble picking up and maintaining peers. Is there any way to improve the peering?

**Comment by m-o-m12** [comment]
> @m-o-m12 thank you but this snapshot will not work for me, it excludes internal transactions, which I need.

@chad-fi There is no such database snapshot which includes both account history balance and internal transactions, such a database is too big.

**Comment by m-o-m12** [comment]
> @L-Reid after reviewing the machine configs, the node is only using between 0 - 1 cpu because it has trouble picking up and maintaining peers. Is there any way to improve the peering?

@chad-fi  First of all, I will suggest you to improve the machine configuration to the recommended: https://github.com/tronprotocol/java-tron#hardware-requirements .  

Then If you are using the configuration file [here](https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf), please try below way to solve the peers and synchronization issue.  First  stop the node, then delete the `common` library: `output-directory/database/common`, then restart the node.

**Comment by tholcman** [comment]
@m-o-m12 

> You can download db snapshot with user history balance here. http://3.219.199.168:18811/

Hi, I am also trying to have a node with "getaccountbalance" available, I have downloaded the snapshot (http://3.219.199.168:18811/backup20230629/FullNode_output-directory.tgz), started the node with 
```
  balance.history.lookup = true
```
set, but the API only returns balances from the block synced after the start of my node. So it looks like the snapshot doesn't contain the balance history.

Is there a way how I can make the sync fast (matter of days) - including balance history & internal transactions? I have 3 tron nodes available on the same private network connected with 10Gbit/s, but whatever I try the sync from scratch is slow. (server spec should be more than enough - 48 cores, 256GB RAM, 6 NVMe in zfs raid, but it is shared with few other light workloads)

**Comment by m-o-m12** [comment]
@tholcman Sorry for that. The snapshot provided on http://3.1.45.217/  has the balance history.

**Comment by tholcman** [comment]
@m-o-m12 probably naive question: we have our node with internal tx., now we are catching up on a node with account balances history, both are based on LEVELDB. Do you think if we stop both nodes on the same block and copy `output-directory/database/balance-trace` from the node with complete balances history to a node with internal transactions, that it will work?

**Comment by m-o-m12** [comment]
@tholcman Yes, that will work. The node A supports internal transactions, the node B supports account balance history. The condition is the two nodes stopping at the same block. Then copy the `output-directory/database/balance-trace` of node B to node A,  and modify the configure file of A: `storage.balance.history.lookup= true` , then starts them, and node A will support both internal transactions and account balance history query.

**Comment by halibobo1205** [comment]
Guessing this got resolved. Otherwise we can reopen.
