### ISSUE TITLE
Tron Transaction Indexer for own node

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5275]
Does Tron have a transaction indexer?

I want get transaction list from address

for example show me all transactions of  address : TXLCsD9xbaCpbYTcLXrUhMAfzS7Mxa8vnZ in TRC20 and TRX and ...

I don't want using Trongrid.I want my own indexer because I have my own node.

I want run that and config start block.

for example, I want transaction indexer work from block 500000 to until, not from genesis or zero block.

I search for that and find this : https://github.com/tronprotocol/tron-eventquery

bot It's not good.
because that have delay about 40 block from tron node last block and too slow,
or filters it's not good.

can we have another transaction indexer ? 
I writing my custom indexer with node.js express bot it's too slow and delay about 100 block from tron node last block

my hardware for running indexers :

 System information

CPU(s): 12
Thread(s) per core: 2
Core(s) per socket: 6
Model name: AMD Ryzen 5 5600X 6-Core Processor
OS : Ubuntu 20.04
64GB memory
4TB NVMe
150TB Transfer

**Comment by 317787106** [comment]
Java-tron don't have such transaction indexer. You can use tronscan api besides trongrid api:
```
https://apilist.tronscanapi.com/api/transaction?sort=-timestamp&count=true&limit=20&start=0&address=TXLCsD9xbaCpbYTcLXrUhMAfzS7Mxa8vnZ
```
you can give start_timestamp and end_timestamp parameters to get history transaction.

**Comment by sunflower-sun** [comment]
@kasrakhamesi  Try event subscription: https://developers.tron.network/docs/event-subscription

**Comment by 317787106** [comment]
@kasrakhamesi Tronscan api has rate limit, and you should apply api key first, see https://docs.tronscan.org/getting-started/api-keys. Another solution is using mongo plugin combined with java-tron, see more detail on https://developers.tron.network/docs/event-plugin-deployment-mongodb. No rate limit of mongo!  But it only store data after you have configured it, so you cannot lookup history data.

**Comment by kasrakhamesi** [comment]
> @kasrakhamesi Tronscan api has rate limit, and you should apply api key first, it's free, see https://docs.tronscan.org/getting-started/api-keys. Another solution is using mongo plugin combined with java-tron, see more detail on https://developers.tron.network/docs/event-plugin-deployment-mongodb. No rate limit of mongo! But it only store data after you have configured it, so you cannot lookup history data.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.

I get this error when try to use https://github.com/tronprotocol/event-plugin

**Comment by m-o-m12** [comment]
> > @kasrakhamesi Tronscan api has rate limit, and you should apply api key first, it's free, see https://docs.tronscan.org/getting-started/api-keys. Another solution is using mongo plugin combined with java-tron, see more detail on https://developers.tron.network/docs/event-plugin-deployment-mongodb. No rate limit of mongo! But it only store data after you have configured it, so you cannot lookup history data.
> 
> error : Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
> 
> I get this error when try to use https://github.com/tronprotocol/event-plugin

@kasrakhamesi  The gradle version used by event-plugin is 4.8, and this version is ok for event-plugin. So just ignore this warning. Using `./gradlew build` command directly, then we will get the "BUILD SUCCESSFUL" result.
