### ISSUE TITLE
Is java-tron available for windows yet? Also are there any Maven dependencies for java-tron to work with?

### ISSUE THREAD

**Issue by mamtamehra07** [tronprotocol/java-tron#5276]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS & Version: Windows/Linux/OSX

**Comment by 317787106** [comment]
@mamtamehra07 No, java-tron cannot run on windows, only support Linux or macOs. Java-tron cannot be a dependency for any project until now.

**Comment by mamtamehra07** [comment]
Thank you for the quick reply. :)
