### ISSUE TITLE
problem ` timeout of 30000ms exceeded` when call `tronWeb.trx.getBlock(number)`

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5281]
I run node on my dedicated server on us location
Why many times I get error  timeout of 30000ms exceeded when use this code in node.js ?
  const privateKey =
    ''
  const fullNode = new HttpProvider(process.env.TRON_NODE_API)
  const solidityNode = new HttpProvider(process.env.TRON_SOLIDITY_NODE_API)
  const eventServer = new HttpProvider(process.env.TRON_NODE_API)
  const tronWeb = new TronWeb(fullNode, solidityNode, eventServer, privateKey)
  tronWeb.setHeader({
    fullHost: process.env.TRON_NODE_API
  })
const r = await tronWeb.trx.getBlock(number)
 
![image](https://github.com/tronprotocol/java-tron/assets/80700084/c457af0f-70f7-4621-8436-b05f433195dd)

 I run tron node with this docker command :

docker run -d --name="java-tron"
-v /root/tron/output-directory:/java-tron/output-directory
-v /root/tron/logs:/java-tron/logs
-v /root/tron/main_net_config.conf:/java-tron/config/main_net_config.conf
--restart always
-p 8090:8090 -p 18888:18888 -p 50051:50051 -p 8091:8091
tronprotocol/java-tron
-c /java-tron/config/main_net_config.conf
System information

 #### System information
CPU(s): 12
Thread(s) per core: 2
Core(s) per socket: 6
Model name: AMD Ryzen 5 5600X 6-Core Processor
OS : Ubuntu 20.04
64GB memory
4TB NVMe
150TB Transfer

**Comment by m-o-m12** [comment]
This error is reported by axios library. It may be that the request did not return data, or the request was not successful. Was any request ever successful?

**Comment by kasrakhamesi** [comment]
> This error is reported by axios library. It may be that the request did not return data, or the request was not successful. Was any request ever successful?

I using tronWeb library in node.js

**Comment by m-o-m12** [comment]
@kasrakhamesi Yes, using tronWeb to interact with node, but the error is originally from axios. To solve this issue, we can first ensure the code is all correct, we can interact with trongrid to test it. If it is normal, then maybe it is a connectivity issue,  and try the below ways: checking the network status, setting a larger timeout, or testing node http api directly.

**Comment by kasrakhamesi** [comment]
> @kasrakhamesi Yes, using tronWeb to interact with node, but the error is originally from axios. To solve this issue, we can first ensure the code is all correct, we can interact with trongrid to test it. If it is normal, then maybe it is a connectivity issue, and try the below ways: checking the network status, setting a larger timeout, or testing node http api directly.

tronWeb package using axios for request to node.

**Comment by m-o-m12** [comment]
> > @kasrakhamesi Yes, using tronWeb to interact with node, but the error is originally from axios. To solve this issue, we can first ensure the code is all correct, we can interact with trongrid to test it. If it is normal, then maybe it is a connectivity issue, and try the below ways: checking the network status, setting a larger timeout, or testing node http api directly.
> 
> tronWeb package using axios for request to node.

@kasrakhamesi That's it!
