### ISSUE TITLE
Will the disk database of the FullNode increase infinitely, and how to crop the data?

### ISSUE THREAD

**Issue by jiangsheng6** [tronprotocol/java-tron#5302]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS & Version: Windows/Linux/OSX

**Comment by m-o-m12** [comment]
Hi @jiangsheng6 FullNode stores full blockchain data, verifies all blocks and states, provides APIs for external query.  so the data should not be cropped. And for the data storage issue, TRON provides a database storage partition tool to migrate some databases to other storage disks to relieve the pressure on a single disk. This is the guide of how to use this tool: https://tronprotocol.github.io/documentation-en/using_javatron/toolkit/#database-partition-tool 

LiteFullNode does not provide historical block and transaction data query, its database is more lightweight, and it is support to clip data periodically using [LitFullNodeTool](https://github.com/tronprotocol/java-tron/tree/develop/plugins).

**Comment by jiangsheng6** [comment]
thank you, It works
