### ISSUE TITLE
Nile testnet stopped syncing at 38004300 block

### ISSUE THREAD

**Issue by plansten** [tronprotocol/java-tron#5307]
### System information

java-tron version: GreatVoyage-v4.7.1.1(Pittacus)
OS & Version: Linux

**Comment by vivian-kang** [comment]
@plansten Please refer to #5299

**Comment by junghyun0783** [comment]
I have the same symptoms now.
Since version 4.7.2 is not out now, synchronization cannot continue.
I'm running a node through docker... but it keeps crashing and I don't know what to do.

**Comment by vivian-kang** [comment]
> I have the same symptoms now. Since version 4.7.2 is not out now, synchronization cannot continue. I'm running a node through docker... but it keeps crashing and I don't know what to do.

@junghyun0783 Please refer to #5299
