### ISSUE TITLE
Synchronization stops at 38004300 during nile testnet operation through Docker.

### ISSUE THREAD

**Issue by junghyun0783** [tronprotocol/java-tron#5311]
System information
java-tron version: GreatVoyage-v4.7.1.1(Pittacus)
OS & Version: Linux

Synchronization stops at 38004300 during nile testnet operation through Docker. Since it's docker, I don't know how to patch the version to 4.7.2. help.

**Comment by junghyun0783** [comment]
If I create an image by modifying the docker file and then create a new one as follows, it breaks.
thank you

**Comment by Channing0501** [comment]
@junghyun0783 As the [5299#issuecomment-1611078316](5299#issuecomment-1611078316) said, If your node is on Nile testnet, you can build a docker image by yourself. Just using the docker.sh shell script to build the docker image  according to the [guide](https://github.com/tronprotocol/java-tron/blob/develop/docker/docker.md). DId you build success? if not what errors are reported?

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as it may be solved. This is the [comment](https://github.com/tronprotocol/java-tron/issues/5299#issuecomment-1768193974).
