### ISSUE TITLE
FullNode, sync block 38044528 error

### ISSUE THREAD

**Issue by YYMi** [tronprotocol/java-tron#5321]
The stop synchronization is 38044526, and the error is 38044528
The contract method called is written by me, and the source code needs to be provided
![image_2023_06_30T09_49_30_141Z](https://github.com/tronprotocol/java-tron/assets/33677742/54bf3f59-0ae0-4c9b-a067-c395ab1958a0)
Contact email address yuaizifeng@gmail.com

**Comment by Channing0501** [comment]
@YYMi This transaciton was executed successfully by other nodes, but reported OUT_OF_ENERGY by your node. If the issue exists after re-start the node, maybe the database of your node is corrupted. You can re-downloaad the db snapshot of Nile testnet to solve this issue.

**Comment by YYMi** [comment]
> @YYMi This transaciton was executed successfully by other nodes, but reported OUT_OF_ENERGY by your node. If the issue exists after re-start the node, maybe the database of your node is corrupted. You can re-downloaad the db snapshot of Nile testnet to solve this issue.


Tried again and downloaded the latest snapshot, still not working.
Wait for the official, update the program, many people have encountered this problem

**Comment by yanghang8612** [comment]
@YYMi Hi, what is the link to the snapshot you downloaded? And which is the `java-tron` branch of the FullNode you started?
