### ISSUE TITLE
Synchronization is constantly interrupted...

### ISSUE THREAD

**Issue by junghyun0783** [tronprotocol/java-tron#5334]
### System information

java-tron version: GreatVoyage-v4.7.2
OS & Version: Docker in Windows

### 1. What did you do?
  
  We are running Tron testnet and mainnet through Docker. However, when operating a node, a phenomenon in which synchronization is continuously interrupted occurs. Then it goes back... it cuts off again... and it repeats. The cut-off time is repeated at intervals of several hours to several hours.
  I don't know why it keeps doing this.
  
 < PC specs >
  Docker image: tronprotocol/java-tron:GreatVoyage-v4.7.2
  cpu : Intel Xeon(R) CPU E5-2620 v4 @ 2.10GHz
  memory: 128
  disk: 4tb
  
  Please help me... I need to solve it.

**Comment by forfreeday** [comment]
@junghyun0783 
Can you show the sync break as a log?

**Comment by junghyun0783** [comment]
@forfreeday  Still not syncing. Show the current log.

03:54:57.367 INFO  [PeerClient-14] [net](P2pChannelInitializer.java:36) Close channel:/47.90.214.183:18888
03:54:57.368 INFO  [PeerClient-14] [net](ConnPoolService.java:179) Peer stats: channels 1, activePeers 1, active 1, passive 0
03:55:00.452 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.90.214.183:18888
03:55:00.708 INFO  [PeerClient-15] [net](MessageHandler.java:28) Channel active, /47.90.214.183:18888
03:55:00.708 INFO  [PeerClient-15] [net](ChannelManager.java:127) Add peer /47.90.214.183:18888, total peers: 2
03:55:00.708 INFO  [PeerClient-15] [net](ConnPoolService.java:179) Peer stats: channels 2, activePeers 2, active 2, passive 0
03:55:00.708 INFO  [PeerClient-15] [net](PeerConnection.java:171) Send peer /47.90.214.183:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442900452
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:00.962 INFO  [PeerClient-15] [net](P2pChannelInitializer.java:36) Close channel:/47.90.214.183:18888
03:55:00.963 INFO  [PeerClient-15] [net](ConnPoolService.java:179) Peer stats: channels 1, activePeers 1, active 1, passive 0
03:55:04.052 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.90.214.183:18888
03:55:04.052 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.253.34.98:18888
03:55:04.053 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 95.143.184.195:15602
03:55:04.053 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 172.105.238.212:18888
03:55:04.090 INFO  [PeerClient-19] [net](MessageHandler.java:28) Channel active, /172.105.238.212:18888
03:55:04.090 INFO  [PeerClient-19] [net](ChannelManager.java:127) Add peer /172.105.238.212:18888, total peers: 2
03:55:04.090 INFO  [PeerClient-19] [net](ConnPoolService.java:179) Peer stats: channels 2, activePeers 2, active 2, passive 0
03:55:04.090 INFO  [PeerClient-19] [net](PeerConnection.java:171) Send peer /172.105.238.212:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442904053
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:04.128 INFO  [PeerClient-19] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /172.105.238.212:18888, type: P2P_HELLO
from: /172.105.238.212:18888
timestamp: 1688442911656
headBlockId: Num:38144047,ID:000000000246082f65f643da7fdf0b0720a759ffbacfa58c829263dfb506260a
nodeType: 0
lowestBlockNum: 0

03:55:04.129 INFO  [PeerClient-19] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /172.105.238.212:18888, type: SYNC_BLOCK_CHAIN
size: 5, start block: Num:38144028,ID:000000000246081c1b7bb768749557dbf8cf625628d7da9496ad97cd5bb77826, end block Num:38144047,ID:000000000246082f65f643da7fdf0b0720a759ffbacfa58c829263dfb506260a
03:55:04.134 INFO  [PeerClient-19] [net](PeerConnection.java:171) Send peer /172.105.238.212:18888 message type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:38144047,ID:000000000246082f65f643da7fdf0b0720a759ffbacfa58c829263dfb506260a, end blockId: Num:38146047,ID:0000000002460fff6e889406de45fb926a1af7ca67eb637b8993109a8e573e31
03:55:04.258 INFO  [PeerClient-19] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /172.105.238.212:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:38144028,ID:000000000246081c1b7bb768749557dbf8cf625628d7da9496ad97cd5bb77826, end block Num:38146047,ID:0000000002460fff6e889406de45fb926a1af7ca67eb637b8993109a8e573e31
03:55:04.262 INFO  [PeerClient-19] [net](PeerConnection.java:171) Send peer /172.105.238.212:18888 message type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:38146047,ID:0000000002460fff6e889406de45fb926a1af7ca67eb637b8993109a8e573e31, end blockId: Num:38148047,ID:00000000024617cff99bd0641d4685970d62f8268eaab6cf1d6e1f7e27716c39
03:55:04.307 INFO  [PeerClient-16] [net](MessageHandler.java:28) Channel active, /47.90.214.183:18888
03:55:04.307 INFO  [PeerClient-17] [net](MessageHandler.java:28) Channel active, /47.253.34.98:18888
03:55:04.307 INFO  [PeerClient-16] [net](ChannelManager.java:127) Add peer /47.90.214.183:18888, total peers: 3
03:55:04.307 INFO  [PeerClient-17] [net](ChannelManager.java:127) Add peer /47.253.34.98:18888, total peers: 4
03:55:04.307 INFO  [PeerClient-16] [net](ConnPoolService.java:179) Peer stats: channels 4, activePeers 3, active 3, passive 0
03:55:04.307 INFO  [PeerClient-17] [net](ConnPoolService.java:179) Peer stats: channels 4, activePeers 4, active 4, passive 0
03:55:04.307 INFO  [PeerClient-16] [net](PeerConnection.java:171) Send peer /47.90.214.183:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442904052
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:04.307 INFO  [PeerClient-17] [net](PeerConnection.java:171) Send peer /47.253.34.98:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442904053
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:04.560 INFO  [PeerClient-16] [net](P2pChannelInitializer.java:36) Close channel:/47.90.214.183:18888
03:55:04.560 INFO  [PeerClient-16] [net](ConnPoolService.java:179) Peer stats: channels 3, activePeers 3, active 3, passive 0
03:55:04.561 INFO  [PeerClient-17] [net](P2pChannelInitializer.java:36) Close channel:/47.253.34.98:18888
03:55:04.561 INFO  [PeerClient-17] [net](ConnPoolService.java:179) Peer stats: channels 2, activePeers 2, active 2, passive 0
03:55:06.055 WARN  [PeerClient-18] [net](PeerClient.java:52) Connect to peer /95.143.184.195 fail, cause:connection timed out: /95.143.184.195:15602
03:55:06.055 INFO  [PeerClient-18] [net](P2pChannelInitializer.java:36) Close channel:null
03:55:06.055 WARN  [PeerClient-18] [net](ChannelManager.java:70) Notify Disconnect peer has no address.
03:55:07.152 INFO  [pool-61-thread-1] [net](PeerManager.java:147)

============ Peer stats: all 2, active 2, passive 0

Peer /172.105.238.212:18888
connect time: 3s [75ms]
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:10908
syncChainRequested:0
blockInProcess:0

Peer /58.65.160.225:18888
connect time: 5854s [189ms]
last know block num: 37995484
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:163471
syncChainRequested:0
blockInProcess:0


03:55:07.653 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.90.214.183:18888
03:55:07.914 INFO  [PeerClient-20] [net](MessageHandler.java:28) Channel active, /47.90.214.183:18888
03:55:07.914 INFO  [PeerClient-20] [net](ChannelManager.java:127) Add peer /47.90.214.183:18888, total peers: 3
03:55:07.914 INFO  [PeerClient-20] [net](ConnPoolService.java:179) Peer stats: channels 3, activePeers 3, active 3, passive 0
03:55:07.914 INFO  [PeerClient-20] [net](PeerConnection.java:171) Send peer /47.90.214.183:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442907653
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:08.175 INFO  [PeerClient-20] [net](P2pChannelInitializer.java:36) Close channel:/47.90.214.183:18888
03:55:08.175 INFO  [PeerClient-20] [net](ConnPoolService.java:179) Peer stats: channels 2, activePeers 2, active 2, passive 0
03:55:11.253 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.90.214.183:18888
03:55:11.253 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 49.12.196.84:18888
03:55:11.254 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.252.19.181:18888
03:55:11.254 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 65.109.22.249:18888
03:55:11.254 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.252.3.238:18888
03:55:11.254 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 18.162.222.224:18888
03:55:11.341 INFO  [PeerClient-2] [net](MessageHandler.java:28) Channel active, /18.162.222.224:18888
03:55:11.341 INFO  [PeerClient-2] [net](ChannelManager.java:127) Add peer /18.162.222.224:18888, total peers: 3
03:55:11.342 INFO  [PeerClient-2] [net](ConnPoolService.java:179) Peer stats: channels 3, activePeers 3, active 3, passive 0
03:55:11.342 INFO  [PeerClient-2] [net](PeerConnection.java:171) Send peer /18.162.222.224:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442911254
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:11.431 INFO  [PeerClient-2] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /18.162.222.224:18888, type: P2P_HELLO
from: /18.162.222.224:18888
timestamp: 1688442910671
headBlockId: Num:38004300,ID:000000000243e64ce0c6004889df1d6b37dfb1eb0042be5e35cea4d4a8aa7cab
nodeType: 0
lowestBlockNum: 0

03:55:11.432 INFO  [PeerClient-2] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /18.162.222.224:18888, type: SYNC_BLOCK_CHAIN
size: 5, start block: Num:38004281,ID:000000000243e639d2a9175e6950febaa01b37acc402c4f8fdb7166513a80822, end block Num:38004300,ID:000000000243e64ce0c6004889df1d6b37dfb1eb0042be5e35cea4d4a8aa7cab
03:55:11.436 INFO  [PeerClient-2] [net](PeerConnection.java:171) Send peer /18.162.222.224:18888 message type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:38004300,ID:000000000243e64ce0c6004889df1d6b37dfb1eb0042be5e35cea4d4a8aa7cab, end blockId: Num:38006300,ID:000000000243ee1cafab35919079443c1fd70e067ec1ef4413abc74e3867dcbe
03:55:11.508 INFO  [PeerClient-23] [net](MessageHandler.java:28) Channel active, /47.252.19.181:18888
03:55:11.508 INFO  [PeerClient-23] [net](ChannelManager.java:127) Add peer /47.252.19.181:18888, total peers: 4
03:55:11.508 INFO  [PeerClient-23] [net](ConnPoolService.java:179) Peer stats: channels 4, activePeers 4, active 4, passive 0
03:55:11.508 INFO  [PeerClient-23] [net](PeerConnection.java:171) Send peer /47.252.19.181:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442911254
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:11.512 INFO  [PeerClient-21] [net](MessageHandler.java:28) Channel active, /47.90.214.183:18888
03:55:11.512 INFO  [PeerClient-21] [net](ChannelManager.java:127) Add peer /47.90.214.183:18888, total peers: 5
03:55:11.512 INFO  [PeerClient-1] [net](MessageHandler.java:28) Channel active, /47.252.3.238:18888
03:55:11.512 INFO  [PeerClient-1] [net](ChannelManager.java:127) Add peer /47.252.3.238:18888, total peers: 6
03:55:11.512 INFO  [PeerClient-21] [net](ConnPoolService.java:179) Peer stats: channels 5, activePeers 5, active 5, passive 0
03:55:11.512 INFO  [PeerClient-1] [net](ConnPoolService.java:179) Peer stats: channels 6, activePeers 6, active 6, passive 0
03:55:11.512 INFO  [PeerClient-21] [net](PeerConnection.java:171) Send peer /47.90.214.183:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442911253
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:11.512 INFO  [PeerClient-1] [net](PeerConnection.java:171) Send peer /47.252.3.238:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442911254
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:11.515 INFO  [PeerClient-22] [net](MessageHandler.java:28) Channel active, /49.12.196.84:18888
03:55:11.515 INFO  [PeerClient-22] [net](ChannelManager.java:127) Add peer /49.12.196.84:18888, total peers: 7
03:55:11.515 INFO  [PeerClient-22] [net](ConnPoolService.java:179) Peer stats: channels 7, activePeers 7, active 7, passive 0
03:55:11.515 INFO  [PeerClient-22] [net](PeerConnection.java:171) Send peer /49.12.196.84:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442911254
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:11.555 INFO  [PeerClient-0] [net](MessageHandler.java:28) Channel active, /65.109.22.249:18888
03:55:11.556 INFO  [PeerClient-0] [net](ChannelManager.java:127) Add peer /65.109.22.249:18888, total peers: 8
03:55:11.556 INFO  [PeerClient-0] [net](ConnPoolService.java:179) Peer stats: channels 8, activePeers 8, active 8, passive 0
03:55:11.556 INFO  [PeerClient-0] [net](PeerConnection.java:171) Send peer /65.109.22.249:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442911254
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:11.713 INFO  [PeerClient-2] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /18.162.222.224:18888, type: SYNC_BLOCK_CHAIN
size: 11, start block: Num:38004281,ID:000000000243e639d2a9175e6950febaa01b37acc402c4f8fdb7166513a80822, end block Num:38006300,ID:000000000243ee1cafab35919079443c1fd70e067ec1ef4413abc74e3867dcbe
03:55:11.717 INFO  [PeerClient-2] [net](PeerConnection.java:171) Send peer /18.162.222.224:18888 message type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:38006300,ID:000000000243ee1cafab35919079443c1fd70e067ec1ef4413abc74e3867dcbe, end blockId: Num:38008300,ID:000000000243f5ec9c37941ddc7c65482595a0df1a213fcc448dcd571a7514c0
03:55:11.762 INFO  [PeerClient-23] [net](P2pChannelInitializer.java:36) Close channel:/47.252.19.181:18888
03:55:11.763 INFO  [PeerClient-23] [net](ConnPoolService.java:179) Peer stats: channels 7, activePeers 7, active 7, passive 0
03:55:11.769 INFO  [PeerClient-1] [net](P2pChannelInitializer.java:36) Close channel:/47.252.3.238:18888
03:55:11.769 INFO  [PeerClient-1] [net](ConnPoolService.java:179) Peer stats: channels 6, activePeers 6, active 6, passive 0
03:55:11.769 INFO  [PeerClient-21] [net](P2pChannelInitializer.java:36) Close channel:/47.90.214.183:18888
03:55:11.769 INFO  [PeerClient-21] [net](ConnPoolService.java:179) Peer stats: channels 5, activePeers 5, active 5, passive 0
03:55:11.776 INFO  [PeerClient-22] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /49.12.196.84:18888, type: P2P_HELLO
from: /49.12.196.84:18888
timestamp: 1688442911254
headBlockId: Num:23930978,ID:00000000016d286249e92fc962d0b26d853b5d9c1d0ce245002319c7463822c4
nodeType: 0
lowestBlockNum: 0

03:55:11.786 INFO  [PeerClient-22] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /49.12.196.84:18888, type: SYNC_BLOCK_CHAIN
size: 5, start block: Num:23930960,ID:00000000016d285067ae1c95ea39097f2008154b1a7557edbfb4af5eaa0501a4, end block Num:23930978,ID:00000000016d286249e92fc962d0b26d853b5d9c1d0ce245002319c7463822c4
03:55:11.791 INFO  [PeerClient-22] [net](PeerConnection.java:171) Send peer /49.12.196.84:18888 message type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:23930978,ID:00000000016d286249e92fc962d0b26d853b5d9c1d0ce245002319c7463822c4, end blockId: Num:23932978,ID:00000000016d3032cb8e758a9f6ff762df09fef9e84e8d6201e0ae289507915a
03:55:11.857 INFO  [PeerClient-0] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /65.109.22.249:18888, type: P2P_HELLO
from: /65.109.22.249:18888
timestamp: 1688442911006
headBlockId: Num:38017099,ID:000000000244184b273e3e08631234f299eace7c9137c13b40930a69ffb6e120
nodeType: 0
lowestBlockNum: 0

03:55:11.857 INFO  [PeerClient-0] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /65.109.22.249:18888, type: SYNC_BLOCK_CHAIN
size: 3, start block: Num:38017093,ID:00000000024418455ef88b0b78113d3b29a3980d7bb0e22ce204dc80c3ffb95e, end block Num:38017099,ID:000000000244184b273e3e08631234f299eace7c9137c13b40930a69ffb6e120
03:55:11.862 INFO  [PeerClient-0] [net](PeerConnection.java:171) Send peer /65.109.22.249:18888 message type: BLOCK_CHAIN_INVENTORY
size: 2001, first blockId: Num:38017099,ID:000000000244184b273e3e08631234f299eace7c9137c13b40930a69ffb6e120, end blockId: Num:38019099,ID:000000000244201be88c652ffb2b0938dcbc2eaebec7f336f7283b8efbc02bff
^C
[root@d688dbe38557 logs]# vi tron.log
[root@d688dbe38557 logs]# tail -f tron.log
needSyncFromPeer:false
needSyncFromUs:true
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:137856
syncChainRequested:0
blockInProcess:0


03:55:29.256 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.90.214.183:18888
03:55:29.519 INFO  [PeerClient-9] [net](MessageHandler.java:28) Channel active, /47.90.214.183:18888
03:55:29.519 INFO  [PeerClient-9] [net](ChannelManager.java:127) Add peer /47.90.214.183:18888, total peers: 7
03:55:29.519 INFO  [PeerClient-9] [net](ConnPoolService.java:179) Peer stats: channels 7, activePeers 7, active 7, passive 0
03:55:29.519 INFO  [PeerClient-9] [net](PeerConnection.java:171) Send peer /47.90.214.183:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442929256
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:29.785 INFO  [PeerClient-9] [net](P2pChannelInitializer.java:36) Close channel:/47.90.214.183:18888
03:55:29.785 INFO  [PeerClient-9] [net](ConnPoolService.java:179) Peer stats: channels 6, activePeers 6, active 6, passive 0
03:55:32.856 INFO  [pool-59-thread-1] [net](PeerClient.java:62) Connect to peer 47.90.214.183:18888
03:55:33.106 INFO  [PeerClient-10] [net](MessageHandler.java:28) Channel active, /47.90.214.183:18888
03:55:33.106 INFO  [PeerClient-10] [net](ChannelManager.java:127) Add peer /47.90.214.183:18888, total peers: 7
03:55:33.106 INFO  [PeerClient-10] [net](ConnPoolService.java:179) Peer stats: channels 7, activePeers 7, active 7, passive 0
03:55:33.107 INFO  [PeerClient-10] [net](PeerConnection.java:171) Send peer /47.90.214.183:18888 message type: P2P_HELLO
from: /220.117.153.147:18888
timestamp: 1688442932857
headBlockId: Num:38158955,ID:000000000246426be62ace23a81558de4fc90c8b37aa2bf55c2370e8e91132eb
nodeType: 0
lowestBlockNum: 0

03:55:33.355 INFO  [PeerClient-10] [net](P2pChannelInitializer.java:36) Close channel:/47.90.214.183:18888
03:55:33.355 INFO  [PeerClient-10] [net](ConnPoolService.java:179) Peer stats: channels 6, activePeers 6, active 6, passive 0
03:55:35.703 INFO  [PeerClient-19] [net](P2pEventHandlerImpl.java:140) Receive message from  peer: /172.105.238.212:18888, type: P2P_DISCONNECT
reason: TIME_OUT
03:55:35.703 INFO  [PeerClient-19] [net](P2pChannelInitializer.java:36) Close channel:/172.105.238.212:18888
03:55:35.704 INFO  [PeerClient-19] [net](ConnPoolService.java:179) Peer stats: channels 5, activePeers 5, active 5, passive 0

**Comment by chengtx01** [comment]
@junghyun0783 
The log fragments you provided are not sufficient to pinpoint the issue you encountered. Could you provide more complete logs, such as those from one hour before and after the interruption occurred? Of course, the more logs you can provide, the better chance we have of identifying the issue.

**Comment by junghyun0783** [comment]
@chengtx01 
[tron.log](https://github.com/tronprotocol/java-tron/files/11944697/tron.log)
Upload my log file.
Please help me.

**Comment by junghyun0783** [comment]
@chengtx01 @forfreeday 
And now it works fine.
I cleared and ran the container and it works fine now.
But again, it will turn off after a while.
I don't know why.
I'm guessing it might be a problem with your pc specs.

**Comment by forfreeday** [comment]
@junghyun0783 
Are you referring to the docker container exit process?

**Comment by chengtx01** [comment]
> @chengtx01 @forfreeday And now it works fine. I cleared and ran the container and it works fine now. But again, it will turn off after a while. I don't know why. I'm guessing it might be a problem with your pc specs.

@junghyun0783 Through analyzing the logs you provided, we found that your node failed to process block 38158956, which caused synchronization interruption. It appears that the local database is corrupted. You can try to solve this problem by downloading the latest database snapshot. Could you also provide us with the logs of the latest synchronization interruption, so that we can confirm our inference is correct?
