### ISSUE TITLE
use trident sdk api delegateResource by 2.0 on version 0.6.0 connect fullnode 4.7.2 will make a excption

### ISSUE THREAD

**Issue by 405560984** [tronprotocol/java-tron#5335]
I use the trident SDK by version 0.6.0 and the node version is 4.7.2
now i use she SDK api delegateResource,
it will make an exception:
delegateResource fail ,param:from=TKqngb5tmJ5ArSBLos3azHV3wvGGtjmZKJ,recv=TGEsrHpBkjQH2iYdTsKdUkGGcbqpo8vLFU,amount=16118,resCode=1,error msg：createTransactionExtention error,UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetNowBlock2
org.tron.trident.core.exceptions.IllegalException: createTransactionExtention error,UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetNowBlock2
	at org.tron.trident.core.ApiWrapper.createTransactionExtention(ApiWrapper.java:326)
	at org.tron.trident.core.ApiWrapper.delegateResource(ApiWrapper.java:595)

i want to know how to fix this problem

as i read the code and it looks like at the function createTransaction at line 306, use blockingStubSolidity.getNowBlock2 has miss the function?

now my question is the function is miss by trident SDK or in fullnode ？

as i see the node computer, i open the RPC/HTTP port 50051 and HTTP prot 8081

so what next to do??

thanks!!!!!

**Comment by vivian-kang** [comment]
Duplicated issue with [Trident issue 95](https://github.com/tronprotocol/trident/issues/95), So close this one.
