### ISSUE TITLE
A

### ISSUE THREAD

**Issue by RZ7272** [tronprotocol/java-tron#5342]
https://dapp.tronlink.org/?dapp_url=https%3A%2F%2Fgithub.com%2FOmniLayer%2Fomnicore%2Fwiki%2FUse-the-raw-transaction-API-to-create-a-Simple-Send-transaction&dapp_name=Use%20the%20raw%20transaction%20API%20to%20create%20a%20Simple%20Send%20transaction%20%C2%B7%20OmniLayer%2Fomnicore%20Wiki%20%C2%B7%20GitHub#/sharedapp

**Comment by Jake151987** [comment]
@RZ7272, would you mind specifying the problem you met?
