### ISSUE TITLE
Get assets of an account

### ISSUE THREAD

**Issue by vahidsabet** [tronprotocol/java-tron#5344]
System information

nohup java -Xms20G -Xmx59G -XX:ReservedCodeCacheSize=256m
-XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m
-XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails
-XX:+PrintGCDateStamps -Xloggc:gc.log
-XX:+UseConcMarkSweepGC -XX:NewRatio=2
-XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled
-XX:+HeapDumpOnOutOfMemoryError
-XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70
-jar FullNode.jar -c main_net_config.conf --es >> start.log 2>&1 &
1. What did you do?

I want using my fullnode to retrieve account assets:

2. What did you expect to see?

List of assets of given base58 address

3. What did you see instead?

nothing

**Comment by Jake151987** [comment]
@vahidsabet，you may try https://developers.tron.network/reference/account-getaccount this API to get the balance of given addresses.

**Comment by vahidsabet** [comment]
Thanks dear @Jake151987 . So there isn't a single  call to get both TRX and other tokens?

**Comment by Jake151987** [comment]
@vahidsabet, sorry no single API could achieve that.

**Comment by FerdyCai** [comment]
I try to get balance of TRC-20 with api “/wallet/triggersmartcontract”，why the response is {
    "result": {
        "code": "CONTRACT_VALIDATE_ERROR",
        "message": "this node does not support constant"
    }
}

by params 
{
"contract_address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
"function_selector":"balanceOf(address)",
"owner_address":"TM442vw56hUxmYmZ5L2q3cqZy7ZSBQgRXn",
"visible" : true
}

**Comment by ExOCeo** [comment]
@FerdyCai   I guess you are rolling with your own node? In your node config file, find the item `supportConstant` and set it to 'true`, then you may use `triggerconstantcontract` to query the balance of your TRC-20 token.

**Comment by FerdyCai** [comment]
@ExOCeo,yes,i am rolling with my own node. but https://developers.tron.network/reference/triggersmartcontract here also can not get balance of TRC-20 .
