### ISSUE TITLE
Golang code example of how to create->sign->broadcast transaction

### ISSUE THREAD

**Issue by biganashvili** [tronprotocol/java-tron#5348]
As you know `GreatVoyage-v4.7.1.1` removed insecure API endpoints like `easytransferbyprivate`, so my project needs a code adjustment to these changes, I will be glad to any suggestions/links on how to do this in **Golang**.

**Comment by ferdinand026** [comment]
Signing transactions offline will be more secure. I know a [golang SDK](https://github.com/fbsobreira/gotron-sdk), and there are demos for [transferring TRX ](https://github.com/fbsobreira/gotron-sdk/blob/master/pkg/client/client_test.go#L30) and [TRC20 tokens](https://github.com/fbsobreira/gotron-sdk/blob/master/cmd/subcommands/trc20.go#L45), just refer to them.

**Comment by aemet93** [comment]
Is there any golang examples how to create and sign raw trx (and trc-20) transactions? Thank you in advance for any help.

**Comment by ClarkChenc** [comment]
> Is there any golang examples how to create and sign (using private key) raw trx (and trc-20) transactions? Thank you in advance for any help.

hi, @aemet93, this doc may help you https://cn.developers.tron.network/reference/tronweb-sign.

**Comment by biganashvili** [comment]
> Is there any golang examples how to create and sign (using private key) raw trx (and trc-20) transactions? Thank you in advance for any help.

You can find my simple solution here, feel free to ask questions if you have any.
https://github.com/biganashvili/hexpay

**Comment by ClarkChenc** [comment]
> > Is there any golang examples how to create and sign (using private key) raw trx (and trc-20) transactions? Thank you in advance for any help.
> 
> Hi, @aemet93 You can find my simple solution here, feel free to ask questions if you have any. https://github.com/biganashvili/hexpay

I find your example leaks your private key, take care of it.

**Comment by biganashvili** [comment]
@ClarkChenc Thank you.
I generated it to test this particular case,
I don't use it for any other purpose.

**Comment by SantiiRepair** [comment]
interesting thread, I didn't know there was a Tron SDK for Golang
