### ISSUE TITLE
New blocks are not synced

### ISSUE THREAD

**Issue by d1mpi** [tronprotocol/java-tron#5352]
### System information
OS : Linux
JVM : Private Build 1.8.0_362 amd64
Git : 4b6e0a5c85dabcb972dcc7e0962d18ffd359ef71
Version : 4.7.2
Code : 17686

### 1. What did you do?
Launched the node using screen java -Xmx24g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c main_net_config.conf

### 2. What did you expect to see?
Synchronization of node blocks.

### 3. What did you see instead?
Synchronization of blocks stops a couple of blocks after the node is started, 5-7 blocks and no more reaction.
[tron.log](https://github.com/tronprotocol/java-tron/files/12061052/tron.log)

**Comment by ferdinand026** [comment]
@d1mpi  From the log, it is reported different result code error, the failed transaction executed successful on your node. If the issue exists after re-start the node, maybe the database of your node is corrupted. You can re-downloaad the [database snapshot ](https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/#fullnode-data-snapshot)to solve this issue.

**Comment by d1mpi** [comment]
> @d1mpi Из журнала сообщается о другой ошибке кода результата, неудачная транзакция успешно выполнена на вашем узле. Если проблема существует после перезапуска узла, возможно, база данных вашего узла повреждена. Вы можете повторно загрузить [снимок базы данных](https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/#fullnode-data-snapshot) , чтобы решить эту проблему.

Now at startup I see this [main] [DB](SnapshotManager.java:496) the checkpoint check failed, it is not possible to convert the checkpoint from version 2 to version 1

**Comment by ferdinand026** [comment]
@d1mpi Yes, If the node enabled the checkpoint v2 through `storage.checkpoint.version = 2`, then it cannot support to rollback to checkpoint v1.

**Comment by d1mpi** [comment]
> 

In this case, should I just do storage.checkpoint.version = 1?

**Comment by d1mpi** [comment]
I tried using storage.checkpoint.version = 1, it didn't help

**Comment by ferdinand026** [comment]
@d1mpi Becasue the node has already reported different result code, so the db may have already been corrupted. I will suggest you to re-download the db snapshot. After downloading, it's ok to set`storage.checkpoint.version` to 1 or 2.

**Comment by d1mpi** [comment]
> @d1mpiПоскольку узел уже сообщил о другом коде результата, возможно, база данных уже повреждена. Я предлагаю вам повторно загрузить снимок базы данных. После загрузки можно установить `storage.checkpoint.version`значение 1 или 2.

Can you tell me where to enter it? I tried to enter this line, but the error remained the same

**Comment by d1mpi** [comment]
That's it, the blocks have started to be updated, everything is fine!
