### ISSUE TITLE
How Can Get Last inner transactions to wallet

### ISSUE THREAD

**Issue by mojtaban12** [tronprotocol/java-tron#5353]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS & Version: Windows/Linux/OSX

### 1. What did you do?

In Bitcoin Full Node , we have a main wallet that the addresses are created under its collection.
cause the addresses are created in full node, with a simple configuration, inner txId can be obtained instantly.

walletnotify=/home/scripts/transaction.sh %s

1- how can import,define,set or ... my generated address (offline) to java-tron !?
2- How can I get the txid deposited to the address I made in the moment?

**Comment by ysk4dx** [comment]
- [x] Ammm I've no idea ****

**Comment by ferdinand026** [comment]
@mojtaban12 Though there is no such a script you can use directly to obtain a certain account's transaction, we can use [event subscription mechanism](https://developers.tron.network/docs/event-subscription), or[ trongrid](https://developers.tron.network/reference/get-transaction-info-by-account-address) event service and so on.

**Comment by mojtaban12** [comment]
that's mean! I have to subscribe all of transactions then get details of that !
 if receiver address was my address push notif to user !!!? 
It does not seem very reasonable :|

**Comment by ferdinand026** [comment]
> that's mean! I have to subscribe all of transactions then get details of them! if receiver address was my address push notif to user !!!? It does not seem very reasonable :|

Event subscription of FullNode will send the corresponding type of transactions or blocks or events to mongodb/kafka/zeromq, then you can get data from them. It has nothing related to other users. 

If you want to try a more easy way, just to use [trongrid API](https://developers.tron.network/reference/get-transaction-info-by-account-address) to get the transactions of an account address periodically.

**Comment by mojtaban12** [comment]
you say
Assuming 1000 addresses, should I send a request to [trongrid API](https://developers.tron.network/reference/get-transaction-info-by-account-address) every few seconds for each address and find out what address was charged?
I think this will take 10 minutes for each check! 
It is not logical at all
How do Binance and other crypto currency exchanges solve this problem?
