### ISSUE TITLE
Improve the performance of  vote reward withdrawal

### ISSUE THREAD

**Issue by lurais** [tronprotocol/java-tron#5354]
# Rationale

The reward calculation logic is divided into two parts: the old one and the new one. This is based on proposal [No.82](https://tronscan.org/#/proposal/82) which took effect on 2023-01-20 at 14:00:00. Due to the proposal, the vote rewards that occurred before that time (14:00:00, 2023-01-20) would still be calculated with the old reward algorithm when withdrawing, which has poor performance. For more details, please see [TIP-465](https://github.com/tronprotocol/tips/blob/master/tip-465.md).

There are three types of transactions that trigger vote reward withdrawal: VoteWitnessContract, UnfreezeBalanceContract, and WithdrawBalanceContract.

# Why should this feature exist?
To improve the performance of withdrawing vote rewards that occurred before 2023-01-20 14:00:00, reduce the execution time of the above three types of transactions.

# Implementation

 Do you have ideas regarding the implementation of this feature?

 ## Option 1
 Calculate the vote rewards (before 14:00:00, 2023-01-20) in advance by background task and cache them.

### Previews

![image](https://github.com/tronprotocol/java-tron/assets/82020050/92740d54-8956-4fe7-9d50-bd171ac34100)

 ### Problems&Shortcomings

- [x] DB Cache pollution due to bulk queries
- [x] how to mark the calculation progress
- [x] ~~how to mark and clean `outdated data`(reward has been withdrawn)~~

 ## ~~Option 2~~
Execute the above three transactions asynchronously.

### Previews

![image](https://github.com/tronprotocol/java-tron/assets/82020050/7c6ae36a-15cc-4f64-bd15-7bf0c50bba2c)

 ### Problems&Shortcomings

- [x] ~~transactions `expire` due to time-consuming reward calculations~~
- [x] ~~the transactions are in disorder~~
- [x] ~~how to callback for `broadcastTransaction` when executed asynchronously~~
- [x] ~~transactions are not guaranteed to be broadcast over the entire network~~

Are you willing to implement this feature?
 Yes.

# statistic
 As of Aug. 9, 2023, nearly **210k** accounts(rewarding cumulative **2+** maintenances) still need old  reward calculation logic , about **1k accounts/w** declined online. There are **20k** accounts rewarding cumulative **3k** maintenances, **150k** accounts rewarding cumulative **1k** maintenances.

**Comment by guoquanwu** [comment]
Sounds good, I think we can discuss more details about it

For option1: how to cache the pre-calculation result and rebuild it when a node crash 

For option2: does it mean executing the withdrawal transactions with other transactions in parallel? How to guarantee transaction state isolation and merge them in final

**Comment by forfreeday** [comment]
How do you do a speed bump? Tell me how it works.

**Comment by bladehan1** [comment]
For option1 why not billing old rewards section?

**Comment by halibobo1205** [comment]
> Sounds good, I think we can discuss more details about it
> 
> For option1: how to cache the pre-calculation result and rebuild it when a node crash
> 
> For option2: does it mean executing the withdrawal transactions with other transactions in parallel? How to guarantee transaction state isolation and merge them in final

For option1:  pre-calculated results persistence ?
For option2:  No better ideas for now, it not a good idea indeed.

**Comment by halibobo1205** [comment]
> For option1 why not billing old rewards section?

@bladehan1 Make users pay for design flaws? 💔💔💔

**Comment by lvs007** [comment]
Can you give specific detailed ideas?

**Comment by halibobo1205** [comment]
> Can you give specific detailed thoughts?

@lvs007 Description has been updated.

**Comment by lvs007** [comment]
I think the task could run ahead for a while and then switch calculations once all the nodes are harmonized.

**Comment by halibobo1205** [comment]
@lvs007 Great, i will try it.

**Comment by halibobo1205** [comment]
For the latest implementation, please check  https://github.com/tronprotocol/tips/issues/635
