### ISSUE TITLE
Acquire Internet IP from Libp2p API

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/java-tron#5368]
# Rationale

At present, java-tron clients obtain external IPv4 and IPv6 through a method that accesses two certain URLs, it’s the same as libp2p. Java-tron executes this method first, and libp2p executes later when being initialized. This time-consuming method has been executed twice and may delay the startup speed of the java-tron clients.

# Implementation

1.  When java-tron clients start, it obtains the external IP through Libp2p’s method/api directly.
2.  When initializing libp2p, java-tron assigns two IPs to the related fields of P2pConfig, and Libp2p does not need to acquire the external IP again. To meet this requirement we need to add a new constructor method for libp2p.

# Compatibility

There is no backward compatibility concern for this issue.

**Comment by halibobo1205** [comment]
What is the purpose of `external IPv4 and IPv6`?  What are the effects if they are not acquired ?

**Comment by 317787106** [comment]
@halibobo1205 The main usage of ip in libp2p is used to construct your homenode, that is part of UDP Ping & Pong message sent to other in p2p node discovering, and you can find third party nodes from neighbours's message that include  ip. Usage of ip in java-tron is to build HelloMessage in HandshakeService.

**Comment by guoquanwu** [comment]
Why not initial the libp2p module first, and try to get the IPs through the libp2p interface?

**Comment by xq-lu** [comment]
> Why not initial the libp2p module first, and try to get the IPs through the libp2p interface?

agree with @guoquanwu , if java-tron's use libp2p module as a dependency, it is better to query the needed config directly from the dependency instead of constructing it itself.

**Comment by 317787106** [comment]
@guoquanwu @xq-lu @yuekun0707 Good suggestion! I accept this idea. There will be more places to modify, but that is another matter.

**Comment by halibobo1205** [comment]
> @halibobo1205 The main usage of ip in libp2p is used to construct your homenode, that is part of UDP Ping & Pong message sent to other in p2p node discovering, and you can find third party nodes from neighbours's message that include ip. Usage of ip in java-tron is to build HelloMessage in HandshakeService.

 BTW, what are the effects if they are not acquired ?

**Comment by 317787106** [comment]
@halibobo1205 If java-tron fails to get the external IP, it use 127.0.0.1 as default, it records HelloMessage in log. When some exception happens, developer can backtrack the whole process easily. But this will become harder if ip is missing or use default ip in HelloMessage.

**Comment by lurais** [comment]
What if the ip changed after you acquired it ?
