### ISSUE TITLE
Optimize p2p handshake logic

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/java-tron#5369]
# Rationale
After the handshake is completed, it will be negotiated whether to use message compression to communicate.

There should be no other message exchange before the handshake is completed, which may cause message parsing failure and disconnection.

<img width="411" alt="image" src="https://github.com/tronprotocol/java-tron/assets/37210306/b895234d-d2ea-4bde-af0a-6b08544ffde0">

### Background
After the TCP connection is established, if there is a network jitter, the handshake time may exceed 20s. At this time, the channel keep-alive function will be triggered and a ping message will be sent. Since the handshake is not completed, the ping packet sent at this time is an uncompressed packet. If the handshake result is communicated in a compressed way, the uncompressed message will fail to parse and the connection will be disconnected.

<img width="448" alt="image" src="https://github.com/tronprotocol/java-tron/assets/37210306/abef5ca8-cef9-4c47-a526-1b61d829ddd3">

# Implementation
For the current version release_v4.7.2, after the TCP connection is established, there should be no packet or message exchange until the p2p handshake is completed except for the channel keep-alive message. So the ping message should be sent after the handshake is completed, otherwise, disconnection may be incurred.

**Comment by halibobo1205** [comment]
Suggest a flowchart to explain

**Comment by ClarkChenc** [comment]
Yes, I do think so. The keepalive message should occur after the handshake process, because before the handshake is complete, some important message exchanges have not been completed, which can cause many issues.

**Comment by wubin01** [comment]
> Suggest a flowchart to explain

@halibobo1205 Great idea, flowchart has been added

**Comment by guoquanwu** [comment]
Does this issue only exist in v4.7.2, if not, please specify all the versions that will be fixed

**Comment by wubin01** [comment]
@guoquanwu libp2p handshake takes effect in v4.7.2, other versions do not have this function, no need to fix.

**Comment by xq-lu** [comment]
from this issue, still can not understand how you optimize the current situation you describe above. could you highlight in the flowchart what you do to prevent this issue happen?

**Comment by wubin01** [comment]
@xq-lu It is introduced in the rationale and implementation, do not send other messages after the handshake is completed.

**Comment by wubin01** [comment]
> I am curious about the purpose of the `ping message`. If you try to remove the `ping` logic, will it affect the connection establishment?
> 
> what will happen when `ping` failed or time-out based on existing logic?

@ guoquanwu The ping message is used for channel keep-alive, If you haven’t sent a message to a neighbor node for a long time, you need to send a ping message, otherwise the connection will be disconnected. ping failed or time-out will disconnect the connection.

**Comment by guoquanwu** [comment]
> The ping message is used for channel keep-alive

Get your point, you are trying to delay the ping message not remove it. Nice try!

**Comment by wubin01** [comment]
This issue will be discussed here: https://github.com/tronprotocol/libp2p/issues/61
