### ISSUE TITLE
Supplement Disconnect Reasons in Java-tron

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/java-tron#5372]
# Rationale

Java-tron nodes send DisconnectMessage to peers before closing the connection. The nodes use relatedReasonCode if it exists as DisconnectMessage, otherwise, no message would be sent. Most of the java-tron logs record the ReasonCode of peer disconnection, but some do not. 

## Missing scene

- The reason for disconnection with non-witness nodes in RelayService is not given.
- When node shutdowns, it doesn't tell other peers the reason.

We summarize the use of ReasonCode, many of which have been abandoned:

    enum ReasonCode {
      REQUESTED = 0x00;             //Not used
      BAD_PROTOCOL = 0x02;         
      TOO_MANY_PEERS = 0x04;        //Not used
      DUPLICATE_PEER = 0x05;       
      INCOMPATIBLE_PROTOCOL = 0x06; //Not used
      RANDOM_ELIMINATION = 0x07;    //Not used
      PEER_QUITING = 0x08;          //Not used
      UNEXPECTED_IDENTITY = 0x09;   //Empty Block Hash
      LOCAL_IDENTITY = 0x0A;        //Not used
      PING_TIMEOUT = 0x0B;          //Not used
      USER_REASON = 0x10;           //Not used
      RESET = 0x11;                 //Not used
      SYNC_FAIL = 0x12;
      FETCH_FAIL = 0x13;
      BAD_TX = 0x14;
      BAD_BLOCK = 0x15;
      FORKED = 0x16;
      UNLINKABLE = 0x17;
      INCOMPATIBLE_VERSION = 0x18;
      INCOMPATIBLE_CHAIN = 0x19;
      TIME_OUT = 0x20;
      CONNECT_FAIL = 0x21;                //Not used
      TOO_MANY_PEERS_WITH_SAME_IP = 0x22; //Not used
      LIGHT_NODE_SYNC_FAIL = 0x23;   
      BELOW_THAN_ME = 0X24;
      UNKNOWN = 0xFF;
    }

    message DisconnectMessage {
      ReasonCode reason = 1;
    }

# Implementation

### Add new types to java-tron ReasonCode

Add the following enumeration type to protos/core/Tron.proto

    enum ReasonCode {
      REQUESTED = 0x00;         
      ...
      NOT_WITNESS = 0x25; //Added
      ...
      UNKNOWN = 0xFF;
    }

### Give ReasonCode before disconnect

Use ReasonCode NOT_WITNESS in RelayService.java :
![image](https://github.com/tronprotocol/java-tron/assets/23312631/b898d33d-9900-4f99-9f3e-d5829688aa35)

Use ReasonCode NOT_WITNESS in PeerManager.java : 
<img width="501" alt="image" src="https://github.com/tronprotocol/java-tron/assets/23312631/e9b6dd4f-edd9-409c-9f95-172133930ad8">

# Compatibility

All of the newly added unrecognized ReasonCode will be converted to UNKNOWN, and no exception will be thrown.

**Comment by lvs007** [comment]
It sounds very helpful for troubleshooting and clarifying the reasons for disconnection.

**Comment by lvs007** [comment]
Can you analyze where there are currently no reasons for disconnection?

**Comment by wubin01** [comment]
@317787106 When the node is shutting down, the socket service will be closed. Can the disconnect message be sent out at this time?

**Comment by lurais** [comment]
@317787106 Shall we send an ack for the disconnect message ?

**Comment by 317787106** [comment]
> Can you analyze where there are currently no reasons for disconnection?

I have find two situation where there are no disconnection reason until now.  I may update this issue later.

**Comment by 317787106** [comment]
@lurais No ack will be sent for the disconnect message.

**Comment by 317787106** [comment]
> @317787106 When the node is shutting down, the socket service will be closed. Can the disconnect message be sent out at this time?

@wubin01 The problem we are discussing here has nothing to do with node shutdown, it is closing the connection.

**Comment by wubin01** [comment]
> 

@317787106 When the node is shutting down, there will also be a process of closing the connection.

**Comment by 317787106** [comment]
@wubin01 node tries to send disconnect message before shutdown in libp2p, we can discuss here https://github.com/tronprotocol/libp2p/issues/60.

**Comment by 317787106** [comment]
@lvs007 All scenes without no ReasonCode have been updated as above.
