### ISSUE TITLE
Moving LiteFullNodeTest test cases to plugins module

### ISSUE THREAD

**Issue by forfreeday** [tronprotocol/java-tron#5380]
## Rationale

Since `LiteFullNode` function has been moved to the `plugins` module as `DbLite`, and the corresponding test cases should be grouped into the `plugins` block. Moving test cases to the `plugins` module also improves the efficiency of test case execution. The test cases in the `framework` and `plugins` modules run in parallel.

### 1. Adding dependencies

Add a dependency to the `build.gradle` of the `plugins` module.

```
testCompile project(":framework")
testCompile project(":framework").sourceSets.test.output
```

### 2. Moving test cases around

Move the `org/tron/program/LiteFullNodeToolTest.java` test case from the `framework` module to the `plugins` module and rename it to `org/tron/plugins/DbLiteTest.java`.

**Comment by chengtx01** [comment]
Improving the efficiency of test cases sounds great. I feel that the current execution time of test cases is relatively long. May I ask, how much time can be saved by this operation?

**Comment by forfreeday** [comment]
This saves about 3 minutes because the LiteFullNodeTest test cases are executed in parallel in the `plugins` module.

**Comment by mikeluxue** [comment]
A Little curiours about why you want to seperate this LiteFullNodeTest test cases to other place? does it have any bad effects to current ?

**Comment by forfreeday** [comment]
@mikeluxue 
Because the current test cases are executed serially, the execution time is long. Moving to other modules allows you to execute the test cases in parallel, node the execution time of the test cases, and improve the efficiency of executing the test cases.
