### ISSUE TITLE
Give suggestion about checkpoint v2 error info

### ISSUE THREAD

**Issue by lurais** [tronprotocol/java-tron#5381]
# Rationale
The current database uses a checkpoint mechanism to ensure data integrity and consistency, and the mechanism has two versions, namely v1 and v2. If you are currently using the v2 version, you cannot use v1 again after restarting the node, so if this is the case, an error will be reported when starting the node with no solution provided. Therefore, it is necessary to propose a solution while the error info is printed so that users are able to be aware of this issue.
Why should this feature exist?
To improve user-friendliness.

# Implementation
Just add the solution in the log while the error info is printed.(eg:)

Are you willing to implement this feature?
yes

**Comment by chengtx01** [comment]
If I am currently using version 2, what exceptions will occur if I restart the node using version 1? Will the node fail to start? Or will there be worse consequences?

**Comment by lurais** [comment]
> If I am currently using version 2, what exceptions will occur if I restart the node using version 1? Will the node fail to start? Or will there be worse consequences?

@chengtx01 No exceptions will be thrown, and error log will be printed ,then it will exit  directly, it will be stoped and no other consequences
