### ISSUE TITLE
Give suggestion about db corrupt error info

### ISSUE THREAD

**Issue by lurais** [tronprotocol/java-tron#5382]
# Rationale
When the current database is in use, it may be damaged due to various reasons. When damaged, the log will provide error information, but no suggestion is provided for users to deal with this situation. It is necessary to print out the corresponding suggestions, along with the database error information, such as re-downloading the database and restarting the node.
Why should this feature exist?
To improve user-friendliness.

# Implementation
Just add the solution in the log while the error info is printed.

Are you willing to implement this feature?
yes

**Comment by guoquanwu** [comment]
Can you show a comparative demo so that we can have a clear understanding of this optimization?

**Comment by lurais** [comment]
> Can you show a comparative demo so that we can have a clear understanding of this optimization?

yes, currently we just print "Can't initialize database, account" when the account is corrupted , but we can just print "Can't initialize database: account, please delete all the databases and download the databases and restart the node." instead. @guoquanwu

**Comment by guoquanwu** [comment]
Good, we can think about how to give a more precise tip
