### ISSUE TITLE
Transfer Token ERC20 from contracts failed 

### ISSUE THREAD

**Issue by liscody** [tronprotocol/java-tron#5388]
Hello!
Blochain Shasta Tron 
Deployed two contracts:
- Wallet.sol (THRftB26L2D2xuxfnmKoptWn4JtPM1AkGG)
- USDT.sol (My copy of the original contract for testing) (TKnpv4XgQhqLSXgCqj7WhFVNQV5ENSD3Tv)

I try to transfer TRX from the wallet contract, and it passed well. (tx https://shasta.tronscan.org/#/transaction/efa403f3641d0c0f6e26455c397a4f9248d44b4c74cbc9270eb0b11628b73741)

Also, I try to send a test USDT tokens from the wallet contract but this transaction reverted ( tx https://shasta.tronscan.org/#/transaction/dc98a371b989d84ab5af2db97487bde51c72153ad51740f6e5304ec715bb19c5) 

How to fix this problem?
Thanks in advance for any solutions....

**Comment by Channing0501** [comment]
Revert is a type of error occurs when smart contract executing, and it needs to analysis from the smart contract code according to the "contractResult" returns by gettransactioninfobyid API. 
```
curl --location --request POST 'https://api.shasta.trongrid.io/wallet/gettransactioninfobyid' \
--header 'Content-Type: application/json' \
--data-raw '{
     "value": "dc98a371b989d84ab5af2db97487bde51c72153ad51740f6e5304ec715bb19c5",
     "visible":true
}'
```
Convert the "contractResult" in return value from the hex format to string, we can get the error information: SafeERC20: ERC20 operation did not succeed. It is from the code, so please try to analysis the code through the parameter to solve this issue.
