### ISSUE TITLE
getHeadBlockId abnormal return

### ISSUE THREAD

**Issue by wubin01** [tronprotocol/java-tron#5389]
# System information

Java-tron version: v4.7.2
OS & Version: Linux & macOS

# Expected behavior

The `getHeadBlockId` function should return the correct block header information.

# Actual behavior

When synchronizing blocks, an abnormal block ID appears, as shown in the following log:
<img width="800" alt="image" src="https://github.com/tronprotocol/java-tron/assets/37210306/6437783f-79d3-473f-9a6f-8f45061d5414">

This ID: `00000000032b9cc50deb2777f7e751ade0245ace23c2cc8579d733af34401832` is composed of two parts, the number of block 53189829 and the hash of block 53189830. The reason for this phenomenon is that there is a concurrency problem in this function. The function definition is as follows:
```
public synchronized BlockId getHeadBlockId() {
    return new BlockId(
        dynamicPropertiesStore.getLatestBlockHeaderHash(),
        dynamicPropertiesStore.getLatestBlockHeaderNumber());
  }
```
When calling this function, if only the block hash is written at this time, and the block number has not been written in time, the above-mentioned situation will occur.

**Comment by chengtx01** [comment]
Do you have any good solutions for how to solve this concurrency problem?

**Comment by wubin01** [comment]
@chengtx01 Just use `dynamicPropertiesStore.getLatestBlockHeaderHash()` to construct, The function implementation is as follows.
```
public synchronized BlockId getHeadBlockId() {
    return new BlockId(dynamicPropertiesStore.getLatestBlockHeaderHash());
  }
```
