### ISSUE TITLE
There should be a configure item which can set the rate limit for all single API.

### ISSUE THREAD

**Issue by ferdinand026** [tronprotocol/java-tron#5390]
# Rationale
Limiting the API access rate can not only effectively allocate node resources, but also ensure the stable running of a node. Java-tron supports API rate limits, it only supports separately setting the rate limit of each interface, or setting a global rate limit for all APIs.  But it not supports to configure one item to control all single API. Expected there is a configure item which can set the rate limit for all single API.

## Why should this feature exist?
There are so many APIs provided by java-tron. if user wants to configure each API's rate limit to 10, he needs to configures interfaces one by one, which is too much work. So It would be great if there will be a single configure item like this.

**Comment by xq-lu** [comment]
what is the relationship between the globe rate limit config and the single rate limit config? In other words, how to coordinate when both globe config and single config existed in the project, could you provide more details?

**Comment by wubin01** [comment]
@ferdinand026 This is a great idea and complements the rate limiting feature.

**Comment by halibobo1205** [comment]
Close with #5502.
