### ISSUE TITLE
Expected to support gRPCurl tool for grpc interface invocation easily

### ISSUE THREAD

**Issue by hitlxy** [tronprotocol/java-tron#5391]
# Rationale
Expected Java-tron to support gRPCurl tool for grpc interface invocation.

## Why should this feature exist?
Java-tron supports HTTP、json-rpc and grpc APIs,  some users may usually test them through command line tool, For example, curl and grpcurl and so on.  For http and json-rpc API, they may use curl command, but for grpc call, gRPCurl is not supported by Java-tron. Although other tools can be used: postman or bloomRPC, but they may generally need to import proto files, which is not convenient enough for users to use.

**Comment by guoquanwu** [comment]
> they may generally need to import proto files, which is not convenient enough for users to use.

Yes. TRON now does not support the reflection of gRPC, if you are maintaining a fullnode, you can try to update the code to support the reflection.

Demo:
```
// add the dependency in `build.gradle` in the framework module
compile "io.grpc:grpc-services:1.14.0"

// add ReflectionService in `RpcApiService` before  `serverBuilder.build()`
serverBuilder.addService(ProtoReflectionService.newInstance());
```

Or would you like to submit a PR to help TRON support this feature?

**Comment by Mgarcia1996** [comment]
Bien
