### ISSUE TITLE
What is the default rate limit for a single API？

### ISSUE THREAD

**Issue by ferdinand026** [tronprotocol/java-tron#5397]
I saw the default qps is 10000 per second [here](https://github.com/tronprotocol/java-tron/blob/develop/framework/src/main/resources/config.conf#L294C37-L294C37), But actually it seems that the max access rate is about 1000 per second, so what is the default access rate limit for a interface indeed?

**Comment by wubin01** [comment]
@ferdinand026  The default value is 100

**Comment by halibobo1205** [comment]
<img width="1010" alt="image" src="https://github.com/tronprotocol/java-tron/assets/82020050/e3ea19d9-8338-4731-bb3e-00e30e17e88b">
Needs to be fixed.

**Comment by jwrct** [comment]
@ferdinand026 In [GreatVoyage-v4.7.3](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.7.3), a unified rate limit configuration `rate.limiter.global.api.qps` has been provided for all HTTP and gRPC APIs.

**Comment by ferdinand026** [comment]
Thank you very much.
