### ISSUE TITLE
Operating behind the NAT w/ TCP only

### ISSUE THREAD

**Issue by arcivanov** [tronprotocol/java-tron#5400]
# Rationale

1. In secure cloud solutions nodes are generally behind the NAT gateway with multiple dynamic public IP addresses and fluctuating outgoing source ports, i.e. no incoming connections are practically possible, only stateful replies.
2. It is possible to setup ingress gateways, but routing UDP responses across multiple nodes over a single load-balancer is practically impossible - responses arriving on the LB will be likely misrouted among the servers.
3. Furthermore if a node is deployed with Kubernetes/Mesh, UDP response routing is extremely complicated, if possible at all.

Peer discovery can be easily accomplished with sending exactly the same requests and responses to TCP 18888 instead of UDP, thus avoiding the connection-less nature of things.

# Implementation

Do you have ideas regarding the implementation of this feature?

Currently, if you disable `node.discovery` and fill `node->active` with `seed` IPs the synchronization works for certain number of blocks until it seizes (why?), i.e. even now the primary function of the Tron node is unaffected by the absence of UDP. Thus the only changes required are to:

1. Pick a port on which TCP discovery can be active (if TCP peer discovery cannot be added to TCP 18888).
2. Modify libp2p to have an option to exchange discovery messages on the TCP port in [1].

No protocol modification beyond that should be necessary.

Are you willing to implement this feature?
Yes.

**Comment by wubin01** [comment]
@arcivanov When running the neighbor discovery protocol, there is only one interaction each time. If TCP is used, the connection needs to be established and disconnected every time, which affects performance.

**Comment by arcivanov** [comment]
Sure, but what number of connections are we talking about? 100s? 1000s? or 10000s? If we're talking of 100s of connections per second (assuming the channel in libp2p can't be preserved) that should not be relevant at all.

Furthermore on Linux TCP is dramatically faster than UDP: https://developers.redhat.com/articles/2021/11/05/improve-udp-performance-rhel-85#

**Comment by xq-lu** [comment]
@arcivanov 
I think enabling Node discovery on TCP is a good idea which also makes sense as you describe above.

But in the current scenario, for node discovery, where a node simply wants to make its presence known in order to then establish a formal connection with a peer, UDP is sufficient, also it may have many drawbacks( eg: does not support any error checking, resending of failed packets, or dynamically opening and closing connections)

Using UDP instead of TCP is kind of a trade-off strategy.

**Comment by arcivanov** [comment]
> where a node simply wants to make its presence known in order to then establish a formal connection with a peer, UDP is sufficient

Not when UDP is not available due to environment constraints.

> Using UDP instead of TCP is kind of a trade-off strategy.

To a degree, yes. But this is the only component that prevents the node to function behind the NAT actively establishing outgoing connections while being unable to accept incoming ones. With a TCP-based peer discovery the deployment requirements and constraints are dramatically reduced.

**Comment by arcivanov** [comment]
I want to emphasize, that the UDP here is not merely an inconvenience. Requirement for a UDP server in an NAT environment with a load-balancer (AWS, GCE, Azure etc) completely prevents deployment in that scenario. 
Additionally, the fluctuating outgoing NAT IP results in faulty detection of the "self IPv4" and if the incoming connection is to be established via a load-balancer (also with dynamic set of IPv4/6 addresses) the result is completely non-functional.

TCP-based discovery would entirely solve that problem due to stateful NAT traversal.

**Comment by wubin01** [comment]
@arcivanov The point is that each connection only interacts once. Even if it is tcp, the port will always change. In this simple interaction scenario, UDP can actually meet the requirements.

**Comment by chengtx01** [comment]
@arcivanov Yes, your idea is great. You have pointed out some limitations of Tron, which provides a direction for optimizing the Tron network. However, I have some questions about the implementation plan you proposed. How do you plan to manage the TCP connections discovered by the nodes since they are only temporary? Also, how do we achieve version compatibility, provided that we need to understand the principles of Tron network upgrades?

**Comment by 317787106** [comment]
@arcivanov Your idea sounds good, but some issues may exist as others have raised. Can you implement your idea in libp2p with proposing a pr ? It seems simple, and then we can try it.

**Comment by arcivanov** [comment]
Hello folks. I have managed to work around the the issue. The UDP replies were received and the failure of the Hello with "code: 3" has been within acceptable rates without impacting the node operation. I apologize for the noise and will be closing the issue.

To summarize: if the UDP replies are received within a reasonable time, the stateful NAT GW rules in AWS permit the reply packets to be routed back as long as the replies are to the originating NAT GW IP:port rather than to the IP detected by Tron itself.

If the problem returns I will reopen and implement a prototype solution using TCP.
