### ISSUE TITLE
For stake2.0, why does wallet/getcandelegatedmaxsize API return { }

### ISSUE THREAD

**Issue by laurenceja** [tronprotocol/java-tron#5402]
I query the delegatable bandwidth share through the following command, and it returns empty {}. But the unused bandwidth share is 3TRX, So i need to know why it returns empty or how many unused bandwidth share I need to have so as to wallet/getcandelegatedmaxsize API will not return { }.
```
curl --request POST \
     --url https://api.nileex.io/wallet/getcandelegatedmaxsize \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "owner_address": "TUoHaVjx7n5xz8LwPRDckgFrDWhMhuSuJM",
  "type": 0,
  "visible": true
}
'
```

**Comment by m-o-m12** [comment]
Hi @laurenceja We query the delegatable amount of bandwidth share, then in fact, we may need to delegate resources to others, and delegate resource transaction needs to consume bandwidth, so this interface pre-deducts this part of the bandwidth, then returns. If the delegatable bandwidth share is zero, it returns {}. You can refer to this [doc](https://developers.tron.network/reference/getcandelegatedmaxsize). So If you want to delegate bandwidth to ohters, please stake more TRX to obtain bandwidth, for example 300TRX, have a try.

**Comment by asi90sp** [comment]
Ok
