### ISSUE TITLE
Optimize error logs in signature verification

### ISSUE THREAD

**Issue by lurais** [tronprotocol/java-tron#5423]
# Rationale

At present, in the process of verifying the signature of a transaction, if the signature format is wrong, an error log will also be printed out. But the current form of this error log makes it not clear for developers. And it should be captured and converted to a more understandable exception.
The current error message format is as follows:

> 17:16:23.017 WARN [qtp250219336-22365] o.t.c.Wallet Broadcast transaction fc6a47670a46bf01ad006320b90bb9bd572f45e8d0f199c4f3b222dd737cbff8 failed
java.lang.IllegalArgumentException: Invalid point compression
at [org.bouncycastle.math.ec](http://org.bouncycastle.math.ec/).ECCurve$AbstractFp.decompressPoint(Unknown Source)
at [org.bouncycastle.math.ec](http://org.bouncycastle.math.ec/).ECCurve.decodePoint(Unknown Source)
at org.tron.common.crypto.ECKey.decompressKey(ECKey.java:636)
at org.tron.common.crypto.ECKey.recoverPubBytesFromSignature(ECKey.java:552)
at org.tron.common.crypto.ECKey.signatureToKeyBytes(ECKey.java:426)

Why should this feature exist?
To make the error logs more standardized.
# Implementation
Just catch the exception which is only argument exception type and convert to another more standardized one.

Are you willing to implement this feature?
Yes.

**Comment by halibobo1205** [comment]
@lurais Would you like to submit a PR to improve the situation?

**Comment by lurais** [comment]
> @lurais Would you like to submit a PR to improve the situation?

yes

**Comment by 317787106** [comment]
Which standardized exception will you use? It there any other WARN that print stacktrace ?

**Comment by lurais** [comment]
> o.t.c.Wallet Broadcast transaction

@317787106 I will use SignatureFormatException for that is caused by format of signature,and there is only warn message like this : "17:16:23.017 WARN  [qtp250219336-22365] [o.t.c.Wallet](Wallet.java:591) Broadcast transaction fc6a47670a46bf01ad006320b90bb9bd572f45e8d0f199c4f3b222dd737cbff8 failed
"

**Comment by lurais** [comment]
A pr has been proposed: https://github.com/tronprotocol/java-tron/pull/5446
