### ISSUE TITLE
Tune the databases closure

### ISSUE THREAD

**Issue by halibobo1205** [tronprotocol/java-tron#5428]
# Rationale
Databases are basic, so they are always loaded first and closed last to avoid using unloaded or closed databases.
The spring dependency injection ensures that the databases are always loaded first. 
However, the databases are closed by the [ChainBaseManager.closeAllStore](https://github.com/tronprotocol/java-tron/blob/develop/chainbase/src/main/java/org/tron/core/ChainBaseManager.java#L259), there may be some threads accessing the closed database at `kill -15`.
# Implementation

Do you have ideas regarding the implementation of this feature?

Database beans's shutdown changed to be managed by the Spring IoC container, not by ChainBaseManager.
As documented in [Bean.destroyMethod](https://docs.spring.io/spring-framework/docs/5.3.18/javadoc-api/org/springframework/context/annotation/Bean.html#destroyMethod--):

  > public abstract [String](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html?is-external=true) destroyMethod
The optional name of a method to call on the bean instance upon closing the application context, for example a close() method on a JDBC DataSource implementation, or a Hibernate SessionFactory object. The method must have no arguments but may throw any exception.
As a convenience to the user, the container will attempt to infer a destroy method against an object returned from the @Bean method. For example, given an @Bean method returning an Apache Commons DBCP BasicDataSource, the container will notice the close() method available on that object and automatically register it as the destroyMethod. This 'destroy method inference' is currently limited to detecting only public, no-arg methods named 'close' or 'shutdown'. The method may be declared at any level of the inheritance hierarchy and will be detected regardless of the return type of the @Bean method (i.e., detection occurs reflectively against the bean instance itself at creation time).
To disable destroy method inference for a particular @Bean, specify an empty string as the value, e.g. @Bean(destroyMethod=""). Note that the [DisposableBean](https://docs.spring.io/spring-framework/docs/5.3.18/javadoc-api/org/springframework/beans/factory/DisposableBean.html) callback interface will nevertheless get detected and the corresponding destroy method invoked: In other words, destroyMethod="" only affects custom close/shutdown methods and [Closeable](https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html?is-external=true)/[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html?is-external=true) declared close methods.
Note: Only invoked on beans whose lifecycle is under the full control of the factory, which is always the case for singletons but not guaranteed for any other scope.
See Also:
[DisposableBean](https://docs.spring.io/spring-framework/docs/5.3.18/javadoc-api/org/springframework/beans/factory/DisposableBean.html), [ConfigurableApplicationContext.close()](https://docs.spring.io/spring-framework/docs/5.3.18/javadoc-api/org/springframework/context/ConfigurableApplicationContext.html#close--)
Default:
"(inferred)"

According to [DisposableBeanAdapter.inferDestroyMethodIfNecessary](https://github.com/spring-projects/spring-framework/blob/5.3.x/spring-beans/src/main/java/org/springframework/beans/factory/support/DisposableBeanAdapter.java#L394):
> If the current value of the given beanDefinition's "destroyMethodName" property is AbstractBeanDefinition.INFER_METHOD, then attempt to infer a destroy method. Candidate methods are currently limited to public, no-arg methods named "close" or "shutdown" (whether declared locally or inherited). The given BeanDefinition's "destroyMethodName" is updated to be null if no such method is found, otherwise set to the name of the inferred method. This constant serves as the default for the @Bean#destroyMethod attribute and the value of the constant may also be used in XML within the  or  attributes.
Also processes the java.io.Closeable and AutoCloseable interfaces, reflectively calling the "close" method on implementing beans as well.

A list of known beans that trigger the destroyMethod. 
|| bean | type | trigger type |note|
|--------|--------|--------|--------|--------|
1|checkTmpStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
2|revokingDatabase|revoking db|["(inferred)"-> close()](https://github.com/spring-projects/spring-framework/blob/5.3.x/spring-beans/src/main/java/org/springframework/beans/factory/support/DisposableBeanAdapter.java#L410)| close thread pool|
3|accountStateStoreTrie|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
4|balanceTraceStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
5|accountTraceStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
6|dynamicPropertiesStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
7|accountStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
8|accountAssetStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
9|blockStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
10|witnessStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
11|assetIssueStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
12|assetIssueV2Store|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
13|blockIndexStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
14|accountIdIndexStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
15|accountIndexStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
16|witnessScheduleStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
17|votesStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
18|proposalStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
19|exchangeStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
20|exchangeV2Store|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
21|marketAccountStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
22|marketOrderStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
23|marketPairPriceToOrderStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
24|marketPairToPriceStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
25|abiStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
26|codeStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
27|contractStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
28|contractStateStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
29|delegatedResourceStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
30|delegatedResourceAccountIndexStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
31|storageRowStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
32|nullifierStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
33|ZKProofStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
34|incrementalMerkleTreeStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
35|delegationStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
36|khaosDatabase|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
37|commonStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
38|transactionStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
39|transactionRetStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
40|recentBlockStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
41|recentTransactionStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
42|transactionHistoryStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
43|commonDataBase|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
44|pbftSignDataStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
45|treeBlockIndexStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
46|sectionBloomStore|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
47|pbftMessageHandle|pbft message|[Common Annotations @PreDestroy](https://docs.oracle.com/javase/8/docs/api/javax/annotation/PreDestroy.html)| close timer|
48|transactionCache|db|[AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--)| close db|
49|tronNetDelegate|block sync|[Common Annotations @PreDestroy](https://docs.oracle.com/javase/8/docs/api/javax/annotation/PreDestroy.html)| close thread|

Are you willing to implement this feature?

Yes

**Comment by wubin01** [comment]
@halibobo1205 For example, to prevent the database from being damaged, will there be a scene where the database needs to be closed first, and whether there is a sequence between the databases？

**Comment by halibobo1205** [comment]
> @halibobo1205 For example, to prevent the database from being damaged, will there be a scene where the database needs to be closed first?

@wubin01 , The `database damage` mentioned above, does it refer to `data inconsistency` or `database corruption`? If it is a `data inconsistency`, `checkpoint` can guarantee this, if it is a `database corruption`, it cannot be guaranteed under any case.

> whether there is a sequence between the databases？

  Databases are closed in the reverse order of initialization, as guaranteed by spring.
