### ISSUE TITLE
Downgrade version of io.grpc and  com.google.protobuf

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/java-tron#5430]
# Rationale

To solve security vulnerability, [[pull request 5254](https://github.com/tronprotocol/java-tron/pull/5254)](https://github.com/tronprotocol/java-tron/pull/5254) was submitted to update gradlew dependecy version of package com.google.protobuf and io.grpc.

      compile group: 'com.google.protobuf', name: 'protobuf-java', version: protobufVersion
      compile group: 'com.google.protobuf', name: 'protobuf-java-util', version: protobufVersion

      compile group: 'io.grpc', name: 'grpc-netty', version: grpcVersion
      compile group: 'io.grpc', name: 'grpc-protobuf', version: grpcVersion
      compile group: 'io.grpc', name: 'grpc-stub', version: grpcVersion

The version of com.google.protobuf was upgraded from 3.19.2 to 3.21.12, andio.grpc was upgraded from 1.14.0 to 1.52.1. But Libp2p's dependcies version of these two package refered by Java-tron stays lower. Some communction issues between different versions of protobuf may exist or not known yet.

# Implementation

### Do you have ideas regarding the implementation of this feature?

Downgrade version of com.google.protobuf to 3.19.2, downgrade io.grpc to 1.14.0.

### Are you willing to implement this feature?

Yes.

**Comment by halibobo1205** [comment]
I don't agree with the downgrade, the reasons aren't very strong.

**Comment by forfreeday** [comment]
Have you conducted sufficient downgrade verification?

**Comment by chengtx01** [comment]
@317787106 Would it be more appropriate to also upgrade the versions of com.google.protobuf and andio.grpc in libp2p?

**Comment by 317787106** [comment]
> @317787106 I also have the same question, why downgrade instead of upgrade?

It's not downgrade really but stay the same as 4.7.2. May be someone else can upgrade as libp2p.

**Comment by 317787106** [comment]
@lurais May be it's a good idea, update version of io.grpc and com.google.protobuf in libp2p, and java-tron has same version with libp2p.
