### ISSUE TITLE
Tune the sequence of resources closure

### ISSUE THREAD

**Issue by halibobo1205** [tronprotocol/java-tron#5433]
# Rationale

Why should this feature exist?
The order of loading resources is Databases → Thread Pools -> Network -> Consensus → API, the order of releasing should be reversed, API → Consensus -> Network -> Thread Pools → Databases.

# Implementation

Do you have ideas regarding the implementation of this feature?
As mentioned above.   
- [x] The lifecycle of Databases is managed by the spring container. #5428
- [x] Thread Pools are initialized with beans.
- [x] Application. startup: Network-> Consensus -> API.
- [x] Application.shutdown: API → Consensus -> Network -> Thread Pools.

Are you willing to implement this feature?
 Yes.

**Comment by wubin01** [comment]
@halibobo1205 Each module also has many threads, and these threads also need to have the correct shutdown order.

**Comment by halibobo1205** [comment]
> @halibobo1205 Each module also has many threads, and these threads also need to have the correct shutdown order.

@wubin01 Maybe analyze all the thread pools first.
