### ISSUE TITLE
 Improve code coverage to 70%

### ISSUE THREAD

**Issue by forfreeday** [tronprotocol/java-tron#5434]
# Rationale

Why should this feature exist?

To improve the test case coverage of your code, cover as much as possible.

# Implementation

**database**

- [ ] https://github.com/tronprotocol/java-tron/pull/5461
- [ ] https://github.com/tronprotocol/java-tron/pull/5463

**api**
- [x] https://github.com/tronprotocol/java-tron/pull/5471
- [x] https://github.com/tronprotocol/java-tron/pull/5442

**net**
- [x] https://github.com/tronprotocol/java-tron/pull/5459

Are you willing to implement this feature?
Yes, I would like to complete these use cases and would like to have more people participate in them.

**Comment by wubin01** [comment]
@forfreeday This is a good idea, it is really necessary to increase the unit test rate to avoid introducing bugs.

**Comment by forfreeday** [comment]
@wubin01 

Yes, this will be ongoing, with 70% coverage in the first phase

**Comment by forfreeday** [comment]
Current coverage: 66.48%.
Continuously adding test cases, expected to reach 70% coverage in June.

**Comment by forfreeday** [comment]
Current coverage status:
* actuator: 75.33%
* chainbase: 77.40%
* common: 60.69%
* consensus: 63.49%
* crypto: 71.62%
* framework: 57.51%
* plugins: 70.18%

**Comment by forfreeday** [comment]
Current coverage status:
actuator: 75.33%
chainbase: 77.40%
common: 60.69%
consensus: 63.49%
crypto: 71.62%
framework: 60.51%
plugins: 70.18%

**Comment by lxcmyf** [comment]
Current coverage status:

- actuator: 75.49%
- chainbase: 77.56%
- common: 61.29%
- consensus: 63.75%
- crypto: 71.62%
- framework: 57.74%
- plugins: 71.84%
Subsequently, we will focus on enhancing and increasing the unit test coverage of the framework module.

**Comment by Goodmanisrael27** [comment]
Uploading VID-20240705-WA0000.mp4…

**Comment by lxcmyf** [comment]
Some development work aimed at improving code coverage for low-coverage modules is already in the planning stage.

**Comment by lxcmyf** [comment]
At present, the total coverage rate has reached 66.85%. The following are the latest coverage statistics for each module. Some modules have slightly fluctuated compared to before, which is a normal phenomenon. We now plan to focus on improving the modules with low coverage rates. Currently, the improvement work for the framework module is being carried out urgently, and the improvement of other modules is also being carried out in an orderly manner.
<img width="1288" alt="image" src="https://github.com/user-attachments/assets/6d32465c-216d-4090-a61f-f07d73298ca2">

**Comment by lxcmyf** [comment]
Current coverage status:

actuator: 75.41%
chainbase: 77.82%
common: 69.84%
consensus: 63.50%
crypto: 71.65%
framework: 58.59%
plugins: 71.84%

The total coverage rate is 67.82%.

**Comment by lxcmyf** [comment]
Current coverage status:
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/d4320aa3-713a-484e-9a78-afb5d2a58285">
The total coverage rate is 69.19%.

**Comment by lxcmyf** [comment]
Current coverage status:
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/d4320aa3-713a-484e-9a78-afb5d2a58285">
The total coverage rate is 69.19%.

**Comment by lxcmyf** [comment]
Another PR aimed at improving coverage is currently being prepared and will be released soon.
