### ISSUE TITLE
Add Resource Unit Price Query APIs for Solidity & PBFT

### ISSUE THREAD

**Issue by lxcmyf** [tronprotocol/java-tron#5437]
# Rationale
In the TRON network, `GetEnergyPrices` and `GetBandwidthPrices` are interfaces for querying historical unit prices of bandwidth and energy. However, in recent usage, it has been found that `GetBandwidthPrices` do not have API implementations for solidity and PBFT. However, `GetEnergyPrices` do exist, and bandwidth and energy are frequently used resources in the tron network. Their behavior as interfaces for querying should be consistent. Therefore, We hope to supplement the solidity and PBFT implementation of `GetBandwidthPrices` in future version updates.
Why should this feature exist?

# Implementation

Add the implementation of solidity and PBFT for `GetBandwidthPrices`.

**Comment by halibobo1205** [comment]
great!

**Comment by chengtx01** [comment]
Looking forward to the implementation of this feature.

**Comment by lxcmyf** [comment]
Next, I will implement it by submitting a PR.
