### ISSUE TITLE
The return of `wallet/delegateresource` could not be found in the browser

### ISSUE THREAD

**Issue by FerdyCai** [tronprotocol/java-tron#5443]
The return of wallet/delegateresource is correct, but the returned txID could not be inquired in the browser, how is this happening? And wallet/freezebalancev2 has the same issue.

**Comment by ferdinand026** [comment]
@FerdyCai These APIs only return an unsigned transaction. After we get an unsigned transaction using these APIs, we need to sign it and then broadcast it to the network. After it is successfully on-chain, then it can be queried through transactionID.   [Here](https://developers.tron.network/docs/tron-protocol-transaction#transaction-lifecycle) is the transaction lifecycle.

**Comment by FerdyCai** [comment]
@ferdinand026 请问调用wallet/delegateresource接口后，得到返回数据如下：
{
    "visible": true,
    "txID": "3874c723136b1e34d0b6102e6be0869308af6fc30b4fa0acc8b4ec7b581f00f1",
    "raw_data": {
        "contract": [
            {
                "parameter": {
                    "value": {
                        "balance": 1000000,
                        "resource": "ENERGY",
                        "receiver_address": "TM442vw56hUxmYmZ5L2q3cqZy7ZSBQgRXn",
                        "owner_address": "TG1uAGw5ZKm6VEiqhVPpMoBcLZvGSkuvpX"
                    },
                    "type_url": "type.googleapis.com/protocol.DelegateResourceContract"
                },
                "type": "DelegateResourceContract"
            }
        ],
        "ref_block_bytes": "56bb",
        "ref_block_hash": "2159f7a25f96839e",
        "expiration": 1692694536000,
        "timestamp": 1692694478400
    },
    "raw_data_hex": "0a0256bb22082159f7a25f96839e40c0bed3e3a1315a710839126d0a35747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e44656c65676174655265736f75726365436f6e747261637412340a154142531c0e3d3efdc713ba1fbd51dc98c7cd4098ad100118c0843d2215417993fa4082357fb3a8ea934e6f07050ecf9c643f70c0fccfe3a131"
}
要如何进行签名呢？
