### ISSUE TITLE
Using locally installed levelDB

### ISSUE THREAD

**Issue by smunx** [tronprotocol/java-tron#545]
Hi,
I am trying to compile the code on a Mac server I have resolved most of the compile issues but I am having trouble with levelDB. I was able to install the levelDB mvn repo locally on the machine. How do I make gradle use the local mvn repo ?

This is just one of the failures most of them are linked to levelDB
```
org.tron.common.storage.leveldb.LevelDbDataSourceImplTest > testLockReleased FAILED
    java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.leveldbjni.JniDBFactory
        at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.openDatabase(LevelDbDataSourceImpl.java:100)
        at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.initDB(LevelDbDataSourceImpl.java:84)
        at org.tron.common.storage.leveldb.LevelDbDataSourceImplTest.testLockReleased(LevelDbDataSourceImplTest.java:153)
```

I had similar kind of issues with the jar file(This was compiled on Ubuntu and all the tests passsed).

Thanks,

**Comment by zhaohong** [comment]
@zhangheng1536  follow this

**Comment by smunx** [comment]
Hi,
I was able to resolve the leveldb library install but I hit another problem now. The node also requires leveldbJni libraries but the leveldbJni supports only ARM 64 bit. I dunno how can I compile the leveldbJni for a different architecture. 

Thanks,

**Comment by huzhenyuan** [comment]
@smunx 
The local mvn repo not tested.
Please use the official build script to build.

Is there any problem with the "./gradlew build"?
