### ISSUE TITLE
Delete four unused paramaters in Args

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/java-tron#5453]
# Rationale

There are some outdated network variables and configurations in Args and CommonParameter. Since Libp2p is extracted as an independent project, these variables and configurations have been moved to Libp2p and imported by Java-tron, so they should be deleted. Variables in CommonParameter include:

```
  public boolean nodeDiscoveryPublicHomeNode;
  public long nodeDiscoveryPingTimeout;
  public long nodeP2pPingInterval;
  public String p2pNodeId;
```
Related configurations include:
```
node.discovery.public.home.node
node.discovery.ping.timeout
node.p2p.pingInterval
```

# Implementation

**Do you have ideas regarding the implementation of this feature?**
yes

**Are you willing to implement this feature?**
yes

**Comment by wubin01** [comment]
@317787106 Good idea, these parameters are really not used at the moment, except for the ones listed above, other unused ones can also be optimized together.

**Comment by forfreeday** [comment]
@317787106 
If the parameter is not needed, it can be deleted
