### ISSUE TITLE
LOCC

### ISSUE THREAD

**Issue by Codeone11** [tronprotocol/java-tron#5458]
Trx20
# Rationale

Why should this feature exist?
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no content basically.

Please feel free to re-open it if you have suggestions, comments or issues about java-tron , thanks.
