### ISSUE TITLE
[Bounty] Wallet not synced with testnet 

### ISSUE THREAD

**Issue by endeavors** [tronprotocol/java-tron#546]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I ran java-tron by running
./gradlew build
./gradlew run
and then ran wallet-cli by
./gradlew build
./gradlew run
and then registered a wallet on wallet-cli and also created a wallet on tronscan.org. When I send TRX from tronscan.org to my wallet-cli wallet, I never receive the transaction. I haven't changed the config.conf file. How can I make my wallet sync to the testnet?

2. What did you expect to see?
Wallet accounts should be synced with the testnet and I should receive my transaction from tronscan.org to my wallet-cli wallet

3. What did you see instead?
Transaction never appeared.

Out of curiosity, am I connecting to the testnet properly?

**Comment by oroblu** [comment]
Check from wallet-cli if the lastblock that you get with "getblock" give you the same block present on  tronscan.org,  If not the problem is java-tron not the wallet.

**Comment by wuliqi** [comment]
C:\java-tron-develop\src\main\java\org\tron\core\db\api\index\AbstractIndex.java:109: 错误: 不兼容的类型: 无法推断类型变量 F,T#1
            .filter(Iterables.transform(resultSet, AbstractIndex.this::getObject), Objects::nonNull)
                   ^
    (参数不匹配; 方法引用无效
      对于getObject(? super WrappedByteArray), 找不到合适的方法
          方法 AbstractIndex.getObject(byte[])不适用
            (参数不匹配; Object无法转换为byte[])
          方法 AbstractIndex.getObject(WrappedByteArray)不适用
            (参数不匹配; Object无法转换为WrappedByteArray))
  其中, F,T#1,T#2是类型变量:
    F扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#1扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#2扩展已在类 AbstractIndex中声明的Object
C:\java-tron-develop\src\main\java\org\tron\core\db\api\index\AbstractIndex.java:122: 错误: 不兼容的类型: 无法推断类型变量 F,T#1
            .filter(Iterables.transform(resultSet, AbstractIndex.this::getObject), Objects::nonNull)
                   ^
    (参数不匹配; 方法引用无效
      对于getObject(? super WrappedByteArray), 找不到合适的方法
          方法 AbstractIndex.getObject(byte[])不适用
            (参数不匹配; Object无法转换为byte[])
          方法 AbstractIndex.getObject(WrappedByteArray)不适用
            (参数不匹配; Object无法转换为WrappedByteArray))
  其中, F,T#1,T#2是类型变量:
    F扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#1扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#2扩展已在类 AbstractIndex中声明的Object
C:\java-tron-develop\src\main\java\org\tron\core\db\api\index\AbstractIndex.java:131: 错误: 不兼容的类型: 无法推断类型变量 F,T#1
        .filter(Iterables.transform(index, AbstractIndex.this::getObject), Objects::nonNull)
               ^
    (参数不匹配; 方法引用无效
      对于getObject(? super WrappedByteArray), 找不到合适的方法
          方法 AbstractIndex.getObject(byte[])不适用
            (参数不匹配; Object无法转换为byte[])
          方法 AbstractIndex.getObject(WrappedByteArray)不适用
            (参数不匹配; Object无法转换为WrappedByteArray))
  其中, F,T#1,T#2是类型变量:
    F扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#1扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#2扩展已在类 AbstractIndex中声明的Object
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
3 个错误
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
4 actionable tasks: 4 executed
Compilation failed; see the compiler error output for details.
15:23:08: Task execution finished 'build'.

**Comment by marcusyanghe** [comment]
Hi, @endeavors,
(Just in case, my last comment of the same content may not be shown to you, since my prev account was flagged by GitHub spam system, so I am using this account to repost the same comment)
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang

**Comment by kookiekrak** [comment]
@PanamaCatalyst please email me at tian@Tron.network for a developer slack invite!
