### ISSUE TITLE
/tmp directory is full of sapling-send.params.* files and libzksnarkjni* files

### ISSUE THREAD

**Issue by mumianhua** [tronprotocol/java-tron#5465]
#### System information

java-tron version: latest develop  or other new branches based on develop branch
OS & Version:  aws CentOS Linux release 7.8.2003 (Core)
Commit hash : (if `develop`)

#### Expected behaviour
sapling-send.params.* files and libzksnarkjni* files in /tmp directory can be removed by java-tron

#### Actual behaviour
/tmp directory is full of sapling-send.params.* files and libzksnarkjni* files

#### Steps to reproduce the behaviour
1、git clone java-tron project
2、cd "java-tron  project directory", and then run several times "./gradlew clean build" 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by halibobo1205** [comment]
[deleteOnExit not deleting file](https://stackoverflow.com/questions/24758520/deleteonexit-not-deleting-file)

**Comment by halibobo1205** [comment]
`sapling-send.params `needs to be deleted manually for now.
