### ISSUE TITLE
Problem Own Tron Node `Stuck` In Block And Can't Get New Block

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5466]
My tron node stuck in 
![image](https://github.com/tronprotocol/java-tron/assets/80700084/dffbc6c7-17f2-4ab5-a24e-e3d417c26eb6)

this block
I delete my chaindata and download new chaindata from https://developers.tron.network/docs/main-net-database-snapshots

but still stuck and can't update and get new block,

how can fix that ? 

my main_net_config.conf is https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf

and my docker-compose.yml config is 
![image](https://github.com/tronprotocol/java-tron/assets/80700084/2a555242-33c6-4875-91d8-390e0ce44af8)

this is my tron.log file

![image](https://github.com/tronprotocol/java-tron/assets/80700084/82c854a3-ad5f-4c6f-a910-beb799b18fb8)
![image](https://github.com/tronprotocol/java-tron/assets/80700084/682fc301-13f6-4e57-8a21-40d3ee1226ef)

please help me

**Comment by ss3344520** [comment]
@kasrakhamesi Can you provide the complete log?

**Comment by bughoho** [comment]
I have the same problem.always stuck in block 54633223 and can' get new block.
pls help me
[logs.zip](https://github.com/tronprotocol/java-tron/files/12778648/logs.zip)

**Comment by bughoho** [comment]
09:16:16.207 ERROR [pool-48-thread-1] [DB](KhaosDatabase.java:119) Block: BlockCapsule 
[ hash=000000000341a3117f1cdaa75b33484384afe1d0204eeadd997ccec47027036b
number=54633233
parentId=000000000341a310cb3b2127902a3e3d1a9e010d982632d70f5c46a0b7d9a5d2
witness address=41456798cb4ab28109d8cc643cd7da7bd6069ceae9
generated by myself=false
generate time=2023-09-12 22:50:36.0
account root=0000000000000000000000000000000000000000000000000000000000000000
merkle root=ef6c25e36dec3474bb0447fab06511ad0518012b74989e1d53387b8684f5f4ab
txs size=192
], head: KhaosBlock{blk=BlockCapsule 
[ hash=000000000341a30701810d5000337e3de5b2b1491ab5ef6f5250a0e538ae5d2d
number=54633223
parentId=000000000341a306e2eb34b91ac2f63e9967807ff3bb7cc00e8d683cb8bade82
witness address=419a96c8003a1e3a6866c08acff9f629e2a6ef062b
generated by myself=false
generate time=2023-09-12 22:50:06.0
account root=0000000000000000000000000000000000000000000000000000000000000000
merkle root=a8ca18727fb09d546036a6bae7dda07373512ebccd6b0234c5787126a0a16e35
txs size=285
], parent=null, id=000000000341a30701810d5000337e3de5b2b1491ab5ef6f5250a0e538ae5d2d, num=54633223}, miniStore: KhaosStore{hashKblkMap={000000000341a30701810d5000337e3de5b2b1491ab5ef6f5250a0e538ae5d2d=KhaosBlock{blk=BlockCapsule 
[ hash=000000000341a30701810d5000337e3de5b2b1491ab5ef6f5250a0e538ae5d2d
number=54633223
parentId=000000000341a306e2eb34b91ac2f63e9967807ff3bb7cc00e8d683cb8bade82
witness address=419a96c8003a1e3a6866c08acff9f629e2a6ef062b
generated by myself=false
generate time=2023-09-12 22:50:06.0
account root=0000000000000000000000000000000000000000000000000000000000000000
merkle root=a8ca18727fb09d546036a6bae7dda07373512ebccd6b0234c5787126a0a16e35
txs size=285
], parent=null, id=000000000341a30701810d5000337e3de5b2b1491ab5ef6f5250a0e538ae5d2d, num=54633223}}, maxCapacity=1024, numKblkMap={54633223=[KhaosBlock{blk=BlockCapsule 
[ hash=000000000341a30701810d5000337e3de5b2b1491ab5ef6f5250a0e538ae5d2d
number=54633223
parentId=000000000341a306e2eb34b91ac2f63e9967807ff3bb7cc00e8d683cb8bade82
witness address=419a96c8003a1e3a6866c08acff9f629e2a6ef062b
generated by myself=false
generate time=2023-09-12 22:50:06.0
account root=0000000000000000000000000000000000000000000000000000000000000000
merkle root=a8ca18727fb09d546036a6bae7dda07373512ebccd6b0234c5787126a0a16e35
txs size=285
], parent=null, id=000000000341a30701810d5000337e3de5b2b1491ab5ef6f5250a0e538ae5d2d, num=54633223}]}}, miniUnlinkedStore: KhaosStore{hashKblkMap={000000000341a3117f1cdaa75b33484384afe1d0204eeadd997ccec47027036b=KhaosBlock{blk=BlockCapsule 
[ hash=000000000341a3117f1cdaa75b33484384afe1d0204eeadd997ccec47027036b
number=54633233
parentId=000000000341a310cb3b2127902a3e3d1a9e010d982632d70f5c46a0b7d9a5d2
witness address=41456798cb4ab28109d8cc643cd7da7bd6069ceae9
generated by myself=false
generate time=2023-09-12 22:50:36.0
account root=0000000000000000000000000000000000000000000000000000000000000000
merkle root=ef6c25e36dec3474bb0447fab06511ad0518012b74989e1d53387b8684f5f4ab
txs size=192
], parent=null, id=000000000341a3117f1cdaa75b33484384afe1d0204eeadd997ccec47027036b, num=54633233}}, maxCapacity=1024, numKblkMap={54633233=[KhaosBlock{blk=BlockCapsule 
[ hash=000000000341a3117f1cdaa75b33484384afe1d0204eeadd997ccec47027036b
number=54633233
parentId=000000000341a310cb3b2127902a3e3d1a9e010d982632d70f5c46a0b7d9a5d2
witness address=41456798cb4ab28109d8cc643cd7da7bd6069ceae9
generated by myself=false
generate time=2023-09-12 22:50:36.0
account root=0000000000000000000000000000000000000000000000000000000000000000
merkle root=ef6c25e36dec3474bb0447fab06511ad0518012b74989e1d53387b8684f5f4ab
txs size=192
], parent=null, id=000000000341a3117f1cdaa75b33484384afe1d0204eeadd997ccec47027036b, num=54633233}]}}.
09:16:16.208 ERROR [pool-48-thread-1] [DB](Manager.java:1237) LatestBlockHeaderHash: 000000000341a30701810d5000337e3de5b2b1491ab5ef6f5250a0e538ae5d2d, latestBlockHeaderNumber: 54633223, latestSolidifiedBlockNum: 54633205.

**Comment by ss3344520** [comment]
@kasrakhamesi   @bughoho    Which specific day's snapshot are you using?  Have you solved this problem?

**Comment by omkar-bestdeveloperBTZ** [comment]
i'm having a smilar issue , my tron block gets stuck at a particular block number,I did shut down the node, i deleted the db & used latest snapshot, then the node started  syncing again. but later after a few hours it stopped again, what is the issue here, there are no error in the logs

**Comment by halibobo1205** [comment]
Closing for now but please continue the discussion thread if you are looking for more help.

**Comment by omkar-bestdeveloperBTZ** [comment]
I finally resolved by using newer snapshot of database but not sure why we need to do this process of using newer snapshots so many times.
