### ISSUE TITLE
Optimize the efficiency of running LiteFullNode test cases

### ISSUE THREAD

**Issue by forfreeday** [tronprotocol/java-tron#5489]
# Rationale

**Why should this feature exist?**
Improve the efficiency of test case execution, moving test cases to plugins can reduce the execution time by about 3 minutes.

# Implementation

Split into three steps:
1. Change `LiteFullNodeTool` and `LiteFullNodeToolTest` to deprecated and in the `run` method prompts: LiteFullNodeTool is an obsolete tool and is not recommended to be used any more, please use the tool DbLite
   ```java
   @Slf4j
   @Deprecated
   public class LiteFullNodeTool {
       ...
       private void run(Args argv) {
          logger.info("LiteFullNodeTool is an obsolete tool and is not recommended to be used any more, please use the tool DbLite.");
      }
   }
   ```
2. Copy the `LiteFullNodeTest` test case from the `framework` into the `plugins` module and name it `DbLiteTest`,path: `org/tron/plugins/DbLiteTest.java`
   ```java
   @Slf4j
   public class DbLiteTest {
   ```
3. The next release will remove `LiteFullNodeTest` from the `framework`

**Comment by halibobo1205** [comment]
`org.tron.tool.litefullnode` need to be removed,  otherwise, coverage will decrease.
