### ISSUE TITLE
use the appropriate log level

### ISSUE THREAD

**Issue by halibobo1205** [tronprotocol/java-tron#5495]
# Rationale

**Why should this feature exist?**

Logging levels distinguish various log events from each other. They are used for filtering important information about your system’s state and reducing information noise or alert fatigue. It is essential to realize that the logging event level is the key to this process. Setting a specific log level in the logging framework ensures less important logging levels can be reasonably ignored.
It is crucial to choose the right logging level when developing an application. This is beneficial to everyone using logs when searching for problems, creating alerts, troubleshooting, or regularly checking the application.
During coding, it may not seem like an important thing to consider. Yet, it is still essential to ease information search, alerting, and filtering when handling vast log messages that the systems produce. To make your logs more useful, ensure that you choose the right logging levels. 

# Implementation

**Do you have ideas regarding the implementation of this feature?**

<img width="859" alt="image" src="https://i.stack.imgur.com/z5Fim.png">

**Are you willing to implement this feature?**

This is an ongoing improvement.

# Related PRs
- [x]  #5496 
- [x]  #5499
- [x]  #5601
- [x]  #5624
- [x]  #5687
- [x]  #5697

**Comment by JeetDSharma** [comment]
@halibobo1205, I would like to provide help on this issue

**Comment by JeetSharmaKarpuragaurai** [comment]
@halibobo1205 on what part/file should I start working on, also I am new open source hence apologies for any inconvenience. in advance.

**Comment by JeetDSharma** [comment]
@halibobo1205 on what part/file should I start working on, also I am new open source hence apologies for any inconvenience. in advance.

**Comment by halibobo1205** [comment]
@JeetDSharma Hello, you can start from `framework/src/main/java/org/tron/core/services`,  this is the API, and there may be some unreasonable logging. Your contributions are welcome!

**Comment by halibobo1205** [comment]
@JeetDSharma Anything new so far?
