### ISSUE TITLE
tron key

### ISSUE THREAD

**Issue by datis7756** [tronprotocol/java-tron#5497]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Discord](https://discord.gg/cGKSsRVCGm) or [Telegram](https://t.me/TronOfficialDevelopersGroupEn).

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no content basically.

Please feel free to re-open it if you have suggestions, comments or issues about java-tron , thanks.
