### ISSUE TITLE
Problem with `Kafka` in event subscription

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5510]
Hi,I have many try but can't running kafka for tron event,please help me

this is my docker-compose file
![image](https://github.com/tronprotocol/java-tron/assets/80700084/a041ae60-3b2f-47b3-b7c6-3625b792d538)

this is my main_net_config.conf file 
![image](https://github.com/tronprotocol/java-tron/assets/80700084/cee7159b-4e2d-43e8-a809-b7be854afe98)

this is my kafka.js file for show result : 
![image](https://github.com/tronprotocol/java-tron/assets/80700084/fc75f34f-cd5e-472b-ae91-5bf62f948d63)

docker-compose worked fine and up without any error about plogin in tron.log file

but always show me

 {"level":"ERROR","timestamp":"2023-09-21T20:44:13.084Z","logger":"kafkajs","message":"[Connection] Connection error: read ECONNRESET","broker":"ip:port","clientId":"my-app","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"}
{"level":"ERROR","timestamp":"2023-09-21T20:44:13.087Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: read ECONNRESET","retryCount":3,"retryTime":1754}

error when trying to see data from kafka

firewall allow all port

I tested it in linux ubuntu

all read all document like : https://developers.tron.network/docs/event-plugin-deployment-kafka

but can't start kafka event plugin

please help me to start kafka event plugin for tron node with docker-compose.yml file

**Comment by 317787106** [comment]
@kasrakhamesi Kafka event plugin is deprecated, you can use jsonrpc service.

**Comment by kasrakhamesi** [comment]
> @kasrakhamesi Kafka event plugin is deprecated, you can use jsonrpc service instead. See more detail https://developers.tron.network/reference/json-rpc-api-overview

I want a future like websocket for node, to subscribe transaction like ethereum web3.js

json rpc only have http request :((

**Comment by 317787106** [comment]
> > @kasrakhamesi Kafka event plugin is deprecated, you can use jsonrpc service instead. See more detail https://developers.tron.network/reference/json-rpc-api-overview
> 
> I want a feature like websocket for tron node to subscribe transactions like ethereum web3.js
> 
> json rpc only have http request :((

ZeroMQ is supported, you can also subscribe transactions. kafka plugin is not maintained recent years.

**Comment by kasrakhamesi** [comment]
> > > @kasrakhamesi Kafka event plugin is deprecated, you can use jsonrpc service instead. See more detail https://developers.tron.network/reference/json-rpc-api-overview
> 
> > 
> 
> > I want a feature like websocket for tron node to subscribe transactions like ethereum web3.js
> 
> > 
> 
> > json rpc only have http request :((
> 
> 
> 
> ZeroMQ is supported, you can also subscribe transactions, it's very simple. And api eth_getFilterLogs of jsonrpc has similar function as websocket.  kafka plugin is not maintained recent years.

zeroMq have many problem, for example when start it for 5 hours or more,that stopped and should I restart tronNode or zeroMq client.

so, zeroMq not stable when we want uptime 100% for 2 or 3 month or more

**Comment by CarlChaoCarl** [comment]
@kasrakhamesi 
I configured kafka and java-tron according to the following documents. 
https://developers.tron.network/docs/event-plugin-deployment-kafka
As a result, events were subscribed normally and no exceptions occurred.
I read your question, please check it by following the steps below:

1. Please check the following two configurations in your configuration file config.conf:

      path = "/home/dev/event-plugin/build/plugins/plugin-kafka-1.0.0.zip" // absolute path of plugin
      server = "127.0.0.1:9092" // target server address to receive event triggers
     
 Is your path filled in with the correct full path?
 Is your server configured with ip:port? (The one configured in the screenshot is kafka:9092)

2. Please check whether you have created subscription topics in Kafka
      bin/kafka-topics.sh --create --topic block --bootstrap-server 127.0.0.1:9092
Have you used the above command to create kafka topics?

3. Please check whether you have started an event subscription node
      java -jar FullNode.jar -c config.conf --es
Did you add the --es parameter when starting java-tron?

If all the above checks are correct, we will follow up for troubleshooting.

**Comment by vivian1912** [comment]
@kasrakhamesi  Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
