### ISSUE TITLE
Optimize database backup logic

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/java-tron#5512]
# Rationale

The automatic database backup logic of Java-tron can manually roll back to the state before a certain block when there is a problem with the data. During the automatic database backup process, use the enumeration type state(\`enum State\`) to mark the current state:

      public enum State {
        BAKINGONE(1), BAKEDONE(11), BAKINGTWO(2), BAKEDTWO(22);
        private int status;

        State(int status) {
          this.status = status;
        }

        public static State valueOf(int value) {
          switch (value) {
            case 1:
              return BAKINGONE;
            case 11:
              return BAKEDONE;
            case 2:
              return BAKINGTWO;
            case 22:
              return BAKEDTWO;
            default:
              return BAKEDONE;
          }
        }

        public int getStatus() {
          return status;
        }
      }

But in fact, only BAKEDONE and BAKEDTWO are used:
![image](https://github.com/tronprotocol/java-tron/assets/23312631/d4c0dbb6-0a59-4992-9b48-7acc4edfe118)
State changes

# Implementation

1.  Clear useless backup status
2.  Give the correct initialization state

**Comment by halibobo1205** [comment]
Did the previous code function correctly?

**Comment by 317787106** [comment]
> Did the previous code function correctly?

yes.

**Comment by lurais** [comment]
The BAKINGONE state seems like some init state, so have you understand what this state represents?

**Comment by halibobo1205** [comment]
Replaced by #5698.
