### ISSUE TITLE
The account is not activated and therefore cannot be used to transfer assets

### ISSUE THREAD

**Issue by bilaljawed** [tronprotocol/java-tron#5513]
Hey guys,

I have fully synced lite node from snapshots but when i try to send funds using my own rpc url from Tron link wallet I get this error: The account is not activated and therefore cannot be used to transfer assets

However the same account with other public RPCs is working,

Is there anything I am missing?

Thanks

**Comment by ferdinand026** [comment]
Is it a mainnet lite fullnode? you can check the node information by wallet/getnodeinfo API.

**Comment by bilaljawed** [comment]
Yes its mainnet lite fullnode, the api works but seems like tron link doesn't support custom rpcs as it doesn't take transactions ids
