### ISSUE TITLE
Missing `Transaction Status` in `Json-rpc` api

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5514]
in https://developers.tron.network/reference/eth_getblockbyhash api
I want get transaction status in this route : success or failed

now its bad way to get transaction status because need 1 request for each transaction to get transaction status,
for example If I want get transaction status of Transactions in block,I should 1 request per each transaction.

so, When 100 transaction exist in one block, I should send 100 request to check transaction status for all of them,

In web3 for ethereum. web3 Package has BatchRequest and handled that.but In tron node not exist.

please help me.I Want using that for create my Own indexer without mongo plugin or kafka plugin for tron node
I don't want using Full Node Solidity HTTP API.I Want using tron jsonrpc-api

**Comment by CarlChaoCarl** [comment]
Based on my understanding:
BatchRequest is specifically designed for batching JSON-RPC calls to your Ethereum node's API. Transactions are independent and unrelated to these calls. BatchRequest can only provide a moderate reduction in HTTP traffic.
The consideration of adding this feature will be included in the next version of TRON.

@kasrakhamesi  @317787106

**Comment by 317787106** [comment]
@kasrakhamesi eth_getblockbyhash only returns a list of transaction hash, that's compatible with Ethereum node's API. There are some many cloumns of transaction, we could't add anything except hash.

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
