### ISSUE TITLE
State root is 0x for all blocks

### ISSUE THREAD

**Issue by mariabeyrak** [tronprotocol/java-tron#5518]
Hello! Why does `stateRoot` always return as `0x` for all blocks? As far as I understand, it has been renamed from accountStateRoot (see [TIP-23](https://github.com/tronprotocol/TIPs/issues/23)).

It gets updated through the following code:
https://github.com/tronprotocol/java-tron/blob/de23b55d8d9318e32da46bdc90fa28c4094318d0/framework/src/main/java/org/tron/core/services/jsonrpc/types/BlockResult.java#L103
This code retrieves results from here:
https://github.com/tronprotocol/java-tron/blob/de23b55d8d9318e32da46bdc90fa28c4094318d0/framework/src/main/java/org/tron/core/db/accountstate/callback/AccountStateCallBack.java#L99

Request example:
POST https://api.trongrid.io/jsonrpc
```
{
    "method":"eth_getBlockByHash",
    "params":["000000000345fe33b0eb7a61b6faa4260abc89d59336ac29751f2bb06a48e46a",false],
    "id":1,
    "jsonrpc":"2.0"
}

```

**Comment by CarlChaoCarl** [comment]
Hello，Java-tron currently does not support state trees, and the state tree functionality is temporarily disabled in the online environment.

**Comment by mariabeyrak** [comment]
@CarlChaoCarl, thank you for your answer!
Bu I still can deploy a custom node that will save the stateRoot? (As far as I understand, this relates to the 'committee.allowAccountStateRoot' parameter)

**Comment by CarlChaoCarl** [comment]
This proposal  allowAccountStateRoot is currently in a disabled state
@mariabeyrak
