### ISSUE TITLE
fauilure while deploying upgradeable TRC20 contract with proxy contract

### ISSUE THREAD

**Issue by eitanZcharia1** [tronprotocol/java-tron#5522]
Hi All, 

i am trying to implement an upgradeable TRC20 and a proxy contract - the contracts code can be found below. 
i have account on shasta with 17729K energy and 10,209 bandwith. 
while trying to deploy the contract using tronbox i am getting the following error:

Deploying MyProxy...
ERROR: Contract MyProxy has not been deployed on the network.
For more details, check the transaction at:
http://127.0.0.1:9090/wallet/gettransactionbyid?value=XXXXXXXXX
If the transaction above is empty, most likely, your address had no bandwidth/energy to deploy the contract.

- The TRC20 contract implementation was taken from openzepplin , deployed and woking properly. i am able to do mint , burn ext... 

- when removing the _data from from the delegating call in the constractor (_upgradeToAndCall (_logic, "", false);
) i am also able to deploy but not to perform action in the implementation contract since it is not initialized. 

did someone faced this kind of issue before ? 
doest UUPS upgradeable contract with ERC1967Proxy supported by tron ? If yes, what i am doing wrong in my contracts? 

kindly advise. 

**Proxy contract:** 

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "./contracts/proxy/Proxy.sol";
import "./contracts/proxy/ERC1967/ERC1967Upgrade.sol";
import "./contracts/access/Ownable.sol";

/**
 * @dev This contract implements an upgradeable proxy. It is upgradeable because calls are delegated to an
 * implementation address that can be changed. This address is stored in storage in the location specified by
 * https://eips.ethereum.org/EIPS/eip-1967[EIP1967], so that it doesn't conflict with the storage layout of the
 * implementation behind the proxy.
 */
contract MyProxy is Proxy, ERC1967Upgrade, Ownable {

   constructor(address _logic, bytes memory _data) payable {
        assert(_IMPLEMENTATION_SLOT == bytes32(uint256(keccak256("eip1967.proxy.implementation")) - 1));
        _upgradeToAndCall(_logic, _data, false);
    }

    /**
     * @dev Returns the current implementation address.
     */
    function _implementation() internal view virtual override returns (address impl) {
        return ERC1967Upgrade._getImplementation();
    }
}

**TRC20 contract :** 

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.11;

import "./contracts/token/ERC20/ERC20Upgradeable.sol";
import "./contracts/token/ERC20/extensions/ERC20BurnableUpgradeable.sol";
import "./contracts/security/PausableUpgradeable.sol";
import "./contracts/access/OwnableUpgradeable.sol";
import "./contracts/token/ERC20/extensions/ERC20PermitUpgradeable.sol";
import "./contracts/proxy/utils/Initializable.sol";
import "./contracts/proxy/utils/UUPSUpgradeable.sol";

contract MyToken is Initializable, ERC20Upgradeable, ERC20BurnableUpgradeable, PausableUpgradeable, OwnableUpgradeable, ERC20PermitUpgradeable, UUPSUpgradeable {
    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    function initialize() initializer public {
        __ERC20_init("MyToken", "MyToken");
        __ERC20Burnable_init();
        __Pausable_init();
        __Ownable_init();
        __ERC20Permit_init("MyToken");
        __UUPSUpgradeable_init();
    }

    function pause() public onlyOwner {
        _pause();
    }

    function unpause() public onlyOwner {
        _unpause();
    }

    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }

    function _beforeTokenTransfer(address from, address to, uint256 amount)
        internal
        whenNotPaused
        override
    {
        super._beforeTokenTransfer(from, to, amount);
    }

    function _authorizeUpgrade(address newImplementation)
        internal
        onlyOwner
        override
    {}
}

**Comment by ferdinand026** [comment]
@eitanZcharia1 It is supported. You can get the detailed error information by gettransactioninfobyid API.

**Comment by eitanZcharia1** [comment]
@ferdinand026 any idea what i am doing worng ? 
i am able to deploy those 2 contract over shasta network, but since i didnt call the TRC20 inialize() i was not able to do mint. 

i change the proxy contractor to : 

    constructor() payable Ownable() {
        assert(_IMPLEMENTATION_SLOT == bytes32(uint256(keccak256("eip1967.proxy.implementation")) - 1));
        bytes memory data = abi.encodeWithSignature("initialize()");
        _upgradeToAndCall(addressImp, data, false);
    }
    
    and i got {"ret":[{"contractRet":"OUT_OF_ENERGY"}], but i have a lot of energy ~17M and bandwith 10K.

**Comment by ferdinand026** [comment]
@eitanZcharia1  For OUT_OF_ENERGY, I will suggest to estimate transaction energy consumption according to [this guide](https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-calling-the-contract), then check the feelimit of the transaction and the account's TRX balance and energy, ensure both of them are enough.

**Comment by eitanZcharia1** [comment]
Hi All, 
need your help to understand why a TRC20 upgradeable contract is not deployed successfully on Shasta but I am able to deploy it on local Tron  network. 
generated from open zepplin wizard: 
contract MyToken is Initializable, ERC20Upgradeable, ERC20BurnableUpgradeable, PausableUpgradeable, OwnableUpgradeable, ERC20PermitUpgradeable, UUPSUpgradeable {
this is my deployment script : 
const { deployProxy } = require('@openzeppelin/truffle-upgrades');

const MyToken = artifacts.require('MyToken');

module.exports = async function (deployer) {
  try {
    deployer.trufflePlugin = true;

    const instance = await deployProxy(MyToken, [], { deployer });
    console.info('Deployed', instance.address);


  } catch (error) {
    console.error('Transparent: deploy box error', error);
  }
};
in my local network i am able to deploy it 
 Running migration: 1_initial_migration.js
  Deploying MyToken...
  MyToken:
    (base58) TK6YqXWyeyWiPCpTS5dmV2tp4AwTN4EJu1
    (hex) 41641c9a0cc20cbd7ace5fef0b99b995a7014dd73c
  Deploying ERC1967Proxy...
  ERC1967Proxy:
    (base58) TNWh9KQzzdbqnVLGyFeEWC1x1EABuD8KLK
    (hex) 418995e574e089a334ade978d60af18df5aa4f7a86
Deployed 0x8995e574e089a334ade978d60af18df5aa4f7a86

and from the logs i can see it tooks ~ 4M energy.
[Output] ........"0x5f","contractAddress":"0x641c9a0cc20cbd7ace5fef0b99b995a7014dd73c","cumulativeGasUsed":"0x3a38be","effectiveGasPrice":"0x64","from":"0x6763f22146ab4ea415cf52a2f53c02239f585836","gasUsed":"0x3a38be"

i have 17M energey in my Shasta account but i a getting the following error: 
https://api.shasta.trongrid.io/wallet/gettransactionbyid?value=52156acd8bc088e1dbcbd81c423e87bf5d2e3bd16b255e9b483781ca93dcacf4
If the transaction above is empty, most likely, your address had no bandwidth/energy to deploy the contract.
    at /usr/local/lib/node_modules/tronbox/build/components/TronWrap/index.js:1:8728 (edited)

**Comment by ferdinand026** [comment]
@eitanZcharia1 We can get the execution result "resMessage" from gettransactioninfobyid：https://api.shasta.trongrid.io/wallet/gettransactioninfobyid?value=52156acd8bc088e1dbcbd81c423e87bf5d2e3bd16b255e9b483781ca93dcacf4 . And convert the "resMessage" from hex to string, we can get the message: "Not enough energy for 'save just created contract code' executing: needEnergy[3789600], leftEnergy[3545414];"

* needEnergy is the energy required for the next instruction. 
* leftEnergy is the remaining available energy allowed by the transaction. 3545414*0.00042 = 1489.07388TRX , becasue the  feelimit of the transaction is 1500TRX.

So it reported out of energy error. and to solve this issue, you can set a larger feelimit. for example: 1700TRX.

**Comment by eitanZcharia1** [comment]
@ferdinand026 
this is my shasta network settings : 

shasta: { 
      privateKey: process.env.PRIVATE_KEY_SHASTA,
      userFeePercentage: 100,
      feeLimit: 170 * 1e12,
      originEnergyLimit: 10000000,
      fullHost: 'https://api.shasta.trongrid.io',
      network_id: '2'
    },
      
      i encreased the fee limit as mentioned above and it is still failing , can you please advise what is missing or what needs to 
      be change ?
      also, how did u decoded the error message ?

**Comment by ferdinand026** [comment]
@eitanZcharia1 The feelimit of 170 * 1e12 exceeds the max value of feelimit (15000TRX). For 1700TRX, feelimit can be set to 1700*1e6 .

**Comment by ferdinand026** [comment]
@eitanZcharia1 Try to use this tool to decode the hex message: https://codebeautify.org/hex-string-converter

**Comment by vivian1912** [comment]
@eitanZcharia1  Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
