### ISSUE TITLE
FAILED deploying Token. You lost: 4.90014 TRX Reason: Not enough energy for 'save just created contract code' executing: needEnergy[444200], leftEnergy[410168];

### ISSUE THREAD

**Issue by BeforeLights** [tronprotocol/java-tron#5527]
May i ask what the leftEnergy is ?

**Comment by laurenceja** [comment]
@BeforeLights  When the contract is executed, Energy is calculated and deducted according to instruction one by one. But the upper limit of the energy consumed cannot exceed the value corresponding to feelimit. And the maximum energy allowed by feelimit minus the consumed energy is the leftEnergy.  If the remaining available energy is not enough, it will report error.

**Comment by BeforeLights** [comment]
so does the leftEnergy adds up from failed transactions or do i have to put in the resources consumed + the addtional

**Comment by BeforeLights** [comment]
and i don't even know how it failed. I had 502k energy which is greater than the needed and also covered the Bandwidth needed was 4100 (4.1TRX)

**Comment by BeforeLights** [comment]
@laurenceja

**Comment by laurenceja** [comment]
@BeforeLights Have you already estimated the energy consumption? If yes, you may ensure the feelimit of the transaction is set correctly, and ensure the account has enough energy or TRX. if no, you can refer to this guide for estimating the transaction fee https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-calling-the-contract .

**Comment by ferdinand026** [comment]
> @laurenceja i thought the needEnergy[444200] was the needed energy for the contract

`needEnergy` is only the energy which the next instruction will consume, not the total energy for this transaction. So suggest to estimate energy consumption according to the guide.

**Comment by vivian1912** [comment]
@BeforeLights Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
