### ISSUE TITLE
Address modification in TRON

### ISSUE THREAD

**Issue by Neoblock8** [tronprotocol/java-tron#5531]
Hi,
  Trying to modify address first two letters, For example:
  
  It works, modify first letter
  TCU6EF4oVy4vM1ApmykiXtfCZdU8qgnocE
  ACU6EF4oVy4vM1ApmykiXtfCZdU8qgnocE  
  
  It doesnt works,
  TCU6EF4oVy4vM1ApmykiXtfCZdU8qgnocE
  ABU6EF4oVy4vM1ApmykiXtfCZdU8qgnocE

**Comment by laurenceja** [comment]
@Neoblock8 We should not modify the TRON address manually, that will make the address invalid. TRON's key pair generation algorithm is ECDSA-secp256k1, for details please refer to this [guide](https://developers.tron.network/docs/account). And you can check the correctness of the address by [wallet/validateaddress](https://developers.tron.network/reference/validateaddress) or [isaddress](https://developers.tron.network/reference/isaddress).

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
