### ISSUE TITLE
怎么获取nile测试网的USDT test tokens？

### ISSUE THREAD

**Issue by FerdyCai** [tronprotocol/java-tron#5545]
![image](https://github.com/tronprotocol/java-tron/assets/136073679/a4dfe88e-ffac-4f8d-8d89-af7a951d93e1)

当我从 https://nileex.io/join/getJoinPage 页面中如图的地方获取usdt后，页面提示成功获取，但是查不到余额。查看转账详情 https://nile.tronscan.org/#/transaction/0d79233040e440ae7115705aeb2fb99e9a857fb60d7cf47547b4474ec5a6e180 ，这个貌似不是USDT的转账，并且还提示合约地址是一个有风险的。
正确的nile测试网USDT合约地址应该是 TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf 吧？！
那要怎么获取nile测试网的USDT test tokens呢？

**Comment by laurenceja** [comment]
@FerdyCai I get the test tokens through telegram or discord, it is very convenience, just sending a command will be ok, and we can get all common tokens. Please have a try.

All tokens on nile testnet only use for testing, It cannot be said that a certain token is correct or not, as we also can deploy our own USDT contract on testnet to test the features.

**Comment by FerdyCai** [comment]
@laurenceja 请教一下，如何从telegram 获取usdt测试币呢？

**Comment by laurenceja** [comment]
Type `!help` in [TRON developer group](https://developers.tron.network/docs/online-technical-support), then you will get the command to obtain testcoin.
