### ISSUE TITLE
TVM: Gas consumption for Gtxdatazero vs. Gtxdatanonzero

### ISSUE THREAD

**Issue by DmytroShalaiev** [tronprotocol/java-tron#5546]
Hello, please have a question.

Tron TVM has no difference in Gtxdatazero vs. Gtxdatanonzero ? I'll test it with zero and non-zero byte addresses passed as data in tx for trc20 'transfer'

Screenshot from ethereum yellow paper 
![Снимок экрана 2023-10-19 в 18 23 10](https://github.com/tronprotocol/java-tron/assets/26797262/cc41a7cb-30b8-467e-8a3d-43dcf1788f12)

https://medium.com/coinmonks/on-efficient-ethereum-addresses-3fef0596e263
is it relevant for TRON?

**Comment by laurenceja** [comment]
@DmytroShalaiev I think it is a difference between TVM and EVM. Except energy, TRON has the concept of bandwidth. Energy is for the TVM instruction's execution. Bandwidth is for the byte occupation on-chain for the transaction. So I think in TRON, the bandwidth fee is corresponding to the fees of Gtxdatazero and Gtxdatanonzero. [This](https://developers.tron.network/docs/resource-model#bandwidth) is the introduction to bandwidth.

**Comment by DmytroShalaiev** [comment]
Thanks for reply

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
