### ISSUE TITLE
Decreasing a proposals expiration time on private tron chain

### ISSUE THREAD

**Issue by SukiratWarring** [tronprotocol/java-tron#5549]
Is there a way to decrease the expiration time of a proposal so that i can speed up the development process as i need to approve/disapprove the proposals and their verdict comes at the end of the expiration time.

**Comment by laurenceja** [comment]
@SukiratWarring The expiration time of a proposal is set by node configuration item: `block.proposalExpireTime`, the unit is millisecond.  The mainnet is 259200000L, that is 3 days. If we want to set the expiration time is 10 minutes, we can configure the item to `block.proposalExpireTime=600000`.

**Comment by SukiratWarring** [comment]
@tomatoishealthy @laurenceja  thanks guys!!!
