### ISSUE TITLE
Bad substitution Error when starting network with docker

### ISSUE THREAD

**Issue by TOBEACODER7** [tronprotocol/java-tron#5551]
My local machine is WSL2-Ubuntu22.04 and I had installed docker in my system instead of docker desktop.
When starting network by ```sh docker.sh --run --net private```,there have a error:
```
➜  java-tron-docker sh docker.sh --run --net private
Docker version 24.0.6, build ed223bc
docker.sh: 276: Bad substitution
```
Actually, I don`t know what causes this error. Can anyone help me?

**Comment by TOBEACODER7** [comment]
> The error message is a bit lacking in detail, but refer to this link to see if it helps.
> 
> https://stackoverflow.com/questions/20615217/bash-bad-substitution

Thanks for your help. The answer works for me. Maybe the setting of the shell caused this error!

**Comment by forfreeday** [comment]
This may be caused by the fact that WSL2-Ubuntu22.04 does not support the bash syntax.
You can try changing `{}` to `()` in docker.sh: line 276.

**Comment by TOBEACODER7** [comment]
> This may be caused by the fact that WSL2-Ubuntu22.04 does not support the bash syntax. You can try changing `{}` to `()` in docker.sh: line 276.

Actually, I try to change ```sh docker.sh --run --net private``` to ```zsh docker.sh --run --net private```,then it works. Maybe it can help the person who meets the same problem.
