### ISSUE TITLE
API createaddress throws "Error 405 HTTP method POST is not supported by this URL"

### ISSUE THREAD

**Issue by krkart** [tronprotocol/java-tron#5553]
Hi
I run a fullnode on mainnet. Other http apis work except createaddress. Please help.

`curl --request POST --url http://127.0.0.1:8090/wallet/createaddress --header 'accept: application/json' --data '{"value":"56789"}'
`

Output:
```
{
"servlet":"org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-aca2a0b",
"message":"HTTP method POST is not supported by this URL",
"url":"/wallet/createaddress",
"status":"405"
}
```

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

FullNode version:
https://github.com/tronprotocol/java-tron/releases/download/GreatVoyage-v4.7.2/FullNode.jar

**Comment by ferdinand026** [comment]
@krkart This API is not supported by Java-tron anymore, and any API which related with private key does not supported. You can [create an address offline](https://developers.tron.network/docs/account#ways-to-create-accounts), for example, using wallet-cli or any SDK. You can find the supported APIs [here](https://developers.tron.network/reference/full-node-api-overview).
