### ISSUE TITLE
i have setup a tron private chain, i also deployed a token contract , now i am not able to get the asset transfer from any api

### ISSUE THREAD

**Issue by SukiratWarring** [tronprotocol/java-tron#5558]
### What did i try ?
**I tried the GetTransactionById APi**

->/wallet/gettransactionbyid
-This is the usual response:-
`    "contract": [
      {
        "parameter": {
          "value": {
            "amount": 2000000,
            "owner_address": "TMmYhZ5XyjWwkPSLizzMoqyQLVrwqDdH5Y",
            "to_address": "TEouV6gdGqZvFDde6dDKHBJgbVFV2NW48T"
          },
          "type_url": "type.googleapis.com/protocol.TransferContract"
        },
        "type": "TransferContract"
      }
    ],`
    
- This is what i get !
`    "    "contract": [
      {
        "parameter": {
          "value": {
            "data": "a9059cbb00000000000000000000000065776280f01cdc51d0bc2b5a952a552d1c62bc2f00000000000000000000000000000000000000000000000000000000000186a0",
            "owner_address": "TKYpb1JwBuyecNR2bxYhW96Sg3kATh3DCr",
            "contract_address": "TGfRnUCjEi8S1HJbnheMUL9qR1iDNWeZhX"
          },
          "type_url": "type.googleapis.com/protocol.TriggerSmartContract"
        },
        "type": "TriggerSmartContract"
      }
    ]`
    
i donot get the amount in my transaction

**Comment by ferdinand026** [comment]
@SukiratWarring The TRC20 token transfer amount is at the data field, but is not at the amount field. you can parse the data field to get the transfer amount according to the [guide](https://developers.tron.network/docs/parameter-encoding-and-decoding#parameter-decoding).

**Comment by SukiratWarring** [comment]
Ohk thanks! @ferdinand026
