### ISSUE TITLE
Advance transaction validation when producing blocks

### ISSUE THREAD

**Issue by halibobo1205** [tronprotocol/java-tron#5564]
# Rationale

Why should this feature exist?
Transaction execution requires some resources to be requested, and this process can be time-consuming, so transaction validation should be done in advance to avoid unnecessary waste of resources.

## Current Transaction Validation
Tapos
TooBig
Expiration
ContractSize
Signature
Duplication

## Current Block Production Flow
![image](https://github.com/tronprotocol/java-tron/assets/82020050/eec8f372-9836-44cc-a0ba-4144723b6d4f)

# Implementation

Do you have ideas regarding the implementation of this feature?
 Transactions are validated first and executed after.
## New Block Production Flow
![image](https://github.com/tronprotocol/java-tron/assets/82020050/2bc209ff-d87c-4671-9ae8-f2f4b0b73014)

Are you willing to implement this feature?
Yes

**Comment by halibobo1205** [comment]
> Can you provide more details, such as which code logic should the above verification be advanced to?

@tomatoishealthy  Tapos、TooBig、Expiration 、ContractSize、Signature and Duplication.

**Comment by jwrct** [comment]
I understand that the only difference between the two diagrams you provided is that the "buildsession" is moved after the transaction validation. My question is, can the transaction validation really be placed outside of the session? Will there be any transaction concurrency issues?

**Comment by halibobo1205** [comment]
> I understand that the only difference between the two diagrams you provided is that the "buildsession" is moved after the transaction validation. My question is, can the transaction validation really be placed outside of the session? Will there be any transaction concurrency issues?

`the session` is a new clear session, which is designed to execute each transaction independently,  there are no transaction concurrency issues.

**Comment by forfreeday** [comment]
The second graph removes the catch error && log, if there is a "catch error" during the packaging process, what is the performance loss, and is there a basis for this?

**Comment by halibobo1205** [comment]
> The second graph removes the catch error && log, if there is a "catch error" during the packaging process, what is the performance loss, and is there a basis for this?

About 0.01 ms for catch errors && log

**Comment by lurais** [comment]
As I can see, the difference is the op "throw and catch error " and the op "buildSession", some buildSession ops may be reduced, but are you sure that this op cost much time ?

**Comment by halibobo1205** [comment]
> buildSession

@lurais In fact, buildSession is not the key.

**Comment by halibobo1205** [comment]
catch errors && log（0.02ms） + buildSession(0.01 ms) ：About 0.03 ms

**Comment by lurais** [comment]
> > buildSession
> 
> @lurais In fact, buildSession is not the key.
So,  this change may not make the production process more efficient, do you only mean to adjust the order of the operations in the process of producing blocks?

**Comment by halibobo1205** [comment]
> So, this change may not make the production process more efficient, do you only mean to adjust the order of the operations in the process of producing blocks?

Sorry, catch errors && log（0.02ms） + build session (0.01 ms): about 0.03 ms,  it does have an impact.

**Comment by 317787106** [comment]
@halibobo1205 The difference is throw error and catch error, not catch errors && log. Suppose these two steps of each transaction cost 0.03 ms, and suppose there are 300 transactions in one block, the estimated execute time of one block can reduce 10ms. Can you specify the percent of time cost ?

**Comment by halibobo1205** [comment]
> @halibobo1205 The difference is throw error and catch error, not catch errors && log. Suppose these two steps of each transaction cost 0.03 ms, and suppose there are 300 transactions in one block, the estimated execute time of one block can reduce 10ms. Can you specify the percent of time cost ?

@317787106 , This is only for invalid transactions, such as dup transactions, the block production period is 750 ms, so if there are 20,000 duplicate transactions, 600 ms will be wasted. build session (0.01 ms) + check (Tapos ->TooBig -> Expiration->ContractSize -> Duplication) (0.02 ms).
I was wrong, it's not the catch & log that takes 0.02 ms, it's the invalid check process that causes it. So the point is to optimize the check order, what do you think?
