### ISSUE TITLE
How to calculate the bandwidth consumed by TRON

### ISSUE THREAD

**Issue by wds1181977** [tronprotocol/java-tron#5567]
This raw_data_hex is

**Comment by wds1181977** [comment]
0a02d15522080d9d25c7f5468c3140c8c392efb8315aae01081f12a9010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412740a1541c623389bfef856cad0cf8eb453ed5eb62d17bd1f121541a614f803b6fd780986a42c78ec9c7f77e6ded13c2244a9059cbb0000000000000000000000416d4edc2177cc3350dd8faa78405b692a203d1de000000000000000000000000000000000000000000000000000000000000f424070b4f68eefb831900180b48913

**Comment by wds1181977** [comment]
How to calculate the bandwidth consumed by TRON

**Comment by laurenceja** [comment]
@wds1181977 The amount of bandwidth consumed by a transaction is equal to the number of bytes occupied by the on-chain data, which includes three parts: the raw_data of the transaction, the transaction signature, and the transaction result. There are some examples for estimating bandwidth consumption [here](https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-calling-the-contract).

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.

**Comment by abn2357** [comment]
> @wds1181977 The amount of bandwidth consumed by a transaction is equal to the number of bytes occupied by the on-chain data, which includes three parts: the raw_data of the transaction, the transaction signature, and the transaction result. There are some examples for estimating bandwidth consumption [here](https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-calling-the-contract).

@laurenceja  Why the size of transaction result in both examples  of your referenced doc are all set to a fixed number(64)?
