### ISSUE TITLE
createShieldedContractParameters failed

### ISSUE THREAD

**Issue by codes0003** [tronprotocol/java-tron#5568]
```
{
    "ask": "3jaYchi6Jca+KFCMVtNR31VUH4YVjKkKcNBYj6bHugA=",
    "nsk": "5/BADPppNdaXSXso8fg3cdLd+0w7W+KWEthfJPNfEAE=",
    "ovk": "kG+onsTnibLSQCRN7lsftRiceYZIx6ZgRMtDho4sK9g=",
    "fromAmount": "5000",
    "shieldedReceives": {
        "note": {
            "value": 50,
            "paymentAddress": "ztron1y5uwj0p6rx62t5nzdp779cdqamj5r5dkcla3fnrn6zgj2hdqgavvww3ust4a4g0vuuvq70uhckx",
            "rcm": "zPaKFXOFMvk7NdVYYhQpT/7UF77KWmIQqqFMI2AMmgk="
        }
    },
    "shieldedTrc20ContractAddress": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
}
```

output
```
rpc error: code = Internal desc = BigInteger: modulus not positive
```

**Comment by lurais** [comment]
> ```
> {
>     "ask": "3jaYchi6Jca+KFCMVtNR31VUH4YVjKkKcNBYj6bHugA=",
>     "nsk": "5/BADPppNdaXSXso8fg3cdLd+0w7W+KWEthfJPNfEAE=",
>     "ovk": "kG+onsTnibLSQCRN7lsftRiceYZIx6ZgRMtDho4sK9g=",
>     "fromAmount": "5000",
>     "shieldedReceives": {
>         "note": {
>             "value": 50,
>             "paymentAddress": "ztron1y5uwj0p6rx62t5nzdp779cdqamj5r5dkcla3fnrn6zgj2hdqgavvww3ust4a4g0vuuvq70uhckx",
>             "rcm": "zPaKFXOFMvk7NdVYYhQpT/7UF77KWmIQqqFMI2AMmgk="
>         }
>     },
>     "shieldedTrc20ContractAddress": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
> }
> ```
> 
> output
> 
> ```
> rpc error: code = Internal desc = BigInteger: modulus not positive
> ```

Hello, is there any more detail info about this issue? Such as the complete url you have used (contains the ip/port).

**Comment by 317787106** [comment]
@codes0003 I can give you an example:
```
{
    "ask":"c2513e9e308494932bd82e0ce53662d17421d90b72a8471a0a12b8552a336e02",
    "nsk":"4c6bf3dd4a0643d20b628f7e45980c5e187f07a51d6f3e86aaf1ab916c07eb0d",
    "ovk":"17a58d9a5058da6e42ca12cd289d0a6aa169b926c18e19bca518b8d6f8674e43",
    "from_amount":"100",
    "shielded_receives":[
        {
            "note":{
                "value":100,
                "payment_address":"ztron1y99u6ejqenupvfkp5g6q6yqkp0a44c48cta0dd5gejtqa4v27hqa2cghfvdxnmneh6qqq03fa75",
                "rcm":"16b6f5e40444ab7eeab11ae6613c27f35117971efa87b71560b5813829c9390d"
            }
        }
    ],
    "shielded_TRC20_contract_address":"4144007979359ECAC395BBD3CEF8060D3DF2DC3F01"
}
```
This is hex and not base58, only visible is different.  Please checkout your paramenter, from_amount Not fromAmount, and also.

**Comment by codes0003** [comment]
> @codes0003我可以给你举个例子：
> 
> ```
> {
>     "ask":"c2513e9e308494932bd82e0ce53662d17421d90b72a8471a0a12b8552a336e02",
>     "nsk":"4c6bf3dd4a0643d20b628f7e45980c5e187f07a51d6f3e86aaf1ab916c07eb0d",
>     "ovk":"17a58d9a5058da6e42ca12cd289d0a6aa169b926c18e19bca518b8d6f8674e43",
>     "from_amount":"100",
>     "shielded_receives":[
>         {
>             "note":{
>                 "value":100,
>                 "payment_address":"ztron1y99u6ejqenupvfkp5g6q6yqkp0a44c48cta0dd5gejtqa4v27hqa2cghfvdxnmneh6qqq03fa75",
>                 "rcm":"16b6f5e40444ab7eeab11ae6613c27f35117971efa87b71560b5813829c9390d"
>             }
>         }
>     ],
>     "shielded_TRC20_contract_address":"4144007979359ECAC395BBD3CEF8060D3DF2DC3F01"
> }
> ```
> 
> 这是十六进制而不是base58，只是可见的不同。请检查您的参数，from_amount 不是 fromAmount，以及。

```
type CreateShieldedContractMeta struct {
	OVK              string `json:"ovk"`
	ASK              string `json:"ask"`
	NSK              string `json:"nsk"`
	FromAmount       string `json:"fromAmount"`
	ShieldedReceives struct {
		Note struct {
			Value          int64  `json:"value"`
			PaymentAddress string `json:"paymentAddress"`
			Rcm            string `json:"rcm"`
		} `json:"note"`
	} `json:"shieldedReceives"`
	ShieldedTRC20ContractAddress string `json:"shieldedTrc20ContractAddress"`
}

req := CreateShieldedContractMeta{}
	if e := json.NewDecoder(r.Body).Decode(&req); e != nil {
		return nil, e
	}
	note := &api.Note{
		Value:          req.ShieldedReceives.Note.Value,
		PaymentAddress: req.ShieldedReceives.Note.PaymentAddress,
		Rcm:            internal.DecodeString(req.ShieldedReceives.Note.Rcm),
	}
	shieldedReceives := make([]*api.ReceiveNote, 0)
	shieldedReceives = append(shieldedReceives, &api.ReceiveNote{})
	shieldedReceives[0].Note = note
	trc20, _ := hdwallet.DecodeCheck(req.ShieldedTRC20ContractAddress)
	return &api.PrivateShieldedTRC20Parameters{
		Ask:                           internal.DecodeString(req.ASK),
		Nsk:                           internal.DecodeString(req.NSK),
		Ovk:                           internal.DecodeString(req.OVK),
		FromAmount:                    req.FromAmount,
		ShieldedReceives:              shieldedReceives,
		Shielded_TRC20ContractAddress: trc20,
		ToAmount:                      req.FromAmount,
	}, nil
	
	
<img width="1078" alt="image" src="https://github.com/tronprotocol/java-tron/assets/133564520/997e9dc6-0fac-43e0-b5c8-6f8b3164cf48">

```

**Comment by codes0003** [comment]
> > ```
> > {
> >     "ask": "3jaYchi6Jca+KFCMVtNR31VUH4YVjKkKcNBYj6bHugA=",
> >     "nsk": "5/BADPppNdaXSXso8fg3cdLd+0w7W+KWEthfJPNfEAE=",
> >     "ovk": "kG+onsTnibLSQCRN7lsftRiceYZIx6ZgRMtDho4sK9g=",
> >     "fromAmount": "5000",
> >     "shieldedReceives": {
> >         "note": {
> >             "value": 50,
> >             "paymentAddress": "ztron1y5uwj0p6rx62t5nzdp779cdqamj5r5dkcla3fnrn6zgj2hdqgavvww3ust4a4g0vuuvq70uhckx",
> >             "rcm": "zPaKFXOFMvk7NdVYYhQpT/7UF77KWmIQqqFMI2AMmgk="
> >         }
> >     },
> >     "shieldedTrc20ContractAddress": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 输出
> > ```
> > rpc error: code = Internal desc = BigInteger: modulus not positive
> > ```
> 
> 您好，请问这个问题有更详细的信息吗？比如你使用过的完整url（包含ip/端口）。

<img width="1078" alt="截屏2023-11-03 11 28 29" src="https://github.com/tronprotocol/java-tron/assets/133564520/d1c0bff8-bf8b-4629-8a4b-f2ae8b0de63c">
use.  34.220.77.106:50051

**Comment by Federico2014** [comment]
Please use the correct encodeing, for example:
```
{
   "ovk": "cd361834b3adc06f130de24f7d0c18f92a093cc885d9ce492cc6c02071f7a4f0",
   "from_amount": "5000",
    "shielded_receives": {
       "note": {
          "value": 50,
          "payment_address": "ztron13lvfnt4rau4ad9mmgztd3aftw49e3amz8gm2kvyzrsaw0ugz2grxwkvcfys5e2gkchj7cnnetjz",
          "rcm": "499e73f2f8aaf05fac41a35b8343bde27f6629cbe66d35da5364a99b94a55a06"
       }
    },
    "shielded_TRC20_contract_address": "41f3392eaa7d38749176e0671dbc6912f8ef956943"
}
```
For more details, please refer the doc: https://github.com/tronprotocol/documentation-en/blob/master/docs/mechanism-algorithm/shielded-TRC20-contract.md

**Comment by Federico2014** [comment]
`TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t` is not the shieldedTrc20ContractAddress, this is the shieleded USDT contract address: https://tronscan.org/#/contract/TQEuSEVRk1GtfExm5q9T8a1w84GvgQJ13V

**Comment by codes0003** [comment]
> 请使用正确的编码，例如：
> 
> ```
> {
>    "ovk": "cd361834b3adc06f130de24f7d0c18f92a093cc885d9ce492cc6c02071f7a4f0",
>    "from_amount": "5000",
>     "shielded_receives": {
>        "note": {
>           "value": 50,
>           "payment_address": "ztron13lvfnt4rau4ad9mmgztd3aftw49e3amz8gm2kvyzrsaw0ugz2grxwkvcfys5e2gkchj7cnnetjz",
>           "rcm": "499e73f2f8aaf05fac41a35b8343bde27f6629cbe66d35da5364a99b94a55a06"
>        }
>     },
>     "shielded_TRC20_contract_address": "41f3392eaa7d38749176e0671dbc6912f8ef956943"
> }
> ```
> 
> 有关更多详细信息，请参阅文档：https://github.com/tronprotocol/documentation-en/blob/master/docs/mechanism-algorithm/shielded-TRC20-contract.md

This is the parameter I am submitting now
```json
{
   "ovk": "a2e3bcec9bc13b9f29e4106de416c1553bda095755ca75636cd95a1e67b6f3a5",
   "from_amount": "5000",
    "shielded_receives": {
       "note": {
          "value": 50,
          "payment_address": "ztron1f5wnqchcxw4v7ej72jw4tlc2yuyd0uj2pv4h6ewr6hlwvkgtm7uglyqtpu3gkgz8j28jqy4ys5q",
          "rcm": "fc502bc203e0fbb95bb6b97e97f1d2b997a427ecec2f6ef148cd0e213bfd9e0a"
       }
    },
    "shielded_TRC20_contract_address": "419c89c0c7156dceb5dde2f04252c382b7f80b9015"
}
```

output
```
rpc error: code = Internal desc = invalid shielded TRC-20 parameters
```

**Comment by Federico2014** [comment]
http://34.220.77.106:8090/wallet/createshieldedcontractparameters
```
{
   "ovk": "a2e3bcec9bc13b9f29e4106de416c1553bda095755ca75636cd95a1e67b6f3a5",
   "from_amount": "5000",
    "shielded_receives": {
       "note": {
          "value": 5000,
          "payment_address": "ztron1f5wnqchcxw4v7ej72jw4tlc2yuyd0uj2pv4h6ewr6hlwvkgtm7uglyqtpu3gkgz8j28jqy4ys5q",
          "rcm": "fc502bc203e0fbb95bb6b97e97f1d2b997a427ecec2f6ef148cd0e213bfd9e0a"
       }
    },
    "shielded_TRC20_contract_address": "419c89c0c7156dceb5dde2f04252c382b7f80b9015"
}
```
The response： 
```
{
    "receive_description": [
        {
            "value_commitment": "4bb95a408e387157594f4889ebdbd6cf447edf5219f930d57680709c6b2f66bc",
            "note_commitment": "6452151d3e53af62f12dba9051258db732172f85b6bd765c2b57ccd99f7aee25",
            "epk": "340638626b153b2cc66986ee0eaa8a87082bd5a56139b485e4a0f9007a5db34e",
            "c_enc": "9cd847cd4f02a4224db9e74a810e7f691eb2b04b80ee2dda465c085cfe04dc38132379ba43f06b71916d71eb62018bde97c72c32a6b3cf74925e06f75014a30860fef613762d2f6ee9598280968acce261dc97c2965a268f497a3e9cf6f27270ca44ec90f816c158aa626268387b861646b1b93dac1bbe8a32eb35bd4d354d717cf0558414aae73564e3ba3fddca44536f828799ccd08628c1f9fce542b8776601920bbda9d399f47673c2f9d535f9e135e105d123af89b71b22a8b501383095e53fcc74a40264bb1941a3a95f6a9daf60bea9496a30e37b17dd881aacfff3e1ff421db7eb382aaae49e371de6e5f3ddd331fa1f26a7e75e485f95725e620e537e77ef1a9bfa4e3f32202755f7e0a67ed04681c3a00b067f6e7c0d52503eaf5344ef6f2ae1dbfdae93eba4c5f6c68f5dbca8a814052bb45b510b969567d74267bff50d2539d2f1804f4cea5392fd4d9fc3de2f66afe330f588fdebd9ee7d6916648536a1e19c0e38dd94980ed09c4276457c46ee18f9cfb88fea7226e913fcbfd2b3dee421a8cb32e72d0aa46e18ae21d8c33e87149d1faecdc955170e4b35258a1919ba5336c6c447beb5def10426429a687847cc2e571b089b0947d18384284ce10b57916879e659af1826ed726c0a48aa1f062b5cc6a47143dc223388592823a1b49042606afa35f7be10450f1909a05f00071e8df51bf99ad18ffe2c6675392308ab5b17e0fa80c5cb831b40b4bc19770413a0ecd0e662e08c6b306f657d78306d34b1dd0f2595ea4ee9cb06472112e5d06e1ed655efb2b3e716e34bafde2954c736",
            "c_out": "841864e7b44747e9b640b28de75e384310df7c0c937b67c25ff2c36466ed395334ee83562c75d68793376a5606b64a09ad23895b6415a2dcf5f6920990652f252324bbcb54af36eac4e6289a61a3229b",
            "zkproof": "86d6c48478a0b036d6fcea8f51bf90ee54f9b91e02e92b9ca21c40438a1be282e43413b5cbd8121d13d7d3078751515d97becc5e180e4ee39b1a54ede20db8da8486778258557ff049a296b2cb1c90c4679c3162a46f8e1b17778110e395431b05e51704468c759cb93e3ffa8c8781f678df9795986f8de1a91d34fe5c2680c277b8285a81371785229eab37918cbf428e1979bc71c33ce4a555afe475f9300e51df53d131469d4b315ea391e71d8ee15ada2018dfd0795fbc5ebc17749e34e5"
        }
    ],
    "binding_signature": "30be96808367920268fab601d06e23c9db1d83ff70fe5fcdd676776b36cc0748e8b7791a3a1b994164206bdefe66e8f279805ab39d57083a7c770d752ccb3304",
    "message_hash": "f821f499061d0ea4b977278ca42de5cf59981ea2e86d14460ef6a6bbb583f0dd",
    "trigger_contract_input": "00000000000000000000000000000000000000000000000000000000000013886452151d3e53af62f12dba9051258db732172f85b6bd765c2b57ccd99f7aee254bb95a408e387157594f4889ebdbd6cf447edf5219f930d57680709c6b2f66bc340638626b153b2cc66986ee0eaa8a87082bd5a56139b485e4a0f9007a5db34e86d6c48478a0b036d6fcea8f51bf90ee54f9b91e02e92b9ca21c40438a1be282e43413b5cbd8121d13d7d3078751515d97becc5e180e4ee39b1a54ede20db8da8486778258557ff049a296b2cb1c90c4679c3162a46f8e1b17778110e395431b05e51704468c759cb93e3ffa8c8781f678df9795986f8de1a91d34fe5c2680c277b8285a81371785229eab37918cbf428e1979bc71c33ce4a555afe475f9300e51df53d131469d4b315ea391e71d8ee15ada2018dfd0795fbc5ebc17749e34e530be96808367920268fab601d06e23c9db1d83ff70fe5fcdd676776b36cc0748e8b7791a3a1b994164206bdefe66e8f279805ab39d57083a7c770d752ccb33049cd847cd4f02a4224db9e74a810e7f691eb2b04b80ee2dda465c085cfe04dc38132379ba43f06b71916d71eb62018bde97c72c32a6b3cf74925e06f75014a30860fef613762d2f6ee9598280968acce261dc97c2965a268f497a3e9cf6f27270ca44ec90f816c158aa626268387b861646b1b93dac1bbe8a32eb35bd4d354d717cf0558414aae73564e3ba3fddca44536f828799ccd08628c1f9fce542b8776601920bbda9d399f47673c2f9d535f9e135e105d123af89b71b22a8b501383095e53fcc74a40264bb1941a3a95f6a9daf60bea9496a30e37b17dd881aacfff3e1ff421db7eb382aaae49e371de6e5f3ddd331fa1f26a7e75e485f95725e620e537e77ef1a9bfa4e3f32202755f7e0a67ed04681c3a00b067f6e7c0d52503eaf5344ef6f2ae1dbfdae93eba4c5f6c68f5dbca8a814052bb45b510b969567d74267bff50d2539d2f1804f4cea5392fd4d9fc3de2f66afe330f588fdebd9ee7d6916648536a1e19c0e38dd94980ed09c4276457c46ee18f9cfb88fea7226e913fcbfd2b3dee421a8cb32e72d0aa46e18ae21d8c33e87149d1faecdc955170e4b35258a1919ba5336c6c447beb5def10426429a687847cc2e571b089b0947d18384284ce10b57916879e659af1826ed726c0a48aa1f062b5cc6a47143dc223388592823a1b49042606afa35f7be10450f1909a05f00071e8df51bf99ad18ffe2c6675392308ab5b17e0fa80c5cb831b40b4bc19770413a0ecd0e662e08c6b306f657d78306d34b1dd0f2595ea4ee9cb06472112e5d06e1ed655efb2b3e716e34bafde2954c736841864e7b44747e9b640b28de75e384310df7c0c937b67c25ff2c36466ed395334ee83562c75d68793376a5606b64a09ad23895b6415a2dcf5f6920990652f252324bbcb54af36eac4e6289a61a3229b000000000000000000000000",
    "parameter_type": "mint"
}
```
The scaling factor in [TQEuSEVRk1GtfExm5q9T8a1w84GvgQJ13V](https://tronscan.org/#/contract/TQEuSEVRk1GtfExm5q9T8a1w84GvgQJ13V)  is different from the example.

**Comment by codes0003** [comment]
> http://34.220.77.106:8090/wallet/createshieldedcontractparameters
> 
> ```
> {
>    "ovk": "a2e3bcec9bc13b9f29e4106de416c1553bda095755ca75636cd95a1e67b6f3a5",
>    "from_amount": "5000",
>     "shielded_receives": {
>        "note": {
>           "value": 5000,
>           "payment_address": "ztron1f5wnqchcxw4v7ej72jw4tlc2yuyd0uj2pv4h6ewr6hlwvkgtm7uglyqtpu3gkgz8j28jqy4ys5q",
>           "rcm": "fc502bc203e0fbb95bb6b97e97f1d2b997a427ecec2f6ef148cd0e213bfd9e0a"
>        }
>     },
>     "shielded_TRC20_contract_address": "419c89c0c7156dceb5dde2f04252c382b7f80b9015"
> }
> ```
> 
> The response：
> 
> ```
> {
>     "receive_description": [
>         {
>             "value_commitment": "4bb95a408e387157594f4889ebdbd6cf447edf5219f930d57680709c6b2f66bc",
>             "note_commitment": "6452151d3e53af62f12dba9051258db732172f85b6bd765c2b57ccd99f7aee25",
>             "epk": "340638626b153b2cc66986ee0eaa8a87082bd5a56139b485e4a0f9007a5db34e",
>             "c_enc": "9cd847cd4f02a4224db9e74a810e7f691eb2b04b80ee2dda465c085cfe04dc38132379ba43f06b71916d71eb62018bde97c72c32a6b3cf74925e06f75014a30860fef613762d2f6ee9598280968acce261dc97c2965a268f497a3e9cf6f27270ca44ec90f816c158aa626268387b861646b1b93dac1bbe8a32eb35bd4d354d717cf0558414aae73564e3ba3fddca44536f828799ccd08628c1f9fce542b8776601920bbda9d399f47673c2f9d535f9e135e105d123af89b71b22a8b501383095e53fcc74a40264bb1941a3a95f6a9daf60bea9496a30e37b17dd881aacfff3e1ff421db7eb382aaae49e371de6e5f3ddd331fa1f26a7e75e485f95725e620e537e77ef1a9bfa4e3f32202755f7e0a67ed04681c3a00b067f6e7c0d52503eaf5344ef6f2ae1dbfdae93eba4c5f6c68f5dbca8a814052bb45b510b969567d74267bff50d2539d2f1804f4cea5392fd4d9fc3de2f66afe330f588fdebd9ee7d6916648536a1e19c0e38dd94980ed09c4276457c46ee18f9cfb88fea7226e913fcbfd2b3dee421a8cb32e72d0aa46e18ae21d8c33e87149d1faecdc955170e4b35258a1919ba5336c6c447beb5def10426429a687847cc2e571b089b0947d18384284ce10b57916879e659af1826ed726c0a48aa1f062b5cc6a47143dc223388592823a1b49042606afa35f7be10450f1909a05f00071e8df51bf99ad18ffe2c6675392308ab5b17e0fa80c5cb831b40b4bc19770413a0ecd0e662e08c6b306f657d78306d34b1dd0f2595ea4ee9cb06472112e5d06e1ed655efb2b3e716e34bafde2954c736",
>             "c_out": "841864e7b44747e9b640b28de75e384310df7c0c937b67c25ff2c36466ed395334ee83562c75d68793376a5606b64a09ad23895b6415a2dcf5f6920990652f252324bbcb54af36eac4e6289a61a3229b",
>             "zkproof": "86d6c48478a0b036d6fcea8f51bf90ee54f9b91e02e92b9ca21c40438a1be282e43413b5cbd8121d13d7d3078751515d97becc5e180e4ee39b1a54ede20db8da8486778258557ff049a296b2cb1c90c4679c3162a46f8e1b17778110e395431b05e51704468c759cb93e3ffa8c8781f678df9795986f8de1a91d34fe5c2680c277b8285a81371785229eab37918cbf428e1979bc71c33ce4a555afe475f9300e51df53d131469d4b315ea391e71d8ee15ada2018dfd0795fbc5ebc17749e34e5"
>         }
>     ],
>     "binding_signature": "30be96808367920268fab601d06e23c9db1d83ff70fe5fcdd676776b36cc0748e8b7791a3a1b994164206bdefe66e8f279805ab39d57083a7c770d752ccb3304",
>     "message_hash": "f821f499061d0ea4b977278ca42de5cf59981ea2e86d14460ef6a6bbb583f0dd",
>     "trigger_contract_input": "00000000000000000000000000000000000000000000000000000000000013886452151d3e53af62f12dba9051258db732172f85b6bd765c2b57ccd99f7aee254bb95a408e387157594f4889ebdbd6cf447edf5219f930d57680709c6b2f66bc340638626b153b2cc66986ee0eaa8a87082bd5a56139b485e4a0f9007a5db34e86d6c48478a0b036d6fcea8f51bf90ee54f9b91e02e92b9ca21c40438a1be282e43413b5cbd8121d13d7d3078751515d97becc5e180e4ee39b1a54ede20db8da8486778258557ff049a296b2cb1c90c4679c3162a46f8e1b17778110e395431b05e51704468c759cb93e3ffa8c8781f678df9795986f8de1a91d34fe5c2680c277b8285a81371785229eab37918cbf428e1979bc71c33ce4a555afe475f9300e51df53d131469d4b315ea391e71d8ee15ada2018dfd0795fbc5ebc17749e34e530be96808367920268fab601d06e23c9db1d83ff70fe5fcdd676776b36cc0748e8b7791a3a1b994164206bdefe66e8f279805ab39d57083a7c770d752ccb33049cd847cd4f02a4224db9e74a810e7f691eb2b04b80ee2dda465c085cfe04dc38132379ba43f06b71916d71eb62018bde97c72c32a6b3cf74925e06f75014a30860fef613762d2f6ee9598280968acce261dc97c2965a268f497a3e9cf6f27270ca44ec90f816c158aa626268387b861646b1b93dac1bbe8a32eb35bd4d354d717cf0558414aae73564e3ba3fddca44536f828799ccd08628c1f9fce542b8776601920bbda9d399f47673c2f9d535f9e135e105d123af89b71b22a8b501383095e53fcc74a40264bb1941a3a95f6a9daf60bea9496a30e37b17dd881aacfff3e1ff421db7eb382aaae49e371de6e5f3ddd331fa1f26a7e75e485f95725e620e537e77ef1a9bfa4e3f32202755f7e0a67ed04681c3a00b067f6e7c0d52503eaf5344ef6f2ae1dbfdae93eba4c5f6c68f5dbca8a814052bb45b510b969567d74267bff50d2539d2f1804f4cea5392fd4d9fc3de2f66afe330f588fdebd9ee7d6916648536a1e19c0e38dd94980ed09c4276457c46ee18f9cfb88fea7226e913fcbfd2b3dee421a8cb32e72d0aa46e18ae21d8c33e87149d1faecdc955170e4b35258a1919ba5336c6c447beb5def10426429a687847cc2e571b089b0947d18384284ce10b57916879e659af1826ed726c0a48aa1f062b5cc6a47143dc223388592823a1b49042606afa35f7be10450f1909a05f00071e8df51bf99ad18ffe2c6675392308ab5b17e0fa80c5cb831b40b4bc19770413a0ecd0e662e08c6b306f657d78306d34b1dd0f2595ea4ee9cb06472112e5d06e1ed655efb2b3e716e34bafde2954c736841864e7b44747e9b640b28de75e384310df7c0c937b67c25ff2c36466ed395334ee83562c75d68793376a5606b64a09ad23895b6415a2dcf5f6920990652f252324bbcb54af36eac4e6289a61a3229b000000000000000000000000",
>     "parameter_type": "mint"
> }
> ```
> 
> The scaling factor in [TQEuSEVRk1GtfExm5q9T8a1w84GvgQJ13V](https://tronscan.org/#/contract/TQEuSEVRk1GtfExm5q9T8a1w84GvgQJ13V) is `1` instead of `100` from the example.

thank
