### ISSUE TITLE
Upgrade cache library Guava to Caffeine

### ISSUE THREAD

**Issue by CarlChaoCarl** [tronprotocol/java-tron#5569]
# Rationale
Caffeine is the result of improved design based on the experience of Google Guava Cache. It offers greater efficiency in terms of performance and hit rates compared to Guava, can be considered a Guava Plus.

Currently, I am exploring migrating the local cache from Guava to Caffeine. Actual comparison data will be given later, and then whether the next Java-tron version would include, this upgrade will be considered. The following sections will provide the migration strategy and performance comparison before and after the migration.

# Background
Currently, Java-tron uses Guava for its local caching.

Based on some technical research, Caffeine is a high-performance, near-optimal caching library.

- High performance.  Please refer to the benchmark. For details, please see: [Benchmarks](https://github.com/ben-manes/caffeine/wiki/Benchmarks) 

- High efficiency.  Caffeine uses the Window TinyLfu policy due to its high hit rate and low memory footprint. For details, please see: [Efficiency](https://github.com/ben-manes/caffeine/wiki/Efficiency) 

The successor to the Guava cache API is Caffeine. In order to enhance the performance of the Java-Tron system, the local cache should be upgraded to Caffeine.

# Implementation
The implementation is simple, with the following steps,
- Proposal Control: A new proposal will be introduced to control the activation of Caffeine. Guava is used as the local cache before the proposal takes effect, and once the proposal is active, Caffeine is used as the local cache.

-  Adding the Caffeine library to Gradle.
`implementation group: 'com.github.ben-manes.caffeine', name: 'caffeine', version: '3.0.6'
`

- Caffeine provides an adapter to expose its cache through Guava's interfaces. These adapters offer the same API with the following considerations:

  - Change CacheBuilder.newBuilder() to Caffeine.newBuilder().

  -  Guava's get() method throws an ExecutionException. After switching to Caffeine, the get() method no longer throws an exception, allowing it to return null.

   - Guava's getUnchecked() method does not require us to explicitly catch exceptions, but it throws an UncheckedExecutionException. After switching to Caffeine, the getUnchecked() method is no longer available, so make sure to handle null checks accordingly.

- Before and after migration, correctness testing is necessary to ensure logical accuracy.

- The performance comparison testing before and after migration will be provided later.

**Comment by lxcmyf** [comment]
Attaching some official or third-party performance comparison charts for two different caching schemes would be more intuitive. What interests me more is how much this improvement can improve TRON's overall TPS for transactions? I think it may be necessary to prove the actual performance improvement through actual pressure test data.

**Comment by lurais** [comment]
As an open source project, it would be great to define interfaces for easier integration of other cache libraries in the future.

**Comment by forfreeday** [comment]
Availability of benchmark comparison data for Caffeine?

**Comment by CarlChaoCarl** [comment]
@forfreeday 

Here is benchmark comparison data for Caffeine and Guava.
https://github.com/ben-manes/caffeine/wiki/Benchmarks

**Comment by jwrct** [comment]
I believe that modifications that do not involve protocols should not be controlled by proposals to determine their effectiveness, because such modifications only affect the node itself and do not require consensus on whether the modifications should take effect. I suggest that there is no need for control, or if you are concerned about potential issues, control can be achieved through configuration. Do you think my understanding is correct?

**Comment by CarlChaoCarl** [comment]
@jwrct 

Thank you for your advice
