### ISSUE TITLE
Json-Rpc calls not working on tron private chain

### ISSUE THREAD

**Issue by SukiratWarring** [tronprotocol/java-tron#5572]
i added this object in the SR as well as Fullnode config.
`node.jsonrpc {
httpFullNodeEnable = true
httpFullNodePort = 50545
httpSolidityEnable = true
httpSolidityPort = 50555
}`

do i have to make any other change?

**Comment by laurenceja** [comment]
@SukiratWarring That's all for enabling json-rpc API service.  After the configuration, restarting the node, then accessing the endpoint: http://ip:50545/jsonrpc to request json-rpc API.

**Comment by SukiratWarring** [comment]
thats exaclty what i am doing but i am not able to get any response,i get this timeout result 
curl: (28) Failed to connect to <IP> port 50545 after 130227 ms: Connection timed out

**Comment by 317787106** [comment]
@SukiratWarring Please check if `telnet <ip> 50545` works at first. Looking at the logs/tron.log, does the jsonrpc service start successfully?

**Comment by SukiratWarring** [comment]
@317787106 
telnet <ip> 50545 is not connecting,how to resolve it?

**Comment by 317787106** [comment]
@SukiratWarring Can you paste your log when node starts? the file is logs/tron.log, 
begin like this "13:28:14.289 INFO  [main] [app](FullNode.java:53) Full node running.", 
end like this    "13:28:29.165 INFO  [main] [app](ServiceContainer.java:58) All api services started."

**Comment by SukiratWarring** [comment]
@317787106 
the port was not whitelisted on my firewall, thanks for the reply tho!
