### ISSUE TITLE
Gettransactioninfobynum is returning empty

### ISSUE THREAD

**Issue by bmalepaty** [tronprotocol/java-tron#5574]
![image](https://github.com/tronprotocol/java-tron/assets/77955726/19a6b3a3-d72f-421c-b088-3dea97aaf8bb)
10.213.73.71:6332/wallet/gettransactioninfobyblocknum

This is the docker-compose.yml used to setup the node
version: "3.7"
services:
  node:
    image: tronprotocol/java-tron:latest
    restart: on-failure
    ports:
      - "6332:8090"
      - "18888:18888"
      - "50051:50051"
    volumes:
      - /NewDisk71Machine/tron-fullnode/output-directory:/java-tron/output-directory
      - /NewDisk71Machine/tron-fullnode/logs:/java-tron/logs
    container_name: tron_fullnode

**Comment by forfreeday** [comment]
@bmalepaty 
Have your database blocks been synchronized to this height?
You can check the current database height with this command:
```
curl -X POST 10.213.73.71:6332/walletsolidity/getnowblock
```

**Comment by vivian1912** [comment]
@bmalepaty Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
