### ISSUE TITLE
illegal operation while deploying token contract

### ISSUE THREAD

**Issue by Neoblock8** [tronprotocol/java-tron#5576]
Hi,
  Running private node and trying to deploy a trc20 token contract, cant able to deploy the contract it results **Illegal Operation**
  
  Config in supernode:
  
  committee = {
  allowCreationOfContracts = 1  //mainnet:0 (reset by committee),test:1
  allowMultiSign = 1
  allowSameTokenName = 1
  allowTvmTransferTrc10 = 1
  allowTvmConstantinople = 1
  allowTvmSolidity059 = 1
  allowMarketTransaction = 1
  allowDelegatedResource = 1
  changedDelegation = 1
}

Can i add any other proposals?

**Comment by yanghang8612** [comment]
allowTvmShangHai = 1

**Comment by vivian1912** [comment]
@Neoblock8 Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks.
