### ISSUE TITLE
multi-signature

### ISSUE THREAD

**Issue by codes0003** [tronprotocol/java-tron#5577]
I want to use A's private key to control B's address to call DelegateResource，
I don't know how to structure this transaction

```
params, err := anypb.New(&core.DelegateResourceContract{
		OwnerAddress:    PublicKeyToAddress(privateKey.PublicKey),
		ReceiverAddress: r,
		Resource:        core.ResourceCode_ENERGY,
		Balance:         3200000000,
		Lock:            false,
		LockPeriod:      50,
	})
	if err != nil {
		return
	}
	multiSigTransaction := &core.Transaction{
		RawData: &core.TransactionRaw{
			Contract: []*core.Transaction_Contract{{
				Type:         core.Transaction_Contract_DelegateResourceContract,
				Parameter:    params,
				PermissionId: 2,
			}},
			
			RefBlockBytes: now.Blockid,
		},
	}
	tx, err := SignTransaction(multiSigTransaction, privateKey)
	if err != nil {
		fmt.Println(err)
	}
	re, err := c.WalletClient.BroadcastTransaction(ctx, multiSigTransaction)
	if err != nil {
		fmt.Println(err)
	}

func SignTransactions(transaction *core.Transaction, privateKey *ecdsa.PrivateKey) (*core.Transaction, error) {
	transaction.GetRawData().Timestamp = time.Now().UnixNano() / 1000000
	rawData, err := proto.Marshal(transaction.GetRawData())
	if err != nil {
		return nil, err
	}
	h256h := sha256.New()
	h256h.Write(rawData)
	hash := h256h.Sum(nil)
	contractList := transaction.GetRawData().GetContract()
	for range contractList {
		signature, err := crypto.Sign(hash, privateKey)
		if err != nil {
			return nil, err
		}
		transaction.Signature = append(transaction.Signature, signature)
	}
	return transaction, nil
}
```
output
```
Transaction broadcasted: code:TAPOS_ERROR message:"Tapos check error."
```

**Comment by ferdinand026** [comment]
@codes0003 TAPOS check error is the reference block set incorrectly. [Here](https://github.com/fbsobreira/gotron-sdk/blob/master/pkg/client/account_test.go#L83 ) is the test code of delegating resources for your reference. 

You want to use A's private key to control B's address to call DelegateResource，so A should have the DelegateResource permission of B first(we can get the account permission information of B in Tronscan), then A can trigger a transaction to delegate resources of B to others.

**Comment by codes0003** [comment]
> @codes0003TAPOS检查错误是参考块设置不正确。[下面](https://github.com/fbsobreira/gotron-sdk/blob/master/pkg/client/account_test.go#L83)是委托资源的测试代码，供大家参考。
> 
> 你想用A的私钥控制B的地址来调用DelegateResource，所以A应该先拥有B的DelegateResource权限（我们可以在Tronscan中获取B的账户权限信息），然后A才能触发交易来委托B的资源给其他人。

I'm sure I have permission,but return Tapos check error

**Comment by ferdinand026** [comment]
@codes0003 So you may try to modify the code according to the example as test case. For example, modify or remove the the code:`RefBlockBytes: now.Blockid,`.

**Comment by codes0003** [comment]
> @codes0003所以你可以尝试根据示例作为测试用例修改代码。例如，修改或删除代码：`RefBlockBytes: now.Blockid,`。

The sample code does not contain multi-signing. My DelegateResource can work normally. I encountered a multi-signing problem.

**Comment by ferdinand026** [comment]
@codes0003 But this error is irrelevant with signature, it is the reference block setting issue, so my suggestion is to modify or remove the the code: RefBlockBytes: now.Blockid,

**Comment by codes0003** [comment]
> @codes0003但这个错误与签名无关，是引用块设置问题，所以我的建议是修改或删除代码：RefBlockBytes: now.Blockid，

After deletion, the return is still Tapos check error

**Comment by halibobo1205** [comment]
@codes0003  How to set `RefBlockHash` and `RefBlockBytes`, you can refer to the following code:

``` java
  public void setReference(long blockNum, byte[] blockHash) {
    byte[] refBlockNum = ByteArray.fromLong(blockNum);
    Transaction.raw rawData = this.transaction.getRawData().toBuilder()
        .setRefBlockHash(ByteString.copyFrom(ByteArray.subArray(blockHash, 8, 16)))
        .setRefBlockBytes(ByteString.copyFrom(ByteArray.subArray(refBlockNum, 6, 8)))
        .build();
    setRawData(rawData);
  }
```

**Comment by halibobo1205** [comment]
@codes0003 Closing for now but please continue the discussion thread if you are looking for more help.
