### ISSUE TITLE
Delete network config item - node.discovery.bind.ip

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/java-tron#5579]
# Rationale

In the configuration file ```config.conf```, you can configure the local IP address through configuration items, including LAN IP and WAN IP. The main role of IP is to be used in the node discovery phase to construct UDP messages that are sent to peers. Generally, the LAN address is configured through node.discovery.bind.ip, and the WAN address is configured through node.discovery.external.ip.

Setting the IP of P2pConfig in java-tron is divided into as following priorities:

1.  The external network IP / WAN IP obtained from the query URL through the libp2p module;
2.  The value obtained by reading the configuration item node.discovery.external.ip;
3.  The value obtained by reading the configuration item node.bind.bind.ip;

This IP is used to fill in the address or addressIpv6 field of the Endpoint from in the following 5 messages:

1.  HelloMessage
2.  PingMessage
3.  PongMessage
4.  FindNeighbors
5.  Neighbors

For Ethernet networking (main chain), an external network connection must be ensured, so that priority 1 is met. For local area networking (private chain), assume that it cannot obtain the external network IP. During the actual connection, the node obtains peer's IP through the data packet socket , and then encapsulates the IP into a ```Node``` and adds it to the peer's k bucket. 

See the method org.tron.p2p.discover.socket.P2pPacketDecoder#decode:
```
@Override
public void decode(ChannelHandlerContext ctx, DatagramPacket packet, List<Object> out)
    throws Exception {
  ByteBuf buf = packet.content();
  int length = buf.readableBytes();
  ...
  byte[] encoded = new byte[length];
  buf.readBytes(encoded);
  try {
    UdpEvent event = new UdpEvent(Message.parse(encoded), packet.sender());
    out.add(event);
  } catch (P2pException pe) {
    ...
  }
}
```
Local node doesn’t get peer’s ip from above messages. Therefore, it is actually not necessary to configure the LAN IP.

# Implementation

Delete the configuration item node.discovery.bind.ip in the configuration file to reduce redundant items. For nodes without ethernet access, the local ip is 127.0.0.1.

**Comment by ss3344520** [comment]
Regardless of LAN or Internet, it is recommended to obtain IP automatically rather than configure it.

**Comment by CarlChaoCarl** [comment]
Good idea. This reduces configuration and makes the code logic clearer.

**Comment by forfreeday** [comment]
Redundant configurations can be removed if they don't affect functionality, has the network been tested with the configurations removed?

**Comment by 317787106** [comment]
> Redundant configurations can be removed if they don't affect functionality, has the network been tested with the configurations removed?

@forfreeday Not yet. We may test it later.

**Comment by lurais** [comment]
Actually， is this configuration item node.discovery.external.ip used as a backup way when the query URL is banned?

**Comment by jwrct** [comment]
By looking at the code, it is found that the configuration "node.discovery.bind.ip" is used in scenarios such as when obtaining the external IP fails and no external IP is configured. Have you considered migrating the logic of "bind.ip" to libp2p?

**Comment by 317787106** [comment]
> Actually， is this configuration item node.discovery.external.ip used as a backup way when the query URL is banned?

@lurais Yes, you are right

**Comment by 317787106** [comment]
> By looking at the code, it is found that the configuration "node.discovery.bind.ip" is used in scenarios such as when obtaining the external IP fails and no external IP is configured. Have you considered migrating the logic of "bind.ip" to libp2p?

@jwrct You can set the ip of libp2p outside that package. Even though bind ip is not configured, other peer can get your ip through data packet. It's useless.
