### ISSUE TITLE
I would like to receive the block database of nile testnet...

### ISSUE THREAD

**Issue by junghyun0783** [tronprotocol/java-tron#5591]
I would like to receive the block database of nile testnet........please help me..
Is it currently impossible to download the Nile Testnet database snapshot?
http://47.90.243.177
It says on the official website that you can download it here...
I can't connect.
Or should I get it from somewhere other than here?

**Comment by forfreeday** [comment]
@junghyun0783 
You can download it from this node: https://database.nileex.io/

**Comment by junghyun0783** [comment]
@forfreeday 
Thank you so much.
Thanks to you, I think I can solve it!
It's downloading.
Thank you again.
