### ISSUE TITLE
How do I change the symbol and full name of the base coin(TRX) in the private chain I set up?

### ISSUE THREAD

**Issue by heelearn** [tronprotocol/java-tron#5598]
Is it modified in the java-tron source code or do I need to publish a smart contract myself?

**Comment by ss3344520** [comment]
@heelearn  The symbol can be set through this variable `TRX_SYMBOL_BYTES`, the base coin name is defined by yourself and is not set on the chain.  Can you see the base coin name in your private chain?  Where did you see it?

**Comment by heelearn** [comment]
### First, let me respond individually to your answer and my question.

Following your reminder, I found the code in the following file, but at the same time, I am puzzled about it. Isn't the TRON base coin symbol supposed to be "TRX"? Why is it "_" here? 

[common/src/main/java/org/tron/core/config/Parameter.java](https://github.com/tronprotocol/java-tron/blob/be07f5c91899cee0bfde517ac3a5e5f73c6fc957/common/src/main/java/org/tron/core/config/Parameter.java#L53)
```
public static class ChainSymbol {
    public static final byte[] TRX_SYMBOL_BYTES = "_".getBytes(); // TRX symbol
}
```
### Next, let me discuss a few confusions I am currently encountering.

I have successfully deployed two nodes on a server, one is a SuperNode (SR) , and the other is a FullNode. What I can confirm is:

**The SR is producing blocks normally, and the FullNode is synchronizing the SR blocks through the internal network.**

I modified the config.conf based on [private_net_config.conf](https://github.com/tronprotocol/tron-deployment/blob/master/private_net_config.conf), following the standards set out in the [developers documentation](https://developers.tron.network/docs/tron-private-chain).

1. Please note, the only thing I did not do according to the document is **7. Modify the dynamic parameters of the private chain**, because I don't know why I need to synchronize with the main network environment. My need is to be completely independent of the TRON mainnet, so will there be any problems if I don't do this step?

2. I am a bit confused because the TRON developer documentation has caused some conceptual confusion for me. **What I want to know is what exactly is the difference between the TRON network and a TRON node?** I am not ignorant of the difference between the two, but various wallet applications (TokenPocket, imToken, TronLink, and MetaMask) have completely confused me. I will elaborate on my confusion in points 3, 4, and 5.

3. In the TronLink settings, under network settings, switching networks, there are only public networks (TRON mainnet, Shasta, and Nile), and other private networks cannot be added. In switching nodes, it is possible to add deployed nodes. My question is, since my deployed private chain node is not synchronized with the mainnet, it seems pointless to add the node. So when I add my own node, the number of TRX coins under my address should be different from the mainnet, but why are they the same of result?

4. Interestingly, in the TokenPocket wallet, after selecting the TRON network, I can add the httpFullNode address of my deployed FullNode as a custom node. Although the TokenPocket connection test fails, all functions are normal, including transfer, receiving, and the coin balance on the address.

5. Additionally, I found that, apart from the TokenPocket wallet, other wallets seem not to support customization of the TRON network. I know TRON supports Ethereum network's jsonrpc. In many wallet applications, when adding a network, select "Ethereum series", fill in the jsonrpc httpFullNode address of the FullNode, and after obtaining the chainid through the [document tutorial](https://developers.tron.network/reference/eth_chainid), it is possible to normally add an EVM network. But does this added network still belong to TRON?

### These are some of my confusions. Finally, let me summarize my questions.

**My core need is: To completely detach from the TRON mainnet and build my own TRON.**

1. My two deployed nodes are interacting normally with each other. What else do I need to do to achieve my core need?

2. Why, in the TronLink Google Chrome plugin, after adding the httpFullNode address of the deployed FullNode as a custom node, is the bandwidth of the same address different from the mainnet, but the coin balance is the same as the mainnet?

**Comment by heelearn** [comment]
**Attached is the content of the config.conf configuration file of my two nodes.**
**Please note that both nodes are deployed on the same server.**

### SuperNode (SR) config.conf

```
net {
  type = mainnet
}

storage {
  db.version = 2,
  db.engine = "LEVELDB",
  db.directory = "database",
  index.directory = "index",
  properties = []
}

node.discovery = {
  enable = true 
  persist = true
  bind.ip = ""
  external.ip = 127.0.0.1
}

node.backup {
  port = 10001
  priority = 8
  members = [
  ]
}

node {
  trustNode = "127.0.0.1:50051"

  walletExtensionApi = true

  listen.port = 16666

  connection.timeout = 2

  tcpNettyWorkThreadNum = 0

  udpNettyWorkThreadNum = 1

  maxActiveNodes = 30

  maxActiveNodesWithSameIp = 2

  minParticipationRate = 0

  disconnectNumberFactor = 0.4
  maxConnectNumberFactor = 0.8
  receiveTcpMinDataLength = 2048
  isOpenFullTcpDisconnect = true

  p2p {
    version = 20231124
  }

  active = [
  ]

  passive = [
  ]

  http {
    fullNodePort = 16667
    solidityPort = 16668
  }

  rpc {
    port = 16669
    
    maxConnectionIdleInMillis = 60000
    
    minEffectiveConnection = 0
  }

  dns {
    treeUrls = [
      #"tree://APFGGTFOBVE2ZNAB3CSMNNX6RRK3ODIRLP2AA5U4YFAA6MSYZUYTQ@nodes1.example.org",
    ]
  }
}



seed.node = {
  ip.list = [
  ]
}

genesis.block = {
  assets = [
    {
      accountName = "Zion"
      accountType = "AssetIssue"
      address = "TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY"
      balance = "95000000000000000"
    },
    {
      accountName = "Sun"
      accountType = "AssetIssue"
      address = "TWsm8HtU2A5eEzoT8ev8yaoFjHsXLLrckb"
      balance = "5000000000000000"
    },
    {
      accountName = "Blackhole"
      accountType = "AssetIssue"
      address = "TSJD5rdu6wZXP7F2m3a3tn8Co3JcMjtBip"
      balance = "-9223372036854775808"
    },
    {
      accountName = "Test"
      accountType = "AssetIssue"
      address = "TGSJ8DE4XVm58*******"
      balance = "1000000000000000"
    }
  ]

  witnesses = [
    {
      address: T9yd98bcDK6*******,
      url = "http://tronstudio.com",
      voteCount = 10000
    }
  ]

  timestamp = "0"

  parentHash = "957dc2d350daecc7bb6a38f3938ebde0a0c1cedafe15f0edae4256a2907449f6"
}

localwitness = [
  9efa9bfad09f1fbb7b42**********
]

block = {
  needSyncCheck = false # first node : false, other : true
  proposalExpireTime = 600000
  maintenanceTimeInterval = 300000 // 1 day: 86400000(ms), 6 hours: 21600000(ms)
}

vm = {
  supportConstant = true
  minTimeRatio = 0.0
  maxTimeRatio = 5.0
}

committee = {
  allowCreationOfContracts = 1
  allowSameTokenName = 1
  allowTvmTransferTrc10 = 1
}

event.subscribe = {
  native = {
    useNativeQueue = true
    bindport = 5555 // bind port
    sendqueuelength = 1000
  }

  path = ""
  server = ""
  dbconfig = ""
  contractParse = true,
  topics = [
    {
      triggerName = "block"
      enable = false
      topic = "block" 
    },
    {
      triggerName = "transaction"
      enable = false
      topic = "transaction"
    },
    {
      triggerName = "contractevent"
      enable = false
      topic = "contractevent"
    },
    {
      triggerName = "contractlog"
      enable = false
      topic = "contractlog"
    },
    {
      triggerName = "solidity"
      enable = true            
      topic = "solidity"
    }
  ]

  filter = {
    fromblock = ""
    toblock = "" 
    contractAddress = [
      ""
    ]

    contractTopic = [
      ""
    ]
  }
}

```

### FullNode config.conf

```
net {
  type = mainnet
}

storage {
  db.version = 2,
  db.engine = "LEVELDB",
  db.directory = "database",
  index.directory = "index",
  properties = []
}

node.discovery = {
  enable = true  
  persist = true  
  bind.ip = ""
  external.ip = 127.0.0.1
}

node.backup {
  port = 10001
  priority = 8
  members = [
  ]
}

node {
  trustNode = "127.0.0.1:50051"

  walletExtensionApi = true

  listen.port = 15555

  connection.timeout = 2

  tcpNettyWorkThreadNum = 0

  udpNettyWorkThreadNum = 1

  maxActiveNodes = 30

  maxActiveNodesWithSameIp = 2

  minParticipationRate = 0

  disconnectNumberFactor = 0.4
  maxConnectNumberFactor = 0.8
  receiveTcpMinDataLength = 2048
  isOpenFullTcpDisconnect = true

  p2p {
    version = 20231124
  }

  active = [
    "127.0.0.1:16666"
  ]

  passive = [
  ]

  http {
    fullNodePort = 15557
    solidityPort = 15558
  }

  rpc {
    port = 15559
    
    maxConnectionIdleInMillis = 60000
    
    minEffectiveConnection = 0
  }

  dns {
    treeUrls = [
      #"tree://APFGGTFOBVE2ZNAB3CSMNNX6RRK3ODIRLP2AA5U4YFAA6MSYZUYTQ@nodes1.example.org",
    ]
  }
  
  jsonrpc {
    httpFullNodeEnable = true
    httpFullNodePort = 8545
    httpSolidityEnable = true
    httpSolidityPort = 8555
    httpPBFTEnable = true
    httpPBFTPort = 8565
  }
  
}

seed.node = {
  ip.list = [
    "127.0.0.1:16666"
  ]
}

genesis.block = {
  assets = [
    {
      accountName = "Zion"
      accountType = "AssetIssue"
      address = "TPL66VK2gCXNCD7EJg9pgJRfqcRazjhUZY"
      balance = "95000000000000000"
    },
    {
      accountName = "Sun"
      accountType = "AssetIssue"
      address = "TWsm8HtU2A5eEzoT8ev8yaoFjHsXLLrckb"
      balance = "5000000000000000"
    },
    {
      accountName = "Blackhole"
      accountType = "AssetIssue"
      address = "TSJD5rdu6wZXP7F2m3a3tn8Co3JcMjtBip"
      balance = "-9223372036854775808"
    },
    {
      accountName = "Test"
      accountType = "AssetIssue"
      address = "TGSJ8DE4XVm58*******"
      balance = "1000000000000000"
    }
  ]

  witnesses = [
    {
      address: T9yd98bcDK6*******,
      url = "http://tronstudio.com",
      voteCount = 10000
    }
  ]

  timestamp = "0"

  parentHash = "957dc2d350daecc7bb6a38f3938ebde0a0c1cedafe15f0edae4256a2907449f6"
}

localwitness = [
]

block = {
  needSyncCheck = true
  proposalExpireTime = 600000
  maintenanceTimeInterval = 300000
}


vm = {
  supportConstant = true
  minTimeRatio = 0.0
  maxTimeRatio = 5.0
}

committee = {
  allowCreationOfContracts = 1
  allowSameTokenName = 1
  allowTvmTransferTrc10 = 1
}

event.subscribe = {
  native = {
    useNativeQueue = true
    bindport = 5555 // bind port
    sendqueuelength = 1000
  }

  path = ""
  server = ""
  dbconfig = ""
  contractParse = true,
  topics = [
    {
      triggerName = "block"
      enable = false
      topic = "block" 
    },
    {
      triggerName = "transaction"
      enable = false
      topic = "transaction"
    },
    {
      triggerName = "contractevent"
      enable = false
      topic = "contractevent"
    },
    {
      triggerName = "contractlog"
      enable = false
      topic = "contractlog"
    },
    {
      triggerName = "solidity"
      enable = true            
      topic = "solidity"
    }
  ]

  filter = {
    fromblock = ""
    toblock = "" 
    contractAddress = [
      ""
    ]

    contractTopic = [
      ""
    ]
  }
}
```

**Comment by ss3344520** [comment]
@heelearn The network you have deployed is your own TRON, and it is completely separated from the TRON main network.

**Comment by heelearn** [comment]
@ss3344520 Why, in the TronLink Google Chrome plugin, after adding the httpFullNode address of the deployed FullNode as a custom node, is the bandwidth of the same address different from the mainnet, but the coin balance is the same as the mainnet?

**Comment by ferdinand026** [comment]
> ### First, let me respond individually to your answer and my question.
> Following your reminder, I found the code in the following file, but at the same time, I am puzzled about it. Isn't the TRON base coin symbol supposed to be "TRX"? Why is it "_" here?
> 
> [common/src/main/java/org/tron/core/config/Parameter.java](https://github.com/tronprotocol/java-tron/blob/be07f5c91899cee0bfde517ac3a5e5f73c6fc957/common/src/main/java/org/tron/core/config/Parameter.java#L53)
> 
> ```
> public static class ChainSymbol {
>     public static final byte[] TRX_SYMBOL_BYTES = "_".getBytes(); // TRX symbol
> }
> ```
> 
> ### Next, let me discuss a few confusions I am currently encountering.
> I have successfully deployed two nodes on a server, one is a SuperNode (SR) , and the other is a FullNode. What I can confirm is:
> 
> **The SR is producing blocks normally, and the FullNode is synchronizing the SR blocks through the internal network.**
> 
> I modified the config.conf based on [private_net_config.conf](https://github.com/tronprotocol/tron-deployment/blob/master/private_net_config.conf), following the standards set out in the [developers documentation](https://developers.tron.network/docs/tron-private-chain).
> 
> 1. Please note, the only thing I did not do according to the document is **7. Modify the dynamic parameters of the private chain**, because I don't know why I need to synchronize with the main network environment. My need is to be completely independent of the TRON mainnet, so will there be any problems if I don't do this step?
> 2. I am a bit confused because the TRON developer documentation has caused some conceptual confusion for me. **What I want to know is what exactly is the difference between the TRON network and a TRON node?** I am not ignorant of the difference between the two, but various wallet applications (TokenPocket, imToken, TronLink, and MetaMask) have completely confused me. I will elaborate on my confusion in points 3, 4, and 5.
> 3. In the TronLink settings, under network settings, switching networks, there are only public networks (TRON mainnet, Shasta, and Nile), and other private networks cannot be added. In switching nodes, it is possible to add deployed nodes. My question is, since my deployed private chain node is not synchronized with the mainnet, it seems pointless to add the node. So when I add my own node, the number of TRX coins under my address should be different from the mainnet, but why are they the same of result?
> 4. Interestingly, in the TokenPocket wallet, after selecting the TRON network, I can add the httpFullNode address of my deployed FullNode as a custom node. Although the TokenPocket connection test fails, all functions are normal, including transfer, receiving, and the coin balance on the address.
> 5. Additionally, I found that, apart from the TokenPocket wallet, other wallets seem not to support customization of the TRON network. I know TRON supports Ethereum network's jsonrpc. In many wallet applications, when adding a network, select "Ethereum series", fill in the jsonrpc httpFullNode address of the FullNode, and after obtaining the chainid through the [document tutorial](https://developers.tron.network/reference/eth_chainid), it is possible to normally add an EVM network. But does this added network still belong to TRON?
> 
> ### These are some of my confusions. Finally, let me summarize my questions.
> **My core need is: To completely detach from the TRON mainnet and build my own TRON.**
> 
> 1. My two deployed nodes are interacting normally with each other. What else do I need to do to achieve my core need?
> 2. Why, in the TronLink Google Chrome plugin, after adding the httpFullNode address of the deployed FullNode as a custom node, is the bandwidth of the same address different from the mainnet, but the coin balance is the same as the mainnet?


@heelearn TRX is the native token of TRON network, it does not need to be specified in code and we called it as TRX. For your private chain, you can name the native token as anything. 

Because of the "node.p2p.version" of your node is different from the TRON mainnet, so your private chain is a separated network, and it has nothing related with TRON main network. No matter if the dynamic parameters are the same, they are different networks. As for why to  configure the dynamic parameters, it is because private chains are mostly used to test new features. It is more conducive to testing only when the configuration of the private chain is the same as that of the main network. Of course, this step is an optional, we can choose whether to configure it. 

It is supported to add new endpoint to Tronlink chrome extension, Settings->Networks->Add network. After switching to the new endpoint, the account information shown on tronlink will be updated, you can check the data through fullnode api: wallet/getaccount.

**Comment by 317787106** [comment]
> @ss3344520 Why, in the TronLink Google Chrome plugin, after adding the httpFullNode address of the deployed FullNode as a custom node, is the bandwidth of the same address different from the mainnet, but the coin balance is the same as the mainnet?

@heelearn The coin balance of your private address should be 0. You can use http://{ip}:16667/wallet/getaccount?address=xx to verify it. Can you choose other address to test it ?

**Comment by heelearn** [comment]
@ferdinand026 @317787106 
Thank you for your answers. 
I suspect TronLink does not support private chain networks. After TronLink correctly added a new node, it was unable to synchronize the network's account-related information, such as the number of coins.
<img width="349" alt="maintron-main" src="https://github.com/tronprotocol/java-tron/assets/151829484/874db4ff-99f9-4d5d-82da-e1fe9de839f9">
<img width="349" alt="privatetron-main" src="https://github.com/tronprotocol/java-tron/assets/151829484/1467efa5-6689-4b05-9f44-134687bb4470">
<img width="349" alt="set" src="https://github.com/tronprotocol/java-tron/assets/151829484/264e788d-220f-48d5-95a4-042d0c45284f">
<img width="1451" alt="curl" src="https://github.com/tronprotocol/java-tron/assets/151829484/90914cc6-e58d-4ee2-aad4-3a64ec738c4a">

**Comment by iamdye** [comment]
Okay, I captured the packet and figured out the problem. The tronlink application is not complete and the relevant version needs to be updated to enhance support for custom nodes.
Also, I want to know if the tronscan frontend and backend will be updated?

**Comment by heelearn** [comment]
Okay, I captured the packet and figured out the problem. The tronlink application is not complete and the relevant version needs to be updated to enhance support for custom networks.
Also, I want to know if the tronscan frontend and backend will be updated?

**Comment by sunflower-sun** [comment]
@heelearn Yes, Tronlink does not support customized network now, and so does the tronscan api. I usually use wallet-cli to communicate with private chain.  Maybe wallet-cli is a good choice for you.
