### ISSUE TITLE
Block synchronization stopped at height 57156498

### ISSUE THREAD

**Issue by xianggy** [tronprotocol/java-tron#5609]
network: mainnet
os: centos7
version: Fullnode.jar 4.7.2

here is some logs:

21:11:46.764 WARN  [pool-56-thread-1] [o.t.c.Wallet](Wallet.java:576) Broadcast transaction 17c7a8def561fe658e2220f442e78fc7358a6ca2b8c8cac7631986419ac8816d failed, Tapos failed, different block hash, 23297, 81b6759bbbd17d7e , recent block 991edd6dae99f523, solid block Num:57156480,ID:0000000003682380036e04bb988762d1da15061b66a09d4cda4defa9ec57e90f head block Num:57156498,ID:0000000003682392786bda051ce38e1b26423eb7f84dbfed3c16212abf18ee0e.
21:11:46.768 WARN  [pool-56-thread-3] [o.t.c.Wallet](Wallet.java:586) Broadcast transaction 38dac71fb96f46b64d140ad9cc9e22296296fad7f4b2bdd458f94afd35a1bbb0 failed, Transaction expiration, transaction expiration time is 1701949029000, but headBlockTime is 1702102518000.
21:11:46.772 WARN  [pool-56-thread-4] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 6edcfcd9dc6a72543a2fb8bb01f82f75f55674bb791ec38faf9a247ae1cee77d failed, dup trans : 6edcfcd9dc6a72543a2fb8bb01f82f75f55674bb791ec38faf9a247ae1cee77d .
21:11:46.776 WARN  [pool-56-thread-2] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 04d9899ee37773f5497d0065be85c1fdff1ec101b53b3e0f5bd5ce0edb593da7 failed, dup trans : 04d9899ee37773f5497d0065be85c1fdff1ec101b53b3e0f5bd5ce0edb593da7 .
21:11:46.779 WARN  [pool-56-thread-1] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 02de0f778c3be5dbc14a6224480f50070f904dd42456997fd4c05c2c7f995e7c failed, dup trans : 02de0f778c3be5dbc14a6224480f50070f904dd42456997fd4c05c2c7f995e7c .
21:11:46.782 WARN  [pool-56-thread-3] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 67d99d4bd35c025ddd9124669423dba5e9fb33a864346290a5fef01026f4fafd failed, dup trans : 67d99d4bd35c025ddd9124669423dba5e9fb33a864346290a5fef01026f4fafd .
21:11:46.786 WARN  [pool-56-thread-4] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction c56eb39a44f8e234da6ef8785cbda7d1458524c8a6c05bb3adc4249475051d42 failed, dup trans : c56eb39a44f8e234da6ef8785cbda7d1458524c8a6c05bb3adc4249475051d42 .
21:11:46.789 WARN  [pool-56-thread-2] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 282fd1db93b63632cfafecb550c04157ce36e4aac65c3870b0c7a66c2aff370a failed, dup trans : 282fd1db93b63632cfafecb550c04157ce36e4aac65c3870b0c7a66c2aff370a .
21:11:46.793 WARN  [pool-56-thread-1] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction d50fd1d740b874554fced08c50b46e3cae9188a374dd23d1a7120ba1262d4b4f failed, dup trans : d50fd1d740b874554fced08c50b46e3cae9188a374dd23d1a7120ba1262d4b4f .
21:11:46.796 WARN  [pool-56-thread-3] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 3fe8791a531b67cf6bc02d9dfa92318128ca2fbb0a12db022c037d276369141b failed, dup trans : 3fe8791a531b67cf6bc02d9dfa92318128ca2fbb0a12db022c037d276369141b .
21:11:46.800 WARN  [pool-56-thread-4] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction fb7b9a1bf663c36800f1d8286a7182297e1ad3d7721000a97fae7e321f2d269a failed, dup trans : fb7b9a1bf663c36800f1d8286a7182297e1ad3d7721000a97fae7e321f2d269a .
21:11:46.804 WARN  [pool-56-thread-2] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction a5a2bcf7617b9e166a9c7a4c82b724de2ecbd374f0f87bba208a2d3578270151 failed, dup trans : a5a2bcf7617b9e166a9c7a4c82b724de2ecbd374f0f87bba208a2d3578270151 .
21:11:46.813 WARN  [pool-56-thread-1] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 37d604644876c7dd8879f2a95533aed4b5b1d301687ad11157e818bcc818ac69 failed, dup trans : 37d604644876c7dd8879f2a95533aed4b5b1d301687ad11157e818bcc818ac69 .
21:11:46.816 WARN  [pool-56-thread-3] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction f89842b871ba317d491cda63deed65ffab36f0aedbf0462f08de377e547e492d failed, dup trans : f89842b871ba317d491cda63deed65ffab36f0aedbf0462f08de377e547e492d .
21:11:46.820 WARN  [pool-56-thread-4] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction ec0a0a5b5bbcb2d00d1882a2a3ffd4c37a25ffbaee7f73d3e15a2fe573fba066 failed, dup trans : ec0a0a5b5bbcb2d00d1882a2a3ffd4c37a25ffbaee7f73d3e15a2fe573fba066 .
21:11:46.824 WARN  [pool-56-thread-2] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 43203cc5a2eba2aa3f70a450d0646fb5e07bf23c78d666a2681f083cfc94cb7c failed, dup trans : 43203cc5a2eba2aa3f70a450d0646fb5e07bf23c78d666a2681f083cfc94cb7c .
21:11:46.827 WARN  [pool-56-thread-1] [o.t.c.Wallet](Wallet.java:571) Broadcast transaction 986304bc2d1ebb004e9c20994b19bd6ab0916c70aa9a554d09095c4e29eeacdd failed, dup trans : 986304bc2d1ebb004e9c20994b19bd6ab0916c70aa9a554d09095c4e29eeacdd .
============ Peer stats: all 9, active 9, passive 0

Peer /170.187.228.182:18888
connect time: 431061s [0ms]
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:false
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:0
syncChainRequested:0
blockInProcess:0

Peer /172.104.62.120:18888
connect time: 222945s [0ms]
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:false
syncToFetchSize:0
syncToFetchSizePeekNum:-1
syncBlockRequestedSize:0
remainNum:0
syncChainRequested:0
blockInProcess:0

Peer /172.105.195.20:18888
connect time: 60403s [65ms]
last know block num: 0
needSyncFromPeer:false
needSyncFromUs:false
syncToFetchSize:0
syncToFetchSizePeekNum:-1

**Comment by ferdinand026** [comment]
@xianggy Hope this guide helps: https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization.

**Comment by halibobo1205** [comment]
@alexexxman Could you provide the logs of the first synchronization near 57156498?

**Comment by 317787106** [comment]
@xianggy Your node only have active nodes, but not passive nodes. Please checkout that the listen port 18888 is open to public network.

**Comment by xianggy** [comment]
> @alexexxman Could you provide the logs of the first synchronization near 57156498?

14:15:18.616 INFO  [PeerClient-6] [DB](DynamicPropertiesStore.java:2190) Update state flag = 0.
14:15:18.616 INFO  [PeerClient-6] [consensus](DposService.java:162) Update solid block number to 57156480
14:15:18.617 INFO  [PeerClient-6] [DB](DynamicPropertiesStore.java:2185) Update latest block header id = 0000000003682392786bda051ce38e1b26423eb7f84dbfed3c16212abf18ee0e.
14:15:18.617 INFO  [PeerClient-6] [DB](DynamicPropertiesStore.java:2177) Update latest block header number = 57156498.
14:15:18.617 INFO  [PeerClient-6] [DB](DynamicPropertiesStore.java:2169) Update latest block header timestamp = 1702102518000.
14:15:18.617 INFO  [PeerClient-6] [DB](Manager.java:1311) Save block: BlockCapsule
[ hash=0000000003682392786bda051ce38e1b26423eb7f84dbfed3c16212abf18ee0e
number=57156498
parentId=000000000368239194f30754ba7bcc0d4ed75de99a194468e908741ff1bb3706
witness address=419a96c8003a1e3a6866c08acff9f629e2a6ef062b
generated by myself=false
generate time=2023-12-09 14:15:18.0
account root=0000000000000000000000000000000000000000000000000000000000000000
merkle root=e650c48cb0984c11bdb2b3dbf6c8e5b1344441e1af9af6d09e6e996f20899a6d
txs size=152
]
14:15:18.617 INFO  [PeerClient-6] [DB](PendingManager.java:57) Pending tx size: 157.
14:15:18.617 INFO  [PeerClient-6] [DB](Manager.java:1329) PushBlock block number: 57156498, cost/txs: 54/152 false.
14:15:18.617 INFO  [PeerClient-6] [net](TronNetDelegate.java:263) Success process block Num:57156498,ID:0000000003682392786bda051ce38e1b26423eb7f84dbfed3c16212abf18ee0e
14:15:18.618 INFO  [PeerClient-6] [net](BlockMsgHandler.java:90) Receive block/interval 57156498/1 from /178.63.27.40:18888 fetch/delay 248/559ms, txs/process 152/59ms, witness: 419a96c8003a1e3a6866c08acff9f629e2a6ef062b
14:15:18.618 INFO  [PeerClient-6] [net](P2pEventHandlerImpl.java:212) Message processing costs 59 ms, peer: /178.63.27.40:18888, type: BLOCK, time tag: ~~
14:15:18.655 INFO  [pool-50-thread-2] [DB](SnapshotManager.java:365) Flush cost: 31 ms, create checkpoint cost: 25 ms, refresh cost: 6 ms.
14:15:18.735 INFO  [PeerClient-1] [net](P2pEventHandlerImpl.java:167) Receive message from  peer: /172.232.159.118:18888, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000003682392786bda051ce38e1b26423eb7f84dbfed3c16212abf18ee0e
14:15:18.758 INFO  [PeerClient-10] [net](P2pEventHandlerImpl.java:167) Receive message from  peer: /69.164.192.37:18888, type: INVENTORY
invType: BLOCK, size: 1, First hash: 0000000003682392786bda051ce38e1b26423eb7f84dbfed3c16212abf18ee0e
14:15:19.086 INFO  [PeerClient-6] [net](P2pChannelInitializer.java:44) Close channel:/178.63.27.40:18888
14:15:19.086 INFO  [PeerClient-6] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:19.101 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /13.213.225.227:18888
14:15:19.105 INFO  [PeerClient-7] [net](ChannelManager.java:145) Add peer /13.213.225.227:18888, total channels: 9
14:15:19.105 INFO  [PeerClient-7] [net](HandshakeService.java:49) Handshake failed /13.213.225.227:18888, code: 1, networkId:11111, version: 1
14:15:19.105 INFO  [PeerClient-7] [net](P2pChannelInitializer.java:44) Close channel:/13.213.225.227:18888
14:15:19.105 INFO  [PeerClient-7] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:19.110 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /132.145.129.253:18888
14:15:19.567 INFO  [PeerClient-8] [net](ChannelManager.java:145) Add peer /132.145.129.253:18888, total channels: 9
14:15:19.567 INFO  [PeerClient-8] [net](HandshakeService.java:49) Handshake failed /132.145.129.253:18888, code: 1, networkId:11111, version: 1
14:15:19.568 INFO  [PeerClient-8] [net](P2pChannelInitializer.java:44) Close channel:/132.145.129.253:18888
14:15:19.568 INFO  [PeerClient-8] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:19.576 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /65.21.95.39:18888
14:15:20.121 INFO  [PeerClient-9] [net](ChannelManager.java:145) Add peer /65.21.95.39:18888, total channels: 9
14:15:20.121 INFO  [PeerClient-9] [net](HandshakeService.java:49) Handshake failed /65.21.95.39:18888, code: 1, networkId:11111, version: 1
14:15:20.121 INFO  [PeerClient-9] [net](P2pChannelInitializer.java:44) Close channel:/65.21.95.39:18888
14:15:20.122 INFO  [PeerClient-9] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:20.128 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /18.142.183.117:18888
14:15:20.130 INFO  [PeerClient-10] [net](ChannelManager.java:145) Add peer /18.142.183.117:18888, total channels: 9
14:15:20.130 INFO  [PeerClient-10] [net](HandshakeService.java:49) Handshake failed /18.142.183.117:18888, code: 1, networkId:11111, version: 1
14:15:20.131 INFO  [PeerClient-10] [net](P2pChannelInitializer.java:44) Close channel:/18.142.183.117:18888
14:15:20.131 INFO  [PeerClient-10] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:20.136 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /13.124.62.58:18888
14:15:20.308 INFO  [PeerClient-11] [net](ChannelManager.java:145) Add peer /13.124.62.58:18888, total channels: 9
14:15:20.309 INFO  [PeerClient-11] [net](HandshakeService.java:49) Handshake failed /13.124.62.58:18888, code: 1, networkId:11111, version: 1
14:15:20.309 INFO  [PeerClient-11] [net](P2pChannelInitializer.java:44) Close channel:/13.124.62.58:18888
14:15:20.309 INFO  [PeerClient-11] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:20.314 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /162.55.238.181:18888
14:15:20.588 WARN  [pool-56-thread-3] [o.t.c.Wallet](Wallet.java:576) Broadcast transaction 17c7a8def561fe658e2220f442e78fc7358a6ca2b8c8cac7631986419ac8816d failed, Tapos failed, different block hash, 23297, 81b6759bbbd17d7e , recent block 991edd6dae99f523, solid block Num:57156480,ID:0000000003682380036e04bb988762d1da15061b66a09d4cda4defa9ec57e90f head block Num:57156498,ID:0000000003682392786bda051ce38e1b26423eb7f84dbfed3c16212abf18ee0e.
14:15:20.593 WARN  [pool-56-thread-2] [o.t.c.Wallet](Wallet.java:586) Broadcast transaction 38dac71fb96f46b64d140ad9cc9e22296296fad7f4b2bdd458f94afd35a1bbb0 failed, Transaction expiration, transaction expiration time is 1701949029000, but headBlockTime is 1702102518000.
14:15:20.826 INFO  [PeerClient-12] [net](ChannelManager.java:145) Add peer /162.55.238.181:18888, total channels: 9
14:15:20.826 INFO  [PeerClient-12] [net](HandshakeService.java:49) Handshake failed /162.55.238.181:18888, code: 1, networkId:11111, version: 1
14:15:20.826 INFO  [PeerClient-12] [net](P2pChannelInitializer.java:44) Close channel:/162.55.238.181:18888
14:15:20.827 INFO  [PeerClient-12] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:20.833 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /52.60.187.83:18888
14:15:21.339 INFO  [PeerClient-13] [net](ChannelManager.java:145) Add peer /52.60.187.83:18888, total channels: 9
14:15:21.339 INFO  [PeerClient-13] [net](HandshakeService.java:49) Handshake failed /52.60.187.83:18888, code: 1, networkId:11111, version: 1
14:15:21.339 INFO  [PeerClient-13] [net](P2pChannelInitializer.java:44) Close channel:/52.60.187.83:18888
14:15:21.339 INFO  [PeerClient-13] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:21.346 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /18.231.27.82:18888
14:15:22.003 INFO  [PeerClient-14] [net](ChannelManager.java:145) Add peer /18.231.27.82:18888, total channels: 9
14:15:22.004 INFO  [PeerClient-14] [net](HandshakeService.java:49) Handshake failed /18.231.27.82:18888, code: 1, networkId:11111, version: 1
14:15:22.004 INFO  [PeerClient-14] [net](P2pChannelInitializer.java:44) Close channel:/18.231.27.82:18888
14:15:22.004 INFO  [PeerClient-14] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:22.010 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /52.15.93.92:18888
14:15:22.453 INFO  [PeerClient-15] [net](ChannelManager.java:145) Add peer /52.15.93.92:18888, total channels: 9
14:15:22.454 INFO  [PeerClient-15] [net](HandshakeService.java:49) Handshake failed /52.15.93.92:18888, code: 1, networkId:11111, version: 1
14:15:22.454 INFO  [PeerClient-15] [net](P2pChannelInitializer.java:44) Close channel:/52.15.93.92:18888
14:15:22.454 INFO  [PeerClient-15] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:22.460 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /13.231.145.195:18888
14:15:22.598 INFO  [PeerClient-0] [net](ChannelManager.java:145) Add peer /13.231.145.195:18888, total channels: 9
14:15:22.598 INFO  [PeerClient-0] [net](HandshakeService.java:49) Handshake failed /13.231.145.195:18888, code: 1, networkId:11111, version: 1
14:15:22.598 INFO  [PeerClient-0] [net](P2pChannelInitializer.java:44) Close channel:/13.231.145.195:18888
14:15:22.598 INFO  [PeerClient-0] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:22.603 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /162.248.224.199:18888
14:15:22.961 INFO  [PeerClient-1] [net](ChannelManager.java:145) Add peer /162.248.224.199:18888, total channels: 9
14:15:22.961 INFO  [PeerClient-1] [net](HandshakeService.java:49) Handshake failed /162.248.224.199:18888, code: 1, networkId:11111, version: 1
14:15:22.961 INFO  [PeerClient-1] [net](P2pChannelInitializer.java:44) Close channel:/162.248.224.199:18888
14:15:22.961 INFO  [PeerClient-1] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:22.968 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /217.28.62.27:18888
14:15:23.506 INFO  [PeerClient-2] [net](ChannelManager.java:145) Add peer /217.28.62.27:18888, total channels: 9
14:15:23.506 INFO  [PeerClient-2] [net](HandshakeService.java:49) Handshake failed /217.28.62.27:18888, code: 1, networkId:11111, version: 1
14:15:23.507 INFO  [PeerClient-2] [net](P2pChannelInitializer.java:44) Close channel:/217.28.62.27:18888
14:15:23.507 INFO  [PeerClient-2] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:23.513 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /65.21.125.7:18888
14:15:23.833 INFO  [NodePersistTaskTimer] [net](NodePersistService.java:88) Write nodes to store: 30/122 nodes
14:15:24.061 INFO  [PeerClient-3] [net](ChannelManager.java:145) Add peer /65.21.125.7:18888, total channels: 9
14:15:24.061 INFO  [PeerClient-3] [net](HandshakeService.java:49) Handshake failed /65.21.125.7:18888, code: 1, networkId:11111, version: 1
14:15:24.062 INFO  [PeerClient-3] [net](P2pChannelInitializer.java:44) Close channel:/65.21.125.7:18888
14:15:24.062 INFO  [PeerClient-3] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:24.068 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /54.252.224.209:18888
14:15:24.253 INFO  [PeerClient-4] [net](ChannelManager.java:145) Add peer /54.252.224.209:18888, total channels: 9
14:15:24.253 INFO  [PeerClient-4] [net](HandshakeService.java:49) Handshake failed /54.252.224.209:18888, code: 1, networkId:11111, version: 1
14:15:24.254 INFO  [PeerClient-4] [net](P2pChannelInitializer.java:44) Close channel:/54.252.224.209:18888
14:15:24.254 INFO  [PeerClient-4] [net](ConnPoolService.java:254) Peer stats: channels 8, activePeers 8, active 8, passive 0
14:15:24.260 INFO  [pool-61-thread-1] [net](ConnPoolService.java:188) Connect to peer /91.228.147.6:18888
14:15:24.628 INFO  [PeerClient-5] [net](ChannelManager.java:145) Add peer /91.228.147.6:18888, total channels: 9
14:15:24.629 INFO  [PeerClient-5] [net](HandshakeService.java:49) Handshake failed /91.228.147.6:18888, code: 1, networkId:11111, version: 1
14:15:24.629 INFO  [PeerClient-5] [net](P2pChannelInitializer.java:44) Close channel:/91.228.147.6:18888

**Comment by xianggy** [comment]
> @xianggy Your node only have active peers, but not passive peers. Please checkout that the listen port 18888 of tcp and udp is open to public network.

I think the port is fine. Because this node has been working fine before.
btw,  what is the difference about  active peers and passive peers?

**Comment by halibobo1205** [comment]
Is service back to normal now? It is clear from the above log that the next block was not received just like this.
<img width="1378" alt="image" src="https://github.com/tronprotocol/java-tron/assets/82020050/061ec75e-8b88-43f6-a13a-2faaeeb78cf4">

**Comment by xianggy** [comment]
> Is service back to normal now? It is clear from the above log that the next block was not received just like this. <img alt="image" width="1378" src="https://private-user-images.githubusercontent.com/82020050/289818874-061ec75e-8b88-43f6-a13a-2faaeeb78cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzMzMDMsIm5iZiI6MTcwMjQzMzAwMywicGF0aCI6Ii84MjAyMDA1MC8yODk4MTg4NzQtMDYxZWM3NWUtOGI4OC00M2Y2LWExM2EtMmZhYWVlYjc4Y2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAyMDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMjM2MTBiNzE1OWE1MDM2ZDZlZDI0OWUyYzAwM2M0ZmUyMDZjYmNjMWFkOWE2ZDkwODhkODMzZmI4YWVhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qu4sCNXQq8XxVsTWLi3NlyoocLqQxFoWctdmt77jewQ">

I updated to v4.7.3 and it's ok now.
Could you tell me what is the reason?
Will it be possible to back to normal by upgrading the node if we encounter such problems later?

**Comment by halibobo1205** [comment]
@xianggy, keeping the latest version is a good choice.  If the full logs are still available, can you provide these, please?

**Comment by 317787106** [comment]
> > @xianggy Your node only have active peers, but not passive peers. Please checkout that the listen port 18888 of tcp and udp is open to public network.
> 
> I think the port is fine. Because this node has been working fine before. btw, what is the difference about active peers and passive peers?

@xianggy If the port 18888 of tcp & udp is not open to public network, only you can connect peer actively, but peer can not connect with you actively through port 18888, so only active peers is exist. And you should also checkout that config item node.discovery.enable is true, otherwise your number of peers will not exceed the default value of 8, in this case, it's possible that all peers' head number is low than you and you can not sync.

**Comment by xianggy** [comment]
> @xianggy, keeping the latest version is a good choice. If the full logs are still available, can you provide these, please?

**Comment by xianggy** [comment]
> @xianggy, keeping the latest version is a good choice. If the full logs are still available, can you provide these, please?
[tron-2023-12-09.0.log.zip](https://github.com/tronprotocol/java-tron/files/13657617/tron-2023-12-09.0.log.zip)

**Comment by xianggy** [comment]
> @xianggy If the port 18888 of tcp & udp is not open to public network, only you can connect peer actively, but peer can not connect with you actively through port 18888, so only active peers is exist. And you should also checkout that config item node.discovery.enable is true, otherwise your number of peers will not exceed the default value of 8, in this case, it's possible that all peers' head number is low than you and you can not sync.
> 
> I have got the same problem as your several days ago. May you can try to use my advice.

Thanks you Bro, I will check about it.

**Comment by CaCaBlocker** [comment]
Hello, @xianggy 
Can you help me?
https://github.com/tronprotocol/java-tron/issues/5640
Thanks in advance.

**Comment by vivian1912** [comment]
@xianggy Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.

**Comment by xianggy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
