### ISSUE TITLE
Block synchronization stopped at height 57123557

### ISSUE THREAD

**Issue by alexexxman** [tronprotocol/java-tron#5610]
15:48:58.178 INFO  [peerClient-8] [net](ChannelManager.java:148) Add peer /52.15.93.92:18888, total channels: 9
15:48:58.179 INFO  [peerClient-8] [net](HandshakeService.java:56) Handshake failed /52.15.93.92:18888, code: 1, reason: TOO_MANY_PEERS, networkId: 11111, version: 1
15:48:58.179 INFO  [peerClient-8] [net](ChannelManager.java:178) Try to close channel: /52.15.93.92:18888, reason: TOO_MANY_PEERS
15:48:58.179 INFO  [peerClient-8] [net](P2pChannelInitializer.java:45) Close channel:/52.15.93.92:18888
15:48:58.179 INFO  [peerClient-8] [net](ConnPoolService.java:261) Peer stats: channels 8, activePeers 8, active 5, passive 3

15:48:58.581 INFO  [peerClient-9] [net](ChannelManager.java:148) Add peer /65.21.138.147:18888, total channels: 9
15:48:58.581 INFO  [peerClient-9] [net](HandshakeService.java:56) Handshake failed /65.21.138.147:18888, code: 1, reason: TOO_MANY_PEERS, networkId: 11111, version: 1
15:48:58.582 INFO  [peerClient-9] [net](ChannelManager.java:178) Try to close channel: /65.21.138.147:18888, reason: TOO_MANY_PEERS
15:48:58.582 INFO  [peerClient-9] [net](P2pChannelInitializer.java:45) Close channel:/65.21.138.147:18888
15:48:58.582 INFO  [peerClient-9] [net](ConnPoolService.java:261) Peer stats: channels 8, activePeers 8, active 5, passive 3

**Comment by alexexxman** [comment]
10:27:53.230 INFO  [nioEventLoopGroup-6-12] [net](P2pChannelInitializer.java:44) Close channel:/18.143.155.86:37228
10:27:53.230 INFO  [nioEventLoopGroup-6-12] [net](ConnPoolService.java:254) Peer stats: channels 10, activePeers 10, active 3, passive 7
10:27:53.537 WARN  [pool-50-thread-1] [net](PeerStatusCheck.java:49) Peer /34.237.210.82 not sync for a long time
10:27:53.537 INFO  [pool-50-thread-1] [net](PeerConnection.java:171) Send peer /34.237.210.82:18888 message type: P2P_DISCONNECT
reason: TIME_OUT
10:27:53.537 INFO  [PeerClient-11] [net](P2pChannelInitializer.java:44) Close channel:/34.237.210.82:18888
10:27:53.537 INFO  [PeerClient-11] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:53.540 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /162.19.136.25:30001
10:27:53.855 INFO  [PeerClient-6] [net](ChannelManager.java:145) Add peer /162.19.136.25:30001, total channels: 10
10:27:53.855 INFO  [PeerClient-6] [net](HandshakeService.java:49) Handshake failed /162.19.136.25:30001, code: 1, networkId:11111, version: 1
10:27:53.855 INFO  [PeerClient-6] [net](P2pChannelInitializer.java:44) Close channel:/162.19.136.25:30001
10:27:53.855 INFO  [PeerClient-6] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:53.858 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /94.130.64.26:18888
10:27:54.218 INFO  [PeerClient-7] [net](ChannelManager.java:145) Add peer /94.130.64.26:18888, total channels: 10
10:27:54.218 INFO  [PeerClient-7] [net](HandshakeService.java:49) Handshake failed /94.130.64.26:18888, code: 1, networkId:11111, version: 1
10:27:54.219 INFO  [PeerClient-7] [net](P2pChannelInitializer.java:44) Close channel:/94.130.64.26:18888
10:27:54.219 INFO  [PeerClient-7] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:54.221 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /168.119.32.242:18888
10:27:54.558 INFO  [PeerClient-8] [net](ChannelManager.java:145) Add peer /168.119.32.242:18888, total channels: 10
10:27:54.559 INFO  [PeerClient-8] [net](HandshakeService.java:49) Handshake failed /168.119.32.242:18888, code: 1, networkId:11111, version: 1
10:27:54.559 INFO  [PeerClient-8] [net](P2pChannelInitializer.java:44) Close channel:/168.119.32.242:18888
10:27:54.559 INFO  [PeerClient-8] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:54.561 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /65.109.89.115:18888
10:27:54.933 INFO  [PeerClient-9] [net](ChannelManager.java:145) Add peer /65.109.89.115:18888, total channels: 10
10:27:54.933 INFO  [PeerClient-9] [net](HandshakeService.java:49) Handshake failed /65.109.89.115:18888, code: 1, networkId:11111, version: 1
10:27:54.934 INFO  [PeerClient-9] [net](P2pChannelInitializer.java:44) Close channel:/65.109.89.115:18888
10:27:54.934 INFO  [PeerClient-9] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:54.936 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /176.9.90.23:18888
10:27:55.290 INFO  [PeerClient-10] [net](ChannelManager.java:145) Add peer /176.9.90.23:18888, total channels: 10
10:27:55.290 INFO  [PeerClient-10] [net](HandshakeService.java:49) Handshake failed /176.9.90.23:18888, code: 1, networkId:11111, version: 1
10:27:55.291 INFO  [PeerClient-10] [net](P2pChannelInitializer.java:44) Close channel:/176.9.90.23:18888
10:27:55.291 INFO  [PeerClient-10] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:55.293 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /18.196.99.16:18888
10:27:55.609 INFO  [PeerClient-11] [net](ChannelManager.java:145) Add peer /18.196.99.16:18888, total channels: 10
10:27:55.609 INFO  [PeerClient-11] [net](HandshakeService.java:49) Handshake failed /18.196.99.16:18888, code: 1, networkId:11111, version: 1
10:27:55.609 INFO  [PeerClient-11] [net](P2pChannelInitializer.java:44) Close channel:/18.196.99.16:18888
10:27:55.609 INFO  [PeerClient-11] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:55.612 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /18.166.99.110:18888
10:27:55.698 INFO  [PeerClient-12] [net](ChannelManager.java:145) Add peer /18.166.99.110:18888, total channels: 10
10:27:55.699 INFO  [PeerClient-12] [net](HandshakeService.java:49) Handshake failed /18.166.99.110:18888, code: 1, networkId:11111, version: 1
10:27:55.699 INFO  [PeerClient-12] [net](P2pChannelInitializer.java:44) Close channel:/18.166.99.110:18888
10:27:55.699 INFO  [PeerClient-12] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:55.701 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /3.218.137.187:18888
10:27:56.168 INFO  [PeerClient-13] [net](ChannelManager.java:145) Add peer /3.218.137.187:18888, total channels: 10
10:27:56.168 INFO  [PeerClient-13] [net](HandshakeService.java:49) Handshake failed /3.218.137.187:18888, code: 1, networkId:11111, version: 1
10:27:56.168 INFO  [PeerClient-13] [net](P2pChannelInitializer.java:44) Close channel:/3.218.137.187:18888
10:27:56.168 INFO  [PeerClient-13] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:56.170 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /136.243.243.67:18888
10:27:56.506 INFO  [PeerClient-14] [net](ChannelManager.java:145) Add peer /136.243.243.67:18888, total channels: 10
10:27:56.506 INFO  [PeerClient-14] [net](HandshakeService.java:49) Handshake failed /136.243.243.67:18888, code: 1, networkId:11111, version: 1
10:27:56.507 INFO  [PeerClient-14] [net](P2pChannelInitializer.java:44) Close channel:/136.243.243.67:18888
10:27:56.507 INFO  [PeerClient-14] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:56.509 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /34.151.199.72:18888
10:27:56.835 INFO  [nioEventLoopGroup-6-13] [net](ChannelManager.java:114) Peer /18.143.155.86:37382 | f1d2f6f66162d8afda89d20e0ea318b48e02c8e3afcbbf1eef10c161b6cdac09f5d2df2c97cd050b4c3987c03d85baf9d52d6dda4205635f674529de445a9551 recently disconnected
10:27:56.835 INFO  [nioEventLoopGroup-6-13] [net](P2pChannelInitializer.java:44) Close channel:/18.143.155.86:37382
10:27:56.836 INFO  [nioEventLoopGroup-6-13] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:57.171 INFO  [PeerClient-15] [net](ChannelManager.java:145) Add peer /34.151.199.72:18888, total channels: 10
10:27:57.172 INFO  [PeerClient-15] [net](HandshakeService.java:49) Handshake failed /34.151.199.72:18888, code: 1, networkId:11111, version: 1
10:27:57.172 INFO  [PeerClient-15] [net](P2pChannelInitializer.java:44) Close channel:/34.151.199.72:18888
10:27:57.172 INFO  [PeerClient-15] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:57.174 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /95.217.44.33:18888
10:27:57.532 INFO  [PeerClient-0] [net](P2pChannelInitializer.java:44) Close channel:/95.217.44.33:18888
10:27:57.532 INFO  [PeerClient-0] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:57.534 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /18.183.152.64:18888
10:27:57.673 INFO  [PeerClient-1] [net](ChannelManager.java:145) Add peer /18.183.152.64:18888, total channels: 10
10:27:57.673 INFO  [PeerClient-1] [net](HandshakeService.java:49) Handshake failed /18.183.152.64:18888, code: 1, networkId:11111, version: 1
10:27:57.673 INFO  [PeerClient-1] [net](P2pChannelInitializer.java:44) Close channel:/18.183.152.64:18888
10:27:57.674 INFO  [PeerClient-1] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:57.676 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /157.90.208.206:18888
10:27:58.038 INFO  [PeerClient-2] [net](ChannelManager.java:145) Add peer /157.90.208.206:18888, total channels: 10
10:27:58.038 INFO  [PeerClient-2] [net](HandshakeService.java:49) Handshake failed /157.90.208.206:18888, code: 1, networkId:11111, version: 1
10:27:58.039 INFO  [PeerClient-2] [net](P2pChannelInitializer.java:44) Close channel:/157.90.208.206:18888
10:27:58.039 INFO  [PeerClient-2] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:58.041 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /188.187.190.7:18888
10:27:58.477 INFO  [PeerClient-3] [net](ChannelManager.java:145) Add peer /188.187.190.7:18888, total channels: 10
10:27:58.478 INFO  [PeerClient-3] [net](HandshakeService.java:49) Handshake failed /188.187.190.7:18888, code: 1, networkId:11111, version: 1
10:27:58.478 INFO  [PeerClient-3] [net](P2pChannelInitializer.java:44) Close channel:/188.187.190.7:18888
10:27:58.478 INFO  [PeerClient-3] [net](ConnPoolService.java:254) Peer stats: channels 9, activePeers 9, active 2, passive 7
10:27:58.480 INFO  [pool-64-thread-1] [net](ConnPoolService.java:188) Connect to peer /178.63.104.190:18888

**Comment by ferdinand026** [comment]
@alexexxman Hope this guide helps: https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization.

**Comment by halibobo1205** [comment]
@alexexxman Could you provide the logs of the first synchronization near 57123557?

**Comment by CaCaBlocker** [comment]
@ferdinand026 

Can you help me?
https://github.com/tronprotocol/java-tron/issues/5640

**Comment by vivian1912** [comment]
@alexexxman Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
