### ISSUE TITLE
How to do token(TRC20) record in private network?

### ISSUE THREAD

**Issue by heelearn** [tronprotocol/java-tron#5613]
I have successfully issued a TRC10 token and a contract in a private network. 

**My current issue is how to create a TRC20 token in the private network?** 

According to my research, TRC20 tokens are created in tronscan.org through the API interface /external/trc20tokens, but I haven't found a similar interface in either the tronscan-api library or the HTTP API provided by java-tron.

**Comment by laurenceja** [comment]
@heelearn  "wallet/deploycontract" API of fullnode is used to depoay a trc20 token, here are some guides: https://developers.tron.network/docs/smart-contract-deployment-and-invocation . https://developers.tron.network/docs/smart-contract-development

**Comment by heelearn** [comment]
@laurenceja  Thanks for the reply, but I was referring to the token record, not the contract.
<img width="404" alt="token" src="https://github.com/tronprotocol/java-tron/assets/151829484/ffb055f9-eb3e-4d52-8c7b-94404cf77662">

**Comment by heelearn** [comment]
Are there any contributors who can solve this issue?

**Comment by laurenceja** [comment]
> @laurenceja Thanks for the reply, but I was referring to the token record, not the contract. <img alt="token" width="404" src="https://private-user-images.githubusercontent.com/151829484/290137885-ffb055f9-eb3e-4d52-8c7b-94404cf77662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzgxMTgsIm5iZiI6MTcwMjUzNzgxOCwicGF0aCI6Ii8xNTE4Mjk0ODQvMjkwMTM3ODg1LWZmYjA1NWY5LWViM2UtNGQ1Mi04YzdiLTk0NDA0Y2Y3NzY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwNzEwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGY5NzI4ZjI2ZjQ3NDlhYjVjMGZjYTNkMjNlN2M5ZWM2MGVhYzU5MmM2YTM3NThkNWJmODU1MmIxMzg2MzMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.niShNjVaMMHJqdOZHk6UHCqEQhRr4oPyJIoLzRidgzA">

Creating a TRC20 token is to deploy a contract, and the contract needs to meet the TRC20 protocal standard: https://developers.tron.network/docs/trc20-protocol-interface. As for record the trc 20 on tronscan, it is to upload the token
 information to TRONSCAN, for example, token introduction. But there is no explore for private network, so just ignore the step.

**Comment by heelearn** [comment]
@laurenceja When a smart contract is released in a private network, does it mean that trc20 tokens are created? But if I don’t perform tronscan’s token record operation, how can I query transaction records such as token transfers on the private network?

**Comment by laurenceja** [comment]
> @laurenceja When a smart contract is released in a private network, does it mean that trc20 tokens are created? But if I don’t perform tronscan’s token record operation, how can I query transaction records such as token transfers on the private network?

Yes, once the contract is deployed, the token is created. You can query the transaction through the query APIs provided by Fullnode: https://developers.tron.network/reference/getblock-1

**Comment by heelearn** [comment]
> > @laurenceja When a smart contract is released in a private network, does it mean that trc20 tokens are created? But if I don’t perform tronscan’s token record operation, how can I query transaction records such as token transfers on the private network?
> 
> Yes, once the contract is deployed, the token is created. You can query the transaction through the query APIs provided by Fullnode: https://developers.tron.network/reference/getblock-1

@laurenceja Thank you for your support, I have already solved this issue.
On this occasion, I would like to ask again, what are some good ways to obtain a list of all contracts and tokens through the fullnode HTTP API in a private network?
Do we really only have the option to loop traversal?

**Comment by laurenceja** [comment]
> > > @laurenceja When a smart contract is released in a private network, does it mean that trc20 tokens are created? But if I don’t perform tronscan’s token record operation, how can I query transaction records such as token transfers on the private network?
> > 
> > 
> > Yes, once the contract is deployed, the token is created. You can query the transaction through the query APIs provided by Fullnode: https://developers.tron.network/reference/getblock-1
> 
> @laurenceja Thank you for your support, I have already solved this issue. On this occasion, I would like to ask again, what are some good ways to obtain a list of all contracts and tokens through the fullnode HTTP API in a private network? Do we really only have the option to loop traversal?

Except the loop traversal, we can also use the [event subscription](https://developers.tron.network/docs/event-subscription) function to get the specified events.

**Comment by vivian1912** [comment]
@heelearn Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
