### ISSUE TITLE
Reduce database snapshot size

### ISSUE THREAD

**Issue by moqi2011** [tronprotocol/java-tron#5614]
# Rationale

### Why should this feature exist?

The current full-node database snapshot file is too large, downloads slowly, and takes up too much disk space.

### What are the use-cases?

Users with limited disk space or limited network bandwidth.

# Implementation

### Do you have ideas regarding the implementation of this feature?

Analyze which files take up more space.
```bash
# du -lh database/ | sort -h
24K	database/account-asset-issue
24K	database/account-trace
24K	database/accountTrie
24K	database/balance-trace
24K	database/block_KDB
24K	database/common-database
24K	database/IncrementalMerkleVoucher
24K	database/market_account
24K	database/market_order
24K	database/market_pair_price_to_order
24K	database/market_pair_to_price
24K	database/nullifier
24K	database/pbft-sign-data
24K	database/zkProof
32K	database/witness_schedule
36K	database/accountid-index
48K	database/exchange-v2
216K	database/proposal
384K	database/asset-issue
396K	database/witness
1.2M	database/exchange
1.3M	database/votes
1.7M	database/account-index
1.9M	database/asset-issue-v2
3.2M	database/properties
4.5M	database/IncrementalMerkleTree
6.3M	database/tmp
7.3M	database/DelegatedResource
9.2M	database/common
13M	database/recent-block
18M	database/peers
46M	database/contract-state
155M	database/section-bloom
201M	database/abi
278M	database/DelegatedResourceAccountIndex
316M	database/tree-block-index
878M	database/contract
1.1G	database/code
1.9G	database/recent-transaction
2.0G	database/block-index
3.3G	database/trans-cache
3.5G	database/account-asset
4.3G	database/delegation
13G	database/storage-row
23G	database/account
141G	database/transactionHistoryStore
313G	database/trans
576G	database/transactionRetStore
926G	database/block
2.0T	database/
```
We can see that mainly the four databases "transactionHistoryStore, trans, transactionRetStore, block" occupy disk space. By analyzing the code, it seems that the first three databases can be built through the "block" database.    

If it is what I guessed, then we can discard the first three databases when building the database snapshot, and rebuild the complete database file through the command line program after the user downloads it.

But I don't know how long it will take to rebuild.

**Comment by halibobo1205** [comment]
1. `transactionHistoryStore` is the previous version of `transactionRetStore`, which is now deprecated. If you resync from 0, the relevant data is written to `transactionRetStore`.
2. `transactionRetStore` or `transactionHistoryStore` rebuild relies on transaction execution, which will be time-consuming,  basically equivalent to synchronizing from zero.
3. `trans` can be recovered directly with the help of the `block`.

**Comment by moqi2011** [comment]
> 1. `transactionHistoryStore` is the previous version of `transactionRetStore`, which is now deprecated. If you resync from 0, the relevant data is written to `transactionRetStore`.

So can I delete the `transactionHistoryStore` database?

**Comment by halibobo1205** [comment]
> > 1. `transactionHistoryStore` is the previous version of `transactionRetStore`, which is now deprecated. If you resync from 0, the relevant data is written to `transactionRetStore`.
> 
> So can I delete the `transactionHistoryStore` database?

Sorry, you can't delete it according to the above explanation, there's no overlap between the two databases.

**Comment by forfreeday** [comment]
Are you considering this issue from the perspective of optimizing the size of the database snapshot or from the perspective of slow download speeds?

**Comment by forfreeday** [comment]
If you are considering it from the perspective of slow download speeds, then the role of full node data is to maintain the complete state of the database. In that case, using lightweight node data may be more appropriate. However, if you are considering optimizing download speed, you need to take into account the dependencies between databases.

**Comment by moqi2011** [comment]
> Are you considering this issue from the perspective of optimizing the size of the database snapshot or from the perspective of slow download speeds?

The main purpose is to optimize download speed, since in my place I don't have direct access to the snapshot server.

**Comment by halibobo1205** [comment]
@moqi2011 Hi, what is your region, we can consider optimizing it later!
