### ISSUE TITLE
Is there a solution similar to EIP-4337 abstract accounts on the TRON network?

### ISSUE THREAD

**Issue by BillInUK** [tronprotocol/java-tron#5617]
Is there a solution similar to EIP-4337 abstract accounts on the TRON network? Currently, I would like to implement virtual accounts on TRON, at least requiring support for the functionality of contract wallets paying gas fees on behalf of users.

**Comment by ferdinand026** [comment]
@BillInUK Just to implement the interfaces specified by EIP-4337 on TRON. For the contract paying for the resources fee, I think an alternative way is to let the contract delegateing energy and bandwidth to users to pay for the transaction fee.

**Comment by BillInUK** [comment]
@ferdinand026 ok,i will try it

**Comment by vivian1912** [comment]
@BillInUK  Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
