### ISSUE TITLE
How can I check my node's status in real time?

### ISSUE THREAD

**Issue by CaCaBlocker** [tronprotocol/java-tron#5619]
### I installed my own node for testnet(nile) and I checked it was working well at first.
![image](https://github.com/tronprotocol/java-tron/assets/87882515/cfea98d2-170e-4364-a521-70f9373def85)

But I'm not sure how to check its status in real time.

**I would appreciate it if you let me know the best way. 😃**

Thanks in advance.

**Comment by laurenceja** [comment]
@CaCaBlocker Node metrics monitoring, please have a try: https://tronprotocol.github.io/documentation-en/using_javatron/metrics/

**Comment by vivian1912** [comment]
@CaCaBlocker Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
