### ISSUE TITLE
How to decompress tar.gz files of data snapshot (in ubuntu)?

### ISSUE THREAD

**Issue by CaCaBlocker** [tronprotocol/java-tron#5629]
**http://3.219.199.168/backup20231219/**

I downloaded all files from the above link.
Then to verify the integrity of the files, I run the following command.
```
md5sum -c FullNode_LevelDB.md5sum
```
Finally, I run this command to decompress.
```
tar -xzvf FullNode_LevelDB_00.tar.gz
```
But I got this issue at the end.
```
output-directory/database/trans/33897520.sst
output-directory/database/trans/40795874.sst

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by CarlChaoCarl** [comment]
try the following commands:
gunzip FullNode_LevelDB_00.tar.gz
tar -xf FullNode_LevelDB_00.tar

These two commands are intended to unzip a file named FullNode_LevelDB_00.tar.gz. 
Firstly, use the gunzip command to decompress the file (removing the ".gz" extension), 
and then use the tar command to extract (with the -xf option) the original file FullNode_LevelDB_00.tar.

**Comment by 317787106** [comment]
@CaCaBlocker There is some problem with your decompress procedure, it is not complete. 

1. First, download all the file, including FullNode_LevelDB_00.tar.gz ~ FullNode_LevelDB_07.tar.gz,  
2. Then use the command:  `cat FullNode_LevelDB* |tar -xzf - -C dir` to decompress all the file.

**Comment by CaCaBlocker** [comment]
> Try the following commands: gunzip FullNode_LevelDB_00.tar.gz tar -xf FullNode_LevelDB_00.tar
> 
> These two commands are intended to unzip a file named FullNode_LevelDB_00.tar.gz. Firstly, use the gunzip command to decompress the file (removing the ".gz" extension), and then use the tar command to extract (with the -xf option) the original file FullNode_LevelDB_00.tar.
> 
> @CaCaBlocker

@CarlChaoCarl 

I got this issue while I run `gunzip` command.

![image](https://github.com/tronprotocol/java-tron/assets/87882515/9f6dee38-ebd5-420f-a099-36a0474af44e)

**Comment by 317787106** [comment]
> > Try the following commands: gunzip FullNode_LevelDB_00.tar.gz tar -xf FullNode_LevelDB_00.tar
> > These two commands are intended to unzip a file named FullNode_LevelDB_00.tar.gz. Firstly, use the gunzip command to decompress the file (removing the ".gz" extension), and then use the tar command to extract (with the -xf option) the original file FullNode_LevelDB_00.tar.
> > @CaCaBlocker
> 
> @CarlChaoCarl
> 
> I got this issue while I run `gunzip` command.
> 
> ![image](https://private-user-images.githubusercontent.com/87882515/292092539-9f6dee38-ebd5-420f-a099-36a0474af44e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzQ3NjEsIm5iZiI6MTcwMzEzNDQ2MSwicGF0aCI6Ii84Nzg4MjUxNS8yOTIwOTI1MzktOWY2ZGVlMzgtZWJkNS00MjBmLWEwOTktMzZhMDQ3NGFmNDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA0NTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNzY4YjJjZjAyNmYyZjg4OWE3OWM2N2VlYmYyZWI2M2IxNWRiZDFmMzU0MmY1MDU5NGVlZmRmYWI2YjMzYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8dtSiLtjzN7LXfo2hQ687utsQDJQ-qYfVAg5tRw8SqU)

@CaCaBlocker Please try it as my advice. Don't use gzip.

**Comment by CaCaBlocker** [comment]
Hi, @317787106 

Finally, I failed. 😥

![image](https://github.com/tronprotocol/java-tron/assets/87882515/c7468fe2-6a3d-464f-87ca-e0792bf37597)
![image](https://github.com/tronprotocol/java-tron/assets/87882515/ad0575a1-312c-4bff-bc56-086b15b27be4)
![image](https://github.com/tronprotocol/java-tron/assets/87882515/8c8f93b3-1d25-4b25-9117-ab79305b776d)

**Comment by 317787106** [comment]
@CaCaBlocker Is your data decompressed ok? The data size 1824GB seems ok. readme.txt has been uploaded in snapshot website: http://3.219.199.168/backup20231219/.

**Comment by 317787106** [comment]
@CaCaBlocker There are 8 lines in file FullNode_LevelDB.md5sum. You can check whether every db's md5sum is same as listed.

**Comment by CaCaBlocker** [comment]
Hello, @317787106 
```
cat FullNode_LevelDB* |tar -xzf - -C dir
```

Could you explain about this command? Why can't I decompress one by one?
Thanks in advance. 😀
