### ISSUE TITLE
How tron prevents double spend problems

### ISSUE THREAD

**Issue by arvin-lau** [tronprotocol/java-tron#5630]
There is no concept of nonce in tron similar to that in eth, may I ask how tron prevents double spend? I asked the same question in discord, but didn't get a reply.

**Comment by ferdinand026** [comment]
@arvin-lau The transaction with the same transaction id will not be accepted by the TRON node. If we send the same transaction twice and the first sent transaction is executed successfully, the second transaction will be discarded because of the same transaction id found by the node.

**Comment by arvin-lau** [comment]
> @arvin-lau The transaction with the same transaction id will not be accepted by the TRON node. If we send the same transaction twice and the first sent transaction is executed successfully, the second transaction will be discarded because of the same transaction id found by the node.

thank you for you anwser, I have some other questions. Question 1: eth can determine the order in which transactions are executed based on nonce, does tron have a similar feature? Question 2: Does tron have a concept similar to gasPrice in eth?

**Comment by ferdinand026** [comment]
@arvin-lau Question 1, Tron does not have a similar feature. Question 2, Yes, Tron has energy price, but now the energy price   is 420sun, it is [the NO. 11 parameter](https://tronscan.io/#/sr/committee) of TRON network, the value can be modified through proposal voting. You can get the transaction fee information from [here](https://developers.tron.network/docs/tron-protocol-transaction#transaction-fee).

**Comment by arvin-lau** [comment]
> @arvin-lau Question 1, Tron does not have a similar feature. Question 2, Yes, Tron has energy price, but now the energy price is 420sun, it is [the NO. 11 parameter](https://tronscan.io/#/sr/committee) of TRON network, the value can be modified through proposal voting. You can get the transaction fee information from [here](https://developers.tron.network/docs/tron-protocol-transaction#transaction-fee). @arvin-lau 问题1，Tron没有类似的功能。问题2，是的，Tron有能源价格，但现在能源价格是420sun，这是NO。 TRON网络的11个参数，可以通过提案投票修改该值。您可以从这里获取交易费用信息。

I see. Thank you very much

**Comment by arvin-lau** [comment]
> @arvin-lau Question 1, Tron does not have a similar feature. Question 2, Yes, Tron has energy price, but now the energy price is 420sun, it is [the NO. 11 parameter](https://tronscan.io/#/sr/committee) of TRON network, the value can be modified through proposal voting. You can get the transaction fee information from [here](https://developers.tron.network/docs/tron-protocol-transaction#transaction-fee).

I see. Thank you very much

**Comment by vivian1912** [comment]
@arvin-lau Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
