### ISSUE TITLE
I have staked some native currency on my private tron network to gain energy, but when i do a smart contract interaction the energy is no utilised but the native currency gets burned?

### ISSUE THREAD

**Issue by SukiratWarring** [tronprotocol/java-tron#5634]
### Before transfer of token .
**/getaccountresource**
 ```
 {
    "freeNetLimit": 1500,
    "NetUsed": 2011,
    "NetLimit": 416245122,
    "TotalNetLimit": 43200000000,
    "TotalNetWeight": 20757,
    "tronPowerUsed": 18,
    "tronPowerLimit": 104249,
    "EnergyLimit": 25898510887,
    "TotalEnergyLimit": 90000000000,
    "TotalEnergyWeight": 360886
}
```
### After transfer of token
```
{
    "freeNetLimit": 1500,
    "NetUsed": 2352,
    "NetLimit": 416245122,
    "TotalNetLimit": 43200000000,
    "TotalNetWeight": 20757,
    "tronPowerUsed": 18,
    "tronPowerLimit": 104249,
    "EnergyLimit": 25898510887,
    "TotalEnergyLimit": 90000000000,
    "TotalEnergyWeight": 360886
}
```
### This i the transaction receipt for the token transfer by /gettransactioninfobyid
```
{
    "id": "b3d845bf232045fcabaf3e4375f7d6c277785f75a5519e5c1375870bdc98e886",
    "fee": 3781680,
    "blockNumber": 1601665,
    "blockTimeStamp": 1703048577000,
    "contractResult": [
        "0000000000000000000000000000000000000000000000000000000000000001"
    ],
    "contract_address": "41496c1057c93871e664253e456a72597d00161ceb",
    "receipt": {
        "energy_fee": 3781680,
        "energy_usage_total": 13506,
        "net_usage": 345,
        "result": "SUCCESS"
    },
    "log": [
        {
            "address": "496c1057c93871e664253e456a72597d00161ceb",
            "topics": [
                "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "00000000000000000000000065776280f01cdc51d0bc2b5a952a552d1c62bc2f",
                "000000000000000000000000a022a9d2f05938ce0cace863ad1c3c12c6840ca8"
            ],
            "data": "00000000000000000000000000000000000000000000000000000000000f4240"
        }
    ]
}
```
I DON'T SEE ENERGY BEING USED IN THE TRANSACTION EVENTHOUGH I HAVE "25898510887" ENERGY.

**Comment by lxcmyf** [comment]
@SukiratWarring 
Can you show the staking status of your account before and after the transfer? Just call **getaccount**.

**Comment by SukiratWarring** [comment]
i dont get the energy_usage field , just some native currency gets burned

**Comment by lxcmyf** [comment]
@SukiratWarring 
Please check if your smart contract allows energy consumption when sending transactions, or does it directly burn TRX?

**Comment by SukiratWarring** [comment]
@lxcmyf how to check this?

**Comment by lxcmyf** [comment]
> @lxcmyf how to check this? i donot see any energy consumption,straight away the native currency is burned **This is my response for my /getaccount api**
> 
> ```
> {
>     "account_name": "TestD",
>     "address": "TBcBVYnotCt6CtRyBiwnaALjMyoypXH8Wj",
>     "balance": 999934031076964,
>     "net_usage": 247,
>     "latest_opration_time": 1702994064000,
>     "free_net_usage": 1403,
>     "latest_consume_time": 1702994064000,
>     "latest_consume_free_time": 1702991967000,
>     "net_window_size": 28271000,
>     "net_window_optimized": true,
>     "account_resource": {
>         "latest_consume_time_for_energy": 1702993065000,
>         "energy_window_size": 28800000,
>         "energy_window_optimized": true
>     },
>     "frozenV2": [
>         {
>             "amount": 20000000000
>         },
>         {
>             "type": "ENERGY",
>             "amount": 20400000000
>         },
>         {
>             "type": "TRON_POWER"
>         }
>     ]
> }
> ```

@SukiratWarring 
Is this the status before the transfer or after the transfer? If possible, provide both of these states.

**Comment by SukiratWarring** [comment]
@lxcmyf **consumeUserResourcePercentage** for the contract is **100**, and the above object is the status of the account just after the token transfer
do i need to change somthing in my chain parameters list?
```
{
  "chainParameter": [
    {
      "key": "getMaintenanceTimeInterval",
      "value": 900000
    },
    {
      "key": "getAccountUpgradeCost",
      "value": 9999000000
    },
    {
      "key": "getCreateAccountFee",
      "value": 100000
    },
    {
      "key": "getTransactionFee",
      "value": 1000
    },
    {
      "key": "getAssetIssueFee",
      "value": 1024000000
    },
    {
      "key": "getWitnessPayPerBlock",
      "value": 16000000
    },
    {
      "key": "getWitnessStandbyAllowance",
      "value": 115200000000
    },
    {
      "key": "getCreateNewAccountFeeInSystemContract",
      "value": 1000000
    },
    {
      "key": "getCreateNewAccountBandwidthRate",
      "value": 1
    },
    {
      "key": "getAllowCreationOfContracts",
      "value": 1
    },
    {
      "key": "getRemoveThePowerOfTheGr",
      "value": -1
    },
    {
      "key": "getEnergyFee",
      "value": 1
    },
    {
      "key": "getExchangeCreateFee",
      "value": 1024000000
    },
    {
      "key": "getMaxCpuTimeOfOneTx",
      "value": 80
    },
    {
      "key": "getAllowUpdateAccountName"
    },
    {
      "key": "getAllowSameTokenName",
      "value": 1
    },
    {
      "key": "getAllowDelegateResource",
      "value": 1
    },
    {
      "key": "getTotalEnergyLimit",
      "value": 90000000000
    },
    {
      "key": "getAllowTvmTransferTrc10",
      "value": 1
    },
    {
      "key": "getTotalEnergyCurrentLimit",
      "value": 90000000000
    },
    {
      "key": "getAllowMultiSign",
      "value": 1
    },
    {
      "key": "getAllowAdaptiveEnergy"
    },
    {
      "key": "getTotalEnergyTargetLimit",
      "value": 6250000
    },
    {
      "key": "getTotalEnergyAverageUsage"
    },
    {
      "key": "getUpdateAccountPermissionFee",
      "value": 100000000
    },
    {
      "key": "getMultiSignFee",
      "value": 1000000
    },
    {
      "key": "getAllowAccountStateRoot"
    },
    {
      "key": "getAllowProtoFilterNum"
    },
    {
      "key": "getAllowTvmConstantinople",
      "value": 1
    },
    {
      "key": "getAllowTvmSolidity059",
      "value": 1
    },
    {
      "key": "getAllowTvmIstanbul",
      "value": 1
    },
    {
      "key": "getAllowShieldedTRC20Transaction",
      "value": 1
    },
    {
      "key": "getForbidTransferToContract"
    },
    {
      "key": "getAdaptiveResourceLimitTargetRatio",
      "value": 10
    },
    {
      "key": "getAdaptiveResourceLimitMultiplier",
      "value": 1000
    },
    {
      "key": "getChangeDelegation",
      "value": 1
    },
    {
      "key": "getWitness127PayPerBlock",
      "value": 160000000
    },
    {
      "key": "getAllowMarketTransaction"
    },
    {
      "key": "getMarketSellFee"
    },
    {
      "key": "getMarketCancelFee"
    },
    {
      "key": "getAllowPBFT"
    },
    {
      "key": "getAllowTransactionFeePool"
    },
    {
      "key": "getMaxFeeLimit",
      "value": 10000000000
    },
    {
      "key": "getAllowOptimizeBlackHole",
      "value": 1
    },
    {
      "key": "getAllowNewResourceModel"
    },
    {
      "key": "getAllowTvmFreeze",
      "value": 1
    },
    {
      "key": "getAllowTvmVote"
    },
    {
      "key": "getAllowTvmLondon",
      "value": 1
    },
    {
      "key": "getAllowTvmCompatibleEvm"
    },
    {
      "key": "getAllowAccountAssetOptimization"
    },
    {
      "key": "getFreeNetLimit",
      "value": 1500
    },
    {
      "key": "getTotalNetLimit",
      "value": 43200000000
    },
    {
      "key": "getAllowHigherLimitForMaxCpuTimeOfOneTx"
    },
    {
      "key": "getAllowAssetOptimization"
    },
    {
      "key": "getAllowNewReward"
    },
    {
      "key": "getMemoFee"
    },
    {
      "key": "getAllowDelegateOptimization"
    },
    {
      "key": "getUnfreezeDelayDays",
      "value": 1
    },
    {
      "key": "getAllowOptimizedReturnValueOfChainId"
    },
    {
      "key": "getAllowDynamicEnergy",
      "value": 1
    },
    {
      "key": "getDynamicEnergyThreshold",
      "value": 3000000000
    },
    {
      "key": "getDynamicEnergyIncreaseFactor",
      "value": 2000
    },
    {
      "key": "getDynamicEnergyMaxFactor",
      "value": 12000
    },
    {
      "key": "getAllowTvmShangHai",
      "value": 1
    },
    {
      "key": "getAllowCancelAllUnfreezeV2",
      "value": 1
    },
    {
      "key": "getMaxDelegateLockPeriod",
      "value": 86400
    }
  ]
}
```

**Comment by lxcmyf** [comment]
@SukiratWarring 
Please check the configuration item **enery.limit.block.num** in the **config.conf** file and set `enery.limit.block.num = 0`. The height of the private chain block you have built is relatively low, so it will be affected.

**Comment by SukiratWarring** [comment]
@lxcmyf 
### This is my SR Config
```
net {
   type = mainnet
  # type = testnet
}

storage {
  # Directory for storing persistent data

  db.version = 2,
  db.engine = "LEVELDB",
  db.directory = "database",
  index.directory = "index",

  # You can custom these 14 databases' configs:

  # account, account-index, asset-issue, block, block-index,
  # block_KDB, peers, properties, recent-block, trans,
  # utxo, votes, witness, witness_schedule.

  # Otherwise, db configs will remain defualt and data will be stored in
  # the path of "output-directory" or which is set by "-d" ("--output-directory").

  # Attention: name is a required field that must be set !!!
  properties = [
    //    {
    //      name = "account",
    //      path = "storage_directory_test",
    //      createIfMissing = true,
    //      paranoidChecks = true,
    //      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
    //    {
    //      name = "account-index",
    //      path = "storage_directory_test",
    //      createIfMissing = true,
    //      paranoidChecks = true,
    //      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
  ]

}

# this part of config is used to node discovery.
node.discovery = {
  enable = true  # you should set this entry value with true if you want your node can be discovered by other node.
  persist = true  # this entry is used to determined to whether storing the peers in the database or not.
  bind.ip = "0.0.0.0"
  external.ip = 13.201.104.132
}

# this part of config is used to set backup node for witness service.
node.backup {
  port = 10001
  priority = 8
  members = [
  ]
}
#Enabling JSON-RPC service of a node
node.jsonrpc {
httpFullNodeEnable = true
httpFullNodePort = 50545
httpSolidityEnable = true
httpSolidityPort = 50555
}

node {
  # trust node for solidity node
  # trustNode = "ip:port"
  trustNode = "127.0.0.1:50051"

  # expose extension api to public or not
  walletExtensionApi = true

  listen.port = 16666

  connection.timeout = 2

  tcpNettyWorkThreadNum = 0

  udpNettyWorkThreadNum = 1

  # Number of validate sign thread, default availableProcessors / 2
  # validateSignThreadNum = 16

  maxActiveNodes = 30

  maxActiveNodesWithSameIp = 2

  minParticipationRate = 0

  # check the peer data transfer ,disconnect factor
  disconnectNumberFactor = 0.4
  maxConnectNumberFactor = 0.8
  receiveTcpMinDataLength = 2048
  isOpenFullTcpDisconnect = true

  p2p {
    version = 1 # 11111: mainnet; 20180622: testnet; you can set other number when you deploy one private net, but the node must have the same number in some private net. 
  }

  active = [
    # Active establish connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]

  passive = [
    # Passive accept connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]

  http {
    fullNodePort = 16667
    solidityPort = 16668
  }

  rpc {
    port = 16669

    # Number of gRPC thread, default availableProcessors / 2
    # thread = 16

    # The maximum number of concurrent calls permitted for each incoming connection
    # maxConcurrentCallsPerConnection =

    # The HTTP/2 flow control window, default 1MB
    # flowControlWindow =

    # Connection being idle for longer than which will be gracefully terminated
    maxConnectionIdleInMillis = 60000

    # Connection lasting longer than which will be gracefully terminated
    # maxConnectionAgeInMillis =

    # The maximum message size allowed to be received on the server, default 4MB
    # maxMessageSize =

    # The maximum size of header list allowed to be received, default 8192
    # maxHeaderListSize =

    # Transactions can only be broadcast if the number of effective connections is reached.
    minEffectiveConnection = 0
  }

  # Whether to enable the node detection function, default false
  # nodeDetectEnable = false

  # use your ipv6 address for node discovery and tcp connection, default false
  # enableIpv6 = false

  # if your node's highest block num is below than all your pees', try to acquire new connection. default false
  # effectiveCheckEnable = false

  # Dynamic loading configuration function, disabled by default
  # dynamicConfig = {
    # enable = false
    # Configuration file change check interval, default is 600 seconds
    # checkInterval = 600
  # }

  dns {
    # dns urls to get nodes, url format tree://{pubkey}@{domain}, default empty
    treeUrls = [
      #"tree://APFGGTFOBVE2ZNAB3CSMNNX6RRK3ODIRLP2AA5U4YFAA6MSYZUYTQ@nodes1.example.org",
    ]
  }
}



seed.node = {
  # List of the seed nodes. This is used to enable the node can connect when join one net at first.
  # If you deploy one private net, you must add some "ip:port" here for other node connecting.
  # Seed nodes are stable full nodes, and the first SuperNode must be inclued in.
  # example:
  # ip.list = [
  #   "ip:port",
  #   "ip:port"
  # ]
  ip.list = [
  ]
}

genesis.block = {
  # Reserve balance
  assets = [
    {
      accountName = "LBM"
      accountType = "AssetIssue"
      address = "TR4Bqq9zhBQvi8bKFfD9S2oePptvTxZsM5"
      balance = "10000000000"
    },
    {
      accountName = "POX"
      accountType = "AssetIssue"
      address = "TR4Bqq9zhBQvi8bKFfD9S2oePptvTxZsM5"
      balance = "10000000000"
    },
    {
      accountName = "Blackhole"
      accountType = "AssetIssue"
      address = "TUKZpDNnzAufcJQjmq9Eo2gQs8wTSKDfQY"
      balance = "-10000000000"
    },
    {
      accountName = "TestA"
      accountType = "AssetIssue"
      address = "TKDiGS7ZpAj92UcYQCbASjTBYzCYK6CQsS"
      balance = "10000000000"
    },
    {
      accountName = "TestB"
      accountType = "AssetIssue"
      address = "TJVb3LEZtxaLfZHvdutj8M2zjL8xEgdPGM"
      balance = "10000000000"
    },
    {
      accountName = "TestC"
      accountType = "AssetIssue"
      address = "TUPxRRwjzPtLpbHYY21CLCCoPZ4eaynKm5"
      balance = "10000000000"
    },
    {
      accountName = "TestD"
      accountType = "AssetIssue"
      address = "TBcBVYnotCt6CtRyBiwnaALjMyoypXH8Wj"
      balance = "10000000000"
    },
    {
      accountName = "TestE"
      accountType = "AssetIssue"
      address = "TE9gsbPsVSzbHhQP3DF3wa1n3ANq1SgiSC"
      balance = "10000000000"
    }
  ]

  witnesses = [
    {
      address: TKYpb1JwBuyecNR2bxYhW96Sg3kATh3DCr,
      url = "http://polluxstudio.com",
      voteCount = 10000
    }
  ]

  timestamp = "0" #2017-8-26 12:00:00

  parentHash = "957dc2d350daecc7bb6a38f3938ebde0a0c1cedafe15f0edae4256a2907449f6"
}

localwitness = [
  540c0dc73de95e31344d65c09903948276a85671c57b552eb4904a3630a511da  # you must enable this value and the witness address are match.
]

#localwitnesskeystore = [
#  "src/main/resources/localwitnesskeystore.json"  # if you do not set the localwitness above, you must set this value.Otherwise,your SuperNode can not produce the block. 
#]

block = {
  needSyncCheck = false # first node : false, other : true
  maintenanceTimeInterval = 900000 // 1 day: 86400000(ms), 6 hours: 21600000(ms),15 mins: 900000
  proposalExpireTime = 900000 // 15 mins: 900000
}


vm = {
  supportConstant = true
  minTimeRatio = 0.0
  maxTimeRatio = 5.0
}

committee = {
  allowCreationOfContracts = 1  //mainnet:0 (reset by committee),test:1
}

event.subscribe = {
  native = {
    useNativeQueue = true // if true, use native message queue, else use event plugin.
    bindport = 5555 // bind port
    sendqueuelength = 1000 //max length of send queue
  }

  path = "" // absolute path of plugin
  server = "" // target server address to receive event triggers
  dbconfig = "" // dbname|username|password
  contractParse = true,
  topics = [
    {
      triggerName = "block" // block trigger, the value can't be modified
      enable = true
      topic = "block" // plugin topic, the value could be modified
    },
    {
      triggerName = "transaction"
      enable = true
      topic = "transaction"
    },
    {
      triggerName = "contractevent"
      enable = true
      topic = "contractevent"
    },
    {
      triggerName = "contractlog"
      enable = true
      topic = "contractlog"
    },
    {
      triggerName = "solidity" // solidity block event trigger, the value can't be modified
      enable = true            // the default value is true
      topic = "solidity"
    }
  ]

  filter = {
    fromblock = "0" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
    toblock = "latest" // the value could be "", "latest" or a specified block number as end of the queried range
    contractAddress = []

    contractTopic = []
  }
}
```

**Comment by lxcmyf** [comment]
> enery.limit.block.num = 0

@SukiratWarring 
Yes, add `energy. limit. block. num=0` to your configuration file and try again.

**Comment by lxcmyf** [comment]
@SukiratWarring 
Did you change this value? Look at the issue you sent before, it should be 280.
<img width="869" alt="image" src="https://github.com/tronprotocol/java-tron/assets/29877167/80af5734-a6ca-409b-a297-7e66d6c3837a">

**Comment by SukiratWarring** [comment]
@lxcmyf yes i have changed it to 1

**Comment by charil10** [comment]
@lxcmyf we are stucked into same issue and the above methods you mentioned is not working for us. 
is there any other way to do that?? we have changed the params through proposal as well.but still no changes.
also do let me know the File in the java-tron where the energy is deducted or calculated for deduction of smart contract interaction

**Comment by lxcmyf** [comment]
> > enery.limit.block.num = 0
> 
> @SukiratWarring Yes, add `energy.limit.block.num = 0` to your configuration file and try again.

@charil10 
Have you tried this too? Still not working?

**Comment by charil10** [comment]
`net {
    type = mainnet
  #  type = testnet
}

storage {
  # Directory for storing persistent data

  db.version = 2,
  db.engine = "LEVELDB",
  db.directory = "database",
  index.directory = "index",

  # You can custom these 14 databases' configs:

  # account, account-index, asset-issue, block, block-index,
  # block_KDB, peers, properties, recent-block, trans,
  # utxo, votes, witness, witness_schedule.

  # Otherwise, db configs will remain defualt and data will be stored in
  # the path of "output-directory" or which is set by "-d" ("--output-directory").

  # Attention: name is a required field that must be set !!!
  properties = [
    //    {
    //      name = "account",
    //      path = "storage_directory_test",
    //      createIfMissing = true,
    //      paranoidChecks = true,
    //      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
    //    {
    //      name = "account-index",
    //      path = "storage_directory_test",
    //      createIfMissing = true,
    //      paranoidChecks = true,
    //      verifyChecksums = true,
    //      compressionType = 1,        // compressed with snappy
    //      blockSize = 4096,           // 4  KB =         4 * 1024 B
    //      writeBufferSize = 10485760, // 10 MB = 10 * 1024 * 1024 B
    //      cacheSize = 10485760,       // 10 MB = 10 * 1024 * 1024 B
    //      maxOpenFiles = 100
    //    },
  ]

}

# this part of config is used to node discovery.
node.discovery = {
  enable = true  # you should set this entry value with true if you want your node can be discovered by other node.
  persist = true  # this entry is used to determined to whether storing the peers in the database or not.
  bind.ip = "0.0.0.0"
  external.ip = 3.109.94.186
}

# this part of config is used to set backup node for witness service.
node.backup {
  port = 10001
  priority = 8
  members = [
  ]
}

#Enabling JSON-RPC service of a node

node.jsonrpc {
httpFullNodeEnable = true
httpFullNodePort = 50545
httpSolidityEnable = true
httpSolidityPort = 50555
}

node {
  # trust node for solidity node
  # trustNode = "ip:port"
  trustNode = "127.0.0.1:50051"

  # expose extension api to public or not
  walletExtensionApi = true

  listen.port = 16665

  connection.timeout = 2

  tcpNettyWorkThreadNum = 0

  udpNettyWorkThreadNum = 1

  # Number of validate sign thread, default availableProcessors / 2
  # validateSignThreadNum = 16

  maxActiveNodes = 30

  maxActiveNodesWithSameIp = 2

  minParticipationRate = 0

  # check the peer data transfer ,disconnect factor
  disconnectNumberFactor = 0.4
  maxConnectNumberFactor = 0.8
  receiveTcpMinDataLength = 2048
  isOpenFullTcpDisconnect = true

  p2p {
    version = 1 # 11111: mainnet; 20180622: testnet; you can set other number when you deploy one private net, but the node must have the same number in some private net. 
  }

  active = [
    # Active establish connection in any case
    # Sample entries:
    # "ip:port",
    "3.109.94.186:16666"
  ]

  passive = [
    # Passive accept connection in any case
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]

  http {
    fullNodePort = 16667
    solidityPort = 16668
  }

  rpc {
    port = 16669

    # Number of gRPC thread, default availableProcessors / 2
    # thread = 16

    # The maximum number of concurrent calls permitted for each incoming connection
    # maxConcurrentCallsPerConnection =

    # The HTTP/2 flow control window, default 1MB
    # flowControlWindow =

    # Connection being idle for longer than which will be gracefully terminated
    maxConnectionIdleInMillis = 60000

    # Connection lasting longer than which will be gracefully terminated
    # maxConnectionAgeInMillis =

    # The maximum message size allowed to be received on the server, default 4MB
    # maxMessageSize =

    # The maximum size of header list allowed to be received, default 8192
    # maxHeaderListSize =

    # Transactions can only be broadcast if the number of effective connections is reached.
    minEffectiveConnection = 0
  }

  # Whether to enable the node detection function, default false
  # nodeDetectEnable = false

  # use your ipv6 address for node discovery and tcp connection, default false
  # enableIpv6 = false

  # if your node's highest block num is below than all your pees', try to acquire new connection. default false
  # effectiveCheckEnable = false

  # Dynamic loading configuration function, disabled by default
  # dynamicConfig = {
    # enable = false
    # Configuration file change check interval, default is 600 seconds
    # checkInterval = 600
  # }

  dns {
    # dns urls to get nodes, url format tree://{pubkey}@{domain}, default empty
    treeUrls = [
      #"tree://APFGGTFOBVE2ZNAB3CSMNNX6RRK3ODIRLP2AA5U4YFAA6MSYZUYTQ@nodes1.example.org",
    ]
  }
}



seed.node = {
  # List of the seed nodes. This is used to enable the node can connect when join one net at first.
  # If you deploy one private net, you must add some "ip:port" here for other node connecting.
  # Seed nodes are stable full nodes, and the first SuperNode must be inclued in.
  # example:
  # ip.list = [
  #   "ip:port",
  #   "ip:port"
  # ]
  ip.list = [ "3.109.94.186:16666"
,"3.111.51.50:16666"  ]
}

genesis.block = {
  # Reserve balance
  assets = [
    {
      accountName = "LBM"
      accountType = "AssetIssue"
      address = "TR4Bqq9zhBQvi8bKFfD9S2oePptvTxZsM5"
      balance = "95000000000000000"
    },
    {
      accountName = "POX"
      accountType = "AssetIssue"
      address = "TR4Bqq9zhBQvi8bKFfD9S2oePptvTxZsM5"
      balance = "5000000000000000"
    },
    {
      accountName = "Blackhole"
      accountType = "AssetIssue"
      address = "TUKZpDNnzAufcJQjmq9Eo2gQs8wTSKDfQY"
      balance = "-9223372036854775808"
    },
    {
      accountName = "TestA"
      accountType = "AssetIssue"
      address = "TKDiGS7ZpAj92UcYQCbASjTBYzCYK6CQsS"
      balance = "1000000000000000"
    },
    {
      accountName = "TestB"
      accountType = "AssetIssue"
      address = "TJVb3LEZtxaLfZHvdutj8M2zjL8xEgdPGM"
      balance = "1000000000000000"
    },
    {
      accountName = "TestC"
      accountType = "AssetIssue"
      address = "TUPxRRwjzPtLpbHYY21CLCCoPZ4eaynKm5"
      balance = "1000000000000000"
    },
    {
      accountName = "TestD"
      accountType = "AssetIssue"
      address = "TBcBVYnotCt6CtRyBiwnaALjMyoypXH8Wj"
      balance = "1000000000000000"
    },
    {
      accountName = "TestE"
      accountType = "AssetIssue"
      address = "TE9gsbPsVSzbHhQP3DF3wa1n3ANq1SgiSC"
      balance = "1000000000000000"
    }
  ]

  witnesses = [
    {
      address: TKYpb1JwBuyecNR2bxYhW96Sg3kATh3DCr,
      url = "http://polluxstudio.com",
      voteCount = 10000
    }
  ]

  timestamp = "0" #2017-8-26 12:00:00

  parentHash = "957dc2d350daecc7bb6a38f3938ebde0a0c1cedafe15f0edae4256a2907449f6"
}

localwitness = []
#da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0  # you must enable this value and the witness address are match.

#localwitnesskeystore = [
#  "src/main/resources/localwitnesskeystore.json"  # if you do not set the localwitness above, you must set this value.Otherwise,your SuperNode can not produce the block. 
#]

block = {
  needSyncCheck = true # first node : false, other : true
  maintenanceTimeInterval = 900000 // 1 day: 86400000(ms), 6 hours: 21600000(ms),15 mins : 900000
  proposalExpireTime=900000//15 mins 
}


vm = {
  supportConstant = true
  minTimeRatio = 0.0
  maxTimeRatio = 5.0
}

committee = {
  allowCreationOfContracts = 1  //mainnet:0 (reset by committee),test:1
}

event.subscribe = {
  native = {
    useNativeQueue = true // if true, use native message queue, else use event plugin.
    bindport = 5555 // bind port
    sendqueuelength = 1000 //max length of send queue
  }

  path = "" // absolute path of plugin
  server = "" // target server address to receive event triggers
  dbconfig = "" // dbname|username|password
  contractParse = true,
  topics = [
    {
      triggerName = "block" // block trigger, the value can't be modified
      enable = true
      topic = "block" // plugin topic, the value could be modified
#	 solidified = true    
},
    {
      triggerName = "transaction"
      enable = true
      topic = "transaction"
#	 solidified = true
	    ethCompatible = true
    },
    {
      triggerName = "contractevent"
      enable = true
      topic = "contractevent"
    },
    {
      triggerName = "contractlog"
      enable = true
      topic = "contractlog"
    },
    {
      triggerName = "solidity" // solidity block event trigger, the value can't be modified
      enable = true            // the default value is true
      topic = "solidity"
    },
{
          triggerName = "solidityevent"
          enable = true
          topic = "solidityevent"
        },
        {
          triggerName = "soliditylog"
          enable = true
          topic = "soliditylog"
          redundancy = true // if set true, solidityevent will also be regarded as soliditylog
        }
  ]

  filter = {
    fromblock = "earliest" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
    toblock = "latest" // the value could be "", "latest" or a specified block number as end of the queried range
    contractAddress = [""]

    contractTopic = [""]
  }
}`


@lxcmyf  this is my config file. can you please tell me where should I mention this energy.limit.block.num = 0. also Im only getting events of transaction topic . why im not getting other events using ZMQ I have enable the value but still getting only transaction event.

**Comment by SukiratWarring** [comment]
@lxcmyf this is my config file. can you please tell me where should I mention this energy.limit.block.num = 0. also Im only getting events of transaction topic .

**Comment by lxcmyf** [comment]
@charil10 @SukiratWarring 
Simply add this setting at the tail end.
`filter = {
    fromblock = "earliest" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
    toblock = "latest" // the value could be "", "latest" or a specified block number as end of the queried range
    contractAddress = [""]

    contractTopic = [""]
  }
}
enery.limit.block.num = 0
`

**Comment by SukiratWarring** [comment]
@lxcmyf we tried this but this ,it is not working!

**Comment by lxcmyf** [comment]
@SukiratWarring 
<img width="924" alt="image" src="https://github.com/tronprotocol/java-tron/assets/29877167/6408583f-56c4-4dc7-8606-3b2829d481ff">
Please note that the code is for **enery**, not **energy**.

**Comment by SukiratWarring** [comment]
@lxcmyf  ohk i will change it in the config!

**Comment by SukiratWarring** [comment]
@lxcmyf  thanks broski it worked , is there a way i can connect with you, like on telegram or something?

**Comment by lxcmyf** [comment]
Just post the issue on GitHub, and we will have dedicated personnel to follow up in a timely manner.

**Comment by YuMenGuan** [comment]
> @SukiratWarring Please check if your smart contract allows energy consumption when sending transactions, or does it directly burn TRX?



> @SukiratWarring Please check if your smart contract allows energy consumption when sending transactions, or does it directly burn TRX?

@lxcmyf which kind of contract or operation in contract will burn trx firstly when consume energy, or the order of energy consumption way (energy from staking and energy from burning trx) can be configured by contract author?I have always believed that when a contract need consume  energy, it will consume staked energy firstly, if not enough, then going to burn trx.
