### ISSUE TITLE
i want the Energy unit price to be 0.0000001 which is not possible cause the trx private chain has only 6 decimal places , any solution to achieve this?

### ISSUE THREAD

**Issue by SukiratWarring** [tronprotocol/java-tron#5635]
->Will i be able to achieve it if i increase the native currency precision to 7 ?

**Comment by hitlxy** [comment]
@SukiratWarring  Of cource, If the decimals of the native token is 7, the energy unit price can be set to 0.0000001. #5628

**Comment by SukiratWarring** [comment]
I tried it but it doesnot work.
