### ISSUE TITLE
How long does it take to finish synchronization?

### ISSUE THREAD

**Issue by CaCaBlocker** [tronprotocol/java-tron#5640]
I downloaded the latest data snapshot, and started a tron node with synchronization.

```
nohup java -Xms9G -Xmx9G -XX:ReservedCodeCacheSize=256m \
             -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m \
             -XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails \
             -XX:+PrintGCDateStamps  -Xloggc:gc.log \
             -XX:+UseConcMarkSweepGC -XX:NewRatio=2 \
             -XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled \
             -XX:+HeapDumpOnOutOfMemoryError \
             -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=70 \
             -jar FullNode.jar --es -c main_net_config.conf >> start.log 2>&1 &
```

![image](https://github.com/tronprotocol/java-tron/assets/87882515/281e8020-29ee-458a-8420-e3785084a067)

_After 2 days, I noticed that over 5,000,000 blocks were confirmed, but I doubt how long it will take to finish the synchronization.
Currently, over 57,600,000 blocks are already confirmed, and if I follow this, I guess it will take over 20 days._

**Is there any way to boost? Or it is normal speed?**
Thanks in advance.

**Comment by halibobo1205** [comment]
you can try these settings in [main_net_config.conf#L25](https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf#L25). Normally, a day's blocks can be synchronized in 2 hours. BTW,  You can also choose to download the latest day's snapshot from [main-net-database-snapshots](https://developers.tron.network/docs/main-net-database-snapshots)
<img width="808" alt="image" src="https://github.com/tronprotocol/java-tron/assets/82020050/bedf1607-ed27-4cc4-970c-e0e95e4b9f90">

**Comment by CaCaBlocker** [comment]
Hi, @halibobo1205 

I already downloaded the latest snapshot and unzip them in a day. Then I started my tron node. I expected it would boost the speed, but I don't know now.

**Comment by CaCaBlocker** [comment]
Hello, @halibobo1205

can I resume the sync after I stop the current sync and reset the configuration?

**Comment by CaCaBlocker** [comment]
### This is what I did next for my tron full node.

1. I stopped the current process with the `kill PID` command.
2. Then I enabled `maxOpenFiles` in the `main_net_config.conf` file.

![image](https://github.com/tronprotocol/java-tron/assets/87882515/254f7d68-f003-4786-a623-c3238afb1bae)

3. Finally, I resumed a tron node and it was working well.

![image](https://github.com/tronprotocol/java-tron/assets/87882515/6df5cf7e-3fb1-4d20-a43f-62f2d35a7c5d)


**As a result of calculating the speed, it's about `708 blocks/min`.
To conclude, I noticed that I can finish sync for over 50 days.**

_This is awful for me. 😰_

**Comment by halibobo1205** [comment]
@CaCaBlocker, there's no faster way for now.

**Comment by CaCaBlocker** [comment]
Hey, @halibobo1205.

**I was interested in setting up my full node on Tron to receive real-time transaction events.** Are there any alternative methods to achieve this?

https://developers.tron.network/docs/use-java-trons-built-in-message-queue-for-event-subscription

**Comment by CaCaBlocker** [comment]
Hi, @ss3344520 
Can you help me?

**Comment by moqi2011** [comment]
If you only want to listen to future real-time events, then using a LiteFullNode seems to be a better choice. LiteNode does not require special configuration files, you only need to download the LiteFullNode database. [Lite Fullnode data snapshot](https://developers.tron.network/docs/main-net-database-snapshots#lite-fullnode-data-snapshot)

**Comment by CaCaBlocker** [comment]
Hello, @moqi2011 

Thank you for getting to me. To be frank, I'm working on creating a deposit system on the Tron network, and the Tron node aims to quickly confirm transactions in real-time. Essentially, we plan to examine confirmed transactions with our main wallet as the destination address, verify the transfer value, fee, and status, and then promptly store this information in our database. I'm interested in determining whether a light node would be appropriate for our needs.

**Comment by moqi2011** [comment]
@CaCaBlocker  LiteFullNode can implement these functions. It only removes the block data and transaction data before the snapshot creation time node. All other functions are available.

**Comment by CaCaBlocker** [comment]
Hi, @moqi2011 

First things first, I'd appreciate your help.
Now, I can receive real-time events for blocks in my litefullnode.

But I have another problem parsing transaction details.

Despite setting `openHistoryQueryWhenLiteFN = true` in the config file, I can't call some APIs.

![image](https://github.com/tronprotocol/java-tron/assets/87882515/cb88f864-ea9d-428e-a0ea-ce95afd7f7ae)

Hope your help now.

**Comment by moqi2011** [comment]
@CaCaBlocker Try using the get method: /walletsolidity/gettransactioninfobyid?value=7deb4a226ad87642da29422ec5a390a0e38f834d8f0c0db3ca0582bdbd7e2b15

**Comment by CaCaBlocker** [comment]
> @CaCaBlocker Try using the get method: /walletsolidity/gettransactioninfobyid?value=7deb4a226ad87642da29422ec5a390a0e38f834d8f0c0db3ca0582bdbd7e2b15

```
{
"servlet":"org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-9771c71",
"message":"Not Found",
"url":"/walletsolidity/gettransactionbyid",
"status":"404"
}
```

**Comment by moqi2011** [comment]
fullNodeApi and solidityApi use different ports.
```conf
http {
    fullNodeEnable = true
    fullNodePort = 8090
    solidityEnable = true
    solidityPort = 8091
  }
```

**Comment by vivian1912** [comment]
@CaCaBlocker  Thanks for your contribution to Java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.

**Comment by CaCaBlocker** [comment]
Hello, @moqi2011 
Could you help me out?
https://github.com/tronprotocol/tronweb/issues/477
