### ISSUE TITLE
Tron Private Chain ENERGY Issue

### ISSUE THREAD

**Issue by charil10** [tronprotocol/java-tron#5641]
I am  running tron private chain when I do smart contract transaction like trc20 token transfer from 1 wallet to other wallet. there should be energy deduct from my energy balance but instead of consuming my available energy its using my balance to burn tron and consume energy from there. I have staked multiple times to retrive energy but still its not even use energy,. whats the solution of this?

**Comment by lxcmyf** [comment]
@charil10 
Please refer to https://github.com/tronprotocol/java-tron/issues/5634.

**Comment by lxcmyf** [comment]
@charil10 
So please provide your account status before and after the transfer, and call **getaccount**.
