### ISSUE TITLE
APR percentage by SR on tronscan .

### ISSUE THREAD

**Issue by SukiratWarring** [tronprotocol/java-tron#5642]
**How is the APR calculated ?**

I am aware that for a VOTER this is how the Rewards are calculated but as you can see the reward depends upon the votes given by the voter.**So how an APR be calcualted without taking in account the no of votes?**

``` Reward = 4,608,000 * votes obtained by the SR or SRP / the total votes of all the SR and SRP  * 80% *（ votes /  votes obtained by the SR or SRP ） =  4,608,000 * votes / the total votes of all the SR and SRP  * 80% ```
    
![image](https://github.com/tronprotocol/java-tron/assets/89912502/9f26c484-11dc-4e20-b3e8-78e75d3f3c9d)

In the above  case we can see we multiply by 10,000,000

![Screenshot from 2023-12-27 17-52-05](https://github.com/tronprotocol/java-tron/assets/89912502/0755aa83-8577-43c3-a3f2-2f03ff3a4fe6)

**Comment by laurenceja** [comment]
@SukiratWarring The reward calculation formula on TRON is as written in the document, so you can roughly calculate the rate based on the formula. Please attention, the block production rewards and voting rewards of mainnet and testnet may be different, but the mechanisms are the same.

**Comment by SukiratWarring** [comment]
@laurenceja i have mentioned the formula above , i just want to know that it has a dependancy of vote count and it will differ for 2 different user who are voting for 1 and 100,000 Tronpower,so how is tron justifying the written APR fro both the user?

**Comment by laurenceja** [comment]
@SukiratWarring This is APY, only a rate, so we can assume the voting number, then to compute the reward rate.

**Comment by abn2357** [comment]
> @laurenceja i have mentioned the formula above , i just want to know that it has a dependancy of vote count and it will differ for 2 different user who are voting for 1 and 100,000 Tronpower,so how is tron justifying the written APR fro both the user?

@SukiratWarring My understanding is that APR is calculated for SR not for a voter
