### ISSUE TITLE
I WANT TO DECREASE Energy Usage In smart contract Transaction

### ISSUE THREAD

**Issue by charil10** [tronprotocol/java-tron#5644]
I am working on tron private chain where I  faced a challenge where energy usage on Smart contract transaction is high. so I need to decreased the energy used in smart contract transaction where i find 2 solutions that is:
1- currently its working on same as tron so decimals is 6 , We thought that if we can increase the decimal to 10 or increase more then it will eventually decrease the evergy. for this We have changed the TRX_PRECISION variable TRX_PRECISION = 10000000_000L; this but I haven't see any difference. Will it work? if it work then how can I see the difference??
2- In code I will change the Energy deduction function and set a threshold where I can manage the limit using but Im unable to find the function where the overall energy is calculated where I can implement my custom condition , so give me the exact path and name of the function which results the energy to be consume and after that it deduct the energy from the account and burn trx if not enough energy.

I found this 2 ways to solve this, If anyone faced same issue or have proper knowledge of energy in tron-java please do comment here and help me to solve the issue.
IF THERE IS ANY OTHER WAY OR APPROACH TO SOLVE MY ISSUE THAN DO LET ME KNOW.

**Comment by sunflower-sun** [comment]
@charil10 I don't think setting the decimal to 10 can decrease the energy usage. The execution of each instruction of smart contract consume a certain amount of energy while running. When the contract is executed, Energy is calculated and deducted according to instruction one by one. So if you want to decrease energy usage, you can define a lower energy consumption for [each instruction](https://github.com/tronprotocol/java-tron/blob/develop/actuator/src/main/java/org/tron/core/vm/EnergyCost.java).

**Comment by charil10** [comment]
@sunflower-sun Okay I will try to change the energy through code then can you please tell me the variables and functions where I can implement the condition.
suppose current energy code of ERC20(TRC20) token TRANSFER cost me 10000 I want to decrease it to 1000. like I want 10% OF THE CURRENT CONSUMPTION. so can you please tell me accordingly

**Comment by sunflower-sun** [comment]
@charil10 I don't get your point. Energy is calculated and deducted according to instruction one by one. so Just decrease each opcode's energy consumption will solve your issue.
