### ISSUE TITLE
Full node has been stuck 160 block number of sync not proceeding foreword.

### ISSUE THREAD

**Issue by SamirBitzees** [tronprotocol/java-tron#5649]
I asked this question on Telegram and Discord also but not got any reply there.

Basically I have done setup full node for tron nertwork. Using this testnet config template for config file (https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf). My build was successful and i have open all necessary port like UDP 18888, TCP 8090, but it is not syncing the complete node. 
Below is an output where we can see nuberof blocks.

ubuntu@ip-172-31-10-44:~/full_node$ curl -X POST http://3.110.171.223:8090/wallet/getnowblock | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   536  100   536    0     0   4229      0 --:--:-- --:--:-- --:--:--  4220
{
  "blockID": "00000000000000a0511b0d7ac24e2ddab3358aaec8ba98bdecf409e2b7d32283",
  "block_header": {
    "raw_data": {
      "number": 160,
      "txTrieRoot": "0000000000000000000000000000000000000000000000000000000000000000",
      "witness_address": "413c85a420eed66135a378eb7e5f9246f6fb896b07",
      "parentHash": "000000000000009f224f96f28e98807bfb0df18e0d27b41d92789f26e88f02be",
      "version": 9,
      "timestamp": 1572510600000
    },
    "witness_signature": "3384c4950c6b6f297a6a80d2c59c493a406fa504cc2cf37efd6d6693a643ed4f65b7b5dc4fdde95dad9f78874da5d41daf433b66d062f2c0296080e89a591cbc00"
  }
}

**Comment by laurenceja** [comment]
@SamirBitzees Delete the database, then download the snapshot of Nile testnet at https://database.nileex.io/ , then restart the node.

**Comment by omkar-bestdeveloperBTZ** [comment]
> @SamirBitzees Delete the database, then download the snapshot of Nile testnet at https://database.nileex.io/ , then restart the node.

did this but later the node is now stuck at 42119342 block number ,


java -jar SolidityNode.jar --version
OS : Linux
JVM : Oracle Corporation 1.8.0_202 amd64
Git : 440d062dc7d39eff532414cc3b887f61509ef9f5
Version : 4.7.3
Code : 18173

**Comment by ss3344520** [comment]
@omkar-bestdeveloperBTZ Can you try using the database from January 7th (https://database.nileex.io/ )? If you encounter any problems, please send me the log, thank you very much.

**Comment by omkar-bestdeveloperBTZ** [comment]
> @omkar-bestdeveloperBTZ Can you try using the database from January 7th (https://database.nileex.io/ )? If you encounter any problems, please send me the log, thank you very much.

i was using the snapshot from 4th jan , will try the 7th jan snapshot & let you know

**Comment by ss3344520** [comment]
@omkar-bestdeveloperBTZ The testnet environment requires the use of Nile branch code https://github.com/tronprotocol/java-tron/tree/Nile

**Comment by omkar-bestdeveloperBTZ** [comment]
> @omkar-bestdeveloperBTZ You seem to have used the wrong code branch, The testnet environment requires the use of Nile branch code https://github.com/tronprotocol/java-tron/tree/Nile

Should i use Nile branch or Nile_v4.7.0 latest branch? also when i've cloned the master branch , node does sync but stops after a particular block. with the latest snapshot i'm able to perform getbalance etc

**Comment by ss3344520** [comment]
@omkar-bestdeveloperBTZ The test environment can only use `Nile` branch.

**Comment by omkar-bestdeveloperBTZ** [comment]
> @omkar-bestdeveloperBTZ The test environment can only use `Nile` branch.

I understand but for now i'm facing no issues, the transaction listner & everything works fine for the nile testnet, i can also get the balance etc, but if the node stops again, i will clone the nile branch & use its fullnode.jar & soliditynode.jar file & then start the node.

**Comment by halibobo1205** [comment]
Closing for now but please continue the discussion thread if you are looking for more help.

**Comment by dipuyadav** [comment]
I am facing the same issue i.e. stuck at 160 block. I have tried cloning and using nile branch also as told above- https://github.com/tronprotocol/java-tron/tree/Nile
But not working still.
Using the latest version of Fulljar (4.7.5- celoblus)
