### ISSUE TITLE
节点间歇性出现接口连不上

### ISSUE THREAD

**Issue by FerdyCai** [tronprotocol/java-tron#5653]
当前使用的程序版本是v4.7.3，从今天早上开始出现间歇性api连接不上，过几秒又能连上
启动方式：
    export LD_PRELOAD="/usr/lib64/libtcmalloc.so.4"
    export TCMALLOC_RELEASE_RATE=10
    nohup java -Xmx12g -XX:+UseConcMarkSweepGC -jar FullNode.jar -d output-directory -c main_net_config.conf >./console.log 2>&1 &
请问这大概是出了什么问题？

**Comment by vivian1912** [comment]
@FerdyCai To get better and faster feedback from the community, it will be great to create the issue in English. Thanks for your contribution to Java-tron.

**Comment by FerdyCai** [comment]
@vivian1912 Okay, thank you for the reminder.

**Comment by laurenceja** [comment]
@FerdyCai  What do you mean for the no connection, is there any error message or return value?

**Comment by FerdyCai** [comment]
@laurenceja  I mean that when I tried to get balance of a wallet by :
  curl -H "Content-Type:application/json" -X POST 127.0.0.1:8090/wallet/getaccount -d '{"address":"TVTrj8vBNSh7rfYHgKhE1x2tfQvkBwhgjA","visible":true}'
  sometimes ，it'll take 20+s,  sometimes,it is very fast.
This phenomenon has occurred in the past few days.
eg:The data has exceeded 2T now, and I am not sure if too much data will affect the efficiency of the HTTP interface.

**Comment by 317787106** [comment]
@FerdyCai You can start the fullnode as the guide on README: 

```
nohup java -Xms9G -Xmx9G -XX:ReservedCodeCacheSize=256m \
             -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m \
             -XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails \
             -XX:+PrintGCDateStamps  -Xloggc:gc.log \
             -XX:+UseConcMarkSweepGC -XX:NewRatio=2 \
             -XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled \
             -XX:+HeapDumpOnOutOfMemoryError \
             -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=70 \
             -jar FullNode.jar -c main_net_config.conf >> start.log 2>&1 &

```
There are some gc parameters. Maybe full gc occurs on your node.

**Comment by FerdyCai** [comment]
@317787106  Thanks. Generally speaking, will the increase in data affect the efficiency of HTTP API execution?

**Comment by 317787106** [comment]
@FerdyCai There is little effect, because each business has its own leveldb store, such as account store which is related to /wallet/getaccount api, it is small.

**Comment by FerdyCai** [comment]
My start.sh changed to:
export LD_PRELOAD="/usr/lib64/libtcmalloc.so.4"
export TCMALLOC_RELEASE_RATE=10
nohup java -Xms9G -Xmx9G -XX:ReservedCodeCacheSize=256m \
             -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m \
             -XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails \
             -XX:+PrintGCDateStamps  -Xloggc:gc.log \
             -XX:+UseConcMarkSweepGC -XX:NewRatio=2 \
             -XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled \
             -XX:+HeapDumpOnOutOfMemoryError \
             -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=70 \
             -jar FullNode.jar -d output-directory -c main_net_config.conf >> start.log 2>&1 &

And the top info:
![image](https://github.com/tronprotocol/java-tron/assets/136073679/0fb57c6f-aa06-414a-adf8-24c082bf5acf)

However, intermittent inability to obtain balance still occurs.

**Comment by krakenliew** [comment]
same thing happened here,the response time can up to 1 minutes or even timeout when broadcast transaction.Any solution?
