### ISSUE TITLE
about energy recovery

### ISSUE THREAD

**Issue by txf1p** [tronprotocol/java-tron#5655]
> https://developers.tron.network/docs/resource-model#energy-recovery

after the energy resource of the account is consumed, it will gradually recover within 24 hours.

according to my actual tests, there is absolutely no pattern in recovery. Can anyone tell me how this recovery is calculated?

**Comment by ferdinand026** [comment]
@txf1p Assume that no energy is used before, and if an amount of energy is used at this time，the used energy will need 24 hours to fully recovery. So the energy recovery time is 24 hours. But if during the recovery period, the user uses energy again, the new energy recovery time will be:

Resource recovery time = (original resource usage * remaining resource recovery time + new resource usage * 28800) / (original resource usage + new resource usage)

Please pay attention, the unit of all recovery time is 3 second (that is block time). 28800 is 24 hours. You can get the values of all variables on the right side of the formula through the getaccount API.

**Comment by txf1p** [comment]
> @txf1p Assume that no energy is used before, and if an amount of energy is used at this time，the used energy will need 24 hours to fully recovery. So the energy recovery time is 24 hours. But if during the recovery period, the user uses energy again, the new energy recovery time will be:
> 
> Resource recovery time = (original resource usage * remaining resource recovery time + new resource usage * 28800) / (original resource usage + new resource usage)
> 
> Please pay attention, the unit of all recovery time is 3 second (that is block time). 28800 is 24 hours. You can get the values of all variables on the right side of the formula through the getaccount API.

How to use recovery faster?

**Comment by ferdinand026** [comment]
Can't be faster

**Comment by YuMenGuan** [comment]
> @txf1p Assume that no energy is used before, and if an amount of energy is used at this time，the used energy will need 24 hours to fully recovery. So the energy recovery time is 24 hours. But if during the recovery period, the user uses energy again, the new energy recovery time will be:
> 
> Resource recovery time = (original resource usage * remaining resource recovery time + new resource usage * 28800) / (original resource usage + new resource usage)
> 
> Please pay attention, the unit of all recovery time is 3 second (that is block time). 28800 is 24 hours. You can get the values of all variables on the right side of the formula through the getaccount API.

@ferdinand026  if before the resource recovery time, the account use energy third time, logically there is two ways to calculate a new recovery time, which one is right:

1. resource recovery time = (first resource usage * first resource remaining recovery time + second resource usage *second resource remaining recovery time + third resource usage*28800 ) / (first resource usage + second resource usage + third resource usage), Here first resource remaining recovery time  = 28800-time delta between current time and the time when the first usage happened, second resource remaining recovery = 28800-time delta between current time and the time when the second usage happened

2. Formula as yours, just substitute original resource usage with sum of first resource usage and second resource usage, substitute remaining resource recovery time with you calculated resource recovery time

**Comment by simbadMarino** [comment]
For anyone still wondering about this, I made a formula, as per my calculations and tests, looks good, but I would like to get some confirmation from core devs:

![Image](https://github.com/user-attachments/assets/d2246023-1a9b-47a7-8635-6eb218cf3227)

Is this accurate @ferdinand026 , @Benson0224 ?
