### ISSUE TITLE
Full Node Http Api "getaccount" returns empty object

### ISSUE THREAD

**Issue by jurijus01** [tronprotocol/java-tron#5680]
OS : Linux
JVM : Private Build 1.8.0_392 amd64
Git : 7a6a6d8008b28d472100c9fcff2b6b9010829ed0
Version : 4.7.3.1
Code : 18180

#### Expected behaviour

https://developers.tron.network/reference/account-getaccount
"This API returns the account object, which contains the following fields:"

#### Actual behaviour

{}

**Comment by SukiratWarring** [comment]
@jurijus01 You need to activate the account i.e send some native currency to that account.

**Comment by jurijus01** [comment]
https://tronscan.org/#/address/TD78cTr5Y5FUmtsi8B1GgrxSfvZUwx7mfc

Account is activated. It has 15 TRX and 3.2 USDT on it.

**Comment by SukiratWarring** [comment]
@jurijus01 
are you setting up a private chain?

**Comment by jurijus01** [comment]
No, not at all.

**Comment by SukiratWarring** [comment]
USe this 
https://api.trongrid.io/wallet/getaccount
```
{
  "address": "TD78cTr5Y5FUmtsi8B1GgrxSfvZUwx7mfc",
  "visible": true
}
```
RESULT:-
```
{
    "address": "TD78cTr5Y5FUmtsi8B1GgrxSfvZUwx7mfc",
    "balance": 15000000,
    "create_time": 1705164519000,
    "net_window_size": 28800000,
    "net_window_optimized": true,
    "account_resource": {
        "energy_window_size": 28800000,
        "energy_window_optimized": true
    },
    "owner_permission": {
        "permission_name": "owner",
        "threshold": 1,
        "keys": [
            {
                "address": "TD78cTr5Y5FUmtsi8B1GgrxSfvZUwx7mfc",
                "weight": 1
            }
        ]
    },
    "active_permission": [
        {
            "type": "Active",
            "id": 2,
            "permission_name": "active",
            "threshold": 1,
            "operations": "7fff1fc0033ec30f000000000000000000000000000000000000000000000000",
            "keys": [
                {
                    "address": "TD78cTr5Y5FUmtsi8B1GgrxSfvZUwx7mfc",
                    "weight": 1
                }
            ]
        }
    ],
    "frozenV2": [
        {},
        {
            "type": "ENERGY"
        },
        {
            "type": "TRON_POWER"
        }
    ],
    "asset_optimized": true
}
```

**Comment by jurijus01** [comment]
That doesn't fix the bug

**Comment by jurijus01** [comment]
So nobody is using HTTP API at all? Just me? :)

**Comment by ferdinand026** [comment]
@jurijus01 Do you mean your own node returns empty when querying the account information? You can check if the node has already fully synced. wallet/getnowblock will return the head block, and then compare the value with that shown on tronscan.

**Comment by CarlChaoCarl** [comment]
Check to see if the full node you built has not been synchronized to the latest block.

**Comment by jurijus01** [comment]
No I am not sync'ed to the latest block, however it allowed creating new accounts so it gave the impression everything was fine. 

Why the API won't give a sensible response instead of just {} ? 

Tronweb for the same command gives error 405 and that's it - go figure. 

Honesty, it is all very confusing.

**Comment by jurijus01** [comment]
Ok, now my node is synced to the latest block. Still getting {} on getaccount.

What am I doing wrong?

**Comment by jurijus01** [comment]
My bad, forgot to .json() the response. Thanks for help everybody!
