### ISSUE TITLE
Dropped block Policy

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/java-tron#569]
I am running a full witness node. Last night I was elected Super Representative and am processing blocks. Overnight TRON added 11 million+ votes to my candidate and put me in the #1 spot at the top of the queue.

I have noticed that we started with 15 servers and as some have gone offline they have not been replaced. There are currently 9 nodes processing blocks.

It does not look like the lost blocks are made up - the network just loses that time. When nodes drop a block, the behavior that I'm witnessing is those transactions are held over and added to the block of the #1 node. My average block size is about 4x the size of the others.

So the lost earnings are absorbed by all the remaining nodes, but the workload is assigned to only one of them.

Of course, with traffic so light the algorithm may be behaving completely differently than it will in production.

1. What did you do?
Elected to Super Representative with the most number of votes. Processed dropped blocks.

2. What did you expect to see?
Increased block rate.

3. What did you see instead?
Increased block size.

**Comment by zhaohong** [comment]
@olenheim  to follow this issue.
