### ISSUE TITLE
Potential concurrency vulnerabilities in TransactionCapsule

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/java-tron#5695]
#### System information

Java-tron version: [v4.7.3](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.7.3) /Java1.8
OS & Version: Linux

#### Actual behaviour
There is a global variable StringBuilder toStringBuff in org.tron.core.capsule.TransactionCapsule

```
private StringBuilder toStringBuff = new StringBuilder();
...
@Override
public String toString() {
  toStringBuff.setLength(0);
  toStringBuff.append("TransactionCapsule \n[ ");
  ...
  return toStringBuff.toString();
}
```

The variable toStringBuff can be changed in the method `toString()`, but the class java.lang.StringBuilder is not thread-safe and cannot be accessed concurrently, otherwise, StringIndexOutOfBoundsException may happen. It is similiar as https://github.com/tronprotocol/java-tron/issues/5592, through we have not found the concurrent usage of `toString()` in  TransactionCapsule.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ss3344520** [comment]
`StringBuilder` object should not be defined as a class variable, it is best to create a `StringBuilder` object in the `toString` method.

**Comment by jwrct** [comment]
Does it mean that there are no concurrency issues even if it is not modified? Is the reason for the modification to avoid introducing problems in the future due to improper use?

**Comment by 317787106** [comment]
> `StringBuilder` object should not be defined as a class variable, it is best to create a `StringBuilder` object in the `toString` method.

@ss3344520 Yes, I have the same opinion as you

**Comment by 317787106** [comment]
> Does it mean that there are no concurrency issues even if it is not modified? Is the reason for the modification to avoid introducing problems in the future due to improper use?

@jwrct Yes, we have not found the concurrency usuge now, but eliminating potential bugs is also important.
