### ISSUE TITLE
Optimize RocksDB's  backup function

### ISSUE THREAD

**Issue by forfreeday** [tronprotocol/java-tron#5698]
# Rationale
The  [RocksDB database backup function](https://tronprotocol.github.io/documentation-en/architecture/database/#use-rocksdbs-data-backup-function) ensures the backup of consensus data within the databases of locally running nodes, crucial for maintaining data consistency across all nodes in the TRON network.

When TRON was designed, all the necessary backup data for consensus data were included in the backup function. However, as the network grows and evolves, some newly added databases have not been backed up by the RocksDB backup function. Some of these databases were developed after implementing the RocksDB backup function. It is necessary to back up these databases.

To prevent future instances of missing data, all necessary databases, except for some unnecessary ones, will be backed up this time.

Database Analysis
An analysis of the currently unbacked-up databases:

* `AccountAssetStore`: Account 10 asset database
* `CheckpointV2Store`: WAL checkpoint backup data
* `CheckTmpStore`: WAL checkpoint backup data
* `RewardViStore`: Old reward algorithm-related database
* `ZKProofStore`: Storage of ZK proofs for anonymous transactions
* `CommonDataBase`: PBFT-related
* `CommonStore`: Storage of P2P node information
* `KhaosDatabase`: In-memory block storage database
* `PbftSignDataStore`: PBFT-related

Databases that do not require backup
The following two databases serve as write-ahead log checkpoint backup databases and are only used for recovery in the event of abnormal node shutdown. They do not participate in business data storage.

* `CheckPointV2Store`: Used to store checkpoint data
* `CheckTmpStore`: Checkpoint V1 version

# Implementation
All databases, except for the two WAL checkpoint databases, should be included in the backup.

**Are you willing to implement this feature?**
Yes, I can make this happen.

**Comment by halibobo1205** [comment]
Nice improvement.

**Comment by halibobo1205** [comment]
I am working on it.

**Comment by halibobo1205** [comment]
No change plan for now.
