### ISSUE TITLE
Why Tronscan knows more about my accounts than I do with own node?

### ISSUE THREAD

**Issue by jurijus01** [tronprotocol/java-tron#5699]
# Rationale

Why should this feature exist?

https://tronscan.org/#/address/TD78cTr5Y5FUmtsi8B1GgrxSfvZUwx7mfc

Tronscan is showing TRC20 in my account. I can't get such info using Tron APIs. However I should - this is my info and own node. 

I created an account on owm node, sent TRC20 to it, activated it by senging TRX to it and the only balance I can get by using Tron API is TRX balance. But Tronscan is showing TRC20 balance too. Why I can't see the same info just by using API of own node?

What are the use-cases?

Just simply having an account on own node and sending TRC20s to it needs this feature of listing all the TRC20s the account has in and their total balance. Kind of obvious, isn't it?

# Implementation

Do you have ideas regarding the implementation of this feature? No.
Are you willing to implement this feature? No.

**Comment by ferdinand026** [comment]
@jurijus01 All application including Tronscan get the online data through the API of the fullnode, and then display the data to users. We can get all data we want through fullnode API, and this is a guide for [how to get the balance or transferring history.](https://developers.tron.network/docs/exchangewallet-integrate-with-the-tron-network#deploy-a-fullnode-of-tron-network)

**Comment by 317787106** [comment]
@jurijus01 Tronscan collects and processes all data and integrates it into structured data, which is available to all users and is not consistent with the role of a single node. For a single node, this is too costly and unnecessary.

**Comment by jurijus01** [comment]
If I receive TRC20s - for example, as a donation - how do I know TRC20 contract address beforehand? I have no idea who would send them to me and when. All I see in the docs is that I need to know TRC20 contract address beforehand.

I don't agree about "unnececary" at all. This is a user having opened new wallet to receive TRC20s would want straight away - to have all TRC20s received listed.

I agree about "costly", meaning that it would take the node to keep on parsing where single block transaction it can get hold of to be able to ftrace that destination of TRC20s is my account? Is this the only way?

**Comment by 317787106** [comment]
> If I receive TRC20s - for example, as a donation - how do I know TRC20 contract address beforehand? I have no idea who would send them to me and when. All I see in the docs is that I need to know TRC20 contract address beforehand.
> 
> I don't agree about "unnececary" at all. This is a user having opened new wallet to receive TRC20s would want straight away - to have all TRC20s received listed.
> 
> I agree about "costly", meaning that it would take the node parse every transaction in Tron's history it has synced (that's why it is Fullnode) - starting from my account creation date - to come up with all TRC20s the account ever received?

@jurijus01 Tronscan server gets block from fullnode, parse transaction, generate many kinds of data, store data, supply many apis, that's a very complcated progress. Query trc20 asset of one account is only one module. If you only want to query your trc20, you can use `getlogs` method of jsonrpc. You only need to query transfer event, merge all contract addresses, that's your trc20 approximately. This does not require any changes to fullndoe.

**Comment by halibobo1205** [comment]
@jurijus01 Closing for now but please continue the discussion thread if you are looking for more info.
