### ISSUE TITLE
Nile Testnet Node Throw NullPointerException

### ISSUE THREAD

**Issue by jwrct** [tronprotocol/java-tron#5702]
#### System information

Java-tron version: v4.7.3
OS & Version: Linux & macOS

#### Expected behaviour
The PbftMessageHandle class no longer throws a null pointer exception.

#### Actual behaviour
My Nile testnet node reported a NullPointerException, and the exception information is as follows:
```
14:41:00.183 ERROR [pbft-timer] [app](DefaultConfig.java:40) Uncaught exception
java.lang.NullPointerException: null
        at org.tron.consensus.pbft.PbftMessageHandle.onPrePrepare(PbftMessageHandle.java:107)
        at org.tron.consensus.pbft.PbftMessageHandle.remove(PbftMessageHandle.java:293)
        at org.tron.consensus.pbft.PbftMessageHandle.checkTimer(PbftMessageHandle.java:306)
        at org.tron.consensus.pbft.PbftMessageHandle.access$000(PbftMessageHandle.java:38)
        at org.tron.consensus.pbft.PbftMessageHandle$2.run(PbftMessageHandle.java:315)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

After reviewing the code, the analysis of the general reasons is as follows:
The function of the thread pbft-timer is to clear expired pbft information. If the information to be cleared is SRL's pbft information, it will be retried once. The logic is as follows:
```
private void checkTimer() {
    for (Entry<String, Long> item : timeOuts.entrySet()) {
      if (System.currentTimeMillis() - item.getValue() > TIME_OUT) {
        //If the timeout has not been agreed, the vote will be invalid.
        logger.info("vote will be invalid:{}", item.getKey());
        remove(item.getKey());
      }
    }
}

private void remove(String no) {
    ...
    //just try once
    if (srPbftMessage != null && StringUtils.equals(no, srPbftMessage.getNo())) {
      try {
        Thread.sleep(100);
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
      } catch (Exception e) {
      }
      onPrePrepare(srPbftMessage);
      srPbftMessage = null;
    }
  }
```
In the thread pbft-msg-manager, after the completion of block consensus, the onCommit method will set srPbftMessage to null. The logical code is as follows:

```

public synchronized void onCommit(PbftMessage message) {
    ...
    if (agCou >= Param.getInstance().getAgreeNodeCount()) {
      srPbftMessage = null;
      remove(message.getNo());
      //commit,
      if (!isSyncing()) {
        pbftMessageAction.action(message, dataSignCache.getUnchecked(message.getDataKey()));
      }
    }
  }
```
When these two threads are executed concurrently, there will be a concurrency access issue for the global variable srPbftMessage.

Can you help me check if my analysis process and conclusion are correct?

#### Steps to reproduce the behaviour
In a network with PBFT functionality enabled (e.g., Nile testnet), observe its PBFT-related logs. However, the probability of concurrent occurrences is relatively low and may take a long time to occur.

#### Backtrace

````
14:41:00.141 INFO  [pbft-msg-manager-0] [pbft](PbftManager.java:78) receive pbft msg: DataType:BLOCK, MsgType:COMMIT, node address:4139e58c94e9877bbe5556ee7ac
c6d6d428a3929e9, viewN:43775135, epoch:1706128800000, data:00000000029bf49f3ee83cd6b21d68b8a3807d146361e939ed8daca8f027aff6, type: PBFT_MSG

14:41:00.143 INFO  [pbft-msg-manager-0] [pbft](PbftMessageAction.java:29) commit msg block num is:43775135
...

14:41:00.183 ERROR [pbft-timer] [app](DefaultConfig.java:40) Uncaught exception
java.lang.NullPointerException: null
        at org.tron.consensus.pbft.PbftMessageHandle.onPrePrepare(PbftMessageHandle.java:107)
        at org.tron.consensus.pbft.PbftMessageHandle.remove(PbftMessageHandle.java:293)
        at org.tron.consensus.pbft.PbftMessageHandle.checkTimer(PbftMessageHandle.java:306)
        at org.tron.consensus.pbft.PbftMessageHandle.access$000(PbftMessageHandle.java:38)
        at org.tron.consensus.pbft.PbftMessageHandle$2.run(PbftMessageHandle.java:315)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 317787106** [comment]
@jwrct Can you specify how the method `onPrePrepare` uses the varible `srPbftMessage`? It's not clear in the doc.

**Comment by jwrct** [comment]
> @jwrct Can you specify how the method `onPrePrepare` uses the varible `srPbftMessage`? It's not clear in your description.

The remove method calls the `onPrePrepare` method and passes `srPbftMessage` as a parameter.

**Comment by jwrct** [comment]
> This is a thread concurrent access problem. Is there any good solution?

Adding a synchronized lock control to the `remove` method can solve this problem.
