### ISSUE TITLE
Add APIs like eth_blockNumber to grpc and http

### ISSUE THREAD

**Issue by moqi2011** [tronprotocol/java-tron#5704]
# Rationale

### Why should this feature exist?

Obtaining the latest block number is a very common requirement. The current http and grpc seem to be implemented only through getnowblock, but it provides too much redundant information.

# Implementation

### Do you have ideas regarding the implementation of this feature?
[org.tron.core.services.jsonrpc.TronJsonRpcImpl#getLatestBlockNum](https://github.com/tronprotocol/java-tron/blob/master/framework/src/main/java/org/tron/core/services/jsonrpc/TronJsonRpcImpl.java#L346)

**Comment by halibobo1205** [comment]
A similar solution has been provided：https://github.com/tronprotocol/java-tron/issues/3945, it is implemented by [GreatVoyage-v4.5.2](https://github.com/tronprotocol/java-tron/releases/tag/GreatVoyage-v4.5.2). You can find more details in https://developers.tron.network/reference/getblock-2

**Comment by 317787106** [comment]
@moqi2011 Do you only want to get latest  blockNumber and blockHash?

**Comment by moqi2011** [comment]
@halibobo1205  The name of this interface is a bit confusing. 

@317787106 I only want to get latest blockNumber. Used to confirm synchronization status and scan blocks.

**Comment by halibobo1205** [comment]
```bash
curl 127.0.0.1:8090/wallet/getblock
```


```json
{
    "blockID":"00000000037e8a88f525c526617cd8365e41330940416274550b6ea34c34d0b7",
    "block_header":{
        "raw_data":{
            "number":58624648,
            "txTrieRoot":"1999d0085982737a5bc811f4629c76e4e6b11f6b37eba05bd8fe8d9138f5741c",
            "witness_address":"411c8163d2a981b90481dcc8ca34c0f837b3305bc6",
            "parentHash":"00000000037e8a874ead8cbf3642e7e054192475c45bea902ae45008c66907f8",
            "version":28,
            "timestamp":1706508525000
        },
        "witness_signature":"c86bc5e0043e534fdffca6d0466a387f1b5a0830b307cc00402ff94bba43df925c3c3ad7685c532074a8860549da3a616cbde78a85a9acae1aa9f756caa8211c00"
    }
}

```
