### ISSUE TITLE
{     "Error": "class org.tron.core.exception.ContractValidateException : Invalid ownerAddress!" }

### ISSUE THREAD

**Issue by xiezh1010** [tronprotocol/java-tron#5710]
I try to invoke HTTP /wallet/createtransaction

curl -X POST http://127.0.0.1:8090/wallet/createtransaction -d
'{
    "owner_address": "54514A684E3963314E367745687852477439426661703952313351386F6457373155",
    "to_address": "545668577137336469376138565A64466B3946765359475773587368615768624159",
    "amount": 100
}'

What is the problem？？

Add a description

I want to complete the transfer through nile test network

**Comment by lxcmyf** [comment]
@xiezh1010 
How did you create an address?

**Comment by CarlChaoCarl** [comment]
curl -X POST http://127.0.0.1:8090/wallet/createtransaction -d
'{
    "owner_address": "TRGhNNfnmgLegT4zHNjEqDSADjgmnHvubJ",
    "to_address": "TJCnKsPa7y5okkXvQAidZBzqx3QyQ6sxMW",
    "amount": 1000000,
    "visible": true
}'

@xiezh1010 
I tried calling it on my private chain, no problem
Check that your owner_address exists and there is no problem with the format.

**Comment by xiezh1010** [comment]
> @xiezh1010 How did you create an address? Please ensure that the address you entered has been activated. To activate them, simply create an account or transfer token to the address that needs to be activated.

I created it through tronlink

**Comment by CarlChaoCarl** [comment]
You created the owner_address in the nile test network, and then you created a transaction on the private chain, so the owner_address does not exist on the private chain. Check whether this is the problem.

@xiezh1010

**Comment by xiezh1010** [comment]
> nile test network

how can i created a transaction  on the nile test network?

**Comment by chaosuper85** [comment]
curl -X POST http://34.208.18.175:8090/wallet/createtransaction -d '{"owner_address": "TQJhN9c1N6wEhxRGt9Bfap9R13Q8odW71U","to_address": "TVhWq73di7a8VZdFk9FvSYGWsXshaWhbAY","amount": 100,"visible": true}'

1. I used StringUtil.hexString2ByteString to perform address conversion.
54514A684E3963314E367745687852477439426661703952313351386F6457373155
=>TQJhN9c1N6wEhxRGt9Bfap9R13Q8odW71U
545668577137336469376138565A64466B3946765359475773587368615768624159
=>TVhWq73di7a8VZdFk9FvSYGWsXshaWhbAY
2. I added the parameter visible=true.
3. I created the transaction, I used the IP of nile test net: 34.208.18.175

After doing the above, I successfully created the transaction.
You can try it as I posted.

@xiezh1010

**Comment by CarlChaoCarl** [comment]
curl -X POST http://34.208.18.175:8090/wallet/createtransaction -d '{"owner_address": "TQJhN9c1N6wEhxRGt9Bfap9R13Q8odW71U","to_address": "TVhWq73di7a8VZdFk9FvSYGWsXshaWhbAY","amount": 100,"visible": true}'

I used StringUtil.hexString2ByteString to perform address conversion.
54514A684E3963314E367745687852477439426661703952313351386F6457373155
=>TQJhN9c1N6wEhxRGt9Bfap9R13Q8odW71U
545668577137336469376138565A64466B3946765359475773587368615768624159
=>TVhWq73di7a8VZdFk9FvSYGWsXshaWhbAY
I added the parameter visible=true.
I used the IP of nile test net: 34.208.18.175
After doing the above, I successfully created the transaction.
You can try it as I posted.

@xiezh1010

**Comment by halibobo1205** [comment]
@xiezh1010 Closing for now but please continue the discussion thread if you are looking for more help.
