### ISSUE TITLE
Restricting access to the node

### ISSUE THREAD

**Issue by d1mpi** [tronprotocol/java-tron#5715]
Is it possible to make a similar API Key for GRPC as on Trongrid, but for your own private node? There is a need to restrict access to the node for clients.

**Comment by ferdinand026** [comment]
@d1mpi Currently an available function is interface access rate limiting. You can set the QPS for each interface through node configuration file, please refer to [here](https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf#L343), or set the default interface rate limit through `rate.limiter.global.api.qps`. If this does not meet your requirement, then the only way is to implement the function through code by yourself.

**Comment by halibobo1205** [comment]
@d1mpi Closing for now but please continue the discussion thread if you are looking for more help.
