### ISSUE TITLE
TransferAsset format issue

### ISSUE THREAD

**Issue by Torakushi** [tronprotocol/java-tron#5718]
Hello,

I am trying to send TRC10 token using the `transferAsset` api call. However, I have some problems with the `visible` param.

Indeed, when doing visible = false  and addresses/asset_name in hex format, I have no problem.

```
await this.fullnode.post('/wallet/transferasset', {
        to_address: Buffer.from(TronWeb.utils.crypto.decodeBase58Address(to)).toString('hex'),
        owner_address: Buffer.from(TronWeb.utils.crypto.decodeBase58Address(from)).toString('hex'),
        asset_name: Buffer.from(tokenId, 'utf-8').toString('hex'),
        amount,
        visible: false,
      })
```

However, when putting `visible = true`, I don't know what to put in asset_name. For example in Nile, I want to play with the tokenId 1000016.

I tried to put the hex format, the utf8 token ID and even the base58 tokenID but I always have these errors:

either

```
    class org.tron.core.exception.ContractValidateException : No asset!
```
(for hexFormat)

or, when transferAsset API call works, it will fail when trying to broadcast with:

```
    CONTRACT_VALIDATE_ERROR: Contract validate error : asset [<ByteString@3c1e40fc size=4 contents="\020\000\001\006">] does not exist
```

(transaction to be broadcasted:

```
 {
      contract: [ 
                {
                  type: 'TransferAssetContract',
                  parameter: {
                    value: {
                            amount: 1,
                            asset_name: '1000016',
                            owner_address: 'TDYh3krP3XmMB8f1ipS1GQHQcEsDXNRcWi',
                            to_address: 'TDNX3cbK9wEf85LxJL11CD6iQ98dNe5wP8'
                      },
                    type_url: 'type.googleapis.com/protocol.TransferAssetContract'
                  }
                }
      ],
      ref_block_bytes: 'a7c0',
      ref_block_hash: '0df12150a2e1f3b1',
      timestamp: 1706862944756,
      expiration: 1706863002000
    }
```

Did I do something wrong?

**Comment by ferdinand026** [comment]
@Torakushi `visible` refers to whether the address is in base58 format, it is not related with asset_name, so asset_name should be in hex format no matter what the value of visible is.

**Comment by Torakushi** [comment]
@ferdinand026 thanks for your answer.

However, if I put visible = true, the addresses in base58 and the asset_name in hex, I get 

```
    class org.tron.core.exception.ContractValidateException : No asset!
```

```
await this.fullnode.post('/wallet/transferasset', {
        to_address: to,
        owner_address:from,
        asset_name: Buffer.from(tokenId, 'utf8').toString('hex'),
        amount,
        visible: true
      })
```

when tokenID = 1000016

I don't have this error if visible =false and addresses in hex

**Comment by halibobo1205** [comment]
Yes, `asset_name` is affected by `visible`, a list of all the parameters affected by this parameter can be found here [HttpSelfFormatFieldName](https://github.com/tronprotocol/java-tron/blob/develop/framework/src/main/java/org/tron/core/services/http/HttpSelfFormatFieldName.java)


//TransferAssetContract
NameFieldNameMap.put("protocol.TransferAssetContract.asset_name", 1);

**Comment by Torakushi** [comment]
Thanks @halibobo1205 for this answer! 

So, if I understand correctly, I should put `asset_name` in UTF8 when putting `visible=true`?

WHen I do that, `transferAsset` works, but broadcasting the resulting transaction fails with:

    CONTRACT_VALIDATE_ERROR: Contract validate error : asset [<ByteString@5d866682 size=4 contents="\020\000\001\006">] does not exist

I guess, when converting into a protobuf transaction(using `Transaction.deserializeBinary()`) to use `broadcasthex`, their is a problem.

Indeed, when I check the  protobuf format of the resulting transaction, I have:

<img width="678" alt="image" src="https://github.com/tronprotocol/java-tron/assets/61413577/f0ee218b-849a-47fc-9ec6-7f5d0228ed94">

addresses are converted into hex but not asset_name

**Comment by halibobo1205** [comment]
`asset_name: Buffer.from(tokenId, 'utf-8')`
Probably not needed .toString('hex'),  you can try it.

<img width="645" alt="image" src="https://github.com/tronprotocol/java-tron/assets/82020050/c5789a82-5c7c-4851-862c-d23da73949dd">

**Comment by Torakushi** [comment]
Sorry I was unclear.

What I did is:

```
await this.fullnode.post('/wallet/transferasset', {
        to_address: to, // base58
        owner_address: from, // base58
        asset_name: "1000016", //utf8
        amount,
        visible: true,
      })
```

`transferAsset` works but when broadcasting the resulting transaction it fails 
Surely because, when converting in the protobuf format, asset_name should have been transformed into hex but it wasn't (the addresses were converted when using protobuf, see screenshot)

**Comment by halibobo1205** [comment]
@Torakushi  try this `/wallet/broadcasttransaction` , `broadcastHex` may not support `visible` = true

**Comment by halibobo1205** [comment]
@Torakushi 
From the code `/wallet/broadcasttransaction`
![telegram-cloud-photo-size-5-6199705354300929874-y](https://github.com/tronprotocol/java-tron/assets/82020050/2c9f9d0d-e57b-408a-b099-ba8f21d38a56)
`/wallet/broadcastHex`
![telegram-cloud-photo-size-5-6199705354300929875-y](https://github.com/tronprotocol/java-tron/assets/82020050/c90e4782-0a37-41c8-ab12-1d00362d1213)

`broadcastHex` do not support `visible = true`.
> I used visible = true for smartcontract interaction, which worked well with broadcastHex.

Can you share the details? Thanks.

**Comment by Torakushi** [comment]
Yes sure, I was unclear:

> I used visible = true for smartcontract interaction, which worked well with broadcastHex.

I used "visible = true" to build the transaction (triggersmartcontract or transferAsset)

Here is the workflow:

For SmartContractInteraction:

1)
```
await this.fullnode.post('/wallet/triggersmartcontract', {
        contract_address: contractAddress, // Base58
        function_selector: functionSelector,
        owner_address: ownerAddress, // Base58
        parameter: parameter,
        visible: true, // base58 address
        fee_limit: feeLimit,
      })
    )
```

Then we will sign it offline:

```
txPb = TronWeb.utils.transaction.txJsonToPb(transaction).serializeBinary()

// add signature
txPb.addSignature(signature)

// Broadcast the txHex
await this.fullnode.post('/wallet/broadcasthex', {
        transaction: transactionHex,
})
```

No problem for that


For TRC10:

```
await this.fullnode.post('/wallet/transferasset', {
        to, // Base58
        owner_address: owner_address, // Base58
        asset_name: tokenId, // UTF8
        amount,
        visible: true,
      })
```

then the same process to sign and broadcast the transaction.

But here, it fails.

**Comment by halibobo1205** [comment]
@Torakushi, for questions about `TronWeb calls`, you can find more professional support here:https://github.com/tronprotocol/tronweb/issues.
