### ISSUE TITLE
Optimize event subscribe exception handling

### ISSUE THREAD

**Issue by lurais** [tronprotocol/java-tron#5719]
# Rationale

Why should this feature exist?
I notice that the codes of the [event subscribe](https://github.com/tronprotocol/documentation-en/blob/master/docs/architecture/event.md) function are quite close to the applyBlock process codes in the pushBlock function, and any exception thrown by the event subscribe function will lead to normal blocks being removed from KhaosDB, which has been committed successfully. 

In this case, the next block will be processed failed when putting into the KhaosDB since no parent block could be found in KhaosDB.

The detail code is here:

```java
try (ISession tmpSession = revokingStore.buildSession()) {
    long oldSolidNum =
            chainBaseManager.getDynamicPropertiesStore().getLatestSolidifiedBlockNum();
    applyBlock(newBlock, txs);
    tmpSession.commit();
    // if event subscribe is enabled, post block trigger to queue
    postBlockTrigger(newBlock);
    // if event subscribe is enabled, post solidity trigger to queue
    postSolidityTrigger(oldSolidNum,
            getDynamicPropertiesStore().getLatestSolidifiedBlockNum());
  } catch (Throwable throwable) {
    logger.error(throwable.getMessage(), throwable);
    khaosDb.removeBlk(block.getBlockId());
    throw throwable;
  }
```

The block synchronization should work as we expected when any exception is thrown in the event subscribe function, in detail, it should work well if the event subscribe function is allowed to miss some data.
# Implementation

Do you have ideas regarding the implementation of this feature?

Solution: The event subscribe logic is the subsequent processing logic of  block processing, and the event subscribe logic is independent from the existing block processing logic. Therefore, exceptions related to the event subscribe logic should be handled separately. In addition, due to some users' high dependence on the stability of event subscribe functions, while others require synchronization services to remain stable and allow occasional exceptions to occur in the event subscribe logic, a new switch is added to control whether synchronization functions should be suspended when event subscribe services are abnormal.

The new added switch is located in config file path: event.subscribe.ignoreSubscribeError, and the node will stop when any exception is thrown in event subscribe services if the config is not set or set  to false; and the node will ignore the exceptions thrown by the event subscribe services and continue to synchronize blocks only if it has set to true .

The related code will be like this:
```java
    try (ISession tmpSession = revokingStore.buildSession()) {
      applyBlock(newBlock, txs);
      tmpSession.commit();
    } catch (Throwable throwable) {
      logger.error(throwable.getMessage(), throwable);
      khaosDb.removeBlk(block.getBlockId());
      throw throwable;
    }
    try {
      long oldSolidNum =
              chainBaseManager.getDynamicPropertiesStore().getLatestSolidifiedBlockNum();
      // if event subscribe is enabled, post block trigger to queue
      postBlockTrigger(newBlock);
      // if event subscribe is enabled, post solidity trigger to queue
      postSolidityTrigger(oldSolidNum,
              getDynamicPropertiesStore().getLatestSolidifiedBlockNum());
    } catch (Exception e) {
      logger.error("Post trigger error.", e);
      // as disscussed below, this switch will not be added 
      if (!ignoreSubscribeErrorSwitchOn()) {
        System.exit(1);
      }
    }
```
As discussed below, the config ignoreSubscribeError is unnecessary and will not be added. The next question is, if the event subscription function throws an exception, does it need to be retried? Or just stop the node if any exception is found in the event subscription:
```java
     try (ISession tmpSession = revokingStore.buildSession()) {

        long oldSolidNum =
                chainBaseManager.getDynamicPropertiesStore().getLatestSolidifiedBlockNum();

        applyBlock(newBlock, txs);
        // if event subscribe is enabled, post block trigger to queue
        postBlockTrigger(newBlock);
        // if event subscribe is enabled, post solidity trigger to queue
        postSolidityTrigger(oldSolidNum,
                getDynamicPropertiesStore().getLatestSolidifiedBlockNum());
        tmpSession.commit();
      } catch (Throwable throwable) {
        logger.error(throwable.getMessage(), throwable);
        khaosDb.removeBlk(block.getBlockId());
        throw throwable;
      }
```
As discussed in the comments, the node will stop if an exception is found in the event subscription.

Are you willing to implement this feature?
Yes.

**Comment by halibobo1205** [comment]
why need `ignoreSubscribeErrorSwitchOn `?

**Comment by lurais** [comment]
> while others require synchronization services to remain stable and allow occasional exceptions to occur in the event subscribe logic

To offer users a choice, synchronization services can remain stable while allowing occasional exceptions to occur during subscribe logic.

**Comment by lurais** [comment]
@jwrct @317787106 @ss3344520  Do you have any ideas about this issue?

**Comment by ss3344520** [comment]
@lurais  From your description, there are more than two exception handling strategies. It is recommended to use enumeration types for configuration parameters instead of boolean types.

**Comment by halibobo1205** [comment]
I don't recommend adding more configurations for user purposes.

**Comment by 317787106** [comment]
@lurais is System.exit(1) has any potential problems, such as resource release ?

**Comment by lurais** [comment]
> @lurais is System.exit(1) has any potential problems, such as resource release ?

@317787106 When you use the command "System.exit", it will take effect as same as "kill -15" actually.

**Comment by lurais** [comment]
@halibobo1205 Why do you not recommend adding more configurations for user purposes? Do you have any more detail reasons?
@317787106 @ss3344520 @jwrct The issue that needs to be discussed now is whether to add more configurations to continue to synchronize blocks for user purposes when there is a problem with the event subscription service. Do you have any ideas about this?

**Comment by jwrct** [comment]
Based on your plan and default configuration, if an exception is thrown causing the system to exit when publishing an event, how should the node user handle it to recover? Will there be any data loss issue after the node restarts? Will there be any impact on the event subscribers?

**Comment by halibobo1205** [comment]
Event subscribers are not allowed to drop data in most cases.

**Comment by lurais** [comment]
> Based on your plan and default configuration, if an exception is thrown causing the system to exit when publishing an event, how should the node user handle it to recover? Will there be any data loss issue after the node restarts? Will there be any impact on the event subscribers?

@jwrct We expect the event subscription mechanism to work without any issues and not lose any data. If you encounter any problems with the event subscription component itself, you should fix the problem and restart it as before. If the problem is caused by sporadic issues like network problems, restarting the node can generally return it to normal. As the currently processed block is not solidified, there will be no data loss. However, duplicate data may be generated due to the impact on the event subscription component.

**Comment by lurais** [comment]
> Event subscribers are not allowed to drop data in most cases.

@halibobo1205 As we can see, if someone builds a website, the website provides external services by calling the RPC interface of the node, and also uses event subscription for subsequent on-chain tracking. If the node is stopped directly, the overall service will lose availability. Is this reasonable?

**Comment by lurais** [comment]
> > Event subscribers are not allowed to drop data in most cases.
> 
> @halibobo1205 As we can see, if someone builds a website, the website provides external services by calling the RPC interface of the node, and also uses event subscription for subsequent on-chain tracking. If the node is stopped directly, the overall service will lose availability. Is this reasonable?

@jwrct @ss3344520 @317787106 do you have any ideas about this scenario?

**Comment by jwrct** [comment]
@lurais What scene? I don't understand what you are asking.

**Comment by lurais** [comment]
> if someone builds a website, the website provides external services by calling the RPC interface of the node, and also uses event subscription for subsequent on-chain tracking. If the node is stopped directly, the overall service will lose availability. Is this reasonable?

@jwrct if someone builds a website, the website provides external services by calling the RPC interface of the node, and also uses event subscription for subsequent on-chain tracking. If the node is stopped directly, the overall service will lose availability. Is this reasonable?

**Comment by lxcmyf** [comment]
Isn't that right? I see that when the modified code throws an exception in the event subscription service, if the switch is not turned on, the program will exit directly? How can users perceive when a node stops without doing so? Since we are concerned about the generation of duplicate data, we should focus on data deduplication.

**Comment by lurais** [comment]
> Isn't that right? I see that when the modified code throws an exception in the event subscription service, if the switch is not turned on, the program will exit directly? There's nothing like that. How do users perceive when a node stops? Since we are concerned about the generation of duplicate data, we should focus on data deduplication.

@lxcmyf If the switch is not turned on, the program will terminate. This behavior is similar to the one before the modification. Previously, if there was an abnormal event subscription, synchronization would stop but the process would continue running. However, existing tools can easily detect when a node stops running. Since forks and other similar situations may arise, it is possible that the subscription service may receive duplicate data, this is another question.

**Comment by lxcmyf** [comment]
> > Isn't that right? I see that when the modified code throws an exception in the event subscription service, if the switch is not turned on, the program will exit directly? There's nothing like that. How do users perceive when a node stops? Since we are concerned about the generation of duplicate data, we should focus on data deduplication.
> 
> @lxcmyf If the switch is not turned on, the program will terminate. This behavior is similar to the one before the modification. Previously, if there was an abnormal event subscription, synchronization would stop but the process would continue running. However, existing tools can easily detect when a node stops running. Since forks and other similar situations may arise, it is possible that the subscription service may receive duplicate data, this is another question.

I think the focus is on why the event subscription service threw an error and then resolved it. Restarting after throwing the error does not provide such a switch
This switch gives people a strange feeling. Since there is a mistake in positioning, it is necessary to solve the problem instead of temporarily ignoring it. We provide underlying services and should not provide such a switch.

**Comment by halibobo1205** [comment]
My point is to make sure that messages can't be lost if the event subscription is turned on .

**Comment by lurais** [comment]
> tron provides underlying services and should not provide such a switch.

@lxcmyf Most people think that the switch is not needed. Therefore, it will be removed to avoid data loss in the event subscription service. However, users with specific requirements can modify the code to suit their needs.

**Comment by bladehan1** [comment]
This switch doesn't do much for me, I don't really like using a service that clearly tells me there's a problem.

**Comment by CarlChaoCarl** [comment]
I've read all of the above and think the ignoreSubscribeErrorSwitchOn switch is unnecessary.

**Comment by lurais** [comment]
> I've read all of the above and think the ignoreSubscribeErrorSwitchOn switch is unnecessary.

@CarlChaoCarl Ok, got it.

**Comment by lurais** [comment]
As discussed below, the config ignoreSubscribeError is unnecessary and will not be added. 
The next question is, if the event subscription function throws an exception, does it need to be retried? Or just stop the node if any exception is found in the event subscription. @317787106 @lxcmyf @ss3344520 @jwrct @halibobo1205

**Comment by halibobo1205** [comment]
`event subscribe exception`: You need to confirm when the exception occurs.

**Comment by lurais** [comment]
> `event subscribe exception`: You need to confirm when the exception occurs.

@halibobo1205 From what I can understand, the event subscription logic seems to work fine without any exceptions. However, there may be cases where we end up throwing exceptions due to incorrect usage of third-party components. For instance, in this scenario https://github.com/tronprotocol/ java-tron/issues/5535, if two threads try to use the Zeromq client simultaneously, it might result in errors. Although it may work if we try pushBlock again, it is not advisable as some data might be lost, and it could lead to other issues in the future.

**Comment by 317787106** [comment]
@halibobo1205 This exception only happens when write to ZeroMQ fails. When event plugin enables, the data is write to a queue that exists in memory so exception may not happen in this scene generaly. ZeroMQ and  event plugin  cannot be used at the same time. ZeroMQ is a native queue, exception happens rarely. I prefer to stop the node  as retrying to write data might not work if IO error occurs.

**Comment by lurais** [comment]
> @lurais This exception only happens when write to ZeroMQ fails. When event plugin enables, the data is write to a queue that exists in memory so exception may not happen in this scene generaly. ZeroMQ and event plugin cannot be used at the same time. ZeroMQ is a native queue, exception happens rarely. I prefer to stop the node as retrying to write data might not work if IO error occurs.

@317787106 Yes , it may be wise to resolve a problem as soon as you find it, to avoid any further complications.

**Comment by lurais** [comment]
@lxcmyf @ss3344520 @jwrct @CarlChaoCarl As discussed earlier, the node will stop if an exception is found in the event subscription. Do you have any suggestions?
