### ISSUE TITLE
Cache data not cleared when connection terminated

### ISSUE THREAD

**Issue by ss3344520** [tronprotocol/java-tron#5720]
#### System information
java-tron version: v4.7.4
OS & Version: Linux & macOS

#### Expected behaviour
Cache data should be cleared when the connection is disconnected.

#### Actual behaviour

The cache clearing data method is used incorrectly, resulting in the data not being cleared, should use the `invalidateAll()` method.
```
advInvReceive.cleanUp();
advInvSpread.cleanUp();
advInvRequest.clear();
syncBlockIdCache.cleanUp();
```

**Comment by jwrct** [comment]
Will this issue cause any serious consequences?

**Comment by lurais** [comment]
What will happen if the cache data not be cleared?

**Comment by ss3344520** [comment]
> Will this issue cause any serious consequences?

No, even if it is not cleared, it will be recycled by the system.

**Comment by ss3344520** [comment]
> What will happen if the cache data not be cleared?

There is no impact, and the results are all recycled by the system.
