### ISSUE TITLE
Shielded smart contracts' test cases cannot be Executed

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/java-tron#5723]
# Rationale

The shielded smart contract is able to transfer TRC-20 tokens from a public address to a shielded address and among shielded addresses. One example is TQEuSEVRk1GtfExm5q9T8a1w84GvgQJ13V. It is an extension of shielded transactions and can ensure the privacy of either the transaction or its initiator.

*   The shielded contract includes some solidity functions, including mint, transfer, burn, etc.
*   Every solidity function is implemented by Java precompile contract.
*   Java precompile contract calls some jni.

The solidity function’s parameter is called shielded input parameters, it is generated by the method in Wallet.class. Related methods involved in Wallet.class include:

1.  createShieldedContractParameters
2.  createShieldedContractParametersWithoutAsk
3.  other private class

The class ShieldedTRC20BuilderTest implements test coverage of these related methods. Still, the prerequisite for running these test cases is to deploy a shielded contract at first because it is necessary to obtain the scaling factor of the constructor that is set when deploying the contract. You need to call the scalingFactor() method of the shielded contract to obtain it. However, a shielded contract cannot be deployed in the test case. If the contract method cannot be called, the test case cannot be executed, the correctness of the relevant functions cannot be verified, and it will be difficult to verify the correctness of any related functions.

```java
 @Ignore
  @Test
  public void createShieldedContractParametersForMint()
      throws ZksnarkException, ContractValidateException, ContractExeException {
    int totalCountNum = 2;
    long leafCount = 0;
    long value = 100L;
    byte[] frontier = new byte[32 * 33];
    ...  
  }
```

# Implementation

There is currently no solution to enable test cases to run. If you have any good suggestions, you are welcome to put them forward and discuss them.

**Comment by lurais** [comment]
Ignoring tests seems reasonable, but using mock classes can improve coverage.

**Comment by 317787106** [comment]
> Ignoring tests seems reasonable, but using mock classes can improve coverage.

@lurais The calling stack is very deep, it's not easy, but i will try it.

**Comment by Mgarcia1996** [comment]
[](url)main

**Comment by 317787106** [comment]
> main

Do you have any good idea?
