### ISSUE TITLE
Issue while adding SR

### ISSUE THREAD

**Issue by Neoblock8** [tronprotocol/java-tron#5734]
Hi,
 Deploying tron private network with 12 seconds. Running perfect without adding SRs. But when i add one  SR the block time will increase by 12. Kindly provide me solution

**Comment by laurenceja** [comment]
[This](https://developers.tron.network/docs/tron-private-chain) is a guide for deploying a private chain. Maybe you can have a try, and if the issue still exists, would you please paste some logs.

**Comment by Neoblock8** [comment]
> [This](https://developers.tron.network/docs/tron-private-chain) is a guide for deploying a private chain. Maybe you can have a try, and if the issue still exists, would you please paste some logs.

Still the error persists. Kindly provide me a solution

**Comment by laurenceja** [comment]
@Neoblock8 Would you please detailed the issue, or paste the error logs?

**Comment by 11111961abc** [comment]
Не добавляй ср.переведи мге денег

пн, 26 февр. 2024 г., 2:15 PM laurenceja ***@***.***>:

**Comment by Neoblock8** [comment]
> @Neoblock8 Would you please detailed the issue, or paste the error logs?

Hi @laurenceja,
Blocks are produced with 12 seconds. Maintanance time interval is **5 mins**. Adding 2 more witness and after vote for added witness. the block time will be changed.
Kindly find the log file.
[cypher.log](https://github.com/tronprotocol/java-tron/files/14404827/cypher.log)

Node version: 4.4.3

**Comment by Neoblock8** [comment]
> > Blocks are produced with 12 seconds. Maintanance time interval is **5 mins**. Adding 2 more witness and after vote for added witness. the block time will be changed.
> 
> According to the log, this SR `1c20033ffcbdde9c4368433715c780ef34a86eb709` has not established a link with other SRs.
> 
> TRON’s consensus mechanism is that all SRs take turns to generate blocks in a fixed order. This SR cannot occupy the slots of other SRs, so whenever an SR is added, the block interval will increase by one slot for a single SR.

Hi @tomatoishealthy,
 How to remove SRs from the SR List. Is there any API?

**Comment by Neoblock8** [comment]
> @Neoblock8
> 
> Sorry, SR is not allowed to be removed if the total number of SRs does not exceed 27.

Thanks @tomatoishealthy  @ss3344520.
Already running one SR  with this command: "java -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -jar  FullNode.jar --witness -
c ./supernode.conf".

Need to run another SR. Those both SRs will produce block one by one. What are all the variables to be modified in supernode.conf file

**Comment by Neoblock8** [comment]
> > [This](https://developers.tron.network/docs/tron-private-chain) is a guide for deploying a private chain
> 
> As laurenceja mentioned, all the parameters that need to be modified are in this doc.
> 
> Is the second SR starting abnormally now?

No. Want to run second SR in same server

**Comment by Neoblock8** [comment]
> @Neoblock8
> 
> Sorry, SR is not allowed to be removed if the total number of SRs does not exceed 27.



> > No. Want to run second SR in same server
> 
> You can try to configure multiple SRs in `localwitness` in the configuration file, so that one service can be used to start multiple SRs
> 
> Or you can start multiple services and modify the ports to avoid port conflicts.

Try to run separate another SR . In that directory, only fullnode.jar and supernode.conf file only there. copied the same conf file and modified the localwitness section with another SR private key. But it will produce blocks from the beginning

**Comment by Neoblock8** [comment]
> > But it will produce blocks from the beginning
> 
> <img alt="image" width="806" src="https://private-user-images.githubusercontent.com/31307926/308157774-447a503e-e228-4829-b287-b4837a5c988a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTU5NjUsIm5iZiI6MTcwOTA5NTY2NSwicGF0aCI6Ii8zMTMwNzkyNi8zMDgxNTc3NzQtNDQ3YTUwM2UtZTIyOC00ODI5LWIyODctYjQ4MzdhNWM5ODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA0NDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMzNhNmJjMzZiYWM2YmNiNmMxMTg3MTk1NzJjMmYyNjQyY2FjODQ1OTdiMTQ1YThlZTY1MWNiMGExMmQ2OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jaR7sszsgXTRoomGYVR0Kj6KHkhZp8hrnAStcNLkuDI"> Refer to this

Thanks @tomatoishealthy. Its working
