### ISSUE TITLE
ILLEGAL_OPERATION Error while Deploying ShieldedTRC20 Contract into a Private Network

### ISSUE THREAD

**Issue by vp-qappi** [tronprotocol/java-tron#5738]
I'm trying to deploy a ShieldedTRC20 Contract ([source code](https://github.com/Federico2014/java-tron/blob/feature/shieldedUSDT/deploy/ShieldedTRC20.sol)) to my private network ([configuration guide](https://developers.tron.network/docs/tron-private-chain)) and I'm getting the ILLEGAL_OPERATION error with a 'resMessage': 'Invalid operation code: opCode[1b];'. I took the bytecode from TronIDE, TronScan and TronBox, neither of them worked.

I have successfully deployed this contract into a VM (TronIDE), public testnets and the mainnet (using TronScan) but now I need to research/adjust a few things so I need a private network here.

Am I doing something wrong?

**Comment by vp-qappi** [comment]
Thank you, it works now!

**Comment by vp-qappi** [comment]
Now I'm trying to send a "mint" transaction which should shield my public tokens. It didn't work, resulting in an "Invalid operation code: opCode[fe];" error. 
I tried to add some params to the committee, but it didn't help:
```
allowShieldedTransaction = 1
fullNodeAllowShieldedTransaction = 1
```
I've also tried putting "fullNodeAllowShieldedTransaction = true" everywhere but no result. 

Any ideas on this?

**Comment by vp-qappi** [comment]
Where exactly? I tried adding to committee - didn't work.

**Comment by lily309** [comment]
Try TRE in TronBox suite.
https://developers.tron.network/reference/test-your-contracts#using-tronbox-runtime-environment-tre

**Comment by vp-qappi** [comment]
I cleaned up my network and started from scratch used the config above. Now mint and transfer work! Now I have some unexpected behaviour with burn method which worked on mainnet but it's no more the same issue from my understanding.
Thank you all very much for help!
