### ISSUE TITLE
How can I calculate how much more space is required for Java Tron on server ?

### ISSUE THREAD

**Issue by sergei-kh** [tronprotocol/java-tron#5745]
We have a total volume of 2.46 TB on our server and now it is 100% full.
Can you please tell me how to calculate how much more space is needed ?

**Comment by halibobo1205** [comment]
@sergei-kh Currently, the main-net data is increasing by about 1G per day.

**Comment by sergei-kh** [comment]
@halibobo1205 It turns out that we will need to constantly increase disk space?

**Comment by halibobo1205** [comment]
It is recommended that at least 1 year of data space be set aside. @sergei-kh

**Comment by sergei-kh** [comment]
@halibobo1205 thank you very much.
And I would also like to clarify, is there a practice to delete, for example, old, irrelevant data over time from the server ?
I just understand that having allocated space for a year, then you will have to increase it again and so on endlessly ?

**Comment by halibobo1205** [comment]
@sergei-kh  You can read about [litefullnode](https://tronprotocol.github.io/documentation-en/developers/litefullnode/).
