### ISSUE TITLE
Are we Windows friendly?

### ISSUE THREAD

**Issue by sfhacker** [tronprotocol/java-tron#5753]
Hi.

I am very very very new to this project, so .... bear with me.

### **Environment**

- Windows 10 x64

Built this project from source.

![image](https://github.com/tronprotocol/java-tron/assets/25817529/42ef7084-2941-4fc7-9a0d-fc8136ad421b)

![image](https://github.com/tronprotocol/java-tron/assets/25817529/7a76ec6e-5d09-416c-a78e-f30a926eb84c)

### **Unit tests**

![image](https://github.com/tronprotocol/java-tron/assets/25817529/da571115-e2e2-40b3-90e7-4c7d9e279d23)

### **RPC/REST Queries**

![image](https://github.com/tronprotocol/java-tron/assets/25817529/396338bb-ea23-4412-943c-c50488cbb72f)

![image](https://github.com/tronprotocol/java-tron/assets/25817529/09a3cd49-92aa-47f0-bf2b-2a35d9a56ffa)

My basic question is:  Do I need to run extra tests or checks to make sure the server is functioning properly?

Thanks in advance.

**Comment by lurais** [comment]
@sfhacker Tron is not recommended to be run on Windows since it has not been verified as a compatible operating system, according to the guide found at https://github.com/tronprotocol/java-tron.

**Comment by halibobo1205** [comment]
@sfhacker Sorry, java-tron is not supported for Windows.
