### ISSUE TITLE
I lost 835 TRON in Sunswap,  How Can I get it back. Showing Failed Transaction Revert 

### ISSUE THREAD

**Issue by brihlogold** [tronprotocol/java-tron#5762]
I lost 835 TROn in Sunswap, My Hard Earned Money is Lost. Can anyone Guide How to Recover back.  See this Transaction:
https://tronscan.org/#/transaction/bd067bee4d5ec597fe437cbe48b1e0592513da79c4752226d13a42fe4c8b86ec

Please help to get it recovered my lost fee of 835 TRON.

**Comment by lxcmyf** [comment]
> I lost 835 TROn in Sunswap, My Hard Earned Money is Lost. Can anyone Guide How to Recover back. See this Transaction: https://tronscan.org/#/transaction/bd067bee4d5ec597fe437cbe48b1e0592513da79c4752226d13a42fe4c8b86ec
> 
> Please help to get it recovered my lost fee of 835 TRON.

@brihlogold 
I'm very sorry about this, the money should not be able to come back. Then it is suggested to refer to similar transaction fees and set a reasonable limit to prevent excessive consumption of money.

**Comment by laurenceja** [comment]
@brihlogold Nobody can revert the online transaction. From the "contractResult" field of this transaction result, we can know  that the error message is: TRANSFER_FROM_FAILED. So maybe you did not approve the "SunSwap V2 Router" to transfer your USDT token. If you don't know how to do it, I will suggest you to contact swap side to solve your issue.
