### ISSUE TITLE
request to wallet/generateaddress shows error: Error 405 HTTP method POST is not supported by this URL

### ISSUE THREAD

**Issue by sergei-kh** [tronprotocol/java-tron#5764]
Hello everyone, please tell me how can I create an account via HTTP API ?
I understand that I must first generate the address and then activate it, but when I try to generate the address I get an error

**Comment by lxcmyf** [comment]
@sergei-kh 
Please refer to:https://developers.tron.network/reference/account-createaccount

**Comment by sergei-kh** [comment]
@lxcmyf 
Thank you very much
Please tell me, if I need to create an account from my application, then unfortunately I cannot use `wallet-cli` to get param: `account_address`. Could you give me any advice ?

**Comment by CarlChaoCarl** [comment]
@sergei-kh 

Hello, what is the error you got when generating the address?

**Comment by sergei-kh** [comment]
@CarlChaoCarl Hello, I have Java-Tron running on my server, but when I make a request like this:
`http://{my_ip}:8090/wallet/generateaddress`
server shows error: `Error 405 HTTP method POST is not supported by this URL`
that is, it’s as if there is no such endpoint

**Comment by lxcmyf** [comment]
> @lxcmyf Thank you very much Please tell me, if I need to create an account from my application, then unfortunately I cannot use `wallet-cli` to get param: `account_address`. Could you give me any advice ?

TRON does not provide an HTTP API for generateaddress. To use wallet cli, please refer to:https://developers.tron.network/docs/account#ways-to-create-accounts

**Comment by CarlChaoCarl** [comment]
> @CarlChaoCarl Hello, I have Java-Tron running on my server, but when I make a request like this: `http://{my_ip}:8090/wallet/generateaddress` server shows error: `Error 405 HTTP method POST is not supported by this URL` that is, it’s as if there is no such endpoint

@sergei-kh 

Hello
The http API of generateaddress has been deleted in https://github.com/tronprotocol/java-tron/pull/5096, mainly for security reasons.
You can use the generateaddress command in wallet-cli.
refer to:
https://tronprotocol.github.io/documentation-en/clients/wallet-cli-command/#generateaddress

**Comment by charil10** [comment]
@sergei-kh refer to 
https://developers.tron.network/reference/account-createaccount
