### ISSUE TITLE
Nile testnet stuck sync. 

### ISSUE THREAD

**Issue by amiDMast** [tronprotocol/java-tron#5767]
Sync unexpectedly stuck on block 45179615...

Run CMD:
```
java -XX:+CMSParallelRemarkEnabled -XX:+UseConcMarkSweepGC -XX:+HeapDumpOnOutOfMemoryError -jar /opt/tron/FullNode.jar -c /opt/tron/test_net_config.conf
```

Java, Tron Versions:
```
java -jar /opt/tron/FullNode.jar -v
OS : Linux
JVM : Oracle Corporation 1.8.0_331 amd64
Git : 7a6a6d8008b28d472100c9fcff2b6b9010829ed0
Version : 4.7.3.1
Code : 18180
```

Could you help me please?

[tron.log](https://github.com/tronprotocol/java-tron/files/14613124/tron.log)

**Comment by junghyun0783** [comment]
me too..... 
Why doesn't it work...suddenly?

**Comment by 1scrooge** [comment]
The same problem

**Comment by 317787106** [comment]
@amiDMast @junghyun0783 @1scrooge Please update java-tron to latest version, 4.7.4. See more detail at https://github.com/tronprotocol/java-tron/releases or https://nileex.io/

**Comment by lxcmyf** [comment]
@amiDMast @junghyun0783 @1scrooge 
Nile has been fully upgraded. Please download the latest Nile branch and restart it.

**Comment by amiDMast** [comment]
@317787106 @lxcmyf Thanks you!!! It works! 👍🏼 =)

**Comment by junghyun0783** [comment]
@lxcmyf 
thank you so much  i got it
