### ISSUE TITLE
tron有类似memory pool概念，如何通过websocket调用？

### ISSUE THREAD

**Issue by qfengthree** [tronprotocol/java-tron#5776]
hi,
请问一个，tron有没有类似EVM的memory pool概念，如何通过websocket调用？

**Comment by laurenceja** [comment]
@qfengthree Websocket does not supported by tron, but http/grpc/jsonrpc. If you have your own tron node and want to subscribe tranctions, you can try the event subscription function: https://developers.tron.network/docs/event-subscription , if you do not deploy a node, the special APIs provided by trongrid are also an alternative way: https://developers.tron.network/reference/get-account-info-by-address.

**Comment by charil10** [comment]
tron does not provide websocket feature. if you wanna get the events in real time use run a fullnode and use zeroMQ to get the data in real time.
 https://developers.tron.network/docs/event-subscription

**Comment by vivian1912** [comment]
@qfengthree Thanks for your contribution to java-tron. May I ask if this issue has been resolved? And do you have any other questions?

**Comment by BeycanDeveloper** [comment]
Hello, I was facing the same problem and that's why I installed [TronSocket.com](https://tronsocket.com/). You can listen to all events as soon as they are published.

```typescript
import TronSocket, { Transaction } from "@tronsocket/sdk/node";

const socket = new TronSocket("your_token_here", true);

await socket.connect().then((connected) => {
    console.log("Connected:", connected);
}).catch((error) => {
    console.error("Error:", error);
});

// All transactions
socket.on("transaction", (tx: Transaction) => {
    const id = tx.transactionId;
});

const usdtAddress = 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t'

// Only USDT transactions
socket.on("transaction", (tx: Transaction) => {
    const id = tx.transactionId;
}, { toAddress: usdtAddress });
```
