### ISSUE TITLE
Does the TRON Network currently have plans to follow up on the Ethereum EL Cancun Upgrade?

### ISSUE THREAD

**Issue by lily309** [tronprotocol/java-tron#5777]
We see that the Ethereum EL Cancun Upgrade has been activated on the mainnet and this upgrade contains several improvements. As an EVM-compatible blockchain, does the TRON Network have any plans to consider following suit in the near future?

Below is a detailed list of the upgrade features and the instructions that have been added or modified, does TRON need to support all or just some of these features?
- [ ] [EIP-1153: Transient storage opcodes](https://eips.ethereum.org/EIPS/eip-1153)
    - [ ] `TLOAD (0x5c)` **new!**
    - [ ] `TSTORE (0x5d)` **new!**
- [ ] [EIP-4788: Beacon block root in the EVM](https://eips.ethereum.org/EIPS/eip-4788)
    - [ ] Is there any reference to the concept of deploying system contracts in hard fork upgrades?
- [ ] [EIP-4844: Shard Blob Transactions](https://eips.ethereum.org/EIPS/eip-4844)
    - [ ] `BLOBHASH (0x49)` **new!**
- [ ] [EIP-5656: MCOPY - Memory copying instruction](https://eips.ethereum.org/EIPS/eip-5656)
    - [ ] `MCOPY (0x5e)` **new!**
- [ ] [EIP-6780: SELFDESTRUCT only in same transaction](https://eips.ethereum.org/EIPS/eip-6780)
    - [ ] `SELFDESTRUCT (0xff)` **changed!**
- [ ] [EIP-7516: BLOBBASEFEE opcode](https://eips.ethereum.org/EIPS/eip-7516)
    - [ ] `BLOBBASEFEE (0x4a)` **new!**

We also see that deploying contracts on TRON requires the use of the TRON-specific Solidity compiler. Are there any plans to upgrade the support for the Solidity compiler?

Looking forward to your answers. Thank you!

**Comment by ferdinand026** [comment]
Due to TRON’s unique mechanism, for example the stake system, it needs special TVM instructions, so deploying such smart contract which related with TRON’s unique features on TRON requires to use the TRON solidiy compiler, but not Etherum solidity sompiler. But for smart cotract which have nothing related with TRON’s unique features, we can use either of them.

**Comment by lily309** [comment]
@ferdinand026 

Thank you for your answer.

First of all, are there any compatible upgrades planned?

Second, the Ethereum Solidity compiler has been updated to [v0.8.25](https://github.com/ethereum/solidity/releases/tag/v0.8.25) and the default EVM version is set to `cancun`, which means that the bytecode of some contracts compiled with the default configuration of the Ethereum Solidity compiler can no longer run on TRON, as the operations for memory copies in it will use the `MCOPY` instruction in place of the former `MLOAD/MSTORE`.

Once again, thank you sincerely for your answer.

**Comment by yanghang8612** [comment]
@lily309 

The TRON community is already moving forward with compatibility plans. Details will be released to the [TIPs](https://github.com/tronprotocol/tips) repository in the near future, so stay tuned.

If you have any questions, please move to the [TIPs](https://github.com/tronprotocol/tips) repository to discuss. Thank you.

**Comment by yanghang8612** [comment]
@tomatoishealthy

Yes, for the instructions in `EIP-4844` as well as `EIP-7516`, we tend to implement them simply, returning only 0 or the default value. For `EIP-4788`, we tend not to implement them since there are no new instructions or pre-compiled contracts.

**Comment by Federico2014** [comment]
> @tomatoishealthy
> 
> Yes, for the instructions in `EIP-4844` as well as `EIP-7516`, we tend to implement them simply, returning only 0 or the default value. For `EIP-4788`, we tend not to implement them since there are no new instructions or pre-compiled contracts.

There have already deployed [TRON zkEVM testnet](https://test-zkevm.bt.io/bridge/), we may need to reconsider whether TRON should support  EIP-4844 or not.
