### ISSUE TITLE
Mandatory upgrade to 4.7.4

### ISSUE THREAD

**Issue by mercy1230** [tronprotocol/java-tron#5781]
My current FullNode version is 4.7.2,
Do I need to Mandatory update to 4.7.4 ?

thanks for your kindly answer

**Comment by Diamondb32** [comment]
> My current FullNode version is 4.7.2, Do I need to Mandatory update to 4.7.4 ?
> 
> thanks for your kindly answer

**Comment by ferdinand026** [comment]
> My current FullNode version is 4.7.2, Do I need to Mandatory update to 4.7.4 ?
> 
> thanks for your kindly answer

Yes, we'd better upgrade the node to 4.7.4 before the deadline, otherwise, node synchronization may be affected once a new proposal is launched.

**Comment by Diamondb32** [comment]
Ok great
