### ISSUE TITLE
Data synchronization

### ISSUE THREAD

**Issue by mercy1230** [tronprotocol/java-tron#5782]
If I don’t download the snapshot data, how long will it take to synchronize to the latest block ?

**Comment by endiaoekoe** [comment]
> If I don’t download the snapshot data, how long will it take to synchronize to the latest block ?

hi, @mercy1230 
it will take about 3 or 4 months to synchronize from genesis block to recent block if you choose not use snapshot.

**Comment by mercy1230** [comment]
> > If I don’t download the snapshot data, how long will it take to synchronize to the latest block ?
> 
> hi, @mercy1230 it will take about 2 months(in perfect condition) ~ 4 months to synchronize from the genesis block to the recent block if you choose not to use the snapshot.

thank you.
