### ISSUE TITLE
Download the snapshot of FullNode data

### ISSUE THREAD

**Issue by mercy1230** [tronprotocol/java-tron#5787]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Discord](https://discord.gg/cGKSsRVCGm) or [Telegram](https://t.me/TronOfficialDevelopersGroupEn).

![image](https://github.com/tronprotocol/java-tron/assets/136230486/536b0028-76b1-4c4a-9340-6fdd4edd1d85)

What is the use of the second file in the picture?

Is it a necessary file ?

**Comment by laurenceja** [comment]
@mercy1230 FullNode_output-directory.tgz is the DB snapshot file, FullNode_output-directory.tgz.md5sum is the verification file which is used to verify the integrity of FullNode_output-directory.tgz file.

**Comment by vivian1912** [comment]
@mercy1230 Thanks for your contribution to java-tron. May I ask if this issue has been resolved? And do you have any other questions?

**Comment by vivian1912** [comment]
This issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
