### ISSUE TITLE
> When I tried to upgrade FullNode 4.7.4, this error occurred, indicating that the database was damaged;

### ISSUE THREAD

**Issue by aguinaldok4** [tronprotocol/java-tron#5788]
> When I tried to upgrade FullNode 4.7.4, this error occurred, indicating that the database was damaged;
> 
> But when I roll back to the previous version 4.7.2, it can start normally.
> 
> Why？

hi, @mercy1230 
the error messages just give the methods to solve this 'start failed' problem. I recommend you can delete the database directory(output-directory/database) and restart. then it may start normally.
as for the reason why it started well when rolling back to the previous version, can you provide more error messages during node start up, so it will be better to investigate the root cause?

_Originally posted by @endiaoekoe in https://github.com/tronprotocol/java-tron/issues/5780#issuecomment-2016978217_

**Comment by vivian1912** [comment]
Duplicated with #5780 , so close this issue.
