### ISSUE TITLE
Log In Issues

### ISSUE THREAD

**Issue by puppimp05** [tronprotocol/java-tron#579]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
In trying to log in to my account on the tron site, I created some time ago, with info saved on my Lastpass manager, the system tells me incorrect email/ password. I try to reset password, it tells me Email is not in the system. I try to create a new registry, it tells me email is already used, now in trying to create a new registry, with a different email of mine and it tells me email is already in use. I have cleaned my cache, used both Firefox and Google, even tried with a VPN, all to no avail. My original email in the system is PUPPIMP@YAHOO.COM

2. What did you expect to see?

access to tron's site

3. What did you see instead?
the above

**Comment by huzhenyuan** [comment]
Please move the bug to https://github.com/tronprotocol/wallet-web
@puppimp05
