### ISSUE TITLE
Open my wallet 

### ISSUE THREAD

**Issue by A1985J09** [tronprotocol/java-tron#5792]
# Background

# Rationale

Why should this feature exist?

What are the use-cases?

# Specification

# Test Specification

# Scope Of Impact

# Implementation

Do you have ideas regarding the implementation of this feature?

Are you willing to implement this feature?

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no content basically. Please feel free to re-open it if you have suggestions, comments or issues about java-tron , thanks.
