### ISSUE TITLE
unable to sync on nile testnet.

### ISSUE THREAD

**Issue by mookk4ever** [tronprotocol/java-tron#5793]
Ever since I downloaded I have downloaded the latest snapshot and replace the output-directory with it however the block is still stuck at 160.

```
============ Peer stats: all 0, active 0, passive 0


13:41:42.850 INFO  [peer-manager] [net](PeerManager.java:152) 

============ Peer stats: all 0, active 0, passive 0
```

this is my startup
```
nohup java -Xms9G -Xmx9G -XX:ReservedCodeCacheSize=256m \
             -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m \
             -XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails \
             -XX:+PrintGCDateStamps  -Xloggc:gc.log \
             -XX:+UseConcMarkSweepGC -XX:NewRatio=2 \
             -XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled \
             -XX:+HeapDumpOnOutOfMemoryError \
             -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=70 \
             -jar FullNode-Nile-4.7.4.jar -c test_net_config.conf >> nohup.log 2>&1 &
```

**Comment by ferdinand026** [comment]
@mookk4ever You said that the block was still stuck at 160. Did you mean the block number is 160? If you downloaded the latest db snapshot, the block number should be more than that value, so would you please re-download at https://database.nileex.io/# . And use the node configuration file [here](https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf) to have a try.

**Comment by mookk4ever** [comment]
Hi yes, issue is resolved! add -d parameter to point toward output-directory.
