### ISSUE TITLE
About `Event Plugin MongoDb`

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5801]
I want in https://developers.tron.network/docs/event-plugin-deployment-mongodb mongo db event plugin,set start block for parse block in mongo db, for example current block of my node is 6000000,and always mongo event plugin start from current block,but I want start parse from block : 500 for example,how can fix it ? 

I set 
![image](https://github.com/tronprotocol/java-tron/assets/80700084/80b4b9fc-4bcf-48d7-9b86-c1dff639ddda)

I test hex string instead of block number , for example put 0x3a0b92a instead of 60864810 still have that problem in filter and 
don't work,help me plz.

**Comment by CarlChaoCarl** [comment]
@kasrakhamesi 

Can you post your complete config.conf below?

**Comment by kasrakhamesi** [comment]
> The node will not send events in already processed blocks to subscriber. That means that if the block with block number 500 has already been solidified, the events in it will not send to event plugin. You can try the below steps to receive events starting from the value of "fromblock".
> 
> 1. stop the node
> 
> 2. delete all db of the node
> 
> 3. configure the fromblock to 500
> 
> 4. restart the node

its very bad solution.because every time when miss a blockNumber,should delete node chaindata and resync.are you sure its best solution?

**Comment by ferdinand026** [comment]
I only give your an example of how to use the fromblock configuration item. Once the node start running, it will send all the events in all blocks it processing after the node startup, but not include the blocks which processed before the node startup.

**Comment by kasrakhamesi** [comment]
> I only give your an example of how to use the fromblock configuration item. Once the node start running, it will send all the events in all blocks it processing after the node startup, but not include the blocks which processed before the node startup.

This solution is inadequate. Whether I set 'fromBlock' or not, there is no difference because block data needs to be removed every time. Therefore, 'fromBlock' is not useful in this filter

**Comment by vivian1912** [comment]
@kasrakhamesi Thank you for your question. May I ask if this issue has been resolved? And is anything unclear?

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
