### ISSUE TITLE
Tron gRPC API from thirdparty

### ISSUE THREAD

**Issue by kasrakhamesi** [tronprotocol/java-tron#5804]
Where can I buy the gRPC Tron API request package?

**Comment by 11111961abc** [comment]
Вот номер счета 3900 рублей 2200380389965260

пт, 19 апр. 2024 г., 21:30 Kasra Khamesi ***@***.***>:

**Comment by ferdinand026** [comment]
@kasrakhamesi I got the information from the developer document: https://developers.tron.network/docs/networks#mainnet-infrastructure-providers

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
