### ISSUE TITLE
Should we support EIP-4844?

### ISSUE THREAD

**Issue by 3for** [tronprotocol/java-tron#5810]
# Background
[EIP-4844](https://eips.ethereum.org/EIPS/eip-4844) , also known as proto-danksharding, so end-users are expected to benefit from lower gas fees on layer two (L2) transactions following proto-danksharding.

EIP-4844 introduces:
1. **Blob transaction**: a new transaction format for “blob-carrying transactions”. Blob-carrying transactions are similar to regular Ethereum transactions, but they carry some additional data, known as a blob. Compared to the current immutable calldata storage and read-only memory, blobs have much larger storage and are cheaper. Blob cannot be accessed by EVM execution, but its commitment can be accessed. 
2. **Point evaluation precompile**: Add a precompile that verifies a KZG proof which claims that a blob (represented by a commitment) evaluates to a given value at a given point.
3. **BLOBHASH opcode**:  a new opcode to get versioned hashes.
4. **excess_blob_gas and blob_gas_used**: a new type of gas pricing for blob.
5. **verify_kzg_proof() and verify_blob_kzg_proof_batch()**: new cryptographic methods to verify the corresponding proofs.

EIP-4844 will influence the tx fees of L2 rollups ecosystem on TRON. EIP-4844 is expected to reduce tx fees by 2X - 5X according to Polygon team [evaluation](https://polygon.technology/blog/eip-4844-is-coming-to-polygon).

# Rationale
Rollups are in the short and medium term, and possibly in the long term, the only trustless scaling solution for Tron. We have already deployed [TRON zkEVM testnet](https://test-zkevm.bt.io/bridge/)  based on Polygon zkEVM technology.  So we should consider to support EIP-4844 to decrease the tx fees for Tron zkEVM and future L2 rollups ecosystem.

**Comment by halibobo1205** [comment]
@3for The previous discussion, which you can continue here:
- #5777

**Comment by 3for** [comment]
We should prepare for the future. No new progress so far.

**Comment by YuMenGuan** [comment]
> We should prepare for the future. No new progress so far.

@3for  Obviously, things related to layer2  is not urgent for Tron, considering the fee of Tron transaction is low  and competitive, also TPS of Tron meets current needs. If a protocol is not urgent and involving a lot of work(Layer2 is not a easy thing), the team of Tron maybe don't have enough motivation to implement.
Not all the protocols of Ethereum suit Tron.

**Comment by simbadMarino** [comment]
Hello @3for , I took a look on your project based on some recent interest from our community about TRON L2s and recen EIPs, I noticed you are using BTTC as well, is this only for bridging purposes or you are bringing ZKRollups for BTTC? 
Are you part of the BTTC team?

I'll be glad to know more about this development and how we can prepare TRON/BTTC for the future.

**Comment by 3for** [comment]
> Hello @3for , I took a look on your project based on some recent interest from our community about TRON L2s and recen EIPs, I noticed you are using BTTC as well, is this only for bridging purposes or you are bringing ZKRollups for BTTC? Are you part of the BTTC team?
> 
> I'll be glad to know more about this development and how we can prepare TRON/BTTC for the future.

Hi, @simbadMarino , our current [TRON zkEVM Testnet](https://test-zkevm.bt.io/bridge) with Nile testnet is alive since last year, and we've done several upgrades for it. I'm part of the TRON team.

**Comment by simbadMarino** [comment]
Great to hear @3for ! I have some questions about this:

- As per the home page, it looks like this is an EVM fully compatible chain. Do you see any advantage in doing a TVM implementation over an EVM one?
- How different is this implementation from Scrolls?
- If this project moves forward to mainnet, how do you envision the relationship between TRON Mainnet as L1, this TRON zkEVM, and the BitTorrent Chain will be?

Thanks in advance!

**Comment by Federico2014** [comment]
@simbadMarino As for your questions:
- It is an EVM-compatible L2 chain. Implementing zkTVM can be convenient for the TRON ecosystem but may bring some technical challenges. This is not an easy task.
- The zkEVM is based on the Polygon zkEVM stack. You can check the difference between Polygon zkEVM and Scroll.
- TRON zkEVM and BTTC are both Layer 2 of the TRON network. The difference is that TRON zkEVM is zkRollup, while BTTC is a side chain.

I hope this will offer some help.
