### ISSUE TITLE
A NullPointerException was thrown while the node was running

### ISSUE THREAD

**Issue by CSGT-KZ** [tronprotocol/java-tron#5812]
#### System information
Java-tron version: v4.7.4
OS & Version: Linux & macOS

#### Expected behavior
NullPointerException should not be thrown.

#### Actual behavior
When checking the node's log, I found a NullPointerException:
<img width="639" alt="image" src="https://github.com/tronprotocol/java-tron/assets/169013091/7c3271b7-fdd5-42f9-a2ef-a7adf37b3b92">

#### Frequency
1 time

**Comment by ss334452** [comment]
@CSGT-KZ  There is a concurrent access problem with the fetchBlockInfo object. The concurrency steps are as follows.

1. The `request block thread` assigns a value to the fetchBlockInfo object
3. The `fetchBlock thread` sets the fetchBlockInfo object to null
4. A null pointer exception occurs when the `request block thread` accesses the fetchBlockInfo object.

**Comment by jwrct** [comment]
@ss334452 What is the probability of this concurrency issue occurring?

**Comment by zeusoo001** [comment]
@jwrct The probability of occurrence is extremely low and has no impact on the system.

**Comment by jwrct** [comment]
@zeusoo001 Even though the probability of this concurrency issue occurring is low and does not affect the system, after all, the program threw an exception, which is not the expected result, right? Do you think it's necessary to fix this problem? Or maybe you already have a solution to fix it?

**Comment by zeusoo001** [comment]
@jwrct  Considering the strictness of the code, it needs to be repaired. The repair plan is not to directly access the `fetchBlockInfo` object when printing the log. The modification is as follows.

```
          fetchBlockInfo = new FetchBlockInfo(sha256Hash, peer, System.currentTimeMillis());
          logger.info("Set fetchBlockInfo, block: {}, peer: {}, time: {}", sha256Hash,
              fetchBlockInfo.getPeer().getInetAddress(), fetchBlockInfo.getTime());
```

change into

```
          long now = System.currentTimeMillis();
          fetchBlockInfo = new FetchBlockInfo(sha256Hash, peer, now);
          logger.info("Set fetchBlockInfo, block: {}, peer: {}, time: {}", sha256Hash,
              peer.getInetAddress(), now);
```

**Comment by zeusoo001** [comment]
Fixed in this PR： https://github.com/tronprotocol/java-tron/pull/5831
