### ISSUE TITLE
The node reported "Handle sync block error" and no blocks were synchronized in the next 20 seconds.

### ISSUE THREAD

**Issue by liuyifei001** [tronprotocol/java-tron#5813]
#### System information
Java-tron version: v4.7.4
OS & Version: Linux & macOS

#### Expected behavior
Synchronization of blocks should be normal, no exceptions should occur.

#### Actual behavior
The node reported a `Handle sync block error` exception, and no blocks were synchronized for 20 seconds after the exception occurred.

![image](https://github.com/tronprotocol/java-tron/assets/169016168/255128ba-3648-4a01-b6b7-6eaebdddb95a)

**Comment by zeusoo001** [comment]
@liuyifei001  The pop function threw an exception. It should be that `syncBlockToFetch object` has multi-threaded access.
```
if (blockId.equals(peer.getSyncBlockToFetch().peek())) {
        peer.getSyncBlockToFetch().pop();
```

**Comment by jwrct** [comment]
@zeusoo001  Can you please describe in detail the scenario of multiple-thread access? For example, which threads will access syncBlockToFetch? What scenarios can cause program exceptions?

**Comment by zeusoo001** [comment]
@jwrct Three threads accessed the syncBlockToFetch variable at the same time.

Thread 1: When the peer disconnects, the clear method of the object is called.
Thread 2: When processing the synchronization block, the pop method of the object is called.
Thread 3: When processing the chain inventory message, the pop method of the object is called.

Concurrent access by thread 1 and thread 2 may cause the exception. When thread 2 calls the peek method of the object, then thread 1 clears the data, and then an exception is thrown when thread 2 pops the data.

**Comment by jwrct** [comment]
@zeusoo001 As you said, I have a question, do Thread 1 and Thread 3 have concurrent access to the syncBlockToFetch issue? What about Thread 2 and Thread 3?

**Comment by zeusoo001** [comment]
@jwrct Thread 3 uses the try catch statement to handle the concurrency problem, and there is no problem. Thread 2 and thread 3 use locks directly, and there is no concurrency problem.

**Comment by zeusoo001** [comment]
Fixed in this PR: https://github.com/tronprotocol/java-tron/pull/5832
