### ISSUE TITLE
Compilation build failed

### ISSUE THREAD

**Issue by Neoblock8** [tronprotocol/java-tron#5816]
Hi,
 Trying to compile with some modifications getting this error.
 
 ../common/zksnark/JLibrustzcash.java:24: error: cannot find symbol
  private static Librustzcash INSTANCE = LibrustzcashWrapper.getInstance();
                 ^
  symbol:   class Librustzcash
  location: class JLibrustzcash
  
  /common/zksnark/JLibsodium.java:13: error: cannot find symbol
  private static Libsodium INSTANCE = LibsodiumWrapper.getInstance();
                 ^
  symbol:   class Libsodium
  location: class JLibsodium
2 errors

How to overcome this error? Kindly guide me to solve this error

**Comment by liuyifei001** [comment]
@Neoblock8 Can you specify your compile environment? Such as OS/JVM/JDK, etc.

**Comment by 317787106** [comment]
@Neoblock8 What's your modifications?

**Comment by endiaoekoe** [comment]
hi, @Neoblock8 
seems like the modifications result in missing Librustzcash and Libsodium class definitions.
to resolve this issue, it is recommended you do the following checking, as below:

1. you step through your changes to ensure that the dependency libraries are correctly introduced and configured, 
2. the class paths are correct, 
3. the source files exist,
4. the dependency library versions are compatible with the code.

By step-by-step troubleshooting the possible causes, you should be able to resolve the missing Librustzcash and Libsodium class definitions.

**Comment by Karthigasrini** [comment]
> @Neoblock8 Can you specify your compile environment? Such as OS/JVM/JDK/Version, etc.

OS: Ubuntu
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-8u372-ga~us1-0ubuntu1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

**Comment by Neoblock8** [comment]
> @Neoblock8 Can you specify your compile environment? Such as OS/JVM/JDK/Version, etc.

OS: Ubuntu
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-8u372-gaus1-0ubuntu118.04-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

**Comment by Neoblock8** [comment]
> @Neoblock8 What's your modifications?

Modified package of tron to test

**Comment by Neoblock8** [comment]
> hi, @Neoblock8 seems like the modifications result in missing Librustzcash and Libsodium class definitions. to resolve this issue, it is recommended you do the following checking, as below:
> 
> 1. you step through your changes to ensure that the dependency libraries are correctly introduced and configured,
> 2. the class paths are correct,
> 3. the source files exist,
> 4. the dependency library versions are compatible with the code.
> 
> By step-by-step troubleshooting the possible causes, you should be able to resolve the missing Librustzcash and Libsodium class definitions.

Hi @endiaoekoe,
Need to run a private tron network. Without modifying tron packages it works fine, But i change all the tron packages and imported statements from tron to test. Compilation and building code successful. Getting this error while running the node.

![image](https://github.com/tronprotocol/java-tron/assets/81068101/0af01110-d15a-4ba8-9db7-9618410406d6)

**Comment by 317787106** [comment]
@Neoblock8 LibrustzcashJNI comes from another project: 
`compile 'io.github.tronprotocol:zksnark-java-sdk:1.0.0'`. 
Source project is https://github.com/tronprotocol/zksnark-java-sdk. 
You can see LibrustzcashJNI has fixed path: org_tron_common_zksnark_Librustzcash_LibrustzcashJNI.h at https://github.com/tronprotocol/zksnark-java-sdk/blob/master/cpp/src/LibrustzcashJNIImpl.cpp
If you want it to works fine, you may have to change some path, recompile this zksnark-java-sdk, import this jar directly instead of remote import. It may be al little complicated.

**Comment by Karthigasrini** [comment]
> @Neoblock8 LibrustzcashJNI comes from another project: `compile 'io.github.tronprotocol:zksnark-java-sdk:1.0.0'`. Source project is https://github.com/tronprotocol/zksnark-java-sdk. You can see LibrustzcashJNI has fixed path: org_tron_common_zksnark_Librustzcash_LibrustzcashJNI.h at https://github.com/tronprotocol/zksnark-java-sdk/blob/master/cpp/src/LibrustzcashJNIImpl.cpp If you want it to works fine, you may have to change some path, recompile this zksnark-java-sdk, import this jar directly instead of remote import. It may be a little complicated.


Hi @317787106,
Can you please guide me to import the jar file directly rather than remote import

**Comment by 317787106** [comment]
@Karthigasrini There are 3 steps to import local jar:

1. mkdir directory libs in chainbase.
2. put compiled jar `zksnark-java-sdk.jar` into chainbase/libs/
3. edit file chainbase/build.gradle:
- comment `compile 'io.github.tronprotocol:zksnark-java-sdk:1.0.0'`
- add `fileTree(dir: 'libs', include: 'zksnark-java-sdk.jar')`

**Comment by Karthigasrini** [comment]
> @Karthigasrini There are 3 steps to import local zksnark-java-sdk.jar:
> 
> 1. mkdir directory libs in chainbase.
> 2. put compiled jar `zksnark-java-sdk.jar` into chainbase/libs/
> 3. edit file chainbase/build.gradle:
> 
> * comment `compile 'io.github.tronprotocol:zksnark-java-sdk:1.0.0'`
> * add `fileTree(dir: 'libs', include: 'zksnark-java-sdk.jar')`

Hi @317787106,

As you said, I modified in build.gradle file still having same issue

**Comment by Karthigasrini** [comment]
> @Karthigasrini There are 3 steps to import local zksnark-java-sdk.jar:
> 
> 1. mkdir directory libs in chainbase.
> 2. put compiled jar `zksnark-java-sdk.jar` into chainbase/libs/
> 3. edit file chainbase/build.gradle:
> 
> * comment `compile 'io.github.tronprotocol:zksnark-java-sdk:1.0.0'`
> * add `fileTree(dir: 'libs', include: 'zksnark-java-sdk.jar')`

Hi @317787106 
Kindly give me a solution

**Comment by 317787106** [comment]
@Karthigasrini It's a little complicated. I will try to test it when I am free.

**Comment by Karthigasrini** [comment]
> @Karthigasrini It's a little complicated. I will try to test it when I am free.

Thanks @317787106. Kindly test and provide a best solution asap

**Comment by liuyifei001** [comment]
@Karthigasrini Can you specify the steps that how do you modify package of tron to test ?

**Comment by 317787106** [comment]
@Karthigasrini What changes have you made ? How do you modify package of tron to test ?

**Comment by Karthigasrini** [comment]
> @Karthigasrini What changes have you made ? How do you modify package of tron to test ?

I have rename all tron to test and changed the tron package name to test. 
Then download the ["https://github.com/tronprotocol/zksnark-java-sdk"] zksnark package and renamed tron to test then compile and make the files. And pushed this files in another github repo, putting this repo name in tron source code

**Comment by 317787106** [comment]
@Karthigasrini I have compiled the project successful, it is complicated and time cost. You can do it as following:
1. Modify and recompile the project `zksnark-java-sdk`:

- Add modifier public before `class Librustzcash` 
- comile this project, use `mvn clean package`
- get `zksnark-java-sdk-1.0.0.jar` under directory `zksnark-java-sdk/target/`.
- copy it to chainbase/libs under java-tron project

2. modify chainbase/build.gradle
```
    compile fileTree(dir: 'libs', include: 'zksnark-java-sdk-1.0.0.jar')
    //compile 'io.github.tronprotocol:zksnark-java-sdk:1.0.0'
```

3. Rename Other package and class. such as:
```
package org.tron. -> package org.brown.
import org.tron. -> import org.brown.  
import static org.tron. -> import static org.brown.
import org.brown.p2p -> import org.tron.p2p
org.tron.protos. -> org.brown.protos.
```
4. rename proto:
```
org.tron. -> org.brown.
```

**Comment by Karthigasrini** [comment]
> @Karthigasrini I have compiled the project successful, it is complicated and time cost. You can do it as following:
> 
> 1. Modify and recompile the project `zksnark-java-sdk`:
> 
> * Add modifier public before `class Librustzcash`
> * comile this project, use `mvn clean package`
> * get `zksnark-java-sdk-1.0.0.jar` under directory `zksnark-java-sdk/target/`.
> * copy it to directory chainbase/libs/ under java-tron project
> 
> 2. modify chainbase/build.gradle
> 
> ```
>     compile fileTree(dir: 'libs', include: 'zksnark-java-sdk-1.0.0.jar')
>     //compile 'io.github.tronprotocol:zksnark-java-sdk:1.0.0'
> ```
> 
> 3. Rename Other package and java class. such as:
> 
> ```
> mv actuator/src/main/java/org/tron/ actuator/src/main/java/org/brown/
> mv chainbase/src/main/java/org/tron/ chainbase/src/main/java/org/brown
> mv common/src/main/java/org/tron/ common/src/main/java/org/brown/
> mv consensus/src/main/java/org/tron/ consensus/src/main/java/org/brown
> mv crypto/src/main/java/org/tron crypto/src/main/java/org/brown
> mv example/actuator-example/src/main/java/org/tron/ example/actuator-example/src/main/java/org/brown
> mv framework/src/main/java/org/tron/ framework/src/main/java/org/brown
> mv framework/src/test/java/org/tron/ framework/src/test/java/org/brown/
> mv plugins/src/main/java/org/tron/ plugins/src/main/java/org/brown/
> mv plugins/src/test/java/org/tron/ plugins/src/test/java/org/brown/
> ```
> 
> replace import:
> 
> ```
> package org.tron. -> package org.brown.
> import org.tron. -> import org.brown.  
> import static org.tron. -> import static org.brown.
> import org.brown.p2p -> import org.tron.p2p
> org.tron.protos. -> org.brown.protos.
> ```
> 
> modify any other necessary class.
> 
> 5. Modify all .proto files:
> 
> ```
> org.tron. -> org.brown.
> ```
> 
> 6. compile to find if there is any other error:
> 
> ```
> ./gradlew clean build -x test --info
> ```

Thanks a lot @317787106. I will check and let you know

**Comment by Karthigasrini** [comment]
> @Karthigasrini I have compiled the project successful, it is complicated and time cost. You can do it as following:
> 
> 1. Modify and recompile the project `zksnark-java-sdk`:
> 
> * Add modifier public before `class Librustzcash`
> * comile this project, use `mvn clean package`
> * get `zksnark-java-sdk-1.0.0.jar` under directory `zksnark-java-sdk/target/`.
> * copy it to directory chainbase/libs/ under java-tron project
> 
> 2. modify chainbase/build.gradle
> 
> ```
>     compile fileTree(dir: 'libs', include: 'zksnark-java-sdk-1.0.0.jar')
>     //compile 'io.github.tronprotocol:zksnark-java-sdk:1.0.0'
> ```
> 
> 3. Rename Other package and java class. such as:
> 
> ```
> mv actuator/src/main/java/org/tron/ actuator/src/main/java/org/brown/
> mv chainbase/src/main/java/org/tron/ chainbase/src/main/java/org/brown
> mv common/src/main/java/org/tron/ common/src/main/java/org/brown/
> mv consensus/src/main/java/org/tron/ consensus/src/main/java/org/brown
> mv crypto/src/main/java/org/tron crypto/src/main/java/org/brown
> mv example/actuator-example/src/main/java/org/tron/ example/actuator-example/src/main/java/org/brown
> mv framework/src/main/java/org/tron/ framework/src/main/java/org/brown
> mv framework/src/test/java/org/tron/ framework/src/test/java/org/brown/
> mv plugins/src/main/java/org/tron/ plugins/src/main/java/org/brown/
> mv plugins/src/test/java/org/tron/ plugins/src/test/java/org/brown/
> ```
> 
> replace import:
> 
> ```
> package org.tron. -> package org.brown.
> import org.tron. -> import org.brown.  
> import static org.tron. -> import static org.brown.
> import org.brown.p2p -> import org.tron.p2p
> org.tron.protos. -> org.brown.protos.
> ```
> 
> modify any other necessary class.
> 
> 5. Modify all .proto files:
> 
> ```
> org.tron. -> org.brown.
> ```
> 
> 6. compile to find if there is any other error:
> 
> ```
> ./gradlew clean build -x test --info
> ```

Hi @317787106,
 Geeting same error while compiling "zksnark-java-sdk"

**Comment by 317787106** [comment]
@Karthigasrini what's the error?

**Comment by Karthigasrini** [comment]
> @Karthigasrini what's the error?

![328849617-0af01110-d15a-4ba8-9db7-9618410406d6](https://github.com/tronprotocol/java-tron/assets/30004506/8457e3ab-d0e9-4391-a273-06f7b3fb9d03)

**Comment by 317787106** [comment]
@Karthigasrini Please make use this not changed: 
```
private static org.tron.common.zksnark.Librustzcash INSTANCE;
```

I have successfully run the node after changes. Don't forget to modify .gradle, logback.xml, TransactionRegister and CommonConfig class.

**Comment by 317787106** [comment]
@Karthigasrini Have you fix this problem? If you did, please tell me.

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
