### ISSUE TITLE
Why I get an empty response GetAccountResource? 

### ISSUE THREAD

**Issue by kandrukKV** [tronprotocol/java-tron#5817]
Please help me figure it out. There is an example request in the documentation:

`curl --request POST \
     --url https://api.shasta.trongrid.io/wallet/getaccountresource \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "address": "TZ4UXDV5ZhNW7fb2AMSbgfAEZ7hWsnYS2g",
  "visible": true
}
'`

I use a different address and get an empty object {}

`curl --request POST \
     --url https://api.shasta.trongrid.io/wallet/getaccountresource \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "address": "TFRCrr4bH9HRhT8TtBFB3LixKrf31DD4qC",
  "visible": true
}
'`

Account TFRCrr4bH9HRhT8TtBFB3LixKrf31DD4qC is active.

[tronscanLink to:TFRCrr4bH9HRhT8TtBFB3LixKrf31DD4qC ](https://tronscan.org/#/address/TFRCrr4bH9HRhT8TtBFB3LixKrf31DD4qC)

What am I doing wrong? How do I request the data correctly?

**Comment by ferdinand026** [comment]
@kandrukKV "TFRCrr4bH9HRhT8TtBFB3LixKrf31DD4qC" is an inactivated address on shasta testnet. Sending some TRX into it to activate this address, then execute the curl command again, you will get the resource information of this address.

**Comment by kandrukKV** [comment]
Thank you so much for your reply!

**Comment by YuMenGuan** [comment]
> @kandrukKV "TFRCrr4bH9HRhT8TtBFB3LixKrf31DD4qC" is an inactivated address on shasta testnet. Sending some TRX into it to activate this address, then execute the curl command again, you will get the resource information of this address.
> 
> https://api.shasta.trongrid.io/ is the shasta testnet endpoint. and your Tronscan query link is the TRON mainnet.



> @kandrukKV "TFRCrr4bH9HRhT8TtBFB3LixKrf31DD4qC" is an inactivated address on shasta testnet. Sending some TRX into it to activate this address, then execute the curl command again, you will get the resource information of this address.
> 
> https://api.shasta.trongrid.io/ is the shasta testnet endpoint. and your Tronscan query link is the TRON mainnet.

Is there any other way to activate a new address besides sending sone TRX?
