### ISSUE TITLE
API Services Fail to Start Silently

### ISSUE THREAD

**Issue by halibobo1205** [tronprotocol/java-tron#5820]
## Software Versions

OS: Linux
JVM: Oracle Corporation 1.8.0_161 AMD64
Version: 4.7.4
Code: 18260

## Expected behavior

An exception should be thrown and the node service should exit when the API services fail to start.

## Actual behavior

 Node starts with no API services and no exception about it thrown.

## Steps to reproduce the behavior

1. Make gRPC service port 50051 occupied in advance
2. Start the node
3. Try to access the API endpoint

## Backtrace

````service
14:54:41.976 ERROR [rpc] RpcApiService
java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50051
	at io.grpc.netty.NettyServer.start(NettyServer.java:328)
Caused by: java.net.BindException: Address already in use
14:54:41.983 INFO [app] All api services started.

````

````Client:
UNIMPLEMENTED: Method not found: protocol.Wallet/GetAccount
io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: protocol.Wallet/GetAccount
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
````

**Comment by zeusoo001** [comment]
@halibobo1205  In addition to api services, do other services also have such demands?

**Comment by halibobo1205** [comment]
@zeusoo001, IMHO: external services should not silently  fail to start, such as event-plugins.

**Comment by halibobo1205** [comment]
external services :
- [ ] API 
- [ ] event-plugins 
- [ ] Net P2P 
- [ ] metrics 
- [ ] ZKsnark

**Comment by halibobo1205** [comment]
Force-enabled services: `RpcApiService`, `RpcApiServiceOnSolidity`, `RpcApiServiceOnPBFT`, and `HttpApiOnPBFTService` need to be adjusted to optional before the fix.

**Comment by halibobo1205** [comment]
> This may require adjusting the priority of each service startup. 
@lxcmyf why it needs to be adjusted?

**Comment by lxcmyf** [comment]
@halibobo1205 
I would like to say that various services may be divided into many types according to their functions, but there are also similar services that can be classified under the same category. Real time startup errors can be classified by type, making the sorting of errors clearer.

**Comment by 317787106** [comment]
@halibobo1205 Should you check whether some configured ports are occupied before the main thread starts ?

**Comment by halibobo1205** [comment]
> Real time startup errors can be classified by type, making the sorting of errors clearer.

@lxcmyf I don't think it's necessary, the error is even less clear, and the original error is still needed, you can see the sample above.

**Comment by halibobo1205** [comment]
> An exception should be thrown and the node service should exit when all external services fail to start.

Working on this.

**Comment by halibobo1205** [comment]
> An exception should be thrown and the node service should exit when the API services fail to start.

Is it necessary to exit the node service? PTAL @317787106 @lxcmyf @tomatoishealthy

**Comment by halibobo1205** [comment]
Final decision: exit the node service when  API services fail to start. cc @tomatoishealthy

**Comment by halibobo1205** [comment]
Related PRs:

- [ ] #5857 
- [ ] #6228 
- [ ] #6233

**Comment by halibobo1205** [comment]
1. The node is witness, but no private key is configured
2. The configured rate limiter is not working as expected.
3. Configured auto-stop block time parsing error
