### ISSUE TITLE
Node with event plug-in enabled takes too much memory, or OOM happens 

### ISSUE THREAD

**Issue by liuyifei001** [tronprotocol/java-tron#5821]
#### System information

**Versions**
* Software version: [`java -jar FullNode.jar -v`] 4.7.3
* Java version: [`java -version`]  openjdk version "1.8.0_402"
* OS Name & Version: [`cat /etc/*release`] CentOS Linux release 7.9.2009 (Core)
* Kernel Version: [`uname -a`]  x86_64 x86_64 x86_64 GNU/Linux
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]
* Node Type: [e.g. fullNode, liteFullNode] fullNode
* Blockchain Net: [e.g. main, test or private ] test
* Commit hash : [if `develop`]

#### Expected behavior
Nodes with event plug-ins enabled can run normally and stably.

#### Actual behavior
I deployed a nile node using the snapshot database and started with the mongo plug-in. After running for a period of time (about 20 days), I found that the node was always in sync status. After checking the logs, I found that the block processing took a long time and could not catch up with the latest block. At the same time, the memory usage was as high as 37GB.

#### Steps to reproduce the behavior

Deployed a nile node using the snapshot database, started with the mongo plug-in. Mongo configuration is listed as follow :
```
event.subscribe = {
 native = {
   useNativeQueue = false // if true, use native message queue, else use event plugin.
   bindport = 5555 // bind port
   sendqueuelength = 1000 //max length of send queue
 }


 path = "/data/event-plugin/build/plugins/plugin-mongodb-1.0.0.zip" // absolute path of plugin
 server = "127.0.0.1:27017" // target server address to receive event triggers
 dbconfig = "online|oom|oom" // dbname|username|password
 contractParse = true,
 topics = [
   {
     triggerName = "block" // block trigger, the value can't be modified
     enable = true
     topic = "block" // plugin topic, the value could be modified
     solidified = true // if set true, just need solidified block, default is false
   },

   {
     triggerName = "transaction"
     enable = true
     topic = "transaction"
     solidified = true
     ethCompatible = true // if set true, add transactionIndex, cumulativeEnergyUsed, preCumulativeLogCount, logList, energyUnitPrice, default is false
   },

   {
     triggerName = "contractevent"
     enable = true
     topic = "contractevent"
   },

   {
     triggerName = "contractlog"
     enable = true
     topic = "contractlog"
     redundancy = true // if set true, contractevent will also be regarded as contractlog
   },

   {
     triggerName = "solidity" // solidity block trigger(just include solidity block number and timestamp), the value can't be modified
     enable = true            // the default value is true
     topic = "solidity"
   },

   {
     triggerName = "solidityevent"
     enable = true
     topic = "solidityevent"
   },

   {
     triggerName = "soliditylog"
     enable = true
     topic = "soliditylog"
     redundancy = true // if set true, solidityevent will also be regarded as soliditylog
   }

 ]


 filter = {
   fromblock = "" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
   toblock = "" // the value could be "", "latest" or a specified block number as end of the queried range
   contractAddress = [
     "" // contract address you want to subscribe, if it's set to "", you will receive contract logs/events with any contract address.
   ]

   contractTopic = [
     "" // contract topic you want to subscribe, if it's set to "", you will receive contract logs/events with any contract topic.
   ]
 }

}
```
Later I discovered that all collections had no indexes.

#### Backtrace

Memory monitoring chart:
![image](https://github.com/tronprotocol/java-tron/assets/169016168/9f21cfb7-3a6d-42e3-8b88-bcbcbb7c21ad)

File diagram after dumping memory:

![image](https://github.com/tronprotocol/java-tron/assets/169016168/649f361d-3408-41a5-95e5-7895cc1111a4)

![image](https://github.com/tronprotocol/java-tron/assets/169016168/d6d3a49f-fcfa-4cb7-97aa-8b0a28cd740e)

Note: when submitting logs, please submit them as plain text, not in screenshots.

**Comment by jwrct** [comment]
@liuyifei001 从你提供的信息来看，你的节点有可能是出现了事件堆积的情况。一般出现事件堆积可能是由于以下原因造成：

**Comment by jwrct** [comment]
@liuyifei001 From the information you provided, it seems that your node may be experiencing event accumulation. Event accumulation typically occurs due to the following reasons: 
1. Insufficient bandwidth between the full node and the target storage node. For example, if the full node and the mongo server are located in different regions, there may be high latency. 
2. Missing indexes in mongo collections. For instance, if the dbconfig configured for mongo does not enable the latest version=2 configuration option, indexes will not be automatically created. 
3. Incorrect unique index settings in mongo collections. 
Please verify if any of the above-mentioned reasons exist.

**Comment by zeusoo001** [comment]
Is there any good solution?

**Comment by 317787106** [comment]
@liuyifei001 We can get some information from this memory dump. It seems there are two many tasks in a ThreadPoolExecutor, and this  ThreadPoolExecutor's pool size is 8. So the root cause may come from the event-plugin. 

First let's try to understand the  running process of the mongo plug-in. The api of mongo event-plugin works as following:

1. Initialize a queue:
```
private BlockingQueue<Object> triggerQueue = new LinkedBlockingQueue<>();
```
And create a thread pool with a fixed size of 8:
```
private ExecutorService service = Executors.newFixedThreadPool(8);
```
2. When each API is called, the plug-in is written to this queue.
```
    @Override
    public void handleBlockEvent(Object data) {

        if (Objects.isNull(data)){
            return;
        }

        MongodbSenderImpl.getInstance().getTriggerQueue().offer(data);
    }
```
4. Start a thread to read a piece of data from the queue.

```
private Runnable triggerProcessLoop =
      () -> {
        while (isRunTriggerProcessThread) {
          try {
            String triggerData = (String) triggerQueue.poll(1, TimeUnit.SECONDS);

            if (Objects.isNull(triggerData)) {
              continue;
            }

            if (triggerData.contains(Constant.BLOCK_TRIGGER_NAME)) {
              handleBlockEvent(triggerData);
            } else if (triggerData.contains(Constant.TRANSACTION_TRIGGER_NAME)) {
              handleTransactionTrigger(triggerData);
            } else if (triggerData.contains(Constant.CONTRACTLOG_TRIGGER_NAME)) {
              handleContractLogTrigger(triggerData);
            } else if (triggerData.contains(Constant.CONTRACTEVENT_TRIGGER_NAME)) {
              handleContractEventTrigger(triggerData);
            } else if (triggerData.contains(Constant.SOLIDITY_TRIGGER_NAME)) {
              handleSolidityTrigger(triggerData);
            } else if (triggerData.contains(Constant.SOLIDITYLOG_TRIGGER_NAME)) {
              handleSolidityLogTrigger(triggerData);
            } else if (triggerData.contains(Constant.SOLIDITYEVENT_TRIGGER_NAME)) {
              handleSolidityEventTrigger(triggerData);
            }
          } catch (InterruptedException ex) {
            log.info(ex.getMessage());
            Thread.currentThread().interrupt();
          } catch (Exception ex) {
            log.error("unknown exception happened in process capsule loop", ex);
          } catch (Throwable throwable) {
            log.error("unknown throwable happened in process capsule loop", throwable);
          }
        }
      };
```
5. According to the topic type of the data, the thread pool starts a thread, which writes data into mongo, the thread runs in the background and needs to be scheduled:
```
  public void handleBlockEvent(Object data) {
    if (blockTopic == null || blockTopic.length() == 0) {
      return;
    }

    MongoTemplate template = mongoTemplateMap.get(blockTopic);
    if (Objects.nonNull(template)) {
      service.execute(new Runnable() {
        @Override
        public void run() {
          if (mongoConfig.enabledIndexes()) {
            upsertEntityLong(template, data, "blockNumber");
          } else {
            template.addEntity((String) data);
          }
        }
      });
    }
  }
```


If threads write to mongo slowly, it will cause the thread pool to accumulates a large number of tasks to be scheduled. After a period of time, full gc may happen frequently in this node, and at last eventually the memory will be exhausted, namely OOM occurs.

**Comment by ss334452** [comment]
@317787106 You explained the cause of the problem very well. Do you have a preliminary solution now?

**Comment by jwrct** [comment]
@liuyifei001 To better analyze and locate the problem, as well as design effective solutions, please confirm if the situations mentioned above exist, such as not creating indexes correctly.

**Comment by 317787106** [comment]
> @317787106 You explained the cause of the problem very well. Do you have a preliminary solution now?

If you check that there aren't any indexes in mongo clooection, not include `_id`, we can create indexes manually as following:

```
db.block.createIndex({'blockNumber':1})

db.contractevent.createIndex({'uniqueId':1}, {unique:true})

db.contractlog.createIndex({'contractAddress':1})
db.contractlog.createIndex({'uniqueId':1}, {unique:true})

db.solidity.createIndex({'latestSolidifiedBlockNumber':1},{unique:true})

db.solidityevent.createIndex({'uniqueId':1},{unique:true})

db.soliditylog.createIndex({'contractAddress':1})
db.soliditylog.createIndex({'uniqueId':1},{unique:true})

db.transaction.createIndex({'transactionId':1},{unique:true})
```

It may take dozens of minutes, depending on the size of the data. After building the indexes successfully, write opertaion will be mush faster.

**Comment by lvs007** [comment]
I think the problem here, is that no index is created; so is it just a matter of reminding the user who is using it that the index is created, no logical changes need to be made at the java-tron, just give some logs and documentation to remind them.

**Comment by liuyifei001** [comment]
@317787106 I can easily reproduce the case, the memory grows quickly. When I building the indexes as your description,
 memory consumption decreases gradually. It looks good.

**Comment by liuyifei001** [comment]
@317787106  @lvs007 @jwrct Before the indexes are created, i use `kill -15` to stop the node, I found that many events  lost, such as collection `block`. There is not any reminder message. Data lost in unacceptable. Is theren any way to supplementary lost data ?

**Comment by jwrct** [comment]
> I think the problem here, is that no index is created; so is it just a matter of reminding the user who is using it that the index is created, no logical changes need to be made at the java-tron, just give some logs and documentation to remind them.

Agree with the above proposal. It is better for users to solve the problems of third-party applications by themselves, after all, the root cause of the problem should be resolved.
