### ISSUE TITLE
Usdt trx 

### ISSUE THREAD

**Issue by Bob978863** [tronprotocol/java-tron#5823]
I tried to send usdt trx to another wallet, the transaction go after some seconds I receive the funds back,  when I check the transaction ID it tells me FAILED -TRANSACTION
REVERT> 

help

**Comment by ferdinand026** [comment]
@Bob978863 Detailed information will help a lot, eg, transaction id, transaction sending way: coding or through wallet/exchange app.

**Comment by Bob978863** [comment]
> @Bob978863 Detailed information will help a lot, eg, transaction id, transaction sending way: coding or through wallet/exchange app.

this funds are in a decentralized wallet (exodus) and trying to send it on an trust wallet

**Comment by ferdinand026** [comment]
@Bob978863 Do you have the transaction id? or you may try again, or you can check if your address is blacklisted by USDT: https://tronscan.org/#/token20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/code 
<img width="1091" alt="image" src="https://github.com/tronprotocol/java-tron/assets/138766914/1919a3c6-fd68-44d2-98b9-7a72b8bfa359">

**Comment by vivian1912** [comment]
@Bob978863 May I ask if this issue has been resolved? And do you have any other questions?

**Comment by vivian1912** [comment]
@Bob978863 Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
