### ISSUE TITLE
Connect node

### ISSUE THREAD

**Issue by A1985J09** [tronprotocol/java-tron#5827]
#### Steps to reproduce the behaviour

1. [Step 1]
2. [Step 2]
3. [Step ...]

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by vivian1912** [comment]
@A1985J09 Would you please detailed your issue? Thanks.

**Comment by vivian1912** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no content basically. Please feel free to re-open it if you have suggestions, comments or issues about java-tron , thanks.
