### ISSUE TITLE
Where do I submit a doc change for the official site?

### ISSUE THREAD

**Issue by VetchM** [tronprotocol/java-tron#5829]
Hi, I would like to add another language example for the [build transaction doc](https://developers.tron.network/v3.7/docs/how-to-build-a-transaction-locally), but I couldn't find the repo that contains it. Do I submit it to this repo or another?

**Comment by ferdinand026** [comment]
@VetchM The doc you mentioned above is not the latest one, and the latest document is https://developers.tron.network/ ,it is not a github repository. but we also can submit our suggestions through [Suggest Edits](https://developers.tron.network/edit/tron-protocol-transaction). 
<img width="1133" alt="image" src="https://github.com/tronprotocol/java-tron/assets/138766914/48b2b565-1fd4-45c6-b65c-34e7d7b09377">

**Comment by VetchM** [comment]
@ferdinand026 Thanks, but I don't find the "How to Build a Transaction Locally" page in latest document, do you know where it is?

**Comment by ferdinand026** [comment]
@VetchM [This page](https://developers.tron.network/docs/tron-protocol-transaction#transaction-lifecycle) is to introduce how to create transaction locally in three steps.

**Comment by vivian1912** [comment]
@VetchM Thanks for your contribution to java-tron, this issue will be closed, Please feel free to re-open it if you have any comments or questions, thanks.
