### ISSUE TITLE
BAD_JUMP_DESTINATION ERROR ON TRON PRIVATE CHAIN

### ISSUE THREAD

**Issue by 0xarmaansidhu** [tronprotocol/java-tron#5850]
I am trying to create a contract from a already deployed contract and i get this, i am trying to execute the "create method"
```
    "ret": [
        {
            "contractRet": "BAD_JUMP_DESTINATION"
        }
    ],
```
THIS IS THE CONTRACT
```
pragma solidity ^0.8.23;
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

contract Car {
    address public owner;
    string public model;
    address public carAddr;

    constructor(address _owner, string memory _model) payable {
        owner = _owner;
        model = _model;
        carAddr = address(this);
    }
    receive() external payable {}
}

contract CarFactory {
    Car[] public cars;
    receive() external payable {}
    function create(address _owner, string memory _model) public {
        Car car = new Car(_owner, _model);
        cars.push(car);
    }

    function createAndSendEther(
        address _owner,
        string memory _model
    ) public payable {
        Car car = (new Car){value: msg.value}(_owner, _model);
        cars.push(car);
    }

    function create2(
        address _owner,
        string memory _model,
        bytes32 _salt
    ) public {
        Car car = (new Car){salt: _salt}(_owner, _model);
        cars.push(car);
    }

    function create2AndSendEther(
        address _owner,
        string memory _model,
        bytes32 _salt
    ) public payable {
        Car car = (new Car){value: msg.value, salt: _salt}(_owner, _model);
        cars.push(car);
    }

    function getCar(
        uint256 _index
    )
        public
        view
        returns (
            address owner,
            string memory model,
            address carAddr,
            uint256 balance
        )
    {
        Car car = cars[_index];

        return (car.owner(), car.model(), car.carAddr(), address(car).balance);
    }
}

```

**Comment by endiaoekoe** [comment]
> I am trying to create a contract from a already deployed contract and i get this, i am trying to execute the "create method"
> 
> ```
>     "ret": [
>         {
>             "contractRet": "BAD_JUMP_DESTINATION"
>         }
>     ],
> ```
> 
> THIS IS THE CONTRACT
> 
> ```
> pragma solidity ^0.8.23;
> // SPDX-License-Identifier: MIT
> pragma solidity ^0.8.23;
> 
> contract Car {
>     address public owner;
>     string public model;
>     address public carAddr;
> 
>     constructor(address _owner, string memory _model) payable {
>         owner = _owner;
>         model = _model;
>         carAddr = address(this);
>     }
>     receive() external payable {}
> }
> 
> contract CarFactory {
>     Car[] public cars;
>     receive() external payable {}
>     function create(address _owner, string memory _model) public {
>         Car car = new Car(_owner, _model);
>         cars.push(car);
>     }
> 
>     function createAndSendEther(
>         address _owner,
>         string memory _model
>     ) public payable {
>         Car car = (new Car){value: msg.value}(_owner, _model);
>         cars.push(car);
>     }
> 
>     function create2(
>         address _owner,
>         string memory _model,
>         bytes32 _salt
>     ) public {
>         Car car = (new Car){salt: _salt}(_owner, _model);
>         cars.push(car);
>     }
> 
>     function create2AndSendEther(
>         address _owner,
>         string memory _model,
>         bytes32 _salt
>     ) public payable {
>         Car car = (new Car){value: msg.value, salt: _salt}(_owner, _model);
>         cars.push(car);
>     }
> 
>     function getCar(
>         uint256 _index
>     )
>         public
>         view
>         returns (
>             address owner,
>             string memory model,
>             address carAddr,
>             uint256 balance
>         )
>     {
>         Car car = cars[_index];
> 
>         return (car.owner(), car.model(), car.carAddr(), address(car).balance);
>     }
> }
> ```

hi, @0xarmaansidhu 
Usually,Bad Jump Destination error happend due to a control flow jump error in the contract.
below are some factors you can check to investigate the root cause of this error,
1. the parameters passed in when creating the Car contract instance. Ensure that the _owner and _model parameters are of the correct format and type.
2. the value of msg. value when calling the createAndSendEther or create2AndSendEther functions. Check that you are passing in the correct number of Ether when calling these functions.

**Comment by 0xarmaansidhu** [comment]
Even though i remove the input arguments it still throws the error,do i have to make any changes in the config file or any parameter changes on the tron private chain

**Comment by 0xarmaansidhu** [comment]
@endiaoekoe solved it,there was something wrong with the input arguments
