### ISSUE TITLE
我的区块同步为啥很慢，每天只比新产出的区块多同步3000个

### ISSUE THREAD

**Issue by xiaobeibeinihao** [tronprotocol/java-tron#5851]
我的区块同步为啥很慢，每天只比新产出的区块多同步3000个。还差290000个，这啥时候能同步完呢?
Peer /5.45.76.201:18888
connect time: 738s [823ms]
last know block num: 62063114
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:3793
syncToFetchSizePeekNum:62063115
syncBlockRequestedSize:0
remainNum:298439
syncChainRequested:0
blockInProcess:1

**Comment by halibobo1205** [comment]
According to [the official configuration](https://github.com/tronprotocol/java-tron?tab=readme-ov-file#running-java-tron): 16C 32G,2T SSD, block processing takes time as follows:
<img width="1822" alt="image" src="https://github.com/tronprotocol/java-tron/assets/82020050/7f8929ff-5232-44ca-88f5-d8b92981f8c2">

**Comment by halibobo1205** [comment]
Please provide details of the hardware configuration, [startup script](https://github.com/tronprotocol/java-tron?tab=readme-ov-file#running-a-full-node-for-mainnet) and [database config](https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf#L6).

**Comment by xiaobeibeinihao** [comment]
![image](https://github.com/tronprotocol/java-tron/assets/3068075/42a57184-7859-4acb-b52b-9880e84ca9e3)
<img width="480" alt="image" src="https://github.com/tronprotocol/java-tron/assets/3068075/648bba3a-af26-4cb3-8e04-347c13825921">
<img width="717" alt="image" src="https://github.com/tronprotocol/java-tron/assets/3068075/a9971bd8-4d41-41a3-bfe3-0aad50ba34a8">

**Comment by xiaobeibeinihao** [comment]
<img width="449" alt="image" src="https://github.com/tronprotocol/java-tron/assets/3068075/837c2ae3-bc67-4896-a0ee-355e4e3ee8d4">

**Comment by 317787106** [comment]
@xiaobeibeinihao 32GB memory is recommended for mainnet network. What's your machine memory? It seems to be 12.9GB.  And can you also privide your config.conf?

**Comment by xiaobeibeinihao** [comment]
> The machine load is a bit high. You can check whether other services are affecting each other.

OK ,thanks

**Comment by xiaobeibeinihao** [comment]
> @xiaobeibeinihao 32GB memory is recommended for mainnet network. What's your machine memory? And can you also privide your config.conf?

I reload the progress ,it is faster than more.

**Comment by xiaobeibeinihao** [comment]
> The machine load is a bit high. You can check whether other services are affecting each other.

I reload the progress, it is  a little faster than before

**Comment by xiaobeibeinihao** [comment]
I restarted the client ,it works
