### ISSUE TITLE
现在磁盘越来越大了，想请教下有没有剪切快照的功能，来减小数据磁盘大小

### ISSUE THREAD

**Issue by astrid19981112** [tronprotocol/java-tron#5852]
Now the disk is getting bigger and bigger, I would like to ask if there is a function to cut snapshots to reduce the size of the data disk

**Comment by halibobo1205** [comment]
@astrid19981112 ,Hi you can use [lite-fullnode-data-pruning](https://tronprotocol.github.io/documentation-en/using_javatron/toolkit/#lite-fullnode-data-pruning).

**Comment by vivian1912** [comment]
@astrid19981112 Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
