### ISSUE TITLE
通证

### ISSUE THREAD

**Issue by dxy-933** [tronprotocol/java-tron#5855]
_最初由 @dxy-933 在 https://github.com/tronscan/tron-tvc-list/issues/239 发布_

**Comment by 317787106** [comment]
@dxy-933 What problems did you encounter?

**Comment by vivian1912** [comment]
This issue will be closed as no content basically. Please feel free to re-open it if you have suggestions, comments or issues about java-tron , thanks.

**Comment by sfhacker** [comment]
Embarrassing!
