### ISSUE TITLE
How to check that the transaction was successful?

### ISSUE THREAD

**Issue by mr-mr7** [tronprotocol/java-tron#5863]
How to check that the transaction was successful?
for example transaction with hash: f6feb91a9da89011dd5e22f75776fc07bfdea45eff7f4cae7a8cdd0f20dbaa68

**Comment by ferdinand026** [comment]
@mr-mr7 Use the /walletsolidty/gettransactioninfobyid API to check the transaction's successful or not. https://developers.tron.network/docs/tron-protocol-transaction#transaction-confirmation

**Comment by vivian1912** [comment]
@mr-mr7 Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
