### ISSUE TITLE
FullNode Sync failed

### ISSUE THREAD

**Issue by desuraghu13** [tronprotocol/java-tron#5871]
#### Software Versions
```
java -jar FullNode.jar -v
OS : Linux
JVM : Oracle Corporation 1.8.0_411 amd64
Git : b1fc2f0f2bd79527099bc3027b9aba165c2e20c2
Version : 4.7.4
Code : 18260

```

#### Expected behaviour

Sync should proceed without any issues.

#### Actual behaviour

Sync up got failed with the following reason:

08:54:20.196 ERROR [main] [app](DefaultConfig.java:40) Uncaught exception
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationImpl': Unsatisfied dependency expressed through field 'tronNetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tronNetService': Unsatisfied dependency expressed through field 'advService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'advService': Unsatisfied dependency expressed through field 'tronNetDelegate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tronNetDelegate': Unsatisfied dependency expressed through field 'dbManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in string value
 at [Source: (String)"{"num":61871206,"transactionIds":["4498a38df1c95dc2291c03cedafc1f93bdea1cb76fef7a96d6c0f0fd123afe99","07fdca7482fd52f44186cd1c8b4eda4b510b50c2a1d505c6486d189c62147783","752d3cc452522c9406709f29f0dbff421bbabbb72e93443212a1a383df30d0ea","0863cbeb553a34113102edf88bdd1b690b82b93c379887fd5836fb10837067f5","8b576a090f7633bf9d8701d00d0b273637614d1b35b70b2b26d4f76a3ebc6542","7bc159cfa7df5295932b0c3e0082370e81364c53e0ab81d7d2a592830ac65c77","5757b29122ac1a399b6128ecbb8bd25956366b78e131fa73fcdcaa038bb2032"[truncated 7702 chars]; line: 1, column: 3114] (through reference chain: org.tron.core.db.RecentTransactionItem["transactionIds"]->java.util.ArrayList[45])
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.tron.program.FullNode.main(FullNode.java:80)

#### Steps to reproduce the behaviour

1. Downloaded the backup
2. Started the syncup. 
3. At block #61871206 sync up got failed.
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by fyyhtx** [comment]
@desuraghu13 From the logs you provided, it seems that your node encountered an exception during the startup process, which is not a common occurrence. You can try starting your node with the following command.
`$ nohup java -Xms9G -Xmx9G -XX:ReservedCodeCacheSize=256m \
             -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m \
             -XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails \
             -XX:+PrintGCDateStamps  -Xloggc:gc.log \
             -XX:+UseConcMarkSweepGC -XX:NewRatio=2 \
             -XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled \
             -XX:+HeapDumpOnOutOfMemoryError \
             -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=70 \
             -jar FullNode.jar -c main_net_config.conf >> start.log 2>&1 &`
Pay attention to the configuration file name and path.

To deploy a node, you can refer to the documentation: https://tronprotocol.github.io/documentation-en/using_javatron/installing_javatron/#run-a-java-tron-node .

**Comment by desuraghu13** [comment]
@fyyhtx , still getting the same error

17:24:40.416 INFO  [main] [DB](TronDatabase.java:103) ******** End to close CheckTmpStore. ********
17:24:40.421 ERROR [main] [app](DefaultConfig.java:40) Uncaught exception
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationImpl': Unsatisfied dependency expressed through field 'tronNetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tronNetService': Unsatisfied dependency expressed through field 'advService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'advService': Unsatisfied dependency expressed through field 'tronNetDelegate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tronNetDelegate': Unsatisfied dependency expressed through field 'dbManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 0)): has to be escaped using backslash to be included in string value
 at [Source: (String)"{"num":61871206,"transactionIds":["4498a38df1c95dc2291c03cedafc1f93bdea1cb76fef7a96d6c0f0fd123afe99","07fdca7482fd52f44186cd1c8b4eda4b510b50c2a1d505c6486d189c62147783","752d3cc452522c9406709f29f0dbff421bbabbb72e93443212a1a383df30d0ea","0863cbeb553a34113102edf88bdd1b690b82b93c379887fd5836fb10837067f5","8b576a090f7633bf9d8701d00d0b273637614d1b35b70b2b26d4f76a3ebc6542","7bc159cfa7df5295932b0c3e0082370e81364c53e0ab81d7d2a592830ac65c77","5757b29122ac1a399b6128ecbb8bd25956366b78e131fa73fcdcaa038bb2032"[truncated 7702 chars]; line: 1, column: 3114] (through reference chain: org.tron.core.db.RecentTransactionItem["transactionIds"]->java.util.ArrayList[45])
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
                                                                                                           209,1-8       62%

**Comment by fyyhtx** [comment]
@desuraghu13 Could you provide the complete log from node startup?

**Comment by fyyhtx** [comment]
@desuraghu13 Please confirm the following issues: 1. Is the issue occurring during node operation or did it occur for the first time when starting up? 2. Did you perform any operations before starting the node? 3. Have you tried downloading a new data snapshot for recovery after the issue occurred?

**Comment by desuraghu13** [comment]
> @desuraghu13 Please confirm the following issues: 

1. Is the issue occurring during node operation or did it occur for the first time when starting up? 
After downloading the snapshot, i have started the sync-up. It ran normally for 5-6 hrs. Then observed timeout issues. Hence tried to restart the application. Post restart observed this issue.

2. Did you perform any operations before starting the node? 
No.
 
3. Where did you download the data snapshot from? 
https://db-backup-asia.s3-ap-southeast-1.amazonaws.com/FullNode-61811421-4.7.4-output-directory.tgz

4. Have you tried downloading a new data snapshot for recovery after the issue occurred?
Nope. As it will take long time to download a new snapshot, trying to recover from this state only.

Please check the complete log.
[tron.log](https://github.com/user-attachments/files/15922547/tron.log)

**Comment by fyyhtx** [comment]
> 1. After downloading the snapshot, i have started the sync-up. It ran normally for 5-6 hrs. Then observed timeout issues. Hence tried to restart the application. Post restart observed this issue.

@desuraghu13 How do you restart the node? For example, what command do you use?

**Comment by desuraghu13** [comment]
Restart : Killing the existing process (kill -15 pid) and starting the java process using nohup in background.

**Comment by desuraghu13** [comment]
Sure, let me do the same and will update you once done. Hope i am downloading the snapshot from the correct place.

**Comment by desuraghu13** [comment]
Downloaded new version and started the java process. Sync-up has been started now. 

Can you please guide me on the following:
To prevent DB corruption, would like to know the options we have ?
How to increase the sync-up speed ?
java -kill <pid>, is the correct way to kill the process without corrupting the DB ?

**Comment by jwrct** [comment]
@desuraghu13 
> Can you please guide me on the following:
> To prevent DB corruption, would like to know the options we have ?

Try to avoid machine crashes as much as possible and do not use unsafe process killing commands such as 'kill -9 pid'.
> How to increase the sync-up speed ?

Upgrade machine configuration.
> java -kill , is the correct way to kill the process without corrupting the DB ?

kill -15 pid
> Also, if any peer node has been dis-connected due to time-out, does it automatically retry ? If so what is the retry interval ? Also is the timeout configurable ?

New connections will only be actively attempted if the number of connections is less than the minimum connection count or minimum active connection count, but new passive connection requests will continue to supplement the connection count. The interval for active connections is 3.6 seconds. Timeout time is not configurable.

**Comment by desuraghu13** [comment]
Observed the same issue once again. Timeout has been occurred once again. Killed the process by issuing kill -15 <pid> and started the java process. During server startup observed the db corruption error.

shutdown log:
04:44:16.788 INFO  [main] [app](Args.java:1633) P2P version: 11111
04:44:16.788 INFO  [main] [app](Args.java:1634) LAN IP: 192.168.50.193
04:44:16.789 INFO  [main] [app](Args.java:1635) External IP: 210.242.49.250
04:44:16.789 INFO  [main] [app](Args.java:1636) Listen port: 18888
04:44:16.789 INFO  [main] [app](Args.java:1637) Node ipv6 enable: false
04:44:16.789 INFO  [main] [app](Args.java:1638) Discover enable: true
04:44:16.789 INFO  [main] [app](Args.java:1639) Active node size: 0
04:44:16.789 INFO  [main] [app](Args.java:1640) Passive node size: 0
04:44:16.789 INFO  [main] [app](Args.java:1641) FastForward node size: 2
04:44:16.789 INFO  [main] [app](Args.java:1642) FastForward node number: 3
04:44:16.789 INFO  [main] [app](Args.java:1643) Seed node size: 30
04:44:16.789 INFO  [main] [app](Args.java:1644) Max connection: 30
04:44:16.789 INFO  [main] [app](Args.java:1645) Min connection: 8
04:44:16.789 INFO  [main] [app](Args.java:1646) Min active connection: 3
04:44:16.789 INFO  [main] [app](Args.java:1647) Max connection with same IP: 2
04:44:16.789 INFO  [main] [app](Args.java:1648) Solidity threads: 16
04:44:16.790 INFO  [main] [app](Args.java:1649) Trx reference block: solid
04:44:16.790 INFO  [main] [app](Args.java:1650) Open full tcp disconnect: false
04:44:16.790 INFO  [main] [app](Args.java:1651) Node detect enable: false
04:44:16.790 INFO  [main] [app](Args.java:1652) Node effective check enable: false
04:44:16.790 INFO  [main] [app](Args.java:1653) Rate limiter global qps: 50000
04:44:16.790 INFO  [main] [app](Args.java:1654) Rate limiter global ip qps: 10000
04:44:16.790 INFO  [main] [app](Args.java:1655) Rate limiter global api qps: 1000
04:44:16.790 INFO  [main] [app](Args.java:1656) ************************ Backup config ************************
04:44:16.790 INFO  [main] [app](Args.java:1657) Backup priority: 8
04:44:16.790 INFO  [main] [app](Args.java:1658) Backup listen port: 10001
04:44:16.790 INFO  [main] [app](Args.java:1659) Backup listen keepAliveInterval: 3000
04:44:16.790 INFO  [main] [app](Args.java:1660) Backup member size: 0
04:44:16.790 INFO  [main] [app](Args.java:1661) ************************ Code version *************************
04:44:16.793 INFO  [main] [app](Args.java:1662) Code version : 4.7.5
04:44:16.793 INFO  [main] [app](Args.java:1663) Version code: 18306
04:44:16.793 INFO  [main] [app](Args.java:1664) ************************ DB config *************************
04:44:16.793 INFO  [main] [app](Args.java:1665) DB engine : LEVELDB
04:44:16.793 INFO  [main] [app](Args.java:1666) Snapshot max flush count: 1
04:44:16.793 INFO  [main] [app](Args.java:1667) ***************************************************************
04:44:16.793 INFO  [main] [app](Args.java:1668) ************************ shutDown config *************************
04:44:16.793 INFO  [main] [app](Args.java:1669) ShutDown blockTime  : null
04:44:16.794 INFO  [main] [app](Args.java:1670) ShutDown blockHeight : -1
04:44:16.794 INFO  [main] [app](Args.java:1671) ShutDown blockCount : -1
04:44:16.794 INFO  [main] [app](Args.java:1672) ***************************************************************
04:44:16.794 INFO  [main] [app](Args.java:1673)

-------------------------------
04:44:48.796 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:591) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationImpl': Unsatisfied dependency expressed through field 'tronNetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tronNetService': Unsatisfied dependency expressed through field 'advService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'advService': Unsatisfied dependency expressed through field 'tronNetDelegate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tronNetDelegate': Unsatisfied dependency expressed through field 'dbManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: corrupted compressed block contents


04:44:48.897 ERROR [main] [app](DefaultConfig.java:40) Uncaught exception
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationImpl': Unsatisfied dependency expressed through field 'tronNetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tronNetService': Unsatisfied dependency expressed through field 'advService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'advService': Unsatisfied dependency expressed through field 'tronNetDelegate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tronNetDelegate': Unsatisfied dependency expressed through field 'dbManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: corrupted compressed block contents
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.tron.program.FullNode.main(FullNode.java:80)

Attaching the complete log.

**Comment by jwrct** [comment]
@desuraghu13 What do you mean by 'timeout'? Can you provide the complete log?

**Comment by desuraghu13** [comment]
@jwrct please find the log as an attachment.
[tron-1.log](https://github.com/user-attachments/files/15967669/tron-1.log)

Complete log is 188 mb. I have added last few mins of log here.

**Comment by fyyhtx** [comment]
@desuraghu13 We still can't see why your node stopped syncing from the latest logs you provided. Could you provide at least one hour of logs before and after the sync was stopped? Additionally, we need to carefully analyze the possible reasons for the abnormal node startup issue.

**Comment by desuraghu13** [comment]
@fyyhtx - i see there are 2 possible issues here.
1. SYNC got stopped due to some reason.
2. Though i have stopped the process in normal way, still the db got corrupted. 

[Uploading tron-2.zip…]()

**Comment by fyyhtx** [comment]
@desuraghu13 Okay, we are carefully analyzing the logs you provided to determine the reason for the block synchronization stop. Please be patient, thank you.

**Comment by halibobo1205** [comment]
@desuraghu13 ,  based on the above analysis, it is recommended that you can run service with a new disk, and you can contact your service provider for node disk problems.

**Comment by desuraghu13** [comment]
@halibobo1205 , i am curious to know how this issue is related to disk ? 
I will use new disk and perform the syncup operation. Will update here with my observation.

Also i could not observe any IO error trace during shutdown and startup. Please correct me if i am missing anything here.

**Comment by halibobo1205** [comment]
@desuraghu13, It is not explicitly stated that it is a disk issue; it is just a troubleshooting suggestion. Please feel free to try it and give me your feedback.

**Comment by desuraghu13** [comment]
Hi @halibobo1205 , @fyyhtx ,

I was trying to extract the contents from latest backup file. But each time i perform the extract getting the following error :

output-directory/database/block/228291.sst
output-directory/database/block/139933.sst
tar: Skipping to next header
tar: Archive contains â<80><98>\374Ê°\341\034|\244\325D9\003\026â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>e\270Y\024\377\036\232\343\265N\242\tâ<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>\025A\277\340\234\360\006\341\006+\036\326â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>\002\376\343\024\256\343\024\0\365\376\002\023â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>\031D\232)\344\241\333>\302\372\204\035â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>_J\204/\315\343\324,\273K\232*â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>8\274\344b\360Z\302\026\352\v-1â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>\247\221\315_I|\341\221\362\356\370\262â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>\030\001\n\320\001\n\206\001R\305\002\034â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>.1\341\342\353e\371\363\341\025I[â<80><99> where numeric off_t value expected
tar: Archive contains â<80><98>\032E\331\305\312x\250\215\f\264L\030â<80><99> where numeric off_t value expected

Not sure what was the issue. I have done the extracting around 4-5 times, same response has been observed.

**Comment by halibobo1205** [comment]
@desuraghu13 What does the extract command look like that you're using?

**Comment by desuraghu13** [comment]
@halibobo1205 
Cmd i am using is - nohup tar -zxvf FullNode-62962913-4.7.5-output-directory.tgz -C /data/java-tron/bkp/ > tar.log 2>&1 &"

**Comment by halibobo1205** [comment]
`FullNode-62962913-4.7.5-output-directory.tgz` 
Is this file downloaded or self-packed, if it is downloaded please provide the download URL, if it is self-packed, please give the packing command.

**Comment by desuraghu13** [comment]
This is a downloaded file from the following location:

https://db-backup-asia.s3-ap-southeast-1.amazonaws.com/FullNode-62962913-4.7.5-output-directory.tgz

**Comment by halibobo1205** [comment]
> This is a downloaded file from the following location:
> 
> https://db-backup-asia.s3-ap-southeast-1.amazonaws.com/FullNode-62962913-4.7.5-output-directory.tgz

This file doesn't exist anymore. You can check if the file is downloaded completely(if has md5) or if the disk is full.

**Comment by vivian1912** [comment]
@desuraghu13 Thanks for your contribution to java-tron. May I ask if this issue has been resolved? And do you have any other questions?

**Comment by desuraghu13** [comment]
@vivian1912 , I have tried multiple times to download the backup file and extract the contents. Each time facing the same problem in extracting it self.

Trying to setup one more node to check the same.

**Comment by vivian1912** [comment]
@desuraghu13  First we need to ensure that the disk has enough space to accommodate the downloaded backup file or the unzipped files. ( The backup file size is about 1800G, the unzipped files are about 2T). After downloading, check the integrity of the file through the .md5sum file (For example, http://34.143.247.77/backup20240708/ ). If everything is ok,  would you please provide the following detailed information, including: 1. Where to download the backup database 2. the backup file name 3. tar version 4. the detailed error information during unzip.

**Comment by desuraghu13** [comment]
@vivian1912 , i have 10T diskspace. I am downloading from AWS southeast location. As my servers are near to that place. 
If there is any alternative location from where can i download the file, please let me know.

**Comment by vivian1912** [comment]
> @vivian1912 , i have 10T diskspace. I am downloading from AWS southeast location. As my servers are near to that place. If there is any alternative location from where can i download the file, please let me know.

You may try to download the backup file from the data source in Singapore: https://developers.tron.network/docs/main-net-database-snapshots

**Comment by desuraghu13** [comment]
Downloading the following snapshot, will update the result by tomorrow:
http://35.247.128.170/backup20240709/FullNode_output-directory.tgz

**Comment by desuraghu13** [comment]
@vivian1912 , my n/w connection got interrupted. 
Restarted the download once again. Will keep you updated.

**Comment by desuraghu13** [comment]
Sync got stuck @63481547 block. Checking the logs.

**Comment by desuraghu13** [comment]
Do i need to update the peer ip details in the conf file ?
Restart will work ? Really worried if i restart the process it is going to corrupt the db ?

**Comment by desuraghu13** [comment]
We are good to close this ticket, as sync has been resumed now. 
Thanks a lot for all your assistance.

**Comment by YuXiaoCoder** [comment]
> We are good to close this ticket, as sync has been resumed now. Thanks a lot for all your assistance.

How did you get back in sync, please?

**Comment by risinek** [comment]
@desuraghu13 what was the reason/solution on your side? Im in the same boat

**Comment by desuraghu13** [comment]
Hard disk issue. Once i changed the partition, sync ran without any issues
