### ISSUE TITLE
Why are the net type of main_net_config.file and private_net_config_file and test_net_config_file all mainnet?

### ISSUE THREAD

**Issue by YuMenGuan** [tronprotocol/java-tron#5874]
<img width="651" alt="截屏2024-06-21 16 40 25" src="https://github.com/tronprotocol/java-tron/assets/165134544/34721488-7198-4344-b013-bde0e0749a7f">
<img width="715" alt="截屏2024-06-21 16 39 42" src="https://github.com/tronprotocol/java-tron/assets/165134544/0b312b19-a725-4b69-b0d0-aba31d61c01f">
<img width="694" alt="截屏2024-06-21 16 39 28" src="https://github.com/tronprotocol/java-tron/assets/165134544/8cfc612f-c588-497a-b998-a19e29db424d">

**Comment by YuMenGuan** [comment]
> This is to ensure compatibility with multiple network addresses.
> 
> The `type` controls the encoding of the address prefix. A unified configuration was adopted to ensure the compatibility of the main network and test network addresses.
> 
> Of course, you can also try to use the `testnet`, It depends on your needs.

Thanks for your reply.

**Comment by vivian1912** [comment]
@YuMenGuan Thanks for your contribution to java-tron, this issue will be closed. Please feel free to re-open it if you still see the issue, thanks.
