### ISSUE TITLE
Sync stuck at block 62808277 after server restart

### ISSUE THREAD

**Issue by anti-captcha** [tronprotocol/java-tron#5877]
After server hangup and restart the FullNode.jar does not continue to sync. I suspect that the DB is corrupted, but there are no records showing that in the log file. Using config file from docs.

#### Software Versions
```
OS : Linux
Version : 4.7.5
```

#### Expected behaviour
Should sync

#### Actual behaviour
Stuck at block 62808277

[tron.log](https://github.com/user-attachments/files/15942459/tron.log)

**Comment by anti-captcha** [comment]
The issue was reproduced at another server at another block. It hanged up and I had to reboot. Upon reboot started the full node. The sync is stuck at another block 62683952. 
[tron.log](https://github.com/user-attachments/files/15949095/tron.log)

**Comment by lxcmyf** [comment]
@anti-captcha 
Yes, service suspension can damage the database. It is recommended to download the latest snapshot and restart. Also, please make sure to use jdk1.8, otherwise it will also affect synchronization.

**Comment by lxcmyf** [comment]
@anti-captcha 
If your issue has been resolved smoothly, you can close it.

**Comment by lxcmyf** [comment]
@anti-captcha 
Based on the analysis of logs, from the current phenomenon, it is highly likely that service downtime will damage the database and affect block synchronization. Have you done any other operations besides this? For example, modifying contract configuration parameters, modifying configuration files, etc?
