### ISSUE TITLE
Compilation build failed

### ISSUE THREAD

**Issue by bytesharky** [tronprotocol/java-tron#5883]
Please help me![image](https://github.com/tronprotocol/java-tron/assets/21698649/6a7df8e9-da20-4d65-bb8a-1800fda1ab99)

**Comment by CarlChaoCarl** [comment]
Could you provide a bit more information, such as the java-tron code branche, the Gradle configuration, the Java version, etc.?

**Comment by bytesharky** [comment]
`root@ip-172-31-39-17:~# cat /proc/version
Linux version 6.8.0-1008-aws (buildd@lcy02-amd64-030) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #8-Ubuntu SMP Sat Apr 20 00:46:25 UTC 2024
root@ip-172-31-39-17:~#
root@ip-172-31-39-17:~# java -version
java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)
`
master branche，no change configuration

**Comment by CarlChaoCarl** [comment]
I tried it locally using the root user, but it also failed.
Command: ./gradlew clean build -x test --debug
The reason is: Could not find tools.jar
You need to check if the JDK installation is valid.
If the JDK installation is fine, check the gradle debug output for the error reason.

**Comment by CarlChaoCarl** [comment]
@bytesharky 
Hello, if your issue has been resolved, this issue can be closed.
