### ISSUE TITLE
Reject transactions which don't have raw.type specified

### ISSUE THREAD

**Issue by Rovak** [tronprotocol/java-tron#589]
Transactions which don't have a `Transaction.raw.type` specified (https://github.com/tronprotocol/protocol/blob/c7495f89fb92028b8a54606114ed7116b163d7d0/core/Tron.proto#L156) are accepted as valid transactions and will show up on `tronscan.org` but don't affect the account balance. 

`wallet-cli` includes this check in the validate function here (https://github.com/tronprotocol/wallet-cli/blob/master/src/main/java/org/tron/common/utils/TransactionUtils.java#L111) but i can't seem to find this in `java-tron`

**Comment by zhaohong** [comment]
thanks, I'll fix this later.

**Comment by zhaohong** [comment]
I will delete the   
enum TransactionType {
    UtxoType = 0;
    ContractType = 1;
 }
the utxoType is desperate.
