### ISSUE TITLE
Is there a way to synchronize data of world state and a few latest blocks only?

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/java-tron#5891]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Discord](https://discord.gg/cGKSsRVCGm) or [Telegram](https://t.me/TronOfficialDevelopersGroupEn).

**Comment by laurenceja** [comment]
@abn2357 You can try to build a LiteFulllNode which does not store all blocks. https://tronprotocol.github.io/documentation-en/developers/litefullnode/

**Comment by abn2357** [comment]
> @abn2357 You can try to build a LiteFulllNode which does not store all blocks. https://tronprotocol.github.io/documentation-en/developers/litefullnode/

@laurenceja  Thx. This is useful for me. Another question, according to the document, if I run a LiteFulllNode, I need to periodically cut the data. Whether can LiteFulllNode add a feature that automatic cut data to keep the number of blocks about 3% of all blocks.

**Comment by halibobo1205** [comment]
> automatic cut data to keep the number of blocks about 3% of all blocks.

@abn2357 Hi, this feature may make synchronizing blocks between peers unstable, e.g. the requested block may be automatically deleted by the peer.

**Comment by vivian1912** [comment]
@abn2357 May I ask if this issue has been resolved? If yes, this issue will be closed. Thanks.

**Comment by abn2357** [comment]
> @abn2357 May I ask if this issue has been resolved? If yes, this issue will be closed. Thanks.

@vivian1912 yes it can be closed
