### ISSUE TITLE
DATABASE BACKUP FOR SR ON PRIVATE NET NOT WORKING WHEN RESTARTING.

### ISSUE THREAD

**Issue by 0xarmaansidhu** [tronprotocol/java-tron#5896]
I CHANGED MY SERVER FOR MY SR ON A TRON PRIVATE NET, I MADE A ZIP FOR THE OUTPUT-DIRECTORY THEN UNZIPPED ON THE NEW SERVER ,I GET THIS ERROR WHILE STARTING IT WITH THE SAME DATABASE.
WHAT CAN BE THE ISSUE?
PS:-(I FOLLOWED THE SAME FOLDER STRUCTURE )

19:02:45.695 INFO  [main] [app](FullNode.java:69) not in debug mode, it will check energy time
19:02:49.325 ERROR [main] [DB](RocksDbDataSourceImpl.java:273) Open Database account failed
org.rocksdb.RocksDBException: While lock file: output-directory/database/account/LOCK: Resource temporarily unavailable
	at org.rocksdb.RocksDB.open(Native Method)

**Comment by endiaoekoe** [comment]
> I CHANGED MY SERVER FOR MY SR ON A TRON PRIVATE NET, I MADE A ZIP FOR THE OUTPUT-DIRECTORY THEN UNZIPPED ON THE NEW SERVER ,I GET THIS ERROR WHILE STARTING IT WITH THE SAME DATABASE.我在 TRON 专用网络上为 SR 更改了服务器，我对输出目录进行了压缩，然后在新服务器上解压缩，在使用相同的数据库启动它时出现此错误。 WHAT CAN BE THE ISSUE? 可能是什么问题？ PS:-(I FOLLOWED THE SAME FOLDER STRUCTURE ) PS：-（我遵循相同的文件夹结构）
> 
> 19:02:45.695 INFO [main] app not in debug mode, it will check energy time19:02:45.695 INFO [main] 应用程序未处于调试模式，它将检查能量时间 19:02:49.325 ERROR [main] DB Open Database account failed19:02:49.325 错误 [main] DB 打开数据库帐户失败 org.rocksdb.RocksDBException: While lock file: output-directory/database/account/LOCK: Resource temporarily unavailableorg.rocksdb.RocksDBException：锁定文件时：输出目录/数据库/帐户/LOCK：资源暂时不可用 at org.rocksdb.RocksDB.open(Native Method)在 org.rocksdb.RocksDB.open（本机方法）

hi, @0xarmaansidhu 
seems like the files you unzip from output directory are temporarily unavailable to access.
usually, it happened when the process released locks incorrectly on server shutdown.
could you make sure shut down the server instance properly and then restart on other machines with the well-saved output zip file?

**Comment by 0xarmaansidhu** [comment]
i shut the sr node by kill -9 <PID>, is that a problem.

**Comment by endiaoekoe** [comment]
> i shut the sr node by kill -9 , is that a problem.

kill -9 will terminate the process immediately and no cleanup operation can be performed.
kill -15 will be a proper way to use to shut down the service.
by the way, you can use the script java-tron provides [here](https://github.com/tronprotocol/java-tron/blob/01502f341c3e2c4c5a44139f603a124e3ac08b74/start.sh#L261) to start/restart the service.
hope it helps.

**Comment by 0xarmaansidhu** [comment]
@endiaoekoe the approach i am using will work right? for changing the sr server on private chain?

**Comment by endiaoekoe** [comment]
> MY

yes. For the details about the settings/changes that should be made,pls refer to this [doc](https://developers.tron.network/docs/tron-private-chain).
