### ISSUE TITLE
Does the contract supplied energy has the same source as user energy？

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/java-tron#5898]
<img width="805" alt="截屏2024-07-03 12 00 59" src="https://github.com/tronprotocol/java-tron/assets/165134544/b5bf1e13-321b-44ca-9e0f-ca1c861ddbff">

User energy can get from staking trx and burning trx, I wonder whether the contract supplied energy only has the source of staking? I have the question because the statistical data of total energy consists of three part as below:

<img width="414" alt="截屏2024-07-03 12 09 38" src="https://github.com/tronprotocol/java-tron/assets/165134544/9bf0fadc-4935-46e8-af1e-d700bc95c062">

**Comment by endiaoekoe** [comment]
> <img alt="截屏2024-07-03 12 00 59" width="805" src="https://private-user-images.githubusercontent.com/165134544/345276774-b5bf1e13-321b-44ca-9e0f-ca1c861ddbff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODk4NTQsIm5iZiI6MTcxOTk4OTU1NCwicGF0aCI6Ii8xNjUxMzQ1NDQvMzQ1Mjc2Nzc0LWI1YmYxZTEzLTMyMWItNDRjYS05ZTBmLWNhMWM4NjFkZGJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODFjOTA2NDdhZThmZTRlNTI4MWE1NmY0M2RkNGEwZTMxNGQwNDhlMmIzOGVmMTM2MDk0YWFjZjM2OTliZjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DU72hNfZxJWUoHUTE0F948a4RMyLjbAg7V-87CaMTpc">
> User energy can get from staking trx and burning trx, I wonder whether the contract supplied energy only has the source of staking? I have the question because the statistical data of total energy consists of three part as below:
> 
> <img alt="截屏2024-07-03 12 09 38" width="414" src="https://private-user-images.githubusercontent.com/165134544/345277710-9bf0fadc-4935-46e8-af1e-d700bc95c062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODk4NTQsIm5iZiI6MTcxOTk4OTU1NCwicGF0aCI6Ii8xNjUxMzQ1NDQvMzQ1Mjc3NzEwLTliZjBmYWRjLTQ5MzUtNDZlOC1hZjFlLWQ3MDBiYzk1YzA2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGM0NzcxN2IyYTA4ZTcxMGFjODUzYjcyNzUzM2ZmNjFiOWU3OTMwY2FhMzRmOGQyYTBmYTg2MDUzMTI1OWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2g5r7KtGn_SvCgqOzNcugZrRi7_q87vwg1GePt0hqK0">

hi, @abn2357 
for the details about energy-consumption mechanics ,pls refer to this [doc](https://developers.tron.network/v4.0/docs/energy-consumption) which explain it very carefully.

**Comment by laurenceja** [comment]
@abn2357 The contract can stake TRX to obtain energy, and it is the same with external account address. But for "Energy consumption radio", it means that the contract deployer can pay a portion of the energy required to invoke the contract, so it's talking about the contract deployer, not the contract itself. If the available energy of contract deployer is not enough or the energy paid by contract deployer has reached the upper limit, the remaining energy should be paid by caller.

**Comment by abn2357** [comment]
> @abn2357 The contract can stake TRX to obtain energy, and it is the same with external account address. But for "Energy consumption radio", it means that the contract deployer can pay a portion of the energy required to invoke the contract, so it's talking about the contract deployer, not the contract itself. If the available energy of contract deployer is not enough or the energy paid by contract deployer has reached the upper limit, the remaining energy should be paid by caller.

@laurenceja  So the "contract _supplied" energy is provided by the contract deployer?

**Comment by laurenceja** [comment]
> @laurenceja So the "contract _supplied" energy is provided by the contract deployer?

Yes.

**Comment by abn2357** [comment]
> > @laurenceja So the "contract _supplied" energy is provided by the contract deployer?
> 
> Yes.

@laurenceja My doubt has not been resolved yet. Statistical data of total energy consists of three parts: "energy", "contract_supplied", "trx", So the "trx" burning energy is all from user trx burning or from user trx burning and contract deployer trx burning both?

**Comment by laurenceja** [comment]
> @laurenceja My doubt has not been resolved yet. Statistical data of total energy consists of three parts: "energy", "contract_supplied", "trx", So the "trx" burning energy is all from user trx burning or from user trx burning and contract deployer trx burning both?

TRX burned is all from user. Contract deployer will only provide energy.

**Comment by abn2357** [comment]
> > @laurenceja My doubt has not been resolved yet. Statistical data of total energy consists of three parts: "energy", "contract_supplied", "trx", So the "trx" burning energy is all from user trx burning or from user trx burning and contract deployer trx burning both?
> 
> TRX burned is all from user. Contract deployer will only provide energy.

@laurenceja So the energy provided by the contract deployer can be obtained only by staking? In my opinion, if the energy provided by the contract deployer can be obtained by staking and burning as users, the statistical data of "trx" energy would not all be from user. Are there any problems with my understanding?

**Comment by laurenceja** [comment]
> > > @laurenceja My doubt has not been resolved yet. Statistical data of total energy consists of three parts: "energy", "contract_supplied", "trx", So the "trx" burning energy is all from user trx burning or from user trx burning and contract deployer trx burning both?
> > 
> > 
> > TRX burned is all from user. Contract deployer will only provide energy.
> 
> @laurenceja So the energy provided by the contract deployer can be obtained only by staking? In my opinion, if the energy provided by the contract deployer can be obtained by staking and burning as users, the statistical data of "trx" energy would not all be from user. Are there any problems with my understanding?

The contract deployer can only provide energy, but not TRX burning, of course, the energy can be obtained through staking TRX or other account's energy delegation.

**Comment by abn2357** [comment]
> > > > @laurenceja My doubt has not been resolved yet. Statistical data of total energy consists of three parts: "energy", "contract_supplied", "trx", So the "trx" burning energy is all from user trx burning or from user trx burning and contract deployer trx burning both?
> > > 
> > > 
> > > TRX burned is all from user. Contract deployer will only provide energy.
> > 
> > 
> > @laurenceja So the energy provided by the contract deployer can be obtained only by staking? In my opinion, if the energy provided by the contract deployer can be obtained by staking and burning as users, the statistical data of "trx" energy would not all be from user. Are there any problems with my understanding?
> 
> The contract deployer can only provide energy, but not TRX burning, of course, the energy can be obtained through staking TRX or other account's energy delegation.

@laurenceja Thanks a lot. I got it now.

**Comment by vivian1912** [comment]
@abn2357 Glad your issue was resolved. And this issue will be closed.
