### ISSUE TITLE
Wrong number of tokens received for voting on testnet

### ISSUE THREAD

**Issue by emanzanoaxa** [tronprotocol/java-tron#590]
I think there is an important bug when requesting TRX tokens to vote for SR.

1. What did you do?
I've just registered on tronscan.org and requested tokens to vote, following [Vote for delegate how-to](https://github.com/tronprotocol/Documentation/blob/master/TRON_Protocol/How_to_vote_EN.md).

2. What did you expect to see?
I expect to have 10.000 TRX to vote.

3. What did you see instead?
I've received 1.000.000 TRX tokens to vote.

**Comment by Jacob8765** [comment]
I don't think this is a bug. They changed the amount of TRX you could request from 10,000 to 1,000,000 about one week ago. I'm not sure exactly why, but I'm almost positive it was intentional.

**Comment by fbsobreira** [comment]
All translation, but English, on tronprotocol/wallet-web are showing the value 10.000. Translation needs to be updated.

**Comment by emanzanoaxa** [comment]
Oh I thought it was an error. I'm closing the issue then, thanks.
