### ISSUE TITLE
Where is the 80th network parameter?

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/java-tron#5904]
<img width="1324" alt="截屏2024-07-08 17 06 11" src="https://github.com/tronprotocol/java-tron/assets/165134544/93f4fc57-ecf1-4956-8532-a8973360c68c">

**Comment by m-o-m12** [comment]
Now there is no No.80 parameter, maybe it is under development or it is a deprecated feature. You can get all parameters from java-tron [source code](https://github.com/tronprotocol/java-tron/blob/773b374cec6668bb75911357576a41221503f806/actuator/src/main/java/org/tron/core/utils/ProposalUtil.java#L787)

**Comment by abn2357** [comment]
> Now there is no No.80 parameter, maybe it is under development or it is a deprecated feature. You can get all parameters from java-tron [source code](https://github.com/tronprotocol/java-tron/blob/773b374cec6668bb75911357576a41221503f806/actuator/src/main/java/org/tron/core/utils/ProposalUtil.java#L787) .

Is there any way to obtain the history of network parameter

**Comment by 317787106** [comment]
@abn2357 You can get all parameters by code: actuator/src/main/java/org/tron/core/utils/ProposalUtil.java

**Comment by abn2357** [comment]
> Now there is no No.80 parameter, maybe it is under development or it is a deprecated feature. You can get all parameters from java-tron [source code](https://github.com/tronprotocol/java-tron/blob/773b374cec6668bb75911357576a41221503f806/actuator/src/main/java/org/tron/core/utils/ProposalUtil.java#L787) .

@m-o-m12 In the source code, why the 80th parameter is deleted directly,  not annotated? If annotated, it will help the developers know the history.
