### ISSUE TITLE
Exchange currency incomplete

### ISSUE THREAD

**Issue by xuetong6** [tronprotocol/java-tron#5905]
BTCBOX currency incomplete
At present, BTCBOX's markets only include BTC, ETH, BCH, LTC, but lack TRX, DOT, and DOE
Please help update

**Comment by 317787106** [comment]
@xuetong6 What's BTCBOX's markets?

**Comment by abn2357** [comment]
@xuetong6 It seems none sense of this project

**Comment by vivian1912** [comment]
@xuetong6 This issue will be closed as it has nothing to do with Java-tron. And welcome any suggestions, questions, or issues about Java-tron.
