### ISSUE TITLE
Timeout occurred when synchronizing blocks

### ISSUE THREAD

**Issue by xxo1shine** [tronprotocol/java-tron#5913]
#### System information
OS : Linux
JVM : Oracle Corporation 1.8.0_411 amd64
Version : 4.7.5

#### Expected Behavior
Blocks can be synchronized and broadcasted normally, and no timeout should occur.

#### Actual Behavior
I deployed a private chain locally. The two nodes have been synchronizing and broadcasting blocks normally. However, after a while, they suddenly disconnected due to a TIME_OUT. Here is the last interaction log.
```
23:09:48.561 INFO  [peerClient-23] [net](PeerConnection.java:175) Send peer /192.168.0.15:18888 message type: SYNC_BLOCK_CHAIN
size: 5, start block: Num:61885758,ID:0000000003b04d3e2e00336955e1385188e9b60d8cf10b41dcf7da7477ff51ac, end block Num:61885778,ID:0000000003b04d52c62137c5f12f421309888ed8e3118b7b2a57e1d311dd2b3c
23:09:48.850 INFO  [peerClient-23] [net](P2pEventHandlerImpl.java:168) Receive message from  peer: /192.168.0.15:18888, type: BLOCK_CHAIN_INVENTORY
size: 3, first blockId: Num:61885778,ID:0000000003b04d52c62137c5f12f421309888ed8e3118b7b2a57e1d311dd2b3c, end blockId: Num:61885780,ID:0000000003b04d541a1c5a38f31f3ca8eefa5a77d5f3cc2522a7026e349256f5, remain_num: 0
23:10:19.831 WARN  [peer-status-check] [net](PeerStatusCheck.java:51) Peer /192.168.0.15 not sync for a long time
23:10:19.831 INFO  [peer-status-check] [net](PeerConnection.java:175) Send peer /192.168.0.15:18888 message type: P2P_DISCONNECT
reason: TIME_OUT
```

**Comment by xxo1shine** [comment]
@tomatoishealthy OK, from the logs, there was no communication for about 30 seconds at the end, and then they disconnected.

**Comment by xxo1shine** [comment]
> It sounds like you've already got the relevant logs.
> 
> Can you provide them so we can see if there are more details to help solve the problem.

The log has been posted in the issue.

**Comment by zeusoo001** [comment]
@xxo1shine There is a concurrency problem between the synchronization thread and the broadcast thread. This problem is being fixed. Please refer to pr https://github.com/tronprotocol/java-tron/pull/5879

**Comment by lvs007** [comment]
pr #5921  merge to GreatVoyage-v4.7.6
