### ISSUE TITLE
Cancellation

### ISSUE THREAD

**Issue by aguinaldok4** [tronprotocol/java-tron#5914]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Discord](https://discord.gg/cGKSsRVCGm) or [Telegram@kris9773180017.com](https://t.me/TronOfficialDevelopersGroupEn)/message InternalTransaction {
  // internalTransaction identity, the root InternalTransaction hash
  // should equals to root transaction id.
  bytes hash = 1;
  // the one send trx (TBD: or token) via function
  bytes caller_address = 2;
  // the one recieve trx (TBD: or token) via function
  bytes transferTo_address = 3;
  message CallValueInfo {
    // trx (TBD: or token) value
    int64 callValue = 1;
    // TBD: tokenName, trx should be empty
    string tokenId = 2;
  }
  repeated CallValueInfo callValueInfo = 4;
  bytes note = 5;
  bool rejected = 6;
  string extra = 7;
[}](https://t.me@telegram.com/#:kris9773180017)

**Comment by vivian1912** [comment]
@aguinaldok4 Would you please detailed this issue?
