### ISSUE TITLE
May I ask if trx has been attacked recently? Our two full nodes have been attacked recently. Please reply. Thank you.

### ISSUE THREAD

**Issue by astrid19981112** [tronprotocol/java-tron#5918]
May I ask if trx has been attacked recently? Our two full nodes have been attacked recently. Please reply. Thank you.

**Comment by L-Reid** [comment]
@astrid19981112  My node is running fine and everything looks OK from my project perspective.

**Comment by kafein** [comment]
Same for me. I had service interruptions because of DDoS attacks.

**Comment by astrid19981112** [comment]
> 你能详细描述一下这次攻击吗？这是 DDoS 攻击吗？

Yes, Ddos has a lot of traffic all of a sudden, but it doesn’t last long*. Usually there are no attacks after 5 minutes.

**Comment by astrid19981112** [comment]
> > 你能详细描述一下这次攻击吗？这是 DDoS 攻击吗？
> 
> 是的，Ddos 会突然产生大量流量，但不会持续很长时间*。通常 5 分钟后就不会再发生攻击。

Yes, Ddos has a lot of traffic all of a sudden, but it doesn’t last long*. Usually there are no attacks after 5 minutes.

**Comment by astrid19981112** [comment]
> 我也是。由于 DDoS 攻击，我的服务中断了。
> 
> <img alt="图像" width="846" src="https://private-user-images.githubusercontent.com/12200104/349900252-b267d8c3-70f4-43a4-b2ec-8b76e1bee62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTM0MTksIm5iZiI6MTcyMTM1MzExOSwicGF0aCI6Ii8xMjIwMDEwNC8zNDk5MDAyNTItYjI2N2Q4YzMtNzBmNC00M2E0LWIyZWMtOGI3NmUxYmVlNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYWE2MTkzZTFmYzAyMmQ0NDlkYTUzMjA0YmM2MzI2MjYyNDU5ZWVhZTM0OGIxNDY5NjY1ODBlZWZhMWU1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L9sCrtqavL-xGcF9_Byc35DUnoYLTlcb7zyuRb8pXDM">

Hello, is the attack time short?

**Comment by kafein** [comment]
> > 我也是。由于 DDoS 攻击，我的服务中断了。
> > <img alt="图像" width="846" src="https://private-user-images.githubusercontent.com/12200104/349900252-b267d8c3-70f4-43a4-b2ec-8b76e1bee62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTM0MTksIm5iZiI6MTcyMTM1MzExOSwicGF0aCI6Ii8xMjIwMDEwNC8zNDk5MDAyNTItYjI2N2Q4YzMtNzBmNC00M2E0LWIyZWMtOGI3NmUxYmVlNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYWE2MTkzZTFmYzAyMmQ0NDlkYTUzMjA0YmM2MzI2MjYyNDU5ZWVhZTM0OGIxNDY5NjY1ODBlZWZhMWU1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L9sCrtqavL-xGcF9_Byc35DUnoYLTlcb7zyuRb8pXDM">
> 
> Hello, is the attack time short?

Last one was about 15 minutes

**Comment by astrid19981112** [comment]
> > > 我也是。由于 DDoS 攻击，我的服务中断了。
> > > <img alt="图像" width="846" src="https://private-user-images.githubusercontent.com/12200104/349900252-b267d8c3-70f4-43a4-b2ec-8b76e1bee62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTM0MTksIm5iZiI6MTcyMTM1MzExOSwicGF0aCI6Ii8xMjIwMDEwNC8zNDk5MDAyNTItYjI2N2Q4YzMtNzBmNC00M2E0LWIyZWMtOGI3NmUxYmVlNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYWE2MTkzZTFmYzAyMmQ0NDlkYTUzMjA0YmM2MzI2MjYyNDU5ZWVhZTM0OGIxNDY5NjY1ODBlZWZhMWU1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L9sCrtqavL-xGcF9_Byc35DUnoYLTlcb7zyuRb8pXDM">
> > 
> > 
> > 你好，请问攻击时间短嗎？
> 
> 最后一次大约15分钟

I will end the attack in about 5 minutes

**Comment by astrid19981112** [comment]
> 看起来有人正在进行无差别攻击。调查正在进行中。
Thanks

**Comment by astrid19981112** [comment]
> 这几天你还遭遇攻击吗？

It’s gone now. Has it been repaired?

**Comment by abn2357** [comment]
> Could you describe the attack in detail? Is it a DDoS attack?

@tomatoishealthy Is there any way to prevent ddos attack?

**Comment by 11111961abc** [comment]
Нет не атаковали

вт, 30 июл. 2024 г., 11:16 abn2357 ***@***.***>:

**Comment by liuxuanru** [comment]
My Tron all nodes experienced a DDoS attack yesterday, which resulted in the IP unified export being blocked, affecting my entire business system Do you have any good solutions? Is there a solution to ensure secure and stable synchronization of block data without exposing the IP port of the node itself, in order to prevent such incidents from occurring??

**Comment by xxo1shine** [comment]
@astrid19981112 There is no perfect way to defend against DDoS attacks. We are working hard to improve this. The impact of DDoS attacks is currently limited. It may temporarily affect block synchronization, but will not have a significant impact on the chain or data consistency.

**Comment by vivian1912** [comment]
@astrid19981112 Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
