### ISSUE TITLE
Archive node snapshot source - getting 502/503 on backup.trongrid.io

### ISSUE THREAD

**Issue by ttibord** [tronprotocol/java-tron#5931]
We used to rely on [TronGrid backups](https://backup.trongrid.io/) for an archive node snapshot, now the page returns 503 after returning 502 in previous attempts. I'm not seeing it mentioned in the [official snapshot docs](https://developers.tron.network/docs/main-net-database-snapshots) - was it abandoned, or should it still work and is there an issue that can be resolved?

If TronGrid backups are abandoned, can you confirm which of the [officially listed snapshots](https://developers.tron.network/docs/main-net-database-snapshots#fullnode-data-snapshot) would be the equivalent of what used to be hosted by TronGrid? I'm asking because the most archive-looking snapshot `Official data source with accountbalance` states that it lacks internal transactions, which are included in other smaller snapshots.

Thank you!

**Comment by ExOCeo** [comment]
Trongrid does not provide snapshot download for a while. And as far as I know the trongrid snapshot does not contain trx balance for all accounts as well, only contains internal transactions. So if you get used to the trongrid backups, pick the one with internal transactions in the offcial list.

**Comment by KrisdiaPaul** [comment]
> We used to rely on [TronGrid backups](https://backup.trongrid.io/) for an archive node snapshot, now the page returns 503 after returning 502 in previous attempts. I'm not seeing it mentioned in the [official snapshot docs](https://developers.tron.network/docs/main-net-database-snapshots) - was it abandoned, or should it still work and is there an issue that can be resolved?
> 
> If TronGrid backups are abandoned, can you confirm which of the [officially listed snapshots](https://developers.tron.network/docs/main-net-database-snapshots#fullnode-data-snapshot) would be the equivalent of what used to be hosted by TronGrid? I'm asking because the most archive-looking snapshot `Official data source with accountbalance` states that it lacks internal transactions, which are included in other smaller snapshots.
> 
> Thank you!

TRONgrid backup is abandoned, you could only select from the [official snapshot docs](https://developers.tron.network/docs/main-net-database-snapshots) list. You may need to get balance and internal transactions separately.

**Comment by ttibord** [comment]
Thanks, @ExOCeo and @KrisdiaPaul - we'll be checking the `Official data source (Singapore)` on [35.247.128.170](http://35.247.128.170/) - any EU/US mirror planned, if you know?

Also, can someone please confirm, based on the APIs we currently scrape - that we don't care for account balances, and can go only for internal txs for now:
- `eth_getBlockByNumber`
- `eth_getTransactionReceipt`
- `eth_call` (latest state only)
- `wallet/gettransactioninfobyid`
- `wallet/getblock`

**Comment by ttibord** [comment]
Great, thanks for the details, and fast responses!
