### ISSUE TITLE
What id tokenId?

### ISSUE THREAD

**Issue by web3-coder-hub** [tronprotocol/java-tron#5932]
![WeChat6a03d553f8246aef3ad6857beca71ca4](https://github.com/user-attachments/assets/a401a739-0033-47ef-a1a3-c13e7511065b)
what is the USDT's token id,if I set the USDT's ContractAddress, it must be a int64.so where can i get the token id of USDT?

**Comment by laurenceja** [comment]
@web3-coder-hub It is the TRC10 token's ID, if you need to transfer trc10 token to contract when you triggering smart contract, use this parameter to set the trc10 id.

**Comment by endiaoekoe** [comment]
> ![WeChat6a03d553f8246aef3ad6857beca71ca4](https://private-user-images.githubusercontent.com/94896756/352715381-a401a739-0033-47ef-a1a3-c13e7511065b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjE0NTIsIm5iZiI6MTcyMjIyMTE1MiwicGF0aCI6Ii85NDg5Njc1Ni8zNTI3MTUzODEtYTQwMWE3MzktMDAzMy00N2VmLWExYTMtYzEzZTc1MTEwNjViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAyNDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNzVjZTY1OThmNjJkNTk5Y2NkYWQ0MDEyODI3ZGZlNGVjMjNkNzJmMzFhMTcwMWQ0NDY2NzljZTExY2I1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_GKOIv1Vv3qMpbc6aimftoCSt1GWa2i5plUrZbYEts) what is the USDT's token id,if I set the USDT's ContractAddress, it must be a int64.so where can i get the token id of USDT?

@web3-coder-hub if you want to transfer usdt, You can choose to use this field 'data' to fulfill your request. See the example [here](https://developers.tron.network/docs/trc20-contract-interaction#transfer)

**Comment by web3-coder-hub** [comment]
> > ![WeChat6a03d553f8246aef3ad6857beca71ca4](https://private-user-images.githubusercontent.com/94896756/352715381-a401a739-0033-47ef-a1a3-c13e7511065b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjE0NTIsIm5iZiI6MTcyMjIyMTE1MiwicGF0aCI6Ii85NDg5Njc1Ni8zNTI3MTUzODEtYTQwMWE3MzktMDAzMy00N2VmLWExYTMtYzEzZTc1MTEwNjViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAyNDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNzVjZTY1OThmNjJkNTk5Y2NkYWQ0MDEyODI3ZGZlNGVjMjNkNzJmMzFhMTcwMWQ0NDY2NzljZTExY2I1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_GKOIv1Vv3qMpbc6aimftoCSt1GWa2i5plUrZbYEts) what is the USDT's token id,if I set the USDT's ContractAddress, it must be a int64.so where can i get the token id of USDT?
> 
> @web3-coder-hub if you want to transfer usdt, You can choose to use this field 'data' to fulfill your request. See the example [here](https://developers.tron.network/docs/trc20-contract-interaction#transfer)

Ok,than you !

**Comment by 0xbigapple** [comment]
USDT is TRC20 token, only TRC10 needs tokenId.
query TRC10 TokenID. [here](https://developers.tron.network/reference/getassetissuebyname)
transfer TRC10 token in Smart Contracts [here](https://developers.tron.network/docs/trc10-transfer-in-smart-contracts)
transfer TRC20 token in Smart Contracts [here](https://developers.tron.network/docs/trc20-contract-interaction#transfer)

**Comment by web3-coder-hub** [comment]
> USDT is TRC20 token, only TRC10 needs tokenId. query TRC10 TokenID. [here](https://developers.tron.network/reference/getassetissuebyname) transfer TRC10 token in Smart Contracts [here](https://developers.tron.network/docs/trc10-transfer-in-smart-contracts) transfer TRC20 token in Smart Contracts [here](https://developers.tron.network/docs/trc20-contract-intera
![WeChat4088e118dad64f0929cb05b8ee0b8f9e](https://github.com/user-attachments/assets/275546ad-fa4b-444b-b602-df4e2d6a50a1)
ction#transfer)
these address is encoded,but

![WeChat101266c941719e7137ccc9e6d636d568](https://github.com/user-attachments/assets/3304497f-3084-4dde-a3a5-acb2ee7d3e71)
these address no encode, So do i need to encode it?

**Comment by 0xbigapple** [comment]
<img width="478" alt="image" src="https://github.com/user-attachments/assets/08353eb6-250c-4416-8ab5-e8d0006d7c3a">

**Comment by 0xbigapple** [comment]
> > USDT is TRC20 token, only TRC10 needs tokenId. query TRC10 TokenID. [here](https://developers.tron.network/reference/getassetissuebyname) transfer TRC10 token in Smart Contracts [here](https://developers.tron.network/docs/trc10-transfer-in-smart-contracts) transfer TRC20 token in Smart Contracts [here](https://developers.tron.network/docs/trc20-contract-intera
> > ![WeChat4088e118dad64f0929cb05b8ee0b8f9e](https://private-user-images.githubusercontent.com/94896756/353303586-275546ad-fa4b-444b-b602-df4e2d6a50a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTk4NzksIm5iZiI6MTcyMjUxOTU3OSwicGF0aCI6Ii85NDg5Njc1Ni8zNTMzMDM1ODYtMjc1NTQ2YWQtZmE0Yi00NDRiLWI2MDItZGY0ZTJkNmE1MGExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEzMzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZDE2MjdmZDU1YzNhZmRkZDcyM2NjNTQxOWE0ZWEwZTZjN2FhYWRiNTk3NjFlMjFhMDhjZmZhYjI3Nzg3ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8kvVQUIYMEYhhqtIh4R_VoG2An8FYEbTMRJv9diJbZA)
> > ction#transfer)
> > these address is encoded,but
> 
> ![WeChat101266c941719e7137ccc9e6d636d568](https://private-user-images.githubusercontent.com/94896756/353303695-3304497f-3084-4dde-a3a5-acb2ee7d3e71.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTk4NzksIm5iZiI6MTcyMjUxOTU3OSwicGF0aCI6Ii85NDg5Njc1Ni8zNTMzMDM2OTUtMzMwNDQ5N2YtMzA4NC00ZGRlLWEzYTUtYWNiMmVlN2QzZTcxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEzMzkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYzgyNDFiMTE5ZDI5Nzk4Y2Q2ZGEyOWI2ZTBhMDg1YTQ2YjY1ZjcxNGFjMGJkYTE4ZTJhYWNmNzM5MjcyOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O_5GgW6fcH8U_oLdlwgAOFj-cdX-Lo2jHl0m4cVryQg) these address no encode, So do i need to encode it?


visible default is true， so don't need encode
<img width="478" alt="image" src="https://github.com/user-attachments/assets/3ceff07a-199f-4277-9850-9b917676d753">

**Comment by 11111961abc** [comment]
Кодируй и вышли мне для снятия денег

чт, 1 авг. 2024 г., 19:47 0xbigapple ***@***.***>:
