### ISSUE TITLE
About the transaction fee when transferring TRC20 tokens

### ISSUE THREAD

**Issue by VetchM** [tronprotocol/java-tron#5933]
I just found out that transferring USDT to an address that holds some USDT is a lot cheaper than transferring to an address that holds **zero USDT**. But I couldn't find anything in the docs that can explain this. Why does the transaction fee change based on the recipient's  USDT balance?

**Comment by 0xbigapple** [comment]
I also meet this problem，because the characteristics of the TRON virtual machine. If the variable value is empty, the SSTORE operation to set it will consume more energy than modifying a non-empty value.
Thanks to @laurenceja

**Comment by abn2357** [comment]
> I also meet this problem，because the characteristics of the TRON virtual machine. If the variable value is empty, the SSTORE operation to set it will consume more energy than modifying a non-empty value. Thanks to @laurenceja

btw,  in which function of usdt contract is SSTORE operation called?

**Comment by 0xbigapple** [comment]
> > I also meet this problem，because the characteristics of the TRON virtual machine. If the variable value is empty, the SSTORE operation to set it will consume more energy than modifying a non-empty value. Thanks to @laurenceja
> 
> btw, in which function of usdt contract is SSTORE operation called?

TRC20 usually has a mapping structure for storing account balances.
`mapping(address => uint256) private  balanceOf;`
When a transfer is made to an address for the first time with a token, and there is no existing entry in the mapping for that address in the token contract, the smart contract needs to create this new entry in the mapping.

In the TRON Virtual Machine (TVM), the energy consumption of the SSTORE instruction is as follows:

**- Setting a New Non-zero Value:** 20,000 gas
**- Modifying an Existing Non-zero Value:** 5,000 gas
**- Setting a Non-zero Value to Zero:** 5,000 gas

**Comment by vivian1912** [comment]
@VetchM Does this answer your question? This issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
