### ISSUE TITLE
How to calculate the final TRX in an ExchangeTransactionContract

### ISSUE THREAD

**Issue by Hulumulula** [tronprotocol/java-tron#5934]
I need to calculate how much TRX was received or sent in an exchange and preferably do it through a node (if possible).

I found 3 url's that help me a little bit, but don't solve the problem:

1) wallet/getassetissuebyid Allows me to get me the balances of a couple, but as I understand it, it's the balance now, not at any particular moment

2) wallet/getexchangebyid Allows me to get the token information

3) wallet/gettransactionbyid Get the transaction from the node.

The whole problem is that 3) option returns 2 important fields:
- quant
- expected

But the final TRX value when exchanging token for TRX is almost always different from expected. And how to calculate it - I don't know.

Also I found information in Tron documentation, where they talk about Bancor protocol, but they don't have any information about token exchange in Tron network.

**Comment by endiaoekoe** [comment]
hi, @Hulumulula 
below is the mechanism of  how to calculate the amount of Token You Can Get:

sellTokenQuant is the amount of the first_token you want to sell.
buyTokenQuant is the amount of second_token you can get.

eg:
supply = 1_000_000_000_000_000_000L
supplyQuant = -supply * (1.0 - Math.pow(1.0 + (double) sellTokenQuant/(firstTokenBalance + sellTokenQuant, 0.0005))
buyTokenQuant = (long)balance * (Math.pow(1.0 + (double) supplyQuant / supply, 2000.0) - 1.0)

for more details , you can refer to this [docs](https://tronprotocol.github.io/documentation-en/mechanism-algorithm/dex/#calculate-the-amount-of-token-you-can-get);

**Comment by abn2357** [comment]
> hi, @Hulumulula below is the mechanism of how to calculate the amount of Token You Can Get:
> 
> sellTokenQuant is the amount of the first_token you want to sell. buyTokenQuant is the amount of second_token you can get.
> 
> eg: supply = 1_000_000_000_000_000_000L supplyQuant = -supply * (1.0 - Math.pow(1.0 + (double) sellTokenQuant/(firstTokenBalance + sellTokenQuant, 0.0005)) buyTokenQuant = (long)balance * (Math.pow(1.0 + (double) supplyQuant / supply, 2000.0) - 1.0)
> 
> for more details , you can refer to this [docs](https://tronprotocol.github.io/documentation-en/mechanism-algorithm/dex/#calculate-the-amount-of-token-you-can-get);

@endiaoekoe  Is this calculation method suitable for all liquidity pools of DEX on Tron.

**Comment by endiaoekoe** [comment]
@abn2357 in my understanding,DEX in Tron is composed of many exchange pairs using Bancor protocol. and the exchange tokens are limited to TRC10 token/TRX;
but liquidity pools are concepts of Defi which involve in TRC20 tokens and smart contracts(eg:USDT);
To clarify , they are different things;

**Comment by abn2357** [comment]
> @abn2357 in my understanding,DEX in Tron is composed of many exchange pairs using Bancor protocol. and the exchange tokens are limited to TRC10 token/TRX; but liquidity pools are concepts of Defi which involve in TRC20 tokens and smart contracts(eg:USDT); To clarify , they are different things;

@endiaoekoe Exchange tokens limited TRC10 token/TRX don't need liquidity pool? I don't think so, in the [docs](https://tronprotocol.github.io/documentation-en/mechanism-algorithm/dex/) you refered, it also has exchange pair injection, a way to add liquidity and decrease range of ratio fluctuation.This is why I ask the question.
