### ISSUE TITLE
Is there a mathematical formula that can calculate the approximate time to synchronize blocks given hardware and network condition?

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/java-tron#5935]

**Comment by endiaoekoe** [comment]
hi, @abn2357 
currently, It is recommended to use this specifications for a Fullnode, as below
```
CPU：16 cores
RAM：32G
Bandwidth：100M
SSD：2.5T+
```
in the recommended config and network condition, It will cost **300ms to sync one block**, you can calculate using this formula to get the approximate time you will cost;

**Comment by charil10** [comment]
yes you can do it, but its better to use snapshot
