### ISSUE TITLE
How much TRX will cost to deoloy a smart contract on Tron?

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/java-tron#5941]

**Comment by 0xbigapple** [comment]
Deploying a smart contract on Tron consumes bandwidth and energy，the amount is related to the contract's complexity.  

bandwidth calculations [here](https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-callingdeploying-a-contract). The unit price of bandwidth is **0.001TRX**.

energy calculations [here](https://developers.tron.network/docs/set-feelimit#how-to-estimate-the-energy-consumption-of-a-contract-deployment-transaction) .The unit price of Energy is **0.00042TRX**.

**Comment by abn2357** [comment]
> Deploying a smart contract on Tron consumes bandwidth and energy，the amount is related to the contract's complexity.
> 
> bandwidth calculations [here](https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-callingdeploying-a-contract). The unit price of bandwidth is **0.001TRX**.
> 
> energy calculations [here](https://developers.tron.network/docs/set-feelimit#how-to-estimate-the-energy-consumption-of-a-contract-deployment-transaction) .The unit price of Energy is **0.00042TRX**.

@0xbigapple Which kind of complexity?Could you give me more detail information?For example, I know size of contract affect bandwidth consumption

**Comment by endiaoekoe** [comment]
@abn2357 
per my understanding ,there are several factors which have effect on the cost amount for deploy a smart contract,as below:
1.Code Length:
Longer code requires more storage space, potentially increasing deployment costs.
2.Number and Complexity of Functions:
The logical complexity of each function also contributes to overall complexity.
3.Data Structures:
Complex data structures (e.g., nested mappings, large arrays) increase complexity.
4.Loops and Recursion:
Contracts with loops (especially nested ones) and recursive functions are typically more complex.
These structures can lead to higher computational complexity and gas consumption.
5.External Contract Interactions:
Frequency and method of interactions with other contracts.
Frequent calls to external contracts or libraries increase complexity.

**Comment by abn2357** [comment]
> @abn2357 per my understanding ,there are several factors which have effect on the cost amount for deploy a smart contract,as below: 1.Code Length: Longer code requires more storage space, potentially increasing deployment costs. 2.Number and Complexity of Functions: The logical complexity of each function also contributes to overall complexity. 3.Data Structures: Complex data structures (e.g., nested mappings, large arrays) increase complexity. 4.Loops and Recursion: Contracts with loops (especially nested ones) and recursive functions are typically more complex. These structures can lead to higher computational complexity and gas consumption. 5.External Contract Interactions: Frequency and method of interactions with other contracts. Frequent calls to external contracts or libraries increase complexity.

@endiaoekoe  I have a question about "Complexity of Functions", I just deploy a smart contract, not to call a function of the smart contract, Why the deploying fee involved in with Complexity of Functions?

**Comment by abn2357** [comment]
> > > @abn2357 per my understanding ,there are several factors which have effect on the cost amount for deploy a smart contract,as below: 1.Code Length: Longer code requires more storage space, potentially increasing deployment costs. 2.Number and Complexity of Functions: The logical complexity of each function also contributes to overall complexity. 3.Data Structures: Complex data structures (e.g., nested mappings, large arrays) increase complexity. 4.Loops and Recursion: Contracts with loops (especially nested ones) and recursive functions are typically more complex. These structures can lead to higher computational complexity and gas consumption. 5.External Contract Interactions: Frequency and method of interactions with other contracts. Frequent calls to external contracts or libraries increase complexity.
> > 
> > 
> > @endiaoekoe I have a question about "Complexity of Functions", I just deploy a smart contract, not to call a function of the smart contract, Why the deploying fee involved in with Complexity of Functions?
> 
> @abn2357 when deploy a smart contract, for example, if the function is highly optimized ,it will save a lot of fee.otherwise,it will cost more fees when deploy it.

@endiaoekoe I think it is not the answer of my question.  Does "Complexity of Functions" means those functions that will be called like the constructor function when deploy a smart contract?

**Comment by endiaoekoe** [comment]
> Does "Complexity of Functions" means those functions that will be called like the constructor function when deploy a smart contract?

@abn2357 
yes
for example, the constructor function of USDT contract will be called when deplopy the contract.some optimization can save some fees when deploy.
i just found a refer [docs ]([Awesome Solidity Gas-Optimization](https://github.com/0xisk/awesome-solidity-gas-optimization))which detailed many gas optimization skills.
also ,you can read this paper about how to save gas/fee when deploy a smart contract.[[Saving Deployment Costs of Smart Contracts by Eliminating Gaswasteful Patterns - 2017](https://article.nadiapub.com/IJGDC/vol10_no12/6.pdf)]
hope this helps.

**Comment by abn2357** [comment]
> > Does "Complexity of Functions" means those functions that will be called like the constructor function when deploy a smart contract?
> 
> @abn2357 yes for example, the constructor function of USDT contract will be called when deplopy the contract.some optimization can save some fees when deploy. i just found a refer [docs ]([Awesome Solidity Gas-Optimization](https://github.com/0xisk/awesome-solidity-gas-optimization))which detailed many gas optimization skills. also ,you can read this paper about how to save gas/fee when deploy a smart contract.[[Saving Deployment Costs of Smart Contracts by Eliminating Gaswasteful Patterns - 2017](https://article.nadiapub.com/IJGDC/vol10_no12/6.pdf)] hope this helps.

Thx a lot

**Comment by abn2357** [comment]
> > Does "Complexity of Functions" means those functions that will be called like the constructor function when deploy a smart contract?
> 
> @abn2357 yes for example, the constructor function of USDT contract will be called when deplopy the contract.some optimization can save some fees when deploy. i just found a refer [docs ]([Awesome Solidity Gas-Optimization](https://github.com/0xisk/awesome-solidity-gas-optimization))which detailed many gas optimization skills. also ,you can read this paper about how to save gas/fee when deploy a smart contract.[[Saving Deployment Costs of Smart Contracts by Eliminating Gaswasteful Patterns - 2017](https://article.nadiapub.com/IJGDC/vol10_no12/6.pdf)] hope this helps.

@endiaoekoe  btc, I have another question, what is the average fee of smart contract triggered transaction on tron mainnet now? Thx.

**Comment by endiaoekoe** [comment]
> what is the average fee of smart contract triggered transaction on tron mainnet now? Thx.

@abn2357 
as we know, there are tons of smart contracts in Tron mainnet, and the fees are different for different contracts when triggering transactions.
also, USDT contract is the biggest contract in Tron maninet(I guess the USDT contract is also one of the biggest contracts in Ethereum mainnet), so I will use the USDT contract as an example, which applies to other contracts(as a reference).
below is the average fee to transfer usdt:
![image](https://github.com/user-attachments/assets/ecc34353-c047-4759-9659-194c3e3cda3b)
for the details , please refer to this [site ](https://gasfeesnow.com/heatmap/#tron)which has more explanations;

**Comment by abn2357** [comment]
> > what is the average fee of smart contract triggered transaction on tron mainnet now? Thx.
> 
> @abn2357 as we know, there are tons of smart contracts in Tron mainnet, and the fees are different for different contracts when triggering transactions. also, USDT contract is the biggest contract in Tron maninet(I guess the USDT contract is also one of the biggest contracts in Ethereum mainnet), so I will use the USDT contract as an example, which applies to other contracts(as a reference). below is the average fee to transfer usdt: ![image](https://private-user-images.githubusercontent.com/7970865/355360139-ecc34353-c047-4759-9659-194c3e3cda3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDU2MDcsIm5iZiI6MTcyMzAwNTMwNywicGF0aCI6Ii83OTcwODY1LzM1NTM2MDEzOS1lY2MzNDM1My1jMDQ3LTQ3NTktOTY1OS0xOTRjM2UzY2RhM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMDQzNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDAwZWI3ZWU4ZDc1YzA1NTlmODg0Njk3ZTQ5OTk1Yjk4ODU4YWMwZmY1MDkzN2YxMmI5ZTlhNDEyMGEyZDgwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DhmOx29N-bYhQ-6JTP_HEGXgyhfdsuQjBhPv-Cn66CI) for the details , please refer to this [site ](https://gasfeesnow.com/heatmap/#tron)which has more explanations;

@endiaoekoe  Is the unit of the vertical axis dollar?

**Comment by endiaoekoe** [comment]
> Is the unit of the vertical axis dollar?

yes

**Comment by abn2357** [comment]
> > Is the unit of the vertical axis dollar?
> 
> yes

@endiaoekoe usdt example may be not suit for me. I plan to develop a defi smart contract on tron,  do you have information of average transaction fee of sunswap or justlend? Thx.

**Comment by endiaoekoe** [comment]
> do you have information of average transaction fee of sunswap or justlend? Thx.

currently,there are no any public resource about the fees of invoke transaction in justlend contract.
but I will do this if I want to develop a contract in tron and want to know the average fee the txs of the contract will cost,as below:
1.find the [justlend contract](https://tronscan.org/#/contract/TE2RzoSV3wFK99w6J9UnnZ4vLfXYoxvRwP/transactions) in tronscan.
2.Use a blockchain browser (e.g. tronscan) to view the transaction logs for the contract address
3.In the transaction log, find the "Resources Consumed & Fee" field for each transaction, which indicates the amount of gas consumed by that transaction.
4.store the fee of every tx in db,and then analysis later.

**Comment by vivian1912** [comment]
@abn2357 May I ask if this issue has been resolved? If yes, this issue will be closed. Thanks.

**Comment by abn2357** [comment]
> @abn2357 May I ask if this issue has been resolved? If yes, this issue will be closed. Thanks.
@vivian1912  yes it can be closed
