### ISSUE TITLE
Insider trading that doesn't exist

### ISSUE THREAD

**Issue by dg123lzk** [tronprotocol/java-tron#5945]
When access to insider trading, a few more note equals 756 e667265657a6542616c616e63655632466f72456e65726779 deal, is only the right note is 63616 c6c is insider trading?

{
"hash": "cf2dac12c60f83a421797b5e87f025f5788eecfd74e4fb57c63bed3c33ded2ec",
"caller_address": "41c60a6f5c81431c97ed01b61698b6853557f3afd4",
"transferTo_address": "41c64e69acde1c7b16c2a3efcdbbdaa96c3644c2b3",
"callValueInfo": [{
"callValue": 18108682
}].
"note": "63616c6c"
}, {
"hash": "680ca9f11dae39b1c2e32b165cbe352ff21b029dcbb843aaeeda2537af85adec",
"caller_address": "41c64e69acde1c7b16c2a3efcdbbdaa96c3644c2b3",
"transferTo_address": "41c64e69acde1c7b16c2a3efcdbbdaa96c3644c2b3",
"callValueInfo": [{}],
"note": "63616c6c"
}, {
"hash": "7ab8718bc6f5aea10f739e7270a078167d726672aa91bb98206b9abd5c122179",
"caller_address": "41c64e69acde1c7b16c2a3efcdbbdaa96c3644c2b3",
"transferTo_address": "41c64e69acde1c7b16c2a3efcdbbdaa96c3644c2b3",
"callValueInfo": [{
"callValue": 1579932023
}].
"note": "756e667265657a6542616c616e63655632466f72456e65726779"
}, {
"hash": "59989573ffb6afc2c6ae02f32ae22fa969c87d7d588ea2893002c8baba65aaa8",
"caller_address": "41c64e69acde1c7b16c2a3efcdbbdaa96c3644c2b3",
"transferTo_address": "41c64e69acde1c7b16c2a3efcdbbdaa96c3644c2b3",
"callValueInfo": [{
"callValue": 1314750458
}].
"note": "7769746864726177457870697265556e667265657a655768696c65556e667265657a696e67"
}, {
"hash": "35485f0d3a623f7c6c14b165483d40657618e01ca4133e5d2d943bc483ba0d5c",
"caller_address": "41c64e69acde1c7b16c2a3efcdbbdaa96c3644c2b3",
"transferTo_address": "41c60a6f5c81431c97ed01b61698b6853557f3afd4",
"callValueInfo": [{}],
"note": "63616c6c"
}, {
"hash": "87fa3108da17b48dab7f8a616442c2666b0c6e37d4022db50d5d4172e7ce630d",
"caller_address": "41c60a6f5c81431c97ed01b61698b6853557f3afd4",
"transferTo_address": "41c60a6f5c81431c97ed01b61698b6853557f3afd4",
"callValueInfo": [{}],
"note": "63616c6c"
}

**Comment by 317787106** [comment]
@dg123lzk Inner transaction's hash is the column "hash". The hex string of "call" is "63616c6c", and hex string of "unfreezeBalanceV2ForEnergy" is "756e667265657a6542616c616e63655632466f72456e65726779".

**Comment by xxo1shine** [comment]
@dg123lzk `63616c6c` is an internal call, `756e667265657a6542616c616e63655632466f72456e65726779`
is an internal call to unfreezeBalanceV2ForEnergy. For details, please refer to this document https://developers.tron.network/docs/tron-protocol-transaction#the-examples-of-internal-transactions
