### ISSUE TITLE
Duplicate records and no event_indeing

### ISSUE THREAD

**Issue by Himanityagi27** [tronprotocol/java-tron#5946]
I setup mongodb as event plugin in tron for event subscription, setup using the docs ..
what i have noticed is

1. there are lots of duplicate records ie same tx record occurring twice in the entire block record.
2. there is no event_Index for the tx record.
Any suggestions , How i solved this issue ..

**Comment by 0xbigapple** [comment]
I have encountered the same problem, I avoided it by modifying my contract events. 😃

**Comment by Himanityagi27** [comment]
> I have encountered the same problem, I avoided it by modifying my contract events. 😃

what modification you did in your contract events..?

**Comment by Himanityagi27** [comment]
what modifications you did in your contract events..?

**Comment by 317787106** [comment]
@Himanityagi27 In the [event-plugin ](https://github.com/tronprotocol/event-plugin), ths descrption is :  
```
event.subscribe = {
    path = "" // absolute path of plugin
    server = "" // target server address to receive event triggers
    // dbname|username|password, if you want to create indexes for collections when the 
    //collections are not exist, you can add version and set it to 2, as dbname|username|password|version
    dbconfig = "" 
  ...
}
```

You should use dbconfig = "dbname|username|password|2" . If you start the mongodb with no collection, it will create the index automatically, including uniqie index. Or you can drop all old collections and restart fullnode.

**Comment by 317787106** [comment]
@Himanityagi27 You can also create these indexes manually:
```
db.block.createIndex({'blockNumber':1})

db.contractevent.createIndex({'uniqueId':1}, {unique:true})

db.contractlog.createIndex({'contractAddress':1})
db.contractlog.createIndex({'uniqueId':1}, {unique:true})

db.solidity.createIndex({'latestSolidifiedBlockNumber':1},{unique:true})

db.solidityevent.createIndex({'uniqueId':1},{unique:true})

db.soliditylog.createIndex({'contractAddress':1})
db.soliditylog.createIndex({'uniqueId':1},{unique:true})

db.transaction.createIndex({'transactionId':1},{unique:true})
```

**Comment by Himanityagi27** [comment]
> @Himanityagi27 In the [event-plugin ](https://github.com/tronprotocol/event-plugin), ths descrption is :
> 
> ```
> event.subscribe = {
>     path = "" // absolute path of plugin
>     server = "" // target server address to receive event triggers
>     // dbname|username|password, if you want to create indexes for collections when the 
>     //collections are not exist, you can add version and set it to 2, as dbname|username|password|version
>     dbconfig = "" 
>   ...
> }
> ```
> 
> You should use dbconfig = "dbname|username|password|2" . If you start the mongodb with no collection, it will create the index automatically, including uniqie index. Or you can drop all old collections and restart fullnode.

i already define dbconfig ,

**Comment by 317787106** [comment]
> > @Himanityagi27 In the [event-plugin ](https://github.com/tronprotocol/event-plugin), ths descrption is :
> > ```
> > event.subscribe = {
> >     path = "" // absolute path of plugin
> >     server = "" // target server address to receive event triggers
> >     // dbname|username|password, if you want to create indexes for collections when the 
> >     //collections are not exist, you can add version and set it to 2, as dbname|username|password|version
> >     dbconfig = "" 
> >   ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should use dbconfig = "dbname|username|password|2" . If you start the mongodb with no collection, it will create the index automatically, including uniqie index. Or you can drop all old collections and restart fullnode.
> 
> i already define dbconfig ,

Try to create index manually. It will create collection and index only when the collection is not exisit.

**Comment by vivian1912** [comment]
@Himanityagi27 May I ask if this issue has been resolved? If yes, this issue will be closed. Thanks.
