### ISSUE TITLE
Tron exposes IP ports on all nodes, leading to attacks

### ISSUE THREAD

**Issue by liuxuanru** [tronprotocol/java-tron#5955]
My Tron all nodes experienced a DDoS attack yesterday, which resulted in the IP unified export being blocked, affecting my entire business system Do you have any good solutions? Is there a solution to ensure secure and stable synchronization of block data without exposing the IP port of the node itself, in order to prevent such incidents from occurring??

**Comment by abn2357** [comment]
Is there a way not to expose ip  under the circumstance of nodes communication?

**Comment by abn2357** [comment]
> Refer to this [#5918 (comment)](https://github.com/tronprotocol/java-tron/issues/5918#issuecomment-2290524298)

@tomatoishealthy Is there a way not to expose ip under circumstance of nodes communication?
