### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by paulvi** [tronprotocol/java-tron#596]
Where are or when there will be Binary releases ?

Not all users are developers.

**Comment by grandpaWilly** [comment]
Pretty sure you're going to have to wait until Main Net if you're not willing to compile this code. The instructions tell you how to pull the repository and build it. If you have any questions about it, feel free to DM me on here or Reddit  @  /u/Grandpa_Willy

**Comment by taihaofu** [comment]
The code to generate binary release is ready. We will provide Binary in future release. So, close it for now. 

Thanks.
