### ISSUE TITLE
Node won't start on Windows Server 2019

### ISSUE THREAD

**Issue by jcube2024** [tronprotocol/java-tron#5964]
0:04:31.016 INFO  [main] [app](FullNode.java:69) not in debug mode, it will check energy time
00:04:31.579 WARN  [getIp] [net](NetUtil.java:111) Fail to get ipv4 by https://4.ipw.cn/, cause:Server returned HTTP response code: 403 for URL: https://4.ipw.cn/
00:04:36.856 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB account open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
00:04:36.918 INFO  [main] [app](DefaultConfig.java:49) key-value data source created.
00:04:36.981 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB tmp open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:37.074 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB accountTrie open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:37.137 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB balance-trace open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:37.184 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB account-trace open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:37.293 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB properties open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:37.668 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB account-asset open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:40.439 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB block open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:40.517 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB witness open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:40.579 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB asset-issue open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:40.704 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB asset-issue-v2 open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:40.798 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB block-index open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:40.845 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB accountid-index open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:40.876 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB account-index open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:40.939 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB witness_schedule open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.017 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB votes open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.064 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB proposal open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.142 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB exchange open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.236 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB exchange-v2 open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.298 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB market_account open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.345 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB market_order open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.407 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB market_pair_price_to_order open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.486 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB market_pair_to_price open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.548 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB abi open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.611 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB code open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.782 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB contract open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
00:04:41.959 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB contract-state open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:42.131 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB DelegatedResource open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:42.240 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB DelegatedResourceAccountIndex open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:42.600 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB storage-row open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
00:04:42.662 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB nullifier open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:42.709 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB zkProof open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:42.756 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB IncrementalMerkleTree open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:42.975 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB delegation open success with writeBufferSize 64 M, cacheSize 32 M, maxOpenFiles 100.
00:04:43.053 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB block_KDB open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:43.115 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB common open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:47.026 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB trans open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:48.537 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB transactionRetStore open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:48.630 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB recent-block open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:48.708 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB recent-transaction open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:49.318 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB transactionHistoryStore open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:49.380 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB common-database open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:49.443 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB pbft-sign-data open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:49.490 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB tree-block-index open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:49.615 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB section-bloom open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:49.865 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB trans-cache open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:50.015 INFO  [main] [DB](LevelDbDataSourceImpl.java:149) DB reward-vi open success with writeBufferSize 16 M, cacheSize 32 M, maxOpenFiles 100.
00:04:50.562 INFO  [main] [DB](SnapshotManager.java:511) checkpoint v1 recover success
00:04:50.562 INFO  [main] [DB](TxCacheDB.java:287) txCache init optimization is disabled, skip fast recovery mode.
00:04:50.562 INFO  [main] [DB](TxCacheDB.java:288) If you want fast recovery mode, please set `storage.txCache.initOptimization = true` in config.conf.
00:05:21.656 INFO  [main] [DB](TxCacheDB.java:180) Load cache from recentTransactionStore, filter: 14205329, filter-fpp: 5.0040865787850045E-5, cost: 28401 ms.
00:05:21.656 INFO  [rewardViCalService] [rewardViCalService](RewardViCalService.java:174) calcMerkleRoot start
00:05:21.931 INFO  [main] [DB](Manager.java:538) Current headNum is: 64287648.
00:05:21.931 INFO  [main] [DB](Manager.java:540) Node type is: full.
00:05:22.348 INFO  [main] [o.r.Reflections](Reflections.java:232) Reflections took 401 ms to scan 1 urls, producing 495 keys and 2843 values 
00:05:22.535 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:478) Autowired annotation is not supported on static fields: private static final java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractLogTriggerMap
00:05:22.535 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:478) Autowired annotation is not supported on static fields: private static final java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractEventTriggerMap
00:05:23.067 INFO  [main] [API](ZksnarkInitService.java:26) init zk param begin
00:05:23.067 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:591) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zksnarkInitService': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [java.lang.LinkageError: Unable to load library zksnarkjni]
00:05:23.082 INFO  [main] [common-executor](ExecutorServiceManager.java:64) Pool query-section shutdown...
00:05:23.082 INFO  [main] [common-executor](ExecutorServiceManager.java:81) Pool query-section shutdown done
00:05:23.082 INFO  [main] [common-executor](ExecutorServiceManager.java:64) Pool valid-header-pbft-sign shutdown...
00:05:23.082 INFO  [main] [common-executor](ExecutorServiceManager.java:81) Pool valid-header-pbft-sign shutdown done
00:05:23.082 INFO  [main] [backup](BackupServer.java:96) Closing backup server...
00:05:23.082 INFO  [main] [common-executor](ExecutorServiceManager.java:64) Pool backup-manager shutdown...
00:05:23.082 INFO  [main] [common-executor](ExecutorServiceManager.java:81) Pool backup-manager shutdown done
00:05:23.082 INFO  [main] [backup](BackupServer.java:107) Backup server closed.
00:05:23.082 INFO  [main] [DB](TronDatabase.java:97) ******** Begin to close RewardViStore. ********
00:05:23.082 INFO  [main] [DB](TronDatabase.java:103) ******** End to close RewardViStore. ********
00:05:23.082 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close TransactionCache. ********
00:05:23.098 INFO  [main] [DB](TxCacheDB.java:348) dump bloomFilters start.
00:05:23.098 INFO  [ForkJoinPool.commonPool-worker-57] [DB](TxCacheDB.java:367) dump bloomFilters[0] to file.
00:05:23.098 INFO  [ForkJoinPool.commonPool-worker-50] [DB](TxCacheDB.java:367) dump bloomFilters[1] to file.
00:05:23.770 INFO  [ForkJoinPool.commonPool-worker-50] [DB](TxCacheDB.java:381) dump bloomFilters[1] to file done,filter: 14205329, filter-fpp: 5.0040865787850045E-5, crc32c: 5d03bb02, cost 672 ms.
00:05:27.900 INFO  [ForkJoinPool.commonPool-worker-57] [DB](TxCacheDB.java:381) dump bloomFilters[0] to file done,filter: 0, filter-fpp: 0.0, crc32c: 1d72ffc0, cost 4802 ms.
00:05:27.900 INFO  [ForkJoinPool.commonPool-worker-57] [DB](TxCacheDB.java:425) filterStartBlock: -1, currentBlockNum: 64287648, currentFilterIndex: 0, write done.
00:05:27.900 INFO  [ForkJoinPool.commonPool-worker-57] [DB](TxCacheDB.java:356) dump bloomFilters done.
00:05:27.900 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close TransactionCache. ********
00:05:27.900 INFO  [main] [common-executor](ExecutorServiceManager.java:64) Pool pbft-msg-manager shutdown...
00:05:27.900 INFO  [main] [common-executor](ExecutorServiceManager.java:81) Pool pbft-msg-manager shutdown done
00:05:27.900 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close SectionBloomStore. ********
00:05:27.900 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close SectionBloomStore. ********
00:05:27.900 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close TreeBlockIndexStore. ********
00:05:27.915 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close TreeBlockIndexStore. ********
00:05:27.915 INFO  [main] [DB](TronDatabase.java:97) ******** Begin to close PbftSignDataStore. ********
00:05:27.915 INFO  [main] [DB](TronDatabase.java:103) ******** End to close PbftSignDataStore. ********
00:05:27.915 INFO  [main] [DB](TronDatabase.java:97) ******** Begin to close CommonDataBase. ********
00:05:27.915 INFO  [main] [DB](TronDatabase.java:103) ******** End to close CommonDataBase. ********
00:05:27.915 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close TransactionHistoryStore. ********
00:05:27.915 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close TransactionHistoryStore. ********
00:05:27.915 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close RecentTransactionStore. ********
00:05:27.931 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close RecentTransactionStore. ********
00:05:27.931 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close RecentBlockStore. ********
00:05:27.931 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close RecentBlockStore. ********
00:05:27.931 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close TransactionRetStore. ********
00:05:27.962 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close TransactionRetStore. ********
00:05:27.962 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close TransactionStore. ********
00:05:28.009 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close TransactionStore. ********
00:05:28.009 INFO  [main] [DB](TronDatabase.java:97) ******** Begin to close CommonStore. ********
00:05:28.009 INFO  [main] [DB](TronDatabase.java:103) ******** End to close CommonStore. ********
00:05:28.009 INFO  [main] [DB](TronDatabase.java:97) ******** Begin to close KhaosDatabase. ********
00:05:28.009 INFO  [main] [DB](TronDatabase.java:103) ******** End to close KhaosDatabase. ********
00:05:28.009 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close DelegationStore. ********
00:05:28.009 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close DelegationStore. ********
00:05:28.009 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close IncrementalMerkleTreeStore. ********
00:05:28.009 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close IncrementalMerkleTreeStore. ********
00:05:28.009 INFO  [main] [DB](TronDatabase.java:97) ******** Begin to close ZKProofStore. ********
00:05:28.009 INFO  [main] [DB](TronDatabase.java:103) ******** End to close ZKProofStore. ********
00:05:28.009 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close NullifierStore. ********
00:05:28.009 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close NullifierStore. ********
00:05:28.009 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close StorageRowStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close StorageRowStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close DelegatedResourceAccountIndexStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close DelegatedResourceAccountIndexStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close DelegatedResourceStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close DelegatedResourceStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close ContractStateStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close ContractStateStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close ContractStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close ContractStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close CodeStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close CodeStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close AbiStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close AbiStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close MarketPairToPriceStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close MarketPairToPriceStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close MarketPairPriceToOrderStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close MarketPairPriceToOrderStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close MarketOrderStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close MarketOrderStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close MarketAccountStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close MarketAccountStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close ExchangeV2Store. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close ExchangeV2Store. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close ExchangeStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close ExchangeStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close ProposalStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close ProposalStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close VotesStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close VotesStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close WitnessScheduleStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close WitnessScheduleStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close AccountIndexStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close AccountIndexStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close AccountIdIndexStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close AccountIdIndexStore. ********
00:05:28.025 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close BlockIndexStore. ********
00:05:28.040 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close BlockIndexStore. ********
00:05:28.040 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close AssetIssueV2Store. ********
00:05:28.040 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close AssetIssueV2Store. ********
00:05:28.040 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close AssetIssueStore. ********
00:05:28.040 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close AssetIssueStore. ********
00:05:28.040 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close WitnessStore. ********
00:05:28.040 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close WitnessStore. ********
00:05:28.040 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close BlockStore. ********
00:05:28.071 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close BlockStore. ********
00:05:28.071 INFO  [main] [DB](TronDatabase.java:97) ******** Begin to close AccountAssetStore. ********
00:05:28.071 INFO  [main] [DB](TronDatabase.java:103) ******** End to close AccountAssetStore. ********
00:05:28.071 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close AccountStore. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close AccountStore. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close DynamicPropertiesStore. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close DynamicPropertiesStore. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close AccountTraceStore. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close AccountTraceStore. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close BalanceTraceStore. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close BalanceTraceStore. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:185) ******** Begin to close AccountStateStoreTrie. ********
00:05:28.087 INFO  [main] [DB](TronStoreWithRevoking.java:191) ******** End to close AccountStateStoreTrie. ********
00:05:28.087 INFO  [main] [DB](TronDatabase.java:97) ******** Begin to close CheckTmpStore. ********
00:05:28.087 INFO  [main] [DB](TronDatabase.java:103) ******** End to close CheckTmpStore. ********
00:05:28.087 ERROR [main] [app](DefaultConfig.java:40) Uncaught exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zksnarkInitService': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [java.lang.LinkageError: Unable to load library zksnarkjni]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.tron.program.FullNode.main(FullNode.java:80)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [java.lang.LinkageError: Unable to load library zksnarkjni]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:237)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:189)
	at org.tron.common.zksnark.LibrustzcashWrapper.<clinit>(LibrustzcashWrapper.java:22)
	at org.tron.common.zksnark.JLibrustzcash.isOpenZen(JLibrustzcash.java:316)
	at org.tron.core.zen.ZksnarkInitService.librustzcashInitZksnarkParams(ZksnarkInitService.java:28)
	at org.tron.core.zen.ZksnarkInitService.init(ZksnarkInitService.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 12 common frames omitted
	Suppressed: java.lang.LinkageError: Unable to load library zksnarkjni
		at org.fusesource.hawtjni.runtime.Library.loadLibrary(Library.java:543)
		at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:221)
		... 24 common frames omitted
	Caused by: java.lang.UnsatisfiedLinkError: no zksnarkjni in java.library.path
		at java.lang.ClassLoader.loadLibrary(Unknown Source)
		at java.lang.Runtime.loadLibrary0(Unknown Source)
		at java.lang.System.loadLibrary(Unknown Source)
		at org.fusesource.hawtjni.runtime.Library.loadLibrary(Library.java:539)
		... 25 common frames omitted
start with:
java -d64 -jar FullNode.jar -c main_net_config.conf

**Comment by jcube2024** [comment]
Any body can help me? 
PS D:\downloads> java -version
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)
error R6025

**Comment by lxcmyf** [comment]
@jcube2024 
Unfortunately, Java-tron node do not yet support running under Windows.

**Comment by vivian1912** [comment]
@jcube2024 Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.

**Comment by sfhacker** [comment]
Alo.
We haven’t faced any issues running Tron nodes on Windows (so far)!

We are more than welcome to assist you.
