### ISSUE TITLE
Why not increase TotalEnergyLimit?

### ISSUE THREAD

**Issue by buffuwei** [tronprotocol/java-tron#5966]
In light of Justin's recent near-insane energy staking behavior, which has seriously shadowed the original energy rental ecosystem on TRON.
We propose to add `TotalEnergyLimit` to meet the increasing energy demand.

**Comment by abn2357** [comment]
@buffuwei After reading what you said, It seems adding TotalEnergyLimit can't  solve your concerns.

**Comment by hitlxy** [comment]
@buffuwei The energy obtained by staking can make the transaction completely free, so many users stake TRX to obtain energy or rent energy. However, the total energy provided by TRON “TotalEnergyLimit”is limited. The less the amount of stake in the entire network, the more energy can be obtained per unit staked, which means that energy is cheaper. The more the amount of stake in the entire network, the less energy can be obtained per unit staked, which means that energy is relatively more expensive, but in this situation, using the energy obtained by staking can still reduce a lot of transaction fees.

The increase in the amount of staked will not affect the energy leasing ecosystem, but will only make the TRON network more reliable. With the increase in the amount of staked, the energy received by all stakers per unit staked will decrease, and the market price may also increase accordingly, but this is determined by the market.

**Comment by 0xbigapple** [comment]
I think lowering energy price is better.

**Comment by 0xbigapple** [comment]
they already have  tips [here](https://github.com/tronprotocol/tips/issues/667)

**Comment by buffuwei** [comment]
It seems that any idea put forward by community members who are not part of the TRON team, you guys are the first to object to it, rather than seriously consider it.

Unfortunately, this time your boss Justin seem to agree with us.
