### ISSUE TITLE
Check whether past transactions were successful

### ISSUE THREAD

**Issue by bbaktaeho** [tronprotocol/java-tron#5970]
Hello.
I have a question about the transaction.
When I requested the API for the transaction in the past, I couldn't know if it was successful.
However, the scan confirmed it as a success.

How can I determine the success of the transaction?

I've decided on `contactRet`.

### trnasction

5281eb99b3cab6b3cb4777e6b070df936f2cb068163fb8f3959a1cd88733a4c2

### response

```json
{
  "signature": [
    "d9e9abac1f4fbd560da9499b8bca17fddb86be9d82cb1dd7840e4ad1f59ff17838b4fb82d0edacfb88e5883c0f89a529305a5b5c430ebc3b1bbb6c78a6f6eaa101"
  ],
  "txID": "5281eb99b3cab6b3cb4777e6b070df936f2cb068163fb8f3959a1cd88733a4c2",
  "raw_data": {
    "contract": [
      {
        "parameter": {
          "value": {
            "amount": 33251807524000000,
            "owner_address": "4171b0af54e0a1182a5e0947d6a64f3b22740ef318",
            "to_address": "41b87f2be4dede9fc25387f8df7e0944b5cb7900e1"
          },
          "type_url": "type.googleapis.com/protocol.TransferContract"
        },
        "type": "TransferContract"
      }
    ],
    "ref_block_bytes": "0145",
    "ref_block_hash": "499a95010de906a4",
    "expiration": 1529892573000,
    "timestamp": 1529892550266
  },
  "raw_data_hex": "0a0201452208499a95010de906a440c89ed0a5c32c5a6c080112680a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412370a154171b0af54e0a1182a5e0947d6a64f3b22740ef318121541b87f2be4dede9fc25387f8df7e0944b5cb7900e11880a2eefcfbca883b70faeccea5c32c"
}
```

**Comment by lxcmyf** [comment]
@bbaktaeho 
The `contractRet` field is used to identify whether the contract transaction is successful, as the execution result of the contract is unpredictable, and non contract transactions are considered successful when they are put on the chain.

**Comment by lxcmyf** [comment]
@bbaktaeho 
Yes, that's true for transactions from a long time ago. ContractRet is a field added later, which can identify not only the results of contract transactions but also the results of non contract transactions.

**Comment by bbaktaeho** [comment]
@lxcmyf Thanks so much.
close this issue.

**Comment by abn2357** [comment]
> @bbaktaeho The `contractRet` field is used to identify whether the contract transaction is successful, as the execution result of the contract is unpredictable, and non contract transactions are considered successful when they are put on the chain.

If there are internal transactions, whether 'contractRet' field conclude information of each internal transaction?

**Comment by sYNCHROtime** [comment]
> contractRet

How does contractRet identify the results of non contract transactions?

**Comment by leo-lambda256** [comment]
@sYNCHROtime 
what is non contract transactions?
I understand that all Tron transactions operate through system contracts(contract). Even in case of TRX, TRC-10 transfer etc.
