### ISSUE TITLE
Two testnet nodes stopped syncing at block 49607871

### ISSUE THREAD

**Issue by plansten** [tronprotocol/java-tron#5971]
Two testnet nodes simultaneously stopped syncing at block 49607871
Version: GreatVoyage-v4.7.5

**Comment by CarlChaoCarl** [comment]
@plansten 

Hi, could you provide a detailed log?

**Comment by endiaoekoe** [comment]
@plansten 
Make sure the proposal configuration is consistent with the nile testnet template:
```
block = {
  needSyncCheck = false
  maintenanceTimeInterval = 600000
  proposalExpireTime = 600000 //
}
```
Make sure to use the latest nile branch to run the program: https://nileex.io/

In addition, considering that the database may be dirty, you can use a new snapshot to start the node, which can be downloaded from here: https://nile-snapshots.s3-accelerate.amazonaws.com/backup20240616/FullNode_output-directory.tgz

**Comment by GuipaiQigong111** [comment]
1

**Comment by plansten** [comment]
Starting nodes from the fresh snapshot helped me. Thanks!
