### ISSUE TITLE
Does Tron network save discovered nodes locally for a long time?

### ISSUE THREAD

**Issue by TayC710** [tronprotocol/java-tron#5972]
I want to know if the tron network has a mechanism for storing nodes discovered during the node discovery process for a long time, just like Bitcoin, where these discovered nodes are saved locally. Even if the Bitcoin network restarts, these discovered nodes will not disappear.

**Comment by endiaoekoe** [comment]
> I want to know if the tron network has a mechanism for storing nodes discovered during the node discovery process for a long time, just like Bitcoin, where these discovered nodes are saved locally. Even if the Bitcoin network restarts, these discovered nodes will not disappear.

@TayC710 
per my understanding to java-tron node discovery mechanism. except for the seed nodes confined in the config file . the node-find mechanism will keep trying to connect to new peers in order to maintain enough connections. The results of node discovery will be stored temporarily for establishing new connections.
which means the nodes found through the node discovery mechanism will be dynamically stored tempporarily and will not be permanently stored.

**Comment by 11111961abc** [comment]
Нет не исчезнут

пн, 26 авг. 2024 г., 08:20 TayC710 ***@***.***>:

**Comment by abn2357** [comment]
> > I want to know if the tron network has a mechanism for storing nodes discovered during the node discovery process for a long time, just like Bitcoin, where these discovered nodes are saved locally. Even if the Bitcoin network restarts, these discovered nodes will not disappear.
> 
> @TayC710 per my understanding to java-tron node discovery mechanism. except for the seed nodes confined in the config file . the node-find mechanism will keep trying to connect to new peers in order to maintain enough connections. The results of node discovery will be stored temporarily for establishing new connections. which means the nodes found through the node discovery mechanism will be dynamically stored tempporarily and will not be permanently stored.

@endiaoekoe How many seed nodes do Java Tron have now?

**Comment by endiaoekoe** [comment]
> How many seed nodes do Java Tron have now?

hi, @TayC710 
you can find the current seeds nodes confined in java-tron  in [main_net_config](https://github.com/tronprotocol/tron-deployment/blob/14699a3d5348efdd84a54da023b955f163b2483d/main_net_config.conf#L410) .
and for more details descriptions,check it [here](https://developers.tron.network/docs/networks#public-node)

**Comment by abn2357** [comment]
> > How many seed nodes do Java Tron have now?
> 
> hi, @TayC710 you can find the current seeds nodes configed in java-tron in [main_net_config](https://github.com/tronprotocol/tron-deployment/blob/14699a3d5348efdd84a54da023b955f163b2483d/main_net_config.conf#L410) . and for more details descriptions,check it [here](https://developers.tron.network/docs/networks#public-node)

@endiaoekoe  In the ref doc, seed node means stable online mainnet full node, So what is the definition of stable?

**Comment by endiaoekoe** [comment]
> So what is the definition of stable?

in my opinion, "stable node " means it's available 24/7  and you can rely on it and communicate with it as much as possible (synchronize blocks/transactions, etc.)

**Comment by abn2357** [comment]
> > So what is the definition of stable?
> 
> in my opinion, "stable node " means it's available 24/7 and you can rely on it and communicate with it as much as possible (synchronize blocks/transactions, etc.)

what is the minimum number of seed modes does Tron need?

**Comment by endiaoekoe** [comment]
> what is the minimum number of seed modes does Tron need?

I think there are no limits for seed nodes amount;
but it is recommended to config multiple seed nodes to accelerate the node discovery process;
on the other hand,insufficient number of seed nodes may result in slower node discovery or even failure to connect to the network.

**Comment by vivian1912** [comment]
@TayC710 May I ask if the above answer your question? This issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
