### ISSUE TITLE
Are there any restrictions on public nodes?

### ISSUE THREAD

**Issue by junghyun0783** [tronprotocol/java-tron#5973]
Hello.
I am currently using the "https://api.nileex.io/" public node provided by tron.
Is there a limit for public nodes?
I wonder if there is a limit on the number of speed requests.

Please answer, experts.

**Comment by endiaoekoe** [comment]
> Hello. I am currently using the "https://api.nileex.io/" public node provided by tron. Is there a limit for public nodes? I wonder if there is a limit on the number of speed requests.
> 
> Please answer, experts.

@junghyun0783 
I used  Nile API service several months ago, I remembered that there is a rate limit for usage of endpoint "https://api.nileex.io/", which is **20 requests per second**.

**Comment by junghyun0783** [comment]
@endiaoekoe 
Thank you for your kind reply. It helped me a lot.

**Comment by S1ep** [comment]
> > Hello. I am currently using the "https://api.nileex.io/" public node provided by tron. Is there a limit for public nodes? I wonder if there is a limit on the number of speed requests.
> > Please answer, experts.
> 
> @junghyun0783 I used Nile API service several months ago, I remembered that there is a rate limit for usage of endpoint "https://api.nileex.io/", which is **20 requests per second**.

What about the limit rate of mainnet?

**Comment by laurenceja** [comment]
> What about the limit rate of mainnet?

The rate limit of trongird:  https://developers.tron.network/reference/rate-limits
