### ISSUE TITLE
listexchanges api return body  first_token_id, second_token_id not match trc10 token id

### ISSUE THREAD

**Issue by 0xbigapple** [tronprotocol/java-tron#5974]
1.  query https://api.trongrid.io/wallet/listexchanges, I got 
<img width="627" alt="image" src="https://github.com/user-attachments/assets/cab5cfda-c949-4f12-867c-c076c7d41f52">

2. query getassetissuebyid by first_token_id, but return null.
<img width="877" alt="image" src="https://github.com/user-attachments/assets/aa1b7404-7e81-4fa7-9439-ed577b5998d4">

**Comment by endiaoekoe** [comment]
@0xbigapple 
try 'getassetissuebyname' instead of getassetissuebyid ,here is  the scrips:
```
curl -i -X POST \
   -H "Content-Type:application/json" \
   -d \
'{
  "value": "31303030343038"
}' \
 'https://api.trongrid.io/wallet/getassetissuebyname'
```

**Comment by 0xbigapple** [comment]
> @0xbigapple try 'getassetissuebyname' instead of getassetissuebyid ,here is the scrips:
> 
> ```
> curl -i -X POST \
>    -H "Content-Type:application/json" \
>    -d \
> '{
>   "value": "31303035303338"
> }' \
>  'https://api.trongrid.io/wallet/getassetissuebyname'
> ```

"31303035303338" is hexstring,  when I add 'visible=true' param, It  works.

https://api.trongrid.io/wallet/listexchanges?visible=true

<img width="566" alt="image" src="https://github.com/user-attachments/assets/1fbea69c-8f58-466a-be2d-a8f1221e72dd">
 
thanks!
