### ISSUE TITLE
Questions about the name of TRC-10

### ISSUE THREAD

**Issue by bbaktaeho** [tronprotocol/java-tron#5975]
Hello, I have a question.
`0a089a927329cdafce0318763153089d8833eb31f7f8c75f33ab4a074574ee1` transaction is TransferAssetContact Type.

```json
{
  "signature": [
    "b0a7f6f652082130d1c2f8ae6fab757af5b0e08f01365921bfe9c16f6cc5d9105110712ea08d5ad4bb83fcc75e6acfb4e81000180312f6e7efa3ea689c9131cc01"
  ],
  "txID": "0a089a927329cdafce0318763153089d8833eb31f7f8c75f33ab4aa074574ee1",
  "raw_data": {
    "contract": [
      {
        "parameter": {
          "value": {
            "amount": 100,
            "asset_name": "426974636f696e",
            "owner_address": "41d1fa093149cfb9a13c33fb484506a6e20821cabc",
            "to_address": "414068acae124b943b49a53a803227bdec78019e6e"
          },
          "type_url": "type.googleapis.com/protocol.TransferAssetContract"
        },
        "type": "TransferAssetContract"
      }
    ],
    "ref_block_bytes": "15ce",
    "ref_block_hash": "1f5b73d304a720bc",
    "expiration": 1529908590000,
    "timestamp": 1529908289136000000
  },
  "raw_data_hex": "0a0215ce22081f5b73d304a720bc40b0eba1adc32c5a730802126f0a32747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e736665724173736574436f6e747261637412390a07426974636f696e121541d1fa093149cfb9a13c33fb484506a6e20821cabc1a15414068acae124b943b49a53a803227bdec78019e6e20647080f88187bbefd49d15"
}
```

This transaction is before the TIP-10 proposal is reflected and the id value cannot be verified.
Also, the TRC-10 cannot be specified with duplicate name.

```json
{
  "assetIssue": [
    {
      "owner_address": "41d1fa093149cfb9a13c33fb484506a6e20821cabc",
      "name": "426974636f696e",
      "abbr": "425443",
      "total_supply": 21000000,
      "trx_num": 1000000,
      "num": 1,
      "start_time": 1529991531000,
      "end_time": 1561441020000,
      "description": "426974636f696e20697320616e20696e6e6f766174697665207061796d656e74206e6574776f726b20616e642061206e6577206b696e64206f66206d6f6e65792e",
      "url": "687474703a2f2f626974636f696e",
      "id": "1000004"
    },
    {
      "owner_address": "410f6d26e25b0e55d37161989a1319c60df4bd0687",
      "name": "426974636f696e",
      "abbr": "425443",
      "total_supply": 21000000000000,
      "frozen_supply": [
        {
          "frozen_amount": 20000000000000,
          "frozen_days": 30
        }
      ],
      "trx_num": 1000000,
      "precision": 6,
      "num": 1000000,
      "start_time": 1553184000000,
      "end_time": 1561132800000,
      "description": "5472756520426974636f696e",
      "url": "68747470733a2f2f626974636f696e2e6f7267",
      "id": "1002211"
    },
    {
      "owner_address": "414f10065476e61054dad85d1c9a32cf429a6bc8cd",
      "name": "426974636f696e",
      "abbr": "425457",
      "total_supply": 2.1e+18,
      "trx_num": 888000000,
      "precision": 4,
      "num": 247980000,
      "start_time": 1609023600000,
      "end_time": 1609110000000,
      "description": "426974636f696e20546f6b656e2073657320706565722d746f2d7065657220746563686e6f6c6f677920746f206f7065726174652077697468206e6f2063656e7472616c20617574686f72697479206f722062616e6b733b206d616e6167696e67207472616e73616374696f6e7320616e64207468652069737375696e67206f6620626974636f696e732069732063617272696564206f757420636f6c6c6563746976656c7920627920746865206e6574776f726b2e",
      "url": "68747470733a2f2f626974636f696e2e6f72672f",
      "id": "1003591"
    },
    {
      "owner_address": "414e96c78e43819373ddca58a3861ec29b6c190860",
      "name": "426974636f696e",
      "abbr": "424954434f494e",
      "total_supply": 25000000,
      "trx_num": 1000000,
      "precision": 1,
      "num": 10,
      "start_time": 1640732400000,
      "end_time": 1640818800000,
      "description": "426974636f696e207573657320706565722d746f2d7065657220746563686e6f6c6f677920746f206f7065726174652077697468206e6f2063656e7472616c20617574686f72697479206f722062616e6b733b206d616e6167696e67207472616e73616374696f6e7320616e64207468652069737375696e67206f6620626974636f696e732069732063617272696564206f757420636f6c6c6563746976656c7920627920746865206e6574776f726b2e20426974636f696e206973206f70656e2d736f75726365",
      "url": "68747470733a2f2f626974636f696e2e6f72672f",
      "id": "1004673"
    }
  ]
}
```

But I was able to check which TRC-10 it was in the tronscan. ([tronscan link](https://tronscan.org/#/transaction/0a089a927329cdafce0318763153089d8833eb31f7f8c75f33ab4aa074574ee1))

Is there a way to check like tronscan?

**Comment by endiaoekoe** [comment]
> ```json
>  "asset_name": "426974636f696e",
> ```

@bbaktaeho 
try 'getassetissuelistbyname' interface ,
below is the script to check asset '426974636f696e' you mentioned above:

`curl -i -X POST \
   -H "Content-Type:application/json" \
   -d \
'{
  "value": "426974636f696e"
}' \
 'https://api.trongrid.io/wallet/getassetissuelistbyname'`

**Comment by bbaktaeho** [comment]
@endiaoekoe 
There is response above. I wonder which token is on the list.

**Comment by endiaoekoe** [comment]
> I wonder which token is on the list.

filter with param 'owner_address',like below:
![image](https://github.com/user-attachments/assets/aaa4c3a8-b67d-4abf-b926-07cab503c5be)

**Comment by bbaktaeho** [comment]
@endiaoekoe 
Is there a way to find TRC-10 not only in `0a089a927329cdafce0318763153089d8833eb31f7f8c75f33ab4aa074574ee1` but also in TransferAssetContact transaction with that `asset_name`?

**Comment by endiaoekoe** [comment]
> @endiaoekoe Is there a way to find TRC-10 not only in `0a089a927329cdafce0318763153089d8833eb31f7f8c75f33ab4aa074574ee1` but also in TransferAssetContact transaction with that `asset_name`?

seems like you misunderstood my descriptions above.
you can use interface 'getassetissuelistbyname' to query all the TRC10 tokens(not only in the tx you mentioned but also every txs which contains trc10 token transfers) with the specific asset_name as input params;
I just give an example with the tx you provide, which does not mean it only fits in **the** tx you mentioned above.

**Comment by bbaktaeho** [comment]
@endiaoekoe 
Thank you for your answer.
If so, can I know which TRC-10 token was sent just by looking at the `3426db0be3d16fd1601b674e84c5ff31947aee0e2fbd99a830ff84298c3de564` transaction?

```json
{
  "signature": [
    "f6809912d9c15215f3112944d6e90a15be58dde48eff2887f229f2ac65d67de549d836e8e9762f70883958d2c138759e202d543fcde9ff9d5b8d5e6247b8732001"
  ],
  "txID": "3426db0be3d16fd1601b674e84c5ff31947aee0e2fbd99a830ff84298c3de564",
  "raw_data": {
    "contract": [
      {
        "parameter": {
          "value": {
            "amount": 1,
            "asset_name": "426974636f696e",
            "owner_address": "4102f8f200d422276f1d13b7bc6e7f879ed878e6fd",
            "to_address": "41195db8b3c0b1f012d5c52af38c6846355f21f87f"
          },
          "type_url": "type.googleapis.com/protocol.TransferAssetContract"
        },
        "type": "TransferAssetContract"
      }
    ],
    "ref_block_bytes": "8b52",
    "ref_block_hash": "2dbca869a78e9721",
    "expiration": 1535515809000,
    "timestamp": 1535515750703
  },
  "raw_data_hex": "0a028b5222082dbca869a78e972140e8a9ff9ed82c5a730802126f0a32747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e736665724173736574436f6e747261637412390a07426974636f696e12154102f8f200d422276f1d13b7bc6e7f879ed878e6fd1a1541195db8b3c0b1f012d5c52af38c6846355f21f87f200170afe2fb9ed82c"
}
```

**Comment by endiaoekoe** [comment]
> If so, can I know which TRC-10 token was sent just by looking at the `3426db0be3d16fd1601b674e84c5ff31947aee0e2fbd99a830ff84298c3de564` transaction?

i just query the trc10 tokens owned by account ’4102f8f200d422276f1d13b7bc6e7f879ed878e6fd‘ by interface getassetissuebyaccount，the response is null;which means account '4102f8f200d422276f1d13b7bc6e7f879ed878e6fd' does not own any trc10 token;
but the response you paste show account ’4102f8f200d422276f1d13b7bc6e7f879ed878e6fd‘ own asset '426974636f696e'.
the two results  conflicts;
per my understanding ,there may be some dirty data;I think the main reason is that the tx you mentioned above is too old(in 2018).
hope it helps;

**Comment by bbaktaeho** [comment]
@endiaoekoe 
Thank you for your help. I will refer to it.

**Comment by bbaktaeho** [comment]
I think solve the problem in the following way.

---

Prerequisite: TransferAssetContact that occurred before block 5537806 has duplicate asset_name,
```Go
// 1. getaasetissuelistbyname
assetList = getaasetissuelistbyname

// 2. filtering
for asset <- assetList {
   if asset.id < 1001872 { // TRC-10s smaller than this ID value do not have duplicate names.
      // This token!
   }
}
```

**Comment by vivian1912** [comment]
@bbaktaeho Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.
