### ISSUE TITLE
names of protocol fields have spelling errors

### ISSUE THREAD

**Issue by paulvi** [tronprotocol/java-tron#598]
names of protocol fields have spelling errors

while #597 has some fixes for comments, changing spelling error within fields can be breaking of protocol compatibility (needs to be checked within gRPC docs)

in `/java-tron/src/main/protos/core/Tron.proto`

![image](https://user-images.githubusercontent.com/1614482/39557467-77e5e1d2-4eba-11e8-8c31-9bb082136922.png)

**Comment by zhaohong** [comment]
thanks , this is reserved message,  I'll fix later.
