### ISSUE TITLE
Node Setup. Node listener via WebSocket.

### ISSUE THREAD

**Issue by Osiris8888** [tronprotocol/java-tron#5985]
I would like to run a full node on my computer to help improve TRON network and gain invaluable experience.

Questions:  

1. I need 2.5 TB of memory to run node, but do I need to have one NVMe SSD ( 4tb ) or can I run it on two memory sticks (2tb + 2 tb)?

2. Question regarding GetTransactionFromPending endpoint. Will I get information about all recent transactions with pending status in the response? 

3. Can I see memory pool related to specific token?

4. Can I enable webSocket so that my js\rust code triggers as soon as I receive a new transaction?

**Comment by xxo1shine** [comment]
@Osiris8888 
Question 2:
The interface `GetTransactionFromPending` requires a transaction ID parameter and only returns the transaction corresponding to the transaction ID, and does not return all transactions in the `Pending` queue.

**Comment by 317787106** [comment]
@Osiris8888 Related to websocket, you can see this issue: https://github.com/tronprotocol/java-tron/issues/5811

**Comment by Osiris8888** [comment]
> Referenc

You're right. I made a mistake in writing my question. I wanted to clarify about GetTransactionListFromPending. This is a regular get endpoint and I want to understand which transactions I will receive. All of them or certain ones according to node settings. If all, then there are hundreds, maybe thousands of them every second, is there any way to filter them? So that there are transactions related to a certain coin, as an example.

**Comment by Osiris8888** [comment]
> @Osiris8888 Question 2: The interface `GetTransactionFromPending` requires a transaction ID parameter and only returns the transaction corresponding to the transaction ID, and does not return all transactions in the `Pending` queue.

@xxo1shine You're right. I made a mistake in writing my question. I wanted to clarify about GetTransactionListFromPending. This is a regular get endpoint and I want to understand which transactions I will receive. All of them or certain ones according to node settings. If all, then there are hundreds, maybe thousands of them every second, is there any way to filter them? So that there are transactions related to a certain coin, as an example.

**Comment by Osiris8888** [comment]
> > 1. I need 2.5 TB of memory to run node, but do I need to have one NVMe SSD ( 4tb ) or can I run it on two memory sticks (2tb + 2 tb)?
> 
> Both are fine.
> 
> If you want to use two SSD hard disks, you need to understand the storage space currently occupied by different DBs of TRON, and configure the specified DB to the dest `path` in `storage.properties` of the `config.conf`. This may require you to be very familiar with the current status and growth of TRON DBs data volume.
> 
> For ease of use, a 4T SSD is recommended.

@tomatoishealthy 
Thanks for the quick reply.

**Comment by xxo1shine** [comment]
> > @Osiris8888 Question 2: The interface `GetTransactionFromPending` requires a transaction ID parameter and only returns the transaction corresponding to the transaction ID, and does not return all transactions in the `Pending` queue.
> 
> @xxo1shine You're right. I made a mistake in writing my question. I wanted to clarify about GetTransactionListFromPending. This is a regular get endpoint and I want to understand which transactions I will receive. All of them or certain ones according to node settings. If all, then there are hundreds, maybe thousands of them every second, is there any way to filter them? So that there are transactions related to a certain coin, as an example.

All transactions. Currently, the interface does not provide filtering parameters.

**Comment by vivian1912** [comment]
@Osiris8888 May I ask if the above answer your question?  If yes, this issue will be closed later and please feel free to re-open it if you still see the issue, thanks.

**Comment by BeycanDeveloper** [comment]
We realized that this was a big gap in the Tron Blockchain network without WebSockets, so we built [TronSocket.com](https://tronsocket.com). Now it's easy to listen to Tron Blockchain events via WebSocket.
