### ISSUE TITLE
p2p connection does not work.

### ISSUE THREAD

**Issue by junghyun0783** [tronprotocol/java-tron#6000]
Synchronization stopped 2 days ago.
p2p connections keep failing.
The reason is TIME_OUT. 
It is currently stopped at block 50104160.
What is the reason why synchronization goes well and then does not work?

We desperately need help from experts. thank you
![61](https://github.com/user-attachments/assets/cef48edb-7d28-4c83-89be-79a619b59e6a)

**Comment by fyyhtx** [comment]
@junghyun0783 The screenshot of the log you provided is not enough for us to help you diagnose the cause of the problem you encountered. Please provide the logs at least one hour before and after the block height stopped growing, as this will help us identify the cause of the problem you are facing. Additionally, please confirm the following points: whether you did any operations on your node before the issue occurred, such as a restart; if there are any abnormalities in the network environment where the node is located; if you have made any changes to the code the node is running; and whether the node is running on the main network or the Nile test network.

**Comment by junghyun0783** [comment]
@fyyhtx 
![62](https://github.com/user-attachments/assets/b295fb13-a390-4fa7-8ab0-add4c2366903)
[tron-2024-09-10.0.log.gz](https://github.com/user-attachments/files/16987136/tron-2024-09-10.0.log.gz)

There were no changes before the issue occurred. The node was working fine,
and the node is currently running via docker ("tronprotocol/java-tron").
There were no changes to the code while it was running.
The node is on the Nile test network.
The PC that currently runs the node is running the TRX testnet along with the ETH mainnet and BTC testnet.
The PC specifications are i5 10th generation. The memory is 128G, and the hard drive is (SSD 2TB + HDD 8TB) in RAID 0.

What could be the issue? Thank you for your reply.

**Comment by fyyhtx** [comment]
@junghyun0783 It is obvious that your node failed to process block 50104161, and the most likely reason is that your node's database is corrupted. The quickest recovery method is to download the latest data snapshot and restart the node. Download link: https://nileex.io/join/getJoinPage. Also, please confirm where the original database was downloaded from. If possible, please provide the node's configuration file so we can analyze the reason for data corruption.

**Comment by junghyun0783** [comment]
@fyyhtx 
Here is the config file.
But this situation happened more than once or twice.
Every time, I received a block snapshot and it worked... I want to know why it does this.

I provide the config file below.
[test_net_config.zip](https://github.com/user-attachments/files/16987914/test_net_config.zip)
thank you!

**Comment by fyyhtx** [comment]
@junghyun0783 Your goal is to run the node of the Nile test network. Please obtain the node jar package, database snapshot and recommended configuration file you need from https://nileex.io/. Comparing the configuration file you used with the recommended configuration file, the difference is very big, I think this is the root cause of the problem.

**Comment by abn2357** [comment]
> @junghyun0783 It is obvious that your node failed to process block 50104161, and the most likely reason is that your node's database is corrupted. The quickest recovery method is to download the latest data snapshot and restart the node. Download link: https://nileex.io/join/getJoinPage. Also, please confirm where the original database was downloaded from. If possible, please provide the node's configuration file so we can analyze the reason for data corruption.

Is there any other common reason that could cause failing to process block except network interruption?

**Comment by abn2357** [comment]
> > > @junghyun0783 It is obvious that your node failed to process block 50104161, and the most likely reason is that your node's database is corrupted. The quickest recovery method is to download the latest data snapshot and restart the node. Download link: https://nileex.io/join/getJoinPage. Also, please confirm where the original database was downloaded from. If possible, please provide the node's configuration file so we can analyze the reason for data corruption.
> > 
> > 
> > Is there any other common reason that could cause failing to process block except network interruption?
> 
> I don't understand why you are asking this, the issue being discussed is not caused by network interruption resulting in block processing failure, but by block processing failure causing all peers to disconnect. The root cause of the issue has been identified, please refer to: [#6000 (comment)](https://github.com/tronprotocol/java-tron/issues/6000#issuecomment-2348149321)

what I actualy  wanna know is that is there any other common reason that could cause failing to process block except database corruption and network interruption. Network interruption is the most common but insignificant reason, that is why 
 I rule out it in my question.

**Comment by xxo1shine** [comment]
@abn2357 The network will not cause damage to the database, and normal exit will not cause damage to the database. Generally, only abnormal exit will cause damage, such as a sudden server crash.

**Comment by jwrct** [comment]
@junghyun0783 Have you solved the problem you encountered? Looking forward to your feedback.

**Comment by fyyhtx** [comment]
@junghyun0783 Have you solved the problem you encountered? Looking forward to your feedback.

**Comment by junghyun0783** [comment]
@jwrct @fyyhtx 
No..
I'm proceeding by receiving a new block snapshot.
But this keeps happening again and again.
I'm currently running with docker.
I'm using the docker image "tronprotocol/java-tron".
Is it a config configuration file problem?

**Comment by fyyhtx** [comment]
> @junghyun0783 Your goal is to run the node of the Nile test network. Please obtain the node jar package, database snapshot and recommended configuration file you need from https://nileex.io/. Comparing the configuration file you used with the recommended configuration file, the difference is very big, I think this is the root cause of the problem.

@junghyun0783 Hope you have seen this reply.
