### ISSUE TITLE
Issue with ZeroMQ on Tron Fullnode – Not Receiving Messages

### ISSUE THREAD

**Issue by 273million** [tronprotocol/java-tron#6004]
I have a Tron full node and am trying to use ZeroMQ, but I never seem to get replies from the server. I’ve tried everything and seen similar issues posted, but couldn’t find a concrete solution, so I’m posting here for help.

Here the response for Node.js
**_Subscriber connected to port 5555_**

response for phyton:
**_Setting up ZeroMQ subscriber...
Connected to ZeroMQ server
Subscribed to 'block' messages_**

Here is my jdk version:
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (build 1.8.0_422-8u422-b05-1~20.04-b05)
OpenJDK 64-Bit Server VM (build 25.422-b05, mixed mode)

Here is my zeromq version:
:~/libzmq$ npm list zeromq
n_gunkewitsch@1.0.0 /home/n_gunkewitsch
└── zeromq@5.3.1

this is the main_net_config.conf:

```
event.subscribe = {
  native = {
    useNativeQueue = true // if true, use native message queue, else use event plugin.
    bindport = 5555 // bind port
    sendqueuelength = 1000 //max length of send queue
  }

  path = "" // absolute path of plugin
  server = "" // target server address to receive event triggers
  dbconfig = "" // dbname|username|password
  contractParse = true,
  topics = [
      {
        triggerName = "block" // block trigger, the value can't be modified
        enable = true
        topic = "block" // plugin topic, the value could be modified
        solidified = false // if set true, just need solidified block, default is false
      },
      {
        triggerName = "transaction"
        enable = true
        topic = "transaction"
        solidified = false
        ethCompatible = false // if set true, add transactionIndex, cumulativeEnergyUsed, preCumulativeLogCount, logList, energyUnitPrice, default is false
      },
      {
        triggerName = "contractevent"
        enable = true
        topic = "contractevent"
      },
      {
        triggerName = "contractlog"
        enable = true
        topic = "contractlog"
        redundancy = true // if set true, contractevent will also be regarded as contractlog
      },
      {
        triggerName = "solidity" // solidity block trigger(just include solidity block number and timestamp), the value can't be modified
        enable = true            // the default value is true
        topic = "solidity"
      },
      {
        triggerName = "solidityevent"
        enable = true
        topic = "solidityevent"
      },
      {
        triggerName = "soliditylog"
        enable = true
        topic = "soliditylog"
        redundancy = true // if set true, solidityevent will also be regarded as soliditylog
      }
  ]

  filter = {
    fromblock = "" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
    toblock = "" // the value could be "", "latest" or a specified block number as end of the queried range
    contractAddress = [
      "" // contract address you want to subscribe, if it's set to "", you will receive contract logs/events with any contract address.
    ]

    contractTopic = [
      "" // contract topic you want to subscribe, if it's set to "", you will receive contract logs/events with any contract topic.
    ]
  }
}
```
Here the subscribe.js
```
// subscriber.js
const zmq = require("zeromq");

const sock = zmq.socket("sub");


sock.connect("tcp://127.0.0.1:5555");
sock.subscribe("block");
console.log("Subscriber connected to port 5555");

sock.on("message", function(topic, message) {
  console.log(
    "received a message related to:",
    Buffer.from(topic).toString(),
    ", containing message:",
    Buffer.from(message).toString()
  );
});
```

I’ve verified that my firewall is configured for port 5555, but I still don’t seem to be receiving any messages from the server. Any guidance or suggestions would be much appreciated!

Thanks for your help!

**Comment by CarlChaoCarl** [comment]
@273million 

Hello,
First, please check the startup parameters of your node:
The event subscription service parameter in Tron is disabled by default. 
You need to enable it by adding the command line parameter --es.
The node startup command to enable the event subscription service is as follows:
`$ java -jar FullNode.jar --es`

Secondly, you can refer to the following documentation for further assistance:
[use-java-trons-built-in-message-queue-for-event-subscription](https://developers.tron.network/docs/use-java-trons-built-in-message-queue-for-event-subscription)

Lastly, if you have any further questions, feel free to leave a message.

**Comment by 273million** [comment]
Thank you mate, that fixed it!
