### ISSUE TITLE
How does grpc obtain the TRC20 Token transfer record of a certain address?

### ISSUE THREAD

**Issue by 19byte** [tronprotocol/java-tron#6005]
I am using go to develop a tron ​​application and need to obtain the transaction records of the trc20 contract token at a certain address. Are there any implementation cases or documents?

**Comment by ExOCeo** [comment]
You may find HTTP implementation for that (https://developers.tron.network/reference/get-trc20-transaction-info-by-account-address), no grpc interface.

**Comment by 19byte** [comment]
> 您可能会发现该 HTTP 实现（https://developers.tron.network/reference/get-trc20-transaction-info-by-account-address），没有 grpc 接口。

🙏

**Comment by CarlChaoCarl** [comment]
@19byte 
If the problem has been resolved, we will close the issue.
