### ISSUE TITLE
How to obtain the USDT exchange rate dynamically

### ISSUE THREAD

**Issue by CupidStar** [tronprotocol/java-tron#6008]
How to obtain the USDT exchange rate dynamically

**Comment by ExOCeo** [comment]
you meant real-time exchang rate of usdt to what?

**Comment by CupidStar** [comment]
Yes, I hope to obtain the real-time exchange rate at a fixed speed through http protocol or websocket protocol. Do you provide that? If so, could you please provide me with a copy of the instructions? Thank you very much

**Comment by ExOCeo** [comment]
> Yes, I hope to obtain the real-time exchange rate at a fixed speed through http protocol or websocket protocol. Do you provide that? If so, could you please provide me with a copy of the instructions? Thank you very much

There is no interface for obtaining token exchange rate, you might find that from other dApp or DEX, TRON has no such service.

**Comment by abn2357** [comment]
> > Yes, I hope to obtain the real-time exchange rate at a fixed speed through http protocol or websocket protocol. Do you provide that? If so, could you please provide me with a copy of the instructions? Thank you very much
> 
> There is no interface for obtaining token exchange rate, you might find that from other dApp or DEX, TRON has no such service.

Is there a way to get exchange rate of tokens on tron in my smart contract?

**Comment by endiaoekoe** [comment]
> Is there a way to get exchange rate of tokens on tron in my smart contract?

@abn2357 
maybe [winklink](https://doc.winklink.org/v1/doc/architecture.html#winklink-node-model)(oracle protocol in java-tron) can fulfill your requirement. In the arch of winklink , you can set your own contract as a consumer contract and get the required token pair prices through your contract.

**Comment by abn2357** [comment]
> > Is there a way to get exchange rate of tokens on tron in my smart contract?
> 
> @abn2357 maybe [winklink](https://doc.winklink.org/v1/doc/architecture.html#winklink-node-model)(oracle protocol in java-tron) can fulfill your requirement. In the arch of winklink , you can set your own contract as a consumer contract and get the required token pair prices through your contract.

Is Winklink developed by tron or by a third-party?
