### ISSUE TITLE
I want to trigger the Energy Rental of JustLend DAO through the contract

### ISSUE THREAD

**Issue by 19byte** [tronprotocol/java-tron#6013]
```

const (
	// rentResource(address receiver, uint256 amount, uint256 resourceType)
	methodRentResource = "fd8527a1"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	endpoint, err := tron.NewEndpoint()
	if err != nil {
		panic(err)
	}
	var data []byte
	methodId, _ := hexutil.Decode(methodRentResource)
	receive := internal.DecodeCheck("TDXhWtfwXqH6DadcrB5uucJ6HXtQQQQQQQ")
	amount := int64(2000000)
	paddedReceive := common.LeftPadBytes(receive[1:], 32)
	amountBig := new(big.Int).SetInt64(amount)
	paddedAmount := common.LeftPadBytes(amountBig.Bytes(), 32)
	resourceTypeBig := new(big.Int).SetInt64(int64(0))
	paddedResourceType := common.LeftPadBytes(resourceTypeBig.Bytes(), 32)
	data = append(data, methodId...)
	data = append(data, paddedReceive...)
	data = append(data, paddedAmount...)
	data = append(data, paddedResourceType...)
	fmt.Println(endpoint.TriggerSmartContract(ctx, "TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd", data, &tron.Wallet{
		Owner: "TDXhWtfwXqH6DadcrB5uucJ6HXtQQQQQQQ",
		Ctrl:  "xxxx",
	}))
}


func (e *Endpoint) TriggerSmartContract(ctx context.Context, contract string, data []byte, wallet *Wallet) (*api.TransactionExtention, error) {
	transferContract := new(core.TriggerSmartContract)
	transferContract.OwnerAddress = internal.DecodeCheck(wallet.Owner)
	transferContract.ContractAddress = internal.DecodeCheck(contract)
	transferContract.Data = data

	transferTransactionEx, err := e.wallet.TriggerConstantContract(ctx, transferContract)
	var txId string
	if err != nil {
		return nil, err
	}
	transferTransaction := transferTransactionEx.Transaction
	if transferTransaction == nil ||
		len(transferTransaction.GetRawData().GetContract()) == 0 {
		return nil, fmt.Errorf("transfer error: invalid transaction")
	}
	transferTransaction.RawData.FeeLimit = 50000000

	hash, err := SignTransaction(transferTransaction, wallet.Ctrl)
	if err != nil {
		return nil, err
	}
	txId = hexutil.Encode(hash)

	result, err := e.BroadcastTransaction(ctx, transferTransaction)
	if err != nil {
		return nil, err
	}
	if !result {
		return nil, fmt.Errorf("api get false the msg: %v", result)
	}
	fmt.Println(txId)
	return transferTransactionEx, err
}

failed hash：
3eaedea576dc2de6e96d61ff3169b48f45fa01e5d9903cd886ffb9951e649ee2
573a7be64223df383500574d731bc4e298d31faafb03ce19b5a7f04eeb66d7e5
553c1d8c89ad0853122a27153d045beb4213690bb0c086a21ac6ea47fcad542d
```
looking forward to your help. . .

**Comment by laurenceja** [comment]
@19byte You can get the detailed error information according to this [guide](https://developers.tron.network/docs/faq#4-how-to-troubleshoot-when-calling-the-contract-and-return-the-revert-error). Converting the error message from hex to string, then finding the string from the contract source code to get the reason.

**Comment by 19byte** [comment]
output : Contract result does not contain enough data.
I don’t know the reason. There are 3 parameters in total, including the receiving address, the number of leases, and the resource type. I have passed them all.

**Comment by 19byte** [comment]
return : rent is paused,what does this mean?

**Comment by endiaoekoe** [comment]
> resourceTypeBig := new(big.Int).SetInt64(int64(0))
hi,@19byte 
from your decsptions, you want to trigger energy rental through the contract;
but per my understanding , resourceType=0 means bandwidth，and resourceType=1 is energy;
could you check whether you want to rent energy or rent bandwidth？

**Comment by endiaoekoe** [comment]
> resourceTypeBig := new(big.Int).SetInt64(int64(0))

hi, @19byte 
i just check the [justlend dao contract](https://tronscan.io/#/contract/TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd/code) 
and found the bandwidth rent are paused,see below:
![image](https://github.com/user-attachments/assets/c69cc784-e3d3-4014-a4eb-5837383cd966)
and energy rental are ok
![image](https://github.com/user-attachments/assets/3911d6ef-987d-4075-b1fd-bdd56af983f5)
not sure if this can resolve your problem.

**Comment by 19byte** [comment]
@endiaoekoe Thank you for your reply. What I called was renting energy, and the return was still paused.

**Comment by endiaoekoe** [comment]
> resourceTypeBig := new(big.Int).SetInt64(int64(0))
> What I called was renting energy, and the return was still paused.
@19byte 
from the scripts you posted above, the resource type you set in this script is 0, which means bandwidth. and 1 means energy, to clarify.

**Comment by 19byte** [comment]
@endiaoekoe It's working fine now, but it tells me : Not enough security deposit
```
methodId, _ := hexutil.Decode("fd8527a1")
	receive := internal.DecodeCheck("T.....")
	paddedReceive := common.LeftPadBytes(receive[1:], 32)
	amountBig := new(big.Int).SetInt64(1000000)
	paddedAmount := common.LeftPadBytes(amountBig.Bytes(), 32)
	resourceTypeBig := new(big.Int).SetInt64(int64(1))
	paddedResourceType := common.LeftPadBytes(resourceTypeBig.Bytes(), 32)

	data = append(data, methodId...)
	data = append(data, paddedReceive...)
	data = append(data, paddedAmount...)
	data = append(data, paddedResourceType...)
```

**Comment by endiaoekoe** [comment]
> but it tells me : Not enough security deposit

@19byte 
it is not an error, but a normal business logic return message ; 
please check it [here ](https://docs.justlend.org/getting-started/faq/energy-rental-market#why-is-my-energy-rental-order-liquidated), which explain why your security deposit are not enough

**Comment by 19byte** [comment]
@endiaoekoe  another question, why doesn’t the api allow me to enter how long I need to rent? In justlend, you can choose the number of days to rent.

**Comment by 19byte** [comment]
my trans:
> https://tronscan.io/#/transaction/4471a4ca4afe2f36d22ac2440bf100c48f7cfe612425907db816147c2f033eb0
moreover, the on-chain browser doesn’t seem to recognize my parameters 😂

**Comment by endiaoekoe** [comment]
> why doesn’t the api allow me to enter how long I need to rent?

@19byte 
for this question, you can contact  Justlend dao community through its [public channels](https://justlend.org/),eg:telegram/discord/twitter ;where you can talk about the API design consideration you mentioned above.
hope it helps.

**Comment by 19byte** [comment]
@endiaoekoe  no one pays attention to me

**Comment by 11111961abc** [comment]
Ты кто я сергей

ср, 25 сент. 2024 г., 18:01 0xbigapple ***@***.***>:

**Comment by sniperyen** [comment]
@19byte  Have you solved your problem? I have the same problem.  It told me "resource rent: Not enough security deposit
"

Here is the transcation details:

`{'id': '2b078d677dc393da6da44992d1fb8fc1bd1e4a036cd2f0609bde581ecfe80fd1', 'blockNumber': 65592242, 'blockTimeStamp': 1727425080000, 'contractResult': ['08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002a7265736f757263652072656e743a204e6f7420656e6f756768207365637572697479206465706f73697400000000000000000000000000000000000000000000'], 'contract_address': 'TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd', 'receipt': {'energy_usage': 13867, 'origin_energy_usage': 18218, 'energy_usage_total': 32085, 'net_usage': 378, 'result': 'REVERT'}, 'result': 'FAILED', 'resMessage': 'REVERT opcode executed', 'internal_transactions': [{'hash': '669aaa8adc2e9825ec09e5ce5c46f35dc8a9ca1cf9ac3849825fb9ff2fac03b2', 'caller_address': 'TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd', 'transferTo_address': 'TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd', 'callValueInfo': [{}], 'note': '63616c6c', 'rejected': True}, {'hash': 'e4cba8fc04e5874f2708084482154fbcb43c5e62d63aebe05df8e0087b8c2bfe', 'caller_address': 'TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd', 'transferTo_address': 'TU3kjFuhtEo42tsCBtfYUAZxoqQ4yuSLQ5', 'callValueInfo': [{}], 'note': '63616c6c', 'rejected': True}, {'hash': '185c37517fe5fcfd5beda07128f0ae2c01367c756d030e75c881a0ee0f3cfc23', 'caller_address': 'TU3kjFuhtEo42tsCBtfYUAZxoqQ4yuSLQ5', 'transferTo_address': 'TU3kjFuhtEo42tsCBtfYUAZxoqQ4yuSLQ5', 'callValueInfo': [{}], 'note': '63616c6c', 'rejected': True}, {'hash': '070c74fe4d55c3d09a69b93f1d1178b4c56951d3908050ab51720641dc70fbd1', 'caller_address': 'TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd', 'transferTo_address': 'TXA2WjFc5f86deJcZZCdbdpkpUTKTA3VDM', 'callValueInfo': [{}], 'note': '63616c6c', 'rejected': True}, {'hash': '36a6008d9888fc6d7bd9acfb562e3379c972c1d3d3ac57bcbc58485d54ec117c', 'caller_address': 'TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd', 'transferTo_address': 'TXA2WjFc5f86deJcZZCdbdpkpUTKTA3VDM', 'callValueInfo': [{}], 'note': '63616c6c', 'rejected': True}]}`

And I compared the success case and failed case:

success:
<img width="948" alt="image" src="https://github.com/user-attachments/assets/9403895c-4182-458f-81ae-814729a55dca">

failed:
<img width="965" alt="image" src="https://github.com/user-attachments/assets/f4b78a57-2fdd-41f5-9c9e-a12059816411">

No data in the method. 

Do you have good idea to solve it ?

**Comment by 19byte** [comment]
@sniperyen no brother please help me if you solved it

**Comment by 19byte** [comment]
@sniperyen Did you solve it? Have a nice day

**Comment by 19byte** [comment]
The problem has been solved:

```

const (
	methodRentResource = "0xfd8527a1"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	endpoint, err := tron.NewEndpoint()
	if err != nil {
		panic(err)
	}

	var data []byte

	methodId, _ := hexutil.Decode(methodRentResource)
	receive := internal.DecodeCheck("Txxxx")
	paddedReceive := common.LeftPadBytes(receive[1:], 32)
	amountBig := new(big.Int).SetInt64(tron.ToSUN(1))
	paddedAmount := common.LeftPadBytes(amountBig.Bytes(), 32)
	resourceTypeBig := new(big.Int).SetInt64(1)
	paddedResourceType := common.LeftPadBytes(resourceTypeBig.Bytes(), 32)

	data = append(data, methodId...)
	data = append(data, paddedReceive...)
	data = append(data, paddedAmount...)
	data = append(data, paddedResourceType...)

	fmt.Printf("parameter: %x\n", data)
	endpoint.TriggerSmartContract(ctx, "TU2MJ5Veik1LRAgjeSzEdvmDYx7mefJZvd", data, &tron.Wallet{
		Owner: "Txxx",
		Ctrl:  "xxx",
	}, tron.ToSUN(50))
}




func (e *Endpoint) TriggerSmartContract(ctx context.Context, contract string, data []byte, wallet *Wallet, cv int64) (*api.TransactionExtention, error) {
	transferContract := new(core.TriggerSmartContract)
	transferContract.OwnerAddress = internal.DecodeCheck(wallet.Owner)
	transferContract.ContractAddress = internal.DecodeCheck(contract)
	transferContract.Data = data
	transferContract.CallValue = cv

	transferTransactionEx, err := e.wallet.TriggerConstantContract(ctx, transferContract)
	var txId string
	if err != nil {
		return nil, err
	}
	transferTransaction := transferTransactionEx.Transaction
	if transferTransaction == nil ||
		len(transferTransaction.GetRawData().GetContract()) == 0 {
		return nil, fmt.Errorf("transfer error: invalid transaction")
	}

	transferTransaction.RawData.FeeLimit = 200000000
	hash, err := SignTransaction(transferTransaction, wallet.Ctrl)
	if err != nil {
		return nil, err
	}
	txId = hexutil.Encode(hash)

	result, err := e.BroadcastTransaction(ctx, transferTransaction)
	if err != nil {
		return nil, err
	}
	if !result {
		return nil, fmt.Errorf("api get false the msg: %v", result)
	}
	fmt.Println(txId)
	return transferTransactionEx, err
}
```

**Comment by wonddok** [comment]
> return : rent is paused,what does this mean?

I also encountered this problem, what is the reason?

**Comment by wonddok** [comment]
It's OKay f207473e4c997a0083d5eb22e5641ef58b0e10120c0c84c69df7c76d157203dd
