### ISSUE TITLE
Start at newest block

### ISSUE THREAD

**Issue by TelegramXPlus** [tronprotocol/java-tron#6016]
Hello,

I know this might be a dumb question, but I was trying to get the newest transactions (from the latest) block, however I keep getting old transactions (starting from 2018). I am not sure what I am doing wrong but this is my config.conf

```
event.subscribe = {
    native = {
      useNativeQueue = true
      bindport = 5555
      sendqueuelength = 1000
    }

    path = ""
    server = ""
    dbconfig = ""
    contractParse = true
    topics = [
        {
          triggerName = "transaction"
          enable = true
          topic = "transaction"
          solidified = false
          ethCompatible = false
        }
    ]
    filter = {
       fromblock = ""
       toblock = ""
       contractAddress = [""]
       contractTopic = [""]
    }
}
```

I am using zeromq with js to listen to events (transaction).

**Comment by abn2357** [comment]
what do you mean 'start at newest block',  run a fullnode and omit the block synchronization process?

**Comment by endiaoekoe** [comment]
> I was trying to get the newest transactions (from the latest) block

@TelegramXPlus 
below is the explanation of how to filter the logs you want to receive in config.conf:
```
    filter = {
       fromblock = "" // the value could be "", "earliest" or a specified block number as the beginning of the queried range
       toblock = "" // the value could be "", "latest" or a specified block number as end of the queried range
       contractAddress = [
           "" // contract address you want to subscribe, if it's set to "", you will receive contract logs/events with any contract address.
       ]

       contractTopic = [
           "" // contract topic you want to subscribe, if it's set to "", you will receive contract logs/events with any contract topic.
       ]
    }
```
In my opinion, youou can try set the value of 'from block' to a newer number(eg: newest block num -1000), and set the value of 'toblock' to 'latest'.

**Comment by 0xbigapple** [comment]
you can download the Fullnode data snapshot from [here](https://developers.tron.network/docs/main-net-database-snapshots#fullnode-data-snapshot)，then continue to sync.

**Comment by TelegramXPlus** [comment]
> what do you mean 'start at newest block',  run a fullnode and omit the block synchronization process?

Yes indeed. I am only interested in the new transactions and the synchronization process is taking too long, so I wanted to know if there was a way to bypass it and get the newest events on the node.

**Comment by abn2357** [comment]
> > what do you mean 'start at newest block',  run a fullnode and omit the block synchronization process?
> 
> Yes indeed. I am only interested in the new transactions and the synchronization process is taking too long, so I wanted to know if there was a way to bypass it and get the newest events on the node.

I think there is no way to omit synchronization process. If you want to save time, try[ lite fullnode](https://tronprotocol.github.io/documentation-en/developers/litefullnode/).

**Comment by vivian1912** [comment]
@TelegramXPlus May I ask if the above answer your question?  If yes, this issue will be closed later and please feel free to re-open it if you still see the issue, thanks.

**Comment by TelegramXPlus** [comment]
> @TelegramXPlus May I ask if the above answer your question? If yes, this issue will be closed later and please feel free to re-open it if you still see the issue, thanks.

Yes it does. thanks for the help.
