### ISSUE TITLE
what does Constant mean here in config file?

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/java-tron#6018]
<img width="302" alt="截屏2024-09-27 15 47 24" src="https://github.com/user-attachments/assets/6eba6efe-d0f6-4933-ab3c-ad8aa8afc4ca">

**Comment by halibobo1205** [comment]
Set `vm.supportConstant = true for` [triggerconstantcontract](https://developers.tron.network/reference/triggerconstantcontract).
