### ISSUE TITLE
How can I quickly obtain all internal transactions

### ISSUE THREAD

**Issue by z1z2z3z** [tronprotocol/java-tron#6019]
I have set up a full node locally (including internal transactions), how can I quickly retrieve all internal transactions on the blockchain.
`GetBlockByLimitNext` method cann't give the block info included internal transactions
Is there a method to retrieve multiple block information at once?

**Comment by endiaoekoe** [comment]
> method cann't give the block info included internal transactions

@z1z2z3z 
In my development experience of using these query APIs when querying multiple blocks, I will use  API 'wallet/getblockbylatestnum' to get latest blocks ,use the tx_ids extract from returned block info as query param then query the API 'wallet/gettransactioninfobyid' to get the tx details(include internal txs).
