### ISSUE TITLE
return value in event log is inaccurate

### ISSUE THREAD

**Issue by z307287280** [tronprotocol/java-tron#6022]
#### Expected behaviour

the data of event from queried transaction should have exact hex content as it shows on tronscan

#### Actual behaviour

the return value of data has been cut down into half size when the length of entire hex is long greater than 128, which only presents a part of original data information. 

Here is an instance , the third index event(pairCreated even, having index number of 2) on this transaction: https://tronscan.org/#/transaction/227300c7d557d125f2d50bec9a562485df41b408f8760b22e0658df39c231753/event-logs has original size of 256:

"00000000000000000000000040bfb16cad6816ec37d74c1e20988670e4dcfcd0000000000000000000000000891cdb91d149f23b1a45d9c5ca78a88d0cb44c1800000000000000000000000033137bddf327a8300777a372a1916ddfae88d4050000000000000000000000000000000000000000000000000000000000000ef2"

**However, by querying through the method "GetTransactionInfoById" from sdk, the return value of data size is only 128:**

"00000000000000000000000033137bddf327a8300777a372a1916ddfae88d4050000000000000000000000000000000000000000000000000000000000000ef2"

if we take a closely look at the return value, it is exact the second half content of the original data.  I have tried different node(trongrid and my own private node) and sdk (python and golang), the return value are all the same.   

#### Frequency

100%
#### Steps to reproduce the behaviour

1. [Step 1] Check the transaction tronscan and lookup an original event data
2. [Step 2] Check the same transaction through trongrid api and lookup the return event data 
3. [Step ...] Compare the data from step1 and step2, they are different

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 0xbigapple** [comment]
index data  in topics, other in data.

<img width="1462" alt="image" src="https://github.com/user-attachments/assets/abd8a009-d35b-4b4f-9a27-191b9cee319d">

**Comment by 0xbigapple** [comment]
same with ethereum 
<img width="487" alt="image" src="https://github.com/user-attachments/assets/e28d3999-1389-4506-9e73-d70144237f7f">

**Comment by z307287280** [comment]
> same with ethereum <img alt="image" width="487" src="https://private-user-images.githubusercontent.com/175079588/371995151-e28d3999-1389-4506-9e73-d70144237f7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTYxNDcsIm5iZiI6MTcyNzY5NTg0NywicGF0aCI6Ii8xNzUwNzk1ODgvMzcxOTk1MTUxLWUyOGQzOTk5LTEzODktNDUwNi05ZTczLWQ3MDE0NDIzN2Y3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxMTMwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDA0NjViNDc4ZDRlZTZjYjgzNWMxZjZiYWNjNTVmNTFiNDc5N2JiZWQ1ZjcyMzIxOWFhM2E2MmM2Yjc5ZjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._g5HZojOKvlIB5KDcE_7NwbrBvfqqVykYdW5qwi5G4k">

Thanks! Totally got it
