### ISSUE TITLE
There is a small error in tronscan

### ISSUE THREAD

**Issue by S1ep** [tronprotocol/java-tron#6038]
<img width="668" alt="截屏2024-10-10 19 57 58" src="https://github.com/user-attachments/assets/f4b3f4fd-0023-4da1-b177-c2c0edd59efb">

It should be Contracts not Contacts
Anyone who can contact the tronscan team can report this issue to them

**Comment by 317787106** [comment]
@S1ep Maybe I can try to contact them to fix the issue.
