### ISSUE TITLE
Can I activate account through Internal Transaction?

### ISSUE THREAD

**Issue by bbaktaeho** [tronprotocol/java-tron#6040]
Hi, I have a question about activate account.

Can I activate account through Internal Transaction?

**Comment by bbaktaeho** [comment]
@abn2357 
Isn't it activated even if the balance is only 1 SUN?

**Comment by abn2357** [comment]
> @abn2357 Isn't it activated even if the balance is only 1 SUN?

You mean your sun balance of your newly created account gt 1 but you are not sure whether it is activated?

**Comment by bbaktaeho** [comment]
https://developers.tron.network/docs/account#account-activation
look at this docs, 
> Send any amount of TRX or TRC-10 tokens from an existing account to the new account;

So, I was wondering if the account would be activated if the amount was received through an internal transaction.

**Comment by bbaktaeho** [comment]
@abn2357 Thanks!

**Comment by bbaktaeho** [comment]
https://github.com/tronprotocol/tips/blob/master/tip-54.md
