### ISSUE TITLE
Why the name of function 2 and function3  are same in the juststable main contract?

### ISSUE THREAD

**Issue by S1ep** [tronprotocol/java-tron#6042]
<img width="627" alt="截屏2024-10-18 11 10 14" src="https://github.com/user-attachments/assets/5cb4586e-15bb-4e83-954e-884c084b2e23">

**Comment by laurenceja** [comment]
@S1ep What is the contract address?

**Comment by S1ep** [comment]
> @S1ep What is the contract address?

TCBLTVx7dJWcFBBNE7e3QEPHXEtigsbpth

**Comment by laurenceja** [comment]
Although the function names are the same, but they have different parameters, so they are two different functions, and they have different function selector. https://tronscan.org/#/contract/TCBLTVx7dJWcFBBNE7e3QEPHXEtigsbpth/code

**Comment by S1ep** [comment]
> Although the function names are the same, but they have different parameters, so they are two different functions, and they have different function selector. https://tronscan.org/#/contract/TCBLTVx7dJWcFBBNE7e3QEPHXEtigsbpth/code

I know they are two different functions because function selector of them are different, one is 1edf0c1e, the other is 516e9aec. I think it is better to name different names in tronscan to distinguish.

**Comment by laurenceja** [comment]
Tronscan will not modify the contract function's name, it only gets and shows all functions, user can trigger contract function through coding or tronscan, and the original function name can keep the two ways consistent.

**Comment by S1ep** [comment]
> Tronscan will not modify the contract function's name, it only gets and shows all functions, user can trigger contract function through coding or tronscan, and the original function name can keep the two ways consistent.

Thx, got it.
