### ISSUE TITLE
How to determine if a trc20 token is a meme coin on tron?

### ISSUE THREAD

**Issue by S1ep** [tronprotocol/java-tron#6045]

**Comment by KrisdiaPaul** [comment]
In my opinion, generally speaking if a trc20 token is not verified with a small red icon on TRONSCAN, it is a meme coin, you could refer to [here](https://tronscan.io/#/tokens/list) to check all the listed trc20 tokens. And if you talking about the meme coin listed on sunpump, you could check it by inputting the contract address and search on the sunpump [homepage](https://sunpump.meme/home).

**Comment by S1ep** [comment]
> In my opinion, generally speaking if a trc20 token is not verified with a small red icon on TRONSCAN, it is a meme coin, you could refer to [here](https://tronscan.io/#/tokens/list) to check all the listed trc20 tokens. And if you talking about the meme coin listed on sunpump, you could check it by inputting the contract address and search on the sunpump [homepage](https://sunpump.meme/home).

Is there an interface to check?

**Comment by KrisdiaPaul** [comment]
> > In my opinion, generally speaking if a trc20 token is not verified with a small red icon on TRONSCAN, it is a meme coin, you could refer to [here](https://tronscan.io/#/tokens/list) to check all the listed trc20 tokens. And if you talking about the meme coin listed on sunpump, you could check it by inputting the contract address and search on the sunpump [homepage](https://sunpump.meme/home).
> 
> Is there an interface to check?

No, as far as I know

**Comment by 0xbigapple** [comment]
meme coin is a community definition, we can't distinguish it  by it's contract。

**Comment by abn2357** [comment]
I Find an interface to check whether a token is a sunpump token(meme coin). 
![Uploading 截屏2024-11-04 17.27.31.png…]()
Hope it can help you.

**Comment by abn2357** [comment]
I Find an interface to check whether a token is a sunpump token(meme coin).
<img width="501" alt="截屏2024-11-04 17 27 31" src="https://github.com/user-attachments/assets/8fc646f5-ae20-47ed-9326-c599f174ef9f">

Hope it can help you.
