### ISSUE TITLE
How can I get the exact date of the latest upgrade of java-tron.

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/java-tron#6049]
<img width="551" alt="截屏2024-10-23 12 58 12" src="https://github.com/user-attachments/assets/5dbe744c-c79c-4fc0-b302-eccb36e92291">

**Comment by KrisdiaPaul** [comment]
If you move your mouse over the `xx minutes|hours\... ago` label, a tooltip will be displayed showing the UTC time the commit was created at.

<img width="585" alt="image" src="https://github.com/user-attachments/assets/78b00e56-e339-4944-97a2-fc19013a61a6">
