### ISSUE TITLE
About order of token transfers in tronscan

### ISSUE THREAD

**Issue by S1ep** [tronprotocol/java-tron#6052]
Are the token transfers ordered by the code execution order？
For example transaction [7d189fe178f7b5e591a6169eabf5deaef8f75f58c052ac4be221a5256474dfc5](https://tronscan.io/#/transaction/7d189fe178f7b5e591a6169eabf5deaef8f75f58c052ac4be221a5256474dfc5)
<img width="1322" alt="截屏2024-10-25 12 39 11" src="https://github.com/user-attachments/assets/a4b61f5b-f304-4462-96fe-0b65a41fb7fb">

**Comment by KrisdiaPaul** [comment]
No, it's not followed by the code execution order.

**Comment by S1ep** [comment]
> No, it's not followed by the code execution order.

So which order is it followed?

**Comment by KrisdiaPaul** [comment]
> > No, it's not followed by the code execution order.
> 
> So which order is it followed?

Most likely ordered by the type of transfer transactions, internal transactions first, and then the different standard token transfer transactions.

**Comment by 0xbigapple** [comment]
I think it's same with etherscan， in chronological order.
