### ISSUE TITLE
Can smart contract account have resource of bandwidth?

### ISSUE THREAD

**Issue by GrothenDI** [tronprotocol/java-tron#6061]
I know It can have resource of energy. About bandwidth, I am a little puzzled.

**Comment by endiaoekoe** [comment]
@GrothenDI 
per my understanding, a smart contract account can have both energy resources as well as bandwidth resource.
a smart contract account can stake TRX to acquire resources（energy or bandwidth）

**Comment by DongDongSunny** [comment]
tron account generated by wallet and smart contract account are both account in Tron with same resource model like free bandwidth, energey gain through stake.

**Comment by DongDongSunny** [comment]
The special part would be the way to get bandwith and energy, as current we cannot directly call Tron API to do smart contract account resource delegation through freezeBalanceV2 or delegateResource, but we can write smart contract logic to allow contract account itself to freezeBalanceV2. Delegate resource to smart contract address is not allowed in Tron.

**Comment by vivian1912** [comment]
Hi @GrothenDI May I ask if the above answer your question?  If yes, this issue will be closed later and please feel free to re-open it if you still see the issue, thanks.
