### ISSUE TITLE
Does Tron support creating a meme coin with a Gif(dynamic picture)?

### ISSUE THREAD

**Issue by S1ep** [tronprotocol/java-tron#6063]

**Comment by endiaoekoe** [comment]
@S1ep 
as far as I know.'[Sunpump](https://sunpump.meme/)' meme coin platform seems like fits your requirements. you can create a meme coin on the platform with a dynamic picture.

**Comment by 0xbigapple** [comment]
> @S1ep as far as I know.'[Sunpump](https://sunpump.meme/)' meme coin platform seems like fits your requirements. you can create a meme coin on the platform with a dynamic picture.

yes，also find some gif on sunpump

**Comment by S1ep** [comment]
> > @S1ep as far as I know.'[Sunpump](https://sunpump.meme/)' meme coin platform seems like fits your requirements. you can create a meme coin on the platform with a dynamic picture.
> 
> yes，also find some gif on sunpump

Could you share me an address. Thx a LOT.
