### ISSUE TITLE
Where can I find source code of unverified smart contract?

### ISSUE THREAD

**Issue by S1ep** [tronprotocol/java-tron#6067]
For example, the comptroller implementation of JustLend(address: [TCtzg2CQsAuLkSxrGjFGbHVwKvv95W9C8e](https://tronscan.io/#/contract/TCtzg2CQsAuLkSxrGjFGbHVwKvv95W9C8e/code))

**Comment by DongDongSunny** [comment]
I think for now, the source code of unverified smart contract is not public

**Comment by 0xbigapple** [comment]
> For example, the comptroller implementation of JustLend(address: [TCtzg2CQsAuLkSxrGjFGbHVwKvv95W9C8e](https://tronscan.io/#/contract/TCtzg2CQsAuLkSxrGjFGbHVwKvv95W9C8e/code))

Generally, if the source code not unverified, you can visit its official website,  where myabe you can find  github link or view source code.

**Comment by JanellG** [comment]
Everyone should be careful with fake bitcoin platforms, as I was scammed on facebook trying to invest in bitcoin. If you have been scammed before, kindly contact (cryptospamhacker@gmail .com) to help you recover back you lost money, He's the best.
