### ISSUE TITLE
About token transfers of  tx id: 05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63 

### ISSUE THREAD

**Issue by GrothenDI** [tronprotocol/java-tron#6068]
[05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63
](https://tronscan.io/#/transaction/05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63)
why token transfer doesn't include 116.368208 trx transfer from user [TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL](https://tronscan.io/#/address/TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL) to [jtrx](https://tronscan.io/#/contract/TE2RzoSV3wFK99w6J9UnnZ4vLfXYoxvRwP) 
I also can't find the corresponding transfer record on the user page.

**Comment by DongDongSunny** [comment]
Hi, I could see the transaction 05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63 on user page https://tronscan.io/#/address/TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL, you could see the transactions and transfers there.

**Comment by GrothenDI** [comment]
I mean trx transfer in the refered transaction, not the transaction itself.

**Comment by Sophiestanworth** [comment]
> [05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63 ](https://tronscan.io/#/transaction/05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63) why token transfer doesn't include 116.368208 trx transfer from user [TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL](https://tronscan.io/#/address/TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL) to [jtrx](https://tronscan.io/#/contract/TE2RzoSV3wFK99w6J9UnnZ4vLfXYoxvRwP) I also can't find the corresponding transfer record on the user page.


Hello @GrothenDI,

The transaction 05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63 doesn’t display the 116.368208 TRX transfer from TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL to jtrx, and there's no related record on the user page. Please check the blockchain explorer or contact support with the transaction ID for further assistance.

A support ticket has been created for you (ID: TRN7638). For help, visit [Tron Protocol Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat at the bottom right to connect with an agent.

Thank you for your patience!

**Comment by 0xbigapple** [comment]
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/4703f2e2-3ff6-4905-a986-15bcd7ee0676">

TRX and other trc10 tokens show in Value form.

**Comment by GrothenDI** [comment]
> <img alt="image" width="1117" src="https://private-user-images.githubusercontent.com/175079588/383797564-4703f2e2-3ff6-4905-a986-15bcd7ee0676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzY3OTEsIm5iZiI6MTczMTAzNjQ5MSwicGF0aCI6Ii8xNzUwNzk1ODgvMzgzNzk3NTY0LTQ3MDNmMmUyLTNmZjYtNDkwNS1hOTg2LTE1YmNkN2VlMDY3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwMzI4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWViOTY2N2Y3N2ZjZDM0N2U3ZWVmZjVmNjZhOGFiOTI0YzUzMTMyNmM5OGEzMTdlNGFjMzRiOGRjZGVhMzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rCp9x7Zl01LQl6tqnuIWwkXpMeZqNGYDXa3wI3zJNK4">
> TRX and other trc10 tokens show in Value form.
Why only trx display as value form. jusdt or other token mint of justlend  doesn't have the above question.
<img width="1245" alt="截屏2024-11-08 11 32 32" src="https://github.com/user-attachments/assets/b7963db1-14a2-4b4b-a7a1-9e5dc2872cc5">

**Comment by GrothenDI** [comment]
> > [05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63 ](https://tronscan.io/#/transaction/05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63) why token transfer doesn't include 116.368208 trx transfer from user [TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL](https://tronscan.io/#/address/TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL) to [jtrx](https://tronscan.io/#/contract/TE2RzoSV3wFK99w6J9UnnZ4vLfXYoxvRwP) I also can't find the corresponding transfer record on the user page.
> 
> Hello @GrothenDI,
> 
> The transaction 05c22a854937e22d88f1f1cb93037f2d3c9af9d2dcef3332ad375ad4818dff63 doesn’t display the 116.368208 TRX transfer from TFUjkiDNC375VzinEJtq4WHwQKm5h4KtNL to jtrx, and there's no related record on the user page. Please check the blockchain explorer or contact support with the transaction ID for further assistance.
> 
> A support ticket has been created for you (ID: TRN7638). For help, visit [Tron Protocol Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat at the bottom right to connect with an agent.
> 
> Thank you for your patience!

Thx a lot for your help. But the page doesn't response when I click Support Ticket.
<img width="336" alt="截屏2024-11-08 11 45 24" src="https://github.com/user-attachments/assets/f24fd841-2713-4f5e-9df3-49623111a5d6">

**Comment by 0xbigapple** [comment]
> > <img alt="image" width="1117" src="https://private-user-images.githubusercontent.com/175079588/383797564-4703f2e2-3ff6-4905-a986-15bcd7ee0676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzY3OTEsIm5iZiI6MTczMTAzNjQ5MSwicGF0aCI6Ii8xNzUwNzk1ODgvMzgzNzk3NTY0LTQ3MDNmMmUyLTNmZjYtNDkwNS1hOTg2LTE1YmNkN2VlMDY3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwMzI4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWViOTY2N2Y3N2ZjZDM0N2U3ZWVmZjVmNjZhOGFiOTI0YzUzMTMyNmM5OGEzMTdlNGFjMzRiOGRjZGVhMzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rCp9x7Zl01LQl6tqnuIWwkXpMeZqNGYDXa3wI3zJNK4">
> > TRX and other trc10 tokens show in Value form.
> 
> Why only trx display as value form. jusdt or other token mint of justlend doesn't have the above question. <img alt="截屏2024-11-08 11 32 32" width="1245" src="https://private-user-images.githubusercontent.com/29111864/384216837-b7963db1-14a2-4b4b-a7a1-9e5dc2872cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDEyMjQsIm5iZiI6MTczMTA0MDkyNCwicGF0aCI6Ii8yOTExMTg2NC8zODQyMTY4MzctYjc5NjNkYjEtMTRhMi00YjRiLWE3YTEtOWU1ZGMyODcyY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA0NDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MmUxMGVkYmYzNGZhOTc4NWQ4MzFjNDljMTZiMjhjMDIxZGM4ZDQ1N2E1MGIzNmEzNzlmZWQ2Njk3MGExNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DsRUYsMFaId2o7wOOgc10qdbqDIWkfQb9OznlLoSpx0">

jusdt and other tokens are trc20 token.

**Comment by GrothenDI** [comment]
> > > <img alt="image" width="1117" src="https://private-user-images.githubusercontent.com/175079588/383797564-4703f2e2-3ff6-4905-a986-15bcd7ee0676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzY3OTEsIm5iZiI6MTczMTAzNjQ5MSwicGF0aCI6Ii8xNzUwNzk1ODgvMzgzNzk3NTY0LTQ3MDNmMmUyLTNmZjYtNDkwNS1hOTg2LTE1YmNkN2VlMDY3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwMzI4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWViOTY2N2Y3N2ZjZDM0N2U3ZWVmZjVmNjZhOGFiOTI0YzUzMTMyNmM5OGEzMTdlNGFjMzRiOGRjZGVhMzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rCp9x7Zl01LQl6tqnuIWwkXpMeZqNGYDXa3wI3zJNK4">
> > > TRX and other trc10 tokens show in Value form.
> > 
> > 
> > Why only trx display as value form. jusdt or other token mint of justlend doesn't have the above question. <img alt="截屏2024-11-08 11 32 32" width="1245" src="https://private-user-images.githubusercontent.com/29111864/384216837-b7963db1-14a2-4b4b-a7a1-9e5dc2872cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDEyMjQsIm5iZiI6MTczMTA0MDkyNCwicGF0aCI6Ii8yOTExMTg2NC8zODQyMTY4MzctYjc5NjNkYjEtMTRhMi00YjRiLWE3YTEtOWU1ZGMyODcyY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA0NDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MmUxMGVkYmYzNGZhOTc4NWQ4MzFjNDljMTZiMjhjMDIxZGM4ZDQ1N2E1MGIzNmEzNzlmZWQ2Njk3MGExNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DsRUYsMFaId2o7wOOgc10qdbqDIWkfQb9OznlLoSpx0">
> 
> jusdt and other tokens are trc20 token.

It didn't solve my problem. My real question is we can't find the transfer record both in jtrx and user account page. It is not a good thing that token can' be traced in tronscan.

**Comment by Sophiestanworth** [comment]
> Thx a lot for your help. But the page doesn't response when I click Support Ticket.

Hey there @GrothenDI , 
Apologies for the delay in response. It seems your message may have been missed due to temporary network downtime, and our dev team was unavailable to assist at that time. Please reach out now using the live chat bubble on the support page linked above to [connect directly with a support agent in real-time](thedappsupport.com). They’ll be ready to help you right away.

**Comment by JanellG** [comment]
I’m pleased to recommend the fund recovery services for (cryptospamhacker@gmail .com) has the best and reliable fund recovery agency to help you get back your lost, missing or stolen digital assets back in just one swipe. They are the real deal as I was able to recover my stolen USDT back after days of being depressed. This team brought back my lost hope, they are the best
