### ISSUE TITLE
Error getting Oracle Java 1.8

### ISSUE THREAD

**Issue by bleiva** [tronprotocol/java-tron#6070]
Hi everyone, I want to run a node for Tron but I couldn't download the correct Java version from Oracle website. 

https://www.oracle.com/java/technologies/downloads/#java8?er=221886

I registered to download deprecated versions but I got this error

![Screenshot from 2024-11-07 09-46-32](https://github.com/user-attachments/assets/49a02be3-3203-47f3-aad3-42a16f19a447)

Do you know other place where I can download oracle java 1.8?

Thanks

**Comment by DongDongSunny** [comment]
Could download here for mac [https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=416&f[…]_architecture_target_id=391&field_java_package_target_id=Al](https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=416&field_operating_system_target_id=431&field_architecture_target_id=391&field_java_package_target_id=All) and you could choose Operation System for windows

**Comment by bleiva** [comment]
Thank you @DongDongSunny :+1:
