### ISSUE TITLE
How to query state of past block?

### ISSUE THREAD

**Issue by bbaktaeho** [tronprotocol/java-tron#6074]
Can’t I get the state of past blocks on Tron?
For example, I want to check the TRC-20 balance owned by account in 10000 block.

See [docs](https://developers.tron.network/reference/eth_call),
```
QUANTITY|TAG - currently, only "latest" is available. 
```
Isn't there a solution not only for JSONRPC but also for other APIs?

**Comment by laurenceja** [comment]
@bbaktaeho As I know, now it does not support to query a TRC20 token balance on a past block directly. Alternatively, we can get the events about accounts, and save the balance changes to realize this function indirectly.

**Comment by bbaktaeho** [comment]
@laurenceja Thanks.
I want query the historical balance of TRC-20. But, currently not possible in the tron ​​java client.

**Comment by DongDongSunny** [comment]
you could see all the transactions related to your own easily use transcan, like [this link](https://tronscan.org/#/tools/advanced-filter?type=tx&times=24h&relation=or), choose the Type to "Trigger Smart Contract" and choose the change balance method like "Transfer" or your customised method

**Comment by S1ep** [comment]
> @bbaktaeho As I know, now it does not support to query a TRC20 token balance on a past block directly. Alternatively, we can get the events about accounts, and save the balance changes to realize this function indirectly.
Do you know any data statistical provider on Tron provide the function?

**Comment by S1ep** [comment]
> @bbaktaeho As I know, now it does not support to query a TRC20 token balance on a past block directly. Alternatively, we can get the events about accounts, and save the balance changes to realize this function indirectly.

@laurenceja Do you know any tron data statistical provider provide the function?

**Comment by laurenceja** [comment]
@S1ep Sorry, I haven't heard of it.
