### ISSUE TITLE
connect ETIMEDOUT during calling full node http api

### ISSUE THREAD

**Issue by inapeace0** [tronprotocol/java-tron#6085]
I set up a lite fullnode and called the `GetTransactionInfoById` Solidity API to analyze all `TRX` and `USDT` transactions asyncronously.
However, I've encountered an issue with some transactions, as shown in the image below.
![image](https://github.com/user-attachments/assets/4b71c744-2072-4d28-969b-ba6a7199e29b)

I'm considering the possibility of **rate limit** but I'm not certain. I would appreciate your advice on this matter. Thank you!

**Comment by CarlChaoCarl** [comment]
@inapeace0 
You can consider using java-tron's Event Subscription mechanism to implement it. 
For details, please refer to: 
https://tronprotocol.github.io/documentation-en/architecture/event/

**Comment by DongDongSunny** [comment]
for your problem, maybe you could set a longer timeout value. But since you will request every 3 second to analyze **all** TRX and USDT transactions, using Event Subscription would be a better way and give you a timely events. as [CarlChaoCarl](https://github.com/CarlChaoCarl) mentioned.

**Comment by inapeace0** [comment]
> @inapeace0 You can consider using java-tron's Event Subscription mechanism to implement it. For details, please refer to: https://tronprotocol.github.io/documentation-en/architecture/event/

I subscribe transaction events by that mechanism. I'm going to confirm the success of transaction and its detail(like token amount).

**Comment by inapeace0** [comment]
> for your problem, maybe you could set a longer timeout value, as sever maybe busy at some time. But since you will request every 3 second to analyze **all** TRX and USDT transactions, using Event Subscription would be a better way and give you a timely events. as [CarlChaoCarl](https://github.com/CarlChaoCarl) mentioned.

I subscribe transaction events by that mechanism. I'm going to confirm the success of transaction and its detail(like token amount).
