### ISSUE TITLE
Two questions about meme coin with same pic

### ISSUE THREAD

**Issue by S1ep** [tronprotocol/java-tron#6087]
<img width="612" alt="截屏2024-11-22 12 54 35" src="https://github.com/user-attachments/assets/bcb6880a-5c0b-4693-8e15-3fa43c3d5882">

1.Why different meme can use same pic?
2.Do they involve infringement issues with the company that develops the game?

**Comment by CooperDepp** [comment]
@S1ep I think only check the md5 of the pic, regardless of the content of the pic. And for the background, I think you should turn to tronscan for more info.
