### ISSUE TITLE
QUESTION: Add Test data for private test net

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/java-tron#609]
I am building a private test net. I would like to test the sync by creating blocks of transactions. Could I put a call at the end of my config file to load  a test blockchain? Since I'm restarting the network so often it would be convenient if I could just load that data when the first witness starts up.

Or does all that load with a SolidityNode test suite?

**Comment by taihaofu** [comment]
@bondibox I will close it for now. Please reopen this issue if you have more output.
