### ISSUE TITLE
Invoke a bunch of http solidity apis, but all requests are failed in the azure server

### ISSUE THREAD

**Issue by inapeace0** [tronprotocol/java-tron#6091]
Hello,

I have a code that calls an http solidity api every 4 milliseconds. I installed a self-hosted lite full node and tested it on my VPS ([Cloudzy](https://cloudzy.com/)), where it worked perfectly.

However, when I deployed my code on an azure server, all the api calls failed. Interestingly, when I invoked the api manually through the Azure console, it worked without any issues.

This is the result that I invoked an api while running the azure server.(failed)
![image](https://github.com/user-attachments/assets/f59abaa3-9a59-4ad3-8ccb-aea76ccf60b9)

I'd appreciate it if you give any advice to solve this problem.
Thanks in advance.

**Comment by endiaoekoe** [comment]
> Hello,
> I'd appreciate it if you give any advice to solve this problem. Thanks in advance.

hi, @inapeace0 
Based on the error message and your description, here are several potential solutions to troubleshoot the API connection issues i can make.

1.Check Azure's Network Security Group (NSG) rules, ensure port 8091 is open for both inbound and outbound traffic
,and verify that your application's security group allows HTTP/HTTPS traffic

2.Check if DNS resolution is working properly in Azure environment

**Comment by jacksun55** [comment]
> > Hello,
> > I'd appreciate it if you give any advice to solve this problem. Thanks in advance.
> 
> hi, @inapeace0 Based on the error message and your description, here are several potential solutions to troubleshoot the API connection issues i can make.
> 
> 1.Check Azure's Network Security Group (NSG) rules, ensure port 8091 is open for both inbound and outbound traffic ,and verify that your application's security group allows HTTP/HTTPS traffic
> 
> 2.Check if DNS resolution is working properly in Azure environment

Thanks for your reply.

But I guess this is not a security problem. As I described, it's good to call an api in azure server(through console) one by one, but it failed when my code calls a bunch of apis at the same time. I tried the same action in my vps, but it was success.

**Comment by inapeace0** [comment]
> > Hello,
> > I'd appreciate it if you give any advice to solve this problem. Thanks in advance.
> 
> hi, @inapeace0 Based on the error message and your description, here are several potential solutions to troubleshoot the API connection issues i can make.
> 
> 1.Check Azure's Network Security Group (NSG) rules, ensure port 8091 is open for both inbound and outbound traffic ,and verify that your application's security group allows HTTP/HTTPS traffic
> 
> 2.Check if DNS resolution is working properly in Azure environment

Thanks for your reply.

But I guess this is not a security problem. As I described, it's good to call an api in azure server(through console) one by one, but it failed when my code calls a bunch of apis at the same time. I tried the same action in my vps, but it was success.

**Comment by endiaoekoe** [comment]
> but it failed when my code calls a bunch of apis at the same time

hi, @inapeace0 
could it possible ‘calling an API every 4ms (250 calls per second)’ might trigger rate limiting settings in azure server, can you set your calls rate to 1 call per second, then watch if this error occured again or not？

**Comment by vivian1912** [comment]
@inapeace0 May I ask if the above answer your question?  If yes, this issue will be closed later and please feel free to re-open it if you still see the issue, thanks.
