### ISSUE TITLE
FullNode.jar 4.7.7 : Thread qtp: [API](Util.java:315) NullPointer Exception ?

### ISSUE THREAD

**Issue by mercy1230** [tronprotocol/java-tron#6109]
After The version 4.7.7 FullNode.jar run successfully, 
it is sync normally, 

when I check the tron.log

I found  a  NullPointer Exception:
     A Thread named 'qtp',
     Position: [ API ] ( Util.java: 315 )  null

Does anyone know what's going on and what the impact in future will be?

**Comment by 317787106** [comment]
@mercy1230 Can you paste the related log and how it happens ?

**Comment by DongDongSunny** [comment]
> I am running the downloaded jar package, and the node cannot be stopped, so debugging is not very convenient. Is there anyone who knows ?

there is a log folder and file inside called tron.log, could you find it and check the logging info

**Comment by 317787106** [comment]
@mercy1230 If you broadcast a transaction without vaild contract, it will throw the NullPointerException.

![telegram-cloud-photo-size-5-6228932632520016872-y](https://github.com/user-attachments/assets/900b1474-b068-4343-927e-815d8d1d52f1)

![telegram-cloud-photo-size-5-6228932632520016873-y](https://github.com/user-attachments/assets/b4be568f-95c1-4e4c-b669-726d2683b039)

Contract belongs to the transaction:

![telegram-cloud-photo-size-5-6228932632520016874-y](https://github.com/user-attachments/assets/ea203934-dd61-4eae-b0df-fb2be9ec5489)

 This error doesn't have any impact on Fullnode.

**Comment by zeusoo001** [comment]
@317787106 Does this prompt information need to be optimized, otherwise users will not understand it?

**Comment by 317787106** [comment]
Yes, the specification of exception is not very clear, it's excepted to revise it later.

**Comment by mercy1230** [comment]
> Does this prompt information need to be optimized, otherwise users will not understand it?

I ' ve taken a screenshot
hi, as the pic below
![qtp](https://github.com/user-attachments/assets/0a6bb280-804d-4976-bf8b-b50596d70d5d)

**Comment by mercy1230** [comment]
> I ' ve taken a screenshot
> I found it from the tron.log
> hi, as the pic below



> @mercy1230 If you broadcast a transaction without vaild contract using http, it will throw the NullPointerException.
> 
> ![telegram-cloud-photo-size-5-6228932632520016872-y](https://private-user-images.githubusercontent.com/23312631/391438139-900b1474-b068-4343-927e-815d8d1d52f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjY5MTIsIm5iZiI6MTczMzEyNjYxMiwicGF0aCI6Ii8yMzMxMjYzMS8zOTE0MzgxMzktOTAwYjE0NzQtYjA2OC00MzQzLTkyN2UtODE1ZDhkMWQ1MmYxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA4MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ODVmMWIzNDViZTMwNmZkMWEwZDRhMGIxYzE0NTRjYWE0YzI0ZmE0MGM2NGFmNDc4ZDZmZGNiY2VmOTg4NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JQHAAjjRW2-xI0ZVVYIAJ6zlNP3Nfsz9AAljyRlgSH8)
> 
> ![telegram-cloud-photo-size-5-6228932632520016873-y](https://private-user-images.githubusercontent.com/23312631/391438170-b4be568f-95c1-4e4c-b669-726d2683b039.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjY5MTIsIm5iZiI6MTczMzEyNjYxMiwicGF0aCI6Ii8yMzMxMjYzMS8zOTE0MzgxNzAtYjRiZTU2OGYtOTVjMS00ZTRjLWI2NjktNzI2ZDI2ODNiMDM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA4MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYjhhZTliNDljZGZmOTE3OGQ4YmQ0ZGM0ZTRiYmE0YzVkOWRhZWUwNWNkMWM3OTU5YThjNWFhYTQyYjVlZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QrrxxdX3KhanOSgTMNsKtjkPM4VZMNoCnvrtjXXcFbk)
> 
> Contract belongs to the transaction:
> 
> ![telegram-cloud-photo-size-5-6228932632520016874-y](https://private-user-images.githubusercontent.com/23312631/391438514-ea203934-dd61-4eae-b0df-fb2be9ec5489.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjY5MTIsIm5iZiI6MTczMzEyNjYxMiwicGF0aCI6Ii8yMzMxMjYzMS8zOTE0Mzg1MTQtZWEyMDM5MzQtZGQ2MS00ZWFlLWIwZGYtZmIyYmU5ZWM1NDg5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA4MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZjQxZDZiOGIwNDRkZWNkYTM5MzIxMzZkODU3MzNkODgxNGQzYTkzY2U0MWRkYjRkOGY0OTU1YWYzMDIzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sYP1myZsL_qawpvapaIRZxrPKazX8jovCmhXX0TChuA)
> 
> This error doesn't have any impact on Fullnode.


It seems to be the question you mentioned
I have attached a screenshot of the log, please review it
![qtp](https://github.com/user-attachments/assets/95208458-6c4d-4d1d-a806-5b96a04d5236)
