### ISSUE TITLE
Nile Testnet Status: Unable to Calculate Resources for Contract Deployment

### ISSUE THREAD

**Issue by marco1208marco** [tronprotocol/java-tron#6110]
### Description
When attempting to deploy a TRC20 contract on the Nile testnet, the network shows "Unable to Calculate" (无法测算) status for energy and bandwidth resources.

### Environment
- Network: TRON Nile Testnet
- Wallet: TronLink
- Contract Type: TRC20 Token Contract
- Development Environment: Remix/TronIDE

### Steps to Reproduce
1. Connect to Nile testnet via TronLink
2. Attempt to deploy a standard TRC20 contract
3. Check resource calculation before deployment

### Current Behavior
- Network shows "Unable to Calculate" for resources
- Unable to estimate deployment costs
- Cannot proceed with contract deployment

### Expected Behavior
- Should be able to calculate required energy and bandwidth
- Should show estimated deployment costs
- Should allow contract deployment with proper resource estimation

### Questions
1. Is the Nile testnet currently experiencing any known issues?
2. Are there any plans to restore the resource calculation functionality?
3. Are there any recommended alternatives for testing TRC20 contracts in the meantime?

### Additional Context
This issue appears to be affecting the entire Nile testnet, not just specific contracts or accounts.

**Comment by DongDongSunny** [comment]
let me try the steps, last time it works well. I wonder does your contracts compile success? maybe it caused by the wrong logic.

**Comment by DongDongSunny** [comment]
> ### Description
> When attempting to deploy a TRC20 contract on the Nile testnet, the network shows "Unable to Calculate" (无法测算) status for energy and bandwidth resources.
> 
> ### Environment
> * Network: TRON Nile Testnet
> * Wallet: TronLink
> * Contract Type: TRC20 Token Contract
> * Development Environment: Remix/TronIDE
> 
> ### Steps to Reproduce
> 1. Connect to Nile testnet via TronLink
> 2. Attempt to deploy a standard TRC20 contract
> 3. Check resource calculation before deployment
> 
> ### Current Behavior
> * Network shows "Unable to Calculate" for resources
> * Unable to estimate deployment costs
> * Cannot proceed with contract deployment
> 
> ### Expected Behavior
> * Should be able to calculate required energy and bandwidth
> * Should show estimated deployment costs
> * Should allow contract deployment with proper resource estimation
> 
> ### Questions
> 1. Is the Nile testnet currently experiencing any known issues?
> 2. Are there any plans to restore the resource calculation functionality?
> 3. Are there any recommended alternatives for testing TRC20 contracts in the meantime?
> 
> ### Additional Context
> This issue appears to be affecting the entire Nile testnet, not just specific contracts or accounts.

I just tried deploy one Trc-20 smart contract using tron TronIDE on nile net, and it does success.  Did you select the correct compiler version as tron-doc mentioned **0.5.16**.

**Comment by marco1208marco** [comment]
![微信截图_20241202102800](https://github.com/user-attachments/assets/6836c00f-2257-4db8-9741-52cc49ad45ba)
现在连钱包都无法显示trx，你刚部署？是怎样做到的？我更新钱包就无法显示trx，想部署也部署不了~

**Comment by marco1208marco** [comment]
> 不知道你们的合约编译成功没有？可能是逻辑错误导致的。

应该不是，tronlink版本问题，更新后，测速才正常（旧版本一直显示无法测速），但无法显示trx，shasta测试网就显示trx，重新新建钱包也是不能显示trx测试币~

**Comment by DongDongSunny** [comment]
make sure the net is the same in transcan and wallet. Notice in your screenshot the warning there.
<img width="376" alt="Screenshot 2024-12-02 at 10 52 47 AM" src="https://github.com/user-attachments/assets/6448eb4e-3cc3-4c20-aece-f69b10a778c7">

**Comment by marco1208marco** [comment]
![微信截图_20241202113648](https://github.com/user-attachments/assets/a69f64ba-c2e6-4195-9376-8fbbb848b6a9)
还是无显示资产~~

**Comment by marco1208marco** [comment]
![微信截图_20241202114121](https://github.com/user-attachments/assets/0a2f6dcc-6b29-416b-a8d5-ca2137032e14)
联网了，还是无显示资产

**Comment by 317787106** [comment]
@marco1208marco Please connect to nile.tronscan.org using your tronlink wallet. It's ok like this:

<img width="1577" alt="image" src="https://github.com/user-attachments/assets/c4d1fe15-3914-4dd0-b1c8-a3dcd8b0f6b1">

**Comment by marco1208marco** [comment]
![微信截图_20241202122636](https://github.com/user-attachments/assets/b0b7c480-a91e-474f-bfc1-7e4983999d39)
不知道是啥原因，还是无显示资产~新创钱包也是，nile测试网就不显示资产~shasta却显示资产清单，尽管是零也是显示的，nile网却啥都不显示~

**Comment by laurenceja** [comment]
@marco1208marco Could you provide the account address？

**Comment by laurenceja** [comment]
@marco1208marco Can you try again to see if it works now?

**Comment by marco1208marco** [comment]
> @marco1208marco Can you try again to see if it works now?

已恢复正常了 ~ 可能读取记录吧~缓一下，2个小时后就出现了~可能是升级的nile问题吧~
谢谢大家热心的回复~
