### ISSUE TITLE
Does Tron have a plan to lower the fee of usdt transaction

### ISSUE THREAD

**Issue by S1ep** [tronprotocol/java-tron#6114]
It is a litter expensive now

**Comment by ferdinand026** [comment]
@S1ep Recently, a series of proposals have just come into effect to reduce transaction fees, such as reducing the unit price of energy and increasing the supply of energy: https://tronscan.org/#/proposals . If we want to transfer USDT for free, it is best to choose to stake to obtain energy.

**Comment by DongDongSunny** [comment]
Many users new to Tron don't know about Tron staking, Tron energy, how to use it for cheaper gas fees on Tron and also earn from it. Staking your TRX allows you to passively earn staking rewards for your help to secure the network. Check [here](https://x.com/GordianHogan/status/1854653558768935200) as someone shared.

**Comment by 317787106** [comment]
@S1ep The price has fluctuated a bit recently. We will evaluate the cost after the price fluctuation becomes smaller.

**Comment by simbadMarino** [comment]
I would suggest reducing the maximum increase factor, which was increased in [Proposal # 95](https://tronscan.io/#/proposal/95), to reduce the amount of energy paid from USDT transactions; there is a lot of payment processing platforms already getting hurt from it, especially now with TRX price increases.

**Comment by DongDongSunny** [comment]
@tomatoishealthy here tron has a all [Tran proposal here ](https://github.com/tronprotocol/tips/issues), quite a lot of them are resource model related, which will effect the transaction fee, so before any real changes make on Tron chain, tron will put proposal there to gather feedbacks and suggestions.

**Comment by CooperDepp** [comment]
@S1ep the issues in this repository mainly focus on the java-tron development related problems. It's recommended to discuss the fee related issues in the TIP repository, you may propose how to optimize the transactions fees by changing the network parameters. TRON community actually pays close attention to the fees, and there have been such discussions and proposals recently, and the fees seem to have reached a reasonable range.
