### ISSUE TITLE
How to get history internal_transaction data for a full node?

### ISSUE THREAD

**Issue by PikaZ76** [tronprotocol/java-tron#6119]
I deployed a Tron full node of my own with steps:

1. download Fullnode data snapshot from http://34.86.86.229/backup20241114/
2. run java-tron and use this downloaded snapshot data, but I just use the config as default which `saveInternalTx` was false
```
  saveInternalTx = false
```
the node is running as expected, but neither the transactions in the data snapshot nor the newly created transactions have the internal_transactions field from this api `/wallet/gettransactioninfobyid` according the [API Doc](https://developers.tron.network/reference/gettransactioninfobyid)
seems like there also have no `internal_transactions` in transactions which inside the data snapshot.

I update my node by redeploied it with setting `saveInternalTx = True`, so I can get avaiable `internal_transactions` data for transactions created after my redeployment. but still can't get `internal_transactions` for earlier transactions in history.

So, I’d like to know how to retrieve the internal_transactions for all historical data ?

**Comment by jwrct** [comment]
@PikaZ76 Please refer to the documentation (https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/#fullnode-data-snapshot) to obtain a data snapshot containing `internal_transactions`. Or you can try another approach: when is the earliest historical transaction you want to get for `internal_transactions`? It is recommended that you download the data snapshot before this time, and then set `saveInternalTx = True` to start the node.

**Comment by DongDongSunny** [comment]
@PikaZ76 according to jwrct's suggestion this http://35.247.128.170/ will provide data snapshot containing internal trans, or you turn your config true and resync the transactions with a lightweight data snapshot without internal trans.

**Comment by jwrct** [comment]
@PikaZ76 The 33rd API in gRPC API (https://tronprotocol.github.io/documentation-en/api/rpc/) should be what you need, right?

**Comment by jwrct** [comment]
> And by the way, I really wish to know where I can get the trace data (internal call stack on TVM) like `debug_traceBlockByHash` in Ethereums?

@PikaZ76 Tron currently does not have an interface similar to Ethereum's `debug_traceBlockByHash`. If the tron ​​node sets vm.vmTrace to true, the trace data will be output to a file in the `./vm_trace` directory.

**Comment by PikaZ76** [comment]
@jwrct so if I want to use`GetTransactionInfoById` or `GetTransactionInfoByBlockNum` [apis](https://github.com/tronprotocol/protocol/blob/release_v4.7.4/api/api.proto)  in json way like apis in`Full Node JSON-RPC API` means that I have to deploy a grpc-gateway connect with my fulll node?

**Comment by DongDongSunny** [comment]
@PikaZ76 Here we also do provide json-rpc support https://developers.tron.network/reference/eth_gettransactionbyhash

**Comment by PikaZ76** [comment]
> https://developers.tron.network/reference/eth_gettransactionbyhash

@DongDongSunny Yes bro, but there are no internal_transaction in those json-rpc api

**Comment by DongDongSunny** [comment]
@PikaZ76 ok, I think you have to use rpc for method GetTransactionInfoByBlockNum now, could refer my rpc example here https://github.com/DongDongSunny/tron-rpc-client, it will save your effort to write code

**Comment by PikaZ76** [comment]
> @PikaZ76 ok, I think you have to use rpc for method GetTransactionInfoByBlockNum now, could refer my rpc example here https://github.com/DongDongSunny/tron-rpc-client, it will save your effort to write code

thanks bro

**Comment by PikaZ76** [comment]
@DongDongSunny 哥们，怎么能私信一下？

**Comment by DongDongSunny** [comment]
@PikaZ76 then refer the network config here https://developers.tron.network/docs/networks#mainnet to connect to rpc grpc.trongrid.io:50051

**Comment by jwrct** [comment]
@PikaZ76 1. Yes, only contract transactions, one file per transaction. 2. Compression is not currently supported. 3. You can do whatever you want with these files. 4. No such data snapshot is currently provided.

**Comment by PikaZ76** [comment]
I think internal transactions is work for me in an appropriate way. I'll closed this and open another issue for history trace data.
Very appericiate @jwrct and @DongDongSunny
