### ISSUE TITLE
What is 'fastForward' configure used for? 

### ISSUE THREAD

**Issue by abn2357** [tronprotocol/java-tron#6120]
<img width="361" alt="截屏2024-12-11 18 05 13" src="https://github.com/user-attachments/assets/78366233-786a-423c-9e83-432a9f11ab43">

**Comment by jwrct** [comment]
@abn2357 Tron provides multiple types of nodes. `fastForward` is a node that focuses on synchronizing blocks, which is convenient for a subnet to quickly synchronize information.
