### ISSUE TITLE
How to get trace data of all history

### ISSUE THREAD

**Issue by PikaZ76** [tronprotocol/java-tron#6121]
I deploied node with enabled vm.vmTrace, it's work with trace data as {TxID}.json inside the ./vm_trace, but I  have some additional questions:

1. I notice that only latest transactions appears in the ./vm_trace after I enabled vmTrace, are there any way to get trace for all historial transactions or blocks? It's seems no trace in Data snapshot.
2. Is every single transaction have a trace json file inside this dir? or just Contract related transactions？
3. Are there any config in vm like vm.vmTrace to make those trace json file compressed? it's seems very storage-consuming on disk.
4. If tron node can't compress the json file, is that ok to compress them manully by my self and remove the origional json files from vm_trace? Will doing this affect the normal operation of the node?

**Comment by jwrct** [comment]
@PikaZ76 1. Yes, only contract transactions, one file per transaction. 2. Compression is not currently supported. 3. You can do whatever you want with these files. 4. No such data snapshot is currently provided.

**Comment by jwrct** [comment]
@PikaZ76 1. I'm sorry to tell you that no such data snapshot is currently provided. 2. Yes, only contract transactions, one file per transaction. 3. Compressed files are not supported yet. 4. You can do whatever you want with these files.

**Comment by PikaZ76** [comment]
@jwrct   lol, so there are no way to get history trace data? may be some official archive files or other api? any avaiable data source for those history trace?

**Comment by jwrct** [comment]
@PikaZ76 I'm sorry to tell you that there is currently no such official data provided, but you can generate this data yourself according to your own needs, which is a little more troublesome. Whether the official will provide these data snapshots in the future remains to be discussed. Again, sorry.

**Comment by PikaZ76** [comment]
@jwrct  I really appreciate your kind support!

**Comment by PikaZ76** [comment]
@jwrct if I deploy a Full Node with `vm.vmTrace enabled` and sync it from the very beginning (genesis block) without using a data snapshot, I can get all trace data from now back to the genesis block, right?

**Comment by jwrct** [comment]
@PikaZ76 Yes, you are right.

**Comment by vivian1912** [comment]
@PikaZ76 Thanks for your contribution to java-tron, this issue will be closed as I think this question has been answered. And please feel free to re-open it if you have any other questions about this issue, thanks.
