### ISSUE TITLE
When was the last time of sr node was replaced

### ISSUE THREAD

**Issue by GrothenDI** [tronprotocol/java-tron#6122]
and What is the approximate replacement frequency
<img width="815" alt="截屏2024-12-13 12 59 56" src="https://github.com/user-attachments/assets/33cb84ed-9754-40fc-9bb7-bad1b7d50aeb" />

**Comment by jwrct** [comment]
@GrothenDI The most recent SR node replacement occurred on May 26 this year. SRs will be re-elected every 6 hours based on the latest voting data.

**Comment by DongDongSunny** [comment]
@GrothenDI [here](https://tronprotocol.github.io/documentation-en/mechanism-algorithm/sr/#how-to-become-a-super-representative) will give you some explanation, [here](https://tronprotocol.github.io/documentation-zh/mechanism-algorithm/sr/#how-to-become-a-super-representative) is Chinese version.

**Comment by vivian1912** [comment]
@GrothenDI Thanks for your contribution to java-tron. This issue will be closed because I think your question has been answered. And please feel free to re-open it if you still have any questions, thanks.
