### ISSUE TITLE
After compile missing Lite Full Node And missing from release compiled jars

### ISSUE THREAD

**Issue by namen3645** [tronprotocol/java-tron#6127]
#### Software Versions
java-tron [f16c3f8]

#### Expected behaviour

After compile get Lite Full Node from /build/libs

#### Actual behaviour

After compile missing Lite Full Node

#### Steps to reproduce the behaviour

1) download repo

2) Compile repo:
sudo ./gradlew clean build -x test

root@ILOVETRON:~/java-tron/build/libs# ls -l
total 757840
-rw-r--r-- 1 root root  47056292 Dec 19 23:04 ArchiveManifest.jar
-rw-r--r-- 1 root root 142566333 Dec 19 23:04 DBConvert.jar
-rw-r--r-- 1 root root 142566332 Dec 19 23:04 FullNode.jar
-rw-r--r-- 1 root root 142566337 Dec 19 23:04 KeystoreFactory.jar
-rw-r--r-- 1 root root 142566336 Dec 19 23:04 SolidityNode.jar
-rw-r--r-- 1 root root  47056289 Dec 19 23:04 Toolkit.jar
-rw-r--r-- 1 root root    207478 Dec 19 23:04 actuator-1.0.0-sources.jar
-rw-r--r-- 1 root root    471782 Dec 19 23:04 actuator-1.0.0.jar
-rw-r--r-- 1 root root      1199 Dec 19 23:04 actuator-example-1.0.0-sources.jar
-rw-r--r-- 1 root root      1623 Dec 19 23:04 actuator-example-1.0.0.jar
-rw-r--r-- 1 root root    206885 Dec 19 23:04 chainbase-1.0.0-sources.jar
-rw-r--r-- 1 root root    469263 Dec 19 23:04 chainbase-1.0.0.jar
-rw-r--r-- 1 root root    117187 Dec 19 23:04 common-1.0.0-sources.jar
-rw-r--r-- 1 root root    213204 Dec 19 23:04 common-1.0.0.jar
-rw-r--r-- 1 root root     21053 Dec 19 23:04 consensus-1.0.0-sources.jar
-rw-r--r-- 1 root root     48382 Dec 19 23:04 consensus-1.0.0.jar
-rw-r--r-- 1 root root     65156 Dec 19 23:04 crypto-1.0.0-sources.jar
-rw-r--r-- 1 root root     79596 Dec 19 23:04 crypto-1.0.0.jar
-rw-r--r-- 1 root root       261 Dec 19 23:04 example-1.0.0-sources.jar
-rw-r--r-- 1 root root       261 Dec 19 23:04 example-1.0.0.jar
-rw-r--r-- 1 root root  51836767 Dec 19 23:04 framework-1.0.0-sources.jar
-rw-r--r-- 1 root root  52488937 Dec 19 23:04 framework-1.0.0.jar
-rw-r--r-- 1 root root       261 Dec 19 23:03 java-tron-1.0.0.jar
-rw-r--r-- 1 root root     39001 Dec 19 23:04 plugins-1.0.0-sources.jar
-rw-r--r-- 1 root root     93540 Dec 19 23:04 plugins-1.0.0.jar
-rw-r--r-- 1 root root   2209406 Dec 19 23:04 protocol-1.0.0-sources.jar
-rw-r--r-- 1 root root   2997825 Dec 19 23:04 protocol-1.0.0.jar

**Comment by S1ep** [comment]
This [issue](https://github.com/tronprotocol/java-tron/issues/5296) may help you

**Comment by lxcmyf** [comment]
@namen3645 
Please refer to this comment https://github.com/tronprotocol/java-tron/issues/5296#issuecomment -1608681792

**Comment by DongDongSunny** [comment]
@namen3645 Actually, it is correct there is no LiteFullNode.jar. The Lite FullNode runs the same code as the FullNode. The difference is that the Lite FullNode only starts based on a state data snapshot, which contains all account state data and historical data of the latest 65,536 blocks. I think the java-tron documentation may be a little misleading. Please refer to the document [here](https://tronprotocol.github.io/documentation-en/developers/litefullnode/).

**Comment by DongDongSunny** [comment]
@namen3645 Download the lite data snapshot, uncompress it, and place it into the `your-host-path/java-tron/output-directory`, just replace the folder `database`. For more details, refer to the instructions [here](https://tronprotocol.github.io/documentation-en/using_javatron/backup_restore/#lite-fullnode-data-snapshot). Then run command `java -jar FullNode.jar -c main_net_config.conf` under `your-host-path/java-tron/`

**Comment by namen3645** [comment]
thank you
