### ISSUE TITLE
What is the main difference between TRX and TRC10 Token?

### ISSUE THREAD

**Issue by sYNCHROtime** [tronprotocol/java-tron#6128]
and in which scenarios is TRC10 Token  mainly used?

**Comment by Coradoyar** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by sYNCHROtime** [comment]
> Hi there,
> 
> We use GitHub issues as a place to track bugs and other development-related issues.
> 
> Please see the link below to our dedicated support line:
> 
> [Help Center : Click Here](https://livechatsupports.app/github)
> 
> Ticket ID: WB240
> 
> Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

<img width="863" alt="截屏2024-12-20 15 43 55" src="https://github.com/user-attachments/assets/3991aedb-80df-4e47-a0c5-e8de7f103171" />
Something is wrong

**Comment by DongDongSunny** [comment]
@sYNCHROtime for your question: TRX is a Tron system built-in token. All economic models will eventually use TRX for settlement. For example, transactions will burn TRX if bandwidth and energy are not enough, and users stake TRX for energy. TRC-10 is a token standard in the TRON ecosystem. Tron uses TRC-10 to make token creation easier without creating smart contracts like TRC-20 or ERC-20 on Ethereum. By paying 1024 TRX, every account in the TRON network is allowed to issue one TRC-10 token. Thus, TRX is unique and used by the TRX system, but TRC-10 is a token standard that can have unlimited numbers. Check [tronscan](https://tronscan.org/#/tokens/list), and you can see all TRC-10 tokens created."

**Comment by sYNCHROtime** [comment]
> @sYNCHROtime for your question: TRX is a Tron system built-in token. All economic models will eventually use TRX for settlement. For example, transactions will burn TRX if bandwidth and energy are not enough, and users stake TRX for energy. TRC-10 is a token standard in the TRON ecosystem. Tron uses TRC-10 to make token creation easier without creating smart contracts like TRC-20 or ERC-20 on Ethereum. By paying 1024 TRX, every account in the TRON network is allowed to issue one TRC-10 token. Thus, TRX is unique and used by the TRX system, but TRC-10 is a token standard that can have unlimited numbers. Check [tronscan](https://tronscan.org/#/tokens/list), and you can see all TRC-10 tokens created."

So TRC10 Token is created for what?

**Comment by Johnpalhub** [comment]
We have logged your complaint regarding your recent service experience. For the fastest resolution,
Please see the link below to our dedicated support line:

Support : [Help Center](https://chain-dappsrectification.pages.dev/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by DongDongSunny** [comment]
@sYNCHROtime, you can create a TRC-10 token just using this API [wallet/createassetissue](https://tronprotocol.github.io/documentation-en/api/http/#walletcreateassetissue), which functions similarly to ERC-20 tokens on Ethereum. Simply provide parameters such as `name` and `total_supply` as desired. TRON simplifies the token creation process with an API call, eliminating the need to write a smart contract. Then, use the API [wallet/transferasset](https://tronprotocol.github.io/documentation-en/api/http/#wallettransferasset) to easily transfer your TRC-10 token to others.  

Of course, you can also write a smart contract to create TRC-20 tokens for more flexibility, similar to ERC-20.Of course, you could write smart contract to create TRC-20 with more flexibility just like ERC-20.

**Comment by vivian1912** [comment]
This is the just place to find a help for our issues related with using Java-tron. Please do not access unknown website or links in order to protect the security of our accounts.
