### ISSUE TITLE
[Web] Account Address different during registration and then after login

### ISSUE THREAD

**Issue by shymi80** [tronprotocol/java-tron#616]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

- Go to https://tronscan.org
- Click "Register/Log-in
- Go to "Register" tab
- Copy info provided in TextBoxes (Account Address will be my focus in further steps)
![image](https://user-images.githubusercontent.com/38183098/39618784-971006d4-4f85-11e8-978c-7ff272dacb7c.png)
- Tick all the checboxes
- Click "Create Account"
- Go to "Account tab"

2. What did you expect to see?
Address which is the same as the one which was shown during registration: 
![image](https://user-images.githubusercontent.com/38183098/39618784-971006d4-4f85-11e8-978c-7ff272dacb7c.png)

3. What did you see instead?
Different account address than the one during the registration (do not know which one is valid - i suspect the one in the Account page)
![image](https://user-images.githubusercontent.com/38183098/39618914-12e79344-4f86-11e8-9f2d-1bcbbb55075b.png)

**Comment by Rovak** [comment]
This has something to do with the recent change to remove the password field https://github.com/tronprotocol/wallet-web/commit/f8da009eb317a02c04de6262ba5b96cd042b61a8, i'll push a fix later today

**Comment by Rovak** [comment]
Fixed
