### ISSUE TITLE
Some Transactions have invalid Timestamp

### ISSUE THREAD

**Issue by nfleury** [tronprotocol/java-tron#621]
1. What did you do?

Use Grpc client to retrieve a block and list all its transactions

Very tricky to reproduce as it seems to be random, but here are examples of transactions with those strange timestamps on current testnet :

Blocks: 

- 38804 (1 tx with 23972-09-11 05:55:46.811)
- 38803 (1 tx with 23972-07-29 17:54:14.656)
- 38799 (1 tx with 23970-10-07 14:11:13.002)
... and many more

2. What did you expect to see?

Valid an coherent timestamps on all the transactions of a block

3. What did you see instead?

Some timestamps that are clearly not valid such as :  23972-09-11 05:55:46.811

**Comment by romzes13** [comment]
Did you divide by 1000? Here's what I get, the latest block.
![image](https://user-images.githubusercontent.com/13972438/39646440-7382f70c-4fa9-11e8-8922-dc565010aca1.png)

**Comment by nfleury** [comment]
The blocks timestamps looks all fine. The issue is on some transactions in some blocks ... 

Just looks all transactions of the blocks I have previously set as example they all contain multiple transactions with timestamp that are ok, but some of them have those strange timestamps ... not all blocks are concerned ...

**Comment by zhaohong** [comment]
@nfleury  we will filter the wrong timestamp and drop these trans.

**Comment by kookiekrak** [comment]
Ah whoops

**Comment by kookiekrak** [comment]
@renchenchang no timestamp validation on some transactions

**Comment by badazzyella30** [comment]
https://github.com/tronprotocol/java-tron/issues/621

**Comment by fanyangyang** [comment]
i send a transfer through https://tronscan.org,  and then query the transfer's detail, i got this below
``` json
{
    "ret": [
        {
            "contractRet": "SUCCESS"
        }
    ],
    "signature": [
        "b566fe1e192bf85ff19d7363a6c32f50eccfc3674c2fc0a78bf11b1fbb66e013721ef675f9e1f54857129874f39ff373878906463917887952fcfd61ff3c78c801"
    ],
    "txID": "97902a0a7f121c95a6163b9a6c3a5062fe1c461f1f52235a384db3eacea663ed",
    "raw_data": {
        "contract": [
            {
                "parameter": {
                    "value": {
                        "amount": 1000000,
                        "owner_address": "416194aed8dda9cf28f5e3efad2e5d116eab2f6149",
                        "to_address": "413dd65d1dfe365d945f080ff2f24de37da07db8bc"
                    },
                    "type_url": "type.googleapis.com/protocol.TransferContract"
                },
                "type": "TransferContract"
            }
        ],
        "ref_block_bytes": "725c",
        "ref_block_hash": "e3116256bd5c5066",
        "expiration": 1548667578000
    }
}
```
this transaction do not have  raw_data.timestamp.
can you tell me if the filed raw_data.timestamp is always be there for validation?
or just one filed raw_data.expiration is enough.
