### ISSUE TITLE
Build - java getters (.getAccountIndex(), etc) Full Node

### ISSUE THREAD

**Issue by ijkl000** [tronprotocol/java-tron#622]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

After building with gradle in intelliJ I try running FullNode.java but an error shows up leading to StoreAPI.java where it cannot find method getAccountIndex() amongst others, variable logger also not showing up.

2. What did you expect to see?

Running the FullNode

3. What did you see instead?

Error:(52, 51) java: cannot find symbol
  symbol:   method getAccountIndex()
  location: variable indexHelper of type org.tron.core.db.api.IndexHelper

Error:(58, 7) java: cannot find symbol
  symbol:   variable logger
  location: class org.tron.core.db.api.StoreAPI

......

**Comment by Yrp** [comment]
confirm the code is latest and try again.

**Comment by taihaofu** [comment]
I will close this issue for now. @ijkl000 Please reopen it if you have more questions.

Thanks.
