### ISSUE TITLE
Apache license violation/Missing reference to bitcoinj project

### ISSUE THREAD

**Issue by wongjustin99** [tronprotocol/java-tron#63]
Similar to #25: 

java-tron: https://github.com/tronprotocol/java-tron/blob/develop/src/main/java/org/tron/core/Coin.java
bitcoinj: https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/Coin.java

There's many more files from bitcoinj besides the example. All the unmodified pieces need attribution, and the license re-attached (it was stripped out of all the files).

**Comment by ac-opensource** [comment]
Provided a fix in this PR: https://github.com/tronprotocol/java-tron/pull/65

**Comment by jromero** [comment]
This should be closed as they already addressed these.

**Comment by ruchern** [comment]
Let's ping them. @tronfoundation
