### ISSUE TITLE
Asset/Token name is not unique and doesn't have any restrictions

### ISSUE THREAD

**Issue by nfleury** [tronprotocol/java-tron#635]
Please answer these questions before submitting your issue. Thanks!

Already talked to @zhaohong about this, but just wanted to leave an issue so that it can be tracked (didn't found existing issue about this)

1. What did you do?

- Created multiple tokens with the same name.
- Created a Token with very long names and with some special characters  like: '$#@!...'

If possible, provide a recipe for reproducing the error:

- Go to tronscan.org . Create a new token with a name that already exists. 
- Go to tronscan.org . Create a new token with a long and name with special characters 

2. What did you expect to see?

- Token names should be unique
- Token names should have some basic restrictions (max length, avoid special characters ...)

3. What did you see instead?

- Users can create tokens with the same name multiple time
- Token names doesn't have any limitation (uniqueness, lenght etc ...)

**Comment by zhaohong** [comment]
fix this later.
the same name because the space.

**Comment by Rovak** [comment]
Token names are now unique.

@zergweak @zhaohong https://github.com/tronprotocol/java-tron/blob/develop/src/main/java/org/tron/core/actuator/AssetIssueActuator.java#L153 should also check for unique `Abbreviation` for the `abbr` field https://github.com/tronprotocol/protocol/blob/master/core/Contract.proto#L86

**Comment by seanrobbins** [comment]
Per Rovak's comment from 28th May that token names are now unique, should this issue be closed?
