### ISSUE TITLE
[Bounty] Build fails after getting newest java-tron version

### ISSUE THREAD

**Issue by shymi80** [tronprotocol/java-tron#643]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

sudo apt-get update
sudo apt-get upgrade
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo git clone https://github.com/tronprotocol/java-tron.git
cd java-tron
sudo ./gradlew build

2. What did you expect to see?
Succesfull build

3. What did you see instead?

Build failed:
![image](https://user-images.githubusercontent.com/38183098/39666747-0461ef80-50a9-11e8-9017-84262ef0ccdb.png)

with following test failed:
![image](https://user-images.githubusercontent.com/38183098/39666751-101ce726-50a9-11e8-8305-9ba158ca1009.png)

**Comment by Mickey69** [comment]
I have exactly (100%) the same issues

**Comment by theweekendcoder** [comment]
Also I see you just joined 28 days ago do you know how to correctly fork the project and set up the remote upstream? 

If not delete what you cloned and restart following this guide on [forking](https://help.github.com/articles/fork-a-repo/) to make sure you have your forked project synced with the original. Pretty much follow the ReadMe step by step in full detail helped me in this situation you are having. I hope this helps.

**Comment by cbaker88** [comment]
Same issue here trying to build in IntelliJ on Windows 10, hoping someone here has a solution. 

[Failed message](https://imgur.com/a/y0uHM0c)

**Comment by taihaofu** [comment]
Hi @shymi80, the code works for me. Please make sure you pull the latest code. It seems you are failed on broadTest, my suggestion is check if you have an output-nodeImpleTest folder. Sometimes, things may go weird due to the unexpected uncleaned up testing folder remained in your project. Please let me know if it helps or not.

**Comment by bondibox** [comment]
> Also I see you just joined 28 days ago do you know how to correctly fork the project and set up the remote upstream?

Unless you are contributing to or changing the code base, I'm not sure I see the purpose of forking the repository.

**Comment by shymi80** [comment]
Thanks for all the answers. 

My intention is not to change anything in the code. I want just to run full node or witness node. 

I am following all the steps from instructions (readme from github, information from http://tron-wiki.readthedocs.io and related documents) but still getting some errors. 

The errors during build occur when I am cloning develop branch as well as when I am getting master branch (sudo git checkout -t origin/master).

Currently I am getting following errors:
- during building develop branch

org.tron.core.net.node.BroadTest > testConsumerAdvObjToFetch FAILED
    java.lang.AssertionError: expected:<null> but was:<BLOCK>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.tron.core.net.node.BroadTest.testConsumerAdvObjToFetch(BroadTest.java:128)

- during building master branch 

org.tron.core.net.node.BroadTest > testConsumerAdvObjToFetch FAILED
    java.lang.AssertionError: expected:<null> but was:<BLOCK>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.tron.core.net.node.BroadTest.testConsumerAdvObjToFetch(BroadTest.java:128)
		

org.tron.core.witness.WitnessControllerTest > testSlot FAILED
    java.lang.AssertionError: expected:<4> but was:<21>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.tron.core.witness.WitnessControllerTest.testSlot(WitnessControllerTest.java:50)

I am running builds on Ubuntu 16.04. Every build I am performing on clean tron repository (deleting the previous one and starting from getting rep by sudo git clone https://github.com/tronprotocol/java-tron.git)

**Comment by cryptoguyinza** [comment]
same problem on my side, downloaded last night and got build error.

Thanks.

**Comment by taihaofu** [comment]
@shymi80 I am trying to reproduce your problem.
For broadTest, seems I would get the same error message if I comment out Thread.sleep(1000)
So, please change 1000 to a larger number to see if it works or not.
<img width="719" alt="screen shot 2018-05-08 at 6 02 13 pm" src="https://user-images.githubusercontent.com/9706126/39751395-a8dc1c3c-52ea-11e8-89d2-8ef59beacbd6.png">
And can you try to debug it on your side? Check if you can get advObjToFetch and condition.getBlockId() properly. It will help narrow down the issue. Also you can try run just this single test itself, not in the whole list.

Thanks.

**Comment by zhaohong** [comment]
@taihaofu  please review this test case.

**Comment by shymi80** [comment]
@taihaofu  I am not using any dev tool to make the build. I am just trying to build the code from master branch on Ubuntu system following the steps from readme from github.

However I have found the file you mentioned and changed the sleep value and I am still getting the error.

I am attaching the file containing info from test report. Maybe this will help somehowe to solve this.
[testConsumerAdvObjToFetch_test.txt](https://github.com/tronprotocol/java-tron/files/1983609/testConsumerAdvObjToFetch_test.txt)

**Comment by taihaofu** [comment]
@shymi80 Seems you are using port 17889 which is conflict with the test. Could you change to another one?

**Comment by shymi80** [comment]
@taihaofu I have checked port 17889 with "sudo lsof | grep 17889" command and it seems that nothing else is using this port. Will come back to the subject later. Thanks for help and hints.

**Comment by Mickey69** [comment]
For me, ive double checked my installation, and have correctly commanded OS to installed all the correct modules, my port 17889 is not being used by any other app.
Only thing i can try is disabling AV & Firewall then start installation anew, quick test, then re-enable firewall, test again, then re en-enable AV, with a final test, and see if 1 of those two is causing the problem, If it returns a Positive, i should be able to then fix problem.

**Comment by taihaofu** [comment]
Hi all, please try the code on latest develop branch. If still get failure, please provide logs when you   execute ./gradlew build

Thanks.

**Comment by cryptoguyinza** [comment]
Hi

Tried now, build was fine for me. Worked. No errors

Thanks

**Comment by cryptoguyinza** [comment]
syncing still bad with errors.

**Comment by shymi80** [comment]
@taihaofu After building on current develop branch everything is fine and build finishess sucessfully with no error :) Thanks taihaofu. Good work :) 🥇 

Having this opporotunity I would like to ask one thing. 
Do you know on which  version are running the nodes from https://tronscan.org/#/network? I 
would like to use the same one.

**Comment by zhaohong** [comment]
@shymi80  you can use the latest code in the develop branch.

**Comment by Mickey69** [comment]
@taihaofu Thanks! That latest build works for me too. :)
