### ISSUE TITLE
Requesting test TRX fails in testnet.

### ISSUE THREAD

**Issue by shanadas** [tronprotocol/java-tron#650]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
From wallet web, I requested some test TRX

2. What did you expect to see?
Some test TRX credited in the account

3. What did you see instead?
Unknown error occurred (Screenshots below)
![image](https://user-images.githubusercontent.com/3648025/39689760-847e4824-51f5-11e8-9e70-a2bde75dbd00.png)
![image](https://user-images.githubusercontent.com/3648025/39689775-8aae3dee-51f5-11e8-9fe6-3d11f734ca93.png)

**Comment by bondibox** [comment]
Registering as Super Representative also fails.

**Comment by shymi80** [comment]
Asking for test TRX seems to work now. However Applying for delegate still is not possible.

**Comment by bondibox** [comment]
Also sending TRX feature not working currently.

**Comment by Rovak** [comment]
This has been fixed

**Comment by haidoan** [comment]
hi anyone, issue happen again, I tried to request TRX for testing from [https://test.tronscan.org/account](https://test.tronscan.org/account) but get this error, please help! thanks
<img width="917" alt="screen shot 2018-09-20 at 16 53 39" src="https://user-images.githubusercontent.com/7260527/45810837-d3218980-bcf5-11e8-8629-b660be2aa867.png">
