### ISSUE TITLE
Cant acces my tron wallet. The browser keeps refreshing on its log in page.

### ISSUE THREAD

**Issue by bonjovi3** [tronprotocol/java-tron#67]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I tried to click on the wallet button and it leads to the usual log in page.

2. What did you expect to see?
I expect to key in my usename and password. 

3. What did you see instead?
All it does is keep refreshing by itself on my browser and  I cant even key in my username and password. 

![capture](https://user-images.githubusercontent.com/35513454/35022358-8787f190-fb70-11e7-8298-51b703bfafef.JPG)

**Comment by good-stuey** [comment]
First, the login address is https://tron.network/newlogin.html

**Comment by bonjovi3** [comment]
when i key in https://tron.network/newlogin.html , it leads me to https://tron.network/login.html and keeps refreshing.

**Comment by good-stuey** [comment]
You try to clear the browser cache

**Comment by good-stuey** [comment]
are you ok

**Comment by bonjovi3** [comment]
tried to clear cache, cleared history, cleared everything. yet , the refreshing problem still occur.

**Comment by good-stuey** [comment]
You take a screenshot of me

**Comment by good-stuey** [comment]
You directly click on this link   https://tron.network/newlogin.html

**Comment by bonjovi3** [comment]
yup, i cleared my cache, i try clicking the address you have given, and it still drectly jumps to the  https://tron.network/login.html . :(

**Comment by bonjovi3** [comment]
i tried on firefox, chrome, even my safari browser. just goes to the https://tron.network/newlogin.html

**Comment by good-stuey** [comment]
your phone number

**Comment by good-stuey** [comment]
You first enter https://tron.network then enter log in

**Comment by bonjovi3** [comment]
please, someone from the tron team, need your help man. at least someone can tell me whats the problem? and is there anyone looking into this matter?

**Comment by bonjovi3** [comment]
this is what it is refreshing all the time......

![capture2](https://user-images.githubusercontent.com/35513454/35029641-d2abd922-fb96-11e7-9182-68e174661867.JPG)
![capture1](https://user-images.githubusercontent.com/35513454/35029648-d983a716-fb96-11e7-82f4-3efc2fadc384.JPG)

**Comment by bonjovi3** [comment]
hi guys,
just solved it. its my bad. The reason I found out is due the time setting on my pc. I accidentally changed it from 'pm' to 'am'. Thats why i could not log in. Now it has resolved. And i can continue supporting Justin!

**Comment by conglinduye** [comment]
@bonjovi3 Thank you for your attention and support.

**Comment by jingyi2811** [comment]
Programmer should not use client's pc date. Should use server's date. I guess new Date() is used somewhere

**Comment by Rovak** [comment]
Closing as this issue seems to be resolved
