### ISSUE TITLE
Apply for Delegate

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/java-tron#671]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Created account at Tronscan and applied for Delegate.
Created account at Tronscan, requested TRX, and applied for Delegate.

2. What did you expect to see?
Submit Success

3. What did you see instead?
Case 1 'An unknown error occurred'
Case 2 green submit button greys out, process hangs.

**Comment by Rovak** [comment]
The error message isn't really helpful right now but i suspect the issue might be that you didn't freeze any trx. Could you freeze some trx and try again?
