### ISSUE TITLE
Withdrawing issue tron.network wallet

### ISSUE THREAD

**Issue by potsy24** [tronprotocol/java-tron#68]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
When trying to withdraw my trx from the wallet it will send but gets resposited back in after 12 hours and i believe this time it has not come back as of yet.  Has happened 3 times in the past three days. I checked etherscan and there is no transaction data at all of the sent coins. I know this is not an issue of wallet addresses. And this is a issue from the tron lab wallet.

2. What did you expect to see?

Deposited from binance, tried to withdraw back to binance. Was exspecting no issues and not redirection of my trx 

I cannot get a hold of anyone for help and only have seen one person with this issue.

I would really like to have the situation resolved 

Thank you in advance for your help 

Anthony

**Comment by jdehgh1** [comment]
I’m having a related, albeit slightly different, issue. I’m clicking “confirm” to process the transfer back to Binance but the “confirm” button is not responding to my click. Is this a widespread issue? I’ve tried using four different browsers. Thanks.

**Comment by shodderRAN** [comment]
@jdehgh1 Saw this post and tried to withdraw, ended up with the same problem as you so I am guessing it is just a widespread issue at the moment since there was no problem with the withdraws before.

**Comment by Didier13690** [comment]
@shodderRAN @jdehgh1 I have the same issue. Did you be able to withdraw? I´m clicking "confirm" and nothing happens. it´s longer than one day they have this issue... I think It´s enough time to solve it out

**Comment by shodderRAN** [comment]
@Didier13690 No luck so far... If you find anything new please let us know 👍 Ill do the same

**Comment by potsy24** [comment]
I litterally started clicking confirm like a mad man untill it went through lol and it did....over a day later.....sorry i have no step by step....well...
Step 1 get more frustrated
Step 2 click the heck out of it
Step 3 worry
Step 4 wait nervously 
Step 5 see coins in other wallet
Step 6 hate tronlab wallet 

Lol best of luck.

**Comment by shodderRAN** [comment]
Gonna try and spam it with autoclick script

**Comment by asim247** [comment]
Hey Guys

I legit just transferred all my coins from binance into the Tron Wallet:

https://tron.network/ennewmine.html

I transferred 7000 coins now i cant withdraw them :( what can i do guys? there are no support options or nothing when i click confirm nothing happens.

please update if possible thanks.

**Comment by shodderRAN** [comment]
We're having the same issue I guess the best we can do is to just wait.

**Comment by Didier13690** [comment]
I could transfer my BTN few minutes ago. Try it noooooow!  haha

**Comment by asim247** [comment]
yeah that worked now they mustve fixed it. But i got scammed :'( 

Hey Everyone :'( 

MyEtherWallet got hacked and someone stole all my TRX :'( i had 6757 all together. 

How i think it happend? Well i seen this post about TRX Airdrop by Justin Sun on there website:

https://tronix.foundation/blog/airdrop/

I followed all the steps and i transferred all the trx i had from my binance account into myetherwallet i never knew this was going to be a scam :'( I just want to make other people wary before it happens to them :'(

MyEtherWallet account:

0x72c18C85E3a1cE87a077b9B22fED42fB974296b3

Hackers account:

0x545f5E5c54d8ac72AF1c7DE8c070387b73841A24 

This is what happened:

Transfers
2 total

Deposited my funds: 

2018-01-22 21:29:38	
Tx: 0x224a768e578d97f13a6be8d5d5cd9b5237f4c0935d665d8774cdef14bfd4ef74
From: 0x540fb834ba63dec251c927610e69d7f9db4e0529
To: 0x72c18c85e3a1ce87a077b9b22fed42fb974296b3
Tronix	6,757.00 TRX
$ 473.33

Hacker took my funds:

2018-01-22 21:39:34	
Tx: 0x724952a1be9e11d341eb603a3811fae87e3fd51825f7cd9f8402febdf67b94f7
From: 0x72c18c85e3a1ce87a077b9b22fed42fb974296b3
To: 0x545f5e5c54d8ac72af1c7de8c070387b73841a24
Tronix	-6,757.00 TRX
$ 473.33

I dont know what to do or where to go i invested my hard earned cash into this but its all gone and i looked at the hackers account and it looks like im not the only one hes hacked and he has something like 2.3 million worth of coins.

If anyone is feeling kind and generous to help me out i would really really appreciatie that and i will take a note of whoever helps me i will help them back in the future and thats my promise! :'(

My XRP address is: 0x69057c12e092d9af45871b3b8b8cf4843f00c360
My Bitcoin Address is: 12njwRj9tmkEzfSnr5vCQrvBy2WHMnx6R1
My Etherium Adress is: 0x69057c12e092d9af45871b3b8b8cf4843f00c360
My Litecoin Address is: LZm8iXBuLz1o9pNZKrSzrWZWQKDCoEb7Hr

I mean as a community if anyone can help me that would be so amazing honestly thats only if someone can help me :'( People please be wary there are so many scams going on i just wanted to bring attention to people that this is a scam and please dont fall for it. I hope everyone understands whats happened and can help me out or tell me what i can do to get my funds back :'(

Im sorry for my long message if anyone can help me please comment below :'(

I'm also not asking anyone for donations for my fuck i i deeply from the bottom of my heart want to let people know about this scam :'(

Thank you for youre time.

**Comment by Phayd3** [comment]
Dude, are you serious?! Github is not the place to be asking for this kind of stuff!!!

You are just clogging up the page and distracting those working on the project from actual improvements.

**Comment by asim247** [comment]
Okay im really sorry i have edited it but is it okay if i let people know or not? I'm really sorry again :'(

**Comment by jdehgh1** [comment]
It appears to be working now. I’m able to click “confirm” and transfer the TRX. I’ll post a final update when the TRX makes it way back to Binance.

**Comment by jdehgh1** [comment]
Transfer took about 10 minutes.

**Comment by shodderRAN** [comment]
Great @jdehgh1 thx for the update.

**Comment by shodderRAN** [comment]
Apparently there is a withdrawal limit for some reason. If someone knows it is a intentional 24hr limit?

**Comment by xiechang33** [comment]
@shodderRAN Now every natural day can only withdrawals once .

**Comment by Rovak** [comment]
Closing this issue as it seems to be resolved, with the limitation that you can only withdraw once a day. I don't know if this limitation is still in effect.
