### ISSUE TITLE
Block not sync in lastest develop (p2p.version = 64)

### ISSUE THREAD

**Issue by KenjiroAI** [tronprotocol/java-tron#685]
1. What did you do?
- I have build successful without any error
- I want to sync with public testnet (same network as tronscan.org)
- I have been syncing over a day

2. What did you expect to see?
- Full sync with lastest block that show in tronscan

3. What did you see instead?
- My lastest block is 2
- I think the problem is related to block 3 (it shows repeatedly)

```
13:23:18.049 ERROR [pool-7-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:693) We get a bad block, reason is validate schedule exception
 the block isBlockCapsule
[ hash=0000000000000003d4be783c09f17975103497eb7a5096a5f23c89b28074931a
number=3
parentId=0000000000000002963b890bf22d268ad8a7d76a57c9da825a769f178e13e4e1
witness address=a00a9309758508413039e4bc5a3d113f3ecc55031d
generated by myself=false
generate time=2018-05-09 11:59:42.0
merkle root=aba0aa7a73da0addd77b6da04cc77ed651106d88e64c52a1b28124915c4e5b84
txs size=1
tx: {0:TransactionCapsule
[ hash=ed3a2239a359e6d30135cfd3e95c79f02a9ee4e24d5d2edeae1ae713a7f3264d
contract list:{ [0] type: TransferContract
from address=[B@6a361e21
to address=[B@2366ca84
transfer amount=1000000000000
sign=Gw/BCElDzNi9wU0bW/tBr4plMlRBdfbwT4wBDfF23Ext7pS7EuwGT9sL0lM6GXsOLyhYXplHzllYSoC8zTzzlrk=
}
]
}]
```

- Status from console show me
```
MyHeadBlockNum: 2
advObjToSpread: 0
advObjToFetch: 0
advObjWeRequested: 0
unSyncNum: 0
blockWaitToProc: 1285
blockJustReceived: 0
syncBlockIdWeRequested: 0
badAdvObj: 1
```

What did I do wrong? How do I fix this?

**Comment by shymi80** [comment]
I have the same symptoms in the newest develop branch (#680 )- synch is stuck in the same place.

However I have noticed that version #677  of develop branch works OK - you just have to change the p2p.Version in config from 63 to 64 and synch will be ok. That is the version on which I am running now.

**Comment by shymi80** [comment]
I think I have figured it out and know how to solve that. 

Perform following steps (I have done those before build):
- ./src/main/resources/
- open config.conf
- in witnesses section you will see that the default ones have votes set to 0
- set those votes from 105 to 95 respectively (as it was in some of the previous configs)
- run node and enjoy :)

It seems that in one of the previous commits someone zeroed those votes but the code was not ready for that. I hope that someone will correct that.

**Comment by KenjiroAI** [comment]
Wow, you saved my day.
I confirm that the problem is from the config file.

Thank you
