### ISSUE TITLE
Tried to register for the tron network and it says my email and or username is already registered, which is not possible because i havent registered yet.

### ISSUE THREAD

**Issue by Blpz21** [tronprotocol/java-tron#687]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

**Comment by taihaofu** [comment]
@Blpz21, Can you provide the login email and username you use to register? 

Thanks.

**Comment by cccyyc** [comment]
Can you provide the login email and username you use to register ? @Blpz21 
We will check it.

**Comment by Blpz21** [comment]
williamelopez21@yahoo.com was the email and username i  was trying to register was Blpz21

**Comment by cccyyc** [comment]
Both email and username are not registered,you can check the network status and try it again.

**Comment by cccyyc** [comment]
Both email and username are not registered,you can check the network
status and try it again.
