### ISSUE TITLE
Can you please update the readme putting in more instructions how to run the gradle project from IDEA

### ISSUE THREAD

**Issue by ajayt6** [tronprotocol/java-tron#7]
Kafka is up and running.
imported project in IDEA and built it using gradle.
Do not know how to run 
Can you please update the README with more instructions regarding this

**Comment by sasaxie** [comment]
![run](https://github.com/tronprotocol/wiki/blob/master/images/show-how/run.gif)

**Comment by sasaxie** [comment]
Thanks for your suggestion.  We will be updated soon.

![run](https://user-images.githubusercontent.com/11765472/34399109-4489f520-ebbf-11e7-96d6-4711bb77ad2a.gif)

**Comment by ajayt6** [comment]
Wow thanks!
I just figured it out independently and was coming to close off this issue. Anyway updating readme will be helpful to others.
