### ISSUE TITLE
"No such message" Error and dropping blocks

### ISSUE THREAD

**Issue by cryptoguyinza** [tronprotocol/java-tron#702]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Node was in sync and making blocks. Then stopped making blocks

2. What did you expect to see?
To carry on making blocks

3. What did you see instead?
Stopped making blocks and gave error. Restart node doesn't help.

![image](https://user-images.githubusercontent.com/37824699/39872792-59fc6c36-5469-11e8-9b71-1b04d9bad041.png)

**Comment by cryptoguyinza** [comment]
did an update and this  error is gone with latest update on development branch.

**Comment by taihaofu** [comment]
Close it for now. Feel free to reopen it if you have any other updates.

Thanks.
