### ISSUE TITLE
Unable to sign in my tron wallet

### ISSUE THREAD

**Issue by bonjovi3** [tronprotocol/java-tron#706]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I sign in as usual. Put in my username and password. Then it will prompt a sliding picture to verify. Once I complete the step. It says Mail or Password is wrong. Which is not the case. 

2. What did you expect to see?
Expect to log in.

3. What did you see instead?

Mail and Password is wrong. 
![capture123](https://user-images.githubusercontent.com/35513454/39911227-4219a86c-552d-11e8-83ec-9992e0432f8c.JPG)

**Comment by conglinduye** [comment]
You can click ‘forgot password’ to change your password ， then sign in the tron.newwork

**Comment by techno420** [comment]
When i go to forget password, the link im the email i get brings me to the tron.network mainpage with the url from the email. No field to change the password

**Comment by conglinduye** [comment]
Sorry, tron.network has just been upgraded. You can now change your password.
