### ISSUE TITLE
Transactions don't have any associated result yet

### ISSUE THREAD

**Issue by nfleury** [tronprotocol/java-tron#711]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- Create a transaction

2. What did you expect to see?

- The transaction should have a result associated once processed

3. What did you see instead?

- No result associated to the transaction

**Comment by nfleury** [comment]
Looks like none of the transaction on current testnet has a return result. I guess the way of creating the transaction doesn't matter 

Might be due to this in TransactionCapsule:

`public void setResult(TransactionResultCapsule transactionResultCapsule) {
   //this.getInstance().toBuilder(). (transactionResultCapsule.getInstance());
 }`

**Comment by ithinker1991** [comment]
You can try again, that commented code has been uncommented.

**Comment by nfleury** [comment]
@ithinker1991, I still can't see any return result on transactions

**Comment by ithinker1991** [comment]
It's gRPC cli for broadcastTransaction API
public boolean broadcastTransaction(Transaction signaturedTransaction) {
    GrpcAPI.Return response = blockingStub.broadcastTransaction(signaturedTransaction);
    if (!response.getResult()) {
      String hash = Sha256Hash.of(signaturedTransaction.getRawData().toByteArray()).toString();
      System.err.println("hash:" + hash + ",code:" + response.getCode() + ",msg:" + response.getMessage());
    }
    return response.getResult();
  }

**Comment by nfleury** [comment]
I was actually thinking that the return results were stored. I expected that retrieving a block with gRPC and the associated transaction would give me the return result list associated with it, but that information doesn't seems to be stored.

My understanding now is that those return results in transactions are intended only for when we broadcasting a transaction, am I right ?

Seems that the only way to check the status of a transaction right now is to check if it is part of solidity node.

But something is really bothering me, or maybe I do not understand it correctly. With current implementation, if I am right, a transaction can be only OK (available on solidity node) or KO (not available on solidity node) when checking it afterward. 

If something went wrong when broadcasting a transaction shouldn't this information (the status code) be stored ? Because right now the only way to check the status of a transaction is right after submitting it (on broadcast).

And even if the transaction was ok, we don't have the information of the fees (I know that there is no fees for most of Tx but some has a fee) associated to it. 

Seems to me that a ledger should keep track of these data.

**Comment by nfleury** [comment]
I am closing this : TransactionInfo was implemented to solve this
