### ISSUE TITLE
running full node but not producing any blocks on the network

### ISSUE THREAD

**Issue by iamjonjon** [tronprotocol/java-tron#715]
Please answer these questions before submitting your issue. Thanks!

1. I set up a node via google cloud and managed to successfully run the node in Pwitness.

2. I expected to see blocks being produced on Tronscan.org. What am I doing wrong? Please advise

3. What did you see instead?

**Comment by shymi80** [comment]
On what place have your node been on tronscan.org in network section. Only first 15 are allowed to produce blocks in testnet. In mainet this will be increased to 27.

**Comment by iamjonjon** [comment]
Thanks i really appreciate your feedback! Your awesome ! Hopefully Ille get in the top 15 soon !

**Comment by shymi80** [comment]
No problem. Glad to help. ;)

**Comment by taihaofu** [comment]
@iamjonjon Seems you are all set. I will close it now. Please reopen it if you have more question on this topic.

Thanks.
