### ISSUE TITLE
debug.tronlab.com Issue

### ISSUE THREAD

**Issue by herosdroid** [tronprotocol/java-tron#72]
HI @sasaxie ,

Since thread was in wrong place I reopen in correct place.

I created account and deposited to debug.tronlab.com
Send went thru to debug account. 
Debug account does not register that it received deposit. 
Outcome: Cannot withdrawal out of debug wallet. 

I understand you guys are working to fix issue - however, I will leave this open for communication for questions etc.. until issue is resolved.

Thank you Tron team for being awesome. 
-C

**Comment by sasaxie** [comment]
ok

**Comment by herosdroid** [comment]
@sasaxie Issue fixed and resolved. Thank you to you and the Tron Team.
