### ISSUE TITLE
[Question] API Protocol

### ISSUE THREAD

**Issue by KenjiroAI** [tronprotocol/java-tron#721]
**1. What did you do?**
- I want to find block hash of current block via gRPC (/wallet/getblockbynum)
- I want to find transaction hash for each transaction included in block data (same above endpoint)
- I have seen (/wallet/gettransactionbyid) but I don't know where to get transaction id
- Is /walletsolidity/* endpoint not implemented?

**2. What did you expect to see?**
- Parent block hash and current block hash are included in block data
- Transaction hash for each transaction

**3. What did you see instead?**
- Only parent hash here
- No any field related to transaction hash or id in block data (only ref for block; ref_block_hash)
- No method found response for all endpoint from /walletsolidity/*

**Comment by taihaofu** [comment]
Hi,
>I want to find block hash of current block via gRPC (/wallet/getblockbynum)
I want to find transaction hash for each transaction included in block data (same above endpoint)

Currently we don't support block hash and transaction hash via /wallet/getblockbynum. But you can get block hash and transaction hash yourself.
Please refer to these functions:
BlockCapsule.java:

         public BlockId getBlockId() {
            if (blockId.equals(Sha256Hash.ZERO_HASH)) {
              blockId = new BlockId(Sha256Hash.of(this.block.getBlockHeader().toByteArray()), getNum());
            }
            return blockId;
          }

TransactionCapsule.java:

          public Sha256Hash getTransactionId() {
            return Sha256Hash.of(this.transaction.getRawData().toByteArray());
          }


>I have seen (/wallet/gettransactionbyid) but I don't know where to get transaction id

You have to get the transaction id from the one who send you transaction.


> Is /walletsolidity/* endpoint not implemented?

Not quiet sure if I understand the question, since you can find it here:

        /src/main/java/org/tron/core/WalletSolidity.java

**Comment by 2tvenom** [comment]
Now i try receive transaction by GetTransactionById. In received data BlockNum is `0`! How generate block hash or block number by transaction data? By `ref_block_num` and `ref_block_hash` this is impossible. Release `Odyssey-v1.1`

**Comment by KenjiroAI** [comment]
@taihaofu Thank you for your help.

I have successful to get block hash by using SHA256 in block header and transaction by using SHA256 in transaction raw data bytes

For anyone who interested in calculate block hash and transaction hash in Node.js, this code below is solution.
```javascript
const crypto = require('crypto');
const caller = require('grpc-caller');

const { WalletClient } = require('./src/protocol/api/api_grpc_pb');
const { EmptyMessage } = require('./src/protocol/api/api_pb');

const rpc = caller('127.0.0.1:50051', WalletClient);

const lastBlock = await rpc.getNowBlock(new EmptyMessage());
const lastBlockNumber = lastBlock.getBlockHeader().getRawData().getNumber();

// Block hash
const lastBlockHash = crypto.createHash('sha256')
  .update(
    Buffer(lastBlock.getBlockHeader().getRawData().serializeBinary())
  )
  .digest('hex');

for (const transaction of lastBlock.getTransactionsList()) {
  const transactionBinary = transaction.serializeBinary();

  // Transaction hash
  const txHash = crypto.createHash('sha256')
    .update(Buffer(transactionBinary))
    .digest('hex');
}
```
