### ISSUE TITLE
Any Chance for Tron on Node.js?

### ISSUE THREAD

**Issue by netcinematics** [tronprotocol/java-tron#73]
Hello, I am content creator. WebGL.

Tron looks fantastic for Node. 

Lots of mini visual apps going out to the web.

What is required for Tron to run on Node.js?

Thx.

**Comment by razorsyntax** [comment]
Most likely an API.

**Comment by Nkmol** [comment]
https://developers.caffeina.com/chiccocoin-learn-what-is-a-blockchain-by-creating-one-in-nodejs-12929a89208b maybe this article can be helpful as a start.

**Comment by Rovak** [comment]
A node.js wallet api is being worked on in the https://github.com/tronprotocol/node-wallet-api repository. There aren't any plans right now to develop a full working node in node.js
