### ISSUE TITLE
Attempting to Transfer TRX from Tron Website to Binance

### ISSUE THREAD

**Issue by jdehgh1** [tronprotocol/java-tron#75]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Attempting to send TRX from Tron Network site to Binance. However, the “confirm” button will not responsd to my click.

2. What did you expect to see?
Expected to see the transfer process begin after clicking “confirm.”

3. What did you see instead?
Nothing results when I click “confirm.” Triednysing four separate browsers.

**Comment by shodderRAN** [comment]
Same problem

**Comment by KJackson50** [comment]
I see you tried four separate browsers, I was going to say did you try "Compatibility View" on IE?

**Comment by jdehgh1** [comment]
It’s working now. Guess they were able to fix the issue. Thanks for reaching out KJackson50.
