### ISSUE TITLE
Configuring Private Test Net

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/java-tron#751]
`What did you do?`
I have built a test net using ports 18818 and 50021. To start everything up, I launched 3 instances of wallet-cli and registered 3 wallets, then used those addresses for my config file witnesses and genesis blocks, and included the private keys in the config files for each of the 3 witnesses. Witness0 has the added flag needSyncCheck = false

These nodes were launched with the following commands:

>activenode1 ./gradlew run   
activenode2 ./gradlew run    
seednode1 ./gradlew run   	 
trustnode  ./gradlew run	 
solidity ./gradlew run -PmainClass=org.tron.program.SolidityNode   	 
witness0  ./gradlew run -Pwitness=true
witness1  ./gradlew run -Pwitness=true
witness2  ./gradlew run -Pwitness=true

My config.conf has these relevant changes:

>node {	
  trustNode = "trustnode:50021"

>  listen.port = 18818
  rpc.port = 50021

>  active = [
    "activenode1:18818",
    "activenode2:18818"
  ]

>  p2p {
    version = 299
  }
}

> seed.node = {
  ip.list = [
    "seednode1:18818"
  ]
}

wallet-cli config files point to trustnode.

Run wallet-cli 'listnodes' grpc, ---> 7 nodes besides trustnode (expected)
Run wallet-cli 'listwitnesses' grpc ---> 3 witnesses in order (expected)

> witness 0 :::
[
address: 27kzKoRJLx2AArNc7rBW2s89GSXyTPUzy1e
voteCount: 98
pubKey: 
url: http://www.communitynode.org
totalProduced: 0
totalMissed: 0
latestBlockNum: 0
latestSlotNum: 0
isJobs: true
]
etc

`What did you expect to see?`  
Witnesses syncd and taking turns producing blocks. Balances in wallets whose addresses appear in genesis block assets.

`What did you see instead?`  
Wallet balances are zero  
The witnesses are not syncd. 

Witness 1&2 say 'Try Produce Block - Not sync'  
Witness0 gives these errors:

23:30:48.000 INFO  [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:143) Try Produce Block
23:30:48.005 INFO  [Thread-5] [o.t.c.w.WitnessController](WitnessController.java:202) scheduledWitness:a0bb04a1657d6dda20ba30d4c06529fef211d2cbfb, currentSlot:508837816
23:30:48.007 INFO  [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:201) It's not my turn, ScheduledWitness[a0bb04a1657d6dda20ba30d4c06529fef211d2cbfb],slot[508837816],abSlot[508837816],
23:30:51.000 INFO  [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:143) Try Produce Block
23:30:51.003 INFO  [Thread-5] [o.t.c.w.WitnessController](WitnessController.java:202) scheduledWitness:a06685aadf5fc1b519adb3d12afa79fa2be95842ea, currentSlot:508837817
23:30:51.081 INFO  [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:201) It's not my turn, ScheduledWitness[a06685aadf5fc1b519adb3d12afa79fa2be95842ea],slot[508837817],abSlot[508837817],
23:30:54.000 INFO  [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:143) Try Produce Block
23:30:54.006 INFO  [Thread-5] [o.t.c.w.WitnessController](WitnessController.java:202) scheduledWitness:a0f057b8bcb379ddaa689d8139b51c2d6292fb957c, currentSlot:508837818
23:30:54.008 INFO  [Thread-5] [o.t.c.d.Manager](Manager.java:933) postponedTrxCount[0],TrxLeft[0]
23:30:54.052 INFO  [Thread-5] [o.t.c.d.Manager](Manager.java:740) update head, num = 1
23:30:54.053 INFO  [Thread-5] [o.t.c.d.DynamicPropertiesStore](DynamicPropertiesStore.java:552) update latest block header id = 0000000000000001bb34aee6cffcfc264b15727f00c5065d4f4160cb918e1c9e
23:30:54.054 INFO  [Thread-5] [o.t.c.d.DynamicPropertiesStore](DynamicPropertiesStore.java:544) update latest block header number = 1
23:30:54.056 INFO  [Thread-5] [o.t.c.d.DynamicPropertiesStore](DynamicPropertiesStore.java:536) update latest block header timestamp = 1526513427000
23:30:54.058 ERROR [Thread-5] [o.t.c.s.WitnessService](WitnessService.java:85) unknown exception happened in witness loop
java.lang.IllegalArgumentException: The key argument cannot be null
        at org.fusesource.leveldbjni.internal.NativeDB.checkArgNotNull(NativeDB.java:209)
        at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:290)
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:85)
        at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:77)
        at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.getData(LevelDbDataSourceImpl.java:175)
        at org.tron.core.db.AccountStore.getSun(AccountStore.java:93)
        at org.tron.core.db.Manager.updateSignedWitness(Manager.java:1092)
        at org.tron.core.db.Manager.processBlock(Manager.java:978)
        at org.tron.core.db.Manager.applyBlock(Manager.java:560)
        at org.tron.core.db.Manager.pushBlock(Manager.java:708)
        at org.tron.core.db.Manager.generateBlock(Manager.java:939)
        at org.tron.core.services.WitnessService.generateBlock(WitnessService.java:251)
        at org.tron.core.services.WitnessService.tryProduceBlock(WitnessService.java:218)
        at org.tron.core.services.WitnessService.blockProductionLoop(WitnessService.java:94)
        at org.tron.core.services.WitnessService.lambda$new$0(WitnessService.java:81)
        at java.lang.Thread.run(Thread.java:748)

**Comment by zhaohong** [comment]
./gradlew run -Pwitness        not  "./gradlew run -Pwitness=true"
