### ISSUE TITLE
Fork scala-tron to tronprotocol organisation

### ISSUE THREAD

**Issue by Rovak** [tronprotocol/java-tron#76]
The [scala-tron](https://github.com/Rovak/scala-tron) project has been started a few weeks ago with the goal to provide a working tronprotocol in the [Scala language](https://www.scala-lang.org/). This week we nearly implemented most of the features that exist in the java-tron project.

The scala-tron project plans on being fully compatible with the java-tron project by adding support for Apache Gossip, Kafka, CopyCat and sharing the same protobuf models.

**Would the tron team consider forking the scala-tron project to the tronprotocol organisation so it can receive more exposure and attract developers who prefer Scala over Java?**

If scala-tron is being forked to the tronprotocol organisation then development can resume in the forked repository. I can be added as collaborator to the repository so i can further manage the project.

I would also like to volunteer as collaborator to the java-tron project to triage issues and answer technical questions. For example there are quite a few issues which should have been closed already or require more feedback.

**Comment by zhaohong** [comment]
hi Rovak ,
I really appreciate your great work and  your proposal is very good. 
Now we are still improving the tron protocal and  the design of existing code,  so it's a little early to do this.
I think we can start this after we finished the code refactoring.

**Comment by Rovak** [comment]
Hi Zhao, thanks for your response! I understand that this might not be the right time, lets wait till things stabilize. In the meantime i'll try to keep up with the progress you guys are making.

My offer still stands to help out with the moderation of Github issues.

Keep up the good work, looking forward to the beta release of Exodus!

**Comment by JusticeForMikeBrown** [comment]
Please moderate Github.  There needs to be a place where people can ask about hardware wallets but this isn't the venue.  Maybe refer them to Telegram.

**Comment by Rovak** [comment]
@JusticeForMikeBrown what does this issue/question have to do with hardware wallets?
