### ISSUE TITLE
master and develop branch unable to sync past 7207 blocks

### ISSUE THREAD

**Issue by metjm** [tronprotocol/java-tron#760]
1. What did you do?
-clone the repo, compile it using `gradlew build`
-run the node using `java -jar java-tron.jar -c config.conf`
the config file was not modified

2. What did you expect to see?
a full sync up to the block count i can see on tronscan.org

3. What did you see instead?
every time the nodes reached 7207 blocks, it stops verifying blocks. The node keeps running and connected to other nodes, but it doesn't get past 7200 blocks. Restarts do not help, and I ran nodes on google cloud platform, hetzner.com, and on my local network. All of them get stuck around 7200 blocks  
This was tested with the master branch, and the develop branch a couple times over the last week or so.

**Comment by bondibox** [comment]
That has been a constant struggle for me since test net started. I can not tell if it's on my end or the network's. I'm thinking it has to do with something I read a long time back that it would take a witness node 24 hours to sync so maybe they put up these hurdles every 23 hours or whatever so no one can get the full chain in one pop. I used to go back through the commit history looking for a 'better' version but I think that's a waste of time.

**Comment by zhaohong** [comment]
please use  master branch, if still have problem, let me know.

**Comment by jerkyrs** [comment]
how is testnet being managed in terms of versions? i commonly see 

different p2p version, peer->45, me->65

I was on latest in develop branch, but how does this work if one node is on older tag or not on same tip of master when they compile?

The last tag is 1.0.6.3 on May 11th , Master is updated today

I notice Tronscan.org many functions are currently not operating as expected.

**Comment by jerkyrs** [comment]
If i pull out MASTER and compile connect to network clean config.conf i get the following error

`
14:06:02.955 INFO  [nioEventLoopGroup-3-2] [HandshakeHandler](HandshakeHandler.java:121) Peer /80.29.83.2:36665 different p2p version, peer->46, me->64
14:06:02.955 INFO  [nioEventLoopGroup-3-1] [HandshakeHandler](HandshakeHandler.java:121) Peer /23.121.134.201:56172 different p2p version, peer->45, me->64
14:06:02.955 INFO  [nioEventLoopGroup-3-1] [Channel](Channel.java:149) Send disconnect to /23.121.134.201:56172, reason:INCOMPATIBLE_PROTOCOL
14:06:02.955 INFO  [nioEventLoopGroup-3-2] [Channel](Channel.java:149) Send disconnect to /80.29.83.2:36665, reason:INCOMPATIBLE_PROTOCOL`

When connecting to other nodes

**Comment by mglfnc85** [comment]
Is it possible tronscan.org is having "down" problems due to  traffic? however after 40 hours this is my screenshot. What do you think? Same problem?
![tronfm](https://user-images.githubusercontent.com/39280042/40237136-d1553460-5aaf-11e8-85ca-16daa0e503f6.JPG)

**Comment by metjm** [comment]
@mglfnc85 not sure if thats the same problem. 

After the network reset 30 minutes ago my node is synced now (only 1700 blocks right now, so not sure if that means its fixed). We'll see if that stays that way and if syncing from 0 is possible in a couple days.

@zhaohong  I used the master branch in most attempts, using the develop one was just a last ditch attempt which didn't help. Either way, I'll keep my main node running now in the hopes that it stays synced and run another one in a day or two to make sure i can sync from scratch if thats ever needed.

**Comment by bondibox** [comment]
I'm afraid if you're at block 1700 you've got bigger problems because the current block is 607. See my issue #580 which I keep coming back to.

**Comment by metjm** [comment]
yeah, it got reset a couple times today

**Comment by jerkyrs** [comment]
@mglfnc85 seems to me you are seeing the same as #777 , this version is specified in config.conf , are nodes capable of being on different P2P versions , seems to me if they are they fail on that P2P communication with Incompatible Protocol.

Really someone from TRON team should specify what version of code the Testnet should be running on, do they have a plan around how they update on mainnet versions and what repercussions there are from running multiple versions, my pull of Master today is not the same as someones from yesterday, we should really be using TAGS.

Has the TESTNET suffered a FORK ? I now see Tronscan.org back online with 37 NODES

**Comment by mglfnc85** [comment]
Now it seems to be ok! You need to reset everything and rebuild from master. If you look on config.conf version now is 67. Now is going very fast.

**Comment by mglfnc85** [comment]
a lot of bad blocks now, but it is working, I hope...
![tronfm1](https://user-images.githubusercontent.com/39280042/40242153-1a52843a-5abd-11e8-88c2-2e54c94808d2.JPG)

**Comment by jerkyrs** [comment]
![selection_999 432](https://user-images.githubusercontent.com/10046115/40242276-1c77980c-5ab5-11e8-89a2-d10a423e7c8a.png)

**Comment by mglfnc85** [comment]
...and?

**Comment by jerkyrs** [comment]
well i was on version 64 which was master 2 hours ago..

**Comment by bondibox** [comment]
You're also on block 88783 :-/

**Comment by jerkyrs** [comment]
Ya latest pull of master they commented out that other witness on its own little solo blockchain expedition. Cleared database and was on the new sequence again

**Comment by metjm** [comment]
so, update after a week: The node still isn't syncing from zero. The only one that synced successfully for me, was one I ran minutes after the network was reset the last time. Every other node I set up now gets stuck at 91 blocks. I am using the master branch with default settings.

**Comment by zhaohong** [comment]
@metjm  sill not work?

**Comment by wubin12** [comment]
sync problems  has been solved in the latest code. but now, if your clock is not synchronized, block verification may fail, this phenomenon will still exist

**Comment by jerkyrs** [comment]
@wubin12 what latest code out of master or a tag? Can we agree on tags, network should be notified to what version we should all run. Master is different from day to day unless only a tagged release is generated from tip of master when ever a merge from develop occurs.

For example latest tag is 1.1? 1.0.6.3 or 3.1?

**Comment by metjm** [comment]
Can confirm that the current master branch synced from scratch within minutes. Thanks guys

**Comment by metjm** [comment]
And it seems the bug is back. 1022511 is the block my nodes get stuck on now. Tried twice, both default settings and compiled from scratch. @wubin12

**Comment by jerkyrs** [comment]
@metjm I think network is forked on purpose by tron team. Look at the block height of the nodes and block height of super reps. A SR is a node but there is not one node anywhere near the same block height reported by SR on tronscan.org.

My bet is they are testing these 27 nodes for throughput as block height is high  after only being reset the other day , my perception is community nodes are not really stable enough but this is probably down to code maturity , server configuration  and network stability between nodes.
