### ISSUE TITLE
restart superNode,the tron Process can not start

### ISSUE THREAD

**Issue by laxpio** [tronprotocol/java-tron#768]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
a.) kill -15(kill -9) the tron process
b.) start tron process ag

2. What did you expect to see?
the tron process start succ.

3. What did you see instead?
a.) the tron process can not start all work thread,listen port...
b.) used a high io util, all is write io
the log as :
08:50:45.222 INFO  [main] [o.t.p.FullNode](FullNode.java:21) Full node running.
08:50:45.866 INFO  [main] [o.t.c.c.a.Args](Args.java:443) Bind address wasn't set, Punching to identify it...
08:50:45.922 INFO  [main] [o.t.c.c.a.Args](Args.java:447) UDP local bound to: 10.104.83.141
08:50:45.923 INFO  [main] [o.t.c.c.a.Args](Args.java:462) External IP wasn't set, using checkip.amazonaws.com to identify it...
08:50:46.518 INFO  [main] [o.t.c.c.a.Args](Args.java:475) External address identified: 123.207.6.164
08:50:46.658 INFO  [main] [o.s.c.a.AnnotationConfigApplicationContext](AbstractApplicationContext.java:573) Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@409bf450: startup date [Fri May 18 08:50:46 CST 2018]; root of context hierarchy
08:50:47.551 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring

**Comment by zhaohong** [comment]
do you  use (-9) ?
