### ISSUE TITLE
Bad blocks without sync

### ISSUE THREAD

**Issue by mglfnc85** [tronprotocol/java-tron#782]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Witness node on

2. What did you expect to see?
Normal sync. 

3. What did you see instead?
A lot of "bad blocks". It seems it cant sync.

**Comment by ithinker1991** [comment]
May you give me your logs? I will check it

**Comment by wubin12** [comment]
Bad blocks can cause disconnection, block sync problem was solved in the latest code
