### ISSUE TITLE
The usage method used across classes should be replaced by toString method

### ISSUE THREAD

**Issue by jingyi2811** [tronprotocol/java-tron#79]
This is a suggestion to remove boilerplate code.

Usage method is used to print message. 
public abstract void usage(); 
is used across the projects and This should be removed.

Should override toString() method instead.
So to print the message, System.out.println(Obj) is enough.

Also, consider using String.join. Java 8 added a new static method to java.lang.String which offers a slightly better alternative:

For example

String s = String.join(
    System.getProperty("line.separator"),
    "First line.",
    "Second line.",
    "The rest.",
    "And the last!"
);

**Comment by xiechang33** [comment]
@jingyi2811 OK.Thanks for your advice and attention.

**Comment by Rovak** [comment]
Closing this issue as this is mostly personal preference, feel free to make a pull request with your suggested changes.
