### ISSUE TITLE
WARN BUG: any private key you enter is linked to a wallet

### ISSUE THREAD

**Issue by mglfnc85** [tronprotocol/java-tron#792]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I invented a casual private key with the right lenght (64) and it is linked to a wallet.

2. What did you expect to see?
If you create a casual private key you coludn't be linked to any wallet.

3. What did you see instead?
I found that any private key you enter is linked to a wallet. It seems that it needs only the right length. Try with
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
or
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
for example.

**Comment by Rovak** [comment]
please move this to https://github.com/tronscan/tronscan-frontend/issues

**Comment by mglfnc85** [comment]
ok
