### ISSUE TITLE
Add Multi-Factor Authentication for User Login in TRON website

### ISSUE THREAD

**Issue by davendersingh76** [tronprotocol/java-tron#80]
1. What did you do?
After I registered at https://tron.network/enindex.html, I logged in.

2. What did you expect to see?
I expected to see good security controls (for example: multi-factor authentication) in place for login, and TRX wallet deposits and withdrawals.

3. What did you see instead?
The login experience was way too simple with not enough security in place. In today's times, this will be a major issue for on-boarding and retaining users. For TRX wallet deposits and withdrawals, we absolutely need to do much better with security to minimize hacking, etc. Better security will lead to better adoption globally.

**Comment by shodderRAN** [comment]
Great suggestion @davendersingh76 
+1

**Comment by styk-tv** [comment]
+1

**Comment by zhaohong** [comment]
@davendersingh76  Nice, we'll take your suggestion.

**Comment by travek** [comment]
+1

**Comment by styk-tv** [comment]
since we're on improvements:

there should be a separate repo for website so issues don't mix with protocol

there should be a ticket queue/dispatch so wallet/support is not mixed wirh website issues like layout

**Comment by JusticeForMikeBrown** [comment]
These types of questions I think should be posted on Telegram.  That's the usual way that developers interact with community.  Github isn't the place to post these types of questions as they have nothing to do with the code in this repository.

**Comment by corya0687** [comment]
+1
