### ISSUE TITLE
currently unable to build java-tron with JDK 8

### ISSUE THREAD

**Issue by javatanu** [tronprotocol/java-tron#802]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
1.Installing java8 showing version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
2.then clone java-tron from github
3.then checkout branch master
4.pull project from master branch
5.try to run ./gradlew run

2. What did you expect to see?

Building Successfully

3. What did you see instead?
89% build then no result found.Sometime got an error that build is failure.Try to use ./gradlew clean then ./gradlew build but build is not finishing

**Comment by bondibox** [comment]
If you are using Ubuntu this is a reported problem but one which no one is taking responsibility for. Yes, it stalls at Test number 72 with 26 failed tests. I have been going back and forth with the gradle devs who are more interested in bickering about the syntax of my wording than in actually investigating the problem. My guess is there are 300 libraries that gradle imports and many of them are gettting updated every few days. Sometimes the updates are incompatible with the java-tron build.

**Comment by kaankozan** [comment]
which system should I use 
You are using ubuntu @bondibox

**Comment by bondibox** [comment]
kaankozan I'm not using anything until someone figures out what the problem is with Ubuntu. If builds fine on Mac os if you're dying to get it running.

**Comment by javatanu** [comment]
I am using ubuntu 16.04 LTS

**Comment by javatanu** [comment]
I am following the below steps:

1. install JDK 1.8(oracle jdk 8)
2.using OS Ubuntu 16.04 LTS
3.then in the terminal clone the project

git clone https://github.com/tronprotocol/java-tron.git
4.

cd java-tron

5.

git checkout -t origin/master
6.

./gradlew build

the build result is attached here..after that build gets stop at 89%

**Comment by javatanu** [comment]
![screenshot from 2018-05-22 11-49-11](https://user-images.githubusercontent.com/39491556/40345284-32f3e974-5db6-11e8-82e1-1acd1ff60af3.png)

**Comment by kaankozan** [comment]
Close comment pls @bondibox say it #788
