### ISSUE TITLE
Tron process doing nothing but use high cpu and always in doing GC

### ISSUE THREAD

**Issue by laxpio** [tronprotocol/java-tron#803]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
run tron process as Super Representative.

2. What did you expect to see?
sync block,and try to Produce Block

3. What did you see instead?
the process doing nothing but used high cpu 200% cpu
the mem used 33.9% MEM;
the java process is always in doing GC
S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
  0.00   0.00  99.99  99.95  96.28  92.81  11934  100.174  7717 15572.772 15672.947
  0.00   0.00  99.99  99.95  96.28  92.81  11934  100.174  7717 15572.772 15672.947

**Comment by huzhenyuan** [comment]
The ECDSA library we used is com.madgag.spongycastle.
It will create quite a lot BigInteger object during verify transaction signature, and we can't cache them.

We will optimize the library in future.

**Comment by zhaohong** [comment]
@laxpio  what's your machine type.

**Comment by laxpio** [comment]
i do isolation,assign 2 cpu（Intel(R) Xeon(R) CPU E5-26xx v3） 4G mem for tron；
Expand to 6 cpu 16G；does not reappear it.
