### ISSUE TITLE
idea build错误 

### ISSUE THREAD

**Issue by wuliqi** [tronprotocol/java-tron#806]
C:\java-tron-develop\src\main\java\org\tron\core\db\api\index\AbstractIndex.java:109: 错误: 不兼容的类型: 无法推断类型变量 F,T#1
            .filter(Iterables.transform(resultSet, AbstractIndex.this::getObject), Objects::nonNull)
                   ^
    (参数不匹配; 方法引用无效
      对于getObject(? super WrappedByteArray), 找不到合适的方法
          方法 AbstractIndex.getObject(byte[])不适用
            (参数不匹配; Object无法转换为byte[])
          方法 AbstractIndex.getObject(WrappedByteArray)不适用
            (参数不匹配; Object无法转换为WrappedByteArray))
  其中, F,T#1,T#2是类型变量:
    F扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#1扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#2扩展已在类 AbstractIndex中声明的Object
C:\java-tron-develop\src\main\java\org\tron\core\db\api\index\AbstractIndex.java:122: 错误: 不兼容的类型: 无法推断类型变量 F,T#1
            .filter(Iterables.transform(resultSet, AbstractIndex.this::getObject), Objects::nonNull)
                   ^
    (参数不匹配; 方法引用无效
      对于getObject(? super WrappedByteArray), 找不到合适的方法
          方法 AbstractIndex.getObject(byte[])不适用
            (参数不匹配; Object无法转换为byte[])
          方法 AbstractIndex.getObject(WrappedByteArray)不适用
            (参数不匹配; Object无法转换为WrappedByteArray))
  其中, F,T#1,T#2是类型变量:
    F扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#1扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#2扩展已在类 AbstractIndex中声明的Object
C:\java-tron-develop\src\main\java\org\tron\core\db\api\index\AbstractIndex.java:131: 错误: 不兼容的类型: 无法推断类型变量 F,T#1
        .filter(Iterables.transform(index, AbstractIndex.this::getObject), Objects::nonNull)
               ^
    (参数不匹配; 方法引用无效
      对于getObject(? super WrappedByteArray), 找不到合适的方法
          方法 AbstractIndex.getObject(byte[])不适用
            (参数不匹配; Object无法转换为byte[])
          方法 AbstractIndex.getObject(WrappedByteArray)不适用
            (参数不匹配; Object无法转换为WrappedByteArray))
  其中, F,T#1,T#2是类型变量:
    F扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#1扩展已在方法 <F,T#1>transform(Iterable<F>,Function<? super F,? extends T#1>)中声明的Object
    T#2扩展已在类 AbstractIndex中声明的Object
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
3 个错误
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
4 actionable tasks: 4 executed
Compilation failed; see the compiler error output for details.
15:23:08: Task execution finished 'build'.

**Comment by Yrp** [comment]
jdk version？

**Comment by wuliqi** [comment]
jdk1.8.0_171

**Comment by bondibox** [comment]
Ubuntu 16.04?

**Comment by wuliqi** [comment]
idea community 2018.1  开发环境

**Comment by wuliqi** [comment]
我是根据节点搭建文档用idea来build
https://github.com/tronprotocol/Documentation/blob/master/中文文档/波场协议/如何建立节点.md

**Comment by Yrp** [comment]
Pls run the command：```./gradlew clean build``` (if you compile it under Linux/Mac) or ```gradlew.bat clean build```(if you compile it under Windows),and try it again.

**Comment by bondibox** [comment]
Problem Solved
https://github.com/tronprotocol/java-tron/issues/788
Use a 2 core CPU or wait for a fix.
