### ISSUE TITLE
output-directory location

### ISSUE THREAD

**Issue by pynki** [tronprotocol/java-tron#808]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
running `java -jar ./somePath/to/the/java-tron.jar -c ./some/path/config.conf`

2. What did you expect to see?
expect `output-directory` to be created in the folder ` ./somePath/to/the/`

3. What did you see instead?
`output-directory` is created in `./` and not `./somePath/to/the/`

**Comment by Yrp** [comment]
you need ```cd ./somePath/to/the/```, then run ```java -jar java-tron.jar -c config.conf```

**Comment by pynki** [comment]
I know how to prevent this behavior.  That's not the problem.

But is it behavior that brings any advantages? It should either be configurable via the `config.conf` or have a fixed path relative to the `java-tron.jar`.  Just drop the folder where ever the jar was called from seems chaotic. 

And btw. the `java-tron.jar` should check if it has write access to the folder it tries to create the `output-directory` in and gracefully exit if not instead running into the exceptions.

**Comment by zhaohong** [comment]
@pynki  hi, we will add new configuration for db location.

**Comment by pynki** [comment]
@zhaohong while on it remember to check if the access rights are OK for the java-tron to run before you try to read/write the database/index folders.

**Comment by zhaohong** [comment]
https://github.com/tronprotocol/java-tron/pull/839

**Comment by wind4869** [comment]
@pynki Hi, we think it's intuitive to put `output-directory` just in the path where you run `jar jar ...` command, rather than in the path where the jar file put. But we add detailed configurations for each database, including path and levelDB options.
