### ISSUE TITLE
Can you source code analysis help me!

### ISSUE THREAD

**Issue by wkk13171473832** [tronprotocol/java-tron#818]
There is no source code analysis. It's hard to understand. Can you write an introduction?  Thanks

**Comment by zhaohong** [comment]
if you have any question ,   you can join  our development slack.

**Comment by iiimoon** [comment]
@zhaohong can you send me development slack invite, I also want to join.

**Comment by zhaohong** [comment]
the link
https://join.slack.com/t/tronfoundation/shared_invite/enQtMzAzNzg4NTI4NDM3LTAyZGQzMzEzMjNkNDU0ZjNkNTA4OTYyNTA5YWZmYjE3MTEyOWZhNzljNzQwODM3NDQ0OWRiMTIyMDhlYzgyOGQ

this link is also in the readme doc of java-tron.

**Comment by iiimoon** [comment]
tried the link but it's not active 
------------
This invite link is no longer active.
If you have an @tronlab.com email address, you can still create an account.

If not, please check with the person who shared the invite link with you to ask for an invitation.

-----------------

**Comment by kookiekrak** [comment]
@iiimoon Hi, please email me at tian@tron.network for a slack invite!
