### ISSUE TITLE
remove documentation from readme.md

### ISSUE THREAD

**Issue by styk-tv** [tronprotocol/java-tron#85]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
as a developer i want to have a solid documentation

2. What did you expect to see?
i expect to see complete documentation at http://wiki.tron.network

3. What did you see instead?
need to just leave header and 1st paragraph, remove everything below and point people to site above instead

**Comment by styk-tv** [comment]
@sasaxie can you add me to collaborators here so I can sort this out? without creating too many PR's?

**Comment by jingyi2811** [comment]
I volunteer to draw simple UML diagram for TRON.

**Comment by styk-tv** [comment]
@jingyi2811 would be cool to get simple UseCase with actors and services: wallet, node(s) and one or two users interacting.

**Comment by xiechang33** [comment]
@jingyi2811 Thanks for your attention.

**Comment by sasaxie** [comment]
@styk-tv We will update README.md, thank you very much.

**Comment by jingyi2811** [comment]
I plan to read the whole project and then write documentation on it.

**Comment by xiechang33** [comment]
@jingyi2811 The phase of the Tron is rapid development.There may be many changes in structure.  Thanks to your attention and please continue to pay attention the Tron.

**Comment by jingyi2811** [comment]
Okay.

**Comment by Rovak** [comment]
I've limited the documentation of the readme in this project to building and running the code (#312). I'll make sure that all other documentation is being moved to the wiki project.
