### ISSUE TITLE
[Help] Tapos check error

### ISSUE THREAD

**Issue by KenjiroAI** [tronprotocol/java-tron#857]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I want to create new transaction in Node with below code
```javascript
const crypto = require('crypto');
const EC = require('elliptic').ec;
const bs58check = require('bs58check');
const protobufAny = require('google-protobuf/google/protobuf/any_pb');

const { WalletClient } = require('./src/protocol/api/api_grpc_pb');
const { TransferContract } = require('./src/protocol/core/Contract_pb');
const { Transaction } = require('./src/protocol/core/Tron_pb');

const transferContract = new TransferContract();
transferContract.setOwnerAddress(
  Uint8Array.from(
    bs58check.decode('27THRv5MqadxEi5iuuk6WZXcqWtWNcvMKNW')
  )
);
transferContract.setToAddress(
  Uint8Array.from(
    bs58check.decode('27d3byPxZXKQWfXX7sJvemJJuv5M65F3vjS')
  )
);
transferContract.setAmount(30 * 1000000);

const parameters = new protobufAny.Any();
parameters.pack(transferContract.serializeBinary(), 'protocol.TransferContract');

const contract = new Transaction.Contract();
contract.setType(Transaction.Contract.ContractType.TRANSFERCONTRACT);
contract.setParameter(parameters);

const transactionRaw = new Transaction.raw();
transactionRaw.addContract(contract);
transactionRaw.setTimestamp(Date.now() * 1000000);

const transaction = new Transaction();
transaction.setRawData(transactionRaw);

const transactionRawBin = transactionRaw.serializeBinary();
const transactionHash = crypto.createHash('sha256')
  .update(transactionRawBin)
  .digest('hex');

const privKey = Buffer('8F3C8AF64D8C65BBACC8426DDC67D66F46CA910720CB9BDDA6043A40C29475F3', 'hex');

const ec = new EC('secp256k1');
const key = ec.keyFromPrivate(privKey);
const signature = key.sign(transactionHash);

const sig = signature.r.toString('hex') + signature.s.toString('hex') + Buffer([signature.recoveryParam]).toString('hex');
transaction.addSignature(new Uint8Array(Buffer(sig, 'hex')));

const result = await rpc.broadcastTransaction(tx);
console.log(result.toObject());
```

2. What did you expect to see?
Transaction broadcast and transaction included in block

3. What did you see instead?
Transaction not included in block and return tapos error
`{ result: false, code: 6, message: 'VGFwb3MgY2hlY2sgZXJyb3I=' }`

Base64 -> UTF8
`VGFwb3MgY2hlY2sgZXJyb3I= -> Tapos check error`

**Comment by zhaohong** [comment]
@renchenchang

**Comment by olenheim** [comment]
You must  set a refBlockHash in your transaction. this hash should be one of  recent 65535 block's.

**Comment by Ampakinetic** [comment]
I'm getting this same error in the https://tronscan.org/#/account wallet when I try to send some test net coins to a wallet - is this a known problem?

**Comment by KenjiroAI** [comment]
@olenheim Thank you for you help.

I have successfully broadcast transaction to network by set refBlockHash and refBlockBytes in transaction.

```javascript
const crypto = require('crypto');
const caller = require('grpc-caller');

const { WalletClient } = require('./src/protocol/api/api_grpc_pb');
const { EmptyMessage } = require('./src/protocol/api/api_pb');

const rpc = caller('127.0.0.1:50051', WalletClient);

const lastBlock = await rpc.getNowBlock(new EmptyMessage());
const lastBlockNumber = lastBlock.getBlockHeader().getRawData().getNumber();
const lastBlockHash = crypto.createHash('sha256')
  .update(
    Buffer(lastBlock.getBlockHeader().getRawData().serializeBinary())
  )
  .digest('hex');

const refBlockHash = Buffer.from(lastBlockHash, 'hex').slice(8, 16).toString('base64');
const refBlockBytes = Buffer.from((lastBlockNumber).toString(16), 'hex').slice(0, 2).toString('base64');

```

**Comment by SummerJC** [comment]
Excause me. can u share your code to me.I have same problem. but my code is diffreent with yours.

**Comment by RachitGod** [comment]
Hi @KrakenAI ,
I am facing the same issue, can you please share your final payload you are sending to broadcast which got rid of this error?
Thanks in advance

**Comment by SummerJC** [comment]
你好，你的邮件我已经收到！谢谢

**Comment by pengten** [comment]
> You must set a refBlockHash in your transaction. this hash should be one of recent 65535 block's.

Is this mean that broadcast transaction will be failed if refBlockHash less than recent 65535 block?

**Comment by hitlxy** [comment]
> > You must set a refBlockHash in your transaction. this hash should be one of recent 65535 block's.
> 
> Is this mean that broadcast transaction will be failed if refBlockHash less than recent 65535 block?

If you reference a block that is generated before recent 65535 block, the transaction will be failed. I will suggest to use the latest solidified block as the reference block to ensure the transaction cannot failed because of TAPOS error.

**Comment by pengten** [comment]
> If you reference a block that is generated before recent 65535 block, the transaction will be failed. I will suggest to use the latest solidified block as the reference block to ensure the transaction cannot failed because of TAPOS error.

I get it, thanks for your answer :)
