### ISSUE TITLE
How to join slack group?

### ISSUE THREAD

**Issue by KenjiroAI** [tronprotocol/java-tron#868]
**1. What did you do?**
I want to join slack group to ask some question.

**2. What did you expect to see?**
I see Slack link in README, but invite link is no longer active
`https://tronfoundation.slack.com/join/shared_invite/enQtMzAzNzg4NTI4NDM3LTAyZGQzMzEzMjNkNDU0ZjNkNTA4OTYyNTA5YWZmYjE3MTEyOWZhNzljNzQwODM3NDQ0OWRiMTIyMDhlYzgyOGQ`

**3. What did you see instead?**
Please update invite link in README.

**Comment by zhaohong** [comment]
@HaoqiZhao

**Comment by kookiekrak** [comment]
My email is also on the Readme now :)

**Comment by KenjiroAI** [comment]
Thank you
