### ISSUE TITLE
[Question] Bandwidth consumption

### ISSUE THREAD

**Issue by KenjiroAI** [tronprotocol/java-tron#869]
**1. I was wondering about what happened. How does it work?**

In Tron wiki, it have reference some information about bandwidth consumption.

`All contracts consume bandwidth, including transfer, migration of asset, voting, freezing balance, etc. Inquiries do not consume bandwidth while for every contract about 100,000 bandwidths is consumed.`

From the above sentence it means that the transfer contract will spend 100,000 bandwidth.

I have creating the new account and no bandwidth at all, but why I can create transfer contract without any error about insufficient bandwidth.

After trying to create a transaction a few times (about 2-3 transaction), I have faced with the insufficient bandwidth (result code: 4, high freq error) [sometime return code: 20, other error].

**2. Can anyone explain more information about this paragraph?**

`If a new operation exceeds a given amount of time (10s) from the last contract, if does not consume any bandwidth.`

**3. What is free_net_usage in account data?**
There are new fields in account data, but I can't find the document about it.
```
int64 free_net_usage = 19;
map<string, int64> free_asset_net_usage = 20;
int64 latest_consume_free_time = 22;
```

**Comment by zhaohong** [comment]
seem the doc is a little old.
