### ISSUE TITLE
Many problems with login after my first registraion on Tron site

### ISSUE THREAD

**Issue by Magnolia25** [tronprotocol/java-tron#87]
On January 15th I correctly registered my user account on Tron site and I was able to login only for a few times in that same day. Then, unitl now, I wasn't able anymore to login (the system said me multiple times that the e-mail address or the password were uncorrect). Now I had to register me again with the same identical credentials of the first registration to have a correct access. It would therefore seem that my first registration was canceled. How is that possible?

**Comment by xiechang33** [comment]
I registered my user account and tested it. There is no similar problem.Do you still have this phenomenon?

**Comment by Magnolia25** [comment]
I tried few minutes ago and now it works. In the past three days after my comment, however, didn't work anymore when I tried to access. I hope that now it will work correctly in a constant way. Thanks for your reply.

**Comment by Rovak** [comment]
Closing as the problem seems to be resolved, feel free to reopen if the problem persists
