### ISSUE TITLE
Can't get transaction by GetTransactionById

### ISSUE THREAD

**Issue by KenjiroAI** [tronprotocol/java-tron#870]
**1. What did you do?**
I want to get transaction by using getTransactionById method via gRPC from full node and no result return.

For example, I want to get this transaction 
(https://tronscan.org/#/transaction/4cf062d8a2eb8961a9b72c792fe61928d7ca1be7a5ccaecd2e53a545e1068b27)

I have been trying to set `value` as
- Base64 from hex hash: `TPBi2KLriWGptyx5L+YZKNfKG+elzK7NLlOlReEGiyc=`
- Raw hex hash: `4cf062d8a2eb8961a9b72c792fe61928d7ca1be7a5ccaecd2e53a545e1068b27`
- Raw uppercase hex hash: `4CF062D8A2EB8961A9B72C792FE61928D7CA1BE7A5CCAECD2E53A545E1068B27`

```javascript
const caller = require('grpc-caller');

const { WalletClient } = require('./src/protocol/api/api_grpc_pb');
const { BytesMessage } = require('./src/protocol/api/api_pb');

const txId = new BytesMessage();
txId.setValue(
  Buffer('4cf062d8a2eb8961a9b72c792fe61928d7ca1be7a5ccaecd2e53a545e1068b27', 'hex').toString('base64')
);

const tx = await rpc.getTransactionById(txId);
console.log(tx.toObject());
```

**2. What did you expect to see?**
Transaction with corresponding hash returned

**3. What did you see instead?**
No any transaction returned
```
{ rawData: undefined, signatureList: [], retList: [] }
```

**Comment by danciuc** [comment]
There doesn't seem to be any transaction with hash
`4cf062d8a2eb8961a9b72c792fe61928d7ca1be7a5ccaecd2e53a545e1068b27` 
on mainnet.
