### ISSUE TITLE
Events about new blocks and transactions

### ISSUE THREAD

**Issue by 2tvenom** [tronprotocol/java-tron#877]
How receive events about new blocks? I implement tron node protocol, made handshake and response to PING, but not receive new block or transactions. I don't want `fetch` or `sync` blocks, just receive new blocks. This can do tron node protocol? 
Thank you

**Comment by olenheim** [comment]
If you don't sync blocks, your data would not be same with the other nodes' data, you couldn't check a new block or transaction's validity.  If you only want know a node's event about new blocks you can use GRPC to get.

**Comment by olenheim** [comment]
yes. If you don't want to run a FullNode to sync data, it's the only way to get events. because  other nodes only broadcast data to that they think it is synchronous with them.  If you want a listener interface in java-tron. it's another issue.
