### ISSUE TITLE
Add eclipse support in the gradle file

### ISSUE THREAD

**Issue by pborgen** [tronprotocol/java-tron#879]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I ran the following command "gradlew eclipse"

2. What did you expect to see?
I expected that the eclipse metadata files would get created so i could open the java-tron project in eclipse

3. What did you see instead?
the gradle file does not apply the eclipse plugin so this functionality is not supported

**Comment by zhaohong** [comment]
thanks
but this pr break the build.
https://github.com/tronprotocol/java-tron/pull/880 .

**Comment by zhaohong** [comment]
It's not your reason,  we will fix this later.
