### ISSUE TITLE
git checkout failed 

### ISSUE THREAD

**Issue by macleanliu** [tronprotocol/java-tron#889]
root@localhost:~# git clone https://github.com/tronprotocol/java-tron.git
Cloning into 'java-tron'...
remote: Counting objects: 51413, done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 51413 (delta 75), reused 198 (delta 44), pack-reused 51138
Receiving objects: 100% (51413/51413), 7.86 MiB | 2.61 MiB/s, done.
Resolving deltas: 100% (23541/23541), done.
Checking connectivity... done.

root@localhost:~# git checkout -t origin/master
fatal: Cannot update paths and switch to branch 'master' at the same time.
Did you intend to checkout 'origin/master' which can not be resolved as commit?

**Comment by jerkyrs** [comment]
@macleanliu did you change into directory *java-tron* using  "cd java-tron*

**Comment by pborgen** [comment]
The checkout worked. Must be user error

**Comment by kookiekrak** [comment]
@macleanliu 

As @jerkyrs said, when you `git clone`, it'll create a new directory `java-tron`.

You'll need to `cd java-tron` before running the `git checkout -t origin/master` command.

Hope that helps solve the issue 👍

**Comment by macleanliu** [comment]
then you should update the document:
master branch: more stable than develop. In the shell command, type:
git clone https://github.com/tronprotocol/java-tron.git
git checkout -t origin/master

**Comment by zhaohong** [comment]
@macleanliu thanks!
