### ISSUE TITLE
TRON wallet integration with Trezor, Nano Ledger, etc.

### ISSUE THREAD

**Issue by davendersingh76** [tronprotocol/java-tron#90]
I highly recommend that the TRON team pursue direct integration with hardware wallets (TREZOR, etc). This is not an issue; rather, a suggestion. Given the upcoming main chain release in March 2017 and other long-term goals, hardware wallet integration will lead to better trust and security globally.

Once TRX is no longer an ERC20 token on the Ethereum blockchain, I'm assuming this is possible.

**Comment by zealthio** [comment]
Brilliant idea. Ledger Nano S and Ledger Blue. Atm you have to go through MEW but it doesn't show up on both devices. And its a pain paying Gas to move the funds from MEW

**Comment by davendersingh76** [comment]
Yep! When you guys go to for this, definitely handle it for Trezor Too! 😎
Davender
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: zealthio <notifications@github.com> Date: 1/30/18  10:03 PM  (GMT-05:00) To: tronprotocol/java-tron <java-tron@noreply.github.com> Cc: davendersingh76 <davendersingh76@gmail.com>, Author <author@noreply.github.com> Subject: Re: [tronprotocol/java-tron] TRON wallet integration with Trezor, Nano Ledger, etc. (#90) 
Brilliant idea. Ledger Nano S and Ledger Blue. Atm you have to go through MEW but it doesn't show up on both devices. And its a pain paying Gas to move the funds from MEW

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tronprotocol/java-tron","title":"tronprotocol/java-tron","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tronprotocol/java-tron"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zealthio in #90: Brilliant idea. Ledger Nano S and Ledger Blue. Atm you have to go through MEW but it doesn't show up on both devices. And its a pain paying Gas to move the funds from MEW"}],"action":{"name":"View Issue","url":"https://github.com/tronprotocol/java-tron/issues/90#issuecomment-361809059"}}}

**Comment by xiechang33** [comment]
@davendersingh76 We have this plan.As the project progresses to increase support for the hardware wallets.

**Comment by PedritoPerro** [comment]
That is good news xiechang33. I'm all-in and need a safe place to store them...., thanks!

**Comment by davendersingh76** [comment]
Awesome! Definitely handle it for Trezor too, cos' that's what I have! hehe

**Comment by JusticeForMikeBrown** [comment]
They're on Ethereum blockchain so you can use hardware wallets now.  When their own coin launches of course hardware wallets will be supported.

**Comment by Pit-R** [comment]
Thanks @xiechang33.

Lot of us are waiting for Trezor model T.

**Comment by tradebully** [comment]
Sooner you guys integrate the hardware wallet more people will join Tron's network.

**Comment by JusticeForMikeBrown** [comment]
Hi

Please see [this link on Trezor](https://www.reddit.com/r/Tronix/comments/8z2q1l/tron_does_not_meet_trezor_quality_requirements/)

I contacted Trezor support about supporting mainnet TRX Coin.  They claim Tron developers need to contact them about getting it to work with the Trezor.  Can this be done?

**Comment by Rovak** [comment]
@fbsobreira has already contacted the Trezor team. Me and @fbsobreira are working on Trezor support right now

**Comment by JusticeForMikeBrown** [comment]
@Rovak sounds great!

**Comment by Pit-R** [comment]
When Tron on Trezor
