### ISSUE TITLE
Cannot write blocks as witness

### ISSUE THREAD

**Issue by oroblu** [tronprotocol/java-tron#903]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I'm a superdelegate (27WvBazCE39iLkX2LRvUXBCm2NPAfCLk8fK)  and i'm try to write blocks

2. What did you expect to see?

be in sync and write blocks

3. What did you see instead?
Blocks sync but i cannot write (i attach startup log)
[tron.log](https://github.com/tronprotocol/java-tron/files/2054024/tron.log)

**Comment by oroblu** [comment]
[tron_2.log](https://github.com/tronprotocol/java-tron/files/2054043/tron_2.log)
this is when block sync complete

**Comment by kaankozan** [comment]
How do it can you write

**Comment by bondibox** [comment]
It looks ok to me based on this line
`Ready to broadcast block`

**Comment by oroblu** [comment]
now it all stucked on block 63, full or witness, build, rebuild...nothing
It happen to many people right now.

**Comment by oroblu** [comment]
[tron.log](https://github.com/tronprotocol/java-tron/files/2055757/tron.log)

**Comment by oroblu** [comment]
switched to block 63 problem
