### ISSUE TITLE
[BOUNTY] Incorrect timestamps getting Transactions via gRPC

### ISSUE THREAD

**Issue by deblanco** [tronprotocol/java-tron#904]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I get a Transaction via gRPC with getTransactionById or getTransactionsFromThis for example, and the transactions received comes with an incorrect timestamp format.

2. What did you expect to see?
Unix epoch timestamp in millis

3. What did you see instead?
I'm receiving timestamps with more zeroes than normal, like: 1527700488990000000

Transactions in getBlockByNum comes in good format, I only tried it on SolidityNodes.

**Comment by deblanco** [comment]
![image](https://user-images.githubusercontent.com/343824/41989284-0bd08686-7a3f-11e8-8505-8928c70efd2e.png)

Right now happening on mainnet, look up the attachment for further details.

**Comment by kookiekrak** [comment]
So the timestamps are set by the creator of the transaction, and some people are broadcasting with timestamps with ms and some with ns accuracy.

We can't change the data because this will alter the hash of the data.

**Comment by AngelQuirogaM** [comment]
Does this means that the user can set the timestamp he wants? 

What I mean with this is that the transactions timestamps obtained from the solidty with the **GetTransactionsToThis**, **GetTransactionsFromThis** cannot be trusted for logic purposes and they could be removed if they are not showing real network information about the transactions times.

Am I wrong with this?

**Comment by kookiekrak** [comment]
Yes the user sets what they want. I believe its validated in a range before broadcast.
