### ISSUE TITLE
Last block 63 and dont contiune

### ISSUE THREAD

**Issue by kaankozan** [tronprotocol/java-tron#905]
Tonight 3x clean server again build and run full node

But not synching

Try to synching but last block 63 dont contiune 

What is problem can you help me

**Comment by iiimoon** [comment]
The same issue, I am using Odyssey-v2.0

**Comment by Ampakinetic** [comment]
Yes same here, stock on block 63

**Comment by kaankozan** [comment]
So what should I do

**Comment by deblanco** [comment]
`01:56:25.363 INFO  [pool-16-thread-1] [o.t.p.SolidityNode](SolidityNode.java:88) sync solidity block, lastSolidityBlockNum:63, remoteLastSolidityBlockNum:19202
01:56:25.383 INFO  [pool-16-thread-1] [o.t.c.w.WitnessController](WitnessController.java:207) scheduledWitness:a0149b27b39bdbb29ef2b8dae4575296f4d5ba0f96, currentSlot:509225546
01:56:25.396 ERROR [pool-16-thread-1] [o.t.c.d.Manager](Manager.java:737) balance is not sufficient.
org.tron.core.exception.ContractValidateException: balance is not sufficient.`

Running a Solidity Node

**Comment by kaankozan** [comment]
kaankozan05@tron-1:~/java-tron/build/libs$ ls
config.conf  java-tron.jar  logs  output-directory
kaankozan05@tron-1:~/java-tron/build/libs$ sudo java -jar So
lidityNode.jar -c config.conf
Error: Unable to access jarfile SolidityNode.jar
kaankozan05@tron-1:~/java-tron/build/libs$

**Comment by zhaohong** [comment]
there is bug here ,  please use the master code.

**Comment by jerkyrs** [comment]
@zhaohong i am on Odyssey-v2.01 and i am on block 63, seems like fork again, how do we avoid this, how does a node know which chain to sync, id assume it uses Seed List to initialize but that assumes Seedlist is forked itself

**Comment by 2tvenom** [comment]
same on `Odyssey-v2.0.1`

**Comment by zhaohong** [comment]
@jerkyrs   the testnet has bug and produce wrong block,  Odyssey-v2.0 fix it  and Odyssey-v2.0 can not sync the block on testnet.

**Comment by oroblu** [comment]
how to change from testnet to mainnet or viceversa?
Which parmater we need to change in config file?

**Comment by jerkyrs** [comment]
@zhaohong is there plan to upgrade testnet to 2.0.1? Would make sense to have testnet ahead of mainnet :)

@oroblu im assuming it is config.conf but it would also make sense that in changing it from type = testnet to type = mainnet that they would also need to change the ip.list which is used to seed the network to give your node information how to join. Just changing the type alone is not sufficient.

**Comment by kaankozan** [comment]
Fix it problems#915
