### ISSUE TITLE
Question: Would a dotnet implementation be of interest?

### ISSUE THREAD

**Issue by rickythefox** [tronprotocol/java-tron#91]
I'm thinking of porting the code to .net core. Would such a port be of interest?

**Comment by xiechang33** [comment]
I think .NET can do it well.Thanks for your attention.

**Comment by Rovak** [comment]
Someone in the Gitter channel made a start at https://github.com/net-tron/net-tron

**Comment by rickythefox** [comment]
Argh, already been done then.

**Comment by Rovak** [comment]
@rickythefox looking at the dotnet code it is mostly a copy paste of the java version right now https://github.com/net-tron/net-tron/blob/master/src/NetTron/Datasource/AbstractCachedSource.cs

I doubt the project can be compiled in its current state. There hasn't been activity for 17 days. I think you give it a try and implement your own dotnet version.

**Comment by codedevmk** [comment]
@rickythefox, I'm game if you want to collab. DotNetCore with Kestrel?

**Comment by dandcg** [comment]
Hi, I started a netcore tron implementation before Xmas but the product was to immature at that point. I'd been keen on collaboration if anybody is interested.

**Comment by shanadas** [comment]
Has this dotnet implementation started? I would like to contribute.

**Comment by rickythefox** [comment]
Got a few rl commitments to take care of, so I won't be able to lead this. Would love to contribute a bit though.

**Comment by dariogriffo** [comment]
I have started something, you can check the progress [here](https://github.com/griffo-io/tron.net)
My intention is not to create a Wallet but to provide a .NET environment for TRON, ie: GRPC calls, Wallet abstraction, signature and EC KEy management, but without store.
