### ISSUE TITLE
Suggestion : Server.java

### ISSUE THREAD

**Issue by jingyi2811** [tronprotocol/java-tron#92]
Below is the snippet of Server.java, starting from line 39.

 ```
 @Override
  public void start() {
    InetAddress localhost = null;
    try {
      localhost = InetAddress.getLocalHost();
      System.out.println("Server localhost: " + localhost.getHostAddress());
      Address address = new Address(localhost.getHostAddress(), 5000);
```

It should be replaced with

 ```
 @Override
  public void start() {
    try {
      String hostAddressStr = InetAddress.getLocalHost().getHostAddress();
      System.out.println("Server localhost: " + hostAddressStr);
      Address address = new Address(hostAddressStr, 5000);
```
1) localhost variable is not used outside the try-catch
2) localhost is not reused, localhost.getHostAddress is called twice, that is why we should declare a variable for InetAddress.getLocalHost().getHostAddress(); but not InetAddress.getLocalHost().

The Exception handled is for UnknownHostException. I think it should be replaced by Exception. It is possible to have NullPointerException as well.

**Comment by zhaohong** [comment]
Thanks @jingyi2811 @Rovak 
we'll  re-design the consensus module and  these codes  will be discarded
