### ISSUE TITLE
testnet version

### ISSUE THREAD

**Issue by iiimoon** [tronprotocol/java-tron#921]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Running the Odyssey-v2.0 

2. What did you expect to see?

I expect it connect to testnet at https://tronscan.org

3. What did you see instead?

I don;t find my IP listed in nodes

How to find out version running on https://tronscan.org  ?  Is there any mainnet live running with test data ?

**Comment by ithinker1991** [comment]
@iiimoon  you can change your config.conf and try again

net {
  type = mainnet
  # type = testnet
}

p2p {
    version = 10000 # 10000: mainnet; 71: testnet
  }

**Comment by iiimoon** [comment]
Thanks !  I tried it but it's giving an error , can you share any working config.conf .

Here is the error 

Exception in thread "main" java.lang.IllegalArgumentException: The address(null) must be a 21 bytes.
	at org.tron.core.config.args.Account.setAddress(Account.java:51)
	at org.tron.core.config.args.Args.createAccount(Args.java:411)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.tron.core.config.args.Args.getAccountsFromConfig(Args.java:404)
	at org.tron.core.config.args.Args.setParam(Args.java:301)
	at org.tron.program.FullNode.main(FullNode.java:22)

so I think address in genesis.block assets should change to mainnet address ( prefix 65 ?? )

**Comment by ithinker1991** [comment]
On branch master, the newest config.conf 
```
net {
  type = mainnet
  # type = testnet
}

storage {
  # Directory for storing persistent data

  db.directory = "database",
  index.directory = "index",

  # You can custom these 14 databases' configs:

  # account, account-index, asset-issue, block, block-index,
  # block_KDB, peers, properties, recent-block, trans,
  # utxo, votes, witness, witness_schedule.

  # Otherwise, db configs will remain defualt and data will be stored in
  # the path of "output-directory" or which is set by "-d" ("--output-directory").

  # Attention: name is a required field that must be set !!!
  properties = [
//    {
//      name = "account",
//      path = "storage_directory_test",
//      createIfMissing = true,
//      paranoidChecks = true,
//      verifyChecksums = true,
//      compressionType = 0,
//      blockSize = 10485760,
//      writeBufferSize = 10485760,
//      cacheSize = 0,
//      maxOpenFiles = 32
//    },
//    {
//      name = "account-index",
//      path = "storage_directory_test",
//      createIfMissing = true,
//      paranoidChecks = true,
//      verifyChecksums = true,
//      compressionType = 0,
//      blockSize = 10485760,
//      writeBufferSize = 10485760,
//      cacheSize = 0,
//      maxOpenFiles = 32
//    }
  ]

}

node.discovery = {
  enable = true
  persist = true
  bind.ip = ""
  external.ip = null
}

node {
  # trust node for solidity node
  # trustNode = "ip:port"
  trustNode = "127.0.0.1:50051"

  # expose extension api to public or not
  walletExtensionApi = true

  listen.port = 18888
  rpc.port = 50051

  # Number of gRPC thread, default availableProcessors / 2
  # rpc.thread = 16

  connection.timeout = 2

  tcpNettyWorkThreadNum = 0

  udpNettyWorkThreadNum = 1

  # Number of validate sign thread, default availableProcessors / 2
  # validateSignThreadNum = 16

  active = [
    # Initial active peers
    # Sample entries:
    # "ip:port",
    # "ip:port"
  ]

  maxActiveNodes = 30

  minParticipationRate = 33

  p2p {
    version = 10000 # 10000: mainnet; 71: testnet
  }

}

seed.node = {
  # List of the seed nodes
  # Seed nodes are stable full nodes
  # example:
  # ip.list = [
  #   "ip:port",
  #   "ip:port"
  # ]
  ip.list = [
    "47.254.16.55:18888",
    "47.254.18.49:18888",
    "18.188.111.53:18888",
    "54.219.41.56:18888",
    "35.169.113.187:18888",
    "34.214.241.188:18888",
    "47.254.146.147:18888",
    "47.254.144.25:18888",
    "47.91.246.252:18888",
    "47.91.216.69:18888",
    "39.106.220.120:18888"
  ]
}

genesis.block = {
  # Reserve balance
  assets = [
    {
      accountName = "Zion"
      accountType = "AssetIssue"
      address = "TNNqZuYhMfQvooC4kJwTsMJEQVU3vWGa5u"
      balance = "95000000000000000"
    },
    {
      accountName = "Sun"
      accountType = "AssetIssue"
      address = "TWsm8HtU2A5eEzoT8ev8yaoFjHsXLLrckb"
      balance = "5000000000000000"
    },
    {
      accountName = "Blackhole"
      accountType = "AssetIssue"
      address = "TSJD5rdu6wZXP7F2m3a3tn8Co3JcMjtBip"
      balance = "-9223372036854775808"
    }
  ]

  witnesses = [
    {
      address: TVdyt1s88BdiCjKt6K2YuoSmpWScZYK1QF,
      url = "http://Alioth.com",
      voteCount = 100027
    },
    {
      address: TCNVmGtkfknHpKSZXepZDXRowHF7kosxcv,
      url = "http://Aries.com",
      voteCount = 100026
    },
    {
      address: TAbzgkG8p3yF5aywKVgq9AaAu6hvF2JrVC,
      url = "http://Cancer.com",
      voteCount = 100025
    },
    {
      address: TMmmvwvkBPBv3Gkw9cGKbZ8PLznYkTu3ep,
      url = "http://Capricorn.com",
      voteCount = 100024
    },
    {
      address: TBJHZu4Sm86aWHtt6VF6KQSzot8vKTuTKx,
      url = "http://Cassiopeia.com",
      voteCount = 100023
    },
    {
      address: TLvCstA93piBhpdvMggJ9r5b793b6rqdGd,
      url = "http://Crux.com",
      voteCount = 100022
    },
    {
      address: TEf2ADumcubtg9NeNi7bNP14KfvYxKzTDu,
      url = "http://Delphinus.com",
      voteCount = 100021
    },
    {
      address: TTqqbNxnqniyeCFi4aYwQQFHtuMwiBLARo,
      url = "http://Dorado.com",
      voteCount = 100020
    },
    {
      address: TWwJwoqAYvUVjmp5odhwZYgKekBqL3Mbcf,
      url = "http://Dubhe.com",
      voteCount = 100019
    },
    {
      address: TCPKsDZCJDzC83KWcAnHo9b46DN9o4s48y,
      url = "http://Eridanus.com",
      voteCount = 100018
    },
    {
      address: TJnd8wF5ScEvuYq4WnJUyGbg6iS7ibnWrY,
      url = "http://Gemini.com",
      voteCount = 100017
    },
    {
      address: TTZDB64rNpdw8rpEKko5FhB7BMUf5y4JMT,
      url = "http://Hercules.com",
      voteCount = 100016
    },
    {
      address: TVWapNccbdFDqdHjFGnJ8ePancR6HjSned,
      url = "http://Leo.com",
      voteCount = 100015
    },
    {
      address: TUVdiR6bYsuDNB5HWPLyK3ueY6225n5AdJ,
      url = "http://Libra.com",
      voteCount = 100014
    },
    {
      address: TRBQFNJrJJzzgqfnbP9WvAjWd2oCNyqanC,
      url = "http://Lupus.com",
      voteCount = 100013
    },
    {
      address: TBSq7zAhyEyVf96tbQmh6SwBGRiQXJf9sx,
      url = "http://Lyra.com",
      voteCount = 100012
    },
    {
      address: TFZhwKPxqadgLGSwkiD1JeFJgfSMn2BD75,
      url = "http://Monoceros.com",
      voteCount = 100011
    },
    {
      address: TZ6PqKSodEW7yQNYSDS8WoDo8t3SfACV3V,
      url = "http://Norma.com",
      voteCount = 100010
    },
    {
      address: TSiyqwmcqsDBXQmWPZhC4Y5zncECMN61Li,
      url = "http://Orion.com",
      voteCount = 100009
    },
    {
      address: TVnWr8bm3b2gDrJDBTfWXuPXiT1cvZUGan,
      url = "http://Pavo.com",
      voteCount = 100008
    },
    {
      address: TNR2BDkX53rFCvkSg89nK7nfeC6hLN7B5o,
      url = "http://Perseus.com",
      voteCount = 100007
    },
    {
      address: TVw2k1pD3n4ErWnr4uWmjVwsdai8vT5wyn,
      url = "http://Phecda.com",
      voteCount = 100006
    },
    {
      address: THtcGdFXoGWNd9PDrhCradfvcdsQAoNVAC,
      url = "http://Phoenix.com",
      voteCount = 100005
    },
    {
      address: TEZ31xxrECtLmsGvQFnh2quQVxKFoHxqqu,
      url = "http://Pyxis.com",
      voteCount = 100004
    },
    {
      address: TA6ztifHZSkQ5F6KMe73rYRgQ5fBKLPomV,
      url = "http://Scutum.com",
      voteCount = 100003
    },
    {
      address: TXuLKjf8J8aCKgDgA5uczwn1yQNYVPLocY,
      url = "http://Taurus.com",
      voteCount = 100002
    },
    {
      address: TAihbgDWBK1QTS5gsk7evWDy2nhpkmkGZJ,
      url = "http://Volans.com",
      voteCount = 100001
    }
  ]

  timestamp = "0" #2017-8-26 12:00:00

  parentHash = "0x0000000000000000000000000000000000000000000000000000000000000000"
}

localwitness = [

]

block = {
  needSyncCheck = true # first node : false, other : true
  maintenanceTimeInterval = 21600000 // 1 day: 86400000(ms), 6 hours: 21600000(ms)
}
```

**Comment by iiimoon** [comment]
Thanks.

I think we should display the https://tronscan.org   testnet/mainnet versions under tools -> system menu. It is not possible to find out public testnet version unless you are part of core development team or may be it is shared on slack. 

Also it would be great if you can send me slack link ( the one in readme is not working ).

**Comment by iiimoon** [comment]
After using config file from master branch, the node is not coming up, I am using 2.0 

Error in log



pplicationContext.java:544) Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rpcApiService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.NodeManager org.tron.core.services.RpcApiService.nodeManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/root/java-tron-live/java-tron.jar!/org/tron/common/overlay/discover/NodeManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.common.overlay.discover.NodeManager]: Constructor threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBe
