### ISSUE TITLE
How to use this coin in my exchange platfrom?

### ISSUE THREAD

**Issue by thomsonimjd** [tronprotocol/java-tron#923]
I have been devloping an crypto exchange and trading platfrom where I have used 10 coins as of now, I would like to add this coin too? I want following functionalties to be automated in my impl. create new account/address, get balance, transfer balance, import/export privatekey. How to run this tether coin and achieve those functionalties? Please let me know if there is any testnet faucet for this coin?

Thanks in advance.

**Comment by zhaohong** [comment]
https://tronscan.org/  the testnet

**Comment by LeetJoe** [comment]
@zhaohong well then how to get test bonus? the balance is always 0.
It is testnet, really? How to check it is testnet or mainnet?
I am always confused.

**Comment by 2tvenom** [comment]
same question. tronscan is testnet? it seems like mainnet

**Comment by thomsonimjd** [comment]
@LeetJoe please let me know any documentation to run TRON node and its json rpc method api call list?

**Comment by Crypto2** [comment]
I've been looking for docs as well, doesn't seem there are any good docs or tutorials out yet.

**Comment by songky** [comment]
Hey guys, do you have any ideas? I tried as [the document](https://github.com/tronprotocol/Documentation/blob/master/TRX_CN/Tron-exchange.md) said, useless.

**Comment by Crypto2** [comment]
Yeah, I've never seen a coin like this where it's just insane to try to figure anything about basic usage.

**Comment by Rovak** [comment]
Documentation on how to integrate Tron with an exchange have been published at https://tron.network/exchangesList?lng=en. 

Feel free to reopen this issue if there are any questions
