### ISSUE TITLE
Compile error on the latest code in develop branch

### ISSUE THREAD

**Issue by gp12** [tronprotocol/java-tron#93]
1. What did you do?
I just synced and tried to build the project. 

2. What did you expect to see?
'BUILD SUCCESSFUL'

3. What did you see instead?
Bulild failed, here is the 1st compile error
_xxxxx/java-tron/src/main/java/org/tron/core/db/BlockStore.java:26: error: cannot find symbol
public class BlockStore extends **Database** {_

Commit 'Merge pull request #88 from ruchern/develop' is the latest good build

Please help to fix the compile error. Thanks!

**Comment by styk-tv** [comment]
@zhaohong trigger happy.  BIg 'X' means do not merge because it does not compile.

https://github.com/tronprotocol/java-tron/pull/89

**Comment by styk-tv** [comment]
@zhaohong its weird as build is failing on 

```
$ ./gradlew assemble
/home/travis/.travis/job_stages: line 236: ./gradlew: Permission denied
The command "eval ./gradlew assemble " failed. Retrying, 2 of 3.
```

right here: https://travis-ci.org/tronprotocol/java-tron/builds/335648446#L439

can you check is this as simple as doing `chmod +x gradlew` ? maybe got removed somehow @sasaxie  @ruchern maybe you can double check?

**Comment by ruchern** [comment]
A failed pull request was merged. And it’s a huge one. I think there are a total of 120+ files in that PR.

**Comment by styk-tv** [comment]
@ruchen but if you take a look at error i pasted above, its gradle permission, maybe +x got removed, i'm on mobile would you mind trying a different branch? i don't have contributor access so i can't try another branch without forking and setting up CI of my own

**Comment by ruchern** [comment]
@styk-tv I've started a PR to fix the permission issue.

**Comment by styk-tv** [comment]
@ruchern you rule man

<img width="277" alt="screen shot 2018-01-31 at 18 25 05" src="https://user-images.githubusercontent.com/838921/35640123-2d3410bc-06b4-11e8-90b5-d054ae8e0169.png">

<img width="703" alt="screen shot 2018-01-31 at 18 25 25" src="https://user-images.githubusercontent.com/838921/35640135-37a5360c-06b4-11e8-9098-513d23dfbf76.png">

**Comment by ruchern** [comment]
Thanks @styk-tv it's just a `a+x` to set executable permission to all.

**Comment by gp12** [comment]
Just synced latest and everything builds fine now. Thanks!
I'm closing the issue.
