### ISSUE TITLE
Question: is it possible to load balance a witness node?

### ISSUE THREAD

**Issue by oroblu** [tronprotocol/java-tron#936]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Looking for a way to provide load balancing  to a witness node.

2. What did you expect to see?
Find a method to distribuite load of a single witness node among different server

3. What did you see instead?
It's a question

**Comment by oroblu** [comment]
Let say there isn't any native way to load balance and for HA a background third part hardware or software replication is needed. 
Right?

**Comment by zhaohong** [comment]
fullnode can charge for the load balance and sr node behind the fullnode.

**Comment by oroblu** [comment]
ok thanks
