### ISSUE TITLE
Suggestion : Client.java

### ISSUE THREAD

**Issue by jingyi2811** [tronprotocol/java-tron#94]
Syntax (line 127, trunk)

`if (!(pretime == null)){{`

should be replaced by

`  if (pretime != null){`

Also, the code of client.java needs to be improved.

**Comment by Rovak** [comment]
Every suggestion is appreciated but making an issue for very minor changes which only alters a line to a different code style is not gonna help development in this stage. It also creates extra work for the team which has to handle more issues.

I'd suggest making a Pull Request or tracking down the commit in which the line was pushed, see https://github.com/tronprotocol/java-tron/commit/b353b63c4a35da2485be76d27eefd69927bd6763#diff-83543a2b061e68c274e8f2c5cf59757aR127

**Comment by shufps** [comment]
IMHO there is no difference in functionality between the two versions but semantics to understand what the code is doing can be different. I often do such constructs only to make it better understandable ... Nothing wrong about. And complaining about so small issues and using for each mini-thingy the bug-tracker makes the programmer-skill-level of jingyi2811 very questionable.

**Comment by jingyi2811** [comment]
programmer-skill-level of jingyi2811 very questionable. How do you know?

So far cannot complain the big picture as time needed to read everything.

Blockchain needs speed.

1）if (!(pretime == null)) ->  Checking pretime == null then check again with ！
2)  pretime != null -> run 1 time enough.

**Comment by jingyi2811** [comment]
Like Client.java
Line 195.

  preMessage[0] = preMessage[0];

What is this？
A=A？　Why this is written?

**Comment by shufps** [comment]
> 1）if (!(pretime == null)) -> Checking pretime == null then check again with ！
> 2) pretime != null -> run 1 time enough.

That won't change anything on the outcome of the java compiler ... 

> preMessage[0] = preMessage[0];

That's certainly not a bug ... It's like documentary and it will not cause performance problems because it is optimized out by the compiler.

All the things mentioned by you don't have any impact on performance because the compiler is smart enough to see how it is best execuded and how boolean terms are reduced.

**Comment by jingyi2811** [comment]
Are you sure or not? Don't have any impact on performance Write A=a; for 1000 times is okay?

Assume you are correct, If you write A = A; 

1)The compiler still needs to check the line of code. 
2) And match with another A.
3) Then decide the line to be ignored.

Memory used. (Like human you use brain power to see the line, even your brain power used is very little)

This is public blockchain code, we write the code to be used by billions.

After all, we are helping to make the code better.

**Comment by shufps** [comment]
> 1)The compiler still needs to check the line of code.
> 2) And match with another A.
> 3) Then decide the line to be ignored.

Yes, the *compiler* ... But after it's compiled (which only have to be done once) all the statements without any effect will be gone.

It doesn't matter if the compiler has a tiny bit more work to do because the result of the compiler will be used for executing.

If I had time, I would compile and disassemble (in Java-VM-Mnemonics) a small sample illustrating this, this discussion is not worth doing it.

**Comment by jingyi2811** [comment]
I am a perfectionist.  :)

**Comment by shufps** [comment]
> I am a perfectionist. :)

Perhaps, but perfectionism often stands in someone's way ... There are some videos about this topic ... Look on youtube for "finished not perfect" :)

**Comment by Rovak** [comment]
Lets not derail this issue in questioning each other skill levels. I agree with @jingyi2811, i'm a perfectionist myself and i would modify it if i encounter such code following the [Boy Scout Rule](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule) even though it is only a code style change.

Clean code should be encouraged. But i also agree with @shufps that the focus is now on pushing working code and new features instead on trivial things.

**Comment by jingyi2811** [comment]
If you read client.java again,  they use the array with size 1. The programmer should non-array data type again here.

**Comment by jingyi2811** [comment]
Why not like this let me post this to StackOverflow? See what other people say?

**Comment by shufps** [comment]
You may, but that's not a bug and a bug tracker is primarly for bugs. 

The correct way would be to fork the code base, do your changes and submit a pull request.

**Comment by jingyi2811** [comment]
Okay.

**Comment by zhaohong** [comment]
hi guys, We have re-designed this module  and not pushed the new codes here. 
If you run FullNode,  you can see that these code are not reached.
