### ISSUE TITLE
How to sign transaction from offline node and broadcast to online node?

### ISSUE THREAD

**Issue by JokerCatz** [tronprotocol/java-tron#958]
How to sign transaction from offline node and broadcast to online node?

If I install `tron-java` to 2 vm , run it as offline main chain & online main chain , then I use `grpc-gateway` as JSON-RPC proxy , then I read like this

http://wiki.tron.network/en/latest/Account_Management.html#transition-manual-for-exchanges-and-trx

I can generate the private key from random hex & convert it to public key by myself , then what is next ? it like ETH has from wallet / to wallet / amount right ? did it need gas / gas price (miner fee) ? or did you can show me how to self sign transaction process ? please help , many thanx : )

=====

如何自签？类似在离线的节点上签好後在连线的节点上进行广播？

如果我安装了 `tron-java` 在两台机器上，一台离线的主链，一台连线的主链，之後我安装好`grpc-gateway`做为 JSON-RPC 中继，然後我阅读了这个

http://wiki.tron.network/en/latest/Account_Management.html#transition-manual-for-exchanges-and-trx

我已经可以产生随机 hex 作为私钥并转换成公钥，但是之後该怎麽做呢？他像是 ETH 有 from wallet / to wallet / amount 这三个栏位对吧？然而它需要 gas / gas price (矿工费用)吗？或是你可以弄个自签的范例或是流程给我看吗？烦请帮忙，非常感谢 :)

您可以用中文进行回覆，非常感恩

**Comment by fbsobreira** [comment]
@JokerCatz you need bandwidth to broadcast the transaction. Dally a user has free 5000 for bandwidth, and more can be acquired if you freeze TRX. Those represent the number of bytes in the message.

About the documentation you pointed, I think that there is a mistake. For main net you should add 41, not b0. 

To self-sign the transaction, here is an example you can follow at https://github.com/tronprotocol/wallet-cli/blob/d4030d4e328182b72d640b9f95bc6a5ee443fde2/src/main/java/org/tron/walletserver/WalletClient.java#L294

hope this can help you

**Comment by zk19862018** [comment]
+
