### ISSUE TITLE
SolidityNode didn't synchronize Block when  create several witness

### ISSUE THREAD

**Issue by wangzichichi** [tronprotocol/java-tron#959]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
------On beat env, there are five witness, I create several witness by money(use 9999 TRX to create a witness)

2. What did you expect to see?
No matter how many witness I created, the solidityNode can synchronize the block from fullnode normally.

3. What did you see instead?
When the fullnode has produce more then 10000 block ,the solidityNode block number I query is 1943.

**Comment by wangzichichi** [comment]
This issue is solving by taigohu.

**Comment by taihaofu** [comment]
We got 5 witness node on our BETA envrionment. When we run the test cases, we create 3 new witness nodes dynamically, which lead the consensus for the solidityNode  smaller than 2/3(>5/8). In this case, solidity node can't sync with new produced block from any node on our BETA environment. This should be a normal case, not a bug. You can also find when the new witness number is 2. This situation can't be reproduced, which is  a proven to this judgement.

Thanks.
