### ISSUE TITLE
[BOUNTY] CENTOS 7 Builds Fail to Run bug?

### ISSUE THREAD

**Issue by dbriggsie** [tronprotocol/java-tron#967]
Please answer these questions before submitting your issue. Thanks!

**1. What did you do?
If possible, provide a recipe for reproducing the error.**
I have tried to build on 3 different CENTOS 7 Machines. 1 small, 1 medium & 1 large cpu.
Not one of them has executed after build... by running
`./gradlew run`

**2. What did you expect to see?**
I expected to see the node run. 

**3. What did you see instead?**

> Task :generateProto UP-TO-DATE
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be
removed in Gradle 5.0. Use TaskInputs.files() instead.
<===========--> 85% EXECUTING [11m 50s]
<===========--> 85% EXECUTING [56m 47s]
> :run

**Comment by dbriggsie** [comment]
Forgot to add, the `./gradlew build` is successful on all machines running CENTOS 7. 
Just never executing using `./gradle run`

**Comment by fbsobreira** [comment]
@dbriggsie check the log at logs/tron.log, there is no output on terminal.

**Comment by dbriggsie** [comment]
Closed, I managed to rebuild on CENTOS 7 not problems

**Comment by jerkyrs** [comment]
You probably don't want to run the process under gradel, you are better of running it direct

```
nohup  java -Xms256m -Xmx4096m -jar /home/tron/java-tron/build/libs/java-tron.jar -p $LOCAL_WITNESS_PRIVATE_KEY --witness -c /home/tron/config.conf > /home/tron/tron-shell.log 2>&1 & echo $! >/home/tron/pid.txt
```

Something like this or better yet Supervisor or systemd managed process
