### ISSUE TITLE
How to deploy Solidity smart contract in tron

### ISSUE THREAD

**Issue by sevvandhiNagulan** [tronprotocol/java-tron#973]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I try to deploy solidity smart contract in tron by using this link "https://medium.com/@Tronfoundation/official-debut-of-tron-virtual-machine-195680959fac". I cannot able to Deploy. So please provide How to deploy solidity smart contract in tron.

2. What did you expect to see?
Please provide some information about How to deploy solidity smart contract in tron.

3. What did you see instead?

**Comment by kookiekrak** [comment]
@sevvandhiNagulan please email me at tian@tron.network for a developer slack invite. we've released our vm on our test network so you can deploy contracts now
