### ISSUE TITLE
Build is breaking

### ISSUE THREAD

**Issue by Ampakinetic** [tronprotocol/java-tron#987]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
git pull, ./gradlew build

2. What did you expect to see?
A successful build

3. What did you see instead?
/home/soa/java-tron/src/test/java/stest/tron/wallet/common/client/WalletClient.java:383: error: cannot find symbol
    public boolean createAssetIssue(AssetIssueContract contract) {
                                    ^
  symbol:   class AssetIssueContract
  location: class WalletClient
/home/soa/java-tron/src/test/java/stest/tron/wallet/common/client/WalletClient.java:414: error: cannot find symbol
    public static Transaction createAssetIssueTransaction(AssetIssueContract contract) {
                                                          ^
  symbol:   class AssetIssueContract
  location: class WalletClient

**Comment by taihaofu** [comment]
Please try master again.

Thanks.

**Comment by Ampakinetic** [comment]
Build is successful now, thanks :)
